os-autoinst/os-autoinst-distri-opensuse

- data/virt_autotest/virt_logs_collector.sh
**1**.This s:cript supports some given options:
* -f virt_logs_folder: Folder on host as logs destination residence which will contain all logs from host and guest at the last. By the way, logs collected inside guest will also be put into this folder inside guest
* -l virt_extra_logs_host: Please specify if any extra logs on host are wanted
* -g virt_guests_wanted: Sometimes not all guests on host are concerned. If this option is not empty, only guests specified by this option are involved in this script
* -e virt_extra_logs_guest: Please specify if any extra logs in guest are wanted
**2**.Firstly collect supportconfig from both host and guest via ssh, function collect_supportconfig
**3**.If ssh connection to guest is broken, switching to guest virsh console to collect supportconfig, …
> [Log Enhancement] Gather logs from both host and guest

- data/virt_autotest/fetch_logs_from_guest.sh
**1**.This script supports some given options: 
* -f virt_logs_folder: Folder on host as logs destination residence which contain all logs from host and guest at the last
* -g virt_guests_wanted: If not all guests on host are involved, you can specify those you are interested
* -e virt_extra_logs_guest: Under extreme circumstances, logs inside virtual machine can only be fetched by using libguestfs tools. You can specify those you wanted
* -h help message
**2**.Fetching logs from guest starts from through ssh, function fetch_logs_from_guest -> function fetch_logs_from_guest_via_ssh
**3**.If ssh connection to guest is broken, switching to use libguestfs tools to fetching logs directly from guest images, function fetch_logs_from_guest_via_libguestfs
**4**.Under extreme circumstances, some …
> [Log Enhancement] Fetch and compress logs from virtual machine

- data/filesystem/autoyast_filesystem.xml
- data/filesystem/autoyast_filesystem_ext4_btrfs.xml
Add autoyast xml config file for OS installation for xfstest and btrfs-progs
autoyast_filesystem.xml for xfstests
autoyast_filesystem_ext4_btrfs.xml for btrfs-progs test
- Related ticket: https://progress.opensuse.org/issues/68062
http://10.67.133.10/tests/123
http://10.67.133.10/tests/135
> Add autoyast xml config file for OS installation for xfstest

- tests/publiccloud/register_system.pm
SCC failures are pretty common, try retry the action and believe
- Fail: https://openqa.suse.de/tests/4550929
- Verification run: https://openqa.suse.de/tests/4551139
> publiccloud: retry 3 times on SCC registration

- tests/cpu_bugs/xen_domu_mitigation_test.pm
Add sshpass package
- Needles: N/A
- Verification run: http://10.67.134.217/tests/11199, http://10.67.134.217/tests/11312
> Add sshpass package

- tests/xfstests/partition.pm
If configure XFSTESTS_LOOP_DEVICE in openQA, test will create loop device in root partition. And complete xfstest with those loop devices. This could run in qcow2 without /home device. But better have no less than 80GB when run in openqa(configure with HDDSIZEGB=80 or higher).
- Related ticket: https://progress.opensuse.org/issues/69247
Test without configure XFSTESTS_LOOP_DEVICE - http://openqa.suse.de/tests/4489969
Test with configure XFSTESTS_LOOP_DEVICE
xfs - http://openqa.suse.de/tests/4489980
btrfs - http://openqa.suse.de/tests/4490049
ext4 - http://openqa.suse.de/tests/4490050
> xfstests: Support test in loop device

- tests/cpu_bugs/xen_domu_mitigation_test.pm
Add qa repo as packages source
- Needles: N/A
- Verification run: http://10.67.134.217/tests/11368
> Add qa repo as packages source

- tests/console/shar.pm
Ticket: https://progress.opensuse.org/issues/69397
Verification: https://openqa.opensuse.org/t1360786
> Install diffutils on jeos for shar test

- tests/systemd_testsuite/binary_tests.pm
- tests/systemd_testsuite/prepare_systemd_and_testsuite.pm
- Failed run: https://openqa.opensuse.org/tests/1360504
- Verification run: http://emerson.suse.de/tests/2371
> systemd: set milestone after testsuite preparation

- lib/Mitigation.pm
Fix ssh connect issue due to ssh host key checking
- Needles: N/A
- Verification run:http://10.67.134.217/tests/11370
> Fix ssh host key checkcing causing issue

- schedule/virtualization/vmware_hyperv.yaml
- tests/virtualization/xen/open_vm_tools.pm
Simple vmware client testing with updated open-vm-tools
https://progress.opensuse.org/issues/52139
- Related ticket: https://progress.opensuse.org/issues/52139
- Verification run: http://10.161.229.249/tests/525
> Add open-vm-tools test

- tests/network/autofs_client.pm
- Related ticket: https://progress.opensuse.org/issues/67234
- Verification run: https://openqa.suse.de/tests/4565885#step/autofs_client/40
> Extract command from var test_conf_file_content

- lib/rstudio.pm
- Needles: https://github.com/os-autoinst/os-autoinst-needles-opensuse/pull/676
- Verification run: ~~https://openqa.opensuse.org/t1348915~~ https://openqa.opensuse.org/tests/1348916
> Rstudio 1 3 fixes

- schedule/qam/12-SP2/qam-minimal.yaml
- schedule/qam/12-SP3/qam-minimal.yaml
- schedule/qam/12-SP4/qam-minimal.yaml
- schedule/qam/12-SP5/qam-minimal.yaml
- schedule/qam/15-SP1/qam-minimal.yaml
- schedule/qam/15-SP2/qam-minimal.yaml
- schedule/qam/15/qam-minimal.yaml
qam-minimal: enable s390tools test
- Related ticket: https://progress.opensuse.org/issues/53012
15-SP2:
https://openqa.suse.de/t4546622
15-SP1:
https://openqa.suse.de/t4546572
15:
https://openqa.suse.de/t4546900
12-SP5:
https://openqa.suse.de/t4546623
12-SP4:
https://openqa.suse.de/t4546697
12-SP3:
https://openqa.suse.de/t4546698
12-SP2:
https://openqa.suse.de/t4546699
> qam-minimal: enable s390tools test

- tests/console/shar.pm
Ticket: https://progress.opensuse.org/issues/70126
Verification: https://openqa.suse.de/tests/4563365
Ticket: https://progress.opensuse.org/issues/69397
Verification on JeOS: https://openqa.opensuse.org/t1363719
Verification on RPi: `openqa-clone-custom-git-refspec https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/10830 https://openqa.opensuse.org/tests/1363714` https://openqa.opensuse.org/t1365222
> Install sharutils on sle and diffutils on RPi

- lib/x11utils.pm
- Related ticket: https://bugzilla.opensuse.org/show_bug.cgi?id=1169203
- Needles: https://github.com/os-autoinst/os-autoinst-needles-opensuse/pull/678
- Verification run: http://openqa.slindomansilla-vm.qa.suse.de/tests/2637#step/opensuse_welcome/1
> Fix bug number of broken opensuse-welcome

- schedule/yast/nvme.yaml
- test_data/yast/nvme.yaml
- tests/console/nvme_checks.pm
Reuse validate_fs_table to validate partitioning and                                                                                                                                                                                                                           
add a new module to perform smoke tests on the NVM Controller.                                                                                                                                                                                                                 
This patch checks basics files and paths in the system, validate the …
> Add smoke tests for NVM express

- schedule/yast/textmode/textmode.yaml
- schedule/yast/textmode/textmode@ppc64le_hmc_spvm.yaml
- schedule/yast/textmode/textmode@svirt-xen.yaml
- Related ticket: https://progress.opensuse.org/issues/69574
- Verification run: https://openqa.suse.de/tests/overview?build=b10n1k%2Fos-autoinst-distri-opensuse%2310824&version=15-SP3&distri=sle
> Add scheduler for textmode

- lib/klp.pm
In light of the recent module signkey rotation, implement a new check that
livepatch kernel modules have been signed with a key on the target kernel's
trust keyring.
- Related ticket: None.
- Needles: Current HEAD, unmodified.
- Verification run: Local, not publicly accessible.
> Check that livepatches' kernel module signatures are valid

- tests/hpc/mpi_master.pm
MVAPICH2: segfault while executing without ib_uverbs loaded
https://bugzilla.suse.com/show_bug.cgi?id=1144000
blocked maintenance update e.g. https://openqa.suse.de/tests/4560315#step/mpi_master/61
- Verification run: https://openqa.suse.de/tests/4569506
> Record soft failure on bsc#1144000 HPC segfault

- lib/Mitigation.pm
- tests/cpu_bugs/xen_domu_mitigation_test.pm
Update test cases content
- Needles: N/A
- Verification run: http://10.67.134.217/tests/11382
> Update test cases content

- lib/main_common.pm
- Needles: n/a
- Verification run: not required
> Fix a typo in lib/main_common.pm

- lib/utils.pm
Ticket: https://progress.opensuse.org/issues/70132
Verification: http://kazhua.qa.suse.de/tests/74#step/machinery/38
> Include related zypper logs in fail msg for error 104

- tests/rt/rt_chrt.pm
- Verification run: [slert15sp2](http://kepler.suse.cz/tests/1293)
> chrt update priority test

- data/autoyast_qam/12_installation.xml.ep
- data/autoyast_qam/15_installation.xml.ep
- Fail: https://openqa.suse.de/tests/4608966
- Verification run: https://openqa.suse.de/tests/4609004
> Fix DESKTOP=textmode in autoyast profile

- schedule/qam/QR/15-SP2/btrfs_sle_libstorage-ng.yaml
- schedule/qam/QR/15-SP2/zfcp.yaml
A small adjustment was needed for zfcp.yaml.
- Related ticket: https://progress.opensuse.org/issues/64442
https://openqa.suse.de/tests/4599517
https://openqa.suse.de/tests/4599519
https://openqa.suse.de/tests/4599838
> add qam/QR/15-SP2 schedules

- lib/rstudio.pm
- tests/x11/rstudio_desktop.pm
- tests/x11/rstudio_prepare.pm
- tests/x11/rstudio_server.pm
- Needles: https://github.com/os-autoinst/os-autoinst-needles-opensuse/pull/682
- Verification run: https://openqa.opensuse.org/tests/1374453
> Extend rstudio tests

- tests/console/sysstat.pm
Ticket: https://progress.opensuse.org/issues/70534
Verification: http://kazhua.qa.suse.de/tests/80
> Verify old sysstat sar columns for 15.3

- data/sssd-tests/testincl.sh
- Related ticket: https://progress.opensuse.org/issues/67987
- Needles: N/A
- Verification run: https://openqa.opensuse.org/t1383087 (sssd passed)
> sssd: prepare system to modify /etc/nsswitch.conf

- tests/boot/grub2_test.pm
- Fail: https://openqa.suse.de/tests/4629569#step/grub2_test/1
https://openqa.suse.de/tests/4643794 12-SP5
https://openqa.suse.de/tests/4643796 15-SP1
> Update repo for working kernel-vanilla

- lib/known_bugs.pm
- lib/opensusebasetest.pm
- lib/utils.pm
Ticket: https://progress.opensuse.org/issues/65040
Verification: http://kazhua.qa.suse.de/tests/94#step/oom/25
> Show OOM infos in post fail hook

- lib/known_bugs.pm
https://openqa.suse.de/t4659370 
Follow up to: #10954
> Disable oom serial failure for LTP tests

- lib/opensusebasetest.pm
- schedule/jeos/sle/rpi/jeos-main.yaml
- tests/jeos/firstrun.pm
Verification: https://openqa.suse.de/tests/4666935
> Test SLE15SP3 for Raspberry Pi

- lib/sles4sap.pm
I forgot to rename this sap slice in my last PR #10978.
- Needles: N/A
> Rename sap.slice to SAP.slice

- .travis.yml
See also https://github.com/os-autoinst/os-autoinst/pull/1533
> Update perltidy to 20200907

- tests/console/glibc_sanity.pm
Verifiction:  https://openqa.suse.de/tests/4681555#
> Fix glibc_sanity for aarch64

- lib/kdump_utils.pm
- schedule/jeos/sle/rpi/jeos-extratest.yaml
Verification: https://openqa.suse.de/tests/4688527
> Run and fix extratest for RPi

- schedule/migration/leaptosle_zdup.yaml
This is a yaml file, for leap to sle zdup migration test
> For leap to sle zdup migration yaml file

- schedule/jeos/sle/rpi/jeos-filesystem.yaml
Verification: https://openqa.suse.de/t4696158
> Add YAML schedule for rpi filesystem test

- tests/boot/grub2_test.pm
- Fail: https://openqa.suse.de/tests/4696931#step/grub2_test/23
- Verification run: https://openqa.suse.de/tests/4695858
> Use another kernel-vanilla repo on 15-SP2 and never

- tests/containers/zypper_docker.pm
- bsc#1171672 Missing Leap:latest container image for s390x
- This is a known bug, indicated as soft-fail in other tests (eg
docker.pm, podman.pm)
- Related ticket: https://progress.opensuse.org/issues/71035
- Needles: N/A
s390x : [SLE15-SP3](https://openqa.suse.de/tests/4695778)
X86_64 : [SLE15-SP3](https://openqa.suse.de/tests/4692997), [SLE15](https://openqa.suse.de/tests/4693001), [Tumbleweed](https://openqa.opensuse.org/tests/1395077), [Leap JeOS](https://openqa.opensuse.org/tests/1394741)
aarch64 : [SLE15-SP3](https://openqa.suse.de/tests/4693025)
> Fix failing in zypper_docker test

- tests/console/bind.pm
- Related ticket: https://progress.opensuse.org/issues/71329
http://10.100.12.155/tests/16394
https://openqa.suse.de/tests/4688277 x86_64 15-SP2
https://openqa.suse.de/tests/4688278 s390x 15-SP2
https://openqa.suse.de/tests/4688276 aarch64 15-SP2
https://openqa.suse.de/tests/4688280 x86_64 15-SP1
https://openqa.suse.de/tests/4688279 s390x 15-SP1
> Bind testsuite fixes

- data/filesystem/autoyast_filesystem_withouthome.xml.ep
- lib/autoyast.pm
- Related ticket: https://progress.opensuse.org/issues/70993
- Fail: https://openqa.suse.de/tests/4701167
http://dzedro.suse.cz/tests/16421 15
http://dzedro.suse.cz/tests/16422 15-SP1
> xfstest: Fix for missing LTSS

- lib/data_integrity_utils.pm
- tests/installation/bootloader_svirt.pm
- Related ticket: [[qac][JeOS] enable VMware test suites](https://progress.opensuse.org/issues/64406?issue_count=26&issue_position=23&next_issue_id=64445&prev_issue_id=68815)
- Needles: [sle](https://gitlab.suse.de/openqa/os-autoinst-needles-sles/-/merge_requests/1432)
* [jeos-poc](http://kepler.suse.cz/tests/1717)
* [jeos-extratest_xenhvm@svirt-xen-hvm](http://kepler.suse.cz/tests/1720#)
* [jeos-extratest_xenpv@svirt-xen-pv](http://kepler.suse.cz/tests/1721)
- Sync update: [MR:ibs-plugin](https://gitlab.suse.de/openqa/openqa-trigger-from-ibs-plugin/-/merge_requests/19)
> Enable JeOS testing in vmware host

- tests/remote/remote_controller.pm
Reverts os-autoinst/os-autoinst-distri-opensuse#9835
> Revert "Apply workaround to remote controller on SLES"

- tests/console/prepare_test_data.pm
- Needles: N/A
- Verification run: https://openqa.opensuse.org/t1398256 [running]
> prepare_test_data: combine curl and cpio call

- tests/virt_autotest/virt_utils.pm
libvirtd.log with debug level is over 100G on XEN host which use up the disk space ~ we have to record warning level output for now to continue the tests then investigate this issue.
- Failed tests in OSD: https://openqa.nue.suse.com/tests/4694347
- Verification run: https://openqa.nue.suse.com/tests/4701457
> Increase the log level to warning from debug

- schedule/qam/15-SP2/qam-sles4sap_wmp_hana_node1.yaml
- schedule/qam/15-SP2/qam-sles4sap_wmp_hana_node2.yaml
This PR adds dedicated YAML files for testing SAP WMP in QAM.
- Needles: N/A
> Add dedicated QAM tests for SAP wmp

- tests/console/snapper_jeos_cli.pm
Ticket: https://progress.opensuse.org/issues/71494
Verification: https://openqa.suse.de/tests/4706989
> Wait longer for bootloader for aarch64 jeos (aka RPi)

- schedule/sles4sap/ha_supportserver.yaml
- schedule/sles4sap/hana/hana_cluster_node.yaml
- schedule/sles4sap/hana/pvm_hana_cluster_node.yaml
- schedule/sles4sap/installation/install_sles4sap.yaml
- schedule/sles4sap/migration/migration_offline_sles4sap.yaml
- schedule/sles4sap/migration/migration_online_sles4sap.yaml
- schedule/sles4sap/netweaver/netweaver_cluster_node.yaml
- schedule/sles4sap/remote_desktop/sles4sap_remote_desktop_server.yaml
- schedule/sles4sap/remote_desktop/sles4sap_remote_desktop_windows_client.yaml
- schedule/sles4sap/sles4sap_gnome_saptune_v2.yaml
Fix some SLES4SAP test issues due to the recent change from "regular" testsuites to YAML format.
- Needles: N/A
- Verification run: http://1b210.qa.suse.de/tests/7361, http://1b210.qa.suse.de/tests/7362
- Related to schedule change: https://gitlab.suse.de/qa-css/openqa_ha_sap/-/merge_requests/186
> Fix SLES4SAP test issues

- schedule/sles4sap/netweaver/netweaver_cluster_node.yaml
Fix NetWeaver cluster test.
- Needles: N/A
- YAML scheduling file: https://gitlab.suse.de/qa-css/openqa_ha_sap/-/merge_requests/188
> Fix HA/SAP tests on sles4sap

- data/file_copy
- schedule/jeos/sle/rpi/jeos-fs_stress.yaml
- tests/console/fs_stress.pm
Verification: https://openqa.suse.de/tests/4715778
> Add rpi yaml schedule for fs-stress test

- lib/consoletest.pm
- lib/utils.pm
- tests/console/fs_stress.pm
Ticket: https://progress.opensuse.org/issues/66607
Verification:  https://openqa.suse.de/t4718837
> Run sysrq-t in post-fail-hook

- data/autoyast_sle15/autoyast_rt.xml
- tests/rt/kmp_modules.pm
* [slert15sp1](http://kepler.suse.cz/tests/1763)
* [slert15sp2](http://kepler.suse.cz/tests/1764)
> Update RT tests

- tests/jeos/glibc_locale.pm
> Define is_leap for glibc test case

- data/autoyast_sle15/autoyast_containers_ppc64le.xml
- data/autoyast_sle15/autoyast_containers_s390x.xml
VR's:  [s390x](https://openqa.suse.de/tests/4729954) [ppc64le](https://openqa.suse.de/tests/4729932)
> Containers: Fix AutoYaST profile for ppc64le and s390x

- lib/x11utils.pm
bsc#1159950 (gnome-session-failed is detected) can happens on *big* hardware with lot of cpus/memory.
This commit adds a workaround for this issue.
- Needles: Already done in o.s.d. (was needed to be able to run the verification test).
- Verification run: https://openqa.suse.de/t4746387
- Regression test: http://1b210.qa.suse.de/tests/7448
**Note:** the failure in `wizard_hana_install` is not related to this PR. It looks like as if screensaver is activated (see the reducing gamma [here](https://openqa.suse.de/tests/4744503#step/wizard_hana_install/40)). This issue will be addressed in another PR.
> Workaround bsc#1159950

- lib/partition_setup.pm
Current implementation of `select_first_hard_disk` has issues when NVME devices are present, as these devices are selected by default during OS installation.
This commit fixes this.
**More details:** the current code exits if `skip_select_first_hard_disk` return true, and this function always return true if the first device is selected. So the code after `return if skip_select_first_hard_disk;` is in fact rarely executed, which may lead to sporadic issues, as `check_screen/assert_screen` not always return the same tag, but the one found during the check.
So the purpose of this PR is still to select the first device for the OS installation, but all the exclude parts are done at the beginning, instead of always select the first device. If this approach looks wrong, in that case maybe we …
> Fix partitioning_finish test on NVME server

- schedule/yast/yast2_ncurses/yast2_ncurses_gnome.yaml
- schedule/yast/yast2_ncurses/yast2_ncurses_textmode.yaml
- schedule/yast/yast2_ncurses/yast2_ncurses_textmode@svirt-xen-hvm.yaml
- Related ticket: https://progress.opensuse.org/issues/70867
- [Verification run](https://openqa.suse.de/tests/overview?build=b10n1k%2Fos-autoinst-distri-opensuse%2310984&distri=sle&version=15-SP3)
> Move yast2_nfs_server module to the YaST job group

- tests/virt_autotest/virt_utils.pm
Reverts os-autoinst/os-autoinst-distri-opensuse#11087
> Revert "Workaround of bsc#1176593 to use build 23.1 to install guest"

- tests/console/zypper_extend.pm
- tests/console/zypper_in.pm
- Related ticket: https://jira.suse.com/browse/SLE-16271
- Package to reproduce:
- For openSUSE Tumbleweed: https://build.opensuse.org/package/show/devel:openSUSE:QA:Tumbleweed/MariaDB-server-JIRA-SLE-16271
- For SLE15-SP3: https://build.suse.de/package/show/QA:Head/MariaDB-server-JIRA-SLE-16271
- Tumbleweed x86_64: http://openqa.slindomansilla-vm.qa.suse.de/tests/2840#step/zypper_extend/199
- SLE15-SP3 x86_64: http://openqa.slindomansilla-vm.qa.suse.de/tests/2841#step/zypper_extend/199
- SLE15-SP3 aarch64: http://openqa.slindomansilla-vm.qa.suse.de/tests/2845
- SLE15-SP2 x86_64: http://openqa.slindomansilla-vm.qa.suse.de/tests/2842
- Leap 15.2 x86_64: http://openqa.slindomansilla-vm.qa.suse.de/tests/2843#
> Check case-sensitive "zypper search --provides"

- tests/qam-updinstall/update_install.pm
The test previously parsed the patchinfo for the binary name, but was not
guaranteed to find the correct one as shown in [poo#69580](https://progress.opensuse.org/issues/69580). To fix that, the name
queried from SMELT is used. Add step to install binaries newly introduced in the
update.
- [Related ticket](https://progress.opensuse.org/issues/69580)
- Verification runs: [12SP2](http://apappas-openqa.qam.suse.de/tests/365) [12SP3](http://apappas-openqa.qam.suse.de/tests/367) [12SP4](http://apappas-openqa.qam.suse.de/tests/368) [12SP5](http://apappas-openqa.qam.suse.de/tests/366) [15SP0](http://apappas-openqa.qam.suse.de/tests/370) [15SP1](http://apappas-openqa.qam.suse.de/tests/371) [15SP2](http://apappas-openqa.qam.suse.de/tests/369)
> Change prepatch installation logic, add new binary installation test

- lib/containers/common.pm
This commit improved the output in the error case for the generic `test_container_image` routine
- Related ticket: https://progress.opensuse.org/issues/72124
- Needles: -
- Verification run: http://phoenix-openqa.qam.suse.de/t3084
> Improve debug output of test_container_image

- tests/hpc/slurm_master.pm
> HPC: Enable PMIx basic check for <SLE15SP2

- products/sle/main.pm
See jsc#SLE-15713 and jsc#SLE-16258 as design only provided png and they are smaller, it can be considered as a feature.
VR: https://openqa.suse.de/tests/4777396
> Adapt wallpaper extension for 15sp3

- tests/console/cups.pm
Ticket: https://progress.opensuse.org/issues/71503
Verification: https://openqa.opensuse.org/t1420763
> Disable cups in a reliable way

- tests/hpc/mpi_master.pm
> HPC: Add cpu info

- lib/main_common.pm
- tests/console/udisks2.pm
- Related failure: [tw-udisks2](https://openqa.opensuse.org/tests/1418458#step/udisks2/25)
- ticket: https://progress.opensuse.org/issues/71374
* [sle15.3](http://kepler.suse.cz/tests/2090)
* [tw-softfail](http://kepler.suse.cz/tests/2089)
* [tw](http://kepler.suse.cz/tests/2091)
> Softfail udisksctl when setting up loop device

- tests/kernel/install_klp_product.pm
Calling `select_serial_terminal()` more than once doesn't work on s390 workers. Select the best console in `install_klp_product` according to arch.
- Needles: N/A
- x86_64: https://openqa.suse.de/tests/4794424
- s390x: https://openqa.suse.de/tests/4794425
- ppc64le: https://openqa.suse.de/tests/4794426
> install_klp_product: Fix console switching on s390

- .travis.yml
See also https://github.com/os-autoinst/os-autoinst/pull/1551
> Update perltidy to 20201001

- schedule/functional/extra_tests_transactional_server.yaml
Ticket: https://progress.opensuse.org/issues/72205
Verification: http://kazhua.qa.suse.de/tests/95#step/update_alternatives/8
> Schedule update_alternatives on extra_tests_transactional_server

- lib/opensusebasetest.pm
- tests/shutdown/shutdown.pm
Reverts os-autoinst/os-autoinst-distri-opensuse#11120
> Revert "Add a workaround for shutdown module on s390"

- tests/yast2_cmd/yast_dns_server.pm
- Related ticket: https://progress.opensuse.org/issues/73219
- Needles: no
sles12sp4: http://10.67.17.201/tests/1109
sles12sp5: http://10.67.17.201/tests/1106
sles15sp1: http://10.67.17.201/tests/1102
sles15sp2: http://10.67.17.201/tests/1104
> Fixed failed test for yast dns server

- tests/security/selinux/selinux_setup.pm
Install "policycoreutils-python-utils" pkg for tool "semanage".
Add a warning message if any pkgs are missing,
e.g., pkgs "setools-devel/setools-java/setools-libs" are missing on Tumbleweed.
Test cases are passed and no new issue introduced.
- Related ticket: https://progress.opensuse.org/issues/73102
- Needles: NA
SLE: http://openqa.suse.de/tests/4830911#
TW: https://openqa.opensuse.org/tests/1434600 
(the failed case can be tracked by bsc#1177675 - SELinux command "# sepolgen-ifgen" failed on ".../userdomain.if: Syntax error ..."
> Fix selinux_setup issue: revise necessary pkgs

- tests/console/firewalld.pm
VR: https://openqa.suse.de/t4832478
> Fix firewalld test to run in SLE 15-SP3

- tests/console/openqa_review.pm
- tests/transactional/health_check.pm
- Related ticket: https://progress.opensuse.org/issues/73231
- verification runs: 
- `health_check`: https://openqa.opensuse.org/t1436280
- `openqa-review`: https://openqa.opensuse.org/t1436133
> Make sure we are on the root console

- lib/Utils/Systemd.pm
- lib/apparmortest.pm
- lib/hacluster.pm
- lib/openscaptest.pm
- lib/opensusebasetest.pm
- lib/s390base.pm
- lib/wickedbase.pm
- tests/console/snapper_cleanup_timeline.pm
- tests/console/validate_lvm.pm
- tests/console/validate_yast2_firstboot_configuration.pm
- tests/kernel/run_ltp.pm
- tests/yast2_gui/yast2_lan_restart_bond.pm
- tests/yast2_gui/yast2_lan_restart_bridge.pm
- tests/yast2_gui/yast2_lan_restart_vlan.pm
Ticket: https://progress.opensuse.org/issues/72175
Verification: http://kazhua.qa.suse.de/tests/101#step/rabbitmq/172
> Extend post_fail_hooks to capture journal from specific units

- tests/console/firewalld.pm
VR: https://openqa.suse.de/t4863472
See JSC#15028
> Display details about firewalld installed version

- tests/x11/remote_desktop/onetime_vncsession_xvnc_remmina.pm
Revert "Update onetime_vncsession_xvnc_remmina to fix poo#71785"
> Revert "Update onetime_vncsession_xvnc_remmina to fix poo#71785"

- lib/containers/common.pm
- lib/containers/container_images.pm
- lib/version_utils.pm
- lib/virt_autotest/kernel.pm
- schedule/containers/sle_image_on_centos.yaml
- schedule/containers/sle_image_on_ubuntu.yaml
- tests/containers/docker_image.pm
- tests/containers/host_configuration.pm
- tests/containers/podman_image.pm
- tests/cpu_bugs/ipmi_to_qemu.pm
- tests/virt_autotest/virt_utils.pm
- tests/virtualization/universal/hotplugging.pm
- tests/virtualization/universal/patch_guests.pm
- tests/virtualization/universal/register_guests.pm
- tests/virtualization/universal/ssh_hypervisor_init.pm
- tests/virtualization/universal/stresstest.pm
Append logic in the `install_podman_when_needed` and `install_docker_when_needed`                                                                                                                                                            
to cover docker and podman installation when host is Ubuntu.
Rename get_sles_release and enhance return variables.                                                                                                                                                                                                                                                                                                                                                                                                                           
The function now returns the …
> Add instructions to install docker and podman in Ubuntu

- tests/console/gdb.pm
Follow up of https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/11263
> Sysvinit tool install in leap

- lib/windowsbasetest.pm
- lib/wsl.pm
- schedule/wsl/wsl_main.yaml
- tests/wsl/firstrun.pm
- tests/wsl/prepare_wsl_feature.pm
- tests/wsl/wsl_cmd_check.pm
- Needles:
* [osd](https://gitlab.suse.de/openqa/os-autoinst-needles-sles/-/merge_requests/1453)
* [o3](https://github.com/os-autoinst/os-autoinst-needles-opensuse/pull/695)
* [TW-wsl1](http://kepler.suse.cz/tests/2347#)
* [TW-wsl2](http://kepler.suse.cz/tests/2348#)
* [sle-15-SP2-wsl2-main+register@windows_bios_boot](http://kepler.suse.cz/tests/2350#)
* [sle-15-SP2-wsl2-main+skip_reg@windows_bios_boot](http://kepler.suse.cz/tests/2351#)
* [sle-15-SP2-wsl1-wsl-main+skip_reg@windows_bios_boot ](http://kepler.suse.cz/tests/2355#)
* [sle-15-SP2-wsl1-main+register@windows_bios_boot ](http://kepler.suse.cz/tests/2354#)
- Test Suite setup:
* `WSL2=1`
* `QEMUCPU=Skylake-Client-v3,kvm=off,vmx=on,hypervisor=off,hv_time,hv_relaxed,hv_vapic,hv_spinlocks=0x1fff`
> WSL2 kick off

- data/virt_autotest/virt_logs_collector.sh
* **Use** "cp --parent" to copy parent directories of extra logs to preserve absolute path info
* **Create** host extra log directory to contain all extra host logs
* **Verification run:**
* **The** logs collected on 12-SP5 KVM host now look like:
* **This** modification works for log collecting via ssh:
[virt_logs_collector.log](https://github.com/os-autoinst/os-autoinst-distri-opensuse/files/5412990/virt_logs_collector.log)
[fetch_logs_from_guest.log](https://github.com/os-autoinst/os-autoinst-distri-opensuse/files/5412991/fetch_logs_from_guest.log)
* **This** modification also works for log collecting via guest console:
[virt_logs_collector.log](https://github.com/os-autoinst/os-autoinst-distri-opensuse/files/5412993/virt_logs_collector.log) …
> Copy parent directories of extra logs to preserve absolute path info

- tests/microos/journal_check.pm
Example: https://openqa.suse.de/tests/4870905#step/journal_check/6
Fix: https://openqa.suse.de/tests/4887311#step/journal_check/5
> MicroOS: Add bsc#1178033 to whitelist

- tests/wsl/prepare_wsl_feature.pm
* failure: [timeout](https://openqa.suse.de/tests/4888219#step/prepare_wsl_feature/27)
> Increase download timeout value for pull kernel update

- lib/validate_encrypt_utils.pm
- schedule/yast/encryption/cryptlvm+cancel_existing.yaml
- schedule/yast/encryption/cryptlvm+cancel_existing_pvm.yaml
- schedule/yast/lvm/lvm+cancel_existing_cryptlvm.yaml
- schedule/yast/lvm/lvm+cancel_existing_cryptlvm_pvm.yaml
- test_data/yast/encryption/cryptlvm+cancel_existing.yaml
- tests/console/validate_encrypted_partition_not_activated.pm
- See [poo#72172](https://progress.opensuse.org/issues/72172)
- Verification run: [validate_encrypted_partition_not_activated](https://openqa.suse.de/tests/overview?build=jknphy%2Fos-autoinst-distri-opensuse%23fix_ensure_locked_enc_part&distri=sle&version=15-SP3)
> Verify locked encrypted partition

- tests/boot/snapper_rollback.pm
Reverts os-autoinst/os-autoinst-distri-opensuse#11278
> Revert "Fix 'snapper list' timeout in snapper_rollback"

- lib/windowsbasetest.pm
[Reboot issue](https://openqa.suse.de/tests/4888803#step/prepare_wsl_feature/40)
> Increase reboot timeout

- tests/ha/iscsi_client.pm
In SLES 15-SP3 when the hostname of the cluster nodes are changed (by test module `console/hostname`), drbd resources configured to the cluster fail to start (more info in [bsc#1177927](https://bugzilla.suse.com/show_bug.cgi?id=1177927#c15))
As explained in the bug report:
```
The reason of DRBD start failure by RA is because udev rules of creating DRBD
device (drbd_passive in this case) is not applied. Re-set the hostname(without a reboot)
is the reason of this issue, cause it makes a mismatch of configuration in udev daemon.
This issue caused by udev daemon get the hostname and store it in static area.
The spawn(forked) processes shared the same area and get the old hostname. And
DRBD will ignore the configuration that not belong to local host.
``` …
> Restart udevd in HA tests if HOSTNAME was changed

- tests/installation/ipxe_install.pm
Some minor fixes for the ipxe_install.pm without autoyast
> Fix ipxe install

- tests/fips/mozilla_nss/firefox_nss.pm
**Description**:
The problem is randomly reproduced in aarch64 and few times in x86_64/s390x, I suspect the error is also a race condition about poor worker performance in aarch64. Plan to extend a bit the waiting time and also adjust the 2nd Firefox launch approach. It's probably also some trouble for **x11_start_program**() if inputting 3 parameters under the bad internet connection, thus the input password pop-up window is not reacted before **type_string $fips_password** and cause the password input lose.
1. Replace x11_start_program 2nd Firefox launch to xterm
2. Add 2 needles match to avoid racing condition
- Related ticket: https://progress.opensuse.org/issues/75283
- Needles: 2 Needles are merged in O.S.D.
https://openqa.suse.de/t4899112 (x86_64) …
> Amend 2nd Firefox launch via xterm to avoid password input lose

- products/sle/main.pm
- tests/virt_autotest/update_package.pm
- tests/virt_autotest/virt_utils.pm
This PR is associated with https://github.com/SUSE/qa-automation/pull/749.
[gi-guest_developing-on-host_developing-xen](http://10.67.129.51/tests/1624)
[gi-guest_developing-on-host_sles15sp2-xen](http://10.67.129.51/tests/1625)
[gi-guest_developing-on-host_sles12sp5-kvm](http://10.67.129.51/tests/1626)
@alice-suse @guoxuguang @waynechen55 Please help review.
> Skip reboot after update package for sles15sp2+ host

- lib/autoyast.pm
- lib/kdump_utils.pm
- lib/maintenance_smelt.pm
- lib/qam.pm
- lib/utils.pm
- tests/installation/add_update_test_repo.pm
- tests/qam-updinstall/update_install.pm
- Related ticket: https://progress.opensuse.org/issues/72121
http://10.100.12.155/tests/16567#step/add_update_test_repo/56 don't add released repo
http://10.100.12.155/tests/16584 remove already added repo
https://openqa.suse.de/tests/4789266 aarch64
https://openqa.suse.de/tests/4789267 s390x
https://openqa.suse.de/tests/4789268 x86_64
http://10.100.12.15/tests/16882
http://10.100.12.15/tests/16887
http://10.100.12.15/tests/16884
http://10.100.12.15/tests/16886
http://10.100.12.15/tests/16885
> QEM: Don't add released or declined repositories

- data/autoyast_sle15/autoyast_microos_50_x86_64.xml
- lib/microos.pm
- schedule/microos/suse_microos_autoyast.yaml
- tests/autoyast/installation.pm
- Related ticket: https://progress.opensuse.org/issues/75340
- Verification run: http://fromm.arch.suse.de/tests/659
> MicroOS: Add autoyast installation

- tests/console/journalctl.pm
This commit adds a softfailure for [bsc#1178193](https://bugzilla.suse.com/show_bug.cgi?id=1178193) in the `journalctl` test
- Related ticket: https://progress.opensuse.org/issues/75166
- Needles: -
* [Tumbleweed x86_64](http://phoenix-openqa.qam.suse.de/tests/3404) | [Tumbleweed aarch64](https://openqa.opensuse.org/t1453025)
* [SLE15-SP2 x86_64](http://phoenix-openqa.qam.suse.de/tests/3408) | [SLES15-SP2 aarch64](https://openqa.suse.de/t4912205) | [SLES15-SP2 s390x](https://openqa.suse.de/t4914008)
* [SLE15-SP1](http://phoenix-openqa.qam.suse.de/tests/3409)
* [SLE15](http://phoenix-openqa.qam.suse.de/tests/3420)
* [SLE12-SP5](http://phoenix-openqa.qam.suse.de/tests/3415)
* [SLE12-SP4](http://phoenix-openqa.qam.suse.de/tests/3416)
* …
> Softfailure for 1178193 in journalctl

- lib/windowsbasetest.pm
- tests/wsl/prepare_wsl_feature.pm
- Related failure: [Powershell does not start in time](https://openqa.suse.de/tests/4900233#step/prepare_wsl_feature/50)
- Job group definition: [Use 2 vcpus for WSL2 testing ](https://gitlab.suse.de/qac/qac-openqa-yaml/-/merge_requests/65) 
- Verification run: [wsl2_15.2](https://openqa.suse.de/tests/4914129#)
> Do not close powershell after installing MS kernel

- lib/containers/utils.pm
- tests/containers/zypper_docker.pm
Fix random timeouts of docker* tests
- Related ticket: [poo#75418](https://progress.opensuse.org/issues/75418)
- Verification run: [SLE 15 SP1 Azure](http://pdostal-server.suse.cz/tests/10311#)
> Fix random docker timeouts

- lib/utils.pm
- Related ticket: https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/11153
- Fail: https://openqa.suse.de/tests/4915993
- Verification run: https://openqa.suse.de/tests/4916006
> Add pattern to identify released repo

- tests/wicked/before_test.pm
We currently face the problem that haveged is shown in `zypper ps` but
this isn't a issue from wicked. So we do now only care for `zypper ps`
programs which we really installed.
- Verification run: http://openqa.wicked.suse.de/t3417
> wicked: Validate `zypper ps` output with installed packages

- lib/networkdbase.pm
- tests/networkd/networkd_dhcp.pm
Ticket: https://bugzilla.suse.com/show_bug.cgi?id=1141597
Verification: http://kazhua.qa.suse.de/tests/108#details
> Remove workaround for boo#1141597 (networkd timezone)

- tests/console/mysql_odbc.pm
- Related ticket: https://progress.opensuse.org/issues/71929
* Tumbleweed x86_64: https://openqa.opensuse.org/t1414813
> Add unixODBC dep which is not pulled automatically - poo#71929

- schedule/functional/extra_tests_textmode.yaml
- schedule/qam/15-SP2/mau-extratests.yaml
- tests/console/ovn.pm
Add OVN basic test
- Related ticket: https://progress.opensuse.org/issues/70501
15.2 x86: https://openqa.suse.de/tests/4930361
15.2 s390: https://openqa.suse.de/tests/4924106
15.2 aarch64: https://openqa.suse.de/tests/4930305
tumbleweed x86: http://10.161.229.176/tests/84#
> Add OVN basic test

- schedule/functional/extra_tests_gnome.yaml
- tests/x11/exiv2.pm
Including YAML scheduling
Ticket: https://progress.opensuse.org/issues/76870
Verification: https://openqa.opensuse.org/t1458516
> openSUSE: Move extra_tests_on_gnome to extra_tests_gnome

- tests/sles4sap/hana_install.pm
It seems changes introduced in #11325 are causing HANA tests on IPMI with an specific device set on `HANA_INST_DEV` to fail as the partition still contains some LVM information from the previous test.
Current guess is that the `wipefs -a` calls introduced in #11325 for IPMI wipe enough information from the disk so the installer detects it as an empty disk, but leave LVM information intact at least in the third partition which make the `hana_install` module fail while creating a PV.
This PR introduces a `wipefs` call directly on the new partition (created in the same module) to ensure that it contains no LVM information, while also preemptively removing any trace of the VG and LVs that may have remained in the disks from a previous test.
- Failed test: …
> Ensure HANA_INST_DEV is clean before configuration

- lib/transactional.pm
- lib/utils.pm
- tests/transactional/rebootmgr.pm
- tests/transactional/verify_undelete_snapshots.pm
- Related ticket: https://progress.opensuse.org/issues/65304
- Job Group MR: https://gitlab.suse.de/qsf-y/qa-sle-functional-y/-/merge_requests/311
- Verification run: [create_hdd_transactional_server](https://openqa.suse.de/tests/4944579) |  [transactional_server_helper_apps](https://openqa.suse.de/tests/4944581) | [transactional_server_snapper_dev](https://openqa.suse.de/tests/4944580)
> Add transactional scenarios on PowerVM

- lib/service_check.pm
- lib/services/ntpd.pm
- lib/utils.pm
In SLES11SP4 migration, We'd like to check the ntp service, but the service name
is ntp not ntpd and the SLES11SP4 use the SystemV init.d. To make the service check  
framework to work on SLES11SP4, We'd add some common function to make the service 
actions unified. This means our service check needs to take care of both SystemV
and Systemd services.
- Related ticket: https://progress.opensuse.org/issues/70591
- Needles: N/A
https://openqa.nue.suse.com/tests/4854189 
https://openqa.nue.suse.com/tests/4854204 
https://openqa.nue.suse.com/tests/4930320  SLES11sp4
https://openqa.nue.suse.com/tests/4930338  SLES11sp4 
https://openqa.nue.suse.com/tests/4930341  SLES12sp5
http://openqa.nue.suse.com/t4934435 ntp 12sp4 passed
http://openqa.nue.suse.com/t4934470 ntp 12sp5 …
> Fix ntp service on SLES11SP4

- tests/x11/multi_users_dm.pm
We don't use cirrus for some time now, so this is no longer necessary.
TW GNOME: http://10.160.67.86/tests/834
TW Plasma: http://10.160.67.86/tests/836
15.2 Plasma: http://10.160.67.86/tests/838
15.3 Xfce: http://10.160.67.85/tests/840
What else needs a VR?
> Drop reboot workaround in multi_users_dm

- tests/console/apache.pm
VR: https://openqa.suse.de/tests/4962193
Failing job: https://openqa.suse.de/tests/4955079#step/apache/24
> Use serial terminal to reduce probability of mistyping

- schedule/functional/allpatterns.yaml
- Failed job: https://openqa.suse.de/tests/4961295#step/scc_registration/2
- Verification run: https://openqa.suse.de/tests/4966196#step/scc_registration/2
> Schedule disk_activation when z/VM

- schedule/qam/common/qam-libssh.yml
- tests/console/libssh.pm
Libssh1 and libssh2 test
- Related ticket: https://progress.opensuse.org/issues/73420
- Needles: no
sles15sp3: http://10.67.183.130/tests/131
sles15sp2: http://10.67.183.130/tests/125
sles15sp1: http://10.67.183.130/tests/132
sles12sp5: http://10.67.183.130/tests/121
sles12sp4: http://10.67.183.130/tests/47
opensuse-Tumbleweed: http://10.67.183.130/tests/126
Detailed test cases: http://bugzilla.suse.com/tr_show_case.cgi?case_id=1768668
> Libssh1 and libssh2 test

- declarative-schedule-doc.md
- lib/scheduler.pm
- schedule/functional/extra_tests_gnome.yaml
- t/02_yaml_schedule.t
- t/data/test_schedule_recursive_conditional.yaml
- tools/detect_nonexistent_modules_in_yaml_schedule
Ticket: https://progress.opensuse.org/issues/76870
Verification (scheduling only):
* *x86_64*: http://kazhua.qa.suse.de/tests/124
* *ppc64le*: http://kazhua.qa.suse.de/tests/125
> Run steam only on x86_64

- schedule/yast/allmodules+registration/allmodules+registration.yaml
- schedule/yast/allmodules+registration/allmodules+registration@pvm.yaml
- schedule/yast/allmodules+registration/allmodules+registration@s390x-zVM.yaml
- schedule/yast/allmodules+registration/allmodules+registration@s390x.yaml
- schedule/yast/allmodules+registration/allmodules+registration@svirt-hyperv.yaml
- schedule/yast/allmodules+registration/allmodules+registration@uefi.yaml
- schedule/yast/allmodules/allmodules.yaml
- schedule/yast/allmodules/allmodules_pvm.yaml
Remove allpatterns from allmodules+allpatterns+registration.
Related ticket https://progress.opensuse.org/issues/76918
Gitlab PR https://gitlab.suse.de/qsf-y/qa-sle-functional-y/-/merge_requests/312
> Remove allpatterns from allmodules+allpatterns+registration. 

- lib/virt_autotest/kernel.pm
- lib/virt_autotest/utils.pm
- tests/virt_autotest/virsh_external_snapshot.pm
- tests/virtualization/universal/guest_management.pm
- tests/virtualization/universal/hotplugging.pm
- tests/virtualization/universal/list_guests.pm
- tests/virtualization/universal/prepare_guests.pm
- tests/virtualization/universal/virtmanager_add_devices.pm
- tests/virtualization/universal/virtmanager_init.pm
- tests/virtualization/universal/virtmanager_rm_devices.pm
Various improvements in the QEM virtualization runs
- Related tickets: [poo#69910](https://progress.opensuse.org/issues/69910) [poo#72295](https://progress.opensuse.org/issues/72295) [poo#72298](https://progress.opensuse.org/issues/72298)
- Needles: https://gitlab.suse.de/openqa/os-autoinst-needles-sles/-/merge_requests/1462
- Verification run: http://phoenix-openqa.qam.suse.de/tests/3864
> Various QEM virtualization improvements

- lib/main_common.pm
- tests/console/parsec.pm
* aarch64: https://openqa.opensuse.org/t1470060
* x86_64: https://openqa.opensuse.org/tests/1475832
> Add parsec test

- lib/utils.pm
We need report failure when patterns conflict happen, besides workaround for known bug we need deal with other patterns conflict and report failure. 
- Related ticket: https://progress.opensuse.org/issues/77794
- Needles: N/A
- Verification run: http://openqa.nue.suse.com/tests/4991588#step/patch_sle/133
http://openqa.nue.suse.com/tests/4991532#details  # verify it won't affect workaround for reported bug
> Need report failure when patterns conflict happen

- tests/qam-updinstall/update_install.pm
If the test knows what is missing, it should tell me and not let me dig it up from infos I don't have :)
> Make the failure condition in update_install a little more expressive

- tests/console/system_prepare.pm
Ticket: https://progress.opensuse.org/issues/62864
Verification: http://kazhua.qa.suse.de/tests/126#
> Install systemd-coredump when needed

- tests/console/force_scheduled_tasks.pm
- Related ticket: https://progress.opensuse.org/issues/75424
- Job Group MR: https://gitlab.suse.de/qsf-y/qa-sle-functional-y/-/merge_requests/313
- Verification run: [10 runs allmodules+allpatterns+registration](https://openqa.suse.de/tests/overview?distri=sle&version=15-SP3&build=78.1&groupid=96)
> Bump timeout in force_scheduled_tasks

- lib/containers/common.pm
- lib/containers/utils.pm
- tests/publiccloud/register_system.pm
* podman container commit tw tw:saved timeout
https://openqa.suse.de/tests/4928694#step/podman/89
* zypper lr error
https://openqa.suse.de/tests/4943137#step/register_system/7
---
- Verification run: [SLE 15-SP1 GCE BYOS](http://pdostal-server.suse.cz/tests/10423#)
> Fix occasional timeouts and serial console failures

- tests/wsl/install/ms_win_firstboot.pm
- Verification run: [Win10_20H2](http://kepler.suse.cz/tests/2671)
> Update installation flow to 2h02 release

- tests/x11/vlc.pm
Ticket: https://progress.opensuse.org/issues/42773
Needles: https://github.com/os-autoinst/os-autoinst-needles-opensuse/pull/699
Verification: http://kazhua.qa.suse.de/tests/139
> VLC: test video rendering

- tests/wsl/install/ms_win_firstboot.pm
- tests/wsl/install/ms_win_installation.pm
- Verification run: [windows_bios_boot](https://openqa.suse.de/tests/5065129)
> Windows installation wait more while account options being loaded

- tests/console/validate_raid.pm
See [poo#80244](https://progress.opensuse.org/issues/80244).
[Verification run](https://openqa.suse.de/tests/5070305).
> Adjust regexp for RAID validation on arm

- tests/containers/docker_compose.pm
Failure: https://openqa.suse.de/tests/5068092#step/docker_compose/27
VR: https://openqa.suse.de/tests/5070041#step/docker_compose/84
> Do not register python2 for sle15

- tests/wsl/install/ms_win_installation.pm
- Verification runs: [Build20H2-windows_10@uefi_win ](http://kepler.suse.cz/tests/2681#step/ms_win_installation/26)
> Click next after selecting partition

- lib/wicked/wlan.pm
We are missing hostapd package in PackageHub for SLE-12-SP5.
So we are going to install hostapd from
https://build.opensuse.org/package/show/Base:System/hostapd which is the
development project for all hostapd versions in SLE and openSUSE.
We also need to create a workaround to set one PHY into the network
namespace. Reason, the `iw phy <phy> netns` command doesn't support the
`name` parameter. The solution is to run a "dummy" process, just to get
a pid, so we can set a phy into a namespace.
- Related ticket: https://progress.opensuse.org/issues/66102
- Verification run: http://openqa.wicked.suse.de/tests/4011
> wicked: WLAN testsuite for SLE-12-SP5

- lib/Installation/Partitioner/AbstractExpertPartitionerController.pm
- lib/Installation/Partitioner/FormattingOptionsPage.pm
- lib/Installation/Partitioner/LibstorageNG/v4/ExpertPartitionerController.pm
- lib/Installation/Partitioner/LibstorageNG/v4_3/AddLogicalVolumePage.pm
- lib/Installation/Partitioner/LibstorageNG/v4_3/AddVolumeGroupPage.pm
- lib/Installation/Partitioner/LibstorageNG/v4_3/CreatePartitionTablePage.pm
- lib/Installation/Partitioner/LibstorageNG/v4_3/DeletingCurrentDevicesDialog.pm
- lib/Installation/Partitioner/LibstorageNG/v4_3/ExpertPartitionerController.pm
- lib/Installation/Partitioner/LibstorageNG/v4_3/ExpertPartitionerPage.pm
- lib/YuiRestClient/App.pm
- lib/YuiRestClient/Widget/RadioButton.pm
- lib/YuiRestClient/Widget/Textbox.pm
- lib/YuiRestClient/Widget/Tree.pm
- schedule/yast/encryption/lvm_encrypt_separate_boot.yaml
- schedule/yast/encryption/lvm_encrypt_separate_boot_opensuse.yaml
- schedule/yast/encryption/lvm_encrypt_separate_boot_pvm.yaml
- schedule/yast/encryption/lvm_full_encrypt.yaml
- schedule/yast/encryption/lvm_full_encrypt_opensuse.yaml
- schedule/yast/encryption/lvm_full_encrypt_pvm.yaml
- test_data/yast/encryption/full_lvm_enc_prep_boot.yaml
- test_data/yast/encryption/full_lvm_enc_prep_boot_pvm.yaml
- test_data/yast/encryption/full_lvm_enc_uefi.yaml
- test_data/yast/encryption/lvm_encrypt_separate_boot_prep_boot.yaml
- test_data/yast/encryption/lvm_encrypt_separate_boot_prep_boot_pvm.yaml
- test_data/yast/encryption/lvm_encrypt_separate_boot_uefi.yaml
- tests/installation/partitioning/encrypted_full_lvm.pm
- tests/installation/setup_libyui.pm
- Related ticket: [poo#78016](https://progress.opensuse.org/issues/78016) | [poo#78088](https://progress.opensuse.org/issues/78088)
- Job Group MR: https://gitlab.suse.de/qsf-y/qa-sle-functional-y/-/merge_requests/318
- Verification run: [opensuse](https://openqa.opensuse.org/tests/overview?version=Tumbleweed&build=jknphy%2Fos-autoinst-distri-opensuse%23adapt_with_libyui_rest_api&distri=opensuse) | [sle](https://openqa.suse.de/tests/overview?build=jknphy%2Fos-autoinst-distri-opensuse%23adapt_with_libyui_rest_api&distri=sle&version=15-SP3)
Note: for aarch64 failures, please see [poo#1178832](https://bugzilla.suse.com/show_bug.cgi?id=1178832) and for grub_test failures [poo#1178832](https://bugzilla.suse.com/show_bug.cgi?id=1178832)
> Adjust lvm-full-encrypt for the UI changes in the Expert Partitioner

- lib/wicked/wlan.pm
Hostapd isn't in SLES so we need to install from a third party. With
PackageHub we are not able to install for product QA e.g. SLE-15-SP3
which is currently in development.
Thanks to @plusky we have now
`https://build.suse.de/package/show/QA:Head/hostapd` which is a link to
`openSUSE.org:Base:System/hostapd`.
- Related ticket: https://progress.opensuse.org/issues/66102
- http://openqa.wicked.suse.de/t4039 (SLE_15_SP3)
- http://openqa.wicked.suse.de/t4073 (SLE_15_SP2)
- http://openqa.wicked.suse.de/t4043 (SLE_15)
- http://openqa.wicked.suse.de/t4037 (SLE_12_SP5)
> wicked: Use QA:Head for hostapd

- tests/console/clamav.pm
**Description:**
In SLE15 SP3 new feature, SLE-16780 upgrade Clamav SLE. SLE shipped Clamav 0.100 already, we will plan to upgrade to 0.103 (the latest stable version). This PR is adding the version check in Clamav, and if the version is not higher than 0.100 will be record as soft fail in advance, and then will add more function tests if necessary in the future. 
- Related ticket: https://progress.opensuse.org/issues/80182
- Needles: NA
https://openqa.suse.de/tests/5076639#step/clamav/15 (Updated)
> Add Clamav version check for SLE15 SP3 feature

- lib/power_action_utils.pm
GNOME 3.38 changes the openQA graphical reboot process.
This requires branching the reboot behavior based on gnome version and not  on product version, since the afforementioned behavior can affect the maintenance products eventually.
- Related ticket: https://progress.opensuse.org/issues/77785
- Needles: No Needles
- Verification run: [sle-15-SP2](http://angmar.suse.de/tests/2629#step/reboot_gnome/11) |  [sle-12-SP4](http://angmar.suse.de/tests/2628#step/reboot_gnome/11) | [upgrade-Leap-to-Tumbleweed](http://angmar.suse.de/tests/2630#step/reboot_gnome/9) | [Tumbleweed](http://angmar.suse.de/tests/2627#step/reboot_and_install/12) | [Tumbleweed-Staging](http://angmar.suse.de/tests/2626#step/reboot_gnome/10)
> Check gnome version before graphical reboot

- lib/virt_autotest/utils.pm
- products/sle/main.pm
- tests/virt_autotest/download_guest_assets.pm
- tests/virt_autotest/restore_guests.pm
- tests/virt_autotest/sriov_network_card_pci_passthrough.pm
- tests/virt_autotest/virt_utils.pm
#1 add modules in main.pm to support the test suite
#2 adjust test scenarios of original SRIOV tests
#3 enhance guest download scripts
[sriov_network_card_pci_passthrough-xen  15-sp3-pv](http://10.67.129.51/tests/1690)  
[sriov_network_card_pci_passthrough-xen  15-sp2-fv](http://10.67.129.51/tests/1677) 
[sriov_network_card_pci_passthrough-xen  download_multiple_guests](http://10.67.129.51/tests/1675) 
[sriov_network_card_pci_passthrough-kvm](http://10.67.129.51/tests/1650)
@alice-suse @guoxuguang @waynechen55  Please help review.
> Deploy SRIOV passthrough test in OSD

- test_data/yast/lvm_raid1/lvm+raid1.yaml
- test_data/yast/lvm_raid1/lvm+raid1_hyperv.yaml
- test_data/yast/lvm_raid1/lvm+raid1_hyperv_uefi.yaml
- test_data/yast/lvm_raid1/lvm+raid1_svirt-xen.yaml
- test_data/yast/lvm_raid1/lvm+raid1_uefi.yaml
Originally I've accidentally used merge key, even though simple include
was required. Fixing it.
See [poo#77767](https://progress.opensuse.org/issues/77767).
[VR](https://openqa.suse.de/tests/5083225).
> Fix yaml test data imports for lvm+RAID1 test suite

- tests/containers/validate_btrfs.pm
- Verification run: https://openqa.suse.de/tests/overview?distri=sle&build=b10n1k%2Fos-autoinst-distri-opensuse%23btrfs&version=15-SP3
> Use image with increased size for btrfs validation test

- tests/installation/partitioning_specific_disk.pm
Fix Expert Partitioner screen and hot key change
Related ticket: N/A
Needles: https://gitlab.suse.de/openqa/os-autoinst-needles-sles/-/merge_requests/1465
Verification run: http://10.67.129.7/tests/425
> Fix Expert Partitioner screen and hot key change

- tests/console/force_scheduled_tasks.pm
Avoid to waste time when trying to settle the load for 2nd time when [bsc#1178761](https://bugzilla.suse.com/show_bug.cgi?id=1178761) is present.
- Related ticket: see [poo#75424](https://progress.opensuse.org/issues/75424)
- Verification run: [10 runs of select_modules_and_patterns+registration](https://openqa.suse.de/tests/overview?distri=sle&version=15-SP3&build=89.1&groupid=96) Notice 1-2 out of 10 is reproducible and we [soft-fail](https://openqa.suse.de/tests/5082484#step/force_scheduled_tasks/6) and we don't waste time settle the load a second time which might help to not restart the job because exceeded 2 hours or configure it to run for more than that default time.
> Adjust force_scheduled_tasks to not waste time

- lib/Installation/Partitioner/FormattingOptionsPage.pm
- lib/Installation/Partitioner/LibstorageNG/v4_3/ConfirmationWarning.pm
- lib/Installation/Partitioner/LibstorageNG/v4_3/DeletingCurrentDevicesWarning.pm
- lib/Installation/Partitioner/LibstorageNG/v4_3/ExpertPartitionerController.pm
- lib/Installation/Partitioner/LibstorageNG/v4_3/ExpertPartitionerPage.pm
- lib/Installation/Partitioner/LibstorageNG/v4_3/ResizePage.pm
- lib/Installation/Partitioner/LibstorageNG/v4_3/SmallForSnapshotsWarning.pm
- schedule/yast/separate_usr_partition.yaml
- tests/installation/partitioning/separate_usr_partition.pm
See [poo#78100](https://progress.opensuse.org/issues/78100)
Verification run: [separate_usr_partition](https://openqa.opensuse.org/tests/1491784#step/separate_usr_partition/15)
> Adapt separate_usr_partition to use YuiRestClient

- lib/containers/utils.pm
Address https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/11510#discussion_r533144800 and https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/11510#discussion_r533146252
> Update perlpod for can_build_sle_base based on feedbacks

- data/containers/docker-compose.yml
- tests/containers/containers_3rd_party.pm
- tests/containers/docker_compose.pm
- tests/containers/registry.pm
Affected tests:
- containers_3rd_party
- docker_compose
- registry
See failures: https://openqa.opensuse.org/tests/1492189
VR: TBD
> Containers: Fix remaining test cases pulling from docker.io

- lib/main_common.pm
- tests/cpu_bugs/mitigation_perf.pm
Initialize scripts for vt mitigation performanace test
- Needles: N/A
- Verification run: http://10.67.134.217/tests/11608, http://10.67.134.217/tests/11607
> Initialize scripts for mitigation performance test

- lib/Installation/Partitioner/LibstorageNG/v4_3/AddLogicalVolumePage.pm
- lib/Installation/Partitioner/LibstorageNG/v4_3/ExpertPartitionerController.pm
- Related ticket: [poo#78016](https://progress.opensuse.org/issues/78016) | [poo#78088](https://progress.opensuse.org/issues/78088)
- [splitusr](https://openqa.opensuse.org/tests/1492299)
- [lvm-full-encrypt](https://openqa.suse.de/tests/5118990)
- [lvm-full-encrypt on aarch64](https://openqa.suse.de/tests/5119016)
> Fix size textbox id with YuiRestClient adding LVs

- data/virtualization/Vagrantfile
- data/virtualization/ansible_playbook.yml
- data/virtualization/check_ip.sh
- data/virtualization/prepare_repos.sh
- data/virtualization/provision.sh
- schedule/vagrant.yaml
- tests/virtualization/vagrant/boxes/tumbleweed.pm
This is a work in progress pull request to move the currently hidden jenkins pipeline fully into openQA and test the Tumbleweed Vagrant box on openQA.
- Needles: not required
- Verification run: https://openqa.opensuse.org/tests/1481792
> port vagrant jenkins pipeline to openQA

- data/man_or_boy.go
- schedule/functional/extra_tests_textmode.yaml
- schedule/qam/12-SP5/mau-extratests.yaml
- schedule/qam/15-SP1/mau-extratests.yaml
- schedule/qam/15-SP2/mau-extratests.yaml
- tests/console/golang.pm
Ticket: https://progress.opensuse.org/issues/78031
Verification: http://kazhua.qa.suse.de/tests/161
> Add golang test

- CONTRIBUTING.md
Related progress issue: https://progress.opensuse.org/issues/72853
> CONTRIBUTING: Add best practice for handling separate product codebases

- lib/hacluster.pm
Add POD documentation to `lib/hacluster`.
- Related ticket: https://jira.suse.com/browse/TEAM-2107
- Needles: N/A
> Add POD documentation to lib/hacluster

- schedule/qam/QR/lvm_encrypt_separate_boot.yaml
- test_data/qam/QR/full_lvm_enc.yaml
- Related ticket: https://progress.opensuse.org/issues/78088
- Job Group MR: [mr#32](https://gitlab.suse.de/qa-maintenance/qam-openqa-yml/-/merge_requests/32)
- Verification run: [15-SP1](https://openqa.suse.de/tests/overview?build=jknphy%2Fos-autoinst-distri-opensuse%23fix_qr_lvm_encrypt_separate_boot&version=15-SP1&distri=sle) | [15-SP2](https://openqa.suse.de/tests/overview?version=15-SP2&build=jknphy%2Fos-autoinst-distri-opensuse%23fix_qr_lvm_encrypt_separate_boot&distri=sle)
> Fix lvm_encrypt_separate_boot for QR-15-SP1

- lib/sles4sap.pm
Add POD documentation to `lib/sles4sap`.
- Related ticket: https://jira.suse.com/browse/TEAM-2118
- Needles: N/A
> Add POD documentation to lib/sles4sap

- tests/autoyast/installation.pm
- tests/installation/welcome.pm
https://bugzilla.suse.com/show_bug.cgi?id=1179654
https://openqa.suse.de/tests/overview?distri=sle&version=15&build=20201208-1&groupid=165
https://openqa.suse.de/tests/5144638 x86_64
https://openqa.suse.de/tests/5144640 s390x
https://openqa.suse.de/tests/5144639 aarch64
https://openqa.suse.de/tests/5144774 x86_64 autoyast
https://openqa.suse.de/tests/5144775 s390x autoyast
https://openqa.suse.de/tests/5144776 aarch64 autoyast
http://dzedro.suse.cz/tests/17029
http://dzedro.suse.cz/tests/17032 autoyast
> workaround: Expired repo key on sle15

- schedule/yast/detect_yast2_failures.yaml
- Related ticket: https://progress.opensuse.org/issues/80766
- Online: http://falafel.suse.cz/tests/1022
- Full: http://falafel.suse.cz/tests/1021
> Adjust test detect_yast2_failures for UI changes

- tests/autoyast/installation.pm
- tests/installation/welcome.pm
#11566 https://bugzilla.suse.com/show_bug.cgi?id=1179654
> workaround: Record soft fail on SLE15 only

- lib/Installation/Partitioner/LibstorageNG/v4_3/ExpertPartitionerController.pm
- schedule/yast/encryption/home_encrypted.yaml
- tests/installation/partitioning/edit_proposal_encrypt.pm
- Related ticket: https://progress.opensuse.org/issues/80216
- Verification run: http://falafel.suse.cz/tests/1020
> Adjust test home_encrypted for UI changes

- lib/YuiRestClient/App.pm
- lib/YuiRestClient/Widget/CheckBox.pm
The PR adds suport for Libyui CheckBox Widget.
> Add basic support for checkbox yui widget

- lib/Mitigation.pm
Enhance function for getting output from guest
- Needles: N/A
- Verification run: http://openqa.qa2.suse.asia/tests/26220
> Enhance function for getting output from guest

- lib/utils.pm
- Follow-up:
#11153
https://progress.opensuse.org/issues/65992
- Fail:
https://openqa.suse.de/tests/5156025#step/gdb/3
- Verification run:  https://openqa.suse.de/tests/5156876
> Add exit code 8 to released update workaround

- tests/publiccloud/boottime.pm
VR : https://openqa.suse.de/tests/5160613
> boottime: make sure that we work with single line

- lib/transactional.pm
- Related ticket: [poo#80638](https://progress.opensuse.org/issues/80638)
- Verification run: [health_check](https://openqa.suse.de/tests/overview?arch=&machine=&modules=health_check&distri=sle&version=15-SP3&build=100.1&groupid=96#)
> Increase timeout for grub in transactional scenario

- tests/x11/firefox/firefox_extensions.pm
see https://progress.opensuse.org/issues/78191
100 without failure:
https://openqa.suse.de/tests/5164446#next_previous
> Use and repeat assert_and_click_until_screen_change

- data/console/test_java.sh
- schedule/functional/extra_tests_transactional_server.yaml
- tests/console/java.pm
add test_java_transactional-server.sh for transactional server.
see https://progress.opensuse.org/issues/72208
verifications:
http://10.162.23.47/tests/8567#step/java/35 (transactional server)
http://10.162.23.47/tests/8568#step/java/24 (extra_test_testmode sles)
http://10.162.23.47/tests/8570#step/java/18 (extra_test_testmode tw)
http://10.162.23.47/tests/8569#step/java/21 (jeos)
> Schedule java test module on extra_tests_transactional_server

- data/console/test_java.sh
- Related ticket: #11388
- Verification run: https://openqa.suse.de/tests/5174941
> Add missing quote in bash script #11388

- .github/workflows/static.yml
See also https://github.com/os-autoinst/os-autoinst/pull/1601
> Update perltidy to 20201207

- lib/Installation/Partitioner/LibstorageNG/v4_3/ExpertPartitionerController.pm
- lib/Installation/Partitioner/LibstorageNG/v4_3/NewPartitionTypePage.pm
- schedule/yast/msdos.yaml
- tests/installation/partitioning/msdos_partition_table.pm
- Related ticket: https://progress.opensuse.org/issues/80206
VR: http://waaa-amazing.suse.cz/tests/13775#step/msdos_partition_table/42
> Adapt install on msdos partition table to UI changes

- CONTRIBUTING.md
* CONTRIBUTING.md: Add rule for comments in source code
* CONTRIBUTING.md: Phrase "Tumbleweed first" more strongly
> CONTRIBUTING.md: Add rule for comments in source code + Clarify Tumbleweed as primary product

- lib/services/hpcpackage_remain.pm
Before checking, the release number needs to be stripped off of
the package name according bsc#1179303
Refer jira feature:  https://jira.suse.com/browse/SLE-8608
- Related ticket: https://progress.opensuse.org/issues/80588
- Verification run: https://openqa.suse.de/tests/5188020
> Stripped off the release number from pkg name before checking

- tests/installation/partitioning_specific_disk.pm
Fix partitioning specific disk,increase loop 
- Needles: N/A
- Verification run:  http://10.67.129.4/tests/25875
> Fix partitioning specific disk

- tests/boot/boot_to_desktop.pm
For bsc#1180313, can't stop wicked during reboot make system need more time to wait bootloader, so add 60s wait time to workaround this issue.
- Related ticket: https://progress.opensuse.org/issues/81176
- Needles: N/A
- Verification run: http://openqa.nue.suse.com/tests/5218017#
> Wait more time for bootloader on ppc64le, workaround bsc#1180313

- schedule/migration/multimachine_samba_upgrade.yaml
Add samba migration mutimachine test
- Related ticket: https://progress.opensuse.org/issues/81292
> Add samba migration mutimachine test

- tests/virt_autotest/reboot_and_wait_up.pm
* **[bsc#1156315](https://bugzilla.suse.com/show_bug.cgi?id=1156315)** leads to difficulty of asserting pattern in non-still serial console. This happens to online host upgrade from sles15sp2 to sles15sp3.
* **This** issue can be mitigated temporarily by rebooting the host directly by using ipmitool for this scenario
* **Implementation** employs perl caller function to facilitate detecting whether host upgrade is being performed in reboot_and_wait_up module which can also be used in some other scenarios
* **With** this implementation virtualization host upgrade test from 15sp2 to 15sp3 can be executed as normal
* **Related ticket:** [prj2_host_upgrade_sles15sp2_to_developing_kvm](https://openqa.suse.de/tests/5149073#step/reboot_and_wait_up_upgrade/1)
* **Needles:** n/a
* **Verification …
> Skip serial console pattern asserting for specific online host upgrade

- schedule/yast/dud_development_tools.yaml
- Related failure: https://openqa.suse.de/tests/5241883#step/validate_dud_addon_repos/14
> Add system_prepare to dud scenario schedule

- tests/console/zfs.pm
Add handling for `.zfs/snapshot` directory to zfs test
- Related ticket: https://progress.opensuse.org/issues/81266 and https://progress.opensuse.org/issues/70981
- Needles: -
- Verification run: http://phoenix-openqa.qam.suse.de/t4389
Two commits, because there were two distinct features to be implemented.
> Improve zfs test

- lib/containers/container_images.pm
Apply feedback from https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/11691#discussion_r552483085
In addition, add regex to match Version differences when the report does not
provide any update.
- Related ticket: https://progress.opensuse.org/issues/71050
- [no updates](http://aquarius.suse.cz/tests/4343#details)
- [with updates](http://aquarius.suse.cz/tests/4342)
> Add regex for non-update rpm and replace assert with die command

- lib/utils.pm
Need wait the system has login to the root console
- Related ticket: https://progress.opensuse.org/issues/76891
http://openqa.suse.de/t5232795
http://openqa.suse.de/t5232796
http://openqa.suse.de/t5232797
http://openqa.suse.de/t5232798
> Need wait the system has login to the root console

- tests/installation/add_update_test_repo.pm
- Fail: https://openqa.suse.de/tests/5249691
https://openqa.suse.de/tests/5252044 aarch64
http://dzedro.suse.cz/tests/17156 x86_64
https://openqa.suse.de/tests/5252848 15-sp2 x86_64
https://openqa.suse.de/tests/5252849 15-sp2 s390x
https://openqa.suse.de/tests/5252850 15-sp2 aarch64
https://openqa.suse.de/tests/5252851 12-sp5 aarch64
https://openqa.suse.de/tests/5253008 15-sp1 aarch64
https://openqa.suse.de/tests/5253011 15-sp2 aarch64
> Fix QEM workaround for released update

- lib/console/ovs_utils.pm
- products/opensuse/main.pm
- products/sle/main.pm
- tests/console/ovs_client.pm
- tests/console/ovs_server.pm
Test IPsec tunneling with openvswitch
- Related ticket: https://progress.opensuse.org/issues/69055
- Needles: N/A
- Verification runs : 
Tumbleweed [ovs-client](http://10.163.41.158/tests/688) | [ovs-server](http://10.163.41.158/tests/687)
SLE15-SP2 [ovs-client](http://10.163.41.158/tests/670) | [ovs-server](http://10.163.41.158/tests/689)
> Test IPsec tunneling with openvswitch

- lib/registration.pm
Workaround expired repo key on sle15 during upgrade process.
This issue is tracked with a softfail for [bsc#1180619](https://bugzilla.suse.com/show_bug.cgi?id=1180619).
- Needles: https://gitlab.suse.de/openqa/os-autoinst-needles-sles/-/merge_requests/1474
- Verification run: http://1b210.qa.suse.de/tests/8224
- Regression test: http://1b210.qa.suse.de/tests/8226
> Workaround expired repo key on sle15 in upgrade

- lib/Installation/Partitioner/LibstorageNG/v4_3/AddLogicalVolumePage.pm
- lib/Installation/Partitioner/LibstorageNG/v4_3/ConfirmationWarning.pm
- lib/Installation/Partitioner/LibstorageNG/v4_3/ConfirmationWarningController.pm
- lib/Installation/Partitioner/LibstorageNG/v4_3/ExpertPartitionerController.pm
- lib/Installation/Partitioner/LibstorageNG/v4_3/ExpertPartitionerPage.pm
- lib/Installation/Partitioner/LibstorageNG/v4_3/SummaryPage.pm
- lib/YuiRestClient.pm
- lib/y2_module_guitest.pm
- schedule/yast/yast2_gui/yast2_gui_sle.yaml
- tests/console/setup_libyui_running_system.pm
- tests/yast2_gui/yast2_expert_partitioner.pm
- variables.md
Setup libyui REST API in running system for x86_64 and implement steps in scenario yast2_storage_ng in new test yast2_expert_partitioner.
- Related ticket: [poo#80840](https://progress.opensuse.org/issues/80840)
- Verification run: [yast2_gui](https://openqa.suse.de/tests/5267384)
> Setup libyui REST API in running system

- lib/main_common.pm
- tests/console/check_package_version.pm
This PR checks the version of package postgresql, mariadb and
python3, to see whether they are the expected version on SLES15SP3.
- Related ticket: https://progress.opensuse.org/issues/77797
http://openqa.suse.de/tests/5270810#step/check_package_version/1
http://openqa.suse.de/tests/5270812#step/check_package_version/1
http://openqa.suse.de/tests/5270813#step/check_package_version/1
http://openqa.suse.de/tests/5270814#step/check_package_version/1
> Check some packages version for SLES15SP3

- lib/publiccloud/ssh_interactive_init.pm
- lib/publiccloud/utils.pm
- tests/publiccloud/instance_overview.pm
- tests/publiccloud/ssh_interactive_end.pm
This reverts commit 2a6ef35562962087b443762911f164dfa1050c1c.
> Revert "Move code into the cleanup subroutine to reduce duplication"

- lib/services/hpcpackage_remain.pm
In hpc package_remain check we'll install nearly 400+ packages.
It will result in 400+ new snapshots. these snapshots will make
the snapper rollback package easily timeout. We need delete them
once the package was installed.
- Related ticket: https://progress.opensuse.org/issues/80878
- Needles: N/A
https://openqa.nue.suse.com/tests/5265495
https://openqa.nue.suse.com/tests/5265496
https://openqa.nue.suse.com/tests/5271079
https://openqa.nue.suse.com/tests/5270912
> Delete snapshots during HPC package remain check

- tests/x11/gnome_music.pm
see https://progress.opensuse.org/issues/81316
verification test:
http://10.162.23.47/tests/8702#step/gnome_music
> Work around sporadic issue with send_key

- tests/console/python_scientific.pm
- Related ticket: https://progress.opensuse.org/issues/81376
http://dzedro.suse.cz/tests/17260 TW
http://dzedro.suse.cz/tests/17258 15
http://dzedro.suse.cz/tests/17259 15-SP1
https://openqa.suse.de/tests/5289498 15 s390x
https://openqa.suse.de/tests/5288302 https://openqa.suse.de/tests/5289500 15 aarch64
> Install and run python3-scipy on 15-SP1 and newer

- tests/sles4sap/robot_fw.pm
- Fail: https://openqa.suse.de/tests/5288848
https://openqa.suse.de/tests/5291023 12-SP5
http://dzedro.suse.cz/tests/17261 15-SP2
> sles4sap/robot_fw: Create test_repo dir

- lib/opensusebasetest.pm
Related to https://progress.opensuse.org/issues/87797
- Verification run: https://openqa.opensuse.org/t1589768
> log: Also upload /etc/resolv.conf

- lib/virt_autotest/virtual_network_utils.pm
- lib/virt_feature_test_base.pm
- tests/virt_autotest/libvirt_virtual_network_init.pm
- **Description:**
Refer to https://149.44.176.58/tests/5212246, figure out fail at the detached active pool size (57GiB) with the current used pool size 60 GiB on sles15sp3 KVM host.
Should be define a expected pool size both on KVM - 40 GiB and XEN 60 GiB.
- **Related ticket:** 
https://progress.opensuse.org/issues/81679
- **Verification run:** 
[gi-guest_developing-on-host_developing-kvm](http://149.44.176.58/tests/5231528)
[gi-guest_developing-on-host_developing-xen](http://149.44.176.58/tests/5231529)
> [virt_autotest] Add expected_pool_size for virt_autotest

- schedule/yast/multipath.yaml
https://progress.opensuse.org/issues/87710
http://kazhua.qa.suse.de/tests/182
http://kazhua.qa.suse.de/tests/183
> Install: Schedule multipath before scc-registration

- tests/sles4sap/wizard_hana_install.pm
Fix SAP wizard test with sap-installation-wizard package above version 4.3.
- Needles: N/A (new ones have been already created in o.s.d.)
- Verification run: http://1b210.qa.suse.de/tests/8256 (the failure is because of [bsc#1181120](https://bugzilla.suse.com/show_bug.cgi?id=1181120))
- Regression run: http://1b210.qa.suse.de/tests/8279 (the test is in fact on 15-SP1, the name 15-SP2 is only because I did a clone of an existing test with a version change)
> Fix SAP wizard test

- tests/console/java.pm
Modify part of the code in order to run in SLE15-SP3 
- Related ticket: https://progress.opensuse.org/issues/87766
- Needles: N/A
- Verification run:  [SLES 15-SP3-extra_tests_textmode](http://10.161.229.247/tests/1666#step/java/33) | [SLES 15-SP3-extra_tests_transactional_server](https://openqa.suse.de/tests/5319706#step/java/51) | [JeOS 15-SP3](https://openqa.suse.de/tests/5319005#step/java/27) | [SLES 15-SP2 ](http://10.161.229.247/tests/1667#step/java/18) | [Tumbleweed-extra_tests_textmode](https://openqa.opensuse.org/tests/1594874#step/java/18) | [Tumbleweed-extra_tests_transactional_server](https://openqa.opensuse.org/tests/1594936#step/java/46)
> Fix java test for SLE 15-SP3

- tests/console/zfs.pm
On Leap 15.3 the filesystem test fails, because there is no repository
available. Because zfs comes from an external repo, we make this
a softfailure.
- Related issue: https://progress.opensuse.org/issues/81266
- Verification run: [Leap 15.3](http://duck-norris.qam.suse.de/tests/4557) | [Tumbleweed](http://duck-norris.qam.suse.de/tests/4558)
> Raise softfailure when zfs repo is not available

- CONTRIBUTING.md
There was some missing information on how to get started with a fresh server installation, these one liners should cover most cases
> Add info on how to get started with this particular repository

- tests/ha/rear_backup.pm
Add a workaround for [bsc#1180946](https://bugzilla.suse.com/show_bug.cgi?id=1180946) on ReaR test.
- Needles: N/A
- Failing test: https://openqa.suse.de/tests/5317414#step/rear_backup/15
- Verification run: http://1b210.qa.suse.de/tests/8280
> Add workaround for ReaR test

- tests/publiccloud/run_ltp.pm
Before this patch we were using internal IBS repo to install LTP.
This was complicating install flow because IBS is not reachable
from Public Cloud VM, so we were downloading rpm to openQA VM and
than uploading it to the cloud.
Main reason for this was that there was no LTP repo in OBS. Now when
we have one we can simplify the flow.
> publiccloud: install LTP from OBS

- test_data/yast/autoyast_reinstall/autoyast_reinstall_64bit.yaml
- test_data/yast/autoyast_reinstall/autoyast_reinstall_aarch64.yaml
- test_data/yast/autoyast_reinstall/autoyast_reinstall_ppc64le-hmc.yaml
- test_data/yast/autoyast_reinstall/autoyast_reinstall_ppc64le.yaml
- test_data/yast/autoyast_reinstall/autoyast_reinstall_s390x.yaml
- Related ticket: https://progress.opensuse.org/issues/69256
- Verification run: https://openqa.suse.de/tests/overview?distri=sle&version=15-SP3&build=_ssyrianidou_2&groupid=96
> Add test_data to validate registration in cloned profile

- data/autoyast_qam/12_installtest.xml.ep
- data/autoyast_qam/15_installtest.xml.ep
- lib/autoyast.pm
- Verification run: https://openqa.suse.de/tests/overview?distri=sle&version=15-SP1&build=15sp1&groupid=293
> QEM installtest profiles & 15-SP1 becoming LTSS

- tests/console/verify_firewall_services.pm
VR: http://falafel.suse.cz/tests/1162
> Fix syntax for console/verify_firewall_services

- tests/publiccloud/run_ltp.pm
Before this patch we were trying to install LTP before registering
This make some dependecies unresolvable.
Current patch change the order - first register the system than try to install LTP
> publiccloud: register image before install LTP

- tests/remote/remote_target.pm
Verification run: https://openqa.opensuse.org/tests/1607433
> remote_target: Remove workaround, bug got fixed

- tests/microos/networking.pm
- Related ticket: Could help to debug https://progress.opensuse.org/issues/87797
- Verification run: https://openqa.opensuse.org/t1607268
> microos: also show ip and dns config in networking test

- schedule/functional/minimal+proxy_SCC-postreg_SUSEconnect.yaml
- schedule/yast/skip_registration/offline_install+skip_registration.yaml
- test_data/yast/skip_registration/default_repos.yaml
See [poo#88045](https://progress.opensuse.org/issues/88045)
Verification: [minimal+proxy_SCC-postreg_SUSEconnect](https://openqa.suse.de/tests/overview?version=15-SP3&distri=sle&build=jknphy%2Fos-autoinst-distri-opensuse%23validation_skip_registration)
> Add validation to skip_registration

- tests/console/autofs.pm
- tests/console/btrfs_qgroups.pm
- tests/console/btrfs_send_receive.pm
- tests/console/coredump_collect.pm
- tests/console/lsof.pm
- tests/console/lvm.pm
- tests/console/snapper_cleanup.pm
- tests/console/snapper_create.pm
- tests/console/snapper_used_space.pm
- tests/console/udisks2.pm
https://openqa.suse.de/tests/5391179 12-SP5 x86_64
https://openqa.suse.de/tests/5391180 12-SP5 aarch64
https://openqa.suse.de/tests/5390859 15-SP2 x86_64
https://openqa.suse.de/tests/5390860 15-SP2 aarch64
https://openqa.suse.de/tests/5390862 15-SP3 x86_64
https://openqa.suse.de/tests/5390862 15-SP3 ppc64le
https://openqa.opensuse.org/tests/1612345 TW jeos
https://openqa.opensuse.org/tests/1612344 TW x86_64
https://openqa.opensuse.org/tests/1612404 TW ppc64le
https://openqa.opensuse.org/tests/1612373 TW aarch64 failures https://openqa.opensuse.org/tests/1609548
> Enable virtio/serial console on console filesystem tests

- data/ai_ml/filelist.txt
- data/ai_ml/tvm/post_processing.py
- schedule/ai_ml.yaml
- tests/ai_ml/tvm.pm
* x86_64: https://openqa.opensuse.org/t1613737
* aarch64: https://openqa.opensuse.org/t1613942
> ai_ml: Add TVM

- schedule/containers/extra_tests_textmode_containers.yaml
- schedule/containers/sle_image_on_centos.yaml
- schedule/containers/sle_image_on_sle_host.yaml
- schedule/containers/sle_image_on_ubuntu.yaml
This reverts commit f24164a319af6e69978ee9f18880b5734d614db8.
Changes breaks TW
> Revert "Remove unnecessary modules from container group"

- products/opensuse/main.pm
- schedule/functional/wireguard.yaml
- tests/network/wireguard.pm
Ticket: https://jira.suse.com/browse/SLE-14409
Verification (only scheduling): http://kazhua.qa.suse.de/tests/191/file/autoinst-log.txt
> Allow wireguard to work for SLE as well

- schedule/sles4sap/hana/test_hana.yaml
We have found a bug with the version `SPS04rev46_0`, we need to revert to `SPS03rev3`.
- Needles: N/A
> Fix HANA version

- lib/ssh_crypto_policy.pm
- tests/console/sshd.pm
- Related ticket: https://progress.opensuse.org/issues/80716
- Needles: No Needles
- Verification run: x86_64: [sle-15-SP3](http://angmar.suse.de/tests/3042#step/sshd/1) | [sle-15-SP2](http://angmar.suse.de/tests/3034#step/sshd/375) | [sle-15-SP1](http://angmar.suse.de/tests/3035#step/sshd/374) | [sle-15](http://angmar.suse.de/tests/3036#step/sshd/374) | [sle-12-SP5](http://angmar.suse.de/tests/3037#step/sshd/394) | [sle-12-SP4](http://angmar.suse.de/tests/3038#step/sshd/394) | [sle-12-SP3](http://angmar.suse.de/tests/3039#step/sshd/394) | [sle-12-SP2](http://angmar.suse.de/tests/3040/sshd/1) | [tumbleweed](http://angmar.suse.de/tests/3041#step/sshd/375)
s390x: [sle-15-SP2](https://openqa.suse.de/tests/5418959#step/sshd/375) | [sle-12-SP5](https://openqa.suse.de/tests/5420464/#step/sshd/1) …
> Test all available openssh cryptographic policies

- lib/containers/container_images.pm
Just an email change for the sake of consistency
> Change .de email to .com

- declarative-schedule-doc.md
- lib/scheduler.pm
- t/02_yaml_schedule.t
- t/data/test_data_vars_expansion.yaml
See [poo#88059](https://progress.opensuse.org/issues/88059)
> Implement vars.json expansion in test data

- tests/network/wireguard.pm
Ticket: https://jira.suse.com/browse/SLE-14409
Verification: http://kazhua.qa.suse.de/tests/208 (unrelated fail due to only one node being executed)
> Fix wireguard test for sle

- tests/virtualization/universal/patch_guests.pm
In our VMware & Hyper-V guest smoke test scenario, we use static guests.
Those guests are running in our network and we connect to them via SSH.
Few months ago, we were running also install test, which installed a VM
and this VM was used to execute our SSH commands from - nothing else.
Now, we use a support server, so we don't need to install anything, we
just load the support server and execute our SSH commands from that.
As the version of support server does not change, we should not check it.
We check for it in XEN & KVM scenarios, where we install a physical
hypervizor with several different guests, but we patch the hypervizor and
only the guests running the same version - not other guests.
- Verification run: [SLE15-SP2 VMware](http://pdostal-server.suse.cz/tests/11103)
> Fix the support server scenario

- schedule/jeos/sle/kvm/jeos-ltp.yaml
- Related ticket: https://gitlab.suse.de/qac/qac-openqa-yaml/-/merge_requests/111
> Aarch64 kvm testing

- tests/console/libssh.pm
- Related ticket: https://bugzilla.suse.com/show_bug.cgi?id=1181835
- Verification run: http://dzedro.suse.cz/tests/17459
> libssh: Add contm on LTSS products

- schedule/ha/bv/ha_cluster_node.yaml
- schedule/ha/bv/ha_supportserver.yaml
We need to disable QEMU snapshots in MM HA tests.
- Needles: N/A
> Add QEMU_DISABLE_SNAPSHOTS=1 in HA yaml schedules

- tests/console/apache.pm
- tests/console/iotop.pm
- Fail:
https://openqa.suse.de/tests/5468512#step/iotop/17 iotop
https://openqa.suse.de/tests/5453116#step/apache/155 apache2
http://dzedro.suse.cz/tests/17485 iotop
http://dzedro.suse.cz/tests/17480 apache2
> Make iotop and apche2 more robust to avoid failures

- tests/publiccloud/register_system.pm
It is necessary to add LTSS addon to our SUT and this add-on needs a registration code.
- Verification run: [15-SP1](http://pdostal-server.suse.cz/tests/11117#step/register_system/27) [12-SP4](http://pdostal-server.suse.cz/tests/11118#step/register_system/45)
> Public Cloud: Register LTSS addon properly

- lib/cfg_files_utils.pm
- schedule/yast/textmode/textmode.yaml
- schedule/yast/textmode/textmode@svirt-xen.yaml
- test_data/yast/installation/network_config.yaml
- test_data/yast/installation/network_config_s390x.yaml
- test_data/yast/installation/network_config_s390x_svirt.yaml
- test_data/yast/yast2_ncurses/textmode.yaml
- test_data/yast/yast2_ncurses/textmode_lzo.yaml
- test_data/yast/yast2_ncurses/textmode_lzo_fadump.yaml
- tests/console/verify_config_files.pm
- tests/console/verify_network.pm
- tests/console/yast2_kdump.pm
See [poo#88313](https://progress.opensuse.org/issues/88313)
[Verification run](https://openqa.suse.de/tests/overview?build=jknphy%2Fos-autoinst-distri-opensuse%23validate_network_configuration&distri=sle&version=15-SP3)
> Validate network configuration after installation

- tests/console/iotop.pm
- Related ticket: #11960
https://openqa.suse.de/tests/5474685
https://openqa.suse.de/tests/5474686
https://openqa.suse.de/tests/5474687
> Increase dd count to not miss the io output

- data/autoyast_xen/sles15HVM_PRG.xml
- data/autoyast_xen/sles15PV_PRG.xml
- data/autoyast_xen/sles15sp2HVM_PRG.xml
- data/autoyast_xen/sles15sp2PV_PRG.xml
- lib/virt_autotest/common.pm
- Verification run: [KVM](http://pdostal-server.suse.cz/tests/11054) [XEN](http://openqa.qam.suse.cz/tests/17506)
> Virtualization: Repair installation URL and accept unsigned repositories

- tests/installation/welcome.pm
- tests/qam-minimal/install_update.pm
- Fail:
https://openqa.suse.de/tests/5487277#step/welcome/19
https://openqa.suse.de/tests/5487121#step/welcome/16
https://openqa.suse.de/tests/5487275
https://openqa.suse.de/tests/5487881
https://openqa.suse.de/tests/5487882
> Increase boot timeouts on aarch64

- tests/console/libvorbis.pm
- Related ticket: #11950
- Verification run: https://openqa.suse.de/tests/5487883
> libvorbis: Add Desktop applications module if not Maintenance

- tests/network/wireguard.pm
Ticket: https://progress.opensuse.org/issues/88511
Verification: n/p
> wireguard: Protect creation of barriers using mutex

- schedule/qam/15-SP2/powerpc-utils.yaml
- tests/console/powerpc_utils.pm
Add powerpc-utils for spvm.
see https://progress.opensuse.org/issues/49025
verification:
https://openqa.suse.de/tests/5494226#step/powerpc_utils
> Add regression test powerpc-utils

- data/autoyast_sle15/autoyast_sle-micro_50.xml
VR: http://fromm.arch.suse.de/tests/173
> SLE Micro: update autoyast profile including SELinux pattern

- lib/ssh_crypto_policy.pm
- Related ticket: No related ticket
- Verification run: [sle 12sp5](http://angmar.suse.de/tests/3065#step/sshd/289)
> Add reference to openssh bug bsc#1182601

- tests/console/rsync_client.pm
- tests/console/rsync_server.pm
- tests/network/autofs_client.pm
- tests/network/autofs_server.pm
- tests/network/salt_master.pm
- tests/network/salt_minion.pm
- tests/smt/smt_client1.pm
- tests/smt/smt_server.pm
- Related ticket: https://progress.opensuse.org/issues/55871 https://progress.opensuse.org/issues/80570
https://openqa.suse.de/tests/5505669 salt
https://openqa.suse.de/tests/5505668 rsync
https://openqa.suse.de/tests/5506856 smt
> Use mutex to make sure barrier is created before waiting for it

- tests/installation/add_update_test_repo.pm
in Incident bs I needed to use INCIDENT_REPO instead of MAINT_TEST_REPO
> Honor INCIDENT_REPO wheen adding repositories

- lib/containers/common.pm
- tests/containers/validate_btrfs.pm
Two commits for some small issues.
One cause by a recent commit
The other breaks from time to time and causes more trouble than its significant for the validate_btrfs
- Verification run: http://aquarius.suse.cz/tests/5010 
http://aquarius.suse.cz/tests/5009
> Fix minor container issues

- tests/installation/partitioning/modify_existing_partition.pm
Fix record info to avoid printing Hash like : https://openqa.suse.de/tests/5477024#step/modify_existing_partition/5
> Fix record_info in modify_existing_partition

- tests/console/journalctl.pm
There have been timeout and race condition issues identified after
update of `journalct.pm`.
1) [FSS key generation on sle15sp0 s390x takes longer than expected](https://openqa.suse.de/tests/5535775#step/journalctl/247)
2) [Race condition occurs](https://progress.opensuse.org/issues/87749#note-8) after feeding journald with test messages
> Relax journalctl.pm

- schedule/jeos/sle/jeos-extratest.yaml
> Test kdump_and_crash in JeOS aarch64 image for kvm

- schedule/functional/extra_tests_textmode.yaml
- tests/console/systemd_nspawn.pm
Ticket: https://progress.opensuse.org/issues/88714
Verification:
http://kazhua.qa.suse.de/tests/238
http://kazhua.qa.suse.de/tests/237
> Add systemd-nspawn test

- lib/services/hpcpackage_remain.pm
Remove debug information from check package list
- Related ticket: https://progress.opensuse.org/issues/89293
- Verification run: https://openqa.suse.de/tests/5571676#
> Remove debug information from check package list

- tests/wsl/firstrun.pm
- Verification run: http://kepler.suse.cz/tests/3750
> Upload non empty logs in wsl

- tests/console/systemd_nspawn.pm
Verification: http://kazhua.qa.suse.de/tests/243#step/systemd_nspawn/121
Ticket: https://progress.opensuse.org/issues/88714
> systemd_nspawn: fixes for pipefail

- schedule/jeos/sle/jeos-base+phub.yaml
- Related ticket: https://progress.opensuse.org/issues/89320
- https://bugzilla.suse.com/show_bug.cgi?id=1180120
> Disable sssd test case from JeOS

- tests/console/systemd_nspawn.pm
Verification: http://kazhua.qa.suse.de/tests/278#step/systemd_nspawn/113
Ticket: https://progress.opensuse.org/issues/88714
> systemd_nspawn: Increase test stability

- tests/kiwi_images_test/validate_build.pm
Fix missing whitespace in download command.
Verification run at http://10.161.229.209/tests/216
> Fix broken download link

- tests/jeos/build_key.pm
- Related ticket: https://progress.opensuse.org/issues/89611
- Verification run: https://openqa.opensuse.org/t1661344
> Make sure to select a console

- tests/console/journalctl.pm
Fix journalctl for 15-SP3 JeOS runs on openSUSE Leap.
- Related ticket: https://progress.opensuse.org/issues/89563
* * [JeOS SLES 15-SP3](http://duck-norris.qam.suse.de/tests/5380)
* * [SLES 12-SP2](http://duck-norris.qam.suse.de/tests/5391) | [SLES 12-SP3](http://duck-norris.qam.suse.de/tests/5392) | [SLES 12-SP4](http://duck-norris.qam.suse.de/tests/5393) | [SLES12-SP5](http://duck-norris.qam.suse.de/tests/5394) | [SLE15](http://duck-norris.qam.suse.de/tests/5395) | [SLE15-SP1](http://duck-norris.qam.suse.de/tests/5396) | [SLE15-SP2](http://duck-norris.qam.suse.de/tests/5397)
* * [SLES 15-SP2 s390x](https://openqa.suse.de/t5621142)
* * [SLES 15-SP2 aarch64](https://openqa.suse.de/t5621143)
* * [Tumbleweed](https://openqa.opensuse.org/t1661345) | [Tumbleweed …
> Fixes for JeOS

- schedule/functional/extra_tests_textmode.yaml
- tests/console/nftables.pm
see  https://progress.opensuse.org/issues/88723
and https://jira.suse.com/browse/SLE-16460
schedule this module in extra_test_texmode for sles 15
verification:
http://openqa.suse.de/tests/5642240#step/nftables/55615
> Add nftables test module to test it's support on sles 15

- test_data/yast/autoyast/profiles/reinstall_ppc64le-hmc.yaml
Fix failure in https://openqa.suse.de/tests/5646459#step/verify_cloned_profile/7
> Fix typo in autoyast_reinstall test_data

- tests/console/ncurses.pm
- Related bug: http://bugzilla.opensuse.org/show_bug.cgi?id=1183234
> Upload files useful to help to debug boo#1183234

- tests/jeos/prepare_firstboot.pm
WIP because the change isn't in a released snapshot yet.
> prepare_firstboot: Adjust path for TW as well now

- lib/containers/common.pm
1. Remove creation of /etc/docker folder because actually we would like to fail in such cases
2. Make more clear error message in case unexpected runtime selected
3. Use handy function instead of direct call for sed
> containers: minor improvements to allow_selected_insecure_registries

- lib/main_common.pm
- tests/console/install_rt_kernel.pm
- Related ticket: https://progress.opensuse.org/issues/80110
- Verification run: http://dzedro.suse.cz/tests/17873#step/install_rt_kernel/16
> Install RT kernel on product SLERT

- tests/publiccloud/sles4sap.pm
- `fence_gce` should use method `cycle` on GCE (workaround)
- fix DRBD workaround on GCE
- use 'run_cmd' by default
- remove fixed [bsc#1179782](https://bugzilla.suse.com/show_bug.cgi?id=1179782)
- Needles: N/A
- Verification runs: [GCP](http://1b210.qa.suse.de/tests/8712), [Azure](http://1b210.qa.suse.de/tests/8714), [AWS](http://1b210.qa.suse.de/tests/8713)
> Improve SLES4SAP tests on Public Cloud

- test_data/yast/autoyast_reinstall/autoyast_reinstall_64bit_leap.yaml
Related ticket: [bsc#1183522](https://bugzilla.suse.com/show_bug.cgi?id=1183522)
Verification run: https://openqa.opensuse.org/tests/1668441#step/verify_cloned_profile/6
> Point to right yaml validating ay profile for reinstall

- schedule/containers/sle_base_image_updates.yaml
Switch from `main_common.pm` to YAML scheduler.
- Verification run: [SLE12-SP2](http://pdostal-server.suse.cz/tests/11224#details)
> Create dedicated YAML schedule for SLE base image updates

- tests/qa_automation/qa_run.pm
- Related ticket: https://progress.opensuse.org/issues/89966
- Verification runs: [mau-qa_userspace_systemd in 15-SP2](http://angmar.suse.de/tests/3175) | [qa_kernel_multipath in 15-SP3](http://angmar.suse.de/tests/3174)
> Skip systemd workarounds in other testsuites

- schedule/sle-micro/remote_ssh_controller.yaml
- schedule/sle-micro/remote_ssh_target.yaml
- tests/installation/welcome.pm
- Related ticket: https://progress.opensuse.org/issues/89740
- Needles: [sles](https://gitlab.suse.de/openqa/os-autoinst-needles-sles/-/merge_requests/1513) [opensuse](https://github.com/os-autoinst/os-autoinst-needles-opensuse/pull/715)
- VR:  [controller](http://fromm.arch.suse.de/tests/483)   [target](http://fromm.arch.suse.de/tests/484)
> SLE Micro: SSH installation test for DVD flavor

- tests/console/journalctl.pm
Validate whether log rotation has been successful, fix minor typo and
upload complete content of journald log directory.
* [sle-15-SP3-JeOS-for-VMware-x86_64-Build24.50-jeos-extratest@svirt-vmware65](http://kepler.suse.cz/tests/4037#step/journalctl/200)
*  [tw](http://kepler.suse.cz/tests/4038#step/journalctl/373)
* [leap15.3](http://kepler.suse.cz/tests/4032#step/journalctl/355)
> Check rotation of journal logs

- lib/x11test.pm
- tests/x11/libreoffice/libreoffice_default_theme.pm
- tests/x11/libreoffice/libreoffice_double_click_file.pm
- tests/x11/libreoffice/libreoffice_open_specified_file.pm
- tests/x11/libreoffice/libreoffice_pyuno_bridge_no_evolution_dep.pm
- Related ticket: https://progress.opensuse.org/issues/90158
https://openqa.suse.de/tests/5687991 15-SP2
https://openqa.suse.de/tests/5687990 15-SP3 wayland
https://openqa.suse.de/tests/5687989 15-SP3 x11
https://openqa.opensuse.org/tests/1670668 TW wayland
https://openqa.opensuse.org/tests/1670703 TW x11
> Fix TableSample change in libreoffice macro

- tests/console/journalctl.pm
Reverts os-autoinst/os-autoinst-distri-opensuse#12141
To fix some journalctl test failures. More info in the original PR comments
> Revert "Check rotation of journal logs"

- lib/Distribution/Opensuse/Tumbleweed.pm
- lib/Installation/SystemRole/SystemRoleController.pm
- lib/Installation/SystemRole/SystemRolePage.pm
- lib/YuiRestClient/App.pm
- lib/YuiRestClient/Widget/Base.pm
- lib/YuiRestClient/Widget/ItemSelector.pm
- lib/scheduler.pm
- schedule/yast/addon-module-ftp.yaml
- schedule/yast/installer_extended.yaml
- schedule/yast/lvm/lvm_thin_provisioning.yaml
- schedule/yast/lvm/lvm_thin_provisioning_opensuse.yaml
- schedule/yast/lvm_raid1/lvm+raid1_opensuse.yaml
- schedule/yast/textmode/textmode.yaml
- schedule/yast/textmode/textmode@svirt-xen.yaml
- schedule/yast/transactional_server/create_hdd_transactional_server.yaml
- schedule/yast/transactional_server/create_hdd_transactional_server_opensuse.yaml
- tests/installation/system_role/select_role.pm
- tests/installation/system_role/validate_default_role.pm
See [poo#37504](https://progress.opensuse.org/issues/37504)
Verification run: [OSD](https://openqa.suse.de/tests/overview?distri=sle&version=15-SP3&build=jknphy%2Fos-autoinst-distri-opensuse%23assert_expected_default_roles) | [O3](https://openqa.opensuse.org/tests/overview?build=jknphy%2Fos-autoinst-distri-opensuse%23assert_expected_default_roles&distri=opensuse&version=Tumbleweed)
> Assert default roles during installation with REST API

- lib/qam.pm
https://openqa.suse.de/tests/5690302
> Accept untrusted GnuPG keys for Maintanece Requests jobs

- lib/qam.pm
- products/sle/main.pm
- tests/qam-updinstall/update_install_mr.pm
MR in smelt doesn't provide info about package binaries, so
reuse old variant of update install test
> Update install test for Maintenance Requests

- tests/qa_automation/qa_run.pm
Reverts os-autoinst/os-autoinst-distri-opensuse#12165
VR: https://openqa.suse.de/tests/5697008#
> Revert "Revert "Skip systemd workarounds in other testsuites""

- schedule/jeos/sle/jeos-container-engines_and_tools.yaml
- Verification run: http://kepler.suse.cz/tests/4057
> Extend container testing on top of JeOS

- tests/console/clamav.pm
- Related ticket: https://progress.opensuse.org/issues/89401
https://openqa.opensuse.org/tests/1677965#step/clamav/27 TW x86_64
https://openqa.opensuse.org/tests/1677966#step/clamav/27 TW JeOS x86_64
https://openqa.opensuse.org/tests/1677967#step/clamav/27 TW aarch64
https://openqa.opensuse.org/tests/1677969#step/clamav/27 TW JeOS aarch32
https://openqa.opensuse.org/tests/1677970#step/clamav/27 TW JeOS aarch64
https://openqa.opensuse.org/tests/1678013#step/clamav/27 15.3 JeOS x86_64
https://openqa.suse.de/tests/5714242#step/clamav/27 SLE 15 SP2 x86_64
https://openqa.suse.de/tests/5714325#step/clamav/27 SLE 15 SP2 s390x
https://openqa.suse.de/tests/5714801#step/clamav/27 SLE 15 SP2 aarch64
https://openqa.suse.de/tests/5713808#step/clamav/27 SLE 12 SP5 x86_64 …
> clamav: First update db from local mirror

- lib/repo_tools.pm
- Related ticket: https://progress.opensuse.org/issues/55784
https://openqa.suse.de/tests/5714219 15 SP2
https://openqa.suse.de/tests/5714103 15 SP1
https://openqa.suse.de/tests/5713952 15 GA
> rmt_feature: Fix failure due to incomplete credentials

- lib/kdump_utils.pm
#12019
http://dzedro.suse.cz/tests/18015
http://dzedro.suse.cz/tests/18016
> Use INCIDENT_REPO if defined instead MAINT_TEST_REPO

- tests/fips/openssh/openssh_fips.pm
**Description:**
OpenSSH 8.3 update will be upgraded to the new version in SLE15 SP3. This PR is going to add the OpenSSH update check to 8.3+ and add the version check and record_info for OpenSSH.
- Related ticket: https://progress.opensuse.org/issues/90458
- Needles: NA
- Verification run: https://openqa.suse.de/tests/5696585#step/openssh_fips/6
> Add the openSSH update check to 8.3+

- lib/Distribution/Opensuse/Tumbleweed.pm
- lib/Installation/Partitioner/LibstorageNG/v4_3/FilesystemOptionsPage.pm
- lib/Installation/Partitioner/LibstorageNG/v4_3/GuidedSetupController.pm
- lib/Installation/Partitioner/LibstorageNG/v4_3/PartitioningSchemePage.pm
- lib/Installation/Partitioner/LibstorageNG/v4_3/SuggestedPartitioningController.pm
- lib/Installation/Partitioner/LibstorageNG/v4_3/SuggestedPartitioningPage.pm
- schedule/yast/btrfs/btrfs_opensuse.yaml
- schedule/yast/btrfs/btrfs_sle_libstorage-ng.yaml
- schedule/yast/btrfs/btrfs_sle_libstorage-ng_s390x_zvm.yaml
- schedule/yast/btrfs/btrfs_sle_libstorage_spvm.yaml
- schedule/yast/ext4/ext4@yast-s390x.yaml
- schedule/yast/ext4/ext4@yast-xen-hvm.yaml
- schedule/yast/ext4/ext4@yast.yaml
- schedule/yast/ext4/ext4@yast_spvm.yaml
- schedule/yast/ext4/ext4_opensuse.yaml
- schedule/yast/xfs/xfs.yaml
- schedule/yast/xfs/xfs_opensuse.yaml
- tests/installation/partitioning/accept_proposed_layout.pm
- tests/installation/partitioning/guided_setup.pm
- tests/installation/partitioning/select_guided_setup.pm
- Related ticket [poo#87919](https://progress.opensuse.org/issues/87919)
- Job Group [mr#345](https://gitlab.suse.de/qsf-y/qa-sle-functional-y/-/merge_requests/345)
- Verification run [openSUSE](https://openqa.opensuse.org/tests/overview?version=Tumbleweed&build=jknphy%2Fos-autoinst-distri-opensuse%23guided_setup_rest_api&distri=opensuse) | [SLE](https://openqa.suse.de/tests/overview?distri=sle&version=15-SP3&build=jknphy%2Fos-autoinst-distri-opensuse%23guided_setup_rest_api) | [SAP-DVD-Updates](https://openqa.suse.de/tests/overview?build=jknphy%2Fos-autoinst-distri-opensuse%23guided_setup_rest_api&distri=sle&version=15)
Note: requires to setup YAML_SCHEDULE for openSUSE test suites.
> Implement partitioning guided with REST API

- tests/migration/version_switch_upgrade_target.pm
Need send ret key to handle login for KDE desktop
- ticket: https://progress.opensuse.org/issues/88467
- Verification run: https://openqa.suse.de/tests/5689699#step/first_boot/4
> Change desktop setting as 11sp4 KDE upgrade to 15SP3 gnome

- data/autoyast_qam/12_installtest.xml.ep
- tests/kernel/update_kernel.pm
https://progress.opensuse.org/issues/90522
fixed !12213 , new PR because @dzedro  is on holidays ..
> Add ericsson repo to LTP and install test

- tests/virt_autotest/sriov_network_card_pci_passthrough.pm
1. Enable pciback debug
2. Enable udev debug and print output
3. change test script for bsc#1183209 
- http://10.67.129.51/tests/2040(unplugging works)
> Debug SRIOV pciback for failed pv hot unplug

- tests/kernel/update_kernel.pm
SLE doesn't like self-signed certificates
> Use non https address for internal repo

- .github/workflows/ci.yml
> Force 'python3' for Inline::Python cpan module in CI

- lib/windowsbasetest.pm
- lib/wsl.pm
- tests/wsl/firstrun.pm
- tests/wsl/prepare_wsl_feature.pm
* [wsl2-main+register@64bit](http://kepler.suse.cz/tests/4268#step/firstrun/17)
* [wsl2-main+skip_reg@64bit](http://kepler.suse.cz/tests/4269)
* [wsl-main+register@uefi](http://kepler.suse.cz/tests/4271)
* [wsl-main+skip_reg@uefi](http://kepler.suse.cz/tests/4270)
> Small updates for WSL testing

- tests/microos/toolbox.pm
runuser is not a valid way to switch to a user cause it doesn't
provide a valid systemd session.
https://bugzilla.opensuse.org/show_bug.cgi?id=1184266
- Related ticket: https://progress.opensuse.org/issues/90605
> MicroOS: Change to user prompt instead of using "runuser"

- tests/x11/gnome_tweak_tool.pm
To handle the new behaviour currently seen in Staging:G
Needle already created
> GNOME 40: handle new extensions notification in GNOME Tweaks

- lib/x11test.pm
https://openqa.opensuse.org/tests/1695275#
Needles made
> xterm: handle GNOME40 behaviour

- tests/console/firewalld.pm
Ticket: https://progress.opensuse.org/issues/80966
Ticket: https://progress.opensuse.org/issues/89999
Verification TW: http://kazhua.qa.suse.de/tests/307
Verification SLE: http://kazhua.qa.suse.de/tests/308
> Add nft support - fix firewalld on TW (which will fix nftables as well)

- tests/console/firewalld.pm
As requested in https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/12270#pullrequestreview-633328930
Verification:
TW: http://kazhua.qa.suse.de/tests/309
SLE: http://kazhua.qa.suse.de/tests/310
> firewalld: Remove useless if statements

- tests/network/setup_multimachine.pm
Ticket: https://progress.opensuse.org/issues/89503
Verification: http://kazhua.qa.suse.de/tests/316#
> setup_multimachine: Autodetect NetworkManager vs wicked

- tests/x11/oomath.pm
* [sle-15-SP2-Desktop-DVD-Updates-x86_64-Build20210414-1-qam-gnome@64bit](https://openqa.suse.de/t5820173)
> oomath: Fix unintended string replace in bfeeb86cb

- tests/sles4sap/hana_install.pm
Try to workaround this rarely issue [1] by retrying the remove command.
The test will fail if the lock still exist.
[1] https://openqa.suse.de/tests/5791655#step/hana_install/112
- Needles: N/A
- Verification run: [a correct test](https://openqa.suse.de/tests/5796951), [a trapped lock](https://openqa.suse.de/tests/5798561#step/hana_install/170)
- 
**EDIT:** [test with the last code update](https://openqa.suse.de/tests/5825756)
> Fix device lock on pvremove in HANA installation

- tests/console/suseconnect_scc.pm
- Related ticket: https://openqa.suse.de/tests/5815718
- Verification runs: https://openqa.suse.de/tests/5826057
> Only JeOS and SLEM should come unregistered

- tests/x11/user_gui_login.pm
- Needles: Already existing from earlier changes; gnome-activities tag
- Verification run: https://openqa.opensuse.org/t1700350
> user_gui_login: Adjust to GNOME 40

- tests/console/journalctl.pm
- Related ticket: https://openqa.suse.de/tests/5814510#step/journalctl/60
* [sle-15-SP3-Online-aarch64@aarch64](https://openqa.suse.de/tests/5827666)
* [sle-15-SP3-Online-s390x@s390x-kvm-sle12](https://openqa.suse.de/tests/5827679#)
* [sle-15-SP3-Online-ppc64le@ppc64le](https://openqa.suse.de/tests/5827689)
* [opensuse-15.3-JeOS-for-kvm-and-xen-x86_64](https://openqa.opensuse.org/tests/1700767#live)
* [opensuse-15.2-JeOS-for-kvm-and-xen-x86_64](https://openqa.opensuse.org/tests/1700777#live)
* [opensuse-15.3-DVD-ppc64le](https://openqa.opensuse.org/tests/1700735)
* [opensuse-Tumbleweed-JeOS-for-kvm-and-xen-x86_64](https://openqa.opensuse.org/tests/1700757)
> Check /var/log/messages several times

- tests/console/nftables.pm
The reference directory /etc/nftables is missng on Tumbleweed, see boo#1183461
and https://progress.opensuse.org/issues/90041
Because nftables works without it and it requires a workaround for Tumbleweed.
For now it is better not to check the reference directory, see comment of above
bug report.
Add checks of loaded firewall setting
http://10.160.64.152/tests/1177 (tw)
http://10.160.64.152/tests/1176 (sle)
> Remove check of reference directory of nftables

- lib/containers/common.pm
Pass multiple commands in $runtine run command.
- Related ticket: https://progress.opensuse.org/issues/90701#note-5
- Verification run: [hvm](http://kepler.suse.cz/tests/4374)
> Execute chain of commands in container

- tests/ha/ha_cluster_preflight_check.pm
Due to [bsc#1182285](https://bugzilla.suse.com/show_bug.cgi?id=1182285), this PR adapts the preflight check test code.
Summarise of the main changes:
1.  "preflight check"  is now handled by the `crmsh` package and not by `python3-cluster-preflight-check` anymore
2.  command `ha-cluster-preflight-check` is also replaced by `crm analyze preflight_check`
3.  options `env-check` & `cluster-check` removed
- Related ticket: https://jira.suse.com/browse/TEAM-3766
- Needles: N/A
- Verification run: [node1](http://1b143.qa.suse.de/tests/7937), [node2](http://1b143.qa.suse.de/tests/7938), [node3](http://1b143.qa.suse.de/tests/7939)
**Please, do not merge this PR unless the new crmsh package is on 15sp3.**
> Reworking ha preflight check due to bsc#1182285

- tests/sles4sap/saptune/mr_test.pm
> sles4sap: Change mr_test repository

- tests/installation/await_install.pm
When the installation fails with "An error occurred during the installation."
during await_install a needle matches with tag `linuxrc_error` and dies immediately.
With this pull request it should collect logs including some linuxrc ones.
I also refactored the module wrapping the statements that modify the timeout into a
subroutine to make the run more readable.
- Related ticket: https://progress.opensuse.org/issues/90510
- Needles: [await_install-linuxrc_error-20210416](https://openqa.suse.de/tests/5838227#step/await_install/1) await_install-linuxrc-error-20210415.json
- Verification run: [crypt_no_lvm@ppc64le](https://openqa.suse.de/tests/5838227#downloads)
> Collect logs when linuxrc installation error banner

- tests/publiccloud/run_ltp.pm
As recommended i set 1200s for each test and with the combination of
LTP_TIMEOUT=7200 the issues with the timeout looks to dissapear
sle-15-SP3-EC2-HVM-ARM-x86_64-Build0085-publiccloud_ltp_cve@ec2_a1.large 
-> https://openqa.suse.de/t5845690                                                                                                                                                                                                           
sle-15-SP2-AZURE-Basic-Updates-x86_64-Build20210419-1-publiccloud_ltp_syscalls@az_Standard_A2_v2
-> https://openqa.suse.de/t5845691 …
> Increase timeout for run_ltp

- .github/workflows/ci.yml
- lib/Utils/Architectures.pm
- lib/Utils/Backends.pm
- lib/version_utils.pm
See related change https://github.com/os-autoinst/os-autoinst/pull/1647
> Update perltidy to 20210402

- schedule/yast/xfs/xfs.yaml
Re-adding test data accidentally deleted [here](https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/12048/files#diff-0b040b4a346eb50eba5560f645a0d95a85a6da0faa90bdb92385b65d2d685b01L64-L67)
> Readding test data for xfs scenario

- tests/x11/oomath.pm
- Related ticket: https://progress.opensuse.org/issues/91275
https://openqa.suse.de/tests/5855767 15 SP2 allpatterns
https://openqa.suse.de/tests/5855768 15 SP2 gnome
https://openqa.suse.de/tests/5855769 15 SP3 we-module
https://openqa.opensuse.org/tests/1706408 TW gnome
https://openqa.opensuse.org/tests/1706409 TW kde
> Workaround for exit of oomath not asking to save changes

- schedule/functional/extra_tests_textmode.yaml
VR: http://phobos.qa.suse.de/tests/3857465
Ticket: https://progress.opensuse.org/issues/72169
> Schedule Samba/AD tests

- schedule/functional/extra_tests_textmode.yaml
> samba_cli: Fix schedule for tumbleweed

- schedule/functional/extra_tests_dracut.yaml
Ticket: https://progress.opensuse.org/issues/68527
Verification:
s390x: https://openqa.suse.de/t5904507
x86_64: https://openqa.suse.de/t5904515
> dracut: Run bootloader_start eg for s390x

- lib/y2_base.pm
Remove dead code when uploading widgets json.
> Remove dead code when uploading widgets json

- lib/YuiRestClient.pm
- schedule/yast/firstboot/autoyast_y2_firstboot.yaml
- schedule/yast/firstboot/autoyast_y2_firstboot_opensuse.yaml
Setup is already done on the ay profile.
- Verification run: [openSUSE](https://openqa.opensuse.org/tests/1716682) | [SLE](https://openqa.suse.de/tests/5905372)
> Unschedule setup_libyui for autoyast firstboot scenario

- lib/LTP/WhiteList.pm
- lib/LTP/utils.pm
Add new "skip" attribute to LTP_KNOWN_ISSUES file which controls whether the test will be excluded from schedule.
This will allow us to define fine-tuned test exclude list without creating dozens of LTP testsuite copies in OpenQA database, with description why each individual test was excluded.
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/5907637 (cloned from https://openqa.suse.de/tests/5895680)
> Skip LTP tests based on LTP_KNOWN_ISSUES

- tests/wsl/install/ms_win_firstboot.pm
- tests/wsl/prepare_wsl_feature.pm
- tests/wsl/wsl_cmd_check.pm
This reverts commit 24bc18f020e7b6ceb738d69bfec91680e03219f8, reversing
changes made to e1d554bfb02737d45a11043c8118c69fe3365a74.
> Revert "Merge pull request #12388 from mloviska/windows_image_performance_update"

- lib/containers/common.pm
- lib/containers/utils.pm
- tests/containers/docker_compose.pm
VR : http://autobot.qa.suse.de/tests/2347
> containers: replace sed calls with dedicated function

- tests/publiccloud/ssh_interactive_init.pm
As this test module was pretty experimental refactoring is needed.
The code is now structured and each section is commented.
- Verification run: [sle-15-SP1-GCE-BYOS-Updates](http://pdostal-server.suse.cz/tests/11728) [sle-15-SP2-AZURE-Standard-gen2-Updates](http://pdostal-server.suse.cz/tests/11727) [sle-12-SP5-EC2-Updates](http://pdostal-server.suse.cz/tests/11725) [15-SP2-AZURE-BYOS-Updates@mau-extratests-publiccloud](http://pdostal-server.suse.cz/tests/11737) [sle-12-SP4-GCE-BYOS-Updates@mau-extratests-publiccloud](http://pdostal-server.suse.cz/tests/11739) [sle-12-SP5-GCE-BYOS-Updates@mau-extratests-publiccloud](http://pdostal-server.suse.cz/tests/11738) [sle-15-SP2-EC2-ARM-Updates@mau-extratests-publiccloud](http://pdostal-server.suse.cz/tests/11735)
> Public Cloud: Refactor ssh_interactive_init module

- tests/console/check_system_info.pm
Check expected system information after migration upgrade
- Related ticket: https://progress.opensuse.org/issues/91932
- Verification run: https://openqa.suse.de/tests/5924105
https://openqa.suse.de/tests/5924285#step/check_system_info/9
> Check expected system information after migration upgrade

- lib/console/procps_utils.pm
- tests/console/procps.pm
Verification of vmstat sample output with and without load. 
- Related ticket: https://progress.opensuse.org/issues/48959
- Needles: No
- Verification run:  Test - procps
sle-15-SP3-Online-ppc64le     - https://openqa.suse.de/tests/5894238#step/procps/1
sle-15-SP3-Online-ppc64le     - https://openqa.suse.de/tests/5894238#step/procps/1
sle-15-SP3-Online-x86_64      - https://openqa.suse.de/tests/5894427#step/procps/1
sle-15-SP3-Online-aarch64     - https://openqa.suse.de/tests/5896129#step/procps/1
sle-15-SP3-Online-s390x       - https://openqa.suse.de/tests/5897087#step/procps/1
openSUSE-Leap-15.3-DVD-x86_64 - http://10.161.229.147/tests/193#step/procps/1
opensuse-Tumbleweed-DVD-x86_64   - http://10.161.229.147/tests/200#step/procps/1
sle-15-SP1-Server-DVD-Updates-x86_64 - …
> Vmstat test 

- schedule/qam/common/mau-extratests2.yaml
This reverts commit 2d25356ed9660e8a5bace6c1ca97d5072097638b.
#12431
> Revert "Schedule Samba/AD tests to select maintenance versions"

- schedule/functional/tomcat.yaml
see https://progress.opensuse.org/issues/91187
verification tests:
http://10.160.64.152/tests/2229
http://10.160.64.152/tests/2230
> Add existing module 'tomcat' for SLES 15 SP3 functional

- tests/console/sshd.pm
I'd like to try some more debug info so we can for example analyse the `dmesg` better.
- Related ticket: [bsc#1181308](https://bugzilla.suse.com/show_bug.cgi?id=1181308)
- Verification run: [SLE15-SP2](http://pdostal-server.suse.cz/tests/11790)
> Improve debug output of console/sshd.pm

- tests/x11/hexchat.pm
- Related ticket: https://progress.opensuse.org/issues/88930
- Verification run: https://openqa.opensuse.org/t1725694
> hexchat: allow more time to disconnect - poo#88930

- tests/sles4sap/monitoring_services.pm
In case of failure it could be useful to have the config files of all the HA/SAP monitoring components.
- Needles: N/A
- Verification run:[sles4sap_nw_node01](http://1b210.qa.suse.de/tests/9023), [sles4sap_nw_node02](http://1b210.qa.suse.de/tests/9022), [sles4sap_hana_node01](http://1b210.qa.suse.de/tests/9028), [sles4sap_hana_node02](http://1b210.qa.suse.de/tests/9029)
> Export config files in monitoring test on SLES4SAP

- lib/main_common.pm
- Related ticket: https://progress.opensuse.org/issues/90411
- Needles: N/A
- Verification run: https://openqa.opensuse.org/tests/1728344
> Do not test gnome-documents on Tumbleweed

- data/autoyast_qam/15-SP3_installation.xml.ep
- data/autoyast_qam/15-SP3_installtest.xml.ep
Fixes https://openqa.suse.de/tests/5947688#
- Related ticket: https://progress.opensuse.org/issues/91455
- Verification run: https://openqa.suse.de/tests/5953616#
> Add 15-sp3 yast profiles

- tests/console/clamav.pm
- tests/console/krb5.pm
- tests/console/openvswitch.pm
- tests/console/ovn.pm
- tests/console/sysstat.pm
- Related ticket: https://progress.opensuse.org/issues/88477
https://openqa.suse.de/tests/5947160 mau-extratests1 x86_64 12 SP5
https://openqa.suse.de/tests/5947231 mau-extratests1 s390x 12 SP5
https://openqa.suse.de/tests/5947106 mau-extratests1 aarch64 12 SP5
https://openqa.suse.de/tests/5947161 mau-extratests2 x86_64 12 SP5
https://openqa.suse.de/tests/5947232 mau-extratests2 s390x 12 SP5
https://openqa.suse.de/tests/5947107 mau-extratests2 aarch64 12 SP5
https://openqa.suse.de/tests/5947478 mau-extratests1 x86_64 15 SP1
https://openqa.suse.de/tests/5947527 mau-extratests1 s390x 15 SP1
https://openqa.suse.de/tests/5947392 mau-extratests1 aarch64 15 SP1
https://openqa.suse.de/tests/5947479 mau-extratests2 x86_64 15 SP1
https://openqa.suse.de/tests/5947528 …
> Do a teardown on passed console tests

- data/qam/dracut/15-SP3_custom_lvm.xml.ep
- data/qam/dracut/15-SP3_custom_usr.xml.ep
Fixes https://openqa.suse.de/tests/5960238#step/prepare_profile/1
- Related ticket: https://progress.opensuse.org/issues/91455
- Verification run: https://openqa.suse.de/tests/5961230
> Add 15-sp3 yast profiles for dracut test

- lib/nfs_common.pm
We have yastr2-nfs-server check in the service check modules in migration's regression test, 
so we need to do cleanup in the service check after migration and check if nfsv4 was enabled
before start the NFS server in yast2_nfs_server module.
- Related ticket: https://progress.opensuse.org/issues/90815
- Needles: N/A
https://openqa.nue.suse.com/tests/5924341 
https://openqa.nue.suse.com/tests/5924666
https://openqa.nue.suse.com/tests/5961025
> Fix yast2_nfs_server modue not works after service check in migration regression test

- lib/containers/common.pm
- lib/containers/utils.pm
- tests/containers/docker.pm
- tests/containers/docker_image.pm
Reverts os-autoinst/os-autoinst-distri-opensuse#12480
> Revert "Implements docker firewall validation"

- lib/containers/common.pm
This fixes [this](https://openqa.suse.de/tests/5959678#step/docker_image/99) problem
> Containers: skip rpm backend check for <15-SP3

- schedule/qam/common/qam-yast-self-update.yaml
- tests/qam-minimal/install_update.pm
- Related ticket: https://progress.opensuse.org/issues/92254
https://openqa.suse.de/tests/5965540 install_update
https://openqa.suse.de/tests/5964858 self_udpate 15 SP2 UEFI
https://openqa.suse.de/tests/5969195 self_udpate 15 SP1 UEFI
> shim: Update grub2 due to new signatures

- tests/sles4sap/hana_install.pm
The sporadic LVM lock can be caused by a bad device-mapper table.
See here: https://openqa.suse.de/tests/5962343#step/hana_install/184
- Needles: N/A
- Verification run: https://openqa.suse.de/t5969659
> Fix device-mapper table on SLES4SAP NVDIMM test

- tests/console/check_system_info.pm
This fix for sles15GA upgrade to sles15sp3, it can add python2 module
by default. For hpc cases, after upgrade to sles15+, the legacy module
will be deleted.
- Related ticket: https://progress.opensuse.org/issues/92275
https://progress.opensuse.org/issues/92269
hpc: https://openqa.suse.de/tests/5967865#
15ga: http://openqa.suse.de/t5967619
> For sles15GA upgrade to sles15sp3, it can add python2 module by default

- tests/installation/bootloader_zkvm.pm
Related with: https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/12401#discussion_r630200355
> Drop soft failure for bsc#1054448

- lib/containers/common.pm
- lib/containers/utils.pm
- tests/containers/docker.pm
I added a small validation for the expected configuration of the firewall.
Briefly, makes sure that Docker firewall zone exists with an active docker0
interface and in turn this is not added on trusted zone. Run a container and
verify the iptables.
Applies firewall test in docker and docker_image
the tests implemented based on https://docs.docker.com/network/iptables/
- Related ticket: https://progress.opensuse.org/issues/89872
opensuse-Tumbleweed-DVD-x86_64-Build20210508-extra_tests_textmode_containers@64bit -> https://openqa.opensuse.org/tests/1735159
opensuse-Tumbleweed-DVD-x86_64-Build20210508-extra_tests_textmode_containers@64bit -> https://openqa.opensuse.org/tests/1735160
opensuse-15.3-DVD-x86_64-Build148.1-extra_tests_textmode_containers@64bit -> …
> Implements docker firewall validation

- 15-SP3_installation.xml.ep
Reverts os-autoinst/os-autoinst-distri-opensuse#12516
> Revert "Create sylink for 15-SP3 for 15-SP3_installation.xml.ep"

- lib/containers/utils.pm
- tests/containers/docker.pm
Fixes two occuring issues when docker interacts with firewalld:
* test fails when firewalld is not started
* Check for special docker firewalld zone on 15.3 (and later) and ocker version >= 20.10
- Related ticket: https://progress.opensuse.org/issues/92728
- Verification runs: [15-SP2 GCE](http://duck-norris.qam.suse.de/tests/6092) | [Leap 15.2 JeOS](http://duck-norris.qam.suse.de/tests/6094) | [15.3 Leap JeOS](https://openqa.opensuse.org/tests/1747311) | [Tumbleweed JeOS](https://openqa.opensuse.org/tests/1747546)
> Fix two issues with docker and firewalld

- schedule/sles4sap/qam/common/qam_install_sles4sap.yaml
The installation file needs to be adapted for 15-SP3.
- Related ticket: https://jira.suse.com/browse/TEAM-4090 & https://progress.opensuse.org/issues/92527
- Needles: N/A
> Add the 15-SP3 condition for SAP QEM installation

- tests/yast2_cmd/yast_users.pm
Reverts os-autoinst/os-autoinst-distri-opensuse#12555
> Revert "Increase timeout for yast_users"

- tests/xfstests/enable_kdump.pm
Reverts os-autoinst/os-autoinst-distri-opensuse#12542
> Revert "xfstests: use activate_kdump_cli to enable kdump"

- tests/wsl/install/ms_win_firstboot.pm
> Fix typo in needle tag

- tests/publiccloud/download_repos.pm
Fix issue with wrong test repo directory for publiccloud maintenance
test runs. Also improve failure when test repos are empty.
- Related ticket: https://progress.opensuse.org/issues/92605
- Verification run: http://duck-norris.qam.suse.de/tests/6128
> Hotfix: PC repo directory name invalid

- tests/installation/partitioning_smalldisk_storageng.pm
Improve partitioning_smalldisk_storageng.pm in:
1)  Smoothly work and verified in 12-SP4, 12-SP5, 15, 15-SP1, 15-SP2, 15-SP3 with x86_64 and ppc64le arch
2) Support override SMALL_DISK parameter to specific one.
Verification:
http://openqa.qa2.suse.asia/tests/32209
http://openqa.qa2.suse.asia/tests/33562
http://openqa.qa2.suse.asia/tests/33263
> Improve partitioning_smalldisk_storageng for text mode installation

- tests/yast2_cmd/yast_users.pm
https://progress.opensuse.org/issues/92431
VR: http://falafel.suse.cz/tests/390
> Increase timeout for yast_users

- tests/transactional/verify_undelete_snapshots.pm
- Related ticket: https://progress.opensuse.org/issues/92452
- Verification run: http://falafel.suse.cz/tests/392
> Add more descriptive comments in verify_undelete_snapshots

- tests/console/sshd.pm
This test stops the firewall, but does not enable it again. This has a
significant influence on later test modules.
15.2 updates: https://openqa.opensuse.org/tests/1751662
TW JeOS: https://openqa.opensuse.org/tests/1751890
> console/sshd: Don't leave the firewall disabled

- lib/services/users.pm
From bug https://bugzilla.suse.com/show_bug.cgi?id=1185943, 'switch user' by button is not supported on s390x VM and we need to logout and login new user for the switch user test.
- Related ticket: https://progress.opensuse.org/issues/92284
- Needles: N/A
- Verification run: https://openqa.nue.suse.com/tests/6093177#step/check_upgraded_service/17
http://openqa.nue.suse.com/tests/6093200#    desktop test run avoid regression
> Update switch user to logout and login for s390x

- lib/rancher/utils.pm
- tests/rancher/rancher_k3s_master.pm
- tests/rancher/rancher_k3s_worker.pm
- tests/rancher/rancher_rke1_master.pm
- tests/rancher/rancher_rke1_worker.pm
- tests/rancher/rancher_supportserver.pm
Hello,
1) Check that we have `default` route and `nameserver` configured
2) Wait for all the nodes to finish networking setup
- Verification run: http://pdostal-server.suse.cz/tests/11843#
> Rancher: Check networking and wait for all nodes

- lib/transactional.pm
Use the message by transactional-update instead, which is more likely to arrive
in time before system reboots.
TW microos-old2microosnext: https://openqa.opensuse.org/tests/1757679
CC @dzedro this should address the failure you linked in https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/12554#issuecomment-846850230.
> lib/transactional: When rebooting, don't wait for the command to return

- tests/fips/mozilla_nss/firefox_nss.pm
**Description:**
Attempt to get the effective log from firefox while crash. Adding the crash reporter option will be a way to resolve the gap. Currently it is unable to reproduce the crash in the latest build, but it is worth adding the enhancement for firefox.
1. Add firefox_nss crashreport option function for getting the useful crash log
2. Add some sub function for firefox preferences testing and code refactoring in DRY
- Related ticket: https://progress.opensuse.org/issues/80754
- Needles: NA
- Verification run: https://openqa.suse.de/tests/6110245
> Add firefox_nss crashreport option and code refactoring in DRY

- lib/bootloader_setup.pm
- Verification run:  https://openqa.opensuse.org/t1758578
> Add console=tty1 on 32-bit arm as well - boo#1186468

- products/sle/main.pm
- schedule/functional/rsync.yaml
- tests/console/rsync_server.pm
Reverts os-autoinst/os-autoinst-distri-opensuse#12608
sorry forgot add yaml schedule on OSD, Now yaml schedule is definded in test suite of rsync test.
> Revert "Revert "Add rsync tests for sles 15 functional""

- products/microos/main.pm
- schedule/sle-micro/raw_image.yaml
- tests/transactional/enable_selinux.pm
- variables.md
TEST SLE Micro and openSUSE MicroOS with SELinux enabled
- Related ticket: https://progress.opensuse.org/issues/91133
> MicroOS: enable SELinux tests

- products/sle/main.pm
* **Move** uefi guest install test under PRJ1 test, and also do feature test after uefi guest installation.
* **New** subroutine load_virt_guest_install_tests to load guest installation and post-setup modules
* **New** subroutine load_virt_feature_tests to load feature test modules
* **Verification run:**
* [Verification run 1](http://10.67.129.106/tests/1302)
* [Verification run 2](http://10.67.129.106/tests/1301)
> Re-organize PRJ1 guest install and feature tests

- tests/containers/docker_compose.pm
- Related ticket: https://progress.opensuse.org/issues/93333
> Record soft failure if docker-compose fails with dependency problems

- data/publiccloud/terraform/azure.tf
Use `azurerm_linux_virtual_machine` resource instead of older
`azurerm_virtual_machine` which is being discontinued.
- Related ticket: [poo#93174](https://progress.opensuse.org/issues/93174)
- Verification run: [published image 15-SP3](http://pdostal-server.suse.cz/tests/11972) [uploaded image 15-SP2](http://pdostal-server.suse.cz/tests/11973) [published image 15-SP2 gen2](http://pdostal-server.suse.cz/tests/11975)
> Public Cloud: Refresh azure terraform config poo#93174

- ui-framework-documentation.md
The documentation of UI Test Automation Framework does not address some question, that new users could have. We want to make the documentation as clear as possible for test writers with any level of expertise.
> Update doc for UI Test Automation Framework

- tests/containers/validate_btrfs.pm
Fix for wrongly assuming 20GB disk size in the validate_btrfs
container tests.
- Related ticket: https://progress.opensuse.org/issues/93339
- Verification run: http://duck-norris.qam.suse.de/tests/6570
> Fix validate_btrfs

- data/autoyast_sle15/pc_tools.xml
- tests/publiccloud/prepare_tools.pm
VR : http://autobot.qa.suse.de/tests/2357
> prepare_tools: Moving terraform into container

- products/microos/main.pm
- schedule/sle-micro/autoyast.yaml
- schedule/sle-micro/dvd.yaml
- schedule/sle-micro/raw_image.yaml
- tests/microos/cockpit_service.pm
- Related ticket: https://progress.opensuse.org/issues/93438
> MicroOS: enable cockpit test in openSUSE MicroOS

- products/sle/main.pm
- schedule/functional/salt.yaml
- tests/network/salt_master.pm
see https://progress.opensuse.org/issues/93330
verification:
http://10.160.64.152/tests/2693#dependencies
> Add salt-server and salt-minion to Product QE (functional)

- lib/virt_autotest/common.pm
- Related ticket: [poo#93579](https://progress.opensuse.org/issues/93579)
> Virtualization: Add 15sp3 VMware / Hyper-V smoketest guests

- schedule/rancher/rancher.yaml
VR: http://angmar.suse.de/tests/3334#
> Add oss repos in rancher leap runs

- tests/console/gdb.pm
Ticket: https://progress.opensuse.org/issues/90557
Verification: http://kazhua.qa.suse.de/tests/overview.html?build=20210605%3Apoo90557&version=Tumbleweed&groupid=1&distri=opensuse
> gdb: Fix sporadic issues by waiting for (gdb) prompt

- tests/x11/remote_desktop/windows_network_setup.pm
See https://openqa.opensuse.org/tests/1745809#step/windows_network_setup/6
> remote_desktop: Fix sporadic slow startup of Windows powershell

- tests/console/sshd.pm
- Related ticket: https://progress.opensuse.org/issues/92617
- Needles: N/A
- Verification run: [TW](https://openqa.opensuse.org/t1767556)
> openssh: Support openssh package shipping default config in /usr/etc

- tests/console/check_system_info.pm
To make sure zypper lr output can show correct product information
and version ID
- Related ticket: https://progress.opensuse.org/issues/93399
SLES: https://openqa.suse.de/tests/6201940#
SLED: https://openqa.suse.de/tests/6201945
HPC:  https://openqa.suse.de/tests/6201942
> Add product information check at zypper lr output

- lib/containers/common.pm
It fixes [this problem](https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/12679#issuecomment-858404529)
VR: https://openqa.opensuse.org/tests/1778407
> Containers: don't run SUSEConnect for opensuse fix

- tests/console/libgpiod.pm
> libgpiod: fix test on RPi3/4

- tests/installation/await_install.pm
- needles: 
- https://github.com/os-autoinst/os-autoinst-needles-opensuse/commit/a066e1cd12d0c0af358ae00556d5c395d70d9c5e
- https://github.com/os-autoinst/os-autoinst-needles-opensuse/commit/4bec565cb3100e31f1214e80a1d5a772886bb659
- Verification run: https://openqa.opensuse.org/t1778635
> Handle mkinitrd error on armv7 installation - boo#1171180

- data/virt_autotest/guest_autoyast_xml_files/sles_15_plus_kvm_hvm_guest_multi-user_x86_64.xml
- data/virt_autotest/guest_autoyast_xml_files/sles_15_plus_xen_hvm_guest_multi-user_x86_64.xml
- lib/concurrent_guest_installations.pm
* **New** subroutine save_guest_installations_assets to upload guest images if it is successfully installed.
* **Add** missing hash character in guest autoyast files.
* **Verification run:**
* [Upload all successful guests](http://10.67.129.106/tests/1319)
* [Do not upload failed guests](http://10.67.129.106/tests/1318)
> Upload uefi guest assets on successful installation

- data/autoyast_containers.xml.ep
VRs: https://openqa.suse.de/group_overview/377 (failures are reported in [poo#93817](https://progress.opensuse.org/issues/93817) and are not related to the profile)
> Containers: improve generic autoyast profile

- tests/console/yast2_ftp.pm
- Related ticket: [poo#93671](https://progress.opensuse.org/issues/93671)
- Verification run: [yast2_ncurses](https://openqa.opensuse.org/tests/1786543)
> Fix RSA params size in yast2 ftp

- data/autoyast_containers.xml.ep
- Added support for ppc64Ie
- Added partitioning section for s390x
- Increased grub timeout to not stall in some aarch64 tests
> Containers: add ppc64le to generic autoyast profile

- tests/x11/enlightenment_first_start.pm
- Verification run: https://openqa.opensuse.org/t1787159
> enlightenment: acpid window is not shown on 32-bit arm

- lib/rstudio.pm
> rstudio: increase time allowed to install profvis

- tests/console/zypper_lifecycle.pm
- tests/console/zypper_moo.pm
- tests/console/zypper_ref.pm
- tests/installation/boot_s390.pm
- tests/installation/bootloader_uefi.pm
- tests/installation/logpackages.pm
- tests/installation/memtest.pm
- tests/installation/post_zdup.pm
- tests/installation/reboot_after_installation.pm
- tests/installation/rescuesystem.pm
- tests/installation/zdup.pm
Zypper modules for QE Core, a few general modules jointly to the department.
> Re-adjust some module maintainerships

- lib/utils.pm
- Related ticket: https://openqa.suse.de/tests/6265736#step/scc_registration/73
- Verification run: https://openqa.suse.de/tests/6270824
> Import gpg untrusted key changed to yes/no

- tests/containers/validate_btrfs.pm
This intends to fix the issue with the `/root/sle_base_image/docker_build`.
This used to work because the scheduling included the steps of the
directory's creation in another module which was running prior to the
`validate_btrfs`, which in turn, it reused it.
i have modified the module to become independent and atomic. That should
include the docker installation, configuration
(as it happens in docker.pm for example), and the creation and
removal of the resources.
In additional the test requires NUMDISKS eq to 2 https://gitlab.suse.de/qac/qac-openqa-yaml/-/merge_requests/277
- Related ticket: https://progress.opensuse.org/issues/93889
sle-12-SP4-Server-DVD-Updates-x86_64-Build20210611-1-engines_and_tools@64bit -> https://openqa.suse.de/t6259324 …
> Makes validate_btrfs module independent from the other container modules

- schedule/functional/tomcat.yaml
see http://10.160.64.152/tests/2862
needles PR:
https://github.com/os-autoinst/os-autoinst-needles-opensuse/pull/730
verification:
http://10.160.64.152/tests/2862
> Add tomcat to Tumbleweed

- lib/publiccloud/ec2.pm
Add EU-West1 helper machine AMIs
- Verification run: http://duck-norris.qam.suse.de/tests/6611
> Add EU-West-1 AMI

- data/autoyast_containers.xml.ep
VRs:
- [15-SP1](https://openqa.suse.de/tests/6282198)
- [15-SP2](https://openqa.suse.de/tests/6282197)
- [15-SP3](https://openqa.suse.de/tests/6279973)
> Containers: fix aarch64 create hdd autoyast profile

- tests/x11/hexchat.pm
- Related ticket: https://progress.opensuse.org/issues/93315
- Needles: N/A
- Verification run: https://openqa.opensuse.org/tests/1791900
> hexchat: Switch network to Libera Chat

- tests/containers/validate_btrfs.pm
VR: http://fromm.arch.suse.de/tests/1692
> Containers: fix validate_btrfs when checking for existing dir

- lib/utils.pm
On Leap 15.3, "zypper patch" first updates only openSUSE-release, the next
call updates libzypp and friends and only the third invocation installs other
patches. Support that by moving the zypper calls into a loop. Move the special
case of 11 SP4 outside.
As a side effect this also fixes that zypper failing with "4" was ignored on
non-SLE by accident.
Previously failing test: https://openqa.opensuse.org/tests/1797173
Verification run: https://openqa.opensuse.org/tests/1798386
> lib/utils.pm: Support two stages of zypper patch returning 103

- tests/virt_autotest/virt_utils.pm
* **Image** operations may fail on running vm using qemu-img due to [can not obtain "write" lock](https://openqa.suse.de/tests/6279407#step/uefi_guest_installation/393)
* **Use** option --force-share with qemu-img can help solve the problem.
* **Verification run:**
* [kvm verification run](https://openqa.suse.de/tests/6285569#step/uefi_guest_installation/401)
* [xen verification run](https://openqa.suse.de/tests/6285562#step/uefi_guest_installation/523)
> Use --force-share to perform operations on vm image

- lib/main_common.pm
Reverts os-autoinst/os-autoinst-distri-opensuse#12765
> Revert "Add os-autoinst version check based on current used feature set"

- test_data/qam/QR/15-SP2/raid/raid0_gpt_bios_boot.yaml
Fixes missed test data in PR https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/12703
> Fix test data in RAID0 QR SLE15 SP2 test suite

- schedule/yast/btrfs/btrfs_opensuse.yaml
- schedule/yast/ext3/ext3_textmode-opensuse.yaml
- schedule/yast/ext4/ex4_textmode-opensuse.yaml
- schedule/yast/ext4/ext4@yast-s390x-disk-activation.yaml
- schedule/yast/ext4/ext4@yast-s390x.yaml
- schedule/yast/ext4/ext4@yast-xen-hvm.yaml
- schedule/yast/ext4/ext4@yast-xen-pv.yaml
- schedule/yast/ext4/ext4@yast.yaml
- schedule/yast/ext4/ext4@yast_spvm.yaml
- schedule/yast/ext4/ext4_opensuse.yaml
- schedule/yast/xfs/xfs.yaml
- schedule/yast/xfs/xfs@svirt-xen-hvm.yaml
- schedule/yast/xfs/xfs@svirt-xen-pv.yaml
- schedule/yast/xfs/xfs_opensuse.yaml
- schedule/yast/xfs/xfs_spvm.yaml
- schedule/yast/xfs/xfs_textmode-opensuse.yaml
See https://progress.opensuse.org/issues/93641
Vrs: 
ext3_textmode http://waaa-amazing.suse.cz/tests/15546
ext4_textmode http://waaa-amazing.suse.cz/tests/15545
xfs_textmode http://waaa-amazing.suse.cz/tests/15549
needle: https://github.com/os-autoinst/os-autoinst-needles-opensuse/pull/732
> Add missing schedules where guided_partitioning applies 

- data/autoyast_sle15/autoyast_rt.xml
> Add variable for AY RT profile

- lib/serial_terminal.pm
- lib/transactional.pm
- schedule/sle-micro/dvd.yaml
- tests/installation/installation_overview.pm
- Related ticket: https://progress.opensuse.org/issues/93125
> SLE Micro: fix s390x installation

- schedule/publiccloud/mau-extratests-docker-publiccloud.yml
- Related ticket: [poo#94673](https://progress.opensuse.org/issues/94673)
> Public Cloud: Do not run Podman on SLE12-SP5

- lib/containers/common.pm
Trivial fix of a classical return code handling error
- Verification run: Trivial fix, not needed
> Fix wrong return code for bsc1187479 softfail

- .github/workflows/ci.yml
See related change https://github.com/os-autoinst/os-autoinst/pull/1703
> Update perltidy to 20210625

- schedule/functional/extra_tests_misc.yaml
see https://progress.opensuse.org/issues/94711
verification:
http://10.160.64.152/tests/3285
> Add 2 extra console tests to Tumbleweed

- tests/containers/registry.pm
- Related ticket: containers/podman#10685
- Verification run: [Tumbleweed](http://pdostal-server.suse.cz/tests/12275)
> Document podman#10685 bug in registry test

- schedule/sle-micro/containers.yaml
The problem was introduced in [this PR](https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/12768)
- Related ticket: https://progress.opensuse.org/issues/94874
- VR: https://openqa.suse.de/tests/6351902
> SLE Micro: remove docker tests

- schedule/yast/switch_keyboard.yaml
Complementary change for PR#12737
fixing failure: https://openqa.suse.de/tests/6353392#step/accept_license/2
VRs: http://falafel.suse.cz/tests/451
http://falafel.suse.cz/tests/450
> Add setup_libyui in switch_keyboard schedule

- lib/containers/container_images.pm
- lib/containers/utils.pm
> Containers: Remove prepare_img(), build_img() and run_img() as they are called only from build_and_run_image()

- lib/sles4sap.pm
- Fail: https://openqa.suse.de/tests/6358254
- Verification run: https://openqa.suse.de/tests/6358950
> robot_fw: Increase bootloader_time in wait_boot

- tests/x11/chrome.pm
* Use explicit functions instead of comments
* Use ternary operator for conditional assignment
* Use no timeouts below default when there are no time-critical
behaviours
* Use single ticks where we do not want to expand variables in strings
```
MARKDOWN=1 openqa-clone-custom-git-refspec https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/12745 https://openqa.opensuse.org/tests/1792294 SCHEDULE=tests/boot/boot_to_desktop,tests/x11/x11_setup,tests/x11/chrome
```
* [opensuse-Tumbleweed-DVD-x86_64-Build20210616-extra_tests_gnome@64bit](https://openqa.opensuse.org/t1795072)
> Simplify chrome test module

- schedule/containers/sle_image_on_res.yaml
- Related ticket: https://progress.opensuse.org/issues/94183
- VR: https://openqa.suse.de/tests/6351517#
> Containers: add schedule for SLES Expanded Support

- tests/console/yast2_apparmor.pm
- Related ticket: https://progress.opensuse.org/issues/90392
https://openqa.suse.de/tests/6366384 15 SP3
https://openqa.suse.de/tests/6363806 15 GA
https://openqa.suse.de/tests/6363705 12 SP5
> apparmor: Fix ocassional failures, press down only on sle12

- tests/console/check_system_info.pm
Changed the code to check the HPC and leap product  
Before and after migration the product name may change. Like:
SLE_HPC will change: SLES -> HPC
HPC proxyscc: HPC -> HPC-15-SP3
HPC media upgrade: HPC -> 15-SP3-HPC
Leap:  openSUSE Leap -> SLES
- Related ticket:https://progress.opensuse.org/issues/94252
HPC media:https://openqa.suse.de/tests/6350996
HPC proxyscc: https://openqa.suse.de/tests/6350797
leap: https://openqa.suse.de/tests/6350916
HPC module:  https://openqa.suse.de/tests/6351083
SLES: https://openqa.suse.de/tests/6350857
> Change the code to check the HPC and leap product name

- tests/console/sudo.pm
On publiccloud the root password needs to be set for this test to work.
An additional check, if the password is required has been added as well.
- Related ticket: https://progress.opensuse.org/issues/95021
- Verification run: [15-SP2-Azure-BYOS](http://duck-norris.qam.suse.de/t6708) | [15-SP2-EC2](http://duck-norris.qam.suse.de/t6709) | [12-SP5 GCE](http://duck-norris.qam.suse.de/t6710)
- [SLES 15-SP2 x86_64](http://duck-norris.qam.suse.de/t6711) | [SLES 12-SP5 x86_64](https://openqa.suse.de/t6378270) | [SLES 15-SP3 aarch64](https://openqa.suse.de/t6378271) | [SLES 15-SP3 x86_64](https://openqa.suse.de/t6378272)
> Fix sudo test for publiccloud

- tests/publiccloud/instance_overview.pm
- Related ticket: https://progress.opensuse.org/issues/95104
> PublicCloud: increase suseconnect timeout

- tests/console/yast2_apparmor.pm
- Related ticket: https://progress.opensuse.org/issues/90392
http://dzedro.suse.cz/tests/18521 12 SP4
http://dzedro.suse.cz/tests/18520 12 SP5
http://dzedro.suse.cz/tests/18519 15
http://dzedro.suse.cz/tests/18518 15 SP2
https://openqa.suse.de/tests/6399723 12 SP5
https://openqa.suse.de/tests/6399722 15
https://openqa.suse.de/tests/6399724 15 SP1
https://openqa.suse.de/tests/6399725 15 SP2
https://openqa.opensuse.org/tests/1831757 TW
> apparmor: Cleanup toggling

- tests/yast2_cmd/yast_lan.pm
- Fail: https://openqa.suse.de/tests/6403069#step/yast_lan/11
- Verification run: http://dzedro.suse.cz/tests/18530#step/yast_lan/10
> yast_lan: Increase timeout on occasionally failing lan add

- tests/console/journalctl.pm
Check if systemd drop-in directory exists and remove printing of
**journactl** manpage.
- failure in [PC](https://openqa.suse.de/tests/6414937#step/journalctl/14)
- Related ticket: https://progress.opensuse.org/issues/91848
> Minor updates for journactl.pm

- tests/security/apparmor_profile/usr_sbin_smbd.pm
- tests/security/apparmor_profile/usr_sbin_traceroute.pm
- Related ticket: https://progress.opensuse.org/issues/92004
- Verification run: https://openqa.opensuse.org/tests/1832705
CC @lilyeyes
> Fix security/apparmor_profile/usr_sbin_smbd and usr_sbin_traceroute on TW

- tests/console/yast2_ftp.pm
- Related ticket: [poo#93671](https://progress.opensuse.org/issues/93671)
- Verification run: [SLES](https://openqa.suse.de/tests/overview?build=jknphy%2Fos-autoinst-distri-opensuse%23fix_rsa_yast2_ftp&distri=sle) | [openSUSE](https://openqa.opensuse.org/tests/1837370)
Note: repo not available for SLE-12-SP2 to test it
> Keep using dsa in config file for SLE<=12-SP2

- data/journal_check/bug_refs.json
VR: <s>https://openqa.opensuse.org/tests/1838577#step/journal_check/10</s> https://openqa.opensuse.org/t1838702
> Update list of known bugs on Raspberry Pi

- tests/boot/grub2_test.pm
- Fail: https://openqa.suse.de/tests/6444600#step/grub2_test/1
- Verification run: https://openqa.suse.de/tests/6444664
> Accept exit 107 when installing vanilla kernel

- tests/console/yast2_ftp.pm
- Related ticket: #12891
- Verification run: http://dzedro.suse.cz/tests/18569#step/yast2_ftp/14
> Fix the not needed \n & don't hide failure with script_run

- lib/publiccloud/instance.pm
- tests/publiccloud/patch_and_reboot.pm
VR: http://autobot.qa.suse.de/tests/2509
> publiccloud: propagate softreboot timeout in variable

- schedule/staging/default_install@s390x-staging.yaml
- schedule/staging/ext4@s390x-staging.yaml
- schedule/staging/minimal+base@s390x-staging.yaml
> Add YAML schedule for Staging on s390x

- tests/kernel/update_kernel.pm
Some incidents contain extra kernel packages that may get accidentally booted instead of the intended kernel. Check that no unexpected packages got installed during `update_kernel`.
- Related ticket: https://progress.opensuse.org/issues/93674
- Needles: N/A
- 15-SP3 KOTD x86_64: https://openqa.suse.de/tests/6346744
- 15-SP3 kernel-azure: https://openqa.suse.de/tests/6350875
- 15-SP3 kernel-default x86_64: https://openqa.suse.de/tests/6346735
- 15-SP3 kernel-default s390x: https://openqa.suse.de/tests/6346734
- 15-SP3 kernel-default ppc64le: https://openqa.suse.de/tests/6346732
- 15-SP3 kernel-default aarch64: https://openqa.suse.de/tests/6346730
- 15-SP3 kernel-default-base x86_64: https://openqa.suse.de/tests/6346965
- 15-SP2 kernel-livepatch ppc64le: …
> update_kernel: Check for unexpected kernel packages

- schedule/yast/installer_extended/installer_extended_opensuse.yaml
- Related ticket: [poo#95467](https://progress.opensuse.org/issues/95467)
- Verification run: [installer_extended](https://openqa.opensuse.org/tests/1842077)
> Unschedule select_patterns in installed_extended_opensuse

- lib/bootloader_setup.pm
- lib/opensusebasetest.pm
- lib/transactional.pm
- schedule/sle-micro/raw_image.yaml
- tests/transactional/disable_grub.pm
- Related ticket: https://progress.opensuse.org/issues/93125
- Verification run: https://openqa.suse.de/tests/6293548
> SLE Micro: update schedule to properly boot s390x image

- lib/bootloader_setup.pm
- lib/main_common.pm
- Verification run: https://openqa.opensuse.org/t1844035
> is_leap should compare to a version with a minor version included

- lib/opensusebasetest.pm
- tests/console/verify_efi_mok.pm
Check serial for MOK Manager initial screen instead of matching a
needle.
Updates could possible change efi settings and JeOS image does not boot
from 'removable' efi rom any more. Test case should consider this as an
option in case of Updates test scenario.
- [ticket](https://progress.opensuse.org/issues/94303)
- [o3 needle removal](os-autoinst/os-autoinst-needles-opensuse#737)
- VRs:
- [tw](http://kepler.suse.cz/tests/6011#)
- [leap15.3](http://kepler.suse.cz/tests/6010#)
- [leap15.2](http://kepler.suse.cz/tests/6012#)
- [sle15sp3](http://kepler.suse.cz/tests/6015#step/verify_efi_mok/516)
- [sle15sp2](http://kepler.suse.cz/tests/6016#step/verify_efi_mok/1)
> Adapt uefi test case for Updates test scenario

- tests/console/zypper_lifecycle_toolchain.pm
gcc on the top is expected to be the latest and not installed
zypper se -t package 'gcc>10'|awk '/\s+gcc[0-9]+\s+/ {print$2}'
Example for explanation:
zypper se -t package 'gcc>6'|awk '/\s+gcc[0-9]+\s+/ {print$2$3}'
gcc10|
gcc10|
|gcc7
|gcc7
|gcc7
|gcc7
|gcc7
|gcc7
|gcc7
gcc8|
gcc9|
gcc9|
gcc9|
- Related ticket: https://progress.opensuse.org/issues/93186
http://dzedro.suse.cz/tests/18586#step/zypper_lifecycle_toolchain/30
http://dzedro.suse.cz/tests/18585#step/zypper_lifecycle_toolchain/24 used gcc9 as example with EOS Now to fail
> Change toolchain lifecycle to fail when latest gcc has EOS Now

- tests/console/zypper_lifecycle.pm
Release data is being fixed within https://jira.suse.com/browse/MSC-70
- Related ticket: https://progress.opensuse.org/issues/95593
http://dzedro.suse.cz/tests/18616 15
http://dzedro.suse.cz/tests/18617 12-SP4
http://dzedro.suse.cz/tests/18618 15-SP3
https://openqa.suse.de/tests/6475553 12-SP3
https://openqa.suse.de/tests/6475575 12-SP5
https://openqa.suse.de/tests/6475577 15-SP1
https://openqa.suse.de/tests/6475583 15-SP2
> Fix regex for lifecycle output

- tests/console/zypper_lifecycle.pm
When run 'zypper lifecycle' as a non-root user, sometimes it'll complain of  "failed to create metadata 
cache dir". We need to make sure that we have a clean cache dirs that have the latest solv and raw metadata files.
- Related ticket: https://progress.opensuse.org/issues/91407
- Needles: N/A
https://openqa.nue.suse.com/tests/6389428#step/zypper_lifecycle/1
https://openqa.nue.suse.com/tests/6416643#step/zypper_lifecycle/11
https://openqa.nue.suse.com/tests/6453804#step/zypper_lifecycle/11
https://openqa.nue.suse.com/tests/6453805#step/zypper_lifecycle/11
https://openqa.nue.suse.com/tests/6455374#step/zypper_lifecycle/9
https://openqa.nue.suse.com/tests/6455372#step/zypper_lifecycle/9
latest result:
ARM: 
https://openqa.nue.suse.com/tests/6463967#step/zypper_lifecycle …
> Fix zypper lifecycle failed to create metadata cache dir

- data/journal_check/bug_refs.json
- Verification run: https://openqa.opensuse.org/tests/1847356
> data/journal_check/bug_refs.json: boo#1188270 also applies to 15.3

- data/journal_check/bug_refs.json
- Verification run: https://openqa.opensuse.org/t1847427
> Add boo#1188444 to list of known bugs

- tests/network/samba/samba_adcli.pm
poo#91950 requires the user to invalidate the stored password and then update the password again using the adcli --add-samba-data option.
- Related ticket: https://progress.opensuse.org/issues/91950
⋅⋅x86_64: [tumbleweed](http://angmar.suse.de/tests/3594) | [15 sp3](http://angmar.suse.de/tests/3587) | [15 sp2](http://angmar.suse.de/tests/3588) | [15 sp1](http://angmar.suse.de/tests/3589) | [12 sp5](http://angmar.suse.de/tests/3590)
⋅⋅aarch64: [15 sp2](https://openqa.suse.de/tests/6475980#)
⋅⋅s390: not scheduled due to https://progress.opensuse.org/issues/95611
> Update machine password with adcli --add-samba-data

- schedule/yast/installer_extended/installer_extended.yaml
- schedule/yast/installer_extended/installer_extended_opensuse.yaml
- Related ticket: [poo#94883](https://progress.opensuse.org/issues/94883)
> Schedule switch_keyboard_layout only in non-VNC installation

- lib/openscaptest.pm
On recent TW, neither /etc/securetty nor /usr/etc/securetty exist anymore,
which means that all ttys are allowed. This is a valid state for the oscap
test so handle it properly. Restore the initial state as well.
Verification run: http://10.160.67.85/tests/1024
CC @lilyeyes
> lib/openscaptest.pm: Deal with no securetty config on Tumbleweed

- tests/security/grub_auth/grub_authorization.pm
Reverts os-autoinst/os-autoinst-distri-opensuse#12926
Haven't see @okurz comment, sorry for that. Then I reverts it.
> Revert "Handle UEFI Firmwre Settings for grub_auth test"

- tests/autoyast/installation.pm
Related ticket: https://progress.opensuse.org/issues/94756
> Change maintainer for AutoYaST installation module

- lib/thunderbird_common.pm
- Fail: https://openqa.suse.de/tests/6502807#step/thunderbird_pop/18
- Verification run: http://dzedro.suse.cz/tests/18681
> Wait after pressing alt-n to avoid typo

- lib/x11utils.pm
Handle gnome-activities in ensure_unlocked_desktop
Update the codes of handling gnome-activities in handle_login
Missing in #12883, as I mentioned in https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/12924#issuecomment-883257409, the multi_users_dm failed caused. ensure_unlocked_desktop need to be updated to handle gnome-activities
- Needles: N/A
- extra_tests_gnome https://openqa.opensuse.org/tests/1848768#step/multi_users_dm/47
- otherDE_lxqt https://openqa.opensuse.org/tests/1849887
- extra_tests_on_kde https://openqa.opensuse.org/tests/1849877
> lib/x11utils.pm: Handle gnome-activities in ensure_unlocked_desktop

- tests/installation/await_install.pm
- Related ticket: https://progress.opensuse.org/issues/93949#change-418507
- Needle: https://github.com/os-autoinst/os-autoinst-needles-opensuse/blob/21fb2464cd0030c7ba1aabafa8594b39ed585366/await_install-gui-installation-20210712.png
- Verification run(s): 
- https://openqa.opensuse.org/tests/1837750
- https://openqa.opensuse.org/tests/1837830
- https://openqa.opensuse.org/tests/1837838
> Add password possibility to await_install.pm for s390x

- data/autoyast_qam/15_installtest.xml.ep
- schedule/qam/common/create-QAM-Installtest.yaml
- Fail: https://openqa.suse.de/tests/6508381
- Verification run: https://openqa.suse.de/tests/6510717
> Fix the old/new autoyast xml element on 15 SP3

- tests/qam-updinstall/update_install_mr.pm
https://openqa.suse.de/tests/6517804 x86_64
https://openqa.suse.de/tests/6517803 s390x
https://openqa.suse.de/tests/6517802 ppc64le
https://openqa.suse.de/tests/6517801 aarch64
> Use serial console on Maintenance install MR

- tests/installation/bootloader_uefi.pm
Added leap upgrade to sle test workflow for uefi
Need support uefi test scenario for leap upgrade to sle
- Related ticket:https://progress.opensuse.org/issues/92650
- Verification run: https://openqa.suse.de/tests/6514986#
Verified opensuse: https://openqa.opensuse.org/tests/1856894#
Verified security case: https://openqa.suse.de/tests/6566995
> Added leap upgrade to sle test workflow for uefi

- tests/x11/oomath.pm
- Related ticket: https://progress.opensuse.org/issues/91275
http://dzedro.suse.cz/tests/18710 Leap 15.3
http://dzedro.suse.cz/tests/18709 TW
http://dzedro.suse.cz/tests/18703 SLE 15 SP3
> oomath: Remove workaround for bsc#1184961

- data/qam/mdadm.sh
- Fail: https://openqa.suse.de/tests/6547068#step/mdadm/7
- Verification run: http://dzedro.suse.cz/tests/18712#step/mdadm/9
> Speedup mdadm with use of fallocate instead dd

- lib/consoletest.pm
This modifies the `consoletest` base module in a way that the Public Cloud instance will be destroyed in case of fatal test module fails.
- Failure: https://openqa.suse.de/tests/6414937#step/journalctl/44
- Verification run: http://pdostal-server.suse.cz/tests/12367#step/system_prepare/166
> Destroy PublicCloud instance when fatal test fails

- tests/boot/grub2_test.pm
- Related ticket: https://progress.opensuse.org/issues/95691
- Verification run: http://dzedro.suse.cz/tests/18719
> Temporary disable grub2 menu test

- lib/YuiRestClient.pm
- schedule/yast/remote_ssh/remote_ssh_controller_sle15.yaml
- schedule/yast/remote_vnc/remote_vnc_controller.yaml
- schedule/yast/ssh-x.yaml
- tests/installation/addon_products_sle.pm
Some quick fixes coming from review of build 16.3 in SLE-15-SP4
- Job group: [mr#359](https://gitlab.suse.de/qsf-y/qa-sle-functional-y/-/merge_requests/359)
- Verification run: [SLES](https://openqa.suse.de/tests/overview?distri=sle&version=15-SP4&build=jknphy%2Fos-autoinst-distri-opensuse%23adjustments_sle15sp4)
> Fix schedules still not using libyui

- .github/workflows/ci.yml
See related change https://github.com/os-autoinst/os-autoinst/pull/1732
> Update perltidy to 20210717

- tests/hpc/rasdaemon.pm
- Related ticket: https://progress.opensuse.org/issues/95126 #12935
- Verification run: https://openqa.suse.de/tests/6591180
> Fix the inject error condition

- lib/publiccloud/provider.pm
- Related ticket: https://progress.opensuse.org/issues/95266
> Public Cloud: increase max retries for Vault login

- tests/publiccloud/instance_overview.pm
- Related ticket: [poo#95104](https://progress.opensuse.org/issues/95104)
> Public Cloud: Do not upload zypper log in instance_overview.pm

- tests/boot/grub2_test.pm
- Related ticket: https://progress.opensuse.org/issues/95691 #12983
- Verification run: http://dzedro.suse.cz/tests/18743#step/grub2_test/21
> grub2: Create fake menu entry test

- lib/y2_module_consoletest.pm
- schedule/qam/QR/15-SP2/gpt.yaml
- schedule/qam/QR/15-SP3/gpt.yaml
- schedule/qam/QR/15-SP3/raid/raid1_sle_gpt.yaml
- test_data/qam/QR/15-SP3/encryption/lvm_encrypt_separate_boot.yaml
- test_data/qam/QR/15-SP3/lvm_raid1/lvm+raid1_hyperv_uefi.yaml
- tests/installation/addon_products_sle.pm
- Related ticket: https://progress.opensuse.org/issues/96302
- Verification runs: https://openqa.suse.de/tests/6618881, https://openqa.suse.de/tests/6618921
> Fix YaST-related tests in QR Updates for SP3

- schedule/qam/QR/15-SP3/raid/raid1_sle_gpt.yaml
> Remove beta popup checking for RAID1 QEM

- tests/console/libgcrypt.pm
- Verification run: http://pdostal-server.suse.cz/tests/12432#details
> libgcrypt: Download libgcrypt-selftest.c if needed

- schedule/qam/common/mau-extratests2.yaml
- Related ticket: https://progress.opensuse.org/issues/96513
http://dzedro.suse.cz/tests/18787 12 SP2
http://dzedro.suse.cz/tests/18788 12 SP3
http://dzedro.suse.cz/tests/18789 12 SP4
http://dzedro.suse.cz/tests/18790 12 SP5
http://dzedro.suse.cz/tests/18791 15
http://dzedro.suse.cz/tests/18792 15 SP1
http://dzedro.suse.cz/tests/18793 15 SP2
http://dzedro.suse.cz/tests/18794 15 SP3
> Unschedule samba_adcli on 12-SP2

- schedule/qam/common/mau-extratests1.yaml
- tests/console/irqbalance.pm
This is a smoketest of `irqbalance` package.
The plan is to extend this test in later pull request.
- Related ticket: [poo#92815](https://progress.opensuse.org/issues/92815) [bsc#1178477](https://bugzilla.suse.com/show_bug.cgi?id=1178477)
- Verification run: [15-SP3](http://pdostal-server.suse.cz/tests/12449)
> Introduce irqbalance test module

- tests/console/php7_postgresql.pm
Reverts os-autoinst/os-autoinst-distri-opensuse#13031
> Revert "Add workanound for slow posgresql start on ARM/ppc64le"

- schedule/sle-perf/hana_install.yaml
Add fix_sle_15gm_multi_disks for ppc64le sle-15 installation.
- Verification run: http://openqa.qa2.suse.asia/tests/overview?distri=sle&version=15&build=GM&groupid=30
> Improve schedule YAML file to fix sle-15 install for ppc64le

- data/journal_check/bug_refs.json
Add know bugs for slem5.1@zkvm and sle15sp4@aarch64
> Add hypfs bug, ITS aarch64 for sle15sp4

- data/journal_check/bug_refs.json
Request from RM for RC release phase.
- Verification run: https://openqa.suse.de/tests/6869800#step/journal_check/21
> SLE Micro: add soft failure for bsc#1188215

- tests/console/sshd.pm
As mentioned in poo#97016 sshd fails to start in 15 SP2 when FIPS is enabled. A bug has been created (bsc#1189534) and the sshd openqa module will now soft_fail when fialing to start under enabled FIPS.
- Related ticket: https://progress.opensuse.org/issues/97016
- Verification run: [softfailing with FIPS](http://angmar.suse.de/tests/3757#step/sshd/9) | [passing without FIPS](http://angmar.suse.de/tests/3758#)
> Softfail sshd service failure under FIPS

- tests/sles4sap/hana_install.pm
There is a sporadic issue with `sles4sap/hana_install` in MACHINE 64bit-ipmi-nvdimm in osd which is tracked in [poo#96833](https://progress.opensuse.org/issues/96833). This PR attempts to fix it by removing DM structures earlier with `dmsetup remove` before any calls to `lvremove`, `vgremove` and `pvremove`.
In cases where this is not enough, the test will fail with a reference to the poo ticket, and will attempt to gather more details during the failure to further debug the issue.
- Related ticket: https://progress.opensuse.org/issues/96833 & https://jira.suse.com/browse/TEAM-4526
- Needles: N/A
- Verification runs (original PR): https://openqa.suse.de/t6838584 - https://openqa.suse.de/t6838585
- Verification runs (remove LV with dmsetup before lvremove): …
> Remove LV with dmsetup remove before lvremove in sles4sap/hana_install

- tests/console/rpm.pm
- Related error: https://openqa.suse.de/tests/6924871#step/rpm/105
- Verification run: http://pdostal-server.suse.cz/tests/12458#step/rpm/103
> console/rpm test module --changelog timeout

- schedule/sle-micro/containers.yaml
- Related ticket: https://progress.opensuse.org/issues/97292
> Sle micro containers fix

- lib/consoletest.pm
- lib/susedistribution.pm
- tests/publiccloud/ssh_interactive_init.pm
- tests/publiccloud/ssh_interactive_start.pm
- Follow up: #13124 
- Verification run: http://pdostal-server.suse.cz/tests/12468#downloads
> Public Cloud: Do not print ssh debug but upload it in case of failure

- lib/Installation/Registration/RegistrationController.pm
- lib/Installation/Registration/RegistrationPage.pm
- lib/Installation/Warnings/ConfirmationWarning.pm
- lib/Installation/Warnings/ConfirmationWarningRichText.pm
- schedule/yast/ext4/ext4@yast.yaml
- schedule/yast/skip_registration/skip_registration.yaml
- tests/installation/registration/register_via_scc.pm
- tests/installation/registration/skip_registration.pm
- Related ticket: https://progress.opensuse.org/issues/95476
- Verification run: http://waaa-amazing.suse.cz/tests/15651
> Add a module for skipping registration with libyui-rest-api 

- lib/y2_installbase.pm
Based on feedback from [bsc#1189550](https://bugzilla.suse.com/show_bug.cgi?id=1189550#c16) we can improve the workaround and avoid failure in latest build in SLE-15-SP4.
- Related ticket: [poo#97760](https://progress.opensuse.org/issues/97760) | [previous workaround](https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/13087)
- Verification run: [mru-install-minimal-with-addons + select_modules_and_patterns](https://openqa.suse.de/tests/overview?distri=sle&build=jknphy%2Fos-autoinst-distri-opensuse%23change_workaround_scrollbar)
> Rewrite workaround for scrolling for bsc#1189550

- schedule/sle-micro/dvd.yaml
https://progress.opensuse.org/issues/97820
Easy and quick request from https://bugzilla.suse.com/show_bug.cgi?id=1189807#c2
> SLE Micro: add SELinux test for DVD flavor

- schedule/sle-micro/dvd_virt.yaml
- VR: [sle-micro-5.1-DVD-x86_64-Build57.3_12.13-sle-micro_installation+qemu@64bit](http://kepler.suse.cz/tests/6734#live)
- MR: https://gitlab.suse.de/qac/qac-openqa-yaml/-/merge_requests/398
> Execute QEMU smoke tests in SLEM5.1 DVD

- tests/publiccloud/instance_overview.pm
Add more information that is collected and stored by `instance_overview`. Those information are useful to verify different machine types (e.g. for https://progress.opensuse.org/issues/61091).
- Verification run: https://duck-norris.qam.suse.de/tests/7203 (cancelled after `instance_overview`)
> Improve information collected by instance_overview

- data/qam/mdadm.sh
- Related ticket: https://progress.opensuse.org/issues/97844
- Verification run: https://openqa.suse.de/tests/7013067
> mdadm: Sync after deleting of image

- schedule/security/build_nested_hdd.yaml
- tests/security/cc/build_nested_hdd.pm
- Related ticket: https://progress.opensuse.org/issues/97796
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/7013681
> Build nested virtualization hdd image

- lib/publiccloud/gce.pm
Fixing minor issue caused by #13183 . 
Example of the issue https://openqa.suse.de/tests/7036605#step/img_proof/2 
VR: http://autobot.qa.suse.de/tests/2545
> publiccloud: follow up fix for #13183

- lib/migration.pm
In deregister_dropped_modules if we set SCC_ADDONS with ltss
and set DROPPED_MODULES=python2, it'll set SCC_ADDONS to null.
- Related ticket: https://progress.opensuse.org/issues/98060
- Needles: N/A
https://openqa.nue.suse.com/tests/7039626
https://openqa.nue.suse.com/tests/7039627
https://openqa.nue.suse.com/tests/7039628
https://openqa.nue.suse.com/tests/7039487
regression:
https://openqa.nue.suse.com/tests/7047115
https://openqa.nue.suse.com/tests/7047113
https://openqa.nue.suse.com/tests/7047545
https://openqa.nue.suse.com/tests/7047544
> Fix deregister_dropped_modules set SCC_ADDONS to null

- schedule/sles4sap/hana/pvm_hana_cluster_node.yaml
Add sle-15-SP4 to the cluster_setup schedule
Would be nice to make this a wildcard setting, but I'm not sure how or even if thats possible.
> add 15-SP4 to cluster_setup in pvm_hana_cluster_node.yaml

- schedule/sle-micro/dvd_virt.yaml
- tests/installation/installation_overview.pm
- tests/qemu/qemu.pm
- Related ticket: https://progress.opensuse.org/issues/98090
> SLE Micro: add patterns module to DVD installation

- schedule/publiccloud/ha_sap.yml
Fix tests to support latest PC code changes.
Also convert all tests to YAML format.
- Needles: N/A
- Merge Request: https://gitlab.suse.de/qac/qac-openqa-yaml/-/merge_requests/414
- Verification runs: http://1b210.qa.suse.de/tests/overview?groupid=17&build=0081&version=15-SP3&distri=sle
> Fix HA/SAP Public Cloud tests

- tests/containers/docker_image.pm
- tests/containers/podman_image.pm
- Related ticket: https://progress.opensuse.org/issues/97430
- [on Leap 15.2](https://openqa.suse.de/tests/7068629)
- [on Leap 15.3](https://openqa.suse.de/tests/7068630)
- [on CentOS](https://openqa.suse.de/tests/7068632)
- [on SLE](https://openqa.suse.de/tests/7068631)
> Containers: Use python3 dockerfile for openSUSE

- install_deps.sh
See also: https://github.com/os-autoinst/openQA/pull/4194
Ticket: https://progress.opensuse.org/issues/97751
> Install test distri deps in worker container on entrypoint

- data/qam/mdadm.sh
- Related ticket: https://progress.opensuse.org/issues/97844
- Verification run: https://openqa.suse.de/tests/7099166
> mdadm: Sync also after creating of image

- tests/console/system_prepare.pm
Do registration for media upgrade cases at system_prepare module.
As we need do regression test after media upgrade, we should register
the modules before regression
Changed the check conditions, as we only can do register at regression job group. The rule is very strictly. I changed it to use setting. It can do register wherever users want. It should not check scc_addons, as some module is registered by default. So I remove this condition. And the upgrade path from sles12+ to sles15+. It will add some modules by default. 
- Related ticket:https://progress.opensuse.org/issues/98195
- Verification run: https://openqa.suse.de/tests/7068280
- https://openqa.suse.de/tests/7097714#
> Do registration for media upgrade cases at system_prepare module

- lib/publiccloud/provider.pm
All added openqa vars get a prefix `openqa_var_`. The following
variables are added by default:
```
JOB_ID (retrieved by mmapi::get_current_job_id()
NAME
```
- Ticked: https://progress.opensuse.org/issues/63604
- Verification run: https://openqa.suse.de/tests/7090717
- PCW view: https://publiccloud.qa.suse.de/instances?&state=UNK&state=ACTIVE&state=DELETING&state=DELETED&instance_id=i-09ef257cd523f82d1
> publiccloud: Add openqa VARs as instance tags

- tests/xfstests/install.pm
- tests/xfstests/partition.pm
Collect test environment information. Upload version.log and local.config for reference
- Related ticket: https://progress.opensuse.org/issues/98316
- Needles: N/A
- http://10.67.133.102/tests/371#downloads
- http://10.67.133.102/tests/372#downloads
> xfstests: upload version.log and xfstest configure file for reference

- tests/containers/bci_tests.pm
https://progress.opensuse.org/issues/98183
> Containers: add gcc package to the host OS

- data/virt_autotest/guest_params_xml_files/sles_12_sp5_64_kvm_hvm_uefi_with_power_management_x86_64.xml
- data/virt_autotest/guest_params_xml_files/sles_12_sp5_64_xen_hvm_uefi_with_power_management_x86_64.xml
- data/virt_autotest/guest_params_xml_files/sles_15_sp3_64_kvm_hvm_uefi_without_power_management_x86_64.xml
- data/virt_autotest/guest_params_xml_files/sles_15_sp3_64_xen_hvm_uefi_with_power_management_x86_64.xml
- data/virt_autotest/guest_params_xml_files/sles_15_sp3_64_xen_hvm_uefi_without_power_management_x86_64.xml
- data/virt_autotest/guest_params_xml_files/sles_15_sp4_64_kvm_hvm_uefi_without_power_management_x86_64_using_virtmanagerlt3.0.0.xml
- data/virt_autotest/guest_unattended_installation_files/sles_12_plus_kvm_hvm_guest_graphical_x86_64.xml
- data/virt_autotest/guest_unattended_installation_files/sles_12_plus_kvm_hvm_guest_multi-user_x86_64.xml
- data/virt_autotest/guest_unattended_installation_files/sles_12_plus_xen_hvm_guest_graphical_x86_64.xml
- data/virt_autotest/guest_unattended_installation_files/sles_12_plus_xen_hvm_guest_multi-user_x86_64.xml
- data/virt_autotest/guest_unattended_installation_files/sles_12_plus_xen_paravirt_guest_graphical_x86_64.xml
- data/virt_autotest/guest_unattended_installation_files/sles_12_plus_xen_paravirt_guest_multi-user_x86_64.xml
- data/virt_autotest/guest_unattended_installation_files/sles_15_plus_kvm_hvm_guest_graphical_x86_64.xml
- data/virt_autotest/guest_unattended_installation_files/sles_15_plus_kvm_hvm_guest_multi-user_x86_64.xml
- data/virt_autotest/guest_unattended_installation_files/sles_15_plus_xen_hvm_guest_graphical_x86_64.xml
- data/virt_autotest/guest_unattended_installation_files/sles_15_plus_xen_hvm_guest_multi-user_x86_64.xml
- data/virt_autotest/guest_unattended_installation_files/sles_15_plus_xen_paravirt_guest_graphical_x86_64.xml
- data/virt_autotest/guest_unattended_installation_files/sles_15_plus_xen_paravirt_guest_multi-user_x86_64.xml
* **Align** all sles autoyast files more strictly with document and fact. So they are clearer and more robust now.
* **Modify** guest profiles
* sles_15_sp3_64_kvm_hvm_uefi_with_power_management_x86_64.xml
* sles_15_sp3_64_kvm_hvm_uefi_without_power_management_x86_64.xml
* sles_15_sp3_64_xen_hvm_uefi_with_power_management_x86_64.xml 
* sles_15_sp3_64_xen_hvm_uefi_without_power_management_x86_64.xml 
to have 15-SP3 GM build installation media.
* **New** guest profiles 
* sles_12_sp5_64_kvm_hvm_uefi_with_power_management_x86_64.xml
* sles_12_sp5_64_xen_hvm_uefi_with_power_management_x86_64.xml
* sles_15_sp4_64_kvm_hvm_uefi_without_power_management_x86_64_using_virtmanagerlt3.0.0.xml
to support more uefi test scenarios.
* [oracle linux on 15sp4 kvm …
> New and improved provisions for unified guest installation

- variables.md
- Related ticket: [poo#98292](https://progress.opensuse.org/issues/98292)
> Add all PUBLIC_CLOUD_ variables to variables.md

- tests/publiccloud/prepare_tools.pm
VR: http://autobot.qa.suse.de/tests/2550
> publiccloud: export img_proof version into variable

- schedule/yast/btrfs/btrfs_sle_libstorage-ng.yaml
- schedule/yast/btrfs/btrfs_sle_libstorage-ng@ipmi.yaml
- schedule/yast/btrfs/btrfs_sle_libstorage-ng_s390x_zvm.yaml
- schedule/yast/textmode_installation_minimal_role/textmode_installation_minimal_role.yaml
- schedule/yast/textmode_installation_minimal_role/textmode_installation_minimal_role@s390x.yaml
- schedule/yast/usb_install.yaml
- schedule/yast/yast_hostname/yast_hostname+dhcp_hostname.yaml
- schedule/yast/yast_hostname/yast_hostname+linuxrc_hostname.yaml
- schedule/yast/yast_hostname/yast_hostname.yaml
- schedule/yast/yast_no_self_update/yast_no_self_update.yaml
- schedule/yast/yast_no_self_update/yast_no_self_update_pvm.yaml
- schedule/yast/yast_self_update/yast_self_update.yaml
- schedule/yast/yast_self_update/yast_self_update_pvm.yaml
- Related ticket: [poo#97973](https://progress.opensuse.org/issues/97973)
- Verification run: [SLE](https://openqa.suse.de/tests/overview?distri=sle&version=15-SP4&build=jknphy%2Fos-autoinst-distri-opensuse%23fix_schedules_registration)
> Fix schedules in registration in YaST group

- lib/registration.pm
Save time to reviewers by specifying what's the problem (or a possible cause)
https://openqa.suse.de/t7150168
> Add notice to PackageHub enablement in early development

- lib/Tomcat/Utils.pm
- Related ticket: https://progress.opensuse.org/issues/98982
https://openqa.suse.de/tests/7182783
https://openqa.suse.de/tests/7182879
https://openqa.suse.de/tests/7182896
> tomcat: Wait before clicking on save password

- lib/qam.pm
- Related ticket: https://progress.opensuse.org/issues/90522
http://dzedro.suse.cz/tests/19377
http://dzedro.suse.cz/tests/19378
https://openqa.suse.de/tests/7182935
https://openqa.suse.de/tests/7182936
https://openqa.suse.de/tests/7182937
https://openqa.suse.de/tests/7182938
> Add Ericsson update repo

- lib/qam.pm
- Related ticket: https://progress.opensuse.org/issues/90522 #13299 
https://openqa.suse.de/tests/7183320
https://openqa.suse.de/tests/7183321
https://openqa.suse.de/tests/7183322
https://openqa.suse.de/tests/7183323
> Fix missing url variable

- lib/kdump_utils.pm
- Related ticket: https://progress.opensuse.org/issues/99048
- Verification run: http://dzedro.suse.cz/tests/19409
> systemtap: Add Ericsson debuginfo repo on 12 SP2

- tests/cpu_bugs/mitigation_perf.pm
Adjust mitigation performance code to adapt slePerf and vt-perf-run code change
- Needles:N/A
- Verification run: http://openqa.qa2.suse.asia/tests/37101
> Adjust code to adapt slePerf & vt-perf-runchange

- tests/xfstests/partition.pm
- Related ticket: https://progress.opensuse.org/issues/98316
- Needles: N/A
http://10.67.133.102/tests/377
http://10.67.133.102/tests/378
>  xfstests: record versions and partition size for reference

- tests/installation/logs_from_installation_system.pm
In "Common Criteria System Role" system, root ssh login
is disabled by default, we need enable it on 390x to fit openQA
tests. btw, Enhance the code to locate the root disk rather than
hardcode the disk name
- Related ticket: https://progress.opensuse.org/issues/98715
x86_64: https://openqa.suse.de/tests/7200097#
arm:       https://openqa.suse.de/tests/7200098#
s390x:   https://openqa.suse.de/tests/7200087#
> Permit root ssh for system with CC system role

- lib/publiccloud/provider.pm
This is a follow up for https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/13289
and try to address the issue with SLES4SAP terraform profiles.
- Ticked: https://progress.opensuse.org/issues/63604
- Verification run: http://1b210.qa.suse.de/t9265
> publiccloud: Do not add region for PUBLIC_CLOUD_SLES4SAP on destroy

- tests/virtualization/universal/save_and_restore.pm
This PR fixes an issue with previous [PR](https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/13279) 
- Needles: NA
- Validation run : http://d488.qam.suse.de/tests/387
> Save and restore fix

- data/journal_check/bug_refs.json
- Verification run: https://openqa.opensuse.org/tests/1940850#live
> Extend data/journal_check/bug_refs.json for 15.3 ARM

- lib/nfs_common.pm
In yast2-nfs-server we disabled the rpcbind and rpcbind.socket
service. This will cause the following rpcbind test to fail. We need
to cleanup all yast2-nfs-server related configure and restart the
rpcbind and rpcbind.socket service in check_upgraded_service.
- Related ticket:  https://progress.opensuse.org/issues/97259
- Needles: N/A
https://openqa.nue.suse.com/tests/7234239 
https://openqa.nue.suse.com/tests/7234273
https://openqa.nue.suse.com/tests/7234274
> Fix rpcbind inactive in check_upgraded_service after migration

- tests/sles4sap/saptune/mr_test.pm
Required changes for testing saptune v3 by @scmschmidt
- Specific SAP note: http://ix64hae1001.qa.suse.de/tests/2273
- All notes: http://ix64hae1001.qa.suse.de/tests/2275
- All solutions: http://ix64hae1001.qa.suse.de/tests/2276
- Delete/rename functionality: http://ix64hae1001.qa.suse.de/tests/2278
Note: Tested with new changes to mr_test repo submitted by Sören.
> Required changes for testing saptune v3 by @scmschmidt

- schedule/jeos/sle/jeos-extratest.yaml
- [sle15sp2](http://kepler.suse.cz/tests/6840#step/evolution_prepare_servers/1)
- [sle15sp4](http://kepler.suse.cz/tests/6838#step/evolution_prepare_servers/1)
> Add dovecot and postfix test

- data/containers/autoyast_containers.xml.ep
- Related ticket: https://progress.opensuse.org/issues/93817
- VR: https://openqa.suse.de/tests/overview?flavor=Container-Host&groupid=377&build=GM
- 15-SP4: https://openqa.suse.de/tests/overview?distri=sle&version=15-SP4&build=43.1&groupid=313&test=create_hdd_autoyast_containers
> Containers: minor adjustments in autoyast profile

- tests/containers/buildah_docker.pm
- tests/containers/buildah_podman.pm
- Related ticket: https://progress.opensuse.org/issues/99750
- Verification run: https://openqa.suse.de/tests/7318680#step/buildah_podman/116
> container: Use BETA variable only for know beta versions

- schedule/qam/QR/15-SP3/textmode/textmode.yaml
Missing fix to schedule related with #13369 
- Related ticket: [poo#96803](https://progress.opensuse.org/issues/96803)
> fix schedule textmode in qam

- schedule/functional/external_iso.yaml
see https://progress.opensuse.org/issues/68527
and https://progress.opensuse.org/issues/99717
verifications:
http://10.162.30.85/tests/3761 (sles)
http://10.162.30.85/tests/3766 (Tumbleweed)
> Add yaml schedule for test 'external_iso'

- tests/virt_autotest/guest_migration_dst.pm
- Description:
Before kernel v5.11, The default value of unprivileged_userfaultfd sysctl is 1,
It means using the userfaultfd syscalls is allowed by unprivileged users.
Since kernel v5.11(current 5.14 for 15-SP4),  The default value of unprivileged_userfaultfd sysctl is
set to 0, In this case, The UFFD_USER_MODE_ONLY is needed if unprivileged
user(without SYS_CAP_PTRACE capability) want to use userfaultfd syscalls.
So, need to reset unprivileged_userfaultfd value on guest live migration dst - 15-SP4 KVM for our OSD guest migration test
- Related ticket: https://progress.opensuse.org/issues/100659
[virt-guest-migration-developing-from-developing-to-developing-kvm-dst](https://openqa.suse.de/tests/7527240#)
[virt-guest-migration-developing-from-developing-to-developing-k …
> [virt_autotest] reset unprivileged_userfaultfd value for guest migration

- lib/publiccloud/ssh_interactive_init.pm
- Related message: https://suse.slack.com/archives/C02CGKBCGT1/p1635777878283600
> publiccloud: Include script_retry as its needed

- tests/containers/rootless_podman.pm
Add a check for bsc1192051 in `rootless_podman` and skip the test run if present. 
This bug breaks the s390x and ppc64le test runs for `rootless_podman`.
- Related ticket: https://progress.opensuse.org/issues/101280
- Verification run: [15-SP3 aarch64](https://openqa.suse.de/t7590883) | [15-SP3 s390x](https://openqa.suse.de/t7590884) | [15-SP3 x86_64](https://openqa.suse.de/t7590885) | [15-SP4 ppc64le](https://openqa.suse.de/t7590886) | [Tumbleweed](https://openqa.opensuse.org/t2009567)
> Add check for bsc1192051

- lib/Mitigation.pm
- tests/virt_autotest/login_console.pm
Fix some issue and needle matching problems for 15sp4
- Needles: N/A
- Verification run: http://openqa.qa2.suse.asia/tests/39469
> Fix mitigation test issue for 15sp4

- data/apparmor/usr.sbin.httpd-prefork-sle12
- Related ticket: https://progress.opensuse.org/issues/101181
https://openqa.suse.de/tests/7591991 15 SP3
https://openqa.suse.de/tests/7591990 12 SP5
https://openqa.suse.de/tests/7592060 12 SP4
http://dzedro.suse.cz/tests/19869 TW
> apache2_changehat: Update apparmor profile

- lib/containers/basetest.pm
- tests/containers/container_diff.pm
- tests/containers/docker.pm
- tests/containers/docker_3rd_party_images.pm
- tests/containers/docker_compose.pm
- tests/containers/docker_image.pm
- tests/containers/docker_runc.pm
- tests/containers/podman.pm
- tests/containers/podman_3rd_party_images.pm
- tests/containers/podman_image.pm
- tests/containers/registry.pm
- tests/containers/rootless_podman.pm
- tests/containers/validate_btrfs.pm
- tests/containers/zypper_docker.pm
- Related ticket: https://progress.opensuse.org/issues/101442
VRs:
[SLE](https://openqa.suse.de/tests/overview?build=jlausuch%2Fos-autoinst-distri-opensuse%23containers_use_factory&distri=sle&version=15-SP3)
[openSUSE](https://openqa.opensuse.org/tests/overview?version=Tumbleweed&distri=opensuse&build=jlausuch%2Fos-autoinst-distri-opensuse%23containers_use_factory)
> Containers: make use of Factory class

- lib/main_publiccloud.pm
VR : https://openqa.suse.de/tests/7604525
> Add console tests to latest pubcloud testing branch

- tests/installation/partitioning/guided_setup/accept_default_part_scheme.pm
Fixes wrong controller used in test module `accept_default_part_scheme`:
https://openqa.suse.de/tests/7591773#step/accept_default_part_scheme/2
> Fix controller in accept_default_part_scheme

- lib/containers/container_images.pm
The functions are not used anymore on buildah test.
So the condition branches for buildah can be removed as they are dead code in the codebase.
http://aquarius.suse.cz/tests/7380
http://aquarius.suse.cz/tests/7381
> Remove dead code from lib/containers/container_images.pm

- lib/wicked/wlan.pm
- tests/wicked/wlan/sut/t08_multi_networks_autoconnect_wpa_psk.pm
- Related ticket: https://progress.opensuse.org/issues/101969
- Verification run: https://openqa.suse.de/t7611482
> wicked/wlan: Retry hostapd start on failure!

- schedule/yast/lvm_multipath.yaml
Fixes https://openqa.suse.de/tests/7618226#step/select_guided_setup/1
> Accept selected role in lvm_multipath test suite

- tests/xfstests/partition.pm
1. Add more mkfs options for testing xfs. e.g xfs_nocrc, xfs_nocrc_512, xfs_reflink_1024, xfs_reflink_normapbt
2. Expand LOG_DEV from 100MB to 1G
- Related ticket: https://progress.opensuse.org/issues/101349
- xfs-nocrc: http://10.67.133.102/tests/433
- xfs-nocrc_512: http://10.67.133.102/tests/434
- xfs-reflink_normapbt: http://10.67.133.102/tests/435
- xfs-reflink_1024: http://10.67.133.102/tests/436
- xfs-logdev: http://10.67.133.102/tests/438
> xfstests: Add more mkfs.xfs options

- lib/y2_base.pm
- tests/yast2_cmd/yast_dns_server.pm
- tests/yast2_cmd/yast_ftp_server.pm
- tests/yast2_cmd/yast_lan.pm
- tests/yast2_cmd/yast_nfs_client.pm
- tests/yast2_cmd/yast_nfs_server.pm
- tests/yast2_cmd/yast_sysconfig.pm
- tests/yast2_cmd/yast_tftp_server.pm
- tests/yast2_cmd/yast_timezone.pm
- tests/yast2_cmd/yast_users.pm
http://dzedro.suse.cz/tests/19824 12 SP2
http://dzedro.suse.cz/tests/19825 12 SP3
http://dzedro.suse.cz/tests/19826 12 SP4
http://dzedro.suse.cz/tests/19832 12 SP5
http://dzedro.suse.cz/tests/19833 15
http://dzedro.suse.cz/tests/19834 15 SP1
http://dzedro.suse.cz/tests/19835 15 SP2
http://dzedro.suse.cz/tests/19831 15 SP3
http://dzedro.suse.cz/tests/19855 15 SP4
https://openqa.suse.de/tests/7605182 15 SP2
> yast2ui-textmode: Use serial terminal

- tests/console/sshd.pm
The ssh calls in the background spam the serial terminal with debug messages,
which confuses serial input functions, leading to wait_serial not matching
and wasting a minute of waiting for each mismatch.
Write the debug output into log files and display it at the end instead.
Also make use of background_script_run.
- Verification run: http://10.160.67.86/tests/1112
Took 29s instead of 1min50s or more (https://openqa.opensuse.org/tests/2010513#step/sshd/1)
> console/sshd: Improve background calls for port forwarding

- tests/console/snapper_create.pm
VRs:
https://openqa.suse.de/tests/7633345# 
https://openqa.suse.de/tests/7631454
> [rpi] Increase timeout for deleting snapshots

- tests/installation/bootloader_hyperv.pm
* Add [copy /z (Copies networked files in restartable
mode.)](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/copy)
* Skip decompression if decompressed images is already present or unxz
is running in the background on the image file.
Created job #7631291: sle-15-SP4-JeOS-for-MS-HyperV-x86_64-Build1.111-jeos-base+sdk+desktop@svirt-hyperv -> https://openqa.suse.de/t7631291
Created job #7631292: sle-15-SP4-JeOS-for-MS-HyperV-x86_64-Build1.111-jeos-extratest@svirt-hyperv-uefi -> https://openqa.suse.de/t7631292
Created job #7631294: sle-15-SP4-JeOS-for-MS-HyperV-x86_64-Build1.111-jeos-fips@svirt-hyperv-uefi -> https://openqa.suse.de/t7631294
Created job #7631297: sle-15-SP4-JeOS-for-MS-HyperV-x86_64-Build1.111-jeos-main@svirt-hyperv-uefi -> …
> Hyperv decompress images when needed

- lib/main_common.pm
- schedule/jeos/sle/jeos-base+phub.yaml
- schedule/qam/12-SP2/mau-filesystem.yaml
- schedule/qam/12-SP3/mau-filesystem.yaml
- schedule/qam/12-SP4/mau-filesystem.yaml
- schedule/qam/12-SP5/mau-filesystem.yaml
- schedule/qam/15-SP1/mau-filesystem.yaml
- schedule/qam/15-SP2/mau-filesystem.yaml
- schedule/qam/15-SP3/mau-filesystem.yaml
- schedule/qam/15/mau-filesystem.yaml
- tests/network/samba/server.pm
Ticket: https://progress.opensuse.org/issues/99645
Verification: http://kazhua.qa.suse.de/tests/17
> Add samba server test replacing mau-qa_userspace_samba

- lib/Installation/Partitioner/LibstorageNG/v4_3/GuidedSetup/SelectHardDisksController.pm
- schedule/yast/btrfs/btrfs_sle_libstorage-ng.yaml
- schedule/yast/btrfs/btrfs_sle_libstorage-ng@ipmi.yaml
- schedule/yast/btrfs/btrfs_sle_libstorage-ng_s390x_zvm.yaml
- schedule/yast/btrfs/btrfs_sle_libstorage_spvm.yaml
- schedule/yast/encryption/activate_encrypted_volume+force_recompute.yaml
- schedule/yast/encryption/activate_encrypted_volume+force_recompute_pvm.yaml
- schedule/yast/encryption/cryptlvm+cancel_existing.yaml
- schedule/yast/encryption/cryptlvm+cancel_existing_pvm.yaml
- schedule/yast/ext4/ext4@yast-s390x-disk-activation.yaml
- schedule/yast/ext4/ext4@yast-s390x.yaml
- schedule/yast/ext4/ext4@yast-xen-hvm.yaml
- schedule/yast/ext4/ext4@yast-xen-pv.yaml
- schedule/yast/ext4/ext4@yast.yaml
- schedule/yast/ext4/ext4@yast_spvm.yaml
- schedule/yast/select_disk/select_disk.yaml
- schedule/yast/xfs/xfs.yaml
- schedule/yast/xfs/xfs@svirt-xen-hvm.yaml
- schedule/yast/xfs/xfs@svirt-xen-pv.yaml
- schedule/yast/xfs/xfs_spvm.yaml
- tests/installation/partitioning/guided_setup/select_disks.pm
Use LibyuiClient and separate test modules for each page of Guided Setup Wizard.
- Related ticket: https://progress.opensuse.org/issues/96813
- encrypt_lvm_ignore_existing: https://openqa.suse.de/tests/overview?version=15-SP4&groupid=96&distri=sle&build=61.1_ignore_existing
- guided_setup: https://openqa.suse.de/tests/overview?version=15-SP4&groupid=96&distri=sle&build=61.1_guided_setup
> Guided setup schedule

- schedule/yast/opensuse/installer_extended/installer_extended.yaml
- Verification run: [installer_extended](https://openqa.opensuse.org/tests/2026286)
> Add user in installer_extended in O3 with YuiRestClient

- tests/x11/firefox/firefox_emaillink.pm
- Related ticket: https://bugzilla.suse.com/show_bug.cgi?id=1131297
https://openqa.suse.de/tests/7642966
http://dzedro.suse.cz/tests/19950
> emaillink: Remove soft fail on fixed mutt email

- tests/installation/partitioning_smalldisk_storageng.pm
Suggested fix for this failing test:
https://openqa.suse.de/tests/7632872#step/partitioning_smalldisk_storageng/12
VR: https://openqa.suse.de/tests/7643969
> sles4sap: Ignore zram on partitioning

- lib/main_publiccloud.pm
- variables.md
VR : https://openqa.suse.de/tests/7647992
> publiccloud: change variable name to more accurate

- lib/x11utils.pm
- Related ticket: https://progress.opensuse.org/issues/102233
https://openqa.suse.de/tests/7648007 s390x 15 SP4
https://openqa.suse.de/tests/7648437 s390x 15 SP4
https://openqa.suse.de/tests/7648053 aarch64 15 SP3
https://openqa.opensuse.org/tests/2028780 TW x86_64 gnome
https://openqa.opensuse.org/tests/2028781 TW aarch64 gnome
https://openqa.opensuse.org/tests/2028782 TW aarch64 kde
> Wait after authentication and press esc multiple times

- lib/containers/utils.pm
- tests/containers/zypper_docker.pm
- Related ticket: https://bugzilla.suse.com/show_bug.cgi?id=1171672
- VR: https://openqa.suse.de/tests/7654321
> Containers: enable Leap:latest image pull on s390

- data/pam_test/pam_deprecated.sh
- tests/console/pam.pm
As pam_tally2 and pam_cracklib modules are deprecated for >=1.5.0 pam releases, the corresponding tests fail in the testsuite, so they have to be removed
- Related ticket: https://progress.opensuse.org/issues/99039
- Needles: N/A
- Verification run: [Tumbleweed](https://openqa.opensuse.org/tests/2016700#step/pam/41)
- [sles15sp3](https://openqa.suse.de/tests/7613725#step/pam/52) | [sles15sp2
](https://openqa.suse.de/tests/7613728#step/pam/52) | [sles15sp1](https://openqa.suse.de/tests/7613787#step/pam/52) | [sles15](https://openqa.suse.de/tests/7613791#step/pam/52) | [sles12sp5](https://openqa.suse.de/tests/7613792#step/pam/52) | [sles12sp4](https://openqa.suse.de/tests/7613793#step/pam/52) | [sles12sp3](https://openqa.suse.de/tests/7613794#step/pam/52) | …
> Remove deprecated testscases for pam

- lib/power_action_utils.pm
* else if = > elsif
* add spaces
shutdown
* http://quasar.suse.cz/tests/7607 (15-sp4 install_ltp)
* http://quasar.suse.cz/tests/7611 (Tumbleweed install_ltp)
* http://quasar.suse.cz/tests/7610 (15-sp4 yast2_firstboot@64bit)
* http://quasar.suse.cz/tests/7608 (15-sp4 gnome_http)
reboot
* http://quasar.suse.cz/tests/7612 (ima_appraisal)
> power_action: Improve readability

- schedule/qam/common/qam-rmt.yaml
Change schedule file for maintenance cases.
- Related ticket: https://progress.opensuse.org/issues/102380
https://openqa.suse.de/tests/7677282
https://openqa.suse.de/tests/7677283
https://openqa.suse.de/tests/7677456
https://openqa.suse.de/tests/7677457
> Change schedule file for maintenance cases

- lib/opensusebasetest.pm
Fix various issues outlined in the ticket.
See the individual commits for details.
- Related ticket: https://progress.opensuse.org/issues/95275
https://openqa.opensuse.org/tests/2031271 (WIP)
http://10.160.67.86/tests/1131
> Improve IN_X11_START_PROGRAM handling in post_fail_hook

- lib/YaST/Bootloader/BootCodeOptionsPage.pm
- lib/YaST/Bootloader/BootloaderOptionsPage.pm
- lib/YaST/Bootloader/BootloaderSettingsController.pm
- lib/YaST/Bootloader/KernelParametersPage.pm
- lib/YuiRestClient/Widget/Tab.pm
- schedule/yast/btrfs/btrfs_sle_libstorage_spvm.yaml
- schedule/yast/clone_system/clone_system_pvm.yaml
- schedule/yast/encryption/activate_encrypted_volume+force_recompute_pvm.yaml
- schedule/yast/encryption/activate_encrypted_volume_spvm.yaml
- schedule/yast/encryption/crypt_no_lvm_pvm.yaml
- schedule/yast/encryption/cryptlvm+cancel_existing_pvm.yaml
- schedule/yast/encryption/cryptlvm_sle_15_spvm.yaml
- schedule/yast/encryption/lvm_encrypt_separate_boot_pvm.yaml
- schedule/yast/encryption/lvm_full_encrypt_pvm.yaml
- schedule/yast/ext4/ext4@yast_spvm.yaml
- schedule/yast/lvm/lvm+cancel_existing_cryptlvm_pvm.yaml
- schedule/yast/lvm/lvm_sle_spvm.yaml
- schedule/yast/select_disk/select_disk.yaml
- schedule/yast/skip_registration/skip_registration_pvm.yaml
- schedule/yast/transactional_server/create_hdd_transactional_server.yaml
- schedule/yast/xfs/xfs_spvm.yaml
- tests/installation/bootloader_settings/disable_plymouth.pm
Edit optional Kernel params with YuiRestClient
- [poo#102164](https://progress.opensuse.org/issues/102164)
- [poo#98889](https://progress.opensuse.org/issues/98889)
- Verification run: [SLE](https://openqa.suse.de/tests/overview?distri=sle&version=15-SP4&build=jknphy%2Fos-autoinst-distri-opensuse%23disable_plymouth) | [openSUSE](https://openqa.opensuse.org/tests/overview?version=15.3&build=jknphy%2Fos-autoinst-distri-opensuse%23disable_plymouth&distri=opensuse)
> Edit optional Kernel params with YuiRestClient

- lib/containers/engine.pm
Add explaining comments and refactor the code to increase the
readability and get rid of unwanted additional spaces in the resulting
container commands.
- Related ticket: https://progress.opensuse.org/issues/102527
- * [SLES15-SP3 docker aarch64](https://openqa.suse.de/t7699040)
- * [SLES15-SP3 podman aarch64](https://openqa.suse.de/t7699041)
- * [SLES15-SP3 docker x86_64](https://openqa.suse.de/t7699042)
- * [SLES15-SP3 podman x86_64](https://openqa.suse.de/t7698597)
- * [SLES12-SP5 docker x86_64](https://openqa.suse.de/t7699043)
- * [SLES15-SP3 image on 12-SP5 host docker](https://openqa.suse.de/t7698679)
- * [SLES15-SP3 image on 15-SP1 host podman@aarch64](https://openqa.suse.de/t7698680)
- * [SLES15-SP3 image on 15-SP3 host podman](https://openqa.suse.de/t7698681) …
> Improve readability of run_container

- schedule/migration/offline_spvm_Upgrade.yaml
Set some common settings include ORIGIN_SYSTEM_VERSION
and UPGRADE_TARGET_VERSION to yaml file, in case they can't be recognized.
- Related ticket: https://progress.opensuse.org/issues/102488
- Verification run: https://openqa.suse.de/tests/7697729#
> Set common setting to yaml file

- tests/virt_autotest/reboot_and_wait_up.pm
* **SOL** session output for xen host may produce additional messages which may disrupt what is displayed on sol console and then the needle matching, for example, [this may happen on xen host](https://openqa.suse.de/tests/7619536#step/reboot_and_wait_up_upgrade/25).
* **So** xen host needs special treatment to get the login prompt back on screen and then match 'linux-login' needle if 'text-login' can not be done successfully.
* **Remove** duplicate "use ipmi_backend_utils;"
* [sles12sp5 to sles15sp4 xen](https://openqa.suse.de/tests/7609439)
* [sles15sp3 to sles15sp4 xen](https://openqa.suse.de/tests/7609440)
> Adjust needle matching strategy for xen host in reboot_and_wait_up

- schedule/yast/select_modules_and_patterns+registration/select_modules_and_patterns+registration.yaml
Fixes https://openqa.suse.de/tests/7721289.
VR: https://openqa.suse.de/tests/7725500#comments
> Increase QEMURAM in select_modules_and_patterns+registration.yaml

- schedule/yast/autoyast_multi_btrfs.yaml
Fixes https://openqa.suse.de/tests/7716956
> Add QEMURAM to autoyast_multi_btrfs

- tests/fips/gnutls/gnutls_base_check.pm
**Description:**
gnutls attempt to update the major version to 3.7.2+ in SLE15 SP4 base on the Jira feature
_Jira#SLE-[19765](https://jira.suse.com/browse/SLE-19765): Update libnettle and gnutls to new major versions_
This PR is also adding the version check and record_info/soft_failure for gnutls
- Related ticket: https://progress.opensuse.org/issues/102770
- Needles: NA
https://openqa.suse.de/tests/7725188#step/gnutls_base_check/8 (x86_64 - KER mode)
https://openqa.suse.de/tests/7725206#step/gnutls_base_check/8 (aarch64 - ENV mode)
https://openqa.suse.de/tests/7725207#step/gnutls_base_check/8 (s390x - KER mode)
> Add the gnutls update to 3.7.2+ for SLE15-SP4

- lib/containers/docker.pm
- lib/containers/podman.pm
- lib/containers/utils.pm
- tests/containers/docker.pm
- tests/containers/podman.pm
- Related ticket: [poo#94132](https://progress.opensuse.org/issues/94132)
- Verification run: [Docker@SLE15-SP3](http://pdostal-server.suse.cz/tests/12840), [Podman@SLE15-SP3](http://pdostal-server.suse.cz/tests/12840), [Docker@Tumbleweed](http://pdostal-server.suse.cz/tests/12837), [Podman@Tumbleweed](http://pdostal-server.suse.cz/tests/12841), [Containers@SLE15-SP3-EC2](http://pdostal-server.suse.cz/tests/12836)
> Containers: Check firewall with podman

- schedule/security/cc_audit_tests.yaml
Verification run: https://openqa.suse.de/tests/7740832
> Load bootloader_zkvm in CC test when ARCH is s390x

- tests/security/usbguard/usbguard.pm
Fix poo#102921 - [sle][security][sle15sp4] test fails in usbguard on aarch64:
Test usbguard failed on aarch64, after doing "systemctl restart usbguard" at some situations the usb device "keyboard" will be blocked, then add workaround for this.
- Related ticket: https://progress.opensuse.org/issues/102921
- Needles: NA
TW: https://openqa.opensuse.org/tests/2057533
aarch on OSD: https://openqa.suse.de/tests/7746578
> Fix usbguard failure on aarch64

- tests/security/ibmtss/ibmtss_basic_function.pm
When test ibmtss binaries installed onto our system,
we can use the existing certificate files. however,
we should define the right working directory.
[We need test aarch64 platform only]
- Related ticket: https://progress.opensuse.org/issues/103086
- Needles: n/a
https://openqa.opensuse.org/tests/2057535 -TW
https://openqa.suse.de/tests/7746606           -SLE
> Use existing certificate files for ibmtss tests

- lib/main_publiccloud.pm
VRs : 
http://autobot.qa.suse.de/tests/2565
http://autobot.qa.suse.de/tests/2566
http://autobot.qa.suse.de/tests/2567
http://autobot.qa.suse.de/tests/2568
http://autobot.qa.suse.de/tests/2569
http://autobot.qa.suse.de/tests/2570
( all failures can not be related to changes because changes touching only "scheduling part" and loadtest part seems to work correct )
> publiccloud: fix mistakes done during creation of main_publiccloud

- schedule/functional/message.yaml
- Related ticket: https://progress.opensuse.org/issues/103092
- Needles: https://gitlab.suse.de/openqa/os-autoinst-needles-sles/-/merge_requests/1583
- Verification run: https://openqa.suse.de/tests/7746809
> Add hexchat test to SLE

- tests/security/check_kernel_config/CONFIG_FORTIFY_SOURCE.pm
- Remove useless use of cat
- The option is no longer SLE specific
- Simplify code
- Related ticket: https://progress.opensuse.org/issues/102726
- Verification run: https://openqa.opensuse.org/tests/2062545
CC @rfan1
> Improve check_kernel_config/CONFIG_FORTIFY_SOURCE

- data/publiccloud/terraform/ec2.tf
- data/publiccloud/terraform/gce.tf
- Related ticket: [poo#102807](https://progress.opensuse.org/issues/102807)
- Bug example: [sle-15-SP3-EC2-Containers](https://openqa.suse.de/tests/7713114)
- Verification run: [EC2](http://pdostal-server.suse.cz/tests/12889#) [GCE](http://pdostal-server.suse.cz/tests/12887) [Azure](http://pdostal-server.suse.cz/tests/12888)
> Public Cloud: Increase boot disk size

- schedule/yast/select_modules_and_patterns+registration/select_modules_and_patterns+registration.yaml
MR: https://gitlab.suse.de/qsf-y/qa-sle-functional-y/-/merge_requests/379
> Revert RAM increase in select modules and patterns in aarch

- schedule/functional/extra_tests_textmode.yaml
- tests/console/rust.pm
A new project is created and built.
- Related ticket: https://progress.opensuse.org/issues/101073
- Verification run: https://openqa.opensuse.org/tests/2064752#step/rust/9
> Add rust test creating and building a project

- data/autoyast_kvm/sles11sp4x32_PRG.xml
- data/autoyast_kvm/sles11sp4x64_PRG.xml
- data/autoyast_kvm/sles12sp3_PRG.xml
- data/autoyast_kvm/sles12sp4_PRG.xml
- data/autoyast_kvm/sles12sp5_PRG.xml
- data/autoyast_kvm/sles15_PRG.xml
- data/autoyast_kvm/sles15sp1_PRG.xml
- data/autoyast_kvm/sles15sp2_PRG.xml
- data/autoyast_kvm/sles15sp3_PRG.xml
- data/autoyast_xen/sles11sp4HVMx32_PRG.xml
- data/autoyast_xen/sles11sp4HVMx64_PRG.xml
- data/autoyast_xen/sles11sp4PVx32_PRG.xml
- data/autoyast_xen/sles11sp4PVx64_PRG.xml
- data/autoyast_xen/sles12sp3HVM_PRG.xml
- data/autoyast_xen/sles12sp3PV_PRG.xml
- data/autoyast_xen/sles12sp4HVM_PRG.xml
- data/autoyast_xen/sles12sp4PV_PRG.xml
- data/autoyast_xen/sles12sp5HVM_PRG.xml
- data/autoyast_xen/sles12sp5PV_PRG.xml
- data/autoyast_xen/sles15HVM_PRG.xml
- data/autoyast_xen/sles15PV_PRG.xml
- data/autoyast_xen/sles15sp1HVM_PRG.xml
- data/autoyast_xen/sles15sp1PV_PRG.xml
- data/autoyast_xen/sles15sp2HVM_PRG.xml
- data/autoyast_xen/sles15sp2PV_PRG.xml
- data/autoyast_xen/sles15sp3HVM_PRG.xml
- data/autoyast_xen/sles15sp3PV_PRG.xml
- Related failures: [KVM](http://openqa.qam.suse.cz/tests/32461#step/patch_guests/690), [XEN](http://openqa.qam.suse.cz/tests/32471#step/patch_guests/95)
- Verification run: [KVM](http://openqa.qam.suse.cz/tests/32529), [XEN](http://openqa.qam.suse.cz/tests/32530)
> Virtualization: Ensure sudo is installed on all guests

- lib/services/rpcbind.pm
Reverts os-autoinst/os-autoinst-distri-opensuse#13706
> Revert "Fix rpcinfo failed to show nfs on s390x"

- tests/nfs/install.pm
Added NFS_GRACE_TIME which controls both grace and lease time.
Also NFS grace/lease time is not correctly set inside tests. Right way of doing it is:
- to set NFSV4LEASETIME inside /etc/sysconfig/nfs
- to set grace-time inside /etc/nfs.conf.local
VRs:
- [SLE](http://10.100.12.105/tests/1462)
- [TW](http://10.100.12.105/tests/1461)
> Set NFS grace time correctly before test

- lib/main_publiccloud.pm
- Related ticket: [poo#102569](https://progress.opensuse.org/issues/102569)
> Public Cloud: Do not use load_extra_tests_prepare()

- tests/console/zypper_extend.pm
VR: https://openqa.suse.de/t7733777
> console/zypper_extend: Avoid depending on a QA_HEAD repo package

- tests/publiccloud/xfsprepare.pm
On some publiccloud providers we need to manually add the required users
to make `generic/079` not fail.
- Related ticket: https://progress.opensuse.org/issues/60179
- Verification run: http://duck-norris.qam.suse.de/tests/7844
> Add required users to xfstests

- lib/virt_autotest/common.pm
- lib/virt_autotest/utils.pm
- Related ticket: https://progress.opensuse.org/issues/102596
- Needles: N/A
- Verification run: [KVM sle-15](http://openqa.qam.suse.cz/tests/32822#)   [XEN sle-15](http://openqa.qam.suse.cz/tests/32811#)
> Static IP for linuxrc profile

- tests/kernel/install_ltp.pm
Fix poo#103608: LTP package is built on daily basis. It can happen
that kernel modules are built against different kernel, than is in
tested snapshot. Variable LTP_GIT_URL allows to install
specific parts from git directly on SUT after was LTP installed from
package.
- Related ticket: https://progress.opensuse.org/issues/103608
- Needles: 
install: https://openqa.suse.de/tests/7802590
before: https://openqa.suse.de/tests/7794772#step/insmod01_sh/8
after: https://openqa.suse.de/tests/7802601#step/insmod01_sh/8
> ltp: Add option to install selected parts from git

- lib/apachetest.pm
The change made it from Tumbleweed into SLE 15 SP4 and Leap 15.4.
- Verification run: https://openqa.opensuse.org/tests/2076275
> lib/apachetest: Install php7-cli on 15.4+ as well

- lib/containers/engine.pm
If keep_container is set to one, retries in run_container would fail
because the container could already exist. This commit improves the
method by implementing a custom retry routine, that ensures to remove
dangling containers between retries.
- Related ticket: https://progress.opensuse.org/issues/103023
- Verification run: [podman](http://duck-norris.qam.suse.de/tests/7901) | [docker](http://duck-norris.qam.suse.de/tests/7902)
> Fix retry issue in run_container

- tests/kernel/wmp_simple.pm
Remove the commented out line, plus, add WMP_STRESSNG_REPO to allow
changing the repository to use
> Minor cleanups

- tests/console/rmt/rmt_feature.pm
This pr tests the function of adding custom repo for rmt server, and
attaching the custom repo to a product. I also add the record info to
the rmt feature case to make it more clear to review.
- Related ticket: https://progress.opensuse.org/issues/101334
- Verification run: https://openqa.nue.suse.com/tests/7810977#
> Test function of adding custom repo for rmt server

- lib/publiccloud/azure.pm
- lib/publiccloud/azure_client.pm
Extracts the code for Azure connection from provider to azure_client to be used in k8s providers
- Related ticket: https://progress.opensuse.org/issues/103419
- Verification run: https://openqa.suse.de/tests/7816102
> Add Azure connexion client

- tests/x11/hexchat.pm
- Related ticket: https://progress.opensuse.org/issues/103809
- Needles: N/A
- Verification run: https://openqa.opensuse.org/tests/2078956
> update tests/x11/hexchat.pm to use auto-detection

- lib/publiccloud/azure.pm
- lib/publiccloud/azure_client.pm
- Verification run: https://openqa.suse.de/tests/7828941
> Fix decode_azure_json

- tests/installation/zdup.pm
Add upload log for zdup.pm
- Related ticket: https://progress.opensuse.org/issues/103632
- Needles: na
- Verification run: https://openqa.suse.de/tests/7816676#step/zdup/21
> Add upload log for zdup.pm

- lib/publiccloud/utils.pm
- tests/publiccloud/run_ltp.pm
This reverts commit 170489d1b25fec68a9e02d66ef2db8ece99088ab.
- Related ticket: [poo#99360](https://progress.opensuse.org/issues/99360) [bsc#1190440](https://bugzilla.suse.com/show_bug.cgi?id=1190440)
- Verification run: [15-SP3-syscalls](http://pdostal-server.suse.cz/tests/12981)
> Revert "publiccloud : add workaround for LTP to detect that we are invirtual env"

- lib/publiccloud/basetest.pm
- variables.md
- Related ticket: https://progress.opensuse.org/issues/98379
- Verification run: https://openqa.suse.de/tests/7843257
Dependency with https://gitlab.suse.de/qac/qac-openqa-yaml/-/merge_requests/538 (both has to be merged at the same time)
> Refactor variable names for Google Cloud Provider

- lib/main_publiccloud.pm
- tests/publiccloud/azure_cli.pm
- variables.md
- Related merge request: [qac/qac-openqa-yaml!546](https://gitlab.suse.de/qac/qac-openqa-yaml/-/merge_requests/546)
> Public Cloud Tools CLI: Fix Azure test and scheduling

- lib/publiccloud/basetest.pm
- tests/publiccloud/az_accelerated_net.pm
- tests/publiccloud/img_proof.pm
- tests/publiccloud/run_ltp.pm
- tests/publiccloud/upload_image.pm
- variables.md
- Related ticket: http://progress.opensuse.org/issues/98379
- Verification run:  https://openqa.suse.de/tests/7843258
> Refactor variable names for Azure Cloud Provide

- tests/virt_autotest/login_console.pm
- Description
According to the latest OSD test gi-guest_win2019-on-host_developing-xen on 15-SP4 build61.1, find out that got Xen Domain0 kernel panic during login_console test. then boot up a normal kernel wihout xen kernel to continue the following test. mean that just only match virttest-bootmenu-xen-kernel needle at login_console step for xen host was not enough during getting kernel panic. 
So, we'd better double-check xen kernel module for xen host after matching virttest-bootmenu-xen-kernel needle successfully at login_console for this PR purpose. 
- Add
> Double-check xen kernel
> Check Xen hypervisor as Grub2 menuentry
> Check if start bootloader from a read-only snapshot
- Related ticket: https://progress.opensuse.org/issues/101509
validate login_console …
> [virt_autotest] Double check xen role for xen host at login_console

- data/mitigation/xen/get_guest_ip.sh
Enhance script to adapt to guest boot muen pause situation 
- Needles: N/A
- Verification run: http://openqa.qa2.suse.asia/tests/42199
> Enhance script to adapt to guest boot menu stop situation

- tests/btrfs-progs/generate_report.pm
upload => generate_report-logs.tar.xz
test => status.log
- Needles: N/A
http://10.67.133.102/tests/482#downloads (before)
http://10.67.133.102/tests/484#downloads (after)
> btrfs-progs: rename log file for more readable

- lib/publiccloud/acr.pm
- lib/publiccloud/azure_client.pm
- lib/publiccloud/basetest.pm
- lib/publiccloud/ecr.pm
- lib/publiccloud/gcr.pm
- lib/publiccloud/k8s_provider.pm
- schedule/containers/sle_image_on_azure_aks.yaml
- tests/containers/push_container_image_to_acr.pm
- Related ticket: https://progress.opensuse.org/issues/97718
-- http://copland.arch.suse.de/tests/678 (AKS)
-- http://copland.arch.suse.de/tests/675 (GKE)
-- http://copland.arch.suse.de/tests/676 (EKS)
-- https://openqa.suse.de/tests/7883754 (Azure img_proof)
> Upload container images to Azure ACR

- schedule/yast/modify_existing_partition_sle.yaml
- Related ticket: [poo#98958[(https://progress.opensuse.org/issues/98958)
- Verification run: [modify_existing_partition@s390x-kvm-sle12](https://openqa.suse.de/tests/7893590)
> Add stop timeout to modify_existing_partition scenario

- tests/security/ibmtss/version_check.pm
- Related ticket: https://progress.opensuse.org/issues/104208
- Needles:n/a
- Verification run: http://openqa.suse.de/tests/7893462
> Fix version isn't numeric issue in ibmtss

- tests/cpu_bugs/ipmi_to_qemu.pm
Enhance package installation from vulnerability test to make it stable due to net issue causing failure.
- Needles: N/A
- Verification run: http://openqa.qa2.suse.asia/tests/42772
> Enhance package installation to make stable due to net issue

- tests/console/sshd.pm
Description:
Currently the curve25519 is not FIPS approved, it's not
available seems intended, this fix is for ENV mode error,
Kernel mode does not show the error.
- Related ticket: https://progress.opensuse.org/issues/104415
- Needles: NA
(SP4 ENV mode) https://openqa.suse.de/tests/7916259#step/sshd/122
(SP4 Kernel mode) https://openqa.suse.de/tests/7916260
(SP3 Maintenance) https://openqa.suse.de/t7918705
(openSUSE TW) https://openqa.opensuse.org/t2110300
> Add a workaround check for sshd about curve25519 error

- lib/utils.pm
This came up as a question in chat, and might be useful for others.
> docs: Explain _until_screen_change return value

- lib/wickedbase.pm
- Verification run: https://openqa.suse.de/t7916535
> wicked: Increase timeout to 5min for scripts

- schedule/functional/extra_tests_textmode.yaml
- tests/network/snmp.pm
Ticket: https://progress.opensuse.org/issues/99633
http://kazhua.qa.suse.de/tests/52
> Add snmp test

- tests/console/journalctl.pm
Fix issues like https://openqa.suse.de/tests/7924703#step/journalctl/13
> systemctl: Fix problems where logdir already exists

- schedule/qam/12-SP5/qam-textmode-autoyast.yaml
- schedule/qam/15-SP1/qam-textmode.yaml
- schedule/qam/15-SP2/qam-textmode.yaml
- schedule/qam/15-SP3/qam-textmode.yaml
- schedule/qam/15/qam-textmode.yaml
Ticket: https://progress.opensuse.org/issues/99633
Rel: https://gitlab.suse.de/qa-maintenance/qam-openqa-yml/-/merge_requests/216
> QAM: Schedule snmp test

- lib/main_common.pm
- schedule/migration/aarch64_regression_test_offline.yaml
- schedule/migration/aarch64_regression_test_online.yaml
- schedule/migration/ppc64le_regression_test_offline.yaml
- schedule/migration/ppc64le_regression_test_online.yaml
- schedule/migration/s390x_regression_test_offline.yaml
- schedule/migration/s390x_regression_test_online.yaml
- schedule/migration/x86_regression_test_offline.yaml
- schedule/migration/x86_regression_test_online.yaml
- tests/console/java.pm
Add java into migration regression check
- Related ticket: https://progress.opensuse.org/issues/104472
- Needles: na
http://openqa.suse.de/t7918620
http://openqa.suse.de/t7918475
http://openqa.suse.de/t7918474
http://openqa.suse.de/t7918473
> Add java into migration regression check

- schedule/migration/aarch64_regression_test_offline.yaml
- schedule/migration/aarch64_regression_test_online.yaml
- schedule/migration/ppc64le_regression_test_offline.yaml
- schedule/migration/ppc64le_regression_test_online.yaml
- schedule/migration/s390x_regression_test_offline.yaml
- schedule/migration/s390x_regression_test_online.yaml
- schedule/migration/x86_regression_test_offline.yaml
- schedule/migration/x86_regression_test_online.yaml
- Related ticket: https://progress.opensuse.org/issues/104455
- Needles: na
x86 
http://openqa.suse.de/t7940474
390
http://openqa.suse.de/t7939289
arm
http://openqa.suse.de/t7939290
power
http://openqa.suse.de/t7939291
> Add cpio module into migration group

- lib/utils.pm
Add extra wait_quit_zypper after s390x boot up
- Related ticket: https://progress.opensuse.org/issues/104439
- Needles: na
- Verification run: https://openqa.suse.de/tests/7926824
NOTE: can not easy reproduce this issue with my fix after around 20 runs, current VR only show no side effect for exist test.
> Add extra wait_quit_zypper after s390x boot up

- lib/containers/utils.pm
- Related issue: containers/podman#12738
- Failure: https://openqa.suse.de/tests/7937932#step/podman/94
- Verification run: http://pdostal-server.suse.cz/tests/13002
> Stabilize 'podman search' command test

- tests/console/zypper_lifecycle.pm
- Related ticket: https://progress.opensuse.org/issues/95593 https://openqa.suse.de/tests/7941078#step/zypper_lifecycle/48
https://openqa.suse.de/tests/7943734
https://openqa.suse.de/tests/7943735
https://openqa.suse.de/tests/7943736
https://openqa.suse.de/tests/7943737
> Workaround Containers module too bsc#1194294

- tests/console/gpg.pm
Add record_info of version in gpg and version upgrade check for libgcrypt
**Libgcrypt needs to be upgraded to 1.9.x from SLE15 SP4**
- Related ticket: https://progress.opensuse.org/issues/104556
(SLE 15 SP4) 
https://openqa.suse.de/tests/7939276#step/gpg/4 (gpg 2.2.27)
https://openqa.suse.de/tests/7939276#step/gpg/9 (libgcrypt 1.9.4)
(SLE 15 SP3) 
https://openqa.suse.de/tests/7939277#step/gpg/4  (gpg 2.2.27)
https://openqa.suse.de/tests/7939277#step/gpg/9  (libgcrypt 1.8.2)
(openSUSE TW) 
https://openqa.opensuse.org/tests/2121149#step/gpg/4  (gpg 2.3.4)
https://openqa.opensuse.org/tests/2121149#step/gpg/9 (libgcrypt 1.9.4)
> Add gpg/libgcrypt version upgrade check in gpg test

- tests/installation/validation/ibft.pm
Yast2-bootloader calls dracut now instead of mkinitrd, so no /var/log/YaST2/mkinitrd.log is present now.
Because of this we need grep for the iscsi ibft info in the y2log, instead of mkinitrd.log in newer builds.
- Related ticket: https://progress.opensuse.org/issues/103704
- Verification run: [sles 15-SP4](https://openqa.suse.de/tests/7944284#step/ibft/50)
> Grep rd.iscsi.ibft in y2log for newer builds

- tests/installation/validate_self_update.pm
- Related ticket: [poo#102515](https://progress.opensuse.org/issues/102515)
- Verification run: [yast_self_update](https://openqa.suse.de/t7950051)
> Use zgrep for y2log in yast_self_update

- tests/publiccloud/xfsprepare.pm
Add ability to handle nvme disks for the xfs tests by adding two features
* nvme disks require an addition `p` characted when partitions are being created.
* Detection of first unused nvme disks (required by EC2-ARM where the secondary nvme disk can be nvme0n1 or nvme1n1)
- Related ticket: https://progress.opensuse.org/issues/104379
- Verification run: [nvme](https://openqa.suse.de/tests/7947751) | [non-nvme](https://openqa.suse.de/tests/7947752) - `generic-042` and `generic-095` are failing due to a different issue
> Add handling for nvme disks

- lib/thunderbird_common.pm
- tests/x11/groupwise/groupwise.pm
- tests/x11/thunderbird/thunderbird_imap.pm
- tests/x11/thunderbird/thunderbird_install.pm
- tests/x11/thunderbird/thunderbird_pop.pm
Failures are happening due to https://bugzilla.suse.com/show_bug.cgi?id=1191916
- Related ticket: https://progress.opensuse.org/issues/101042
https://openqa.suse.de/tests/7950480 15 SP3
https://openqa.suse.de/tests/7950499 15 SP3
https://openqa.suse.de/tests/7950506 15 SP4
> thunderbird: New GUI beviour

- schedule/sle-perf/hana_install.yaml
This commit will apply the followed changes:
1) Support KVM role
2) Support 15 SP4
- Verification run: http://openqa.qa2.suse.asia/tests/overview?distri=sle&version=15-SP4&build=79.1&groupid=32
> Update HANA install.yaml for 15SP4

- tests/network/cifs.pm
Related to https://bugzilla.suse.com/show_bug.cgi?id=1192140
- Verification run: https://openqa.opensuse.org/t2132104
> cifs: Upload audit log to help to troubleshot issues

- tests/ha/hawk_gui.pm
Rebase Docker image to use Leap 15.3 and update geckodriver.
> ha/hawk_gui: Rebase Docker image to use Leap 15.3

- lib/audit_test.pm
There are some known issues in CC testing. In case not block the
following tests, we need to record soft failure for them.
Relate: https://progress.opensuse.org/issues/104862
Verify run: https://openqa.suse.de/tests/7968051#
> Record softfail for CC tests known issues

- tests/publiccloud/run_ltp.pm
VR : https://openqa.suse.de/tests/7969552
> publiccloud : allow run ltp tests without LTP_COMMAND_EXCLUDE

- data/journal_check/bug_refs.json
* [sle-micro-5.2-MicroOS-Image-B-Staging-x86_64-BuildB.150300.2.8-sle-micro_update@64bit(http://kepler.suse.cz/tests/10511#step/journal_check/19)
* [sle-micro-5.2-MicroOS-Image-x86_64-Build__2.5___65.5_2.5__-sle-micro_selinux@64bit](http://kepler.suse.cz/tests/10513#live)
> SLEM5.2: Add known bugs

- lib/y2snapper_common.pm
- Verification run: https://openqa.suse.de/tests/7999876#step/yast2_snapper/41
> Add workaround for bsc#1191112 in yast2_snapper

- data/journal_check/bug_refs.json
- Needles: N/A
- Verification run: NONE
> journal_check: fix obvious typo in bug_refs

- data/journal_check/bug_refs.json
- Related ticket: https://progress.opensuse.org/issues/105076
> Add known bugrefs in the white list for Leap 15.4

- data/journal_check/bug_refs.json
Examples:
https://openqa.suse.de/tests/8001962#step/journal_check/11
https://openqa.suse.de/tests/8001960#step/journal_check/6
https://openqa.suse.de/tests/8001956#step/journal_check/21
> SLE Micro 5.2: Add bsc#1182500 in the journal white list

- tests/x11/enlightenment_first_start.pm
- Verification run: https://openqa.opensuse.org/t2147505
> Enlightenment: Also handle "acpid not found" dialog for 32-bit arm

- lib/thunderbird_common.pm
- Related ticket: https://progress.opensuse.org/issues/101042
- Fail: https://openqa.suse.de/tests/8002907#step/thunderbird_pop/18
- Verification run: https://openqa.suse.de/tests/8005831
> thunderbird: Wait between click for rolldown menu to show

- lib/publiccloud/instance.pm
- lib/publiccloud/utils.pm
- tests/publiccloud/register_system.pm
- tests/publiccloud/run_ltp.pm
- tests/publiccloud/storage_perf.pm
VRs : 
http://autobot.qa.suse.de/tests/2678 - sle-15-SP3-EC2-Updates-publiccloud_img_proof
http://autobot.qa.suse.de/tests/2679 - sle-15-SP3-EC2-Updates-publiccloud_containers
http://autobot.qa.suse.de/tests/2680 - sle-15-SP3-AZURE-BYOS-Updates-publiccloud_ltp_cve
http://autobot.qa.suse.de/tests/2681 - sle-15-SP3-AZURE-BYOS-Updates-publiccloud_img_proof
http://autobot.qa.suse.de/tests/2682 - sle-15-SP3-AZURE-BYOS-Updates-publiccloud_containers
http://autobot.qa.suse.de/tests/2683 - sle-15-SP4-Azure-Basic-publiccloud_consoletests
http://autobot.qa.suse.de/tests/2684 - sle-15-SP4-Azure-Basic-publiccloud_ltp_syscalls
http://autobot.qa.suse.de/tests/2685 - sle-15-SP4-Azure-BYOS-publiccloud_ltp_cve
http://autobot.qa.suse.de/tests/2686 -  sle-15-SP4-Azure-BYOS-publiccloud_containers …
> publiccloud : switch to registercloudguest for BYOS images

- tests/publiccloud/run_ltp.pm
VR : https://openqa.suse.de/tests/8006871
> publiccloud: Fix regression introduced by 9f3b787

- data/atsec/kvm_check_network.xml
- schedule/security/atsec_tests.yaml
- tests/security/atsec/kvm_check.pm
Test steps are https://confluence.suse.com/display/CC/Evaluator+Test+Plan+SLES+15+SP2#EvaluatorTestPlanSLES15SP2-3.20KVMcheck
Relate: https://progress.opensuse.org/issues/101956
Verify run:
https://openqa.suse.de/tests/7985156#  [aarch64]
https://openqa.suse.de/tests/7985163#  [x86_64]
https://openqa.suse.de/tests/7985165#  [s390x]
> Integrate test 'kvm check' of ATSec into openQA

- lib/y2_installbase.pm
- Related ticket: https://bugzilla.suse.com/show_bug.cgi?id=1189550
> Remove displaying workaround bsc#1189550

- tests/publiccloud/storage_perf.pm
VR: https://openqa.suse.de/tests/8012115
> publiccloud: Fix regression introduced by 65286c6

- tests/cpu_bugs/mitigation_perf.pm
1. Remove hard code about password
2. Adjust log name make it readable.
- Needles: N/A
- Verification run: http://openqa.qa2.suse.asia/tests/43604
> Remove password info

- tests/fips/mozilla_nss/firefox_nss.pm
According to 1192086 - FIPS: NSS: Provide module name/identifier and version, mozilla-nss needs to be upgrade to 3.68 for SP4 FIPS certification.
- Related ticket: https://progress.opensuse.org/issues/104989
- Needles: NA
http://openqa.suse.de/tests/8018941#step/firefox_nss/15
http://openqa.suse.de/tests/8018941#step/firefox_nss/18
> Add version upgrade check for mozilla-nss

- lib/susedistribution.pm
See https://progress.opensuse.org/issues/104571
> Fix key missmatch for consoles: user -> username

- lib/containers/common.pm
- lib/containers/docker.pm
- lib/containers/utils.pm
- lib/service_check.pm
- lib/services/docker.pm
- Related ticket: [poo#104775](https://progress.opensuse.org/issues/104775)
- Verification run: [Migration-from-15-SP1-to-15-SP3](http://pdostal-server.suse.cz/tests/13040)
> Add module for docker service check for migration scenarios

- lib/grub_utils.pm
- tests/console/yast2_nis.pm
- tests/installation/setup_libyui.pm
- tests/yast2_cmd/yast_ftp_server.pm
- Related ticket: https://progress.opensuse.org/issues/104223
VRs: https://openqa.suse.de/tests/overview?build=JRivrain/os-autoinst-distri-opensuse%2314065
> Remove workarounds

- tests/containers/docker_compose.pm
- Related ticket: https://bugzilla.suse.com/show_bug.cgi?id=1186691
[12-SP4 s390x](http://openqa.suse.de/t8025508)
[12-SP5 s390x](http://openqa.suse.de/t8025509)
> docker-compose: add soft-failure for s390x

- schedule/sles4sap/remote_desktop/sles4sap_remote_desktop_windows_client.yaml
- tests/x11/remote_desktop/windows_network_setup.pm
Reverts os-autoinst/os-autoinst-distri-opensuse#14088
> Revert "Fix erratic behavior of setting up the network on windows" due to regressions on openSUSE

- tests/console/check_default_network_manager.pm
- Related ticket: https://progress.opensuse.org/issues/105298
I have no local openQA anymore, please verify with this test: https://openqa.opensuse.org/tests/2150920
> expect NM always on TW

- lib/opensusebasetest.pm
- tests/console/check_system_info.pm
Add health check log
- Related ticket: https://progress.opensuse.org/issues/105091
- Needles: na
http://openqa.suse.de/t8007033
> Add health check log

- tests/installation/system_role.pm
- Fail: https://openqa.suse.de/tests/8010789
https://openqa.suse.de/tests/overview?distri=sle&build=system_role SLE
https://openqa.opensuse.org/tests/overview?build=system_role openSUSE
> Don't change system role if it's already selected

- lib/maintenance_smelt.pm
- tests/qam-updinstall/update_install.pm
This fixes the test setup code not being able to extract the modules
from the repos variable because of an extra slash.
Additionally checks where added to make sure that the test fails if:
* the query's HTTP response code is not 200.
* there are no packages found in the update.
* the regex for extracting the modules doesn't match.
* binaries to be installed cannot be found.
---
- Related ticket: https://progress.opensuse.org/issues/101938
- Verification run: [12SP3-15SP3](https://openqa.suse.de/tests/overview?distri=sle&build=vr_updinst_poo101938)
Note that in the VRs that the packages are installed but they weren't installed in the original ones.
> Fix update_install.pm not finding packages to install

- data/publiccloud/terraform/sap/gce.tfvars
Change project id for GCP
- Verification run: https://openqa.suse.de/tests/8028648
Note: VR is failing for other reason.
> sles4sap: Change project id for GCP

- lib/publiccloud/instance.pm
- tests/publiccloud/img_proof.pm
- tests/publiccloud/register_system.pm
- Ticket: [poo#105503](https://progress.opensuse.org/issues/105503)
- Verification run: [BYOS](http://pdostal-server.suse.cz/tests/13130), [PAYG](http://pdostal-server.suse.cz/tests/13131)
> Public Cloud: Upload /var/log/cloudregister

- lib/serial_terminal.pm
Quite often there is a race on o3 during virtio console login
(about 30-50% change in Build 20220129 and few previous builds)"
https://openqa.opensuse.org/tests/2165897
Try to enter username again to workaround it.
Suggested-by: Richard Palethorpe <rpalethorpe@suse.com>
Signed-off-by: Petr Vorel <pvorel@suse.cz>
- https://openqa.opensuse.org/tests/2170315#step/boot_ltp/9 (relogin)
- https://openqa.opensuse.org/tests/2170314#step/boot_ltp/9 (relogin not needed)
- https://openqa.suse.de/tests/8080911#step/boot_ltp/9 (sles => relogin not needed)
> serial_terminal: Relogin to workaround virtio console race

- tests/update/updates_packagekit_kde.pm
The PackageKit test for plasma ([updates_packagekit_kde](https://openqa.opensuse.org/tests/2006325#step/updates_packagekit_kde/27)) doesn't have a defined state for the "installing updates" phase but instead checks for all other phases. This sometimes fails because the needles for the `updates_availables_tray` tag can match during the installation phase.  This aims to fix that
- Related ticket: https://progress.opensuse.org/issues/101881
- Needles: https://github.com/os-autoinst/os-autoinst-needles-opensuse/pull/757
- ~Verification runs: [Leap 15.2](http://apappas-openqa.qam.suse.de/tests/27) [Leap 15.3](http://apappas-openqa.qam.suse.de/tests/28)~
- ~Verification runs: [10 runs for each product](https://openqa.opensuse.org/tests/overview?build=kde) and an [extra run to show needles for …
> Fix packagekit plasma test skipping by the installing updates phase
