lib/main_common.pm
lib/services/nginx.pm
t/data/test_schedule.out

- Related tickets: [poo#105786](https://progress.opensuse.org/issues/105786) [poo#105768](https://progress.opensuse.org/issues/105768)
- Previous PR: #14082
- Verification run: [sle-15-SP3-mau-webserver](http://pdostal-server.suse.cz/tests/13174) [Tumbleweed](http://pdostal-server.suse.cz/tests/13172)

Fix console/nginx test module and its scheduling

---

tests/x11/kontact.pm

* Make sure the KDE PIM pattern is installed
* Remove code for old distros
* Remove softfail for bug worked around above
- Verification run: https://openqa.opensuse.org/tests/2169659

Some fixes for x11/kontact

---

tests/qam-updinstall/update_install.pm

- Related ticket: https://bugzilla.suse.com/show_bug.cgi?id=1195351
https://openqa.suse.de/tests/8086253 x86_64
https://openqa.suse.de/tests/8086254 s390x
https://openqa.suse.de/tests/8086255 ppc64le

Add workaround for pip3 conflict

---

lib/x11utils.pm

- Related ticket: https://progress.opensuse.org/issues/106059
- Needles: N/A
- Verification run: [15sp3](https://openqa.suse.de/tests/8114211#step/consoletest_finish/22) | [15sp4](https://openqa.suse.de/tests/8114212#step/consoletest_finish/21)

Fix issue in qam-gnome s390x

---

tests/publiccloud/prepare_tools.pm

Install the instalation of rsync
- Related ticket: https://progress.opensuse.org/issues/105211
- Verification run: see https://progress.opensuse.org/issues/105211#note-10

PC tools for SP3 needs rsync

---

data/journal_check/bug_refs.json

Bug https://bugzilla.suse.com/show_bug.cgi?id=1192164 has been resolved.

Remove bsc#1192164 entry

---

data/containers/containerd.toml
data/containers/crictl.yaml
lib/containers/basetest.pm
lib/containers/common.pm
lib/containers/containerd_crictl.pm
lib/containers/containerd_nerdctl.pm
lib/main_containers.pm
tests/containers/containerd_crictl.pm
tests/containers/containerd_nerdctl.pm
variables.md

- Related ticket: [poo#105912](https://progress.opensuse.org/issues/105912)
- Verification run: [crictl](http://pdostal-server.suse.cz/tests/13272) [nerdctl](http://pdostal-server.suse.cz/tests/13271)

Test containerd with crictl and nerdctl

---

lib/containers/container_images.pm

- Related ticket: [bsc#1192941](https://bugzilla.suse.com/show_bug.cgi?id=1192941)
- Verification run: [SLE 15-SP3 host_docker](http://pdostal-server.suse.cz/tests/13288)

Remove soft-failure for bsc#1192941 as it won't be fixed

---

lib/sles4sap.pm
tests/boot/boot_from_pxe.pm
tests/sles4sap/saptune/mr_test.pm

- Fail: https://openqa.suse.de/tests/8089441#step/mr_test/29
- Verification run: https://openqa.suse.de/tests/8128138

Fix mr_test failure on ipmi

---

lib/proxymode.pm

Replace hard code password variable by passing from web front-end
- Needles: N/A

Use get_var to replace hardcode password

---

lib/containers/container_images.pm

* Issue: [docker_tests](https://openqa.suse.de/tests/8129897#step/docker_image/1443)

Containers: Increase 'zypper ls' timeout

---

lib/version_utils.pm
tests/installation/enable_selinux.pm

- Related ticket: https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/14207
http://openqa.suse.de/t8133984
http://openqa.suse.de/t8133985
http://openqa.suse.de/t8133986

Fix condition created by #14207

---

lib/containers/common.pm

Enlarge timeout of SUSEConnect command
- Related ticket: https://progress.opensuse.org/issues/106622
- Needles: na
- Verification run: http://openqa.suse.de/t8139587

Enlarge timeout of SUSEConnect command

---

tests/publiccloud/xfsprepare.pm

- Related ticket: https://progress.opensuse.org/issues/106669
- vR: http://openqa.suse.de/t8142091

PublicCloud: increase timeout for activating PackageHub

---

tests/publiccloud/aws_cli.pm
tests/publiccloud/azure_cli.pm
tests/publiccloud/google_cli.pm

- Related Job Groups merge request: [qac-openqa-yaml!640](https://gitlab.suse.de/qac/qac-openqa-yaml/-/merge_requests/640)
- Related metadata merge request: [metadata!580](https://gitlab.suse.de/qa-maintenance/metadata/-/merge_requests/580)
- Related ticket: [poo#106194](https://progress.opensuse.org/issues/106194) [bsc#1195351](https://bugzilla.suse.com/show_bug.cgi?id=1195351) [bsc#1192671](https://bugzilla.suse.com/show_bug.cgi?id=1192671)
- Verification run: [12-SP5](http://pdostal-server.suse.cz/tests/13340) [15-SP1](http://pdostal-server.suse.cz/tests/13339), [15-SP2](http://pdostal-server.suse.cz/tests/13341), [15-SP3](http://pdostal-server.suse.cz/tests/13327)

Public Cloud: Enable CLI Tools on 12-SP5, 15-SP1 and 15-SP2

---

tests/console/ntp_client.pm

- [[qac] test fails in ntp_client](https://progress.opensuse.org/issues/106374) && [[sporadic]test fails in ntp_client - time could not be synced)](https://progress.opensuse.org/issues/95872)
* [sle-15-SP3-Server-DVD-Updates-x86_64-Build20220211-1-mau-extratests-security-fips@64bit](http://kepler.suse.cz/tests/13709) 200+ runs have passed
* [sle-15-SP3-JeOS-for-kvm-and-xen-Updates-x86_64-Build20220215-1-jeos-extratest@64bit-virtio-vga](http://kepler.suse.cz/tests/13710#live)
* [sle-15-SP4-JeOS-for-kvm-and-xen-x86_64-Build5.26-jeos-extratest@64bit-virtio-vga](http://kepler.suse.cz/tests/13711#)
* [opensuse-15.3-JeOS-for-kvm-and-xen-x86_64-Build9.371-jeos-extra@64bit_virtio-2G](http://kepler.suse.cz/tests/13712#live)
* …

Update chrony NTP test case

---

lib/wickedbase.pm

Fix regression of 86366c892
- https://openqa.suse.de/t8178035 
- https://openqa.suse.de/t8178037
- http://openqa.wicked.suse.de/t50312
- http://openqa.wicked.suse.de/t50314

wicked: Fix regression from 86366c892

---

lib/utils.pm
tests/qam-updinstall/update_install.pm

- Related ticket: https://bugzilla.suse.com/show_bug.cgi?id=1195351 #14159 #14172
https://openqa.suse.de/tests/8178323#step/patch_and_reboot/10 PC
https://openqa.suse.de/tests/8178331#step/patch_and_reboot/10 PC
https://openqa.suse.de/tests/8178551 HA
https://openqa.suse.de/tests/8174175#step/update_install/126 HA
https://openqa.suse.de/tests/overview?distri=sle&version=12-SP5&build=%3A22730%3Asamba&groupid=284&flavor=Server-DVD-HA-Incidents-Install

workaround: Extend the condition and add on other places too

---

lib/publiccloud/instance.pm
tests/publiccloud/boottime.pm

VRs : 
http://autobot.qa.suse.de/tests/2695
http://autobot.qa.suse.de/tests/2696
http://autobot.qa.suse.de/tests/2697

publiccloud: cleanup of unused parameter

---

data/wicked/ifrename-1.sh
lib/wickedbase.pm
tests/wicked/startandstop/sut/t17_ifrename.pm

Bug: https://bugzilla.suse.com/show_bug.cgi?id=1194392
- Verification run: http://openqa.wicked.suse.de/tests/47837

 wicked: Add test t17_ifrename

---

lib/registration.pm

This method is used in multiple places, and we have observed that
it fails randomly due to network issues (timeouts, SCC not reachable,
etc). In most cases, restarting the test helps (unless there is a
major outage that tages long to be fixed).
This code does a similar thing what script_retry does, but with a
bit of more logic and info messages.
- Related ticket: https://progress.opensuse.org/issues/107062
Before:
We do 1 time `SUSEConnect -p` and ONLY retry 1 more time if PH.
After:
We do X retries (default 3) for ANY product.
And keep the same fail message if BETA=1 and PH at the end.

[Proposal] Refactor add_suseconnect_product with retries

---

tests/installation/await_install.pm

Reset timeout for migraiton group test cases and upload y2log in post failed hook
- Related ticket: https://progress.opensuse.org/issues/106092
- Needles: na
- Verification run: http://openqa.suse.de/t8189592
The error only happen during heavy load of worker, so VR can not show the actual failed situation.

Reset timeout for migraiton group test cases and upload y2log in post failed hook

---

test_data/yast/minimal+role_minimal.yaml
test_data/yast/minimal+role_minimal_pvm.yaml
test_data/yast/minimal+role_minimal_s390x.yaml

Add pattern `apparmor` to test data patterns
- Related ticket: No ticket
- Verification run: https://openqa.suse.de/tests/overview?distri=sle&version=15-SP4&build=ge0r%2Fos-autoinst-distri-opensuse%23apparmor-module

Add apparmor in patterns to validate

---

lib/main_publiccloud.pm

- Related ticket: https://progress.opensuse.org/issues/107179
- Verification run: http://openqa.suse.de/tests/8205048

Fix Podman & Docker merge in public cloud main

---

lib/microos.pm
lib/version_utils.pm
schedule/sle-micro/raw_image.yaml
tests/transactional/host_config.pm

Reverts os-autoinst/os-autoinst-distri-opensuse#14297

Revert "slem5.1: Ensure booting RT kernel"

---

lib/containers/containerd_crictl.pm
lib/containers/containerd_nerdctl.pm
lib/containers/utils.pm
lib/services/docker.pm
tests/containers/containerd_crictl.pm
tests/containers/containerd_nerdctl.pm
tests/containers/docker.pm
tests/containers/podman.pm

As we test multiple container runtimes and run test in more and more environments I want to create simple and unversal smoke test.  
- Related ticket: [poo#105912](https://progress.opensuse.org/issues/105912)
- Verification run: [pdostal-server](http://pdostal-server.suse.cz/tests/13363#step/containerd_crictl/75)

Create container runtime smoke test

---

lib/main_containers.pm
lib/main_publiccloud.pm

- Related ticket: [poo#107179](https://progress.opensuse.org/issues/107179)
- Hotfix: #14305
- Verification run: [pdostal-server](http://pdostal-server.suse.cz/tests/13378)
I would like to wait with this until we have some successful runs with the hotflix applied.

Export the main_containers::load_3rd_party_image_test() and use it in main_publiccloud

---

tests/x11/nis_client.pm

Fix sporadic issue https://openqa.suse.de/tests/8208663#step/nis_client/51

Bump timeout for nis_client

---

tests/publiccloud/aws_cli.pm

- Related ticket: [poo#107176](https://progress.opensuse.org/issues/107176)
- Sporadic failure: [OSD](https://openqa.suse.de/tests/8202287#step/aws_cli/127)
- Verification run: [pdostal-server](http://pdostal-server.suse.cz/tests/13377)

PC CLI AWS Wait until the instance is running

---

tests/qam-updinstall/update_install.pm

https://openqa.suse.de/tests/8210873#downloads
https://openqa.suse.de/tests/8210874#downloads

Fix the log breaking expected zypper.log path

---

tests/installation/welcome.pm

- Fail: https://openqa.suse.de/tests/8213328#step/scc_registration/1 https://openqa.suse.de/tests/8207071#step/welcome/1
Full
https://openqa.suse.de/tests/8213712 x86_64
https://openqa.suse.de/tests/8213713 ppc64le
Online
https://openqa.suse.de/tests/8213699 x86_64
https://openqa.suse.de/tests/8213705 ppc64le
QR
https://openqa.suse.de/tests/8213724 s86_64
https://openqa.suse.de/tests/8213725 ppc64le

Fix textmode shortcuts on sles4sap

---

tests/console/suseconnect_scc.pm
tests/publiccloud/img_proof.pm

- Related ticket: https://progress.opensuse.org/issues/107062
https://openqa.suse.de/tests/8213565#step/suseconnect_scc/8
https://openqa.suse.de/tests/8213689#step/suseconnect_scc/8
https://openqa.suse.de/tests/8213690#step/suseconnect_scc/5
https://openqa.suse.de/tests/8213691#step/suseconnect_scc/17

Use script_retry for SUSEConnect -r command

---

tests/ai_ml/armnn.pm

- Related ticket: https://progress.opensuse.org/issues/107332
- Verification run: https://openqa.opensuse.org/t2205667

armnn: update download link of onnx mnist model

---

lib/sles4sap.pm

- Fail: https://openqa.suse.de/tests/8217224#step/mr_test/53
- Verification run: https://openqa.suse.de/tests/8223741#step/mr_test/27

Increase wait time on ipmi before wait_boot

---

tests/support_server/setup.pm

- Fail: https://openqa.suse.de/tests/8228466#step/setup/27
- Verification run: https://dzedro.suse.cz/tests/21030

Increase timeout on yast2 firewall add service

---

products/sle-micro/main.pm
tests/installation/bootloader_uefi.pm

Ticket: [Include the new SLE Micro Selfinstall ISO images](https://progress.opensuse.org/issues/105025)
- Verification run: http://kepler.suse.cz/tests/14230#

Add needle cleanup subroutine for sle-micro

---

tests/autoyast/installation.pm
tests/installation/welcome.pm

- Related ticket: [poo#107647](https://progress.opensuse.org/issues/107647)
- Verification run: [mru-install-minimal-with-addons](https://openqa.suse.de/tests/8240969)

Remove soft-failure bsc#1179654

---

lib/publiccloud/instance.pm
tests/publiccloud/ssh_interactive_start.pm

Reverts os-autoinst/os-autoinst-distri-opensuse#14369

Revert "Improve softreboot to work on TUNNELED instances"

---

lib/repo_tools.pm

- Related ticket: https://bugzilla.suse.com/show_bug.cgi?id=1195759
- Verification run: https://openqa.suse.de/tests/8248877

rmt: Workaround post script failure

---

tests/transactional/host_config.pm

- Related ticket: https://bugzilla.suse.com/show_bug.cgi?id=1196330
- Verification run: kepler.suse.cz/tests/14252#

slem5.1:Dont set RT kernel as default

---

tests/network/config_services.pm

- Related ticket: https://progress.opensuse.org/issues/106326
- Verification run: https://openqa.suse.de/tests/8249547

Fix thunderbird passwd setup

---

tests/x11/libreoffice/libreoffice_open_specified_file.pm

- Related ticket: https://bugzilla.suse.com/show_bug.cgi?id=1196648
- Verification run: https://openqa.suse.de/tests/8255386

Workaround for libreoffice being closed on odf file

---

lib/main_containers.pm
tests/containers/rootless_podman.pm

- Related ticket: [poo#107722](https://progress.opensuse.org/issues/107722)
- Verification runs in comment sections.

Container: Podman: Switch to CGroups v2

---

lib/publiccloud/aks.pm
lib/publiccloud/azure_client.pm
lib/publiccloud/basetest.pm
schedule/containers/sle_image_on_azure_aks.yaml
tests/containers/push_container_image_to_acr.pm
variables.md

- Related ticket: https://progress.opensuse.org/issues/97727
- http://copland.arch.suse.de/tests/1006
- http://copland.arch.suse.de/tests/1007
- http://copland.arch.suse.de/tests/1008
- http://copland.arch.suse.de/tests/1011

Azure kubernetes test

---

tests/console/krb5.pm

- Related ticket: https://progress.opensuse.org/issues/106323
- https://openqa.suse.de/tests/8281521

Fix krb5 test

---

lib/containers/container_images.pm
lib/containers/urls.pm
tests/containers/image.pm
tests/containers/push_container_image_to_acr.pm
tests/containers/push_container_image_to_ecr.pm
tests/containers/push_container_image_to_gcr.pm
variables.md

- Related ticket: [poo#107776](https://progress.opensuse.org/issues/107776)
- Verification run: [with](http://pdostal-server.suse.cz/tests/13458) and [without](http://pdostal-server.suse.cz/tests/13459) the variable

Containers: Implement CONTAINER_IMAGES_TO_TEST variable

---

tests/console/suseconnect_scc.pm

- Related ticket: https://progress.opensuse.org/issues/107062#note-32
https://openqa.suse.de/tests/8287612
https://openqa.suse.de/tests/8287611
https://openqa.suse.de/tests/8287610

Use retry command for SUSEConnect --list-extensions

---

tests/security/apparmor_profile/usr_sbin_smbd.pm

Clean audit.log before restarting smbd
poo#101710 - [sle][security][sle15sp4] test fails in usr_sbin_smbd discloses the "audit.log" should not be cleared after "restart smb"
- Related ticket: https://progress.opensuse.org/issues/101710
- Needles: NA
https://openqa.nue.suse.com/tests/8286859# (the new fail can be tracked by bug: https://bugzilla.suse.com/show_bug.cgi?id=1196850)

Clean audit.log before restart smbd

---

.github/checklist.yml
.github/workflows/checklist.yml

See
https://github.com/os-autoinst/os-autoinst/pull/1958#issuecomment-1044231841
for an example in os-autoinst.

Provide automatic review checklist based on changed paths

---

lib/containers/engine.pm

https://progress.opensuse.org/issues/107806
https://progress.opensuse.org/issues/107062
- Verification run: https://openqa.suse.de/tests/8300413

Containers: retry for docker|podman build commands

---

tests/security/pam/pam_config.pm

Based on bsc#1196896, pam_ldap is removed from SLES15SP4.
So enhance the pam-config test by adding ssh method and
skip ldap on SLE
- Related ticket: https://progress.opensuse.org/issues/108096
- Needles: n/a
https://openqa.suse.de/tests/8306589           -SLE
https://openqa.opensuse.org/tests/2237280 -TW

Enhance pam-config test

---

lib/mm_network.pm
tests/network/setup_multimachine.pm

Reverts os-autoinst/os-autoinst-distri-opensuse#14441

Revert "Adapt `mm_network::setup_static_mm_network()` for Network Manager"

---

tests/console/check_system_info.pm

After migration to SLES15SP4, we can enable the python3 module to install python310. 
- Related ticket: https://progress.opensuse.org/issues/106161
- Needles: N/A
https://openqa.nue.suse.com/tests/8312192
https://openqa.nue.suse.com/tests/8312193
https://openqa.nue.suse.com/t8312167
https://openqa.nue.suse.com/t8312168 
https://openqa.nue.suse.com/t8312169 
https://openqa.nue.suse.com/t8312170

Check python3 module

---

tests/console/zypper_in.pm

http://kazhua.qa.suse.de/tests/92#downloads

Upload zypper.log in zypper_in post fail hook

---

tests/ai_ml/tvm.pm

- Related ticket: https://progress.opensuse.org/issues/107518
- Related bug: https://bugzilla.opensuse.org/show_bug.cgi?id=1195952
- Leap 15.4: https://openqa.opensuse.org/t2246401
- Tumbleweed: https://openqa.opensuse.org/t2246400

Fix TVM test on Tumbleweed

---

tests/console/zypper_in.pm

https://progress.opensuse.org/issues/105948
VR: http://kazhua.qa.suse.de/tests/93

Select log-console in zypper_in for post fail hook

---

tests/nfs/pynfs_result.pm

- http://quasar.suse.cz/tests/8567
- http://quasar.suse.cz/tests/8567

pynfs: Mark RD5a as softfail

---

lib/publiccloud/utils.pm

In an attempt to ease the pain of bsc#1196462 we increase the delay
between unsuccessful retries up to two minutes.
- Related ticket: https://bugzilla.suse.com/show_bug.cgi?id=1196462
- Verification run: [15-SP3 Azure-BYOS](http://duck-norris.qam.suse.de/t8358) | [15-SP3 GCE](http://duck-norris.qam.suse.de/tests/8355) | [15-SP1 GCE BYOS](http://duck-norris.qam.suse.de/t8356) | [12-SP5 Azure OnDemand gen2](http://duck-norris.qam.suse.de/t8355)

Add longer delay between registration retries

---

schedule/yast/opensuse/clone_system/clone_system.yaml

see https://progress.opensuse.org/issues/108461
verifications:
http://10.162.30.85/tests/4836

Add clone_system.yaml for Tumbleweed

---

data/sssd/openldap/Dockerfile
data/sssd/openldap/add_test_repositories.sh
tests/console/sssd_openldap_functional.pm

Use test repos also in the Docker image
- Related ticket: https://progress.opensuse.org/issues/108194
12.sp5 https://openqa.suse.de/tests/8341361
15.sp1 https://openqa.suse.de/tests/8341362
15.sp2 https://openqa.suse.de/tests/8341364
15.sp3 https://openqa.suse.de/tests/8339841

Fix sssd test

---

lib/publiccloud/provider.pm

After we updated terraform we have problems destroying Azure instances.
- Related ticket: [poo#108518](https://progress.opensuse.org/issues/108518)
- Failed job: [OSD](https://openqa.suse.de/tests/8340177)
- Verification run: [15-SP3](http://pdostal-server.suse.cz/tests/13865) [15-SP4](http://pdostal-server.suse.cz/tests/13866#)

Public Cloud: Fix terraform for Azure

---

lib/nfs_common.pm

https://progress.opensuse.org/issues/106679

skip testing NFSv2 on tumbleweed

---

lib/utils.pm
tests/qam-updinstall/update_install.pm

- Related ticket: https://bugzilla.suse.com/show_bug.cgi?id=1195351
https://openqa.suse.de/tests/8363917 PC
https://openqa.suse.de/tests/8363072 SLE

Revert workarounds for pip conflict

---

variables.md

Separate publiccloud-related variables from the sea of variables to
increase the overview.

Separate publiccloud variables

---

lib/main_common.pm
tests/security/apparmor/aa_prepare.pm

VRs:
TW: https://openqa.opensuse.org/tests/2257704
SLE15-SP4: https://openqa.suse.de/tests/8365124

[Minimal-VM] Enable apparmor tests on TW and 15-SP4

---

tests/x11/hexchat_ssl.pm

Skip login and send message in hexchat when SASL required
- Related ticket: https://progress.opensuse.org/issues/97679
- Needles:
there are two needles were updated in openQA:
https://openqa.suse.de/tests/8361288#step/hexchat_ssl/14 
https://openqa.suse.de/tests/8361288#step/hexchat_ssl/18
https://openqa.suse.de/tests/8367735 (without `XCHAT_URL` param)
https://openqa.suse.de/tests/8367727 (with `XCHAT_URL` param)

Update hexchat_ssl skip login when SASL required

---

data/autoyast_sle12/autoyast_wicked_x86_64.xml.ep

- Verification run: http://openqa.wicked.suse.de/t53304

wicked: Add LTSS for autoyast SLE-12

---

schedule/da-perf/deploy_sleperf.yaml
tests/kernel_performance/da_perf.pm

[Initialize Diamond Assurance performance test]
- Needles: NA
- Verification run: http://openqa.da.suse.cz/tests/135

init Diamond Assurance performance test

---

tests/fips/fips_setup.pm

Reverts os-autoinst/os-autoinst-distri-opensuse#14584

Revert "Add the CPU model information in fips_setup"

---

lib/containers/common.pm
tests/containers/host_configuration.pm

Fixes a regression caused by https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/14589
Failed tests:
- https://openqa.opensuse.org/tests/2270207#step/host_configuration/84 `podman,docker: command not found`
- https://openqa.opensuse.org/tests/2269976#step/host_configuration/93 `podman,docker: command not found`
- https://openqa.opensuse.org/tests/2269975#step/host_configuration/28 (centos update)
VRs:
https://openqa.opensuse.org/tests/overview?build=jlausuch%2Fos-autoinst-distri-opensuse%23containers_fix_hostconfig&distri=opensuse&version=Tumbleweed

Containers: fix host_configuration

---

data/journal_check/bug_refs.json
lib/version_utils.pm
products/leap-micro

- Related ticket: https://progress.opensuse.org/issues/107872
- Needles: https://github.com/os-autoinst/os-autoinst-needles-opensuse/pull/765

Add leap-micro product

---

lib/main_containers.pm
tests/containers/helm.pm

Added helm test for sle
- Related ticket: https://progress.opensuse.org/issues/108572
- Verification run: http://copland.arch.suse.de/tests/1303

Add helm test for sle

---

lib/containers/common.pm
lib/main_containers.pm
products/microos/main.pm
products/sle-micro/main.pm
tests/containers/docker_runc.pm

https://progress.opensuse.org/issues/109121
[TW MicroOS](https://openqa.opensuse.org/tests/overview?version=Tumbleweed&distri=microos&build=jlausuch%2Fos-autoinst-distri-opensuse%23microos_docker)
[SLE Micro 5.2](https://openqa.suse.de/tests/overview?arch=&flavor=&machine=&test=slem_containers_docker%40jlausuch%2Fos-autoinst-distri-opensuse%23microos_docker&modules=&module_re=&build=94.2_6.9&distri=sle-micro&version=5.2#)

Containers: Include transactional case when installing docker

---

lib/version_utils.pm

- Related ticket: https://bugzilla.opensuse.org/show_bug.cgi?id=1197874

Return true for leap-micro DISTRI in is_opensuse

---

tests/containers/host_configuration.pm

- Related ticket: https://progress.opensuse.org/issues/109388
VR: 
Leap 15.3: https://openqa.opensuse.org/tests/2278548
Leap 15.4: https://openqa.opensuse.org/tests/2278543
TW: https://openqa.opensuse.org/tests/overview?distri=opensuse&build=jlausuch%2Fos-autoinst-distri-opensuse%23containers_image_fix&version=Tumbleweed

Containers: swap restart of services docker and firewall

---

tests/transactional/transactional_update.pm

Reverts os-autoinst/os-autoinst-distri-opensuse#14630

Revert "Making transactional_update module fatal"

---

data/journal_check/bug_refs.json

- Verification run: https://openqa.opensuse.org/tests/2282433

data/journal_check: Ignore boo#1197904

---

lib/main_containers.pm

[MicroOS](https://openqa.opensuse.org/tests/2283217)
[Leap Micro](https://openqa.opensuse.org/tests/2283218)  (error should be fixed by https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/14648)
[SLE Micro](https://openqa.suse.de/tests/8470872)
[SLE 12-SP5](http://openqa.suse.de/t8470873)
[SLE 15-SP1](http://openqa.suse.de/t8470874)

Containers: add conditions for Leap Micro 

---

lib/containers/urls.pm

https://openqa.opensuse.org/t2283578

[Leap Micro] Support CONTAINER_IMAGE_VERSIONS variable

---

lib/containers/k8s.pm

- Related ticket: https://progress.opensuse.org/issues/109295
- Verification run: https://openqa.suse.de/tests/8481452

Remove phub product for SP3 from helm test

---

lib/x11utils.pm

Follow-up of #14662 
- Related ticket: https://progress.opensuse.org/issues/109563
- Needles: N/A

Remove obsolete workarounds

---

data/microos/utt-leap.repo
lib/transactional.pm
tests/transactional/transactional_update.pm

- Related ticket: https://bugzilla.opensuse.org/show_bug.cgi?id=1198171
https://openqa.opensuse.org/t2287101

Use different UTT repos for Leap Micro

---

data/journal_check/bug_refs.json
schedule/sle-micro/dvd.yaml
schedule/sle-micro/dvd_virt.yaml
tests/installation/enable_selinux.pm
tests/qemu/qemu.pm

https://openqa.opensuse.org/tests/overview?version=5.2&distri=leap-micro&build=jlausuch%2Fos-autoinst-distri-opensuse%23leap_micro_dvd

Leap Micro 5.2: Adjust dvd schedule

---

tests/migration/openldap_to_389ds.pm

Since openladp version udpate trigger test case failed, so we need adapt the configuration file also.
- Related ticket: https://progress.opensuse.org/issues/109422
- Needles: na
- Verification run: https://openqa.opensuse.org/tests/2292456
NOTE: currently the 389 tools need a fix so you can see the case failed, once the fix is ready the case should pass. Detail can     refer ticket's comments.

Update openladp configration file

---

tests/containers/rootless_podman.pm

- Remove check for bsc#1182874 as it's a closed bug.
- Move podman installation at the beginning
- Handle situation when /home is not btrfs   
Related comment: https://bugzilla.suse.com/show_bug.cgi?id=1196751#c44
[TW](https://openqa.opensuse.org/tests/2296000)
[TW JeOS](https://openqa.opensuse.org/tests/2296001)
[15-SP3]: [osd](https://openqa.suse.de/tests/8539044) [local](http://fromm.arch.suse.de/tests/6503)
[15-SP3 JeOS]:  [osd](https://openqa.suse.de/tests/8539041)  [local](http://fromm.arch.suse.de/tests/6504)
[15-SP2]: [osd](https://openqa.suse.de/tests/8539043)    [local](http://fromm.arch.suse.de/tests/6505)

Fix rootless_podman when /home has different filesystem

---

tests/console/check_system_info.pm

We need to check the wsm module's registration status then do
the check_nodejs_common function check.
- Related ticket: https://progress.opensuse.org/issues/109956
- Needles: N/A
https://openqa.nue.suse.com/tests/8549527#step/check_system_info/8 
https://openqa.nue.suse.com/tests/8549532#step/check_system_info/8 
https://openqa.nue.suse.com/tests/8549695#step/check_system_info/31 
https://openqa.nue.suse.com/tests/8551475
https://openqa.nue.suse.com/tests/8551476
ppc64le:
https://openqa.nue.suse.com/tests/8556485

Fix check_nodejs_common failed in zdup migration

---

tests/virt_autotest/login_console.pm

* **Fix** for bsc#1195059 revives Yast2 second stage run which needs to be launched manually via ssh after first stage reboot. 
* **Detecting** sshd service ready can not be performed immediately after hitting 'reboot now' when first stage upgrade finishes, because restarting host does not happen immediately and ssh port can be still open the host. So asserting grub2 needle is necessary to make sure host is experiencing reboot before detecting sshd service ready.
* **In** order to make grub2 menu visible on the serial console after upgrade, [pr#786](https://github.com/SUSE/qa-automation/pull/786) has been proposed.
* **At** last, asserting new yast2-second-stage-done needle to make sure yast2 finishes second stage upgrade and switch back to sol console.
* **This** only affects offline …

Add second stage for host offline upgrade

---

variables.md

Add missing terraform variables.

Add terraform variables

---

tests/jeos/prepare_openstack.pm

- Verification run: http://kepler.suse.cz/tests/16470#

Minor updates for SoC

---

tests/hpc/mpi_master.pm

Remove leftover debugging statements in mpi_master

---

lib/windowsbasetest.pm
tests/wsl/firstrun.pm
tests/wsl/prepare_wsl_feature.pm

- motivation: [[sporadic] test fails in prepare_wsl_feature - windows reboot timeout](https://progress.opensuse.org/issues/104376)

Increase WSL timeouts

---

tests/containers/bci_repo.pm

Refresh zypper services after removing `container-suseconnect` in order
to stop spawned services by this package.
Expand repo URL pointing to synced repo in o.s.d
- Related ticket: [Create a new module for BCI Repository testing](https://progress.opensuse.org/issues/109827)
- Verification run: [sle-15-SP3-BCI-Repo-Updates-x86_64-Build171.5-bci_repo_patterns@64bit](http://kepler.suse.cz/tests/16486#)
Follow up for https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/14712

Expand REPO_BCI value with osd link

---

tests/cpu_bugs/ipmi_to_qemu.pm

Add mandatory packages
- Verification run: http://openqa.qa2.suse.asia/tests/47519

Add mandatory packages for ipmi2qemu

---

tests/console/sssd_389ds_functional.pm
tests/console/sssd_openldap_functional.pm

15 SP3
https://openqa.suse.de/tests/8588046
https://openqa.suse.de/tests/8588047
https://openqa.suse.de/tests/8588048
https://openqa.suse.de/tests/8588049
https://openqa.suse.de/tests/8588050
https://openqa.suse.de/tests/8588051
15 SP1
https://openqa.suse.de/tests/8588058
https://openqa.suse.de/tests/8588061
https://openqa.suse.de/tests/8588062
https://openqa.suse.de/tests/8588063
https://openqa.suse.de/tests/8588064
https://openqa.suse.de/tests/8588065
12 SP5
https://openqa.suse.de/tests/8588052
https://openqa.suse.de/tests/8588053
https://openqa.suse.de/tests/8588054
https://openqa.suse.de/tests/8588055

Use serial console on sssd tests

---

schedule/yast/yast_self_update/yast_self_update_pvm.yaml

Wrongly deleted file restored.

Add back yast_self_update_pvm.yaml

---

tests/publiccloud/migration.pm

modified guest registration sub call based on the type of image isbyos(), ondemand()
VR job - http://autobot.qa.suse.de/tests/3147# 
CASEDIR | https://github.com/yarunachalam/os-autoinst-distri-opensuse.git#guestreg

Guest Registration

---

lib/bootloader_setup.pm
tests/installation/bootloader.pm

- Related ticket: https://progress.opensuse.org/issues/110197
- Verification run: https://dzedro.suse.cz/tests/21597#step/bootloader/8

Don't type SCC_URL on openSUSE

---

tests/publiccloud/slem_basic.pm

https://openqa.suse.de/tests/8639568#

SLEM on PC: small fixes for the basic test

---

tests/containers/bci_repo.pm

- Verification run: [bci_repo](http://kepler.suse.cz/tests/16669#step/bci_repo/273)

Change structure of test data

---

tests/jeos/image_info.pm

Follow up from https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/14747

JeOS image info: add CASEDIR condition for DB handling

---

lib/containers/common.pm

- Fixing: #14785
- Related ticket: https://progress.opensuse.org/issues/110331
- Related issue: https://openqa.suse.de/tests/8634857, https://openqa.suse.de/tests/8653032#step/docker/34
- Verification run: [12-SP4-EC2-BYOS](http://pdostal-server.suse.cz/tests/14550), [15-SP3-EC2](http://pdostal-server.suse.cz/tests/14553), [15-SP3-podman](http://pdostal-server.suse.cz/tests/14544), [15-SP1-EC2](http://pdostal-server.suse.cz/tests/14554), [12-SP5-docker](http://pdostal-server.suse.cz/tests/14546), [12-SP3-docker](http://pdostal-server.suse.cz/tests/14541), [15-SP4-image-on-12-SP5-host-docker](http://pdostal-server.suse.cz/tests/14558), …

Refactor containers::common::activate_containers_module()

---

lib/mm_network.pm
schedule/ha/bv/ha_supportserver.yaml
schedule/sles4sap/ha_supportserver.yaml
tests/support_server/setup.pm

Reverts os-autoinst/os-autoinst-distri-opensuse#14761
Due to issues on ppc64le.

Revert "Use serial console on support_server"

---

schedule/jeos/sle/rpi/jeos-realhw.yaml

http://openqa.suse.de/t8680030
http://openqa.suse.de/t8680031

Add journal check tests for RPi jobs in JeOS

---

data/journal_check/bug_refs.json

See also:
* https://bugzilla.suse.com/show_bug.cgi?id=1199163
* #14818

Add journal errors regarding #14818 to config

---

tests/containers/bci_test.pm

So far, BCI tests are using all the images of the same family in the
tests, e.g. dotnet environment is pulling all the dotnet image
versions available for dotnet.
By providing this marker using "-k bci/dotnet-aspnet_6.0" we make
sure the tests are only executed for this specific image.
This way we avoid running the tests for all the images in the same
family and save a lot of time.
This PR also adds running common tests in test_all.py
This goes together with https://gitlab.suse.de/qac/container-release-bot/-/merge_requests/51
VRs (you can compare them with the jobs in `CLONED_FROM`):
http://fromm.arch.suse.de/tests/6703
http://fromm.arch.suse.de/tests/6704
http://fromm.arch.suse.de/tests/6705

BCI: make use of markers to execute the tests

---

tests/console/orphaned_packages_check.pm

https://bugzilla.suse.com/show_bug.cgi?id=1198940

Fix orphan pkg check algorithm

---

lib/x11test.pm

- Related ticket: [poo#110563](https://progress.opensuse.org/issues/110563)
- Verification run: [Tumbleweed](https://openqa.opensuse.org/tests/2328595), [SLE15-SP4](http://pdostal-server.suse.cz/tests/14688#live)

Fix multimachine networking in x11 tests

---

lib/main_common.pm
schedule/qam/12-SP1/qam-regression-firefox.yaml
schedule/qam/12-SP2/qam-regression-firefox.yaml
schedule/qam/12-SP3/qam-regression-firefox.yaml
schedule/qam/12-SP4/qam-regression-firefox.yaml
schedule/qam/12-SP5/qam-regression-firefox.yaml
schedule/qam/15-SP1/qam-regression-firefox.yaml
schedule/qam/15-SP2/qam-regression-firefox.yaml
schedule/qam/15-SP3/qam-regression-firefox.yaml
schedule/qam/15/qam-regression-firefox.yaml

Unschedule firefox_html5
Context: https://suse.slack.com/archives/C02CSAZLAR4/p1651666204646569?thread_ts=1651659975.944389&cid=C02CSAZLAR4
https://suse.slack.com/archives/C02CSAZLAR4/p1651751973583839
- Related ticket: https://progress.opensuse.org/issues/110665
- Verification run: no verification

Unschedule firefox_html5

---

data/xfstests/wrapper.sh

Introduce new parameter INJECT_INFO to add 1 line code in a subtest. INJECT_INFO format in "SUBTEST_NAME INJECT_LINE_NUMBER INJECT_CODE".
e.g. When need to make a xfs_metadump before xfs_repair, assume xfs_repair in line 35, then you could configure like this:
INJECT_INFO=“xfs/xxx:35:‘_scratch_xfs_metadump /opt/log/xfs/xxx-metadumpfile’”
- Related ticket: https://progress.opensuse.org/issues/56237
- 1. inject a line in xfs/220 and check if its log has metadump after test or not https://10.67.133.102/tests/630
- 2. xfs test inject nothing https://10.67.133.102/tests/614

xfstests: Add feature to inject code for debugging

---

tests/console/orphaned_packages_check.pm

- Verification run: http://kepler.suse.cz/tests/16800#step/orphaned_packages_check/9

Trim passed array of detected orphans

---

tests/publiccloud/transfer_repos.pm

- Verification run: http://pdostal-server.suse.cz/tests/14697 http://pdostal-server.suse.cz/tests/14700

Public Cloud: fix the rsync installation in transfer_repos test module

---

data/strongswan/ipsec.conf.temp
schedule/security/fips_strongswan.yaml
tests/fips/strongswan/strongswan_client.pm
tests/fips/strongswan/strongswan_server.pm

Related: https://progress.opensuse.org/issues/108620
Verify run: https://openqa.suse.de/tests/8703118
https://openqa.suse.de/tests/8703119

Integrate strongswan test into OpenQA

---

data/autoyast_sle15/autoyast_btrfs_luks1_separate_boot.xml
schedule/security/autoyast_btrfs_luks1_separate_boot.yaml
schedule/security/luks1_decrypt_ssh_client.yaml
schedule/security/luks1_decrypt_ssh_server.yaml
tests/security/luks1/unlock_via_ssh_client.pm
tests/security/luks1/unlock_via_ssh_server.pm

SLE-16506 - support LUKS unlock via SSH (via dracut-ssh)
- Related ticket: https://progress.opensuse.org/issues/81780
- Needles: n/a
https://openqa.suse.de/tests/8704498
https://openqa.suse.de/tests/8710449
https://openqa.suse.de/tests/8710450
I don't plan to automate it on other platforms since it is not hardware specific case, I will try to automate it on TW later as well.

Support LUKS unlock via SSH

---

schedule/staging/RAID1@64bit-staging.yaml
schedule/staging/RAID1@s390x-staging.yaml
schedule/staging/cryptlvm_minimal_x@64bit-staging.yaml
schedule/staging/cryptlvm_minimal_x@s390x-staging.yaml
schedule/staging/ext4@s390x-staging.yaml
schedule/staging/minimal+base@64bit-staging.yaml
schedule/staging/minimal+base@s390x-staging.yaml

PR to modify yaml schedule in staging as not all the tests control that behavior via setting.

Remove beta acceptance from yaml schedule in staging

---

tests/qam-updinstall/update_install.pm

Fix conflict libGLw1
- Related ticket: https://progress.opensuse.org/issues/110842
- Verification run: https://openqa.suse.de/tests/8729633#

Fix conflict libGLw1

---

lib/x11utils.pm

- Related ticket: https://progress.opensuse.org/issues/110821
- Needles: n/a
No function impact there.

Remove soft failure bgo#731320/boo#1047262

---

lib/registration.pm
tests/yast2_gui/yast2_security.pm

- Related ticket: [poo#109762](https://progress.opensuse.org/issues/109762)
- Verification run: [sle](https://openqa.suse.de/tests/overview?version=&distri=sle&build=jknphy%2Fos-autoinst-distri-opensuse%23fix_workaround_bsc1191112)

Fix workaround for bsc#1191112

---

tests/fips/fips_setup.pm

Reverts os-autoinst/os-autoinst-distri-opensuse#14843

Revert "Check related hmac packages when FIPS installation"

---

tests/qam-updinstall/update_install.pm

fix terminfo conflicts
- Related ticket: https://progress.opensuse.org/issues/110941
- Verification run: https://openqa.suse.de/tests/8735823#details

fix terminfo conflicts

---

lib/publiccloud/k8s_provider.pm

- Verification run: https://progress.opensuse.org/issues/109295
http://fromm.arch.suse.de/tests/6919 (Amazon)
http://fromm.arch.suse.de/tests/6920 (Azure)
http://fromm.arch.suse.de/tests/6921 (helm)

Fix k8s_provider regression

---

schedule/yast/installer_extended/installer_extended.yaml
schedule/yast/installer_extended/installer_extended@pvm.yaml
schedule/yast/installer_extended/installer_extended@s390x.yaml

- Related ticket: No ticket, related to [these failures](https://openqa.suse.de/tests/overview?arch=&flavor=&machine=&test=&modules=validate_beta_message&module_re=&distri=sle&version=15-SP4&build=148.1&groupid=129#)
- Verification run: https://openqa.suse.de/tests/overview?version=15-SP4&build=ge0r%2Fos-autoinst-distri-opensuse%23conditional-validate-beta&distri=sle

Add conditional schedule for validate_beta_message

---

tests/publiccloud/download_repos.pm

* Fix `--no-parent` parameter of `wget` - it has no arguments.
* Fix the URL given to `wget` - it must end with slash.
* Add debug output to the end of the test module.
- Related error: https://openqa.suse.de/tests/8729394#step/download_repos/81
- Verification run: http://pdostal-server.suse.cz/tests/14783#step/download_repos/104 http://pdostal-server.suse.cz/tests/14776

Fix publiccloud/download_repos test module

---

tests/publiccloud/check_registercloudguest.pm

- Verification run: [15-SP1-EC2](http://pdostal-server.suse.cz/tests/14789)

Create publiccloud/check_registercloudguest workaround for LTSS products

---

data/journal_check/bug_refs.json

Failed test https://openqa.suse.de/tests/8748064#

Ignore journal error: dmi Firmware registration failed

---

tests/publiccloud/check_registercloudguest.pm

- Related error: https://openqa.suse.de/tests/8748194#step/check_registercloudguest/6
- Verification run: http://pdostal-server.suse.cz/tests/14792#

Create publiccloud/check_registercloudguest workaround for LTSS products #1

---

lib/publiccloud/gcp_client.pm
tests/publiccloud/azure_cli.pm
tests/publiccloud/google_cli.pm

- Related ticket: [poo#110932](https://progress.opensuse.org/issues/110932), [bsc#1199578](https://bugzilla.suse.com/show_bug.cgi?id=1199578)
- Verification run: [15-SP4](http://pdostal-server.suse.cz/tests/14813), [15-SP3](http://pdostal-server.suse.cz/tests/14814)

Public Cloud CLI for 15-SP4

---

lib/publiccloud/k8s_provider.pm
lib/publiccloud/k8sbasetest.pm

- Related ticket: https://progress.opensuse.org/issues/109854
- http://fromm.arch.suse.de/tests/6947 (AKS)
- http://fromm.arch.suse.de/tests/6948 (EKS)

replace kubectl installation

---

tests/hpc/mpi_slave.pm

The dependencies required to be installed in the compute nodes slightly
differs between sle15 sp versions. Set the proper ones accordingly for
sp1 and GA. SLE15SP2 hasnt been considered as i didnt found jobs to check
against it.
- Related ticket: https://progress.opensuse.org/issues/109584
https://openqa.suse.de/tests/8776475#dependencies

Adjust hpc dependencies per sp

---

tests/fips/fips_setup.pm

Progress issue: https://progress.opensuse.org/issues/110707
Check if related hmac packages are installed when installing FIPS and
when SLE >= 15sp4
- Related ticket: https://progress.opensuse.org/issues/110707
- sle15sp4 verification run
-Env mode test: https://openqa.suse.de/tests/8770651#step/fips_setup/1
-Kernel mode test: https://openqa.suse.de/tests/8770652#step/fips_setup/29
- sle12 verification run: https://openqa.suse.de/tests/8770653#step/fips_setup/40

Check related hmac packages when FIPS installation

---

tests/jeos/image_info.pm

- Related ticket: https://progress.opensuse.org/issues/111362
VR:
https://openqa.opensuse.org/tests/2359265 (RPi)
https://openqa.opensuse.org/tests/2359274 (aarch64)
https://openqa.opensuse.org/tests/2359267 (x86_64)
https://openqa.suse.de/tests/8793664 (openstack)

JeOS: small fix for image_info

---

tests/installation/start_install.pm
tests/migration/online_migration/yast2_migration.pm

match_has_tag only takes one parameter.

Fix wrong syntax of 'match_has_tag' call

---

lib/virt_autotest/common.pm

- Related ticket: https://progress.opensuse.org/issues/111194
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/overview?distri=sle&version=15-SP4&build=%3Atest%3A&groupid=322

Add sle15sp4 guest for vmware and hyper-V

---

tests/security/selinux/audit2allow.pm

On 15-SP3, we need to use `$original_audit` instead of the `$audit_log_short`. 
- 15-SP3:
- aarch64: https://openqa.suse.de/tests/8796815
- s390x: https://openqa.suse.de/tests/8796814
- x86_64: https://openqa.suse.de/tests/8796659
- 15-SP2:
- aarch64: https://openqa.suse.de/tests/8796816
- s390x: https://openqa.suse.de/tests/8796817
- x86_64: https://openqa.suse.de/tests/8796818

Fix audit2allow test on 15-SP3

---

tests/hpc/mpi_master.pm

Some known bugs for older SLE versions are breaking the tests but there is no
intention to be fixed or they are already having a fix in newer versions.
I follow the same practice which already work in the module using grep but
maybe i have to think a better approach in the future.
- Related ticket: https://progress.opensuse.org/issues/111476 
- Verification run: https://openqa.suse.de/tests/8816340#step/mpi_master/93 for bsc#1199811

Prevent known issues on HPC break the mvapich2 tests

---

lib/publiccloud/gcp_client.pm
lib/publiccloud/utils.pm

- Related ticket: https://progress.opensuse.org/issues/108509

PublicCloud: Make use of the credentials service

---

tests/publiccloud/google_cli.pm

- Related ticket: https://progress.opensuse.org/issues/111641
- Related issue: https://openqa.suse.de/tests/8824735
- Verification run: http://pdostal-server.suse.cz/tests/20

Public Cloud: google_cli: Trim id_rsa.pub and increase os disk from 10GB to 15GB

---

tests/virt_autotest/virt_utils.pm

* **QA** found out that guest installation with company openqa repo on local site takes extremely prolonged period to finish which looks quite cumbersome and not optimal. 
* **In** order to make the situation better off, new openqa test suite level parameter REPO_0_PREFIX has been introduced to customize the installation repo to be used in functions repl_repo_in_sourcefile and repl_module_in_sourcefile instead of using repo from company openqa by default. 
* **At** the same time, new function locate_sourcefile has been extracted to provide source file locating service in multiple places.
* [install x86 kvm guest in Beijing](http://10.67.131.12/tests/109)
* [install x86 xen guest in Beijing](http://10.67.131.12/tests/117)
* [install aarch64 kvm guest in …

Use local media to speed up guest installation

---

tests/fips/strongswan/strongswan_server.pm

POO: https://progress.opensuse.org/issues/111581
- Related ticket: https://progress.opensuse.org/issues/111581
- Needles: N/A
- Server: https://openqa.suse.de/tests/8825402

Integrate hkdf function test to strongswan

---

lib/containers/k8s.pm

- Related ticket: https://jira.suse.com/browse/SLE-21858
- Verification run: https://openqa.suse.de/tests/8831111

Helm: don't enable PackageHub for 15-SP4

---

tests/sles4sap/wizard_hana_install.pm

Fix for SAP HANA Wizard test
- Failing test: https://openqa.suse.de/tests/8752377
- Verification run: https://openqa.suse.de/tests/8831692

sles4sap: Fix Wizard test

---

data/autoyast_sle15/autoyast_sle-micro.xml.ep

Failure: https://openqa.suse.de/tests/8831806#step/installation/4
VR: http://openqa.suse.de/t8831845

SLE Micro 5.3: fix autoyast profile

---

tests/security/audit/aureport.pm
tests/security/audit/ausearch.pm

Fix execution of audit on SLES <15-SP4.
15-SP3: https://openqa.suse.de/tests/8833772
15-SP2: https://openqa.suse.de/tests/8833583

Fix audit on SLE <15-SP4

---

lib/grub_utils.pm
lib/kdump_utils.pm

Related progress issue: https://progress.opensuse.org/issues/99663

Correct incorrect use of check_var for truth-checks

---

lib/publiccloud/aws_client.pm

- Related ticket: https://progress.opensuse.org/issues/108509
- Verification run: https://openqa.suse.de/tests/8858857

PublicCloud: Update AWS client to use new credentials system

---

schedule/security/atsec_tests.yaml
tests/security/atsec/check_processor_vulnerability_mitigations.pm

Related: https://progress.opensuse.org/issues/111809
Verify run:
https://openqa.suse.de/tests/8863389# (64bit)
https://openqa.suse.de/tests/8863390# (aarch64)

Integrate 'Check processor vulnerability mitigations' into openQA

---

lib/publiccloud/basetest.pm
lib/publiccloud/gcp_client.pm
lib/publiccloud/gke.pm
lib/publiccloud/k8s_provider.pm
lib/publiccloud/k8sbasetest.pm
schedule/containers/sle_image_on_google_gke.yaml
tests/containers/push_container_image_to_gcr.pm

- Related ticket: https://progress.opensuse.org/issues/97721
- Verification run: http://marvin5.arch.suse.cz/tests/212

Containers: Test for google kubernetes engine

---

tests/containers/helm.pm

- Related ticket: https://progress.opensuse.org/issues/111914
- Verification run: http://marvin5.arch.suse.cz/tests/216

Fix timeouts on bitnami download repos (helm)

---

tests/x11/remote_desktop/windows_network_setup.pm

- Related ticket: https://progress.opensuse.org/issues/109091
- Verification run: https://openqa.suse.de/tests/8906012

Fix missing characters issue in powershell

---

lib/btrfs_test.pm

When script_run times out, it won't die by default and we will get
some value !=0, which does not correspond to the command output.
By using `die_on_timeout`, we force to die to better interpret
the returned value.
Example of failure:
https://openqa.suse.de/tests/8904731#step/snapper_undochange/44
VR: https://openqa.suse.de/tests/8906357#step/snapper_undochange/1

Better handle snapper_nodbus_restore

---

lib/publiccloud/aks.pm
lib/publiccloud/azure_client.pm

- Related ticket: https://progress.opensuse.org/issues/111983
- Verification run: http://marvin5.arch.suse.cz/tests/275

Migrate AKS test to new account

---

tests/security/scap_workbench/scap_workbench.pm

Added SCAP Workbench tool support to Tumbleweed.
- Related ticket: https://progress.opensuse.org/issues/110647
- Needles: 
Here are the needles added on O3:
- https://openqa.opensuse.org/tests/2330832#step/scap_workbench/18
- https://openqa.opensuse.org/tests/2330832#step/scap_workbench/28
- https://openqa.opensuse.org/tests/2330832#step/scap_workbench/25
- https://openqa.opensuse.org/tests/2330832#step/scap_workbench/20
- https://openqa.opensuse.org/tests/2330832#step/scap_workbench/22
- https://openqa.opensuse.org/tests/2330832#step/scap_workbench/21
- https://openqa.opensuse.org/tests/2330832#step/scap_workbench/59
- https://openqa.opensuse.org/tests/2330832#step/scap_workbench/60
- https://openqa.opensuse.org/tests/2330832#step/scap_workbench/56
- …

SCAP Workbench tool support to Tumbleweed

---

lib/publiccloud/eks.pm
lib/publiccloud/k8sbasetest.pm

- Related ticket: https://progress.opensuse.org/issues/111983
- Verification run: http://marvin5.arch.suse.cz/tests/285

Migrate EKS test to new account

---

schedule/qam/common/create_hdd_transactional_server.yaml

- Related ticket: https://progress.opensuse.org/issues/110253
- Needles: -
- Verification run: [SLE](https://openqa.suse.de/tests/overview?distri=sle&version=&build=maintenance_update_test_repo&groupid=96)

Add add_update_test_repo to create_hdd_transactional_server

---

tests/security/luks2/unlock_luks2_vol_tpm2.pm

- Related ticket: https://progress.opensuse.org/issues/112241
- Verification run: https://openqa.opensuse.org/tests/2408550

Fix the  zypper blocked issue by packagekit

---

data/autoyast_qam/15-SP4_installation.xml.ep
data/autoyast_qam/15-SP4_installtest.xml.ep

For the single incidents we have to produce manually
the qcow images.
- Related ticket: https://progress.opensuse.org/issues/112202
- Needles: N/A
- Verification run:N/A

Add new 15-SP4 autoyast files

---

lib/containers/common.pm
tests/containers/registry.pm

- Related ticket: https://progress.opensuse.org/issues/112262
- Verification run: https://openqa.opensuse.org/tests/2410252

Package renamed in Tumbleweed: distribution-registry

---

lib/btrfs_test.pm

As described in https://github.com/systemd/systemd/issues/23660 or [Bug 1185098 - [Build 15.82]
openQA test fails in snapper_undochange - logind fails after return back from rescue](https://bugzilla.suse.com/show_bug.cgi?id=1185098)
we need to add workaround that ensures `tty2` will be available for login.
Issue occurs only in systems running sle15sp2 or below.
VRs:
- [workaround case](http://kepler.suse.cz/tests/17406#step/snapper_undochange/55)
- [expected](http://kepler.suse.cz/tests/17405#step/snapper_undochange/42)

Add workaround for race condition between agetty and logind

---

tests/installation/logs_from_installation_system.pm

Implement & Integrate LUKS test case into openQA
- Related ticket: https://progress.opensuse.org/issues/109163
http://openqa.suse.de/tests/8906171
http://openqa.suse.de/tests/8906497
http://openqa.suse.de/tests/8912867
http://openqa.suse.de/tests/8912868
http://openqa.suse.de/tests/8912869
http://openqa.suse.de/tests/8912870
http://openqa.suse.de/tests/8912871 [https://bugzilla.suse.com/show_bug.cgi?id=1200322 ]
http://openqa.suse.de/tests/8912897
http://openqa.suse.de/tests/8921605
http://openqa.suse.de/tests/8921612

FIPS installation with encrypted volume

---

data/filesystem/autoyast_filesystem_withouthome.xml.ep
lib/Tomcat/JspTest.pm
lib/Utils/Architectures.pm
lib/virtmanager.pm
tests/fips/mozilla_nss/firefox_nss.pm
tests/security/apparmor_profile/apache2_changehat.pm
tests/sles4sap/grafana_dashboards.pm
tests/x11/wireshark.pm

- Containers, Public Cloud: Get rid of multiple arguments in record_soft_failure
- Fix wrong usages of signatures
- Fix usage of certain methods

Fix usage of certain methods in test repo

---

tests/migration/online_migration/register_ltss.pm

- Fail: https://openqa.suse.de/tests/8945637#step/register_ltss/1
- Verification run: https://openqa.suse.de/tests/8945905#step/register_ltss/8

register_ltss: Fix get_var arguments

---

data/filesystem/autoyast_filesystem_withouthome.xml.ep

- Fix wrong usage of check_var
VR: https://openqa.suse.de/tests/8946426#

Followup to #15064

---

lib/virt_autotest/common.pm

This PR fixes an issue with previous [PR](https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/14918)
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/overview?build=%3A24573%3A&distri=sle&groupid=322&version=15-SP1

fix for vmware and hyperV

---

tests/containers/helm.pm

- Related ticket: https://progress.opensuse.org/issues/111917
- Verification run: http://marvin5.arch.suse.cz/tests/342#

Migrate helm tets to new accounts

---

tests/containers/bci_prepare.pm

- Related ticket: [poo#100916](https://progress.opensuse.org/issues/100916)
- Verification run: [SLE15-SP3-podman](http://pdostal-server.suse.cz/tests/87), [Ubuntu-22.04-docker](http://pdostal-server.suse.cz/tests/92), [RES8.5-docker](http://pdostal-server.suse.cz/tests/90) (unrelated error)

Check if org.opensuse.reference label contains CONTAINER_IMAGE_BUILD

---

tests/containers/bci_prepare.pm

* Follows: #15075 
- Related ticket: [poo#112541](https://progress.opensuse.org/issues/112541)
- Verification run: http://pdostal-server.suse.cz/tests/102

Register phub addon because of jq on SLE12-SP5

---

lib/bootloader_setup.pm
tests/console/copy_iso_to_external_drive.pm
tests/console/validate_lvm.pm

https://progress.opensuse.org/issues/112568 
https://progress.opensuse.org/issues/112601
http://openqa.suse.de/tests/8965344
http://openqa.suse.de/tests/8970908
http://openqa.suse.de/tests/8970909
http://openqa.suse.de/tests/8970913

Disable parted prompts

---

tests/publiccloud/azure_cli.pm

We are not running this test at all, and the only issue that the CLI has is this bug. The rest could be run.
Also, by enabling the test again, we will be able to verify a possible fix for it.
VR: https://openqa.suse.de/tests/8972597

Azure CLI: make bsc#1192671 soft

---

data/journal_check/bug_refs.json

https://bugzilla.suse.com/show_bug.cgi?id=1188238

Add bugref for bsc#1188238 to trigger soft fail on rpi3b+ BT issues.

---

schedule/qam/15-SP4/lvm_thin_provisioning.yaml
schedule/qam/15-SP4/mau-filesystem@zkvm.yaml
schedule/qam/15-SP4/mau-userspace.yaml
schedule/qam/15-SP4/mau-webserver.yaml
schedule/qam/15-SP4/powerpc-utils.yaml
schedule/qam/15-SP4/qam-create_hdd_ha_textmode.yaml
schedule/qam/15-SP4/qam-create_hdd_sle_sap_gnome.yml
schedule/qam/15-SP4/qam-create_hdd_sles4sap_gnome.yml
schedule/qam/15-SP4/qam-minimal-RAID1.yaml
schedule/qam/15-SP4/qam-minimal.yaml
schedule/qam/15-SP4/qam-sle_sles4sap_scc_gnome_netweaver_cli.yml
schedule/qam/15-SP4/qam-sle_sles4sap_scc_gnome_sapconf.yml
schedule/qam/15-SP4/qam-sle_sles4sap_scc_gnome_saptune.yml
schedule/qam/15-SP4/qam-sles4sap_wmp_hana_node1.yaml
schedule/qam/15-SP4/qam-sles4sap_wmp_hana_node2.yaml

- Related ticket: https://progress.opensuse.org/issues/112202

Copy yamls 15-SP3 to 15-SP4

---

data/publiccloud/terraform/azure.tf
lib/publiccloud/azure.pm

VR : http://autobot.qa.suse.de/tests/3225

publicloud: switch from legacy defaults to new accounts default

---

tests/security/apparmor_profile/usr_sbin_smbd.pm

https://progress.opensuse.org/issues/112721
- 15-SP4: https://openqa.suse.de/tests/9004774#step/usr_sbin_smbd/1
- 15-SP3: https://openqa.suse.de/tests/9004772#step/usr_sbin_smbd/1

Fix usr_sbin_smbd on 15-SP4

---

lib/opensusebasetest.pm
lib/transactional.pm
tests/microos/selfinstall.pm

- Related ticket: https://progress.opensuse.org/issues/110845
- Needles: 
* https://github.com/os-autoinst/os-autoinst-needles-opensuse/commit/093dcaba26cd076a4b5150131b4f7a47d19e4407
* https://github.com/os-autoinst/os-autoinst-needles-opensuse/commit/669b7d31e3ced825d69be3e6686efb4a5d9fe61b
- Verification run: https://openqa.opensuse.org/t2420243

Selfinstall aarch64

---

tests/installation/enable_selinux.pm

Failure: https://openqa.suse.de/tests/8998741#step/enable_selinux/26
VR: https://openqa.suse.de/tests/9005497#step/enable_selinux/26

Fix SLE Micro 5.3 SELinux selection in s390x

---

schedule/wsl/wsl_main.yaml
tests/wsl/install_from_MSStore.pm

**VRs:**
- 15-SP4: http://openqa.suse.de/tests/9011167 :white_check_mark:
- 15-SP3: https://openqa.suse.de/tests/9011199 :white_check_mark:
- TW: https://openqa.opensuse.org/tests/2432674 :white_check_mark:
- Leap 15.4: https://openqa.opensuse.org/tests/2432697 :white_check_mark: 
- Leap 15.3: https://openqa.opensuse.org/tests/2432685 :white_check_mark:

Renamed some variables due to a conflict with openQA

---

schedule/qam/15-SP4/lvm_thin_provisioning.yaml
schedule/qam/15-SP4/mau-webserver.yaml
schedule/qam/15-SP4/qam-create_hdd_ha_textmode.yaml
schedule/qam/15-SP4/qam-create_hdd_sle_sap_gnome.yml
schedule/qam/15-SP4/qam-create_hdd_sles4sap_gnome.yml
schedule/qam/15-SP4/qam-minimal-RAID1.yaml
schedule/qam/15-SP4/qam-minimal.yaml

- Related ticket: d7dfdbb20
- Verification run: https://openqa.suse.de/tests/9014407

Fix yaml after license handle change d7dfdbb20

---

lib/main_containers.pm
tests/containers/update_host.pm

https://progress.opensuse.org/issues/112886
VRs: http://marvin5.arch.suse.cz/group_overview/1

Containers: create new schedule to update a host

---

data/stig/baseline_comparison.py
lib/stigtest.pm
schedule/security/stig.yaml
tests/security/stig/baseline_comparison.pm
tests/security/stig/oscap_security_guide_setup.pm
tests/security/stig/oscap_xccdf_eval.pm
tests/security/stig/oscap_xccdf_eval_remote.pm
tests/security/stig/oscap_xccdf_remediate.pm

Modify codes for enhancement of test module stig on Tumbleweed and sle, add comparison of evaluation and remediation baseline, generate stats and logs of baselines changed during remediation for downloading and extended research
- Related ticket: https://progress.opensuse.org/issues/104944
- Needles: N/A
- o3: https://openqa.opensuse.org/tests/2440428#
- osd: https://openqa.suse.de/tests/9047876#

Add code enhancement for test module: stig

---

lib/containers/k8s.pm

The k3s version can be controlled by variable
- Related ticket: https://progress.opensuse.org/issues/113114
- Verification run: http://marvin5.arch.suse.cz/tests/680

Containers: The k3s version can be controlled by variable

---

lib/db_utils.pm
tests/containers/bci_prepare.pm
tests/containers/image.pm

- Related ticket: https://hackweek.opensuse.org/21/projects/tool-to-collect-relevant-data-from-images-and-containers-tested-in-openqa

Push container information to remote DB

---

tests/containers/host_configuration.pm

Reverts os-autoinst/os-autoinst-distri-opensuse#15137

Revert "Containers BCI: Workaround issues on RHEL host #1"

---

tests/containers/update_host.pm

- Related ticket: https://progress.opensuse.org/issues/112892
https://openqa.suse.de/tests/9067550
https://openqa.suse.de/tests/9067552

Containers: disable SELinux on RHEL hosts

---

tests/console/sysstat.pm

Fix sysstat
- Related ticket: https://progress.opensuse.org/issues/113207
- Verification run: https://openqa.suse.de/tests/9067915#details

Fix sysstat for 12-SP3

---

tests/containers/rootless_podman.pm

- Related ticket: https://bugzilla.suse.com/show_bug.cgi?id=1200623#c9
- Verification run: http://openqa.suse.de/t9074445

Rootless podman soft fail bsc#1200623

---

tests/containers/bci_test.pm

- Related ticket: https://progress.opensuse.org/issues/112757
- VR: https://openqa.suse.de/tests/overview?distri=sle&version=15-SP4&build=jlausuch%2Fos-autoinst-distri-opensuse%23bci_metadata

BCI: enable metadata tests

---

data/generalhw_scripts/raspberry_pi_hardware_testing_setup.md

- Added RTC
- Added TPM
- Added HDMI Grabber

Update RPi hw setup description

---

schedule/sles4sap/qam/common/qam_install_sles4sap.yaml

- Related ticket: https://progress.opensuse.org/issues/113390 
- Verification run: https://openqa.suse.de/tests/9091681

qam-create_hdd_sles4sap_gnome: Update yaml for 15-SP4

---

tests/console/ping.pm

Both helps debugging (capabilities are needed to ping as non-root on older systems where RAW socket is used). They're set by permissions package.
Also install iputils (should not be needed, but just in case) and libcap-progs (getcap).
- http://quasar.suse.cz/tests/175#step/ping/93 (Tumbleweed)
- http://quasar.suse.cz/tests/173#step/ping/93 (sle-15-SP1)
- http://quasar.suse.cz/tests/174#step/ping/93 (sle-15-SP4)

ping: Print capabilities and permissions package

---

schedule/qam/12-SP1/qam-regression-firefox.yaml
schedule/qam/12-SP2/qam-regression-firefox.yaml
schedule/qam/12-SP3/qam-regression-firefox.yaml
schedule/qam/12-SP4/qam-regression-firefox.yaml
schedule/qam/12-SP5/qam-regression-firefox.yaml
schedule/qam/15-SP1/qam-regression-firefox.yaml
schedule/qam/15-SP2/qam-regression-firefox.yaml
schedule/qam/15-SP3/qam-regression-firefox.yaml
schedule/qam/15-SP4/qam-regression-firefox.yaml
schedule/qam/15/qam-regression-firefox.yaml

Related progress issue: https://progress.opensuse.org/issues/113435

schedule: Disable unstable test module "firefox_downloading"

---

tests/security/audit/auditd.pm
tests/security/audit/ausearch.pm
tests/security/audit/autrace.pm

https://openqa.suse.de/tests/9103321

Fix security_audit on 12-SP5

---

tests/cpu_bugs/mitigation_perf.pm

1.Show detail info for screen name; 
2. kill screen session when repeatedly trigger
- Verification run: http://openqa.qa2.suse.asia/tests/49664#

Enhance VT performance run to easy to use

---

tests/kernel/qa_test_klp.pm

lpechacek moved the repo to SUSE github namespace.

qa_test_klp: Update git repository URL

---

lib/main_containers.pm
tests/microos/toolbox.pm

Includes:
- Automation for SLEM tests which publish updated SLEM HDD
- toolbox,pm test updated to use the toolbox image under test
Related ticket: https://progress.opensuse.org/issues/113036
VRs:
- HDD creation with system update: [slem 5.1](https://openqa.suse.de/tests/overview?distri=sle-micro&version=5.1&build=GM&groupid=377) [slem 5.2](https://openqa.suse.de/tests/overview?distri=sle-micro&version=5.2&build=GM&groupid=377)
- Toolbox test with specific image: [slem 5.1](https://openqa.suse.de/tests/9124243) [slem 5.2](https://openqa.suse.de/tests/9124242)

Schedule SLE Micro toolbox container tests

---

lib/susedistribution.pm

Reverts os-autoinst/os-autoinst-distri-opensuse#15091

Revert "GNOME: assert focus on xterm"

---

lib/windowsbasetest.pm
tests/wsl/install/ms_win_firstboot.pm
tests/wsl/install/ms_win_installation.pm

New installation of the Windows 11 OS based on previous Windows 10 installation.
- Related ticket: [poo#112064](https://progress.opensuse.org/issues/112064)
- Needles:
- https://github.com/os-autoinst/os-autoinst-needles-opensuse/blob/master/windows-accept-20220704.json
- https://github.com/os-autoinst/os-autoinst-needles-opensuse/blob/master/windows-accept-20220704.png
- https://github.com/os-autoinst/os-autoinst-needles-opensuse/blob/master/windows-account-setup-20220624.json
- https://github.com/os-autoinst/os-autoinst-needles-opensuse/blob/master/windows-account-setup-20220624.png
- https://github.com/os-autoinst/os-autoinst-needles-opensuse/blob/master/windows_client_remotelogin-xrdp-sharing-activate-20220324.json
- https://github.com/os-autoinst/os-autoinst-needles-opensuse/blob/mast …

Windows 11 installation process

---

tests/installation/setup_libyui.pm

Improve  libyui REST error message. 
- Related ticket: https://progress.opensuse.org/issues/112832
- Verification run: http://d218.qam.suse.de/tests/42

Improve error message when using libyui REST below SLE-15-SP3

---

lib/main_containers.pm
tests/containers/slem_rancher.pm

- Related ticket: https://progress.opensuse.org/issues/113180
- Verification run: http://marvin5.arch.suse.cz/tests/728#

Containers: enable testing for SLE Micro Rancher image

---

data/virtualization/autoyast/guest_12.xml.ep
data/virtualization/autoyast/guest_15.xml.ep
tests/virtualization/universal/prepare_guests.pm
tests/virtualization/universal/waitfor_guests.pm

- Related ticket: https://progress.opensuse.org/issues/113003
- Needles: N/A
- Verification run: [KVM](http://openqa.qam.suse.cz/tests/43877#) and [XEN](http://openqa.qam.suse.cz/tests/43888#)

Check if guests are fully installed

---

tests/kernel/update_kernel.pm

Remove the manually maintained table of version differences between `kernel-default` and `kernel-source`. Instead, look up the kernel-source version automatically in the update repo and use it for the relevant noarch packages.
- Needles: N/A
- SLE-12SP4: https://openqa.suse.de/tests/9162934
- SLE-12SP5: https://openqa.suse.de/tests/9162999

update_kernel: Simplify livepatch installation

---

data/sssd-tests/krb/test.sh
data/sssd-tests/ldap-nested-groups/test.sh
data/sssd-tests/ldap-no-auth/test.sh
data/sssd-tests/ldap/test.sh
data/sssd-tests/local/test.sh

Ticket: https://progress.opensuse.org/issues/104674

Use new sssd log option

---

schedule/rt/sle15/create_hdd_rt.yaml

- Verification run: https://openqa.suse.de/t9172748

rt: Remove minimal system role from installation schedule

---

tests/cpu_bugs/ipmi_to_qemu.pm

1.Add mandatory package
2.Fix product version check causing issues
3.Use zypper_ar to replace zyper_call for repo add
4.Add "no_gpg_check" flag for pkg install
5.Add timeout parameter for OS upgrade
6.Solve package installation issue due to outside net issue and env issue
7.Assert operation of openqa and worker server
- Verification run: http://openqa.qa2.suse.asia/tests/49802#

Enhance ipmi_to_qemu for functions and structure issue

---

data/publiccloud/terraform/sap/azure.tfvars
data/publiccloud/terraform/sap/gce.tfvars

Fix Azure URI to new account
- Azure: http://1b124.qa.suse.de/tests/22 (failing for other reason)
- GCP: http://1b124.qa.suse.de/tests/28 (failing for other reason)

sles4sap: Fix Azure URI

---

lib/publiccloud/basetest.pm
lib/publiccloud/existing.pm
lib/publiccloud/noprovider.pm
tests/publiccloud/prepare_instance.pm
variables.md

- Related ticket: [poo#108587](https://progress.opensuse.org/issues/108587)
- Verification run: [12-SP5](https://pdostal-server.suse.cz/tests/216), [15-SP4 BYOS](https://pdostal-server.suse.cz/tests/213)

Public Cloud: Allow testing against existing instance

---

lib/wickedbase.pm

We should not check older logs. Otherwise we would get
a log error in all subsequence tests showing the same issue, but they
actually occured only in the first run/boot.
- Verification run: https://openqa.suse.de/t9173655

wicked: Check only logs created during test

---

lib/windowsbasetest.pm
tests/wsl/install/ms_win_firstboot.pm
tests/wsl/install/ms_win_installation.pm
tests/wsl/install_from_MSStore.pm
tests/wsl/prepare_wsl_feature.pm

Add WSL installation from MSStore to Win11
- Related tickets: [poo#60338](https://progress.opensuse.org/issues/60338) // [poo#112064](https://progress.opensuse.org/issues/112064)
- :green_circle: https://openqa.suse.de/tests/overview?distri=sle&version=15-SP4&build=_wsl_test&groupid=386
- :green_circle: https://openqa.suse.de/tests/overview?distri=sle&version=15-SP3&build=_wsl_test&groupid=326
- Needles:
https://github.com/os-autoinst/os-autoinst-needles-opensuse/blob/master/windows-turn-off-find-device-20220715.png
https://github.com/os-autoinst/os-autoinst-needles-opensuse/blob/master/windows-turn-off-find-device-20220715.json
https://github.com/os-autoinst/os-autoinst-needles-opensuse/blob/master/windows-user-acount-ctl-yes-20220715.png …

Install WSL from MSStore in Win11

---

tests/console/ping.pm

ping as non-root to detect missing capabilities on systems where RAW socket is used.
Use sudo for testing because virtio console supports proper non-root user login.
Add sanity check for localhost and ::1 to verify any ping command is working.
Also remove year in copyright (new policy).
- http://quasar.suse.cz/tests/314
- http://quasar.suse.cz/tests/307
- http://quasar.suse.cz/tests/317

ping: Test as non-root

---

lib/publiccloud/aws_client.pm

This PR fixes the upload_img job for AWS.
- Verification run:http://1b124.qa.suse.de/tests/74

sles4sap: Save AWS credentials to ~/.aws/credentials

---

data/publiccloud/terraform/sap/azure.tfvars
data/publiccloud/terraform/sap/ec2.tfvars
data/publiccloud/terraform/sap/gce.tfvars
tests/publiccloud/sles4sap.pm

Related MR: https://gitlab.suse.de/qac/qac-openqa-yaml/-/merge_requests/909
- Azure: http://1b124.qa.suse.de/tests/91
- GCP: http://1b124.qa.suse.de/tests/90

sles4sap: Disable DRBD on all cloud providers

---

tests/containers/bci_repo.pm

- Related ticket: https://jira.suse.com/browse/SLE-22186
VR: https://openqa.suse.de/tests/9209806

BCI repo: check list of forbidden packages

---

lib/main_common.pm
tests/console/java.pm

PR related to os-autoinst/opensuse-jobgroups#176
- ticket: [[qe-core] Increase the coverage of test scenarios in Leap
Maintainance - Proposal for tests from SLES to be added to leap](https://progress.opensuse.org/issues/113297)

Leap154 more updates

---

tests/security/atsec/dbus_fuzzer.pm

- Related ticket: https://progress.opensuse.org/issues/110071
- Verification run: https://openqa.suse.de/tests/9230174#step/dbus_fuzzer/33

Add back org.freedesktop.login1

---

tests/containers/kubectl.pm

- Failure: [openqa.opensuse.org](https://openqa.opensuse.org/tests/2484785)
- Verification run: [openqa.opensuse.org](https://openqa.opensuse.org/tests/2485535)

kubectl: Fix performance issue when scaling in

---

tests/publiccloud/azure_cli.pm

- Related ticket: [bsc#1201870c1](https://bugzilla.suse.com/show_bug.cgi?id=1201870#c1)
- Issue: [OSD](https://openqa.suse.de/tests/9121737#step/azure_cli/88)
- Verification run: [pdostal-server](https://pdostal-server.suse.cz/tests/241)

PC: azure_cli: Repair pint command

---

tests/publiccloud/run_ltp.pm

- Related ticket: [poo#113668](https://progress.opensuse.org/issues/113668)
- Replaces: #15246
- Verification run: [SLE-15-SP2-Azure-LTP-CVE](https://pdostal-server.suse.cz/tests/257)

Rename ltp package to follow upstream changes

---

tests/publiccloud/run_ltp.pm

- Problem introduced in: #14854

Public Cloud: Fix run_ltp publiccloud::utils requirements

---

data/journal_check/bug_refs.json

- Verification run: https://openqa.opensuse.org/tests/2482717#step/journal_check/9

Add bugref for boo#1196618 to trigger soft fail on rpi4 mmc issues

---

data/vsftpd/vsftpd.conf
tests/security/vsftpd/lftp.pm
tests/security/vsftpd/vsftpd.pm
tests/security/vsftpd/vsftpd_setup.pm

- Related ticket: https://progress.opensuse.org/issues/108614
- 15-SP4: https://openqa.suse.de/tests/9236200
- Tumbleweed: https://openqa.opensuse.org/tests/2487063

Fix vsftpd

---

.github/workflows/ci-isotovideo.yml
tools/test_isotovideo

https://github.com/os-autoinst/os-autoinst/pull/2134 added colors to line endings, which make them in fact, different to what the expected output we have.
First test is to see if it works. Altered diff command too to get more info
https://progress.opensuse.org/issues/114869

Fix isotovideo test by removing colors

---

data/journal_check/bug_refs.json

Example of error: https://openqa.suse.de/tests/9223369#step/journal_check/22
VR:  http://openqa.suse.de/t9242594

SLE Micro: ignore bsc 1200490

---

lib/containers/k8s.pm
tests/containers/helm.pm

- Related bug: k3s-io/k3s#5946
- Follows: os-autoinst/os-autoinst-distri-opensuse#15313
- Verification run: [pdostal-server.suse.cz](https://pdostal-server.suse.cz/tests/421)

Containers: k3s: Skip metrics-server as it's causing problems

---

tests/publiccloud/aws_cli.pm

- Verification run: https://pdostal-server.suse.cz/tests/126

Public Cloud: aws_cli: Use special security group

---

products/sle-micro/main.pm

VR: https://openqa.suse.de/tests/9266528

Add svirt_upload_assets module for SLEM HDD creation test

---

lib/windowsbasetest.pm
tests/wsl/install/ms_win_firstboot.pm
tests/wsl/install_from_MSStore.pm
tests/wsl/prepare_wsl_feature.pm

Fixed bugs poo#114712, poo#114715, poo#114721 and poo#114911; and improved tests stability
- Tickets related:
- [poo#114712](https://progress.opensuse.org/issues/114712)
- [poo#114715](https://progress.opensuse.org/issues/114715)
- [poo#114721](https://progress.opensuse.org/issues/114721)
- [poo#114911](https://progress.opensuse.org/issues/114911)
- Verification run: https://openqa.suse.de/tests/overview?distri=sle&version=15-SP4&build=_wsl_test&groupid=386
- Needles:
- https://gitlab.suse.de/openqa/os-autoinst-needles-sles/-/blob/master/windows-desktop-20220802.png
- https://gitlab.suse.de/openqa/os-autoinst-needles-sles/-/blob/master/win11-desktop-20220801.json
- https://gitlab.suse.de/openqa/os-autoinst-needles-sles/-/blob/master/win11-desktop-20220801.png
- …

Fix some errors found in #15243

---

data/journal_check/bug_refs.json

VR: https://openqa.suse.de/tests/9265783#step/journal_check/21

SLEMicro: softfail bsc1202014 as it blocks automatic staging approval

---

lib/x11utils.pm
tests/console/system_prepare.pm

Reverts os-autoinst/os-autoinst-distri-opensuse#15306

Revert "Set windows focus to strict in GNOME"

---

tests/kernel_performance/full_run.pm

After enabling "FULLRUN_MONITOR" we can let openQA to monitor the status of hosts, and openQA instance will wait until the testing finish. So openQA instances finish after our testings finish.
**Note**: if you plan to enable "FULLRUN_MONITOR", it is best to work with "MAX_JOB_TIME=<**seconds**>" (**seconds** depends on the time that your testing takes), for example, I will set
"MAX_JOB_TIME=86400" when running our testing.
- Verification run: http://10.67.129.4/tests/50035
- Needles: N/A

Add "FULLRUN_MONITOR" to support for monitoring the status of hosts

---

.github/actions/trufflehog/action.yml
.github/workflows/trufflehog.yml

Have our own action, to better control what is happening and allow extra parameters (Like debug)
- Related ticket: https://progress.opensuse.org/issues/114787
- Verification run: none

Custom Trufflehog action and debug info

---

data/journal_check/bug_refs.json

Add sle15-sp5 tags for the existing issues

Add list of known issues for 15-SP5

---

lib/containers/k8s.pm
tests/containers/kubectl.pm

- Related ticket: [poo#114457](https://progress.opensuse.org/issues/114457)
- openSUSE job groups pull request: os-autoinst/opensuse-jobgroups#186
- SUSE job groups pull request: [qac/qac-openqa-yaml#924](https://gitlab.suse.de/qac/qac-openqa-yaml/-/merge_requests/924)
- Verification run: [15-SP1](https://pdostal-server.suse.cz/tests/464), [15-SP2](https://pdostal-server.suse.cz/tests/459), [15-SP3](https://pdostal-server.suse.cz/tests/458), [15-SP4](https://pdostal-server.suse.cz/tests/457), [15.4](https://pdostal-server.suse.cz/tests/465), [Tumbleweed](https://pdostal-server.suse.cz/tests/461)

Containers: Optimize kubectl test so it runs on SLE

---

lib/nfs_common.pm
tests/console/yast2_nfs_server.pm

- Related ticket: https://progress.opensuse.org/issues/114854
- Needles: n/a
- Verification run: http://openqa.suse.de/tests/9261717

Fix timeout issue when starting nfs_server

---

lib/main_common.pm
products/sle/main.pm

- Related ticket: https://progress.opensuse.org/issues/111710
- Needles: not needed
- Verification run: http://quasar.suse.cz/tests/547

Use *_TEST_REPOS variable instead of *_TEST_{ISSUES,TEMPLATE}

---

data/virtualization/autoyast/guest_12.xml.ep
data/virtualization/autoyast/host_12.xml.ep
lib/virt_autotest/common.pm
tests/virtualization/universal/patch_guests.pm

Add sles12sp3 teradata ltss repos in autoyast templates. Also improve
code in patching guest.
https://progress.opensuse.org/issues/113764
- Related ticket: https://progress.opensuse.org/issues/113764
- Needles: no
- sles12sp3 kvm: http://10.67.183.130/tests/overview?build=%3AS%3AM%3A25294%3A277021%3Akvm%3Ayoda%3A1443&groupid=2&distri=sle&version=12-SP3
- sles12sp3 xen: http://10.67.183.130/tests/overview?version=12-SP3&distri=sle&groupid=2&build=%3AS%3AM%3A25294%3A277021%3A%3Axen%3Adarthvader%3A1443
- VMware + Hyper-V: 
https://openqa.suse.de/tests/overview?distri=sle&version=12-SP3&build=%3AS%3AM%3A25294%3A277021%3A12-SP3%3Atony&groupid=322

Continue to test sles12sp3 teradata ltss

---

data/containers/Dockerfile
data/containers/www.py
lib/containers/common.pm
lib/containers/utils.pm
lib/main_containers.pm
products/alp/main.pm

- Related ticket: [poo#114935](https://progress.opensuse.org/issues/114935)
- Related pull request os-autoinst/opensuse-jobgroups#185
- Related fix: thkukuk/hello-kubic#1
- Verification run: [pdostal-server.suse.cz/t449](https://pdostal-server.suse.cz/tests/452)

Enable container module for ALP

---

tests/microos/cockpit_service.pm

There are additional cockpit modules we need to make sure are
installable but are not pulled as deps when installing `cockpit`
package.
```
cockpit-machines | Cockpit user interface for virtual machines
cockpit-tukit    | Cockpit module for Transactional Update
```
The cockpit-{wicked,nm} is pre-installed in the images depending on
used network backend.
- ticket: [Extend cockpit smoke test to install the different
modules](https://progress.opensuse.org/issues/115010)

Install additional cockpit modules

---

declarative-schedule-doc.md

Some basic/useful documentation should be added to the existing one to use this new path to
schedule your test modules.
- Related ticket: https://progress.opensuse.org/issues/110245
- Needles: N/A

Document new feature in YAML schedule with default and flows

---

tests/security/pam/pam_login.pm
tests/security/pam/pam_su.pm

Related progress ticket: https://progress.opensuse.org/issues/115364
- Related ticket: https://progress.opensuse.org/issues/115364
- Verification run: [Tumbleweed](https://openqa.opensuse.org/tests/2538861) | [sle15sp4](https://openqa.suse.de/tests/9371744) | [Leap 15.4](https://openqa.opensuse.org/tests/2538862)

Change /usr/etc to /usr/lib for TW

---

tests/kernel/install_ltp.pm

+ update comments
- http://quasar.suse.cz/tests/737 (opensuse-Tumbleweed-DVD-x86_64-Build20220823)
- http://quasar.suse.cz/tests/736 (sle-15-SP5-Online-x86_64-Build12.1-ltp_fs)
- http://quasar.suse.cz/tests/738 (opensuse-Tumbleweed-JeOS-for-kvm-and-xen-x86_64-Build20220823)

install_ltp: Add squashfs as runtime dependency for git build

---

tests/security/swtpm/swtpm_env_setup.pm

- Related ticket: https://progress.opensuse.org/issues/115646
- Build20220824: https://openqa.suse.de/tests/9386203 :heavy_check_mark: 
- Build20220823: https://openqa.suse.de/tests/9374597 :heavy_check_mark: 
- Build20220822: https://openqa.suse.de/tests/9372209 :heavy_check_mark:

swtpm_env_setup.pm: retry on wget failure

---

schedule/sle-micro/raw_image.yaml

Gather same data about images as we do for containers and JeOS
- Verification run: http://kepler.suse.cz/tests/18996#step/image_info/1

Gather size data from SLEM raw image

---

schedule/sle-micro/raw_image.yaml
schedule/sle-micro/virt.yaml

Limit number of tests from which are data gathered

Upload image data from virt test suite

---

tests/console/journal_check.pm

Even though tests scan journal for known bugs, the same error
message can cause a service failure. This was causing failing jobs that
could have softfailed. This PR add a feature to check whether a service
failed due to already known bug by comparing the output of the service's
status against already matched bugs found in journal.
- failure: https://openqa.suse.de/tests/9406188#step/journal_check/44
- ticket: [journal_check should softfail failed services](https://progress.opensuse.org/issues/115616)
- Verification run: [sle-micro-5.2-DVD-Updates-x86_64-Build20220828-1-slem_installation_selinux@64bit](http://kepler.suse.cz/tests/19002#step/journal_check/44)

Softfail services that related to known bugs

---

lib/qam.pm

- Related ticket: https://progress.opensuse.org/issues/115910
- Needles: NO
https://openqa.suse.de/tests/9407189#step/patch_and_reboot/23
https://openqa.suse.de/tests/9407629#step/patch_and_reboot/29

Add SLES-12-SP3-LTSS-TERADATA repository for 12-SP3 

---

schedule/sles4sap/hana/pvm_hana.yaml
schedule/sles4sap/hana/pvm_hana_cluster_node.yaml
schedule/sles4sap/qam/common/qam_install_sles4sap.yaml

Fix pvm_hmc SLES4SAP installation schedules for 15-SP4 & 15-SP5
- Needles: N/A
- Verification run: https://openqa.wdf.sap.corp/tests/195151

Fix pvm_hmc SLES4SAP installation schedules for 15-SP4 & 15-SP5

---

lib/kdump_utils.pm

- Related ticket: https://progress.opensuse.org/issues/115994
- Needles: No
https://openqa.suse.de/tests/9419005#

Fix systemtap test in 12-SP3

---

ui-framework-documentation.md

Rephrase and explain the motivations behind the adoption of Page-Object design pattern and declarative scheduling vs the legacy test style
- Related ticket: https://progress.opensuse.org/issues/106936

ui-framework-documentation.md: explain pros and cons of older vs newer approach

---

schedule/ha/bv/migration/migration_online_sles_ha.yaml

- Related ticket: https://progress.opensuse.org/issues/115751
- Verification run: http://mango.qa.suse.de/tests/4898

fix SCC_PROXY_URL for online migration jobs

---

tests/ai_ml/armnn.pm

- Verification run: https://openqa.opensuse.org/t2592357

armnn: Update path in archive used for onnx

---

tests/security/pam/pam_login.pm

Related progress ticket: poo#116048
- Related ticket: https://progress.opensuse.org/issues/115364
- Needles: N/A
- Verification run: [Tumbleweed](https://openqa.suse.de/tests/9414566#step/pam_login/51) | [sle15sp4](https://openqa.suse.de/tests/9419624#step/pam_login/51)

Move openssh template to /usr/lib/pam.d

---

.github/workflows/trufflehog.yml

We know already the problem with Trufflehog, so let's wait for resolution before doing anything else.

Move trufflehogs checks to its own branch

---

data/containers/kubectl/deployment.yml
data/containers/registries.yaml
lib/containers/k8s.pm
tests/containers/kubectl.pm

- Related ticket: [poo#114457](https://progress.opensuse.org/issues/114457)
- Verification run: [Tumbleweed](https://openqa.opensuse.org/tests/2591351), [SLE15-SP1 x86_64](https://openqa.suse.de/tests/9418701), [SLE15-SP3 aarch64](https://openqa.suse.de/tests/9418637),

Containers: Fix kubectl test

---

lib/power_action_utils.pm

See https://progress.opensuse.org/issues/114439 for details.
With PR https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/15176 we expect the failure
of GUI shutdown because record_soft_failure got removed and no fix was in place.
https://openqa.suse.de/tests/9225020#step/shutdown

FIx GUI shutdown issue on s390x backend zVM and zKVM

---

lib/main_publiccloud.pm
tests/publiccloud/ahb.pm
variables.md

- Get resource group and license type
- Add the param for API version
- Get hostname
- Check license type
- Update license type
- Get new license type if command went well
- Verify expected license type is correct
- Add param for license type
- Verification run: [openqa.mypersonalinstance.de/tests/xyz#step/module/x](http://autobot.qa.suse.de/tests/3300#)

Add AHB test

---

tests/publiccloud/ahb.pm

Fix variable or AHB
- Verification run: http://autobot.qa.suse.de/tests/3313#

Fix variable

---

tests/installation/installation_overview.pm

* **Add** is_sle_micro for open ssh checking

Add is_sle_micro for open ssh checking

---

lib/sles4sap.pm

- Related ticket: https://progress.opensuse.org/issues/57464
- x86_64 VM: https://openqa.suse.de/tests/9462400
- bare-metal: https://openqa.suse.de/tests/9462428

sles4sap: saptune will always complain when running on VM

---

tests/ha/check_after_reboot.pm

Pull request #15473 introduced a regression that makes the `ha/check_after_reboot` module check for `/etc/mdadm.conf`, but the module is also used in scenarios where no cluster_md/mdadm configuration is used. This commit fixes it.
- Related ticket: https://progress.opensuse.org/issues/116191
- Needles: N/A
- Verification run: [suppor server](https://openqa.suse.de/t9462860), [node 1](https://openqa.suse.de/t9462863), [node 2](https://openqa.suse.de/t9462861), [qnetd server](https://openqa.suse.de/t9462862)

Fix a regression introduced by PR #15473

---

data/journal_check/bug_refs.json

- Verification run: https://openqa.opensuse.org/tests/2635413

data/journal_check/bug_refs.json: Typo got fixed for Tumbleweed

---

lib/audit_test.pm
tests/fips/openjdk/openjdk_fips.pm
tests/fips/openjdk/openjdk_ssh.pm

https://progress.opensuse.org/issues/116185

Replace qa-apac-i with qe-security

---

tests/hpc/powerman.pm

This starting as an investigation for the weird last validation from `powerman -c`. it turned out that this was not an issue as the device used on the test it doesnt supported. So the question was if it should be removed or improved in one or the other way.
So as part of that improvement, the module checks for the capabilities of the divice given by the specification files. In additional, the validation of the commands are replaced by `validate_script_output` and some info added to the OpenQA UI.
https://openqa.suse.de/tests/overview?build=b10n1k%2Fos-autoinst-distri-opensuse%2315485&version=15-SP5&distri=sle

Refactor powerman module

---

lib/main_containers.pm
tests/containers/helm.pm

- Related ticket: https://progress.opensuse.org/issues/114700
- Verification run: http://marvin5.arch.suse.cz/tests/1100

Unify names in Helm backend

---

tests/installation/welcome.pm

- Related ticket: https://progress.opensuse.org/issues/115376
https://openqa.suse.de/tests/9495687 online ppc64le
https://openqa.suse.de/tests/9495688 offline ppc64le
https://openqa.suse.de/tests/9495689 online x86_64
https://openqa.suse.de/tests/9495648 offline x86_64

Update textmode key for sles4sap on Full 15-SP5

---

tests/publiccloud/prepare_tools.pm

https://progress.opensuse.org/issues/116440

publiccloud : switch to python39

---

tests/installation/installation_overview.pm

Issue: https://openqa.suse.de/tests/9502281#step/installation_overview/30
VR: https://openqa.suse.de/tests/9519796#

More key presses to match needle in SLEM installation overview

---

products/alp/main.pm
schedule/alp/networking.yaml
schedule/qam/common/mau-extratests1.yaml
tests/console/firewalld.pm

- Related ticket: [poo#115187](https://progress.opensuse.org/issues/115187)
- Related pull request: os-autoinst/opensuse-jobgroups#196
- Verification run: [pdostal-server.suse.cz](https://pdostal-server.suse.cz/tests/559)

Enable networking test suite for ALP

---

schedule/yast/rmt_server_install/rmt_server_install.yaml

Fixes failure here https://openqa.nue.suse.com/tests/9517520#step/install_SLES/2
VR https://openqa.suse.de/tests/9527468

Schedule access_beta_distribution in rmt_server_install

---

lib/qesapdeployment.pm
lib/trento.pm
tests/sles4sap/trento/cluster_configure.pm

More functions to generate all the configuration files needed as running the qe-sap-deployment using its `build.sh`
- Verification run: http://openqaworker15.qa.suse.cz/tests/32374

qesapdeployment lib function for build.sh configuration

---

tests/transactional/host_config.pm

Failure: https://openqa.opensuse.org/tests/2698023#step/host_config/25
VR: https://openqa.opensuse.org/tests/2698887#

Do not install tar on ALP

---

lib/qesapdeployment.pm
lib/trento.pm
schedule/sles4sap/trento/trento.yml
tests/sles4sap/trento/cluster_deploy.pm
tests/sles4sap/trento/cluster_destroy.pm
tests/sles4sap/trento/deploy_trento.pm
tests/sles4sap/trento/init_jumphost.pm
tests/sles4sap/trento/test_trento_deploy.pm
tests/sles4sap/trento/test_trento_web.pm

Add test to deploy a SAP Landscape cluster on Azure
Add test to destroy the cluster at the end
- Verification run: http://openqaworker15.qa.suse.cz/tests/33088# http://openqaworker15.qa.suse.cz/tests/34767#

Add qesap deployment in Trento test

---

tests/installation/welcome.pm

Reverts os-autoinst/os-autoinst-distri-opensuse#15554

Revert "Update textmode key for HA/SLES on Full 15-SP5"

---

data/autoyast_sle15/create_hdd/create_hdd_maintenance.xml.ep

- Related ticket: https://progress.opensuse.org/issues/111743
- Verification runs : https://openqa.suse.de/tests/overview?build=ge0r%2Fos-autoinst-distri-opensuse%23autoyast-poo-111743&arch=x86_64
- Related MR: https://gitlab.suse.de/qa-maintenance/qam-openqa-yml/-/merge_requests/385

Add AutoYast testsuites for YaST MU chained deps

---

tests/xfstests/run.pm

Using background_script_run to replace previous loop sleep way to wait the file complete is more safety.
https://openqa.opensuse.org/tests/2419805
https://openqa.suse.de/tests/8972022

xfstests: modify the upload log wait loop

---

schedule/kernel/sles4sap/hana_cluster_node.yaml

This is just a copy of the existing schedule with wmp_simple scheduled on top.
- Related ticket: https://progress.opensuse.org/issues/105235
- Needles: -

Add wmp cluster

---

schedule/yast/maintenance/autoupgrade_sle15sp4-1_scc_we_sdk_basesys_wsm_srv_desk_lgm_contm_pcm_def_full.yaml
schedule/yast/sle_15_sp3/autoyast_create_hdd_maintenance_deregister.yaml

We need ensure system de-registered and MUs repo cleaned before migration.
Related ticket: https://progress.opensuse.org/issues/116578
MR : https://gitlab.suse.de/qa-maintenance/qam-openqa-yml/-/merge_requests/384
Needles: N/A
https://openqa.nue.suse.com/tests/9600119# 15sp3 installation
https://openqa.nue.suse.com/tests/9600120# migration with MUs

Ensure deregistered and clean MUs before migration

---

lib/mr_test_lib.pm
lib/mr_test_run.pm
tests/sles4sap/saptune/mr_test.pm

Add more comments in general for mr_test
- Related ticket: no
- Needles: no
- Verification run: no

Add more comments in general for mr_test

---

lib/main_publiccloud.pm

- Include upload_image test before migration
- Verification run:  http://autobot.qa.suse.de/tests/3448# 
CASEDIR=https://github.com/yarunachalam/os-autoinst-distri-opensuse.git#upimg

Included upload_image test before migration.

---

tests/virt_autotest/login_console.pm
tests/virt_autotest/reboot_and_wait_up_upgrade.pm

* **Subroutine** STORE in bmwqemu checks letters and invalidate test run if they are lower cases, for example, [this one](http://openqa.suse.de/tests/9574140#step/reboot_and_wait_up_upgrade/2).
* **Capitalise** all parameters that are used for host upgrade test suites and, at the same time, rename some of them to be
more concise and accurate:
* **reboot_for_upgrade_step** to UPGRADE_AFTER_REBOOT
* **offline_upgrade** to OFFLINE_UPGRADE
* **first_reboot_after_upgrade** to REBOOT_AFTER_UPGRADE 
* **after_upgrade** to AFTER_UPGRADE
* [x86_64 host offline upgrade](https://openqa.suse.de/tests/9601447)
* [x86_64 host online upgrade](https://openqa.suse.de/tests/9612222)
* [aarch64 host offline upgrade](http://10.67.131.12/tests/1025)
* [guest …

Capitalise and rename upgrade parameters

---

data/journal_check/bug_refs.json

Those appear randomly, so I didn't start a verification run.

data/journal_check/bug_refs.json: Add 15.5 to some entries

---

tests/xfstests/run.pm

As before when reboot not work we change to use reset, but most of case a reset still can't reboot successful. Here change to use magic sysrq key to a force reboot.
- Verification run: https://openqa.suse.de/t9622898 reboot successful here(https://openqa.suse.de/tests/9622898#step/run/1961), and log file upload successfully in log page(https://openqa.suse.de/tests/9622898/file/run-opt_logs.tar.gz)
- Compare with previous result https://openqa.suse.de/tests/9565012#step/run/1964 when btrfs/262 hang the system
- Add one more line with fatal => 0, now it could show logs when crash happens. https://openqa.suse.de/tests/9627636

xfstests: use alt-sysrq-b when system got hang

---

tests/security/yast2_apparmor/manually_add_profile_ncurses.pm

VRs:
- SLES 15-SP4: https://openqa.suse.de/tests/9634451
- TW: https://openqa.opensuse.org/tests/2767660

yast2_apparmor: small fix for tumbleweed

---

tests/sles4sap/saptune/mr_test.pm

[bsc#1190787](https://bugzilla.suse.com/show_bug.cgi?id=1190787) affects both SLE12+ & SLE15+
- Verification run: https://openqa.suse.de/tests/9635010

sles4sap: Add soft-failure for bsc#1190787

---

tests/security/cc/trustedprograms.pm

see https://progress.opensuse.org/issues/96438

Add soft_failure on trustedprogram

---

lib/qesapdeployment.pm

qesapdeployment.pm does not currently accept additional arguments for 
commands used by qesap.py. This PR adds additional "cmd_options" into 
qesapdeployment/qesap_execute sub and appends it to the final command.
- Needles: N/A
GCP: https://mordor.suse.cz/tests/4771
Azure: https://mordor.suse.cz/tests/4772#

qesap-py, allow appending optional arguments

---

schedule/kernel/sles4sap/wmp_simple_hana_baremetal.yaml

Fix typo in schedule

---

products/microos/main.pm

- Verification run: https://openqa.opensuse.org/tests/2783094
- Related ticket: https://progress.opensuse.org/issues/117643
CC @sysrich

products/microos/main.pm: Skip cockpit_service in microosold2microos

---

data/containers/k8s_job_manifest.yaml
lib/containers/k8s.pm
products/alp/main.pm
tests/containers/run_container_in_k3s.pm
tests/containers/run_container_in_k8s.pm

Test installation of k3s using the script /usr/bin/k3s-install
And run a k8s test
- Related ticket: https://progress.opensuse.org/issues/117004
- Verification run: https://openqa.opensuse.org/tests/2791397

K3s test in Alp

---

data/sles4sap/qe_sap_deployment/qesap_azure.yaml
lib/qesapdeployment.pm
schedule/sles4sap/qesapdeploy/qesap.yml
t/09_qesapdeployment.t
tests/sles4sap/qesapdeployment/configure.pm
tests/sles4sap/qesapdeployment/deploy.pm
tests/sles4sap/qesapdeployment/destroy.pm
tests/sles4sap/qesapdeployment/test_cluster.pm

Test code, reference config.yaml for the qesap.py script (mostly for Azure), schedule
- Verification run: http://1c242.qa.suse.de/tests/1214 http://1c242.qa.suse.de/tests/1228
AZURE: http://openqaworker15.qa.suse.cz/tests/49622 http://openqaworker15.qa.suse.cz/tests/50666

Simple test to validate qe-sap-deployment project

---

tests/publiccloud/run_ltp.pm
variables.md

- Related ticket: https://progress.opensuse.org/issues/116668

Adding new python runltp-ng for LTP tests

---

CONTRIBUTING.md
Makefile
tests/sles4sap/sapconf.pm
tests/sles4sap/sys_param_check.pm

- Related ticket: https://progress.opensuse.org/issues/117835
- Verification run:  [please omit the failed case, it is not released to this code change]
http://openqa.suse.de/tests/9706843
http://openqa.suse.de/tests/9706851

Add variable to record_soft_fail CI check

---

lib/kdump_utils.pm

JeOS aarch64 runs are often failing in reboot after triggering crash or while waiting for `crash` utility to finish its execution.
- ticket: [[aarch64] Adjust timeouts in kdump_and_crash](https://progress.opensuse.org/issues/117796)
https://openqa.suse.de/tests/9715332

Adjust timeout in kdump_and_crash for aarch64

---

tests/shutdown/cleanup_before_shutdown.pm

- Related ticket: [poo#116770](https://progress.opensuse.org/issues/116770)
- Verification run: [create_hdd_textmode](https://openqa.suse.de/tests/9716078), [extra_tests_textmode_mod_desktop](https://openqa.suse.de/tests/9715835), [extra_tests_textmode](https://openqa.suse.de/tests/9716177), [yast2_ncurses_textmode](https://openqa.suse.de/tests/9716178)

Remove /var/lib/wicked/*.xml also on svirt backend

---

tests/console/journald_fss.pm

- Related ticket: https://bugzilla.suse.com/show_bug.cgi?id=1196220
- x86_64: https://openqa.suse.de/tests/9720447
- s390x: https://openqa.suse.de/tests/9720448

journald_fss: fix bsc#1196220

---

tests/console/aide_check.pm

- Related ticket: https://progress.opensuse.org/issues/117916
- x86_64: https://openqa.suse.de/tests/9720567
- s390x: https://openqa.suse.de/tests/9720886
- ppc64le: https://openqa.suse.de/tests/9720952
- aarch64: https://openqa.suse.de/tests/9720570

aide_check: use specific folder instead of the whole fs

---

tests/console/start_systemd_testkit_offline.pm
tests/console/zypper_log_packages.pm
wheels.yaml

Reverts os-autoinst/os-autoinst-distri-opensuse#15336

Revert "Build a wheel for logging offline"

---

data/wicked/test-ext-firewall.sh
tests/wicked/before_test.pm
tests/wicked/startandstop/sut/t18_firewall_extension.pm

Related bugs: bsc#1189560 bsc#1201053
PR: https://github.com/openSUSE/wicked/pull/933
- Verification run: http://openqa.wicked.suse.de/tests/84114

wicked: Add firewall extension test

---

data/autoyast_opensuse/autoyast_leap-micro.xml.ep

More info: https://bugzilla.suse.com/show_bug.cgi?id=1203934#c6
VR: http://kepler.suse.cz/tests/19423#step/cockpit_service/7

Enable networking explicitly in leap-micro AY profile

---

lib/utils.pm

Test connection via hostname to itself and other node in cluster
- Fails:
https://openqa.suse.de/tests/9746988#step/ha_cluster_join/10
https://openqa.suse.de/tests/9744875#step/ha_cluster_join/8
https://openqa.suse.de/tests/9744121
https://openqa.suse.de/tests/9740233
https://openqa.suse.de/tests/9734347
https://openqa.suse.de/tests/9722156
https://openqa.suse.de/tests/9703175
https://openqa.suse.de/tests/9697867
https://dzedro.suse.cz/tests/788
https://dzedro.suse.cz/tests/793
https://dzedro.suse.cz/tests/795
https://openqa.suse.de/tests/9752129
https://openqa.suse.de/tests/9752203

hostname: Restart network on MM jobs with supportserver

---

data/virt_autotest/guest_params_xml_files/sles_15_sp4_64_kvm_hvm_uefi_with_power_management_x86_64.xml
data/virt_autotest/guest_params_xml_files/sles_15_sp4_64_xen_hvm_uefi_with_power_management_x86_64.xml
data/virt_autotest/guest_params_xml_files/sles_15_sp5_64_kvm_hvm_uefi_with_power_management_x86_64.xml
data/virt_autotest/guest_params_xml_files/sles_15_sp5_64_kvm_hvm_uefi_without_power_management_x86_64_using_virtmanagerlt3.0.0.xml
data/virt_autotest/guest_params_xml_files/sles_15_sp5_64_xen_hvm_uefi_with_power_management_x86_64.xml
data/virt_autotest/guest_params_xml_files/sles_15_sp5_64_xen_hvm_uefi_without_power_management_x86_64_using_virtmanagerlt3.0.0.xml
lib/guest_installation_and_configuration_base.pm

* **Add** SLE 15-SP5 uefi guests profiles:
* sles_15_sp5_64_kvm_hvm_uefi_with_power_management_x86_64.xml
* sles_15_sp5_64_xen_hvm_uefi_with_power_management_x86_64.xml
* sles_15_sp5_64_kvm_hvm_uefi_without_power_management_x86_64_using_virtmanagerlt3.0.0.xml
* sles_15_sp5_64_xen_hvm_uefi_without_power_management_x86_64_using_virtmanagerlt3.0.0.xml
* **Update** SLE 15-SP4 guests profiles:
* sles_15_sp4_64_kvm_hvm_uefi_with_power_management_x86_64.xml
* sles_15_sp4_64_xen_hvm_uefi_with_power_management_x86_64.xml
* **Use** timeout command with options --kill-after and --signal to make sure command returns after timeout instead of hang in the system sometimes.
* [sev-es test](https://openqa.suse.de/tests/9707066) Failed due to bsc#1203923
* [15sp5 on 15sp5 uefi …

Enhance uefi test suites

---

data/sles4sap/qe_sap_deployment/qesap_aws.yaml
data/sles4sap/qe_sap_deployment/qesap_azure.yaml
data/sles4sap/qe_sap_deployment/qesap_gcp.yaml
lib/qesapdeployment.pm
tests/sles4sap/qesapdeployment/destroy.pm

Adapt the qesap config.yaml to the new format
AZURE: https://openqaworker15.qa.suse.cz/tests/54854 PASS
GCP: https://openqaworker15.qa.suse.cz/tests/54862 PASS
AWS: https://openqaworker15.qa.suse.cz/tests/54855 FAIL as Ansible is not able to contact nodes, issue present in main branch too

Add hana_vars section in qe-sap-deployment config.yaml

---

data/console/ansible/galaxy.yml
data/console/ansible/hosts
data/console/ansible/main.yaml
data/console/ansible/roles/test/files/static.txt
data/console/ansible/roles/test/handlers/main.yaml
data/console/ansible/roles/test/meta/main.yaml
data/console/ansible/roles/test/tasks/main.yaml
data/console/ansible/roles/test/templates/README.txt.j2
lib/opensusebasetest.pm
products/alp/main.pm
schedule/functional/extra_tests_textmode.yaml
schedule/qam/common/mau-extratests2.yaml
tests/console/ansible.pm

This test is single machine but uses **SSH** and **SUDO** as those are default.
- Related ticket: [poo#116935](https://progress.opensuse.org/issues/116935)
- Discovered bug: [bsc#1204182](https://bugzilla.opensuse.org/show_bug.cgi?id=1204182)
- Verification run: [Tumbleweed](https://pdostal-server.suse.cz/tests/2632), [Leap 15.4](https://pdostal-server.suse.cz/tests/2605), [Leap 15.3](https://pdostal-server.suse.cz/tests/2633), [SLE 15-SP4](https://pdostal-server.suse.cz/tests/2742), [SLE 15-SP3](https://pdostal-server.suse.cz/tests/2747)

Introduce Ansible console test

---

lib/publiccloud/instance.pm
lib/publiccloud/instances.pm
lib/publiccloud/provider.pm
lib/publiccloud/ssh_interactive.pm
lib/version_utils.pm
tests/console/journalctl.pm
tests/publiccloud/instance_overview.pm
tests/publiccloud/prepare_instance.pm
tests/publiccloud/prepare_tools.pm
tests/publiccloud/ssh_interactive_start.pm
tests/publiccloud/upload_image.pm

Re-establishes the ssh tunnel after a publiccloud instance is being rebooted using the instance->softreboot method. This is necessary for the slem on publiccloud test runs, where we need to do many reboots due to the transactional updates.
This is another attempt of https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/15643 but without the ssh tunnel loop running in the background
- Related ticket: https://progress.opensuse.org/issues/116332
* [sle-15-SP4-AZURE-BYOS-Updates-x86_64-publiccloud_ahb](https://duck-norris.qam.suse.de/tests/11029)
* [sle-15-SP4-AZURE-BYOS-Updates-aarch64-publiccloud_consoletests](https://duck-norris.qam.suse.de/tests/11030)
* [sle-15-SP4-AZURE-BYOS-Updates-x86_64-publiccloud_consoletests](https://duck-norris.qam.suse.de/tests/1103 …

Re-establish ssh tunnel after instance reboot

---

lib/y2_installbase.pm
schedule/yast/minimal+base/minimal+base@yast.yaml
tests/installation/select_only_visible_patterns_from_top.pm

Replace select_patterns when unselecting all patterns
- Related ticket: https://progress.opensuse.org/issues/108293
- Verification run: https://openqa.suse.de/tests/9757048#

Replace select_patterns when unselecting all patterns

---

lib/Utils/Logging.pm

with revert of PR#15713 we can correct this minor error.
See poo#117622 for more details.

Remove script_output from use line

---

lib/publiccloud/ssh_interactive.pm

Retry the termination of the tunnel console to improve the stability of the termination process.
- Related ticket: https://progress.opensuse.org/issues/116332
- Related failure: https://openqa.suse.de/tests/9772288#step/journalctl/70
- Verification run: https://duck-norris.qam.suse.de/tests/11065

Improve stability of ssh_interactive_leave

---

data/security/aide_conf
tests/console/aide_check.pm

- Related ticket: https://progress.opensuse.org/issues/119188
- https://openqa.suse.de/tests/9779268
- https://openqa.suse.de/tests/9779269
- https://openqa.suse.de/tests/9779267

Fix aide_check

---

tests/console/ntp.pm
tests/console/prjconf_excluded_rpms.pm
tests/console/systemd_wo_udev.pm
tests/jeos/kiwi_templates.pm
tests/microos/libzypp_config.pm

Follow up for https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/15725

Serial terminal was moved to serial_terminal lib

---

lib/publiccloud/aws_client.pm
lib/publiccloud/azure_client.pm
lib/publiccloud/k8s_provider.pm
tests/containers/push_container_image_to_pc.pm
tests/containers/run_container_in_k8s.pm

- Related ticket: https://progress.opensuse.org/issues/110722
- https://openqa.suse.de/tests/9800268#details
- http://openqa.suse.de/tests/9800296#details
- http://openqa.suse.de/tests/9800301#details
- http://openqa.suse.de/tests/9800325#details

Public cloud: Remove the service param in the PC clients 

---

tests/containers/run_container_in_k8s.pm

Simplify k8s tests and remove redundances
- Related ticket: https://progress.opensuse.org/issues/110722
- Verification run: https://openqa.suse.de/tests/9807974

Public Cloud: Simplify k8s tests

---

lib/qam.pm

Do not add repos if already present
- Related ticket: https://progress.opensuse.org/issues/119470
- Verification run:  https://openqa.suse.de/tests/9821897
https://openqa.suse.de/tests/9821916

Do not add repos if present

---

schedule/jeos/sle/fips.yaml
schedule/security/stig.yaml
schedule/staging/cryptlvm_minimal_x@s390x-staging.yaml
schedule/yast/ssh-x.yaml
schedule/yast/zfcp.yaml

- Related pull request: #15777
- Related ticket: [poo#118588](https://progress.opensuse.org/issues/118588)
- Verification run: Not needed

Fix yamllint warnings in schedule/

---

lib/main_common.pm

- Related ticket: https://progress.opensuse.org/issues/119560
- Needles: N/A
- Verification run: [15-SP4-QR](https://openqa.suse.de/tests/9826832)

Add test_repo_setup for QR runs

---

schedule/security/encryption/fips_lvm_full_encrypt_maint.yaml

Fix this issue: https://openqa.suse.de/tests/9782754
- Related ticket: https://progress.opensuse.org/issues/116956, https://progress.opensuse.org/issues/117103
- Needles: N/A
- Verification run: 15-SP4-QU [x86_64](https://openqa.suse.de/tests/9832579), [aarch64](https://openqa.suse.de/tests/9832580), [s390x](https://openqa.suse.de/tests/9832586), [x86_64_uefi](https://openqa.suse.de/tests/9832587)

Add schedule for fips full lvm in maintenance

---

schedule/security/encryption/fips_lvm_encrypt_separate_boot.yaml

- Related ticket: https://progress.opensuse.org/issues/119650
- Needles: N/A
- Verification run: [x86_64](https://openqa.suse.de/tests/9844060#step/welcome/8) | [aarch64](https://openqa.suse.de/tests/9844106#step/welcome/8) | [ppc64le](https://openqa.suse.de/tests/9844076#step/welcome/8) | [s390x](https://openqa.suse.de/tests/9844075#step/welcome/8)

Add lvm_encrypt_separate_boot for maintenance

---

lib/publiccloud/provider.pm

- Related ticket: https://progress.opensuse.org/issues/119647
1) http://quasar.suse.cz/tests/1208/logfile?filename=autoinst-log.txt
2) http://quasar.suse.cz/tests/1209/logfile?filename=autoinst-log.txt

Select host console in teraform_destroy

---

.github/workflows/checklist.yml
.github/workflows/ci-isotovideo.yml
.github/workflows/ci.yml
.github/workflows/deploy.yml

Version 1 of this action is deprecated and not supported by new runners.

Update action/checkout to v3

---

data/autoyast_sle15/hpc/create_hdd_textmode_aarch64.xml.ep
data/autoyast_sle15/hpc/create_hdd_textmode_x86_64.xml.ep
lib/autoyast.pm

- Related ticket: https://progress.opensuse.org/issues/119704
https://openqa.suse.de/tests/9850012#step/installation/10 x86_64
https://openqa.suse.de/tests/9850011#step/installation/14 aarch64

Add LTSS addon into HPC autoyast profile

---

data/journal_check/bug_refs.json

Ignore both health check messages.
https://duck-norris.qam.suse.de/tests/11082#

Ignore health-check messages for ALP

---

lib/publiccloud/basetest.pm
lib/publiccloud/gce.pm

- Related ticket: https://progress.opensuse.org/issues/113480
- Verification run: http://quasar.suse.cz/tests/1248

Export GCE instace serial log on failure.

---

tests/publiccloud/migration.pm

- Upload distro_migration.log to DMS openqa jobs
- Verification run: https://openqa.suse.de/tests/9855293#downloads

Upload distro_migration.log to DMS openqa jobs

---

tests/publiccloud/ssh_interactive_end.pm

- Related ticket: https://progress.opensuse.org/issues/119848
- VR: http://quasar.suse.cz/tests/1254

PublicCloud - pass args to cleanup call in ssh_interactive_end

---

lib/opensusebasetest.pm

POO: https://progress.opensuse.org/issues/119239
UEFI,gnome workaround for bug: https://bugzilla.suse.com/show_bug.cgi?id=1203641
- Related ticket:  https://progress.opensuse.org/issues/119239
- Needles: N/A
- Verification run: [legacy and gnome](http://openqa.suse.de/t9801030), [UEFI and gnome](http://openqa.suse.de/t9801031), [legacy and textmode](http://openqa.suse.de/t9801876), [UEFI and textmode](http://openqa.suse.de/t9802074)

Add workaround for UEFI mode

---

data/generalhw_scripts/rpi_pico_w_keyboard/README.md
data/generalhw_scripts/rpi_pico_w_keyboard/keymap.h
data/generalhw_scripts/rpi_pico_w_keyboard/rpi_pico_w_keyboard.ino

Ticket: https://progress.opensuse.org/issues/119566

Add rpi realhw usb keyboard emulation option

---

tests/console/sudo.pm

Test sudo without changing the configuration. The expected behaviour is different on public cloud.
- Related ticket: https://progress.opensuse.org/issues/120019
Broken sudo: https://openqa.opensuse.org/tests/2859181#live
Working sudo: https://openqa.opensuse.org/tests/2859138#live
Is my interpretation of public cloud behaviour correct?

tests/console/sudo: Test the default configuration

---

lib/trento.pm
t/08_trento.t
tests/sles4sap/trento/cluster_configure.pm
tests/sles4sap/trento/cluster_deploy.pm
tests/sles4sap/trento/deploy_trento.pm
tests/sles4sap/trento/destroy.pm
tests/sles4sap/trento/init_jumphost.pm
tests/sles4sap/trento/install_agents.pm
tests/sles4sap/trento/setup_jumphost.pm
tests/sles4sap/trento/test_trento_deploy.pm
tests/sles4sap/trento/test_trento_web.pm

Move trento from a base class to a lib of functions
- Verification run: https://openqaworker15.qa.suse.cz/tests/64862#

Move trento from a base class to a lib of functions

---

tests/ha/iscsi_client.pm

Since https://github.com/yast/yast-iscsi-client/pull/121, the packages `open-iscsi` and `iscsiuio` have been dropped as dependencies for `yast2-iscsi-client`, requiring these packages to be explicitly installed to properly use the yast2 iscsi client module. This PR attempts the `yast2-iscsi-client` installation with `--recommends`, and then verifies whether the dropped dependency packages were installed; if not installed, a soft fail is recorded and the dependencies are installed explicitly. A check for the release notes of SLES 15-SP5 was also added when running on SLES 15-SP5: if the documentation bug is present in the release notes, then the soft fail will not be recorded.
- Related ticket: https://bugzilla.suse.com/show_bug.cgi?id=1204528, …

Add soft fail workaround for bsc#1204528 bsc#1204978

---

lib/main_common.pm
tests/kernel/fwupd.pm

fwupd will be scheduled on SLE 15+. get-devices will be run on 15-SP3+.
12-SP3: http://10.100.12.105/tests/1922
12-SP4: http://10.100.12.105/tests/1921
12-SP5: http://10.100.12.105/tests/1920
15: http://10.100.12.105/tests/1915
15-SP1: http://10.100.12.105/tests/1917
15-SP2: http://10.100.12.105/tests/1916
15-SP3: http://10.100.12.105/tests/1918
15-SP4: http://10.100.12.105/tests/1915
15-SP5: http://10.100.12.105/tests/1923

fwupd: Update for older SLE releases

---

tests/wsl/firstrun.pm

WSL based on sle15sp5 just received latest features as WSL GUI pattern and possibility to register WSL against SLED.
- Verification run: http://kepler.suse.cz/tests/19511#step/firstrun/14

WSL GUI pattern and SLED product in 15sp5

---

tests/installation/boot_encrypt.pm

Ugly :-/
- Verification run: https://openqa.opensuse.org/t2866162

installation/boot_encrypt: New grub2 is in more of Tumbleweed now

---

t/09_qesapdeployment.t

Remove previously added hot fix
Improve assert messages
Improve test isolation
- Verification run: github CI/CD

Fix qesapdeployment unit testing

---

lib/publiccloud/gcp_client.pm
tests/containers/helm.pm

- Related ticket: https://progress.opensuse.org/issues/120234
- Verification run: http://openqa.suse.de/tests/9952683

Extend installation of chrony to 15-SP5

---

tests/publiccloud/upload_image.pm
variables.md

Update the default GCP region to europe-west1-b.

Update default GCP region

---

schedule/jeos/sle/jeos-main.yaml
schedule/sle-micro/virt.yaml

Fix yamllint warnings 'Comment not indented like content'

---

tests/console/systemd_rpm_macros.pm

Increase rpmbuild timeout
- Related ticket: https://progress.opensuse.org/issues/120381
- Needles: no
- Verification run: https://openqa.suse.de/tests/9954566#
- https://openqa.suse.de/tests/9961588

Increase rpmbuild timeout

---

tests/console/hostname.pm

And also remove a leftover line from debugging (?).
- Related ticket: https://progress.opensuse.org/issues/120345
- Verification run: https://openqa.opensuse.org/tests/2878492#live

console/hostname: Only attempt to change the setting if the file exists

---

lib/containers/container_images.pm

- Related ticket: https://progress.opensuse.org/issues/104583
- Verification run: http://openqa.suse.de/tests/9963102

Containers: skip zypper_docker update test if no updates

---

tests/installation/hostname_inst.pm

Change test module maintainer to Yam squad.

Change maintainer hostname_inst

---

lib/publiccloud/azure.pm

Azure exports only bootlog on console.
- Related ticket: https://progress.opensuse.org/issues/113480
- Verification run: http://quasar.suse.cz/tests/1282#downloads

PublicCloud - collect bootlog on failure (azure)

---

lib/publiccloud/ec2.pm

- Related ticket: https://progress.opensuse.org/issues/113480
- Verification run: http://quasar.suse.cz/tests/1255

Export console log and screenshot on failure in EC2

---

Makefile
lib/mr_test_lib.pm
lib/publiccloud/ssh_interactive.pm
schedule/sles4sap/sles4sap_gnome_saptune.yaml
tests/publiccloud/prepare_instance.pm
tests/sles4sap/publiccloud/mr_test_setup_env.pm
tests/sles4sap/publiccloud/qesap_terraform.pm
tests/sles4sap/saptune/mr_test.pm
tests/sles4sap/saptune/mr_test_run.pm

Support run mr_test on Public Cloud: Azure
NOTE:
1. about the PC image:  https://dist.suse.de/ibs/SUSE:/${product}:/GA:/TEST/images/${product}-SAP-BYOS.x86_64.*-Azure-.*
(I did not include public image this time as `qesapdeployment` still failed on create instances)
2. about SLE 15: we don't test this product, see TEAM-6798 for more details
3. about cleanup: test module "ssh_interactive_end" does the cleanup
4. about the failure: all issues are known and tracked by https://progress.opensuse.org/issues/119806
- Related ticket: https://jira.suse.com/browse/TEAM-6798
- Needles: NA
- Related MR:
https://gitlab.suse.de/qa-css/openqa_ha_sap/-/merge_requests/386
https://gitlab.suse.de/qa-maintenance/metadata/-/merge_requests/727
- Needles: NA
- Verification run: Flavor: …

Support run mr_test on Public Cloud

---

tests/installation/welcome.pm

- Related ticket: https://progress.opensuse.org/issues/115352
https://openqa.suse.de/tests/9974080
https://openqa.suse.de/tests/9974157

Update SLES textmode keyboard shortcut for 15-SP4 Full

---

tests/qam-updinstall/update_install.pm

- Fail: https://openqa.suse.de/tests/9973372
https://openqa.suse.de/tests/9976847
https://openqa.suse.de/tests/9976848
https://openqa.suse.de/tests/9976948

update_install: Auto accept license in zypper dup

---

tests/x11/vnc_two_passwords.pm

we experience sporadic issue with assert_screen 'tigervnc-desktop-loggedin',
so increase timeout value can be a workaround on some weak workers.
and further workarounds provided as welll for xev and performance issue.
xev hangs sporadic (1%) which cannot be fixed at moment, so provide record_info with ticket
poo#120282 for a later solution
see https://progress.opensuse.org/issues/119416
VRs:
https://openqa.suse.de/tests/9931082
https://openqa.suse.de/tests/9935878
https://openqa.suse.de/tests/9941441#next_previous
https://openqa.opensuse.org/tests/2868571 (opensuse aarch64)
https://openqa.suse.de/tests/9952666 (vnc-two-password@svirt-xen-hvm)
If we still have this kind of issue, we need to re-write on this test module.

Workaround performance/timeout issue for 'vnc-two-passwords' on aarch64

---

data/sles4sap/script_output.yaml
lib/qesapdeployment.pm
t/09_qesapdeployment.t
tests/sles4sap/qesapdeployment/test_cluster.pm

It is sort of a script_output version for Ansible commands
- Verification run: https://openqaworker15.qa.suse.cz/tests/68519 In particular the string for this box https://openqaworker15.qa.suse.cz/tests/68519#step/test_cluster/33 is obtained as output of this new function
https://openqaworker15.qa.suse.cz/tests/68541

Ansible remote command with returned output

---

tests/containers/bci_repo.pm

Increase the robustness of the test run by adding retries for network-dependend zypper operations.
- Related ticket: https://progress.opensuse.org/issues/118822
- Verification run: https://duck-norris.qam.suse.de/tests/11127

Add retry for network commands

---

schedule/qam/common/mau-webserver.yaml

- Related ticket: [bsc#31972](https://progress.opensuse.org/issues/31972)
- Verification run: [Leap 15.4](https://pdostal-server.suse.cz/tests/3119), [SLE 15-SP4](https://pdostal-server.suse.cz/tests/3120), [Tumbleweed](https://pdostal-server.suse.cz/tests/3121)

Test nginx on mau-webserver

---

tests/containers/run_container_in_k8s.pm

- Related ticket: https://progress.opensuse.org/issues/120660
- Verification run: http://openqa.suse.de/tests/10003565
- Note: see http://openqa.suse.de/tests/10003565#step/run_container_in_k8s_GCE/66

containers: Improve k8s job deletion

---

lib/publiccloud/ec2.pm

VR : http://autobot.qa.suse.de/tests/3508

Update uploader VM AMIs

---

tests/console/snapper_cleanup_timeline.pm

- Related ticket: https://progress.opensuse.org/issues/117211
- Needles: na
- Verification run: https://openqa.suse.de/tests/10010703

Add sync after dd in snapper_cleanup_timeline

---

schedule/qam/common/mau-webserver.yaml

- Related pull requst: #15924
- Related ticket: [poo#120823](https://progress.opensuse.org/issues/120823)

Unschedule nginx on SLES12-SP5

---

lib/virt_autotest/utils.pm
tests/virt_autotest/sriov_network_card_pci_passthrough.pm

- Related ticket: https://progress.opensuse.org/issues/95920 and https://bugzilla.suse.com/show_bug.cgi?id=1204882
[gi-guest_developing-on-host_developing-kvm](https://openqa.suse.de/tests/10011755)
[gi-guest_developing-on-host_sles12sp5-xen](https://openqa.suse.de/tests/10013445)

Release DHCP client IP for SR-IOV test

---

Makefile

- Related ticket: [poo#118588](https://progress.opensuse.org/issues/118588)

Make perlcritic output github annotated output

---

data/autoyast_sle15/autoyast_sle-micro.xml.ep
data/journal_check/bug_refs.json

For details, see commit messages.

Prepare sle-micro 5.4 testing

---

tests/console/firewalld.pm

- Related ticket: [poo#120955](https://progress.opensuse.org/issues/120955)
- Verification run: [mau-extratests1@64bit](https://pdostal-server.suse.cz/tests/3169)

Test firewalld timeout

---

tests/console/firewalld.pm

Fixing #15980
- Related ticket: [poo#120985](https://progress.opensuse.org/issues/120985)
- Related failure: [opensuse-Tumbleweed-JeOS-for-kvm-and-xen-x86_64](https://openqa.opensuse.org/tests/2910306#step/firewalld/159)
- Verification run: [pdostal-server.suse.cz/t3350](https://pdostal-server.suse.cz/tests/3350)

Fix firewalld debug timeout

---

.github/workflows/ci.yml

Update perltidy to 20221112

---

tests/ai_ml/tvm.pm

- Related ticket: https://progress.opensuse.org/issues/113075
- Verification run: https://openqa.opensuse.org/t2458693

tvm: Do not force python3-tvm since tvmc should pull the needed package

---

tests/x11/firefox.pm

we have sometimes issue with crash and need to send crash report. 
see https://bugzilla.suse.com/show_bug.cgi?id=1205511 and 
https://progress.opensuse.org/issues/120753

Send firefox crash report if crashed

---

schedule/yast/autoyast/autoyast_iscsi_ibft.yaml

- Related PR: https://github.com/os-autoinst/os-autoinst/pull/2219

Delete portal line in test data

---

tests/yast2_gui/yast2_security.pm

- PR#15889 forgot one if (is_sle('>=15-SP4')
- Verification run: https://openqa.opensuse.org/tests/2920221

Fix for yast2_security in Tumbleweed

---

lib/registration.pm
tests/console/add_phub_extension.pm
tests/console/ansible.pm
tests/console/python_flake8.pm
tests/console/python_scientific.pm
tests/console/sssd_389ds_functional.pm
tests/console/vmstat.pm
tests/console/wpa_supplicant.pm
variables.md

- Related ticket:https://progress.opensuse.org/issues/120879
- Verification run: https://openqa.suse.de/tests/10041939
[Please ignore the failed cases, they are known issues]

Skip 'extra_tests_phub' test if packagehub is not ready

---

tests/fips/stunnel.pm

Since real test target is stunnel, with the upcoming wayland default desktop vnc is a bit too shaky choice; so we'd replace vnc with a netcat message exchange from client to server
- Related ticket: https://progress.opensuse.org/issues/121030
- 15SP4 Verification runs:
https://openqa.suse.de/tests/10082094           
https://openqa.suse.de/tests/10082095              
- 15SP5:
https://openqa.suse.de/tests/10082119          
https://openqa.suse.de/tests/10082120

Simplify stunnel test 

---

tests/publiccloud/azure_cli.pm

- Verification run: [azure_cli@64bit](https://pdostal-server.suse.cz/tests/3417)

Fail when 'az vm create' command fails

---

lib/trento.pm
t/08_trento.t
tests/sles4sap/trento/test_hana_stop.pm

Loop to query the status after the primary stop
Collect scenario also if pass
Fix the stopped instance
- Related ticket: CFSA-1577
- Verification run: https://openqaworker15.qa.suse.cz/tests/96946 https://openqaworker15.qa.suse.cz/tests/96947 https://openqaworker15.qa.suse.cz/tests/97476

Trento wait for stop

---

lib/containers/common.pm
lib/containers/utils.pm
tests/microos/toolbox.pm

* microos/toolbox: Use a newer SLE Micro toolbox image
* lib/containers/{common,utils}: Work around slow searches on registry.suse.com
MicroOS-Image-ContainerHost: https://openqa.opensuse.org/tests/2932287
Staging-DVD-container-host-microos: https://openqa.opensuse.org/t2932288

Work around some registry.suse.com issues

---

lib/publiccloud/gce.pm

Adds a handle to include PUBLIC_CLOUD_ARCH when uploading an new image to GCE. This is required to allow the upload of custom arm64 images e.g. for SLEM on PublicCloud.
- Related ticket: https://progress.opensuse.org/issues/119011
- Verification run: https://duck-norris.qe.suse.de/tests/11257#step/upload_image/32

Add architecture handling for GCE image upload

---

tests/jeos/kiwi_templates.pm

Verification run: https://openqa.opensuse.org/t2942901

jeos/kiwi_templates: Leap 15.5 finally has kiwi-templates-Minimal

---

data/sles4sap/qe_sap_deployment/mr_test_azure.yaml

Support public images on Azure for mr_test: BYOS + PAYG
TEAM-7023 - Modify mr_test maintenance tests in ow15 to use Public OS Images - Azure
- Related ticket: https://jira.suse.com/browse/TEAM-7023
- Needles: NA
Maintenance: SLE 15 SP4 SAP Incidents (all passed):
https://openqaworker15.qa.suse.cz/tests/overview?distri=sle&version=15-SP4&build=%3A27019%3Alibzypp&groupid=21
Maintenance: SLE 15 SP3 SAP Incidents (all passed):
https://openqaworker15.qa.suse.cz/tests/overview?distri=sle&version=15-SP3&build=%3A27019%3Alibzypp&groupid=22
Maintenance: SLE 15 SP2 SAP Incidents (all passed):
https://openqaworker15.qa.suse.cz/tests/overview?distri=sle&version=15-SP2&build=%3A27019%3Alibzypp&groupid=23
Maintenance: SLE 15 SP1 SAP Incidents (all passed): …

Support public images on Azure: BYOS + PAYG

---

tests/publiccloud/prepare_tools.pm

image update to the Terraform v1.3.6
- Verification run: Verification runs: 
[SLE15-SP4-Azure-arm64](https://pdostal-server.suse.cz/tests/3474)
[SLE15SP1-Google](https://pdostal-server.suse.cz/tests/3476)
[SLE12-SP5-EC2](https://pdostal-server.suse.cz/tests/3477)

image update to the Terraform v1.3.6

---

lib/main_common.pm
schedule/security/crypt_krb5client.yaml
schedule/security/crypt_krb5kdc.yaml
schedule/security/crypt_krb5server.yaml
schedule/security/evm_protection.yaml
schedule/security/ima_appraisal.yaml
schedule/security/ima_measurement.yaml
schedule/security/selinux.yaml
schedule/security/system_check.yaml

- Related ticket: https://progress.opensuse.org/issues/121747
- VRs for a couple of tests:
- https://openqa.suse.de/tests/10171261
- https://openqa.suse.de/tests/10171262
Related MR: https://gitlab.suse.de/qe-security/osd-sle15-security/-/merge_requests/41

poo121747: migrate some tests to yaml

---

tests/publiccloud/prepare_tools.pm

Added Ansible installation to the pub. cloud tools image
Terrafrom version could be now set by TERRAFORM_VERSION variable for pub. cloud tools image
- Verification run:-
- Default values :
http://openqaworker15.qa.suse.cz/tests/103201
- Terrraform and Ansible version set:
https://openqaworker15.qa.suse.cz/tests/10319-
- Ansible core version set :
http://openqaworker15.qa.suse.cz/tests/103207

Ansible added, Terraform ver. is now setting for pub. cloud tools image

---

data/sles4sap/qe_sap_deployment/qesap_gcp_sapconf.yaml
lib/trento.pm
schedule/sles4sap/trento/trento.yml
t/08_trento.t
tests/sles4sap/qesapdeployment/configure.pm
tests/sles4sap/trento/cluster_configure.pm
tests/sles4sap/trento/cluster_deploy.pm
tests/sles4sap/trento/deploy_trento.pm
tests/sles4sap/trento/destroy.pm
tests/sles4sap/trento/install_agents.pm
tests/sles4sap/trento/setup_jumphost.pm
tests/sles4sap/trento/test_hana_restore_stopped.pm
tests/sles4sap/trento/test_hana_stop.pm
tests/sles4sap/trento/test_trento_deploy.pm
tests/sles4sap/trento/test_trento_web.pm

- Implement new test module and add to the scheduling
- More code to the lib, some lib methods no more needs to be public
- Fix sapconf qesap regression configuration
Related ticket: CFSA-917
- qesap regression gcp sapconf : http://1c242.qa.suse.de/tests/1469 http://openqaworker15.qa.suse.cz/tests/102153#
- trento http://openqaworker15.qa.suse.cz/tests/103169 http://openqaworker15.qa.suse.cz/tests/103170

Trento test 05.190, restarting stopped DB

---

tests/ai_ml/tvm.pm

- Related ticket: https://progress.opensuse.org/issues/116815
- Verification run: https://openqa.opensuse.org/t2963501

tvm: add input shapes to fix test

---

tests/publiccloud/download_repos.pm
tests/publiccloud/transfer_repos.pm

- Related ticket: [poo#120933](https://progress.opensuse.org/issues/120933)
- Verification run: [Incident](https://pdostal-server.suse.cz/tests/3536), [Aggregate](https://pdostal-server.suse.cz/tests/3535)

Public Cloud: Add possibility of selecting individual incidents when cloning jobs

---

lib/Utils/Logging.pm
lib/consoletest.pm
lib/opensusebasetest.pm

- Related ticket: [poo#120735](https://progress.opensuse.org/issues/120735)
- Follow up to: de0279c (#15977) and 4bad8a0 (#16058)
- Verification run: [extra_tests_textmode@64bit](https://pdostal-server.suse.cz/tests/3516), [extra_tests_gnome@64bit](https://pdostal-server.suse.cz/tests/3515)

Switch possible parts of post_fail_hooks to serial terminal

---

lib/Utils/Systemd.pm

Verification run: not needed (doc)

Systemd.pm: Fix typo in docs

---

data/lynis/baseline-lynis-audit-system-nocolors-15-SP5-aarch64-gnome
data/lynis/baseline-lynis-audit-system-nocolors-15-SP5-aarch64-textmode
data/lynis/baseline-lynis-audit-system-nocolors-15-SP5-s390x-gnome
data/lynis/baseline-lynis-audit-system-nocolors-15-SP5-s390x-textmode
data/lynis/baseline-lynis-audit-system-nocolors-15-SP5-x86_64-gnome
data/lynis/baseline-lynis-audit-system-nocolors-15-SP5-x86_64-textmode

- Related ticket: https://progress.opensuse.org/issues/122248
- https://openqa.suse.de/tests/10230282
- https://openqa.suse.de/tests/10230281
- https://openqa.suse.de/tests/10232996
- https://openqa.suse.de/tests/10232995
- https://openqa.suse.de/tests/10233202
- https://openqa.suse.de/tests/10233203

Add baseline for lynis 15-SP5

---

tests/x11/user_defined_snapshot.pm

https://progress.opensuse.org/issues/122476
- Related ticket: https://progress.opensuse.org/issues/122476
- Verification run: http://openqa.suse.de/tests/10244190

Wait more time after rebooting from a snapshot

---

lib/LTP/utils.pm

- http://quasar.suse.cz/tests/1631#step/boot_ltp/71
- http://quasar.suse.cz/tests/1632#step/boot_ltp/74

LTP: Log kernel-rt package

---

tests/iscsi/iscsi_client.pm

- Related ticket: https://progress.opensuse.org/issues/117949
https://openqa.suse.de/tests/10273045
https://openqa.suse.de/tests/10273048
https://openqa.suse.de/tests/10273050
https://openqa.suse.de/tests/10275755
https://openqa.suse.de/tests/10275756
https://openqa.suse.de/tests/10275758
https://openqa.suse.de/tests/overview?build=jpupava_16180&distri=sle
Test didn't fail in multiple runs:

iscsi_client: Wait for yast window to finish

---

tests/virtualization/universal/waitfor_guests.pm

- Related ticket: https://progress.opensuse.org/issues/113785
- Needles: N/A
[KVM](http://openqa.qam.suse.cz/tests/50045) and [XEN](http://openqa.qam.suse.cz/tests/50043#)
simulated fail runs
[KVM](http://openqa.qam.suse.cz/tests/50049) and [XEN](http://openqa.qam.suse.cz/tests/50051)

track failed guest installations

---

tests/x11/gnome_music.pm

https://progress.opensuse.org/issues/122725
https://bugzilla.suse.com/show_bug.cgi?id=1206793
- Related ticket: https://progress.opensuse.org/issues/122725
https://openqa.opensuse.org/tests/3017576 -Leap
https://openqa.opensuse.org/tests/3017732 -TW

Add softfail for 'gnome_music' test due to known issue

---

tests/x11/gnome_music.pm

Reverts os-autoinst/os-autoinst-distri-opensuse#16189

Revert "Add softfail for 'gnome_music' test due to known issue"

---

tests/console/zfs.pm

https://progress.opensuse.org/issues/122770
- Related ticket: https://progress.opensuse.org/issues/122770
- Verification run: [VRs](https://openqa.opensuse.org/tests/3026529#next_previous)

Skip zpool scrub in case the pool is currently resilvering

---

data/sles4sap/qe_sap_deployment/mr_test_gcp.yaml

TEAM-6928 - Implement mr test on GCE
NOTE:  using latest "apiver: 3" for the config file
- Related ticket: https://jira.suse.com/browse/TEAM-6928
- Needles: NA
Please find **Flavor = GCE-SAP-BYOS-Incidents-saptune** and **Flavor = GCE-SAP-PAYG-Incidents-saptune** for the VRs.
15-SP4: https://openqaworker15.qa.suse.cz/tests/overview?distri=sle&version=15-SP4&build=%3A27019%3Alibzypp&groupid=21 (all passed)
15-SP3: https://openqaworker15.qa.suse.cz/tests/overview?distri=sle&version=15-SP3&build=%3A27019%3Alibzypp&groupid=22 (all passed)
15-SP2: https://openqaworker15.qa.suse.cz/tests/overview?distri=sle&version=15-SP2&build=%3A27019%3Alibzypp&groupid=23 (all passed)
15-SP1: https://openqaworker15.qa.suse.cz/tests/overview?distri=sle&version=15-SP1&build=%3A27019%3Alibzypp …

Implement mr test on Public Cloud: GCE

---

lib/trento.pm
t/08_trento.t
tests/sles4sap/trento/cluster_deploy.pm
tests/sles4sap/trento/deploy_trento.pm
tests/sles4sap/trento/install_agents.pm
tests/sles4sap/trento/test_hana_restore_stopped.pm
tests/sles4sap/trento/test_hana_stop.pm
tests/sles4sap/trento/test_trento_deploy.pm
tests/sles4sap/trento/test_trento_web.pm

Remove duplicated scenarios upload
Only generate scenarios after the cluster to Trento peering Upload scenarios archives with a more recognizable filename
- Ticket [CFSA-1692](https://jira.suse.com/browse/CFSA-1692)
1. http://openqaworker15.qa.suse.cz/tests/118214
2. http://openqaworker15.qa.suse.cz/tests/118215
3. Latest code http://openqaworker15.qa.suse.cz/tests/121955 http://openqaworker15.qa.suse.cz/tests/121956

Improve quality of Photofinish scenarios collection

---

tests/console/firewalld.pm

[VR: #10171245: sle-15-SP5-Online-x86_64-Build58.1-extra_tests_textmode@64bit](https://openqa.suse.de/tests/10189353)
[VR: #10171246: sle-15-Server-DVD-Incidents-x86_64-Build:27104:dtb-aarch64-mau-extratests1@64bit](https://openqa.suse.de/tests/10189352)
[VR: #10171259: sle-15-SP3-Server-DVD-Incidents-x86_64-Build:27094:libslirp-mau-extratests1@64bit](https://openqa.suse.de/tests/10189351)
[VR: #2956667: opensuse-Tumbleweed-DVD-x86_64-Build20221214-extra_tests_textmode@64bit](https://openqa.opensuse.org/tests/2958364)
[VR: #2956668: opensuse-Tumbleweed-JeOS-for-kvm-and-xen-x86_64-Build20221214-jeos-extra@64bit_virtio-2G](https://openqa.opensuse.org/tests/2958363)
[VR: #2956671: alp-0.1-kvm-x86_64-Build20221214-networking@64bit](https://openqa.opensuse.org/tests/2958363)  Look here ✅

Verify iptables default backend

---

tests/hpc/pdsh_slave.pm

Organise the testcases of the module and produce a xml report.
- Related ticket: https://progress.opensuse.org/issues/119743

Create xml report of pdsh module

---

data/graphicsmagick/test.sh

- Related ticket: http://bugzilla.opensuse.org/show_bug.cgi?id=1206322
- Needles: N/A
- Verification run: https://openqa.opensuse.org/t3031140

graphicsMagick: accept higher tolerance on i586

---

lib/Installation/ModuleRegistration/ModuleRegistrationPage.pm
lib/Installation/ModuleRegistration/SeparateRegCodesController.pm
lib/Installation/ModuleRegistration/SeparateRegCodesPage.pm
schedule/yast/sle/flows/default_sle15sp3_aarch64.yaml
schedule/yast/sle/flows/default_sle15sp3_s390x_kvm.yaml
schedule/yast/sle/flows/default_sle15sp3_x86.yaml
tests/installation/module_registration/add_ltss_regcode.pm

Enable interactive installation for LTSS with libyui
- Verification run:  s390x: https://openqa.suse.de/tests/10307861#
x86:  http://openqa.suse.de/t10307871
aarch64: http://openqa.suse.de/t10307872

 Enable interactive installation for LTSS with libyui

---

schedule/yast/opensuse/yast2_gui/yast2_gui.yaml

See https://progress.opensuse.org/issues/123145

Disable screensaver in yast2 gui tests

---

lib/publiccloud/ec2.pm
lib/publiccloud/openstack.pm

https://progress.opensuse.org/issues/123373
https://progress.opensuse.org/issues/105262
- Verification run: (In progress)
AWS https://openqa.suse.de/tests/10346379
Openstack https://openqa.suse.de/tests/10346459 (pendent)

Fix ssh_key problem

---

tests/microos/selfinstall.pm

As the new kiwi version has been deployed, selfinstall images in sle-micro 5.4 do not show the `kexec` failure anymore.
After deployment of the image on the drive, test has to expect an automatic reboot.
In the second stage image is being configured by Ignition/Combustion.
- ticket: https://progress.opensuse.org/issues/123184
[sle-micro-5.4-Default-SelfInstall-x86_64-Build15.2_2.14-slem_installation_default@uefi-virtio-vga](http://kepler.suse.cz/tests/20027#)
[sle-micro-5.3-Default-SelfInstall-Updates](https://openqa.suse.de/tests/10347903#step/selfinstall/8)
[sle-micro-5.2-Default-SelfInstall-Updates](https://openqa.suse.de/tests/10347902#step/selfinstall/8)
[sle-micro-5.3-Default-SelfInstall-Updates](https://openqa.suse.de/tests/10347843#step/selfinstall/6) …

Handle expected reboot in selfinstall

---

tests/security/atsec/syscall_thrasher.pm

- Related ticket: https://progress.opensuse.org/issues/123223
- Verification run: https://openqa.suse.de/tests/10348012

syscall_thrasher.pm: output to file instead of video

---

lib/containers/utils.pm

Test docker|podman update command to check for setting resource limits in container engine tests.
- Related ticket: https://progress.opensuse.org/issues/92461
- SLE 15-SP5 w/ docker: http://1b124.qa.suse.de/tests/309
- TW w/ podman: http://1b124.qa.suse.de/tests/310 (soft-failing due to bug in `podman update`)

lib/containers/common: Add test for update command

---

lib/susedistribution.pm
schedule/yast/opensuse/d_installer.yaml
tests/installation/d_installer_test.pm

- Related ticket: [poo#123586](https://progress.opensuse.org/issues/123586)
- Verification run: https://openqa.opensuse.org/tests/3064048#step/d_installer_test/14
Note: Yam squad will work on top of this preliminary work, it is just to kick off this task and have some starting point in job group for ALP development.

Preliminary work to run D-Installer CLI

---

lib/containers/utils.pm

- Related ticket: https://progress.opensuse.org/issues/123580
- Verification run: https://openqa.suse.de/tests/10374492#

Containers: fix for update command on nerdctl

---

data/lynis/baseline-lynis-audit-system-nocolors-15-SP5-ppc64le-gnome
data/lynis/baseline-lynis-audit-system-nocolors-15-SP5-ppc64le-textmode

- Related ticket: https://progress.opensuse.org/issues/122248
- textmode: https://openqa.suse.de/tests/10378786
- gnome: https://openqa.suse.de/tests/10375514

Add lynis baseline for 15-sp5 ppc64le

---

tests/console/gpg.pm

- Related ticket: [poo#122077](https://progress.opensuse.org/issues/122077)
- Verification run: [pdostal-server.suse.cz/t3918](https://pdostal-server.suse.cz/tests/3918)

Public Cloud: GPG: Do not check package updates in BETA

---

tests/publiccloud/download_repos.pm

- Related tickets: [poo#123655](https://progress.opensuse.org/issues/123655)
- Verification run: [pdostal-server.suse.cz/t3941](https://pdostal-server.suse.cz/tests/3941)

We need to exclude embargoed incidents.

---

tests/console/gpg.pm

Use text mode passphrase entry dialog in gpg2
- Related ticket: https://progress.opensuse.org/issues/123679
- https://openqa.suse.de/tests/10379134#step/gpg/111  
- https://openqa.suse.de/tests/10380627             
- https://openqa.suse.de/tests/10380628             
- https://openqa.suse.de/tests/10380629             
(further test failures are addressed in a separate ticket)

gpg2: use text mode pinentry dialog

---

lib/containers/utils.pm

`podman update` does work but https://github.com/containers/podman/issues/17187 won't be fixed anytime soon, so we can't rely on `docker inspect` to check whether the update was done.  We have to check the relevant file in /sys/fs instead.
- Related ticket: https://github.com/containers/podman/issues/17187
- SLE 15-SP5 (docker): http://1b124.qa.suse.de/tests/321
- Tumbleweed (podman): http://1b124.qa.suse.de/tests/322 (failing in the **buildah** module due to boo#1207509).

Containers: Temporary fix for podman update test

---

data/journal_check/bug_refs.json

-failure: https://openqa.suse.de/tests/10389387#step/journal_check/9

Ignore waitpid wicked error in sle15sp1 LTSS tests

---

lib/consoletest.pm
lib/utils.pm
lib/x11test.pm

- Related ticket: https://progress.opensuse.org/issues/120723
- Verification run: https://openqa.suse.de/tests/overview?build=dzedro%2Fos-autoinst-distri-opensuse%2316271&distri=sle

Call show_tasks_in_blocked_state in post_fail_hook

---

lib/publiccloud/utils.pm
tests/publiccloud/download_repos.pm
tests/publiccloud/transfer_repos.pm

Parent: https://openqa.suse.de/tests/10434440
Child: https://openqa.suse.de/tests/10434442

Public Cloud: fix embargoed updates in transfer repos

---

tests/hpc/genders.pm

Make genders module to export results in xml
- Related ticket: https://progress.opensuse.org/issues/119734
https://aquarius.suse.cz/tests/14670#

Add xml_report for genders

---

tests/hpc/munge_master.pm

Make munge module to export results in xml
- Related ticket: https://progress.opensuse.org/issues/119740
- Verification run: https://aquarius.suse.cz/tests/14686

Add xml_report for munge

---

tests/sles4sap/grafana_dashboards.pm

Fixes poo#124113
VR at https://openqa.suse.de/tests/10457536

Fix grafana login and other navigation issues

---

tests/publiccloud/migration.pm

VR:https://openqa.suse.de/tests/10459533/logfile?filename=serial_terminal.txt
CASEDIR:https://github.com/yarunachalam/os-autoinst-distri-opensuse.git#debug
Change Request works as expected enable verbose and debug mode in config
file
https://openqa.suse.de/tests/10459533/logfile?filename=serial_terminal.txt
verbose_migration: true
debug: true
Job failure is unrelated to this change

Enable debug mode for sle migration service

---

lib/main_micro_alp.pm
lib/registration.pm
tests/installation/scc_registration.pm

VR: https://openqa.suse.de/tests/10477990
The test failure is due to https://bugzilla.suse.com/show_bug.cgi?id=1208148

SLE Micro: handle activation of SCC modules

---

tests/security/openscap/oscap_remediating_offline.pm

- Related ticket: https://progress.opensuse.org/issues/116368
- https://openqa.opensuse.org/tests/3115462
- https://openqa.opensuse.org/tests/3115464

oscap_remediating_offline.pm: fix openscap issue

---

tests/installation/welcome.pm

- Related ticket: https://progress.opensuse.org/issues/124347
- Needles: 
- Verification run: https://openqa.suse.de/tests/10483450

Fix product shortcuts for SLE 15 SP5

---

schedule/yast/btrfs/btrfs+warnings.yaml
schedule/yast/transactional_server/create_hdd_transactional_server.yaml

Added install_SLES test module for aarch64
- Verification run: https://openqa.suse.de/tests/10504173
- https://openqa.suse.de/tests/10504163

Added install_SLES test module for aarch64

---

schedule/yast/iscsi_ibft.yaml

- Related ticket: https://progress.opensuse.org/issues/124574
- Needles: -
- [Verification run](https://openqa.suse.de/tests/overview?distri=sle&version=15-SP5&build=rakoenig%2Fos-autoinst-distri-opensuse%23fix_iscsi_ibft)

Fix disk selection in iscsi_ibft

---

tests/installation/welcome.pm

- Related ticket: https://progress.opensuse.org/issues/115376
- Needles: already created on osd
https://openqa.suse.de/tests/10527113#step/welcome/11 x86_64
https://openqa.suse.de/tests/10527111#step/welcome/14 x86_64
https://openqa.suse.de/tests/10527226#step/welcome/11 ppc64le
https://openqa.suse.de/tests/10527176#step/welcome/11 x86_64

welcome: Use tab to highlight product instead of kb shortcut

---

schedule/yast/sle/guided_btrfs/guided_btrfs_aarch64.yaml

See https://progress.opensuse.org/issues/123394
correction to https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/16414

Replace hibernation_enabled by hibernation_disabled in guided_btrfs

---

lib/main_common.pm

VR: http://kepler.suse.cz/tests/20367#
Failure: https://openqa.suse.de/tests/10548065#

Fix could init test suite variable

---

tests/x11/nis_server.pm

Ensure to press next in nis_server
- Related ticket: https://progress.opensuse.org/issues/124583
- Verification run: https://openqa.suse.de/tests/10547482#

Ensure to press next in nis_server

---

lib/kdump_utils.pm

Timeouts: https://openqa.suse.de/tests/10548120#step/kdump_and_crash/280 
VR: https://openqa.suse.de/tests/10549003

Kdump: increase timeout for aarch64

---

data/journal_check/bug_refs.json

Ticket: https://progress.opensuse.org/issues/124895

Ignore "No Caching mode page found" msgs in log that appear on RPi

---

data/journal_check/bug_refs.json

https://openqa.suse.de/tests/10550246#step/journal_check/2

Fix bug_refs.json escaping

---

lib/publiccloud/openstack_client.pm
tests/publiccloud/ssh_interactive_start.pm

- Verification run: http://kepler.suse.cz/tests/20374#

Fix typos in PC and SoC variables

---

tests/console/btrfsmaintenance.pm

Improve the test structure of the btrfsmaintenance test run. Reorganize the test run and improve the error output of certain commands.
- Related ticket: https://progress.opensuse.org/issues/124898
- Verification run: [Tumbleweed](https://duck-norris.qe.suse.de/tests/12098) | [15-SP4](https://duck-norris.qe.suse.de/tests/12091) | [15-SP3](https://duck-norris.qe.suse.de/tests/12092) | [15-SP2](https://duck-norris.qe.suse.de/tests/12093) | [15-SP1](https://duck-norris.qe.suse.de/tests/12095) | [12-SP5](https://duck-norris.qe.suse.de/tests/12094) | [12-SP4](https://duck-norris.qe.suse.de/tests/12096) | [12-SP3](https://duck-norris.qe.suse.de/tests/12097)

Improve btrfsmaintenance

---

tests/cpu_bugs/mitigations.pm

Modify the mitigations.pm file,which solve the problem of spectre_v2 changed in skylake machine.
Verification run: http://10.67.129.4/tests/56095

Adapt kvm mitigations change of spectre_v2 (skylake)

---

tests/iscsi/iscsi_client.pm

Fix the iscsi path
**Ticket:**
- https://progress.opensuse.org/issues/124158
- https://openqa.suse.de/tests/10463587

Updated iscsi path to /var/lib/iscsi

---

lib/nfs_common.pm

- Related ticket: https://progress.opensuse.org/issues/125072
- Verification run: https://openqa.opensuse.org/tests/3147227

lib/nfs_common: Detect if the kernel does not have NFSv2 support

---

tests/network/snmp.pm

- Related ticket: https://progress.opensuse.org/issues/122926
https://openqa.opensuse.org/tests/3147435#step/snmp/70 TW
https://openqa.suse.de/tests/overview?distri=sle&build=snmp SLE

Drop DES, MD5 and add also other protocols

---

lib/publiccloud/utils.pm
lib/utils.pm

Reverts os-autoinst/os-autoinst-distri-opensuse#16482 because of https://github.com/os-autoinst/os-autoinst-distri-opensuse/actions/runs/4292861529/jobs/7479820161

Revert "Add define_secret_variable to utils"

---

tests/virt_autotest/sriov_network_card_pci_passthrough.pm

Remove previous workaround as the bug has been verified fixed in SLE15SP5 public beta.
- Related ticket: https://bugzilla.suse.com/show_bug.cgi?id=1204882
https://openqa.suse.de/tests/10555160

Remove workaround of wickd bug bsc#1204882

---

tests/installation/partitioning_specific_disk.pm

SUT installation failure due to sending cmd too quick to get respond from installer. So solve the problem.
- Verification run: http://10.67.129.7/tests/1822

 Solve the problem of SUT installation failure.

---

tests/console/ntp_client.pm

NTP servers are chosen randomly in a pool, so sometimes at the start of the service, they can't be all reached. As the NTP sync should occur nevertheless, we wait for it before enumerating all the NTP sources.
- Related ticket: https://progress.opensuse.org/issues/124496
- https://openqa.suse.de/tests/10565433              
- https://openqa.suse.de/tests/10576693              
- https://openqa.suse.de/tests/10576695              
- https://openqa.suse.de/tests/10599890

Wait until time synced before listing NTP sources

---

data/generalhw_scripts/flash_sd_rootless.sh
data/generalhw_scripts/raspberry_pi_hardware_testing_setup.md

This will allow larger images that would exceed worker RAM.

RPi: Stream all formats when flashing sdcard

---

data/generalhw_scripts/flash_sd_rootless.sh

Fix errors like https://openqa.suse.de/tests/10605127

Fix param count in flash_sd_rootless.sh

---

lib/main_micro_alp.pm
tests/fips/openssl/openssl_fips_alglist.pm
tests/fips/openssl/openssl_fips_cipher.pm
tests/fips/openssl/openssl_fips_dhparam.pm
tests/fips/openssl/openssl_fips_hash.pm

VR: https://openqa.suse.de/tests/10604490#

Adjust openSSL FIPS tests for SLE Micro

---

schedule/hpc/installation_node_dev.yaml
schedule/hpc/installation_server.yaml

That was missing from sle15sp1 and broke incidents tests.

Add missing module to handle root settings in 15sp1

---

tests/hpc/mpi_master.pm

Testing imb raises 'Floating point exception' in older versions. So all the invocations of mpirun should be handle and produce a record_soft_failure on OpenQA.

Handle mvapich2 known bug in sle15 with the new invocations

---

tests/console/btrfsmaintenance.pm

Update the checks for the system services according to the recent updates.
- Related ticket: https://progress.opensuse.org/issues/125153
- Verification runs: [TW](https://duck-norris.qe.suse.de/tests/12271) | [15-SP4](https://duck-norris.qe.suse.de/tests/12272) | [15-SP3](https://duck-norris.qe.suse.de/tests/12273) | [15-SP2](https://duck-norris.qe.suse.de/tests/12274) | [15-SP1](https://duck-norris.qe.suse.de/tests/12275) | [12-SP5](https://duck-norris.qe.suse.de/tests/12276) | [12-SP4](https://duck-norris.qe.suse.de/tests/12278) | [12-SP3](https://duck-norris.qe.suse.de/tests/12277)

Update btrfsmaintenance services checks

---

lib/main_micro_alp.pm
tests/fips/gnutls/gnutls_base_check.pm
tests/fips/gnutls/gnutls_server.pm

- Related ticket: https://progress.opensuse.org/issues/125297
VRs:
[SLEM 5.3](http://openqa.suse.de/t10611473)
[SLEM 5.4](http://openqa.suse.de/t10611474)

Adapt GnuTLS tests for transactional servers

---

tests/qam-minimal/install_update.pm

- Related ticket: https://gitlab.suse.de/qa-maintenance/metadata/-/commit/6b1455ee2aa77a91a90db800d56100d3e86e146c
https://openqa.suse.de/tests/10626205
https://openqa.suse.de/tests/10626207
https://openqa.suse.de/tests/10626217
https://openqa.suse.de/tests/10626208

Install yast2-logs on minimal 15-SP4+ installation

---

lib/trento.pm
t/08_trento.t

- Related ticket: [CFSA-1726](https://jira.suse.com/browse/CFSA-1726)
- Verification run: related gh action execution

Add unit testing for the new trento_api_key

---

lib/main_common.pm
schedule/security/apparmor.yaml
schedule/security/apparmor_profile.yaml
schedule/security/cc_audit_tests.yaml
schedule/security/cc_audit_tests_part2.yaml
schedule/security/create_swtpm_hdd.yaml
schedule/security/lynis.yaml
schedule/security/openscap.yaml
schedule/security/security_check_kernel_config.yaml
schedule/security/security_grub_auth.yaml
schedule/security/security_pam.yaml
schedule/security/security_swtpm.yaml
schedule/security/security_tpm2.yaml
schedule/security/yast2_apparmor.yaml
test_known_issues.json
tests/security/cc/enable_root_ssh.pm

- Related ticket: https://progress.opensuse.org/issues/124298
- Other PRs involved: https://gitlab.suse.de/qe-security/osd-sle15-security/-/merge_requests/56 and https://github.com/os-autoinst/opensuse-jobgroups/pull/282
- SLES:
- 15.5: https://openqa.suse.de/tests/overview?distri=sle&version=15-SP5&build=73.2&groupid=431
- 15.4-maint: https://openqa.suse.de/tests/overview?distri=sle&version=15-SP4&build=20230305-1&groupid=431
- openSUSE:
- tumbleweed: [apparmor](https://openqa.opensuse.org/tests/3159782), [apparmor_profile](https://openqa.opensuse.org/tests/3159814), [create_swtpm_hdd](https://openqa.opensuse.org/tests/3159783) and [openscap](https://openqa.opensuse.org/tests/3159784)
- leap: [apparmor](https://openqa.opensuse.org/tests/3159788) and …

Port some security tests from main_common to yaml scheduling.

---

test_known_issues.json

Those files were checked in by mistake with a previous commit

Remove useless files

---

tests/qam-minimal/s390tools.pm

- Related ticket: https://bugzilla.suse.com/show_bug.cgi?id=1208983
https://openqa.suse.de/tests/10630301#step/s390tools/11 -> https://openqa.suse.de/tests/10634243
https://openqa.suse.de/tests/10630300#step/s390tools/11 -> https://openqa.suse.de/tests/10634732

Workaround s390-tools bug on 15-SP4

---

lib/main_micro_alp.pm
tests/fips/mozilla_nss/nss_smoke.pm
variables.md

https://progress.opensuse.org/issues/125513
VR: https://openqa.suse.de/tests/10641679#step/nss_smoke/1

FIPS: new NSS smoke test

---

data/generalhw_scripts/power_off_kasa.sh
data/generalhw_scripts/power_on_kasa.sh

Related to kasa update https://build.opensuse.org/request/show/1070379

generalhw scripts: update kasa syntax

---

data/journal_check/bug_refs.json
lib/main_micro_alp.pm
tests/fips/openssl/openssl_fips_alglist.pm
tests/fips/openssl/openssl_fips_cipher.pm
tests/fips/openssl/openssl_fips_dhparam.pm
tests/fips/openssl/openssl_fips_hash.pm

https://progress.opensuse.org/issues/125558
VR: https://openqa.opensuse.org/tests/3162983
I created https://bugzilla.opensuse.org/show_bug.cgi?id=1209053 to label the failing job

FIPS: fix openssl tests for MicroOS

---

lib/trento.pm
t/08_trento.t

Remove podman run redirection to file as log is already collected internally by the cypress image
Add the test file name to the log filename
Add unit testing for log name and for multiple test files
- Related ticket: CFSA-1732
- Verification run: http://openqaworker15.qa.suse.cz/tests/133675  now each test has its log file http://openqaworker15.qa.suse.cz/tests/133675/logfile?filename=test_hana_restore_stopped-cypress_first_visit_test_eula.cy_log.txt

More specifig log filename for Cypress Trento tests

---

tests/transactional/trup_smoke.pm

- Related ticket: https://bugzilla.suse.com/show_bug.cgi?id=1191863
[5.1](https://openqa.suse.de/tests/10670932)
[5.2](https://openqa.suse.de/tests/10670931)
[5.3](https://openqa.suse.de/tests/10670930)
[5.4](https://openqa.suse.de/tests/10670933)

Remove condition for transactional bootloader test

---

data/sles4sap/qe_sap_deployment/qesap_aws.yaml
data/sles4sap/qe_sap_deployment/qesap_aws_sapconf.yaml
tests/sles4sap/qesapdeployment/configure.pm

Add a config.yaml variable and a setting to control the VM type for the Hana machines
- Related ticket: TEAM-7486
SAPCONF : http://openqaworker15.qa.suse.cz/tests/135376 
SAPTUNE : http://openqaworker15.qa.suse.cz/tests/135375 The generated .tfvars is fine http://openqaworker15.qa.suse.cz/tests/135375/file/configure-terraform.tfvars

Instance type for qesap regression

---

README.md

Fix a small formatting error and add new links to the readme:
Also being enabled in openQA project: https://github.com/os-autoinst/openQA/pull/5030

Add links to Progress wiki and contact section

---

lib/db_utils.pm
schedule/jeos/sle/jeos-main.yaml
tests/jeos/image_info.pm

Moving away from InfluxDB required several code changes in the image data gathering module.
Currently we use postgresql together with postgrest API in order to retrieve or push data from the test runs.
- ticket: https://progress.opensuse.org/issues/124595
- VR: http://kepler.suse.cz/tests/20434#

Gather image data in postgresql

---

tests/jeos/prepare_firstboot.pm

Ticket: https://progress.opensuse.org/issues/125888

Fix network issues in rpi tests with new firstboot version

---

schedule/jeos/sle/jeos-extratest-sle12.yaml

see also https://gitlab.suse.de/qac/qac-openqa-yaml/-/merge_requests/1122

Move kdump test case into single test suite

---

tests/publiccloud/check_registercloudguest.pm

Fix listing of credentials dir

Fix listing of credentials dir

---

tests/jeos/rpi_wifi.pm

Find more about issues like https://openqa.suse.de/tests/10688728#step/rpi_wifi/19

Gather more debug info about rpi wifi issues

---

schedule/security/apparmor.yaml
schedule/security/apparmor_profile.yaml
schedule/security/cc_audit_tests.yaml
schedule/security/fips_crypt_core.yaml
schedule/security/fips_crypt_firefox.yaml
schedule/security/fips_crypt_kernel.yaml
schedule/security/fips_crypt_openjdk.yaml
schedule/security/fips_crypt_tool.yaml
schedule/security/fips_crypt_web.yaml
schedule/security/fips_crypt_x11.yaml
schedule/security/lynis.yaml
schedule/security/openscap.yaml
schedule/security/security_check_kernel_config.yaml
schedule/security/security_grub_auth.yaml
schedule/security/security_pam.yaml
schedule/security/security_swtpm.yaml
schedule/security/security_tpm2.yaml
schedule/security/yast2_apparmor.yaml
schedule/security/yast2_users.yaml

- Verification runs: https://openqa.suse.de/tests/overview?distri=sle&version=15-SP4&build=20230313-1&groupid=431

Use installation/bootloader_start instead of own conditional schedule

---

tests/security/verify_fips_packages.pm

https://progress.opensuse.org/issues/125702

verify_fips_packages: softfail if packages doesn't exist

---

tests/sles4sap/saptune/mr_test_run.pm

Implement mr test on GCE: this is the maintenance part
TEAM-6928 - [AC15+A16]Implement mr test on GCE
[AC15]: GCE product QA (incl. AC2+AC6+AC7)
[AC16]: GCE maintenance QA (incl. AC2+AC4+AC5)
Using a new opened ticket to track the failures.
Marked the **failures** to **softfail** as they are know issues in order to **not** block bot auto approval.
Related MR: https://gitlab.suse.de/qa-css/openqa_ha_sap/-/merge_requests/415
- Related ticket: https://jira.suse.com/browse/TEAM-6928
- Needles: NA
NOTE: I only triggered **sle12** saptune test cases via this branch as there are failures need to be marked as softfail, all **sle15** saptune test cases using master branch as they don't have failure.
15SP4: https://openqa.suse.de/tests/overview?distri=sle&version=15-SP4&build=%3A …

Implement mr test on GCE: maintainence part

---

data/journal_check/bug_refs.json

VR: http://kepler.suse.cz/tests/20441#step/journal_check/8

Fix regex in drm_plane_enable_fb_damage_clips known bug

---

schedule/yast/maintenance/yast_mru_install_minimal_with_addons_restapi.yaml

- Related ticket: https://bugzilla.suse.com/show_bug.cgi?id=1204924
- Verification run: https://openqa.suse.de/tests/10698498

Add SYSTEM_ROLE=textmode to yast-mru-install-minimal-with-addons test

---

lib/publiccloud/basetest.pm

Fix condition deciding to skip cleanup or not

---

tests/sles4sap/wmp_setup.pm

Fixes PED-131
Failure:
https://openqa.suse.de/tests/10694295#step/wmp_setup/1
VR:
https://openqa.suse.de/tests/10702298#step/wmp_setup/1

Fix for deprecated sapwmp package on SLE15SP5+

---

tests/console/check_system_info.pm

- Related ticket: https://progress.opensuse.org/issues/125777
- Needles: -
- [Verification run](https://openqa.suse.de/tests/10702848) exact change can be spotted [here](https://openqa.suse.de/tests/10702848#step/check_system_info/16)

Fix HA mapping in check_system_info

---

lib/yast2_widget_utils.pm

Workaround refreshment issue in iscsi_server for SLE 15 SP5 only.
- Related ticket: https://progress.opensuse.org/issues/125954
- Needles: N/A
- Verification run:  http://openqa.nue.suse.com/tests/10698308#

Apply refreshment workaround for iscsi_server

---

lib/main_common.pm

- Related ticket: https://progress.opensuse.org/issues/124595#

Re-enable image data gathering

---

data/autoyast_sle12/create_hdd/create_hdd_sles_regression_aarch64.xml.ep

Reverts os-autoinst/os-autoinst-distri-opensuse#16596

Revert "Add 12sp5 autoyast with default pattern image"

---

tests/console/zfs.pm

On SLES 15-SP5, SLP is marked as unsupported. To load `zfs` we need to allow the loading of unsupported modules.
In addition we switch to serial_terminal for improved stability and performance.
- Verification run: [SLES15-SP5](https://duck-norris.qe.suse.de/tests/12368) | [Leap 15.5](https://duck-norris.qe.suse.de/tests/12370)

Add allow_unsupported_modules

---

tests/x11/libqt5_qtbase.pm

we have performance issue on aarch64 with less RAM and poor host cpu.
It fails quite often for starting qt5 application and matching needles.
So skip these steps and check the package installation and compile app on aarch64.     
see https://progress.opensuse.org/issues/125873

Re-write and exclude small part  because of performance issue on aarch64

---

lib/main_micro_alp.pm

VR: https://openqa.opensuse.org/tests/3183154 (only for the schedule, the other errors will be fixed in other PRs)
to be merged with https://github.com/os-autoinst/opensuse-jobgroups/pull/292

ALP: create schedule for SELinux tests

---

data/valgrind/valgrind-test.sh
tests/console/valgrind.pm

VR: https://openqa.suse.de/tests/10716187#

Make valgrind test verbose

---

data/autoyast_sle15/pc_tools.xml
tests/publiccloud/prepare_tools.pm

- Related ticket: https://progress.opensuse.org/issues/125117
- Needles: *none*
- http://10.161.229.189/tests/overview?distri=sle&version=15-SP4&build=0051&groupid=1
- http://10.161.229.189/tests/37
- http://10.161.229.189/tests/38
- http://10.161.229.189/tests/39
- http://10.161.229.189/tests/40
- http://10.161.229.189/tests/41
- http://10.161.229.189/tests/43

Change the PC tools image repo to 15-SP4

---

lib/y2snapper_common.pm

https://progress.opensuse.org/issues/126194
[15SP4-QE_CORE](https://openqa.suse.de/tests/overview?build=rfan1&version=15-SP4&distri=sle)

Add timeout for apply_workaround_poo124652

---

lib/main_common.pm
schedule/security/create_hdd.yaml
schedule/security/create_hdd_cc.yaml
schedule/security/create_hdd_cc_uefi.yaml
schedule/security/create_hdd_ntlm.yaml
schedule/security/create_hdd_textmode_ext4_mok_enroll.yaml
schedule/security/create_hdd_textmode_intel_ipmi.yaml
schedule/security/create_hdd_uefi.yaml

- Related ticket: https://progress.opensuse.org/issues/124301
- https://openqa.suse.de/tests/overview?distri=sle&version=15-SP5&build=81.1&groupid=431
- https://openqa.suse.de/tests/10738853

Add YAML schedule for some installation tests

---

tests/console/zypper_ar.pm
tests/transactional/host_config.pm

Reuse logic from MicroOS to replace default repositories by the repos synced by OBS-sync.
VR:
https://openqa.opensuse.org/tests/3184867
https://openqa.opensuse.org/tests/3185085

ALP Fixes - round 2

---

tests/network/samba/samba_adcli.pm

Some of our workers cannot reach the AD controller via IPv6, so we need to disable IPv6 for this test run.
- Related ticket: https://progress.opensuse.org/issues/96512
- Verification run: https://openqa.suse.de/tests/10748272

Disable IPv6 for samba/AD test run

---

tests/console/zypper_ar.pm

Failure: https://openqa.opensuse.org/tests/3193098#step/zypper_ref/31
VR: https://openqa.opensuse.org/tests/3193202

Leap Micro: add repos defined as variables

---

data/journal_check/bug_refs.json

https://openqa.opensuse.org/tests/3194051#step/journal_check/21

ALP: Soft-fail expected healtcheck error message in journal

---

schedule/yast/sle/guided_ext4/guided_ext4_svirt_pv.yaml

Add stop_timeout_system_reboot_now for svirt-xen-pv
- Related ticket: [126620](https://progress.opensuse.org/issues/126620)
- Related MR: [487](https://gitlab.suse.de/qsf-y/qa-sle-functional-y/-/merge_requests/487)
- Needles: N/A
* https://openqa.suse.de/t10807177
* https://openqa.suse.de/t10807178

Add stop_timeout_system_reboot_now after perform_installation for svirt-xen-pv

---

tests/virtualization/universal/hotplugging_HDD.pm

poo#[122617](https://progress.opensuse.org/issues/122617)
Because softfail can ignore issue, change it into fail. Add disk check after detching disk.
- Related ticket: [122617](https://progress.opensuse.org/issues/122617)
- Needles:N/A
- Verification run:  [KVM](http://openqa.qam.suse.cz/tests/51454#step/hotplugging_HDD/141)  [XEN](http://openqa.qam.suse.cz/tests/51469#step/hotplugging_HDD/207)

Change softfail into fail, add disk check after detaching

---

tests/virt_autotest/kubevirt_tests_agent.pm
tests/virt_autotest/kubevirt_tests_server.pm

To resolve volume mounting failure while running datavolume_test, it needs to make a workaround for sle-micro.
https://openqa.suse.de/tests/10337166
http://10.67.129.96/tests/1981
"message": "MountVolume.SetUp failed for volume \"local-storage\" : mkdir /mnt/local-storage: read-only file system"
- Related ticket: https://progress.opensuse.org/issues/123415
- Verification run: https://openqa.suse.de/tests/10738406

Fix volume mount failure on kubevirt agent

---

tests/fips/mozilla_nss/firefox_nss.pm

- Related ticket: https://progress.opensuse.org/issues/125420
- 15-SP5: https://openqa.suse.de/tests/10815587
- 15-SP4: https://openqa.suse.de/tests/overview?distri=sle&version=15-SP4&build=20230328-1&groupid=431

firefox_nss: test both weak and strong pwd

---

lib/x11utils.pm

- Related ticket: https://bugzilla.suse.com/show_bug.cgi?id=1209781 https://progress.opensuse.org/issues/125930
- Verification run: https://openqa.suse.de/tests/overview?build=bsc1209781&distri=sle

Screensaver can't be always unlocked with key on 15-SP3

---

lib/bootloader_pvm.pm

we have issue 'cannot load initrd' since quite long time. The real root cause is on qanet which has problem with exported directory mounts sometimes.
So remove previous workaround for trying to reset at GRUB so that we can save a lot of time for assert_screen and speed up the whole installation progress.
see https://progress.opensuse.org/issues/120570

Remove workaround of 'cannot load initrd' from pvm installation

---

tests/console/orphaned_packages_check.pm

As discussed in https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/16704
Use serial_terminal is a better solution
- Related ticket: https://progress.opensuse.org/issues/126578
- Verification run: https://openqa.opensuse.org/tests/3197878

Use serial_terminal for 'orphaned_packages_check'

---

tests/containers/podman_pods.pm

- Related ticket: https://progress.opensuse.org/issues/124601
- 15-SP4 x86  http://openqa.suse.de/tests/10826614
- 15-SP4 aarch64 http://openqa.suse.de/tests/10826695
- SP3 http://openqa.suse.de/tests/10827390
- SP2 http://openqa.suse.de/tests/10826718 (Excluded)
- SP1 http://openqa.suse.de/tests/10826719 (Excluded)
- Microos https://openqa.opensuse.org/tests/3200047
- TW https://openqa.opensuse.org/tests/3200048

Add podman kube generate test

---

data/autoyast_sle15/create_hdd/create_hdd_textmode_aarch64.xml
data/autoyast_sle15/create_hdd/create_hdd_textmode_s390x.xml
data/autoyast_sle15/create_hdd/create_hdd_textmode_x86_64.xml
schedule/functional/autoyast_create_hdd/autoyast_create_hdd_textmode_libyui.yaml

Create auto-installation for textmode with sle-module-desktop-applications and sle-module-development-tools use libyui-rest-api
- Related ticket: https://progress.opensuse.org/issues/122353
- Verification run: https://openqa.suse.de/tests/10807396
https://openqa.suse.de/tests/10724850
https://openqa.suse.de/tests/10797330

Create auto-installation for textmode with sle-module-desktop-applications and sle-module-development-tools use libyui-rest-api

---

tests/sles4sap/qesapdeployment/test_cluster.pm
tests/sles4sap/trento/cluster_deploy.pm
tests/sles4sap/trento/test_hana_restore_stopped.pm
tests/sles4sap/trento/test_hana_stop.pm

- Related ticket: [TEAM-7627](https://jira.suse.com/browse/TEAM-7627)
qesap Azure [link](https://openqaworker15.qa.suse.cz/tests/141304)
qesap AWS [link](https://openqaworker15.qa.suse.cz/tests/141305)
qesap GCP [link](https://openqaworker15.qa.suse.cz/tests/141306)
Trento [link](https://openqaworker15.qa.suse.cz/tests/141310)

Use more generic Ansible label to refer to hana nodes

---

lib/containers/utils.pm
tests/containers/podman_pods.pm

- Related ticket: https://progress.opensuse.org/issues/124601
VR:
- 15-SP4 http://openqa.suse.de/tests/10832660
- 15-SP3 http://openqa.suse.de/tests/10832455
- 15-SP2 http://openqa.suse.de/tests/10832662
- 15-SP1 http://openqa.suse.de/tests/10832661

Ensure that version of podman is upper than 4.4.2 before testing kube

---

schedule/storage/blktests.yaml

- Related ticket: https://progress.opensuse.org/issues/121696

Remove obsolete disk type

---

lib/publiccloud/azure.pm

This idea has two stages:
1) Upload image md5 as blob metadata after blob is uploaded
2) Check that the md5 metadata field is available
The goal is to not upload one blob two times at the same time.
- Author: @mpagot
- Verification run: [non-existing image](https://pdostal-server.suse.cz/tests/4244), [existing image](https://pdostal-server.suse.cz/tests/4245)

Make sure we save image md5 as Azure blob metadata

---

data/autoyast_sle12/create_hdd/create_hdd_sles_regression_ppc64le.xml.ep
schedule/yast/autoyast/autoyast_create_hdd_sdk_gnome.yaml

We need create autoyast installation for SLES-12-SP5-ppc64le-GM-SDK-gnome.qcow2 with larger hard disk size.
- Related ticket: https://progress.opensuse.org/issues/124904
- Related MR: 
https://gitlab.suse.de/qa-maintenance/qam-openqa-yml/-/merge_requests/492
https://gitlab.suse.de/coolgw/wegao-test/-/merge_requests/277
- Needles: N/A
create qcow: https://openqa.suse.de/tests/10719825
verify failed job: http://openqa.nue.suse.com/tests/10807184#  ``` Failure nothing related with the PR```

Create auto-installation on ppc64le+SDK

---

tests/fips/openssl/openssl_fips_cipher.pm

- Related ticket: https://bugzilla.suse.com/show_bug.cgi?id=1209271
- Failure example: https://openqa.suse.de/tests/10855462#step/openssl_fips_cipher/36http://openqa.suse.de/tests/10861625
- Verification Run: https://openqa.suse.de/tests/10861666#

FIPS: move des3 out of the approved ciphers for SLEMicro5.4

---

schedule/qam/common/qam-minimal.yaml

- Related ticket: https://progress.opensuse.org/issues/127262
https://openqa.suse.de/tests/10861658#step/partitioning_filesystem/11 ext4
https://openqa.suse.de/tests/10861659#step/lvm/6 lvm

Fix ext4 & lvm qam-minimal schedule

---

data/autoyast_sle15/create_hdd/create_hdd_textmode_x86_64.xml

Update create hdd textmode x86_64
- Verification run: https://openqa.suse.de/tests/10853947#

Update create hdd textmode x86_64

---

lib/db_utils.pm

Especially when using `root-console` the `curl` calls take too long to process. Use `Mojo::UserAgent` methods instead.
- Verification run: http://kepler.suse.cz/tests/20521#step/image_info/1

Deprecate curl calls for POST

---

lib/publiccloud/azure.pm

This continues the effort of b5cea54643aada0d0ca134e3a6c044a9da840ea7 (#16770).
- Verification run: [15-SP5-Azure-BYOS](https://pdostal-server.suse.cz/t4263), [15-SP5-EC2-ARM](https://pdostal-server.suse.cz/t4264)

Check that Azure blob md5 field is present

---

lib/main_containers.pm
tests/containers/podman_network.pm

- Related ticket: https://progress.opensuse.org/issues/124619
- Verification run: https://openqa.suse.de/tests/10860610 for SLE-15-SP4 x86_64,  https://openqa.suse.de/tests/10860614 for SLE-15-SP4 aarch64 https://openqa.suse.de/tests/10860609 for SLE-15-SP3 x86_64, https://openqa.suse.de/tests/10854017 for SLE-15-SP2 x86_64, https://openqa.suse.de/tests/10860608 SLE-15-SP1 x86_64, https://openqa.suse.de/tests/10863594, https://openqa.suse.de/tests/10863585 for SLE-Micro-5.2, https://openqa.suse.de/tests/10863588 for SLE-Micro-5.3, https://openqa.suse.de/tests/10863591 for SLE-Micro-5.1

Add podman network test

---

lib/publiccloud/azure.pm

- Reverting pull request: #16785
- Verification run: [existing image](https://pdostal-server.suse.cz/tests/4267), [new image](https://pdostal-server.suse.cz/tests/4268)

Partially revert 3a49545 (#16785)

---

lib/publiccloud/azure.pm

- Previous pull requests: #16785, #16813
- Example failure: [openqa.suse.de/t10889077](https://openqa.suse.de/t10889077)
- Verification run: [pdostal-server.suse.cz/t4272](https://pdostal-server.suse.cz/t4272)

Do not fail if publiccloud::azure::upload_img is called for already uploaded image

---

lib/publiccloud/azure.pm

- Related pull request: #16820

Correct record_soft_fail to record_soft_failure

---

tests/security/selinux/fixfiles.pm

- Related ticket: https://progress.opensuse.org/issues/126812
- https://openqa.opensuse.org/tests/3222262#step/fixfiles/1
- https://openqa.opensuse.org/tests/3222264#step/fixfiles/1

fixfiles.pm: fix string split issue

---

lib/main_common.pm
tests/kernel/bpftrace.pm

Add a basic test for eBPF and user land tooling.

kernel/bpf: Add bpftrace smoke test

---

lib/YaST/workarounds.pm

- Related ticket: https://progress.opensuse.org/issues/127499
- Needles: 
- [SLE15 SP5](https://openqa.suse.de/tests/overview?build=rakoenig%2Fos-autoinst-distri-opensuse%23fix_workaround_poo124652&distri=sle&version=15-SP5)
- [SLE15 SP4 Maintenance](https://openqa.suse.de/tests/overview?version=15-SP4&distri=sle&build=rakoenig%2Fos-autoinst-distri-opensuse%23fix_workaround_poo124652)

Fix code for apply_workaround_poo124652

---

lib/publiccloud/azure.pm
tests/publiccloud/aws_cli.pm
tests/publiccloud/azure_cli.pm
tests/publiccloud/google_cli.pm

- Verification run: [existing](https://pdostal-server.suse.cz/t4283), [new](https://pdostal-server.suse.cz/t4277), [cli](https://pdostal-server.suse.cz/t4287)

Tag uploaded blobs on Azure and fix tags in cli tests

---

lib/YaST/workarounds.pm

Some refactor needed after doing the workaround. See comments here:
https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/16298
- Related ticket: https://progress.opensuse.org/issues/124787
- Needles: N/A
- Verification run: http://openqa.suse.de/tests/10911591#

Update workaround for bsc#1207157

---

lib/x11utils.pm

- Fail:
https://openqa.suse.de/tests/10885303#step/consoletest_finish/27
https://openqa.suse.de/tests/10885313#step/consoletest_finish/1
https://openqa.suse.de/tests/10885315#step/consoletest_finish/28
- Related ticket: 0b1ab57
https://openqa.suse.de/tests/10885873 x86_64
https://openqa.suse.de/tests/10885874 ppc64le
https://openqa.suse.de/tests/10885895 aarch64

Unlock screensaver with mouse also on 15-SP2

---

tests/security/selinux/audit2allow.pm

- Related ticket: https://progress.opensuse.org/issues/126815
- https://openqa.opensuse.org/tests/3224376#step/audit2allow/1
- https://openqa.opensuse.org/tests/3224375#step/audit2allow/1
- https://openqa.opensuse.org/tests/3224389#step/audit2allow/1

audit2allow.pm: fixes for ALP

---

schedule/storage/nfs.yaml
schedule/storage/supportserver.yaml
tests/kernel/before_nfs_test.pm
tests/kernel/nfs_barriers.pm
tests/kernel/nfs_client.pm
tests/kernel/nfs_server.pm

Pushing basic code; this is just code provisioning nfs server-client setup.
This shall be improved over time while I better understand what makes actual sense thus what and how could be abstracted.
- Related ticket: https://progress.opensuse.org/issues/126698

NFS: Add initial modules to provision NFS server-client setup

---

tests/cpu_bugs/xen_mitigations.pm

modify the file of xen_mitigations.pm to adapt for xen hypervisor
Include machine type:skylake haswell cascadelake
- Verification run: http://10.67.129.7/tests/1865
http://10.67.129.4/tests/57322
http://10.67.129.4/tests/57324

Adapt mitigations function test for xen hypervisor

---

tests/console/ovn.pm
variables.md

https://progress.opensuse.org/issues/127580
- Verification run: http://openqa.suse.de/tests/10931806
- **SLE15SP5 feature only**
Please help review the MR below as well
**https://gitlab.suse.de/qsf-u/qa-sle-functional-userspace/-/merge_requests/160**

Test ovn3 on sles15sp5

---

tests/installation/disable_grub_timeout.pm

- Related ticket: https://progress.opensuse.org/issues/127574
- Needles: NO
- Verification run: https://openqa.suse.de/tests/10918976#next_previous

Add timeout for needle match

---

lib/main_micro_alp.pm
schedule/security/container_selinux.yaml
tests/security/selinux/container_selinux.pm

- Related ticket: https://progress.opensuse.org/issues/119827
- Verification run: https://openqa.opensuse.org/tests/3231708

container_selinux: check that containers are using selinux

---

tests/containers/podman_pods.pm

- Related ticket:  https://progress.opensuse.org/issues/124601
VRs:
- SP4 http://openqa.suse.de/tests/10939764
- SP3 http://openqa.suse.de/tests/10947571
- SP2 http://openqa.suse.de/tests/10947574
- TW https://openqa.opensuse.org/tests/3233011

Podman: add test kube apply

---

lib/sles4sap_publiccloud.pm
schedule/sles4sap/publiccloud_hanasr.yml
tests/sles4sap/publiccloud/hana_sr_schedule_cleanup.pm
tests/sles4sap/publiccloud/hana_sr_schedule_primary_tests.pm
tests/sles4sap/publiccloud/hana_sr_schedule_replica_tests.pm
tests/sles4sap/publiccloud/hana_sr_takeover.pm
tests/sles4sap/publiccloud/hana_sr_test_secondary.pm

This commit creates the Azure PoC for SAP HANASR
This branch is a result of cherry-picking changes made by Lumir and Josef in
HANAsr_staging. The original branch was harder to merge because changes from
master were merged into it a long time ago, instead of having the branch rebase
onto master.
- Related ticket: https://jira.suse.com/browse/TEAM-7340
- Verification run:  http://openqaworker15.qa.suse.cz/tests/143171

Merge hanasr_staging and  add HANA master and secondary instance tests

---

.github/CODEOWNERS

* [GitHub CODEOWNERS](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners)

Add QE-C members to CODEOWNERS

---

lib/main_common.pm

https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/16811/commits/c0af69809387c4abd94c5cd7138df5e2e95ff3e2

Revert accidental main_common.pm change

---

lib/utils.pm

We need to reduce modules for regression migration cases at powerVM
- Related ticket: [**126125**](https://progress.opensuse.org/issues/126125)
- Related MR: [**282**](https://gitlab.suse.de/coolgw/wegao-test/-/merge_requests/282)
- Needles: N/A
* [VRs](https://openqa.suse.de/tests/overview?distri=sle&version=15-SP5&build=88.1&groupid=466&Flavor=Regression-on-Migration-from-SLE15-SPx)

we need to reduce modules for regression migration cases at powerVM

---

tests/hpc/conman.pm

Make conman test to export results in xml
- Related ticket: https://progress.opensuse.org/issues/119731
- Verification run: https://openqa.suse.de/tests/overview?build=b10n1k%2Fos-autoinst-distri-opensuse%2316280&distri=sle&version=15-SP5

Add xml_report to conman

---

tests/wsl/prepare_wsl_feature.pm

- Related ticket: https://progress.opensuse.org/issues/126683
- http://openqa.suse.de/tests/10953089
- http://openqa.suse.de/tests/10953113

Increase the timeout for enabling WSL feature

---

tests/microos/toolbox.pm

Adds two additional checks to the toolbox test:
1. Check that the pid namespace separation is not there
2. Perform a zypper ref and zypper up and check if that works with no issues
- Related ticket: https://progress.opensuse.org/issues/110791
- Verification run: [SLEM 5.4](https://duck-norris.qe.suse.de/tests/12668#step/toolbox/1) | [MicroOS](https://duck-norris.qe.suse.de/tests/12667#step/toolbox/1)
Motivation for introducing the `zypper` test: [bsc#1210587](https://bugzilla.suse.com/show_bug.cgi?id=1210587)

Add zypper and ps tests to toolbox

---

tests/containers/podman_pods.pm

Due to broken tests we need to temporarily disable the k3s part of kube apply.
- Related ticket: https://progress.opensuse.org/issues/128069
- Verification run: [MicroOS-Image-ContainerHost](https://duck-norris.qe.suse.de/tests/12669#step/podman_pods/145) | [SLEM 5.3](https://duck-norris.qe.suse.de/tests/12671#step/podman_pods/193)

Disable k3s-related part of kube apply

---

tests/containers/podman_pods.pm

Run the k3s-affiliated test runs only on SLEM 5.3.
- Related ticket: https://progress.opensuse.org/issues/128069
- Verification run: [SLEM 5.3](https://duck-norris.qe.suse.de/tests/12680#step/podman_pods/201) | [SLEM 5.2](https://duck-norris.qe.suse.de/tests/12679#step/podman_pods/141) | [SLEM 5.1](https://duck-norris.qe.suse.de/tests/12678#step/podman_pods/141)

Do k3s test runs only on SLEM 5.3+

---

lib/main_micro_alp.pm

[10G](https://openqa.opensuse.org/tests/3237770)
[non 10G](https://openqa.opensuse.org/tests/3237771)

MicroOS: create separate function for 10GB HDDs

---

tests/installation/disable_grub_timeout.pm
tests/installation/upgrade_select.pm

We need the workaround for some specific test scenarios, so recover it with special condition.
- Related ticket: https://progress.opensuse.org/issues/126602
- Related MR: https://gitlab.suse.de/coolgw/wegao-test/-/merge_requests/289
- Needles: N/A
http://openqa.suse.de/tests/10957592#
http://openqa.suse.de/tests/10957593#

Recover workaround for bsc#1129504

---

.github/CODEOWNERS

Register my user to lib/publiccloud
Add monitoring for the SAP lib/qesapdeployment.pm library

Add watcher for PC and SAP library

---

lib/Installation/PerformingInstallation/PerformingInstallationController.pm
lib/Installation/ProductSelection/ProductSelectionController.pm
lib/YuiRestClient/Wait.pm
tests/installation/performing_installation/perform_installation.pm
tests/installation/product_selection/install_SLES.pm

Put timeout scale logic into Wait.pm
- Related ticket: https://progress.opensuse.org/issues/125561
- Needles: na
- Verification run: https://openqa.suse.de/t10917218

Put timeout scale logic into YuiRestClient.pm

---

schedule/staging/RAID1@64bit-staging.yaml
schedule/staging/cryptlvm_minimal_x@64bit-staging.yaml
schedule/staging/default_install@64bit-staging.yaml
schedule/staging/ext4@uefi-staging.yaml
schedule/staging/gnome@64bit-staging.yaml

- Related ticket: https://progress.opensuse.org/issues/124676
- Needles: 
- [Verification runs](https://openqa.suse.de/tests/overview?distri=sle&version=15-SP5&build=rakoenig%2Fos-autoinst-distri-opensuse%23staging_libyui)

Ensure staging tests are using libyui-rest-api

---

lib/virt_autotest/utils.pm

poo#https://progress.opensuse.org/issues/127805
VM state is not stable, enhance it.
- Related ticket: https://progress.opensuse.org/issues/127805
- Needles: n/A
- Verification run: [XEN guest migration](http://openqa.qam.suse.cz/tests/overview?build=:S:M:28650:295434:64bit-guest-mi-ipmi-group2:12-SP5:g_m_test:&distri=sle&version=12-SP5&groupid=160), [KVM guest migraion](http://openqa.qam.suse.cz/tests/overview?build=:S:M:28650:295434:64bit-guest-mi-ipmi:12-SP5:g_m_test:&distri=sle&version=12-SP5&groupid=149)

Enhance XEN VM state check

---

tests/installation/welcome.pm

- Related ticket: https://progress.opensuse.org/issues/128258
- 15-SP5: https://openqa.suse.de/tests/10985408
- 15-SP4-QR: https://openqa.suse.de/tests/10985410

welcome.pm: fix selection on 15-SP4-QR ppc64le

---

lib/opensslca.pm

Test fails during CA import because the key is missing keyUsage attribute
- Related ticket: https://progress.opensuse.org/issues/128213
```
https://openqa.opensuse.org/tests/3246643              passed
https://openqa.opensuse.org/tests/3246644              passed
https://openqa.opensuse.org/tests/3247734              passed
https://openqa.opensuse.org/tests/3247735              passed
```

389ds : Add required keyUsage to CA key 

---

data/sles4sap/qe_sap_deployment/sles4sap_azure_generic.yaml
lib/sles4sap_publiccloud.pm
tests/sles4sap/publiccloud/hana_sr_takeover.pm
tests/sles4sap/publiccloud/hana_sr_test_secondary.pm

This is a followup pr to https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/16784, to address @alvarocarvajald 's comments.
- Related ticket: https://jira.suse.com/browse/TEAM-7340
15sp4: http://openqaworker15.qa.suse.cz/tests/149473 (FAIL, bug found and filed)
15sp3: http://openqaworker15.qa.suse.cz/tests/149468 (PASS)
15sp5: http://openqaworker15.qa.suse.cz/tests/147325
*failure in 15sp5 VR is due to known crm issue in 15sp5

Add hanasr fixes from pr16784

---

data/yam/agama/auto/alp_tw.json
tests/yam/agama/auto.pm

Add alp auto script for tw
- Related ticket: https://progress.opensuse.org/issues/128183
- Needles: na
https://openqa.opensuse.org/tests/3247743  (sh)
https://openqa.opensuse.org/t3247732 (json, current blocked by suspect issue)

Using Agama to perform auto-installation of Tumbleweed

---

tests/containers/podman_pods.pm

- Related ticket: https://progress.opensuse.org/issues/128456
-VR: https://openqa.suse.de/tests/11013478

Skip k3s installation on ppc64le arch

---

data/security/create_hdd_gnome_x86_64_uefi.xml
data/security/create_hdd_textmode_x86_64_uefi.xml
schedule/security/create_hdd_autoyast/create_hdd_x86_64_uefi.yaml

- Related ticket: https://progress.opensuse.org/issues/128249
- Verification runs: https://openqa.suse.de/tests/overview?distri=sle&version=15-SP4&build=186.1&groupid=431

Add autoyast profiles for 15-SP4

---

tests/boot/grub2_test.pm

- Related ticket: https://progress.opensuse.org/issues/123100
https://dzedro.suse.cz/tests/1092
https://dzedro.suse.cz/tests/1094
https://dzedro.suse.cz/tests/1095
https://dzedro.suse.cz/tests/1096

grub2_test: ZFS is not present on SLE 15+

---

data/security/separate_boot_textmode_x86_64_uefi.xml

- Related ticket: https://progress.opensuse.org/issues/128516
- Verification runs: https://openqa.suse.de/tests/11015244

Add autoyast profiles for 15-SP4 qu (part 2)

---

lib/containers/k8s.pm
tests/containers/run_container_in_k3s.pm

- Related ticket: https://progress.opensuse.org/issues/128354
- Verification run: http://openqa.suse.de/tests/11024155

Containers: Increase the debbug information for k3s 

---

lib/containers/containerd_crictl.pm
lib/containers/containerd_nerdctl.pm

* x86_64: https://openqa.opensuse.org/tests/3263259
* aarch64: https://openqa.opensuse.org/tests/3263260

lib/containers: Use proper packages in tests

---

lib/x11test.pm

- Related ticket: https://progress.opensuse.org/issues/128336
- Verification run: https://openqa.suse.de/tests/overview?build=firefox&distri=sle
https://openqa.suse.de/tests/11024894#step/firefox_smoke/20 retry example

Add assert option in firefox_open_url

---

lib/x11test.pm
tests/x11/firefox/firefox_appearance.pm
tests/x11/firefox/firefox_developertool.pm
tests/x11/firefox/firefox_extcontent.pm
tests/x11/firefox/firefox_extensions.pm
tests/x11/firefox/firefox_fullscreen.pm
tests/x11/firefox/firefox_headers.pm
tests/x11/firefox/firefox_html5.pm
tests/x11/firefox/firefox_localfiles.pm
tests/x11/firefox/firefox_pagesaving.pm
tests/x11/firefox/firefox_passwd.pm
tests/x11/firefox/firefox_pdf.pm
tests/x11/firefox/firefox_private.pm
tests/x11/firefox/firefox_ssl.pm
tests/x11/firefox/firefox_urlsprotocols.pm

- Related ticket: https://progress.opensuse.org/issues/128639 https://progress.opensuse.org/issues/128336
https://openqa.suse.de/tests/overview?build=firefox&distri=sle

Add second host if mirror.suse.cz is down

---

tests/containers/bci_prepare.pm

Adds dependency for PostgreSQL BCI container.
- Verification runs: [SLES15-SP4](https://duck-norris.qe.suse.de/tests/12868) | [SLES15-SP3](https://duck-norris.qe.suse.de/tests/12867) | [SLES15-SP2](https://duck-norris.qe.suse.de/tests/12872) | [SLES15-SP1](https://duck-norris.qe.suse.de/tests/12873) | [Ubuntu](https://duck-norris.qe.suse.de/tests/12869) | [res8](https://duck-norris.qe.suse.de/tests/12875) | [res7](https://duck-norris.qe.suse.de/tests/12881)

Add postgresql dependency

---

tests/smt/smt_server_install.pm

- Related ticket: https://openqa.suse.de/tests/11071551#step/smt_server_install/58

Increase timeout for smt-mirror

---

schedule/staging/RAID1@64bit-staging.yaml
schedule/staging/RAID1@s390x-staging.yaml
schedule/yast/opensuse/raid/raid1_gpt_leap.yaml
schedule/yast/raid/raid0_sle_gpt_prep_boot_pvm.yaml
schedule/yast/raid/raid10_sle_gpt_prep_boot_pvm.yaml
schedule/yast/raid/raid1_sle_gpt.yaml
schedule/yast/raid/raid1_sle_gpt_prep_boot_pvm.yaml
schedule/yast/raid/raid1_sle_gpt_uefi.yaml
schedule/yast/raid/raid5_sle_gpt_prep_boot_pvm.yaml
schedule/yast/raid/raid6_sle_gpt_prep_boot_pvm.yaml
test_data/yast/lvm_raid1/lvm+raid1_mds.yaml
test_data/yast/lvm_raid1/lvm+raid1_mds_hyperv.yaml
test_data/yast/lvm_raid1/lvm+raid1_mds_xen.yaml
test_data/yast/raid/raid0_prep_boot.yaml
test_data/yast/raid/raid10_prep_boot.yaml
test_data/yast/raid/raid1_gpt_uefi_test_data.yaml
test_data/yast/raid/raid1_prep_boot.yaml
test_data/yast/raid/raid5_prep_boot.yaml
test_data/yast/raid/raid6_prep_boot.yaml

- Related tickets: 
https://progress.opensuse.org/issues/128609
https://progress.opensuse.org/issues/128678
https://openqa.suse.de/tests/overview?version=15-SP5&distri=sle&build=sofiasyria%2Fos-autoinst-distri-opensuse%23raid1_fix

Remove chunk size for RAID1 test_data

---

schedule/staging/textmode_install@64bit-staging.yaml

Use conditional schedule to load access_beta_distribution test module

Use conditional schedule to load access_beta_distribution test module

---

lib/kdump_utils.pm

Yast cli may timeout while displaying configuration. It's a bug
bsc#1206274 which is not going to be fixed on SLE12 and has low
priority on SLE 15.
- Verification run:  http://openqa.qam.suse.cz/tests/53109

kdump: Don't use yast cli on XEN to check configuration

---

lib/publiccloud/openstack.pm

https://progress.opensuse.org/issues/129041
VR: https://openqa.suse.de/tests/11087684

Add tag for OpenStack images

---

tests/console/bind.pm

- Related ticket: https://progress.opensuse.org/issues/71329
- Verification run: https://dzedro.suse.cz/tests/1164

bind: Change retry message soft fail to info

---

schedule/yast/addon_extensions_http_ftp/addon_extensions_http_ftp@s390x.yaml
schedule/yast/btrfs/btrfs+warnings@s390x.yaml
schedule/yast/encryption/lvm_encrypt_separate_boot@s390x.yaml
schedule/yast/encryption/lvm_full_encrypt@s390x.yaml
schedule/yast/gnome_install_from_source.yaml
schedule/yast/lvm/lvm_thin_provisioning@s390x.yaml
schedule/yast/minimal+base/minimal+base@yast-s390x.yaml
schedule/yast/minimal+role_minimal/minimal+role_minimal@s390x.yaml
schedule/yast/modify_existing_partition/modify_existing_partition@s390x.yaml
schedule/yast/msdos/msdos@s390x.yaml
schedule/yast/msdos/msdos@svirt-hyperv.yaml
schedule/yast/releasenotes_origin+unregistered@pvm.yaml
schedule/yast/rmt_server_install/rmt_server_install.yaml
schedule/yast/select_modules_and_patterns/select_modules_and_patterns@s390x.yaml
schedule/yast/sle/flows/default_s390x_zvm.yaml
schedule/yast/textmode/textmode@s390x_svirt.yaml
schedule/yast/transactional_server/create_hdd_transactional_server@s390x.yaml

- some YAML files were missing and are now producing fails with GMC

Remove access_beta_distribution from schedules

---

lib/main_containers.pm
tests/containers/openshift_image.pm
tests/containers/openshift_setup.pm
variables.md

- Related ticket: https://progress.opensuse.org/issues/128579
* [OpenShift setup](https://openqa.suse.de/tests/11106809)
* [Placeholder module to test the container images](https://openqa.suse.de/tests/11111155)

Add OpenShift installation and deployment test

---

tests/console/ansible.pm

- Related ticket: [bsc#1210875](https://bugzilla.suse.com/show_bug.cgi?id=1210875), [bsc#1210876](https://bugzilla.suse.com/show_bug.cgi?id=1210876), [poo#128327](https://progress.opensuse.org/issues/128327)
- Follows: #16958
- Verification run: [SLE 15-SP4](https://pdostal-server.suse.cz/tests/4379), [SLE 15-SP5](https://pdostal-server.suse.cz/tests/4381), [JeOS 15-SP5](https://pdostal-server.suse.cz/tests/4383)

Re-enable ansible-test for SLE

---

lib/qam.pm
tests/qam-minimal/install_update.pm

- Related ticket: https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/17027 https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/17078
https://openqa.suse.de/tests/11137342 aarch64
https://openqa.suse.de/tests/11137396 aarch64
https://openqa.suse.de/tests/11137463 MicroOS
https://openqa.suse.de/tests/11137464 MicroOS

Use machine in condition to not affect aarch64 jobs

---

lib/x11test.pm

- Related ticket: https://progress.opensuse.org/issues/67408
- Verification run: https://openqa.suse.de/tests/11139421

Remove progress reference from soft failure

---

tests/iscsi/iscsi_client.pm

The bug already fixed, we need remove the workaround on SLES15SP5(bug fix hasn't been backported to 15SP3 yet).
- Needles: N/A
- Verification run: http://openqa.suse.de/tests/11131425#

Remove workaround of bsc#1206132

---

tests/qemu/qemu.pm

Example of timeout: https://openqa.suse.de/tests/11154370#step/qemu/3
Verification run: https://openqa.suse.de/tests/11154400

qemu: increase timeout for s390x

---

tests/console/python3_new_version_check.pm

https://progress.opensuse.org/issues/129478
[15SP4/15SP5/TW](http://bassey.arch.nue2.suse.org/tests/overview?&build=rfan0518)
Test failure on sle15sp5 is a known issue:https://bugzilla.suse.com/show_bug.cgi?id=1211386

Test all available python3 new versions if any

---

lib/saltbase.pm

- Related ticket: https://bugzilla.suse.com/show_bug.cgi?id=1209248 https://progress.opensuse.org/issues/129496
- Verification run: https://openqa.suse.de/tests/overview?build=salt_129496&distri=sle&version=15-SP5

salt_master: Workround harmless error message

---

data/sles4sap/qe_sap_deployment/qesap_azure.yaml
data/sles4sap/qe_sap_deployment/qesap_azure_sapconf.yaml

Increased reboot timeout to 900 in qesap regression for saptune and sapconf tests for azure
Related ticket: TEAM-6829
- http://openqaworker15.qa.suse.cz/tests/179777 saptune with timeout 900
- http://openqaworker15.qa.suse.cz/tests/179786 sapconf with timeout 900
- http://openqaworker15.qa.suse.cz/tests/179787 no any timeout argument (fall back to default)
This PR is linked to https://github.com/SUSE/qe-sap-deployment/pull/153

Increased reboot timeout for HANA in QESAP Regression

---

tests/qemu/qemu.pm

https://progress.opensuse.org/issues/129598
Example of failure: https://openqa.suse.de/tests/11173400#step/qemu/12
VR: http://openqa.suse.de/tests/11175825

qemu: increase time to deploy VM in s390x

---

tests/publiccloud/migration.pm

Install DMS using latest rpm
Download latest rpms,repo and install
Updated Record Info for rpm install
Fixed perltidy issues
Included create repo for rpm packages
refactor parameter

Install DMS using latest rpm

---

tests/hpc/mpi_master.pm

Add return error code. This is related to bsc#1209130

Fix mpavich2 failure on 15sp1 about IMB

---

tests/console/sssd_389ds_functional.pm

https://progress.opensuse.org/issues/129727
https://progress.opensuse.org/issues/129778
[SLE15SP5](http://openqa.suse.de/tests/overview?version=15-SP5&distri=sle&build=rfan0524)
[QEM](https://openqa.suse.de/tests/overview?&distri=sle&build=rfan0524&test=389ds_security_qem)

Enhance the logic to use right container image in sssd-389ds test

---

tools/test_isotovideo

Repository containers-tw is just a duplicate of containers (both are in fact TW).

Use standard containers repository

---

data/virtualization/autoyast/host_15.xml.ep
lib/virt_autotest/common.pm

Enable virtualization MU tests for 15-SP5 KVM/XEN/VMware/HyperV
- Related ticket: https://progress.opensuse.org/issues/128105
- Needles: https://gitlab.suse.de/openqa/os-autoinst-needles-sles/-/merge_requests/1640
15SP5 as host :
[15SP5-XEN](http://openqa.qam.suse.cz/tests/overview?build=:teodor_test:&distri=sle&version=15-SP5&groupid=168) [15SP5-KVM](http://openqa.qam.suse.cz/tests/overview?build=:teodor_test:&distri=sle&version=15-SP5&groupid=167)
15SP5 as guest on KVM hosts:
[12SP3](http://openqa.qam.suse.cz/tests/overview?build=:teodor_test:&distri=sle&version=12-SP3&groupid=143) [12SP4](http://openqa.qam.suse.cz/tests/overview?build=:teodor_test:&distri=sle&version=12-SP4&groupid=142) [12SP5](http://openqa.qam.suse.cz/tests/overview?build=:teodor_test:&distri=sle …

Enable 15-SP5 virtulization

---

lib/yam/agama/agama_base.pm
schedule/yam/agama_auto.yaml
test_data/yam/agama_auto_bedrock.yaml
test_data/yam/agama_auto_micro.yaml
test_data/yam/agama_auto_tumbleweed.yaml
tests/yam/agama/validate_product.pm

Login properly into the systems installed by Agama and verify OS
- Related ticket: https://progress.opensuse.org/issues/128492
- Needles: na
- Verification run: https://openqa.opensuse.org/t3307952

Login properly into the systems installed by Agama and verify OS

---

tests/security/apparmor_profile/apache2_changehat.pm

- Related ticket: https://progress.opensuse.org/issues/129901
https://openqa.suse.de/tests/11199617
https://openqa.suse.de/tests/11199749

Expand apache_changehat soft-failure to 15-SP5

---

tests/console/zypper_lifecycle.pm

quick PR
- Verification run: https://openqa.suse.de/tests/11200130

Drop python2 module support on 15sp1-ltss

---

tests/containers/podman_netavark.pm

In sle-micro 5.1 httpd container fails to start when SELinux is turned on. Introduce a check whether the container started for netavark test are running.
* [sle-micro-5.1-MicroOS-Image-Updates-x86_64-Build20230528-1-slem_containers@64bit](http://kepler.suse.cz/tests/20983#step/podman_netavark/1)
* [sle-micro-5.2-MicroOS-Image-Updates-x86_64-Build20230528-1-slem_containers_selinux@64bit](http://kepler.suse.cz/tests/20982#step/podman_netavark/1)
* [sle-micro-5.4-Default-Updates-x86_64-Build20230528-1-slem_containers@64bit](http://kepler.suse.cz/tests/20979#step/podman_netavark/1)
* [sle-micro-5.3-MicroOS-Image-Updates-x86_64-Build20230528-1-slem_containers_selinux@64bit](http://kepler.suse.cz/tests/20981#step/podman_netavark/1)
* [sle-micro-5.1-MicroOS-Image-Updates-x86_64-Build20230528-1-sl …

Softfail httpd container start

---

lib/publiccloud/azure.pm

- Verification run: [new image](https://pdostal-server.suse.cz/t4295), [existing image](https://pdostal-server.suse.cz/t4296)

Check if the Azure blob is uploaded correctly

---

lib/publiccloud/azure.pm

Public Cloud: Fix Perl syntax in azure image handling code

---

tests/installation/add_update_test_repo.pm

enlarge the timeout window when adding unreleasing update repos.
- Verification run: https://openqa.suse.de/tests/11222717

Enlarge the timeout window when adding unreleasing update repos.

---

tests/containers/podman_network_cni.pm

- Related ticket: https://progress.opensuse.org/issues/124619
- Verification run: https://openqa.suse.de/tests/11223386 SLE-15-SP5 x86_64, https://openqa.suse.de/tests/11223385 for SLE-15-SP4 x86_64, https://openqa.suse.de/tests/11223387 for SLE-15-SP4 aarch64, https://openqa.suse.de/tests/11223326 for SLE-15-SP1 x86_64, https://openqa.opensuse.org/tests/3326398#step/podman_network_cni/1 for container-host, https://openqa.opensuse.org/tests/3326399#step/podman_network_cni/1 for containers_host_podman

podman_network_cni: added connect, disconnect and reload commands to be validated.

---

tests/xfstests/run.pm

set test blacklist as a range, such as
XFSTESTS_RANGES=btrfs/001,xfs/005-050,generic/001-010
- Related ticket: https://progress.opensuse.org/issues/129676
- Needles: N/A
http://10.67.129.54/tests/821 (blacklist with range and duplicate)
http://10.67.129.54/tests/822 (blacklist with mixed category)
http://10.67.129.54/tests/823 (without blacklist)

xfstests: Add range support to XFSTESTS_BLACKLIST

---

lib/Distribution/Alp.pm
lib/Yam/ControlCenterPage.pm
lib/Yam/PageBase.pm
lib/Yam/ReleaseNotesPage.pm
products/alp/main.pm
schedule/alp/alp_yast.yaml
schedule/yam/control_center_container.yaml
tests/yam/yast_modules/control_center.pm

- Related ticket: https://progress.opensuse.org/issues/122218
- [Verification run based on agama auto installation](https://openqa.opensuse.org/tests/3318470)
- [Verification run in the Development ALP Bedrock group based on a qcow image](https://openqa.opensuse.org/tests/3323997)

Implement YaST Control Center Page

---

tests/console/openvswitch.pm
tests/console/openvswitch_ssl.pm
tests/console/ovn.pm
variables.md

https://progress.opensuse.org/issues/129565
[SLE ovn and openvswitch_ssl](https://openqa.suse.de/tests/overview?build=rfan0602&distri=sle)
[SLE openvswitch](https://openqa.suse.de/tests/overview?build=rfan0602_1&distri=sle)
[Leap ovn and openvswitch](https://openqa.opensuse.org/tests/overview?build=rfan0602_3&distri=opensuse&version=15.5)
[TW ovn,openvswitch and openvswitch_ssl](https://openqa.opensuse.org/tests/overview?build=rfan0602_2)

Test the latest ovn3 and openvswitch3 packages if possible

---

data/zvm.xml
lib/autoyast.pm
schedule/yast/autoyast/autoyast_zvm_sles_product_reg.yaml
tests/installation/bootloader_s390.pm

- Related ticket: [poo#127601](https://progress.opensuse.org/issues/127601)
- Verification run: Tumbleweed: https://openqa.opensuse.org/tests/latest?arch=s390x&distri=opensuse&flavor=DVD&machine=s390x-zVM-vswitch-l2&test=autoyast_zvm&version=Tumbleweed
SLE: https://openqa.suse.de/tests/overview?version=15-SP5&build=sofiasyria%2Fos-autoinst-distri-opensuse%23o3_s390&distri=sle
Should be merged after https://gitlab.suse.de/qsf-y/qa-sle-functional-y/-/merge_requests/504

Create ay test for s390x on o3

---

schedule/storage/nfs.yaml
tests/kernel/nfs_barriers.pm
tests/kernel/nfs_stress_ng.pm

Run stress-ng on our MM setup. So far only added the filename switch, will add more.
https://progress.opensuse.org/issues/127835
Ignore the top two commits, they will be merged in #17170 
@schlad

kernel/nfs: run stress-ng 

---

lib/qam.pm

- Related ticket: https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/17206#pullrequestreview-1457195497
- Verification run: https://openqa.suse.de/tests/overview?&distri=sle&build=arch_only

Fix extra repo arch_only condition

---

lib/qam.pm

Fix return if "exotic" arch is used

---

lib/Mitigation.pm

Enhance code for ssh connecting to guest, to make code can accurately diagnostic if the guest is running, crash or block
Dynamically adjust the timeout when ssh to guest which can reduce the running time when ssh failure.
- Related ticket:https://progress.opensuse.org/issues/73828?issue_count=126&issue_position=115&next_issue_id=73804&prev_issue_id=73840
- Verification run: http://10.67.129.7/tests/2101#downloads

Add debug info for ssh on xen domu

---

tests/console/zfs.pm

Add the zfs-internally provided `ztest` suite.
- Verification run: https://duck-norris.qe.suse.de/tests/12996

Introduce ztest

---

lib/opensusebasetest.pm

Reverts os-autoinst/os-autoinst-distri-opensuse#17116

Revert "Deal with no bounce back on powerKVM"

---

tests/virt_autotest/esxi_open_vm_tools.pm

To fix below job failure, adding a function 'check_vmtools_service()' to check vmtools service status. 
https://openqa.suse.de/tests/11178120#step/esxi_open_vm_tools/78
Cannot complete operation because VMware Tools is not running in this virtual machine.
- Related ticket: https://progress.opensuse.org/issues/128177
Svirt backend for SLE - https://openqa.suse.de/tests/11217079
Qemu backend for MU - https://openqa.suse.de/tests/11223393

Add vmtools service check before power operation

---

data/publiccloud/azure_lb.sh
data/publiccloud/azure_rbac.sh
data/publiccloud/rbac.config

RBAC test and load balancer test
- Verification run:(https://openqa.suse.de/tests/11244444#settings - RBAC)
https://openqa.suse.de/tests/11246854#settings - Load Balancer

Include More Azure CLI tests

---

data/publiccloud/azure_arm_grp.sh
data/publiccloud/azure_arm_grp_template.json
data/publiccloud/azure_arm_mg.sh
data/publiccloud/azure_arm_mg_template.json
data/publiccloud/azure_arm_sub.sh
data/publiccloud/azure_arm_sub_template.json

Add Group , Subscription and Management level ARM test scripts
- Verification run: (https://openqa.suse.de/tests/11247579#) - arm_grp test
https://openqa.suse.de/tests/11247607# - arm_sub test

Include ARM Azure cli test

---

tests/kiwi_images_test/kiwi_build_image.pm

- Related ticket: https://progress.opensuse.org/issues/125657
- Needles: NO
- Verification run: http://deepthi-openqa.qe.suse.de/tests/5308# | http://deepthi-openqa.qe.suse.de/tests/5325#

Fix upload asset of Kiwi image

---

tests/containers/podman_network_cni.pm

- Related ticket: https://progress.opensuse.org/issues/130507
- Verification run: https://openqa.suse.de/tests/11315729 (SLEM 5.1), https://openqa.suse.de/tests/11315734, https://openqa.suse.de/tests/11315787, https://openqa.suse.de/tests/11315767, https://openqa.suse.de/tests/11315769, https://openqa.opensuse.org/tests/3353042

podman_network_cni - change the image of container3 (fix on SLEM 5.1) and variable name $old_podman

---

lib/openjdktest.pm
schedule/security/fips_crypt_openjdk.yaml
tests/fips/openjdk/openjdk11_fips.pm
tests/fips/openjdk/openjdk11_ssh.pm
tests/fips/openjdk/openjdk17_fips.pm
tests/fips/openjdk/openjdk17_ssh.pm

- Related ticket: https://progress.opensuse.org/issues/125654
- Verification run: https://openqa.suse.de/tests/11326492

Add openjdk 17 fips test

---

tests/sles4sap/sys_param_check.pm

- Related ticket: https://progress.opensuse.org/issues/121684
- Verification run: https://dzedro.suse.cz/tests/1480

sys-param: Use public gh repo instead of local

---

tests/publiccloud/migration.pm

Add additional reboot and validate it is reachable after the boot https://jira.suse.com/browse/CSE-457
- Verification run:(https://openqa.suse.de/tests/11272482#step/migration/781)

Additional Reboot after migration

---

tests/transactional/host_config.pm

Fix ALP repo in host configuration

---

tests/transactional/host_config.pm

ALP: fix repo url

---

schedule/yast/msdos/msdos_aarch64.yaml
test_data/yast/msdos/msdos_aarch64.yaml

Add msdos test at YaST job group for aarch64
- Related ticket: [**130567**](https://progress.opensuse.org/issues/130567)
- Related MR: [**521**](https://gitlab.suse.de/qsf-y/qa-sle-functional-y/-/merge_requests/512)
- Needles: N/A
* https://openqa.suse.de/tests/11397818
* https://openqa.suse.de/tests/11397867

Add msdos test at YaST job group for aarch64

---

tests/x11/multi_users_dm.pm

- Related ticket: https://progress.opensuse.org/issues/120010
- Verification run: https://openqa.opensuse.org/tests/3370979

Make sure we are logged out before continuing

---

schedule/qam/15-SP4/qam-regression-other_fips.yaml
schedule/qam/15-SP5/qam-regression-other_fips.yaml

- Related ticket: https://progress.opensuse.org/issues/125654
https://openqa.suse.de/tests/11415831 15-SP5
https://openqa.suse.de/tests/11415840 15-SP4

Update yaml schedule for openjdk test

---

data/security/autoyast/create_hdd_gnome_aarch64.xml
data/security/autoyast/create_hdd_gnome_ppc64le.xml
data/security/autoyast/create_hdd_gnome_s390x.xml
data/security/autoyast/create_hdd_gnome_x86_64.xml
data/security/autoyast/create_hdd_gnome_x86_64_uefi.xml
data/security/autoyast/create_hdd_textmode_aarch64.xml
data/security/autoyast/create_hdd_textmode_ppc64le.xml
data/security/autoyast/create_hdd_textmode_s390x.xml
data/security/autoyast/create_hdd_textmode_x86_64.xml
data/security/autoyast/create_hdd_textmode_x86_64_uefi.xml
schedule/security/create_hdd_autoyast/autoyast_create_hdd_gnome_qesec.yaml
schedule/security/create_hdd_autoyast/autoyast_create_hdd_textmode_qesec.yaml

- Related ticket: https://progress.opensuse.org/issues/127862
- Verification runs: https://openqa.suse.de/tests/overview?distri=sle&version=15-SP5&build=102.1&groupid=431

Add autoyast files and schedules

---

tests/console/dpdk.pm

it seems that different device name is used for aarch64. 
see poo#131168

Fix wrong network device name for aarrch64 on Tumbleweed

---

lib/susedistribution.pm
lib/utils.pm
tests/installation/live_installation.pm

- Verification run: http://10.168.4.168/tests/1316

lib/utils: SDDM 0.20 is in Factory now

---

tests/jeos/firstrun.pm

This PR just improves the summary of what the module jeos/firstrun does do.

Improve summary of jeos/firstrun.pm

---

tests/console/journal_check.pm

This PR just improves the summary of what the module journal_check does do.

Improve summary of journal_check

---

tests/installation/bootloader_svirt.pm

This PR just improves the summary of what the module bootloader_svirt does do.

Improve bootloader_svirt summary

---

tests/console/zypper_lifecycle.pm

- Related ticket: https://jira.suse.com/servicedesk/customer/portal/1/MSC-658 https://suse.slack.com/archives/C02D16TCP99/p1688366603014179
https://openqa.suse.de/tests/11495843
https://openqa.suse.de/tests/11495844
https://openqa.suse.de/tests/11495845
https://openqa.suse.de/tests/11495846
https://openqa.suse.de/tests/11495847
https://openqa.suse.de/tests/11495848
https://openqa.suse.de/tests/11495849
https://openqa.suse.de/tests/11495850
https://openqa.suse.de/tests/11495851
https://openqa.suse.de/tests/11495852
https://openqa.suse.de/tests/11495853
https://openqa.suse.de/tests/11495854
https://dzedro.suse.cz/tests/1549#step/zypper_lifecycle/54 soft_failure

Zypper lifecycle containers workaround on 15-SP3

---

tests/security/oscap_stig/oscap_xccdf_eval.pm

- Related ticket: https://progress.opensuse.org/issues/127355
- Verification runs: https://openqa.suse.de/group_overview/431

stig: fix test on s390x and x86_64
