lib/publiccloud/instance.pm, tests/publiccloud/migration.pm
DMS migration (tests/publiccloud/migration.pm) is running under user migration
until it is not over we will recieve ssh permission denied (pubkey) error
but it is not good reason to die early because after it will be over DMS will return normal
user and error will be resolved.
=> Not allow wait_for_ssh to die early due to wrong pubkey error

tests/containers/bci_prepare.pm, tests/containers/bci_test.pm
- Related ticket: https://progress.opensuse.org/issues/126158
- Failure: https://openqa.suse.de/tests/10716006#step/_root_BCI-tests_metadata_podman/6
- VRs: 
https://openqa.suse.de/tests/10717366 (from failed test)
https://openqa.suse.de/tests/10717367 (from already green test)
=> BCI: Skip metadata tests if the public image is not available

tests/cpu_bugs/mitigations.pm
modify mitigations.pm for kvm passthrough of spectre_v2 cases on skylake machine.
http://10.67.129.4/tests/56928#
Verification run: http://10.67.129.4/tests/56989
=> Adapt kvm mitigations on spectre_v2 for passthrough

lib/publiccloud/instance.pm, lib/publiccloud/provider.pm, tests/jeos/prepare_openstack.pm, tests/publiccloud/az_accelerated_net.pm, tests/publiccloud/boottime.pm, tests/publiccloud/slem_basic.pm, tests/publiccloud/sles4sap.pm, variables.md
Primary Target of this PR in publiccloud is to trigger the boot time measurements collection  in the VM instance creation phase, instead of running in a separate module.
And as the collection as pushing data to InfluxDB are enabled by means of proper parmeters setting.
The _data push_ has been tested in a new created `perf_2` bucket and also in the existing one `perf` ( see param. `PUBLIC_CLOUD_PERF_DB`), successfully.
More details are in the [note-8](https://progress.opensuse.org/issues/118027#note-8) of the  poo.
- Related ticket: https://progress.opensuse.org/issues/118027
- Needles: N/A
- Verification run:   
[x86_64 AZURE 3715](http://10.168.4.117/tests/3715)  
[aarch64 GCE 3716](http://10.168.4.117/tests/3716)  
[x86_64 GCE 3718](http://10.168.4.117/tests/3718)  
This PR  to replace …
=> Boottime measures triggered at P.C. instance creation

data/autoyast_sle12/create_hdd/create_hdd_sles_regression_aarch64.xml.ep, schedule/yast/autoyast/autoyast_create_hdd_sdk_gnome.yaml
For autoyast migration at aarch64, we need replace the use of image, SLES-12-SP5-aarch64-GM-SDK-gnome.qcow2
- Related ticket: https://progress.opensuse.org/issues/125345
- Related MR: [482](https://gitlab.suse.de/qa-maintenance/qam-openqa-yml/-/merge_requests/482)
- Needles: N/A
* https://openqa.suse.de/tests/10737760
* https://openqa.suse.de/tests/10730545
=> Create auto-installation for SLE12SP5 for autoyast migration aarch64

tests/xfstests/generate_report.pm, tests/xfstests/run.pm
Recent s390x keep fail by curl log part, and this PR first accept some log missing to make whole tests complete. Then add a little bit timeout time, to adapt recent low performance in aarch64 in osd.
- Set no die on some log collection steps to workaround s390x fails in generate_report steps
- Check disk usage before download log
- Enlarge wait time to adopt lower performance in aarch64 worker
https://progress.opensuse.org/issues/122539
https://progress.opensuse.org/issues/126203
s390x: https://openqa.suse.de/tests/10730560
aarch64: http://openqa.suse.de/tests/10730566
=> xfstests: More stable in log collection steps

data/supportserver/samba/kinit.exp, data/supportserver/samba/krb5.conf, data/supportserver/samba/smb.conf, schedule/qam/common/mau-extratests2.yaml, tests/network/samba/samba_adcli.pm
This PR reintroduced the samba AD test run. It consists of two commits, one where we revert the test to the old state and one where we adapt it to the new Domain-Controller.
- Related ticket: https://progress.opensuse.org/issues/96512
- Verification runs: [15-SP4](https://duck-norris.qe.suse.de/tests/12387) | [15-SP3](https://duck-norris.qe.suse.de/tests/12381) | [15-SP2](https://duck-norris.qe.suse.de/tests/12382) | [15-SP1](https://duck-norris.qe.suse.de/tests/12383) | [12-SP5](https://duck-norris.qe.suse.de/tests/12384) | [12-SP4](https://duck-norris.qe.suse.de/tests/12385) | [12-SP3](https://duck-norris.qe.suse.de/tests/12386)
=> Reintroduce Samba adcli

data/publiccloud/terraform/azure.tf, data/publiccloud/terraform/ec2.tf, data/publiccloud/terraform/gce.tf
Use latest version of each CSP Terraform provider
For aws we're using version 3.37.0 and the latest version is 4.59.0.  The same happens with other providers.
The changelog for these show many bugfixes that could avoid some issues with `terraform destroy` not working, for example.
Related ticket: https://progress.opensuse.org/issues/126242
Verification runs (**publiccloud_consoletests**):
- AWS: http://1b124.qa.suse.de/tests/352
- Azure: http://1b124.qa.suse.de/tests/353
- GCP: http://1b124.qa.suse.de/tests/354
- Azure-BYOS-ARM: https://openqa.suse.de/tests/10738403
- Azure-BYOS-gen2: https://openqa.suse.de/tests/10738404
- GCE-ARM: https://openqa.suse.de/tests/10738408
- publiccloud_smoketests@gce_n2d_standard_2_confidential: https://openqa.suse.de/tests/10738413
- …
=> pc: Use latest version of each CSP Terraform provider

tests/containers/bci_prepare.pm, tests/containers/bci_test.pm
Reverts os-autoinst/os-autoinst-distri-opensuse#16651
=> Revert "BCI: Skip metadata tests if the public image is not available"

lib/main_micro_alp.pm, tests/fips/libica.pm
The icainfo output also indicates, whether the libica library has
built-in FIPS support, whether it is running in FIPS mode, and whether
it is in an error state. Algorithms that are not FIPS approved are
marked as blocked in both table columns and cannot be processed when
running in FIPS mode. All algorithms are marked as blocked when libica
is in an error state.
- ticket: [Create new test to validate libica package in SLE Micro-s390x on FIPS](https://progress.opensuse.org/issues/125780)
* [sle-micro-5.4-Default-s390x](https://openqa.suse.de/tests/10733033#step/libica/1)
* [sle-micro-5.3-MicroOS-Image-Updates-s390x](https://openqa.suse.de/tests/10733034)
=> Add smoke test for libica

data/supportserver/samba/kinit.exp, data/supportserver/samba/krb5.conf, data/supportserver/samba/smb.conf, schedule/qam/common/mau-extratests2.yaml, tests/network/samba/samba_adcli.pm
Adapt the existing samba Active Directory (AD) test run to work with the new AD Domain Controller host.
Re-Introduce https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/16517 after https://gitlab.suse.de/qa-maintenance/qam-openqa-yml/-/merge_requests/486
- Related ticket: https://progress.opensuse.org/issues/96512
- Verification run: https://duck-norris.qe.suse.de/tests/12390
=> Adapt samba test to new AD Controller

tests/kernel/ulp_openposix.pm
If the livepatch filename is libc_livepatch*.so, the old regex could match across multiple lines. Exclude parantheses which are added to the RPM filename list to prevent matching across lines.
- Related ticket: https://progress.opensuse.org/issues/112004
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/10745529
=> ulp_openposix: Fix libc version regex

data/autoyast_sle15/autoyast_home_encrypted.xml
Fix wrong mount point for swap in autoyast_home_encrypted.xml
**Ticket:**
- https://progress.opensuse.org/issues/126227
- https://openqa.suse.de/tests/10744985
=> Fix wrong mount point for swap

tests/console/java.pm
java-11-openjdk* does not work anymore, that also matches the obsoleted -accessibility subpackage. Mention the actually needed ones explicitly.
- Related ticket: https://bugzilla.suse.com/show_bug.cgi?id=1209404
Leap 15.4: https://openqa.opensuse.org/tests/3186085
SLE 12 SP5: http://10.168.4.168/tests/1302
SLE 15 SP1: http://10.168.4.168/tests/1298
SLE 15 SP4: http://10.168.4.168/tests/1301
=> console/java: Install openjdk packages more explicitly

data/squid/apache_vhost.conf, data/squid/hello.html, data/squid/squid_authdigest.conf, data/squid/squid_reverse.conf, data/squid/squid_sslbump.conf, schedule/security/fips_crypt_squid.yaml, tests/fips/squid/squid_init.pm, tests/fips/squid/squid_reverse_proxy.pm, tests/fips/squid/squid_web_proxy.pm
Schedule first tests for squid web proxy, both in forward and reverse mode.
- Related ticket: https://progress.opensuse.org/issues/125585
- Verification run: https://openqa.suse.de/tests/10739929
=> Setup FIPS squid tests

tests/transactional/install_updates.pm
Occasional timeouts when installing updates motivate to increase the update time from 20 to 30 minutes.
- Related ticket: https://progress.opensuse.org/issues/126428
- Verification run: https://duck-norris.qe.suse.de/tests/12397#step/await_install/15
=> Increase update timeout to 30min

data/autoyast_sle12/autoyast_sles4sap_saptune.xml.ep, data/autoyast_sle15/autoyast_sles4sap_saptune.xml.ep, lib/registration.pm, schedule/sles4sap/installation/autoyast_sles4sap_saptune.yaml
Use autoyast install for maintenance saptune cases 
TEAM-7357 - [AC18+AC2+AC4+AC5] Implement mr test (for maintenance) on x86 on-Premise
Related MR (maintenance + 15sp5): https://gitlab.suse.de/qa-css/openqa_ha_sap/-/merge_requests/419
NOTE: 
1. Incident repos (http-download.suse.de-) are added to system, FYI: http://openqaworker15.qa.suse.cz/tests/139071#step/repos/9
2. AUTOYAST: set via job template, so remove it from openQA code
3. SCC_ADDONS: used "sapapp" instead of "sles4sap" for more accurate
4. Set grub timeout=30s for avoiding openQA reboot stall issue
5. For the new autoyast profiles: it is based on "data/autoyast_sle12/create_hdd/create_hdd_sap_sles.xml.ep"
- Related ticket: https://jira.suse.com/browse/TEAM-7357
- Needles: Added already when debugging …
=> Use autoyast install for maintenance saptune cases

tests/qa_automation/patch_and_reboot.pm
https://progress.opensuse.org/issues/125186
[pvm](https://openqa.suse.de/tests/10743118) | [x86_64](https://openqa.suse.de/tests/10753106) | [s390x](https://openqa.suse.de/tests/10753105) | [ppc64le](https://openqa.suse.de/tests/10753107) | [aarch64](https://openqa.suse.de/tests/10753104)
=> Handle reboot on powerVM for patch_and_reboot test

data/sles4sap/script_output.yaml, lib/qesapdeployment.pm, t/09_qesapdeployment.t, tests/sles4sap/qesapdeployment/deploy.pm, tests/sles4sap/qesapdeployment/destroy.pm, tests/sles4sap/qesapdeployment/test_cluster.pm
Collect logs from each HANA cluster node in case of failure
Change all the Ansible API in qesap lib to support failok mode
Change the script_output Ansible API in qesap also needs a change in the playbook
Move the wait_ssh from qesap regression test module to an API function in qesap
Align input validation in qesap_execute to all the other API of the qesap lib
Add tons of UT about these changes
Related ticket: TEAM-7152
- AZURE : 
1. http://openqaworker15.qa.suse.cz/tests/138655 it is again a PASS and here again an example of log http://openqaworker15.qa.suse.cz/tests/138655/logfile?filename=test_cluster-crm_status.txt
2. [LATEST CODE] http://openqaworker15.qa.suse.cz/tests/139091
- GCP :  it is fail but it does not have logs. It is because the PR code is using fixed …
=> Qesap collect logs in case of failure

tests/publiccloud/slem_basic.pm
`strace` package is not available for slem 5.1. We need to find a common package that is available across all supported versions
- [SLEM 5.1 needs to be enabled for AWS (only !!!!) both archs ( x86_64 and aarch64 )](https://progress.opensuse.org/issues/121363)
- sle-micro-15-SP3-Micro-5-1-BYOS-EC2-HVM-x86_64-Build0002-slem_basic@64bit -> https://openqa.suse.de/t10747171
- sle-micro-15-SP3-Micro-5-2-BYOS-Azure-x86_64-Build0363-slem_basic@64bit -> https://openqa.suse.de/t10747172
- sle-micro-15-SP4-Micro-5-3-BYOS-GCE-x86_64-Build0278-slem_basic@64bit -> https://openqa.suse.de/t10747173
- sle-micro-15-SP4-Micro-5-4-BYOS-GCE-ARM-x86_64-Build0001-slem_basic@64bit -> https://openqa.suse.de/tests/10747596#details
=> Install common package for slem version in PC

data/virt_autotest/guest_unattended_installation_files/opensuse_tumbleweed_kvm_hvm_guest_x86_64.xml, data/virt_autotest/guest_unattended_installation_files/opensuse_tumbleweed_xen_hvm_guest_x86_64.xml, data/virt_autotest/guest_unattended_installation_files/opensuse_tumbleweed_xen_pv_guest_x86_64.xml, data/virt_autotest/guest_unattended_installation_files/slem_5_plus_kvm_hvm_guest_graphical_x86_64.xml, data/virt_autotest/guest_unattended_installation_files/sles_12_plus_kvm_hvm_guest_graphical_x86_64.xml, data/virt_autotest/guest_unattended_installation_files/sles_12_plus_kvm_hvm_guest_multi-user_x86_64.xml, data/virt_autotest/guest_unattended_installation_files/sles_12_plus_xen_hvm_guest_graphical_x86_64.xml, data/virt_autotest/guest_unattended_installation_files/sles_12_plus_xen_hvm_guest_multi-user_x86_64.xml, data/virt_autotest/guest_unattended_installation_files/sles_12_plus_xen_paravirt_guest_graphical_x86_64.xml, data/virt_autotest/guest_unattended_installation_files/sles_12_plus_xen_paravirt_guest_multi-user_x86_64.xml, data/virt_autotest/guest_unattended_installation_files/sles_15_plus_kvm_hvm_guest_graphical_x86_64.xml, data/virt_autotest/guest_unattended_installation_files/sles_15_plus_kvm_hvm_guest_multi-user_x86_64.xml, data/virt_autotest/guest_unattended_installation_files/sles_15_plus_xen_hvm_guest_graphical_x86_64.xml, data/virt_autotest/guest_unattended_installation_files/sles_15_plus_xen_hvm_guest_multi-user_x86_64.xml, data/virt_autotest/guest_unattended_installation_files/sles_15_plus_xen_paravirt_guest_graphical_x86_64.xml, data/virt_autotest/guest_unattended_installation_files/sles_15_plus_xen_paravirt_guest_multi-user_x86_64.xml, lib/guest_installation_and_configuration_base.pm, lib/virt_autotest/utils.pm, tests/virt_autotest/validate_system_health.pm
- To continue the test even if test run to logging failures, fg. https://openqa.suse.de/tests/10685378#step/validate_system_health/24
- Correct timezone settings of guests
- '/etc/ssh/ssh_config' file does not exist in TW
[guest-migration-sles15sp4-from-sles15sp4-to-developing-xen-src](https://openqa.suse.de/tests/10744978)
[gi-guest_developing-on-host_sles12sp5-xen](https://openqa.suse.de/tests/10752905)
=> Minor improvement on logging

lib/main_micro_alp.pm
These two modules were already skipped in the YAML schedule version of this.
- Related ticket: https://progress.opensuse.org/issues/126359
- Verification run: https://openqa.opensuse.org/tests/3186924
=> selinux on ALP is already enabled and in enforcing mode by default

schedule/jeos/sle/jeos-extratest.yaml
Ansible test case installs `ed` as part of its test playbook. A conflict in installation can occur as `x11/evolution/evolution_prepare_servers` installs `busybox-ed` package when deploying `postfix`
VR: http://kepler.suse.cz/tests/20474#step/ansible/1
=> Move ansible test to avoid conflict with busybox-ed

lib/main_ltp.pm, lib/main_micro_alp.pm
This way, the image boot will be done in the main scheduler and the rest in the kernel scheduler.
failure: https://openqa.opensuse.org/tests/3189603#step/install_ltp/128
VR: https://openqa.opensuse.org/tests/3189672
=> ALP: move kernel tests after image boot

data/sles4sap/qe_sap_deployment/qesap_azure.yaml, data/sles4sap/qe_sap_deployment/qesap_azure_uri.yaml, tests/sles4sap/qesapdeployment/configure.pm
- Add Azure config.yaml to support image from uri
- Fix setting management in configure test module
- Remove no needed Terraform setting
Related ticket: TEAM-7514
- qesap regression Azure With os image from uri (using custom JobGroup, special post variables) http://openqaworker15.qa.suse.cz/tests/139943 and parent http://openqaworker15.qa.suse.cz/tests/139942
On emore attempt fails due to a cloud problem http://openqaworker15.qa.suse.cz/tests/139944 http://openqaworker15.qa.suse.cz/tests/139945#step/deploy/7 and one more attempt http://openqaworker15.qa.suse.cz/tests/139950 Errors are not related to PR, they are some sort of problem that qe-sap-deployment seems to have with sles15-sp5
- qesap regression Azure with os from the catalogue …
=> Add test support for os_image from uri

lib/hpcbase.pm
A new 'feature' of Spack 0.19 to no longer set LD_LIBRARY_PATH by default. Apply solution given by Egbert Eich which restores previous behavior and raise a softfailure on those cases.
- Related ticket: https://bugzilla.suse.com/show_bug.cgi?id=1208751
- Verification run: https://openqa.suse.de/tests/overview?build=b10n1k%2Fos-autoinst-distri-opensuse%23spack_1208751&distri=sle&version=15-SP5
- 
https://openqa.suse.de/tests/10797016#details
=> Apply workaround for Spack test for recent version

schedule/storage/nvme.yaml, tests/kernel/nvme.pm
Before running more complex tests that also require more time to run, we should have some simple smoke tests for nvme, especially nvme-cli and vmetcli.
=> Add a simple NVMe loopback test

lib/publiccloud/provider.pm
Using it could allow to correlate resources running in the cloud with openQA jobs that generated them, at least better than using rand numbers.
Keep the hex encoding to short the name and not to hit the limitation imposed on the name length from each cloud API.
Related ticket: TEAM-7595
- Azure mr_test http://openqaworker15.qa.suse.cz/tests/139953 http://openqaworker15.qa.suse.cz/tests/139958. This one with latest code and id without hex encoding http://openqaworker15.qa.suse.cz/tests/140357
- GCP mr_test http://openqaworker15.qa.suse.cz/tests/139954 http://openqaworker15.qa.suse.cz/tests/139959. This one with latest code and id without hex encoding http://openqaworker15.qa.suse.cz/tests/140358
- EC2 mr_test http://openqaworker15.qa.suse.cz/tests/139955 …
=> Use the job id as resource group postfix

lib/bootloader_setup.pm, lib/main_micro_alp.pm
ALP changed grub menuentry from Adaptable Linux Platform to ALP Micro/Bedrock.
`load_journal_check_test` was  scheduled after `load_kernel_tests`,
- Failures:
grub config: https://openqa.opensuse.org/tests/3195013#step/install_ltp/157
schedule: https://openqa.opensuse.org/tests/3195516
ALP Micro: https://openqa.opensuse.org/tests/3195521
ALP Bedrock: https://openqa.opensuse.org/tests/3195522
=> Fixes for LTP installation on ALP

tests/nfs/generate_report.pm, tests/nfs/pynfs_result.pm
The default border color was always green (results == ok). Change the default color to suggest reviewer to see the content:
* 'Results' gets red border if there are failures, yellow if there are skip.
* 'Skipped' gets yellow if there are skipped.
* red in INFO and ERROR for errors
* yellow in INFO for soft failures ("Soft Failed" is already correctly formatted by record_soft_failure_result).
- fail: http://quasar.suse.cz/tests/2545, http://quasar.suse.cz/tests/2546
- soft failures: http://quasar.suse.cz/tests/2542
- pass: http://quasar.suse.cz/tests/2544
=> pynfs: Add result to record_info()

lib/publiccloud/instance.pm, tests/publiccloud/img_proof.pm, tests/publiccloud/run_ltp.pm
Publiccloud **create_instance**, `guestregister` check triggering updated cases:
1) in img_proof, do if ondemand,
2) in run_ltp, skip if openstack.
Moreover the remote DB `perf` _default target_ (used when `PUBLIC_CLOUD_PERF_COLLECT=1` 
and `_PUBLIC_CLOUD_PERF_PUSH_DATA=1`  only) has been changed to be the new `perf_2`, being additional tags used. This update was also tested in VRs of previous PR#16577. A new _token_ is used for r/w.
- Related ticket: https://progress.opensuse.org/issues/118027#note-13
=> P.C. create_instance guestregister triggrering update

lib/hpcbase.pm
This is intent to fix the timeout on aarch64 which getting slower and slower
- Verification run: https://openqa.suse.de/tests/10807422#
=> Increase timeout on spack spec command

tests/jeos/firstrun.pm
jeos-firstboot got updated.
- Failure: https://openqa.opensuse.org/tests/3195374#step/firstrun/1
- Verification run: https://openqa.opensuse.org/tests/3195651
=> jeos/firstrun: Leap 15.5 does not need explicit EULA acceptance

lib/qesapdeployment.pm
There was a problem with the old public cloud images (ver <51) and the installation and use of `python3.9` by sap tests. This pr replaces `python3.9` with `python3.10` to use with the updated public cloud images (>=51).
Sister gitlab pr: https://gitlab.suse.de/qa-css/openqa_ha_sap/-/merge_requests/422
- Related ticket: https://jira.suse.com/browse/TEAM-7506
azure: http://openqaworker15.qa.suse.cz/tests/140794
gcp: http://openqaworker15.qa.suse.cz/tests/140795 (fails on test cluster, not python ver related)
aws: http://openqaworker15.qa.suse.cz/tests/140796
=> Switch to python3.10 from python3.9

tests/console/orphaned_packages_check.pm
Previously it also tried to parse the table header, interpreting "Name" as package name. Just wait for the table to start, this also skips all warnings as a side effect.
Also don't ignore timeouts, that just leads to false negatives.
- Verification run: https://openqa.opensuse.org/tests/3196495
=> console/orphaned_packages_check: Fix zypper output parsing

tests/ha/hawk_gui.pm
The container needed for this was in Ricardo Branco's home OBS project and would eventually be garbage collected.
This uses the same container that has been submitted to the CI subproject in the devel namespace and is for this reason not going to be garbage collected.
- Related ticket: https://jira.suse.com/browse/TEAM-7428
- Verification run: https://openqa.suse.de/tests/10807780
=> Move the container to the devel project

lib/main_ltp.pm, lib/main_micro_alp.pm
Basically reverts https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/16700 and adds more configuration modules.
- Fail: https://openqa.opensuse.org/tests/3195539#
1. ALP Micro:
installation: https://openqa.opensuse.org/tests/3196124
run: https://openqa.opensuse.org/tests/3196128
2. ALP Bedrock:
installation: https://openqa.opensuse.org/tests/3195953
run: https://openqa.opensuse.org/tests/3195946
=> alp: Fix schedule of kernel tests

tests/sles4sap/publiccloud/qesap_terraform.pm
Terraform workspace name to include the job id in place of a rand int
Related ticket: TEAM-7595
-    Azure mr_test http://openqaworker15.qa.suse.cz/tests/140825  and  http://openqaworker15.qa.suse.cz/tests/140830
-    GCP mr_test http://openqaworker15.qa.suse.cz/tests/140826
-    EC2 mr_test http://openqaworker15.qa.suse.cz/tests/140827
=> Terraform workspace to use jod id

lib/hpcbase.pm
spack by its own takes some time to complete as it runs scripts which takes some time and the default timeout is not limited. This commit gives enough time to avoid unecessary timeouts during installation.
- Related ticket: https://progress.opensuse.org/issues/126806
- Verification run: NA
=> Increase timeout for spack installation

tests/sles4sap/trento/setup_jumphost.pm
Add `zypper rr` as creating the tool qcow2 for Trento test
- Related ticket: [TRNT-2018](https://jira.suse.com/browse/TRNT-2018)
- Verification run:  https://openqaworker15.qa.suse.cz/tests/overview?distri=sle&version=15-SP4&build=PREVIEW&groupid=4 and in particular https://openqaworker15.qa.suse.cz/tests/140828#step/setup_jumphost/59 Here a Trento test using the new qcow2 https://openqaworker15.qa.suse.cz/tests/141284
=> Remove "Public Cloud Devel" repo

tests/microos/image_checks.pm
When the drive is encrypted, the previous code [did not find](https://openqa.opensuse.org/tests/3195032#step/image_checks/6) the partition that holds `/var`.
- VR: http://kepler.suse.cz/tests/20487#step/image_checks/8
=> Find encrypted partition for ALP full disk encrypted image

tests/publiccloud/migration.pm
current DMS job fails latest version as "N/A". Fixed regex to extract version number
- Verification run: (https://openqa.suse.de/tests/10807091)
CASEDIR | https://github.com/yarunachalam/os-autoinst-distri-opensuse.git#regfix
-- | --
--
=> Fixed Regex to extract version number

tests/network/samba/samba_adcli.pm
Skip the test run on s390x is the host can not be reached (poo#126866).
- Related ticket: https://progress.opensuse.org/issues/126866
- Verification run: [s390x](https://openqa.suse.de/tests/10817119) | [x86_64](https://openqa.suse.de/tests/10817120)
=> Skip test run on s390x

tests/microos/image_checks.pm
Follow up for https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/16728 as previous PR wrongly used partition to check the size.
Adding `-d` switch to the `lsblk` call as without it the output is as follows.
```
vda3 253:3 0 4G 0 part
luks 254:0 0 4G 0 crypt /usr/local\x0a/srv\x0a/opt\x0a/home\x0a/boot/writable\x0a/boot/grub2/x86_64-efi\x0a/boot/grub2/i386-pc\x0a/.snapshots\x0a/var\x0a/root\x0a/
```
- Verification run: http://kepler.suse.cz/tests/20511#step/image_checks/14
=> Fix encrypted drive detection for ALP

lib/YaST/NetworkSettings/NetworkCardSetup/BondSlavesTab.pm
Ensure to select bond port yast2_lan_restart_bond
**Ticket:**
- https://progress.opensuse.org/issues/125999
- https://openqa.suse.de/t10825294 
- https://openqa.suse.de/t10825266
- https://openqa.suse.de/t10825278
- https://openqa.suse.de/t10825284
- https://openqa.suse.de/t10825286
- https://openqa.suse.de/t10825292
- https://openqa.suse.de/t10825296
- https://openqa.suse.de/t10825299
- https://openqa.suse.de/t10825301
- https://openqa.suse.de/t10825303
- https://openqa.suse.de/t10825340
=> Ensure to select bond port yast2_lan_restart_bond

tests/console/btrfs_autocompletion.pm
Attempt to install the new package together with bash-autocompletion
If the package does not yet exist (stable distros without the split), accept
exit code 104 (package not found) as valid return code.
- Related ticket: https://progress.opensuse.org/issues/126944
- Needles: N/A
- Verification run: https://openqa.opensuse.org/tests/3199379
=> btrfs_autocomplete: btrfsprogs-bash-autocompletion is split into sep package

lib/Utils/Logging.pm, lib/consoletest.pm, lib/opensusebasetest.pm, lib/x11test.pm
- Related ticket:  https://progress.opensuse.org/issues/120735
- Needles: No
I forcefully made the firefox test fail and results looks fine : https://openqa.opensuse.org/tests/3161410#
Other VRs:
https://openqa.suse.de/tests/10635862
https://openqa.opensuse.org/tests/3161407
https://openqa.opensuse.org/tests/3161403
https://openqa.opensuse.org/tests/3161402#
https://openqa.opensuse.org/tests/3161404#
=> Refactor the post_fail_hook functionality

tests/installation/iscsi_configuration.pm
Should fix a sporadic failure where the command is not executed in time, probably due to slow network.
See https://progress.opensuse.org/issues/125753
VRs (not passed yet, please check before merging.)
https://openqa.suse.de/t10717973
https://openqa.suse.de/t10717974
https://openqa.suse.de/t10717975
https://openqa.suse.de/t10717976
https://openqa.suse.de/t10717977
https://openqa.suse.de/t10717978
https://openqa.suse.de/t10717979
https://openqa.suse.de/t10717980
https://openqa.suse.de/t10717981
https://openqa.suse.de/t10717982
=> Replace script_ouput by script_ouput_retry in iscsi_configuration

data/autoyast_sle15/create_hdd/create_hdd_textmode_aarch64.xml
Pacckage 'sle-module-desktop-applications-release' is not installed by default in textmode. We can remove it and install it by tester's requirement.
- Verification run: http://openqa.suse.de/tests/10831905#
=> Remove non-default package from autoyast file

tests/console/btrfs_autocompletion.pm
btrfsprogs-bash-autocompletion has been split out, but does not yet exist
in all versions.
- Related ticket: Fixup to https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/16750
- Needles: N/A
- Verification run: https://openqa.opensuse.org/tests/3202800
=> btrfs_autocomplete: instruct zypper to ignore missing packages

tests/kernel/update_kernel.pm
SLE-11SP3 kernel files also belong to the kernel-default-base package. Change the expected kernel package name for all SLE versions before SLE-12GA.
- Needles: N/A
- SLE-11SP3: https://openqa.suse.de/tests/10832338
- SLE-11SP4: https://openqa.suse.de/tests/10832385
- SLE-12SP2: https://openqa.suse.de/tests/10832386
=> Fix expected kernel package for all SLE-11 service packs

tests/sles4sap/saptune/mr_test.pm
TEAM-7615 - Fix mr_test sapconf softfail on 12sp4: sapconf shows not started as sapconf pkg is not installed as a prerequisite
Install sapconf for all OS version
Remove the redundant `-n` parameter from `zypper_call ""`
- Related ticket: https://jira.suse.com/browse/TEAM-7615
- Needles: NA
https://openqa.suse.de/tests/10715382 (passed without soft failure)
=> Fix mr_test sapconf not started softfail on 12sp4

data/kea-dhcp/kea-dhcp4.conf, schedule/alp/kea_dhcp4.yaml, tests/microos/disk_boot.pm, tests/microos/workloads/kea-container/dhcp4_client.pm, tests/microos/workloads/kea-container/setup_dhcp4_server.pm
Add a multi-machine test to install and verify the ISC Kea DHCP4 server.
- Related ticket: https://progress.opensuse.org/issues/124209
- Needles: NO
- Verification run: [DHCP4_server](http://deepthi-openqa.qe.suse.de/tests/4773) | [DHCP4_client](http://deepthi-openqa.qe.suse.de/tests/4774#)
Latest VRs:
[setup_dhcp4_server](http://deepthi-openqa.qe.suse.de/tests/4855) | [DHCP4_client](http://deepthi-openqa.qe.suse.de/tests/4856#)
=> Test to install and verify kea dhcp4 server container

tests/containers/kubectl.pm
Calling to the balancer using localhost doesn't work.
So the good way is to extract the IP from the services
and use this ip instead of localhost
- Related ticket: https://progress.opensuse.org/issues/126926
- VR: http://openqa.suse.de/tests/10844960
=> Fix kubectl test timeouts

tests/fips/mozilla_nss/firefox_nss.pm
Ticket: https://progress.opensuse.org/issues/125705
Verification runs: 
* 15-sp2 http://openqa.suse.de/tests/overview?distri=sle&version=15-SP2&build=20230402-1&groupid=431
* 15-sp3 http://openqa.suse.de/tests/overview?distri=sle&version=15-SP3&build=20230402-1&groupid=431
* 15-sp4: https://openqa.suse.de/tests/overview?distri=sle&version=15-SP4&build=20230402-1&groupid=431
=> firefox_nss: fixes for SLES <= 15.3

lib/ipmi_backend_utils.pm
[virtualization] Replace grub menu-entry selection on sol console with grub2-set-default
To set the default boot to Xen during host installation where grub2 is modified, https://openqa.suse.de/tests/10679635#step/logs_from_installation_system/25
- Related ticket: https://progress.opensuse.org/issues/122947
- Verification runs with XEN_DEFAULT_BOOT_IS_SET: 
http://10.137.0.177/tests/80
https://openqa.suse.de/tests/10810302
- Verification runs without XEN_DEFAULT_BOOT_IS_SET:
http://openqa.suse.de/tests/10815502
http://10.137.0.177/tests/84
Screenshots: 
http://10.137.0.177/tests/80#step/logs_from_installation_system/16
http://10.137.0.177/tests/80#step/login_console/2
https://openqa.suse.de/tests/10810302#step/logs_from_installation_system/16 …
=> To set the default boot to Xen during host installation where grub2 is modified

lib/Utils/Backends.pm, tests/virt_autotest/login_console.pm
- check kvm modules to avoid the case happens again: bsc#1209596
- keep ssh serial console always alive to get test output after a long run
[host_upgrade from Wayne](https://openqa.suse.de/tests/10758433)
[guest-migration-developing-from-developing-to-developing-kvm](https://openqa.suse.de/tests/10761711)   //2.5 hours for guest migration. It should be convincing.
=> Set ssh serial console alive and check kvm modules

lib/main_micro_alp.pm, tests/microos/patterns.pm
There are only few available patterns that we are not regularly installing.
- ticket: [New test to check and install patterns in SLEM](https://progress.opensuse.org/issues/108356)
- VR: http://kepler.suse.cz/tests/20507#step/patterns/28
=> Install available patterns for sle-micro

lib/main_micro_alp.pm, schedule/functional/extra_tests_textmode.yaml, tests/console/year_2038_detection.pm
Smoke test to detect year 2038 issue
https://en.wikipedia.org/wiki/Year_2038_problem
https://progress.opensuse.org/issues/125639
https://progress.opensuse.org/issues/124736
[SLE15SP5](https://openqa.suse.de/tests/10808235#step/year_2038_detection/45)
[ALP](https://openqa.opensuse.org/tests/3197649#step/year_2038_detection/68)
**I didn't add the test to QEM, since current releases should be EOS in 2038 IMO**
=> Y2K38 Epochalypse

lib/apachetest.pm, lib/services/apache.pm, tests/console/apache.pm, tests/console/shibboleth.pm, variables.md
Introduce the `APACHE2_PKG` setting to select `apache` or `apache2-tls13`, as we need to test both on SLES12-SP5.
- Related ticket: https://progress.opensuse.org/issues/126146
- Verification run: [12-SP5 with apache2](https://duck-norris.qe.suse.de/tests/12480) | [12-SP5 with apache2-tls13](https://duck-norris.qe.suse.de/tests/12481) | [15-SP4](https://duck-norris.qe.suse.de/tests/12482) | [Tumbleweed](https://duck-norris.qe.suse.de/tests/12483)
=> Add apache2 version setting to SLES12-SP5

lib/main_micro_alp.pm
We may not able set right permission for serial console with 'ROOTONLY' system. so right now I will only schedule the test on ALP.
I will try to find a way to enable the tests on Micro-OS later.
- Verification run: https://openqa.opensuse.org/tests/3208912
=> Only test year_2038_detection on ALP

tests/publiccloud/upload_image.pm
Former JeOS OpenStack image is not pulled by IBS with checksum file. As of now, let's skip this check in this specific use case.
- Verification run: [sle-15-SP5-JeOS-for-OpenStack-Cloud-x86_64](https://openqa.suse.de/tests/10855138)
=> Skip checksum check for JeOS Cloud image

lib/y2_installbase.pm
Adding a timeout for validating expected target because of some failures in s390x
failures: https://openqa.suse.de/tests/10846976 and https://openqa.suse.de/tests/10846980
VR: https://openqa.suse.de/tests/10853909
=> Set timeout to validate_default_target

lib/hpcbase.pm
Somehow this start failing for sle15sp1. make sure that post_run is not destructing. Number is huge and maybe needs more investigation why tests are not finding default number sufficient. But sp1 is quite old so i guess this is ok for now.
- Verification run: https://openqa.suse.de/tests/10856747#details
=> Increase log collection timeout on post_run for hpc

lib/publiccloud/provider.pm
Use SIGKILL instead of SIGQUIT for failed terraform apply
- Related ticket: https://progress.opensuse.org/issues/102593
=> pc: Use SIGKILL instead of SIGQUIT for failed terraform apply

tests/fips/squid/squid_reverse_proxy.pm, tests/fips/squid/squid_web_proxy.pm
New version of `curl` has bold output by default, so to use in `validate_script_output` it needs an extra option to switch to plain text  
- Related ticket: https://progress.opensuse.org/issues/125585
- s390x https://openqa.suse.de/tests/10856031
- x86_64 https://openqa.suse.de/tests/10856033
- aarch64 https://openqa.suse.de/tests/10856034
=> Set plain text output in curl for matching on squid test

lib/hpc/formatter.pm, lib/hpc/utils.pm, tests/hpc/mpi_master.pm, tests/hpc/mpi_slave.pm
As for now the scipy test was configured incorrectly and was running with wrong source code. First we need to set HPC_LIB. Then the rest is on this PR.
- Related ticket: https://progress.opensuse.org/issues/126779
- Verification run: https://aquarius.suse.cz/tests/15687
=> Configure scipy module run properly with MPI modules

tests/console/year_2038_detection.pm
Ensure chronyd is started before setting the current date and time.
- Related ticket: https://progress.opensuse.org/issues/127253
- Verification run: https://openqa.suse.de/tests/10863599#
=> Ensure chronyd is started

lib/registration.pm, tests/migration/online_migration/pre_migration.pm, tests/migration/online_migration/yast2_migration.pm
As of leap 15.5, we'd use the yast2-migration-sle tools as default leap to SLE migration tool. So We'd use it for our leap to SLE migration in the Misc.
- Related ticket:  [**124964**](https://progress.opensuse.org/issues/124964)
- Related MR: [**278**](https://gitlab.suse.de/coolgw/wegao-test/-/merge_requests/278)
- Needles: added during tests
*  yast2-migration-leap_to_sle-20230329
*  yast2_migration-license-agreement-leap2sle-20230329
*  yast2-migration-upgrading-leap-20230330
*  yast2_migration-manual-intervention-leap-20230330
*  yast2_migration-desktop-runner-KDE-20230406
- textmode 
* https://openqa.suse.de/tests/10855139
- gnome: 
* https://openqa.suse.de/tests/10854819
- KDE: 
* https://openqa.suse.de/tests/10868805
- Regression:
* …
=> Add yast2-migration-sle for leap to SLE migration

tests/x11/remote_desktop/xrdp_client.pm
The maximum waiting time for assert_screen [qw(connection-failed windows-desktop-on-remmina)] is too small and leads to xrdp_client fails frequently.
Increase the maximum waiting time to fix the issue.
- Related ticket: https://progress.opensuse.org/issues/91575
- Needles: N/A
> [remote-desktop-xrdp-server1](https://openqa.suse.de/tests/10854082)
> [remote-desktop-xrdp-client1](https://openqa.suse.de/tests/10854081)
> [remote-desktop-xrdp-server2](https://openqa.suse.de/tests/10868829)
> [remote-desktop-xrdp-client2](https://openqa.suse.de/tests/10868830)
=> Increase maximum waiting time for xrdp_client test.

tests/microos/disk_boot.pm
By removing it, we will be using the default one (500), which is higher than current one.
We are hitting this 300s timeout sporadically.
- Related ticket: https://progress.opensuse.org/issues/127211
- VR: http://openqa.suse.de/tests/10864238
=> Use default timeout for MicroOS boot in aarch64

schedule/qam/common/qam-minimal-full-ppc64le-sle12.yaml, schedule/qam/common/qam-minimal-full-sle12.yaml
-without SYSTEM_ROLE=textmode & salt, nginx test
- Related ticket: https://progress.opensuse.org/issues/125423
https://openqa.suse.de/tests/10869563 12-SP2
https://openqa.suse.de/tests/10867592 12-SP5 ppc64le
https://openqa.suse.de/tests/10869523 12-SP5 x86_64
=> Split qam-minimal-full* for SLE12

lib/scheduler.pm
Improve the error output in case the test points to a non-existing YAML_SCHEDULE file.
- Verification run: [YAML_SCHEDULE not existing](https://duck-norris.qe.suse.de/tests/12494) | [Normal test run](https://duck-norris.qe.suse.de/tests/12495)
=> Check for YAML_SCHEDULE file

schedule/security/fips_crypt_libica.yaml, tests/fips/libica_upstream_testsuite.pm
We schedule the upstream build testsuite and a simple 'smoke' test to check libica functionality in the system. Libica is s390x only
- Related ticket: https://progress.opensuse.org/issues/120558 
- Verification run: https://openqa.suse.de/tests/10855924#
=> Run upstream libica's build testsuite in FIPS mode

lib/main_common.pm
Accept perl and python extensions in yaml schedule, still defaults to perl when extension is missing
This will allow running python tests from a yaml schedule.
- Related ticket: https://progress.opensuse.org/issues/126590
- https://openqa.suse.de/tests/10860639# (see https://github.com/os-autoinst/os-autoinst-distri-opensuse/compare/master...michaelgrifalconi:os-autoinst-distri-opensuse:pyaml-testing?expand=1 for the code used for validation run)
YAML Schedule used for validation run:
```
---
name: mgrifalconi-test
description: try out stuff
schedule:
- installation/bootloader_start
- boot/boot_to_desktop
- console/prepare_test_data
- console/consoletest_setup
- console/curl_ipv6
- console/curl_ipv6.py
- console/curl_ipv6.pm
...
```
Python test used …
=> Allow perl and python extensions in yaml schedule

data/xfstests/wrapper.sh, tests/xfstests/partition.pm, tests/xfstests/run.pm
Add support NFS test in xfstests, for now, Server and client test in a single VM.
Configure openqa parameter XFSTESTS=nfs to trigger tests under NFS filesystem. And 1 more parameter XFSTESTS_NFS_VERSION to set which NFS version to test, the default version is 4.1.
- Related ticket: https://progress.opensuse.org/issues/126464
1. xfstests for nfs
Run xfstests/nfs/001 in NFS4.1: http://10.67.133.133/tests/158
Run xfstests/generic/001-010 in NFS4.1: http://10.67.133.133/tests/157 (skip tests are known issue)
2. Verification run for inject code(in case some change in wrapper): http://10.67.133.133/tests/168 (inject a test code(free) in nfs/001:49)
3. Verification run for previous xfs/btrfs/ext4 tests
xfs/001-100: http://10.67.133.133/tests/164
=> xfstests: Support xfstests test on nfs

tests/smt/smt_server_install.pm
- Related ticket: https://progress.opensuse.org/issues/127328
- Verification run: https://dzedro.suse.cz/tests/970#step/smt_server_install/36
=> Replace SCC credentials with variable

tests/console/zypper_lifecycle.pm
Replace record_softfailure by record_info in zypper_lifecycle.
- Related ticket: https://progress.opensuse.org/issues/126605
- Needles: N/A
- Verification run: https://openqa.nue.suse.com/tests/10869645#step/zypper_lifecycle/49
=> Replace record_softfailure by record_info in zypper_lifecycle

data/autoyast_sle15/create_hdd/create_hdd_gnome_allpatterns_aarch64.xml, data/autoyast_sle15/create_hdd/create_hdd_gnome_sdk_allpatterns_aarch64.xml
Add two autoyast profiles of SLES15SP4 all patterns installation for aarch64.
- Related ticket: https://progress.opensuse.org/issues/125336
- Needles: n/a
- https://openqa.suse.de/tests/10753154 (create image)
- https://openqa.suse.de/tests/10753166 (create image)
- https://openqa.suse.de/tests/10753250 (verify image)
- https://openqa.suse.de/tests/10753252 (verify image)
- https://openqa.suse.de/tests/10753253 (verify image)
- https://openqa.suse.de/tests/10753307 (verify image)
- Related MR: https://gitlab.suse.de/qa-maintenance/qam-openqa-yml/-/merge_requests/489
=> Add autoyast profiles of 15SP4 allpatterns installation

lib/parallel_guest_migration_base.pm, lib/susedistribution.pm, lib/utils.pm, lib/virt_autotest/domain_management_utils.pm, lib/virt_autotest/utils.pm, schedule/qam/common/virt/virt_guest_migration.yaml, tests/virt_autotest/parallel_guest_migration_barrier.pm, tests/virt_autotest/parallel_guest_migration_destination.pm, tests/virt_autotest/parallel_guest_migration_source.pm, tests/virt_autotest/virt_utils.pm
* **Add** one more console root-ssh-virt for virtualization testing using ipmi backend. Manual postcopy guest migration needs two commands consecutively, the latter one needs to run during execution of the former, but unfortunately the former does not return until it finishes, so the latter do not have chance to run in the same terminal on some SLES versions. A second console is needed.
* **Extend** script_retry to have $option which can be used for passing additional arguments for "timeout".
* **New** file ```lib/virt_autotest/domain_management_utils.pm``` to hold domain management subroutines, including ```construct_uri```, ```create_guest```, ```remove_guest```, ```shutdown_guest```, ```show_guest``` and ```check_guest_state```.
* **Add** ssh options ```-o UserKnownHostsFile=/dev/null …
```
=> Automation Development for Guest Migration Test

lib/hpc/utils.pm
- Related ticket: https://progress.opensuse.org/issues/126779
- Verification run: https://openqa.suse.de/tests/10888875#details
=> Give additional timeout to build mpi4py on aarch64

tests/cpu_bugs/xen_domu_mitigation_test.pm
Modify the xen_domu_mitigation_test.pm file to adapt the function test of mitigations on xen hypervisor(hvm and pv)
machine include:skylake,icelake,haswell,cascadelake
About the cross_cases_on_spec-ctrl_yes is a bug. Refer to:https://bugzilla.suse.com/show_bug.cgi?id=1205618
http://10.67.129.4/tests/57335#step/cross_cases_on_spec-ctrl_yes/1
http://10.67.129.4/tests/57320#step/cross_cases_on_spec-ctrl_yes/1
http://10.67.129.4/tests/57345#step/cross_cases_on_spec-ctrl_yes/1
http://10.67.129.4/tests/57346#step/cross_cases_on_spec-ctrl_yes/1
http://10.67.129.4/tests/57326#step/cross_cases_on_spec-ctrl_yes/1
http://10.67.129.4/tests/57325#step/cross_cases_on_spec-ctrl_yes/1
http://10.67.129.7/tests/1864#step/cross_cases_on_spec-ctrl_yes/1 …
=> Mitigations funtion test  adaption for hvm and pv

lib/virt_autotest/esxi_utils.pm, tests/installation/add_serial_console.pm, tests/virt_autotest/esxi_open_vm_tools.pm
Guest power reboot command failed, because the machine doesn't boot into the OS. To fix the issue, this PR will enable the grub timeout for checking the VM power state.
http://10.67.129.96/tests/2085#step/esxi_open_vm_tools/76
1. Fix getting vm_id failure
2. Provide a option 'KEEP_GRUB_TIMEOUT' to enable grub timeout
3. Use open-vm-tools command to disable VM time sync
https://progress.opensuse.org/issues/126860
https://progress.opensuse.org/issues/127334
svirt backend:  http://10.67.129.96/tests/2130
qemu backend:  https://openqa.suse.de/tests/10825316
=> Fix guest power reboot failure for open-vm-tools tests

tests/migration/openldap_to_389ds.pm
Added retry a few times to get the memberof parameter
- Related ticket: https://progress.opensuse.org/issues/125717
- Verification run:  Have reruned 7 times, all of them can pass:
http://openqa.suse.de/t10869789
http://openqa.suse.de/t10869790
http://openqa.suse.de/t10869791
http://openqa.suse.de/t10869792
http://openqa.suse.de/t10869793
http://openqa.suse.de/t10869794
http://openqa.suse.de/t10869795
=> Added retry a few times to get the memberof parameter

lib/virt_autotest/common.pm
poo# https://progress.opensuse.org/issues/127307
http://mirror.suse.cz/install/SLP/SLE-15-Installer-LATEST/x86_64/DVD1/ is invalid,
http://mirror.suse.cz/install/SLP/SLE-15-Installer-GM/x86_64/DVD1/ is avaiable.
- Related ticket: https://progress.opensuse.org/issues/127307
- Needles: N/A
- Verification run: http://openqa.qam.suse.cz/tests/52336
=> Update invalid link during installation

lib/hpcbase.pm, tests/hpc/spack_master.pm, tests/hpc/spack_slave.pm
boost is a special case which requires LD_LIBRARY_PATH which has been removed
and spack is not setting during its installation. A workaround causes problems
with the system packages and make its fix makes the test complicated. Instead,
some other basic source code can avoid this, as it should be able to be
compiled and run without additional hacks. Although this does not decrease the
execution time. Meaning that spack still takes some time to install its
dependencies, including the openssl which was causing the issues in the
previous implementation.
- Verification run: https://openqa.suse.de/tests/overview?version=15-SP5&distri=sle&build=b10n1k%2Fos-autoinst-distri-opensuse%23spack_openssl
=> Refactor spack to align with source code which is selected by get_mpi_src

tests/installation/online_repos.pm
If the test does not explicitly specify repos to use for installation, enable online updates during live installation as well.
- Verification run: https://openqa.opensuse.org/tests/3221435
=> tests/installation/online_repos.pm: Enable on live cds if applicable

lib/Distribution/Opensuse/Tumbleweed.pm, lib/Installation/Popups/AcceptPopup.pm, lib/Installation/Popups/AcceptPopupController.pm, tests/installation/confirm_installation.pm
For SP4 there is an extra java license popup that breaks installation tests. This PR is adding a way to handle it in confirm_installation.pm
- Related ticket: https://progress.opensuse.org/issues/124140
- Verification run: http://falafel.suse.cz/tests/overview?build=20230411-1&distri=sle&version=15-SP4
OSD: https://openqa.suse.de/tests/10902903#next_previous
=> Handle java license popup during installation

data/sles4sap/qe_sap_deployment/mr_test_azure_uri.yaml, lib/publiccloud/provider.pm, tests/sles4sap/publiccloud/qesap_terraform.pm, variables.md
Add `mr_test_azure_uri.yaml` file to support customer images on Azure. 
This file is copied from `mr_test_azure.yaml` but replaced "`os_image`" with "`os_image_uri`".
Revised some tidy errors.
Revised the default value of **PUBLIC_CLOUD_RESOURCE_GROUP** to a short one '**qesaposd**' as a work around of:
`https://openqa.suse.de/tests/10880299#step/qesap_terraform/260 (Error: name ("stdiagqesapopenqa10880299") can only consist of lowercase letters and numbers, and must be between 3 and 24 characters long) `
VR of **PUBLIC_CLOUD_RESOURCE_GROUP=qesaposd**: https://openqa.suse.de/tests/10897218# ([qesap_terraform](https://openqa.suse.de/tests/10897218/modules/qesap_terraform/steps/1/src) passed on **OSD**)
TEAM-7633 - Enable saptune/mr_test Tests in osd for Azure …
=> Enable saptune/mr_test Tests in OSD for Azure

schedule/migration/s390x_regression_test_offline.yaml, schedule/migration/s390x_regression_test_online.yaml
Related ticket: https://progress.opensuse.org/issues/126344
Verification run: https://openqa.suse.de/tests/10844663
https://openqa.suse.de/tests/10844668
https://openqa.suse.de/tests/10844673
https://openqa.suse.de/tests/10844674
https://openqa.suse.de/tests/10844675
https://openqa.suse.de/tests/10844676
https://openqa.suse.de/tests/10844677
Some Vrs fail but not in force_scheduled_tasks
=> Change force_scheduled_tasks order for s390 migration tests

lib/hpc/utils.pm
the build of mpi4py needs more time to run.
- Verification run: https://openqa.suse.de/tests/10911595#
=> Give more time for wheel compilation on aarch4

tests/installation/confirm_installation.pm
After merging https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/16830
the SP4 tests with legacy and minimal pattern fail : https://openqa.suse.de/tests/10911585#step/confirm_installation/1
This extra condition, fixes the new issue that has appeared
SP4,minimal,legacy : http://falafel.suse.cz/tests/1078
SP4,legacy :  http://falafel.suse.cz/tests/1081
SP4 : http://falafel.suse.cz/tests/1082
=> Add PATTERNS condition for accepting java popup

lib/main_common.pm, tests/installation/online_repos.pm
Revert the previous commits, implement it how it was meant to.
"addon repos" == "online repos" apparently, which is why I previously thought this would be the wrong approach.
- Related ticket: https://progress.opensuse.org/issues/127565
15.4 Incidents: https://openqa.opensuse.org/tests/3223992
15.4 Images (Upgrade from 15.2): https://openqa.opensuse.org/tests/3223991
15.4 Images (installation): https://openqa.opensuse.org/tests/3223999
CC @rfan1
=> lib/utils: Enable online repos on installations from live media if applicable

tests/autoyast/installation.pm
Workaround bsc#1209083 via reducing matched needle
Workaround wrong entry selected in grub menu after migration with AutoYaST
- Related ticket: https://progress.opensuse.org/issues/119515
- Verification run: https://openqa.suse.de/tests/10825456#
=> Workaround bsc#1209083 via reducing matched needle

tests/console/patterns.pm
https://progress.opensuse.org/issues/127562
[VR](http://openqa.suse.de/t10912251)
zypper log can be seen at [link](http://openqa.suse.de/tests/10912251/file/patterns-zypper.log)after case failure.
=> Upload zypper log if any issue with test 'patterns'

tests/console/force_scheduled_tasks.pm
Remove soft-failure in force_scheduled_tasks for bsc#1178761.
- Related ticket: https://progress.opensuse.org/issues/126611
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/10911033#
=> Clean workaround for bsc#1178761

data/autoyast_sle15/autoyast_bcache.xml
Errors on validation of AutoYaST profile, need to fix to /mount instead of mount.
- Related ticket: https://progress.opensuse.org/issues/127583
- Needles: N/A
- Verification run: http://openqa.suse.de/tests/10917174#
=> Update autoyast profile of autoyast_bcache.xml

tests/virt_autotest/esxi_open_vm_tools.pm
Disabling clock sync test failed while running on svirt backend. For the fix, using the same date set command with qemu backend.
- Related ticket: https://progress.opensuse.org/issues/127553
- Verification run: http://10.67.129.96/tests/2148
=> Fix disabling clock sync test failure for svirt backend

tests/sles4sap/sys_param_check.pm
-replace deprecated mkinitrd with dracut
-handle test location and python version on TW
- Related ticket: https://progress.opensuse.org/issues/121684
https://dzedro.suse.cz/tests/1073 TW
https://dzedro.suse.cz/tests/1074 SLE
=> sys_param_check: Update code for TW

tests/installation/confirm_installation.pm
This test fails because of the java popup missing: 
https://openqa.suse.de/tests/10917246
- Related ticket: https://progress.opensuse.org/issues/124140
- Verification run: http://falafel.suse.cz/tests/overview?build=20230412-1&distri=sle&version=15-SP4
http://falafel.suse.cz/tests/1099
=> Add pattern condition for accepting java popup

tests/cpu_bugs/xen_domu_mitigation_test.pm
15SP5 have some change on kernel,So it needs to adapt,refer to the bug https://bugzilla.suse.com/show_bug.cgi?id=1205618.
Modify the file xen_domu_mitigation.pm.
- Verification run:http://10.67.129.4/tests/57559
http://10.67.129.7/tests/overview?result=passed&distri=sle&version=15-SP5&build=88.1&groupid=14
=> Adapt function test for taa and mds problem

lib/YaST/workarounds.pm
- Related ticket:  https://progress.opensuse.org/issues/127499
- Needles: -
- Verification run: https://openqa.suse.de/tests/10912707
- Previous PR turned out to make some  test modules less stable.
=> Fix assert_screen in apply_workaround_poo124652

tests/installation/mediacheck.pm
Neither on TW, Leap nor SLE this takes more than 2-3 minutes.
Due to boo#1192829, sometimes mediacheck doesn't start and openQA just wastes
1h of worker time (2h on aarch64 due to TIMEOUT_SCALE).
- Two hours wasted: https://openqa.opensuse.org/tests/3209137
Early failure: https://openqa.opensuse.org/tests/3225739
Success: https://openqa.opensuse.org/tests/3225736
=> installation/mediacheck: Reduce the timeout from 1h to 5min

lib/main_common.pm, tests/installation/partitioning.pm
Instead of calling it in multiple places with various complex conditions and getting it wrong in some cases, just call it in one place that works for all scenarios.
TW NET: https://openqa.opensuse.org/tests/3225684
TW DVD offline: https://openqa.opensuse.org/tests/3225683#live
Argon: https://openqa.opensuse.org/tests/3225682#live
Backports 15.4 Incidents: https://openqa.opensuse.org/tests/3225681
=> lib/main_common: Refactor online_repos configuration

data/kea-dhcp/kea-dhcp6.conf, schedule/alp/kea_dhcp6.yaml, tests/microos/workloads/kea-container/dhcp6_client.pm, tests/microos/workloads/kea-container/setup_dhcp6_server.pm
- Related ticket: https://progress.opensuse.org/issues/124209
- Needles: No
- Verification run: [DHCP-client](http://deepthi-openqa.qe.suse.de/tests/4926) | [DHCP-server](http://deepthi-openqa.qe.suse.de/tests/4925)
Latest VRs:
[DHCP6-client](http://deepthi-openqa.qe.suse.de/tests/4948) | [DHCP6-server](http://deepthi-openqa.qe.suse.de/tests/4947#)
=> Add a test to verify kea dhcp6 server container in ALP

.github/CODEOWNERS
The [GitHub CODEOWNERS](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners) file basically notifies all the people interested in particular file in case that file has been changed.
Also, if given file has code owners then at least one of them needs to approve every pull request before it can be merged.
This should be valid after we merge this pull request.
=> Add GitHub CODEOWNERS for Public Cloud and Containers tests

lib/publiccloud/azure.pm
Increase the timeout for collecting the boot-diagnostics (i.e. serial terminal) log on Azure.
- Related failure: https://openqa.suse.de/tests/10929910#step/ssh_interactive_end/31
- Verification run: https://openqa.suse.de/tests/10932333
=> Increase timeout for boot log collection

tests/containers/kubectl.pm
If the LB is pending, the current code gets pending as the IP. Changed the way to obtain the IP to solve the problem
- Related ticket: https://progress.opensuse.org/issues/126926
- Verification run: [openqa.mypersonalinstance.de/tests/xyz#step/module/x](https://openqa.suse.de/tests/10933038#step/kubectl/227)
=> Fix kubectl test when loadbalancer is pending

tests/kernel/ulp_openposix.pm, tests/kernel/ulp_threads.pm
Allow ulp_openposix to run without incident repo. In that case, test latest libpulp from product repos using openposix livepatches. Also fix ulp_threads to use livepatch package designated by ulp_openposix.
- Related ticket: https://progress.opensuse.org/issues/112004
- Needles: N/A
- Incident test: https://openqa.suse.de/tests/10810290
- Product test: https://openqa.suse.de/tests/10810299
=> Add support for userspace livepatching tests without incident repo

lib/main_micro_alp.pm, schedule/functional/extra_tests_textmode.yaml, tests/console/year_2038_detection.pm
https://progress.opensuse.org/issues/127130
[SLE](https://openqa.suse.de/tests/overview?distri=sle&build=rfan0406&version=15-SP5)
[TW](https://openqa.opensuse.org/tests/overview?version=Tumbleweed&build=rfan0406&distri=opensuse)
[ALP](https://openqa.opensuse.org/tests/3213577#)
[Micro-OS](https://openqa.opensuse.org/tests/3213576)
=> Cover year_2038_detection test on TW and Micro-OS

tests/installation/confirm_installation.pm
On current maintenance updtaes, there is no update for java package , so the license popup does nto appear anymore and the java handling solution is causing new failures.
- Related ticket: https://progress.opensuse.org/issues/127529
- Verification runs: http://falafel.suse.cz/tests/overview?build=20230416-1&distri=sle&version=15-SP4
=> Remove Java popup handling

tests/kernel/bpftrace.pm
On Aarch64 naptime.bit is terminated before attaching any probes. Doubling the timeout appears to be long enough to prevent this.
This doubles the runtime because scripts run until they receive SIGINT.
=> extra_tests_kernel: Increase runtime for ARM

tests/x11/firefox/firefox_appearance.pm
https://progress.opensuse.org/issues/127511
At the same time, remove the loop to match the needle
[QEM](https://openqa.suse.de/tests/overview?distri=sle&build=rfan0417)
[SLE15SP5](https://openqa.suse.de/tests/overview?build=rfan0417_1&version=15-SP5&distri=sle&test=firefox_desktop)
- Needles: Added via openQA webUI
=> Fix needle match timeout for firefox_appearance test

tests/x11/x3270_ssl.pm
Removing unused needle. The syntax of `record_info` has also been changed to be the same as the rest in the entire document.
- Related ticket: https://progress.opensuse.org/issues/127814
- Verification run: https://openqa.suse.de/tests/10937670
Since no significant logic changes were made, one test run is sufficient (only checking syntax, not test itself).
=> Remove unused needle & update record_info syntax

tests/x11/gedit.pm
Ensure gedit is installed before launching it
GNOME changes the default text-editor from gedit to gnome-text-editor
- Related ticket: https://build.opensuse.org/request/show/1079456
- Needles: N/A
=> gedit: ensure_installed before running it

tests/console/switch_to_wicked.pm
Switching from NetworkManager to wicked requires also wicked to be configured
- Related ticket: https://progress.opensuse.org/issues/125864
- Needles: N/A
- Verification run: https://openqa.opensuse.org/tests/3230050
=> switch_to_wicked: configure dhcp after switching to wicked

lib/main_common.pm, tests/kernel/bcc.pm
Add smoke test for BCC. There are many BCC tools and they all are different. So this just selects a few which might be interesting to us.
Note that it doesn't check the output yet because I want to figure out how to properly do that with bpftrace first. Also a lot of these tools have upstream issues and are inherently flaky. We are only running them to make sure the compiler framework and kernel work.
@czerw @pevik
=> extra_tests_kernel: Add BCC tools test

schedule/kernel/ibtest-master-autoyast.yaml, schedule/kernel/ibtest-master-rdma-next.yaml, schedule/kernel/ibtest-master.yaml, schedule/kernel/ibtest-slave-rdma-next.yaml, schedule/kernel/ibtest-slave.yaml
This is a variable we have to change every now and then to match the version of the distro we are testing, so we should not define it in the schedule but on the testsuite level.
=> Remove DEVEL_TOOLS_REPO from schedules

data/autoyast_opensuse/create_hdd/create_hdd_textmode_aarch64.xml, data/autoyast_opensuse/create_hdd/create_hdd_textmode_x86_64.xml, data/autoyast_sle15/create_hdd/create_hdd_textmode_ppc64le.xml, schedule/functional/autoyast_create_hdd/autoyast_create_hdd_textmode.yaml
https://progress.opensuse.org/issues/124470
o3: x86_64 and aarch64
OSD: x86_64, aarch64, ppc64le_kvm and s390x_kvm
[SLE](https://openqa.suse.de/tests/overview?arch=&flavor=&machine=&test=create_hdd_textmode_autoyast&modules=&module_re=&distri=sle&version=15-SP5&build=88.1&groupid=220)
[TW](https://openqa.opensuse.org/tests/overview?distri=opensuse&build=rfan0407&version=Tumbleweed)
The blow commits need to be reviewed at the same time:
**https://gitlab.suse.de/qsf-u/qa-sle-functional-userspace/-/merge_requests/159**
**https://github.com/os-autoinst/opensuse-jobgroups/pull/304**
=> Add create_hdd_textmode tests via autoyast

data/kernel/open.bt, tests/kernel/bpftrace.pm
Check that bpftrace successfully attaches a kernel probe and it extracts specific data.
Waiting for verification run; https://openqa.suse.de/tests/10939497
=> extra_tests_kernel: Test bpftrace with kprobe:do_sys_openat2

tests/installation/start_install.pm
We need wait more time for 'startupdate'.
- Related ticket: https://progress.opensuse.org/issues/127715
- Needles: N/A
http://openqa.suse.de/tests/10932788#
http://openqa.suse.de/tests/10932789#
http://openqa.suse.de/tests/10932790#
http://openqa.suse.de/tests/10932791#
http://openqa.suse.de/tests/10932793#
=> Increase timeout value for startupdate

lib/main_micro_alp.pm, tests/publiccloud/slem_prepare.pm
Adds code to allow scheduling of container test runs for SLEM on PC.
- Related ticket: https://progress.opensuse.org/issues/110791
- Verification run: [podman](https://duck-norris.qe.suse.de/tests/12581) | [docker](https://duck-norris.qe.suse.de/tests/12583)
=> Add container schedule for SLEM on PC

lib/network_utils.pm, tests/wicked/basic/sut/t01_basic.pm
- Related ticket: https://progress.opensuse.org/issues/120127
- VR: https://openqa.suse.de/tests/10947641
bug reported: https://bugzilla.suse.com/show_bug.cgi?id=1210641
=> Wicked: ignore bonding_masters interface on ppc64le

lib/main_common.pm, lib/main_micro_alp.pm, tests/jeos/firstrun.pm
Wizard is activate on serial device `ttysclp0` as expected.
In order to interact with it, we need borrow the console from the serial
and attach it to already active VNC session on the host.
- Related ticket: https://progress.opensuse.org/issues/119080
- Verification run: https://openqa.suse.de/tests/10897979
=> Testing jeos-firstboot on s390x images 

lib/containers/k8s.pm
When k3s is installed (utils::install_k3s) it needs some time to be ready to accept the creation of pods.
- Related ticket: https://progress.opensuse.org/issues/127955
- Verification run: http://openqa.suse.de/tests/10948319
=> containers: ensure k3s has the default serviceaccount

data/virt_autotest/guest_params_xml_files/sles_12_sp5_64_xen_hvm_uefi_with_power_management_x86_64.xml, data/virt_autotest/guest_params_xml_files/sles_15_sp4_64_xen_hvm_uefi_with_power_management_x86_64.xml, data/virt_autotest/guest_params_xml_files/sles_15_sp5_64_xen_hvm_uefi_with_power_management_x86_64.xml
* **Recent** uefi guest installation on 15-SP4/SP5 xen host failed because text console can not be opened for yast2 installation, which has something to do with ovmf firmware used, for example, [this one](https://openqa.suse.de/tests/10929519#step/unified_guest_installation/1015).
* **After** looking into ovmf firmware definition, it seems that ```ovmf-x86_64-xen-4m.bin``` is the right one to be used because it is used for xenfv virtual machine specifically.
* **The** firmware auto-selection feature for Xen virtual machine also prefers ```ovmf-x86_64-xen-4m.bin```.
* [uefi 15sp5 on 15sp5](https://openqa.suse.de/tests/10932004)
* [uefi 15sp4 on 15sp5](https://openqa.suse.de/tests/10932007)
* [uefi 15sp5 on 15sp4](https://openqa.suse.de/tests/10937285)
* [uefi 12sp5 …
=> Use ovmf xen firmware for uefi guest on SLE 15 host

tests/installation/mediacheck.pm
Bump timeout for mediacheck in aarch64
- Related ticket: https://progress.opensuse.org/issues/127976
- Verification run:https://openqa.suse.de/tests/10952875#details
=> Bump timeout for mediacheck in aarch64

tests/wsl/firstrun.pm
While installing WSL, the order of the screens have changed so now there's a Nvidia driver trust screen before choosing the repos. This only happens in 15-SP5.
- Related ticket: https://progress.opensuse.org/issues/127010
- https://openqa.suse.de/tests/10948602
- https://openqa.suse.de/tests/10948601
=> Nvidia trust drivers screen moved in WSL YaST install

lib/hacluster.pm, tests/ha/check_after_reboot.pm, tests/ha/migrate_clvmd_to_lvmlockd.pm
Workaround for issues found on migrate_clvmd_to_lvmlockd and check_after_reboot related 
to network starting to late and iscsi failing, causing a cascade effect that leads to pacemaker start failure.
fixes:_
TEAM-7786
TEAM-7788
Contains fixes from:
https://github.com/os-autoinst/os-autoinst-distri-opensuse/compare/master...lpalovsky:os-autoinst-distri-opensuse:Wait_for_supportserver
VR:
https://openqa.suse.de/tests/10953277
https://openqa.suse.de/tests/10953330
https://openqa.suse.de/tests/10953892
https://openqa.suse.de/tests/10953888
https://openqa.suse.de/tests/10953877
https://openqa.suse.de/tests/10954017
Failures:
https://openqa.suse.de/tests/10940657
https://openqa.suse.de/tests/10940659
https://openqa.suse.de/tests/10940612
https://openqa.suse.de/tests/10942056 …
=> Workaround for iscsi failure to connect after boot

data/sles4sap/qe_sap_deployment/qesap_aws.yaml, data/sles4sap/qe_sap_deployment/qesap_aws_sapconf.yaml, lib/qesapdeployment.pm, tests/sles4sap/qesapdeployment/configure.pm
Add QESAP_CLUSTER_OS_OWNER setting to configure the os_owner terraform variable from job settings.
Add more logs in qesap_cluster_log_cmds.
Remove no more used DEPLOYMENT_DIR alias for  QESAP_DEPLOYMENT_DIR setting.
Add a user warning about ignored QESAP_INSTALL_GITHUB variables. Split qesap_get_variables culr/grep command composition to have more readable test code.
- Related ticket: [TEAM-7693](https://jira.suse.com/browse/TEAM-7693)
qesap regression AWS: http://openqaworker15.qa.suse.cz/tests/147327
mr_test Azure: https://openqa.suse.de/tests/10954414
=> os_owner configurable in AWS qesap regression

tests/wsl/firstrun.pm, tests/wsl/wsl_cmd_check.pm
The PowerShell screen sometimes stays at the background and creates an incorrect scenario, because the commands are not being typed
- Related ticket: https://progress.opensuse.org/issues/126725
- https://openqa.suse.de/tests/10953266
=> Improve the check of the PowerShell screen

tests/security/ibmtss/ibmtss_basic_function.pm
The openQA module was pulling the latest version of testsuite from upstream git repository.
This was conflicting with the packaged version, giving test failures.
- Related ticket: https://progress.opensuse.org/issues/128057
- Verification run: https://openqa.suse.de/tests/10954352 
NOTE: this test is currently relevant only for aarch64.
=> Use matching version of upstream testsuite

lib/main_micro_alp.pm
Run repo replacement only it is needed after booting an image or finishing the deployment of the system from DVD.
Schedule additional transactional tests for ignition/combustion test suites.
* [dvd-staging](http://kepler.suse.cz/tests/20590#)
* [microos-Staging:D-Staging-DVD-x86_64-BuildD.499.2-container-host-microos@64bit-2G-HD40G](http://kepler.suse.cz/tests/20590#)
* [microos-Staging:D-Staging-MicroOS-Image-ContainerHost-x86_64-BuildD.1.8-container-host@64bit](http://kepler.suse.cz/tests/20591#)
* [microos-Tumbleweed-MicroOS-Image-x86_64-Build20230419-microos-combustion@64bit](http://kepler.suse.cz/tests/20592#)
* [microos-Tumbleweed-MicroOS-Image-x86_64-Build20230419-microos-ignition@64bit](http://kepler.suse.cz/tests/20593#)
* …
=> Fix schedule for MicroOS and SLE-Micro

tests/wicked/basic/sut/t01_basic.pm
Related: https://bugzilla.suse.com/show_bug.cgi?id=1210641
VR: https://openqa.suse.de/tests/10958978
=> Wicked: ignore bonding_masters on t01_basic test suite

data/yam/agama/auto/alp.sh, schedule/yast/opensuse/agama_autoinst.yaml, tests/yam/agama/auto/auto.pm, tests/yam/agama/auto/url_prepare.pm
- Related tickets: https://progress.opensuse.org/issues/126857
(also included parts of): https://progress.opensuse.org/issues/127349
- Needles: 3 new needles created with needle editor
- [Verification runs for aarch64 and x86_64 on O3](https://openqa.opensuse.org/tests/overview?distri=alp&version=1.0.0&build=4.26&groupid=96)
- Using `agama.auto` boot parameter to launch the automatic installation
- Currently using a shell skript to execute agama commands
=> ALP test profile for automated installation of Bedrock

tests/x11/gb18030.pm, tests/x11/gnomecase/gnome_window_switcher.pm, tests/x11/ibus/ibus_test_cn.pm, tests/x11/ibus/ibus_test_jp.pm, tests/x11/ibus/ibus_test_kr.pm
> https://progress.opensuse.org/issues/127964 [desktop] test fails in gb18030: gedit no longer installed by default
> https://progress.opensuse.org/issues/127967 [desktop] test fails in gnome_window_switcher
- Needles: N/A
> https://openqa.opensuse.org/tests/3235288# desktopapps-gb18030
> https://openqa.opensuse.org/tests/3241502# desktopapps-gnome
The ibus related VR is not provided due to [boo#1206230](https://bugzilla.opensuse.org/show_bug.cgi?id=1206230) and [boo#1197719](https://bugzilla.opensuse.org/show_bug.cgi?id=1197719)
=> Ensure installed before invoking gedit

tests/containers/run_container_in_k3s.pm
Increase the timeout for the kubectl apply due to some recent test failures therein.
- Related failure: https://openqa.suse.de/tests/10965642#step/run_container_in_k3s/51
- Verification run: https://duck-norris.qe.suse.de/tests/12697
=> Increase timeout for kubectl apply

data/hpc/papi_hw_info.c, lib/hpc/utils.pm, tests/hpc/mpi_master.pm
Introducing a basic test for HPC papi module by executing a c test file based on papi library.
Related ticket: https://jira.suse.com/browse/PED-3032
Verification Run: https://openqa.suse.de/tests/10957829#
=> Add basic testing for HPC papi module

tests/kernel/bpftrace.pm
On backends using a jump host (e.g. spvm) sending EOT kills the intermediate SSH connection. So use the file download feature instead.
Also kill the background script once we are finished.
Waiting for verification: https://openqa.suse.de/tests/10953267
=> extra_tests_kernel/bpftrace: Avoid ending SSH session with EOT

tests/boot/grub_test_snapshot.pm
Set grub timeout to -1 at grub test snapshot test module
- Verification run: https://openqa.suse.de/tests/10979841#
=> Set grub timeout to -1 at grub test snapshot test module

tests/yast2_gui/yast2_network_settings.pm
We need ensure 'Add' button clicked in Network Settings, and there is refreshment issue for ' yast2-network-settings_overview_hardware-dialog_device-type_bridge', so add workaround for it.
- Related ticket: https://progress.opensuse.org/issues/127607
- Needles: N/A
- Verification run:  https://openqa.suse.de/tests/overview?version=15-SP5&distri=sle&build=lemon-suse%2Fos-autoinst-distri-opensuse%23ensure-add-button-clicked-network-setting&flavor=Online
job for the glitch issue:  https://openqa.suse.de/tests/10971316#step/yast2_network_settings/18
=> Ensure 'Add' button clicked in Network Settings

tests/network/samba/samba_adcli.pm
https://progress.opensuse.org/issues/126866
We can't remove the workaround so far due to
https://sd.suse.com/servicedesk/customer/portal/1/SD-119612
[s390x](https://openqa.suse.de/tests/overview?build=rfan0425&distri=sle)
=> Use ip address instead of DNS name before joining to domain

data/virt_autotest/guest_params_xml_files/alp_bedrock_kvm_hvm_x86_64_uefi_imported_qcow2_disk_vnet.xml, data/virt_autotest/guest_params_xml_files/alp_kvm_hvm_x86_64_imported_disk_vnet_template.xml, lib/concurrent_guest_installations.pm, lib/virt_autotest/utils.pm, schedule/virt_autotest/alp-virt-core-tests.yaml, tests/virt_autotest/alp_guest_installation.pm, tests/virt_autotest/sev_es_guest_verification.pm, tests/virt_autotest/uefi_guest_verification.pm, tests/virt_autotest/unified_guest_installation.pm
Motivation of the PR:
- alp will have quite several different products, and each product will have several images. If using static guest profile, there will be a lot of similar profile files in openqa code directory `data/virt_autotest/guest_params_xml_files/`. 
- To avoid it, give limited template files in the data dir, and let code handles dynamic profile generation based on it.
The design:
- please read the requirement in https://progress.opensuse.org/issues/126905
What will be supported with the PR merged: 
- creation of different types of alp guests with mixture of below
- using alp micro and alp bedrock products (if newer alp products follow similar configuration and have no extra special handling, it will work seamlessly too)
- with each product's  Default-qcow(qcow2) and …
=> [virtualization] Extend guest installation for generating guest profile from template for alp

tests/wsl/firstrun.pm
While installing WSL, the order of the screens have changed so now there's a Nvidia driver trust screen before choosing the repos. This only happens sometimes.
- Related ticket: https://progress.opensuse.org/issues/128135
- http://openqa.suse.de/tests/10979993
- http://openqa.suse.de/tests/10979994
- http://openqa.suse.de/tests/10979995
- http://openqa.suse.de/tests/10979996
=> Nvidia trust drivers screen moved in YaST install

schedule/qam/common/virt/qam_virt_install_guest.yaml
poo#https://progress.opensuse.org/issues/124928
Modify guest installation schedule for guest migration to keep job running well.
- Related ticket: https://progress.opensuse.org/issues/124928
- Needles: N/A
- Verification run: [kvm test](http://openqa.qam.suse.cz/tests/52715), [xen test](http://openqa.qam.suse.cz/tests/52713), [kvm migration test](http://openqa.qam.suse.cz/tests/overview?build=:S:M:28650:295434:64bit-guest-mi-ipmi:12-SP5:g_m_test:&distri=sle&version=12-SP5&groupid=149),  [xen migration test](http://openqa.qam.suse.cz/tests/overview?build=:S:M:28650:295434:64bit-guest-mi-ipmi-group2:12-SP5:g_m_test:&distri=sle&version=12-SP5&groupid=160)
=> Modify guest installation schedule for guest migration

tests/wsl/prepare_wsl_feature.pm
Seems like the time for the installation and activation of WSL features has been significantly increased
- Related ticket: https://progress.opensuse.org/issues/128309
- http://openqa.suse.de/tests/10985950
- http://openqa.suse.de/tests/10985952
=> Increase the timeout for enabling WSL feature

lib/containers/k8s.pm, tests/containers/run_container_in_k3s.pm
I checked during the verification run (e.g. aarch64) it spend ages to deploy the pod. So increasing the timeout solves the problem. Anyway I add extra debugging information for next time.
Also now, K3s is uninstalled after the test
- Related ticket: https://progress.opensuse.org/issues/128354
- Verification run: https://openqa.suse.de/tests/overview?build=ilausuch%2Fos-autoinst-distri-opensuse%23fix_k3s_setup&version=5.2&distri=sle-micro
=> Ensure k3s is working properly

tests/console/ansible.pm
- Previous pull request: #16933
* **Package ansible-test requires Python2.7** [poo#128300](https://progress.opensuse.org/issues/128300), [bsc#1210875](https://bugzilla.suse.com/show_bug.cgi?id=1210875)
Enforcing `python3` in `ansible.cfg` on **SLE 15-SP5**.
* **Nothing provides 'python3-virtualenv** [poo#128327](https://progress.opensuse.org/issues/128327), [bsc#1210876](https://bugzilla.suse.com/show_bug.cgi?id=1210876)
Skipping `ansible-test` on **SLE 15-SP54**.
- Verification run: [Leap 15.5](https://pdostal-server.suse.cz/tests/4373), [SLE 15-SP5](https://pdostal-server.suse.cz/tests/4372), [SLE 15-SP4](https://pdostal-server.suse.cz/tests/4374)
=> Temporally disable ansible-test package on SLE

lib/opensslca.pm
keyUsage attribute with PR #16950 broke CA key generation on 15SP1. We introduce a condition on distro version to address older openssl 
- Related ticket: https://progress.opensuse.org/issues/128396
- https://openqa.suse.de/tests/11000321              
- https://openqa.suse.de/tests/11000322              
- https://openqa.opensuse.org/tests/3251287          
- https://openqa.opensuse.org/tests/3251288
- https://openqa.suse.de/tests/11000327
- https://openqa.suse.de/tests/11000328
- https://openqa.opensuse.org/tests/3251294
- https://openqa.opensuse.org/tests/3251295
=> Exclude keyUsage attr on older openssl (15SP1)

tests/containers/podman_pods.pm
There are still a lot of timeouts in aarch64 jobs.
VRs:
https://openqa.suse.de/tests/11006810
https://openqa.suse.de/tests/11006811
https://openqa.suse.de/tests/11006812
=> Podman Pods: increase timeout for kubectl wait

lib/containers/k8s.pm
k3s has issues with the long hostnames assigned by publiccloud providers. On PublicCloud test runs we therefore assign manually a node name to prevent issues with this.
- Related ticket: https://progress.opensuse.org/issues/128468
- Verification run: [SLEM 5.4 GCE](https://duck-norris.qe.suse.de/tests/12711#step/podman_pods/127)
=> Manually set k3s node name on PublicCloud

schedule/kernel/ibtest-master-autoyast.yaml, schedule/kernel/ibtest-master-rdma-next.yaml, schedule/kernel/ibtest-master-tumbleweed.yaml, schedule/kernel/ibtest-master.yaml, schedule/kernel/ibtest-slave-autoyast.yaml, schedule/kernel/ibtest-slave-rdma-next.yaml, schedule/kernel/ibtest-slave-tumbleweed.yaml, schedule/kernel/ibtest-slave.yaml
Remove IBTEST_IP1 and IBTEST_IP2 from InfiniBand schedules. These should be set elsewhere, so the schedules don't contain actual dependencies to infrastructure.
=> Remove IP settings from InfiniBand tests

schedule/functional/extra_tests_gnome.yaml, schedule/functional/extra_tests_textmode.yaml
At least on PPC, the serial device (dev/hvc0) does not retain permission
post reboot and we fail to write to it as normal user.
system_prepare takes care of setting the right permissions for us.
- Related ticket: https://progress.opensuse.org/issues/123791
- Needles: N/A
- Verification run: https://openqa.opensuse.org/tests/3246598
=> Add system_prepare to extra_test_{gnome,textmode} schedule

tests/containers/podman_pods.pm
Verify that pod manifest HostPid option was set accordingly.
- ticket: https://progress.opensuse.org/issues/124604
- Verification run: http://kepler.suse.cz/tests/20623#
=> podman: verify hostpid was set

schedule/security/create_hdd_autoyast/create_hdd_x86_64_uefi.yaml
- Related ticket: https://progress.opensuse.org/issues/128249
- Related PRs: https://github.com/os-autoinst/opensuse-jobgroups/pull/313
- https://openqa.suse.de/tests/11023545
- https://openqa.suse.de/tests/11023991
- https://openqa.opensuse.org/tests/3260088
- https://openqa.opensuse.org/tests/3260591
=> Move autoyast var to testsuite/jobgroup.

lib/containers/engine.pm, lib/containers/utils.pm, tests/containers/validate_btrfs.pm
New docker uses `overlayfs2` storage driver instead of `btrfs`. Change default settings for the `btrfs` storage driver validation.
- ticket: https://progress.opensuse.org/issues/128387
- Verification run: http://kepler.suse.cz/tests/20647#step/validate_btrfs/241
=> Change storage driver for newest docker

lib/containers/k8s.pm
Sometimes the download for k3s installation fails, this commit retry in this case
- Related ticket: https://progress.opensuse.org/issues/128570
- Verification run: http://openqa.suse.de/tests/11025411
=> Containers: Retry k3s installation script download

data/sles4sap/qe_sap_deployment/qesap_gcp.yaml, data/sles4sap/qe_sap_deployment/qesap_gcp_sapconf.yaml, tests/sles4sap/qesapdeployment/configure.pm
Setting QESAPDEPLOY_HANA_DATA_DISK_TYPE with default value like in the qe-sap-deployment project pd-ssd
Related ticket: TEAM-7761
- qesap regression GCP 12sp5 
- http://openqaworker15.qa.suse.cz/tests/149882 pd-sdd
- http://openqaworker15.qa.suse.cz/tests/151827 pd-standard (failure is about net quota, but tfvars get the right setting) https://openqaworker15.qa.suse.cz/tests/151845
- qesap regression GCP 15sp3 sapconf
- http://openqaworker15.qa.suse.cz/tests/149881 pd-sdd
- http://openqaworker15.qa.suse.cz/tests/151828 pd-standard
- qesap regression GCP 15sp3  saptune
- http://openqaworker15.qa.suse.cz/tests/149880 pd-sdd
- http://openqaworker15.qa.suse.cz/tests/151829 pd-standard (failure is about net quota, but tfvars get the right setting) …
=> Add setting in qesap for the Hana disk type

lib/containers/k8s.pm
Just to avoid things like https://openqa.suse.de/tests/11030336#step/podman_pods/132
=> Increase timeout for K3s installation

data/hpc/net/ifcfg-eth1, lib/hpcbase.pm, schedule/hpc/ww4.yaml, tests/hpc/barrier_init.pm, tests/hpc/ww4.pm, tests/hpc/ww4_await_pxe_install.pm
A new test which will run one controller node and two compute nodes without
supportserver. An important aspect of this test is the controller VM which
requires two network interfaces. The compute nodes should run on this network
once they boot.
- Related ticket: https://jira.suse.com/browse/PED-3033
- Needles: https://gitlab.suse.de/openqa/os-autoinst-needles-sles/-/merge_requests/1639
- Verification run: https://aquarius.suse.cz/tests/16376#
=> Implement test for HPC warewulf4

lib/hpcbase.pm
The variable is called inside the function which setups spack. Side note that this used to work so far until recently. Which sle15sp3 began to fail. So this should fix the issue with the missing libraries but the flow needs some investigation.
- Related ticket: https://progress.opensuse.org/issues/128597
https://openqa.suse.de/tests/overview?version=15-SP3&distri=sle&build=b10n1k%2Fos-autoinst-distri-opensuse%23spack_expansion
https://openqa.suse.de/tests/overview?version=15-SP5&distri=sle&build=b10n1k%2Fos-autoinst-distri-opensuse%23spack_expansion
=> HPC: Fix expansion of $mpi in assert_script_run

lib/Installation/Partitioner/LibstorageNG/v4_3/ExpertPartitionerController.pm, schedule/staging/RAID1@64bit-staging-Y.yaml
Chunk size selection is not an option anymore on the installer for RAID1 and raid1 test fails in staging. This PR fixes the issue
Progress ticket: https://progress.opensuse.org/issues/128609
VR: RAID1 staging: http://falafel.suse.cz/tests/1144
RAID1 old: http://falafel.suse.cz/tests/1145
=> Modify raid partitioning for chunksize=null

data/sles4sap/qe_sap_deployment/sles4sap_azure_generic.yaml, data/sles4sap/qe_sap_deployment/sles4sap_azure_generic_uri.yaml, tests/sles4sap/publiccloud/qesap_terraform.pm
Adopt the qe-sap-deployment feature to use secure storage when accessing installers.
- Related ticket: TEAM-6943
15sp5 http://openqaworker15.qa.suse.cz/tests/152529 (failure is not related to this PR) http://openqaworker15.qa.suse.cz/tests/152530
15sp4 http://openqaworker15.qa.suse.cz/tests/152528
=> Move HanaSr qesap deployment to sec storage

data/sles4sap/qe_sap_deployment/mr_test_gcp.yaml, data/sles4sap/qe_sap_deployment/qesap_gcp.yaml, data/sles4sap/qe_sap_deployment/qesap_gcp_sapconf.yaml, tests/sles4sap/qesapdeployment/configure.pm
Configure hana data and log disk in mr_test on GCP. Configure hana log disk in qesap for gcp and unify setting to configure both data and log disk.
- Related ticket: [TEAM-7761](https://jira.suse.com/browse/TEAM-7761)
-  qesap regression GCP sapconf http://openqaworker15.qa.suse.cz/tests/153201 and with `QESAPDEPLOY_HANA_DISK_TYPE=pd-standard` http://openqaworker15.qa.suse.cz/tests/153202
-  qesap regression GCP saptune
- mr_test 
- with no additional settings https://openqa.suse.de/tests/11040669 it fails as expected with `Could not retrieve required variable HANA_DISK_TYPE `  (this change require a JobGroup change),
-  with HANA_DISK_TYPE=pd-ssd https://openqa.suse.de/tests/11040725 , with HANA_DISK_TYPE=pd-standard https://openqa.suse.de/tests/11040741
=> Configure HANA disk type in mr_test

tests/console/openvswitch_ssl.pm, tests/console/sssd_389ds_functional.pm, tests/console/sssd_openldap_functional.pm, tests/console/syslog.pm, tests/console/wget_https.pm, tests/fips/strongswan/strongswan_client.pm, tests/network/openvpn_client.pm, tests/network/openvpn_server.pm, tests/security/389ds/tls_389ds_server.pm, tests/security/check_kernel_config/dm_crypt.pm, tests/security/create_swtpm_hdd/build_hdd.pm, tests/security/ebpf/check_cap_bpf.pm, tests/security/grub_auth/grub_authorization.pm, tests/security/mariadb/mariadb_ssl_client.pm, tests/security/openscap/oscap_setup.pm, tests/security/oscap_stig/baseline_comparison.pm, tests/security/pam/pam_mount.pm, tests/security/postgresql_ssl/postgresql_ssl_client.pm, tests/security/selinux/selinux_setup.pm, tests/security/swtpm/swtpm_env_setup.pm, tests/security/usbguard/usbguard.pm, tests/security/vsftpd/vsftpd_setup.pm
Some tests have started failing due to migrations to autoyast, eg. https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/16919. This PR adds missing dependencies to relevant tests.
Related ticket: https://progress.opensuse.org/issues/128735
- 15-SP4:
- `security/create_swtpm_hdd/build_hdd.pm` https://openqa.suse.de/tests/11041761
- `security/ebpf/check_cap_bpf` https://openqa.suse.de/tests/11041779
- `console/openvswitch_ssl.pm` https://openqa.suse.de/tests/11041895
- `console/syslog.pm` https://openqa.suse.de/tests/11041895
- `console/wget_https.pm` https://openqa.suse.de/tests/11041937
- `security/postgresql_ssl/postgresql_ssl_client.pm` https://openqa.suse.de/tests/11042045
- `security/mariadb/mariadb_ssl_client.pm` https://openqa.suse.de/tests/11042069
- …
=> Add missing runtime dependencies

tests/qam-minimal/s390tools.pm
This command is returning 4 because it can't reload root dasd.
Generally this check with or without workaround is pointless on running system.
- Related ticket: https://bugzilla.suse.com/show_bug.cgi?id=1209705 https://progress.opensuse.org/issues/125423
- Verification run: https://openqa.suse.de/tests/11024422
=> s390tools: Drop dasd_reload check

data/autoyast_sle15/autoyast_sle_powervm.xml.ep
Update the autoyast profile of textmode installation on spvm, the
pattern list is not the default pattern list, so add them; Under
the 'services-manager', the default_target should be 'multi-user'
for textmode.
- Related ticket: https://progress.opensuse.org/issues/127598
- Needles: n/a
- https://openqa.suse.de/tests/10991561
- https://openqa.suse.de/tests/10991563
- https://openqa.suse.de/tests/10991562
- Related MR: https://gitlab.suse.de/qsf-y/qa-sle-functional-y/-/merge_requests/500
=> Update autoyast profile for textmode installation

tests/console/sssd_389ds_functional.pm, tests/console/sssd_openldap_functional.pm, tests/console/wget_https.pm, tests/security/grub_auth/grub_authorization.pm
Some dependencies were missed in https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/16997.
- Related ticket: https://progress.opensuse.org/issues/128735
- https://openqa.suse.de/tests/11043004
- https://openqa.suse.de/tests/11043005
Some tests were also failing due to missing library `utils`.
- Verification run: https://openqa.suse.de/tests/11043538
=> Add missing runtime dependencies, vol. 2

data/autoyast_qam/12-common_base_installation.xml.ep, data/autoyast_qam/15-common_base_installation.xml.ep, lib/autoyast.pm, schedule/qam/common/15-common_base_installation_ay.yaml
https://progress.opensuse.org/issues/128732
Full name setting might impact needle matching
And if we define pattern in autoyast config files,
we need to use the exact name.
At the same time, fix a typo issue in schedule file
http://openqa.suse.de/tests/11039780
http://openqa.suse.de/tests/11040028
=> Fix autoyast pattern and user issues on qem test

tests/console/ovs_client.pm, tests/console/ovs_server.pm
we have now openvswitch3* packages and current packages of openvswitch belong to repository SLE-Module-Legacy15-SP5-Pool, that is why zypper_call failed
see https://progress.opensuse.org/issues/127799 for more details
=> Switch to openvswitch3* packages for ovs-server test on sles 15 sp5

tests/containers/bci_test.pm
Fail the test run, if the `tox` command fails.
- Verification run: https://openqa.suse.de/tests/11063925
=> Add pipefail

tests/x11/seahorse_sshkey.pm
- Related ticket: https://progress.opensuse.org/issues/128903
- https://openqa.suse.de/tests/11063918#step/seahorse_sshkey/1
- https://openqa.suse.de/tests/11063919#step/seahorse_sshkey/1
=> seahorse_sshkey.pm: fix poo#128903

tests/qa_automation/patch_and_reboot.pm
Workaround:
https://progress.opensuse.org/issues/128840
https://bugzilla.suse.com/show_bug.cgi?id=1211154
[VRs for sles15sp1-p3](https://openqa.suse.de/tests/overview?&distri=sle&build=rfan_ltss)
=> Activate LTSS product due to bsc#1211154

lib/containers/urls.pm
Reverts os-autoinst/os-autoinst-distri-opensuse#16981
ubi-init is back to life:
```
podman pull registry.access.redhat.com/ubi7/ubi-init
Trying to pull registry.access.redhat.com/ubi7/ubi-init:latest...
Getting image source signatures
Copying blob dc611367a437 done  
Copying blob ec121c671d0c done  
Copying config e597c5043a done  
Writing manifest to image destination
Storing signatures
e597c5043a71a0b18da54d03ba9f9c67059ab6a3388419880e0d19a4aac54e3c
```
=> Revert "Remove ubi7-init container image"

tests/wsl/firstrun.pm
The 60s timeout after accepting the NVIDIA license is not enough to complete the installation
- Related ticket: https://progress.opensuse.org/issues/128798
=> Increase NVIDIA drivers screen timeout

schedule/hpc/ww4.yaml
Remove BOOT_HDD_IMAGE from yml to set it up only for the controller of the cluster, and avoid run compute nodes with unwanted job variable.
- Related ticket: https://progress.opensuse.org/issues/128003
=> Move BOOT_HDD_IMAGE to the OpenQA test suite

tests/x11/hexchat_ssl.pm
The test opened overview mode by moving the cursor to `0,0`, which invoked the Gnome hot-corner feature. This mouse movement is now redundant and can be removed.
- Related ticket: https://progress.opensuse.org/issues/128960
- Verification run: https://openqa.suse.de/tests/11072699
=> Prevent hot-corner invocation by mouse movement

data/autoyast_qam/12-common_base_installation.xml.ep, data/autoyast_qam/15-common_base_installation.xml.ep, tests/qa_automation/patch_and_reboot.pm
Remove the old workaround at the same time:
https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/17004
- Related ticket: https://progress.opensuse.org/issues/128846
- Verification run: [sle12sp2-15sp3](https://openqa.suse.de/tests/overview?&distri=sle&build=rfan_ltss_new)
=> Apply workaround for bsc#1202234 for autoyast install

tests/xfstests/generate_report.pm, tests/xfstests/partition.pm, tests/xfstests/run.pm
Support xfstests run nfs test on multi machine. Set XFSTESTS_NFS_SERVER=1 to setup nfs server, and set PARALLEL_WITH for nfs client.
- Related ticket: https://progress.opensuse.org/issues/127478
- Needles: N/A
- https://openqa.suse.de/tests/11052962 (nfs server)
- https://openqa.suse.de/tests/11052963 (nfs client)
- https://openqa.suse.de/tests/10999022 (nfs test in one server)
- https://openqa.suse.de/tests/10999020 (generic test without nfs)
=> xfstests: Support nfs test on multi machine

tests/containers/bci_prepare.pm
The `pg_config` package is present in `postgresql-server-devel`, not in `postgresql-devel`.
- Verification run: [15-SP4](https://openqa.suse.de/tests/11073975#step/bci_prepare/38) | [12-SP5](https://openqa.suse.de/tests/11074493#step/bci_prepare/38) (both fail in a different subsequent step)
=> Update pgsql dependencies

tests/qa_automation/kernel_multipath.pm
- Related ticket: https://progress.opensuse.org/issues/128984
- Verification run: https://openqa.suse.de/tests/11074788
=> Increase timeout for kernel multipath flaky test

tests/containers/bci_prepare.pm
Also on openSUSE, use the postgresql-server-devel package instead of postgresql-devel.
- Verification run: https://openqa.suse.de/tests/11076233 (failure due to outdated BCI repo)
=> Also use postgresql-server-devel on openSUSE

tests/sles4sap/wizard_hana_install.pm
Depending on the disk size used during testing, the SAP Installation Wizard test module can cause a Low Disk Space warning to be shown on gnome which causes troubles when detecting with `assert_screen()` that the wizard has finished, as it checks for a clean gnome desktop. This commit adds the expected HANA filesystems to the ignore-paths key in `org.gnome.settings-daemon.plugins.housekeeping` so these paths are ignored and the warning not shown.
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/11064820#step/wizard_hana_install/21
=> Disable low space warning when testing SAP installation wizard

data/sles4sap/qe_sap_deployment/qesap_aws.yaml, data/sles4sap/qe_sap_deployment/qesap_aws_sapconf.yaml, data/sles4sap/qe_sap_deployment/qesap_azure.yaml, data/sles4sap/qe_sap_deployment/qesap_azure_sapconf.yaml, data/sles4sap/qe_sap_deployment/qesap_azure_uri.yaml, data/sles4sap/qe_sap_deployment/qesap_gcp.yaml, data/sles4sap/qe_sap_deployment/qesap_gcp_sapconf.yaml, tests/sles4sap/qesapdeployment/configure.pm
Always use OS_VER in all the qesap regression conf.yaml templates. This is used for tests using image from the cloud catalog and for tests using custom builds.
- Related ticket: TEAM-7693
AWS 15sp5 (the one that this  PR is mind to fix) http://openqaworker15.qa.suse.cz/tests/154807 **os_image** is fine in http://openqaworker15.qa.suse.cz/tests/154807/file/configure-terraform.tfvars Test fails for similar reason as before. Probably it is due to `os_owner`. Second VR with proper OS_OWNER setting http://openqaworker15.qa.suse.cz/tests/154814
AWS 15sp3 http://openqaworker15.qa.suse.cz/tests/154808 PASS
AZ 15sp5 http://openqaworker15.qa.suse.cz/tests/154810 PASS
AZ 15sp4 http://openqaworker15.qa.suse.cz/tests/154811 PASS
=> Standardize variable name in the conf.yaml for qesap

tests/sles4sap/publiccloud/mr_test_setup_env.pm
Remove PUBLIC_CLOUD_SLES4SAP from mr_test .tar download. This condition of PUBLIC_CLOUD_SLES4SAP can be deleted as non-public and public mr_test env setup use different test module:
- non-cloud env setup use: ./tests/sles4sap/saptune/mr_test.pm
- cloud env setup uses: ./tests/sles4sap/publiccloud/mr_test_setup_env.pm
Related ticket: [TEAM-6798](https://jira.suse.com/browse/TEAM-6798)
- Cloud mr_test https://openqa.suse.de/tests/11076569
- non cloud mr_test https://openqa.suse.de/tests/11076579
=> Remove not needed setting condition from mr_test

test_data/yast/opensuse/lvm+raid1.yaml
fixes failure : https://openqa.opensuse.org/tests/3278116#step/setup_raid1_lvm/4
- Verification run: https://openqa.opensuse.org/tests/3278733
combined with https://github.com/os-autoinst/opensuse-jobgroups/pull/324
=> Add TW test data for lvm+raid1

tests/containers/bci_prepare.pm
On SLES12-SP5 we need to use `python36-devel` instead of `python3-devel` to provide the required dependencies for BCI-Test.
- Verification run: [12-SP5](https://openqa.suse.de/tests/11087357) | [15-SP4](https://openqa.suse.de/tests/11087419)
=> Use python36-devel on SLES12-SP5

data/autoyast_qam/12-common_base_installation.xml.ep, data/autoyast_qam/15-common_base_installation.xml.ep
- Related ticket: https://progress.opensuse.org/issues/129056
- Verification run: https://openqa.suse.de/tests/overview?build=grub2_timeout&distri=sle
=> Set grub2 timeout to infinite

tests/console/golang.pm
Since go 1.20, the binary can newly be provided with debuginfo stripped into
a sep -debuginfo package.
This, in turn, confuses 'zypper se go' as the description of the debug package
matches the filter ' go[0-9][0-9.]* '. Explicitly filter -debuginfo packages out of the list.
- Related ticket: https://progress.opensuse.org/issues/128549
- Needles: N/A
- Verification run: https://openqa.opensuse.org/tests/3279101
=> golang: filter out debuginfo packages when finding go versions

tests/console/yast2_cmdline.pm
the yast-http-server module has been deprecated and removed from
recent products.
- Related ticket: https://progress.opensuse.org/issues/127856
- Needles: N/A
- Verification run: https://openqa.opensuse.org/tests/3276202
=> yast_cmdline: only test http-server on SLE/Leap up to 15.x

lib/main_common.pm
* Move module_build as the latests because it taints kernel
* Move BPF and io_uring to the top (the most important for SLE15, Tumbleweed)
Verification run: TODO
=> Reorder tests in load_extra_tests_kernel

data/autoyast_qam/15-common_base_installation.xml.ep
https://progress.opensuse.org/issues/128843
The NIC 'eth0' is added to firewall zone 'public' by default during
interactive installation. so add the same configuration in AutoYaST
[SLE15-SP1---SLES15-SP4](https://openqa.suse.de/tests/overview?distri=sle&build=rfan_x86)
**This PR only fixes the issue mentioned in [poo#128843](https://progress.opensuse.org/issues/128843), I will try to enhance the firewall configuration settings via [poo#129083](https://progress.opensuse.org/issues/129083) **
=> Add NIC to the default firewall zone 'public' in AutoYaST

tests/yast2_gui/yast2_security.pm
See https://progress.opensuse.org/issues/128687
VRs https://openqa.suse.de/tests/11091142#next_previous
http://waaa-amazing.suse.cz/tests/18315
=> Apply workaround yast2_security due to graphical glitch

lib/nfs_common.pm
The clear_console in serial terminal is unexpected which blocked the system and not returned which caused exportfs timeout.
- Related ticket: https://progress.opensuse.org/issues/128648
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/overview?version=15-SP5&distri=sle&build=lemon-suse%2Fos-autoinst-distri-opensuse%23fix-nfs-server-exports-timeout-issue&flavor=Online&arch=aarch64&arch=x86_64
=> Fix nfs-server exportfs timeout issue

lib/hpcbase.pm, tests/hpc/barrier_init.pm, tests/hpc/ww4.pm, tests/hpc/ww4_await_pxe_install.pm
Add mutex to remove controllers rebooting until the controller is ready. Fix also the tear down operations which destroy the barriers.
Previously, as we implementated the loop, it could have finished before the
controller is ready to boot the nodes or the nodes would have to wait even if
the server was done.
- Related ticket: https://progress.opensuse.org/issues/128003
- Verification run: https://aquarius.suse.cz/tests/16626
=> Let warewulf controller boot when controller is ready

data/yam/agama/auto/alp_tw.sh
Add agama auto install sh script for Tumbleweed
- Related ticket: https://progress.opensuse.org/issues/128183
- Needles: na
- Verification run: https://openqa.opensuse.org/tests/3247743
=> Add agama auto install sh script for Tumbleweed

tests/jeos/firstrun.pm
jeos-firstboot got updated there as well now.
- Verification run: https://openqa.opensuse.org/tests/3282110
=> jeos/firstrun: Leap 15.4 does not need explicit EULA acceptance

lib/susedistribution.pm, schedule/yam/agama/agama_installation.yaml, tests/yam/agama/agama_installation.pm
We need run Playwright tests directly from the Live ISO in openQA.
- Related ticket: https://progress.opensuse.org/issues/124550
- Needles: N/A
- Verification run: https://openqa.opensuse.org/tests/overview?distri=alp&version=agama-0.9&build=4.35&groupid=96
=> Add Playwright automation test 

tests/jeos/diskusage.pm
The expected size of kvm image for s390x is greater than for other KVM images.
- Verification run: [sle-15-SP5-JeOS-for-kvm-and-xen-s390x-Build2.14-jeos-main@s390x-kvm-sle12](https://openqa.suse.de/tests/11100392)
=> Minimal VM image for s390x has bigger rootfs

lib/YaST/Bootloader/BootloaderOptionsTab.pm, lib/YaST/Bootloader/BootloaderSettingsController.pm, schedule/staging/textmode_install@64bit-staging.yaml, schedule/yast/textmode_installation_minimal_role/textmode_installation_minimal_role_x86_64.yaml, tests/installation/bootloader_settings/disable_boot_menu_timeout_navigating_tabs.pm
Catch regression when sending right key when switching to tab Bootloader Options in ncurses
- Related ticket: https://progress.opensuse.org/issues/124610
- Verification run: https://openqa.suse.de/tests/11038962#step/disable_boot_menu_timeout_navigating_tabs/3
https://openqa.suse.de/tests/11041255#step/disable_boot_menu_timeout_navigating_tabs/3
=> Catch regression when sending right key when switching to tab Bootloader Options in ncurses

data/sles4sap/qe_sap_deployment/qesap_azure.yaml, lib/qesapdeployment.pm, lib/trento.pm, t/08_trento.t, t/09_qesapdeployment.t, tests/sles4sap/publiccloud/qesap_terraform.pm, tests/sles4sap/qesapdeployment/cluster_add_repos.pm, tests/sles4sap/qesapdeployment/configure.pm, tests/sles4sap/qesapdeployment/network_peering.pm, tests/sles4sap/qesapdeployment/peering_destroy.pm, tests/sles4sap/qesapdeployment/test_cluster.pm
Add a simple test about network peering in qesap regression for Azure. Increase the timeout for the az peering cmds.
Minor fixes in qesapdeployment and unit testing about peering functions.
Related ticket: [TEAM-7704](https://jira.suse.com/browse/TEAM-7704)
Verification run: Azure 15sp4
- saptune without QESAP_IBSMIRROR_RESOURCE_GROUP http://openqaworker15.qa.suse.cz/tests/156456 PASS http://openqaworker15.qa.suse.cz/tests/156470 PASS
- saptune with QESAP_IBSMIRROR_RESOURCE_GROUP and longer timeout http://openqaworker15.qa.suse.cz/tests/156462 and http://openqaworker15.qa.suse.cz/tests/156469 PASS WITH PEERING
- sapconf http://openqaworker15.qa.suse.cz/tests/156458 PASS
- mr_test https://openqa.suse.de/tests/11099115
- mr_test with IS_MAINTENANCE , …
=> Add IBS Mirror peering in qesap regression Azure

tests/kernel/bcc.pm, tests/kernel/bpftrace.pm, tests/kernel/fwupd.pm, tests/kernel/io_uring.pm, tests/kernel/module_build.pm, tests/kernel/tuned.pm
Reason: when io_uring test fails, following tests are skipped. https://openqa.suse.de/tests/11114594#step/io_uring/52
- https://openqa.suse.de/tests/overview?build=extra_tests_kernel%2Fnon-fatal-flags
- https://openqa.opensuse.org/tests/overview?build=extra_tests_kernel%2Fnon-fatal-flags
- https://openqa.suse.de/tests/11120609 (example of the test where failed test due problem with repos did not block other tests to run)
=> extra_tests_kernel: Add non fatal flags for various tests

data/autoyast_sle15/autoyast_sle_powervm.xml.ep
Sometimes when we install on the slice that has installed encrypted OS, then it
will wait for us to confirm to [**continue**](https://openqa.suse.de/tests/11130609#step/installation/2). We need to add a partition for the autoyast_sle_powervm.xml.ep
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/11130950
=> Add partition for autoyast_sle_powervm.xml.ep

tests/jeos/prepare_firstboot.pm
jeos-firstboot in 15.4 got the modular networking setup backported.
- Verification run: https://openqa.opensuse.org/tests/3290525
=> jeos/prepare_firstboot: Handle updated jeos-firstboot in 15.4

lib/qam.pm, tests/qam-minimal/install_update.pm
- Related ticket: https://progress.opensuse.org/issues/128993
https://dzedro.suse.cz/tests/1157
https://openqa.suse.de/tests/11075329
=> Fix shim for LTSS-ERICSSON

tests/xfstests/partition.pm
server_configure_network() disable firewalld on nfs server side. So disable this for nfs client and local test for compliance.
- Needles: N/A
- Verification run: http://10.67.129.54/tests/812
=> xfstests: disable firewalld before nfs test

lib/bootloader_setup.pm
ppc64le is taking more than 60 seconds to boot, therefore is not able to match bootloader screen.
Failure:
https://openqa.suse.de/tests/11131033
VR:
https://openqa.suse.de/tests/11131517
Fixes:
TEAM-7973 ppc64le is taking too long to show grub screen
=> Fix timeout while booting ppc64le

tests/jeos/firstrun.pm
Due to https://build.opensuse.org/request/show/1087172 - [boo#1207419](https://bugzilla.suse.com/show_bug.cgi?id=1207419)
- Verification run: https://openqa.opensuse.org/tests/3292715
=> tw: JeOS firstboot does not offer wifi configuration anymore

lib/main_micro_alp.pm, lib/transactional.pm, tests/transactional/enable_selinux.pm
Eanble SELinux testing for SLEM on PC. We add additional preparation setps to install and configure SELinux, as well as to allow the ssh tunnel port to make sure we have access to openQA.
This PR enabled the code part. Job group settings will be added after merge.
- Related ticket: https://progress.opensuse.org/issues/110791
* [SLEM 5.1 slem_selinux](https://duck-norris.qe.suse.de/tests/12919)
* [SLEM 5.1 containers_selinux](https://duck-norris.qe.suse.de/tests/12917)
* [SLEM 5.2 slem_selinux](https://duck-norris.qe.suse.de/tests/12926)
* [SLEM 5.2 containers_selinux](https://duck-norris.qe.suse.de/tests/12922)
* [SLEM 5.3 slem_selinux](https://duck-norris.qe.suse.de/tests/12916)
* [SLEM 5.3 containers_selinux](https://duck-norris.qe.suse.de/tests/12918)
* [SLEM 5.4 …
=> Add preparation step for SELinux

data/sles4sap/qe_sap_deployment/sles4sap_aws_generic.yaml
Enable SAP HANA SR Perf-Opt Scenario on AWS for 15SP5  
TEAM-7755 - Enable SAP HANA SR Perf-Opt Scenario on AWS for 15SP5
Related MR: https://gitlab.suse.de/qac/qac-openqa-yaml/-/merge_requests/1211
- Related ticket: https://jira.suse.com/browse/TEAM-7755
- Needles: NA
https://openqa.suse.de/tests/11146601#step/qesap_terraform/367 (test case failed on "Kill site_a - primary" test module, it is other issues)
=> Enable SAP HANA SR Perf-Opt test on AWS for 15SP5

data/sles4sap/qe_sap_deployment/mr_test_azure.yaml, data/sles4sap/qe_sap_deployment/mr_test_azure_maintenance.yaml, data/sles4sap/qe_sap_deployment/mr_test_azure_uri.yaml, data/sles4sap/qe_sap_deployment/mr_test_ec2.yaml, data/sles4sap/qe_sap_deployment/mr_test_ec2_product.yaml, data/sles4sap/qe_sap_deployment/mr_test_gcp.yaml, data/sles4sap/qe_sap_deployment/sles4sap_azure_generic_uri.yaml, tests/sles4sap/publiccloud/qesap_terraform.pm
Change the way to define deployment_name for mr_test and HanaSR Drop the usage of the `terraform workspace`
Use a setting in the conf.yaml template and define it on the fly with `set_var`.
Related ticket: [TEAM-7850](https://jira.suse.com/browse/TEAM-7850)
- HanaSR Azure https://openqa.suse.de/tests/11143744 generated `terraform.tfvars` has `deployment_name = "hanasr11143744"`. Terraform stage is called without `-w`
```
(exec_venv) # python3.10 /root/qe-sap-deployment/scripts/qesap/qesap.py --verbose -c /root/qe-sap-deployment/scripts/qesap/sles4sap_azure_generic_uri.yaml -b /root/qe-sap-deployment terraform  |& tee -a /tmp/qesap_exec_terraform.log.txt; echo Vq3bC-$?-
```
- mr_test Azure https://openqa.suse.de/tests/11143745
- mr_test Azure with …
=> Change the way to define Terraform deployment_name

tests/console/patterns.pm
https://progress.opensuse.org/issues/129436
Enhance the current logic which uploads the zypper log only
- Verification run: [VR](https://openqa.suse.de/tests/11146735)
logs can be uploaded if test fails: [y2logs](https://openqa.suse.de/tests/11146735/file/patterns-patterns_y2logs.tar.bz2)
=> Save y2logs in test 'patterns' if any issue

tests/hpc/spack_master.pm
Log files from /etc/spack for debugging. Mainly, tar should include compiler and packages configuration.
- Verification run:  https://openqa.suse.de/tests/11142688#downloads
=> Add spack config files of interest

tests/autoyast/wicked.pm
Do not pipe output into a pager for wicked service
- Related ticket: https://progress.opensuse.org/issues/128150
- Verification run: https://openqa.suse.de/tests/11146505#step/wicked/1
=> Do not pipe output into a pager for wicked service

tests/console/zypper_lifecycle.pm
Package can come from ISO and then test will fail because it expects repo
- Related ticket: https://progress.opensuse.org/issues/129466
- Verification run: https://openqa.suse.de/tests/overview?build=lifecycle_package&distri=sle
=> zypper_lifecycle: Force reinstall release-notes

tests/network/samba/samba_adcli.pm
- Occasional failures:
https://openqa.suse.de/tests/11149974#step/samba_adcli/150 | samba_adcli_5   | sle    | 15-SP4  | failed
https://openqa.suse.de/tests/11149209#step/samba_adcli/150 | mau-extratests2 | sle    | 15-SP3  | failed
https://openqa.suse.de/tests/11144887#step/samba_adcli/122 | mau-extratests2 | sle    | 15-SP1  | failed
https://openqa.suse.de/tests/11126435#step/samba_adcli/119 | mau-extratests2 | sle    | 15-SP2  | failed
https://openqa.suse.de/tests/11112805#step/samba_adcli/119 | mau-extratests2 | sle    | 15-SP4  | failed
https://openqa.suse.de/tests/11079462#step/samba_adcli/153 | mau-extratests2 | sle    | 15-SP2  | failed
https://openqa.suse.de/tests/11071809#step/samba_adcli/156 | mau-extratests2 | sle    | 15-SP1  | failed …
=> samba_adcli: Use script_retry for network cmds

lib/main_micro_alp.pm
It doesn't make sense to run this test everywhere. In the default list of tests should be enough.
VRs: 
- [microos](https://openqa.opensuse.org/tests/3299722)
- [container-host](https://openqa.opensuse.org/tests/3299740)
- [SLE Micro 5.4](https://openqa.suse.de/tests/11154779)
=> Stop running year_2038_detection everywhere in MicroOS

tests/autoyast/wicked.pm
Reverts os-autoinst/os-autoinst-distri-opensuse#17050
https://openqa.suse.de/tests/11155748 | qam-gnome                                                                                                 | sle    | 15-SP4  | failed
https://openqa.suse.de/tests/11155747 | qam-allpatterns                                                                                           | sle    | 15-SP4  | failed
https://openqa.suse.de/tests/11155450 | qam-gnome                                                                                                 | sle    | 15-SP4  | failed
https://openqa.suse.de/tests/11155266 | qam-gnome                                                                                                 | sle    | 15-SP4  | failed
https://openqa.suse.de/tests/11155265 | …
=> Revert "Do not pipe output into a pager for wicked service"

schedule/qam/15-SP5/qam-minimal-RAID1.yaml
- Related ticket: https://progress.opensuse.org/issues/129562
https://openqa.suse.de/tests/overview?distri=sle&build=raid_129562
=> Remove chunk_size from RAID1 settings on 15-SP5

tests/autoyast/wicked.pm
Not pipe out the information to pager for wicked service
- Verification run:  https://openqa.opensuse.org/tests/3301737#step/wicked/1
=> Not pipe out the information to pager for wicked service

lib/yam/agama/agama_base.pm, tests/yam/agama/auto.pm
See https://progress.opensuse.org/issues/128489
Adding a post_fail_hook directly in the module to use the default
installer password and just upload y2logs, as it seems like there
is nothing that does only that in the libs.
VRs
https://openqa.opensuse.org/tests/overview?distri=alp&build=JRivrain%2Fos-autoinst-distri-opensuse%2316994&version=1.0.0
https://openqa.opensuse.org/tests/overview?version=agama-0.9&build=JRivrain%2Fos-autoinst-distri-opensuse%2316994&distri=alp
=> Recover only yast logs in Agama auto-install

data/virt_autotest/guest_params_xml_files/opensuse_tumbleweed_64_kvm_hvm_x86_64.xml, data/virt_autotest/guest_unattended_installation_files/opensuse_tumbleweed_kvm_hvm_guest_x86_64.xml, data/virt_autotest/guest_unattended_installation_files/opensuse_tumbleweed_xen_hvm_guest_x86_64.xml, data/virt_autotest/guest_unattended_installation_files/opensuse_tumbleweed_xen_pv_guest_x86_64.xml, data/virt_autotest/host_unattended_installation_files/autoyast_opensuse_kvm_sshd.xml, data/virt_autotest/virt_logs_collector.sh, lib/guest_installation_and_configuration_base.pm, lib/ipmi_backend_utils.pm, lib/parallel_guest_migration_base.pm, lib/virt_autotest/utils.pm, lib/virt_autotest/virtual_network_utils.pm, schedule/virt_autotest/tumbleweed-virt-guest-install.yaml, tests/autoyast/installation.pm, tests/installation/ipxe_install.pm, tests/virt_autotest/cleanup_libvirtd_log.pm, tests/virt_autotest/libvirt_host_bridge_virtual_network.pm, tests/virt_autotest/libvirt_isolated_virtual_network.pm, tests/virt_autotest/libvirt_nated_virtual_network.pm, tests/virt_autotest/libvirt_routed_virtual_network.pm, tests/virt_autotest/libvirt_virtual_network_init.pm, tests/virt_autotest/login_console.pm, tests/virt_autotest/set_config_as_glue.pm, tests/virt_autotest/switch_to_ssh_and_install_hypervisor.pm, tests/virt_autotest/unified_guest_installation.pm, tests/virt_autotest/virt_utils.pm, tests/virtualization/universal/guest_management.pm, tests/virtualization/universal/patch_and_reboot.pm, tests/virtualization/universal/prepare_guests.pm, tests/virtualization/universal/virsh_start.pm, tests/virtualization/universal/virsh_stop.pm
Put all commits in one PR because tests have to be verified in O3, downloading TW medium from download.opensuse.org always timeout and is not supported from O3 repo.
Autoyast profiles for KVM host has been done and for XEN host will available soon. but we need not wait for xen autoyast profiles, it will be in a seperate PR.
1. Support installing host with autoyast.  The normal path for host autoyast profiles, data/ or autoyast/ in openqa path, cannot be adoppted in O3 , because static ipxe installation command is used in O3. I commit the files at here but actually copy them manually to a location in O3, /var/lib/openqa/share/factory/other/autoyast_opensuse_kvm_sshd.xml. No installation.pm is used in O3 for the time being, it will be considered if it is implemented for SLE in the future. …
=> Support installing host with autoyast

data/virt_autotest/alp_host_bridge_init.sh, lib/virt_autotest/utils.pm, schedule/virt_autotest/alp-virt-core-tests.yaml, tests/virt_autotest/libvirt_host_bridge_virtual_network.pm, tests/virt_autotest/prepare_alp_host.pm
Add ALP Host Bridge Network Test Support
- Related ticket: https://progress.opensuse.org/issues/122731
[use existed host bridge network interface](http://10.67.129.218/tests/395)
[setup new host bridge network interface](http://10.67.129.218/tests/393#)
[call post_fail_hook](http://10.67.129.218/tests/381)
=> [virt_autotest] Add ALP Host Bridge Network Test Support

lib/transactional.pm
- Occasional failures:
https://openqa.suse.de/tests/11159973#step/year_2038_detection/48 | slem_installation_default  |  5.4     | failed
https://openqa.suse.de/tests/11157712#step/year_2038_detection/48 | slem_installation_default  |  5.2     | failed
https://openqa.suse.de/tests/11157483#step/year_2038_detection/48 | slem_installation_default  |  5.2     | failed
https://openqa.suse.de/tests/11157177#step/year_2038_detection/48 | slem_installation_default  |  5.2     | failed
https://openqa.suse.de/tests/11155723#step/year_2038_detection/48 | slem_installation_default  |  5.4     | failed
https://openqa.suse.de/tests/11149033#step/year_2038_detection/48 | slem_installation_default  |  5.2     | failed
https://openqa.suse.de/tests/11143743#step/year_2038_detection/48 | …
=> Increse s390x boot timeout on SLEM

tests/hpc/conman.pm, tests/hpc/genders.pm, tests/hpc/mrsh_master.pm, tests/hpc/munge_master.pm, tests/hpc/pdsh_slave.pm, tests/hpc/powerman.pm, tests/hpc/ww4.pm
Some invocations are not return a value of 0 or 1 so need to be handled in order to pass the return value to test_case.
- Verification run: https://openqa.suse.de/tests/overview?version=15-SP5&build=b10n1k%2Fos-autoinst-distri-opensuse%2317106&distri=sle
=> Handle return values which assign undef

lib/db_utils.pm, lib/publiccloud/instance.pm, tests/publiccloud/boottime.pm
`Proceed on failures` option added to `influxdb_push_data`, bottime measuring routines updated accordingly
- Related ticket: https://progress.opensuse.org/issues/129574
- Verification run: coming soon.
=> Proceed on failures opt.add to influxdb_push_data

lib/bootloader_setup.pm, tests/installation/bootloader_uefi.pm
The first needle bootloader-grub2 might take already some seconds,
and send_key_until_needlematch is checking first for a needle and
then pressing the key.
By pressing the key first, we reduce the chance that we go into boot
mode before matchin the uefi edit screen.
Related ticket: https://progress.opensuse.org/issues/129601
VRs:
- [Multiple runs of JeOS 15-SP4](https://openqa.suse.de/tests/overview?version=15-SP4&build=jlausuch%2Fos-autoinst-distri-opensuse%23bootloader_uefi_fix&distri=sle) -> 100% success.
- [20 runs of openSUSE JeOS aarch64](https://openqa.opensuse.org/tests/overview?build=jlausuch%2Fos-autoinst-distri-opensuse%23bootloader_uefi_fix&version=Tumbleweed&distri=opensuse) -> 100% success
- [single JeOS 12-SP5 x86_64 uefi](https://openqa.suse.de/tests/11161307#)
- [random …
=> bootloader_uefi decrease chance of needle match timeout

lib/containers/k8s.pm
- Related ticket: https://progress.opensuse.org/issues/129541
- http://openqa.suse.de/tests/11165062
- https://openqa.suse.de/tests/11176573 (with helm)
=> containers: helm could be disabled during the k3s installation

lib/saltbase.pm
- Related ticket: https://progress.opensuse.org/issues/129496
Before: https://openqa.suse.de/tests/11175440#step/salt_minion/98
After: https://openqa.suse.de/tests/11176159#step/salt_minion/95
=> salt_master: Check master log only on master node

lib/qesapdeployment.pm, t/09_qesapdeployment.t, tests/sles4sap/qesapdeployment/test_cluster.pm
Add Ansible to touch /etc/hosts during qesap regression as it seems critical in mr_test.
Rename az based qesapdeploy function
Add timeout and verbosity to qesap_ansible_cmd
Related ticket: [TEAM-7704](https://jira.suse.com/browse/TEAM-7704)
Verification run: Azure 15sp4
https://openqaworker15.qa.suse.cz/tests/180441
=> Add qesap_add_server_to_hosts to qesap regression

data/virt_autotest/setup_dns_service.sh, tests/virt_autotest/setup_dns_service.pm
- move testvirt domain at the beginning of 'search' field in /etc/resolv.conf
- better match "fowarders" in /etc/named.conf
- move outputing file content in setup_dns  log to ease copy text and debug
Related ticket: https://progress.opensuse.org/issues/129544
https://openqa.suse.de/tests/11173132
[gi-guest_developing-on-host_developing-kvm](https://openqa.suse.de/tests/11175443)
[gi-guest_sles12sp5-on-host_developing-xen](https://openqa.suse.de/tests/11175354)
[gi-guest_developing-on-host_sles12sp5-xen](http://openqa.suse.de/tests/11175385)     //it failed previously without this PR. it passed with the PR now.
=> Fix setup_dns failure on sle12sp5 xen host

tests/xfstests/partition.pm
We only install nfs4-acl-tools on nfs server, but nfs/001 requires this package on client.
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/11181566
=> xfstests: install nfs dependencies on client

lib/saltbase.pm
https://bugzilla.suse.com/show_bug.cgi?id=1211591
https://progress.opensuse.org/issues/129595
[15SP1/SP4/SP5](https://openqa.suse.de/tests/overview?distri=sle&build=rfan0523)
15SP2/SP3 will not hit the issue for now, since the salt package version is at older `3004`
=> Add softfail for bsc#1211591 to salt test

lib/publiccloud/instance.pm
3 more parameters added to instance record pushed to InfluxDB for P.C. boottime measures in `perf_2` bucket, 
from test settings: `ARCH`, `DISTRI`, `REGION`
- Related ticket: https://progress.opensuse.org/issues/118027
- Needles: N/A
- Verification run: Coming soon
=> Parameters added to instance record pushed to InfluxDB

lib/registration.pm
Just assign default values on `get_var` of handle_scc_popups which once the variable is unused it throws continuesly warnings for the pattern match.
- Verification run: https://aquarius.suse.cz/tests/16462/logfile?filename=autoinst-log.txt
=> Prevent uninitialized value in pattern match

tests/support_server/setup.pm
Dynamic DNS seems to be broken on Tumbleweed because the  NAMED_CONF_INCLUDE_FILES variable was obsoleted in `/etc/sysconfig/named`
It's not clear if the below fix will break other versions. Also the NFS commit is only partially related; it seems that NetworkManager does not renew the DHCP release like wicked, this needs more investigation.
=> Support server dDNS fix on Tumbleweed

schedule/sles4sap/sles4sap_gnome_saptune_maintenance.yaml, tests/sles4sap/publiccloud/add_server_to_hosts.pm, tests/sles4sap/publiccloud/network_peering.pm
This pr adds changes the ansible calls to ssh calls, so that it doesn't clash with the `ssh_interactive_start` and `ssh_interactive_end` modules (see https://jira.suse.com/browse/TEAM-7992)
- Related ticket: https://jira.suse.com/browse/TEAM-7534
- Verification run: http://openqaworker15.qa.suse.cz/tests/180434
=> Working code for mr_test IBSM job

lib/yam/agama/agama_base.pm
- basically the livecd settings clear the password (and that might change once we move to IBS) but once we are in agama we should match password with the system to linux, and when we finish without failure we should match password to running system password.
=> Set password in pre_run_hook for agama_base

schedule/qam/common/mau-extratests-desktop.yaml, tests/x11/libqt5_qtbase.pm
- Related ticket: https://progress.opensuse.org/issues/129658
- Verification run: https://openqa.suse.de/tests/overview?distri=sle&build=x11_129658&version=15-SP5
=> Don't add development-tools on maintenance tests

tests/x11/seahorse_sshkey.pm
as https://bugzilla.suse.com/show_bug.cgi?id=1211416 , some desktop programs have been moved to the *SLE-WE* repository, so we need to add extension before installing packages
- Related ticket: https://progress.opensuse.org/issues/129334
- Verification run: https://openqa.suse.de/tests/11183052
=> Add workstation extension before seahorse installation

lib/trento.pm, schedule/sles4sap/trento/trento.yml, tests/sles4sap/trento/test_hana_unregister_node.pm
New test for Trento that unregister the secondary node for a hana cluster and check the status of the cluster on Trento.
Ticket number TRNT-921
Verification run: https://openqaworker15.qa.suse.cz/tests/181279#
=> New test for trento about unregister

lib/trento.pm, t/08_trento.t, tests/sles4sap/trento/test_hana_restore_stopped.pm
Align cluster_wait_status to latest fixes from
cluster_wait_status_by_regex.
Improve unit testing coverage in Trento cluster_wait_* API Change cypress_test_exec to return cumulative error score.
Related ticket: [TRNT-921](https://jira.suse.com/browse/TRNT-921)
Verification run: http://openqaworker15.qa.suse.cz/tests/181950 http://openqaworker15.qa.suse.cz/tests/181954
=> Optimize code in trento cluster_wait_status

lib/publiccloud/instance.pm
Source of P.C. REGION parameter updated in record pushed to InfluxDB, for P.C.boottime measures triggered from create_instances. No more got from test settings, but from provider data.
- Related ticket: https://progress.opensuse.org/issues/118027 
- Verification run: TBD see next posts
=> PC region parameter source updated for P.C.boottime measures

tests/console/check_migration_features.pm
python 3.10 is not shipped with SLE15 SP5 any more as it's been upgraded to python 3.11
- Related ticket: https://progress.opensuse.org/issues/128690
- Verification run: https://openqa.suse.de/tests/11111616#step/check_migration_features/29
https://openqa.suse.de/tests/11130644#step/check_migration_features/27
=> Check Python3 module for 3.11 instead of 3.10

lib/utils.pm, tests/kernel/before_nfs_test.pm
Firstly restarting the network service doesn't seem to cause NetworkManager to renew the DHCP lease. If we use `nmcli` instead then it doesn't wait for the lease to be renewed. So we have to wait for DNS to come back or perhaps use ping.
I'm not sure whether we should just switch to Wicked or if these are bugs with the NetworkManager setup.
=> Set host name when NetworkManager is active

schedule/alp/alp_yast.yaml
Enable automation for YaST in Container in ALP
**Ticket:**
- https://progress.opensuse.org/issues/128117
- [Development ALP Micro](https://openqa.opensuse.org/tests/overview?distri=alp&version=micro-0.1&build=3.5&groupid=110)
- [Development ALP Bedrock](https://openqa.opensuse.org/tests/overview?distri=alp&version=bedrock-0.1&build=5.1&groupid=111)
**Related PR:**
- [# 318](https://github.com/os-autoinst/opensuse-jobgroups/pull/318)
=> Enable automation for YaST in Container in ALP

lib/publiccloud/utils.pm, tests/publiccloud/patch_and_reboot.pm
pc: Add kill_packagekit() routine and use it in patch_and_reboot
- Related ticket: https://progress.opensuse.org/issues/120883
=> pc: Add kill_packagekit() routine and use it in patch_and_reboot

lib/trento.pm, t/08_trento.t, tests/sles4sap/trento/test_hana_unregister_node.pm, tests/sles4sap/trento/test_trento_web.pm
Remove unused parameter and better arguments validation in CY related API of the trento lib.
Add UT.
Increase the timeout for the CY execution of the unregistered test.
Related ticket: [TRNT-921](https://jira.suse.com/browse/TRNT-921)
http://openqaworker15.qa.suse.cz/tests/181959 fails in the new test due to script_run(podman ...cy) timeout
http://openqaworker15.qa.suse.cz/tests/181960 fails in eula  test due to script_run(podman ...cy) timeout 
http://openqaworker15.qa.suse.cz/tests/182576
http://openqaworker15.qa.suse.cz/tests/182593 timeout in new test after 1800secs http://openqaworker15.qa.suse.cz/tests/182593#step/test_hana_unregister_node/179  (so quite like it is not a test duration problem)
=> Simplify cypress exec API

lib/utils.pm, tests/kernel/before_nfs_test.pm
Testing a theory - this seems to be a candidate for a failure seen in Stagings
Reverts os-autoinst/os-autoinst-distri-opensuse#17135
=> Revert "Set host name when NetworkManager is active"

data/autoyast_sle12/create_hdd/create_hdd_sles_regression_s390x.xml.ep
Create autoyast installation testsuite to publish s390x image for sles12sp5 migration tests
- Related ticket: https://progress.opensuse.org/issues/128198
- Verification run: https://openqa.suse.de/tests/11193481#
- Related MR: https://gitlab.suse.de/qa-maintenance/qam-openqa-yml/-/merge_requests/529
=> Create autoyast installation testsuite to publish s390x image for sles12sp5 migration tests

tests/containers/podman_netavark.pm
- Related ticket: https://progress.opensuse.org/issues/129910
VRs:
- https://openqa.suse.de/tests/11199934
- https://openqa.suse.de/tests/11200094
- https://openqa.suse.de/tests/11200095
=> Containers: use httpd image instead of fedora/apache

lib/main_containers.pm
Staging jobs are showing the following:
`'aardvark-dns' not found in package names. Trying capabilities. `
due to repository configuration
https://openqa.opensuse.org/tests/3318594
=> Disable Netavark test on staging

lib/main_containers.pm, tests/containers/podman_netavark.pm
- don't execute it in 15-SP1 and 15-SP2
- remove --retry-all-errors in curl
VRs:
- [sle-15-SP3-GCE-CHOST-BYOS-Updates](https://openqa.suse.de/tests/11204907#)
- [sle-15-SP3-JeOS-for-kvm-and-xen-Updates](https://openqa.suse.de/tests/11204906#)
- [sle-15-SP3-Server-DVD-Updates](https://openqa.suse.de/tests/11204905#)
- [sle-15-SP1-GCE-CHOST-BYOS-Updates](https://openqa.suse.de/tests/11204904#)
- [sle-15-SP1-JeOS-for-kvm-and-xen-Updates](https://openqa.suse.de/tests/11204903#)
- [sle-15-SP1-Server-DVD-Updates](https://openqa.suse.de/tests/11204902#)
- [sle-15-SP3-GCE-CHOST-BYOS-Updates](https://openqa.suse.de/tests/11204907#)
- [sle-15-SP3-JeOS-for-kvm-and-xen-Updates](https://openqa.suse.de/tests/11204906#)
- [sle-15-SP3-AZURE-BYOS-Updates](https://openqa.suse.de/tests/11204898#)
- …
=> Podman Netavark fixes for SLE

schedule/yast/maintenance/yast_mru_install_minimal_with_addons_restapi.yaml
Remove stop_timeout_system_reboot test module
- Related ticket: https://progress.opensuse.org/issues/129799
- Verification run: https://openqa.suse.de/tests/11210580#
=> Remove stop_timeout_system_reboot test module

data/autoyast_sle15/hpc/create_hdd_textmode_aarch64.xml.ep, data/autoyast_sle15/hpc/create_hdd_textmode_x86_64.xml.ep, tests/hpc/before_test.pm
As we are shifting towards selinux HPC team suggested that we do not need to be testing against apparmor, which there are not expectations for it to work without issues. This commit ensure that Apparmor is turned off, however we still testing installation where Apparmor comes as dependency of the diveded system roles
- Related ticket: https://progress.opensuse.org/issues/127670
https://openqa.suse.de/tests/overview?version=15-SP5&distri=sle&build=b10n1k%2Fos-autoinst-distri-opensuse%2317162
https://openqa.suse.de/tests/overview?distri=sle&build=b10n1k%2Fos-autoinst-distri-opensuse%2317162&version=15-SP3
=> Make sure that apparmor is disabled on HPC

data/autoyast_sle15/create_hdd/create_hdd_maintenance.xml.ep
Install libyui-rest-api16 at 15sp5 for yast2_expert_partitioner
- Related ticket: https://progress.opensuse.org/issues/129997
- Verification run: https://openqa.suse.de/tests/11215645
15sp4 VR: https://openqa.suse.de/tests/11215661#step/setup_libyui_running_system/8
=> Install libyui-rest-api16 at 15sp5 for yast2_expert_partitioner

lib/publiccloud/instance.pm, lib/publiccloud/provider.pm, tests/publiccloud/slem_basic.pm
Public cloud `wait_for_ssh` routine code has been refactored and updated.
The changes topics are:
* routine structure improved,split in 3 blocks,ssh-port check,system-up check,result report;
* system-up check improved using `systemctl is-system-running`, more reliable than journal inspection;
* report on final status improved, also returned when `die(croak)`, helping in debugging;
* description in head section improved, parameters meaning and usage detailed;
* start-up phases detailed in inner loop, providing precise details on the status detected;
* new option `systemup_check`, to check on-demand ssh-open only and skip system-up check;
* new option `wait_stop`, to wait until ssh-closed,instead of open,improving shutdown/reboot checks;
* new option `logs`, _journalctl_ uploaded to test …
=> Public Cloud wait_for_ssh routine refactored and system-up check updated

schedule/yast/maintenance/yast_mru_install_minimal_with_addons_restapi.yaml, schedule/yast/sle/flows/default_sle15sp4_aarch64.yaml
The 'stop_timeout_system_reboot' test module should be added at 15sp3 aarch64 but 15sp4 don't need it.
- VR: SP4: https://openqa.suse.de/tests/11214412#
SP3: https://openqa.suse.de/tests/11210354
SP5: https://openqa.suse.de/tests/11214778
=> Remove stop_timeout_system_reboot_now test module at default 15sp4 aarch64 yaml file

data/sles4sap/qe_sap_deployment/qesap_azure_uri.yaml, tests/sles4sap/qesapdeployment/configure.pm
Add qesap regression tests: saptune enabled and sapconf enabled 
TEAM-8000 - [OSD] qesap regression test on Azure using 15-SP5 PAYG images
- Related ticket: https://jira.suse.com/browse/TEAM-8000
- Needles: NA
saptune enabled: https://openqa.suse.de/tests/11216912 (passed)
sapconf enabled: https://openqa.suse.de/tests/11216913 (failed on ansible part as it doesn't work on 15-SP5 PAYG images yet)
=> Add qesap regression test on Azure: 15-SP5 PAYG

data/yam/agama/auto/alp.sh, data/yam/agama/auto/alp_micro.jsonnet, tests/yam/agama/auto.pm
- Description
* Automate auto-installation of SUSE ALP Micro with Jasonnet.
* Fixed agama_auto_bedrock with installation finished check.
* https://progress.opensuse.org/issues/126848
- Needles: 
* agama-install-finished
* [**agama_auto_bedrock**](https://openqa.opensuse.org/tests/overview?arch=&flavor=&machine=&test=agama_auto_bedrock&modules=&module_re=&distri=alp&version=agama-0.9&build=4.35&groupid=96#)
* [**agama_auto_micro**](https://openqa.opensuse.org/tests/overview?arch=&flavor=&machine=&test=agama_auto_micro&modules=&module_re=&distri=alp&version=agama-0.9&build=4.35&groupid=96#)
=> Automate auto-installation of SUSE ALP Micro

schedule/security/encryption/lvm_encrypt_separate_boot.yaml, schedule/security/encryption/lvm_encrypt_separate_boot_s390x.yaml, test_data/security/encryption/lvm_encrypt_separate_boot.yaml, test_data/security/encryption/lvm_encrypt_separate_boot_s390x.yaml, test_data/security/encryption/lvm_encrypt_separate_boot_uefi.yaml
New security tests for encrypted installation testing with separate `/boot` partition and running in FIPS mode. So far it doesn't cover testing on `ppc64le`.
The tests are derived from YaST team and patched to run in FIPS mode, since some platforms require special steps in such case. This was done after consulting with the YaST team.
- https://progress.opensuse.org/issues/113162
- https://progress.opensuse.org/issues/116281
- s390x: https://openqa.suse.de/tests/11211502
- x86_64: https://openqa.suse.de/tests/11217049
- aarch64: https://openqa.suse.de/tests/11217050
=> Add new disk encryption tests

lib/virt_autotest/utils.pm, lib/virt_feature_test_base.pm, tests/virt_autotest/reboot_and_wait_up.pm, tests/virt_autotest/sriov_network_card_pci_passthrough.pm
- Fix a few failures in post_fail_hook which blocks consequent tests running after sriov tests. 
- publishing unit log failed due to no command history. In this case, [uefi-gi-guest_developing-on-host_sles12sp5-xen](https://openqa.suse.de/tests/11163170#) , guests were not restored after sriov failure which stopped consequent tests.  
- correct errors in uploading logs in post_fail_hook.
- stop SLE test going into ALP environment. fg. http://10.67.129.102/tests/634#step/sriov_network_card_pci_passthrough/461
- remove duplicate collecting virt logs from product tests as it has been uploaded in collect_host_and_guest_logs().
- remove Perl warnings in autoinst.txt, https://openqa.suse.de/tests/11181432/logfile?filename=autoinst-log.txt
```
Subroutine set_ssh_console_timeout_before_use …
```
=> Fix a few failures in post_fail_hook which make guests failed to be restored

lib/publiccloud/azure.pm
- Related ticket: #16886
When was the blob uploaded incorrectly, we need to overwrite it:
```
ErrorCode:BlobAlreadyExists
If you want to overwrite the existing one, please add --overwrite in your command.[0m
```
=> Public Cloud: Add -overwrite to azure::upload_img

tests/sles4sap/qesapdeployment/configure.pm
Set USE_SAPCONF=false to fix test case "qec2_sap_byos_qesap_saptune" test module "configure" error.   
The error message is "Could not retrieve required variable USE_SAPCONF" it was introduced by [PR#17176](https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/17176)
- Needles: NA
- Verification run (passed): [openqa.mypersonalinstance.de/tests/xyz#step/module/x
](https://openqa.suse.de/tests/11222535#details)
=> Set USE_SAPCONF=false to fix qesap_saptune failure

lib/LTP/utils.pm
The `TEST_SUITE_NAME` variable is always defined but when the job was defined in jobgroup YAML with `testsuite: null`, it will be empty. Check the actual job name to decide whether LTP jobs should use the default LTP package or the 32bit one.
- Needles: N/A
- ltp_math: https://openqa.suse.de/tests/11223299
- ltp_math_m32: https://openqa.suse.de/tests/11223300
=> Fix 32bit compat mode LTP test activation

tests/sles4sap/qesapdeployment/configure.pm
Enforce naming convention for settings used in qesap regression testing.
Verification
- http://openqaworker15.qa.suse.cz/tests/184653
- http://openqaworker15.qa.suse.cz/tests/185060
-  http://openqaworker15.qa.suse.cz/tests/185061
=> Change naming convention of qesap regression settings

lib/qam.pm, schedule/qam/common/qam-glibc-sle11.yaml, tests/kernel/update_kernel.pm
- Related ticket: https://progress.opensuse.org/issues/125606
https://openqa.suse.de/tests/overview?distri=sle&version=11-SP4&build=%3Atest%3A29128&groupid=485
https://openqa.suse.de/tests/overview?distri=sle&version=11-SP4&build=%3Atest%3A29130&groupid=485
https://dzedro.suse.cz/tests/1358#step/patch_and_reboot/19
https://dzedro.suse.cz/tests/1343 kernel_update 29128
https://dzedro.suse.cz/tests/1342 kernel_update 29130
=> Fix SLE11-SP4 Incidents

tests/transactional/enable_selinux.pm
This PR:
- Adds a test that SELinux can be enabled after being disabled on SLEM.
- Checks that SELinux is enabled on SLEM 15.4+
---
- Related ticket: https://progress.opensuse.org/issues/129394
- microos-Tumbleweed-MicroOS-Image-x86_64-Build20230531-microos@64bit -> https://openqa.opensuse.org/tests/3328840
- sle-micro-5.1-MicroOS-Image-Updates-x86_64-Build20230531-1-slem_selinux@64bit -> https://openqa.suse.de/tests/11229117 
- sle-micro-5.2-MicroOS-Image-Updates-x86_64-Build20230531-1-slem_selinux@64bit -> https://openqa.suse.de/tests/11229118 
- sle-micro-5.3-MicroOS-Image-Updates-x86_64-Build20230531-1-slem_selinux@64bit -> https://openqa.suse.de/tests/11229119
=> Test that SELinux can be enabled after being disabled on SLEM

lib/x11test.pm, tests/x11/gedit/gedit_launch.pm, tests/x11/gnote/gnote_first_run.pm, tests/x11/libreoffice/libreoffice_open_specified_file.pm
Change short cuts to close gnote to fix gnote failures
Ensure installed gedit before invoking
Use a stable way to close libreoffice document
Add a softfailure for TW due to bsc#1209179
- Related ticket: https://progress.opensuse.org/issues/126635
- Needles: already added when debugging on osd and o3
>  TW: 
[desktopapps-documentation](https://openqa.opensuse.org/tests/3328460#details)
> SLE: 
[wayland-desktopapps-documentation](https://openqa.suse.de/tests/11228632#details)
[x11-desktopapps-documentation](https://openqa.suse.de/tests/11228633#details)
=> Fix desktopapps-documentation failure on TW

lib/qam.pm
Right now the extra customer repos are only for x86_64, other architectures are failing as they can't add not existing repo
- Related ticket:  #17196
https://openqa.suse.de/tests/11234928 aarch64 jeos
https://openqa.suse.de/tests/11234920 aarch64 jeos
https://openqa.suse.de/tests/11234918 s390x sle
https://openqa.suse.de/tests/11234919 aarch64 sle
=> Add arch_only key for extra repos

lib/guest_installation_and_configuration_base.pm
"Could not resolve guest name" was found in unified guest installation tests too, https://openqa.suse.de/tests/11222650#step/unified_guest_installation/530. Similiar change is supposed to be applied to thoes tests.
Related ticket: https://progress.opensuse.org/issues/129544
[uefi-gi-guest_developing-on-host_sles12sp5-xen](https://openqa.suse.de/tests/11228540#)
[uefi-gi-guest_developing-on-host_sles12sp5-kvm](https://openqa.suse.de/tests/11228828#)
[uefi-gi-guest_developing-on-host_sles15sp4-xen](https://openqa.suse.de/tests/11228830#)
[uefi-gi-guest_developing-on-host_developing-kvm](https://openqa.suse.de/tests/11228827#)
[sev-es-gi-guest_developing-on-host_sles15sp4-kvm](https://openqa.suse.de/tests/11228878)
=> Fix dns resolve failure on sle12sp5 by moving testvirt.net forward in resov.conf

tests/sles4sap/monitoring_services.pm
Perl is perl, so sometimes, when a `script_run` function that is designed to return a port number fails, a number is extracted (and used) from the bogus response, instead of the predefined port number designed to be used in case of a lack of response.
This pr enables checks to make sure that the returned output is indeed a number instead of extracting a number from whatever it finds, and if not, uses the predefined number.
- Related ticket: https://jira.suse.com/browse/TEAM-7996
-- create hdd: https://openqa.suse.de/tests/11225141#
-- support server: https://openqa.suse.de/tests/11225142
-- node01: https://openqa.suse.de/tests/11225144
-- node02: https://openqa.suse.de/tests/11225143
=> Add check for correct port format in monitoring_services

data/virt_autotest/guest_params_xml_files/opensuse_tumbleweed_64_xen_hvm_x86_64.xml, data/virt_autotest/guest_params_xml_files/opensuse_tumbleweed_64_xen_pv_x86_64.xml, data/virt_autotest/guest_unattended_installation_files/opensuse_tumbleweed_xen_hvm_guest_x86_64.xml, data/virt_autotest/guest_unattended_installation_files/opensuse_tumbleweed_xen_pv_guest_x86_64.xml, data/virt_autotest/host_unattended_installation_files/autoyast_opensuse_xen_sshd.xml, lib/virt_autotest/utils.pm
In continuation to Autoyast profiles for the KVM host which has been done PR: #16625 and this PR is for XEN hosts.
This PR will 
1. support installing a host with autoyast profile for TumbleWeed.
2. Install guests with medium from O3 repo. 
- Related ticket: https://progress.opensuse.org/issues/128675
[GuestInstallationXEN](https://openqa.opensuse.org/tests/3318567)
[GuestInstallaionKVM](https://openqa.opensuse.org/tests/3323699) : PASSED
Latest Run [KVM](https://openqa.opensuse.org/tests/3330711#): PASSED
=> Autoyast profile for XEN Host with Install guest medium from O3 repo

data/yam/agama/auto/leap16.json, data/yam/agama/auto/leap16.sh
Automate auto-installation of openSUSE Leap 16.0 on Agama using json and shell format.
- Related ticket: https://progress.opensuse.org/issues/128186
- Needles: n/a
- https://openqa.opensuse.org/tests/3330797#
- https://openqa.opensuse.org/tests/3330796#
The installation is block by bsc#1211506
=> Automate auto-installation of openSUSE Leap 16.0 on Agama

tests/kernel/update_kernel.pm
The kernel-source-rt and kernel-devel-rt package minor versions can also differ from the corresponding kernel-rt package. Apply the same exception as for kernel-source.
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/11242896
=> update_kernel: Apply kernel-source version exception to RT packages

lib/publiccloud/provider.pm, tests/publiccloud/az_accelerated_net.pm, variables.md
The test module was not used for a while and needed to be updated
accordingly. Test suite creates 2 instances of type `Standard_D2_v4`
and measures network throuput using `iperf3`.
In order to install the package, we need to use opensuse repos or devel
repos in OBS as for SLE the `iperf` is provided by package hub and in
older versions only.
- ticket: [enable network performance test](https://progress.opensuse.org/issues/126224)
- Verification run: https://openqa.suse.de/tests/11242895#
=> Resurrect Azure Accelerated Network testing

tests/containers/podman_network_cni.pm
Fix for podman_network_cni,pm
- Verification run: https://openqa.suse.de/tests/11244260, https://openqa.suse.de/tests/11244261, https://openqa.suse.de/tests/11244262, https://openqa.suse.de/tests/11244263, https://openqa.suse.de/tests/11244265, https://openqa.suse.de/tests/11244267, https://openqa.suse.de/tests/11244268,   https://openqa.opensuse.org/tests/3331333
=> Fix for podman_network_cni

tests/openqa/osautoinst/test_running.pm
Note the echo preventing $ret from ever being effective.
See also https://progress.opensuse.org/issues/58007#note-4
See: https://progress.opensuse.org/issues/130201
=> test_running: Fail test if no openQA jobs are running

lib/main_containers.pm
Due to missing package, skip schedule of `podman_netavark` test module on `ppc64` architecture.
- ticket: [podman_netavark: package does not exist on ppc64le](https://progress.opensuse.org/issues/130255)
- Verification run: https://openqa.opensuse.org/tests/3336695#
=> Skip netavark testing on ppc64le

tests/microos/toolbox.pm
Toolbox test run: Do not delete the testapi user, unless it has been created within the test run.
- Related ticket: https://progress.opensuse.org/issues/130141
- Verification run: [SLEM 5.4 on Azure](https://duck-norris.qe.suse.de/tests/12939) | [SLEM 5.4](https://duck-norris.qe.suse.de/tests/12952) | [SLEM 5.3](https://duck-norris.qe.suse.de/tests/12953) | [SLEM 5.2](https://duck-norris.qe.suse.de/tests/12950) | [SLEM 5.1](https://duck-norris.qe.suse.de/tests/12949) | [MicroOS](https://duck-norris.qe.suse.de/tests/12948)
=> Do not remove testuser if not created

lib/apparmortest.pm
- Related ticket: https://progress.opensuse.org/issues/129044
- https://openqa.suse.de/tests/11255114#step/apache2_changehat/113
- https://openqa.suse.de/tests/11255132#step/apache2_changehat/113
=> Use needle to click on save password as aarch64 misses shortcut keypress

lib/trento.pm, t/08_trento.t, tests/sles4sap/trento/test_hana_restore_stopped.pm, tests/sles4sap/trento/test_hana_stop.pm, tests/sles4sap/trento/test_hana_unregister_node.pm, tests/sles4sap/trento/test_trento_web.pm
Change cypress_exec implementation not to wait the cypress execution using the script_run and its timeout mechanism.
Run it detached and poll the status using podman ps. Add a couple of podman utility functions
Add unit testing
This PR  is about a new idea to avoid "uncontrolled" podman termination due to script_run  timeout. 
The idea is to use `podman run ... cypress`  without `-it` and using `enter_cmd`.
Then polling the status with `podman ps`  and eventually gently kill cypress within the container in case of a too long execution
Related ticket: [TRNT-921](https://jira.suse.com/browse/TRNT-921)
- http://openqaworker15.qa.suse.cz/tests/185510
=> Run Cypress in a detached container

lib/virt_autotest/common.pm
poo# https://progress.opensuse.org/issues/129985
SUSE Linux Enterprise Server 15 has exceeded its long-term support (LTSS) end date of December 31, 2022. This means that it is no longer receiving official support or updates from SUSE.
So it is unnecessary to test it again.
- Related ticket: https://progress.opensuse.org/issues/129985
- Needles: N/A
- Verification run:[XEN test]( http://openqa.qam.suse.cz/tests/54270), [KVM test](http://openqa.qam.suse.cz/tests/54100)
=> Remove LTSS ends sles15

tests/console/gpg.pm
libgcrypt20-hmac has been merged into libgcrypt20 and can thus only
be verified using rpm -q --whatprovides libgcrypt20-hmac
for the test it is not important if the package exists as a separate
entity or is merged into the main package, we care for the functionality
being present.
- Related ticket: https://progress.opensuse.org/issues/130036
- Needles: N/A
- Verification run: [MicroOS](https://openqa.opensuse.org/tests/3337480) (openssl-fips-hash is unrelated and fails in all tests at the moment)
=> gpg: consider packages providing merged cabapilities

tests/publiccloud/az_accelerated_net.pm
`ethtool` is required for Accelerated network testing in Azure provider.
- Verification run: https://openqa.suse.de/tests/11261785#
=> Azure CHOST image is missing ethtool

lib/services/sshd.pm
- Related ticket: https://progress.opensuse.org/issues/130240
- Needles: N/A
- Verification run: https://openqa.opensuse.org/tests/3340449
=> sshd: do not quote parameters passing to the ssh server

lib/hacluster.pm
hb_report (at least the current script) is actually a script that calls crm report.
Fixes TEAM-5563
VR:
15SP5:
https://openqa.suse.de/tests/11263915
https://openqa.suse.de/tests/11263916
https://openqa.suse.de/tests/11263917
12SP4:
https://openqa.suse.de/tests/11263920
https://openqa.suse.de/tests/11263921
https://openqa.suse.de/tests/11263919
=> Replace hb_report with crm report 

data/publiccloud/venv/ec2uploadimg.txt
Update the required version of ec2imgutils to 10.0.2.
- Related ticket: https://progress.opensuse.org/issues/129397
- Verification run: https://duck-norris.qe.suse.de/tests/12972#step/prepare_tools/111
=> Update ec2imgutils version

lib/containers/common.pm
As described in https://bugzilla.suse.com/show_bug.cgi?id=1178214 search command was not working properly on oS/SUSE registries. This has been fixed meanwhile, therefore we do not need this softfailure anymore.
- Related ticket: https://progress.opensuse.org/issues/77035
* [sle-15-SP5-Server-DVD-Updates-x86_64-Build20230605-1-podman_tests@64bit](http://kepler.suse.cz/tests/21017#step/podman/373)
* [sle15sp5-docker](http://kepler.suse.cz/tests/21016#step/docker/378)
* [sle-15-SP3-Server-DVD-Updates-x86_64-Build20230606-1-podman_tests@64bit](http://kepler.suse.cz/tests/21015#step/podman/394)
* [sle-15-SP3-Server-DVD-Updates-x86_64-Build20230606-1-docker_tests@64bit](http://kepler.suse.cz/tests/21021#step/docker/384)
* [sle-15-SP3-Server-DVD-Updates-x86_64-Build20230606-1-podman_tests@64bit]( …
=> Remove search softfail on our registries

tests/transactional/enable_selinux.pm
Adds a softfailure for bsc#1211917 until it is resolved.
- Related ticket: https://progress.opensuse.org/issues/110791
- Verification run: [SLEM 5.4](https://duck-norris.qe.suse.de/tests/12969#step/enable_selinux/6) | [SLEM 5.3](https://duck-norris.qe.suse.de/tests/12973#) | [SLEM 5.2](https://duck-norris.qe.suse.de/tests/12974#) | [SLEM 5.1](https://duck-norris.qe.suse.de/tests/12975#) - fails due to [poo#130507](https://progress.opensuse.org/issues/130507)
=> Add softfailure for bsc#1211917

data/sles4sap/qe_sap_deployment/sles4sap_azure_generic_maintenance.yaml, tests/sles4sap/publiccloud/add_server_to_hosts.pm, tests/sles4sap/publiccloud/cluster_add_repos.pm, tests/sles4sap/publiccloud/general_patch_and_reboot.pm, tests/sles4sap/publiccloud/hana_sr_schedule_deployment.pm
This pr is adding the necessary maintenance-specific code, fixes previous errors and is enabling the `SAPHanaSR-ScaleUp-PerfOpt` jobs for maintenance. Scheduling changes needed on Gitlab.
**NOTE**: `patch_and_reboot` module causes problems, and is to be tackled in another ticket (https://jira.suse.com/browse/TEAM-8035), so it's ommited.
- Related ticket: https://jira.suse.com/browse/TEAM-7535
**SAPHanaSR-ScaleUp-PerfOpt**: https://openqaworker15.qa.suse.cz/tests/186747
**mr_test** (modules used in that were changed): http://openqaworker15.qa.suse.cz/tests/186350
Scheduling gitlab mr: https://gitlab.suse.de/qa-css/openqa_ha_sap/-/merge_requests/462
=> Add code for hanasr scaleup maintenance jobs

lib/main_micro_alp.pm, schedule/qam/common/mau-extratests2.yaml, tests/console/year_2038_detection.pm
https://progress.opensuse.org/issues/129139
At the same time, add the test in sle15-sp5 qem
[zvm](https://openqa.suse.de/tests/11255202#next_previous)
[tw](https://openqa.opensuse.org/tests/3340000#next_previous)
[sle](https://openqa.suse.de/tests/overview?&build=rfan0606)
[micro-os](https://openqa.opensuse.org/tests/3339989)
=> Fix boot timeout and NTP sync issues for year_2038_detection

lib/Mitigation.pm
Explicitly print output of each case execution process, which help to trace case running flow 
Enhance xml log, which add more useful info to log especially on failed case, like expected out, unexpected out, actual out, data
-Related ticket: https://progress.opensuse.org/issues/73828?issue_count=126&issue_position=115&next_issue_id=73804&prev_issue_id=73840
- Verification run: http://10.67.129.7/tests/2102#
=> Add debug info for test cases

lib/opensusebasetest.pm
We have workaround the situation when no bounce back happened on powerkvm, but it is not work when online_migration_setup loaded after bootloader module. Because when showed 'display manager' but test still used wait_boot -> boot_local_disk which will match from the point of bootloader. 
We need ensure if no bounce back happend it won't go back to grub2 for the test process, and go ahead, that handle_grub shouldn't be called anymore after dispaly-mananger selected in bootloader module.
- Related ticket: https://progress.opensuse.org/issues/129649
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/11175598#step/online_migration_setup/1
VR to avoid regression: http://openqa.suse.de/tests/11181404
=> Deal with no bounce back on powerKVM

tests/installation/opensuse_welcome.pm
plasmashell crashed and openSUSE theme is not fully applied
Relaunch plasmashell to fix the theme
- Related ticket: https://bugzilla.suse.com/show_bug.cgi?id=1211628
- Needles: https://github.com/os-autoinst/os-autoinst-needles-opensuse/commit/bd6156b9c06ecf49be556c8995f2d55d22d3ba72
- Verification run: https://openqa.opensuse.org/tests/3345638
=> Workaround for boo#1211628

tests/microos/patterns.pm
Increase the timeout to 10 minutes for package installation due to timeout failures in aarch64 test runs.
- Related ticket: https://progress.opensuse.org/issues/130546
- Verification run: https://duck-norris.qe.suse.de/tests/12994#step/patterns/67
=> Increase timeout for pattern installation

tests/shutdown/svirt_upload_assets.pm
Use writeback to fast qemu-img convert
- Related ticket:  https://progress.opensuse.org/issues/125804
- Needles: N/A
- Verification run:   [**svirt_upload_assets**](https://openqa.suse.de/tests/overview?distri=sle&version=15-SP5&build=hjluo%2Fos-autoinst-distri-opensuse%23svirt_upload)
=> Use writeback to fast qemu-img convert

lib/registration.pm
- ticket: [docker_tests fails in docker_compose](https://progress.opensuse.org/issues/130537)
```
2023-06-08 01:25:25 <5> susetest(19903) [zypp-core]
Exception.cc(log):186 FileChecker.cc(operator()):135 THROW:    Signature
verification failed for repomd.xml
2023-06-08 01:25:25 <5> susetest(19903) [zypp-core]
Exception.cc(log):186 Fetcher.cc(provideToDest):571 RETHROW:  Signature
verification failed for repomd.xml
2023-06-08 01:25:25 <5> susetest(19903) [zypp-core]
Exception.cc(log):186 RepoManager.cc(refreshMetadata):1263 CAUGHT:
Signature verification failed for repomd.xml
2023-06-08 01:25:25 <5> susetest(19903) [zypp-core]
Exception.cc(log):186 RepoManager.cc(refreshMetadata):1277 THROW:
[SUSE_Package_Hub_15_SP5_s390x:SUSE-PackageHub-15-SP5-Backports-Pool|https://updates.suse.com/SUSE/Ba …
```
=> Import phub keys while registration

lib/registration.pm
Introduced in 69f78a887fec69a5b2ca1a5ff90951984725efd0, add version checking as not all version of SUSEConnect has key import feature.
VR:
- [15sp1](http://kepler.suse.cz/tests/21061#step/add_phub_extension/6)
- [15sp5](http://kepler.suse.cz/tests/21062#step/add_phub_extension/7)
=> Hotfix for phub key workaround

data/kiwi/appliance.kiwi, data/kiwi/config.sh, schedule/qam/15-SP4/kiwi_build_local_img.yaml, schedule/qam/15-SP4/kiwi_validate_local_img.yaml, tests/kiwi_images_test/kiwi_build_image.pm, tests/kiwi_images_test/validate_local_kiwi_image.pm
- Related ticket: https://progress.opensuse.org/issues/125657
- Needles: NO
- Verification run: [Kiwi_build_image](http://deepthi-openqa.qe.suse.de/tests/5202#) | [boot_kiwi_image](http://deepthi-openqa.qe.suse.de/tests/5203#)
Latest VRs: 
[Kiwi_build_image](http://deepthi-openqa.qe.suse.de/tests/5244) | [boot_kiwi_image](http://deepthi-openqa.qe.suse.de/tests/5245)
=> Introduce Kiwi tests to build image locally

tests/console/sudo.pm
As per https://bugzilla.suse.com/show_bug.cgi?id=1205325#c29 sudo is configured on Azure images to ask for invoking user's password instead of target's user password. This change will eventually hit all supported Azure images.
- ticket: [publiccloud_consoletests fail in sudo](https://progress.opensuse.org/issues/130432)
* [sle-12-SP5-AZURE-Standard-Updates-x86_64-Build20230607-1-publiccloud_consoletests@64bit](http://kepler.suse.cz/tests/21060#step/sudo/16)
* [sle-15-SP4-AZURE-BYOS-Updates-x86_64-Build20230607-1-publiccloud_consoletests@64bit](http://kepler.suse.cz/tests/21059#step/sudo/16)
* [sle-15-SP5-Azure-BYOS-x86_64-Build0333-publiccloud_consoletests@az_Standard_B2s](http://kepler.suse.cz/tests/21058#step/sudo/16)
=> sudo asks for invoking user's password on Azure

data/virt_autotest/host_unattended_installation_files/autoyast/dev_host_15.xml.ep, products/sle/main.pm, tests/virt_autotest/libvirt_extend_storage_lvm.pm
Create a autoyast template for sles15spx in order for product virtuallzation test to switch from GUI installation to autoyast
https://progress.opensuse.org/issues/112508
- Related ticket: https://progress.opensuse.org/issues/112508
- Needles: no
- sle15sp5 xen AMD: http://10.67.183.130/tests/3493
- sle15sp5 kvm: http://10.67.183.130/tests/3492
- sle15sp4 kvm: http://10.67.183.130/tests/3505#
- gi-guest_developing-on-host_developing-kvm: https://openqa.suse.de/tests/11130833
- uefi-gi-guest_developing-on-host_developing-xen: https://openqa.suse.de/tests/11132392 
- gi-guest_sles15sp4-on-host_developing-kvm: https://openqa.suse.de/tests/11132406
- prj2_host_upgrade_sles15sp4_to_developing_xen: https://openqa.suse.de/tests/11132409
- …
=> Replace GUI host installation with autoyast for sle15

tests/console/dpdk.pm
we have different package name for dpdk and openvswitch for openSUSE so dpdk test failed.
see https://progress.opensuse.org/issues/130498
VRs:
http://10.161.8.50/tests/163#step/dpdk (Leap)
http://10.161.8.50/tests/161#step/dpdk (Tumbleweed)
=> Fix dpdk module for openSUSE

tests/sles4sap/publiccloud/cluster_add_repos.pm
Tests fail in `cluster_add_repos`, seemingly because even though only the hana nodes are amended with the test repository and the iscsi server is excluded, it is not excluded in the next loop which `zypper ref`s. That leads to a crash due to no repositories existing in the server.
- Related ticket: https://jira.suse.com/browse/TEAM-7535
=> Fix small iscsi server mistake

lib/yam/agama/patch_agama_base.pm, schedule/yam/agama/agama_installation.yaml, tests/yam/agama/patch_agama.pm, variables.md
Integrate yupdate script in openQA in order to get e2e playwright tests from a different repo
- Related ticket: https://progress.opensuse.org/issues/130000
- Needles: na
- Verification run: https://openqa.opensuse.org/tests/3346380
=> Integrate yupdate script in openQA in order to get e2e playwright tests from a different repo

tests/sles4sap/qesapdeployment/destroy.pm
Fix terraform destroy sporadic timed out failure via increasing the time out value to 1800 seconds though generally the destroy will be finished in 1200 minutes
I hit this sporadic timed out issue (http://openqaworker15.qa.suse.cz/tests/187769#step/destroy/22) when I am working on this ticket [TEAM-8002](https://jira.suse.com/browse/TEAM-8002) - [OW15] qesap regression test on Azure using 12-SP5 BYOS images (PAYG done)
You can see test module "destroy" took 20+ minutes and exited with timed out.
- Related ticket: https://jira.suse.com/browse/TEAM-8002
- Needles: NA
http://openqaworker15.qa.suse.cz/tests/188230# (passed)
=> Fix terraform destroy sporadic timed out failure

tests/kernel/wmp_simple.pm
Using a custom repo on obs will always result in maintenance work, so let's better use packagehub instead of something else for obtaining stress-ng
=> Replace custom repo with packagehub

lib/qesapdeployment.pm, lib/sles4sap_publiccloud_basetest.pm, t/09_qesapdeployment.t
Add peering destruction to the `clenup` function of `sles4sap_publiccloud_basetest`.
Part of the https://jira.suse.com/browse/TEAM-7535 saga.
- Related ticket: https://jira.suse.com/browse/TEAM-7535
FAILING: http://openqaworker15.qa.suse.cz/tests/188749
PASSING: http://openqaworker15.qa.suse.cz/tests/188748 (well, should be passing but there's an unrelated registration error)
NO PEERING: http://openqaworker15.qa.suse.cz/tests/188747
=> Add peering cleanup in base module

lib/y2_installbase.pm, lib/y2_logs_helper.pm
Handle vendor change issues in automation for migration cases that with PackageHub installed.
- Related ticket: https://progress.opensuse.org/issues/128123
- Needles: N/A
http://openqa.suse.de/tests/11215806#step/resolve_dependency_issues/23   # powerVM
http://openqa.suse.de/tests/11215804#step/resolve_dependency_issues/23   # x86_64
=> Handle vendor change issues in automation for migration cases that with PackageHub installed

data/sles4sap/qe_sap_deployment/qesap_azure_no_reg.yaml, data/sles4sap/qe_sap_deployment/qesap_azure_sapconf_no_reg.yaml, tests/sles4sap/qesapdeployment/configure.pm, tests/sles4sap/qesapdeployment/test_cluster.pm
Add some more steps in the test module, about zypper. Add a config.yaml Azure template that is not calling the Ansible registration playbook.
- Related ticket: [TEAM-8059](https://jira.suse.com/browse/TEAM-8059)
AZURE BYOS http://openqaworker15.qa.suse.cz/tests/188257  http://openqaworker15.qa.suse.cz/tests/188261 :heavy_check_mark: 
AZURE PAYG SAPTUNE
- http://openqaworker15.qa.suse.cz/tests/188259  "No provider of '+saptune>=3.0' found." :red_circle: 
-  http://openqaworker15.qa.suse.cz/tests/188260 "No provider of '+saptune>=3.0' found." :red_circle: 
AZURE PAYG SAPCONF 
- http://openqaworker15.qa.suse.cz/tests/188263  : Could not find the requested service sbd: host :red_circle: 
- http://openqaworker15.qa.suse.cz/tests/188266 : Could not find the requested service …
=> Add PAYG support for qesap regression

data/virt_autotest/guest_unattended_installation_files/opensuse_tumbleweed_kvm_hvm_guest_x86_64.xml, data/virt_autotest/guest_unattended_installation_files/opensuse_tumbleweed_xen_hvm_guest_x86_64.xml, data/virt_autotest/guest_unattended_installation_files/opensuse_tumbleweed_xen_pv_guest_x86_64.xml, data/virt_autotest/guest_unattended_installation_files/slem_5_plus_kvm_hvm_guest_graphical_x86_64.xml, data/virt_autotest/guest_unattended_installation_files/sles_12_plus_kvm_hvm_guest_graphical_x86_64.xml, data/virt_autotest/guest_unattended_installation_files/sles_12_plus_kvm_hvm_guest_multi-user_x86_64.xml, data/virt_autotest/guest_unattended_installation_files/sles_12_plus_xen_hvm_guest_graphical_x86_64.xml, data/virt_autotest/guest_unattended_installation_files/sles_12_plus_xen_hvm_guest_multi-user_x86_64.xml, data/virt_autotest/guest_unattended_installation_files/sles_12_plus_xen_paravirt_guest_graphical_x86_64.xml, data/virt_autotest/guest_unattended_installation_files/sles_12_plus_xen_paravirt_guest_multi-user_x86_64.xml, data/virt_autotest/guest_unattended_installation_files/sles_15_plus_kvm_hvm_guest_graphical_x86_64.xml, data/virt_autotest/guest_unattended_installation_files/sles_15_plus_kvm_hvm_guest_multi-user_x86_64.xml, data/virt_autotest/guest_unattended_installation_files/sles_15_plus_xen_hvm_guest_graphical_x86_64.xml, data/virt_autotest/guest_unattended_installation_files/sles_15_plus_xen_hvm_guest_multi-user_x86_64.xml, data/virt_autotest/guest_unattended_installation_files/sles_15_plus_xen_paravirt_guest_graphical_x86_64.xml, data/virt_autotest/guest_unattended_installation_files/sles_15_plus_xen_paravirt_guest_multi-user_x86_64.xml, data/virt_autotest/host_unattended_installation_files/autoyast_opensuse_kvm_sshd.xml, data/virt_autotest/host_unattended_installation_files/autoyast_opensuse_xen_sshd.xml, lib/concurrent_guest_installations.pm, tests/installation/ipxe_install.pm, tests/virt_autotest/login_console.pm
1. type key again to ensure to enter the particular ipxe entry.
2.  reduce timeout of grub2 menu of guest to prevent recieving keys from outside accidently
3.  decrease host installation time(ipxe_install + autoyast_install + login_console) from 30 min to 20 min by optimizing some needle matching
4. stop guest installation when dry run failed. (it will be droppend when the PR is ready to merge)
5. remove `<hiddenmenu>` attribute as it is not found in TW/SLE15SP4/SLE12SP5 autoyast guide.
6. deactivate the 2nd network interface to avoid networking issues
7. add udev rule to make br0 have same MAC with em1 to be able to get an IP from dhcp server
Related ticket: 
https://progress.opensuse.org/issues/130108
https://progress.opensuse.org/issues/130111
// item 1 is not …
=> Make TW test more stable and faster

tests/jeos/firstrun.pm
This PR adds more tests to `jeos-firstrun`:
- Check valid output for `systemd-detect-virt`
- Check that no repos are defined.
- Check 3 bsc's.
Related ticket: https://progress.opensuse.org/issues/57665
- opensuse-Tumbleweed-JeOS-for-AArch64-aarch64-Build20230604-jeos@aarch64-HD20G -> https://openqa.opensuse.org/tests/3357429
- opensuse-Tumbleweed-JeOS-for-kvm-and-xen-x86_64-Build20230611-jeos@uefi_virtio-2G -> https://openqa.opensuse.org/tests/3354945
- sle-12-SP5-JeOS-for-kvm-and-xen-Updates-x86_64-Build20230612-1-jeos-main@64bit-virtio-vga -> https://openqa.suse.de/tests/11329480
- sle-15-SP1-JeOS-for-kvm-and-xen-Updates-x86_64-Build20230612-1-jeos-main@uefi-virtio-vga -> https://openqa.suse.de/tests/11329377
- …
=> jeos: Add more tests

lib/publiccloud/instance.pm, lib/publiccloud/provider.pm, tests/publiccloud/ahb.pm, tests/publiccloud/boottime.pm, tests/publiccloud/img_proof.pm, tests/publiccloud/prepare_instance.pm, tests/publiccloud/run_ltp.pm, tests/publiccloud/storage_perf.pm
Being the `wait_for_guestregister` routine no-more-operational and replaced by the new `wait_for_guestregister_chk`, as explained in its (removed)  _head2_, in this cleanup all related calls have been removed where existing in Public cloud modules and the new routine has been then renamed as the original name `wait_for_guestregister`, in place. 
This PR is a followup of previous merged PR#16577.
- Related ticket: https://progress.opensuse.org/issues/118027
- Needles: N/A
- Verification run: TBD see next posts.
=>  wait_for_guestregister external calls removed

data/virt_autotest/host_unattended_installation_files/autoyast/dev_host_15.xml.ep
Add a missing comma in
data/virt_autotest/host_unattended_installation_files/autoyast/dev_host_15.xml.ep
- Related ticket: https://progress.opensuse.org/issues/130913
- Needles: no
- Verification run:   http://10.67.183.130/tests/3653
=> Add a missing comma in dev_host_15.xml.ep

schedule/migration/migration_offline_media_x86_64.yaml, schedule/migration/migration_offline_scc_x86_64.yaml, tests/migration/SUSEConnect_register_system.pm, tests/migration/deregister_system.pm, tests/migration/drop_unavailable_product_modules.pm, tests/migration/install_patterns.pm, tests/migration/patch_and_reboot_system.pm, tests/migration/setup_sle.pm
Too many functions are integrated in patch_sle test module. To make it clear to understand the steps, split it to several test modules based on the steps: migration_setup; register_origin_system; patch_system; remove_dropped_modules; deregistration_system.
- Related ticket: https://progress.opensuse.org/issues/125594
- Needles: n/a
- https://openqa.suse.de/tests/11313896
- https://openqa.suse.de/tests/11313897
- Related MR: https://gitlab.suse.de/coolgw/wegao-test/-/merge_requests/284
=> Split patch_sle to several modules

schedule/security/encryption/lvm_encrypt_separate_boot.yaml, schedule/security/encryption/lvm_encrypt_separate_boot_s390x.yaml
Changing `DESKTOP` from `gnome` to `textmode` in encrypted installation tests and removing unused modules.
This should be merged in parallel with changes in our security job groups.
- Related ticket: https://progress.opensuse.org/issues/130898
- x86_64: https://openqa.suse.de/tests/11358606
- aarch64: https://openqa.suse.de/tests/11360835
- s390x: https://openqa.suse.de/tests/11360845
=> FIPS encrypted install tests optimizations

tests/jeos/firstrun.pm
Fix detection of Xen hosts
- Related ticket: https://progress.opensuse.org/issues/130958
- Failing test: https://openqa.suse.de/tests/11350628#step/firstrun/61
- Verification run: https://openqa.suse.de/tests/11361279
=> jeos: Fix detection of Xen hosts

tests/jeos/firstrun.pm
Fixes #17257 when generalhw back is used.
- Verification run: https://openqa.opensuse.org/tests/3360908
=> jeos: do not verify_hypervisor on generalhw

schedule/alp/yast_as_workload.yaml
Enable automation for YaST in Container in ALP in OSD
- Related ticket: https://progress.opensuse.org/issues/130384
- Verification run: https://openqa.suse.de/tests/overview?distri=alp&version=1.0&build=4.1&groupid=496
- MR: https://gitlab.suse.de/qsf-y/qa-sle-functional-y/-/merge_requests/509
=> Enable automation for YaST in Container in ALP in OSD

data/filesystem/autoyast_filesystem_withouthome_yast.xml.ep
Enable updates for autoyast_filesystem_withouthome_yast in Maintenance Updates
- Related ticket: https://progress.opensuse.org/issues/129217
- Verification run: https://openqa.suse.de/tests/11355470#
=> Enable updates for autoyast_filesystem_withouthome_yast in Maintenance Updates

tests/console/journalctl.pm
we have sporadic issue with journalctl on Tumbleweed. One possible reason is performance. So increase re-tries for script_retry and check wether this is enough to make the test stabile.
see https://progress.opensuse.org/issues/129304
=> Give more tries for script_retry for journalctl module

tests/installation/await_install.pm
Looks like timeout is not enough for some aarch4 installations. Try a new increased number.
- Verification run: https://openqa.suse.de/tests/11377148
=> Increase default timeout of await_install

lib/registration.pm
Phub key fix has been provided, finally we can revert the previous changes introduced in (PR #17244).
VR: http://kepler.suse.cz/tests/21071#step/docker_compose/7
=> revert gpg keys import for phub

schedule/yast/encryption/activate_encrypted_volume+import_users_pvm.yaml, schedule/yast/lvm/lvm+cancel_existing_cryptlvm_pvm.yaml, schedule/yast/sle/guided_xfs/guided_xfs_pvm.yaml
Fix some glitches for yast ppc64le default yaml afer PR [**17075**](https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/17075/) was merged.
- Related ticket: [**127409**](https://progress.opensuse.org/issues/127490)
- Related MR: [**511**](https://gitlab.suse.de/qsf-y/qa-sle-functional-y/-/merge_requests/511)
- Needles: N/A
- Verification run: [**ppc64le_spvm**](https://openqa.suse.de/tests/overview?distri=sle&version=15-SP5&build=102.1&groupid=318)
=> Fix some glitches for yast ppc64le default yaml

lib/publiccloud/utils.pm
`kill_packagekitd()` fails on Azure without root privileges.
- Related ticket: https://progress.opensuse.org/issues/131105
- Failing test: https://openqa.suse.de/tests/11388077#step/patch_and_reboot/19
- Verification run: https://openqa.suse.de/tests/11389656
=> pc: Make sure kill_packagekitd runs as root

schedule/functional/sway.yaml, tests/sway/sway.pm
This should just be enough to catch the Mesa issue reported here: https://bugzilla.suse.com/show_bug.cgi?id=1212345
I can't create the required needle(s) yet because the active TW image still seems to have the above issue.
Example job group YAML to schedule it.
```yaml
defaults:
x86_64:
machine: 64bit
priority: 50
products:
sle-15-sp5:
distri: sle
flavor: Online
version: 15-SP5
opensuse-Tumbleweed-DVD-x86_64:
distri: opensuse
flavor: DVD
version: Tumbleweed
scenarios:
x86_64:
opensuse-Tumbleweed-DVD-x86_64:
- sway:
testsuite: null
settings:
BOOT_HDD_IMAGE: "1"
VIDEOMODE: text
DESKTOP: textmode
HDD_1: "%DISTRI%-%VERSION%-%ARCH%-%BUILD%-%DESKTOP%@%MACHINE%.qcow2"
UEFI_PFLASH_VARS: "%DISTRI%-%VERSION%-%ARCH%-%BUILD%-%DESKTOP%@%MACHINE%-uefi-vars.qcow2"
QEMU_VIDEO_DEVICE: virtio-vga …
```
=> Add basic Sway WM test

lib/publiccloud/instance.pm, tests/publiccloud/prepare_instance.pm, variables.md
P.C. module `prepare_instance` updated to allow check for system up to _retry_ in case of _publickey_ or _unknown_ errors in `wait_for_ssh`
- Related ticket: https://progress.opensuse.org/issues/130444
- Needles: No change
- Verification run: see next posts
=> prepare_instance updated to retry on error in wait_for_ssh

tests/x11/seahorse_sshkey.pm
openQA logs revelaed that 3 seconds is often too short for this dialog to appear and then the button to be clicked.
6 seconds seems to be enough for this test to pass.
Commit fixes poo#130150
- Related ticket: https://progress.opensuse.org/issues/130150
=> Doubling the timeout for seahorse-sshkey-inhibit.

tests/console/sssd_openldap_functional.pm
- Related ticket: https://progress.opensuse.org/issues/130919
Unable to test properly, as with the change it fails in a different way:
https://openqa.suse.de/tests/11396340#step/sssd_openldap_functional/93
..which is also how it fails with openqa-clone-custom-git-refspec pointing to a repository which does not have a change to the test
https://openqa.suse.de/tests/11396848#step/sssd_openldap_functional/93
So currently not sure how to properly rerun it, but regardless it has been reported that 15-sp3 containers will no longer be available so a switch to 15-SP4 should be done.
=> Use 15-SP4 as base container as suggested in bsc#1212429

data/autoyast_sle15/create_hdd/create_hdd_gnome_sdk_allpatterns_s390x.xml, lib/registration.pm, tests/autoyast/installation.pm
See https://progress.opensuse.org/issues/124922
- Added autoyast profile 
- updated subroutine for deregistration, removed outdated workaround and
added one.
- increased timeout in autoyast installation for s390, as it takes more
time to start all the services we activate in the new autoyast
profile.
VR https://openqa.suse.de/tests/11360003
children jobs https://openqa.suse.de/tests/11361616 https://openqa.suse.de/tests/11361617
MR
https://gitlab.suse.de/qa-maintenance/qam-openqa-yml/-/merge_requests/548
https://gitlab.suse.de/coolgw/wegao-test/-/merge_requests/303
=> Create autoyast installation for sle15 sp3 sdk

tests/installation/bootloader_svirt.pm
https://progress.opensuse.org/issues/126647
- Verification run: https://openqa.suse.de/tests/11395040#
=> Don't use default iface 'ovs-system' on xen setup

tests/transactional/host_config.pm
Extends https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/17263
- Related failure: https://openqa.suse.de/tests/11406695#step/install_ltp/45
- Verification run: http://10.100.12.105/tests/78#step/host_config/32
=> alp: Add source build repository configuration

data/elemental/cloud-config.yaml, products/elemental, schedule/elemental/iso.yaml, tests/elemental/installation.pm, tests/elemental/shutdown.pm
This PR adds a basic installation test for Elemental ISO.
Elemental is a very small OS based on SLEM for Rancher intended to be used with Rancher Manager to provision edge cluster. See [Elemental docs](https://elemental.docs.rancher.com) for more information.
This test will be used mainly by QAM to validate SLEM fixes pushed to Elemental image. More complete E2E tests are done in the [Elemental GitHub project](https://github.com/rancher/elemental).
- Needles: https://gitlab.suse.de/openqa/os-autoinst-needles-sles/-/merge_requests/1641
- Add new product in OBS: https://gitlab.suse.de/openqa/openqa-trigger-from-ibs-plugin/-/merge_requests/128 and https://gitlab.suse.de/openqa/salt-states-openqa/-/merge_requests/868
- Job Group definition: …
=> Add basic installation test for Elemental

data/sles4sap/qe_sap_deployment/mr_test_azure.yaml, lib/trento.pm, tests/sles4sap/publiccloud/qesap_terraform.pm
Add VNET_ADDRESS_RANGE and SUBNET_ADDRESS_RANGE to the qesap config used in mr_tests that does not need network peering to IBS. Change the test module to populate these settings only for Azure tests and not only for IS_MAINTENANCE tests. This is a double step: 1. remove an `if` test that in any case will break when extending the test to AWS, 2. Implement slot IPs also for tests that does not need to perform net peering, it is useless but also harmless.
Related ticket: TEAM-7487 as follow up of https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/17020/files
- mr_test with 15sp5 image from IBS (_uri config) https://openqa.suse.de/tests/11406964 https://openqa.suse.de/tests/11407265
- mr_test maintenance http://openqaworker15.qa.suse.cz/tests/192293
=> Change mr_test_azure config to be more generic

tests/security/cc/filter.pm
This prevents the openqa_review bot from reopening [poo#116683](https://progress.opensuse.org/issues/116683), since the issue will not be fixed upstream.
=> Set WONTFIX to soft failure in cc tests on 15-SP3

lib/hacluster.pm, t/11_hacluster.t
SAP/HA tests are currently failing because of kernel messages creeping into 
'script_output' output. This PR adds "script_output_retry_check" subroutine 
which checks result against expected regex and retries command couple of times 
upon failure. 
- Related ticket: https://jira.suse.com/browse/TEAM-8076
- Needles: N/A
Replicated issue: https://openqa.suse.de/tests/11406510#step/check_after_reboot/31
Issue did not occur: http://openqa.suse.de/tests/11406907#step/check_after_reboot/31
=> Retry script_output with sanity check

lib/sles4sap_publiccloud_basetest.pm, tests/sles4sap/publiccloud/general_patch_and_reboot.pm, tests/sles4sap/publiccloud/hana_sr_schedule_deployment.pm
This solves the problem of `qesap_ansible` failing if `patch_and_reboot` runs before it.
The problem was in the ssh settings: `patch_and_reboot` runs a couple of commands via ssh on the node, and due to the ssh settings and some problem this created a multiplexed ssh connection that broke after the command was executed, leaving a stale ssh socket file behind. Later, ansible ssh command tried to re-use that socket file which lead to failure.
Adding `-o ControlMaster=no` to the ssh command in `patch_and_reboot` disables the ssh multiplexing for that command, which leads to the job succeeding.
- Related ticket: https://jira.suse.com/browse/TEAM-8035
- Verification run: http://openqaworker15.qa.suse.cz/tests/193006
=> Patch and Reboot for Maintenance hanasr jobs

tests/network/autofs_client.pm
https://progress.opensuse.org/issues/131291
At the same time, remove a mutex lock which is not required.
[autofs](https://openqa.suse.de/tests/11437911#dependencies)
=> Add retries on autofs client to sync data with server

tests/hpc/ww4_await_pxe_install.pm
Fix poo#131207: We were trying to enter PXE console by CTRL+B during system boot, but it was not reliable on heavy loaded workers. PXE needle was usually missed and system booted to attached ISO image. This change will solve boot issues. Node will just wait after failed boot. When is controller configuration done, we will continue on compute node by reset(send key comination CTRL-ALT-DELETE). Node will boot via PXE without issue. Test suite settings must not contain HDD_1 or ISO variable to avoid booting from them.
- Related ticket: https://progress.opensuse.org/issues/131207
- Verification run (on loaded workers):  https://openqa.suse.de/tests/11438147#step/ww4_await_pxe_install/1
Logic also works on aarch64 https://openqa.suse.de/tests/11433964#step/ww4_await_pxe_install/ …
=> ww4: Change compute node boot logic

tests/publiccloud/prepare_instance.pm
publiccloud `prepare_instance` update to handle ssh connectivity errors.
As followup of previous PR#17227, in that PR at end we simply applied key rescan refresh only, skipping the retry on error.
But,as explained in the poo [note 11](https://progress.opensuse.org/issues/130444#note-11) the last new tests errors should be likely due to a rush condition of protocol checks in the multiple types of keys. In fact in those `journal` logs appeared 3 keys checks, where RSA is ok, but being last in the attempts sequence of instance VM, those tests failed due to stop at-first-error.
Therefore, the here reproposed retry on error should solve the issue.
- Related ticket: https://progress.opensuse.org/issues/130444
- Verification run: TBD see next posts.
=> prepare_instance update in P.C. to handle ssh connectivity errors

tests/microos/patterns.pm
This module is timing out frequently in `aarch64` machines in the updates test group.
- ticket: https://progress.opensuse.org/issues/131036
```Created job #11443494: sle-micro-5.4-DVD-Updates-aarch64-Build20230625-1-slem_installation_autoyast@aarch64 -> https://openqa.suse.de/t11443494
Created job #11443495: sle-micro-5.4-DVD-Updates-aarch64-Build20230625-1-slem_installation_autoyast@aarch64 -> https://openqa.suse.de/t11443495
Created job #11443496: sle-micro-5.4-DVD-Updates-aarch64-Build20230625-1-slem_installation_autoyast@aarch64 -> https://openqa.suse.de/t11443496
Created job #11443499: sle-micro-5.4-DVD-Updates-aarch64-Build20230625-1-slem_installation_autoyast@aarch64 -> https://openqa.suse.de/t11443499
Created job #11443501: …
```
=> Bump timeout for patterns installation in sle-micro

tests/qam-minimal/update_minimal.pm
https://progress.opensuse.org/issues/131213
After installing new kernel package, system will try to remove the old ones via 'zypper -n purge-kernels', it may block other zypper processes.
- Verification run: https://openqa.suse.de/tests/11451470
=> Wait for 'zypper purge-kernels' done in update_minimal test

lib/hacluster.pm, t/11_hacluster.t
Module 'check_after_reboot' currently fails because of unexpected values 
appearing in SBD delay formula. This PR converts unexpected float parameters to 
int. It also sets default value in case 'pcmk_delay_max' is not obtainable. 
- Related ticket: https://jira.suse.com/browse/TEAM-8104
- Needles: N/A
http://openqa.suse.de/tests/11443306#step/check_after_reboot/35
http://openqa.suse.de/tests/11443643#step/check_after_reboot/36
=> Cover unexpected values appearing in SBD calculation

tests/sles4sap/hana_install.pm, tests/sles4sap/hana_test.pm
HANA install/test modules had hard written to pmem devices starts from 0, which is now chnaged to thle list of exact devices on the system
- Related ticket: https://jira.suse.com/browse/TEAM-8077
- Verification run:  https://openqa.suse.de/tests/11387562
=> HANA install/test now reads actuall pmem devices

tests/containers/bci_test.pm, variables.md
Introduce the BCI_TARGET setting to allow configuration of the BCI target project for debugging and development.
- Related ticket: https://progress.opensuse.org/issues/131441
- Verification run: [aarch64 BCI_TARGET=ibs-cr](https://openqa.suse.de/tests/11452660) | [x86_64](https://openqa.suse.de/tests/11453626) | [aarch64](https://openqa.suse.de/tests/11453625)
=> Introduce BCI_TARGET setting

lib/publiccloud/instance.pm, lib/publiccloud/provider.pm, tests/publiccloud/migration.pm, tests/publiccloud/prepare_instance.pm, tests/publiccloud/slem_basic.pm
Description:
- `wait_for_ssh` updated in P.C. to handle retries on _other errors_, i.e. for any _else_ error occurred, not managed by proper `if` branch, we retry the remote command in loop, eventually until timeout;
- removed option `ignore_wrong_pubkey` and related error handling: always retry check on error, in loop;
- `ignore_wrong_pubkey` option cleaned, removed from any module where it was used in `wait_for_ssh` calls parameters.
References:
- Related ticket: https://progress.opensuse.org/issues/130444
- Needles:None
- Verification run:  TBD, see next
=> wait_for_ssh update in P.C. to handle check retry for other errors

tests/x11/lxqt_reconfigure_openqa.pm
With the switch to SDDM, the graphical session might no longer be on tty7.
- Verification run: http://10.168.4.168/tests/1322
=> x11/lxqt_reconfigure_openqa: Reconfigure the x11 console as well

data/console/systemd_rpm_macros_list, data/console/test_systemd_rpm_macros.sh
* Change for loop to a while read loop, supporting new-line separated commands
* Adjust test file to pass parameters to the macros that require it
- Related ticket: https://progress.opensuse.org/issues/130123
- Needles: N/A
- Verification run: https://openqa.opensuse.org/tests/3371465
=> systemd_rpm_macros: fix test with stricter rpm macros (parameters required)

lib/publiccloud/instance.pm
Description
- wait_for_ssh keep fast retrying 1s the only tests timeout set max 3min, all other delay is 5s
- Also die error message (croak command) improved readability.
References
- Related ticket: https://progress.opensuse.org/issues/130444
- Needles: none.
- Verification run: TBD, see next posts.
=> wait_for_ssh retry delay increased for long waiting cases

tests/update/updates_packagekit_gpk.pm
https://progress.opensuse.org/issues/130468
https://bugzilla.opensuse.org/show_bug.cgi?id=1212680
Close pop-up windows if any after updates installed.
VR: https://openqa.opensuse.org/tests/overview?&build=rfan0703&distri=opensuse
=> Close pop-up windows after updates installed in 'updates_packagekit_gpk' test

lib/qesapdeployment.pm, lib/sles4sap_publiccloud.pm, lib/sles4sap_publiccloud_basetest.pm, tests/sles4sap/publiccloud/add_server_to_hosts.pm, tests/sles4sap/publiccloud/cluster_add_repos.pm, tests/sles4sap/publiccloud/general_patch_and_reboot.pm, tests/sles4sap/publiccloud/hana_sr_schedule_cleanup.pm, tests/sles4sap/publiccloud/hana_sr_schedule_deployment.pm, tests/sles4sap/publiccloud/hana_sr_schedule_primary_tests.pm, tests/sles4sap/publiccloud/hana_sr_schedule_replica_tests.pm, tests/sles4sap/publiccloud/hana_sr_takeover.pm, tests/sles4sap/publiccloud/hana_sr_test_secondary.pm, tests/sles4sap/publiccloud/network_peering.pm, tests/sles4sap/publiccloud/peering_destroy.pm, tests/sles4sap/publiccloud/qesap_ansible.pm, tests/sles4sap/publiccloud/qesap_cleanup.pm, tests/sles4sap/publiccloud/qesap_reuse_infra.pm, tests/sles4sap/publiccloud/qesap_terraform.pm
Move and unify code for the IBSm Network Peering cleanup  to the
sles4sap_publiccloud basetest class.
Variable name change in qesapdeploy.
Related ticket: 
- http://openqaworker15.qa.suse.cz/tests/195021 : the cleanup is properly executed by the `Cleanup resources` test module http://openqaworker15.qa.suse.cz/tests/195021#step/Cleanup%20resources/5 :green_circle: 
- http://openqaworker15.qa.suse.cz/tests/195475 :green_circle: 
- http://openqaworker15.qa.suse.cz/tests/195480 but Ansible deregister is not called http://openqaworker15.qa.suse.cz/tests/195480#step/Cleanup%20resources/12 :red_circle: 
- http://openqaworker15.qa.suse.cz/tests/195936  :green_circle: 
- http://openqaworker15.qa.suse.cz/tests/195944   :green_circle: 
- …
=> Move the network peering cleanup in the baseclass

tests/update/updates_packagekit_gpk.pm
Reverts os-autoinst/os-autoinst-distri-opensuse#17331
https://openqa.opensuse.org/tests/3404576#step/consoletest_finish/14 seems to be a fallout from your latest gpk change (unconditionally pressing alt-f4)
=> Revert "Close pop-up windows after updates installed in 'updates_packagekit_gpk' test"

lib/trento.pm
Fix for bug introduced in https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/17159 (I added a couple of comments in that PR on `lib/trento.pm` and `t/08_trento.t` to explain why the bugs has not been detected by the UT
Related ticket: [TRNT-921](https://jira.suse.com/browse/TRNT-921)
- http://openqaworker15.qa.suse.cz/tests/197257 from here the part is using the fixed code http://openqaworker15.qa.suse.cz/tests/197257#step/test_trento_web/131  :green_circle: 
- http://openqaworker15.qa.suse.cz/tests/197255 triggered with no more existing Trento web image tag :red_circle:
=> Fix podman_exec call in trento lib.

lib/main_containers.pm, tests/containers/bci_test.pm, variables.md
Introduce the BCI_SKIP setting to allow to skip certain BCI test runs more granular than the job group settings allow.
- Related ticket: https://progress.opensuse.org/issues/129301
- Verification run: [normal test run](https://duck-norris.qe.suse.de/tests/13254) | [BCI_SKIP=1](https://duck-norris.qe.suse.de/tests/13255)
=> Introduce BCI_SKIP setting

lib/publiccloud/instance.pm, variables.md
Description:
Boottime parameters defaults added in P.C.instance::measure,store code.
By default now boottime measures collected and saved at instance creation.
References:
- Related ticket: https://progress.opensuse.org/issues/118027
- Needles: None.
- Verification run: To Be Done
=> Boottime parameters defaults added in instance-measure code

tests/containers/bci_test.pm
Adds a softfailure for skipping the postgresql test run on RHEL7.
- Related ticket: https://progress.opensuse.org/issues/129301
- Verification run: [rhel7-postgres14](https://duck-norris.qe.suse.de/tests/13267#step/bci_test_podman/9) | [SLES15-SP4 postgres14](https://duck-norris.qe.suse.de/tests/13263#step/bci_test_docker/61) | [rhel7-pcp](https://duck-norris.qe.suse.de/tests/13264#step/bci_test_podman/40) | [rhel8-postgres14](https://duck-norris.qe.suse.de/tests/13268#step/bci_test_podman/55)
=> Skip postgresql on RHEL7

data/yam/autoyast_sles15sp4_sp5_media_install_textmode_default_patterns_aarch64.xml, data/yam/autoyast_sles15sp4_sp5_media_install_textmode_default_patterns_ppc64le.xml.ep, data/yam/autoyast_sles15sp4_sp5_media_install_textmode_default_patterns_s390x.xml.ep, data/yam/autoyast_sles15sp4_sp5_media_install_textmode_default_patterns_x86_64.xml, lib/utils.pm, schedule/yast/autoyast/autoyast_create_hdd.yaml
Add autoyast profiles for media installation of textmode with all patterns to creates qcow for SLES15SP4/SP5 minimal update migration cases. And update the lib/utils.pm to make the added repos enabled.
- Related ticket: https://progress.opensuse.org/issues/130486; https://progress.opensuse.org/issues/130492
- Needles: n/a
- https://openqa.suse.de/tests/11444336 (testsuite to create image on x86_64)
- https://openqa.suse.de/tests/11444569 (verify the created image on x86_64)
- https://openqa.suse.de/tests/11437904 (testsuite to create image on s390x)
- https://openqa.suse.de/tests/11437996 (verify the created image on s390x)
- https://openqa.suse.de/tests/11444590 (testsuite to create image on aarch64)
- https://openqa.suse.de/tests/11451496 (verify the created image …
=> Add autoyast profiles for media installation of textmode with all patterns

tests/openqa/install/openqa_bootstrap.pm
Ticket: https://progress.opensuse.org/issues/131024
PR for enabling nginx in openQA RPMs: https://github.com/os-autoinst/openQA/pull/5232
=> Add option for testing nginx proxy instead of apache in openqa_bootstrap

tests/sles4sap/publiccloud/hana_sr_test_secondary.pm
There is and issue in HanaSR secondary crash test where 'crm' command is called 
after the cluster is already down on that node. This cause command and 
eventually test to fail. This PR moves the command before stopping the database.
**- Related ticket:** https://jira.suse.com/browse/TEAM-8033
**- Needles: N/A**
**- Verification run:** 
- 15SP2 and 15SP3 VRs are not included due to another problem and test does not reach changed code. 
15SP4: https://openqaworker15.qa.suse.cz/tests/197281#
15SP5: https://openqaworker15.qa.suse.cz/tests/197276#
=> Move SBD delay calculation before hana stop

tests/kernel/nfs_stress_ng.pm
stress-ng is available through packagehub for SLE codestream
=> NFS: Use packagehub in case of SLE

lib/bootloader_setup.pm, lib/serial_terminal.pm, lib/susedistribution.pm
user-serial is svirt serial console for user. Adding a link helps switching between root and non root user in `select_serial_terminal()`. This commit is similar to 4a89bfb0f.
with updated os-autoinst https://github.com/os-autoinst/os-autoinst/pull/2330 (API version 39)
- https://openqa.suse.de/tests/overview?build=sut-serial-for-user
- https://openqa.opensuse.org/tests/overview?build=sut-serial-for-user (please ignore s390x, because virtio console test does not work on z/VM)
- https://openqa.suse.de/tests/11441410#step/zypper_lifecycle/1 (sle-15-SP4-Server-DVD-Updates-s390x-Buildlifecycle-qam-minimal+base@s390x-kvm-sle12, thanks to @dzedro)
Ticket: [poo#131258](https://progress.opensuse.org/issues/131258)
NOTE: WIP is due waiting API version 39 being installed to all …
=> susedistribution: bootloader_setup: Add user-sut-serial

tests/fips/fips_setup.pm
These packages/versions were part of the fips certification but they no longer are. NSS won't be certified package, so these dependencies are not needed.
VR: https://openqa.suse.de/tests/11533058#live
=> Remove version dependencies in fips setup

lib/Yam/agama/agama_base.pm, lib/Yam/agama/patch_agama_base.pm, tests/yam/agama/auto.pm, tests/yam/agama/patch_agama.pm
There are 'Yam' and 'yam' folders under /lib/, actually Yam is the correct one, so we need move files under /lib/yam to /lib/Yam.
- Related ticket: https://progress.opensuse.org/issues/130579
- Needles: n/a
- Verification run: https://openqa.opensuse.org/tests/3365502#
=> Move the files under lib/yam to lib/Yam

tests/yam/agama/agama_installation.pm
Update agama_installation to use own project repo of e2e-agama-playwright and add upload trace to post_fail_hook.
- Verification run:  https://openqa.opensuse.org/tests/3406485#
=> Update agama_installation to use e2e-agama-playwright

tests/installation/bootloader_uefi.pm
Sometimes it can't match grub2 in a short time on aarch64 for agama, we reduce needle to fix it.
- Needles: N/A
- Verification run: https://openqa.opensuse.org/tests/overview?arch=aarch64&flavor=&machine=&test=&modules=&module_re=&distri=alp&build=lemon-suse%2Fos-autoinst-distri-opensuse%23debug-agama-auto-install-issue&version=agama-2.1-staging#
=> Reduce needle to match grub2 on aarch64 for agama

tests/qe-core/x11/openbroadcastersoftware.py
Remove fatal flag on obs test
- Related ticket: https://progress.opensuse.org/issues/109891
- Verification run: https://openqa.opensuse.org/tests/3413239
=> Remove fatal flag on obs test

lib/sles4sap_publiccloud.pm, tests/sles4sap/publiccloud/peering_destroy.pm
Bug in https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/17329
- Related ticket: [TEAM-8153](https://jira.suse.com/browse/TEAM-8153)
- Verification run: https://openqaworker15.qa.suse.cz/tests/199452
=> Add base class for peering_destroy

schedule/kernel/kirk.yaml, tests/kernel/kirk.pm
Kirk is a framework that aims to run mutiple Linux testing frameworks in a single application. With this patch we add support for scheduling it via yaml file.
- Related ticket: https://progress.opensuse.org/issues/130781
- Verification run: https://openqa.suse.de/tests/11406900
=> Add kirk support

lib/susedistribution.pm, tests/console/zypper_lifecycle.pm
- Related ticket: https://progress.opensuse.org/issues/126794 https://github.com/os-autoinst/os-autoinst/pull/2295
- Verification run: https://openqa.suse.de/tests/overview?build=lifecycle&version=15-SP5&distri=sle
=> zypper_lifecycle: Use select_(user_)?serial_terminal

tests/yam/agama/auto.pm
Sometimes 900s is not enough for agama micro to finish the installation, so we need increase the timeout value for it.
- Failed job: https://openqa.opensuse.org/tests/3418101#step/auto/12
https://openqa.opensuse.org/tests/3409587#step/auto/3
- Needles: N/A
- Verification run: https://openqa.opensuse.org/tests/3418125#
=> Fix agama micro install timeout issue

lib/filesystem_utils.pm, tests/xfstests/partition.pm
Init ocfs2 test support. The plan is in related ticket. This is first step to test ocfs2 in 1 node without cluster setting. 
- Related ticket: https://progress.opensuse.org/issues/128918
- test ocfs2/001: http://10.67.133.133/tests/241
- test generic/001-100: http://10.67.133.133/tests/245#step/generate_report/423
- (the fail is expected, to check if new code would solve hung issue, fail tests and skip tests)
=> xfstests: Support ocfs2 test

data/virt_autotest/kubevirt_tests/full-tests.conf, tests/virt_autotest/kubevirt_barriers.pm, tests/virt_autotest/kubevirt_tests_agent.pm, tests/virt_autotest/kubevirt_tests_server.pm
1. Support Longhorn CSI storage setup
Since the kubevirt manifest local-block-storage.yaml has been removed from upstream release v0.50.0, we have to use Longhorn instead for CSI storage setup.
2. Adopt new configurations and run methods
Some test failures are caused by the changes of virt-tests command line from v0.50.0, and also some of settings are required for running specific tests.
https://progress.opensuse.org/issues/128306
https://progress.opensuse.org/issues/126668
For sle - http://10.67.129.96/tests/2467
For sle-micro - http://10.67.129.96/tests/2457
- Needles:
https://gitlab.suse.de/openqa/os-autoinst-needles-sles/-/merge_requests/1646
=> Support Longhorn CSI storage setup and adopt new configs

tests/yam/agama/auto.pm
Sometimes it can't match grub2 after installation in a short time on aarch64 for agama, we add new needle to fix it.
- Failed job:  https://openqa.opensuse.org/tests/3418306#step/auto/15
- Needles:  grub2-agama
- Verification run: https://openqa.opensuse.org/tests/overview?version=agama-2.1-staging&distri=alp&build=lemon-suse%2Fos-autoinst-distri-opensuse%23match-grub2-after-installation-for-agama
=> Add new needle to match grub2 after installation for agama

data/yam/agama/auto/default_alp_micro.jsonnet
Remove the description part from agama jsonnet as it is 'Additional properties are not allowed ('description' was unexpected)'.
- Needles: N/A
- Verification run: https://openqa.opensuse.org/tests/overview?distri=alp&version=agama-2.1-staging&build=lemon-suse%2Fos-autoinst-distri-opensuse%23Fix-unexpected-description-agama-jsonet
=> Fix unexpected description issue for agama jsonnet

data/autoyast_sle12/autoyast_sles12sp5_media_all_patterns_minimal_x86_64.xml, data/autoyast_sle12/autoyast_sles12sp5_media_def_patterns_minimal_x86_64.xml
Create autoyast installation without registration for minimal update qcow on SLES12SP5
- Related ticket: https://progress.opensuse.org/issues/130489
- Needles: na
Publish qcow: https://openqa.suse.de/tests/11437895
Migration: https://openqa.suse.de/tests/11437916
Gitlab new case MR: https://gitlab.suse.de/qa-maintenance/qam-openqa-yml/-/merge_requests/555
=> Create autoyast installation without registration for minimal update qcow on SLES12SP5

lib/bootloader_setup.pm
Short url is not work for dud bootloader parameters, we would add a setting of 'DUD_NO_SHORTEN_URL' for the using of short url or not.
- Needles: N/A
- Verification run: http://openqa.suse.de/tests/11550109#
http://openqa.suse.de/tests/11550156#details
- Related MR: https://gitlab.suse.de/qa-maintenance/qam-openqa-yml/-/merge_requests/564
=> Fix dud bootloader connection timeout issue

schedule/yam/agama/agama_full_disk_encryption.yaml, test_data/yam/agama_full_disk_encryption.yaml, tests/installation/boot_encrypt.pm, tests/yam/agama/agama_full_disk_encryption.pm
- Related ticket: https://progress.opensuse.org/issues/130003
- Related PR for Playwright stuff: https://github.com/jknphy/e2e-agama-playwright/pull/2
- x86_64: https://openqa.opensuse.org/tests/3418668
- aarch64: https://openqa.opensuse.org/tests/3419297
=> Run playwright installation with encryption

lib/Yam/agama/agama_base.pm
Set milestone test flag to agama_base.pm
- Related ticket: https://progress.opensuse.org/issues/131483
- Needles: na
- Verification run: https://openqa.opensuse.org/tests/3420599#
=> Set milestone test flag to agama_base.pm

data/zvm.xml
They were removed in kdump 1.9 and yast-kdump no longer accepts them.
Failure: https://openqa.opensuse.org/tests/3420135
Verification run: https://openqa.opensuse.org/tests/3422145#live
=> data/zvm.xml: Drop use of removed kdump options

tests/containers/podman_netavark.pm
- Related ticket: https://progress.opensuse.org/issues/132572
=> Podman netavark: update openSUSE BCI Busybox image

tests/yam/agama/agama_installation.pm, tests/yam/agama/agama_lvm.pm
Failed job: https://openqa.opensuse.org/tests/3422058#step/agama_installation/13 , we need add new needle instead of generic grub2. 
- Needles: grub2-agama
- Verification run: [openqa.mypersonalinstance.de/tests/xyz#step/module/x](https://openqa.opensuse.org/tests/overview?version=agama-2.1-staging&build=lemon-suse%2Fos-autoinst-distri-opensuse%23use-new-needle-instead-generic-grub2&distri=alp)
https://openqa.opensuse.org/tests/3422192#step/agama_installation/7 failed for slow caused missed character.
=> Add new needle instead of generic grub2

.github/CODEOWNERS
`m-dati` added to `CODEOWNERS`, for some publiccloud repo's code locations.
=> Codeowner update MD

schedule/kernel/kselftests.yaml, tests/kernel/kselftests.pm
This patch aims to add kselftests support to openQA. This is only an initial support that works with cgroup testing. In order to enable other kselftests, we need to adapt the code and to install kselftests from other sources, rather than guessing a Makefile for each kselftests folder.
- Related ticket: https://progress.opensuse.org/issues/130784
=> Add kselftests support

tests/console/soundtouch.pm
Use check_recorded_sound instead of assert_recorded_sound. 
- Related ticket:  https://progress.opensuse.org/issues/132578
- Needles: No
- Verification run:  [Leap15.5](https://openqa.opensuse.org/tests/3424772#next_previous)  | [Tumbleweed](https://openqa.opensuse.org/tests/3426281#next_previous)
=> Fix test soundtouch  

tests/containers/bci_prepare.pm, tests/containers/bci_test.pm
Following subset of images can be found in development group. In order to proceed with testing we need to adapt the BCI openQA modules.
- Images: init, minimal, micro, busybox, golang, rust, ruby and postgres14
- Related ticket: https://progress.opensuse.org/issues/132338
* [init](http://kepler.suse.cz/tests/21195)
* [golang](http://kepler.suse.cz/tests/21197#step/_root_BCI-tests_all_podman/8)
* [postgres](http://kepler.suse.cz/tests/21196)
* [sle-15-SP5-BCI-Updates-x86_64-Build11.5_minimal-image-bci-minimal_15.5_on_SLES_15-SP4@64bit](http://kepler.suse.cz/tests/21203)
* [sle-15-SP5-BCI-Updates-x86_64-Build11.5_minimal-image-bci-minimal_15.5_on_SLES_15-SP2@64bit](http://kepler.suse.cz/tests/21204)
* [sle-15-SP5-BCI-Updates-x86_64-Build11.5_minimal-image-bci-minimal_15.5_on_SLES_12-SP5@64bi …
=> Introduce BCI tests for tumbleweed based images

tests/x11/user_defined_snapshot.pm
- Related ticket: https://progress.opensuse.org/issues/132155
https://openqa.opensuse.org/tests/overview?build=user_defined_snapshot&distri=opensuse TW
https://openqa.suse.de/tests/11572800 SLE
=> Use y2snapper_close_snapper_module to close yast2 snapper

tests/yam/agama/agama_installation.pm, tests/yam/agama/agama_lvm.pm
Use agama_base as base package to avoid the password issue after reboot.
- Failed job: https://openqa.opensuse.org/tests/3432170#step/validate_lvm/4
- Needles: N/A
- Verification run: https://openqa.opensuse.org/tests/3434416#
=> Use agama_base as base package to avoid password issue

lib/publiccloud/azure.pm, lib/publiccloud/provider.pm
* Both x86 as well as Arm64 images are now managed in image galleries.
* Image definition name now contains architecture and SKU as it needs to be unique.
* Image definition offer now contains architecture as it needs to be unique.
* The architecture is set in `PUBLIC_CLOUD_ARCH` and that can be improved in the future.
- Related pull requests: #17375, [gitlab.suse.de/qac/qac-openqa-yaml/-/merge_requests/1266](https://gitlab.suse.de/qac/qac-openqa-yaml/-/merge_requests/1266)
- Related ticket: [poo#114517](https://progress.opensuse.org/issues/114517)
- Scheduling changes:
* Upload: `PUBLIC_CLOUD_REGION=westeurope,westus PUBLIC_CLOUD_AZURE_OFFER=`
* Others: `PUBLIC_CLOUD_AZURE_OFFER= PUBLIC_CLOUD_IMAGE_URI=auto`
* gen1 x86: …
=> Public Cloud: Switch Azure x86_64 disks to compute galleries  * Add V1/V2 to image definition names.

lib/wickedbase.pm
`IS_WICKED_REF` is boolean variable, better to use get_var.
- sle-15-SP4-Server-DVD-Updates-x86_64-Build20230716-1-qam_wicked_advanced_ref@64bit -> https://openqa.suse.de/tests/11599651
- sle-15-SP4-Server-DVD-Updates-x86_64-Build20230716-1-qam_wicked_advanced_sut@64bit -> https://openqa.suse.de/tests/11599652
=> Replace check_var for get_var

data/sles4sap/qe_sap_deployment/qesap_aws.yaml, data/sles4sap/qe_sap_deployment/qesap_aws_sapconf.yaml, data/sles4sap/qe_sap_deployment/qesap_azure.yaml, data/sles4sap/qe_sap_deployment/qesap_azure_sapconf.yaml, data/sles4sap/qe_sap_deployment/qesap_azure_sapconf_no_reg.yaml, data/sles4sap/qe_sap_deployment/qesap_azure_uri.yaml, data/sles4sap/qe_sap_deployment/qesap_gcp.yaml, data/sles4sap/qe_sap_deployment/qesap_gcp_sapconf.yaml, data/sles4sap/qe_sap_deployment/trento_azure.yaml, tests/sles4sap/qesapdeployment/configure.pm
Made conf.yaml templates used by Trento and qesap regressio more consisten.
- Copyright file header
- Hardcoded provider: as in any case each config.yaml is specific to one CPS
- Remove Ansible variables
- String quotations
Related ticket: [TEAM-8049](https://jira.suse.com/browse/TEAM-8049)
-  Results for sle-15-SP4-Qesap-Azure-Byos-x86_64-BuildLATEST_AZURE_SLE15_4_BYOS-qesap_azure_sapconf_test http://openqaworker15.qa.suse.cz/tests/200686 :green_circle: 
-  Results for sle-15-SP4-Qesap-Azure-Byos-x86_64-BuildLATEST_AZURE_SLE15_4_BYOS-qesap_azure_saptune_test http://openqaworker15.qa.suse.cz/tests/200687 :green_circle: 
-  Results for sle-15-SP5-Qesap-Azure-Byos-x86_64-BuildLATEST_AZURE_SLE15_4_BYOS-qesap_azure_saptune_test  `os_image_uri:` …
=> Harmonize qe-sap-deployment config.yaml

tests/installation/bootloader_s390.pm
That code runs on the worker, not the SUT.
It also terminates execution before printing $exception.
Verification run: https://openqa.opensuse.org/tests/3436187
=> installation/bootloader_s390: Remove broken attempt at printing y2start.log

data/autoyast_sle15/mini_s390x.xml, schedule/yast/autoyast/autoyast_mini_aarch64.yaml, schedule/yast/autoyast/autoyast_mini_s390x.yaml, test_data/yast/autoyast/profiles/mini_aarch64.yaml, test_data/yast/autoyast/profiles/mini_s390x.yaml
Add test suite of autoyast_mini for s390x and aarch64
- Related ticket: https://progress.opensuse.org/issues/131342
- Needles: na
s390x:   https://openqa.suse.de/t11614211
aarch64: https://openqa.suse.de/tests/11609007#step/verify_cloned_profile/6
=> Add test suite of autoyast_mini for s390x and aarch64

lib/virt_autotest/common.pm
Optimize test matrix to improve test efficiency
progress ticket: https://progress.opensuse.org/issues/132503
- Related ticket: https://progress.opensuse.org/issues/132530
- Needles: N/A
XEN tests:
[XEN 12-sp4](http://openqa.qam.suse.cz/tests/overview?build=:S:M:29711:302738:xen:hansolo:12-SP4:test:&distri=sle&version=12-SP4&groupid=161)
[XEN 12-sp5](http://openqa.qam.suse.cz/tests/overview?build=:S:M:29711:302738:xen:hansolo:12-SP5:test:&distri=sle&version=12-SP5&groupid=160)
[XEN 15-sp1](http://openqa.qam.suse.cz/tests/overview?build=:S:M:29711:302738:xen:javor:15-SP1:test:&distri=sle&version=15-SP1&groupid=158)
[XEN 15-sp2](http://openqa.qam.suse.cz/tests/overview?build=:S:M:29711:302738:xen:yoda:15-SP2:test:&distri=sle&version=15-SP2&groupid=157)
[XEN …
=> Rearrange the test matrix

tests/wicked/basic/sut/t09_hotplug.pm
Failed test: https://openqa.suse.de/tests/11609292#step/t10_peerip_and_static_route/98
=> wicked: add always_rollback flag for basic/t09_hotplug

lib/main_common.pm, tests/installation/live_installation.pm
This flavor uses published repos during testing.
+ Bonus improvement to a comment I had lying around in my checkout but didn't want to open a separate PR for.
- Related ticket: https://progress.opensuse.org/issues/131186
- Verification run: https://openqa.opensuse.org/tests/3440543
=> lib/main_common: CR-DVD does not need_clear_repos

data/generalhw_scripts/flash_sd.sh
Ignore some additional arguments passed when NUMDISKS=2
=> general_hw: Add a workaround in flash_sd script

lib/containers/engine.pm
`podman-prune` might run while containers are stopping.
- ticket: https://progress.opensuse.org/issues/133031
- Verification run: [sle-micro-5.3-BYOS-Azure-x86_64-Build0468-slem_containers@64bit](http://kepler.suse.cz/tests/21305#)
=> Run prune after all containers are stopped

tests/publiccloud/aws_cli.pm, tests/publiccloud/azure_cli.pm, tests/publiccloud/azure_more_cli.pm, tests/publiccloud/google_cli.pm
This PR:
- Uses `OPENQA_HOSTNAME` if `OPENQA_URL` is not available.
- Use underscores instead of hyphens to mask dots in hostname (hyphens are valid characters in hostnames unlke underscores).
=> Get openQA hostname

tests/update/prepare_system_for_update_tests.pm
https://progress.opensuse.org/issues/133016
After installing new kernel package, purge-kernels service may take sometime to purge the old kernels, it can block PackageKit to start.
- Verification run:https://openqa.opensuse.org/tests/3440335
=> Mask purge-kernels service then not to race with PackageKit

schedule/yast/lvm_multipath_encrypted_x86_64.yaml, schedule/yast/lvm_multipath_x86_64.yaml, schedule/yast/multipath.yaml, schedule/yast/sle/flows/default_x86_64.yaml
- Description
Remove multipath key and replace reuse system_probing in default yaml schedule files for all arches.
- Ticket
https://progress.opensuse.org/issues/132266
- VR
[**system_probing**](https://openqa.suse.de/tests/overview?arch=&flavor=&machine=&test=&modules=&module_re=&distri=sle&version=15-SP5&build=hjluo%2Fos-autoinst-distri-opensuse%23system_probing)
=> Remove multipath and replace system_probing in default yaml 

lib/containers/engine.pm
`all` option in `docker-rm` is unknown. Run `rm --all force` only in case of podman before `system prune`
- Related ticket: https://progress.opensuse.org/issues/133031
* [docker](http://kepler.suse.cz/tests/21306#)
* [podman](http://kepler.suse.cz/tests/21307)
=> Fix docker rm call

schedule/migration/migration_offline_media_x86_64.yaml, schedule/migration/migration_offline_scc_x86_64.yaml, tests/migration/suseconnect_register_system.pm
- Description: Remove the set for `IN_PATCH_SLE` in `tests/migration/SUSEConnect_register_system.pm`
+ update the name of the file `SUSEConnect_register_system.pm` to make it lowercase
- Related ticket: https://progress.opensuse.org/issues/132737
+ [sles15sp3_media](https://openqa.suse.de/tests/11619212)
+ [sles15sp4_pscc](https://openqa.suse.de/tests/11619213)
=> Remove 'IN_PATCH_SLE' in tests/migration/SUSEConnect_register_system.pm

lib/containers/engine.pm
In older podman versions e.g. `2.1.1` we need to force remove pods before containers.
- ticket: https://progress.opensuse.org/issues/133031
* [sle-15-SP4-JeOS-for-kvm-and-xen-Updates-x86_64-Build20230719-1-jeos-containers-podman@uefi-virtio-vga](http://kepler.suse.cz/tests/21318#step/podman_pods/373)
* [http://kepler.suse.cz/tests/21316#step/podman_pods/373](http://kepler.suse.cz/tests/21316#step/podman_pods/373)
* [sle-15-SP1-Server-DVD-Updates-x86_64-Build20230719-1-podman_tests@64bit](http://kepler.suse.cz/tests/21317#step/podman_pods/87)
* [sle-15-SP2-Server-DVD-Updates-x86_64-Build20230719-1-podman_tests@64bit](http://kepler.suse.cz/tests/21315#step/podman_pods/87)
* [sle-15-SP1-AZURE-BYOS-Updates-x86_64-Build20230719-1-publiccloud_containers@64bit](http://kepler.suse.cz/tests/21319#l …
=> Force remove pods before containers

tests/installation/ipxe_install.pm
Sometimes, especially when working in development environments, you just get bogus whitespaces in variables, which will lead to non-functional tests. In order to avoid this, let's trim all strings we retrieve.
=> Trim strings retrieved from variables

lib/publiccloud/azure.pm, lib/publiccloud/provider.pm
Adds the architecture to the image definition name to allow x86_64 and aarch64 images in parallel.
Also prevent a failure due to multiple image definitions, if the given image is already defined (see related failure above)
- Related failure: https://openqa.suse.de/tests/11610662
- Related ticket: https://progress.opensuse.org/issues/133013
* [x86_64 (new image)](https://duck-norris.qe.suse.de/tests/13363#step/upload_image/97) | [x86_64 (reusing existing image)](https://duck-norris.qe.suse.de/tests/13365#step/upload_image/97)
* [aarch64 (new image)](https://duck-norris.qe.suse.de/tests/13364#step/upload_image/97) | [aarch64 (using existing image)](https://duck-norris.qe.suse.de/tests/13366#step/upload_image/97)
* [slem-basic](https://duck-norris.qe.suse.de/tests/13367) …
=> Fix failure in repetitive upload_image calls

lib/serial_terminal.pm, lib/susedistribution.pm
The expected console prompt was switched inconsistently and could get out of sync with the actual SUT shell with the right sequence of console switching function calls. Move the automatic prompt setup logic to `susedistribution::activate_console()` and `susedistribution::console_selected()`. Also make sure that manual prompt changes using the appropriate helper function will update the console prompt expected by script_run().
- Related ticket: https://progress.opensuse.org/issues/126794
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/11574354
=> Fix serial terminal prompt handling

data/virt_autotest/host_unattended_installation_files/autoyast/dev_host_12.xml.ep, tests/virt_autotest/reboot_and_wait_up.pm
Create a autoyast template for sles12sp5 in order for product
virtuallzation test to switch from GUI installation to autoyast
installation
https://progress.opensuse.org/issues/128201
- Related ticket:     https://progress.opensuse.org/issues/128201
- Needles: no
- gi-guest_developing-on-host_sles12sp5-kvm, https://openqa.suse.de/tests/11522341
- gi-guest_developing-on-host_sles12sp5-xen, https://openqa.suse.de/tests/11522379
- prj2_host_upgrade_sles12sp5_to_developing_kvm https://openqa.suse.de/tests/11526423
- prj2_host_upgrade_sles12sp5_to_developing_xen https://openqa.suse.de/tests/11526425
- prj2_host_upgrade_sles15sp4_to_developing_xen: https://openqa.suse.de/tests/11565560
=>     Replace GUI host installation with autoyast for sle12sp5

tests/x11/seahorse_sshkey.pm
This should prevent any occasional timeout failures. It has been increased from 3 to 6 in the past, but still sometimes happens, so we can set this to 8 for good measure.
Related ticket: https://progress.opensuse.org/issues/130150
=> Increase timeout for seahorse_sshkey

tests/publiccloud/aws_cli.pm, tests/publiccloud/azure_cli.pm, tests/publiccloud/azure_more_cli.pm, tests/publiccloud/google_cli.pm
Add openqa_var_SERVER & openqa_var_JOB_ID tags to VM's created by `${provider}_cli` tests so pcw is aware of them.
- Related ticket: https://progress.opensuse.org/issues/132611
- Related PR: https://github.com/SUSE/pcw/pull/278
- Verification run: https://openqa.suse.de/tests/11650015
=> pc: Add openqa_var_SERVER & openqa_var_JOB_ID tags to ${provider}_cli tests

lib/publiccloud/provider.pm, tests/publiccloud/aws_cli.pm, tests/publiccloud/azure_cli.pm, tests/publiccloud/azure_more_cli.pm, tests/publiccloud/google_cli.pm
Use lowercase `openqa_var_SERVER` & `openqa_var_JOB_ID` because `gcloud` doesn't support uppercase keys.
- Related ticket: https://progress.opensuse.org/issues/132611
- Related PR: https://github.com/SUSE/pcw/pull/278
- Verification run: https://openqa.suse.de/tests/11650292
=> pc: Lowercase openqa_var_SERVER & openqa_var_JOB_ID

tests/x11/nis_client.pm
Workaround for refreshment issue for nis-client-configuration
- Related ticket: https://progress.opensuse.org/issues/126488
- Verification run: https://openqa.suse.de/tests/11625444
=> Workaround for refreshment issue for nis-client-configuration

lib/qesapdeployment.pm
Capturing Cloud init logs in Azure to find out root cause of timeout error. cat /var/log/cloud-init.log > azure_cloud_init_log.txt in lib/qesapdeployment.pm
- Verification run: Azure: http://openqaworker15.qa.suse.cz/tests/207043
AWS : http://openqaworker15.qa.suse.cz/tests/207044
=> Add cloud_init_log in Azure to capture timeout error root cause

tests/xfstests/install.pm, tests/xfstests/partition.pm, tests/xfstests/run.pm
The xfstest in alp will default install in /opt/xfstests, so no need to link here.
Also add the alp xfstests repo and denepency repo.
- Related ticket: https://progress.opensuse.org/issues/132533
> Verify previous tests OK with the changes:
> - create_hdd_xfstests: http://10.67.133.133/tests/258
> - xfstests_btrfs-btrfs-001-050: http://10.67.133.133/tests/260
=> xfstests: Change test folder and add repo for alp

tests/systemd_testsuite/prepare_systemd_and_testsuite.pm
Tests paths has change in the package. Update the test code in order to schedule integration tests in openQA
- Verification run: http://kepler.suse.cz/tests/21337#
=> Update test path for systemd-testsuite

data/journal_check/bug_refs.json
According to https://jira.suse.com/browse/PED-4742 switch-root service is going to be removed in the future which will solve above mentioned issue.
- VR: http://kepler.suse.cz/tests/21339#step/journal_check/9
=> Recognize haveged.service failure as known bug

data/yam/autoyast/create_hdd_textmode_aarch64.xml, data/yam/autoyast/create_hdd_textmode_powervm.xml, data/yam/autoyast/create_hdd_textmode_s390x.xml, data/yam/autoyast/create_hdd_textmode_x86_64.xml, schedule/yast/autoyast/autoyast_create_hdd_textmode.yaml
- Description: Create autoyast installation for textmode in _yast_ job group
- Related ticket: https://progress.opensuse.org/issues/130985
+ [overview](https://openqa.suse.de/tests/overview?distri=sle&build=manfredi%2Fos-autoinst-distri-opensuse%23issues-130985&version=15-SP5)
+ [create_hdd_textmode_autoyast@ppc64le](https://openqa.suse.de/tests/overview?distri=sle&version=15-SP5&build=102.1&groupid=96)
- Related [MR#519](https://gitlab.suse.de/qsf-y/qa-sle-functional-y/-/merge_requests/519)
=> Create autoyast installation for textmode in yast job group

data/jeos/g_cloudinit.cfg, tests/jeos/verify_cloudinit.pm
Instead of checking `qemu-guest-agent.service` that requires a device to be added, try to write a custom systemd service and check whether it has executed correctly.
- Verification run: http://kepler.suse.cz/tests/21343#
=> Check custom systemd service setup

lib/utils.pm
Default timeout (10 seconds) may be too short with qemu NO kvm so increase to 20s - poo#131366
- Related ticket: https://progress.opensuse.org/issues/131366
- Verification run:  https://openqa.opensuse.org/tests/3448590#step/hostname/21
=> Increase timeout in 'nmcli device disconnect $dev' for qemu no kvm

tests/console/steamcmd.pm
- Related ticket: https://progress.opensuse.org/issues/131306
- Needles: NO
- Verification run: [opensuse-15.4]( https://openqa.opensuse.org/tests/3450757#step/steamcmd/6 
) | [opensuse-15.5](https://openqa.opensuse.org/tests/3450626#step/steamcmd/6)
=> Enable softfail for bsc#1212977

schedule/yast/opensuse/raid/raid1_gpt_opensuse15.4.yaml, test_data/yast/raid/raid0_prep_boot_opensuse15.4.yaml
Add chunk size for RAID1 opensuse15.4 test_data
- Related ticket: https://progress.opensuse.org/issues/131183
- Needles: na
- Verification run: https://openqa.opensuse.org/tests/3450746
Jobgroup PR: https://github.com/os-autoinst/opensuse-jobgroups/pull/355
NOTE:
This PR ONLY can fix following cases:
opensuse-15.4-CR-DVD-ppc64le-Build32.1-RAID0@ppc64le  https://openqa.opensuse.org/tests/3450746
opensuse-15.4-CR-DVD-x86_64-Build32.2-RAID1_gpt@64bit https://openqa.opensuse.org/tests/3455294  (But this case not stable such as https://openqa.opensuse.org/tests/3450790#step/first_boot/1)
Need further check how to fix following case:
opensuse-15.4-CR-DVD-aarch64-Build32.2-RAID1_gpt_uefi@USBboot_aarch64 https://openqa.opensuse.org/tests/3450791
=> Add chunk size for RAID1 opensuse15.4 test_data

tests/kernel/install_ltp.pm
In case of some architectures for a transactional systems, like ARM, we see 90 sec isn't enough to run the installation
=> Increase timeout

data/yam/autoyast/support_images/sles15sp3_media_install_textmode_minimal_aarch64.xml, data/yam/autoyast/support_images/sles15sp3_media_install_textmode_minimal_x86_64.xml
We need create autoyast installation without registration for minimal update qcow on SLES15SP3.
- Related ticket: https://progress.opensuse.org/issues/130483
- Needles: N/A
create hdd: 
https://openqa.nue.suse.com/tests/11634061# x86_64 
https://openqa.nue.suse.com/tests/11634062#  aarch64
migration test:
http://openqa.nue.suse.com/tests/11623566#  x86_64
http://openqa.nue.suse.com/tests/11623732#  aarch64
- Related MR: https://gitlab.suse.de/qa-maintenance/qam-openqa-yml/-/merge_requests/568
=> Create autoyast installation without registration for minimal update qcow on SLES15SP3

data/sles4sap/fetch_file.yaml, data/sles4sap/script_output.yaml, lib/qesapdeployment.pm, t/09_qesapdeployment.t
Remove logs that are already collected using `crm report`. Improve documentation of qesap functions using Ansible. Add unit testing about qesap_ansible_fetch_file.
This PR also solve some of the comments in the review of https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/17458
Related ticket: https://jira.suse.com/browse/TEAM-8138
Verification:
- sle-15-SP4-Qesap-Azure-Byos-x86_64-BuildLATEST_AZURE_SLE15_4_BYOS-qesap_azure_ibsmirror_peering_test@64bit -> http://openqaworker15.qa.suse.cz/tests/207786
- sle-15-SP4-Qesap-Azure-Byos-x86_64-BuildLATEST_AZURE_SLE15_4_BYOS-qesap_azure_sapconf_test@64bit -> http://openqaworker15.qa.suse.cz/tests/207787 :green_circle: 
- sle-15-SP4-HanaSr-Azure-Byos-x86_64-Build15-SP4_2023-07-26T04:03:33Z-hanasr_azure_test_saptune@64bit -> …
=> Remove duplicated logs from qesap_cluster_log_cmds

lib/saltbase.pm
- Related ticket: https://progress.opensuse.org/issues/133304
- Needles: NO
- Verification run: [salt_mater](https://openqa.suse.de/tests/11658932) | [salt_minion](https://openqa.suse.de/tests/11658931#)
Latest VRs:
[salt_master](https://openqa.suse.de/tests/11674943#step/salt_master/167) | [salt_minion](https://openqa.suse.de/tests/11674944#step/salt_minion/1)
=> Add bsc#1213635 soft-failure for salt test

tests/console/steamcmd.pm
The retry might also fail with 139.
- Failure: https://openqa.opensuse.org/tests/3462243#step/steamcmd/8
- Verification run: https://openqa.opensuse.org/tests/3462877
=> console/steamcmd.pm: Fix order of return code checks

lib/qesapdeployment.pm, lib/trento.pm, t/09_qesapdeployment.t, tests/sles4sap/trento/test_hana_unregister_node.pm
Centralized qesap management of the venv activation/deactivation. Propagate and not recalculate the path of the file downlaoded by Ansible.
Improve documentation.
Improve stability of Trento test_hana_unregister: add `podman stop` as part of error managemnet in the wait function, add some title to various file stages.
- Related ticket: https://jira.suse.com/browse/TEAM-8138
- Trento http://openqaworker15.qa.suse.cz/tests/208693
- qesap regression http://openqaworker15.qa.suse.cz/tests/208694
=> Improve ansible commands management in qesap.

lib/x11test.pm
Trying to counter mistypes like in https://openqa.opensuse.org/tests/3450441#step/ibus_test_cn/8
- Needles: N/A
- Verification run: https://openqa.opensuse.org/tests/3450843 (still far from good, but the mis-typing at least is gone, which makes the current bug reports against g-c-c at least valid again)
=> ibus: type language to add slower

schedule/sle-micro/yam/slem_installation_autoyast.yaml, schedule/sle-micro/yam/slem_installation_default_aarch64.yaml, schedule/sle-micro/yam/slem_installation_default_s390x.yaml, schedule/sle-micro/yam/slem_installation_default_x86_64.yaml
Add yaml schedule files for SLE Micro testsuite of slem_installation_autoyast and slem_installation_default.
- Related ticket: https://progress.opensuse.org/issues/132992
- https://openqa.suse.de/tests/11657764# (autoyast on aarch64)
- https://openqa.suse.de/tests/11657762# (autoyast on s390x)
- https://openqa.suse.de/tests/11657763# (autoyast on x86_64)
- https://openqa.suse.de/tests/11657780# (default on aarch64)
- https://openqa.suse.de/tests/11657781# (default on s390x)
- https://openqa.suse.de/tests/11657782# (default on x86_64)
=> Add yaml schedule files for SLE Micro testsuite

schedule/migration/s390x-zVM-Media-Upgrade.yaml
Optimize test coverage for default module (base) in migrations from SLE 12 SP5
**Ticket:**
- https://progress.opensuse.org/issues/131120
- [my VRs](https://openqa.suse.de/tests/overview?arch=&flavor=Migration-from-SLE12-SPx&machine=&test=&modules=&module_re=&distri=sle&version=15-SP5&build=102.1&groupid=466)
=> Including scc_deregistration in the zvm media migration.

schedule/hpc/gnu-compilers-hpc.yml, tests/hpc/gnu_compilers_hpc.pm, variables.md
Test gnu-compilers-hpc packages for later GNU toolchain that are released available for SLE.
- Related ticket: https://progress.opensuse.org/issues/130844
https://aquarius.suse.cz/tests/17753
=> Create test for later gnu-compilers-hpc later toolchain

.github/CODEOWNERS
Just add colleagues who take a look at hpc stuff expect me. i left pcervinka out of it because i am not sure if he wants to be responsible for all of the HPC context. He can add himself later once he is back. 
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners
=> Update Codeowners for HPC directories

lib/hpcbase.pm, tests/hpc/spack_master.pm, tests/hpc/spack_slave.pm
Spack doesnt set LD_LIBRARY_PATH and libraries cant be found. Apply workaround
from bsc#1208751. This is supposed is gonna be fixed and this workaround would
be needed.
Update: Second commit overrides workaround. 
Signed-off-by: Ioannis Bonatakis ybonatakis@suse.com
https://progress.opensuse.org/issues/127481
http://aquarius.suse.cz/tests/17841 - w/o HPC_LIB
http://aquarius.suse.cz/tests/17835 - with HPC_LIB
=> Use spack_get_libs.sh to setup LD_LIBRARY_PATH

lib/publiccloud/utils.pm, schedule/sles4sap/sles4sap_gnome_saptune_maintenance.yaml, tests/publiccloud/download_repos.pm, tests/publiccloud/validate_repos.pm, tests/sles4sap/publiccloud/hana_sr_schedule_deployment.pm
Create validate_repos derived from download_repos. Add this new test module in HanaSr and mr_test scheduled when IS_MAINTENANCE is enabled
- Related ticket: https://jira.suse.com/browse/TEAM-8322
WITH EMBARGOED: http://openqaworker15.qa.suse.cz/tests/208684#step/validate_repos/46
NO REPO: http://openqaworker15.qa.suse.cz/tests/208685#step/validate_repos/26
=> Add new validate_repos test module

tests/migration/online_migration/post_migration.pm
Update first pacemaker and then rest of the packages, pacemaker or some dependency will trigger system reboot, the code does not expect reboot.
IMO it's simple workaround, better than expecting unexpected reboot.
- Verification run: https://openqa.suse.de/tests/11705396
https://openqa.suse.de/tests/overview?version=15-SP1&distri=sle&build=sap
=> Workaround system reboot due to pacemaker

lib/virt_autotest/common.pm, tests/virtualization/external/prepare.pm
Discover hyperV guests without using static IPs
- Related ticket: https://progress.opensuse.org/issues/111383
- Needles: N/A
[15-SP5](https://openqa.suse.de/tests/overview?distri=sle&version=15-SP5&build=%3Atbaev%3A&groupid=322)
[15-SP3](https://openqa.suse.de/tests/overview?distri=sle&version=15-SP3&build=%3Atbaev%3A&groupid=322)
[15-SP4](https://openqa.suse.de/tests/overview?distri=sle&version=15-SP4&build=%3Atbaev%3A&groupid=322)
[12-SP5](https://openqa.suse.de/tests/overview?distri=sle&version=12-SP5&build=%3Atbaev%3A&groupid=322)
[12-SP4](https://openqa.suse.de/tests/overview?distri=sle&version=12-SP4&build=%3Atbaev%3A&groupid=322)
[12-SP3](https://openqa.suse.de/tests/overview?distri=sle&version=12-SP3&build=%3Atbaev%3A&groupid=322)
=> hyperV dynamic ip

tests/containers/bci_test.pm, tests/containers/host_configuration.pm
Apply the known workaround to fix not working ip-forwarding on 15-SP5.
- Related ticket: https://bugzilla.suse.com/show_bug.cgi?id=1213811
- Verification run: https://duck-norris.qe.suse.de/tests/13382
=> Restart firewalld on 15-SP5

lib/main_ltp.pm, tests/kernel/shutdown_ltp.pm
Kernel livepatches don't have the basic incident tests. Add `zypper_lifecycle` test to one of the kernel jobs.
- Related ticket: https://progress.opensuse.org/issues/133514
- Needles: N/A
- SLE-12SP5: https://openqa.suse.de/tests/11712913
- SLE-15SP5: https://openqa.suse.de/tests/11712919 (expected to fail due to broken metadata in a released package)
=> Add zypper_lifecycle test to livepatch LTP jobs

tests/sles4sap/qesapdeployment/deploy.pm
Add Ansible cmd to re-trigger run if it find Azure reboot time out in qesapdeployment/deploy.pm
Add Fail_ok = 1 flag in qesap_upload_crm_report to avoid log collecting failures
- Verification run: AZURE :  http://openqaworker15.qa.suse.cz/t208688
VR with wrong reg_code : http://openqaworker15.qa.suse.cz/tests/209145 (Expected failure)
-VR for Fail_ok flag : http://openqaworker15.qa.suse.cz/tests/209144
- AWS VR : http://openqaworker15.qa.suse.cz/t208689
=> Add Ansible cmd to retry if Azure reboot timeout error found

tests/openqa/webui/test_results.pm
1 job has been created:
- opensuse-Tumbleweed-DVD-x86_64-Build20230604-openqa_bootstrap@64bit -> https://openqa.opensuse.org/tests/3336705
https://openqa.opensuse.org/tests/3336705#step/test_results/14 shows how the openQA is detected on a scrolled down page despite the job actually still running.
=> openQA: Fix finished results hidden out of screen

lib/qesapdeployment.pm, t/09_qesapdeployment.t, tests/sles4sap/qesapdeployment/test_cluster.pm
Always provide a 0 default for failok.
Export qesap_upload_crm_report.
Create an utility function to download the fetch and command playbooks. Remove some argument to local variable translations. Remove not necessary tests on mandatory arguments. Add all relevant unit testing.
- Related ticket: https://jira.suse.com/browse/TEAM-8138
- qesap deployment http://openqaworker15.qa.suse.cz/tests/209586 http://openqaworker15.qa.suse.cz/tests/209587
- qesap deployment with an artificial Ansible failure http://openqaworker15.qa.suse.cz/tests/209589. The failure is intentionally even before that the cluster is initialized. The `crm report` is called as part of other logs collected at each Ansible failure: http://openqaworker15.qa.suse.cz/tests/209589#step/deploy/191  . The `crm …
=> Manage failok in all qesap_ansible functions

lib/main_micro_alp.pm, tests/xfstests/install.pm
Init xfstests in alp main file, and makes it install success remove fio package first, because one of fio dependency build fails in alp.
- Related ticket: https://progress.opensuse.org/issues/132533
> Use create_hdd_xfstests to create qcow2 which xfstests installed, and runs other tests based on that as  HDD_1
> - create_hdd_xfstests http://10.67.133.133/tests/278
> - example for normal sub tests:
> - xfstests_xfs-generic-001-100 http://10.67.133.133/tests/280
> - xfstests_xfs-xfs-001-100 http://10.67.133.133/tests/281
> - xfstests_btrfs-btrfs-001-050 http://10.67.133.133/tests/282
> - xfstests_btrfs-generic-001-100 http://10.67.133.133/tests/283
> - xfstests_ext4-ext4 http://10.67.133.133/tests/284
> - xfstests_ext4-generic-001-100 http://10.67.133.133/tests/285
=> xfstests: Init xfstests in alp main file

lib/y2_module_consoletest.pm, tests/yam/yast_modules/control_center.pm
Enhance how we open/close YaST modules in containers to detect potential problems
-  Related ticket: https://progress.opensuse.org/issues/131069
-  Verification run: https://openqa.suse.de/tests/11615686#step/control_center/4
https://openqa.suse.de/tests/11623715
=> Enhance how we open/close YaST modules in containers to detect potential problems

tests/containers/image.pm
Run the reset_container_network_if_needed method if needed as a workaround for bsc1213811.
- Verification run: https://duck-norris.qe.suse.de/tests/13392
=> Reset container engine for bsc1213811

lib/Installation/InstallationSettings/InstallationSettingsPage.pm, schedule/migration/migration_offline_media_x86_64.yaml, tests/installation/upgrade/accept_keyboard_layout.pm
1a71a734586260e13d889341da429964075309cf  Enable existing libyui-rest-api modules in migration 
See https://progress.opensuse.org/issues/131048
Updates of the yaml schedule schedule/migration/migration_offline_media_x86_64.yaml
50ffb933603d2c3123ef4090109062e674c69efe Modify InstallationSettingsPage to work in migration
The string "SSH port will be" is not visible if ssh is not enabled, so
the subroutine is_loaded_completely can fail in this case.
On the other hand "Boot Loader Type" is always present, so we can use it
in all cases.
f10b0bee1ec13dc19bd00df959552156530bfe69 Add a module to accept keyboard layout
VR https://openqa.suse.de/tests/overview?version=15-SP5&distri=sle&build=JRivrain%2Fos-autoinst-distri-opensuse%2317421
=> Enable existing libyui-rest-api modules in migration 

tests/jeos/firstrun.pm
see https://progress.opensuse.org/issues/133541
=> Allow kvm or zvm for sle-micro when it's s390

products/sle-micro/main.pm
For a while we have been not adding test repositories due to missing `_TEMPLATE` variable. This variable has been deprecated, but the code changes were missing in sle-micro schedule
- ticket: https://progress.opensuse.org/issues/133799
- Verification run: http://kepler.suse.cz/tests/21467#details
=> Drop templates variable from sle-micro's updates schedule

lib/qesapdeployment.pm, t/09_qesapdeployment.t
Take care that PR also change some default. Default was always everywhere 90sec. Now some API has new 180sec
Related ticket:  https://jira.suse.com/browse/TEAM-8110
- 15sp4 azure byos sapconf http://openqaworker15.qa.suse.cz/tests/211173 . From http://openqaworker15.qa.suse.cz/tests/211173/logfile?filename=autoinst-log.txt is now possible to see that `qesa_ansible_script_output` and `qesa_ansible_fetch_file` are now using longer timeout
```
[2023-08-04T17:24:13.951655+02:00] [debug] [pid:69644] <<< testapi::assert_script_run(cmd="ansible-playbook -vvvv script_output.yaml -l \"hana[0]\" -i /root/qe-sap-deployment/terraform/azure/inventory.yaml -u cloudadmin -b --become-user root -e \"cmd='crm status'\" -e out_file='testout.txt' -e remote_path='/tmp/'", quiet=undef, …
```
=> Expose timeout in any qesap_ansible API

tests/kernel_performance/full_run.pm, tests/kernel_performance/install_qatestset.pm
For now, we use `CASEDIR` to run HANA project on our test code. We would like to commit the related modification to upstream, then we could remove the setting `CASEDIR`.
Verification run: http://openqa.qa2.suse.asia/tests/60130#step/full_run/24
=> Integrate HANA test into upstream code

lib/nfs_common.pm, tests/iscsi/iscsi_client.pm
Enlarge timeout value to fix timeout issue on iscsi_client and nfs client_common_tests.
- Failed jobs: https://openqa.suse.de/tests/overview?result=failed&result=incomplete&result=timeout_exceeded&distri=sle&version=15-SP1&build=20230806-1&groupid=421
https://openqa.suse.de/tests/overview?result=failed&result=incomplete&result=timeout_exceeded&distri=sle&version=15-SP3&build=20230806-1&groupid=421
- Needles: N/A
- Verification run: https://openqa.nue.suse.com/tests/11755996#step/yast2_nfs_client/149
https://openqa.nue.suse.com/tests/11756075#details
https://openqa.nue.suse.com/tests/11756077#details
=> Fix timeout issue on iscsi_client and nfs client_common_tests

products/sle-micro/main.pm
The test code was missing adding incident repo(s) in the incident group testing of sle-micro.
- http://kepler.suse.cz/tests/21472#step/install_updates/56
- http://kepler.suse.cz/tests/21473#step/install_updates/320
=> Add incident repo in sle-micro testing

lib/db_utils.pm
In publiccloud the routine to push boottime data to InfluxDB  the _proceed on failure_ option has been updated in order to handle script_output errors and _timeout_ cases too.
- Related ticket: https://progress.opensuse.org/issues/133871
- Needles: N/A
- Verification run: TDB, see next posts
=> push boottime data updated proceed on failure option

tests/sles4sap/qesapdeployment/deploy.pm
This PR is about Re-evaluating the result of Ansible retry cmd when Timeout error is captured in the log.
It is implemented in qesap deploy.pm
- Verification run:  **Azure**:  http://openqaworker15.qa.suse.cz/tests/211672
**Azure** : with wrong reg_code : http://openqaworker15.qa.suse.cz/tests/211673 (Failure is expected to check other return codes and result in case of other failures except for timeout errors.)
**AWS** : http://openqaworker15.qa.suse.cz/tests/211674
=> Re-evaluate return value of Ansible retry cmd

schedule/yast/encryption/cryptlvm+cancel_existing.yaml, schedule/yast/encryption/cryptlvm+cancel_existing_pvm.yaml, schedule/yast/select_modules_and_patterns/select_modules_and_patterns.yaml, schedule/yast/sle/flows/default.yaml, schedule/yast/sle/flows/default_ppc64le.yaml, schedule/yast/sle/flows/default_s390x_kvm.yaml, schedule/yast/sle/flows/default_s390x_zvm.yaml, schedule/yast/sle/flows/default_svirt-xen-hvm.yaml, schedule/yast/sle/flows/default_svirt-xen-pv.yaml, schedule/yast/sle/flows/default_x86_64.yaml
- Related ticket: https://progress.opensuse.org/issues/133880
Due to moving a lot of schedules to YAML_SCHEDULE_DEFAULT based scheduling we only need to change 10 files this time.
=> Add acces_beta_distribution module for SLE 15 SP6

tests/yam/agama/agama_full_disk_encryption.pm, tests/yam/agama/agama_lvm.pm
Change hard coded product names in playwright test specs, add upload trace file for tests/yam/agama/agama_full_disk_encryption.pm.
- Related ticket: https://progress.opensuse.org/issues/133562
- Related Playwright PR: https://github.com/jknphy/e2e-agama-playwright/pull/9
- Needles: N/A
- Verification run:  https://openqa.opensuse.org/tests/3478043#step/agama_lvm/5
https://openqa.opensuse.org/tests/3478044#step/agama_full_disk_encryption/5
The failures are for https://bugzilla.suse.com/show_bug.cgi?id=1213836
=> Change hard coded product names in playwright test specs

lib/containers/utils.pm
Restart the firewall only if it was previously already active to avoid (bsc#1214080)[https://bugzilla.suse.com/show_bug.cgi?id=1214080]
- Related ticket: https://progress.opensuse.org/issues/133808
- Verification run: https://openqa.opensuse.org/tests/3492898
=> Restart firewalld only if active

data/journal_check/bug_refs.json
https://progress.opensuse.org/issues/133586
https://progress.opensuse.org/issues/133544
- Verification run: [SLE-Micro](https://openqa.suse.de/tests/overview?distri=sle-micro&build=rfan08091&version=5.5)
=> Update journal check whitelist for SLE Micro 5.5

lib/main_micro_alp.pm
* **SLE Micro RT** has no kvm support, so disable relevant tests, otherwise it will fail like [this](https://openqa.suse.de/tests/11713080#step/qemu/4).
* **Please** refer to [SLE Micro 5.5 Test Plan](https://confluence.suse.com/display/qasle/Master+Test+Plan+for+SLE+Micro+5.5)
*  **Verification runs:**
* [Loaded slem_installation_virt on x86_64 DVD](http://10.163.28.134/tests/1927)
* [Loaded slem_installation_virt on aarch64 DVD](http://10.163.28.134/tests/1931)
* [Loaded slem_installation_virt on s390x DVD](http://10.163.28.134/tests/1932)
* [Loaded slem_virtualization on x86_64 Default](http://10.163.28.134/tests/1933)
* [Loaded slem_virtualization on aarch64 Default](http://10.163.28.134/tests/1934)
* [Loaded slem_virtualizaiton on s390x Default](http://10.163.28.134/tests/1935)
* …
=> Disable qemu/kvm specific test for SLE Micro RT

data/sles4sap/qe_sap_deployment/qesap_azure_uri.yaml, lib/publiccloud/azure.pm, t/13_publiccloud.t, tests/sles4sap/qesapdeployment/configure.pm
Add two new function in the Azure provider of publiccloud library.
- `get_image_name` to get the filename of the image uploaded in Azure
- `get_os_vhd_uri` to get the uri of the image on the Azure blob server
Add unit tests file for PC
Change qesap regression to use the new API to get image from the blob server.
- Related ticket: [TEAM-8211](https://jira.suse.com/browse/TEAM-8211)
- qesap regression test using `get_os_vhd_uri` and `PUBLIC_CLOUD_IMAGE_LOCATION` that match an image uploaded this morning by some job on OSD  http://openqaworker15.qa.suse.cz/tests/212118 : the overall test is failing for some other reason. The value for `os_image_uri` is ok in the composed `terraform.tfvars` file.  The Terraform deployment is fine …
=> Two new API to Azure provider about image names

lib/Utils/Logging.pm
Simple debug output: the basic_health_check.txt references the command
dh -h and dh -i, but actually the logger calls df -h/-i.
Clarify the log file to use show the correct commands
- Related ticket: N/A - quickfix identified while reading some log files
- Needles: N/A
=> export_healthcheck_basic: fix debug output to reference df instead of dh

schedule/yast/opensuse/autoyast/autoyast_rules_and_classes.yaml
The referenced autoyast profiles select GNOME as the desktop to be
installed. Ensure, openQA expects the same.
- Related ticket: https://progress.opensuse.org/issues/130042
- Needles: N/A
- Verification run: https://openqa.opensuse.org/tests/3492187
=> autoyast_rules_and_classes: specify expected desktop to be GNOME

tests/console/ntp_client.pm
This is a workaround for bsc#1214141.
- Related ticket: https://progress.opensuse.org/issues/133763
- https://openqa.suse.de/tests/11792552
- https://openqa.suse.de/tests/11792553
=> ntp_client.pm: reinstall chrony if pool.conf is empty

data/sles4sap/qe_sap_deployment/mr_test_azure_uri.yaml, data/sles4sap/qe_sap_deployment/sles4sap_azure_generic_uri.yaml, tests/sles4sap/publiccloud/qesap_terraform.pm
Related ticket: [TEAM-8211](https://jira.suse.com/browse/TEAM-8211)
Note: content of https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/17549/ is useful to understand this PR
Verification run
- HanaSR with OS image from CSP catalog (so should not use code I changed) http://openqaworker15.qa.suse.cz/tests/212573
- sle-15-SP5-Azure-SAP-BYOS-x86_64-Build0290-azure_sap_byos_hanasr_sapconf  https://openqa.suse.de/tests/11787078
- sle-15-SP5-Azure-SAP-BYOS-x86_64-Build0290-sles4sap_gnome_saptune_notes https://openqa.suse.de/tests/11787084
- sle-15-SP5-Azure-SAP-BYOS-x86_64-Build0290-azure_sap_byos_qesap_saptune (qesap regression on OSD, should not be influenced by code changes in this PR) https://openqa.suse.de/tests/11787080
-
=> Change the way to populate os_image_uri

lib/virt_autotest/utils.pm, tests/virt_autotest/login_console.pm
1. To improve the function 'is_monolithic_libvirtd()', adding a warning message for checking whether libvirt package installed or not. (lib/virt_autotest/utils.pm)
2. Skip libvirt service checks for kubevirt tests. (tests/virt_autotest/login_console.pm)
- Related ticket: https://progress.opensuse.org/issues/132608
- Verification run: https://openqa.suse.de/tests/11760650
=> Improve libvirt checks for login_console test module

tests/update/updates_packagekit_gpk.pm
https://progress.opensuse.org/issues/133589
We may need to close one more pop-up window
VR: [leap/tw](https://openqa.opensuse.org/tests/overview?distri=opensuse&build=rfan0811)
Needle has been updated via openQA webUI
=> close pop-up windows for updates_packagekit_gpk

lib/main_ltp.pm, tests/kernel/shutdown_ltp.pm
Reverts os-autoinst/os-autoinst-distri-opensuse#17513
- Related ticket: https://progress.opensuse.org/issues/133514
- Needles: N/A
- Verification runs: N/A
Running the `zypper_lifecycle` test on kernel-livepatch package updates is pointless, the lifecycle data has its own package which gets updated in separate incidents.
=> Revert "Add zypper_lifecycle test to livepatch LTP jobs"

schedule/yast/autoyast/autoyast_rules_and_classes.yaml, schedule/yast/installer_extended/installer_extended_aarch64.yaml
Fix a few yaml schedule files for yast cases.
- https://openqa.suse.de/tests/11820454# (updated the autoyast profile path to yam/autoyast/)
- https://openqa.suse.de/tests/11820453#step/switch_keyboard_layout/1 (to correct the test module sequence)
=> Fix a few yaml schedule files for yast cases

data/autoyast_sle15/hpc/create_hdd_textmode_aarch64.xml.ep, data/autoyast_sle15/hpc/create_hdd_textmode_x86_64.xml.ep
This is a workaround as the `sle-module-python3` is not available and blocks the installation. This obviously needs to be addressed and be reverted asap we get the expectations/requirements.
- Related ticket: https://progress.opensuse.org/issues/134192
- Verification run: https://aquarius.suse.cz/tests/18171
=> Exclude python3-module from 15-SP6 AY profile

tests/installation/disable_grub_timeout.pm
Sometimes timeout is not set to -1, the typing is somehow interrupted
Typed is only '-' and this will set timeout to 0
Pressing down will decrease the value, 0 to -1, -1 is the lowest value
- Related ticket: https://progress.opensuse.org/issues/134183
- Verification run: https://openqa.suse.de/tests/overview?build=grub2_timeout
=> Press down on textmode installation

tests/autoyast/installation.pm
Checking var IPXE or IPXE_UEFI to set pxe_boot_done as 1, during ipxe boot, no boot menu displayed during ipxe boot, so we need not expected any needles.
- Related ticket: https://progress.opensuse.org/issues/134030
- Needles: N/A
- Verification run: http://10.67.129.4/tests/60424
=> Set no wait boot during ipxe autoyast installation

schedule/yam/agama/agama_installation.yaml, tests/yam/agama/patch_agama_opensuse.pm
Fixing failure caused by https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/17586
VR: http://falafel.suse.cz/tests/1295
The new failure is due to the agama_base. We decided to create a new test: https://progress.opensuse.org/issues/134228
=> Fix assert_screen for agama_installation

lib/transactional.pm, tests/transactional/install_updates.pm
RT kernel's scriptlet is failing therefore the whole snapshot is discarded and the rest of the testing is without other updates that are currently in the queue.
- Related ticket: https://progress.opensuse.org/issues/134240
- VRs
* http://kepler.suse.cz/tests/21523#
* http://kepler.suse.cz/tests/21522#
=> Add workaround for bsc#1213991

lib/main_micro_alp.pm
Solve xfstests boot fail in aarch64 when using qcow2 HDD in alp. Using boot_hdd_image instead to boot from qcow2.
- Related ticket: https://progress.opensuse.org/issues/134099
- ALP
- aarch64: https://openqa.suse.de/tests/11835628
- x86_64: https://openqa.suse.de/tests/11835822
- SLE15SP6
- aarch64: https://openqa.suse.de/tests/11836023
- x86_64: https://openqa.suse.de/tests/11836039
=> xfstests: Solve aarch boot from qcow2 fails in alp

lib/containers/engine.pm, lib/main_containers.pm, tests/containers/volumes.pm
Add tests for volumes
- Related ticket: https://progress.opensuse.org/issues/133910
- sle-15-SP4-Server-DVD-Updates-x86_64-Build20230814-1-docker_tests@64bit -> https://openqa.suse.de/t11851425
- sle-15-SP4-Server-DVD-Updates-x86_64-Build20230814-1-podman_tests@64bit -> https://openqa.suse.de/t11851093
- sle-15-SP2-Server-DVD-Updates-x86_64-Build20230815-1-docker_tests@64bit -> https://openqa.suse.de/t11851118
- opensuse-Tumbleweed-DVD-x86_64-Build20230814-containers_host_podman@64bit -> https://openqa.opensuse.org/t3511540
- opensuse-Tumbleweed-DVD-x86_64-Build20230814-containers_host_docker@64bit -> https://openqa.opensuse.org/t3511560
=> containers: Add tests for volumes

tests/wsl/install_from_MSStore.pm
The default timeout is not enough in order to disable Hyper V feature.
- ticket: https://progress.opensuse.org/issues/132731
- Verification run: http://kepler.suse.cz/tests/21533#
=> Disabling Hyper V feature takes more time

tests/containers/volumes.pm
Fix for failing job: https://openqa.opensuse.org/tests/3513038#step/volumes_docker/12
`mkdir: cannot create directory ‘test_dir’: File exists
`
- opensuse-Tumbleweed-JeOS-for-kvm-and-xen-x86_64-Build20230816-jeos-container_host@64bit_virtio-2G -> https://openqa.opensuse.org/t3513256
=> containers: remove test directory

lib/Distribution/Sle/15_current.pm, lib/Installation/NTPConfiguration/NTPConfigurationPage.pm, schedule/yast/sle/flows/default_slem.yaml, tests/yam/ntp_configuration.pm
Create new libyui-rest-api based test modules for ntp_config_settings
- Related ticket: https://progress.opensuse.org/issues/133001
- Verification run: https://openqa.suse.de/tests/11857438
s390x: https://openqa.suse.de/tests/11820003#step/ntp_configuration/1
aarch64: https://openqa.suse.de/tests/11821383#step/ntp_configuration/1
=> Create new libyui-rest-api based test modules for ntp_config_settings

data/yam/autoyast/support_images/create_hdd_hpc_development_node_aarch64.xml.ep, data/yam/autoyast/support_images/create_hdd_hpc_development_node_x86_64.xml.ep, data/yam/autoyast/support_images/create_hdd_hpc_management_server_aarch64.xml.ep, data/yam/autoyast/support_images/create_hdd_hpc_management_server_x86_64.xml.ep, data/yam/autoyast/support_images/create_hdd_hpc_textmode_aarch64.xml.ep, data/yam/autoyast/support_images/create_hdd_hpc_textmode_x86_64.xml.ep
Open the update flag for hpc installation autoyast profiles to recieve the latest update during installation.
- Related ticket: https://progress.opensuse.org/issues/134222
[Jobs of installation](https://openqa.suse.de/tests/overview?distri=sle&version=15-SP5&build=20230814-1&groupid=251)
[Job to confirm the installation above](http://openqa.suse.de/tests/11839243#step/zypper_patch/6)  received the latest updates
- Related mr: [mr1](https://gitlab.suse.de/coolgw/wegao-test/-/merge_requests/324#970720112fbd10d6a14a624c984af6d5c29432d2) and [mr2](https://gitlab.suse.de/qa-maintenance/qam-openqa-yml/-/merge_requests/584)
=> Open the update flag for hpc installation autoyast profiles

lib/main_containers.pm
Rootless podman test case is failing with unexpected list of capablities when container is spawned with `keep-id` option on sle15-sp2. Tested with multiple kernel versions and the podman packages are same for a long time. Further investigation is needed but we should not block updates
- Verification run: http://kepler.suse.cz/tests/21542#
=> Unschedule rootless podman test case on <=15-SP2

tests/security/apparmor_profile/usr_sbin_smbd.pm
It is faster and more accurate to use `assert_and_click` to focus on the address bar.
- Related ticket: https://progress.opensuse.org/issues/134330
- Verification run: https://openqa.opensuse.org/tests/3515713#step/usr_sbin_smbd/61
=> usr_sbin_smbd: use 'assert_and_click' instead of 'send_key'

schedule/yast/clone_system/clone_system_pvm.yaml
We need to fix the typo for system_validation in clone_system_pvm.yaml
- Related ticket:  Quick PR
- Needles: N/A
* https://openqa.suse.de/t11889071
=> Fix typo for system_validation

lib/Installation/NTPConfiguration/NTPConfigurationPage.pm
Chain the functions to the libyui-rest-api based test modules for ntp_config_settings
- Verification run: https://openqa.suse.de/tests/11890159#
=> Chain the functions to the libyui-rest-api based test modules for ntp_config_settings

tests/sles4sap/publiccloud/qesap_terraform.pm
Avoid to call the API when the job is not configured to use and image uploaded from IBS
- Related ticket: [TEAM-8211](https://jira.suse.com/browse/TEAM-8211)
URI IMAGE sle-15-SP5-Azure-SAP-x86_64-Build0296-sles4sap_gnome_saptune_delete_rename@az_Standard_E8s_v3 -> http://openqaworker15.qa.suse.cz/tests/216177  http://openqaworker15.qa.suse.cz/tests/216575
CATALOG IMAGE sle-15-SP5-Azure-SAP-BYOS-Incidents-saptune-x86_64-Build:30243:rpm-sles4sap_gnome_saptune_solutions@az_Standard_E8s_v3 -> http://openqaworker15.qa.suse.cz/tests/216178 http://openqaworker15.qa.suse.cz/tests/216574
=> qesap_terraform only call get_blob_uri for uploaded images tests

schedule/qam/common/mau-extratests2.yaml
- Related ticket: https://progress.opensuse.org/issues/129205
- Needles: N0
[15-SP4](http://openqa.suse.de/tests/11860047#step/suseconnect/1)  | [15-SP5]( http://openqa.suse.de/tests/11869515)
=> add suseconnect test in 15-SP4 and 15-SP5

lib/registration.pm
https://progress.opensuse.org/issues/134423
https://bugzilla.suse.com/show_bug.cgi?id=1214234
[SLES](https://openqa.suse.de/tests/11888696)
[SLED](https://openqa.suse.de/tests/11888689)
Based on the test result, the workaround can not work perfectly on sled tests, we may need to file a new ticket.
=> Add new workaround for nvidia repo not reliable with new hot-key

lib/containers/urls.pm
The registry link to released 15-SP5 container was missing.
- ticket: https://progress.opensuse.org/issues/134465
- VR: http://kepler.suse.cz/tests/21564
=> Add link for released 15-SP5 base container

schedule/qam/common/mau-extratests2.yaml
Reverts os-autoinst/os-autoinst-distri-opensuse#17547
Planning to move suseconnect test to a separate job.
=> Revert "add suseconnect test in 15-SP4 and 15-SP5"

data/containers/autoyast_containers.xml.ep
Update AY template for newer sle15-SP5,6.
The initial problem that pointed to the unmaintained AY profile was that s390x image was [not reachable over ssh](https://openqa.suse.de/tests/11902986#step/console/2)
- ticket: https://progress.opensuse.org/issues/134465
- [sle-15-SP6-Online-s390x-Build13.4-create_hdd_autoyast_containers@s390x-kvm-sle12](https://openqa.suse.de/tests/11903853)
=> Update container AY template

lib/publiccloud/utils.pm, tests/publiccloud/ssh_interactive_start.pm, tests/transactional/enable_selinux.pm
Refactor the `allow_openqa_port_selinux` function to be used in `ssh_interactive_start`. This is needed to allow access to openQA resources from the moment the tunnel was established onwards, e.g. for `instance_overview`.
- Related ticket: https://progress.opensuse.org/issues/134450
- Verification run: https://duck-norris.qe.suse.de/tests/13480
=> Refactor allow_openqa_port_selinux

lib/bootloader_setup.pm
New custom grub entries added parameters to the beginning of kernel command line. This change will add them at the end of command line to allow overwriting (by order) existing parameters.
Alternative approach to  https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/17593. New solution is more simple and more powerful and extends already existing functionality.
- Related ticket:  none
GRUB_PARAM=debug_pagealloc=on;ima_policy=tcb;selinux=0;enforcing=0
adds two new options to disable SELinux, one entry will disable completely, the other one will permissive mode on
installation: https://openqa.suse.de/tests/11897495#
boot (GRUB_BOOT_NONDEFAULT= 3): https://openqa.suse.de/tests/11897572#step/boot_ltp/5
Comparison of test result:
With SELinux: …
=> Swap order of kernel parameters for new grub entries

data/yam/agama/auto/alp_dolomite.jsonnet, tests/yam/agama/agama_lvm.pm
Update jsonnet profile to set product as 'Dolomite'.
- Related ticket: https://progress.opensuse.org/issues/134117
- Needles: N/A
- Verification run: https://openqa.opensuse.org/tests/3524946#details
It shown installation finished successful but in fact failed to start installation.
=> Fix Agama Dolomite auto installation fails due to product changes

lib/main_containers.pm, tests/containers/buildx.pm, tests/containers/volumes.pm
The legacy builder is deprecated since Docker v23.0:
https://github.com/docker/cli/blob/master/docs/deprecated.md#legacy-builder-fallback
This PR adds a basic test for buildx in Tumbleweed.  Later on we must also check whether it was pulled as a hard-dependency, expand it for SLE and so on.
- Related ticket: https://progress.opensuse.org/issues/134468
- microos-Tumbleweed-DVD-x86_64-Build20230822-container-host@64bit -> https://openqa.opensuse.org/t3527186
- opensuse-Tumbleweed-DVD-x86_64-Build20230822-containers_host_docker@64bit -> https://openqa.opensuse.org/t3527187
=> containers: Test buildx

schedule/qam/common/mau-extratests2.yaml
https://progress.opensuse.org/issues/134591
VR: N/A
We are safe to remove this single test module
=> Unschedule gpg for all arch and all SLE versions for QE-Core

schedule/sles4sap/sles4sap_ibsm_embargo_check.yml, tests/sles4sap/publiccloud/check_ibsm_embargoed.pm
A new test is added, using a single node with peering to azure IBSM, that fails with an appropriate message if an embargoed update exists on the IBSMirror.
- Related ticket: https://jira.suse.com/browse/TEAM-8325
WITHOUT EMBARGOED UPDATE: http://openqaworker15.qa.suse.cz/tests/217441
WITH EMBARGOED UPDATE: http://openqaworker15.qa.suse.cz/tests/217440
=> Add azure ibsm embargo test

tests/publiccloud/transfer_repos.pm
Fix newline issue with transfer_repos
- Related ticket: https://progress.opensuse.org/issues/134597
- Failing job: https://openqa.suse.de/tests/11904992#step/transfer_repos/333
- Verification run: sle-15-SP4-AZURE-BYOS-Updates-x86_64-Build20230823-1-publiccloud_ahb@64bit -> https://openqa.suse.de/t11911831
=> pc: Fix newline issue with transfer_repos

lib/saltbase.pm, tests/network/wireguard.pm, tests/x11/vnc_two_passwords.pm
Trivial replacement of newlines in `script_run()` commands with escape sequences which will be interpreted by the shell instead.
- Needles: N/A
- salt_minion: https://openqa.opensuse.org/tests/3528834
- wireguard: https://openqa.opensuse.org/tests/3528836
- vnc_two_passwords: https://openqa.opensuse.org/tests/3528837
=> Fix multiline commands in saltbase, wireguard and vnc_two_passwords

lib/qesapdeployment.pm, lib/sles4sap_publiccloud.pm, lib/sles4sap_publiccloud_basetest.pm, lib/trento.pm, t/09_qesapdeployment.t, tests/sles4sap/publiccloud/qesap_terraform.pm, tests/sles4sap/qesapdeployment/deploy.pm, tests/sles4sap/qesapdeployment/test_cluster.pm
Provider is a mandatory argument for the get_inventory and get_terraform_dir API. Terraform_dir calculated in a single place.
- sle-15-SP4-Trento-PremiumRolling-x86_64-BuildRolling2.1.0-build62.3-trento_test@64bit -> http://openqaworker15.qa.suse.cz/tests/217065
- sle-15-SP4-HanaSr-Azure-Byos-x86_64-Build15-SP4_2023-08-23T04:03:13Z-hanasr_azure_test_sapconf@64bit -> http://openqaworker15.qa.suse.cz/tests/217061
- GCP : sle-12-SP5-Qesap-Gcp-Byos-x86_64-BuildLATEST_GCE_SLE12_5_BYOS-qesap_gcp_saptune_test -> http://openqaworker15.qa.suse.cz/tests/217055 :green_circle: 
- AZURE :
- Image uploaded by `publiccloud_upload_img` sle-15-SP5-Qesap-Azure-Byos-Ibs-x86_64-BuildLATEST_AZURE_SLE15_5_BYOS_IBS-qesap_azure_uri -> http://openqaworker15.qa.suse.cz/tests/217056
- catalog images …
=> Provider as mandatory argument for few qesapdeploy API

tests/fips/gnutls/gnutls_server.pm
Replace newlines with escaped newlines to avoid multiline scripts in openQA.
- Verification runs: [s390x](https://openqa.suse.de/tests/11913033) | [aarch64](https://openqa.suse.de/tests/11913035) | [x86_64](https://duck-norris.qe.suse.de/tests/13486)
=> Remove multiline scripts

schedule/yam/agama_auto_tumbleweed.yaml, tests/yam/validate/validate_apparmor.pm
Utilize tests/security/selinux/sestatus.pm to check selinux in test suite agama_auto_dolomite.
Utilize tests/security/apparmor/aa_status.pm to check apparmor in test suite agama_auto_tumbleweed.
- Related ticket: https://progress.opensuse.org/issues/133046
- Needles: N/A
- Verification run: https://openqa.opensuse.org/tests/3445906#
https://openqa.opensuse.org/tests/3531862#
=> Check status of Linux Security Modules for respective products as a basic validation for installations

lib/main_common.pm
No zsh in there.
- Verification run: https://openqa.opensuse.org/tests/3532597
=> lib/main_common.pm: Skip snapper_jeos_cli in staging

tests/console/dracut_enhanced.pm
With serial terminal dracut output does not go into VNC console
Decrease absurd timeout
- Related ticket: https://progress.opensuse.org/issues/132392
- Verification run: https://dzedro.suse.cz/tests/1750
=> dracut_enhanced: Use serial terminal

products/sle/main.pm, tests/virt_autotest/install_package.pm, tests/virt_autotest/login_console.pm, tests/virt_autotest/reboot_and_wait_up.pm, tests/virt_autotest/update_package.pm
With host installation by autoyast, some configuration functionalities of install_package and update_package get duplicate so adding conditional statements to avoid their execution.
https://progress.opensuse.org/issues/132836
- Related ticket: https://progress.opensuse.org/issues/132836
- Needles: no
- prj2_host_upgrade_sles12sp5_to_developing_kvm, http://10.67.183.130/tests/3787
- prj2_host_upgrade_sles12sp5_to_developing_xen, http://10.67.183.130/tests/3803
- prj2_host_upgrade_sles15sp4_to_developing_xen (GUI install), https://openqa.suse.de/tests/11641701
- prj2_host_upgrade_sles15sp4_to_developing_xen, https://openqa.suse.de/tests/11637657
- prj2_host_upgrade_sles15sp4_to_developing_kvm, https://openqa.suse.de/tests/11739188
- …
=> Avoid duplicate configuration in update_package.pm

schedule/qam/common/mau-registration-stack.yaml, tests/console/suseconnect.pm
Introduce suseconnect test in a new testsuite in SLE 15-SP4 and 15-SP5
MR:  https://gitlab.suse.de/qa-maintenance/qam-openqa-yml/-/merge_requests/586
- Related ticket:  https://progress.opensuse.org/issues/129205
- Needles: No
=> Add testuite for suseconnect test

lib/publiccloud/azure.pm
Due to recent changes in Azure image upload logic ( move to image galaries )
we start to have jobs where ONLY OFFER is defined and default value used for SKU
This change was not addresed in get_image_id function where we were expecting BOTH
variables to be defined. This patch solving this problem.
=> azure: remove SKU from conditional check which type of image to use

tests/containers/containerd_rmt.pm
This reverts commit c417f3a033de8504dacd299526b67b5e6eb300a4.
Too much time wasted on something that should be run on container-release-bot anyway.  In the mean time we have this test failing blocking updates...
Closing https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/17647
- Related MR: https://gitlab.suse.de/qac/qac-openqa-yaml/-/merge_requests/1311
- Related ticket: https://progress.opensuse.org/issues/134594
- Verification run: https://openqa.suse.de/t11952671
=> Revert "containers: Test rmt image by repo/tag"

lib/virt_autotest/utils.pm
Description:
-- Handling Inaccessible NVIDIA Repository during Unified Guest Installation for Virtualization
-- This PR addresses an issue with repository refresh and GPG key trust logic for the NVIDIA repository which is not accessible.
The following is done:
-- Open a bug to report Nvidia repo is inaccessible for OpenSUSE Tumbleweed: [BUGZILLA](https://bugzilla.suse.com/show_bug.cgi?id=1214592)
-- By adding zypper in with "--import...key" option works and this fixes the Nvidia repo issue.
- Related ticket: https://progress.opensuse.org/issues/134333
- Verification run: [KVM_rebel6](https://openqa.opensuse.org/tests/3536968) , [KVM_rebel5](https://openqa.opensuse.org/tests/3536704) and [XEN_rebel6](https://openqa.opensuse.org/tests/3537217#comments)
Small change, Welcome review!! Thanks …
=> Handling Inaccessible NVIDIA Repository during Unified Guest Installation

lib/utils.pm, tests/kernel/install_ltp.pm
LTP installation from Git uses dependencies which are available only on some SLE versions. Zypper does not install anything in non-interactive mode if any package in the install list is missing and installing packages one by one is slow, especially on aarch64. Add a helper function which will search for available packages in the install list and then install only those that were found by exact name match. This speeds up aarch64 LTP installation from git by up to 12 minutes.
- Needles: N/A
- SLE-12SP5 x86_64: https://openqa.suse.de/tests/11863069
- SLE-15SP3 aarch64: https://openqa.suse.de/tests/11862537 (cloned from: https://openqa.suse.de/tests/11843610)
=> install_ltp: Optimize installation of optional Git dependencies

lib/containers/docker.pm, lib/containers/engine.pm, lib/containers/podman.pm, lib/containers/utils.pm, tests/containers/rootless_podman.pm, tests/containers/validate_btrfs.pm
Rework container's engine::info to return plain output or `json` for
futher processing. Use the json output to select detected container's
storage drive that can be used in test modules.
- ticket: [[podman] Add check for storage engine](https://progress.opensuse.org/issues/134366)
* [sle-15-SP5-JeOS-for-kvm-and-xen-Updates-x86_64-Build20230829-1-jeos-containers-docker@64bit-virtio-vga](http://kepler.suse.cz/tests/21722)
* [sle-15-SP6-JeOS-for-kvm-and-xen-x86_64-Build1.5-jeos-containers-podman@uefi-virtio-vga](http://kepler.suse.cz/tests/21721#step/rootless_podman/109)
* [sle-15-SP3-Server-DVD-Updates-x86_64-Build20230829-1-podman_tests@64bit](http://kepler.suse.cz/tests/21720#step/rootless_podman/119)
* [sle-15-SP5-Server-DVD-Updates-x86_64-Build20230829-1-docker_tests@64bit](http://kepler …
=> Get container storage

lib/Yam/agama/agama_base.pm, tests/yam/agama/agama.pm
- Description: Enable logs upload for agama playwright tests
- Related ticket: https://progress.opensuse.org/issues/134690
- Verification run: [overview](https://openqa.opensuse.org/tests/overview?build=manfredi%2Fos-autoinst-distri-opensuse%23issues-134690&distri=alp&version=agama-3.0-staging)
=> Enable logs upload for agama playwright tests

tests/kernel/install_ltp.pm
LTP tests for unsupported (by SUSE) kernel modules fail on SLE-12SP5 because the required modules are provided through the `kernel-default-extra` package but unlike SLE-15, there is no modprobe config file allowing them to be loaded. Skip installing `kernel-default-extra` on SLE-12 and earlier.
- Related ticket: https://progress.opensuse.org/issues/129577
- Needles: N/A
- SLE-12SP5: https://openqa.suse.de/tests/11977706#step/install_ltp/179 (should not be installed)
- SLE-15SP1: https://openqa.suse.de/tests/11977708#step/install_ltp/179 (should be installed)
=> install_ltp: Don't install kernel-default-extra on SLE-12

lib/main_micro_alp.pm
SLE15 will not be 2038-proof, that should only go to ALP base.
=> Disable 2038 year detection in SLE Micro

lib/main_containers.pm
Don't test CNI on ALP
- Failing test: https://openqa.suse.de/tests/11975226#step/volumes_podman/20
- Verification run: https://openqa.suse.de/tests/11981054
=> containers: Don't test CNI on ALP

data/yam/autoyast/eula.xml
- Description: Update autoyast profile of data/yam/autoyast/eula.xml to resolve module dependent issues
- Related ticket: https://progress.opensuse.org/issues/134105
- Verification run: [Flavor full](https://openqa.suse.de/tests/overview?distri=sle&version=15-SP6&build=manfredi%2Fos-autoinst-distri-opensuse%23issues-134105)
=> Update autoyast profile of eula.xml to resolve module dependent issues

data/autoyast_sle15/autoyast_hpc_aarch64.xml.ep, data/autoyast_sle15/autoyast_hpc_x86_64.xml.ep
We had fixed this for the other installations which use yaml profiles. that should be the only one which need to get updated.
=> [HPC] Exclude python2 modules from 15sp6 autoyast

schedule/hpc/installation_node_dev.yaml, schedule/hpc/installation_server.yaml
New SLE version is missing the proper scheduling for HPC.
=> [HPC] Add user_settings_root on yaml schedulers for 15-SP6

lib/hpcbase.pm, tests/hpc/slurm_master.pm
Slurm logs are missing when job is successful and they are fetched only when job is failing.
[slurm_master_backup_db](https://aquarius.suse.cz/tests/18399)
[slurm_master](https://aquarius.suse.cz/tests/18396)
=> Upload slurm logs

lib/virt_autotest/virtual_network_utils.pm
The root cause of the problem is that the output of the 'dig +short openqa.suse.de' command has changed when OpenQA OSD (OpenQA On-Demand) moves to the 'prg2' environment.
poo: https://progress.opensuse.org/issues/135113
- Related ticket: https://progress.opensuse.org/issues/135113
- Needles: N/A
- Verification run: [sle-15-SP5-Server-DVD-Virt-XEN-Incidents-x86_64-Build:S:M:29955:305838:-qam-xen-networking@64bit-ipmi](http://openqa.qam.suse.cz/tests/59953), [sle-15-SP5-Server-DVD-Virt-KVM-Incidents-x86_64-Build:S:M:29955:305838:-qam-kvm-networking@64bit-ipmi](http://openqa.qam.suse.cz/tests/59949)
=> Fix new server domain issue

lib/main_micro_alp.pm, tests/transactional/disable_timers.pm, tests/transactional/host_config.pm
To avoid test run interruptions, disable possible disruptive timers on the test host. This must happen only selectively, and if applied after `services_enabled.pm` is executed.
- Related ticket: https://progress.opensuse.org/issues/134999
- Verification run: [SLEM 5.3 autoyast](https://duck-norris.qe.suse.de/tests/13508#step/disable_timers/1) | [SLEM 5.3 selinux](https://duck-norris.qe.suse.de/tests/13509#step/disable_timers/1) | [MicroOS](https://duck-norris.qe.suse.de/tests/13512#step/disable_timers/1)
=> Disable disruptive timers

lib/qam.pm
Adding specific/unique customer repo for 15-SP4-TERADATA
When adding specific customer repo don't add shared customer repos
IMO repos should be added with add_test_repositories to avoid
conflicts between repos and to don't mix repos together
- Related ticket: https://progress.opensuse.org/issues/131498
https://dzedro.suse.cz/tests/1780
https://dzedro.suse.cz/tests/1784
=> Use variable to define extra cutomer repos

tests/containers/bci_prepare.pm
Remove the BCI-tests directory before a test run to ensure it does not already exist.
- Related failure: https://duck-norris.qe.suse.de/tests/13746#step/bci_prepare/69
- Verification run: https://duck-norris.qe.suse.de/tests/13781#step/bci_prepare/68
=> Ensure BCI directory doesn't exist

tests/wsl/prepare_wsl_feature.pm
Any SMB request from 10.0.2.4 fails on the client side for unclear reasons. Enabling "InsecureGuestLogon" only changes the error.
- Related ticket: https://progress.opensuse.org/issues/126083
- Needles: Already created on o3
- Verification run: https://openqa.opensuse.org/tests/3548234
CC @pablo-herranz (for some reason I can't request a review) and @ggardet
=> wsl/prepare_wsl_feature.pm: Use http download as workaround for broken smb on Arm

data/virt_autotest/host_unattended_installation_files/autoyast/dev_host_12.xml.ep, data/virt_autotest/host_unattended_installation_files/autoyast/dev_host_15.xml.ep
- Related ticket: https://progress.opensuse.org/issues/134261
- Verification run: [sle15sp6 kvm host](http://10.67.129.27/tests/96)
@alice-suse @guoxuguang @waynechen55 @nanzhg @RoyCai7 @varunkojha   Welcome reivew!
=> Add harddisk identifiers of all BJ machines to virt autoyast profiles

tests/containers/rootless_podman.pm
Check unresolved configuration files in distro upgrade test suite as old MicroOS used btrfs instead of overlay as storage driver.
- ticket: https://progress.opensuse.org/issues/135017
- [Build20230902-container-host-old2microosnext@64bit](http://kepler.suse.cz/tests/21761#step/rootless_podman/103)
- [Build20230902-container-host@64bit](http://kepler.suse.cz/tests/21758#step/rootless_podman/89)
=> Refresh container's storage.conf

lib/autoyast.pm, lib/ipmi_backend_utils.pm, tests/installation/bootloader_start.pm, tests/installation/ipxe_install.pm
The `ipxe_install` bootloader currently doesn't work for AutoYaST installation jobs. Fix the issue, add iPXE support to `bootloader_start` job module and simplify iPXE boot script handling.
- Related ticket: https://progress.opensuse.org/issues/130219
- Needles: N/A
- https://openqa.suse.de/tests/11998046 (note: `autoyast/installation` module is expected to fail after reboot due to unrelated AutoYaST profile issue)
- https://openqa.suse.de/tests/11998047
=> iPXE bootloader fixes

tests/xfstests/partition.pm
print RAM size of the VM for debug
- Related ticket: https://progress.opensuse.org/issues/135299
- Needles: N/A
- Verification run: http://10.67.129.54/tests/845#step/partition/57
=> xfstests: Add QEMURAM to Size record_info

lib/Yam/agama/agama_base.pm
Developer need the agama service log for some bug analysis, we'd better support it in agama_base.
- Needles: N/A
- Verification run:  https://openqa.opensuse.org/tests/3536809#
=> Add journal log for agama service

data/autoyast_qam/15-common_base_installation.xml.ep, data/autoyast_qam/15_installation.xml.ep, lib/main_common.pm, lib/registration.pm, lib/version_utils.pm, products/sle/main.pm, tests/boot/grub2_test.pm, tests/installation/add_update_test_repo.pm, tests/qa_automation/patch_and_reboot.pm, tests/qam-minimal/install_update.pm, tests/qam-updinstall/update_install.pm
-disable SCC registration for Teradata in autoyast profiles
-update condition in is_updates_tests to accept Teradata Updates
-update condition in is_using_system_role to schedule system_role
-add next key in registration test when registration is skipper &
update behavior add_update_test_repo
-don't auto set SCC_REGISTER=installation for Teradata FLAVOR
-enable basesystem ISO repo after installation in patch_and_reboot
and install_update
- Related ticket: https://progress.opensuse.org/issues/131498
https://openqa.suse.de/tests/overview?distri=sle&version=15-SP4&build=20230904-1&groupid=414 Aggregates
https://openqa.suse.de/tests/overview?distri=sle&build=%3A30538%3Afrr&groupid=521 Incidents
=> Update code for Teradata flavor without SCC reg

tests/fips/openssl/openssl_fips_cipher.pm
des3 and des-ede3 were reporting failure in SLE Micro 5.4 (see # https://bugzilla.suse.com/show_bug.cgi?id=1209271#c8), but in 5.5 behavior is different, possible cause: (1) different worker used z13 vs linuxone (2) or libica not correctly activated In any case with normal s390x kvm worker we don't need to exclude them anymore and from QE perspective we don't have fixed expectations to do it.
- Related ticket: [poo#134321](https://progress.opensuse.org/issues/134321)
- Verification run: [slem_installation_fips](https://openqa.suse.de/tests/12046799)
=> Add des3 and des-ede3 as approved Ciphers in s390x

tests/wsl/prepare_wsl_feature.pm
Add the URL for Arm64.
This test is incredibly slow but it does work with a patched QEMU.
- Related ticket: https://progress.opensuse.org/issues/126083
- Verification run: https://openqa.opensuse.org/tests/3560340#live
CC @pablo-herranz @ggardet
=> wsl/prepare_wsl_feature.pm: Add support for WSL2 on aarch64

data/yam/autoyast/support_images/sles12sp5_install_default_patterns_aarch64.xml, data/yam/autoyast/support_images/sles12sp5_install_default_patterns_ppc64le.xml, data/yam/autoyast/support_images/sles12sp5_install_default_patterns_s390x.xml, data/yam/autoyast/support_images/sles12sp5_install_default_patterns_x86_64.xml
- Description:
* Create support image via autoyast with default patterns on SLE 12 SP5.
- Related MR: N/A
- Test Cases: [**520**](https://openqa.suse.de/admin/job_templates/520?)
- Related ticket: [**132650**](https://progress.opensuse.org/issues/132650)
- Needles: N/A
- [**Autoyast_VRs**](https://openqa.suse.de/tests/overview?arch=&flavor=&machine=&test=sle_autoyast_support_image_gnome_12sp5&modules=&module_re=&distri=sle&version=12-SP5&build=20230820&groupid=520#)
- Migration
* [**x86_64**](https://openqa.suse.de/tests/12047335 )
* [**aarch64**](https://openqa.suse.de/tests/12047339)
* [**s390x**](https://openqa.suse.de/tests/12047332)
* [**ppc64le**](https://openqa.suse.de/tests/12047337)
=> Create support image via autoyast with default patterns on SLE 12 SP5

lib/sles4sap.pm, tests/sles4sap/hana_install.pm
This partially reverts #14964, which replaced the `lib/sles4sap::copy_media` method for a `mount_media` method, enabling both HANA and NetWeaver installation tests to run the installers directly from the NFS mount. In this commit, the `copy_media` method has been added again to the library, and the HANA installation test has been modified to use `copy_media` instead of `mount_media`.
General purpose of the PR is to be able to more easily identify the root cause of some failures. With the current `mount_media` method, a failing installation could have its root in the performance of the SUT, network connection to the NFS server, NFS server performance and more. If we copy the media first and then install from the local copy, we are segmenting the steps, and we can more easily separate …
=> Do not install HANA from NFS. Copy media instead

lib/sles4sap.pm
As many tests re-use a single qcow2 image, the contents of `/etc/machine-id` could be the same in those tests, resulting in the same NFS id per code introduced in the PR #17722. This PR changes this to instead use the *JOBTOKEN* setting which should be unique per job for the whole openQA instance.
- Needles: N/A
- Verification run: https://openqaworker15.qa.suse.cz/tests/223985
=> Do not rely on /etc/machine-id to generate a unique NFS id

data/yam/autoyast/support_images/sles12sp5_install_all_patterns_aarch64.xml, data/yam/autoyast/support_images/sles12sp5_install_all_patterns_ppc64le.xml, data/yam/autoyast/support_images/sles12sp5_install_all_patterns_s390x.xml, data/yam/autoyast/support_images/sles12sp5_install_all_patterns_x86_64.xml
https://progress.opensuse.org/issues/132653
The tests don't set separate /home partition,
so we can allocate more disk space to / partition.
VRs:
[create_hdd_imgs](https://openqa.suse.de/tests/overview?build=rfan0904_new&version=12-SP5&distri=sle)
[Sanity tests with published qcow2 imgs](http://openqa.suse.de/tests/overview?build=rfan0907&version=15-SP6&distri=sle)
=> Create support image via autoyast with all patterns on SLE12SP5

lib/qesapdeployment.pm, tests/sles4sap/qesapdeployment/deploy.pm
Fix GCP sporadic "missing sudo passwd" failure on test module "deploy.pm" when executing ansible playbook, retry the ansible command when hit "missing sudo passwd".
This issue described in "TEAM-8479 - qesap regression GCP 15sp5 failure in Ansible - Missing sudo password" seems to be a race condition.
- Related ticket: https://jira.suse.com/browse/TEAM-8479
- Needles: NA
1. Detected '"msg": "Missing sudo password"' at step: https://openqaworker15.qa.suse.cz/tests/223965#step/deploy/48 and "ansible retry pass" at step: https://openqaworker15.qa.suse.cz/tests/223965#step/deploy/64
2. Here is a normal test cases passed: https://openqaworker15.qa.suse.cz/tests/223966#details
=> Fix GCP sporadic "missing sudo passwd" failure

lib/main_micro_alp.pm
This test was disabled in staging because at the beginning we don't
have SCC and we need to install some cockpit packages. With this
new condition, we can run the test according to SCC variable,
so it's also useful for staging after SCC is in place.
=> Enable Cockpit for Staging in SLE Micro when SCC is available

lib/virt_autotest/virtual_network_utils.pm
Current, our OSD domain use with openqa.oqa.prg2.suse.org instead due to our MOVE PLAN from NUE TO PRG. 
Meanwhile, suppose that there was the network(DNS) performance problem from our current OSD network. 
FYI
```
10.145.10.207 via 10.168.195.254 dev eth1' failed at /usr/lib/os-autoinst/testapi.pm line 926.
testapi::assert_script_run("ssh root\@10.168.193.25 ip r a openqa.oqa.prg2.suse.org.\x{a}10.14"...) called at sle/lib/virt_autotest/virtual_network_utils.pm line 156
virt_autotest::virtual_network_utils::test_network_interface("sles-15-sp5-64-fv-uefi-kvm", "mac", "00:16:3e:32:66:24", "gate", "10.168.195.254", "net", "vnet_host_bridge") called at sle/tests/virt_autotest/libvirt_host_bridge_virtual_network.pm line 72
```
So, we have to use with google.com instead.  …
=> [virt_autotest] Fix up check with openqa domain problem

schedule/security/autoyast_stig_hardening.yaml, tests/security/stig/validate_stig_rules_applied_by_yast.pm
Introduce validation for STIG rules that YaST should apply in the installed system.
- Related ticket: [poo#135311](https://progress.opensuse.org/issues/135311)
- [autoyast_stig_remediation in QU SLE15SP5](https://openqa.suse.de/tests/12080529)
- [autoyast_stig_remediation in SLE15SP5](https://openqa.suse.de/tests/12091834)
example of [error](https://openqa.suse.de/tests/12080164#step/validate_stig_rules_applied_by_yast/20)
=> Validate STIG rules remediated by YaST

t/07_ltp_whitelist.t
`Mojo::File::spurt()` is deprecated, replace it with `Mojo::File::spew()`.
- Needles: N/A
=> Fix Mojo::File::spurt() deprecation warning in LTP unit test

tests/containers/docker_compose.pm
https://bugzilla.suse.com/show_bug.cgi?id=1186691 is resolved and tests are not soft-failing in this step. It's safe to be removed.
=> Remove soft-failure for bsc 1186691 in docker-compose

lib/containers/engine.pm
In podman v2.0 there is error message mixed up with info output.
Issue apparently happens only in s390x with podman v2.0
- ticket: https://progress.opensuse.org/issues/135497
- bug: https://bugzilla.suse.com/show_bug.cgi?id=1200623
- Verification run: https://openqa.suse.de/tests/12092115#step/rootless_podman/82
=> Remove warning/error messages from podman-info output

tests/containers/bci_prepare.pm, tests/containers/helm_rmt.pm
- Failed jobs: https://openqa.suse.de/tests/overview?distri=sle&version=15-SP5&build=9.46_rmt-server-image&groupid=445
- Verification run: sle-15-SP5-BCI-Updates-x86_64-Build9.46_rmt-server-image-_on_ubuntu@64bit -> https://openqa.suse.de/tests/12096338
=> containers: Restrict helm_rmt test to SLE 15-SP3+

tests/jeos/firstrun.pm
Usually images come with empty repo list, but there is an exception for opensuse and ALP.
- Verification run: [alp-1.0-Dolomite-Default-x86_64-Build6.8-alp_image_wizard@64bit](https://openqa.suse.de/tests/12098751)
=> Skip repo check for ALP

data/sles4sap/qe_sap_deployment/sles4sap_azure_generic_maintenance.yaml
Fix failure "ansible-core requires a minimum of Python2 version 2.7 or Python3 version 3.5. Current version: 3.4.10" in pulbic cloud cases 
TEAM-8361 - Only use cloud catalog images in MU JobGroups
- Related ticket: https://jira.suse.com/browse/TEAM-8361
- Needles: NA
**sap12sp5**: 
https://openqaworker15.qa.suse.cz/tests/225386#
The failure can be tracked by new ticket [TEAM-8533](https://sd.suse.com/browse/SD-8533) - "SAPHanaSR-ScaleUp-PerfOpt" failed on "deploy_qesap_ansible": "zypper lr" returns 6 on "vmiscsi01"
**sap15sp1**:  
https://openqaworker15.qa.suse.cz/tests/224668#step/deploy_qesap_ansible/7
**sap15sp3**:  
https://openqaworker15.qa.suse.cz/tests/224660#step/deploy_qesap_ansible/7
The failures on sap15sp1 and sap15sp3 can be tracked by new ticket …
=> Fix public cloud ansible python version failure

lib/sles4sap_publiccloud.pm, tests/sles4sap/publiccloud/hana_sr_takeover.pm
Fix hanasr sporadic takeover failed to complete on AWS  
TEAM-8371 - [HANA SR - PC AWS] - "Stop_site_a-primary" failed on "takeover failed to complete"
- Related ticket: https://jira.suse.com/browse/TEAM-8371
- Needles: NA
I ran for many times and did not hit the "takeover failed to complete":  
https://openqaworker15.qa.suse.cz/tests/214200#step/Stop_site_a-primary/85
(The "Fenced database 'vmhana01' is not offline" error can be tracked by other ticket https://jira.suse.com/browse/TEAM-8139)
=> Fix sporadic takeover failed to complete on AWS

data/journal_check/bug_refs.json
Minimal has combustion now.
- Related ticket: https://build.opensuse.org/request/show/1110652#comment-1821250
- Verification run: https://openqa.opensuse.org/tests/3571943#live
=> data/journal_check/bug_refs.json: Allow no-config-drive for Tumbleweed

tests/yam/agama/agama.pm
Assert tag 'grub2-agama' to avoid can't match in short time.
- Needles: N/A
- Verification run:  https://openqa.opensuse.org/tests/3531888#details       domolite_lvm          
https://openqa.opensuse.org/tests/3531889#step/agama/3     full_encryption
=> Assert tag 'grub2-agama' to avoid can't match in short time

tests/console/sssd_389ds_functional.pm
When doing manual installation of the package: 389_ds, the dir: /var/lib/dirsrv gets the proper ownership. However doing the zypper in while creating the container image results in improper ownership. Due to that the ns-slapd server does not start.
- Related ticket: https://progress.opensuse.org/issues/134177
- Verification run: https://openqa.suse.de/tests/12104508/modules/sssd_389ds_functional/steps/1/src
=> Fix for poo#134177

tests/sles4sap/qesapdeployment/deploy.pm
This PR is about to fix Missing mandatory argument **provider** , which is detected by GCP regression run
Regression from [PR](https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/17643)
Issue found @:http://openqaworker15.qa.suse.cz/tests/225423#step/deploy/59
- Verification run: GCP : http://openqaworker15.qa.suse.cz/tests/226071
AWS : http://openqaworker15.qa.suse.cz/t226072
Azure: http://openqaworker15.qa.suse.cz/tests/226073 (VR With Wrong reg code)
Azure : http://openqaworker15.qa.suse.cz/t226074 (Failed due to [TEAM-8532](https://jira.suse.com/browse/TEAM-8532))
=> fix Missing mandatory argument provider

lib/bootloader_setup.pm
In this sporadic issue there is a visual glitch not showing the lower half of this screen and some residual text as well, so the 'ret' key doesn't reach the SUT. Therefore we can allow the 5-seconds counter to proceed without stopping it, detecting successfully the grub.
- Related ticket: [poo#134384](https://progress.opensuse.org/issues/134384)
- Verification runs: [10x - aarch64_secureboot](https://openqa.suse.de/tests/overview?distri=sle&build=jknphy%2Fos-autoinst-distri-opensuse%23test&version=15-SP3)
=> Avoid stop timer in Secure boot screen in aarch64 

tests/containers/registry.pm
https://github.com/containers/podman/issues/10685 was fixed and backported to podman 3.2.2.
The soft-failure is unreachable anyway because the module is loaded only for SLE 15-SP4+ in `load_host_tests_docker()`: 
https://github.com/os-autoinst/os-autoinst-distri-opensuse/blob/master/lib/main_containers.pm#L130
=> containers: Remove soft_failure for fixed issue

test_data/yam/agama_auto_micro.yaml
- Description: quick PR to fix `os_release_name` in Agama auto installation
- Issues: [overview](https://openqa.opensuse.org/tests/overview?distri=alp&version=agama-3.0-staging&build=4.62&groupid=96)
- Verification run: [overview](https://openqa.opensuse.org/tests/overview?distri=alp&build=manfredi%2Fos-autoinst-distri-opensuse%23issues-product-name&version=agama-3.0-staging)
=> Fix os_release_name in Agama auto installation

data/journal_check/bug_refs.json
Bunch of error messages has been not caught most likely due to left over pipe. https://openqa.suse.de/tests/12122006#
- Verification run: http://kepler.suse.cz/tests/21887#
=> Remove redundant pipe from regex pattern

schedule/yam/agama/agama_install_on_second_disk.yaml
See https://progress.opensuse.org/issues/133073
Agama allows to choose between several installation devices (disks) so we want to test it. Related to https://github.com/jknphy/e2e-agama-playwright/pull/19
VR 
staging https://openqa.opensuse.org/tests/overview?version=agama-3.0-staging&build=JRivrain%2Fos-autoinst-distri-opensuse%2317660&distri=alp
Fails in devel because of recent UI changes. It is necessary to assert that the disk size is detected, as otherwise fails in next step because the locator then says "no devices detected" unless we refresh the page. I included those VRs anyway.
devel https://openqa.opensuse.org/tests/overview?version=agama-3.0-devel&distri=alp&build=JRivrain%2Fos-autoinst-distri-opensuse%2317660
=> Add a new test to select installation device

tests/containers/helm_rmt.pm
Skip the test run on PPC, where k3s is not available.
- Related failure: e.g. https://openqa.suse.de/tests/12099767
- Verification run: [ppc64le](https://openqa.suse.de/tests/12128076) | [x86_64](https://openqa.suse.de/tests/12128077)
=> Skip helm-rmt on PPC

lib/hpc/utils.pm, tests/hpc/slurm_db.pm, tests/hpc/slurm_master.pm, tests/hpc/slurm_master_backup.pm, tests/hpc/slurm_master_backup_db.pm, tests/hpc/slurm_slave.pm, variables.md
Make possible to install and test latest version of the Slurm package. As for now, Slurm is explicitly invoked. But now test should be able to get the latest available versioned Slurm in the system, install it and run the tests.
Those changes are not apply to all the test cases at the moment. Verifications run only against a basic scenario (see hpc_EPSILON) and the test requires a new job variable, SLURM_VERSIONED_TEST.
- Related ticket: https://progress.opensuse.org/issues/130838
https://aquarius.suse.cz/tests/18805# current version
https://aquarius.suse.cz/tests/18763# versioned slurm
=> Integrate Slurm versioned installation

schedule/virt_autotest/install_guest_on_slem_kvm_host.yaml
* **There** is no need to give IPXE setting in job yaml anymore. Such setting can be found in workers and test suite settings if necessary.
=> Remove IPXE setting in SLE-Micro job yaml

tests/yast2_gui/yast2_control_center.pm
Adapt yast2_control_center for start_directory_server
- Related ticket: https://progress.opensuse.org/issues/134444
- Verification run: https://openqa.suse.de/tests/12088500#step/yast2_control_center/91
=> Adapt yast2_control_center for start_directory_server

data/journal_check/bug_refs.json
Follow-up to https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/17773
Some issues had been hidden in the tests due to a bug in some regex. This has been fixed and some (potentially older) issues now surface (and block stagings)
Accept them for now as 'known issues'
- Related ticket: https://bugzilla.opensuse.org/show_bug.cgi?id=1215367, https://bugzilla.opensuse.org/show_bug.cgi?id=1215368
- Needles: N/A
- Verification run: https://openqa.opensuse.org/tests/3578494
=> journal_check: add bug refs for issues that were hidden before 21a82d6

tests/autoyast/console.pm
When we deploy the system with autoyast, there is no reboot after the installation and wait_boot never sees a grub menu, so let's skip this in this case.
This will fix https://openqa.suse.de/tests/11998046 and similar
=> Skip wait_boot for autoyast installations

lib/main_containers.pm, tests/containers/podman_bci_systemd.pm
Testing systemd in a container for the podman engine
- Related ticket: https://progress.opensuse.org/issues/134687
- Verification run: http://openqa.suse.de/tests/12139439
=> Add test for BCI systemd in podman

tests/containers/podman_bci_systemd.pm
When using Proxy SCC, the repos that the container will get from the host will contain wrong URL, therefore failing the zypper ref. This removes the container-suseconnect-zypp so we will have only the BCI repo in the container.
Also forces using the bci init image, otherwise it might use an image from CONTAINER_IMAGE_TO_TEST variable which could be a base image without running systemd by default.
VRs:
- https://openqa.suse.de/tests/12148599
- https://openqa.opensuse.org/tests/3581662#
=> Fix for container systemd test

schedule/yam/create_support_image_module_combinations_updated.yaml
- Description:
* Create support images with modules for the sles12sp5 default pattern
- Related ticket: [**132704**](https://progress.opensuse.org/issues/132704)
- Needles: N/A
*  [**VRS**](https://openqa.suse.de/tests/overview?distri=sle&version=12-SP5&build=20230912-1&groupid=520)
- sle_autoyast_support_image_gnome_12sp5_ids-idu@ppc64le
* https://openqa.suse.de/tests/12133691
-   sle_autoyast_support_image_gnome_12sp5_lp@ppc64le
* https://openqa.suse.de/tests/12116127
-  sle_autoyast_support_image_gnome_12sp5_lp@s390x-kvm-sle12
* https://openqa.suse.de/tests/12116482
-   sle_autoyast_support_image_gnome_12sp5_phub@64bit
*  https://openqa.suse.de/tests/12116113
-  sle_autoyast_support_image_gnome_12sp5_we_lp@64bit
*  https://openqa.suse.de/tests/12116911
=> Create support images with modules for sles12sp5 default pattern

lib/power_action_utils.pm, tests/shutdown/shutdown.pm
Provide visibility when bsc1215132 will hit again raising a softfail.
VR: https://openqa.suse.de/tests/12056939#step/shutdown/10
=> Check systemd depemdencies required from shutdown test module

data/yam/autoyast/support_images/sled15sp5_install_all_patterns_x86_64.xml, data/yam/autoyast/support_images/sled15sp5_install_default_patterns_x86_64.xml
Add two autoyast profiles for SLED15SP5 installation, one is default patterns installation, one is all patterns installation.
- Related ticket: https://progress.opensuse.org/issues/134408
[Create images](https://openqa.suse.de/tests/overview?distri=sle&version=15-SP5&build=20230917-1&groupid=251)
[Verify images](https://openqa.suse.de/tests/overview?arch=&flavor=Migration-from-SLE15-SPx&machine=&test=&modules=&module_re=&distri=sle&version=15-SP6&build=16.1&groupid=251#)
- Related MR: [link](https://gitlab.suse.de/coolgw/wegao-test/-/merge_requests/340)
=> Add autoyast profile for SLED15SP5 installation

tests/containers/helm_rmt.pm
Skip RMT test on k8s as it uses helm
- Failing test: https://openqa.suse.de/tests/12162189
- Verification run: sle-15-SP5-BCI-Updates-x86_64-Build9.48_rmt-server-image-rmt_on_k8s@64bit -> https://openqa.suse.de/t12163867
=> containers: Skip RMT test on k8s as it uses helm

data/journal_check/bug_refs.json
We can soft-fail the jobs which hit the below bug,
https://bugzilla.suse.com/show_bug.cgi?id=1215377
Then add it the whitelist
[Progress tickets](https://progress.opensuse.org/issues/135875)
[VR](https://openqa.suse.de/tests/overview?build=rfan0918&distri=sle-micro&version=5.4)
Please ignore the new failure on aarch64 platform, it is caused by known issue [known bug](https://bugzilla.suse.com/show_bug.cgi?id=1215405)
=> Add whitelist for bsc#1215377 on SLE Micro

lib/maintenance_smelt.pm
Enhance `maintenance_smelt.pm` robustness with extra checks
- Related ticket: https://progress.opensuse.org/issues/135896
- Verification run: https://openqa.suse.de/tests/12166861
=> Add extra check for undefined values

data/journal_check/bug_refs.json
We can soft-fail the jobs cased by bugs below by
adding a new whitelist:
https://bugzilla.suse.com/show_bug.cgi?id=1215405
https://bugzilla.suse.com/show_bug.cgi?id=1215378
- Related ticket: https://progress.opensuse.org/issues/135926
[Yam](https://openqa.suse.de/tests/overview?version=5.5&distri=sle-micro&build=rfan0919)
[Core](https://openqa.suse.de/tests/overview?version=5.5&distri=sle-micro&build=rfan0919_fnc)
**s390x** seems we don't have available resources to run the tests now, but I think it is fine to merge since no issues with x86_64 and aarch64:)
=> Add whitelist for bsc#1215405 and bsc#1215378 on SLE Micro

schedule/yast/textmode/textmode_x86_64.yaml
- Description:
* We need to add system_prepare for textmode uefi and x86_64
-  Ticket: Quick PR
- Needles: N/A
- VR:
* https://openqa.suse.de/tests/12202202
* https://openqa.suse.de/tests/12202203
- Reference: [**bug_1214452**](https://bugzilla.suse.com/show_bug.cgi?id=1214452)
=> Add system_prepare for textmode uefi and x86_64

tests/console/weechat.pm
- Related ticket: https://progress.opensuse.org/issues/134813
- Needles: N/A
- Verification run: https://openqa.opensuse.org/tests/3587136
=> weechat: ssl paramters were renamed to tls in weechat 4.x (poo#134813)

tests/microos/selfinstall.pm
Older selfinstall medium does a reboot after kexec. The install medium needs to be ejected at that point to avoid booting into it again.
- Related ticket: https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/17797#issuecomment-1727220353
- Verification run: http://10.168.4.192/tests/1338
=> microos/selfinstall: Call eject_cd earlier if a forced reboot happens

tests/installation/ipxe_install.pm
UEFI with IPXE boot need not clean boot information, installer can
help to update nvram and make sure the installed OS as default.
According to https://github.com/os-autoinst/os-autoinst/blob/master/doc/backend_vars.asciidoc, please set `IPMI_HW=supermicro` to address UEFI firmware issue in supermicro platform.
- Related ticket: https://progress.opensuse.org/issues/135734
- Needles: N/A
15-SP1: http://10.67.129.4/tests/61202
15-SP2: http://10.67.129.4/tests/61203
15-SP3: http://10.67.129.4/tests/61204
15-SP4: http://10.67.129.4/tests/61207 
15-SP5: http://10.67.129.4/tests/61206
12-SP5: http://10.67.129.4/tests/61205
=> Fix ipxe autoyast installation timeout issue

data/yam/autoyast/support_images/sles12sp5_install_all_patterns_x86_64.xml
- Verification run: [openqa.mypersonalinstance.de/tests/xyz#step/module/x](https://openqa.suse.de/tests/12220201#step/version_switch_origin_system#1/5)
=> Use gpt as disklabel rather than old msdos for root disk

data/yam/autoyast/support_images/sles15sp5_install_minimal_default_patterns_s390x.xml, data/yam/autoyast/support_images/sles15sp5_install_minimal_default_patterns_x86_64.xml
Create support image on SLE 15 SP5 with minimal role
- Related ticket: https://progress.opensuse.org/issues/135695
- Verification run: https://openqa.suse.de/tests/overview?distri=sle&version=15-SP5&build=GM&groupid=220
verified with migration jobs with minimal: https://openqa.suse.de/tests/overview?distri=sle&version=15-SP6&build=20.1&groupid=220
=> Add ay profiles for sles15sp5 with minimal system role

lib/utils.pm, tests/kernel/multipath_iscsi.pm
Enhancement poo#135818: Adds new function ping_size_check, which
will ping defined target with different and increasing size with
disabled packet fragmentation. If is specified size, it will do single ping
check with one size. Main use of this function is in multi machine
jobs for network verification (MTU in GRE tunnel).
- Related ticket: https://progress.opensuse.org/issues/135818
https://openqa.suse.de/tests/12221263  (contains controlled single size demo failure for size 1431)
https://openqa.suse.de/tests/12221377 (standard run)
=> Add network ping check with different packet sizes

lib/publiccloud/instance.pm
Trim the `Connection to *** closed.` suffix from ssh_script_output.
- Related issue: https://openqa.suse.de/tests/12223247#step/slem_basic/247
- Verification runs: [slem-basic](https://duck-norris.qe.suse.de/tests/13945#step/slem_basic/243) | [15-SP5 Azure](https://duck-norris.qe.suse.de/tests/13946#step/check_registercloudguest/80) | [15-SP5 GCE](https://duck-norris.qe.suse.de/tests/13947#step/check_registercloudguest/70)
`ssh_script_output` is mostly used in the consoletests, e.g. in `check_registercloudguest`.
=> Crop the ssh termination suffix

lib/sles4sap.pm
Kernel file `/sys/fs/nfs/net/nfs_client/identifier` was introduced in kernel version 5.3, meaning that the path is not available in SLES for SAP 12-SP5 or 15-SP1. Since the check is mandatory, this causes tests to fail. This commit changes this path for `/sys/module/nfs/parameters/nfs4_unique_id` which is present in older and newer versions of the kernels.
- Related ticket: https://progress.opensuse.org/issues/135923
- Needles: N/A
- Verification run: [15-SP1](https://openqaworker15.qa.suse.cz/tests/231910), [12-SP5](https://openqaworker15.qa.suse.cz/tests/231911), [15-SP5](http://openqaworker15.qa.suse.cz/tests/231912)
=> Change path of NFS client ID kernel file to /sys/module/nfs/parameters/nfs4_unique_id

data/yam/autoyast/support_images/sles12sp5_install_all_patterns_x86_64.xml
https://progress.opensuse.org/issues/132707
VR:
[create_hdd](https://openqa.suse.de/tests/12223680)
[Test with published qcow2](https://openqa.suse.de/tests/12224337)
The wrong configuration is mentioned at https://bugzilla.suse.com/show_bug.cgi?id=1215557
=> Fix disk partitions error for sle12sp5 all patterns

tests/installation/ipxe_install.pm
Adding `IPXE=1` to some IPMI workers had the side effect of breaking libyui tests because `ipxe_install` does not do the required setup normally done by `boot_from_pxe`. Unconditionally configure textmode console and add `EXTRABOOTPARAMS` to iPXE boot script to allow libyui tests to boot using `ipxe_install`.
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/12205773
=> Fix libyui tests on IPXE workers

data/lib/missing_libraries.sh, lib/Utils/Logging.pm, lib/utils.pm
`script_run()` does not allow multiline commands. Move the check for missing libraries to a script file which will be downloaded to the SUT.
Merge before os-autoinst/os-autoinst#2342
- Needles: N/A
- https://openqa.suse.de/tests/11891664 (normal)
- https://openqa.suse.de/tests/11898293 (`OFFLINE_SUT=1`)
Both verification runs are supposed to fail in `boot_ltp` and execute `post_fail_hook` which actually contains the missing libraries check. Compare verification runs to https://openqa.suse.de/tests/11877493#step/shutdown_ltp/188
=> problem_detection: Move missing libraries check to separate shell script file

tests/publiccloud/slem_basic.pm
If the AVC is empty, the `grep` does not match any items and therefore fails. This commit updates the grep command to not fail on empty input.
- Related ticket: https://progress.opensuse.org/issues/136046
- Related failure: https://openqa.suse.de/tests/12229826#step/slem_basic/240
- Verification run: https://duck-norris.qe.suse.de/tests/13951#
=> Fix failing test run on empty AVC

data/wsl/UpdateInstall.vbs, lib/windowsbasetest.pm, schedule/wsl/install/create_windows_image.yaml, schedule/wsl/update_windows.yaml, schedule/wsl/windows_image_update.yaml, tests/wsl/install/ms_win_firstboot.pm, tests/wsl/update_windows.pm
After a lot of research, I've found a VB script created by Microsoft for handling Windows Update API.
- Related ticket: https://progress.opensuse.org/issues/117577
- Needles: *not_needed*
- *OSD*
- [Windows 10 BIOS](https://openqa.suse.de/tests/12128561)
- [Windows 10 UEFI](https://openqa.suse.de/tests/12128157)
- [Windows 11 UEFI](https://openqa.suse.de/tests/12162312)
- *O3*
- [Windows 10 BIOS](https://openqa.opensuse.org/tests/3584928)
- [Windows 10 UEFI](https://openqa.opensuse.org/tests/3585008)
- [Windows 11 UEFI](https://openqa.opensuse.org/tests/3584926)
=> Update Windows OS installation periodically

data/microos/utt-leap.repo
The package provided by the repository has lower version than the installed localy from the data directory. This makes the command transactional-update cleanup to fail with nothing to update. There is a new utt repo with higher version.
https://progress.opensuse.org/issues/136298
VR: https://openqa.opensuse.org/tests/3594587
=> Update UTT repo for Leap Micro

data/autoyast_qam/15-common_base_installation.xml.ep
A bug was introduced in PR17767 failing this [test](https://openqa.suse.de/tests/12216598#)
- Needles: N/A
- Verification run:  https://openqa.suse.de/tests/12224960
=> fix for a bug introduced in PR17767

tests/cpu_bugs/mitigations.pm
Fix the issue for spectre_v2 on skylake machine
- Related ticket: https://progress.opensuse.org/issues/136091
- Verification run:http://10.67.129.4/tests/62267 (sle15sp5 maintain update)
=> Fix the issue for spectre_v2 on skylake machine

schedule/sle-micro/yam/slem_extensions_and_modules_aarch64.yaml, schedule/sle-micro/yam/slem_extensions_and_modules_s390x.yaml, schedule/sle-micro/yam/slem_extensions_and_modules_x86_64.yaml, schedule/sle-micro/yam/slem_installation_default_s390x.yaml, schedule/sle-micro/yam/slem_installation_default_x86_64.yaml, schedule/sle-micro/yam/slem_installation_default_zvm.yaml, schedule/yast/sle/flows/default_slem.yaml
Added commented schedule to default, so we just need to [un]comment the default file when needed.
=> un-schedule access_beta_distribution for sle-micro

tests/virtualization/universal/patch_guests.pm
The testing process for Teradata on SLES15SP4 did not include the installation of packages, indicating an apparent lack of real testing
- Related ticket:  https://progress.opensuse.org/issues/136334
- Verification run: [sles15sp4 teradata](https://openqa.suse.de/tests/12230065#step/patch_guests/34), [sles12sp5 no teradata](https://openqa.suse.de/tests/12230305)
=> Fix sles15sp4 teradata fake test

lib/mr_test_lib.pm, lib/sles4sap_publiccloud.pm, lib/sles4sap_publiccloud_basetest.pm, tests/sles4sap/publiccloud/add_server_to_hosts.pm, tests/sles4sap/publiccloud/check_ibsm_embargoed.pm, tests/sles4sap/publiccloud/cluster_add_repos.pm, tests/sles4sap/publiccloud/general_patch_and_reboot.pm, tests/sles4sap/publiccloud/hana_sr_schedule_cleanup.pm, tests/sles4sap/publiccloud/hana_sr_schedule_deployment.pm, tests/sles4sap/publiccloud/hana_sr_schedule_primary_tests.pm, tests/sles4sap/publiccloud/hana_sr_schedule_replica_tests.pm, tests/sles4sap/publiccloud/hana_sr_takeover.pm, tests/sles4sap/publiccloud/hana_sr_test_secondary.pm, tests/sles4sap/publiccloud/mr_test_setup_env.pm, tests/sles4sap/publiccloud/network_peering.pm, tests/sles4sap/publiccloud/peering_destroy.pm, tests/sles4sap/publiccloud/qesap_ansible.pm, tests/sles4sap/publiccloud/qesap_cleanup.pm, tests/sles4sap/publiccloud/qesap_terraform.pm, tests/sles4sap/saptune/mr_test.pm
Create flag in the base class to record if Ansible has been executed or not and only to call Ansible deregister when needed. mr_test schedule to use qesap_cleanup in place of peering_destroy Both peering_destroy and qesap_cleanup are doing exactly the same from the point of view of the network peering to the IBSm. qesap_cleanup has cluster destruction after that.
- Related ticket: [TEAM-8153](https://jira.suse.com/browse/TEAM-8153)
- sle-15-SP4-HanaSr-Azure-Byos-x86_64-Build15-SP4_2023-08-24T04:03:11Z-hanasr_azure_test_sapconf@64bit -> http://openqaworker15.qa.suse.cz/tests/219884 . Here after the `qesap_ansible` test module execution  http://openqaworker15.qa.suse.cz/tests/219884#step/Stop_site_a-primary/1 you can see `network_peering_present: undefined …
=> Ansible deployment state

data/autoyast_sle12/hpc/create_hdd_textmode_aarch64.xml.ep, data/autoyast_sle12/hpc/create_hdd_textmode_x86_64.xml.ep, schedule/hpc/autoyast_create_hdd_textmode.yaml
AUTOYAST variable will move to the job settings of kernel-openqa-yaml to distiguish the ones used on SLE12 and SLE15
- Related ticket: https://progress.opensuse.org/issues/136253
https://aquarius.suse.cz/tests/19175
https://openqa.suse.de/tests/overview?distri=sle&version=12-SP5&build=b10n1k%2Fos-autoinst-distri-opensuse%2317843
=> Create autoyast profiles for HPC 12SP5 maint job group

data/journal_check/bug_refs.json
This message comes from chrony if the system clock is off and should be ignored.
- Related failure: https://openqa.suse.de/tests/12230814#step/journal_check/11
- Verification run: https://duck-norris.qe.suse.de/tests/13953
=> Ignore 'System clock wrong by X seconds' message

data/autoyast_sle12/hpc/create_hdd_textmode_aarch64.xml.ep, data/autoyast_sle12/hpc/create_hdd_textmode_x86_64.xml.ep
- Related ticket: https://progress.opensuse.org/issues/136253
- Verification run: https://openqa.suse.de/tests/overview?build=b10n1k%2Fos-autoinst-distri-opensuse%2317858&version=12-SP5&distri=sle
=> Correct HPC Autoyast profile to register required modules

lib/sles4sap.pm, tests/sles4sap/hana_install.pm
This PR includes 2 changes:
1. Refactor NFS client ID code so it is used by `copy_media` and `mount_media` methods.
2. Increase `copy_media` timeout from 30 minutes (1800 seconds) to 45 minutes (2700 seconds) in the `copy_media` call in the `sles4sap/hana_install` test module.
- Related ticket: https://progress.opensuse.org/issues/135923
- Needles: N/A
- Verification run: [HANA on 15-SP1](https://openqaworker15.qa.suse.cz/tests/236448), [NetWeaver on 12-SP5](http://openqaworker15.qa.suse.cz/tests/236449), [HANA on 15-SP5](http://openqaworker15.qa.suse.cz/tests/236450), [NetWeaver on 15-SP5](http://openqaworker15.qa.suse.cz/tests/236447), [HANA on 12-SP5](http://openqaworker15.qa.suse.cz/tests/236451)
=> Refactor NFS client ID code & Increase timeout in copy_media call in hana_install test module

data/virt_autotest/host_unattended_installation_files/autoyast/dev_host_12.xml.ep, data/virt_autotest/host_unattended_installation_files/autoyast/dev_host_15.xml.ep, lib/autoyast.pm, lib/virt_autotest/utils.pm, tests/virt_autotest/libvirt_routed_virtual_network.pm, tests/virt_autotest/xen_guest_irqbalance.pm
- Replace SCC_URL with HOST_SCC_URL as we need them both
- Fix failures when downloading large size files, fg. http://10.67.129.27/tests/101#step/vgpu/169
- Increase timeout of error pop-up during host installation to save screenshots, fg. https://openqa.suse.de/tests/12180564#step/installation/6
- Avoid issueing warnings in auto-inst.txt, fg. https://openqa.suse.de/tests/12180564/logfile?filename=autoinst-log.txt
Related ticket: https://progress.opensuse.org/issues/135932
Related MR on job group settings: https://gitlab.suse.de/qa-testsuites/openqa-job-group-yaml/-/merge_requests/153
[gi-guest_developing-on-host_developing-kvm](https://openqa.suse.de/tests/12245544)
[prj4_guest_upgrade_sles15sp5_on_sles15sp5-xen](https://openqa.suse.de/tests/12245975) …
=> Replace SCC_URL with HOST_SCC_URL and fix some failures

data/yam/autoyast/support_images/sles15sp3_install_gnome_all_patterns_aarch64.xml, data/yam/autoyast/support_images/sles15sp3_install_gnome_all_patterns_s390x.xml, data/yam/autoyast/support_images/sles15sp3_install_gnome_all_patterns_x86_64.xml, data/yam/autoyast/support_images/sles15sp3_install_textmode_all_patterns_aarch64.xml, data/yam/autoyast/support_images/sles15sp3_install_textmode_all_patterns_s390x.xml, data/yam/autoyast/support_images/sles15sp3_install_textmode_all_patterns_x86_64.xml
- Description:
* Create support image autoyast with default modules and all patterns on sles15sp3.
- Related ticket: [**progress_132704**](https://progress.opensuse.org/issues/132704)
- Related MR: [**qam_612**](https://gitlab.suse.de/qa-maintenance/qam-openqa-yml/-/merge_requests/612)
- Needles: N/A
* [**15sp3_all_patterns_VR**](https://openqa.suse.de/tests/overview?distri=sle&version=15-SP3&build=GM&groupid=220)
=> Create support image  with default and all patterns on sles15sp3

test_data/yam/agama_full_disk_encryption.yaml
Remove LUKS version and the key location check at encrypt module
- Related ticket: https://progress.opensuse.org/issues/135194
- Verification run: https://openqa.opensuse.org/tests/3597558#step/validate_encrypt/19
=> Remove LUKS version and the key location check at encrypt module

tests/installation/ipxe_install.pm
Boot flag validity check was dropped in 080200a67017 which now causes ipxe_install to accept stale IPMI flags and not set PXE boot override when needed. Add the IPMI boot flag validity check back.
Fixes: 080200a67017 ("Support ipxe installation for ipmi backend tests(virt, perf and hana tests)")
- Related ticket: https://progress.opensuse.org/issues/130219
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/12167973
=> ipxe_install: Verify that PXE boot override is enabled

lib/YaST/Bootloader/BootloaderOptionsPage.pm
Following a change in yast-bootloader (see https://github.com/yast/yast-bootloader/pull/686/files#diff-673d66967f8d7a2a143e4a776ed743e81346e947c1e6d58b8f2657235902718e)
This test needeed to be adjusted.
- Related ticket: https://progress.opensuse.org/issues/135512
- Verification run: https://openqa.opensuse.org/tests/3570013
https://openqa.suse.de/tests/12114085#step/disable_boot_menu_timeout/1
https://openqa.suse.de/tests/12113447#step/disable_boot_menu_timeout/1
=> Update timeout widget following yast-bootloader changes

lib/transactional.pm, schedule/security/alp/check_tpm2.yaml, tests/security/tpm2/tpm2_fail_key_unsealing.pm
Add TPM2 scenario where boot components are updated, failing LUKS key unsealing. In order to pass key unsealing back, calculate the new PCRs and updates the signature in the sealed key with command `fdectl tpm-authorize`.
Add parameter in process_reboot to process passphrase prompt, due it is needed when failing the key unsealing and apparently is the only library method that ensure proper console handling.
- Related ticket: [poo#134984](https://progress.opensuse.org/issues/134984)
- Related MR: [mr#168](https://gitlab.suse.de/qe-security/osd-sle15-security/-/merge_requests/168)
- Verification run: [check_tpm2](https://openqa.suse.de/tests/12304295#details)
=> Add scenario where TPM2 will fail key unsealing

data/microos/butane/script, lib/main_common.pm, schedule/jeos/sle/jeos-main.yaml, tests/microos/image_checks.pm, tests/microos/verify_setup.pm
[PED-6318](https://jira.suse.com/browse/PED-6318) introduces another option to configure images with combustion.
Re-use already existing test cases in order to test combustion on JeOS/Minimal-vm
- ticket: [Add combustion test for Minimal VM](https://progress.opensuse.org/issues/135371)
* [tw-jeos](http://kepler.suse.cz/tests/21924)
* [slem 5.4](http://kepler.suse.cz/tests/21923)
* [slem 5.3](http://kepler.suse.cz/tests/21927#)
* [slem 5.2](http://kepler.suse.cz/tests/21926#)
* [slem 5.1](http://kepler.suse.cz/tests/21928#)
=> JeOS: Test combustion image setup

tests/hpc/hpc_support.pm, tests/hpc/slurm_db.pm, tests/hpc/slurm_slave.pm
slurm-node is released and can be install. No need to block it anymore.
- Verification run: https://aquarius.suse.cz/tests/19220#details
=> Let slurm-node installation on SLE12

tests/network/autofs_server.pm
Upon first restart, on 15-SP3 nfs-server does not come up properly. We check for this corner case and softfail when encountered
- Related ticket: https://progress.opensuse.org/issues/136004
- Needles: no
- https://openqa.suse.de/tests/12273540
- https://openqa.suse.de/tests/12273541
=> Add check for nfs server status after restart
