- tests/smt/smt_server_install.pm
- Related ticket: https://progress.opensuse.org/issues/132263
- Verification run: https://openqa.suse.de/tests/overview?build=smt&distri=sle&version=12-SP5
> smt: Retry on customer center test

- data/supportserver/mail_server/main.cf
- lib/thunderbird_common.pm
- products/sle/main.pm
Reverts os-autoinst/os-autoinst-distri-opensuse#17343
> Revert "Update postfix main.cf for 15-SP5 server"

- tests/fips/xca.pm
- Related ticket: https://progress.opensuse.org/issues/132464
- 15-SP5: https://openqa.suse.de/tests/overview?distri=sle&version=15-SP5&build=20230709-1&groupid=431
- 15-SP4: https://openqa.suse.de/tests/overview?distri=sle&version=15-SP4&build=20230709-1&groupid=431
> fips/xca.pm: use wait_screen_change

- tests/kernel/nfs_client.pm
- tests/kernel/nfs_server.pm
This way it might get easier to investigate possible problems
> NFS: Add explicit hostname print

- .github/CODEOWNERS
Add rbranco to some modules in .github/CODEOWNERS
> Add rbranco to some modules in .github/CODEOWNERS

- tests/kernel/nfs_server.pm
Also rpcinfo is recorded for ease of debugging
> NFS: Enable and start rpc

- schedule/yam/agama/agama_lvm.yaml
- tests/yam/agama/agama_lvm.pm
We need add lvm installation test, so add related yaml schedule file and test module for it.
- Related ticket: https://progress.opensuse.org/issues/130054
- Needles: N/A
- Verification run: https://openqa.opensuse.org/tests/3422144#
https://openqa.opensuse.org/tests/3422062
> Add lvm installation test

- lib/susedistribution.pm
This reverts commit d5dd91b9c03f9128a9c7acad1349598995d3b544.
> Revert "Change user PS1 $ to > for serial-ssh"

- tests/x11/hexchat_ssl.pm
- Related ticket: https://progress.opensuse.org/issues/132386
- Verification run: https://openqa.suse.de/tests/overview?distri=sle&version=15-SP4&build=20230712-1&groupid=431
> hexchat_ssl.pm: use wait_screen_change

- tests/console/zypper_lifecycle.pm
This reverts commit 1a83414b5684186e1391e5f6d2327d37a7adc3ba.
> Revert "zypper_lifecycle: Use select_(user_)?serial_terminal"

- lib/Mitigation.pm
Add xml log for kvm mitigation function test.
- Related ticket:https://progress.opensuse.org/issues/130667
- Verification run: http://10.67.129.7/tests/2224#
http://10.67.129.7/tests/2218
http://10.67.129.7/tests/2122
> Add xml log for kvm mitigation function test

- lib/publiccloud/provider.pm
Set `openqa_var_SERVER` variable.
Needed for https://github.com/SUSE/pcw/pull/278
> Set openqa_var_SERVER

- lib/wickedbase.pm
- tests/wicked/basic/sut/t10_peerip_and_static_route.pm
- http://dante.wicked.suse.de/t160 (Tumbleweed: show error case)
- http://dante.wicked.suse.de/t158 (Tumbleweed: with fix)
- http://dante.wicked.suse.de/t215 (LEAP 15.5)
- http://dante.wicked.suse.de/t214 (SLE-15-SP5)
- http://dante.wicked.suse.de/t211 (SLE-12-SP5)
> wicked: add regression test for boo#1212806

- lib/qesapdeployment.pm
Also redirect stderr to the same pip_install.txt file
- Verification run: http://openqaworker15.qa.suse.cz/tests/203394
> Qesap pip install log to include stderr

- lib/Distribution/Opensuse/Tumbleweed.pm
- lib/Yam/PreviouslyUsedReposPage.pm
- lib/Yam/SelectForUpdatePage.pm
- schedule/migration/migration_offline_media_x86_64.yaml
- tests/installation/upgrade/accept_remove_previous_repos.pm
- tests/installation/upgrade/select_for_update.pm
2 new modules added and update of yaml schedule migration_offline_media_x86_64.yaml
See https://progress.opensuse.org/issues/130078.
VR https://openqa.suse.de/tests/11560584
> Create two modules to replace upgrade_select

- data/autoyast_qam/15_installtest.xml.ep
- Related ticket: https://suse.slack.com/archives/C02D16TCP99/p1688372514260439
> Add PHUB module to Installtest

- data/sles4sap/qe_sap_deployment/qesap_azure.yaml
- data/sles4sap/qe_sap_deployment/qesap_azure_uri.yaml
- tests/sles4sap/qesapdeployment/configure.pm
Follow up for https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/16595
Related ticket: TEAM-7486 
- Azure http://openqaworker15.qa.suse.cz/tests/207040
- Azure http://openqaworker15.qa.suse.cz/tests/207041
- AWS http://openqaworker15.qa.suse.cz/tests/207042
> Only configure hana_instancetype in AWS.

- tests/migration/patch_and_reboot_system.pm
Improve test module patch_and_reboot_system.pm
- Related ticket: https://progress.opensuse.org/issues/132770
- Verification run: https://openqa.suse.de/tests/11615063#details
> Improve test module patch_and_reboot_system.pm

- data/sles4sap/fetch_file.yaml
- data/sles4sap/script_output.yaml
- lib/qesapdeployment.pm
- t/09_qesapdeployment.t
This pr enables the upload of the results of `crm report` from the cluster machines to openqa
- Related ticket: https://jira.suse.com/browse/TEAM-8138
- Verification run: http://openqaworker15.qa.suse.cz/tests/207356#downloads
(failed on purpose at the end of `deploy`)
> Upload crm report

- schedule/migration/migration_offline_media_all_patterns_x86_64.yaml
- schedule/migration/migration_offline_media_x86_64.yaml
- schedule/migration/migration_offline_scc_all_patterns_x86_64.yaml
- tests/migration/install_all_patterns.pm
- tests/migration/query_all_rpm.pm
- Description: Split and improve recently created test module install_patterns
- Related ticket: [issues/132911](https://progress.opensuse.org/issues/132911)
- Verification run: [Test result overview](https://openqa.suse.de/tests/overview?version=15-SP5&distri=sle&build=manfredi%2Fos-autoinst-distri-opensuse%23issues-132911)
- Related [MR#319](https://gitlab.suse.de/coolgw/wegao-test/-/merge_requests/319)
> Split and improve recently created test module install_patterns

- tests/console/python3_new_version_check.pm
- Related ticket: https://progress.opensuse.org/issues/127241
- Needles: NO
- Verification run:   [Tumbleweed](http://deepthi-openqa.qe.suse.de/tests/5943#step/python3_new_version_check/9) | [SLE15-sP4_x86_64](http://deepthi-openqa.qe.suse.de/tests/5942#step/python3_new_version_check/9)
Latest VRs:  [Tumbleweed](http://deepthi-openqa.qe.suse.de/tests/6006) | [SLE15-sP4_x86_64](http://deepthi-openqa.qe.suse.de/tests/6005)
15-SP5 - [aarch64](https://openqa.suse.de/tests/11704486)  | [s390x](https://openqa.suse.de/tests/11704487)  | [x86_64](https://openqa.suse.de/tests/11704489)
15-SP4 - [aarch64](https://openqa.suse.de/tests/11675634#step/python3_new_version_check/9)  | [s390x](https://openqa.suse.de/tests/11675657#step/python3_new_version_check/9) | …
> Add a test to verify the system python version

- tests/smt/smt_server_install.pm
- Related ticket: https://progress.opensuse.org/issues/132482
- Verification run: https://openqa.suse.de/tests/11713746
> smt_server_install: Increase smt-mirror timeout

- schedule/sle-micro/yam/slem_installation_default_s390x_zvm.yaml
Add schedule file for slem s390x zvm case of slem_installation_default
- Related ticket: https://progress.opensuse.org/issues/132992
- Needles: n/a
- Verification run: http://openqa.suse.de/tests/11721241#
> Add schedule file for slem s390x zvm case

- schedule/migration/migration_offline_media_all_patterns_x86_64.yaml
- schedule/migration/migration_offline_media_x86_64.yaml
- schedule/migration/migration_offline_scc_all_patterns_x86_64.yaml
- schedule/migration/migration_offline_scc_x86_64.yaml
- tests/migration/version_reset_origin_system.pm
- Description: Create a new module to recover version to original
- Related ticket: [issues/132734](https://progress.opensuse.org/issues/132734)
- Verification run: [Test result overview](https://openqa.suse.de/tests/overview?build=manfredi%2Fos-autoinst-distri-opensuse%23issues-132734&distri=sle&version=15-SP5)
> Create a new module to recover version to original

- tests/boot/boot_from_pxe.pm
Nvdimm tests tend to sporadically fail because of typos made during typing grub cmdline. This pr uses a slower typing speed when nvdimm tests are detected.
- Related ticket: https://jira.suse.com/browse/TEAM-8111
- Verification runs: (jobs where cancelled after they passed the relevant module)
https://openqa.suse.de/tests/11731494
https://openqa.suse.de/tests/11731235
https://openqa.suse.de/tests/11731495
https://openqa.suse.de/tests/11732359
https://openqa.suse.de/tests/11732360
https://openqa.suse.de/tests/11733026
(6 back to back tests, problem does not appear)
> Type very slow if NVDIMM

- lib/containers/utils.pm
- tests/containers/bci_test.pm
- tests/containers/host_configuration.pm
- tests/containers/image.pm
Reverts os-autoinst/os-autoinst-distri-opensuse#17527
It caused https://progress.opensuse.org/issues/133808
> Revert "Refactor reset_container_network_if_needed"

- schedule/security/container_selinux.yaml
fix scheduler selinux by removing no longer needed tests
> Fix container_selinux

- tests/containers/containerd_rmt.pm
Enhance RMT Helm test
- Verification run: https://openqa.suse.de/tests/11742742
- Related MR: https://gitlab.suse.de/qac/qac-openqa-yaml/-/merge_requests/1292
TODO:
- Use Docker image instead of pulling from git branch.
- It's not a container_runtime.
- Test RMT functionality?
> containers: Enhance RMT Helm test

- lib/main_common.pm
Skip adding test repos for container updates
VR: http://kepler.suse.cz/tests/21476
> Fix container image updates

- tests/publiccloud/nvidia.pm
Due to the not easy way to provide and install nvidia-compute-utils-G06 which provides the nvidia-smi, we check device files and the loaded modules on the system. Seems there is no better solution for the moment.
- Related ticket: https://progress.opensuse.org/issues/131501
- Verification run: https://openqa.suse.de/tests/11725797 
https://openqa.suse.de/tests/11725798
> Check NVIDIA device files and modules

- lib/DistributionProvider.pm
- products/sle-micro/main.pm
- schedule/sle-micro/yam/slem_extensions_and_modules_s390x.yaml
- schedule/sle-micro/yam/slem_extensions_and_modules_x86_64.yaml
- schedule/sle-micro/yam/slem_installation_default_zvm.yaml
- schedule/yast/sle/flows/default_slem.yaml
- Related ticket: https://progress.opensuse.org/issues/132995
- Verification runs: https://openqa.suse.de/tests/overview?version=5.5&distri=sle-micro&build=sofiasyria%2Fos-autoinst-distri-opensuse%23slem_libyui
Currently the aarch64 tests fail due to scc repos invalid content.
Should be merged before MR: https://gitlab.suse.de/qsf-y/qa-sle-functional-y/-/merge_requests/524
> Switch sle-micro yam tests to libyui

- lib/hacluster.pm
- t/11_hacluster.t
- tests/sles4sap/qesapdeployment/test_cluster.pm
Check the cluster health using crm status and take some actions
- Related ticket: https://jira.suse.com/browse/TEAM-8110
- Verification run: http://openqaworker15.qa.suse.cz/tests/212917#
> Check the cluster health using crm tool

- tests/console/perf.pm
- Related ticket: https://bugzilla.opensuse.org/show_bug.cgi?id=1213785
- Verification run: https://openqa.opensuse.org/tests/3497677
> console/perf: Add softfail for boo#1213785

- lib/Distribution/Opensuse/Leap/15.pm
- lib/Distribution/Opensuse/Tumbleweed.pm
- lib/Distribution/Sle/15_current.pm
- tests/installation/access_beta_distribution.pm
- tests/installation/activate_multipath.pm
- tests/installation/confirm_installation.pm
- tests/installation/confirm_installation_maintenance.pm
- tests/installation/online_repos/disable_online_repos.pm
- tests/installation/system_role/accept_selected_role_SLES_with_GNOME.pm
- tests/installation/system_role/accept_selected_role_text_mode.pm
- tests/installation/system_role/accept_selected_role_transactional_server.pm
- tests/installation/system_role/select_role_desktop_with_GNOME.pm
- tests/installation/system_role/select_role_desktop_with_KDE_plasma.pm
- tests/installation/system_role/select_role_generic_desktop.pm
- tests/installation/system_role/select_role_minimal.pm
- tests/installation/system_role/select_role_server.pm
- tests/installation/system_role/select_role_text_mode.pm
- tests/installation/system_role/select_role_transactional_server.pm
- tests/installation/system_role/validate_no_system_role_selected.pm
- tests/installation/validate_beta_message.pm
-Progress ticket: https://progress.opensuse.org/issues/133865
- Verification runs : https://openqa.suse.de/tests/overview?distri=sle&build=sofiasyria%2Fos-autoinst-distri-opensuse%23rename_controller&version=15-SP5
- https://openqa.suse.de/tests/11757288
> Rename function names with _controller ending

- tests/security/tpm2/keylime/keylime.pm
- Related ticket: https://progress.opensuse.org/issues/134009
- https://openqa.suse.de/tests/11793380
- https://openqa.suse.de/tests/11793381
- https://openqa.suse.de/tests/11793382
> keylime.pm: fix for 15-SP6

- tests/systemd_testsuite/runner.pm
VR: http://kepler.suse.cz/tests/21497#downloads
> Fix logs path in systemd upstream tests

- lib/parallel_guest_migration_base.pm
Progress ticket: https://progress.opensuse.org/issues/133139 
Utilizing NFS share storage in a virtualization environment: 
either by creating a netfs storage pool on both source and destination hosts or by directly mounting the NFS directory on both hosts, with the current testing setup involving only mounting the NFS directory on the destination host without mounting the NFS directory on the source host.
The purpose of doing this is to ensure that the same file system is accessed during guest migration.
- Related ticket: Progress ticket: https://progress.opensuse.org/issues/133139 
- Needles: N/A
- [Xen Guest migration](http://openqa.qam.suse.cz/tests/overview?distri=sle&version=15-SP5&build=:cailftest:live_migrat)
- [Kvm Guest …
> Improve the usage of nfs when guest migration

- tests/installation/module_registration/register_extensions_and_modules.pm
- Repeating failure: https://openqa.suse.de/tests/11774758#step/register_extensions_and_modules/1
- Verification run: https://openqa.suse.de/tests/11801926
> register_extensions_and_modules: Increase timeout

- tests/installation/ipxe_install.pm
https://progress.opensuse.org/issues/133490
> Update ipxe_install for confirm dialog in new ipxe menu

- tests/console/ntp_client.pm
> ntp_client.pm: only apply workaround on SLE

- lib/susedistribution.pm
- lib/x11utils.pm
- tests/console/consoletest_finish.pm
- tests/console/zypper_lifecycle.pm
- tests/jeos/firstrun.pm
- tests/qam-minimal/install_patterns.pm
- Related ticket: https://progress.opensuse.org/issues/129026
- Verification run: In Progress
https://openqa.suse.de/tests/overview?build=zypper_lifecycle SLE
https://dzedro.suse.cz/tests/overview?build=zypper_lifecycle&distri=opensuse&version=Tumbleweed TW
> Fix and enable user-serial-terminal on zVM and JeOS

- schedule/sle-micro/yam/slem_extensions_and_modules_aarch64.yaml
- Verification run: https://openqa.suse.de/tests/11820883#
- MR: https://gitlab.suse.de/qsf-y/qa-sle-functional-y/-/merge_requests/528
> Import GPG key for aarch64

- tests/sles4sap/qesapdeployment/test_cluster.pm
- Related ticket: TEAM-8442
- sle-15-SP4-Qesap-Azure-Payg-x86_64-BuildLATEST_AZURE_SLE15_4_PAYG-qesap_azure_saptune_test@64bit -> http://openqaworker15.qa.suse.cz/tests/213303
- sle-15-SP4-Qesap-Aws-Byos-x86_64-BuildLATEST_AWS_SLE15_4_BYOS-qesap_aws_sapconf_test@64bit -> http://openqaworker15.qa.suse.cz/tests/213304
> Delay the crm status test and call crm report in case of failure

- tests/console/validate_lvm.pm
- tests/yam/agama/agama_full_disk_encryption.pm
- tests/yam/agama/agama_lvm.pm
- tests/yam/agama/patch_agama.pm
- Related ticket: https://progress.opensuse.org/issues/134120
- Needles: https://github.com/os-autoinst/os-autoinst-needles-opensuse/pull/797
- Playwright: https://github.com/jknphy/e2e-agama-playwright/pull/11
- Verification run: http://falafel.suse.cz/tests/overview?build=2.40&version=agama-3.0-staging&distri=alp
> Change dolomite assert_screen

- tests/boot/boot_from_pxe.pm
VR: https://openqa.suse.de/tests/11839234
> Update tests to boot using new iPXE menu

- lib/main_containers.pm
- tests/containers/volumes.pm
Fix for https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/17584
Related tickets:
- https://progress.opensuse.org/issues/134342
- https://progress.opensuse.org/issues/134345
- sle-15-SP1-Server-DVD-Updates-x86_64-Build20230816-1-podman_tests@64bit -> https://openqa.suse.de/t11858543
> containers: Fix for PR#17584

- lib/qam.pm
- Related ticket: https://progress.opensuse.org/issues/134405
- Verification run: https://openqa.suse.de/tests/11869921
> Add extra customer repo only on maintenance tests

- schedule/yam/agama/agama_encrypted_lvm.yaml
- tests/yam/agama/agama_encrypted_lvm.pm
Should be merged after: https://github.com/jknphy/e2e-agama-playwright/pull/12
PR: https://progress.opensuse.org/issues/133010
VR: http://falafel.suse.cz/tests/overview?build=lvm&distri=alp&version=agama-3.0-staging
> Add agama_encrypted_lvm test

- schedule/yast/autoyast/autoyast_ha_spvm.yaml
- schedule/yast/autoyast/autoyast_sap.yaml
- Related ticket: https://progress.opensuse.org/issues/134201
- Verification run: https://openqa.suse.de/tests/11889273
> Fix autoyast setting for failed tests

- tests/qam-updinstall/update_install.pm
- Related ticket: https://progress.opensuse.org/issues/134477
- Needles: No
https://openqa.suse.de/tests/11897374
https://openqa.suse.de/tests/11897743
> Increase timeout of zypper patch

- tests/containers/containerd_rmt.pm
Test rmt image by repo/tag
- Related MR: https://gitlab.suse.de/qac/qac-openqa-yaml/-/merge_requests/1306
- Verification run: https://openqa.suse.de/t11870944
> containers: Test rmt image by repo/tag

- schedule/staging/gnome@64bit-staging.yaml
https://progress.opensuse.org/issues/134507
- Verification run: https://openqa.suse.de/tests/11903032
> Disable grub timeout for gnome staging test

- tests/sles4sap/publiccloud/qesap_terraform.pm
Only test for that variable in jobs configured to run in Azure. Use PC cloud detection methods when possible.
Related ticket: [TEAM-8211](https://jira.suse.com/browse/TEAM-8211)
- AZURE
- Catalog image
- HANASR sle-15-SP4-HanaSr-Azure-Byos-x86_64-Build15-SP4_2023-08-23T04:03:13Z-hanasr_azure_test_sapconf
- http://openqaworker15.qa.suse.cz/tests/217020 called without `PUBLIC_CLOUD=1` as the cloned job does not have it
- http://openqaworker15.qa.suse.cz/tests/217028 the same as before but with `PUBLIC_CLOUD=1`
- Image from `publiccloud_upload_img`
- HANASR sle-15-SP5-Azure-SAP-BYOS-x86_64-Build0298-azure_sap_byos_hanasr_sapconf@az_Standard_E4s_v3 -> http://openqaworker15.qa.suse.cz/tests/217023
- MR_TEST sle-15-SP5-Azure-SAP-BYOS-x86_64-Build0298-sles4sap_gnome_saptune_dele …
> Only test for PUBLIC_CLOUD_IMAGE_LOCATION in Azure

- tests/sles4sap/saptune/mr_test.pm
This PR(TEAM-8153) is about to fix Failure in mr_Test does not clean up the IBSm peering by calling delete_network_peering  in post fail hook.
- Related ticket: [TEAM-8153](https://jira.suse.com/browse/TEAM-8153)
- Verification run: http://openqaworker15.qa.suse.cz/tests/216615#
- Fail Scenario to check cleanup: http://openqaworker15.qa.suse.cz/tests/217042#step/mr_test/89
> delete_network_peering called in post fail hook

- tests/fips/openssl/dirmngr_setup.pm
Replace multiline `expect` commands with non-interactive openssl calls in `fips/openssl/dirmngr_setup` test.
- Needles: N/A
- Verification run: https://openqa.opensuse.org/tests/3528802
> dirmngr_setup: Fix invalid multiline commands

- tests/console/mariadb_odbc.pm
Multiline strings in `script_run` turns to be a bad practice. In order to improve the code, this PR replaces multiline strings with more calls.
- failure: https://openqa.opensuse.org/tests/3526658#step/mariadb_odbc/39
- VR: http://kepler.suse.cz/tests/21579#step/mariadb_odbc/80
> mariadb_odbc: replace multiline strings

- data/autoyast_sle15/create_hdd/create_hdd_gnome_we_x86_64.xml
- data/autoyast_sle15/create_hdd/create_hdd_minimal_base_sdk_aarch64.xml
- data/autoyast_sle15/create_hdd/create_hdd_minimal_base_sdk_ppc64le.xml
- data/autoyast_sle15/create_hdd/create_hdd_minimal_base_sdk_s390x.xml
- data/autoyast_sle15/create_hdd/create_hdd_minimal_base_sdk_x86_64.xml
- data/autoyast_sle15/create_hdd/create_hdd_pcm_aws_aarch64.xml
- data/autoyast_sle15/create_hdd/create_hdd_pcm_aws_ppc64le.xml
- data/autoyast_sle15/create_hdd/create_hdd_pcm_aws_s390x.xml
- data/autoyast_sle15/create_hdd/create_hdd_pcm_aws_x86_64.xml
- schedule/functional/autoyast_create_hdd/autoyast_create_hdd_gnome_we.yaml
- schedule/functional/autoyast_create_hdd/autoyast_create_hdd_minimal_base_sdk.yaml
- schedule/functional/autoyast_create_hdd/autoyast_create_hdd_pcm_aws.yaml
- tests/autoyast/installation.pm
https://progress.opensuse.org/issues/134429
Some job settings are changed in testsuite
VRs:
[gnome+we](http://openqa.suse.de/tests/overview?version=15-SP6&build=rfan0822_we&distri=sle)
[minimal_base+sdk](https://openqa.suse.de/tests/overview?distri=sle&build=rfan0821-sdk&version=15-SP6)
[pcm_aws](http://openqa.suse.de/tests/overview?version=15-SP6&build=rfan0822-pcm_aws&distri=sle)
> Add more create hdd tests via autoyast

- tests/console/timezone.pm
Use temporary file to store test data in `timezone.pm`
- VR: http://kepler.suse.cz/tests/21589#step/timezone/16
> Save test data in tmp file

- schedule/yam/agama/agama_installation.yaml
- tests/yam/agama/agama_installation.pm
Shoudl be merged after : https://github.com/jknphy/e2e-agama-playwright/pull/17/files
- Related ticket: https://progress.opensuse.org/issues/134228
- Verification runs:  http://falafel.suse.cz/tests/overview?build=agama_default&version=agama-3.0-devel&distri=alp
aarch64: https://openqa.opensuse.org/tests/overview?version=agama-3.0-devel&distri=alp&build=sofiasyria%2Fos-autoinst-distri-opensuse%23agama_default
> Edit agama_installation module

- schedule/yam/agama/add_home_file_system.yaml
- Description: Create test and POM for adding a home file system
- Related ticket: https://progress.opensuse.org/issues/133103
+ [Test result overview - Staging](https://openqa.opensuse.org/tests/overview?build=manfredi%2Fos-autoinst-distri-opensuse%23issues-133103&distri=alp&version=agama-3.0-staging)
+ [Test result overview - Devel](https://openqa.opensuse.org/tests/overview?build=manfredi%2Fos-autoinst-distri-opensuse%23issues-133103&distri=alp&version=agama-3.0-devel)
Related PR: https://github.com/jknphy/e2e-agama-playwright/pull/13
> Create test and POM for adding a home file system

- tests/cpu_bugs/ipmi_to_qemu.pm
Enhance the ipmi_to_qemu: solve the libopencv405 and activate packages with packagehub.
- Related ticket: https://progress.opensuse.org/issues/134096
- Verification run: http://10.67.129.4/tests/60538#
> enhance the ipmi_to_qemu

- lib/services/libvirtd.pm
In Tumbleweed, the libvirtd is already removed and replaced by virtqemud, to adapt this change in libvirtd.service testing on upgraded Tumbleweed, enable, start and check the virtqemud.service after upgrading to Tumbleweed.
- Related ticket: https://progress.opensuse.org/issues/133856
- Needles: n/a
- https://openqa.opensuse.org/tests/3531808#step/nested_vm#1/22
- https://openqa.opensuse.org/tests/3531809#step/nested_vm#1/22
> Adapt the removal of libvirtd for upgraded Tumbleweed

- tests/sles4sap/qesapdeployment/deploy.pm
This PR is about to implement clean up function to destroy Terraform and Ansible failed resources before triggering the Re-run in QESAP deployment when Azure reboot timeout found
- AWS : http://openqaworker15.qa.suse.cz/tests/217953# **(PASS)**
- Azure with wrong reg_code : http://openqaworker15.qa.suse.cz/tests/217957 (Failure is expected to check other return codes and result in case of other failures except for timeout errors.)
- Azure : http://openqaworker15.qa.suse.cz/tests/217968# Failed due to [TEAM-8442](https://jira.suse.com/browse/TEAM-8442)
- GCP :http://openqaworker15.qa.suse.cz/tests/217972# **(PASS)**
-
> Destroying Terraform and Ansible Resources before Re-run when Timeout found

- schedule/security/extratests_fips_kernelmode.yaml
https://progress.opensuse.org/issues/134669
> Add extratests_fips_kernelmode.yaml

- tests/console/consoletest_finish.pm
- Related ticket: https://progress.opensuse.org/issues/134672
- Verification run: https://openqa.suse.de/tests/11928007
> consoletest_finish: Do reboot also on 15-SP1 s390x

- tests/security/oscap_stig/oscap_xccdf_eval.pm
- Related ticket: https://progress.opensuse.org/issues/134381
> stig: update rules

- tests/containers/volumes.pm
containers: Fix github issue link in record_soft_failure
> containers: Fix github issue link in record_soft_failure

- tests/containers/podman_netavark.pm
We do not need to switch from CNI to netavark in ALP as netavark is the default network backend in this distro.
- failure: https://openqa.suse.de/tests/11980587#step/podman_netavark/59
- Verification run: http://kepler.suse.cz/tests/21750#
> podman-netavark is default backend in ALP

- tests/security/apparmor_profile/usr_sbin_smbd.pm
- Related ticket: https://progress.opensuse.org/issues/134780
- 12-SP3: https://openqa.suse.de/tests/12011784
- 12-SP5: https://openqa.suse.de/tests/12011892
- 15-SP2: https://openqa.suse.de/tests/12012189
- 15-SP4: https://openqa.suse.de/tests/12012672
- 15-SP5: https://openqa.suse.de/tests/12012968
- openSUSE TW: https://openqa.opensuse.org/tests/3548893
> Refactor usb_sbin_smbd test

- tests/qam-updinstall/update_install.pm
- Related ticket: https://progress.opensuse.org/issues/131534
- Verification run: https://dzedro.suse.cz/tests/1797
> Patch only Teradata patch on Teradata flavor

- tests/console/clamav.pm
- Related ticket: https://progress.opensuse.org/issues/135224
- Needles: No
15-SP4 : [x86_64](https://openqa.suse.de/tests/12025144#step/clamav/1) | [aarch64](https://openqa.suse.de/tests/12025221#step/clamav/1)
15-SP5: [x86_64](https://openqa.suse.de/tests/12025229#step/clamav/1l) | [aarch64](https://openqa.suse.de/tests/12025276#step/clamav/1)
15-SP3: [x86_64](https://openqa.suse.de/tests/12025277#step/clamav/1) | [aarch64](https://openqa.suse.de/tests/12025278#step/clamav/1)
12-SP3- [x86_64](https://openqa.suse.de/tests/12025351)
> Fix test clamav 

- test_data/yam/agama_tumbleweed_full_disk_encryption.yaml
- Related ticket: https://progress.opensuse.org/issues/134615
- Verification run: http://falafel.suse.cz/tests/1371
Agama devel and staging job group should be edited after merging
> Add agama tumbleweed encryption test_data

- tests/transactional/enable_selinux.pm
* Update cmdline to enable/disable selinux. see: https://github.com/SELinuxProject/selinux-kernel/wiki/DEPRECATE-runtime-disable
* Fixed a part of bsc#1214020
> transactional/enable_selinux: Update cmdline

- tests/containers/containerd_rmt.pm
- Related MR's:
- https://gitlab.suse.de/qac/container-release-bot/-/merge_requests/180
- https://gitlab.suse.de/qac/qac-openqa-yaml/-/merge_requests/1315
- Verification run: https://openqa.suse.de/tests/12042613#
> Test all RMT components

- lib/migration.pm
- Description:
Quick fix openqa.suse.de IP address change. 
- Related ticket:  https://openqa.suse.de/tests/12036983  
- Needles: N/A
- Verification run:  https://openqa.suse.de/tests/12047657
> Quick fix openqa.suse.de ip address change

- lib/main_micro_alp.pm
- Related ticket:https://progress.opensuse.org/issues/133859
- Needles: NO
> Remove cockpit_service test in ALP_Functional jobgroup

- lib/publiccloud/ec2.pm
- variables.md
- Related ticket: [poo#128459](https://progress.opensuse.org/issues/128459)
> Introduce PUBLIC_CLOUD_EC2_BOOT_MODE

- lib/transactional.pm
- lib/version_utils.pm
This will take the right rpms form data directory.
Failure example: https://openqa.suse.de/tests/12091735#step/transactional_update/24
Verification Run: https://openqa.suse.de/tests/12094093
> Update condition to get UTT packages for ALP

- data/security/autoyast/create_hdd_gnome_aarch64.xml
- data/security/autoyast/create_hdd_gnome_ppc64le.xml
- data/security/autoyast/create_hdd_gnome_s390x.xml
- data/security/autoyast/create_hdd_gnome_x86_64.xml
- data/security/autoyast/create_hdd_gnome_x86_64_uefi.xml
- data/security/autoyast/create_hdd_textmode_aarch64.xml
- data/security/autoyast/create_hdd_textmode_ppc64le.xml
- data/security/autoyast/create_hdd_textmode_s390x.xml
- data/security/autoyast/create_hdd_textmode_x86_64.xml
- data/security/autoyast/create_hdd_textmode_x86_64_uefi.xml
Bug: https://bugzilla.suse.com/show_bug.cgi?id=1214141
VR: https://openqa.suse.de/tests/12103120
> Remove ntp_client block from autoyast profiles

- data/journal_check/bug_refs.json
Fixes https://openqa.suse.de/tests/12097330#step/journal_check/29
VR: http://openqa.suse.de/tests/12098062
> Whitelist health-check error message in ALP Dolomite

- tests/installation/installation_mode.pm
- Related ticket: https://progress.opensuse.org/issues/135920
- Needles: No
- Verification run:  https://openqa.opensuse.org/tests/3584909#
> increase timeout to match screen in installation

- lib/main_micro_alp.pm
- lib/version_utils.pm
- tests/microos/selfinstall.pm
Needs just some small changes.
- Needles: Already created on o3
- Verification run: https://openqa.opensuse.org/tests/3584904
VR is still running but already past the critical installation parts.
> Support MicroOS-SelfInstall images

- lib/opensusebasetest.pm
- variables.md
- Verification run: https://openqa.opensuse.org/tests/3570015
> Add `EXTRABOOTPARAMS_LINE_OFFSET` option for `EXTRABOOTPARAMS_BOOT_LOCAL`

- lib/main_micro_alp.pm
See individual commits.
- Verification run: https://openqa.opensuse.org/tests/3586636
> Small improvements for MicroOS SelfInstall

- data/journal_check/bug_refs.json
- Verification run: http://kepler.suse.cz/tests/21899#step/journal_check/21
> Known bugs:Failed to lookup EFI memory descriptor

- data/virt_autotest/guest_params_xml_files/sles_15_sp5_64_xen_hvm_uefi_with_power_management_x86_64.xml
- data/virt_autotest/guest_params_xml_files/sles_15_sp6_64_kvm_hvm_sev_es_x86_64.xml
- data/virt_autotest/guest_params_xml_files/sles_15_sp6_64_kvm_hvm_uefi_with_power_management_x86_64.xml
- data/virt_autotest/guest_params_xml_files/sles_15_sp6_64_kvm_hvm_uefi_without_power_management_x86_64_using_virtmanagerlt3.0.0.xml
- data/virt_autotest/guest_params_xml_files/sles_15_sp6_64_xen_hvm_uefi_with_power_management_x86_64.xml
- data/virt_autotest/guest_params_xml_files/sles_15_sp6_64_xen_hvm_uefi_without_power_management_x86_64_using_virtmanagerlt3.0.0.xml
for UEFI guest, sev-es guests installation tests.
- Related ticket: https://progress.opensuse.org/issues/132800  & https://progress.opensuse.org/issues/135872
[uefi-gi-guest_developing-on-host_developing-kvm](https://openqa.suse.de/tests/12180561)
[uefi-gi-guest_developing-on-host_developing-xen](https://openqa.suse.de/tests/12180562)
[uefi-gi-guest_developing-on-host_sles12sp5-kvm](https://openqa.suse.de/tests/12180563)
[uefi-gi-guest_developing-on-host_sles12sp5-xen](https://openqa.suse.de/tests/12180607)
[sev-es-gi-guest_developing-on-host_developing-kvm](https://openqa.suse.de/tests/12180565)
[uefi-gi-guest_sles15sp5-on-host_developing-xen](https://openqa.suse.de/tests/12167517)
[sev-es-gi-guest_sles15sp5-on-host_developing-kvm](https://openqa.suse.de/tests/1216751 …
> Create guest parameter files for sle15sp6 virt tests

- tests/xfstests/run.pm
When test script know tests crash/hang happens. It was in two scenarios:
1. system hang in root console during run subtests;
2. system already crash and reboot by itself waiting in bootloader screen; 
The previous solution ignore the second scenario. The solution is to remove the duplicate select_console here to avoid problem in the second scenario. Use force reboot 'alt-sysrq-b' to adapt both scenarios.
- Related ticket: https://progress.opensuse.org/issues/133502
- Verification run: http://10.67.133.133/tests/335
- (compare with [previous tests](http://10.67.133.133/tests/332#step/run/36), whole tests not die when btrfs/288 crash system, and call trace record in http://10.67.133.133/tests/335#step/run/31)
> xfstests: Fix crash boot keep wait in bootloader

- data/journal_check/bug_refs.json
VR: https://openqa.opensuse.org/tests/3588942
> Enable soft-failures for Leap Micro 5.5 for known bugs

- data/autoyast_qam/12-common_base_installation.xml.ep
- data/autoyast_qam/15-common_base_installation.xml.ep
- data/yam/autoyast/support_images/create_hdd_ha_sles.xml.ep
- data/yam/autoyast/support_images/create_hdd_hpc_development_node_aarch64.xml.ep
- data/yam/autoyast/support_images/create_hdd_hpc_development_node_x86_64.xml.ep
- data/yam/autoyast/support_images/create_hdd_hpc_management_server_aarch64.xml.ep
- data/yam/autoyast/support_images/create_hdd_hpc_management_server_x86_64.xml.ep
- data/yam/autoyast/support_images/create_hdd_hpc_textmode_aarch64.xml.ep
- data/yam/autoyast/support_images/create_hdd_hpc_textmode_x86_64.xml.ep
- data/yam/autoyast/support_images/create_hdd_maintenance.xml.ep
- data/yam/autoyast/support_images/create_hdd_sap.xml.ep
- data/yam/autoyast/support_images/create_hdd_sles_regression_aarch64.xml.ep
- data/yam/autoyast/support_images/create_hdd_sles_regression_ppc64le.xml.ep
- data/yam/autoyast/support_images/create_hdd_sles_regression_s390x.xml.ep
some VRs are still not finished
- Related ticket: https://progress.opensuse.org/issues/132779
- Needles: N/A
https://openqa.suse.de/tests/12105399
https://openqa.suse.de/tests/12105639
https://openqa.suse.de/tests/12105645
https://openqa.suse.de/tests/12105644
https://openqa.suse.de/tests/12106859
https://openqa.suse.de/tests/12105478
https://openqa.suse.de/tests/12105746
https://openqa.suse.de/tests/12105745
https://openqa.suse.de/tests/12105744
> Remove workaround for bsc1202234

- lib/sles4sap.pm
NFS client ID calculation during HANA or NetWeaver installation was introduced in baff123cb6210f8b959b421ffeb57c6adc33c530 and improved on be30deb95fe7e6654fc584b81632e3f1c688973f. This introduces further improvements on calculation and reporting:
1. sha256 digest calculation was moved from SUT to the worker
2. Do not use `tee` to write on `/sys/fs/nfs/net/nfs_client/identifier`
3. Check the contents of `/sys/fs/nfs/net/nfs_client/identifier` after id is set.
4. Ensure `/sys/fs/nfs/net/nfs_client/identifier` exists and is writable
5. Increase timeout on `mount` command
6. Add rsize & wsize mount options
7. Introduce a setting (NFS_TIMEO) to pass the `nfs_timeo` option to `mount`
8. Replace `cp -ax` with `rsync`
- Related ticket: https://progress.opensuse.org/issues/135923
- Needles: N/A
- …
> Improve NFS client ID calculation and reporting

- tests/containers/podman_bci_systemd.pm
Problem: In some cases, the container is not ready yet, to allow commands.
Solution: Wait until the container is ready.
- Related ticket: https://progress.opensuse.org/issues/134687
- http://openqa.suse.de/tests/12187921
- https://openqa.opensuse.org/tests/3587040
> Fix race condition for BCI-init systemd test

- .github/workflows/ci.yml
See
* https://github.com/os-autoinst/os-autoinst/pull/2362
> Update Perl::Tidy to 20230909

- tests/publiccloud/slem_basic.pm
Checks the Access Vector Cache for SELinux denials at startup.
- Related ticket: https://progress.opensuse.org/issues/136046
- Verification run: https://duck-norris.qe.suse.de/tests/13943#step/slem_basic/231
> Add AVC check to SLEM basic

- tests/containers/rootless_podman.pm
- tests/jeos/rpi_bluetooth.pm
- tests/publiccloud/azure_cli.pm
- tests/publiccloud/slem_basic.pm
Remove soft-fails for RESOLVED tickets:
- https://bugzilla.suse.com/show_bug.cgi?id=1192051
- https://bugzilla.suse.com/show_bug.cgi?id=1191482
- https://bugzilla.suse.com/show_bug.cgi?id=1195382
- https://bugzilla.suse.com/show_bug.cgi?id=1211084
- https://bugzilla.suse.com/show_bug.cgi?id=1188238
Related ticket: https://progress.opensuse.org/issues/136076
> Remove softfails

- lib/sles4sap.pm
Commits baff123cb6210f8b959b421ffeb57c6adc33c530 and be30deb95fe7e6654fc584b81632e3f1c688973f introduced the configuration of  an unique NFS client ID while copying SAP installation media from a NFS share. This configuration was done as defined in those commits after the share had been mounted, however there still exists a race condition when more than one system identified with the same NFS client ID attempts to mount the share.
This commit introduces changes which load the `nfs` kernel module before the `mount` command, supplying to it the `nfs4_unique_id` parameter on load so the client has an unique ID before any NFS operation, including before the `mount` command which can be blocked if there are client ID clashes.
This commit also replaces the use of a sha256 for an md5 digest, as …
> Set NFSv4 client ID before mount

- tests/containers/podman_bci_systemd.pm
Problem: In recent test for systemd we use inspect health. But in some podman old versions doen't work
Solution: Use a different way to check it
- http://openqa.suse.de/tests/12230111
- http://openqa.suse.de/tests/12230140
- http://openqa.suse.de/tests/12230141
- http://openqa.suse.de/tests/12230190 (last small change)
> Containers: Replace health check of podman test

- data/yam/autoyast/bug-879147_autoinst.xml
https://bugzilla.suse.com/show_bug.cgi?id=1215591
- Verification run: https://openqa.suse.de/tests/12219080
> Workaround for bsc#1215591

- tests/security/cc/audit_tools.pm
- Related ticket: https://progress.opensuse.org/issues/136367 , https://progress.opensuse.org/issues/125039
- 15-SP4: https://openqa.suse.de/tests/12273525#step/audit_tools/1
- 15-SP5: https://openqa.suse.de/tests/12273526#step/audit_tools/1
> audit_tools.pm: add workaround for 15-SP4+

- lib/windowsbasetest.pm
Verification Run: http://openqa.suse.de/tests/12275975
> Revert default Windows password

- schedule/jeos/sle/jeos-main.yaml
Follow up for
https://gitlab.suse.de/qac/qac-openqa-yaml/-/merge_requests/1328
> Fix machine type for JeOS@s390x main job

- data/sles4sap/qe_sap_deployment/qesap_azure_fullypatch.yaml
- Related ticket: TEAM-8437 - [qesap-deployment] Fully patch system before test start
- Verification run: http://openqaworker15.qa.suse.cz/tests/236435
> Add config to try the new fully-patch-system playbook

- Makefile
> Turn off "source OK" messages from perlcritic

- lib/power_action_utils.pm
https://progress.opensuse.org/issues/136901
- Verification run: https://openqa.suse.de/tests/12272057
> Use mouse click to double confirm system shutdown

- schedule/security/encryption/lvm_encrypt_separate_boot.yaml
- schedule/security/encryption/lvm_encrypt_separate_boot_s390x.yaml
Related ticket: https://progress.opensuse.org/issues/137018
- https://openqa.suse.de/tests/12303928
- https://openqa.suse.de/tests/12303930
- https://openqa.suse.de/tests/12304301
> Fix encryption tests for beta distributions

- data/journal_check/bug_refs.json
- Related ticket: https://bugzilla.opensuse.org/show_bug.cgi?id=1212970
- Verification run: https://openqa.opensuse.org/tests/3600847#step/journal_check/21
> data/journal_check/bug_refs.json: Add workaround for Tumbleweed boo#1212970

- lib/containers/common.pm
- Fail: https://openqa.suse.de/tests/12314256#step/libssh/64
- Verification run: https://dzedro.suse.cz/tests/1808
> Don't add or remove modules on Maintenance tests

- lib/YaST/Bootloader/BootloaderOptionsPage.pm
- Related ticket: https://progress.opensuse.org/issues/135512
- Needles:-
- SLE: https://openqa.suse.de/tests/12327058
- Tumbleweed Staging: https://openqa.suse.de/tests/12327058
> Fix issue with new widget IDs in YaST

- data/yam/autoyast/support_images/sles15sp3_install_minimal_default_patterns_s390x.xml
- data/yam/autoyast/support_images/sles15sp3_install_minimal_default_patterns_x86_64.xml
- Related ticket: https://progress.opensuse.org/issues/135677
- Verification run: [link](https://openqa.suse.de/tests/overview?arch=&flavor=&machine=&test=sles_15sp3_autoyast_support_image_minimal_def_module_1&modules=&module_re=&distri=sle&version=15-SP3&build=GM&groupid=220#)
- verified with migration jobs with minimal: [link](https://openqa.suse.de/tests/overview?arch=&flavor=&machine=&test=offline_sles15sp3_pscc_basesys-srv-python3_def_full_test&modules=&module_re=&distri=sle&version=15-SP6&build=20.1&groupid=220#)
- Related MR: https://gitlab.suse.de/qa-maintenance/qam-openqa-yml/-/merge_requests/619
> Create support image on SLE 15 SP3 with minimal role

- lib/kdump_utils.pm
* Based on #17805 which makes the kdump setup work on transactional systems
* I was not able to verify #17805 due to https://bugzilla.suse.com/show_bug.cgi?id=1213721 so this PR is still a draft. However, with the additional commit to allow testing kdump on SLE Micro as well I was able to verify that it works on SLE Micro.
* See particular commit messages and https://progress.opensuse.org/issues/136028
> Allow testing kdump on SLE Micro

- tests/qam-minimal/install_update.pm
- Related ticket: https://progress.opensuse.org/issues/131534
- Verification run: https://openqa.suse.de/tests/12358520
> Add extra repos on TERADATA before grub2 update

- tests/yam/agama/auto.pm
- Description: Adjust the assert_screen sequence in agama tests
- Related ticket: https://progress.opensuse.org/issues/135227
- Verification run: [overview](https://openqa.opensuse.org/tests/overview?build=issues-135227)
> Adjust the assert_screen sequence in agama tests

- tests/console/yast2_registration.pm
Quick PR for issue _qam-scc_
- Verification run: [overview](https://openqa.suse.de/tests/overview?build=issues-qam-scc)
> Issue qam-scc: assert_screen timeout 600

- schedule/qam/12-SP1/mau-extratests-phub.yaml
- schedule/qam/12-SP2/mau-extratests-phub.yaml
- schedule/qam/12-SP3/mau-extratests-phub.yaml
- schedule/qam/12-SP4/mau-extratests-phub.yaml
- schedule/qam/12-SP5/mau-extratests-phub.yaml
- schedule/qam/15-SP1/mau-extratests-phub.yaml
- schedule/qam/15-SP2/mau-extratests-phub.yaml
- schedule/qam/15-SP3/mau-extratests-phub.yaml
- schedule/qam/15-SP4/mau-extratests-phub.yaml
- schedule/qam/15-SP5/mau-extratests-phub.yaml
- schedule/qam/15/mau-extratests-phub.yaml
- schedule/qam/common/mau-extratests2.yaml
- tests/console/ansible.pm
- tests/console/systemd_rpm_macros.pm
- Related ticket: https://openqa.suse.de/tests/12364842
- Verification run: https://openqa.suse.de/tests/overview?distri=sle&build=phub
> Move tests with phub into extratest-phub

- .github/workflows/ci.yml
See https://github.com/os-autoinst/os-autoinst/pull/2372
> Update Perl::Tidy to 20230912

- data/autoyast_qam/15-common_base_installation.xml.ep
86e75fc57bdcb4eeb36ec6bc1e4d3e9f891f8b33
https://openqa.suse.de/tests/12381788#step/validate_packages_and_patterns/20
https://openqa.suse.de/tests/12381754#step/validate_packages_and_patterns/20
https://bugzilla.suse.com/show_bug.cgi?id=1202234
https://dzedro.suse.cz/tests/1844 -> https://dzedro.suse.cz/tests/1845
https://openqa.suse.de/tests/12382936 15-SP1
https://openqa.suse.de/tests/12382939 15-SP2
> Restore workaround for bsc1202234 on 15-SP2

- tests/console/ansible.pm
- Related ticket: https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/17899
https://openqa.suse.de/tests/12396206
https://openqa.suse.de/tests/12396207
https://openqa.suse.de/tests/12396239
> ansible: Fix phub module in security group

- tests/console/suseconnect.pm
see https://progress.opensuse.org/issues/135488
verification:
http://10.168.192.143/tests/79
> Fix sporadic failure of 'suseconnect -d'

- data/autoyast_qam/12-common_base_installation.xml.ep
- data/autoyast_qam/12_installation.xml.ep
- data/autoyast_qam/15-common_base_installation.xml.ep
- data/autoyast_qam/15_installation.xml.ep
- data/autoyast_sle12/autoyast_sles12sp3+alladdons_allpatterns_reg_full_s390x.xml
- data/autoyast_sle12/autoyast_sles12sp3+alladdons_default_reg_full_s390x.xml
- data/autoyast_sle12/autoyast_sles12sp3+sdk+ha+geo_allpatterns_reg_full_s390x.xml
- data/autoyast_sle12/autoyast_sles12sp3+sdk+ha+geo_default_reg_full_s390x.xml
- data/autoyast_sle12/autoyast_sles12sp3_allpatterns_reg_full_s390x.xml
- data/autoyast_sle12/autoyast_sles12sp3_default_reg_full_s390x.xml
- data/autoyast_sle12/ay.xml
- data/qam/dracut/12-SP2_custom_lvm.xml.ep
- data/qam/dracut/12-SP2_custom_usr.xml.ep
- data/qam/dracut/12_custom_lvm.xml.ep
- data/yam/autoyast/support_images/create_hdd_ha_sles.xml.ep
- data/yam/autoyast/support_images/create_hdd_sles_regression_aarch64.xml.ep
- data/yam/autoyast/support_images/create_hdd_sles_regression_s390x.xml.ep
- data/yam/autoyast/support_images/sles12sp5_install_all_patterns_s390x.xml
- data/yam/autoyast/support_images/sles12sp5_install_default_patterns_s390x.xml
- Related ticket: https://openqa.suse.de/tests/12396302 https://suse.slack.com/archives/C02CANHLANP/p1696574135714859
- Verification run: https://openqa.suse.de/tests/overview?build=s390x_route&distri=sle each job is running on different s390x worker
> Use different gw ip based on SUT location/hostname

- schedule/migration/migration_offline_sap.yaml
- schedule/migration/migration_online_sap.yaml
- schedule/yast/autoyast/autoyast_sap.yaml
https://progress.opensuse.org/issues/137057
[15-sp4](http://openqa.suse.de/t12318823)
[15-sp3](http://openqa.suse.de/t12318826)
> Use new NW server for sap tests

- schedule/yast/minimal+base/minimal+base@s390x_zvm.yaml
Added open ssh port test moudle
- Verification run: https://openqa.suse.de/tests/12417043
> Added open ssh port test moudle

- test_data/yam/agama_full_disk_encryption.yaml
> Need backup path for agama TW

- data/yam/agama/auto/alp_dolomite.jsonnet
- schedule/yam/agama_auto_dolomite_select_installation_device.yaml
- test_data/yam/agama_auto_micro_aarch64.yaml
Validate the install biggest disk for agama dolomite 
- Related ticket: https://progress.opensuse.org/issues/133109
- Verification run: https://openqa.opensuse.org/tests/3629923
https://openqa.opensuse.org/tests/3629924
> Validate the install biggest disk for agama dolomite 

- lib/containers/k8s.pm
- Failure: https://openqa.opensuse.org/tests/3627441#step/podman_pods/157
- Verification run: https://openqa.opensuse.org/tests/3631645
> lib/containers/k8s.pm: Leap does not have the k3s-install package

- schedule/security/alp/fde_regen_key.yaml
- tests/security/fde_regenerate_key.pm
- Related ticket: https://progress.opensuse.org/issues/134987
- Verification run: https://openqa.suse.de/tests/12431066
> Add fde_regenerate_key.pm

- schedule/security/alp/check_tpm2.yaml
- schedule/security/alp/fde_regen_key.yaml
- tests/security/tpm2/check_tpm2.pm
- Related ticket: https://progress.opensuse.org/issues/137675
- Verification run: https://openqa.suse.de/tests/12439865
> Add check_tpm2.pm

- data/yam/autoyast/support_images/sles15sp3_install_minimal_default_patterns_s390x.xml
- data/yam/autoyast/support_images/sles15sp3_install_minimal_default_patterns_x86_64.xml
**Verification run** 
- https://openqa.suse.de/tests/12455553
- https://openqa.suse.de/tests/12455554
**verified with migration jobs with minimal**
- https://openqa.suse.de/tests/12455616
- https://openqa.suse.de/tests/12455618
> add yast2-registration in sle15sp3_mininal_role's profile

- data/yam/autoyast/support_images/sles15sp4_install_minimal_default_patterns_aarch64.xml
https://progress.opensuse.org/issues/135713
VR: 
[publish_qcow2](https://openqa.suse.de/tests/12455808)
[migration test with published qcow2](https://openqa.suse.de/tests/12455976)
> Create support image on SLE 15 SP4 with minimal role

- lib/xml_utils.pm
Otherwise exporting functions don't work.
Related: #17965
> Add a package statement to xml_utils.pm

- data/yam/agama/auto/alp_dolomite.jsonnet
Reconfigure the jsonnet file with new format
- Verification run: https://openqa.opensuse.org/tests/3641659
> Reconfigure the jsonnet file with new format

- data/yam/autoyast/support_images/sles15sp4_install_gnome_all_patterns_aarch64.xml
- data/yam/autoyast/support_images/sles15sp4_install_gnome_all_patterns_s390x.xml
- data/yam/autoyast/support_images/sles15sp4_install_gnome_all_patterns_x86_64.xml
- data/yam/autoyast/support_images/sles15sp4_install_textmode_all_patterns_aarch64.xml
- data/yam/autoyast/support_images/sles15sp4_install_textmode_all_patterns_s390x.xml
- data/yam/autoyast/support_images/sles15sp4_install_textmode_all_patterns_x86_64.xml
https://progress.opensuse.org/issues/135995
[create hdd qcow2 images](https://openqa.suse.de/tests/overview?version=15-SP4&build=20231012-1&groupid=251&distri=sle)
[migration tests with published qcow2 images](http://openqa.suse.de/tests/overview?version=15-SP6&distri=sle&build=rfan1016)
**MR for adding the new tests**
[MR-643](https://gitlab.suse.de/qa-maintenance/qam-openqa-yml/-/merge_requests/643)
> Create support image with default modules and all patterns on SLE15SP4

- data/xfstests/wrapper.sh
Sometime we need debug or reproduce issue manually, so add a switch to collect xtrace of xfstests
Set INJECT_INFO='<line-number> xtrace' to test to enable it and start to
record command start after inject line <line-number>, and redirect debug
info info to /opt/log/xxx_xtrace.log
- Related ticket: https://progress.opensuse.org/issues/136955
- Needles: N/A
- Verification run: http://10.67.129.54/tests/854
> xfstests: Add xtrace option for inject_info

- tests/kernel/kselftests.pm
With this patch we add support for kselftests execution in ALP as well as downloading kernel source code from Linux kernel official repository.
- Related ticket: https://progress.opensuse.org/issues/132680
- Verification run: https://openqa.suse.de/tests/12542468#
> Add ALP support in kselftests module

- tests/console/zziplib.pm
- Related ticket: https://openqa.suse.de/tests/12560302
- Verification run: https://openqa.suse.de/tests/12546401
> zziplib: Add verbose for debugging

- tests/x11/seahorse_sshkey.pm
- Related ticket: https://progress.opensuse.org/issues/137729
- 15-SP5: https://openqa.suse.de/tests/12563653
- 15-SP4: https://openqa.suse.de/tests/12563803
> seahorse_sshkey.pm: add auto-agree-with-licenses to SCC

- lib/x11test.pm
- Related ticket: https://progress.opensuse.org/issues/135836 https://progress.opensuse.org/issues/133382
https://dzedro.suse.cz/tests/1972
https://dzedro.suse.cz/tests/1973
> firefox: Increase timout for started firefox

- tests/transactional/install_updates.pm
- Related ticket: https://openqa.suse.de/tests/12574312#step/install_updates/5
- Verification run: https://openqa.suse.de/tests/12574609
> transactional/install_updates: Use script_retry on curl command

- lib/containers/common.pm
- Related ticket: https://progress.opensuse.org/issues/138260
https://openqa.suse.de/tests/12574346#step/podman/34 s390x
https://openqa.suse.de/tests/12574607#step/podman/34 x86_64
https://openqa.suse.de/tests/12574356#step/podman/34 aarch64
> Disable ipv6 as workaround 

- tests/containers/privileged_mode.pm
- `/dev/bus` exists in minimal-vm images, therefore should not be excluded.
- overlayfs support starts with kernel 4.18.
- ticket: https://progress.opensuse.org/issues/135518#note-18
http://kepler.suse.cz/tests/22032#step/docker_privileged_mode/61
http://kepler.suse.cz/tests/22034#step/docker_privileged_mode/74
http://kepler.suse.cz/tests/22036#step/docker_privileged_mode/74
http://kepler.suse.cz/tests/22033#step/docker_privileged_mode/65
http://kepler.suse.cz/tests/22035#step/docker_privileged_mode/74
> Small fixes for container privileged test case

- lib/kdump_utils.pm
* Merge the basic check whether the `vmcore` file exists with the basic check that it is of non-zero size
* Invoke `crash` on transactional systems via `podman` using a Tumbleweed container (unless the installation of debuginfo was skipped because this seems to be required by `crash`)
* See https://progress.opensuse.org/issues/137891
---
VR: https://openqa.suse.de/tests/12576177
> Check dumps created via kdump with `crash` also on transactional systems

- tests/qemu/qemu.pm
- Related ticket: https://openqa.suse.de/tests/12584506#step/qemu/10
https://openqa.suse.de/tests/12599369
https://openqa.suse.de/tests/12615268
> Wait longer for qemu-system-s390x to finish

- tests/security/apparmor/aa_autodep.pm
Ticket: https://progress.opensuse.org/issues/138392
VRs:
* 12-SP5: https://openqa.suse.de/tests/12634227
* 15-SP1: https://openqa.suse.de/tests/12634215
* 15-SP2: https://openqa.suse.de/tests/12634216
* 15-SP4: https://openqa.suse.de/tests/12634217
> aa_autodep.pm: delete file only if it exists

- data/toolkits/Makefile
- data/toolkits/gtk4.c
Ticket: https://progress.opensuse.org/issues/138419 https://progress.opensuse.org/issues/138422
VR: https://openqa.opensuse.org/tests/3669988
> Fix gtk4 and qt6 toolkit tests on Leap

- lib/qesapdeployment.pm
- t/09_qesapdeployment.t
- t/15_qesap_azure.t
The unit tests for the new functions introduced to clean old peerings.
- Related ticket: https://jira.suse.com/browse/TEAM-8671
- Verification run: (look at current pipeline)
> Add tests for peering cleaner funcs

- data/journal_check/bug_refs.json
- Verification run: https://openqa.opensuse.org/tests/3669986
> data/journal_check/bug_refs.json: Add boo#1215383

- tests/x11/xfce_lightdm_logout_login.pm
- Related ticket: https://openqa.opensuse.org/tests/3623112#step/xfce_lightdm_logout_login/6
https://openqa.opensuse.org/tests/3666668
https://openqa.opensuse.org/tests/3661028
https://openqa.opensuse.org/tests/3661029
> Fix occasional xfce Live failures

- lib/main_micro_alp.pm
See the added comment.
- Related ticket: https://openqa.opensuse.org/tests/3674252
- Verification run: https://openqa.opensuse.org/tests/3675125#live
> lib/main_micro_alp.pm: Work around a case of poo#109929

- lib/susedistribution.pm
- Related ticket: https://progress.opensuse.org/issues/138554 https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/18051
- Verification run: https://openqa.oqa.prg2.suse.org/tests/12679208
> Don't assert logged root on hyperv

- tests/console/year_2038_detection.pm
- Related ticket: https://progress.opensuse.org/issues/138590
- Verification run: https://openqa.opensuse.org/tests/3677387
> console/year_2038_detection.pm: Use actual commands, not {u,w}tmpdump

- data/journal_check/bug_refs.json
- Related ticket: https://openqa.opensuse.org/tests/3677243#step/journal_check/21
- Verification run: https://openqa.opensuse.org/tests/3677461#live
> data/journal_check/bug_refs.json: Catch more cases of boo#1215383

- tests/hpc/spack_master.pm
Generate XML file with test results.
- Related ticket: https://progress.opensuse.org/issues/119725
https://openqa.suse.de/tests/overview?build=b10n1k%2Fos-autoinst-distri-opensuse%2318083&version=15-SP6&distri=sle
> [HPC] Add xml results to the spack module

- data/journal_check/bug_refs.json
- Related ticket: [poo#138611](https://progress.opensuse.org/issues/138611)
- Verification run: [selinux](https://openqa.suse.de/tests/12715432)
> Whitelist known bugs in journal for ALP

- tests/security/pam/pam_faillock.pm
- tests/security/pam/pam_mount.pm
- tests/security/pam/pam_su.pm
- tests/security/pam/pam_u2f.pm
- Related ticket: https://progress.opensuse.org/issues/138713
- Verification runs: https://openqa.suse.de/tests/overview?distri=sle&version=15-SP5&build=20231029-1&groupid=431
> Multiple fixes for pam tests on aarch64

- tests/sles4sap/hana_install.pm
openQA can provide installation artifacts to the SUT from the test server. Switching to that method from NFS allows us to run more tests as we are not limited by the bandwidth of the NFS server but the connection of the openQA server to the SUT. However the old method will be kept for now.
Additionally the server option is provided to the HANA installer as it is the only one we are explicitly installing.
Related ticket: https://jira.suse.com/browse/TEAM-8573
* Verification run:
[15sp4](https://openqa.suse.de/tests/12721495)
[15sp3](https://openqa.suse.de/tests/12716115)
[15sp2](https://openqa.suse.de/tests/12716111)
[15sp1](https://openqa.suse.de/tests/12716102)
[12sp5](https://openqa.suse.de/tests/12716100)
> Download SAP HANA install media from OSD instead of NFS

- tests/security/cc/audit_remote_libvirt.pm
Check libvirt daemons in modular mode, which now is the default mode in SLE 15-SP6 using library.
For further info, please see [checking-whether-modular-monolithic-mode-is-in-use](https://libvirt.org/daemons.html#checking-whether-modular-monolithic-mode-is-in-use)
- Related ticket: [poo#137627](https://progress.opensuse.org/issues/137627)
- Verification run: [cc_audit-remote-libvirt](https://openqa.suse.de/tests/12735532#step/audit_remote_libvirt/16) (notice now fails in a different issue already tracked)
> Check libvirt in modular mode (default 15-SP6)

- schedule/security/fips_crypt_core.yaml
- schedule/security/fips_crypt_firefox.yaml
- schedule/security/fips_crypt_kernel.yaml
- schedule/security/fips_crypt_openjdk.yaml
- schedule/security/fips_crypt_squid.yaml
- schedule/security/fips_crypt_tool.yaml
- schedule/security/fips_crypt_web.yaml
- schedule/security/fips_crypt_x11.yaml
- schedule/security/fips_env_mode_powervm.yaml
- schedule/security/fips_ker_mode_powervm.yaml
Ticket: https://progress.opensuse.org/issues/138470
> Refactor FIPS schedule on pvm_hmc

- lib/sles4sap_publiccloud.pm
- t/12_sles4sap_publicccloud.t
Wait for the database to change state (online to offline) and use it during the test steps when we expect such state changes to occur.
- Related ticket: https://jira.suse.com/browse/TEAM-8139
https://openqaworker15.qa.suse.cz/tests/251371#
http://openqaworker15.qa.suse.cz/tests/252501#
http://openqaworker15.qa.suse.cz/tests/252508# 
- Verification run after pr comments:
https://openqaworker15.qa.suse.cz/tests/259036#
https://openqaworker15.qa.suse.cz/tests/259082#
https://openqaworker15.qa.suse.cz/tests/259978#
> Wait hana database offline

- lib/services/389ds_sssd_client.pm
- tests/console/sssd_389ds_functional.pm
- tests/migration/openldap_configuration.pm
- Related ticket: https://progress.opensuse.org/issues/138989
- Needles: N/A
- Verification run: [openQA Jobs for this PR](https://openqa.opensuse.org/tests/overview?build=DimStar77%2Fos-autoinst-distri-opensuse%2318117&version=Tumbleweed&distri=opensuse)
> sssd: create config directory if not pre-existing

- tests/fips/fips_setup.pm
* Ticket: https://progress.opensuse.org/issues/133298
* VRs:
* 15-SP5: https://openqa.suse.de/tests/12759929
* 15-SP3: https://openqa.suse.de/tests/12759928
* 12-SP5: https://openqa.suse.de/tests/12759952
* JeOS: https://openqa.opensuse.org/tests/3699468
> Use fips-mode-setup script to setup FIPS in kernel mode.

- data/yam/autoyast/support_images/sles15sp3_install_gnome_all_patterns_s390x.xml
- data/yam/autoyast/support_images/sles15sp3_install_gnome_default_patterns_aarch64.xml
- data/yam/autoyast/support_images/sles15sp3_install_gnome_default_patterns_x86_64.xml
- Related ticket: https://progress.opensuse.org/issues/138461
- Verification run: xx
> pre-install zypper-migration-plugin for support images

- tests/fips/fips_setup.pm
- Related ticket: https://progress.opensuse.org/issues/150803
- Verification run: https://openqa.suse.de/tests/12802509
> Reboot after enabling fips ENV mode

- lib/utils.pm
https://progress.opensuse.org/issues/150800
VR: 
[support img](http://openqa.suse.de/tests/12815624)
[migration 1](https://openqa.suse.de/tests/12816050)
[migration 2](https://openqa.suse.de/tests/12816051)
> Add Workaround for bsc#1202478

- data/journal_check/bug_refs.json
Whitelist known journal issues in other product now appearing in latest ALP build.
Verification run: [selinux](https://openqa.suse.de/tests/12826347)
> Whitelist known journal issues in ALP

- tests/publiccloud/instance_overview.pm
* Hotfix to #18123 
* Verification runs: [pdostal-server.suse.cz](https://pdostal-server.suse.cz)
> Public Cloud: Fix the 'ip' command

- tests/containers/privileged_mode.pm
Gather information on devices visible with privileged mode
> containers: Gather information on devices visible with privileged mode

- data/autoyast_qam/15_installtest.xml.ep
- Related ticket: https://suse.slack.com/archives/C02D16TCP99/p1700055229088079
- Verification run: https://openqa.suse.de/tests/12849548 https://openqa.suse.de/tests/12849671
> Add Server-Applications module on SLED

- schedule/yast/installer_extended/installer_extended_x86_64.yaml
- test_data/yast/installer_extended/installer_extended_aarch64.yaml
- test_data/yast/installer_extended/installer_extended_ppc64le_s390x.yaml
- tests/installation/module_registration/verify_module_registration.pm
https://progress.opensuse.org/issues/150941
- [Verification run](https://openqa.suse.de/tests/overview?arch=&flavor=&machine=&test=test_softfail&modules=&module_re=&build=rfan1117&distri=sle&version=15-SP6#)
> Remove soft failure in module verify_module_registration

- variables.md
Summary all xfstests related parameters into variables.md. The info sync from confluence page https://confluence.suse.com/display/qasle/xfstests+specific+openqa+parameters+introduction
- Verification run: NA
> Add xfstests parameter document into variables.md

- lib/windowsbasetest.pm
Many of our tests fail because a 'Notification center' pop-up appears and the current window loses focus. This two registry keys will help prevent notifications to show up.
- Related ticket: *none*
- Needles: *none*
- Verification runs: tested on my local VM and notifications now leave a "bubble" without showing pop-up
> Disable Windows notifications

- lib/susedistribution.pm
Currently the `S390_HOST`-variable is (ab)used to substitute network settings present in `S390_NETWORK_PARAMS`. E.g. if `S390_HOST=1` then every occurrence of `@S390_HOST@` gets replaced by `1`. This was used in the past to derive network parameters for linuxrc and other things like usernames for zVM guests but requires the network infrastructure to be precisely set up for every zVM machine (the machine needs to be called e.g. `zvm1`, the username needs to end with `1` and the IP as well).
This change makes use of DNS to resolve the FQDN in `ZVM_GUEST` into an IP (which is unfortunately required by linuxrc) and derive the hostname and username from it (everything before the domain). We also introduce `ZVM_GUEST_SUBNETMASK` because it was assumed to be /24 previously and cannot always be …
> Rewrite s390 console to work with arbitrary IP and Hostname combinations

- schedule/security/oscap_stig.yaml
Ticket: https://progress.opensuse.org/issues/151328
VRs: https://openqa.suse.de/tests/overview?distri=sle&version=15-SP5&build=20231122-1&groupid=431
> Schedule oscap_eval_remote only on s390x

- lib/qesapdeployment.pm
- tests/sles4sap/publiccloud/qesap_ansible.pm
- tests/sles4sap/qesapdeployment/deploy.pm
Fix ansible "Timed out waiting for last boot time check" on Azure.
Added terraform/ansible retry when hit ansible "Timed out waiting for last boot time check" .
Fixed some tidy issue.
TEAM-6903 - [qesap][Azure] Ansible error: Timed out waiting for last boot time check (timeout=600)
- Related ticket: https://jira.suse.com/browse/TEAM-6903
Detected "timed out" and try "deploy retry" passed: 
https://openqa.suse.de/tests/12855001#step/deploy_qesap_ansible/63
https://openqa.suse.de/tests/12855019#step/deploy_qesap_ansible/63
Comment (no "timed out" issue) run passed:
https://openqa.suse.de/tests/12855002
> Fix ansible "Timed out waiting for last boot"

- lib/migration.pm
- tests/console/system_prepare.pm
- tests/migration/online_migration/post_migration.pm
- tests/migration/online_migration/zypper_patch.pm
- tests/update/patch_sle.pm
- Related ticket: https://progress.opensuse.org/issues/150977
- Verification run: http://falafel.suse.cz/tests/1380
> Remove soft_fail when modifying kernel multiversion

- schedule/yast/rmt_server_install/rmt_server_install.yaml
Added access_beta_distribution test module
> Added access_beta_distribution test module

- tests/virt_autotest/kubevirt_tests_server.pm
New changes from sle15sp6:
1. DevCI Longhorn stable version changed to v1.5.1
2. One fix requires to update in QA automation - https://gitlab.suse.de/virtualization/kubevirt-ci/-/commit/66f54c10adbfc7df63b825141745b3ed20824c06
3. Below changes in virt-tests command from v1.0.0
--ginkgo.slow-spec-threshold => --ginkgo.poll-progress-after
--ginkgo.progress=true => --ginkgo.show-node-events
- Related ticket: https://progress.opensuse.org/issues/133598
- Verification run: http://10.67.129.96/tests/2593
> Adapt kubevirt new changes from v1.0.0

- tests/containers/host_configuration.pm
The host_configuration test uses VERSION to determine the URL of the SUSE CA repository. This is wrong, as the VERSION field in those tests represent the VERSION of the container image, not the host version. We've added the variable HOST_VERSION to determine this.
- [BCI base 15-SP5 on 15-SP5](https://openqa.suse.de/tests/12931274) :white_check_mark: 
- [BCI base 15-SP5 on Liberty 9](https://openqa.suse.de/tests/12931275) :white_check_mark: 
- [BCI base 15-SP5 on Leap 15.5](https://openqa.suse.de/tests/12931276) :white_check_mark:
Related to: https://gitlab.suse.de/qac/qac-openqa-yaml/-/merge_requests/1400
> Added variable HOST_VERSION

- schedule/security/security_misc_o3.yaml
Ticket: https://progress.opensuse.org/issues/151765
> Add schedule/security/security_misc_o3.yaml

- tests/containers/host_configuration.pm
Latest change is trying to install certs and use `zypper` in non-SUSE distros. This PR is paired with https://github.com/os-autoinst/opensuse-jobgroups/pull/394
- Related ticket: https://progress.opensuse.org/issues/151834
- Reverts: https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/18234
- [Tumbleweed](https://openqa.opensuse.org/tests/3774119)
- [SLE15-SP5](https://openqa.suse.de/tests/12941767)
- [Leap](https://openqa.suse.de/tests/12941766)
- [RHEL](https://openqa.suse.de/tests/12941768)
- [Liberty](https://openqa.suse.de/tests/12941769)
> Install certs only for SUSE and openSUSE

- lib/main_publiccloud.pm
This PR enables the cloud-netconfig test on Azure for `latest`.
- Verification run: https://openqa.suse.de/tests/12941799
> Add cloud-netconfig test to schedule latest

- tests/network/config_services.pm
- Related ticket: https://progress.opensuse.org/issues/151693
- Verification run: https://openqa.suse.de/tests/overview?distri=sle&build=jpupava_mail
> mail server: Fix thunderbird test due to latest SCC changes

- tests/support_server/setup.pm
After f8f29e9267e67f251ecda4a8661f6add707fbf69, whenever the `support_server/setup` module runs on migration scenarios (where the support server itself was configured by a previous job), named fails to start because the file `/etc/named.d/openqa.zones` gets included twice into the configuration:
First by the existing `/etc/named.conf`, which has a line including the file `/etc/named.conf.include`, which eventually includes `/etc/named.d/openqa.zones`.
Second by the changes submitted in f8f29e9267e67f251ecda4a8661f6add707fbf69 which explicitly include `/etc/named.d/openqa.zones` into `/etc/named.conf`.
This commit adds a workaround for such cases, by commenting in `/etc/named.conf` the inclusion of `/etc/named.conf.include` when the module runs on a support server which was previously …
> Comment inclusion of /etc/named.conf.include on /etc/named.conf

- schedule/migration/migration_offline_scc_deregistration_aarch64.yaml
- schedule/migration/migration_offline_scc_deregistration_ppc64le.yaml
- schedule/migration/migration_offline_scc_deregistration_s390x.yaml
- schedule/migration/migration_offline_scc_deregistration_x86_64.yaml
Added yaml files for offline migration with public hdd image
- Related ticket: https://progress.opensuse.org/issues/150974
- Verification run: http://openqa.suse.de/t12873898
http://openqa.suse.de/t12873901
http://openqa.suse.de/t12873902
http://openqa.suse.de/t12873904
- MR: https://gitlab.suse.de/qe-yam/openqa-job-groups-migrations/-/merge_requests/393
> Added yaml files for offline migration with public hdd image

- lib/Mitigation.pm
Modify the execution mode for host mitigations.
change to run all cases.
- Verification run: http://openqa.qa2.suse.asia/tests/65011
> Modify the execution mode for host mitigations.

- lib/virt_autotest/utils.pm
https://progress.opensuse.org/issues/151364
- Verification run: https://openqa.suse.de/tests/12966977
> Replace fake poo or bug id with the softfailure umbrella poo#151361

- tests/publiccloud/cloud_netconfig.pm
This fixes the test for 12-SP5 and drops some code for releases prior to SLES 12.
Previously, 12-SP5 failed because there was confusion with a version constraint defined in the specfile for cloud-netconfig.
- Verification run: https://openqa.suse.de/tests/12968150
> Fix cloud-netconfig for 12-SP5

- tests/jeos/firstrun.pm
- Related ticket: https://progress.opensuse.org/issues/151558
- Verification run: https://openqa.suse.de/tests/12973651#step/firstrun/1
> Adapt firstrun to sle micro 6.0

- lib/hacluster.pm
Record SAP/HA upload supportconfig log softfail as it hangs on 12-SP5.
Make it softfail for not blocking qem bot auto approvals on 12-SP5.
Currently not sure if it is related to poo#151612
TEAM-8837 - [ sle-12-SP5] [on-prem] SAPHanaSR_ScaleUp_PerfOpt_node0x failed on test module "check_logs": 'supportconfig -g -B hana' timed out
- Related ticket: https://jira.suse.com/browse/TEAM-8837
- Needles: NA
https://openqa.suse.de/tests/12966866#step/check_logs/35 (check_logs softfailed on 12-SP5)
http://openqa.suse.de/tests/12965897#step/check_logs/40 (check_logs passed on 15-SP5)
> Make SAP/HA upload supportconfig log conditional

- lib/yast2_widget_utils.pm
- Description:
* Apply workaround for the gtk glitches for iscsi_client
- Related ticket: https://progress.opensuse.org/issues/152065
- Needles: N/A
* https://openqa.suse.de/tests/12979469
* https://openqa.suse.de/tests/12979470
> Apply workaround for the gtk glitches for iscsi_client

- tests/console/libssh.pm
- Verification run: https://openqa.suse.de/tests/overview?distri=sle&build=jpupava_libssh restarted multiple times
> libssh: Use serial terminal

- tests/fips/fips_setup.pm
- Related ticket: https://progress.opensuse.org/issues/131435
- 15-SP4: https://openqa.suse.de/tests/12980588#step/fips_setup/1
- ALP: https://openqa.suse.de/tests/12980555#step/fips_setup/1
- SLE Micro: https://openqa.suse.de/tests/12981654#step/fips_setup/1
> Refactor fips/fips_setup.pm

- schedule/security/alp/container_selinux.yaml
- schedule/security/alp/fde_misc.yaml
- schedule/security/alp/fips_crypt_core.yaml
- schedule/security/selinux.yaml
- Related ticket: https://progress.opensuse.org/issues/151552
- https://openqa.suse.de/tests/12980657#step/suseconnect_scc/1
- https://openqa.suse.de/tests/12980910#step/suseconnect_scc/1
> Use suseconnect_scc on SLEM

- tests/security/selinux/audit2allow.pm
- tests/security/selinux/semanage_boolean.pm
- tests/security/selinux/semodule.pm
- tests/security/selinux/sestatus.pm
- Related ticket: https://progress.opensuse.org/issues/152200
- Verification run: https://openqa.suse.de/tests/12999166 (compare to current https://openqa.suse.de/tests/12991920)
> Adapt more selinux modules to ALP Micro 6.0

- tests/ai_ml/tvm.pm
- Related ticket: https://bugzilla.opensuse.org/show_bug.cgi?id=1217914
- x86_64: https://openqa.opensuse.org/tests/3799852
- aarch64: https://openqa.opensuse.org/tests/3799851
> tvm: Fix resnet50-v2-7.onnx URL

- schedule/qam/QR/15-SP5/raid/raid5_sle_gpt_prep_boot.yaml
Missed in #17941
- Related ticket: https://openqa.suse.de/tests/13049093#step/raid_gpt/4
- Verification run: https://openqa.suse.de/tests/13049882
> Fix version in QR RAID yaml

- tests/console/zfs.pm
Adds the 15.6 version to the repo list.
- Related failure: https://openqa.opensuse.org/tests/3802618
- Verification run: https://openqa.opensuse.org/tests/3805841
> Add 15.6 to repository list

- tests/console/java.pm
- Related ticket: https://progress.opensuse.org/issues/15220
- Needles: N/A
- Verification run: https://openqa.opensuse.org/tests/3789882
> java: limit package installations to OSS repo on openSUSE

- tests/xfstests/install.pm
Add repo for xfstests in sle-micro6.0
- Related ticket: https://progress.opensuse.org/issues/151861
- Verification run: https://openqa.suse.de/tests/13060819
> xfstests: Add repo for SLE Micro6.0

- lib/main_common.pm
- tests/x11/thunar.pm
- Needles: Created one for the VR on o3, others need to be created
- Verification run: https://openqa.opensuse.org/tests/3809351
> x11/thunar.pm: Wait for thunar to open before pressing keys + bonus fix

- tests/security/nproc_limits.pm
Ticket: https://progress.opensuse.org/issues/152434
VRs:
- 15-SP6: https://openqa.suse.de/tests/13062482
- 15-SP5: https://openqa.suse.de/tests/13062481
- 12-SP5: https://openqa.suse.de/tests/13062489
> Adapt nproc_limits.conf to new file location

- tests/console/journald_fss.pm
Ticket: https://progress.opensuse.org/issues/152440
VRs:
- 15-SP6: https://openqa.suse.de/tests/13062654#step/journald_fss/1
- 15-SP5: https://openqa.suse.de/tests/13062656#step/journald_fss/1
> Adapt journald_fss.pm to 15-SP6

- tests/publiccloud/storage_perf.pm
FIO storage tests in publiccloud, updated to write data into the new bucket `perf_2` of Influxdb
Some parametrs added to the db/record structure, to better identify the tested storage: DISTRI, ARCH, REGION, jobID, PUBLIC_CLOUD_PROVIDER.
`PUBLIC_CLOUD_FIO_TABLE` can be used to send data to a different table of the DB; default table is `storage_fio`.
- Related ticket: PR[152035](https://progress.opensuse.org/issues/152035)
- Needles:none
- sle-15-SP6-EC2-BYOS-x86_64-Build0457-publiccloud_fio.VR14 @ec2_t3.small
https://openqa.suse.de/tests/13072766#
The data produced in above VR have been also checked on Influxdb in the assigned table and are all ok as expected.
> FIO tests saved in perf_2 of influxdb

- tests/containers/podman_netavark.pm
Re-enable ipv6 after it was disabled in
https://github.com/os-autoinst/os-autoinst-distri-opensuse/blame/master/lib/containers/common.pm#L303
- Verification run: http://kepler.suse.cz/tests/22373#step/podman_netavark/156
> Enable ipv6 for netavark testing on sle-micro

- tests/console/sudo.pm
Fix for sudo on Azure for SLE 15-SP4+
- Related ticket: https://progress.opensuse.org/issues/151873
https://openqa.suse.de/tests/13103051
> Fix for sudo on Azure for SLE 15-SP4+

- tests/btrfs-progs/install.pm
1. add DEPENDENCY_REPO to instead of individual package
2. rename repo name 'filesystems' to btrfs-progs-repo
3. add 'repo info' for repo uri
- Related ticket: https://progress.opensuse.org/issues/152623
- Needles: N/A
- http://10.67.129.54/tests/893 (SLES)
- http://10.67.133.133/tests/407 (ALP)
> btrfs-progs: add DEPENDENCY_REPO for btrfs-progs

- tests/sles4sap/hana_install.pm
Fix sle15sp6 pip install failed.
The original failure is `Test died: command 'pip install $(ls /hana/shared/HA1/hdbclient/hdbcli-*.tar.gz)' failed`.
Also fixed some tidy errors.
The reason why add `"--components=server,client"` to line 269:
CI check of `Running compile tests ` reports error `Possible attempt to separate words with commas at tests/sles4sap/hana_install.pm line 259.`
TEAM-8787 - sle15sp6 37.1 pip install failed
- Related ticket: https://jira.suse.com/browse/TEAM-8787
- Needles: NA
https://openqa.suse.de/tests/13101296#dependencies (test cases passed)
> Fix sle15sp6 pip install failed

- tests/containers/podman_netavark.pm
There is a podman network backend change aligned with ALP and sle-micro 6.0
- ticket: https://progress.opensuse.org/issues/152551
* [sle-micro-6.0-Base-x86_64-Build7.1-slem_containers@64bit](http://kepler.suse.cz/tests/22381#step/podman_netavark/1)
* [sle-micro-5.5-Default-Updates-x86_64-Build20231218-1-slem_containers@64bit](http://kepler.suse.cz/tests/22382#step/podman_netavark/1)
* [opensuse-15.6-DVD-x86_64-Build569.2-extra_tests_textmode_podman_containers@64bit](http://kepler.suse.cz/tests/22380#step/podman_netavark/1)
* [tw](http://kepler.suse.cz/tests/22379)
> Tumbleweed switched from cni to netavark

- lib/main_publiccloud.pm
- tests/publiccloud/check_registercloudguest.pm
- variables.md
- Related ticket: [poo#138221](https://progress.opensuse.org/issues/138221)
- Related merge request: [gitlab.suse.de/qac/qac-openqa-yaml!1416](https://gitlab.suse.de/qac/qac-openqa-yaml/-/merge_requests/1416)
- Verification run: [aggregates](https://pdostal-server.suse.cz/tests/5441), [latest](https://pdostal-server.suse.cz/tests/5442), [registrations](https://pdostal-server.suse.cz/tests/5440)
> Introduce dedicated registration test

- lib/qesapdeployment.pm
Add function argument to control verbosity of ansible in functions to communicate with nodes.
Default is low verbosity.
This is not about verbosity during the deployment but for ansible commands to perform various test operations after the deployment. Remove some local variables from lib qesapdeployment.pm.
- Related ticket:  [TEAM-8396](https://jira.suse.com/browse/TEAM-8396)
- http://openqaworker15.qa.suse.cz/tests/273293 :green_circle: 
- http://openqaworker15.qa.suse.cz/tests/273303 :green_circle: 
- http://openqaworker15.qa.suse.cz/tests/273304 :green_circle: 
- http://openqaworker15.qa.suse.cz/tests/273294 :green_circle: 
- http://openqaworker15.qa.suse.cz/tests/273305 :green_circle: 
- http://openqaworker15.qa.suse.cz/tests/273291
- http://openqaworker15.qa.suse.cz/tests/273306
> Reduce verbosity of Ansible commands in qesap

- lib/qesapdeployment.pm
- t/09_qesapdeployment.t
Use a more generic Ansible label to target the HANA nodes. Hostname is not generic enough: for example in GCP the host name is composed as vmhana0[1|2]-<resource group name>.
- Related ticket: [TEAM-8869](https://jira.suse.com/browse/TEAM-8869)
- sle-15-SP4-Qesap-Gcp-Byos-x86_64-BuildLATEST_GCE_SLE15_4_BYOS-qesap_gcp_sapconf_test@64bit -> http://openqaworker15.qa.suse.cz/tests/273311
Here the change at work http://openqaworker15.qa.suse.cz/tests/273311/logfile?filename=serial_terminal.txt
`ansible-playbook` is called wit the new syntax `hana[0]` and Ansible is properly using it by executing tasks on `qesapval273311-vmhana01`
```
(exec_venv) # ansible-playbook  script_output.yaml -l "hana[0]" -i /root/qe-sap-deployment/terraform/gce/inventory.yaml -u cloudadmin -b --become-user root -e …
```
> More generic HANA node name in qesap_cluster_logs

- data/autoyast_qam/12-common_base_installation.xml.ep
- data/autoyast_qam/12_installation.xml.ep
- data/autoyast_qam/15-common_base_installation.xml.ep
- data/autoyast_qam/15_installation.xml.ep
- tests/installation/add_update_test_repo.pm
Gnome on 12 SP2 & SP3 was crashing because LTSS-TD repo we add in patch_and_reboot, but for that case it's too late
- Related ticket: https://suse.slack.com/archives/C02D16TCP99/p1703147467810819
https://openqa.suse.de/tests/13130367
https://openqa.suse.de/tests/13130276
https://openqa.suse.de/tests/13130277
https://openqa.suse.de/tests/13130278
https://openqa.suse.de/tests/13130279
https://openqa.suse.de/tests/13130282
https://openqa.suse.de/tests/13130369
https://openqa.suse.de/tests/13130287
https://openqa.suse.de/tests/13130289
https://openqa.suse.de/tests/13130290
https://openqa.suse.de/tests/13130321
https://openqa.suse.de/tests/13130323
https://openqa.suse.de/tests/13130325
> Add extra customer repos also during installation

- tests/containers/podman_netavark.pm
In public cloud there might be a possible IP collision with the container and other devices on the network.
- ticket: https://progress.opensuse.org/issues/151876
* [sle-15-SP6-Azure-BYOS-x86_64-Build0453-publiccloud_containers@az_Standard_B2s](http://kepler.suse.cz/tests/22412#step/podman_netavark/238)
* [microos-Tumbleweed-MicroOS-Image-ContainerHost-x86_64-Build20231220-container-host@64bit](http://kepler.suse.cz/tests/22415#step/podman_netavark/228)
* [microos-Tumbleweed-MicroOS-Image-ContainerHost-x86_64-Build20231220-container-host-old2microosnext@64bit](http://kepler.suse.cz/tests/22414#)
> Scope macvlan network

- data/yam/autoyast/support_images/sles15sp3_install_gnome_default_patterns_aarch64.xml
- data/yam/autoyast/support_images/sles15sp3_install_gnome_default_patterns_s390x.xml
- data/yam/autoyast/support_images/sles15sp3_install_gnome_default_patterns_x86_64.xml
Added LTSS addon to the sles15sp3 gnome autoyast profile
- Related ticket: https://progress.opensuse.org/issues/152188
- Verification run: http://openqa.suse.de/tests/13095288#
http://openqa.suse.de/tests/13095289
http://openqa.suse.de/tests/13095291
> Added LTSS addon to the sles15sp3 gnome autoyast profile

- lib/y2snapper_common.pm
- tests/yast2_gui/yast2_bootloader.pm
https://progress.opensuse.org/issues/152548
VRs: https://openqa.suse.de/tests/13121586#details
> Add yast glitch workaround for y2snapper_common

- tests/console/validate_zfcp_multipath.pm
- Description: Update validate_zfcp_multipath to current infrastructure
- Related ticket: [poo#152053](https://progress.opensuse.org/issues/152053)
- Verification run: [overview](https://openqa.suse.de/tests/overview?build=issues-152053)
> Update validate_zfcp_multipath to current infrastructure

- tests/console/sudo.pm
- Related ticket: https://progress.opensuse.org/issues/152915 https://progress.opensuse.org/issues/152915
https://openqa.suse.de/tests/overview?build=dzedro%2Fos-autoinst-distri-opensuse%2318375
> sudo: Fix sudo id -un

- schedule/yam/test_cases/usb_install.yaml
Progress ticket: https://progress.opensuse.org/issues/153007
VRs: https://openqa.suse.de/tests/overview?version=15-SP6&build=sofiasyria%2Fos-autoinst-distri-opensuse%23usb_rm&distri=sle
> Remove system preparation form usb_install test

- schedule/migration/migration_offline_scc_deregistration_aarch64.yaml
- schedule/migration/migration_offline_scc_deregistration_ppc64le.yaml
- schedule/migration/migration_offline_scc_deregistration_x86_64.yaml
continuing progress ticket: https://progress.opensuse.org/issues/152731
> Edit conditional schedule for continuous migration test

- tests/xfstests/partition.pm
To fix some package installation not works in transactional products.
- Related ticket: https://progress.opensuse.org/issues/152641
[nfs3.0 in sle-micro6.0](https://openqa.suse.de/tests/13199458)
[nfs3.0 in SLE15SP6](https://openqa.suse.de/tests/13120791)
> xfstests: Fix nfs tests fail to run in transactional system

- data/journal_check/bug_refs.json
Add softfail for bsc#1217773 for SLEM 5.4.
- Needles: N/A
- Verification run: http://openqa.nue.suse.com/tests/13214377#step/journal_check/10
> Add softfail for bsc#1217773

- schedule/security/fips_crypt_tool.yaml
- schedule/security/vsftpd.yaml
Ticket: https://progress.opensuse.org/issues/137108
VRs:
- 15-SP6: https://openqa.suse.de/tests/overview?distri=sle&version=15-SP6&build=45.1&groupid=431
- 15-SP4: https://openqa.suse.de/tests/overview?distri=sle&version=15-SP4&build=20240107-1&groupid=431
> Run vsftpd under FIPS

- lib/mm_network.pm
- lib/network_utils.pm
- lib/utils.pm
- tests/support_server/setup.pm
- tests/wicked/before_test.pm
- variables.md
See suggestion  in ticket comment https://progress.opensuse.org/issues/152389#note-45
> Allow overriding the MTU for MM tests via `MM_MTU`

- data/journal_check/bug_refs.json
The entry for 1215405 was too broad. Narrowed it down and added additional bug entries
to catch the remaining cases
- https://bugzilla.suse.com/show_bug.cgi?id=1215405
- https://bugzilla.suse.com/show_bug.cgi?id=1205931
- https://bugzilla.suse.com/show_bug.cgi?id=1217872
- Verification run: https://openqa.suse.de/tests/12991975
> Fix bug_refs for bsc#1215405, add entries for bsc#1205931 and bsc#1217872

- lib/qesapdeployment.pm
- t/09_qesapdeployment.t
Remove invalid chars from the Ansible hostname query that result in invalid crm report file name.
Fix for a bug in https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/18350
Related ticket: [TEAM-8869](https://jira.suse.com/browse/TEAM-8869)
- AZURE :  http://openqaworker15.qa.suse.cz/tests/273595 the report is properly collected  http://openqaworker15.qa.suse.cz/tests/273595/file/test_cluster-hana0-crm_report.tar.gz
- GCP : http://openqaworker15.qa.suse.cz/tests/273597 also in gcp the report is properly generated and uploaded to openQA
> Fix crm report filename issue

- tests/console/slp.pm
SLP has been disabled for SSH service on ALP/Tumbleweed.
- [test fails in slp/ssh](https://progress.opensuse.org/issues/152793)
* [opensuse-Tumbleweed-JeOS-for-kvm-and-xen-x86_64-Build20240109-jeos-extra@64bit_virtio-2G](http://kepler.suse.cz/tests/22430#step/slp/1)
> Skip SSH register by slptool

- tests/sles4sap/monitoring_services.pm
The `sles4sap/monitoring_services` test module installs and starts the prometheus node_exporter service and checks that it is running by downloading the metrics with `curl`. In some scenarios, enabling and starting the service and trying to curl the metrics right away leads to failures, as the node_exporter is still initializing. This commit adds a 30s loop to check the service is ready and listening.
- Needles: N/A
- Failure: https://openqa.suse.de/tests/13216762#step/monitoring_services/121
- Verification run: https://openqa.suse.de/tests/13225013 & https://openqa.suse.de/tests/13225012
> Wait until prometheus node_exporter is ready before testing

- tests/console/sssd_389ds_functional.pm
When using new systemd version (>= 248) under cgroups v2 the default for --cgroupns switches from 'host' to 'private'. 
Since test is passing the host's `/sys/fs/cgroup` as a volume, the container runtime tries to create a private cgroup namespace inside it, as the cgroup path inside the container won't match up with the cgroup namespace and this result in a failure starting containerized systemd.
We could apply many [workarounds](https://github.com/moby/moby/issues/42275#issuecomment-1616442602) , like booting the host system with cgroups in v1 compatibility mode, or tweak Docker daemon parameter passing `--cgroupns=host` .
The suggestion from the community itself is to switch to `podman` which is designed to play better with these new `systemd` features.  …
> Use podman on newer sle; wait for effective container running 

- schedule/functional/stack_tests_python.yaml
- Related ticket:  https://progress.opensuse.org/issues/152629
- Needles: No
> Add yaml schedule for python tests in 15-SP6

- lib/utils.pm
- schedule/functional/mm_ping.yaml
- tests/network/setup_multimachine.pm
- variables.md
https://progress.opensuse.org/issues/138302
VR: https://openqa.opensuse.org/tests/3864203
Schedule: https://github.com/os-autoinst/opensuse-jobgroups/pull/413
> Add basic ping testsuite to be used to verify MM setup

- tests/console/valgrind.pm
- Related ticket: https://progress.opensuse.org/issues/153394
- https://openqa.suse.de/tests/13256946              
- https://openqa.suse.de/tests/13256947              
- https://openqa.suse.de/tests/13256948
> Ensure to use stdout in valgrind and quote matching on assertion 

- tests/containers/podman_integration.pm
Enable upstream integration tests on SLE Micro
- Related ticket: https://progress.opensuse.org/issues/153214
- Verification runs: FAILING because of bugs?
- SLE Micro 5.4: https://openqa.suse.de/tests/13257992
- SLES 15-SP5: https://openqa.suse.de/tests/13247598
> Enable upstream integration tests on SLE Micro

- tests/containers/bci_prepare.pm
- Related ticket: https://progress.opensuse.org/issues/132338
- Verification run: http://kepler.suse.cz/tests/22521
> Apply PEP 668 for Leap 15.4 and Leap 15.5

- tests/ha/hawk_gui.pm
`hawk_gui` was failing due to using an outdated version of Docker. This pr updates the test to use podman instead of docker.
- Related ticket: https://jira.suse.com/browse/TEAM-8899
- Verification run: https://openqa.suse.de/tests/13259130 (updated to latest commit)
**NOTE**: This test runs on the development server, which also changes the image used for `ha_hawk_client` to a recent one. This may not be needed, but it was part of the ticket's AC. Whether we still want to abide by it needs to be examined.
> Switch docker for podman in hawk_gui

- tests/console/mdadm.pm
Ticket: https://progress.opensuse.org/issues/153772
VRs:
* 15-SP4 aarch64: https://openqa.suse.de/tests/13276285
* 15-SP5 x86_64: https://openqa.suse.de/tests/13276243
> mdadm.pm: increase script timeout

- tests/x11/reboot_plasma5.pm
- Related ticket: https://progress.opensuse.org/issues/132191
- Verification run: https://openqa.opensuse.org/tests/3875511#live
> x11/reboot_plasma5.pm: Reload VT number for the graphical session

- lib/opensusebasetest.pm
- Related ticket: https://progress.opensuse.org/issues/153085
- Verification runs:  https://openqa.suse.de/tests/13225070
> Add new y2log errors in ignore list

- tests/containers/podman_netavark.pm
If CNI is default, it does not restore the backend configuration after config file removal.
* [sle15sp6](http://kepler.suse.cz/tests/22578#step/podman_netavark/289)
* [sle15sp5](http://kepler.suse.cz/tests/22582#step/podman_netavark/289)
* [sle15sp4](http://kepler.suse.cz/tests/22577#step/podman_netavark/289)
* [sle15sp3](http://kepler.suse.cz/tests/22573#step/podman_netavark/289)
* [sle-micro 6.0](http://kepler.suse.cz/tests/22574#step/podman_netavark/320)
* [sle-micro 5.4](http://kepler.suse.cz/tests/22581#step/podman_netavark/331)
* [Tumbleweed-JeOS](http://kepler.suse.cz/tests/22575#step/podman_netavark/291)
* [microos](http://kepler.suse.cz/tests/22579#step/podman_netavark/320)
* [container-host-old2microosnext@64bit](http://kepler.suse.cz/tests/22580#step/podman_netavark/375)
> Netavark clean up is broken

- schedule/yast/maintenance/skip_registration.yaml
- Related ticket: https://progress.opensuse.org/issues/154024
SP3: https://openqa.suse.de/tests/13317067 
SP4: https://openqa.suse.de/tests/13316999 
SP5: https://openqa.suse.de/tests/13317064
Relevant MR: https://gitlab.suse.de/qa-maintenance/qam-openqa-yml/-/merge_requests/704
> Add skip_registartion schedule for maintenance

- lib/containers/common.pm
Busybox ping does not support -4 option
> containers: Busybox ping does not support -4 option

- lib/y2_module_guitest.pm
- tests/yast2_gui/yast2_instserver.pm
- Description: 
- Change condition for apply_workaround_poo124652
- https://progress.opensuse.org/issues/153379
- Related MR:
- https://gitlab.suse.de/qa-maintenance/qam-openqa-yml/-/merge_requests/702
- Needles: N/A
- [**15sp5**](https://openqa.suse.de/tests/overview?distri=sle&build=hjluo%2Fos-autoinst-distri-opensuse%23mu_refresh&version=15-SP5)
- [**15sp4**](https://openqa.suse.de/tests/overview?distri=sle&build=hjluo%2Fos-autoinst-distri-opensuse%23mu_refresh&version=15-SP4)
- [**15sp3**](https://openqa.suse.de/tests/overview?distri=sle&build=hjluo%2Fos-autoinst-distri-opensuse%23mu_refresh&version=15-SP3)
- [**15sp2**](https://openqa.suse.de/tests/overview?distri=sle&build=hjluo%2Fos-autoinst-distri-opensuse%23mu_refresh&version=15-SP2)
- …
> Change condition for apply_workaround_poo124652

- lib/x11utils.pm
- Description:
-  Remove soft failure for bsc#1192992
- https://progress.opensuse.org/issues/151849
- Needles: 
- N/A
- [**VR**](https://openqa.suse.de/tests/overview?build=hjluo%2Fos-autoinst-distri-opensuse%23first_boot_workaround&distri=sle&version=15-SP6)
> Remove softfailure for bsc#1192992

- lib/main_common.pm
- schedule/qam/common/mau-bootloader.yaml
- tests/console/perl_bootloader.pm
Related ticket: https://progress.opensuse.org/issues/139091
Verification run: https://openqa.suse.de/tests/overview?build=cedvid%2Fos-autoinst-distri-opensuse%2318399
Bugs: 
- SLE12-SP5 aarch64 https://bugzilla.suse.com/show_bug.cgi?id=1218842
- Tumbleweed https://bugzilla.opensuse.org/show_bug.cgi?id=1218847
Maintenance and functional schedules:
- https://gitlab.suse.de/qa-maintenance/qam-openqa-yml/-/merge_requests/695
- https://gitlab.suse.de/qe-core/qa-sle-functional-userspace/-/merge_requests/205
> Update perl-bootloader test

- tests/publiccloud/img_proof.pm
Fix for failure in https://openqa.suse.de/tests/13329039#step/img_proof/56
> pc: Ignore error if chmod failed

- lib/selinuxtest.pm
> Add fixes for selinuxtest

- tests/console/installation_snapshots.pm
- tests/console/ping.pm
- tests/console/verify_efi_mok.pm
- tests/jeos/grub2_gfxmode.pm
- Related ticket: [combustion test suite failures](https://progress.opensuse.org/issues/154093)
* [jeos-15sp6](http://kepler.suse.cz/tests/22599#)
* [12sp5](http://kepler.suse.cz/tests/22594)
> Combustion fixes jeos

- tests/console/suseconnect_scc.pm
After suseconnect-ng 1.6.0, we can not register the system using SUSEConnect command, we need to use transactional-update instead.
But even for previous versions, the trup command can be used
according to the documentation
SLE Micro 6.0 (ALP based): https://openqa.suse.de/tests/13343238
SLEM 5.5: https://openqa.suse.de/tests/13343237
SLEM 5.4: https://openqa.suse.de/tests/13343236
SLEM 5.3: https://openqa.suse.de/tests/13343235
SLEM 5.2: https://openqa.suse.de/tests/13343234
SLEM 5.1: https://openqa.suse.de/tests/13343191
> Use transactional-update command to register the system

- tests/qam-updinstall/update_install.pm
Add install conflict between ec2, gce and azure packages
- Related ticket: https://progress.opensuse.org/issues/154315
- Verification run: https://openqa.suse.de/tests/13356172
> Add cloud-netconfig install conflict

- tests/security/atsec/setup_atsec_env.pm
Ticket: https://progress.opensuse.org/issues/154330
VRs: https://openqa.suse.de/tests/overview?distri=sle&version=15-SP5&build=20240125-1&groupid=431
> setup_atsec_env: use correct folder name

- lib/main_micro_alp.pm
VR: https://openqa.suse.de/tests/13348466
> Add 'Base' flavor to is_image method

- tests/containers/rootless_podman.pm
Ref: #16450 
- https://bugzilla.suse.com/show_bug.cgi?id=1207673
- https://bugzilla.suse.com/show_bug.cgi?id=1218023
> rootless_podman: add user to systemd-journal

- tests/x11/chrome.pm
- Related ticket: https://progress.opensuse.org/issues/154153
- Verification run: https://openqa.opensuse.org/tests/overview?distri=opensuse&build=jpupava_154153
> chrome: Click don't sign in on the new start window

- lib/qesapdeployment.pm
Collect more logs using az cli, when a qe-sap-deployment fails in Ansible stage for Timeout at reboot. It is Azure only implementation for the moment.
- Related ticket: [TEAM-8893](https://jira.suse.com/browse/TEAM-8893)
- sle-15-SP5-HanaSr-Azure-Byos-x86_64-Build15-SP5_2024-01-26T05:03:08Z-hanasr_azure_test_spn@64bit -> http://openqaworker15.qa.suse.cz/tests/274681 :green_circle:  Ansible does not fails so the new code is not called
- http://openqaworker15.qa.suse.cz/tests/274888 :green_circle: Ansible fails for Reboot timeout and the new code runs and collect the logs, they are visible in Log/Asset page as `deploy_qesap_ansible-boot-diagnostics_vmhana01.txt` and `02`
- sle-15-SP5-Azure-SAP-BYOS-Incidents-x86_64-Build:32208:aaa_base-SAPHanaSR-ScaleUp-PerfOpt@az_Standard_E8s_v3 -> …
> Collect boot-diagnostics when Ansible timeout

- tests/console/python3_setuptools.pm
Improve on existing test, installing also the same package via a local http repository.
Also did some basic refactoring 
- Related ticket: https://progress.opensuse.org/issues/153856
- Needles: no
- 15sp4 aarch64  https://openqa.suse.de/tests/13344452
- 15sp4 s390x    https://openqa.suse.de/tests/13344453
- 15sp4 x86_64   https://openqa.suse.de/tests/13344454
- 15sp5 aarch64  https://openqa.suse.de/tests/13344455
- 15sp5 s390x    https://openqa.suse.de/tests/13344456
- 15sp5 x86_64   https://openqa.suse.de/tests/13344457
- LEAP https://openqa.opensuse.org/tests/3892546              
- TW   https://openqa.opensuse.org/tests/3892547
> Install a pip package via local http server

- data/journal_check/bug_refs.json
- Related ticket: https://progress.opensuse.org/issues/154528
> journal_check: Add/update recent ALP bug references

- schedule/security/alp/container_selinux.yaml
- schedule/security/alp/fde_misc.yaml
- schedule/security/selinux.yaml
VR:
https://openqa.suse.de/tests/13373367#
https://openqa.suse.de/tests/13373368#
> Add journal check to security tests for ALP

- tests/console/perl_bootloader.pm
- Related ticket: https://progress.opensuse.org/issues/154471
Added workaround for Tumbleweed due to failure: https://openqa.opensuse.org/tests/3900512#step/perl_bootloader/43
- Bug: https://bugzilla.opensuse.org/show_bug.cgi?id=1219347
- SLE: https://openqa.suse.de/tests/13392605
- Tumbleweed: https://openqa.opensuse.org/tests/3906469
> Change pbl log file verification

- tests/microos/toolbox.pm
https://dzedro.suse.cz/tests/590
https://dzedro.suse.cz/tests/589
> toolbox: Increase timeout

- lib/registration.pm
- Related ticket: https://openqa.suse.de/tests/13398627
- Verification run: https://dzedro.suse.cz/tests/598
https://openqa.suse.de/tests/13401982
https://openqa.suse.de/tests/13401983
https://openqa.suse.de/tests/13401984
> Press i key to unselect beta modules on Micro

- CONTRIBUTING.md
Created as an improvement as a result of the discussion at: https://github.com/openSUSE/qem-bot/pull/154#pullrequestreview-1853975688
> Update suggestion about dead code

- tests/installation/change_desktop.pm
Fixes issue: https://openqa.suse.de/tests/13394662#step/change_desktop/13
- Verification runs: https://openqa.suse.de/tests/13411818#next_previous
> Add wait_still_screen in change_desktop

- tests/publiccloud/cloud_netconfig.pm
This PR implements a softfail for bsc#1219428.
- Related ticket: https://progress.opensuse.org/issues/154519
12-SP5 GCE softfails now: https://openqa.suse.de/tests/13412164#step/cloud_netconfig/8
15-SP4 is still green: https://openqa.suse.de/tests/13412255
Example representing anything else is still green: https://openqa.suse.de/tests/13412256
> Implement softfail for bsc#1219428

- schedule/security/cc_audit_tests.yaml
Ticket: https://progress.opensuse.org/issues/154819
VRs: https://openqa.suse.de/tests/13412587 , https://openqa.suse.de/tests/13412588
> Fix boot on cc_audit_tests.yaml

- data/lynis/baseline-lynis-audit-system-nocolors-15-SP6-aarch64-gnome
- data/lynis/baseline-lynis-audit-system-nocolors-15-SP6-aarch64-textmode
- data/lynis/baseline-lynis-audit-system-nocolors-15-SP6-s390x-textmode
- data/lynis/baseline-lynis-audit-system-nocolors-15-SP6-x86_64-gnome
- data/lynis/baseline-lynis-audit-system-nocolors-15-SP6-x86_64-textmode
Ticket: https://progress.opensuse.org/issues/152437
VRs:
* https://openqa.suse.de/tests/13449605
* https://openqa.suse.de/tests/13449606
* https://openqa.suse.de/tests/13449610
* https://openqa.suse.de/tests/13450091
* https://openqa.suse.de/tests/13450167
> Add lynis baseline for 15-SP6

- tests/containers/podman_integration.pm
Refactor upstream podman tests and increase timeout
- sle-15-SP4-Server-DVD-Updates-x86_64-Build20240206-1-ricardobranco777_master@64bit -> https://openqa.suse.de/t13454865
- sle-15-SP5-Server-DVD-Updates-x86_64-Build20240206-1-ricardobranco777_master@64bit -> https://openqa.suse.de/t13454868
Related MR: https://gitlab.suse.de/qac/qac-openqa-yaml/-/merge_requests/1499
> containers: Refactor upstream podman tests and increase timeout

- lib/qesapdeployment.pm
Add a setting that the user can configure to select python and pip version to be used on the JumpHost
- Related ticket: TEAM-8981
http://openqaworker15.qa.suse.cz/tests/275537  :green_circle: 
- http://openqaworker15.qa.suse.cz/tests/275538 :green_circle:  it only proof that the version of python is now controllable with a setting, it fails as the Python version requested with the setting is not available in the used pc_tool qcow2
-   https://openqa.suse.de/tests/13464763 :green_circle: 
- http://openqaworker15.qa.suse.cz/tests/275596 :green_circle: 
- http://openqaworker15.qa.suse.cz/tests/275597
- http://openqaworker15.qa.suse.cz/tests/275598
- http://openqaworker15.qa.suse.cz/tests/275599
> Allow to configure py version used by qesap

- tests/containers/privileged_mode.pm
Verification run: [pdostal-server.suse.cz/t5643](https://pdostal-server.suse.cz/t5643)
> Fix docker privileged mode

- tests/console/java.pm
java-11-openjdk is in legacy module for 15sp6.
Install L3 supported java version for each supported sles.
- Related ticket: [java-11 is installed from legacy module, update required java version in sle15 service packs](https://progress.opensuse.org/issues/154477)
* [sle-15-SP3-Server-DVD-Updates-x86_64-Build20240129](http://kepler.suse.cz/tests/22626#step/java/6)
* [sle-15-SP6-JeOS-for-kvm-and-xen-x86_64-Build4.22-jeos-base+sdk+desktop](http://kepler.suse.cz/tests/22614#step/java/12)
* [sle-12-SP3-Server-DVD-Updates-x86_64-Build20240129](http://kepler.suse.cz/tests/22619#step/java/6)
* [sle-15-SP4-Server-DVD-Updates-x86_64-Build20240129](http://kepler.suse.cz/tests/22622#step/java/6)
* [sle-12-SP5-Server-DVD-Updates-x86_64-Build20240129](http://kepler.suse.cz/tests/22625#step/java/6)
* …
> Install java version 21 in sle15sp6

- data/journal_check/bug_refs.json
- lib/bootloader_setup.pm
- lib/version_utils.pm
- tests/jeos/firstrun.pm
VR: https://openqa.opensuse.org/tests/3923808
Ticket: https://progress.opensuse.org/issues/135731
> Add support for slowroll to bootloader_uefi

- data/journal_check/bug_refs.json
https://bugzilla.suse.com/show_bug.cgi?id=1217872 is closed
> Remove soft failure for bsc#1217872

- tests/containers/secret.pm
- tests/containers/volumes.pm
Add missing factory calls to volumes and secret modules.
- Failing test: https://openqa.suse.de/tests/13505861#step/volumes_podman/11
- Verification run: https://openqa.suse.de/tests/13510432
> Missing factory

- tests/update/updates_packagekit_gpk.pm
- Related ticket: https://progress.opensuse.org/issues/117460
https://openqa.suse.de/tests/overview?build=jpupava_117460 osd
https://openqa.opensuse.org/tests/overview?distri=opensuse&build=jpupava_pk_gpk o3
> updates_packagekit_gpk: Retry on update failure

- tests/fips/openjdk/prepare_env.pm
Ticket: https://progress.opensuse.org/issues/155455
VRs: [vr1](https://openqa.suse.de/tests/overview?distri=sle&version=15-SP4&build=20240213-1&groupid=431) and [vr2](https://openqa.suse.de/tests/overview?distri=sle&version=15-SP5&build=20240213-1&groupid=431)
> Create dir only if it not already there

- .github/workflows/openqa.yml
- data/journal_check/bug_refs.json
VR: https://openqa.suse.de/tests/13519950
> Whitelist bug 1219218 - pam_systemd Failed to release session

- tests/sles4sap/qesapdeployment/deploy.pm
Change deploy test module only for the qesap regression test (for the moment).
Run terraform for a second time in case of a terraform failure with a specific error message.
- Related ticket: https://jira.suse.com/browse/TEAM-9027
- http://openqaworker15.qa.suse.cz/tests/275468 :green_circle: Terraform PASS at the first try
- http://openqaworker15.qa.suse.cz/tests/275469 :green_circle: Terraform PASS at the first try
- http://openqaworker15.qa.suse.cz/tests/275470 :green_circle: Terraform PASS at the first try
- http://openqaworker15.qa.suse.cz/tests/275471 :green_circle: Terraform PASS at the first try
- http://openqaworker15.qa.suse.cz/tests/275472 :green_circle: Terraform PASS at the first try
- http://openqaworker15.qa.suse.cz/tests/275473 job fails in Ansible for reboot timeout in …
> Terraform retry in case of CSP internal error

- tests/jeos/glibc_locale.pm
`locale` setup can be tested by simply executing `su` rather than using
expensive console switching in openQA
- Related ticket: https://progress.opensuse.org/issues/155476
* https://openqa.suse.de/tests/13519561#step/glibc_locale/1
* http://kepler.suse.cz/tests/22638#
> Replace console switching by user switching

- schedule/security/fips_crypt_tool.yaml
- Related ticket: https://progress.opensuse.org/issues/155440
aarch64: https://openqa.suse.de/tests/13534442
x86_64: https://openqa.suse.de/tests/13534441
> Only execute suseconnect where live patching is available

- tests/microos/patterns.pm
https://bugzilla.suse.com/show_bug.cgi?id=1219200
- Verification run: https://openqa.suse.de/tests/13539493#step/patterns/1 
**Please ignore the failed test module, it is known issue**
> Don't install pattern 'alp_elemental_client' on slem6.0

- data/journal_check/bug_refs.json
- tests/console/journal_check.pm
- Description: Ignore [bsc#1195060](https://bugzilla.suse.com/show_bug.cgi?id=1195060) from `data/journal_check/bug_refs.json`
- Related ticket: [poo#153619](https://progress.opensuse.org/issues/153619)
- Verification run: [overview](https://openqa.suse.de/tests/overview?build=issues-153619)
> Ignore bsc#1195060 from data/journal_check/bug_refs.json

- tests/containers/compose.pm
Failing test: https://openqa.opensuse.org/tests/3948365#step/docker_compose/1
> containers: Skip trup_call if packages are installed

- data/autoyast_qam/12-common_base_installation.xml.ep
Update autoyast profile for 12-sp5 uefi.
- Related ticket: https://progress.opensuse.org/issues/154705
- mru-install-minimal-with-addons@uefi: https://openqa.suse.de/tests/13543021
- mru-install-minimal-with-addons@aarch64-virtio: https://openqa.suse.de/tests/13545686
> Update profile for uefi machine

- lib/containers/container_images.pm
Again NVidia repo is causing troubles when container repos are being refreshed.
- Related ticket: https://progress.opensuse.org/issues/155665
- Verification run: http://kepler.suse.cz/tests/22662#step/image_docker/299
> Auto accept keys in docker-zypper calls

- lib/containers/common.pm
Remove soft-failures:
- https://bugzilla.suse.com/show_bug.cgi?id=1189893 (bug seems fixed and there's no test soft-failing on it).
---
- Related ticket: https://progress.opensuse.org/issues/155452
- Verification run: https://openqa.opensuse.org/tests/3949270 (failing for other reason).
> containers: Remove soft-fail for bsc#1189893

- lib/Installation/ModuleRegistration/ModuleRegistrationPage.pm
- schedule/yam/test_cases/slem-extensions_and_modules.yaml
- schedule/yast/sle/flows/default_slem_s390x.yaml
- tests/yam/ntp_configuration.pm
- Related ticket: https://progress.opensuse.org/issues/155077
MR to remove test from Core Job group: https://gitlab.suse.de/qac/qac-openqa-yaml/-/merge_requests/1504
MR to add test to the other job group: https://gitlab.suse.de/qe-yam/openqa-job-groups/-/merge_requests/79
- Verification run: https://openqa.suse.de/tests/overview?distri=sle-micro&build=sofiasyria%2Fos-autoinst-distri-opensuse%23slem_yui
> Add libyui schedule for slem-extensions_and_modules

- tests/virt_autotest/libvirt_extend_storage_lvm.pm
* **Introduce** new subroutine get_hard_disk_size to verify hard disk size is equal to or greater than 20G before creating lvm with it. 
* **This** can help ensure test run proceed with suitable hard disk and increase test run stability, otherwise test fail may fail like [this](https://openqa.suse.de/tests/13348898#step/libvirt_extend_storage_lvm/62).
* **If** there is no suitable disk to be used, fail test run immediately and give explicit error message. (At the moment, all SUTs have at least on spare disk size of which is more than 20G, so test run will not fail. ```die``` only serves the purpose of raising alert in the future if certain machine does not have qualified disk, so it can be excluded from taking such test run by modifying worker and job yaml files). …
> Verify hard disk size before creating lvm

- schedule/yast/sle/guided_btrfs/guided_btrfs_ipmi.yaml
- Related ticket: https://progress.opensuse.org/issues/154687
- Verification run: https://openqa.suse.de/tests/13580727#next_previous
> Accept default disk selection for guided_btrfs@ipmi

- tests/xfstests/partition.pm
xfstests: install overlayfs-tools unionmount-testsuite for overlayfs
- Related ticket: https://progress.opensuse.org/issues/154078
- Needles: N/A
http://10.67.133.133/tests/456 (install on sle)
http://10.67.133.133/tests/460 (overlay test on xfs)
http://10.67.133.133/tests/458 (overlay test on btrfs)
http://10.67.133.133/tests/459 (btrfs test)
http://10.67.133.133/tests/477 (overlay test on ALP)
> xfstests: install overlayfs-tools unionmount-testsuite for overlayfs

- data/autoyast_hanaperf/12sp5.xml.ep
- schedule/hanaperf/hana_ipxe_autoyast.yaml
Support ppc64le machine(legolas) installation with new autoyast xml and ipxe yaml schedule
- Related ticket: None
- Verification run: http://openqa.qa2.suse.asia/tests/68631
> Support ppc64le machine installation

- lib/containers/common.pm
- tests/containers/buildx.pm
- tests/containers/compose.pm
- tests/containers/ecs_anywhere.pm
- tests/containers/podman_integration.pm
- tests/containers/podman_netavark.pm
- tests/containers/rootless_docker.pm
Refactor install_packages
- Related ticket: https://progress.opensuse.org/issues/155470
- opensuse-Tumbleweed-DVD-x86_64-Build20240225-containers_host_podman_testsuite@64bit -> https://openqa.opensuse.org/t3963560
- opensuse-Tumbleweed-DVD-x86_64-Build20240225-containers_host_podman@64bit -> https://openqa.opensuse.org/t3963561
- opensuse-Tumbleweed-DVD-x86_64-Build20240225-containers_host_docker@64bit -> https://openqa.opensuse.org/t3963590
- microos-Tumbleweed-DVD-x86_64-Build20240225-container-host@64bit -> https://openqa.opensuse.org/t3963563
> containers: Refactor install_packages

- tests/containers/rootless_podman.pm
- Related ticket: https://progress.opensuse.org/issues/155470, Related PR: https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/18570
- Verification run: [sle-15-SP2-JeOS](https://openqa.suse.de/tests/13603164), [sle-micro-5.5-Default-](https://openqa.suse.de/tests/13603165), [ sle-micro-6.0-Base](https://openqa.suse.de/tests/13603166), [sle-15-SP5-](https://openqa.suse.de/tests/13603167), [microos-Tumbleweed-DVD-x86_64-](https://openqa.opensuse.org/tests/3963638)
> Small rootless_podman_refactoring

- data/journal_check/bug_refs.json
http://openqa.suse.de/tests/13605598
> Add bsc#1216196 as soft failures for SLE Micro 6.0

- data/security/autoyast/create_hdd_textmode_cc_aarch64.xml
- data/security/autoyast/create_hdd_textmode_cc_s390x.xml
- schedule/security/create_hdd_autoyast/autoyast_create_hdd_textmode_cc_qesec.yaml
- tests/installation/bootloader_zkvm.pm
Ticket: https://progress.opensuse.org/issues/155257
VRs: https://openqa.suse.de/tests/overview?distri=sle&version=15-SP6&build=58.1&groupid=431 + https://openqa.suse.de/tests/13619177
> Add profiles for s390x and aarch64

- lib/publiccloud/instance.pm
PC boottime_measures: hours unit added in time analysis and overall time > 1h reported in details.
In some PC tests `systemd-analyze` returned time values of hours, unexpected in previous `systemd_time_to_second` code version.
- Related ticket: https://progress.opensuse.org/issues/155635 
- Needles: N/A
- Verification run: see PR body
> PC boottime_measures: hours unit in time analysis

- tests/console/perl_bootloader.pm
- Related ticket: https://progress.opensuse.org/issues/154471
Revised 'pbl --log' test and removed the soft failure for tumbleweed following this bug ticket: https://bugzilla.suse.com/show_bug.cgi?id=1219347
- SLE https://openqa.suse.de/tests/overview?build=os-autoinst%2Fos-autoinst-distri-opensuse%2318718
- Tumbleweed https://openqa.opensuse.org/tests/overview/?build=os-autoinst%2Fos-autoinst-distri-opensuse%2318718
> Update perl-bootloader log test

- tests/boot/cloud_init.pm
VR: https://openqa.suse.de/tests/13620400
> Upload cloud-init logs

- lib/main_publiccloud.pm
- tests/publiccloud/check_registercloudguest.pm
- tests/publiccloud/transfer_repos.pm
- Related ticket: https://progress.opensuse.org/issues/155776, https://progress.opensuse.org/issues/153976
- Verification run: https://pdostal-server.suse.cz/tests/5783, https://pdostal-server.suse.cz/tests/5784
> Run check_registercloudguest in registration test

- tests/sles4sap/publiccloud/qesap_terraform.pm
Enable terraform retry in qesap_terraform.
- Related ticket: https://jira.suse.com/browse/TEAM-9027
- Verification run: https://openqa.suse.de/tests/13626172 (sporadic failure did not happen)
> Use terraform retry for internal errors

- data/publiccloud/terraform/azure.tf
- data/publiccloud/terraform/azure_nfstest.tf
- data/publiccloud/terraform/ec2.tf
- data/publiccloud/terraform/gce.tf
- lib/publiccloud/azure.pm
- lib/publiccloud/provider.pm
- tests/publiccloud/aws_cli.pm
This reverts commit fb3cc81d0cd07dd17f72414c0246f4d9ff4e9f5c.
> Revert "Public Cloud: Use ed25519 in GCP and AWS"

- data/qam/mdadm.sh
- Related ticket: https://progress.opensuse.org/issues/156037
https://openqa.suse.de/tests/overview?build=jpupava_mdadm&distri=sle osd
https://openqa.opensuse.org/tests/3969378 TW
> Fix availbale disk space check and md name

- data/sles4sap/qe_sap_deployment/qesap_azure.yaml
- data/sles4sap/qe_sap_deployment/qesap_azure_fencing_msi.yaml
- data/sles4sap/qe_sap_deployment/qesap_azure_fencing_spn.yaml
- data/sles4sap/qe_sap_deployment/qesap_azure_roles.yaml
- data/sles4sap/qe_sap_deployment/qesap_azure_sapconf.yaml
- data/sles4sap/qe_sap_deployment/qesap_azure_sapconf_no_reg.yaml
- data/sles4sap/qe_sap_deployment/qesap_azure_uri.yaml
- lib/sles4sap_publiccloud.pm
Small change to schedule a new playbook during ansible deployment. Adds a new post playbook to all affected schedules.
- Related ticket: https://jira.suse.com/browse/TEAM-9093
--with SAPHanaSR 0.162.3: https://openqa.suse.de/tests/13618826
--with SAPHanaSR 0.162.2: http://openqaworker15.qa.suse.cz/tests/276843
> Add playbook for sap hana tests

- data/autoyast_sle15/hpc/create_hdd_textmode_aarch64.xml.ep
- data/autoyast_sle15/hpc/create_hdd_textmode_x86_64.xml.ep
- Related ticket: https://progress.opensuse.org/issues/156328
sp6 intel: https://openqa.suse.de/tests/13669414
sp6 arm: https://openqa.suse.de/tests/13669443
sp5 intel: https://openqa.suse.de/tests/13669421
sp5 arm: https://openqa.suse.de/tests/13669426
> HPC: Adapt ay profiles to accomodate product change

- tests/jeos/firstrun.pm
- Verification run: https://openqa.suse.de/tests/13705724
> Allow ssh root access with password

- tests/xfstests/run.pm
Fixed skip status test detacted as failed issue when enable high-speed mode in xfstests.
- SLES http://10.67.133.133/tests/484
- SLE Micro https://openqa.suse.de/tests/13715495
- public cloud  https://openqa.suse.de/tests/13715581
> xfstests: Fix skip test detacted fail issue

- lib/oscap_tests.pm
Fixes for corner cases handling of versioned expected results and exclusions
- Related ticket: https://progress.opensuse.org/issues/155884
https://openqa.suse.de/tests/13649068#
https://openqa.suse.de/tests/13648404#
> Versioned expected results error handling

- lib/publiccloud/instance.pm
- lib/publiccloud/provider.pm
- lib/publiccloud/utils.pm
Follow up for
https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/18797
- ticket: https://progress.opensuse.org/issues/156634
- Verification run: http://kepler.suse.cz/tests/22700#
> Skip measurement routine in openstack

- tests/hpc/ww4.pm
Fix poo#156511: Latest warewulf upgrade changed location of
defaults.conf from /etc/warewulf to /usr/share/warewulf/. Container
and overlay have to be build explicitly from now.
- Related ticket: https://progress.opensuse.org/issues/156511
- Needles: 
15-SP5: https://openqa.suse.de/tests/overview?build=czerw%2Fos-autoinst-distri-opensuse%2318786&version=15-SP5&distri=sle
15-SP6: https://openqa.suse.de/tests/overview?version=15-SP6&build=czerw%2Fos-autoinst-distri-opensuse%2318786&distri=sle
> hpc: Update warewulf test to support new behavior

- data/autoyast_qam/15-common_base_installation.xml.ep
- lib/autoyast.pm
- Related ticket: https://progress.opensuse.org/issues/156199
https://dzedro.suse.cz/tests/752 ay installation
https://dzedro.suse.cz/tests/753 fillowing extratests
> Update sle15 autoyast profile for TERADATA flavor

- tests/publiccloud/check_registercloudguest.pm
VR: https://openqa.suse.de/tests/13716903
> Add support for latest runs

- tests/x11/oomath.pm
https://progress.opensuse.org/issues/156628
[staging](https://openqa.opensuse.org/tests/3993063)
[tw and leap](https://openqa.opensuse.org/tests/overview?build=rfan0307&distri=opensuse)
[sle](http://openqa.suse.de/tests/overview?&build=rfan0307&distri=sle)
> Make sure focus is in text window before typing

- data/journal_check/bug_refs.json
VR: https://openqa.suse.de/tests/13734495#step/journal_check/21
> Soft fail bsc#1220361 - selinux checkpoint_restore

- lib/containers/utils.pm
- tests/containers/container_engine.pm
The basic_container_tests subroutine has historically grown and needed a tidy. In this commit I
* reorganized the blocks into logical tests
* Reduced the scope to only run tests on one container
* Removed duplicate checks within the routine
* Simplified several checks for reduced code
- Related ticket: https://progress.opensuse.org/issues/155404
* [Tumbleweed podman](https://duck-norris.qe.suse.de/tests/14407)
* [Tumbleweed docker](https://duck-norris.qe.suse.de/tests/14408)
* [15-SP5 podman](https://duck-norris.qe.suse.de/tests/14409)
* [15-SP5 docker](https://duck-norris.qe.suse.de/tests/14410)
* [15-SP4 podman](https://duck-norris.qe.suse.de/tests/14411)
* [15-SP4 docker](https://duck-norris.qe.suse.de/tests/14412)
* [15-SP3 podman](https://duck-norris.qe.suse.de/tests/14413)
* [15-SP3 …
> Refactor basic_container_tests

- data/openvpn/ca_client.conf
- data/openvpn/ca_server.conf
- data/openvpn/static_client.conf
- data/openvpn/static_server.conf
- schedule/security/openvpn.yaml
- tests/network/openvpn_server.pm
Ticket: https://progress.opensuse.org/issues/155920
VR: https://openqa.suse.de/tests/overview?distri=sle&version=15-SP6&build=62.1&groupid=431
> Fix openvpn test

- tests/console/yast2_bootloader.pm
https://progress.opensuse.org/issues/156877
- Verification run: [leap 15.6](https://openqa.opensuse.org/tests/3996602#step/yast2_bootloader/5)
> Propose new configuration from scratch if unknown udev devices

- lib/sles4sap_publiccloud.pm
Before execution of the SSH connection the other side is now cheked if  SSH is available, which prevent also "connection refused" cases at connection to the not fully started node, which cannot be catch by simple longer timeout
- lib is polished of some discrepancies in usage of variables
- some typos corrected
Related ticket: https://jira.suse.com/browse/TEAM-9058
Verification run: https://openqa.suse.de/tests/13736598#
> SSH is now checked before connected

- lib/ipsecbase.pm
- schedule/ipsec/multi_machine_ipsec_3hosts.yaml
- schedule/ipsec/supportserver.yaml
- tests/ipsec/barrier_init.pm
- tests/ipsec/ipsec3hosts.pm
IPsec xfrm MTU discovery related testing (3 hosts) #920
- Related ticket: https://github.com/linux-test-project/ltp/issues/920
- Needles: na
- Verification run(tw and sle): 
http://10.168.192.64/tests/overview?result=passed&distri=opensuse&version=Tumbleweed&build=20240302&groupid=3
http://10.168.192.64/tests/overview?result=passed&distri=sle&version=15-SP6&build=60.1&groupid=3
> IPsec xfrm MTU discovery related testing (3 hosts)

- lib/utils.pm
- lib/version_utils.pm
- lib/x11utils.pm
- Verification run: http://10.168.4.192/tests/1459
> lib/version_utils.pm: Argon and TW Staging:L have Plasma 6 now

- lib/version_utils.pm
Issue: https://openqa.opensuse.org/tests/4003087#step/updates_packagekit_gpk/5
VR: https://openqa.opensuse.org/tests/4003135
> lib/version_utils.pm: Make is_plasma6 check DESKTOP as well

- lib/virt_autotest/virtual_network_utils.pm
* **Network** interface attached to public facing network requires more time to get ip address assigned, for example, virtual machine employs host bridge network may fail to get ip address assigned very quickly. Please refer to [this failure](https://openqa.suse.de/tests/13084938#step/libvirt_host_bridge_virtual_network/93).
* **This** might be related to the huge number of devices in the network and subsequent conflicts detecting when a new device joins. It requires additional time to finish. 
* **Using** timeout directly in script_output does not really waits for the period because script_output may return immediately. 
* **Instead** using while loop, in which getting ip address with script_output, is the better way to handle the problem.
* [15sp6 on 15sp6 …
> Retry getting ip address of attached interface

- data/pam_test/pam_deprecated.sh
https://progress.opensuse.org/issues/157009
- [Verification run](http://openqa.suse.de/tests/overview?version=15-SP5&distri=sle&build=rfan0312_pam_1g)
> Add some delay for pam test script to handle race condition

- tests/jeos/firstrun.pm
Ticket: https://progress.opensuse.org/issues/156934
VR: https://openqa.suse.de/tests/13765488#live
> Enable root login for RPi images

- data/pam_test/pam_deprecated.sh
The issue can be seen sporadically even with the change, I will create another PR to fix it.
Reverts os-autoinst/os-autoinst-distri-opensuse#18854
> Revert "Add some delay for pam test script to handle race condition"

- data/pam_test/pam_deprecated.sh
https://progress.opensuse.org/issues/157009
VR:  https://openqa.suse.de/tests/overview?version=15-SP5&distri=sle&build=rfan0313_pamfix
> Add more delay for pam test script to handle race condition

- lib/qesapdeployment.pm
- sle-15-SP5-Qesap-Azure-Byos-x86_64-BuildLATEST_AZURE_SLE15_5_BYOS-qesap_azure_ibsmirror_peering_test@64bit ->  http://openqaworker15.qa.suse.cz/tests/278370 :green_circle: 
- sle-15-SP5-Qesap-Azure-Byos-x86_64-BuildLATEST_AZURE_SLE15_5_BYOS-qesap_azure_ansible_roles_test@64bit -> http://openqaworker15.qa.suse.cz/tests/278371 :green_circle: 
- sle-15-SP5-Qesap-Azure-Byos-x86_64-BuildLATEST_AZURE_SLE15_5_BYOS-qesap_azure_sapconf_test@64bit -> http://openqaworker15.qa.suse.cz/tests/278372  Failure is for Ansible Timeout at reboot  http://openqaworker15.qa.suse.cz/tests/278433
- sle-15-SP6-Qesap-Azure-Byos-Ibs-x86_64-BuildLATEST_AZURE_SLE15_6_BYOS_IBS-qesap_azure_uri@az_Standard_E8s_v3 -> http://openqaworker15.qa.suse.cz/tests/278373 :green_circle: 
- …
> Split long lines in qesapdeploy lib

- lib/version_utils.pm
- Verification run: https://openqa.opensuse.org/tests/4009829#live
> lib/version_utils.pm: Tumbleweed has Plasma 6 now

- tests/containers/host_configuration.pm
-ticket: https://progress.opensuse.org/issues/157111 Basically revert a0472239be0b198630dab4e9c1ce588415616fed
> Drop RHEL 7 code

- tests/console/check_system_info.pm
Quick PR to update product checking for cross product migration.
- Needles: n/a
https://openqa.suse.de/tests/13778223#step/check_system_info/16 (to confirm this issue need to be fixed)
https://openqa.suse.de/tests/13778225#step/check_system_info/14 (SLES migration)
https://openqa.suse.de/tests/13778472#step/check_system_info/29 (HPC to SLES migration)
> Quick PR to update product checking for cross product migration

- schedule/security/create_fips_hdd.yaml
- schedule/security/crypt_krb5client.yaml
- schedule/security/crypt_krb5kdc.yaml
- schedule/security/crypt_krb5server.yaml
- schedule/security/fips_xrdp.yaml
- tests/security/fips_xrdp_server.pm
- tests/security/krb5/krb5_crypt_prepare.pm
- tests/security/verify_fips_enabled.pm
- tests/x11/remote_desktop/windows_client_remotelogin.pm
- Tickets: https://progress.opensuse.org/issues/156844 and https://progress.opensuse.org/issues/156916
- VRs: [15-sp4](https://openqa.suse.de/tests/overview?distri=sle&version=15-SP4&build=20240313-1&groupid=431), [15-sp5](https://openqa.suse.de/tests/overview?distri=sle&version=15-SP5&build=20240313-1&groupid=431), [15-sp6](https://openqa.suse.de/tests/overview?distri=sle&version=15-SP6&build=62.1&groupid=431)
> Fix xrdp and krb5 FIPS tests.

- tests/kernel/run_ltp.pm
Add support for running tcpdump during each LTP test to capture all sent and received packets for debugging.
- Needles: N/A
- without tcpdump: https://openqa.suse.de/tests/13770925
- with tcpdump and failures: https://openqa.suse.de/tests/13770926
- with tcpdump and timeouts: https://openqa.suse.de/tests/13770927
> run_ltp: Capture network traffic during test run

- schedule/security/fips_crypt_core.yaml
Ticket: https://progress.opensuse.org/issues/157291
> Remove wrongly put test

- data/python/pycairo_sample.svg
https://progress.opensuse.org/issues/154486
[sle](http://openqa.suse.de/tests/13790046#step/python_pycairo/1)
[leap](https://openqa.opensuse.org/tests/4014382#step/python_pycairo/1)
> Update 'pycairo_sample.svg' file

- tests/console/validate_lvm_raid1.pm
- Related [PR#18827](https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/18827) already merged
> Quick PR: fix unused import statement

- lib/main_common.pm
- tests/installation/install_service.pm
- tests/installation/post_zdup.pm
- tests/installation/setup_zdup.pm
- variables.md
See individual commits for details.
KDE (product issue found): https://openqa.opensuse.org/tests/4015450
KDE (no product issue during upgrade): https://openqa.opensuse.org/tests/4015497
GNOME (no product issue during upgrade): https://openqa.opensuse.org/tests/4015498
> Fix ZDUP_IN_X

- data/python/pycairo_sample.svg
Reverts os-autoinst/os-autoinst-distri-opensuse#18890
> Revert "Update 'pycairo_sample.svg' file"

- tests/ha/filesystem.pm
typing error(type_string) happened when running `assert_script_run` with a long command string like this:
https://openqa.suse.de/tests/13401947#step/filesystem#1/17
https://openqa.suse.de/tests/13401956#step/filesystem#1/18
this fix uses bash script to replace typing command on terminal, this will avoid or minimize the use of `type_string` and make sure the test case stable.
- Related ticket: https://jira.suse.com/browse/TEAM-9024
- Needles: N/A
ppc64le:
https://openqa.suse.de/tests/13810316#step/filesystem#1/21
https://openqa.suse.de/tests/13823428#step/filesystem#1/21
aarch64:
https://openqa.suse.de/tests/13823163#step/filesystem#1/21
x86_64:
https://openqa.suse.de/tests/13823638#step/filesystem#1/19
> Using bash script to replace commandline for avoiding type_string error

- tests/hpc/mpi_slave.pm
test runs:
https://openqa.suse.de/tests/13834356
https://openqa.suse.de/tests/13834354
https://openqa.suse.de/tests/13834353
https://openqa.suse.de/tests/13834355
> HPC: Make sure entire testapi is included

- data/libgit2/pygit2_test.py
- lib/python_version_utils.pm
- schedule/functional/extra_tests_textmode.yaml
- tests/console/libgit2.pm
https://progress.opensuse.org/issues/156418
[TW](https://openqa.opensuse.org/tests/4032466)
[SLE15SP6](https://openqa.suse.de/tests/13845353)
[LEAP15.6](https://openqa.opensuse.org/tests/4032467)
> Create test module libgit2

- tests/yast2_cmd/yast_dns_server.pm
##
* https://progress.opensuse.org/issues/155812
* https://progress.opensuse.org/issues/151906
- Needles: 
* N/A
* [**VR**](https://openqa.suse.de/tests/overview?version=15-SP5&build=hjluo%2Fos-autoinst-distri-opensuse%23revisit_bsc_1151130&distri=sle)
##
> Revisit soft-failures bsc#1151130 and bsc#1151135

- lib/publiccloud/utils.pm
SLEM PC update: add SCC registering via transactional update
- Related ticket: https://progress.opensuse.org/issues/137168
- Needles: N/A
- Verification run: PASSED
- sle-micro-5.4-GCE-BYOS-Updates-x86_64-Build20240325-1-slem_basic@64bit 
https://openqa.suse.de/tests/13871694
- sle-micro-5.3-GCE-BYOS-Updates-x86_64-Build20240325-1-slem_basic@64bit    
https://openqa.suse.de/tests/13871676
> SLEM PC Update with transactional register

- lib/windowsbasetest.pm
From some point to now, our password is periodically expired, even though we set the flag for it to never happen. Here's a workaround in case it expires again
- Related ticket: https://progress.opensuse.org/issues/153105
- Needles: https://gitlab.suse.de/openqa/os-autoinst-needles-sles/-/blob/74ebbbfeb4293f582cacc3ba6728f2838e76fe3e/win-password-expired-20240325.png
- https://openqa.suse.de/tests/13860100
- https://openqa.suse.de/tests/13860101
- https://openqa.suse.de/tests/13860114
> Reset password in Windows after it expires

- data/wsl/Autounattend_BIOS.xml
- data/wsl/Autounattend_UEFI.xml
- data/wsl/create_unattend_iso.sh
Modified the .xml files to add a non-expiring password command. Added the bash script used for creating the unattend ISOs
> Modify files for Windows unattended install

- lib/db_utils.pm
- tests/jeos/image_info.pm
When there is a connection issue with QA DBs we dont want the test to die.
- Verification run: https://openqa.suse.de/tests/13875620
> Dont die on time when reaching QA DBs

- lib/oscap_tests.pm
Requested by hardening team to collect some more oval evaluations logs
- Related ticket: https://progress.opensuse.org/issues/158068
- Verification run: https://openqa.suse.de/tests/13875153#
> Improve scap tests logging

- lib/db_utils.pm
follow up for 49fda881992177f61e459d0f05959897b43a4756
> Fix broken record_info

- lib/main_micro_alp.pm
Related ticket : https://progress.opensuse.org/issues/157924
VR: https://openqa.suse.de/tests/13891095#live
> Add ability to upload image

- tests/console/libgit2.pm
https://progress.opensuse.org/issues/158128
- Verification run: [vr](https://openqa.opensuse.org/tests/4045167#)
> Fix libgit2 issue

- tests/console/ansible.pm
VR https://openqa.suse.de/tests/13899831
> Fix Ansible test wich got broken by ALP removal

- tests/publiccloud/img_proof.pm
This PR adds a soft-failure for https://bugzilla.suse.com/show_bug.cgi?id=1220269 
- Related ticket: https://progress.opensuse.org/issues/158062
- Verification run: https://openqa.suse.de/tests/13902794
NOTE:
- We can't force the "failed" to "softfailed" due to https://github.com/os-autoinst/openQA/blob/master/lib/OpenQA/Parser/Format/IPA.pm#L55
> pc: Add soft-failure for bsc#1220269

- tests/virt_autotest/libvirt_extend_storage_lvm.pm
* **Volume** group created on spare disk might not be removed in fresh host installation, which leads to failing to create a new one in test module [libvirt_extend_storage_lvm.pm](http://libvirt_extend_storage_lvm.pm/), for example, [this one](https://openqa.suse.de/tests/13876002#step/libvirt_extend_storage_lvm/84).
* **Create** a new function remove_volume_group to remove it forcibly before creating newly.
* [15sp6 on 15sp6 kvm](https://openqa.suse.de/tests/13897221)
* [15sp6 on 12sp5 kvm](https://openqa.suse.de/tests/13896922)
* [15sp5 on 15sp6 xen](https://openqa.suse.de/tests/13896923)
* [uefi 15sp6 on 15sp5 xen](https://openqa.suse.de/tests/13896924)
> Remove volume group before creating it

- data/generalhw_scripts/power_on_off_shelly.sh
Ticket: https://progress.opensuse.org/issues/1584042
> Be more verbose in power_on_off_shelly.sh

- data/generalhw_scripts/flash_sd_rootless.sh
Ticket: https://progress.opensuse.org/issues/158404
> Follow symlinks when showing hdd size in flash_sd_rootless.sh

- tests/x11/toolkits/prepare.pm
Created https://openqa.opensuse.org/tests/4059353
> Fix missing gtk2-devel introduced by #19007

- schedule/microos/bonding.yaml
VR: https://openqa.opensuse.org/tests/4058639
> Recover Microos bonding schedule

- tests/console/sudo.pm
Azure 15-SP2 images are expected to get the '#Defaults targetpw' change in sudoers eventually. In the meantime, we need to check if this change is present there and mark it as softfailure for bsc#1207076.
- Related ticket: https://progress.opensuse.org/issues/158440
- Related failure: https://openqa.suse.de/tests/13937699
- Verification run: [15-SP5 Azure-Basic](https://openqa.suse.de/tests/13942281) | [15-SP3 Azure-BYOS](https://openqa.suse.de/tests/13942280) | [15-SP2 Azure-BYOS](https://openqa.suse.de/tests/13942279#step/sudo/8)
> Add switch for determining Defaults targetpw

- lib/sles4sap_publiccloud.pm
- Related ticket: TEAM-9215
- http://openqaworker15.qa.suse.cz/tests/279854 :tomato:   failure in a different code part, not changed in this PR 
- http://openqaworker15.qa.suse.cz/tests/279861 :green_apple:
> Set timeout to 900 for Crash step in HanaSR

- lib/sles4sap/azure_cli.pm
- t/21_sles4sap_azure_cli.t
- tests/sles4sap/cloud_netconfig/deploy.pm
Related ticket: TEAM-8721
- sle-15-SP5-SapCloud-Azure-Byos-x86_64-BuildLATEST_AZURE_SLE15_5_BYOS-cloud_netconfig_azure_test@64bit -> http://openqaworker15.qa.suse.cz/tests/279883 :green_apple: 
- sle-15-SP5-SapCloud-Azure-Payg-x86_64-BuildLATEST_AZURE_SLE15_5_PAYG-cloud_netconfig_azure_test@64bit -> http://openqaworker15.qa.suse.cz/tests/279882  :green_apple:
> Add lib for az cli for sles4sap

- lib/version_utils.pm
- schedule/sle-micro/migration_with_scc_proxy.yaml
- tests/microos/rollback.pm
- tests/migration/online_migration/zypper_migration.pm
- Related ticket: https://progress.opensuse.org/issues/157096
- Verification runs: https://openqa.suse.de/tests/overview?build=sofiasyria%2Fos-autoinst-distri-opensuse%23slem_rollback&version=6.0&distri=sle-micro
- https://openqa.suse.de/tests/13846111
> Add rollback after slem migration

- tests/publiccloud/img_proof.pm
DO NOT merge until https://github.com/SUSE-Enceladus/img-proof/pull/379 is merged and new version of img-proof is released.
> pc: Do not create swap for hardened tests as img-proof now does it

- schedule/functional/extra_tests_textmode.yaml
- tests/console/libgit2.pm
https://progress.opensuse.org/issues/156418
[all arches](https://openqa.suse.de/tests/overview?distri=sle&version=15-SP6&build=rfan0407)
> Add libgit2 test on ppc64le/s390x

- data/virtualization/autoyast/guest_15.xml.ep
- data/virtualization/autoyast/host_12.xml.ep
- data/virtualization/autoyast/host_15.xml.ep
- lib/virt_autotest/common.pm
The VR runs use RC1 and have some issues, I am looking into them but I think it is best to resolved them in new tickets/PRs.
- Related ticket: https://progress.opensuse.org/issues/153916
- Needles: https://gitlab.suse.de/openqa/os-autoinst-needles-sles/-/merge_requests/1661
[12-SP5-KVM](http://openqa.qam.suse.cz/tests/70819#dependencies)
[12-SP5-XEN](http://openqa.qam.suse.cz/tests/70902#dependencies)
[15-SP6-KVM](http://openqa.qam.suse.cz/tests/70747#dependencies) issue: [poo#157507](https://progress.opensuse.org/issues/157507)
[15-SP6-XEN](http://openqa.qam.suse.cz/tests/70627#dependencies)
[HyperV](https://openqa.suse.de/tests/13959830)
[VMware](https://openqa.suse.de/tests/13959831)
> Enable sle15sp6 virt MU

- lib/repo_tools.pm
Does also fix issue with Server-DVD-Updates-TERADATA flavor
- Related ticket: https://openqa.suse.de/tests/13973221#step/zypper_info/11
- Verification run: https://dzedro.suse.cz/tests/881
> Use generic main_common::is_updates_tests

- tests/security/cc/cc_audit_test_setup.pm
Ticket: https://progress.opensuse.org/issues/158691
VRs: https://openqa.suse.de/tests/overview?distri=sle&version=15-SP6&build=79.1&groupid=431
> Add missing curl package

- lib/sles4sap_publiccloud.pm
Always print ssh down END
- Related ticket: https://jira.suse.com/browse/TEAM-9215
- sle-15-SP5-HanaSr-Azure-Byos-x86_64-Build15-SP5_2024-04-09T04:03:11Z-hanasr_azure_test_spn@64bit -> http://openqaworker15.qa.suse.cz/tests/280303
- sle-15-SP5-HanaSr-Azure-Byos-x86_64-Build15-SP5_2024-04-09T04:03:11Z-hanasr_azure_test_msi@64bit -> http://openqaworker15.qa.suse.cz/tests/280304
> Improve debug log in stop_hana

- data/autoyast_qam/12-common_base_installation.xml.ep
- Related ticket: https://progress.opensuse.org/issues/158760
- Verification run: https://openqa.suse.de/tests/overview?version=12-SP3&distri=sle&build=jpupava_12sp3
> Fix 12-SP3 ay update repo

- data/journal_check/bug_refs.json
https://bugzilla.suse.com/show_bug.cgi?id=1221779
https://bugzilla.suse.com/show_bug.cgi?id=1211721
> Whitelist kernel bugs in s390x Minimal-VM zKVM image

- data/journal_check/bug_refs.json
- Verification run: http://openqa.suse.de/tests/13993268#step/journal_check/20
> Add white list to bug_refs for slem 6.0

- tests/publiccloud/check_registercloudguest.pm
- variables.md
- Related ticket: https://progress.opensuse.org/issues/156364
- Verification run: http://autobot.qe.nue2.suse.org/tests/4312#
> Add registration test for Public Cloud RMTs

- tests/sles4sap/netweaver_swpm_installation.pm
`raise_barriers` and `release_barriers` used an array as value for hash reference, but perl flattens the array into the list which then is interpreted as part of the hash. THis pr turns arrays to references during call, and dereferences them inside the functions.
- Related ticket: https://jira.suse.com/browse/TEAM-9182
- Verification run: https://openqa.suse.de/tests/14004376
https://openqa.suse.de/tests/14006091
> Switch array for array ref in barriers

- lib/main_micro_alp.pm
- tests/console/perl_bootloader.pm
- Related ticket: https://progress.opensuse.org/issues/153871
- SLE https://openqa.suse.de/tests/overview?build=os-autoinst%2Fos-autoinst-distri-opensuse%2319023
- openSUSE https://openqa.opensuse.org/tests/overview?build=os-autoinst%2Fos-autoinst-distri-opensuse%2319023
> Update perl-Bootloader test for sle micro

- tests/security/cc/audit_remote_libvirt.pm
Ticket: https://progress.opensuse.org/issues/156661
VRs: [15-SP5-QR](https://openqa.suse.de/tests/14015445) and [15-SP6](https://openqa.suse.de/tests/14015440)
> Fix audit-remote-libvirt CC test

- lib/publiccloud/ec2.pm
VR: http://autobot.qe.nue2.suse.org/tests/4314
> Remove default value for instance upload type because it is error prone

- tests/security/cc/ipsec/ipsec_certificate.pm
Ticket: https://progress.opensuse.org/issues/156805
VRs:
* 15-SP6: https://openqa.suse.de/tests/14028191
> Change ipsec rsa768 status

- tests/publiccloud/run_ltp.pm
Unfortuanetly parsing logs is needed to be in this place as exmaple in LTP:kirk is incomplete :(
- Verification run: http://quasar.suse.cz/tests/3224
> Partially revert "Simplify uploading and parsing logs in PC/run_ltp"

- schedule/migration/migration_autoyast.yaml
- Related ticket: https://progress.opensuse.org/issues/155827
- Verification run: https://openqa.suse.de/tests/latest?arch=x86_64&distri=sle&flavor=Server-DVD-Updates&machine=64bit&test=migr_sles12sp5_&version=12-SP5
Shoudl be merged before MR: https://gitlab.suse.de/qe-yam/openqa-job-groups/-/merge_requests/104
> Add schedule for migration in MU

- tests/security/cc/cc_audit_test_setup.pm
Ticket: https://progress.opensuse.org/issues/158967
VRs:
* 15-SP6: https://openqa.suse.de/tests/14030424
* 15-SP5: https://openqa.suse.de/tests/14030427
> Add missing nc command to CC tests

- tests/microos/patterns.pm
- tests/qemu/qemu.pm
Issue in staging: https://openqa.suse.de/tests/14037606#step/patterns/30
VR: https://openqa.suse.de/tests/14037863#live
> SL Micro: adapt tests for the new pattern names

- tests/x11/seahorse_sshkey.pm
Ticket: https://progress.opensuse.org/issues/157306
VRs: [15-SP6](https://openqa.suse.de/tests/14038284), [15-SP5-QR](https://openqa.suse.de/tests/14038283), [15-SP4](https://openqa.suse.de/tests/14038285)
> Fix seahorse_sshkey test

- schedule/migration/migration_autoyast.yaml
- schedule/yast/maintenance/autoyast_create_hdd_maintenance.yaml
##
* https://progress.opensuse.org/issues/154948
- Needles: 
* N/A
* TBA
##
> Remove scc_deregister from create_hdd_maintenance_desktop

- data/containers/nginx/index.html
- data/containers/nginx/nginx.conf
- data/containers/nginx/test_nginx.container
- schedule/sle-micro/validate_container_slem_migration.yaml
- tests/containers/testenv_prepare.pm
- tests/containers/testenv_validation.pm
- Related ticket: https://progress.opensuse.org/issues/155857
- Needles: No
- Verification run:  http://deepthi-openqa.qe.suse.de/tests/6876#
Latest VR:http://deepthi-openqa.qe.suse.de/tests/6893
> test to confirm container status post migration from slem-5.5 to 6.0

- data/sles4sap/qe_sap_deployment/mr_test_azure.yaml
- data/sles4sap/qe_sap_deployment/mr_test_gcp.yaml
Some changes that were forgotten in https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/18796
- Related ticket: https://jira.suse.com/browse/TEAM-9123
- Verification run: https://openqa.suse.de/tests/14051770
> Change sshkey variable name in mr_test files

- tests/publiccloud/slem_basic.pm
POO: https://progress.opensuse.org/issues/155938
- Verification run: http://quasar.suse.cz/tests/3232
> Add basic check for snapper-*.timer into slem_basic

- tests/network/samba/samba_adcli.pm
https://progress.opensuse.org/issues/159207
VR: [sle15sp3](http://openqa.suse.de/tests/overview?distri=sle&build=rfan0418_2&version=15-SP3)
> Add retry for samba dns resolve test

- tests/console/dns_srv.pm
https://progress.opensuse.org/issues/159273
[all aarches](https://openqa.suse.de/tests/overview?build=rfan0419&distri=sle&version=15-SP3)
[aarch64](http://openqa.suse.de/tests/overview?build=rfan0419_3&distri=sle&version=15-SP3)
> Add retry for dns resolve test

- lib/utils.pm
##
* https://progress.opensuse.org/issues/158733
- Needles: 
* N/A
* https://openqa.suse.de/t14112356
##
> Revisit soft-failure bsc1192331

- schedule/security/create_hdd_ipmi_libyui/minimal+base_beta_ipmi.yaml
- schedule/security/create_hdd_ipmi_libyui/minimal+base_nobeta_ipmi.yaml
Ticket: https://progress.opensuse.org/issues/152359
VRs: https://openqa.suse.de/tests/overview?distri=sle&version=15-SP6&build=82.1&groupid=431
> New schedule for ipmi tests

- tests/console/libssh.pm
https://progress.opensuse.org/issues/159423
[sle](http://openqa.suse.de/tests/overview?distri=sle&build=rfan0423)
[tw](https://openqa.opensuse.org/tests/4099741)
> Fix package dependency issue for libssh test

- data/yam/autoyast/create_hdd_textmode_powervm.xml
Use default partition for powerVM
- Failed job:  https://openqa.suse.de/tests/13916387#step/installation/3
- Verification run: https://openqa.suse.de/tests/13922380
> Use default partition for powerVM

- tests/containers/testenv_prepare.pm
- tests/containers/testenv_validation.pm
Run two containers within a pod under systemd,  ensure the status of containers running after the migration of SLEM 5.5 to SLEM6.0
- Related ticket: https://progress.opensuse.org/issues/155857
- Needles:NO
- Verification run: http://deepthi-openqa.qe.suse.de/tests/6923#
> Test to confirm the status of two containers within a pod  post migration

- schedule/security/alp/fips_crypt_core.yaml
- tests/console/openssl_alpn.pm
- tests/fips/openssh/openssh_fips.pm
- tests/fips/openssl/openssl_fips_alglist.pm
- tests/fips/openssl/openssl_fips_cipher.pm
Ticket: https://progress.opensuse.org/issues/152359
VRs: [SL-Micro](https://openqa.suse.de/tests/14122024) and [15-SP6](https://openqa.suse.de/tests/14122014)
> Fix openSSL FIPS tests on SLE Micro 6.0

- tests/microos/networkmanager.pm
https://bugzilla.suse.com/show_bug.cgi?id=1221351
- Verification run: https://openqa.suse.de/tests/14121545
> Fix timing issue on slem NM tests

- tests/qam-updinstall/update_install.pm
- Related ticket: https://progress.opensuse.org/issues/159090
- Verification run: https://openqa.suse.de/tests/14142965
> Add libcontainers-openSUSE-policy conflict

- tests/containers/bci_prepare.pm
- Related PR: https://openqa.suse.de/tests/14146248
- Verification run: https://openqa.suse.de/tests/14145887
> Add DHCP workaround for Ubuntu after rebooting

- tests/fips/openssh/openssh_fips.pm
Ticket: https://progress.opensuse.org/issues/159630
VRs: [SLEM](https://openqa.suse.de/tests/14154664#step/openssh_fips/1), [15-SP6](https://openqa.suse.de/tests/14154665#step/openssh_fips/1), [JeOS](https://openqa.suse.de/tests/overview?distri=sle&version=15-SP5&build=20240425-1&groupid=431)
> Fix openssh fips test

- tests/fips/fips_setup.pm
Ticket: https://progress.opensuse.org/issues/158499
VRs: [SLEM](https://openqa.suse.de/tests/14155121#step/fips_setup/1), [15-SP6-ker](https://openqa.suse.de/tests/14155120#step/fips_setup/1), [15-SP6-env](https://openqa.suse.de/tests/14155550#step/fips_setup/1), [JeOS](https://openqa.suse.de/tests/overview?distri=sle&version=15-SP5&build=20240425-1&groupid=431)
> Use setup-fips on SL Micro 6.0

- lib/main_containers.pm
- tests/containers/skopeo.pm
Create a simple smoke test for skopeo with docker. 
- Related ticket: https://progress.opensuse.org/issues/154933
15-SP6 https://openqa.suse.de/tests/14156187   OK
sle-micro 6.0 https://openqa.suse.de/tests/14156188 OK
15-SP6 JeOS https://openqa.suse.de/tests/14156189 OK
openSUSE Tumbleweed  https://openqa.opensuse.org/tests/4110837 OK
MicroOS Tumbleweed https://openqa.opensuse.org/tests/4110836 OK
openSUSE 15.6 https://openqa.opensuse.org/tests/4110838 OK
> Add skopeo test poo#154933

- tests/containers/slem_rancher.pm
- Related ticket: https://progress.opensuse.org/issues/159417
- Failing VRs: [Elemental](https://openqa.suse.de/tests/14138471#settings), [Elemental-base](https://openqa.suse.de/tests/14138470#settings)
- VRs: [Elemental](https://openqa.suse.de/tests/14157904#settings), [Elemental-base](https://openqa.suse.de/tests/14157905#), [SLEM-Rancher-5.4](https://openqa.suse.de/tests/14157902#settings), [SLEM-Rancher-5.2](https://openqa.suse.de/tests/14157903#)
> Fix for Elemental containers images

- schedule/security/slmicro/container_selinux.yaml
- schedule/security/slmicro/fde_misc.yaml
- schedule/security/slmicro/fips_crypt_core.yaml
Ticket: https://progress.opensuse.org/issues/158101
> Rename alp folder to slemicro

- tests/console/openssl_nodejs.pm
https://progress.opensuse.org/issues/159609
[VR](https://openqa.suse.de/tests/overview?build=rfan0430&distri=sle)
> Enable source pool if no updated source package available

- tests/console/python3_setuptools.pm
- Related ticket: https://progress.opensuse.org/issues/159777 https://jira.suse.com/browse/PED-8196
- Verification run: https://dzedro.suse.cz/tests/1001#step/python3_setuptools/114
> Skip puthon39 test on 15-SP5, no pip package

- tests/containers/podman_integration.pm
- tests/containers/runc_integration.pm
- tests/containers/skopeo_integration.pm
Display useful information for packages in upstream tests
- Verification run:  https://openqa.opensuse.org/t4159932
> containers: Display useful information for packages in upstream tests

- tests/publiccloud/slem_basic.pm
Failed job : https://openqa.suse.de/tests/14162176
VR: http://autobot.qe.nue2.suse.org/tests/4320
> Skip cockpit test for SLM 6.0

- data/journal_check/bug_refs.json
https://bugzilla.suse.com/show_bug.cgi?id=1215378
- Verification run: https://openqa.suse.de/tests/14224199#step/journal_check/21
> Add new white list for bsc#1215378

- tests/containers/rootless_podman.pm
- tests/jeos/prepare_openstack.pm
- ticket: https://progress.opensuse.org/issues/158784
* http://kepler.suse.cz/tests/23268
* http://kepler.suse.cz/tests/23267#
> Remove hardcoded usernames from container and jeos tests

- data/yam/autoyast/support_images/create_hdd_sap_textmode_sles.xml.ep
- data/yam/autoyast/support_images/sles12sp5_install_default_patterns_ppc64le_multi-user.xml
- schedule/yast/maintenance/sap_autoyast_create_hdd_textmode_netweaver_sle12.yaml
Change gnome to textmode for sles12sp5 autoyast profile
- Related ticket: https://progress.opensuse.org/issues/158431
- Verification run: https://openqa.suse.de/tests/14067572
https://openqa.suse.de/tests/14048315
https://openqa.suse.de/tests/14048316
- Related MR: https://gitlab.suse.de/qe-yam/openqa-job-groups/-/merge_requests/158
> Change gnome to textmode for sles12sp5 autoyast profile

- schedule/yast/sle/flows/default_sle15sp4_beta_s390x_kvm.yaml
- schedule/yast/sle/flows/default_sle15sp4_beta_x86.yaml
Add temporary mu schedule that includes accepting beta module, for 15-SP6 public rc
https://progress.opensuse.org/issues/159789
> Add accept_beta module for mu schedules 15SP6

- tests/jeos/firstrun.pm
Adjust the condition accordingly.
- Verification run: https://openqa.opensuse.org/tests/4168382
> jeos/firstrun.pm: SSH enrollment is in Tumbleweed now

- data/autoyast_qam/12-common_base_installation.xml.ep
- data/autoyast_qam/12_installation.xml.ep
- data/autoyast_qam/15_installation.xml.ep
Eneable firewalld service for base installation
Add some missed repos/addons
[VR](https://openqa.suse.de/tests/overview?build=rfan0506&distri=sle&version=12-SP5)
> Fix some logic issues for qam autoyast config files

- tests/containers/podman_integration.pm
Fix stupid bug introduced in previous commit
> containers: Fix stupid bug introduced in previous commit

- data/autoyast_qam/12_installation.xml.ep
Quick fix for https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/19239
https://openqa.suse.de/tests/14256976
> Enable vnc-server in firewalld configuration and fix network config issue

- tests/virtualization/universal/xl_create.pm
- Related ticket: https://progress.opensuse.org/issues/153916
- Needles: N/A
[15-SP6](http://10.100.103.65/tests/3147#dependencies)
[15-SP5](http://openqa.qam.suse.cz/tests/73810#dependencies)
[15-SP3](http://openqa.qam.suse.cz/tests/73859#dependencies)
[12-SP5](http://openqa.qam.suse.cz/tests/73865#dependencies)
> Manually add network for xen-xl

- tests/console/bind.pm
- Related ticket: https://progress.opensuse.org/issues/159465 2703d551b32a9334aba4fd62cfe6d9f32beb728c
expected fail: https://dzedro.suse.cz/tests/1024#step/bind/116
https://dzedro.suse.cz/tests/1017 15-SP2
https://dzedro.suse.cz/tests/1018 15-SP3
> Fix required module for bind and expected failure

- schedule/yast/installer_extended/installer_extended_x86_64.yaml
- test_data/yast/installer_extended/installer_extended_aarch64.yaml
- test_data/yast/installer_extended/installer_extended_ppc64le_s390x.yaml
##
- Needles: N/A
- [**VR**](https://openqa.suse.de/tests/overview?distri=sle&version=15-SP6&build=huajluo_lang)
##
> Change license language text for English

- tests/containers/skopeo.pm
- Failing test: https://openqa.suse.de/tests/14266276/modules/docker_skopeo/steps/18
- Related ticket:https://progress.opensuse.org/issues/160185
- Verification run: https://openqa.suse.de/tests/14267743
> containers: Do not select serial terminal for vmware

- schedule/sles4sap/hana/pvm_hana.yaml
- schedule/sles4sap/hana/pvm_hana_cluster_node.yaml
Add 15-SP6 & 15-SP7 on hmc_ppc64le installation schedules.
- Needles: N/A
- Verification run: TBA
> Add 15-SP6 & 15-SP7 on hmc_ppc64le installation schedules

- lib/publiccloud/instance.pm
Flow controls added to the files to upload: in `create_instance`, during boottime measures collection, the code didn't check existence of logs to upload and exit code triggered skip of push to remote db: now fixed.
- Related ticket: https://progress.opensuse.org/issues/160038
- Needles: N/A
- sle-micro-6.0-Azure-BYOS-x86_64-Build0020.VR
https://openqa.suse.de/tests/14234994
- sle-micro-5.4-GCE-BYOS-Updates-x86_64-Build20240507.VR
https://openqa.suse.de/tests/14234993
> P.C.boottime measures fix pushdb skip on missing logs

- tests/migration/online_migration/yast2_migration.pm
Implement packages' vendor change in yast2 migration jobs
- Related ticket: https://progress.opensuse.org/issues/157729
- Verification run: https://openqa.suse.de/tests/14234977#
https://openqa.suse.de/tests/14250937
- Related MR: https://gitlab.suse.de/qe-yam/openqa-job-groups/-/merge_requests/185
> Implement packages' vendor change in yast2 migration jobs

- data/yam/autoyast/create_hdd_migration_ppc64le_15sp4.xml.ep
- lib/autoyast.pm
https://progress.opensuse.org/issues/157837
VRs: https://openqa.suse.de/tests/overview?groupid=527&distri=sle
> Add autoyast xml.ep for migration 15-sp4 pvm

- tests/console/mdadm.pm
Verification runs: https://openqa.opensuse.org/tests/overview?build=foursixnine%2Fos-autoinst-distri-opensuse%2319304&version=Tumbleweed&distri=opensuse
> Upload also systemd log for mdadm tests

- schedule/functional/extra_tests_textmode.yaml
- tests/console/opensuse_repos.pm
Add basic coverage of openSUSE-repos 
Hello this is my first test, so any help is welcome :-)
- Related ticket: https://github.com/openSUSE/openSUSE-repos/issues/54
- Related discussion: https://lists.opensuse.org/archives/list/factory@lists.opensuse.org/thread/DP3CC5RICD2GJVYBC7OZXEQUBG2Q3G4J/
- Verification run: (I don't have my private instance)
> Add opensuse_repos test suite poo#160340

- lib/main_micro_alp.pm
- lib/repo_tools.pm
- tests/publiccloud/run_ltp.pm
- Related ticket: https://progress.opensuse.org/issues/155947
az slem 5.5 https://openqa.suse.de/tests/14317952
ec2 slem 5.4 https://openqa.suse.de/tests/14317957
gce slem 5.3 https://openqa.suse.de/tests/14318272
> Run ltp tests on SLEM in PublicCloud

- CONTRIBUTING.md
Update README
I think this is a useful copypaste for somebody who's trying to add his first test and starts with a bare TW distrobox image. Especially for somebody who's new to perl, it's easier than dealing with cpan (which is not installed at that point).
> Add instructions for distrobox env

- schedule/migration/online_regression_upgrade@pvm.yaml
Remove x11 testings for power cases from yaml schedule file.
- Needles: n/a
- Verification run: https://openqa.suse.de/tests/14320986#step/consoletest_finish/4
- To fix failure: https://openqa.suse.de/tests/14318269#
> Remove x11 testings for power cases from yaml schedule file

- lib/registration.pm
- Related ticket: https://progress.opensuse.org/issues/160165
- Verification run: https://openqa.suse.de/tests/overview?version=15-SP6&build=jpupava_we&distri=sle
> Add BETA_WE variable and code to handle it

- data/yam/autoyast/create_hdd_textmode_s390x.xml
- test_data/yast/yast2_ncurses/textmode_lzo_fadump.yaml
- Related ticket: https://progress.opensuse.org/issues/160168
- Needles: -
- [Verification run](https://openqa.suse.de/tests/14288998)
> Correct KDUMP settings for s390x

- tests/qam-updinstall/update_install.pm
- Related ticket: https://progress.opensuse.org/issues/160586
- Verification run: https://openqa.suse.de/tests/overview?distri=sle&version=15-SP2&build=%3A33891%3AregionServiceClientConfigEC2&groupid=306
> update_install: Add regionServiceClientConfig{Azure,EC2,GCE} conflict

- data/journal_check/bug_refs.json
Will count in slem6.0 as well
- Verification run: http://openqa.suse.de/tests/14379224
> Add new whitelist for bsc#1215405

- lib/migration.pm
##
- Related MR: 
- https://gitlab.suse.de/qe-yam/openqa-job-groups/-/merge_requests/146
- https://progress.opensuse.org/issues/153820
- Needles: N/A
- https://openqa.suse.de/tests/14382018
- https://openqa.suse.de/tests/14387537
- https://openqa.suse.de/tests/14392716
> Check if repos existed before disable repos

- data/autoyast_qam/15_installtest.xml.ep
Packages can have dependencies to other than few mandatory modules
- Related ticket: https://suse.slack.com/archives/C02CLB8TZP1/p1715776081183469
- Verification run: https://dzedro.suse.cz/tests/1049#step/repos/5
> Add back modules to HA image

- tests/qam-updinstall/update_install.pm
- Related ticket: https://openqa.suse.de/tests/14404477#step/update_install/106
- Verification run: https://dzedro.suse.cz/tests/1053
> Add --auto-agree-with-licenses to preinstall solver

- data/yam/autoyast/support_images/create_hdd_maintenance.xml.ep
PR: https://progress.opensuse.org/issues/160269
VRs: created new hdd: https://openqa.suse.de/tests/14321529
yast test passes expert partitioner module: https://openqa.suse.de/tests/14322188
> Include latest SPs in create_hdd_maintenance ay script

- .github/workflows/openqa-comment.yml
Related ticket: https://progress.opensuse.org/issues/130940
> Allow cloning openQA jobs mentioned in PR comments

- lib/services/389ds_server.pm
Explicit `basedn` option in user handling command
- Related ticket: https://progress.opensuse.org/issues/159960
- Needles: no
- https://openqa.opensuse.org/tests/4216865
- https://openqa.opensuse.org/tests/4216866          
- https://openqa.suse.de/tests/14424112
- https://openqa.suse.de/tests/14424113
- https://openqa.suse.de/tests/14424114
- https://openqa.suse.de/tests/14424115
> dsidm: Add base dn to user creation command

- lib/virt_autotest/common.pm
- Related ticket: https://progress.opensuse.org/issues/160811
- Needles: N/A
- Verification run:  [15SP6_XEN](http://openqa.qam.suse.cz/tests/74468#dependencies) [15SP6_KVM](http://openqa.qam.suse.cz/tests/74461#dependencies)
> Switch 15sp6 guests to GMC

- data/yam/autoyast/create_hdd_migration_ppc64le.xml.ep
Add autoyast profile for 15spX prepare migration job
- Related ticket: https://progress.opensuse.org/issues/157837
- Verification run:  https://openqa.suse.de/tests/14386441#details
https://openqa.suse.de/tests/14386416#details
https://openqa.suse.de/tests/14393433
- Related MR: https://gitlab.suse.de/qe-yam/openqa-job-groups/-/merge_requests/209
> Add autoyast profile for 15spX prepare migration job

- test_data/yast/encryption/full_lvm_enc_luks2.yaml
- Related ticket: https://progress.opensuse.org/issues/160841
- Needles: N/A
- Verification run: https://openqa.opensuse.org/tests/4219313#
> Update encrypted devices number in crypttab

- tests/migration/online_migration/zypper_patch.pm
##
- Related ticket: https://progress.opensuse.org/issues/153823
- Needles: N/A
-  https://openqa.suse.de/tests/14440476
-  https://openqa.suse.de/tests/14440477
##
> Change grub timeout setting

- lib/publiccloud/ec2.pm
- tests/publiccloud/upload_image.pm
Delete commit created only for VR that asked for its deletion in https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/19358
> Revert "pc: DELETE THIS COMMIT"

- data/autoyast_qam/15_installtest.xml.ep
- tests/qam-updinstall/update_install.pm
- Related ticket: https://progress.opensuse.org/issues/153388
- Verification run: https://openqa.suse.de/tests/14440862
> update_install: Add conflicts for dpdk on aarch64

- schedule/yast/autoyast/autoyast_install_for_migr_spvm.yaml
Added yaml schedule file for powerVM prepare job
- Related ticket: https://progress.opensuse.org/issues/157837
- Related PR: https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/19348
> Added yaml schedule file for powerVM prepare job

- lib/containers/common.pm
Fix breakage introduced in https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/19383
> containers: Add CAP_NET_RAW capability for ping

- lib/main_common.pm
https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/19060
> Fix openstack image upload schedule

- tests/publiccloud/check_registercloudguest.pm
failed job : https://openqa.suse.de/tests/14424281
VR: http://autobot.qe.nue2.suse.org/tests/4340
> Fix variable name for instance

- data/autoyast_qam/15_installtest.xml.ep
- Related ticket: https://suse.slack.com/archives/C02D16TCP99/p1717049360833559
> Remove phub repo

- tests/security/ntpd.pm
- Related ticket: https://progress.opensuse.org/issues/161141
- Needles: n/a
- Verification run: https://openqa.suse.de/tests/14487383
> ntpd: Install legacy module also on sp5

- tests/yam/migration/setup_registration.pm
##
* https://progress.opensuse.org/issues/161231
- Failed case:
*  https://openqa.suse.de/tests/14491872#step/setup_registration/18
- Needles: 
* N/A
* https://openqa.suse.de/tests/14491879#step/setup_registration/20
##
> De-registers the system and base product

- tests/containers/docker_runc.pm
- tests/containers/podman_network_cni.pm
- tests/containers/podman_quadlet.pm
- tests/containers/podman_remote.pm
- tests/containers/registry.pm
- tests/containers/seccomp.pm
- tests/containers/testenv_prepare.pm
Revert due to https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/19412#issuecomment-2145526267
> Revert "containers: Use busybox instead of tumbleweed image"

- lib/virt_autotest/common.pm
- Related ticket: https://progress.opensuse.org/issues/161261
- Needles: N/A
- Verification run: [15SP6_XEN](http://openqa.qam.suse.cz/tests/74719#dependencies) [15SP6_KVM](http://openqa.qam.suse.cz/tests/74717#dependencies)
> Switch 15sp6 guests to GM

- schedule/security/selinux_jeos.yaml
- Related ticket: https://progress.opensuse.org/issues/160032
- Verification run:  https://openqa.opensuse.org/tests/4232872
Related MR: https://github.com/os-autoinst/opensuse-jobgroups/pull/470
> Enable SELinux on JeOS Tumbleweed

- data/autoyast_sle15/autoyast_no_scc_reg.xml
- schedule/functional/minimal+proxy_SCC-postreg_SUSEconnect.yaml
update yaml, remove nonse
https://gitlab.suse.de/qe-core/qa-sle-functional-userspace/-/merge_requests/226
- Related ticket: https://progress.opensuse.org/issues/134189
skip_registration_functional
https://openqa.suse.de/tests/14516184 x86_64
https://openqa.suse.de/tests/14516182 ppc64le
https://openqa.suse.de/tests/14516180 aarch64
minimal+proxy_SCC-postreg_SUSEconnect
https://openqa.suse.de/tests/14516185 x86_64
https://openqa.suse.de/tests/14516183 ppc64le
https://openqa.suse.de/tests/14516181 aarch64
> Ay profile for skip_registration_functional

- lib/oscap_tests.pm
Execute a potential long-running command in the background and use a loop that checks the process exit code to provide feedback and configurable timeout
change base class to 'console' in order to get more useful information details on an eventual failure 
- Related ticket: https://progress.opensuse.org/issues/161075
- Needles: no
- https://openqa.suse.de/tests/14525836
- https://openqa.suse.de/tests/14526456
> Run ansible remediation in background with a countdown timer

- lib/db_utils.pm
The recently migrated and renamed p.c. server `http://larry.qe.suse.de:8086` is **one-shot** checked if replies ok, before to push data on it: here a **retry** loop is used insteaad.
https://openqa.suse.de/tests/14527522#step/prepare_instance/206
result still WARNING Larry not reachable, **more likely a local network issue.**
https://openqa.suse.de/tests/14527543#step/prepare_instance/188
Same as above.
- other local machine manual checks with:
`curl -skfLI  http://larry.qe.suse.de:8086`
result is _ok_
> P.C. check Larry server up with retries

- tests/x11/toolkits/fltk.pm
- Related ticket: https://progress.opensuse.org/issues/160619
- Needles : NO
- Verification run:  https://openqa.suse.de/tests/14527117#next_previous
> Fix the sporadic issue in fltk test

- data/journal_check/bug_refs.json
Related ticket: https://progress.opensuse.org/issues/160433
VR: https://openqa.suse.de/tests/14541318
> Add soft-failures in jornal for SL Micro 6.1

- lib/oscap_tests.pm
Reverts os-autoinst/os-autoinst-distri-opensuse#19456
> Revert "Run ansible remediation in background with a countdown timer"

- tests/console/opensuse_repos.pm
https://progress.opensuse.org/issues/161798
[Verification run](https://openqa.opensuse.org/tests/overview?build=rfan0607_5&distri=opensuse&version=15.5)
> Refresh repos if zypper gets return 106

- tests/containers/rootless_docker.pm
- tests/containers/rootless_podman.pm
Increase subuid range
Failing test: https://openqa.suse.de/tests/14550490#step/rootless_podman/65
Verification run: https://openqa.suse.de/tests/14553322
> containers: Increase subuid range

- lib/sles4sap.pm
the [issue](https://openqa.suse.de/tests/14367747#step/hana_test/23) happened frequently because of worker performance issue, the command input is error, and running bash script is more stable than running command in terminal, this PR finished the change
- Related ticket: https://jira.suse.com/browse/TEAM-9362
https://openqa.suse.de/tests/14485767
https://openqa.suse.de/tests/14476230
https://openqa.suse.de/tests/14485784
> Change the command in test_pids_max function into bash script

- lib/kdump_utils.pm
- Related ticket: https://progress.opensuse.org/issues/158476 
https://openqa.opensuse.org/tests/overview?build=jpupava_kdump&distri=opensuse o3
https://openqa.suse.de/tests/overview?build=jpupava_kdump&distri=sle osd
> Revert "Use latest kernel instead active to get debuginfo"

- tests/publiccloud/check_registercloudguest.pm
- Related ticket: https://progress.opensuse.org/issues/158973
- Verification run: https://openqa.suse.de/tests/14566609#
> Fix check_registercloudguest in case we have defined user repos

- data/journal_check/bug_refs.json
VR: https://openqa.suse.de/tests/14566806#step/journal_check/9
> Soft fail bsc 1223259 in journal check

- data/journal_check/bug_refs.json
Failed jobs:
http://openqa.suse.de/tests/14570741
http://openqa.suse.de/tests/14570569
- Needles: N/A
http://openqa.suse.de/tests/14577093#
http://openqa.suse.de/tests/14577098#
> Add version slem 5.1 to white list for bsc#1226203

- data/autoyast_qam/12_installtest.xml.ep
- data/autoyast_qam/15_installtest.xml.ep
- Related issue: https://bugzilla.suse.com/show_bug.cgi?id=1226126
- Verification run: https://openqa.suse.de/tests/14569537 https://openqa.suse.de/group_overview/293
> installtest: Drop partition setup & Fix remove ISO repo

- tests/containers/podman_netavark.pm
Minimize dependency on the registry mirror for this test.  Partially reverts https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/19446
Related ticket: https://progress.opensuse.org/issues/161276
> containers: Use registry.opensuse.org/opensuse/nginx instead of httpd

- schedule/sles4sap/qam/common/qam_hana_cluster_node.yaml
- tests/kernel/wmp_simple.pm
We should run wmp_simple test for maintenance tests to verify it is working as intended
> Add wmp_simple test to maintenance tests for hana

- tests/installation/usb_install.pm
To match specified usb device for ISO image installation.
- Related ticket: https://progress.opensuse.org/issues/138638
- Verification run: https://openqa.suse.de/tests/14576136
> Fix specified usb device matching failure

- script/yaml_generator/requirements.txt
https://www.cve.org/CVERecord?id=CVE-2024-35195
> Update python request with known security issue

- lib/publiccloud/provider.pm
fixing the failure caused by #19520  - https://openqa.suse.de/tests/14598491#step/ssh_interactive_end/29
VRs - http://autobot.qe.nue2.suse.org/tests/4375#
http://autobot.qe.nue2.suse.org/tests/4376
> Remove unnecessary navigation to directory

- tests/console/opensuse_repos.pm
https://progress.opensuse.org/issues/161798
- Verification run: https://openqa.opensuse.org/tests/4278308
> Add softfail for opensuse repo refreshing issue

- schedule/security/fips_crypt_core.yaml
- schedule/security/fips_ker_mode_powervm.yaml
- tests/fips/mozilla_nss/nss_smoke.pm
Running this test on 
- Related ticket: https://progress.opensuse.org/issues/162440
- Needles: no
- https://openqa.suse.de/tests/14690720#step/nss_smoke/
- https://openqa.suse.de/tests/14691840#step/nss_smoke/
> Schedule nss_smoke in security FIPS tests

- lib/containers/bats.pm
- tests/containers/podman_integration.pm
This PR enables the podman upstream tests for 15-SP3.
- podman_testsuite 15-SP3 x86_64: https://openqa.suse.de/tests/14692170
- podman_testsuite 15-SP3 aarch64: https://openqa.suse.de/tests/14693992
NOTE: Tests will fail on subtests as we're not yet skipping any.  We're harvesting those.
> Fix python addon

- tests/containers/podman_netavark.pm
Due to constrains in opensuse's nginx and httpd (covered in different
tickets) we need to go back to dockerhub for now.
- ticket: https://progress.opensuse.org/issues/162623
- sle-micro-5.1-MicroOS-Image-Updates-x86_64-Build20240619-1-slem_containers@64bit -> https://openqa.suse.de/tests/14693615
- sle-micro-5.2-MicroOS-Image-Updates-x86_64-Build20240619-1-slem_containers@64bit -> https://openqa.suse.de/tests/14693616
- sle-micro-5.5-Default-Updates-x86_64-Build20240619-1-slem_containers@64bit -> https://openqa.suse.de/tests/14693617
- sle-micro-5.4-Default-Updates-x86_64-Build20240619-1-slem_containers@64bit -> https://openqa.suse.de/tests/14693634
- sle-micro-5.3-MicroOS-Image-Updates-x86_64-Build20240619-1-slem_containers@64bit -> https://openqa.suse.de/tests/14693680
* …
> Use httpd image from dockerhub

- data/yam/autoyast/support_images/sles15sp4_install_gnome_all_patterns_s390x.xml
- data/yam/autoyast/support_images/sles15sp4_install_textmode_all_patterns_s390x.xml
- data/yam/autoyast/support_images/sles15sp5_install_gnome_all_patterns_s390x.xml
- data/yam/autoyast/support_images/sles15sp5_install_textmode_all_patterns_s390x.xml
- Related ticket: https://progress.opensuse.org/issues/162419
- Needles: N/A
15SP4 : http://openqa.suse.de/tests/overview?distri=sle&version=15-SP4&build=lemon-suse%2Fos-autoinst-distri-opensuse%23debug-s390x-installation-issue
15SP5: https://openqa.suse.de/tests/overview?build=lemon-suse%2Fos-autoinst-distri-opensuse%23debug-s390x-installation-issue&distri=sle&version=15-SP5
> Update AY profile to fix s390x installation issue

- lib/LTP/utils.pm
Install recommend package for transactional-update scenario
- Related ticket: https://progress.opensuse.org/issues/161918
- Needles: na
https://openqa.suse.de/tests/14702019  <<< publish hdd job
https://openqa.suse.de/tests/14702096  <<< verify case
> Install recommend package for transactional-update scenario

- lib/main_containers.pm
Fix previous https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/19565
Failing test: https://openqa.suse.de/tests/1470108
> containers: Fix scheduling for BATS tests

- data/autoyast_qam/15_installtest.xml.ep
- tests/qam-updinstall/update_install.pm
- Related ticket: https://progress.opensuse.org/issues/162704
- Verification run: https://openqa.suse.de/tests/14718796#step/update_install/13
> update_install: Add back phub repo with exception

- schedule/security/selinux_jeos.yaml
- Related ticket: https://progress.opensuse.org/issues/160032#note-8
- Verification run: https://openqa.opensuse.org/tests/4297178
> Simplify the JeOS SELinux test

- lib/qesapdeployment.pm
- t/09_qesapdeployment.t
- Related ticket: https://jira.suse.com/browse/TEAM-9463
sle-15-SP5-Qesap-Azure-Payg-x86_64-BuildLATEST_AZURE_SLE15_5_PAYG-qesap_azure_saptune_test@64bit
- http://openqaworker15.qa.suse.cz/tests/286559
- sle-15-SP5-Qesap-Azure-Payg-x86_64-BuildLATEST_AZURE_SLE15_5_PAYG-qesap_azure_saptune_test@64bit -> http://openqaworker15.qa.suse.cz/tests/287033 :green_circle:  example of log http://openqaworker15.qa.suse.cz/tests/287033/logfile?filename=deploy-ansible.fully-patch-system.log.txt
- sle-15-SP5-HanaSr-Aws-Byos-x86_64-Build15-SP5_2024-06-25T02:03:19Z-hanasr_aws_test_fencing_sbd@64bit -> http://openqaworker15.qa.suse.cz/tests/287031 :green_circle:  logs collected  --> example of log http://openqaworker15.qa.suse.cz/tests/287031/logfile?filename=deploy_qesap_ansible-ansible.cluster_sbd_prep.lo …
> Upload glue script logs

- schedule/security/create_hdd_cc_libyui/cc_qr_s390x.yaml
- Related ticket: https://progress.opensuse.org/issues/162584
- Needles: n/a
- https://openqa.suse.de/tests/14737293
- https://openqa.suse.de/tests/14737295
- https://openqa.suse.de/tests/14737539
- https://openqa.suse.de/tests/14737541
> Add product selection step to 15sp4 schedule for s390x CC QR

- tests/containers/podman_netavark.pm
Fix containers volume options
- Failing test: https://openqa.opensuse.org/tests/4302190#step/podman_netavark/124
- Related ticket: https://progress.opensuse.org/issues/162914
- Verification run: https://openqa.opensuse.org/tests/4302820
> containers: Fix containers volume options

- tests/console/zypper_lifecycle.pm
- Verification run: https://dzedro.suse.cz/tests/1172
> zypper_lifecycle: Update module exceptions

- lib/qesapdeployment.pm
- lib/sles4sap_publiccloud.pm
- t/15_qesap_azure.t
- tests/sles4sap/publiccloud/qesap_terraform.pm
This ticket adds 2 playbooks in the excecution of hanasr tests, IF a specific variable (**PTF_INSTALL**) is set. It also adds a function to list files from an azure storage container.
- Related ticket: https://jira.suse.com/browse/TEAM-9453
- Verification run: https://openqa.suse.de/tests/14729087
https://openqa.suse.de/tests/14744852 , https://openqa.suse.de/tests/14761827 (newest)
https://openqa.suse.de/tests/14744947 (without ptf)
> Add func to list files in azure storage

- tests/kernel/ulp_openposix.pm
Livepatch RPMs get released for multiple SLE service packs but some of the targeted glibc versions are not available on all of them. Filter the target version list by available glibc versions.
- Needles: N/A
- SLE-15SP5: https://openqa.suse.de/tests/14744715 (some targeted glibc versions available)
- SLE-15SP6: https://openqa.suse.de/tests/14744680 (no targeted glibc versions available)
> ulp_openposix: Filter livepatchable glibc versions

- tests/containers/bci_test.pm
Introduce a `skip_testrun` method to check for fine-graned test skipping and introduce a skip for spack on SLES12.
- Related ticket: https://progress.opensuse.org/issues/163055
- Verification run: [SLES12-SP5](https://openqa.suse.de/tests/14778981#step/bci_test_docker/1) (skipped) | [15-SP6](https://openqa.suse.de/tests/14778982#step/bci_test_podman/53) (not skipped)
> Skip SLES12 for spack

- lib/sles4sap.pm
softfailing happened since 15-SP6 because the method fails to find /sys/fs/cgroup/pids/user.slice/user-1001.slice/pids.max like this https://openqa.suse.de/tests/1436852,  and the goal of this PR is for compatibility with cgroup directory changes in old and new versions of systemd
- Related ticket: https://jira.suse.com/browse/TEAM-9423
https://openqa.suse.de/tests/14594067
https://openqa.suse.de/tests/14594068
> Fix softfail in hana_test on 15-SP6 because of cgroup path issue

- tests/xfstests/run.pm
Integrate all logs to a function and fix no full log or dmesg log in no heartbeat mode.
- Related ticket: https://progress.opensuse.org/issues/163085
- Verification run: [dmesg and out.bad has content](http://10.67.133.133/tests/677#step/generic-645/5)
> xfstests: Integrate all log to a function

- data/journal_check/bug_refs.json
VR: http://openqa.suse.de/tests/14788821
> Soft fail other failure messages for bsc1218181

- tests/console/qam_zypper_patch.pm
https://progress.opensuse.org/issues/163094
- [Verification run](https://openqa.opensuse.org/tests/overview?version=15.6&build=rfan0703-openSUSE-repos&distri=opensuse)
> Handle new signing key for NVIDIA repo

- tests/publiccloud/prepare_tools.pm
- Related ticket: https://progress.opensuse.org/issues/162206
- sle-15-SP5-Azure-BYOS-Updates-x86_64-Build20240702-1-publiccloud_img_proof@64bit -> https://openqa.suse.de/t14801324
> Revert "Add workaround needed for latest version"

- data/yam/autoyast/create_hdd_textmode_x86_64_raid_encrypted_home.xml
- schedule/yast/autoyast_create_hdd_textmode_raid_encrypted_home.yaml
- test_data/yast/raid/raid1_encrypted_home.yaml
- tests/console/validate_raid_encrypt_home.pm
- Related ticket: https://progress.opensuse.org/issues/160622
- Related MR: https://gitlab.suse.de/qe-yam/openqa-job-groups/-/merge_requests/240
- Needles: N/A
- Verification run:  https://openqa.suse.de/tests/14800756#
> Automate scenario with home encrypted with RAID disks directly formatted

- tests/console/validate_raid_encrypt_home.pm
- Related ticket: https://progress.opensuse.org/issues/160622
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/14809266#
> Fix mount point value for raid encrypted home

- tests/sles4sap/publiccloud/cluster_add_repos.pm
HanaSR test module cluster_add_repos has code to add additional repository. It is used to test MU.
Add an optional setting REPO_PRIORITY to force a custom priority for this additional repo.
Ticket https://jira.suse.com/browse/TEAM-9469
From the zypper man
> and 2147483647 is the lowest. -p 0 will set the priority back to the default (99). Packages from repositories with higher priority will be used even if there are better versions available in a repository with a lower priority.
- sle-15-SP5-Azure-SAP-BYOS-Incidents-x86_64-Build:33974:python3-SAPHanaSR-ScaleUp-PerfOpt@az_Standard_E8s_v3 -> http://openqaworker15.qa.suse.cz/tests/287828
0 will set the priority back to the default (99).
sle-15-SP5-Azure-SAP-BYOS-Incidents-x86_64-Build:33974:python3-SAPHanaSR-ScaleUp-PerfOpt@az_Standard_E8s_v …
> Add setting to change repo priority

- lib/sles4sap/ipaddr2.pm
- t/21_sles4sap_azure_cli.t
- t/22_ipaddr2.t
- tests/sles4sap/ipaddr2/configure.pm
Add commands to create the cluster
Change internal ssh to use private IP in place of hostname
Add UT
Fix some documentation
- Related ticket: [TEAM-9428](https://jira.suse.com/browse/TEAM-9428)
- sle-15-SP5-SapCloud-Azure-Byos-x86_64-BuildLATEST_AZURE_SLE15_5_BYOS-ipaddr2_azure_test@64bit -> http://openqaworker15.qa.suse.cz/tests/287831 :green_circle:
> Add cluster creation to the ipaddr2 test

- tests/console/mdadm.pm
- Related ticket: https://progress.opensuse.org/issues/156337
- Verification run: https://openqa.suse.de/tests/14822046
> Check mdadm version

- lib/migration.pm
Update the code of disabling installation repos for s390x
- Related ticket: https://progress.opensuse.org/issues/162299
- Verification run: https://openqa.suse.de/tests/14785327
https://openqa.suse.de/tests/14785383#
> Update the code of disabling installation repos for s390x

- tests/virtualization/universal/virtmanager_rm_devices.pm
Progress ticket: https://progress.opensuse.org/issues/162056
Related bug: https://bugzilla.suse.com/show_bug.cgi?id=1221917
- Related ticket: https://progress.opensuse.org/issues/162056
- Needles: n/a
- Verification run: http://openqa.qam.suse.cz/tests/77006
> Add softfailed for bug: 1221917

- tests/virtualization/universal/hotplugging_network_interfaces.pm
Progress ticket: https://progress.opensuse.org/issues/162053
Related bug: https://bugzilla.suse.com/show_bug.cgi?id=1201778
- Related ticket: https://progress.opensuse.org/issues/162053
- Needles: N/A
- Verification run: http://openqa.qam.suse.cz/tests/77301
> Add softfailed for bug:1201778

- lib/transactional.pm
- tests/migration/online_migration/zypper_migration.pm
- Related ticket: https://progress.opensuse.org/issues/160203
- Needles: N/A
http://openqa.suse.de/tests/14837463#step/zypper_migration/32 maintenance test for slem
http://openqa.suse.de/tests/14837464#step/zypper_migration/32  SL Micro test
> Add version check after migration in SL Micro

- tests/update/updates_packagekit_gpk.pm
- tests/update/updates_packagekit_kde.pm
- Related ticket: https://progress.opensuse.org/issues/163283
https://openqa.opensuse.org/tests/overview?distri=opensuse&version=15.6&build=20240708-1&groupid=123 15.6 Backports
https://openqa.opensuse.org/tests/overview?distri=opensuse&version=15.6&build=20240708-2&groupid=122 15.6 Updates
https://openqa.suse.de/tests/overview?build=jpupava_gpk&version=15-SP6&distri=sle SLE
> Update is not being installed workaround

- schedule/storage/nfs_baremetal.yaml
> Remove bogus ' in schedule

- schedule/storage/nfs_baremetal.yaml
the label "nfstest:" is missing in condition
> Add missing label to yaml

- tests/containers/podman_netavark.pm
We need to remove/rework (in case it is still needed) this condition if so.
> Remove PC CNI default check

- lib/sles4sap/ipaddr2.pm
- t/22_ipaddr2.t
- tests/sles4sap/ipaddr2/configure.pm
Add checks for connectivity, ssh setup
sle-15-SP5-SapCloud-Azure-Byos-x86_64-BuildLATEST_AZURE_SLE15_5_BYOS-ipaddr2_azure_test@64bit 
- http://openqaworker15.qa.suse.cz/tests/288272
> Add os_sanity to ipaddr2

- tests/publiccloud/cloud_netconfig.pm
Fixing the issue https://progress.opensuse.org/issues/163163
VR: http://autobot.qe.nue2.suse.org/tests/4394#
> Add access key to the call for metadata where it is needed

- data/yam/autoyast/sles15sp5_gnome_unregistered_no_self_update.xml.ep
- schedule/yast/autoyast/sles15sp5_gnome_unregistered_no_self_update.yaml
Ticket: https://progress.opensuse.org/issues/160952
VRs: https://openqa.suse.de/tests/overview?distri=sle&build=20240709-1&version=15-SP5&groupid=431
Related MR: https://gitlab.suse.de/qe-yam/openqa-job-groups/-/merge_requests/233
> Add new installation test without self updates

- tests/console/validate_packages_and_patterns.pm
- progress ticket: https://progress.opensuse.org/issues/163598
- related bug ticket: [#bsc1225970](https://bugzilla.suse.com/show_bug.cgi?id=1225970)
- Verification run: https://openqa.suse.de/tests/overview?build=cedvid%2Fos-autoinst-distri-opensuse%2319710
> Skip update-test check on 15SP6

- tests/sles4sap/publiccloud/qesap_ansible.pm
Add JUnit External Results to HanaSR Tests in CSP
Related ticket: [TEAM-9493](https://jira.suse.com/browse/TEAM-9493) - [Add JUnit External Results to HanaSR Tests in CSP]
- ansible failed: https://openqaworker15.qa.suse.cz/tests/288460 
- ansible passed but test case failed: https://openqaworker15.qa.suse.cz/tests/288465
- test cases passed: https://openqaworker15.qa.suse.cz/tests/288608#
> Add JUnit External Results to HanaSR Tests in CSP

- tests/qam-updinstall/update_install.pm
- Related ticket: https://openqa.suse.de/tests/14864511#step/update_install/1049
- Verification run: https://dzedro.suse.cz/tests/1198#step/update_install/1056
> update_install: Disable update repos after conflict install

- tests/qam-updinstall/update_install.pm
- Related ticket: https://openqa.suse.de/tests/14894289#step/update_install/225 https://suse.slack.com/archives/C02D16TCP99/p1720669327066189
- Verification run: https://dzedro.suse.cz/tests/1204
https://openqa.suse.de/tests/overview?build=%3A34155%3Anvidia-open-driver-G06-signed&groupid=557&flavor=Server-DVD-HA-Incidents-Install
> update_install: Add nvidia conflicts

- tests/qam-updinstall/update_install.pm
- Related ticket: https://suse.slack.com/archives/C02D16TCP99/p1720773870968369
- Verification run: https://dzedro.suse.cz/tests/1205
> update_install: Add xen-tools-domU conflict

- tests/containers/bci_test.pm
Merge all skip conditions into one routine.
- Verification run: https://duck-norris.qe.suse.de/tests/14693#step/bci_test_docker/1
> Simplify skipping routine

- lib/y2_module_consoletest.pm
- schedule/yam/test_cases/verify_consistency_self_update.yaml
- tests/yam/verify_consistency_self_update.pm
Ticket: https://progress.opensuse.org/issues/160952
VRs: https://openqa.suse.de/tests/overview?distri=sle&version=15-SP5&build=20240714-1&groupid=431
Related MR: https://gitlab.suse.de/qe-yam/openqa-job-groups/-/merge_requests/270
> Add verify_consistency_self_update and verify_yast2_control_center tests

- lib/parallel_guest_migration_base.pm
- tests/virt_autotest/parallel_guest_migration_destination.pm
- tests/virt_autotest/parallel_guest_migration_source.pm
Progress ticket: https://progress.opensuse.org/issues/163415
Bug: https://bugzilla.suse.com/show_bug.cgi?id=1221812
- Related ticket: https://progress.opensuse.org/issues/163415
- Needles: n/a
sles15sp6
http://openqa.qam.suse.cz/tests/77864#step/parallel_guest_migration_source/238
other version:
http://openqa.qam.suse.cz/tests/77870
> Add softfailure for bug: 1221812

- schedule/functional/stack_tests_python.yaml
- tests/console/python3_setuptools.pm
- tests/console/python_virtualenv.pm
- Related ticket:  https://progress.opensuse.org/issues/156472
- Needles: NO
SLE15-SP6 : [aarch64](https://openqa.suse.de/tests/14862059) | [s390x](https://openqa.suse.de/tests/14862061) | [x86_64](https://openqa.suse.de/tests/14862068)
SLE15-SP4:  [aaarch64](https://openqa.suse.de/tests/14862014) | [s390x](https://openqa.suse.de/tests/14862017) | [x86_64](https://openqa.suse.de/tests/14862025)
SLE15-SP5:  [aaarch64](https://openqa.suse.de/tests/14862001) | [s390x](https://openqa.suse.de/tests/14861999) | [x86_64](https://openqa.suse.de/tests/14862000)
Tumbleweed:  https://openqa.opensuse.org/tests/4343074
LEAP 15.6 : [x86_64](https://openqa.opensuse.org/tests/4343078) | [ppc64le](https://openqa.opensuse.org/tests/4343077) | …
> Add a new test to verify python311_virtualenv

- lib/utils.pm
VR: https://openqa.suse.de/tests/14942305
> Add missing use into utils

- lib/network_utils.pm
https://progress.opensuse.org/issues/163937
- [Verification run](http://openqa.suse.de/tests/14940234#dependencies)
> Fail the multi-machine test if gateway is not reachable

- data/journal_check/bug_refs.json
VR https://openqa.suse.de/tests/14942409#step/journal_check/9
> Soft fail bsc1215405 on SLMicro 6.0

- schedule/storage/nfs_baremetal.yaml
- tests/kernel/before_nfs_test.pm
- tests/kernel/nfs_client.pm
- tests/kernel/nfs_server.pm
- Related ticket: https://progress.opensuse.org/issues/138089
- Verification run (virtualized with Support server): 
https://openqa.suse.de/tests/14942318
https://openqa.suse.de/tests/14942319
https://openqa.suse.de/tests/14942320
- Verification run (baremetal):
https://openqa.suse.de/tests/14942321
https://openqa.suse.de/tests/14942322
> Make NFS tests able to run on bare metal while preserving behaviour on virtualized tests

- tests/qam-updinstall/update_install.pm
https://progress.opensuse.org/issues/164132
- Verification run: http://openqa.suse.de/tests/14957850
> Resolve conflict between "openssl-ibmca" packages

- data/microos/butane/script
> Variable clean-up in combustion

- lib/publiccloud/provider.pm
> pc: Set SCAP_REPORT

- lib/utils.pm
It is just make sense to also upload zypper.log together with solver 
VR: http://autobot.qe.nue2.suse.org/tests/4411
> Add zypper.log into solver archive

- tests/security/aarch64_secure_boot/yast2_bootloader.pm
Related MR: https://gitlab.suse.de/qe-security/osd-sle15-security/-/merge_requests/263
> Fix yast2_bootloader

- lib/kernel.pm
- tests/kernel/update_kernel.pm
Add support for transactional systems to update_kernel for KOTD
- Related ticket: https://progress.opensuse.org/issues/163886
- Needles: na
- Verification run: https://openqa.suse.de/tests/14957543#
> Add support for transactional systems to update_kernel for KOTD

- data/autoyast_qam/15_installtest.xml.ep
https://progress.opensuse.org/issues/164332
VR:
[create_hdd](https://openqa.suse.de/tests/14993581#details)
[test with new hdd](https://openqa.suse.de/tests/14993767)
Please ignore the failed test module, it is known issue https://progress.opensuse.org/issues/164329
> Publish qcow2 image with tsm enabled

- tests/console/suseconnect_scc.pm
https://progress.opensuse.org/issues/164183#note-4
VR https://openqa.suse.de/tests/14968601
> Auto import keys in transactional systems right after registration

- data/virt_autotest/host_unattended_installation_files/autoyast/dev_host_12.xml.ep
* **Turn** bridge_stp on after bsc#1222105 fix.
* [12sp5 kvm host](https://openqa.suse.de/tests/15000114)
* [12sp5 xen host](https://openqa.suse.de/tests/15000215)
> Turn bridge_stp on after bsc#1222105 fix

- tests/qam-updinstall/update_install.pm
https://progress.opensuse.org/issues/164538
- Verification run: https://openqa.suse.de/tests/15018971
> Resolve conflict between 'openmpi*-config' packages

- tests/fips/fips_setup.pm
Ticket: https://progress.opensuse.org/issues/161072
VRs:
* 15-SP6: [server](https://openqa.suse.de/tests/15019305) and [client](https://openqa.suse.de/tests/15019306)
* 15-SP4: [server](https://openqa.suse.de/tests/15019321) and [client](https://openqa.suse.de/tests/15019322)
> Use correct FIPS setup workflow in env mode

- data/elemental/install.yaml
- schedule/elemental/test_image.yaml
- schedule/elemental/validate_generate_image.yaml
- tests/elemental/container_validation.pm
- tests/elemental/installation.pm
- tests/elemental/shutdown.pm
Verification runs were done on my local lab.
Here some screenshots for validation. Anyway these are new tests which only impact Elemental images.
Job status:
Image generation:
Image validation:
> Adapt Elemental test for BCI release pipeline

- tests/qam-updinstall/update_install.pm
- Related ticket: https://progress.opensuse.org/issues/164329
- Verification run: https://dzedro.suse.cz/tests/1218
> update_install: Add patterns-base-fips-certified conflict

- tests/containers/prepare_hpvs.pm
Accidentaly I have merged the previous PR prematurely. There is an account change that has different settings and we need to pull s390x image specifically as the platform runs on this architecture.
- ticket: https://progress.opensuse.org/issues/163190
- Verification run: http://kepler.suse.cz/tests/23796#step/prepare_hpvs/69
> Additional updates for the HPVS module

- tests/console/libgit2.pm
- Related ticket:  https://progress.opensuse.org/issues/164338
- Needles: NO
- Verification run:  https://openqa.opensuse.org/tests/4358238#step/libgit2/33
> Fix libgit2 test in Tumbleweed

- data/journal_check/bug_refs.json
VRs:
- https://openqa.suse.de/tests/15031120#step/journal_check/4
- https://openqa.suse.de/tests/15031139#step/journal_check/5
> Soft-failures for Micro VMWare images

- schedule/install/agama_install.yaml
- tests/installation/agama.pm
- Related ticket: https://progress.opensuse.org/issues/164141
> Create a YAML schedule to install the agama based leap16.0

- data/journal_check/bug_refs.json
- Verification run: https://openqa.opensuse.org/tests/4382485
> data/journal_check/bug_refs.json: Add softfail for boo#1228854

- lib/sles4sap/azure_cli.pm
- lib/sles4sap/ipaddr2.pm
- t/21_sles4sap_azure_cli.t
- Related ticket:  https://jira.suse.com/browse/TEAM-9428
sle-15-SP5-SapCloud-Azure-Payg-x86_64-Buildmpagot_VR-ipaddr2_azure_test@64bit
-  http://openqaworker15.qa.suse.cz/tests/292422 :green_circle: 
-  http://openqaworker15.qa.suse.cz/tests/292423 :red_circle: bug in webserver config fixed now
-  http://openqaworker15.qa.suse.cz/tests/292426
-  http://openqaworker15.qa.suse.cz/tests/292424 :green_circle: 
-  http://openqaworker15.qa.suse.cz/tests/292425 :red_circle: generic deployment error
-  http://openqaworker15.qa.suse.cz/tests/292427
> Add NAT Gateway to IpAddr2 test

- data/yam/autoyast/sles15sp2_create_hdd_gnome_unregistered_no_self_update.xml.ep
The profile format style is different for 15SP2 from 15SP3+.
- Related ticket: https://progress.opensuse.org/issues/163727
- Related MR: https://gitlab.suse.de/qe-yam/openqa-job-groups/-/merge_requests/297
- Needles: N/A
- Verification run:  https://openqa.suse.de/tests/overview?distri=sle&version=15-SP2&build=20240801-1&groupid=316
> Enable test scenario to verify consistency of self-update repository in SLE 15 SP2

- tests/publiccloud/instance_overview.pm
Reverts os-autoinst/os-autoinst-distri-opensuse#19877
> Revert "PC: Workaround bsc#1228774 - SUSEConnect issues"

- lib/bootloader_pvm.pm
[spvm](https://openqa.suse.de/tests/15098476#step/bootloader/4)
[hmc](https://openqa.suse.de/tests/15098474#step/bootloader/4)
**Please ignore the failed job, it is known issue**
> Print Lpar and SUT information for PVM setup

- data/journal_check/bug_refs.json
Acknowledge long term known bugs in 15 SP7 builds
> Add 15-SP7 to known bugs

- lib/main_containers.pm
- lib/main_micro_alp.pm
POO: https://progress.opensuse.org/issues/155944
VR: http://quasar.suse.cz/tests/46# and http://quasar.suse.cz/tests/47#
> Enable container tests for SL Micro on PublicCloud

- tests/virtualization/universal/virtmanager_rm_devices.pm
- Related ticket: https://progress.opensuse.org/issues/164189
- Needles: N/A
- Verification run: [15-SP5-XEN](http://openqa.qam.suse.cz/tests/78456) , [15-SP6-XEN](http://openqa.qam.suse.cz/tests/78447)
> Clean up guest state bsc#1221917

- tests/cpu_bugs/xen_mitigations.pm
Adaption for mitigations on xen hypervisor change SLE15SP6
- Related ticket: https://progress.opensuse.org/issues/164201
- Verification run: skylake,cascadelake,icelake machines all have been tested.
-http://10.67.129.4/tests/72931 cascadelake machine
http://10.67.129.4/tests/72921  skylake
http://10.67.129.4/tests/72999  icelake
> Adaption for mitigations on xen hypervisor

- lib/main_ltp.pm
Staging: https://openqa.suse.de/tests/15112303
Updates: https://openqa.suse.de/tests/15112302
> ltp: Install updates on transactional systems for -Updates flavors

- lib/web_browser.pm
- tests/console/links_https.pm
- tests/console/lynx_https.pm
- tests/console/w3m_https.pm
Ticket: https://progress.opensuse.org/issues/164844
VRs: [15-SP4 ](https://openqa.suse.de/tests/15113477)and [15-SP5](https://openqa.suse.de/tests/15113478)
> Remove needles for console web browser tests

- lib/main_micro_alp.pm
Fixing wrong schedule https://openqa.suse.de/tests/15125257#step/registration/18 caused by #19884 
VR: TBD
> Fix scheduling regression caused by #19884

- tests/kernel_performance/install_qatestset.pm
Refer to https://jira.suse.com/browse/TEAM-9522
Merging the test workflow to single job for both x86_64 and ppc64le BM testing
VR:
http://10.67.129.4/tests/73147
http://10.67.129.4/tests/73093
http://10.67.129.4/tests/73114
> Update install_qatestset for merging workflow

- lib/hacluster.pm
The call `script_run(..., die_on_timeout => 0)` is deprecated and soon to be removed from os-autoinst. This commit replaces such call in hacluster with an alternative. In this case an alternative implementation using enter_cmd and wait_serial is used.
Change extracted from https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/19853 from @okurz 
- Related ticket: https://progress.opensuse.org/issues/164712
Changed `ha_export_logs` is used in:
- `post_fail_hook` of `hacluster` but then `hacluster`  is not defined as baseclass
- `post_fail_hook` of `sles4sap`, only if `HA_CLUSTER` is defined. It is used as base by these test modules:
- `sles4sap/ase_install`
- `sles4sap/ase_test`
- `sles4sap/desktop_icons`
- `sles4sap/ensa/*.*`
- `sles4sap/forkbomb`
- `sles4sap/grafana_dashboards` …
> Remove deprecated die_on_timeout from hacluster

- lib/containers/bats.pm
Do not install ncat if already installed
> containers: Do not install ncat if already installed

- schedule/yam/test_cases/select_modules_and_patterns+registration.yaml
##
- https://progress.opensuse.org/issues/163277
- Related MR:
- https://gitlab.suse.de/qe-yam/openqa-job-groups/-/merge_requests/293
- Needles: 
- N/A
-  [**reduce_select_modules**](https://openqa.suse.de/tests/overview?distri=sle&version=15-SP6&build=hjluo%2Fos-autoinst-distri-opensuse%23reduce_select_modules)
> Reduce yaml files for select_modules_and_patterns+registration

- lib/containers/bats.pm
- tests/containers/podman_integration.pm
Package Hub is needed for libcriu2
> containers: Add Package Hub to BATS tests

- lib/virt_autotest/esxi_utils.pm
- tests/microos/networkmanager.pm
Get mac address with vm cli command
- Related ticket: https://progress.opensuse.org/issues/164742
- Verification run:  https://openqa.suse.de/tests/15110957
> Get mac address with vm cli command

- schedule/qam/common/mau-extratests1.yaml
- tests/console/velociraptor_client_event_collect.pm
- Needles: NO
- Verification run: https://openqa.suse.de/tests/14911375#step/dpdk/267
> velociraptor-client tests

- data/yam/autoyast/support_images/sles15sp4_install_gnome_all_patterns_aarch64.xml
- data/yam/autoyast/support_images/sles15sp4_install_gnome_all_patterns_s390x.xml
- data/yam/autoyast/support_images/sles15sp4_install_gnome_all_patterns_x86_64.xml
- lib/utils.pm
##
- Failed case:
-  https://openqa.suse.de/tests/15147841#step/patch_sle/117
* Quick PR
- Needles: 
* N/A
* https://openqa.suse.de/tests/15160130
* https://openqa.suse.de/tests/15160131
##
> Fix fips-certified for sles15sp4 support image

- tests/cpu_bugs/xen_domu_mitigation_test.pm
Xen mitigation adaption for hvm and pv on sle15sp6,because of the changes
- Related ticket: https://progress.opensuse.org/issues/151352;  https://progress.opensuse.org/issues/151355
- Verificationrun:http://10.67.129.4/tests/73044; http://10.67.129.4/tests/73113; http://10.67.129.4/tests/73112; http://10.67.129.4/tests/73137; http://10.67.129.4/tests/73134; http://10.67.129.4/tests/73128
> Mitigation adaption for xen hvm and pv

- tests/containers/buildah_integration.pm
Create a temp directory for root & user buildah test
Verification run: https://openqa.opensuse.org/tests/4400611
> containers: Create a temp directory for root & user buildah test

- lib/qam.pm
- tests/migration/online_migration/zypper_migration.pm
##
- https://progress.opensuse.org/issues/161156
- Needles: 
- N/A
- [**mig-slem_migration_5.4_to_5.5_debug**](https://openqa.suse.de/tests/15098264#step/zypper_migration/54)
- [**regression**](https://openqa.suse.de/tests/15098257#)
##
> Add SLEM migration target product's MU patch before migration

- lib/partition_setup.pm
- tests/installation/start_install.pm
Handle the server with multiple NVMe disks
- Related ticket:  https://progress.opensuse.org/issues/164964
- Related PR: https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/19910
- Verification run: https://openqa.suse.de/tests/15175741
sap job: https://openqa.suse.de/tests/15175739
> Handle the server with multiple NVMe disks

- lib/services/apparmor.pm
- Related ticket: 9c31614f8e3330a3cabeacb40ca2728bbe612c77
- Verification run: https://dzedro.suse.cz/tests/1274
> apparmor: Specify workaround for one affected test

- data/journal_check/bug_refs.json
http://kepler.suse.cz/tests/23916#step/journal_check/8
> Extend known bugs for Cloud TW image

- test_data/yast/raid/raid0_gpt_uefi_test_data.yaml
- test_data/yast/raid/raid10_gpt_uefi_test_data.yaml
- test_data/yast/raid/raid1_gpt_uefi_aarch64.yaml
- test_data/yast/raid/raid1_gpt_uefi_test_data.yaml
- test_data/yast/raid/raid5_gpt_uefi_test_data.yaml
- test_data/yast/raid/raid6_gpt_uefi_aarch64.yaml
- test_data/yast/raid/raid_disks_boot_zipl.yaml
- test_data/yast/raid/raid_disks_prep_boot.yaml
- test_data/yast/raid/raid_gpt_disks_with_bios-boot.yaml
- test_data/yast/raid/raid_prep_boot_test_data_pvm.yaml
https://progress.opensuse.org/issues/165237
- Verification run: [VR for sle15sp4/sp5/sp6](http://openqa.suse.de/tests/overview?distri=sle&build=rfan0814_raid_gpt)
**PowerPC jobs are failed due to infra issue *https://progress.opensuse.org/issues/157528*
> Increase swap and bios-boot size for raid_gpt tests

- lib/oscap_tests.pm
Compress all artifacts for security/oscap_profile_tests
- Related ticket: https://progress.opensuse.org/issues/165042
- Verification run: https://openqa.suse.de/tests/15170696
> Compress and upload test artifacts

- tests/qam-updinstall/update_install.pm
- Related ticket: https://suse.slack.com/archives/C02CLB8TZP1/p1723709652348239
- Verification run: https://dzedro.suse.cz/tests/1291#step/update_install/163
> update_install: Add azure-agent conflict on SLE12

- data/journal_check/bug_refs.json
- Verification run: http://kepler.suse.cz/tests/23952#step/journal_check/9
> Add to known bugs audit is on low space error

- data/journal_check/bug_refs.json
http://kepler.suse.cz/tests/23955#step/journal_check/3
> Ignore wicked interface warning

- data/yam/agama/auto/default_tumbleweed.json
- lib/Yam/agama/agama_base.pm
- tests/yam/agama/auto.pm
- Related ticket: https://progress.opensuse.org/issues/163943
- Needles: N/A
https://openqa.opensuse.org/tests/4407119#step/auto/6  x86_64
https://openqa.opensuse.org/tests/4405327#step/auto/5  aarch64
> Update for agama auto installation

- schedule/yam/agama_auto.yaml
Update agama auto schedule file by removing sestatus test module.
- Related ticket: quick pr
- Needles: n/a
> Update agama auto schedule file by removing sestatus test module

- schedule/yast/installer_extended/installer_extended_x86_64.yaml
Quick PR.
- Needles: N/A
http://openqa.suse.de/tests/15210694#step/verify_module_registration/1
http://openqa.suse.de/tests/15210706#step/verify_module_registration/1
> Update test data of modules for installer_extended

- tests/jeos/firstrun.pm
- microos-Tumbleweed-MicroOS-Image-sdboot-x86_64-Build20240816-microos-wizard-tpm@uefi -> https://openqa.opensuse.org/tests/4414793#step/firstrun/15
- microos-Tumbleweed-MicroOS-Image-x86_64-Build20240816-microos-wizard@64bit -> https://openqa.opensuse.org/tests/4414821#step/firstrun/10
> New jeos-firstboot feature in MicroOS

- schedule/yam/agama.yaml
- tests/yam/agama/agama_is_visible.pm
- Related ticket: https://progress.opensuse.org/issues/163943
- Verification run: https://openqa.opensuse.org/tests/4415036#step/agama_is_visible/1
> Add agama interactive dummy test

- tests/openqa/webui/test_results.pm
- Related ticket: https://progress.opensuse.org/issues/165437
- Verification run: https://openqa.opensuse.org/tests/4414995
> Remove dismissing the tutorial for removed tour

- lib/wickedbase.pm
https://progress.opensuse.org/issues/165336
`waitpid` binary is only available on `sle15sp6+` so far, so we need to handle the 'wait for process done timeout' again due to comment at https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/19853/files#r1718454521
VR: 
[sle15sp4](https://openqa.suse.de/tests/15210651#dependencies)
[sle15sp6](http://openqa.suse.de/tests/15210837#dependencies)
[tw](https://openqa.opensuse.org/tests/4414555#dependencies)
> Fix timeout issue on wicked test

- tests/migration/online_migration/post_migration.pm
The `migration/online_migration/post_migration` test module includes a call to `lib/utils::fully_patch_system` as its last task. This call - which performs a `zypper patch` in the SUT - can return a retval of 102, which is a suggestion from `zypper` to restart the SUT as newly installed packages in the SUT require a reboot to start working (for example, new kernel or new kernel modules). This commit adds a check for retval 102 after `fully_patch_system` finishes, and if the return value matches 102, will restart the SUT and reconnect the consoles.
- Failed test: https://openqa.suse.de/tests/15210720#step/check_cluster_integrity/6
- Needles: N/A
- SLES+HA Rolling Upgrade 15-SP1 to 15-SP2 on Aggregates: [support server](http://mango.qe.nue2.suse.org/tests/6171), [node …
> Reboot SUT if zypper patch in post_migration returns 102

- data/autoyast_qam/15_installtest.xml.ep
- Related ticket: https://suse.slack.com/archives/C02D16TCP99/p1711011691382679
- Verification run: https://openqa.suse.de/tests/15224207#step/update_install/54
> update_install: Remove Server Applications Module from SLED

- lib/oscap_tests.pm
Added handling of input with white spaces
- Related ticket: Related ticket: https://progress.opensuse.org/issues/165042
- Verification run: https://openqa.suse.de/tests/15225751
> Fix of parameter with white space

- lib/main_common.pm
- Related ticket: https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/19996#issuecomment-2301010674
- Verification run: https://openqa.opensuse.org/tests/4419851#live
> lib/main_common.pm: Let opensuse_welcome_applicable accept a parameter again

- lib/apparmortest.pm
- schedule/security/apparmor_profile.yaml
- tests/security/apparmor_profile/apache2_changehat.pm
- tests/security/apparmor_profile/mailserver_setup.pm
- tests/security/apparmor_profile/usr_lib_dovecot_imap.pm
- tests/security/apparmor_profile/usr_lib_dovecot_pop3.pm
- tests/security/apparmor_profile/usr_sbin_dovecot.pm
- tests/security/apparmor_profile/usr_sbin_smbd.pm
Reverts os-autoinst/os-autoinst-distri-opensuse#19977
> Revert "Use serial console"

- tests/console/yast2_apparmor.pm
- Related ticket: https://progress.opensuse.org/issues/158745
- Needles: -
- Verification run: https://openqa.suse.de/tests/15233339#
> Remove soft failure for bsc#1126289

- data/publiccloud/terraform/azure.tf
- data/publiccloud/terraform/ec2.tf
- data/publiccloud/terraform/gce.tf
- lib/publiccloud/provider.pm
- variables.md
> Add possibillity to set system disk size in PublicCloud

- data/autoyast_qam/15_installtest.xml.ep
- Related ticket: b1cb1825f9aace8de465196343c438cccf6ff003.
> update_install: Keep Server Applications module on SLES

- schedule/yam/agama.yaml
##
- https://progress.opensuse.org/issues/163949
- Needles: 
-  N/A
- https://openqa.opensuse.org/t4421385
- https://openqa.opensuse.org/t4421387
- https://openqa.opensuse.org/t4421388
##
> Schedule patch_agama_test before agama_is_visible

- lib/susedistribution.pm
- tests/installation/bootloader_s390.pm
- Related ticket:  https://progress.opensuse.org/issues/163943
- Needles: N/A
- Verification run: https://openqa.opensuse.org/tests/4422311#details  with AGAMA
VR for regression: https://openqa.suse.de/tests/15243383#   without AGAMA_TEST
> Agama boot on s390x

- data/journal_check/bug_refs.json
- Related ticket: bsc#1227081
- Needles: N/A
> Nm dispatcher failed

- lib/services/apparmor.pm
- Related ticket: https://bugzilla.suse.com/show_bug.cgi?id=1229029
- Verification run: https://openqa.suse.de/tests/15244535
> apparmor: Revert nscd workaround, update is fixing the bug

- data/journal_check/bug_refs.json
- Related ticket:  https://progress.opensuse.org/issues/165264
- Needles: NO
- Verification run: https://openqa.suse.de/tests/15200124#step/journal_check/21
New VR: 
https://openqa.suse.de/tests/15244869#step/journal_check/21
https://openqa.suse.de/tests/15245014#step/journal_check/22
Ignore the new issue observed in journal log. https://openqa.suse.de/tests/15244869#step/journal_check/24
> Soft fail bsc1229146 on SLMicro 6.1

- tests/publiccloud/check_services.pm
Public cloud check_services refactory: grouped service checks not for sle-micro, improving code visibility in debugging and maintenance.
- Related ticket: Refactory
- Verification run: TBD.
> PC check_services refactory grouped non-slem services

- .github/workflows/ci.yml
Sync with upstream `os-autoinst` which uses   `perl(Perl::Tidy): == 20240511.0.0`
> Update version of Perl::Tidy

- lib/LTP/utils.pm
Creating files for upload needs to be done outside the transactional partition. Run only rpm commands in trup_shell.
This fixes error in boot_ltp
cat: /tmp/ver_linux_before.txt:
Fixes: 80bee236a ("LTP: Adapt record_info() output to Micro")
Fixes: https://progress.opensuse.org/issues/165731
Reported-by: Petr Cervinka <pcervinka@suse.com>
- https://openqa.suse.de/tests/15254008#step/boot_ltp/82 https://openqa.suse.de/tests/15254008#step/boot_ltp/100 (Micro, boot_ltp)
- https://openqa.suse.de/tests/15254009 (SLE 15-SP6, boot_ltp)
- https://openqa.suse.de/tests/15254015 (Micro, install_ltp)
- https://openqa.suse.de/tests/15254017 (15-SP6, install_ltp)
- https://openqa.opensuse.org/tests/overview?build=poo165731 (Tumbleweed verifications)
> LTP/boot_ltp: Fix runtime failure on Micro

- tests/elemental/container_validation.pm
Fix the code to allow test of Elemental images based on SLMicro5.5 in addition to SLMicro6.0 ones (which already work).
- Needles: N/A
- Verification runs: https://openqa.suse.de/tests/15254675, https://openqa.suse.de/tests/15254706
- Regression runs: https://openqa.suse.de/tests/15254702, https://openqa.suse.de/tests/15254705
> Fix Elemental55 image test

- tests/microos/network_bonding.pm
- Related ticket: https://progress.opensuse.org/issues/153217
- Verification run: [https://openqa.opensuse.org/tests/4428402](https://openqa.opensuse.org/tests/4428402)
https://openqa.opensuse.org/tests/4436553 aarch64
> Extension proposition

- tests/fips/openssl/openssl_pubkey_dsa.pm
Related ticket: https://progress.opensuse.org/issues/165689
15-SP5:
- x86_64: https://openqa.suse.de/tests/15275444
- s390x: https://openqa.suse.de/tests/15275445
- aarch64: https://openqa.suse.de/tests/15275446
15-SP6:
- x86_64: https://openqa.suse.de/tests/15275437
- s390x: https://openqa.suse.de/tests/15275438
- aarch64: https://openqa.suse.de/tests/15275439
> Improve DSA failure logic on OpenSSL 3

- tests/elemental/container_validation.pm
An error in the code prevents the build of the ISO.
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/15282599
> Fix Elemental ISO test

- lib/oscap_tests.pm
- tests/security/oscap_profile_tests/oscap_security_guide_setup.pm
Optimize python modules install and fix get_var
- Related ticket: https://progress.opensuse.org/issues/165908
https://openqa.suse.de/tests/15284121
https://openqa.suse.de/tests/15284089
> Optimize python modules install

- tests/transactional/trup_smoke.pm
~~Make check_reboot_changes more efficient and~~ fix https://progress.opensuse.org/issues/165920.
- Related ticket: https://progress.opensuse.org/issues/165920
- Verification run: https://openqa.opensuse.org/tests/4443203
> transactional/trup_smoke.pm: Adjust for new t-u behaviour with sdbootutil

- data/journal_check/bug_refs.json
RETBleed sounds scary but there is nothing what can be done on guest level.
> Softfail known errors in journal

- tests/yam/agama/agama.pm
- Related ticket: https://progress.opensuse.org/issues/165833
- Needles: N/A
https://openqa.opensuse.org/tests/4445470#step/agama/3 aarch64
https://openqa.opensuse.org/tests/4445469#step/agama/3                    x86_64
> Update for logs to ignore kernel message

- tests/yam/agama/agama.pm
- Related ticket:  [poo#163919](https://progress.opensuse.org/issues/163919)
> Change path for agama test execution

- tests/fips/openssl/openssl_pubkey_rsa.pm
Updates are being currently blocked due to
https://openqa.suse.de/tests/15308139#step/openssl_pubkey_rsa/12
```
The command rsautl was deprecated in version 3.0. Use 'pkeyutl' instead.
RSA operation error
804B1E3F6D7F0000:error:1C8000A5:Provider routines:rsa_encrypt:illegal or
unsupported padding
mode:providers/implementations/asymciphers/rsa_enc.c:163:
```
* [15-sp5](http://kepler.suse.cz/tests/23995#step/openssl_pubkey_rsa/22)
* [15-sp6](http://kepler.suse.cz/tests/23996#step/openssl_pubkey_rsa/22)
> Replace rsautl with pkeyutl in FIPS testing

- lib/opensusebasetest.pm
- tests/transactional/host_config.pm
VR: 
https://openqa.suse.de/tests/15319161
> Workaround for slem tests on ppc64le

- data/virt_autotest/guest_params_xml_files/sles_15_sp6_64_kvm_hvm_sev_es_x86_64.xml
- data/virt_autotest/guest_params_xml_files/sles_15_sp6_64_kvm_hvm_uefi_without_power_management_x86_64_using_virtmanagerlt3.0.0.xml
- data/virt_autotest/guest_params_xml_files/sles_15_sp6_64_xen_hvm_uefi_with_power_management_x86_64.xml
- data/virt_autotest/guest_params_xml_files/sles_15_sp6_64_xen_hvm_uefi_without_power_management_x86_64_using_virtmanagerlt3.0.0.xml
- data/virt_autotest/guest_params_xml_files/sles_15_sp7_64_kvm_hvm_sev_es_x86_64.xml
- data/virt_autotest/guest_params_xml_files/sles_15_sp7_64_kvm_hvm_uefi_with_power_management_x86_64.xml
- data/virt_autotest/guest_params_xml_files/sles_15_sp7_64_kvm_hvm_uefi_without_power_management_x86_64_using_virtmanagerlt3.0.0.xml
- data/virt_autotest/guest_params_xml_files/sles_15_sp7_64_xen_hvm_uefi_with_power_management_x86_64.xml
- data/virt_autotest/guest_params_xml_files/sles_15_sp7_64_xen_hvm_uefi_without_power_management_x86_64_using_virtmanagerlt3.0.0.xml
- data/virt_autotest/host_unattended_installation_files/autoyast/dev_host_12.xml.ep
- data/virt_autotest/host_unattended_installation_files/autoyast/dev_host_15.xml.ep
- tests/virt_autotest/install_package.pm
https://progress.opensuse.org/issues/163682
No verfification run yet. Going to verify on OSD after PR is merged.
@alice-suse @guoxuguang @waynechen55 and others, welcome review!
> Support new sle15sp7 release

- schedule/security/vendor_affirmation_validation.yaml
Ticket: https://progress.opensuse.org/issues/165509
VRs: https://openqa.suse.de/tests/overview?distri=sle&version=15-SP6&build=20240904-1&groupid=594
> Add vendor_affirmation_validation.yaml

- tests/console/gpg.pm
Ticket: https://progress.opensuse.org/issues/166214
VRs:
- 15-SP5: https://openqa.suse.de/tests/overview?distri=sle&version=15-SP5&build=20240908-1&groupid=431
- 15-SP4: https://openqa.suse.de/tests/overview?distri=sle&version=15-SP4&build=20240908-1&groupid=431
> gpg.pm: add new check for vendor affirmation

- tests/installation/bootloader_s390.pm
- Verification run: https://openqa.opensuse.org/tests/4465324
> Not bring online dasd in agama

- tests/kernel/install_ltp.pm
nfs-server service is disabled by default in micro lead nfs related case such as statx07 failed.
- Related ticket: https://progress.opensuse.org/issues/161918
- Needles: na 
installation job: https://openqa.suse.de/tests/14810586#
case job: https://openqa.suse.de/tests/14810610#step/statx07/7
https://openqa.suse.de/tests/14837330#step/statx07/7
NOTE: No vsftpd found in current sle-micro.  so make another workaround in code.
```
localhost:~ # zypper lr -u
Repository priorities are without effect. All enabled repositories share the same priority.
--+---------------------------------------------------------+----------+---------+-----------+---------+--------------------------------------------------------------------------------
1 | …
```
> Start nfs service for micro ltp test
