data/sles4sap/qe_sap_deployment/hanasr_azure.yaml
data/sles4sap/qe_sap_deployment/hanasr_ec2.yaml
data/sles4sap/qe_sap_deployment/hanasr_gcp.yaml
data/sles4sap/qe_sap_deployment/trento_azure.yaml
lib/sles4sap_publiccloud.pm
tests/sles4sap/publiccloud/hana_sr_takeover.pm
tests/sles4sap/publiccloud/qesap_ansible.pm

Fully patch system before test start on public cloud qesap-deployment test cases
TEAM-8437 - [qesap-deployment] Fully patch system before test start
1. Fully patch system before test start via ansible playbook
2. Fix the timed out issue introduce in this "fully patch"
3. Remove previous workaround on "zypper up sudo" 
- Related ticket: https://jira.suse.com/browse/TEAM-8437
- Needles: NA
1. sle-15-SP2-HanaSr-Azure-Byos: hanasr_azure_test
https://openqaworker15.qa.suse.cz/tests/229811   (passed, (02:02 hours))
2. sle-15-SP4-HanaSr-Aws-Byos: hanasr_aws_test_saptune
http://openqaworker15.qa.suse.cz/t229807 (Command "sudo SAPHanaSR-showAttr" passed)
(The "Fenced database 'vmhana01' is not offline" failure is a known issue)  
3. sle-15-SP4-Azure-SAP-BYOS: …

Zypper patch system before test start on PC

---

data/yam/agama/auto/alp_dolomite.json
data/yam/agama/auto/alp_tumbleweed.jsonnet
schedule/yam/agama_auto_tumbleweed_select_installation_device.yaml
test_data/yam/agama_auto_tumbleweed_aarch64.yaml

Modify existing scenario agama_auto_dolomite for selecting another installation device
- Related ticket: https://progress.opensuse.org/issues/133109
- Verification run: https://openqa.opensuse.org/tests/3604381#
https://openqa.opensuse.org/tests/3604383#

Modify existing scenario agama_auto_dolomite for selecting another installation device

---

lib/YaST/Bootloader/BootloaderOptionsPage.pm

- Related ticket: https://progress.opensuse.org/issues/135512
- Needles: -
- SLE: https://openqa.suse.de/tests/12332532
- openSUSE staging: https://openqa.opensuse.org/tests/3604569
- Applied a regex to select the correct widget, that helps us to keep libyui code clean and without further version checks.

Better fix for changed widget IDs

---

tests/console/salt.pm

salt-minion is not intentionally pre-installed in TW.
* [TW](http://kepler.suse.cz/tests/21957#step/salt/1)
* [sle](http://kepler.suse.cz/tests/21958#step/salt/1)

JeOS: Fix salt-minion installation

---

lib/main_containers.pm
tests/containers/privileged_mode.pm

Test privileged mode in podman and docker. The command mount -t tmpfs none /mnt
only works in privileged mode because the read-only protection in the default mode
- http://openqa.suse.de/tests/12335440 (15-SP4 podman)
- http://openqa.suse.de/tests/12335443 (15-SP4 docker)
- http://openqa.suse.de/tests/12335444 (12-SP5 docker)

Containers: test privileged mode

---

tests/containers/privileged_mode.pm

In s390x the /dev/bus test cannot be done because doesn't exists
cannot access '/dev/bus': No such file or directory
- Verification run: http://openqa.suse.de/tests/12341927

Fix test_podman_privileged for s390x

---

lib/repo_tools.pm
tests/console/rmt/rmt_feature.pm

rmt does install mariadb104, installing then mariadb (10.2) will result in collision which will by default fail
Enable serial console after yast setup
- Related ticket: https://progress.opensuse.org/issues/135506
- Verification run: https://openqa.suse.de/tests/12325317

Don't install mariadb after rmt-server

---

tests/containers/privileged_mode.pm

/dev/bus is not working on publiccloud test runs.
- Related MR: https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/17793
- Verification run: https://duck-norris.qe.suse.de/tests/14116

Skip /dev/bus on publiccloud

---

tests/containers/volumes.pm

Remove soft-failure for https://github.com/containers/podman/issues/19529 as it was fixed on 4.7.0.
- Verification run: Not needed since the test is not soft-failing on latest podman: https://openqa.opensuse.org/tests/3612585

containers: Remove soft-failure for podman 4.7.0+

---

tests/microos/toolbox.pm

Remove soft-failure for resolved [bsc#1210587](https://bugzilla.suse.com/show_bug.cgi?id=1210587)
Not soft-failing anymore:
- sle-micro-5.2-GCE-BYOS-x86_64-Build0517-slem_containers_selinux@64bit -> https://openqa.suse.de/tests/12345825
- sle-micro-5.3-GCE-BYOS-aarch64-Build0549-slem_containers@64bit -> https://openqa.suse.de/tests/12343039
- sle-micro-5.4-EC2-BYOS-aarch64-Build0287-slem_containers_selinux@64bit -> https://openqa.suse.de/tests/12343012
- Verification run: Not needed.

microos: Remove soft-failure for resolved bsc#1210587

---

lib/hacluster.pm

This ticket clears the `args` hash of arguments not used in `script_output`, before `script_output` is called. The reason is, some failures were noticed before due to `script_output_retry_check` using some arguments contained in `%args` that are not used in the `script_output` function, however the same `%args` is internally passed to `script_output`. This can sometimes lead to wrong arguments taking the place of `timeout` in `script_output` leading to errors.
- Related ticket: https://jira.suse.com/browse/TEAM-8176
-  Verification Run:
https://openqa.suse.de/tests/12342121#details
https://openqa.suse.de/tests/12342122#details
https://openqa.suse.de/tests/12342123#details
https://openqa.suse.de/tests/12342124#details

Clean args before script_output

---

lib/version_utils.pm
tests/console/salt.pm

As it is in TW, community images are missing salt-minion.
- opensuse-15.5-JeOS-for-AArch64-aarch64-Build10.179-jeos@USBboot_aarch64 -> https://openqa.opensuse.org/tests/3609105
- sle-15-SP4-JeOS-for-kvm-and-xen-Updates-x86_64-Build20230929-1-jeos-extratest@64bit-virtio-vga -> https://openqa.suse.de/tests/12345593
- opensuse-Tumbleweed-JeOS-for-kvm-and-xen-x86_64-Build20230927-jeos@64bit_virtio -> https://openqa.opensuse.org/tests/3609106
- opensuse-Tumbleweed-JeOS-for-AArch64-aarch64-Build20230922-jeos@aarch64-HD20G -> https://openqa.opensuse.org/tests/3609107
- opensuse-Tumbleweed-JeOS-for-RPi-aarch64-Build20230922-jeos@RPi4 -> https://openqa.opensuse.org/tests/3609109
- opensuse-15.5-JeOS-for-RPi-aarch64-Build10.179-jeos@RPi3 -> https://openqa.opensuse.org/tests/3609283

JeOS: Community images do not have pre-installed salt

---

data/journal_check/bug_refs.json

Manually marking those failures as softfailures becomes cumbersome.
- Related ticket: https://bugzilla.suse.com/show_bug.cgi?id=1215380
- Related failure: https://openqa.suse.de/tests/12358146#step/journal_check/22
- Verification run: https://openqa.suse.de/tests/12358338

Add softfailure for bsc1215380

---

data/journal_check/bug_refs.json

Just to avoid this: https://openqa.suse.de/tests/12325898#step/journal_check/10
VR: https://openqa.suse.de/tests/12342071

Fix missing .* in the soft-failure for bsc1215405

---

tests/console/libgcrypt.pm

- Related ticket: https://openqa.suse.de/tests/12358748#step/libgcrypt/7
- Verification run: https://openqa.suse.de/tests/12359939

libgcrypt: Use serial terminal

---

tests/containers/rootless_podman.pm

Podman-reset yields an error after changing storage driver in [TUP test scenario](https://openqa.opensuse.org/tests/3583311#step/rootless_podman/51).
- ticket: https://progress.opensuse.org/issues/135017
- Verification run: https://openqa.opensuse.org/tests/3614543#live

Remove libpod local files in upgrade test scenario

---

tests/containers/privileged_mode.pm

The test `ls /dev/bus` will not work on JeOS.
- Related failure: https://openqa.suse.de/tests/12358111#step/docker_privileged_mode/40
- Verification run: https://openqa.suse.de/tests/12359894

Don't run /dev/bus on JeOS

---

tests/console/libgcrypt.pm

Reverts os-autoinst/os-autoinst-distri-opensuse#17893
* Breaks PC test runs, see [poo#137357](https://progress.opensuse.org/issues/137357)

Revert "libgcrypt: Use serial terminal"

---

tests/qemu/qemu.pm

Booting on s390x sometimes takes longer than the current timeout allows. This commit increases the timeout from 3 to 5 minutes.
- Related failure:
- Verification run: https://openqa.suse.de/tests/12365748

Increase timeout for booting

---

lib/sles4sap_publiccloud.pm

Add playbook fully-patch-system scheduling only if HANA is enabled.
This PR is an hot fix for mr_test failure introduced by https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/17787
TEAM-8437 - [qesap-deployment] Fully patch system before test start
- sle-15-SP4-HanaSr-Azure-Byos-x86_64-Build15-SP4_2023-10-03T04:03:09Z-hanasr_azure_test_sapconf@64bit -> http://openqaworker15.qa.suse.cz/tests/240440
- sle-15-SP5-Azure-SAP-BYOS-Incidents-saptune-x86_64-Build:30903:systemd-rpm-macros-sles4sap_gnome_saptune_notes@az_Standard_E8s_v3 -> http://openqaworker15.qa.suse.cz/tests/240441

Only call Ansible fully-patch-system if HANA

---

lib/sles4sap_publiccloud.pm
tests/sles4sap/publiccloud/cluster_add_repos.pm

IBS Mirror does not clone `Development-Tools` repositories. This pr uses `record_info` to report if tests they contain `Development-Tools` repos, so that the reviewer is aware that a repo was left out.
- Related ticket: https://jira.suse.com/browse/TEAM-8608
- Verification run: https://openqa.suse.de/tests/12365737#step/cluster_add_repos/3

Record when Development repos are found in IBSM jobs and skip them

---

tests/publiccloud/check_registercloudguest.pm

Retry the registration and increase the timeout for each try.
- Related failure: https://openqa.suse.de/tests/12366219
- Verification run: https://openqa.suse.de/tests/12366572#step/check_registercloudguest/181

Retry registration and increase timeout

---

data/containers/kubectl/deployment.yml
data/containers/registries.yaml
lib/containers/k8s.pm
tests/containers/kubectl.pm

k3s server might not have been fully operational and were not waiting long
enough to let it properly start before usage.
Installation of k3s got also complicated and for certain distros we need
to pull it from upstream whereas for TW, MicroOS or the k3s deployment
script is already packaged. For k3s usage, we do not need to
specifically install `kubenernetes-client` as this handled in the k3s
deployment script.
Allow installation of kubernetes-client either by version that should be
part of the test suite setup or pull the newest available in the distro.
- tickets:
- https://progress.opensuse.org/issues/132284
- https://progress.opensuse.org/issues/134726
[sle-micro-5.1-MicroOS-Image-Updates-x86_64-Build20230906](http://kepler.suse.cz/tests/21787#step/podman_pods/199) …

Rework installation of k3s and kubectl 

---

lib/containers/k8s.pm

k3s-config check reports missing apparmor-parser package on pre-installed systems.
- failure: https://openqa.suse.de/tests/12369980#step/kubectl/116
* [15-SP1](http://kepler.suse.cz/tests/21973#step/kubectl/130)
* [15-SP3@s390x](https://openqa.suse.de/tests/12372094)
* [15-SP3@aarch64](https://openqa.suse.de/tests/12372095#details)

Install explicitly apparmor for older versions of sle

---

schedule/security/389ds_sssd.yaml

- Related ticket: https://progress.opensuse.org/issues/137117
- 15-SP5: https://openqa.suse.de/tests/overview?distri=sle&version=15-SP5&build=20231003-1&groupid=431
- 15-SP4: https://openqa.suse.de/tests/overview?distri=sle&version=15-SP4&build=20231003-1&groupid=431

Add FIPS option to 389ds_sssd.yaml

---

tests/containers/privileged_mode.pm

Test podman inside other container runtime
- http://openqa.suse.de/tests/12366592
- http://openqa.suse.de/tests/12366808
- http://openqa.suse.de/tests/12366818
- http://openqa.suse.de/tests/12366819
- TW:
- https://openqa.opensuse.org/tests/3617005
- https://openqa.opensuse.org/tests/3617006
- MicroOS
- https://openqa.opensuse.org/tests/3617007

Containers: Improve container runtime privileged mode

---

tests/installation/installation_mode.pm

SUSE Linux Enterprise 15 repo on openSUSE Leap is often slow also on my desktop
- Related ticket: https://openqa.suse.de/tests/12372538#step/installation_mode/4
- Verification run: https://openqa.suse.de/tests/12373014

Increase timeout for opensuse repos

---

lib/containers/utils.pm

Add soft-failure for https://bugzilla.opensuse.org/show_bug.cgi?id=1215465
- Related ticket: https://progress.opensuse.org/issues/137429
- Verification run: https://openqa.opensuse.org/tests/3620875#

containers: Add soft-failure for bsc#1215465

---

lib/main_containers.pm

Disable privileged container test runs because of unintended failures on non-mainstream architectures and images.
- Verification run: https://openqa.suse.de/tests/12374466 (not present in schedule anymore)

Temporarily disable privileged container test runs

---

lib/containers/utils.pm

Fix the broken man page validation on non-Tumbleweed.
- Related ticket: https://progress.opensuse.org/issues/137456
- Verification run: [15-SP5](https://duck-norris.qe.suse.de/tests/14125#step/docker/239) | [MicroOS](https://duck-norris.qe.suse.de/tests/14126)

Fix man page validation

---

tests/hpc/gnu_compilers_hpc.pm

Testing installation of gnu-compilers-hpc-devel doesnt include the expected exit code when the process is success. So far we were catching the error code to softfail.
- Related ticket: https://progress.opensuse.org/issues/137432
https://aquarius.suse.cz/tests/19271
updated VR: https://aquarius.suse.cz/tests/19273#
updated VR_2:
first commit: https://aquarius.suse.cz/tests/19286
with second commit: https://aquarius.suse.cz/tests/19287

Remove bsc#1212351 softfail 

---

tests/hpc/ww4.pm
variables.md

Use container image with the one provided by HPC and mentioned on the documentation
- Related ticket: https://progress.opensuse.org/issues/136355
https://aquarius.suse.cz/tests/19190
updated: https://aquarius.suse.cz/tests/19227
updated2: https://aquarius.suse.cz/tests/19235

 Replace sle-micro container with the one HPC builds for warewulf

---

data/virt_autotest/host_unattended_installation_files/autoyast/dev_host_12.xml.ep
data/virt_autotest/host_unattended_installation_files/autoyast/dev_host_15.xml.ep

unreal2 and unreal3 are new SUTs on OSD. 
- Add their disk wwns to sle autoyast template.
- Change the OS partition instead of '/var/lib/libvirt/images' to default 120G as it was in non-autoyast installation.
[sle15sp6 kvm non-autoyast on unreal2](https://openqa.suse.de/tests/12415704)
[sle15sp6 xen non-autoyast on unreal3](https://openqa.suse.de/tests/12415810)   //please ignore debugging screenshots
[sle15sp6 kvm autoyast on unreal2](https://openqa.suse.de/tests/12416972)
[sle12sp5 kvm autoyast on unreal3](https://openqa.suse.de/tests/12416987)

Add disk identifier of unreal2/3 to SLE autoyast profile template for virt test

---

tests/publiccloud/img_proof.pm

Basic test for Hardened images:
- Run OpenSCAP.
- Check /etc/motd as per https://github.com/SUSE-Enceladus/img-proof/issues/358
- Check /etc/audit/rules.d/{access,delete}.rules as per the above ticket.
- Check account age as per the above ticket.
Related ticket: https://progress.opensuse.org/issues/133628
- sle-15-SP4-Azure-BYOS-Hardened-Incidents-x86_64-Build:30903:systemd-rpm-macros-publiccloud_img_proof@az_Standard_B2s -> https://openqa.suse.de/tests/12417292

pc: Basic test for Hardened images

---

schedule/migration/migration_offline_media_all_patterns_x86_64.yaml
tests/migration/deregister_ltss.pm
tests/migration/deregister_python2.pm

This PR is to split derigister_dropped_modules test module by creating two new test module to deregister ltss and python2 module. Because the supported hpc migration path doesn't include older scenarios, so we don't have ltss in hpc cases, so I didn't add SLE_HPC-LTSS to the deregister_ltss text module.
- Related ticket: https://progress.opensuse.org/issues/132920
- Needles: n/a
- https://openqa.suse.de/tests/12051316#step/deregister_ltss/1
- https://openqa.suse.de/tests/12051316#step/deregister_python2/1

Split derigister_dropped_modules test module

---

tests/virtualization/external/prepare.pm

The root cause of the issue is that the key for the problematic repository has expired. 
Solution:
use the command sudo zypper -n --gpg-auto-import-keys to automatically import and trust the repository key, then proceed with package installation.
- Related ticket:  https://progress.opensuse.org/issues/137579
- Needles: NONE
- Verification run: [Vmware test](https://openqa.suse.de/tests/12423233)， [Hyper-V test](http://openqa.suse.de/tests/12423272)

Fix expired key when uning zypper

---

lib/parallel_guest_migration_base.pm
lib/virt_autotest/utils.pm
lib/virt_autotest/virtual_network_utils.pm
tests/virt_autotest/libvirt_host_bridge_virtual_network.pm
tests/virt_autotest/libvirt_isolated_virtual_network.pm
tests/virt_autotest/libvirt_nated_virtual_network.pm
tests/virt_autotest/libvirt_routed_virtual_network.pm
tests/virt_autotest/libvirt_virtual_network_init.pm
tests/virtualization/universal/guest_management.pm
tests/virtualization/universal/patch_and_reboot.pm
tests/virtualization/universal/prepare_guests.pm
tests/virtualization/universal/virsh_start.pm
tests/virtualization/universal/virsh_stop.pm

- Description
Refer to [PED-4804](https://jira.suse.com/browse/PED-4804), In SLES15SP6, we should consider enabling libvirt modular daemons by default on new installations.
So, adapt SLE automation from monolithic to modular libvirt from 15SP6 for this PR purpose. 
- New changes
- New func `check_modular_libvirt_daemons()`
After enabled modular libvirt daemons as the default in SLES15SP6, meanwhile, we should check with each modular libvirt daemons are working properly before our SLE automation test 
- Enhancement
- Update func `restart_libvirtd()` 
- Remove func `restart_network()`
- Remove the step of restarting the service when each virtualization network type test fails
After a lot of research and investigation, when performing each virtualization network type test and found errors, …

[virt_autotest] Adapt SLE automation from monolithic to modular libvirt on 15SP6

---

tests/ha/setup_hosts_and_luns.pm

Allow HA tests on non MM setup to use a FQHN as iSCSI server.
- Related ticket: https://jira.suse.com/browse/TEAM-8206
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/12402830 & https://openqa.suse.de/tests/12402831

Allow HA tests on non MM setup to use a FQHN as iSCSI server

---

lib/qesapdeployment.pm
t/09_qesapdeployment.t
tests/sles4sap/qesapdeployment/deploy.pm

Unify qesap_ansible_log_find_timeout and qesap_ansible_log_find_missing_sudo_password.
- Related ticket: [TEAM-8593](https://jira.suse.com/browse/TEAM-8593)
- sle-15-SP5-Qesap-Azure-Payg-x86_64-BuildLATEST_AZURE_SLE15_5_PAYG-qesap_azure_saptune_test@64bit -> 
http://openqaworker15.qa.suse.cz/tests/241754
With simulated Ansible failure
```
% openqa-clone-job --parental-inheritance --skip-chained-deps --within-instance ${REF_JOB}  BUILD=mpagot_VR _GROUP="mpagot_dev" _GROUP_ID=0 _OBSOLETE=1 CASEDIR='https://github.com/mpagot/os-autoinst-distri-opensuse.git#'$(git rev-parse --abbrev-ref HEAD) QESAP_INSTALL_GITHUB_REPO='github.com/mpagot/qe-sap-deployment' QESAP_INSTALL_GITHUB_BRANCH='ansible_failure'
```
- sle-15-SP5-Qesap-Azure-Payg-x86_64-BuildLATEST_AZURE_SLE15_5_PAYG-qe …

Unify two qesap functions for the log inspection

---

lib/y2_installbase.pm
tests/autoyast/installation.pm

- Fix network disconnection(fg. https://openqa.suse.de/tests/12409285#step/installation/17) during post_fail_hook because br0 config overwritten.  br0 is the network bridge created by default on a kvm/xen server. its enlave an master interface eth0/em1/eth1/....
- Avoid issueing warnings fg. `Use of uninitialized value in pattern match (m//) at sle/tests/autoyast/installation.pm line 120.` in https://openqa.suse.de/tests/12409280/logfile?filename=autoinst-log.txt
- Replace a setting
Related ticket: https://progress.opensuse.org/issues/137078
[connection not broken in post_fail_hook](https://openqa.suse.de/tests/12423462)
[a normal sle test](https://openqa.suse.de/tests/12426655)

Fix network disconnection during post_fail_hook because br0 config overwritten and other minor improvement

---

tests/virt_autotest/guest_upgrade_run.pm
tests/virt_autotest/host_upgrade_generate_run_file.pm

* **This** aims to add support for host/guest upgrade test with non-default scc registration information. 
* **Take** host upgrade test as an example, registered SLE 12-SP5 host will also try to register upgraded 15-SP6 host which may need a different scc url instead of scc.suse.com and corresponding scc addons also need registration together.
* **Current** host upgrade is about to fail due to improper scc url, please refer to [failure1](https://openqa.suse.de/tests/12161735#step/reboot_and_wait_up_upgrade/1) and [2](https://openqa.suse.de/tests/12161736#step/reboot_and_wait_up_upgrade/1). Yast terminates before upgrade process starts.
* **Add** three parameters, including whether do registration, registration server and registration code, at all levels, including …

Add support for host/guest upgrade scc customization

---

tests/console/force_scheduled_tasks.pm

Tentative to make the test more reliable by relaxing the `force_scheduled_tasks` constraint check for loadavg <= 0.11 ; this PR addresses the first part of the ticket proposal.
- Related ticket: https://progress.opensuse.org/issues/137246
- Needles: NO
- SLE Verification runs: 
- https://openqa.suse.de/tests/12374159
- https://openqa.suse.de/tests/12374160
- https://openqa.suse.de/tests/12374161
- https://openqa.suse.de/tests/12374162
- https://openqa.suse.de/tests/12374163
- https://openqa.suse.de/tests/12374164
- https://openqa.suse.de/tests/12374165
- https://openqa.suse.de/tests/12374166
- https://openqa.suse.de/tests/12374167
- https://openqa.suse.de/tests/12374168
- https://openqa.suse.de/tests/12374169
- Leap 15.4:
- https://openqa.opensuse.org/tests/3626435              
- …

Relax max load average threshold to cope with flakyness

---

lib/main_publiccloud.pm
tests/publiccloud/hardened.pm
tests/publiccloud/img_proof.pm

Move hardened test to smoke tests
- Related ticket: https://progress.opensuse.org/issues/133628
- Verification run: https://openqa.suse.de/tests/12442448
Found a bug in hardened images:
https://bugzilla.suse.com/show_bug.cgi?id=1216088

pc: Move hardened test to smoke tests

---

schedule/hpc/multi_machine_test.yaml

Avoid running redundant tests of cpuid for each mpi test suite. The change will run it only for dolly test suite.
https://aquarius.suse.cz/tests/19317#details

[HPC] Move cpuid in single job

---

tests/hpc/slurm_db.pm

This mariadb install seems redundant now since all needed dependencies including db should be installed with slurm/slurmdbd. Moreover this additional and somehow redundat zypper in mariadb resulted in a test failure for sle15sp1 since there are two mariadbs provided
**SLE12-SP5** 
**- slurm 18.08:**
**db node**: https://openqa.suse.de/tests/12442120
master node: https://openqa.suse.de/tests/12442123
slave nodes: https://openqa.suse.de/tests/12442121 
https://openqa.suse.de/tests/12442118
master backup node: https://openqa.suse.de/tests/12442119
**- slurm 20.02:**
**db node**: https://openqa.suse.de/tests/12442124
master node: https://openqa.suse.de/tests/12442126
slave nodes:  https://openqa.suse.de/tests/12442129
https://openqa.suse.de/tests/12442127
master backup node: …

HPC: Remove zypper in mariadb from slurmdb module

---

lib/services/nginx.pm
tests/console/libgcrypt.pm
tests/console/mutt.pm
tests/console/valgrind.pm

Increase timeout, maintenance repos are super slow
```
Retrieving: repomd.xml [.done (253 B/s)]
Checking whether to refresh metadata for http-download.suse.de-6658790f Retrieving: repomd.xml [.done (253 B/s)]
Checking whether to refresh metadata for http-download.suse.de-6b71bc81 Retrieving: repomd.xml [.done (253 B/s)]
Checking whether to refresh metadata for http-download.suse.de-6e13c51a Retrieving: repomd.xml [.done (253 B/s)]
Checking whether to refresh metadata for http-download.suse.de-7155363c Retrieving: repomd.xml [.done (253 B/s)]
```
- Related ticket: https://openqa.suse.de/tests/12429884#next_previous
- Verification run: https://openqa.suse.de/tests/12442663

libgcrypt, nginx, mutt: Add verbose for debugging

---

lib/containers/utils.pm

Fix the man page validation of docker and podman to account for non-ASCII characters being present now.
- Related ticket: https://progress.opensuse.org/issues/137456
- Related failure: https://openqa.opensuse.org/tests/3634257
- Verification runs: [TW docker](https://duck-norris.qe.suse.de/tests/14141) | [TW podman](https://duck-norris.qe.suse.de/tests/14140) | [15-SP5 docker](https://duck-norris.qe.suse.de/tests/14143) | [15-SP5 podman](https://duck-norris.qe.suse.de/tests/14145) | [15-SP4 docker](https://duck-norris.qe.suse.de/tests/14144) | [15-SP4 podman](https://duck-norris.qe.suse.de/tests/14146) | [15-SP3 docker](https://duck-norris.qe.suse.de/tests/14147) | [15-SP3 podman](https://duck-norris.qe.suse.de/tests/14148) | [15-SP2 docker](https://duck-norris.qe.suse.de/tests/14149) | …

Fix man page validation for docker, podman

---

tests/virtualization/external/prepare.pm

In this change we add test parameters to the "Maintenance: Virtualization - VMware + Hyper-V" Test Job so that the server details of hyperv and vmware are dynamically passed.
Related ticket: https://progress.opensuse.org/issues/133466
Needles: No corresponding needles.
Passing runs : 
vmware : https://openqa.suse.de/tests/12447151#
hyperv : https://openqa.suse.de/tests/12447152#
Failing runs : (Testing the code by not giving desired parameters.)
https://openqa.suse.de/tests/overview?build=%3AS%3AM%3A30957%3A309785%3A&distri=sle&version=15-SP5&groupid=322
Both failed with appropriate error messages.

Adding dynamic variables to identify server.

---

tests/publiccloud/hardened.pm

Avoid the warning message:
```
WARNING: Data stream component 'scap_org.open-scap_cref_pub-projects-security-oval-suse.linux.enterprise.15.xml' points out to the remote 'https://ftp.suse.com/pub/projects/security/oval/suse.linux.enterprise.15.xml'. The option --local-files 'oscap/' has been provided, but the file 'oscap/pub-projects-security-oval-suse.linux.enterprise.15.xml' can't be used locally: No such file or directory.
WARNING: Skipping ./pub-projects-security-oval-suse.linux.enterprise.15.xml file which is referenced from XCCDF content
```
- Related ticket: https://progress.opensuse.org/issues/133628
- Failing test: https://openqa.suse.de/tests/12441894/logfile?filename=serial_terminal.txt
- Verification run: https://openqa.suse.de/tests/12447030

pc: Fix name for downloaded SCAP XML

---

lib/hacluster.pm
t/11_hacluster.t

This PR is about the match case insensitive string in the cluster_status_matches_regex function (lib/hacluster.pm)
- Related ticket: [TEAM-8594](https://jira.suse.com/browse/TEAM-8594)
- Verification run: Azure @ http://openqaworker15.qa.suse.cz/tests/244007#step/test_cluster/456
http://openqaworker15.qa.suse.cz/tests/244006#step/test_cluster/456
AWS :http://openqaworker15.qa.suse.cz/tests/244009#
GCP :http://openqaworker15.qa.suse.cz/tests/244008# 
Latest VR : http://openqaworker15.qa.suse.cz/tests/245027#step/test_cluster/456
http://openqaworker15.qa.suse.cz/tests/245028#step/test_cluster/456
http://openqaworker15.qa.suse.cz/tests/245029

 fix cluster_status_matches_regex to match case insensitive strings

---

data/yam/autoyast/support_images/sles15sp3_install_gnome_default_patterns_aarch64.xml
data/yam/autoyast/support_images/sles15sp3_install_gnome_default_patterns_s390x.xml
data/yam/autoyast/support_images/sles15sp3_install_gnome_default_patterns_x86_64.xml
data/yam/autoyast/support_images/sles15sp3_install_textmode_default_patterns_aarch64.xml
data/yam/autoyast/support_images/sles15sp3_install_textmode_default_patterns_s390x.xml
data/yam/autoyast/support_images/sles15sp3_install_textmode_default_patterns_x86_64.xml

- Description: Create support image via autoyast with default modules and default patterns on SLE 15 SP3
- Related ticket: https://progress.opensuse.org/issues/132848
- Verification run: [overview](https://openqa.suse.de/tests/overview?build=issues-132848)
+ [Flavor: Server-DVD-Updates](https://openqa.suse.de/tests/overview?build=issues-132848&flavor=Server-DVD-Updates)
+ [Flavor: Migration-from-SLE15-SPx](https://openqa.suse.de/tests/overview?flavor=Migration-from-SLE15-SPx&build=issues-132848)
- Related [MR#623](https://gitlab.suse.de/qa-maintenance/qam-openqa-yml/-/merge_requests/623)

Add ay profiles for sles15sp3 default patterns installation

---

lib/Yam/agama/agama_base.pm

The command "agama logs store" gathers output from dmesg, journalctl and y2logs, so pretty much everything we need, it obsoletes save_y2logs.
VR https://openqa.opensuse.org/tests/3627417#live

Upload agama logs using agama cli

---

test_data/yast/yast2_ncurses/textmode.yaml

Crash Dump Configuration file updated, need update code to validate new values
- Related ticket: https://progress.opensuse.org/issues/137555
- Verification run: https://openqa.suse.de/tests/12440943#
https://openqa.suse.de/tests/12440955#
https://openqa.suse.de/tests/12440944#
- Related bug: https://bugzilla.suse.com/show_bug.cgi?id=1214383

Crash Dump Configuration file updated, need update code to validate new values

---

lib/publiccloud/basetest.pm
lib/sles4sap_publiccloud.pm
lib/sles4sap_publiccloud_basetest.pm

PC Modules that we use in sles4sap tests, and sap modules that inherit the PC basetest class instead of the sles4sap basetest class, do not correctly run cleanup for sap and do not destroy the peering. 
In order to tackle this in the least invasive and breaking way, this pr adds a simple conditional sap resource+peering cleanup to the PC basetest class `post_fail_hook`.
- Related ticket: https://jira.suse.com/browse/TEAM-8605
--Without failure: https://openqa.suse.de/tests/12441883
--With failure in module that inherits sles4sap basetest class: https://openqa.suse.de/tests/12443208
--With failure in module that inherits PC baseclass, outside of ssh_interactive_start/end block: https://openqa.suse.de/tests/12443384
--With failure in module that inherits PC baseclass, …

Add sap cleanup to PC basetest

---

data/sles4sap/qe_sap_deployment/qesap_azure.yaml
data/sles4sap/qe_sap_deployment/qesap_azure_fullypatch.yaml
data/sles4sap/qe_sap_deployment/qesap_azure_roles.yaml
data/sles4sap/qe_sap_deployment/qesap_azure_sapconf.yaml
data/sles4sap/qe_sap_deployment/qesap_azure_sapconf_no_reg.yaml
data/sles4sap/qe_sap_deployment/qesap_azure_uri.yaml

Fix Azure broken cluster in qesap regression via replace sap_hana_install_sid='HDB' with sap_hana_install_sid='HA0'
TEAM-8442 - Azure: broken cluster in qesap regression
- Related ticket: https://jira.suse.com/browse/TEAM-8442
- Needles: NA
- Verification run (all passed):
* qesap_azure_saptune_test (qesap_azure.yaml)  
https://openqaworker15.qa.suse.cz/tests/243955 (passed)
* qesap_azure_fullypatch (qesap_azure_fullypatch.yaml)  
http://openqaworker15.qa.suse.cz/t243956 (passed)
* qesap_azure_ansible_roles_test (qesap_azure_roles.yaml)  
https://openqaworker15.qa.suse.cz/tests/243962   (passed)
* qesap_azure_ibsmirror_peering_test (qesap_azure.yaml)  
http://openqaworker15.qa.suse.cz/t243958  (passed)
* qesap_azure_sapconf_test (qesap_azure_sapconf.yaml) …

Fix Azure broken cluster in qesap regression

---

lib/oscap_tests.pm

Except in rare occasions, probably linked to specific worker, we are able to run this expensive command in 16 minutes but most of the time it takes aroun 40-50 minutes, so we are reaching the boundary and bumping it a bit should help.
16': https://openqa.suse.de/tests/12450777#step/oscap_xccdf_eval_remote/61
51': https://openqa.suse.de/tests/12437781#step/oscap_xccdf_eval_remote/61
Note: No verification due to at the moment s390x infra is very unstable.

Bump timeout for oscap fetching remote in s390x

---

tests/console/gpg.pm

Ask gpgconf to kill all parts before cleaning up and regenerating, instead of just killing parts of it.
Fixes https://bugzilla.opensuse.org/show_bug.cgi?id=1211456 and https://bugzilla.suse.com/show_bug.cgi?id=1211444. 
Fixing these paves the way for fixing https://bugzilla.opensuse.org/show_bug.cgi?id=1215890

Kill all gpg parts before modifying configuration files

---

data/yam/autoyast/support_images/sles15sp4_install_gnome_default_patterns_aarch64.xml
data/yam/autoyast/support_images/sles15sp4_install_gnome_default_patterns_s390x.xml
data/yam/autoyast/support_images/sles15sp4_install_gnome_default_patterns_x86_64.xml
data/yam/autoyast/support_images/sles15sp4_install_textmode_default_patterns_aarch64.xml
data/yam/autoyast/support_images/sles15sp4_install_textmode_default_patterns_s390x.xml
data/yam/autoyast/support_images/sles15sp4_install_textmode_default_patterns_x86_64.xml

Add sles15sp4 ay profile for default module pattern install. Because the sles15sp4's installation ay profiles is the same with sles15sp5, so I add softlink to sles15sp5's ay profiles.
- Related ticket: https://progress.opensuse.org/issues/135992
- Needles: n/a
[Create support images](https://openqa.suse.de/tests/overview?distri=sle&version=15-SP4&build=20231011-2&groupid=251); [Verify created images](https://openqa.suse.de/tests/overview?distri=sle&version=15-SP6&build=26.1&groupid=251)
- Related mr: [mr_link](https://gitlab.suse.de/qa-maintenance/qam-openqa-yml/-/merge_requests/641)

Add sles15sp4 ay profile for default module pattern install

---

lib/virt_autotest/utils.pm
tests/virt_autotest/virt_autotest_base.pm

- Upload guest assets for normal job and clone job only, and not allow jobs with PR or personal branch upload guest assets.
- Have to increase the download time from 5 min to 15 min again because it sets the timeout of shell command rather than the openqa api. Fg. it exceeded 5 min in this test, http://10.67.129.27/tests/111#, and the test failed.
To distinguish those jobs by `CASEDIR`:
for jobs or without PR:
`CASEDIR='sle|opensuse|...'`
for jobs with PR or personal branch:
```
CASEDIR=/var/lib/openqa/pool/7/os-autoinst-distri-opensuse
CASEDIR=https://github.com/Julie-CAO/os-autoinst-distri-opensuse#julie/upload_guest_disk
```
- Related ticket: https://progress.opensuse.org/issues/137726
http://10.67.129.27/tests/111   //a normal job(upload guest assets) …

Fix uploading guest assets in virt guest installation tests

---

lib/main_containers.pm
tests/containers/bci_prepare.pm
tests/containers/bci_version_check.pm

To increase visibility for outdated container test runs, split the container version check into a separate test run.
- Related ticket: https://progress.opensuse.org/issues/135365
- Verification runs: [podman](https://duck-norris.qe.suse.de/tests/14164#step/bci_version_check/32) | [docker](https://duck-norris.qe.suse.de/tests/14165#)
The db data push error is unrelated (see https://progress.opensuse.org/issues/137819)

Separate the BCI version check

---

tests/microos/selfinstall.pm

ALP's combustion version is recent enough to not require a reboot for firstboot.
- Related failures: https://openqa.suse.de/tests/12484607#
- Verification run: https://duck-norris.qe.suse.de/tests/14253#step/selfinstall/1

Fix broken selfinstall for ALP

---

lib/sles4sap_publiccloud_basetest.pm

Small fix for potential bug mentioned in https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/17942#discussion_r1352365135
- Related ticket: https://jira.suse.com/browse/TEAM-8605
- Verification run: https://openqa.suse.de/tests/12487292 (PASS case), https://openqa.suse.de/tests/12487420 (FAIL case)

Fix forgotten sles4sap status flags update

---

data/journal_check/bug_refs.json

Happens with fixed microos-tools + combustion
- Related ticket: https://openqa.opensuse.org/tests/3641640#step/journal_check/21 https://bugzilla.opensuse.org/show_bug.cgi?id=1216196
- Verification run: https://openqa.opensuse.org/tests/3642813#live

data/journal_check/bug_refs.json: Add boo#1216196

---

data/sles4sap/qe_sap_deployment/mr_test_gcp.yaml

TEAM-8664 - [GCP][Latest - HA + SAP] all "mr_test" cases failed on qesap_terraform: Could not retrieve required variable QESAP_CLUSTER_OS_VER
The setting "SLE_IMAGE" comes from tests/sles4sap/publiccloud/qesap_terraform.pm
- Related ticket: https://jira.suse.com/browse/TEAM-8664
- Needles: NA
15SP5 production: https://openqa.suse.de/tests/12480370 (passed)
15SP5 maintenance: https://openqa.suse.de/tests/12481241 (passed)

Fix QESAP_CLUSTER_OS_VER error for mr_test

---

lib/registration.pm

ha module doesn't display eula when it has already been displayed before, but requires registration code. This PR fixes related failures.
Progress ticket: https://progress.opensuse.org/issues/136991
MR for support image: https://gitlab.suse.de/qa-maintenance/qam-openqa-yml/-/merge_requests/635
MR for migrations tests: https://gitlab.suse.de/coolgw/wegao-test/-/merge_requests/348

Modify addons_with_license conditions

---

data/yam/autoyast/support_images/sles15sp5_install_gnome_all_patterns_aarch64.xml
data/yam/autoyast/support_images/sles15sp5_install_gnome_all_patterns_s390x.xml
data/yam/autoyast/support_images/sles15sp5_install_gnome_all_patterns_x86_64.xml
data/yam/autoyast/support_images/sles15sp5_install_textmode_all_patterns_aarch64.xml
data/yam/autoyast/support_images/sles15sp5_install_textmode_all_patterns_s390x.xml
data/yam/autoyast/support_images/sles15sp5_install_textmode_all_patterns_x86_64.xml

See https://progress.opensuse.org/issues/135683:
Create support image via autoyast with default modules and all patterns on SLE 15 SP5
VRs https://openqa.suse.de/tests/overview?build=JRivrain%2Fos-autoinst-distri-opensuse%2317915&version=15-SP5&distri=sle
VRs for migration jobs https://openqa.suse.de/tests/overview?build=JRivrain%2Fos-autoinst-distri-opensuse%2317915&version=15-SP6&distri=sle
MR https://gitlab.suse.de/qa-maintenance/qam-openqa-yml/-/merge_requests/629/diffs

Add autoyast profiles for default modules all patterns in sle15sp5 migration

---

tests/publiccloud/storage_perf.pm

Current verification proved to be error prone
so currently we want to run test for some time
to collect data which will allow us to decide
which approach can be better.

Disable verification of storage_perf test

---

tests/sles4sap/qesapdeployment/configure.pm

get_blob_uri is used to populate the terraform.tfvars for Azure images not from the Azure catalog, uploaded by `publiccloud_upload_img` test module.
Avoid the the test is attempting to use the same mechanism when used in AWS/GCP testing.
- Related ticket: TEAM-8627
- Verification run: http://openqaworker15.qa.suse.cz/tests/246993

Restrict get_blob_uri call to Azure qesap regression

---

lib/main_common.pm
lib/main_ltp_loader.pm
lib/main_micro_alp.pm
products/opensuse/main.pm
products/sle/main.pm

Having a cyclic dependency is generally wrong. It now finally leads to problems when trying to use `repo_tools.pm` from `LTP/utils.pm` which on its own should be fine (see https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/17965).
Instead of relying on `main_ltp.pm` being loaded implicitly via `main_common.pm` (which `main_ltp.pm` itself depends on) this change simply loads `main_ltp.pm` where it is needed.
This change preserves the error handling. To avoid duplication the error handling was moved in the separate module `main_ltp_loader.pm` which is used instead of using `main_ltp.pm` directly. It still works (tested by putting `use foo;` in `main_ltp.pm` and running the compile check).
I've also just ran an LTP test locally and it still worked. So I guess this change doesn't …

Remove cyclic dependency between `main_common.pm` and `main_ltp.pm`

---

lib/LTP/utils.pm
tests/kernel/install_ltp.pm
tests/kernel/kirk.pm

Now it's possible to define KIRK_FROM variable that can define how we install kirk: from LTP repository or git.
This modification add support for transactional-update command.
- SLE-SP5 https://openqa.suse.de/tests/12466993#
- ALP with repo installation: https://openqa.suse.de/tests/12467943#
- ALP with git installation: https://openqa.suse.de/tests/12470996#
Ticket: https://progress.opensuse.org/issues/132680

Install kirk from repositories

---

data/sles4sap/qe_sap_deployment/qesap_aws_fullypatch.yaml
data/sles4sap/qe_sap_deployment/qesap_gcp_fullypatch.yaml

The two files are derived from qesap_aws.yaml and qesap_gcp.yaml and just add the new playbook added in  https://github.com/SUSE/qe-sap-deployment/pull/175
- Related ticket: TEAM-8437 TEAM-8629
- sle-12-SP5-Qesap-Aws-Byos-x86_64-BuildLATEST_AWS_SLE12_5_BYOS-qesap_aws_saptune_test@64bit -> http://openqaworker15.qa.suse.cz/tests/247768 :green_circle: 
- sle-15-SP5-Qesap-Aws-Payg-x86_64-BuildLATEST_AWS_SLE15_5_PAYG-qesap_aws_saptune_test@64bit -> http://openqaworker15.qa.suse.cz/tests/247757 :green_circle: 
- sle-15-SP5-Qesap-Aws-Byos-x86_64-BuildLATEST_AWS_SLE15_5_BYOS-qesap_aws_saptune_test@64bit -> http://openqaworker15.qa.suse.cz/tests/247758  :green_circle: 
- sle-15-SP4-Qesap-Aws-Byos-x86_64-BuildLATEST_AWS_SLE15_4_BYOS-qesap_aws_saptune_test@64bit -> …

Add fullypatch qesap config variants for AWS/GCP

---

t/06_autoyast.t

This hopefully helps debugging the CI failure
```
```
we're currently seeing in some PRs.

Improve error message when autoyast related check fails

---

data/yam/autoyast/support_images/sles15sp3_install_gnome_all_patterns_aarch64.xml
data/yam/autoyast/support_images/sles15sp3_install_gnome_all_patterns_s390x.xml
data/yam/autoyast/support_images/sles15sp3_install_gnome_all_patterns_x86_64.xml
data/yam/autoyast/support_images/sles15sp3_install_textmode_all_patterns_aarch64.xml
data/yam/autoyast/support_images/sles15sp3_install_textmode_all_patterns_s390x.xml
data/yam/autoyast/support_images/sles15sp3_install_textmode_all_patterns_x86_64.xml

Add ltss module for sles15sp3 all patterns with default module. 
We add it to workaround [**_bug 1216116_**](https://bugzilla.suse.com/show_bug.cgi?id=1216116).
- Related ticket: [**132854**](https://progress.opensuse.org/issues/132854)
- Needles: N/A
* [**sle_autoyast_support_image_gnome_15sp3_all_patterns**](https://openqa.suse.de/tests/overview?arch=&flavor=&machine=&test=sle_autoyast_support_image_gnome_15sp3_all_patterns_dev&modules=&module_re=&distri=sle&version=15-SP3&build=GM&groupid=220)
* [**sle_autoyast_support_image_textmode_15sp3_all_patterns**](https://openqa.suse.de/tests/overview?arch=&flavor=&machine=&test=sle_autoyast_support_image_textmode_15sp3_all_patterns_dev&modules=&module_re=&distri=sle&version=15-SP3&build=GM&groupid=220)
* VRs for modules …

 Add ltss module to workaround bug 1216116

---

data/virt_autotest/host_unattended_installation_files/autoyast/dev_host_12.xml.ep
data/virt_autotest/host_unattended_installation_files/autoyast/dev_host_15.xml.ep
data/virt_autotest/host_unattended_installation_files/autoyast_opensuse_kvm_one_disk.xml
data/virt_autotest/host_unattended_installation_files/autoyast_opensuse_kvm_two_disk.xml
data/virt_autotest/host_unattended_installation_files/autoyast_opensuse_xen_one_disk.xml
data/virt_autotest/host_unattended_installation_files/autoyast_opensuse_xen_two_disk.xml

Because of different screen resolution, not all "Error" pop-up can be detected by autoyast/installation.pm, so abort the test when errors happen.
- Related ticket: https://progress.opensuse.org/issues/138017
[sle15sp6 kvm](https://openqa.suse.de/tests/12535861#step/installation/5)  //installation stop when error pop-up occurs
[sle15sp6 kvm](https://openqa.suse.de/tests/12535846)  //installation stop when error pop-up occurs
[sle12sp5 host](https://openqa.suse.de/tests/12535887)   //test pass without errors
[TW](http://10.67.129.27/tests/120)    //installation stop when error pop-up occurs

Tests will not continue when Errors pop-up occurs in virt test host autoyast installation

---

data/wsl/Autounattend_BIOS.xml
data/wsl/Autounattend_UEFI.xml
lib/windowsbasetest.pm
schedule/wsl/install/create_windows_image.yaml
tests/wsl/install/ms_win_firstboot.pm
tests/wsl/install/ms_win_installation.pm
tests/wsl/update_windows.pm

By adding an `Autounattend.xml` file to the ISO root folder with all the options defined, the installation of Windows runs unattended without need of any clicks or screens.
- Related ticket: https://progress.opensuse.org/issues/121033
- Needles:
- [Windows 10 BIOS](https://openqa.suse.de/tests/12373524)
- [Windows 10 UEFI](https://openqa.suse.de/tests/12373672)
- [Windows 11 UEFI](https://openqa.suse.de/tests/12374123)
- [Job running on a PUBLISH_HDD_1](https://openqa.suse.de/tests/12374209)
- [Win10 job group after changes](https://openqa.suse.de/tests/overview?distri=windows&version=10&build=22H2&groupid=287)
- [Win11 job group after changes](https://openqa.suse.de/tests/overview?distri=windows&version=11&build=22H2&groupid=287)
*NOTE: the keys used in the XML files …

Make the installation of Windows unattended

---

data/journal_check/bug_refs.json
schedule/jeos/sle/jeos-main.yaml

Whenever the combustion device is missing, ignore the systemd time out
message
- http://kepler.suse.cz/tests/21996#

Combustion test adjustments in SLE

---

lib/main_containers.pm
tests/containers/privileged_mode.pm

TW
- https://openqa.opensuse.org/tests/3621805
- https://openqa.opensuse.org/tests/3622558
- https://openqa.opensuse.org/tests/3622559
SLE:
- http://openqa.suse.de/tests/12389133
- http://openqa.suse.de/tests/12389135
- http://openqa.suse.de/tests/12389143
- http://openqa.suse.de/tests/12389147(solved with retry pull) restarted https://openqa.suse.de/tests/12389248
- http://openqa.suse.de/tests/12389145
MicroOS
- https://openqa.opensuse.org/tests/3622568
With the retry for images
https://openqa.suse.de/t12389673

Containers: fix problems with privileged mode

---

tests/publiccloud/hardened.pm

Increase timeout for SCAP profile download
- Failing job: https://openqa.suse.de/tests/12539965/logfile?filename=autoinst-log.txt
- Verification run: https://openqa.suse.de/t12552741

pc: Increase timeout for SCAP profile download

---

lib/registration.pm

Pressing next directly after repo confirmation can miss the key, installation is then stuck on unexpected modules list
This is from passed test where the modules list is not even visible in video, registration registered the next key press and it worked, but often it will not be so lucky and fail.
- Related ticket: https://openqa.suse.de/tests/12546751#step/ntp_config_settings/2
- Verification run: https://openqa.suse.de/tests/12552748

registration: Wait after confirming update repos

---

lib/x11test.pm
tests/x11/firefox/firefox_html5.pm
tests/x11/plasma_browser_integration.pm

- Related ticket: https://progress.opensuse.org/issues/98949
- Verification run: https://openqa.suse.de/tests/overview?arch=&flavor=&machine=&test=qam-regression-firefox-SLES&modules=&module_re=&distri=sle&build=20231016-1
https://dzedro.suse.cz/tests/1954
https://dzedro.suse.cz/tests/1955

firefox: Drop unused code

---

tests/kernel/bpftrace.pm

Fails on TW Aarch64 due to missing symbols in the headers
- Related ticket: https://progress.opensuse.org/issues/137681
- Verification run: https://openqa.opensuse.org/tests/3650964 (failed for unrelated reason, waiting for new one)
@czerw

kernel/bpftrace: mv runqlat to unreliable list

---

lib/qesapdeployment.pm
schedule/sles4sap/sles4sap_gnome_saptune_maintenance.yaml
schedule/sles4sap/sles4sap_ibsm_embargo_check.yml
tests/sles4sap/publiccloud/clean_leftover_peerings.pm

Sometimes, a job will terminate without calling proper peering cleanup. This may prevent future jobs running on the same worker from creating a peering, leading them to fail.
This pr adds a set of functions and a new module, which checks all open peerings, checks if their jobs have finished, and if the answer is positive, deletes those peerings.
- Related ticket: https://jira.suse.com/browse/TEAM-8671
- Verification run: https://openqa.suse.de/tests/12551639
https://openqa.suse.de/tests/12554006

Add functions to delete stale peerings

---

data/yam/autoyast/bug-872532_ix64ph1069.xml
data/yam/autoyast/bug-876411_btrfs_h5_autoinst.xml

https://progress.opensuse.org/issues/138080
http://openqa.suse.de/tests/12561466
http://openqa.suse.de/tests/12561467
**Please** omit the new failure, it is caused by [bsc#1216283](https://bugzilla.suse.com/show_bug.cgi?id=1216283)

Add required package 'openssh' to autoyast config file

---

tests/hpc/gnu_compilers_hpc.pm

At least for all the SLE15 the default gnu_compilers_hpc should use gcc7. The
tests for non-verioned package should work without the
GNU_COMPILERS_HPC_VERSION by default.
- Related ticket: https://progress.opensuse.org/issues/138002
https://aquarius.suse.cz/tests/19434
12sp5 https://openqa.suse.de/tests/overview?version=12-SP5&distri=sle&build=b10n1k%2Fos-autoinst-distri-opensuse%2317993
15sp1 https://openqa.suse.de/tests/overview?version=15-SP1&build=b10n1k%2Fos-autoinst-distri-opensuse%2317993&distri=sle
15SP2 https://openqa.suse.de/tests/overview?version=15-SP2&distri=sle&build=b10n1k%2Fos-autoinst-distri-opensuse%2317993
15sp3 https://openqa.suse.de/tests/overview?version=15-SP3&distri=sle&build=b10n1k%2Fos-autoinst-distri-opensuse%2317993
15sp4 …

Make gnu_compilers_hpc module to work with default package

---

lib/registration.pm

After PR: https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/17956/files there was a failure due to WE module still asking for EULA acceptance during migration from 15sp5 to 15sp6:
https://openqa.suse.de/tests/12551482#details
- Verification run: WE: https://openqa.suse.de/tests/12551610
-HA: https://openqa.suse.de/tests/12553299

Modify addons_with_license conditions for HA

---

lib/qesapdeployment.pm
t/09_qesapdeployment.t
tests/sles4sap/qesapdeployment/deploy.pm

Add argument to allow the user to specify a specific filename for the log.
Use this new argument in qesap regression deployment retry.
- Related ticket:  https://jira.suse.com/browse/TEAM-8479 and https://jira.suse.com/browse/TEAM-8006
- sle-15-SP5-Qesap-Azure-Byos-x86_64-BuildLATEST_AZURE_SLE15_5_BYOS-qesap_azure_ansible_roles_test@64bit -> http://openqaworker15.qa.suse.cz/tests/249491

Add logname argument to qesap_execut

---

tests/publiccloud/hardened.pm

Add soft-fail for https://github.com/OpenSCAP/openscap/issues/1796
Failing test (killed because of OOM): https://openqa.suse.de/tests/12552741#step/hardened/18
Verification run: https://openqa.suse.de/tests/12563487

pc: Add soft-fail for https://github.com/OpenSCAP/openscap/issues/1796

---

lib/main_micro_alp.pm
lib/microos.pm
lib/opensusebasetest.pm
lib/version_utils.pm
tests/transactional/host_config.pm
variables.md

Add two helper functions to version_utils to determine which bootloader is used and make use of those in strategic places.
Implement the minimal amount of functionality needed to make a basic microos test pass.
Needs https://build.opensuse.org/request/show/1118337
- Needles: https://github.com/os-autoinst/os-autoinst-needles-opensuse/pull/801
- Verification run: http://10.168.4.192/tests/1375
VR using GRUB: https://openqa.opensuse.org/tests/3652123#live

Add support for systemd-boot as bootloader on MicroOS

---

tests/publiccloud/hardened.pm

For some reason `script_output()` doesn't catch the 137 return code when OOM, so let's check instead for the existence of report.html.
- Failing test: https://openqa.suse.de/tests/12555232/
- Related ticket: https://progress.opensuse.org/issues/138146
- Verification run: https://openqa.suse.de/tests/12563837

pc: Fix openSCAP soft-failure because of OOM

---

data/virt_autotest/host_unattended_installation_files/autoyast/dev_host_12.xml.ep

* **Some** SUT machines do not use default network interface, for example, eth0. 
* **In** order to have virtualization bridge interface correctly configured, it is better to use specified interface in bridge_ports instead of just using a list of ports that can be available, which may lead to ip lease inconsistency.
* **The** [failure](https://10.145.10.207/tests/12549852#step/login_console/7) looks like this. After modifying config for br0 by only keeping ```eth1``` in bridge_ports, the machine can get correct ip and hostname.
* Manual verification passed
* [Passed on machine uses default interface](https://openqa.suse.de/tests/12561537)
* [Passed on machine uses eth1 interface](https://openqa.suse.de/tests/12561720)

Use specified network interface in autoyast profile

---

tests/security/cc/ipsec/ipsec_client.pm
tests/security/cc/ipsec/ipsec_server.pm
tests/security/mariadb/mariadb_ssl_client.pm
tests/security/mariadb/mariadb_ssl_server.pm
tests/security/postgresql_ssl/postgresql_ssl_client.pm
tests/security/postgresql_ssl/postgresql_ssl_server.pm

NETDEV is referring to the if name on the hypervisor (which is vlan2114 in this case) it would
be best for the test to grab it from the SUT directly.
- Related ticket: [poo#137711](https://progress.opensuse.org/issues/137711)
- Verification run: https://openqa.suse.de/tests/overview?distri=sle&version=15-SP4&build=jknphy%2Fos-autoinst-distri-opensuse%23netdev

Get NETDEV from the SUT in certain s390x scenarios

---

lib/main_micro_alp.pm
tests/installation/configure_sdboot.pm

If BOOTLOADER is set to systemd-boot, this module is scheduled and selects
systemd-boot instead of GRUB2 during installation with YaST.
The module code was based on installation/disable_grub_timeout.
- Needles: https://github.com/os-autoinst/os-autoinst-needles-opensuse/pull/802
- Verification runs: http://10.168.4.192/tests/1383 (textmode) http://10.168.4.192/tests/1381 (graphical)
They fail because of dep issues (hopefully) fixed by https://build.opensuse.org/request/show/1118843

Add installation/configure_sdboot module to select systemd-boot

---

data/sles4sap/qe_sap_deployment/qesap_aws_fencing.yaml
data/sles4sap/qe_sap_deployment/qesap_gcp_fencing.yaml
tests/sles4sap/qesapdeployment/configure.pm

Add AWS and CGP config.yaml with terraform vars to control fencing and not using `-e use_sbd=false`.
Add QESAPDEPLOY_FENCING setting to control the config.yaml content.
- sle-15-SP5-Qesap-Azure-Byos-x86_64-BuildLATEST_AZURE_SLE15_5_BYOS-qesap_azure_saptune_test@64bit -> http://openqaworker15.qa.suse.cz/tests/250528 :green_circle: job failure is the same of cloned job, generated conf.yaml is fine.
this VR does not use any new .yaml file from this PR. It is mostly to check that change in `tests/sles4sap/qesapdeploy/configure.pm` does not interfere with existing jobs
Triggered with:
- `QESAP_CONFIG_FILE=qesap_aws_fencing.yaml` the new conf.yaml file
- `QESAPDEPLOY_FENCING='native'` the new setting
- sle-15-SP5-Qesap-Aws-Byos-x86_64-BuildLATEST_AWS_SLE15_5_BYOS-qesap_aws_saptune_test@64bit -> …

Add qesap regression fencing controllable config.

---

lib/qesapdeployment.pm
t/09_qesapdeployment.t

Fix logic of qesap_file_find_string about grep exit code in case of match.
Related to bug in https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/17903
- Related ticket: [TEAM-8593](https://jira.suse.com/browse/TEAM-8593)
All VR with a simulated failure use https://github.com/SUSE/qe-sap-deployment/pull/184
http://openqaworker15.qa.suse.cz/tests/248633 No qesap.py failure [this code version](https://github.com/os-autoinst/os-autoinst-distri-opensuse/compare/65487c871b4991e98744a600198f05fcd21b47aa..e18e95e16aacf92edcb0c3ef9ae7550830f697d5)
- sle-15-SP5-Qesap-Azure-Byos-x86_64-BuildLATEST_AZURE_SLE15_5_BYOS-qesap_azure_saptune_test@64bit -> http://openqaworker15.qa.suse.cz/tests/248684
Timeout error properly detected in the Ansible log …

Fix qesap log grep

---

tests/sles4sap/publiccloud/hana_sr_schedule_deployment.pm

Adds the old peering cleanup module to the rest of the IBSM jobs on OSD.
- Related ticket: https://jira.suse.com/browse/TEAM-8671
https://openqa.suse.de/tests/12572929
https://openqa.suse.de/tests/12572949
(failures unrelated to new module)

Add peering clean to peering jobs

---

tests/autoyast/installation.pm

This part is not needed and will cause timing issue for autoyast installation.
- Failed job: https://openqa.suse.de/tests/12568901#
- Needles: N/A
- Verification run: https://openqa.nue.suse.com/tests/12574240#step/svirt_upload_assets/8

Remove check_screen for nvidia in autoyast installation

---

data/sssd-tests/krb/slapd.conf
data/sssd-tests/krb/slapd_old.conf
data/sssd-tests/ldap-nested-groups/slapd.conf
data/sssd-tests/ldap-no-auth/slapd.conf
data/sssd-tests/ldap/slapd.conf
data/sssd/openldap/slapd.conf
tests/console/sssd_openldap_functional.pm

The hdb backend was disabled when openldap was updated to 2.5.8 in Tumbleweed.
Signed-off-by: Samuel Cabrero <scabrero@suse.de>
- Related ticket: https://bugzilla.suse.com/show_bug.cgi?id=1205160

sssd: Switch to mdb openldap backend

---

data/sles4sap/qe_sap_deployment/qesap_aws.yaml
data/sles4sap/qe_sap_deployment/qesap_aws_sapconf.yaml
data/sles4sap/qe_sap_deployment/qesap_gcp.yaml
data/sles4sap/qe_sap_deployment/qesap_gcp_sapconf.yaml

The `use_sbd`  configured in the inventory
This PR is for qesap regression only
This PR depend on https://github.com/SUSE/qe-sap-deployment/pull/181 and maybe some jobs needs the first `qe-sap-deployment` release with it (will be 0.17.0)
[TEAM-8672](https://jira.suse.com/browse/TEAM-8672)
- sle-15-SP5-Qesap-Azure-Byos-x86_64-BuildLATEST_AZURE_SLE15_5_BYOS-qesap_azure_ansible_roles_test@64bit -> http://openqaworker15.qa.suse.cz/tests/246959
- sle-15-SP5-Qesap-Gcp-Byos-x86_64-BuildLATEST_GCE_SLE15_5_BYOS-qesap_gcp_sapconf_test@64bit -> http://openqaworker15.qa.suse.cz/tests/246960
- sle-15-SP5-Qesap-Aws-Byos-x86_64-BuildLATEST_AWS_SLE15_5_BYOS-qesap_aws_saptune_test@64bit -> http://openqaworker15.qa.suse.cz/tests/246961
- `qesap_aws.yaml` Native fencing : …

Remove use_sbd configuration from the playbook commandline

---

lib/containers/common.pm

- Related ticket: https://progress.opensuse.org/issues/138260 https://progress.opensuse.org/issues/138296
https://openqa.suse.de/tests/12597969 EC2 x86_64
https://openqa.suse.de/tests/12597973 EC2 aarch64
https://openqa.suse.de/tests/12597972 SLE micro

Disable ipv6 only on SLE Micro

---

tests/containers/bci_test.pm

BCI test run 2 or more steps of tox runs that, when fail, report in the webgui `no fail` and only in a final collecting phase all failed steps as enumerated in a single one only failure box. So on the web report it is not easy to identify the previous failed step.
Scope of this PR is to change from _softfailed_ to **failed** the report box of a **tox failed step**, more evident and helpful in debugging analysis.
- Verification runs of code updated:
- http://mdati-openqa.qe.suse.de/tests/665
- clone of https://openqa.suse.de/tests/12570974
- failed step VR
- 
- http://mdati-openqa.qe.suse.de/tests/665#step/bci_test_docker/33
- http://mdati-openqa.qe.suse.de/tests/665#step/bci_test_docker/40
- failed step cloned
- https://openqa.suse.de/tests/12570974#step/bci_test_docker/33
- …

BCI tests failed-steps status changed from softfail to fail.

---

data/console/rsyncd.conf
data/lib/tomcat/tomcat-users.xml
data/security/tpm2/emulator.conf
lib/Tomcat/Utils.pm
tests/console/rsync_server.pm
tests/security/apparmor/aa_easyprof.pm
tests/security/tpm2/tpm2_env_setup.pm

Move test config files into the data directory to avoid running multiline commands with `script_run` just to create a static text file.
- Needles: N/A
- aa_easyprof: https://openqa.opensuse.org/tests/3528949
- rsync_server: https://openqa.opensuse.org/tests/3528950
- tomcat: https://openqa.opensuse.org/tests/3528952
- tpm2_env_setup: https://openqa.opensuse.org/tests/3528953

Fix multiline commands in aa_easyprof, rsync_server, tomcat and tpm2_env_setup

---

tests/security/apparmor/aa_autodep.pm
tests/security/apparmor/aa_logprof.pm

This is needed because the cache file has a newer timestamp than the
profile in /etc/apparmor.d/. Otherwise the next relaod (in
lib/apparmortest.pm pre_run_hook()) would load the cached /usr/sbin/nscd
profile as created by aa-autodep.
The shipped profile that gets loaded (and is expected to be used) in the
aa-logprof test is named 'nscd' (without the path), therefore it won't
replace the /usr/sbin/nscd profile when it gets loaded.
The final result was that nscd was running under the wrong profile
(/usr/sbin/nscd from the cache), and therefore didn't create any log
entries for the 'nscd' profile.
With this fixed, we can also remove the workaround that was added to
cover this test bug in Tumbleweed for the last two years.
Note: I intentionally left some aa-status calls in the tests. They …

Cleanup cache after unloading /usr/sbin/nscd profile

---

schedule/migration/migration_offline_media_all_patterns_x86_64.yaml
schedule/migration/migration_offline_media_x86_64.yaml
schedule/migration/migration_offline_scc_all_patterns_x86_64.yaml
schedule/migration/migration_offline_scc_x86_64.yaml
tests/migration/reboot_to_migration.pm

- Description:
* Create test modules for reboot_before_migration and stop_grub_timeout.
- Related ticket: https://progress.opensuse.org/issues/132950
- Needles: N/A
* https://openqa.suse.de/tests/12615294
* https://openqa.suse.de/tests/12615295
* https://openqa.suse.de/tests/12615296
* https://openqa.suse.de/tests/12615297

Create test modules for reboot_before_migration  and stop_grub_timeout

---

tests/installation/configure_sdboot.pm

Otherwise it tries to start the installation before it's been recalculated.
Failure: https://openqa.opensuse.org/tests/3662819#step/start_install/3
VRS:
https://openqa.opensuse.org/tests/3667342
https://openqa.opensuse.org/tests/3667343
https://openqa.opensuse.org/tests/3667344

installation/configure_sdboot: Really make sure the inst overview loaded

---

tests/containers/bci_prepare.pm

Install the required packages also for HELM test runs.
- Related ticket: https://progress.opensuse.org/issues/138212
- Verification run: [12-SP5](https://duck-norris.qe.suse.de/tests/14257) | [15-SP1](https://duck-norris.qe.suse.de/tests/14258#step/bci_prepare/32) (unrelated failure) | [15-SP2](https://duck-norris.qe.suse.de/tests/14261#step/bci_prepare/32) | [CentOS](https://duck-norris.qe.suse.de/tests/14262)

Install packages also on HELM test runs

---

data/virt_autotest/host_unattended_installation_files/autoyast/dev_host_12.xml.ep

* **Remove** useless dns setting in autoyast profile for sles12, because incorrect ip address of bridge issue is fixed by pr#18011 and the dns becomes unavailable after machine relocation.
* [12sp5 kvm host](https://openqa.suse.de/tests/12633068)
* [12sp5 xen host](https://openqa.suse.de/tests/12633093)

Remove useless dns setting in autoyast

---

tests/fips/openssh/openssh_fips.pm

This softfail was instroduced because of outdated `openssh` on 15-SP3. See more at <https://jira.suse.com/browse/SLE-16308>. 15-SP3 now has `openssh` on version `8.4p1`.
- Related ticket: https://progress.opensuse.org/issues/133076
- Verification run: https://openqa.suse.de/tests/12635486

Remove obsolete softfail for openssh

---

lib/bootloader_setup.pm
lib/utils.pm
tests/kernel/update_kernel.pm

- Related ticket: https://progress.opensuse.org/issues/138182
sle:   https://openqa.suse.de/tests/12628830
Verification for incorrect product: http://black-bit.suse.cz/tests/185#step/update_kernel/132
Verification for patch not needed: http://black-bit.suse.cz/tests/187#step/update_kernel/122
Patch verification: http://black-bit.suse.cz/tests/186

kernel: Add support for transactional systems to update_kernel module

---

tests/containers/privileged_mode.pm

`/dev/bus/` is missing in Xen PV VMs as we do not create VMs with usb passthrough.
- ticket: https://progress.opensuse.org/issues/135518
- Verification run: http://kepler.suse.cz/tests/22040#step/docker_privileged_mode/41

Xen PV VMs are without usb

---

lib/main_containers.pm
tests/containers/suma_containers.pm

Implement basic openQA testing for SUMA container images using podman, based on the rancher container test.
The test  covers:
- Pull the image from internal  registry.suse.de test registry
- Executes a simple command within the container to test that it at least runs
The test is meant for  the following SUMA container images:
- proxy-httpd-image
- proxy-salt-broker-image
- proxy-squid-image
- proxy-ssh-image
- proxy-tftpd-image
- proxy-helm charts
Additional info:
- Based on work done on Draft PR #17425
- Related ticket: https://progress.opensuse.org/issues/132692

Add basic openQA test file for SUMA containers

---

lib/main_common.pm

`openldap2` was deprecated as of SLE-15-SP4, `389ds` is the supported alternative.
Limiting the test execution to run only until SLE-SP3.
- Deprecation Announced in SP2 [0].
- Announced Removal in SP4 [1].
For the still valid products, this will support #16176 to run properly.
`389ds` functional tests are equivalent enough to the test that will be disabled in >=SP4.
Addresses poo#120028 [2].
[0]: https://www.suse.com/releasenotes/x86_64/SUSE-SLES/15-SP2/index.html#jsc-SLE-16552
[1]: https://www.suse.com/releasenotes/x86_64/SUSE-SLES/15-SP4/index.html
[2]: https://progress.opensuse.org/issues/120028
- Related ticket: https://progress.opensuse.org/issues/120028
- Verification run:  TBD ~openqa.mypersonalinstance.de/tests/xyz#step/module/x~

Deprecating openldap2 test in favor of `389ds` functional tests

---

lib/susedistribution.pm

- Related ticket: https://openqa.suse.de/tests/12626798#step/bootloader_svirt/4
- Verification run: https://openqa.suse.de/tests/12627204

svirt: Assert text-logged-in-root after password

---

Makefile

This is a follow up to os-autoinst/os-autoinst#2396

Remove unsused absolutize

---

lib/hacluster.pm

Fix SAPHanaSR_ScaleUp_PerfOpt_node01 command "crm_mon" failure: "no inactive resources" failure
TEAM-8696 - [SAPHanaSR_ScaleUp_PerfOpt_node01] test module "sap_suse_cluster_connector" failed on: command 'crm_mon -R -r -n -N -1 | grep -i 'no inactive resources''
- Related ticket: https://jira.suse.com/browse/TEAM-8696
- Needles: NA
- Verification run (tried 2 times all passed):
https://openqa.suse.de/tests/12633869#step/sap_suse_cluster_connector/234 (passed)
https://openqa.suse.de/tests/12633872#step/sap_suse_cluster_connector/237 (passed)

Fix hanaSR crm_mon "no inactive resources" failure

---

tests/security/atsec/dbus_services_exposure.pm

- Related ticket: https://progress.opensuse.org/issues/137699
- VRs: https://openqa.suse.de/tests/overview?distri=sle&version=15-SP6&build=26.1&groupid=431

dbus_services_exposure: whitelist virtqemud on 15-SP6+

---

tests/console/cryptsetup.pm

This softfail was introduced untill `cryptsetup` is updated to version `>=2.4.0` on 15-SP4. It is now on version `2.4.3`.
https://jira.suse.com/browse/SLE-20275
- Related ticket: https://progress.opensuse.org/issues/138413
- Verification run: https://openqa.suse.de/tests/12659990#step/cryptsetup/15

Remove obsolete softfail for cryptsetup

---

schedule/yam/agama/agama_installation.yaml

The name was removed by 97c613a132377909d480bbc18187569b39206bc6 without further explanation. It is likely a mistake because it causes the YAML validation to fail (technically it still succeeds despite the error but that is another problem):
```
$ make test-yaml-valid
tools/check_yaml
not ok 1694 - schedule/yam/agama/agama_installation.yaml has invalid schema
1..2833
check_yaml SUCCESS
```

Add back name in `agama_installation.yaml`

---

lib/main_common.pm
schedule/kernel/bpftools.yaml
schedule/kernel/io_uring.yaml

These tests modules are so far scheduled as kernal extra tests (on OSD via the test suites `extra_tests_kernel` and `extra_tests_kernel_spvm`). This change moves them to YAML schedule files so the can be scheduled via their own test suites (`io_uring` and `bpftrace` on OSD).
Related ticket: https://progress.opensuse.org/issues/138407

Split io_uring and bpftrace tests from kernel extra tests

---

Makefile
lib/YuiRestClient/Widget/Tree.pm
lib/hacluster.pm
lib/qesapdeployment.pm
lib/trento.pm
lib/version_utils.pm
tools/check_pod_errors

Run perldoc and check for error in the documentation format. 
Add a make target about it.
Fix some documentation error.
Related ticket: https://progress.opensuse.org/issues/138521
This check is about spotting error otherwise visible in the official documentation: have a look at the end of https://os-autoinst.github.io/os-autoinst-distri-opensuse/qesapdeployment.html
Time for the target execution (on my laptop)
```
% time make test_pod_errors
tools/check_pod_errors
POD ERROR CHECK SUCCESS
make test_pod_errors  26.29s user 6.74s system 99% cpu 33.079 total
```
The overall script works like:
1. get a list of `.pm` files in the `lib/` folder using `git ls-files lib/` 
2. for each file run `perldoc -T -D "${libfile}"`
In case of no issue it print out the documentation on the stdout
``` …
```

Add target to check documentation errors

---

tests/shutdown/svirt_upload_assets.pm

- Related ticket: https://progress.opensuse.org/issues/138524
- Verification run: IMO VR is not required just for timeout increase, and workers are busy

Increase timeout for s390x qcow2 convert & upload

---

data/virt_autotest/host_unattended_installation_files/autoyast/dev_host_12.xml.ep

* **Configuration** error: uninitialized interface can be seen during sles12sp5 host autoyast installation, please see [here](https://openqa.suse.de/tests/12561583#step/installation/6).
* **The** error has nothing to do with any inactive or down interfaces. On the contrary, error reported on available interface.
* **By** the way, although automation tells "Error detected during first stage of the installation", this is an error reported during second stage of autoyast installation actually.
* **Disable** auto-install second stage for sles12sp5 host installation to avoid configuration error of uninitialized interface can be seen during configuring lan in second stage.
* **Experiment** shows that disabling second stage will get rid of this error with gonzo machine, because all three …

Disable auto-install second stage for sles12 host installation

---

lib/filesystem_utils.pm
tests/xfstests/generate_report.pm
tests/xfstests/run.pm
tests/xfstests/xfstests_failed.pm

During review QAM and o3 results may need to set test fail to softfail. Add a new parameter XFSTESTS_SOFTFAIL to do so. When any tests fail, first check whether it is in this softfail list, if so change the result from fail to softfail.
Also, I did some refactoring work to avoid the CI checking error "Code structure is deeply nested".
- Related ticket: https://progress.opensuse.org/issues/137732
- Verification run: http://10.67.133.133/tests/356
- VR description: I set XFSTESTS_SOFTFAIL=generic/686 in this verify run. Previous tests are failing in this generic/686 test. The verify run should mark softfail in generic/686. Because the code change involve include/exclude group feature I test it in following test and works fine http://10.67.133.133/tests/361 (xfs/270 is in 'mount' group and …

xfstests: Add softfail control feature

---

tests/containers/privileged_mode.pm

If proxy scc is used and the container is based on different version of
SLE the repo URLs inside of container are invalid.
HyperV does not has `/dev/bus` as xen pv.
* [15-SP4](http://kepler.suse.cz/tests/22102#step/docker_privileged_mode/92)
* [15-SP6](http://kepler.suse.cz/tests/22101#step/podman_privileged_mode/65)
* [TW](http://kepler.suse.cz/tests/22103#)

Scope package installation in container

---

lib/windowsbasetest.pm

When powershell opens in win11, the Startup menu shows up breaking previous needle logic. Introduced code in windowsbasetest.pm to account for this.
- Related ticket: https://progress.opensuse.org/issues/137471
- Needles: https://github.com/os-autoinst/os-autoinst-needles-opensuse/blob/master/powershell-with-startup-menu-20231009.png
- Verification run: https://openqa.suse.de/tests/12551885#step/update_windows/5

Fixed powershell startup menu popup

---

tests/console/gpg.pm

More details in https://bugzilla.suse.com/show_bug.cgi?id=1216347#c1 -ticket: https://progress.opensuse.org/issues/138677
* [microos](http://kepler.suse.cz/tests/22119#step/gpg/9)
* [15sp5](http://kepler.suse.cz/tests/22118#step/gpg/10)
* [15sp6](http://kepler.suse.cz/tests/22117#step/gpg/7)

libgcrypt2-hmac is deprecated in sle15sp6

---

tests/virtualization/yast_virtualization.pm

**Fix test failures in yast_virtualization for modular libvirt**
- Description:
This Pull Request addresses the test failures in the yast_virtualization module for the modular libvirt setup. The main goal is to make the tests green again.
Reuse the modular libvirt in virt_autotest::utils.pm and restart the modular libvirt. Some daemons are started by default but some daemons are required to be started manually.
- Related ticket: https://progress.opensuse.org/issues/133862
https://openqa.opensuse.org/tests/3675096 
https://openqa.opensuse.org/tests/3677738
https://openqa.opensuse.org/tests/3677786
- Latest runs:
https://openqa.opensuse.org/tests/3678860#step/yast_virtualization/61
https://openqa.opensuse.org/tests/3678868
https://openqa.opensuse.org/tests/3679617#

Fix Tumbleweed virtualization test for modular libvirt

---

.github/workflows/commit-message-checker.yml
CONTRIBUTING.md

- DRY github workflows, commit checks are now used here but defined in os-autoinst-common.
- Related ticket: https://progress.opensuse.org/issues/138416
- Needles: not applicable
- Verification run: not applicable

Use commit message checks from os-autoinst-common

---

tests/containers/privileged_mode.pm

Same situation as for other hypervisors except of QEMU or Xen-HVM.
* [podman](https://openqa.suse.de/tests/12715958#step/podman_privileged_mode/20)
* [docker](https://openqa.suse.de/tests/12716040#)

Folder '/dev/bus' is not present in vmware either

---

lib/qesapdeployment.pm
t/15_qesap_azure.t
tests/sles4sap/publiccloud/qesap_terraform.pm
tests/sles4sap/qesapdeployment/configure.pm

Create new lib function to create token for storage container. Allow to set permission and duration.
No more secrets to be transmitted using job settings
It does not take care about double % issue yet
- Related ticket: [TEAM-8713](https://jira.suse.com/browse/TEAM-8713)
- sle-15-SP5-Qesap-Azure-Byos-x86_64-BuildLATEST_AZURE_SLE15_5_BYOS-qesap_azure_ansible_roles_test@64bit -> http://openqaworker15.qa.suse.cz/tests/257072 :green_circle:  failure is a known issue far after the Hana installation 
- sle-15-SP5-Qesap-Aws-Byos-x86_64-BuildLATEST_AWS_SLE15_5_BYOS-qesap_aws_fullypatch@64bit -> http://openqaworker15.qa.suse.cz/tests/257074 :green_circle:
- sle-15-SP4-HanaSr-Azure-Byos-x86_64-Build15-SP4_2023-10-27T04:03:08Z-hanasr_azure_test_saptune@64bit -> …

New qesap lib to create SAS Token

---

tests/console/year_2038_detection.pm

On TW/ALP/etc. this is a proper failure.
https://openqa.opensuse.org/tests/3677459 (TW MicroOS)
Apparently it's not scheduled for Leap? Feel free to do VRs for SLE.
Depends on #18084

console/year_2038_detection.pm: Only treat as softfail on SLE <= 15 and make syncing more reliable

---

schedule/qam/15-SP2/qam-sles4sap_wmp_hana_node1.yaml
schedule/qam/15-SP2/qam-sles4sap_wmp_hana_node2.yaml
schedule/qam/15-SP3/qam-sles4sap_wmp_hana_node1.yaml
schedule/qam/15-SP3/qam-sles4sap_wmp_hana_node2.yaml
schedule/qam/15-SP4/qam-sles4sap_wmp_hana_node1.yaml
schedule/qam/15-SP4/qam-sles4sap_wmp_hana_node2.yaml
schedule/qam/15-SP5/qam-sles4sap_wmp_hana_node1.yaml
schedule/qam/15-SP5/qam-sles4sap_wmp_hana_node2.yaml

Commit 98e884f337a553dd8c36d07eb238ed6b44341a2d forces HANA nodes to run on the serial terminal by removing the VIRTIO_CONSOLE=0 setting from the schedules, but the aggregates schedules are located in a different directory so they were not updated as part of that commit. This commit fixes this.
- Related ticket: https://jira.suse.com/browse/TEAM-8684 & https://progress.opensuse.org/issues/138113
- Needles: N/A

Run HANA nodes on QEMU with VIRTIO_CONSOLE=1 on QAM/Aggregates

---

tests/installation/partitioning.pm

We often got create partition issue since kernel 6.x. it's due to system menu cannot response in time. Thus use type_string_slow instead of type_string to avoid fails.
- Related ticket: https://progress.opensuse.org/issues/138737
- Needles: N/A
- Verification run: http://10.67.129.54/tests/864

installation: avoid partitioning issue

---

tests/virt_autotest/login_console.pm

* **Grub2** menu matching may fail after offline upgrade. Please refer to [the failure](https://openqa.suse.de/tests/12659119#step/reboot_and_wait_up_upgrade/48).
* **The** failure can be mitigated by rebooting SUT machine one more time.
* [offline upgrade kvm](https://openqa.suse.de/tests/12715291)
* [offline upgrade xen](https://openqa.suse.de/tests/12715292)
* [rebooting sut after offline upgrade fixes grub2 needle matching issue](https://openqa.suse.de/tests/12715703)

Another reboot to match grub2 menu after offline upgrade

---

lib/trento.pm
tests/sles4sap/publiccloud/qesap_terraform.pm
tests/sles4sap/qesapdeployment/configure.pm
variables.md

Add token generation in Trento too.
Fix qesap regression token generation condition.
Remove all TOKEN settings.
Fix some setting documentation.
Related ticket: [TEAM-8713](https://jira.suse.com/browse/TEAM-8713)
- sle-15-SP5-Qesap-Gcp-Payg-x86_64-BuildLATEST_GCE_SLE15_5_PAYG-qesap_gcp_sapconf_test@64bit -> http://openqaworker15.qa.suse.cz/tests/258104  :green_apple: Ansible download media is ok
- sle-15-SP5-Qesap-Azure-Byos-x86_64-BuildLATEST_AZURE_SLE15_5_BYOS-qesap_azure_ansible_roles_test@64bit -> http://openqaworker15.qa.suse.cz/tests/258108  :green_apple: Ansible download media is ok
- sle-15-SP3-HanaSr-Azure-Byos-x86_64-Build15-SP3_2023-10-30T12:54:21Z-hanasr_azure_test@64bit -> http://openqaworker15.qa.suse.cz/tests/258109
- …

SAS URI token generation for Trento

---

tests/virt_autotest/virt_utils.pm

Refer to the following Error info during :
```
command 'nice ionice qemu-img convert -c -p -O qcow2 /var/lib/libvirt/images/sles-15-sp5-64-fv-def-net.qcow2 guest_sles-15-sp5-64-fv-def-net_on-host_sle-15-SP6_build28.1_xen_x86_64.disk' timed out at /usr/lib/os-autoinst/testapi.pm line 985.
testapi::script_run("nice ionice qemu-img convert -c -p -O qcow2 /var/lib/libvirt/"..., 360) called at sle/tests/virt_autotest/virt_utils.pm line 336
```
Timeout to compressing both 12sp5 and 15sp5 guest disk file on 15sp6 xen domain0. So, setup TIMEOUT both KVM and XEN to fix up compressing guest disk file timeout problem.  
- Related ticket: https://progress.opensuse.org/issues/138575
[gi-guest_sles12sp5-on-host_developing-xen](https://openqa.suse.de/tests/12744879#) …

virt_autotest: fix up compressing guest disk file timeout

---

tests/virtualization/universal/hotplugging_network_interfaces.pm

A soft-failure warning message was issued when a network interface is hotpluged on a guest vm which is hosted on xen host.
The corresponding bug https://bugzilla.suse.com/show_bug.cgi?id=1168124 is now resolved.
- Related ticket : https://progress.opensuse.org/issues/138443
- Needles: No corresponding needles.
- Verification run: http://openqa.qam.suse.cz/tests/62719#

Removed softfailure message for hotplugged nic of guest hosted on xen

---

tests/console/ca_certificates_mozilla.pm

With the latest infrastructure changes, the website `https://static.opensuse.org` requires explicit "servername" parameter when invoked from an older openSSL client. 
- Related ticket: https://progress.opensuse.org/issues/138998
- https://openqa.suse.de/tests/12753795
- https://openqa.suse.de/tests/12753796
- https://openqa.suse.de/tests/12753797
- https://openqa.suse.de/tests/12753798
- https://openqa.suse.de/tests/12753799
- https://openqa.suse.de/tests/12753800
- https://openqa.suse.de/tests/12753801
- https://openqa.suse.de/tests/12753802
- https://openqa.suse.de/tests/12753803
- https://openqa.suse.de/tests/12753805
- https://openqa.suse.de/tests/12753807
- https://openqa.suse.de/tests/12753810

Explicit servername in ca-certificates test

---

tests/wicked/before_test.pm

The `/etc/systemd/journald.conf` doesn't exists on latest Tumbleweed. As it is moved to `/usr/...`.
Use drop-in mechanism to write our journal configuration.
Error's: 
- http://openqa.wicked.suse.de/tests/170674#step/before_test/20
- https://openqa.opensuse.org/tests/3696259#step/before_test/20
fixed: 
- http://openqa.wicked.suse.de/tests/170885#step/before_test/20

wicked: configure journald via drop-in

---

lib/wickedbase.pm

This project is configured to build the container for different architectures. 
- https://build.opensuse.org/project/show/home:cfconrad:openqa
- https://progress.opensuse.org/issues/137852
- https://registry.opensuse.org/cgi-bin/cooverview?srch_term=container%3Dhome%2Fcfconrad%2Fopenqa%2Fcontainers%2Fscapy+

wicked: use scapy container from different project

---

data/wicked/ifreload-3.sh

`brctl` from `bridge-utils` isn't installed by default.

wicked: cleanup ifreload-3.sh

---

data/autoyast_sle15/hpc/create_hdd_textmode_aarch64.xml.ep
data/autoyast_sle15/hpc/create_hdd_textmode_x86_64.xml.ep

Modify profile and enable sle-module-python3 in the Autoyast profile
to perform installation of the module on 15-SP6.
- Related ticket: https://progress.opensuse.org/issues/134195
https://openqa.suse.de/tests/overview?version=12-SP5&distri=sle&build=b10n1k%2Fos-autoinst-distri-opensuse%2318116
https://openqa.suse.de/tests/overview?distri=sle&build=b10n1k%2Fos-autoinst-distri-opensuse%2318116&version=15-SP6
https://openqa.suse.de/tests/overview?build=b10n1k%2Fos-autoinst-distri-opensuse%2318116&distri=sle&version=15-SP2

Enable sle-module-python3 installation on 15-SP6

---

tests/console/zypper_lifecycle_toolchain.pm

Package can have any status except retracted, I was not able to make it work with awk, works with grep
- Related ticket: https://progress.opensuse.org/issues/139037
- Verification run: https://openqa.suse.de/tests/12762593

zypper_lifecycle_toolchain: Use pipe as field separator

---

lib/publiccloud/utils.pm

In order to install google could cli, we need to use python3.8 and newer
- ticket: https://progress.opensuse.org/issues/138548
* [15sp3](http://kepler.suse.cz/tests/22200#live)
* [15sp4](http://kepler.suse.cz/tests/22199#step/helm_GCE/48)
* [15sp5](http://kepler.suse.cz/tests/22198#step/helm_GCE/55)

Python 3.6.x is no longer officially supported by the Google Cloud CLI

---

data/python/bs4/python3-beautifulsoup4-test.py
data/python/bs4/testpage.html
lib/python_version_utils.pm
schedule/qam/common/mau-extratests1.yaml
tests/console/python3_beautifulsoup4.pm

- Related ticket: https://progress.opensuse.org/issues/138095
- Needles: NO
- https://openqa.suse.de/tests/12762519
- https://openqa.suse.de/tests/12762520
- https://openqa.suse.de/tests/12762607
- https://openqa.suse.de/tests/12762608
- https://openqa.suse.de/tests/12762609
- https://openqa.suse.de/tests/12762610

Introduce a new test for python-beautifulsoup4

---

lib/Mitigation.pm
lib/main_common.pm
tests/cpu_bugs/kvm_guest_mitigations.pm

Remove the ipmi_to_qemu from kvm guest mitigation test.
- Related ticket:  https://progress.opensuse.org/issues/127796
- Verification run: skylake(15sp6), icelake(15sp5),cascadelake(15sp5)
http://10.67.129.4/tests/60927
http://10.67.129.4/tests/60928
http://10.67.129.4/tests/61045
http://10.67.129.4/tests/61044
http://10.67.129.4/tests/61137
http://10.67.129.4/tests/61138#
http://10.67.129.4/tests/61138#step/mitigations/11

Remove ipmi_to_qemu for guest mitigation test

---

tests/console/mutt.pm

This commit fixes the new screen in the mutt test with a SSL certificate check. I have only tested this with the mutt in Tumbleweed. 
- Related ticket: https://progress.opensuse.org/issues/138194
- Verification run: https://openqa.opensuse.org/tests/3700669

fix test fails in mutt - New screen "SSL Certificate Check"

---

data/autoyast_sle15/hpc/create_hdd_textmode_x86_64.xml.ep

xmllint doesnt validate the profile with <kdump>.
The entry is no needed anyway for the HPC installation.
https://aquarius.suse.cz/tests/19802

Remove kdump section from hpc autoyast profile

---

lib/virt_autotest/utils.pm

- Related ticket: https://progress.opensuse.org/issues/137876
[gi-guest_developing-on-host_developing-kvm](http://openqa.suse.de/tests/12785888#) PASS
[gi-guest_developing-on-host_sles15sp5-kvm](http://openqa.suse.de/tests/12785889#) PASS
[gi-guest_developing-on-host_sles12sp5-kvm](http://openqa.suse.de/tests/12785893#) FAIL by bsc#1205880
[gi-guest_developing-on-host_developing-xen](http://openqa.suse.de/tests/12785891#) FAIL by bsc#1216587

virt_autotest: enhancement for modular libvirt daemons

---

tests/containers/volumes.pm

Dockerfile in volumes.pm was missing full path to busybox container used for the test. To avoid the ambiguity of source, always use container from registy.opensuse.org.
```
STEP 1/2: FROM busybox
Please select an image:
registry.opensuse.org/busybox:latest
registry.suse.com/busybox:latest
docker.io/library/busybox:latest
```
- ticket: https://progress.opensuse.org/issues/150806
- Verification run: http://kepler.suse.cz/tests/22207#step/volumes_podman/17

Specify registry url for busybox

---

data/autoyast_sle15/mini_s390x.xml

'openssh' is not installed by default on sle15sp6 with minimal role
during autoyast installation, so add it to make sure ssh can work on s390x platform which needs ssh access
- Verification run: [s390x-mimi-ay](https://openqa.suse.de/tests/12809351#details)

Add openssh to autoyast package list on s390x

---

tests/installation/system_role.pm

There are focus issue on aarch64 on TW, which cause we can't click the gnome role to select it. So send tab and hot keys to recover the focus to fix this issue.
- Related ticket: https://progress.opensuse.org/issues/138041
- Needles: N/A
- Verification run: https://openqa.opensuse.org/tests/3693563#step/system_role/8
avoid regression on x86_64: https://openqa.opensuse.org/tests/3678463#step/system_role/4

Fix system-role issue on aarch64 on TW

---

data/virt_autotest/host_unattended_installation_files/autoyast/dev_host_12.xml.ep

* **Parameter** ```bridge_forwarddelay``` can not be zero. Set it to 15 which is the most common value being used for bridge settings.
* **Parameter** ```bridge_stp``` is better given "on" for bridge settings.
* [sles12sp5 installation with second stage passed](https://openqa.suse.de/tests/12788993)
* [sles12sp5 installation with second stage failed]()
* [sles12sp5 installation without second stage](https://openqa.suse.de/tests/12788992)

Correct bridge config in sles12 autoyast

---

tests/sles4sap/publiccloud/hana_sr_schedule_deployment.pm

Remove test module `general_patch_and_reboot`.
Test module `general_patch_and_reboot` is duplicated as test module `deploy_qesap_ansible` also does the `patch` and `reboot` stuff.
TEAM-8741 - [BYOS]BYOS images are registered before any patching is run
- Related ticket: https://jira.suse.com/browse/TEAM-8741
- Needles: NA
- Verification run: https://openqa.suse.de/tests/12815589# (passed)

Registered BYOS images before any patching is run

---

lib/qesapdeployment.pm
t/09_qesapdeployment.t

Optionally add call to ansible-galaxy if requirements.yml is present, so if new qe-sap-deployment version is used.
This PR can be merged at any time without any change in the qe-sap-deplyoment, but it is a preparation for https://github.com/SUSE/qe-sap-deployment/pull/189
http://openqaworker15.qa.suse.cz/tests/266525 :green_circle: 
http://openqaworker15.qa.suse.cz/tests/266522 :green_circle:

Add ansible-galaxy install to qesap regression

---

tests/microos/selfinstall.pm

There is no reboot after `dd`-ing the raw image into drive. This behavior is the same as we can see in MicroOS.
* [slem 6.0](http://kepler.suse.cz/tests/22212#step/selfinstall/5)
* [slem 5.5](http://kepler.suse.cz/tests/22213#step/selfinstall/7)

Align Micro 6.0 with MicroOS

---

tests/xfstests/partition.pm

Add XFSTESTS_BIG_SPACE option for btrfs testing.(Only effect on loop device since other devices practically obsolete for xfstests)
As btrfs needs 6 partitions for raid or some specific testing, it's got no space error occasionally compared to other fs. But we cannot use a huge size disk simply as following reasons:
1. only a few tests need a huge size disk (more than 100G)
2. some tests take a long time on big partition
3. most of tests just use 1 or 2 partitions
4. several tests require devices have the same size
Therefore a flexible partition policy is needed.
1. all devices share entire free space equally at default
2. for btrfs, if free space more than 38G: 15G each for test_dev and scratch_dev1, other devices share the rest …

xfstests: Add option to allocate more disk space

---

tests/security/apparmor/aa_autodep.pm
tests/security/apparmor/aa_genprof.pm
tests/security/apparmor/aa_notify.pm

Ticket: https://progress.opensuse.org/issues/139049
VRs:
- 15-SP4: https://openqa.suse.de/tests/12816985
- TW: https://openqa.opensuse.org/tests/3728139
- `aa_notify` expected to fail due to https://bugzilla.opensuse.org/show_bug.cgi?id=1216660

Ensure nscd is installed

---

tests/security/cc/audit_tools.pm

Related ticket: [poo#125039](https://progress.opensuse.org/issues/125039)
Soft-failure should be pointing to bugs in general.

Update soft-failure to bsc#1209910

---

lib/containers/utils.pm
lib/main_common.pm
lib/main_containers.pm
tests/containers/bci_prepare.pm
tests/containers/bci_test.pm
tests/containers/bci_version_check.pm
tests/containers/helm_rmt.pm
tests/containers/host_configuration.pm
tests/containers/suma_containers.pm
tests/publiccloud/slem_prepare.pm
variables.md

We should rename the openQA setting CONTAINER_RUNTIME to CONTAINER_RUNTIMES to indicate, that it might contain multiple runtimes, e.g. docker,podman
- Related ticket: https://progress.opensuse.org/issues/134354
- Needles: *not_needed*
- Verification run: https://openqa.suse.de/tests/12824128
Paired with: https://gitlab.suse.de/qac/qac-openqa-yaml/-/merge_requests/1395

Rename CONTAINER_RUNTIME to CONTAINER_RUNTIMES

---

tests/console/check_network.pm
tests/console/installation_snapshots.pm

- Avoid poo#43889 by switching to serial console
- Switch imports around
VR: [passed with flying colors](https://openqa.suse.de/tests/overview?version=15-SP6&distri=sle&build=os-autoinst%2Fos-autoinst-distri-opensuse%2318141)

Reduce failure probability by switching to serial terminal

---

tests/containers/bci_test.pm

- Related ticket: https://progress.opensuse.org/issues/150980
- Verification runs: https://openqa.suse.de/tests/12835693, https://openqa.suse.de/tests/12835973, https://openqa.suse.de/tests/12835974, https://openqa.suse.de/tests/12836031, https://openqa.suse.de/tests/12836044

Fix the export=CONTAINER_RUNTIME

---

tests/migration/online_migration/pre_migration.pm

for sles15sp3 zypper migration, we don't need to make sure zypper-migration-plugin was install anymore.
- Related ticket: [**138461**](https://progress.opensuse.org/issues/138461)
- Needles: N/A
* https://openqa.suse.de/tests/12849119
* https://openqa.suse.de/tests/12849120
* https://openqa.suse.de/tests/12849144 (zypper)
* https://openqa.suse.de/tests/12849158 (yast)

Skip zypper-migration-plugin for sles15sp3

---

data/virt_autotest/host_unattended_installation_files/autoyast/dev_host_15.xml.ep
lib/virt_autotest/utils.pm
tests/virt_autotest/sriov_network_card_pci_passthrough.pm
tests/virt_autotest/xen_guest_irqbalance.pm

- Continue test even if logging script fail to be downloaded, take this case as example, https://openqa.suse.de/tests/12803055#step/sriov_network_card_pci_passthrough/147. Not sure the root of the dns problem, but test should continue even if no logs are uploaded. The failure could not be reproduced, it might be fixed by the other commit in this PR, or the dns resolution failure could occurred sporatically.
- Remove useless static nameserver in sle15. The nameserver was removed from sle12 host via https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/18055
- Related ticket: https://progress.opensuse.org/issues/150848
https://openqa.suse.de/tests/12822812#step/sriov_network_card_pci_passthrough/149   //a simulated dns failure …

Remove useless static nameserver in sle15 autoyast template

---

tests/nfs/install.pm

cdmackay's git tree not only contains fix for bsc#1217128, but it's newer (contains 6 more fixes from Jeff Layton).
Link: https://bugzilla.suse.com/show_bug.cgi?id=1217128#c3
Related ticket: https://bugzilla.suse.com/show_bug.cgi?id=1217128#c3
- https://openqa.suse.de/tests/overview?build=pynfs/use-cdmackay-git (sle 15-SP6)
- https://openqa.opensuse.org/tests/overview?build=pynfs/use-cdmackay-git (Tumbleweed)

pynfs: Use cdmackay's git tree

---

data/sles4sap/qe_sap_deployment/mr_test_azure.yaml
data/sles4sap/qe_sap_deployment/mr_test_azure_uri.yaml
data/sles4sap/qe_sap_deployment/mr_test_ec2.yaml
data/sles4sap/qe_sap_deployment/mr_test_ec2_product.yaml
data/sles4sap/qe_sap_deployment/mr_test_gcp.yaml
data/sles4sap/qe_sap_deployment/sles4sap_aws_generic.yaml
data/sles4sap/qe_sap_deployment/sles4sap_azure_generic.yaml
data/sles4sap/qe_sap_deployment/sles4sap_azure_generic_maintenance.yaml
data/sles4sap/qe_sap_deployment/sles4sap_azure_generic_uri.yaml
tests/sles4sap/publiccloud/qesap_terraform.pm

Unify the variable used in all the  qesap conf.yaml template for HanaSr and mr_tests.
- Related ticket: TEAM-8180
sle-15-SP5-Azure-SAP-BYOS-Incidents-x86_64-Build:31486:saptune-SAPHanaSR-ScaleUp-PerfOpt@az_Standard_E8s_v3 
For this test is is crucial to select the right combination of settings:
Cloned from https://openqa.suse.de/tests/12825885 and manually adding:
- `PUBLIC_CLOUD_AZURE_OFFER=""`  that is like removing it
- `PUBLIC_CLOUD_IMAGE_ID="suse:sles-sap-15-SP5-byos:gen2:latest"`
Cloned from https://openqa.suse.de/tests/12825885 and manually adding:
- `PUBLIC_CLOUD_IMAGE_LOCATION=""`   that is like removing it
- `PUBLIC_CLOUD_AZURE_OFFER=""`  that is like removing it
- `PUBLIC_CLOUD_IMAGE_ID="suse:sles-sap-15-SP5-byos:gen2:latest"`
Cloned from https://openqa.suse.de/tests/12825885 …

Unify the variable about os image for qesap

---

lib/power_action_utils.pm
schedule/qam/15/qam-gfxdrivers.yaml
tests/console/yast2_vnc.pm

Enhancement poo#130219: We need to test gnome based installation on
baremetal to do basic verification of kernel graphical stack. Module
yast2_vnc was extended with condition to run in ncurses mode on IPMI
backend. Improve shutdown handling on IPMI backend, increase timeout
for shutdown and switch to sol console after shutdown.
- Related ticket: https://progress.opensuse.org/issues/130219
qam-gfxdrivers 15-sp5: https://openqa.suse.de/tests/12850693#
qam-gnome 15-sp5: https://openqa.suse.de/tests/12849770

Add new qam-gfxdrivers schedule for baremetal

---

tests/publiccloud/img_proof.pm

Add support for testing img-proof from Git repo to test PR's like https://github.com/SUSE-Enceladus/img-proof/issues/358
- Related ticket: https://progress.opensuse.org/issues/133628
- sle-15-SP4-GCE-BYOS-Updates-x86_64-Build20231119-1-publiccloud_img_proof@64bit -> https://openqa.suse.de/tests/12851211

pc: Add support for testing img-proof PR's

---

tests/sles4sap/publiccloud/qesap_terraform.pm
tests/sles4sap/qesapdeployment/configure.pm

Change the token lifetime accommodating it with the test duration.
- Related ticket: [TEAM-8713](https://jira.suse.com/browse/TEAM-8713)
- *qesap regression* sle-15-SP5-Qesap-Azure-Payg-x86_64-BuildLATEST_AZURE_SLE15_5_PAYG-qesap_azure_saptune_test@64bit** -> http://openqaworker15.qa.suse.cz/tests/269109 :green_circle:  fails in destroy but that not relevant as destroy is not using the token
- *HanaSR* sle-15-SP4-HanaSr-Azure-Byos-x86_64-Build15-SP4_2023-11-20T12:40:41Z-hanasr_azure_test_saptune_spn@64bit -> http://openqaworker15.qa.suse.cz/tests/269110 :green_circle:  fails after the end of the deployment

Change the qesap SAS token lifetime

---

tests/fips/fips_setup.pm

- Related ticket: [poo#150947](https://progress.opensuse.org/issues/150947)
- Verification run: [fips_ker_mode_tests_crypt_core](https://openqa.suse.de/tests/12855064#step/fips_setup/23)

Revert fips_setup to use pattern in ALP

---

tests/wsl/install_wsl.pm

The WSL version contains dashes instead of spaces which causes Leap tests to fail, as Windows cannot find the app in the search bar when written with dashes
- https://openqa.suse.de/tests/12857353
- https://openqa.opensuse.org/tests/3744855
- https://openqa.opensuse.org/tests/3744854

Split WSL version from dashes

---

data/microos/butane/script
tests/microos/verify_setup.pm

* minimal-vm based on JeOS requires interface configuration otherwise the default interface has no DHCP setup
* based on https://jira.suse.com/browse/SMO-262 test combustion's prepare marker
- Related ticket: https://jira.suse.com/browse/SMO-262 && [minimal-vm failure](https://openqa.suse.de/tests/12637839#step/suseconnect_scc/2)
* [jeos-15sp6](http://kepler.suse.cz/tests/22093#step/verify_setup/153)
* [tw-jeos](http://kepler.suse.cz/tests/22092#step/verify_setup/120)
* [microos](http://kepler.suse.cz/tests/22091#)
* [slem-5.5](http://kepler.suse.cz/tests/22094#step/verify_setup/127)

Extend networking testing in combustion script

---

tests/migration/online_migration/pre_migration.pm

Now for sles15sp2/3 don't need package zypper-migration-plugin to make
yast2 migration work, we can safely remove it to make sles15sp2/sp3 
migration tests to pass.
- Related ticket: Quick PR original [**138461**](https://progress.opensuse.org/issue/138461)
- Needles: N/A
* https://openqa.suse.de/tests/12861494
* https://openqa.suse.de/tests/12861495

Remove zypper-migration-plugin check

---

lib/services/hpcpackage_remain.pm

See https://progress.opensuse.org/issues/150935:
bsc#1194917 is 'VERIFIED INVALID' and https://bugzilla.suse.com/show_bug.cgi?id=1194917#c15 comments that 'After updating the openqa test case, the conflict reported in this bug is gone'.
[VRs](https://openqa.suse.de/tests/overview?version=15-SP6&build=JRivrain%2Fos-autoinst-distri-opensuse%2318151&distri=sle)

Remove workaround for bsc1194917

---

lib/utils.pm
tests/console/scc_deregistration.pm

Change to use serial_terminal for scc_deregistration
- Related ticket: https://progress.opensuse.org/issues/137585
ten times: http://openqa.suse.de/tests/12861496#next_previous
aarch64: http://openqa.suse.de/t12861845
s390x: http://openqa.suse.de/t12861886

Change to use serial_terminal for scc_deregistration

---

data/sles4sap/qe_sap_deployment/sles4sap_aws_generic.yaml
data/sles4sap/qe_sap_deployment/sles4sap_azure_generic.yaml
data/sles4sap/qe_sap_deployment/sles4sap_azure_generic_maintenance.yaml
data/sles4sap/qe_sap_deployment/sles4sap_azure_generic_uri.yaml
tests/sles4sap/publiccloud/qesap_terraform.pm

Remove Terraform variable that does no more exist in qe-sap-deployment.
Removed in qe-sap-deployment in https://github.com/SUSE/qe-sap-deployment/pull/128
- Related ticket:  TEAM-6956
http://openqaworker15.qa.suse.cz/tests/269375
http://openqaworker15.qa.suse.cz/tests/269374 :red_circle: generic Terraform error

Remove qesap setting HANA_OS_MAJOR_VERSION

---

lib/publiccloud/utils.pm

Install latest python3 from python3 module in GCE testing.
- ticket: https://progress.opensuse.org/issues/151260
- Verification run: http://kepler.suse.cz/tests/22233#step/helm_GCE/53

15SP6: register python3 module for GCE helm

---

tests/hpc/slurm_master.pm

Slurm 23_02 has removed the `--uid`. The check can be removed safely. In this commit the `srun` commands which use `-N` parameter takes also the `-x` one which set the nodes for exclusion from the node allocation of the job to run. Those nodes are not configured properly and prints a warning in the stderr.
https://aquarius.suse.cz/tests/19920 v22_05
https://aquarius.suse.cz/tests/19909 v23_02
https://openqa.suse.de/tests/overview?distri=sle&version=15-SP1&build=b10n1k%2Fos-autoinst-distri-opensuse%2318180

[HPC] Remove softfail for uid parameter on Slurm

---

products/sle/main.pm
tests/console/verify_lock_package.pm

Enhance the lock_package test through ensure packages installed before test and verify lock_package test after migration.
- Related ticket: https://progress.opensuse.org/issues/133652
- Needles: N/A
- Verification run: http://openqa.nue.suse.com/tests/12861468#
http://openqa.nue.suse.com/tests/12873535#details #online migration VR

Verify lock_package test after migration

---

lib/containers/common.pm
lib/main_containers.pm
tests/containers/rootless_podman.pm

Reuse existing code to introduce switch_cgroup() function that we'll use for testing cgroup versions 1 & 2.
- Related ticket: https://progress.opensuse.org/issues/137198
sle-15-SP5-Server-DVD-Updates-x86_64-Build20231121-1-podman_tests@64bit -> https://openqa.suse.de/tests/12879666

containers: Introduce switch_cgroup() function

---

lib/LTP/utils.pm
lib/kernel.pm
lib/main_common.pm
schedule/kernel/prepare_baremetal.yaml
tests/kernel/install_kernel_flavor.pm
tests/kernel/update_kernel.pm
variables.md

Enhancement poo#151153: We should to be able to install any kernel
flavor. New variable KERNEL_FLAVOR was introduced. 
First  use case is for kernel-64kb on aarch64 baremetal.
- Related ticket: https://progress.opensuse.org/issues/151153
- Needles:  NONE
15-SP5 installation: https://openqa.suse.de/tests/12879693
15-SP5 install_ltp with update_ltp for KOTD: https://openqa.suse.de/tests/12879694 
15-SP5 cve: https://openqa.suse.de/tests/12881277
15-SP5 syscalls: https://openqa.suse.de/tests/12881278
15-SP5 installation: https://openqa.suse.de/tests/12881505
15-SP5 install_ltp with update_ltp for KOTD: https://openqa.suse.de/tests/12881506
15-SP5 cve: https://openqa.suse.de/tests/12881507
15-SP5 syscalls: https://openqa.suse.de/tests/12881508

Add installation module for custom kernel flavor with kernel-64kb support

---

lib/susedistribution.pm

This should help to prevent an error message we encountered like 'Bad
arg length for Socket::inet_ntoa, length is 0, should be 4'.
```
openqa-clone-custom-git-refspec https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/18189 https://openqa.opensuse.org/tests/3751720
```
- opensuse-Tumbleweed-DVD-s390x-Build20231115-autoyast_zvm@s390x-zVM-vswitch-l2 -> https://openqa.opensuse.org/tests/3751739
now saying
```
Failed to get host by name for 'o3zvm004.openqanet.opensuse.org' (on openqaworker23_container)
```
Related progress issue: https://progress.opensuse.org/issues/137408

Improve error message for s390 param construction

---

data/virt_autotest/sriov_network_guest_logging.sh
lib/virt_autotest/virtual_network_utils.pm
tests/virt_autotest/sriov_network_card_pci_passthrough.pm

- check 3 VFs' network status. Originally it is 2 for sake of saving test time and IPs, but failures might be hidden.
- print more logs
- stop tests at the point the failure happens.
Related ticket: https://progress.opensuse.org/issues/151133
always fail to reprodue failure.
https://openqa.suse.de/tests/12860822

Enhance sriov test a little bit and print more detailed logs

---

tests/virt_autotest/virt_utils.pm

Enhancement compress single qcow2 disk via qemu-img
- Related ticket: https://bugzilla.suse.com/show_bug.cgi?id=1216796
[gi-guest_developing-on-host_developing-kvm](http://openqa.suse.de/tests/12869104#) fail by [bsc#1217139](https://bugzilla.suse.com/show_bug.cgi?id=1217139)
[gi-guest_sles12sp5-on-host_developing-kvm](http://openqa.suse.de/tests/12869105#) fail by [bsc#1217139](https://bugzilla.suse.com/show_bug.cgi?id=1217139)
[gi-guest_sles15sp5-on-host_developing-kvm](http://openqa.suse.de/tests/12869106#) fail by [bsc#1217139](https://bugzilla.suse.com/show_bug.cgi?id=1217139)

virt_autotest: enhancement compress single qcow2 disk via qemu-img

---

tests/console/php_version.pm

Maintenance tests have all modules pre-added
- Related ticket: #18168
https://openqa.suse.de/tests/12904231
https://openqa.suse.de/tests/12904234
https://openqa.suse.de/tests/12904235
https://openqa.suse.de/tests/12904236
https://openqa.suse.de/tests/12904237
https://openqa.suse.de/tests/12904239
https://openqa.suse.de/tests/12904240
https://openqa.suse.de/tests/12904241
https://openqa.suse.de/tests/12904242

php_version: Don't check or add script module on maintenance tests

---

lib/main_publiccloud.pm
tests/publiccloud/cloud_netconfig.pm

This PR is to add a very basic test for cloud-netconfig to be expanded in the future.
This is a work in progress!
- Related ticket: https://progress.opensuse.org/issues/136235
- Needles: N/A
- Verification run: ~~https://openqa.suse.de/tests/12701598~~ ~~https://openqa.suse.de/tests/12897213~~ https://openqa.suse.de/tests/12897652

Add test for cloud-netconfig

---

lib/mm_network.pm
schedule/alp/firewalld_container.yaml
tests/microos/workloads/firewalld-container/firewalld_client.pm
tests/microos/workloads/firewalld-container/firewalld_server.pm

Introduce a new multi-machine test for checking containerized firewalld workload in ALP product
- Fixes also a bug on `mm_network.pm` that sporadically caused `lo` interface being selected
- Related ticket: https://progress.opensuse.org/issues/131189
- https://openqa.suse.de/tests/12908711
- https://openqa.suse.de/tests/12908712
- https://openqa.suse.de/tests/12908713
- https://openqa.suse.de/tests/12908714
- https://openqa.suse.de/tests/12908715
- https://openqa.suse.de/tests/12908716
- https://openqa.suse.de/tests/12908717
- https://openqa.suse.de/tests/12908718
- https://openqa.suse.de/tests/12908719
- https://openqa.suse.de/tests/12908720
- https://openqa.suse.de/tests/12908721
- https://openqa.suse.de/tests/12908722
- …

Test for firewalld container in ALP product

---

data/containers/autoyast_containers.xml.ep
lib/containers/common.pm

as described in https://bugzilla.suse.com/show_bug.cgi?id=1217509, podman should pull cni plugin as dependency
* http://kepler.suse.cz/tests/22241#step/podman/39
* http://kepler.suse.cz/tests/22239#step/podman/39

Do not install podman-cni-plugin explicitly

---

tests/systemd_testsuite/prepare_systemd_and_testsuite.pm

`python3-pefile` is needed for upstream systemd test execution. The package is located in phub.
- Verification run: http://kepler.suse.cz/tests/22248#

Register phub for systemd upstream testing

---

lib/main_common.pm
lib/y2_installbase.pm
tests/virt_autotest/login_console.pm

- Related ticket: https://progress.opensuse.org/issues/126110
- Needles: https://gitlab.suse.de/openqa/os-autoinst-needles-sles/-/merge_requests/1652
- Other related MR: https://github.com/SUSE/qa-automation/pull/807 and https://github.com/SUSE/qa-testsuites/pull/1085
Aim:
- To install a guest operating system with a 64KB page size on a hypervisor that also operates with a 64KB page size.
Implementation Strategy:
- For Baremetal Setup:
Introduce a new module named select_packages which is optimized for text mode. This module will facilitate the configuration and management of systems with a 64KB page size setting in a baremetal environment.
- For Virtual Machine (VM) Setup:
Create a new scenario that involves installing a kernel-64kb package using AutoYaST. This …

Add new test for 64kb page size

---

data/yam/autoyast/support_images/sles12sp5_install_all_patterns_s390x.xml
data/yam/autoyast/support_images/sles12sp5_install_default_patterns_ppc64le.xml
data/yam/autoyast/support_images/sles12sp5_install_default_patterns_x86_64.xml

- Description:
* In SLE12SP5 we have to use 'config:type' not the 't=' in the autoyast profile, the t shortcut was introduced in SLE-15-SP3.
- More info:
- [**slack_discussion**](https://suse.slack.com/archives/C02D1T4S58S/p1701089829017879)
- Needles: N/A
- https://openqa.suse.de/tests/12915680#step/hostname/8
- https://openqa.suse.de/tests/12915745#step/hostname/8
- https://openqa.suse.de/tests/12915747#step/hostname/8
- Without the fix it still has /home
*   https://openqa.suse.de/tests/12915743#step/hostname/10

Change the 't=' to 'config:type=' for sle12sp5 autoyast profile

---

lib/main_micro_alp.pm

Enable btrfs-progs for alp dolomite in openqa
- Related ticket: https://progress.opensuse.org/issues/150872
- Needles: N/A
- http://10.67.129.54/tests/884 (SLES)
- http://10.67.133.133/tests/387 (ALP)

btrfs-progs: init btrfs-progs in main_micro_alp

---

data/kea-dhcp/kea-dhcp4.conf
tests/microos/workloads/kea-container/setup_dhcp4_server.pm
tests/microos/workloads/kea-container/setup_dhcp6_server.pm

Removing the verification of the cni-podman0 interface after creating the DHCPv4 container workload in the background. The plan is to schedule the DHCP container test in the ALP Functional job group.
- Verification run:  [dhcp4_server](https://openqa.suse.de/tests/12892993) | [dhcp_client](https://openqa.suse.de/tests/12892994)
[dhcp6_server](https://openqa.suse.de/tests/12892991) | [dhcp6_client](https://openqa.suse.de/tests/12892992#)

Remove the check of verifying podman0 interface

---

tests/installation/boot_encrypt.pm

A quick fix to address 15SP6 grub update; for readability reasons, introduce a boolean variable that explicit the condition when we can skip the passphrase input
- Related ticket: https://progress.opensuse.org/issues/151393
- SLE 15sp6: https://openqa.suse.de/tests/12908857
- SLE 15sp5: https://openqa.suse.de/tests/12909185
- Tumbleweed: https://openqa.opensuse.org/tests/3761967
- Leap 15sp6: https://openqa.opensuse.org/tests/3761964
- Leap 15sp4: https://openqa.opensuse.org/tests/3761960

New grub on 15SP6 don't need to type LUKS passphrase

---

tests/microos/image_checks.pm

Currently the partition is not resized but the partition table is not resized either which results in an "Unpartitioned space: 0 Bytes" false positive. Detect this failure.
- Related ticket: https://bugzilla.opensuse.org/show_bug.cgi?id=1217448
http://10.168.4.192/tests/1406#step/image_checks/11 (expected failure now)
http://10.168.4.192/tests/1407 (expected success with fixed image)

microos/image_checks.pm: Verify that the partition table got resized

---

lib/containers/common.pm
tests/containers/container_engine.pm
tests/containers/rootless_podman.pm
variables.md

Introduce CONTAINERS_CGROUP_VERSION variable to switch cgroups version.
- Related ticket: https://progress.opensuse.org/issues/137198
- opensuse-Tumbleweed-DVD-x86_64-Build20231126-containers_host_docker@64bit -> https://openqa.opensuse.org/tests/3765302#step/docker/21
Bug opened for podman:
https://bugzilla.opensuse.org/show_bug.cgi?id=1217590
TODO:
- Add scheduling for TW on opensuse-jobgroups
- Add scheduling for SLE 15-SP3+ on qac-openqa-yaml

Introduce CONTAINERS_CGROUP_VERSION variable

---

tests/installation/select_patterns.pm

Display the conflict message on the OpenQA web page whenever a conflict occurs during the installation.
- Related ticket: https://progress.opensuse.org/issues/138680
- Needles: No
https://openqa.suse.de/tests/12855037#step/select_patterns/22
https://openqa.suse.de/tests/12855039#step/select_patterns/1
Latest VRs:
https://openqa.suse.de/tests/12861755
https://openqa.suse.de/tests/12861756

Add the conflict message to display on the openQA page 

---

lib/YaST/NetworkSettings/NetworkCardSetup/VLANAddressTab.pm
tests/x11/nis_server.pm
tests/yast2_gui/yast2_bootloader.pm

We need to add workaround_poo124652 for some yast2 screen refresh with SHIFT+F3.
- Related ticket: https://progress.opensuse.org/issues/151663
- Needles: N/A
- nis_server
* https://openqa.suse.de/t12930810
* https://openqa.suse.de/t12930811
- yast2_gui
* https://openqa.suse.de/t12930850

Add workaround to refresh some yast screen

---

data/virtualization/autoyast/host_12.xml.ep
data/virtualization/autoyast/host_15.xml.ep
lib/virt_autotest/common.pm
lib/virt_autotest/utils.pm
schedule/qam/common/virt/qam_virt_tests.yaml

Adopt SR-IOV PCI passthrough test from product automation test to maintenance test
- Related ticket: https://progress.opensuse.org/issues/89098
- Needles: no
- sle15sp2 xen and kvm: http://10.67.183.130/tests/overview?version=15-SP2&groupid=2&build=sriov%3Avr&distri=sle
- sle15sp4 kvm: http://10.67.183.130/tests/overview?distri=sle&version=15-SP4&groupid=2&build=sriov%3Avr
- sle15sp5 xen: http://openqa.qam.suse.cz/tests/overview?groupid=168&build=%3AS%3AM%3A31417%3A312541%3Axen%3A%3Asriov&version=15-SP5&distri=sle
- gi-guest_developing-on-host_sles15sp5-xen: https://openqa.suse.de/tests/12857627

Adopt SR-IOV PCI passthrough test to maintenance test

---

lib/YaST/NetworkSettings/NetworkCardSetup/AddressTab.pm
lib/YaST/NetworkSettings/NetworkCardSetup/VLANAddressTab.pm

After adding apply_workaround_poo124652 to refresh the yast screen, the test 
run complains with 'Undefined subroutine'
- Related ticket: https://progress.opensuse.org/issues/151663
- Needles: N/A
- https://openqa.suse.de/tests/12931258 yasts_gui
- https://openqa.suse.de/tests/12931314 nis server

 Fix workaround to refresh some yast screen undefined issue

---

lib/containers/urls.pm

The BCI URLs for testing 15-SP4 and 15-SP5 in SLE Micro were missing
- Related ticket: https://progress.opensuse.org/issues/151699
- Verification run: https://openqa.suse.de/tests/12931527

Missing URLs for testing images in SLE Micro

---

lib/package_utils.pm
tests/console/year_2038_detection.pm
tests/kernel/update_kernel.pm

- Related ticket: https://progress.opensuse.org/issues/117028
https://dzedro.suse.cz/tests/301#step/update_kernel/106 SLE Micro
https://dzedro.suse.cz/tests/302#step/update_kernel/26 SLES
https://openqa.suse.de/tests/overview?distri=sle&version=15-SP5&build=jpupava_wrapper

Wrapper for zypper_call and trup_call

---

lib/Utils/Logging.pm

- Related ticket: https://progress.opensuse.org/issues/112547
- Verification run: https://openqa.suse.de/tests/12941265#step/python_flake8/174 [coredump files can be listed if any]

Make coredumps more visible

---

tests/console/prepare_test_data.pm

Quick PR to fix no permission access serial console on ppc64le.
- Failed job: https://openqa.suse.de/tests/12958494#step/prepare_test_data/12
- Needles: N/A
- Verification run: http://openqa.nue.suse.com/tests/12958637#

Fix no permission to access serial console on ppc64le

---

tests/console/sudo.pm

- Related ticket: https://progress.opensuse.org/issues/151600
- Needles: N/A
- Verification run: https://openqa.opensuse.org/tests/3782319

sudo: copy template config from /usr/etc to /etc before modifying it

---

schedule/alp/bonding.yaml
tests/microos/network_bonding.pm

Introduce a new test for ALP that create a network bond and check interface failover
- Related ticket: https://progress.opensuse.org/issues/151273
- Needles: no
- Verification run: https://openqa.suse.de/tests/12961079

Test bonding two network interfaces on ALP

---

tests/microos/workloads/kea-container/dhcp4_client.pm
tests/microos/workloads/kea-container/dhcp6_client.pm
tests/microos/workloads/kea-container/setup_dhcp4_server.pm
tests/microos/workloads/kea-container/setup_dhcp6_server.pm

Fixed the issue of selecting the 'lo' interface in Kea DHCP tests. Now, both the KEA DHCP tests on IPv4 and IPv6 have successfully passed.
- Needles: No
[Kea_dhcp4_server](https://openqa.suse.de/tests/12970246#) | [Kea_dhcp4_client](https://openqa.suse.de/tests/12970248#)
[Kea_dhcp6_server](https://openqa.suse.de/tests/12970244#)  | [Kea_dhcp6_client](https://openqa.suse.de/tests/12970247#)

Fix the issue of the wrong interface being selected in KEA DHCP test

---

lib/mm_network.pm
lib/network_utils.pm

We already set the MTU to 1458 various other MM scenarios, e.g. this makes
this helper consistent with what the similar helper `configure_static_ip`
already does.
This should fix the connection problems with scc.suse.com in 
`qam-wicked_basic_ref` and similar tests.
Related ticket: https://progress.opensuse.org/issues/151612

Set MTU also in `setup_static_network` helper of wicked tests

---

lib/apachetest.pm
tests/console/sssd_389ds_functional.pm
tests/console/sssd_openldap_functional.pm

The former no longer exists in TW and sudoers.d should be used anyway.
http://10.168.4.192/tests/1409 (php_postgresql)
http://10.168.4.192/tests/1412 (sssd_389ds_functional)

Port users of /etc/sudoers to /etc/sudoers.d/

---

tests/migration/openldap_configuration.pm

- Related ticket: https://progress.opensuse.org/issues/139049 (nscd no longer preinstalled)
- Needles: N/A
- Verification run: https://openqa.opensuse.org/tests/3789258

openldap_configuration: only disbale nscd if installed

---

tests/containers/bci_version_check.pm

Update BCI openQA test runs to new version scheme
- Related ticket: https://progress.opensuse.org/issues/152068
- Verification run: openjdk-17-devel-new-scheme: https://openqa.suse.de/tests/12990799, openjdk-17-devel-old-scheme: https://openqa.suse.de/tests/12990754, go_oldstable-old scheme: https://openqa.suse.de/tests/12990755, go_oldstable_new_scheme:https://openqa.suse.de/tests/12990900

Update BCI openQA test runs to new version scheme

---

lib/qesapdeployment.pm
t/15_qesap_azure.t
tests/sles4sap/publiccloud/qesap_ansible.pm
tests/sles4sap/publiccloud/qesap_terraform.pm

Remove subscription id from qesap_az_setup_native_fencing_permissions and qesap_az_assign_role and calculate it on the fly using az cli.
Manage arguments for qesap_az_enable_system_assigned_identity with a different Perl pattern.
Reorganize few UT to split tests about missing arguments from test from proper behavior.
- Related ticket: TEAM-8714
- SBD fencing - sle-15-SP5-HanaSr-Azure-Byos-x86_64-Build15-SP5_2023-12-07T05:03:10Z-hanasr_azure_test_sbd@64bit -> http://openqaworker15.qa.suse.cz/tests/272524 :green_circle:  deployment phase is ok
- Native MSI  - sle-15-SP5-HanaSr-Azure-Byos-x86_64-Build15-SP5_2023-12-07T05:03:10Z-hanasr_azure_test_msi@64bit -> http://openqaworker15.qa.suse.cz/tests/272525  :green_circle:  deployment phase is ok. Failure is later in …

Remove subscription_id from az related qesap API

---

tests/x11/gnomecase/nautilus_permission.pm

In recent GNOME versions, we need to press ESC once more to get
back to the file view. Pressing too many times ESC does not matter,
as we end up on the nautilus file list; this makes it easier for us
not having to worry about the GNOME version running.
- Related ticket: https://progress.opensuse.org/issues/136229
- Needles: N/A
- Verification run: https://openqa.opensuse.org/tests/3789921

gnome/nautilus: close custom permission dialog

---

tests/fips/fips_setup.pm

- Related ticket: https://progress.opensuse.org/issues/152230
https://openqa.suse.de/tests/12999644 - env mode
https://openqa.suse.de/tests/12999660 - another env mode fips test
https://openqa.suse.de/tests/12999666 - a kernel mode test

 Fix brokenness of FIPS setup on SLE >=15-SP4 in env mode

---

tests/kernel/update_kernel.pm

Fix poo#152272: SLE Micro RT 5.1 contains both kernel flavors, kernel-default must be removed to avoid conflicts.
- Related ticket: https://progress.opensuse.org/issues/152272
- Needles:  none
SLE Micro RT 5.1: https://openqa.suse.de/tests/13001589
SLE Micro RT 5.2: https://openqa.suse.de/tests/13001521
SLE 15-SP3: https://openqa.suse.de/tests/13001522

kernel: Fix kernel update on SLE Micro RT 5.1

---

lib/YaST/workarounds.pm
lib/yast2_widget_utils.pm

We need to apply workaround_poo124652 for send key until needle match.
- Related ticket: https://progress.opensuse.org/issues/152065
* Fix for this kind of error:
* https://openqa.suse.de/tests/13010426#step/iscsi_client/55
- Needles: N/A
* https://openqa.suse.de/t13022227
* https://openqa.suse.de/t13022232

Apply workaround_poo124652 for send_key_until

---

schedule/wsl/wsl_main.yaml
tests/wsl/enable_systemd.pm

WSL now supports systemd, so there's need to check that we can enable and test it
- Paired with: https://gitlab.suse.de/qac/qac-openqa-yaml/-/merge_requests/1309
- Related ticket: [poo#133691](https://progress.opensuse.org/issues/133691)
- Needles: *not_needed*
- SLE:
- https://openqa.suse.de/tests/12855059
- https://openqa.suse.de/tests/12867495
- https://openqa.suse.de/tests/12855057
- https://openqa.suse.de/tests/12867496
- https://openqa.suse.de/tests/12855055
- https://openqa.suse.de/tests/12867497
- TW:
- https://openqa.opensuse.org/tests/3744420
- https://openqa.opensuse.org/tests/3747994
- https://openqa.opensuse.org/tests/3744422
- https://openqa.opensuse.org/tests/3747995
- https://openqa.opensuse.org/tests/3744424
- https://openqa.opensuse.org/tests/3800853 …

New test for checking systemd in WSL

---

lib/main_containers.pm
tests/containers/podman_quadlet.pm

Quadlet is an opinionated tool for easily running podman system
containers under systemd in an optimal way.
- ticket: https://progress.opensuse.org/issues/151243
- Verification run: [tw](http://kepler.suse.cz/tests/22323#live)

Smoke test for podman-systemd-generator 

---

data/containers/autoyast_containers.xml.ep

Autoyast file partitioning updated for BCI containers HDD image, refactoring and fixing of code in https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/18195, with particular attention to **s390x** case.
- Related ticket: https://progress.opensuse.org/issues/151510

HDD autoyast partitioning updated for BCI tests

---

tests/microos/network_bonding.pm

Fix for openSUSE, makes the test independent from the network device naming scheme
- Related ticket: https://progress.opensuse.org/issues/151273
- Needles: N/A
- https://openqa.opensuse.org/tests/3800277
- https://openqa.suse.de/tests/13023338

Read network device names from Network Manager

---

data/autoyast_qam/12-common_base_installation.xml.ep
data/autoyast_qam/12_installation.xml.ep
data/autoyast_qam/15-common_base_installation.xml.ep
data/autoyast_qam/15_installation.xml.ep
data/autoyast_sle12/autoyast_sles12sp3+alladdons_allpatterns_reg_full_s390x.xml
data/autoyast_sle12/autoyast_sles12sp3+alladdons_default_reg_full_s390x.xml
data/autoyast_sle12/autoyast_sles12sp3+sdk+ha+geo_allpatterns_reg_full_s390x.xml
data/autoyast_sle12/autoyast_sles12sp3+sdk+ha+geo_default_reg_full_s390x.xml
data/autoyast_sle12/autoyast_sles12sp3_allpatterns_reg_full_s390x.xml
data/autoyast_sle12/autoyast_sles12sp3_default_reg_full_s390x.xml
data/autoyast_sle12/ay.xml
data/lynis/baseline-lynis-audit-system-nocolors-15-SP2-s390x-gnome
data/lynis/baseline-lynis-audit-system-nocolors-15-SP2-s390x-textmode
data/lynis/baseline-lynis-audit-system-nocolors-15-SP3-s390x-gnome
data/lynis/baseline-lynis-audit-system-nocolors-15-SP3-s390x-textmode
data/lynis/baseline-lynis-audit-system-nocolors-15-SP4-s390x-textmode
data/lynis/baseline-lynis-audit-system-nocolors-15-SP5-aarch64-gnome
data/lynis/baseline-lynis-audit-system-nocolors-15-SP5-aarch64-textmode
data/lynis/baseline-lynis-audit-system-nocolors-15-SP5-ppc64le-gnome
data/lynis/baseline-lynis-audit-system-nocolors-15-SP5-ppc64le-textmode
data/qam/dracut/12-SP2_custom_lvm.xml.ep
data/qam/dracut/12-SP2_custom_usr.xml.ep
data/qam/dracut/12_custom_lvm.xml.ep
data/yam/autoyast/sles_zvm.xml
data/yam/autoyast/support_images/create_hdd_ha_sles.xml.ep
data/yam/autoyast/support_images/create_hdd_sles_regression_aarch64.xml.ep
data/yam/autoyast/support_images/create_hdd_sles_regression_s390x.xml.ep
data/yam/autoyast/support_images/sles12sp5_install_all_patterns_s390x.xml
data/yam/autoyast/support_images/sles12sp5_install_default_patterns_s390x.xml
products/sle/templates

10.160.0.1 was in the SUSE NUE datacenter which is now decommissioned
and replaced by 10.144.53.53.
```
openqa-clone-custom-git-refspec https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/18287 https://openqa.suse.de/tests/13045251
```
sle-15-SP4-Server-DVD-Updates-s390x-Build20231211-1-mru-install-minimal-with-addons@s390x-kvm -> https://openqa.suse.de/tests/13049868
Related progress issue: https://progress.opensuse.org/issues/152461

Update all outdated references to SUSE internal DNS server

---

tests/console/firewalld.pm

Firewalld adds the icmp protocol rule in the filter_IN_public_allow nftables chain, but the testcase is checking for this rule in the filter_FWD_public chain which it is not able to find and thus failing.
- Related ticket: https://progress.opensuse.org/issues/131411
- Needles: Not Needed
- Verification run: Tested locally. Issue is resolved. Test results in **softfailed** with "bsc#1206383 - iptables uses legacy backend instead of nftables"

Fix firewalld check_rules() to check for correct nft chain

---

data/containers/autoyast_containers.xml.ep

The autoyast_containers.xml needed to have subpartition `/var` too, for checks to pass in `tests/containers/validate_btrfs.pm`
- Related ticket: https://progress.opensuse.org/issues/151510
- Needles: N/A

autoyast: subpartition /var add in containers HDD

---

tests/btrfs-progs/install.pm

1. install attr for ALP dependence
2. use space to split BTRFS_PROGS_DEPS for more readable
- Related ticket: https://progress.opensuse.org/issues/152245
- Needles: N/A
- Verification run: http://10.67.133.133/tests/400

btrfs-progs: update install_dependencies for ALP

---

tests/qemu/qemu.pm

* **Starting** from SLE Micro 6.0, which uses ALP code base, there are some packages changes, for exmaple, patterns-microos-kvm_host is changed to patterns-alp-kvm_host.
* [x86_64](https://openqa.suse.de/tests/13058518)
* [aarch64](https://openqa.suse.de/tests/13058517)

Adapt qemu test for SLE Micro 6.0

---

lib/qesapdeployment.pm
lib/sles4sap_publiccloud.pm
t/12_sles4sap_publicccloud.t

Improve as lib arguments are managed, do not create auxiliary variables when possible.
Split some unit tests.
No behavioral changes.
- Related ticket: TEAM-8714
-> http://openqaworker15.qa.suse.cz/tests/272774 :red_circle: failed in Ansible task `SAP HSR - Register secondary node to HANA System Replication` due to `unable to contact primary site host vmhana01:40006. connection refused`
->  http://openqaworker15.qa.suse.cz/tests/272797 :green_circle: 
-> http://openqaworker15.qa.suse.cz/tests/272775 :red_circle: fails in Ansible with `Timed out waiting for last boot time check (timeout=600)`
-> http://openqaworker15.qa.suse.cz/tests/272798 :green_circle:

Improve lib arguments handling for Azure Native fencing

---

lib/sles4sap_publiccloud_basetest.pm

Add call to qesap_cluster_logs in post_fail_hook of sles4sap_publiccloud basetest.
- Related ticket: TEAM-8800
- sle-15-SP3-Azure-SAP-PAYG-Incidents-x86_64-Build:31531:SAPHanaSR-SAPHanaSR-ScaleUp-PerfOpt@az_Standard_E8s_v3
--> http://openqaworker15.qa.suse.cz/tests/272839 :green_circle:  it fails with error similar to TEAM-8800 and now we have error logs :partying_face: 
- sle-15-SP2-Azure-SAP-BYOS-Incidents-x86_64-Build:31531:SAPHanaSR-SAPHanaSR-ScaleUp-PerfOpt@az_Standard_E8s_v3 
--> http://openqaworker15.qa.suse.cz/tests/272835 this one is fine, test fails and logs are properly collected (check the log tab) :green_circle: 
--> http://openqaworker15.qa.suse.cz/tests/272836 in this one there's a test module failure, the post_fail_hooks properly call the function `qesap_cluster_logs()` to …

Add cluster log collection in sles4sap_pc tests

---

tests/console/java.pm

Instead of installing java-* (which includes debuginfo), be more specific and install java-*-devel.
- Related ticket: https://progress.opensuse.org/issues/152206
- Needles: N/A
- Verification run: https://openqa.opensuse.org/tests/3809161
Limiting to `-r OSS` causes issues as the name is not stable across all tests (works in regular ToTest based QA runs, but not on image tests)

java: revert limiting to OSS repo but rather make the package names more explicit

---

tests/sles4sap/hana_install.pm

`sles4sap/hana_install` test module sporadically times out when unpacking the installer. See: https://openqa.suse.de/tests/13037858#step/hana_install/44
The serial terminal does not show errors:
```
2023-12-12 23:31:40 (29.6 MB/s) - ‘SPS05rev57_x86_64.tar’ saved [16489840640/16489840640]
DqIvc-0-
abWGm-0-
```
So more than likely, command is working but it's taking longer than the default time to finish.
- Needles: N/A

Increase timeout to unpack HANA installer

---

t/12_sles4sap_publicccloud.t

Import a test library to mock the all time functions. The result is that all sleeps has mostly zero execution time. Test about waiting timeout failure are executed in shorter time.
Here execution time of the test with and without the fix
```
% time PERL5OPT=-MCarp::Always  prove --verbose -l -Ios-autoinst/ t/12_sles4sap_publicccloud.t
PERL5OPT=-MCarp::Always prove --verbose -l -Ios-autoinst/   0.88s user 0.25s system 0% cpu 7:31.37 total
PERL5OPT=-MCarp::Always prove --verbose -l -Ios-autoinst/   1.06s user 0.21s system 90% cpu 1.403 total
```
Or you can compare PR pipeline execution time of this PR https://github.com/os-autoinst/os-autoinst-distri-opensuse/actions/runs/7193214082/job/19591195904?pr=18297#step:6:127 with one from a previous PR like …

Reduce execution time of the sles4sap pc UT

---

lib/qesapdeployment.pm
t/09_qesapdeployment.t

Adds a function to retrieve the native fencing method (msi or spn) and relevant tests.
- Related ticket: https://jira.suse.com/browse/TEAM-8714
- Verification run: function not used anywhere yet

Add func to retrieve native fencing type

---

lib/grub_utils.pm
lib/opensusebasetest.pm
lib/utils.pm
tests/boot/grub_test_snapshot.pm
tests/installation/boot_encrypt.pm
tests/x11/reboot_and_install.pm

https://progress.opensuse.org/issues/151393
VRs:
[tw crypt_no_lvm](https://openqa.opensuse.org/tests/3787186#)
[sle crypt_no_lvm](https://openqa.suse.de/tests/12988792#)
[Staging](https://openqa.suse.de/tests/overview?build=rfan1206_stage&version=15-SP6&distri=sle)
[yast failed cases](https://openqa.suse.de/tests/overview?build=rfan1206&version=15-SP6&distri=sle)
[yast passed cases](http://openqa.suse.de/tests/overview?build=rfan1207_yast&version=15-SP6&distri=sle)
New VRs:
[boot_to_desktop](http://openqa.suse.de/tests/12999431#)
[staging](http://openqa.suse.de/tests/overview?version=15-SP6&distri=sle&build=rfan1208_stage)
[yast sainty](https://openqa.suse.de/tests/overview?version=15-SP6&build=rfan1208_yast&distri=sle)
[kernel_encrypt_create_hdd](http://openqa.suse.de/tests/12999490#)

New logic to type LUKS passphrase in grub phase

---

lib/main_containers.pm
tests/containers/podman_netavark.pm

Do not install nor switch to netavark as it is the default setup in sle-micro 6.0
- Related ticket: https://progress.opensuse.org/issues/152581
- Verification run: http://kepler.suse.cz/tests/22339#

Netavark is default it sle-micro 6.0

---

tests/installation/bootloader_zkvm.pm

https://progress.opensuse.org/issues/152619
- Verification run: https://openqa.suse.de/tests/13070132#step/bootloader_start/8

Make s390x zKVM SUT hostname more visible

---

lib/main_publiccloud.pm

Any scenarios which trying to install something are problematic for
unreleased version of SLE because we often has image with newer
than one which exists in SCC. And there is no way around that

Unschedule libgcrypt for unreleased SLE versions

---

tests/wsl/install_wsl.pm

The install_wsl test would attempt to use the search function before exiting powershell. I added a line to check for windows desktop before proceeding with searching for WSL installation.
- Related ticket: https://progress.opensuse.org/issues/151624
- Verification run: https://openqa.opensuse.org/tests/3810149#step/install_wsl/1
- Needles: https://github.com/os-autoinst/os-autoinst-needles-opensuse/blob/master/windows-search-bar-20231211.png

fix install_wsl race condition

---

lib/windowsbasetest.pm
tests/wsl/firstrun.pm

in order to maximize a window, swaps a needle verification for a keyboard input (super+up).
- Related ticket: https://progress.opensuse.org/issues/138248
- Verification run (updated): https://openqa.suse.de/tests/13070688#

Improve maximize window poo#138248

---

data/virt_autotest/virt_logs_collector.sh
lib/virt_autotest/utils.pm
tests/virt_autotest/sriov_network_card_pci_passthrough.pm
tests/virt_autotest/xen_guest_irqbalance.pm

- Allow to set the count of VFs to be plugged in to the guests to ease reproduce bugs
- Upload one more vf configration xml file which might be needed when opening a bug
- add more debug info for dns resolution failure on sriov test
- Add check guest health in irqbalance tests
- Exclude collecting "File system list" and "Audit" logs because supportconfig always hung at these two steps and failed to create supportconfig.tar.gz, fg. http://openqa.suse.de/tests/13021703#step/hotplugging_guest_preparation/108 & https://openqa.suse.de/tests/13047795#step/sriov_network_card_pci_passthrough/484.  Even sometime they finally passed, it took more than 1 hour, fg. https://openqa.suse.de/tests/13037049,  which is unacceptable.
Related ticket: https://progress.opensuse.org/issues/151133 & …

Allow set vf count for sriov test and check guest health for irqbalance test

---

data/yam/autoyast/support_images/sles15sp3_install_textmode_default_patterns_aarch64.xml
data/yam/autoyast/support_images/sles15sp3_install_textmode_default_patterns_s390x.xml
data/yam/autoyast/support_images/sles15sp3_install_textmode_default_patterns_x86_64.xml

Add ltss to sles15sp3 textmode default patterns autoyast installation.
- Related ticket: https://progress.opensuse.org/issues/152185
- Verification run: [autoyast installation and images verify](https://openqa.suse.de/tests/overview?distri=sle&version=15-SP3&build=20231212-2&groupid=251) 
- Related mr: [support images testsuite update](https://gitlab.suse.de/qa-maintenance/qam-openqa-yml/-/merge_requests/677); [migration testsuites update](https://gitlab.suse.de/qe-yam/openqa-job-groups/-/merge_requests/11)

Add ltss to SLES15SP3 textmode default patterns ay installation

---

tests/migration/online_migration/zypper_migration.pm

Need report failure when zypper migration failed
- Related ticket: https://progress.opensuse.org/issues/152356
- Verification run: failed job: https://openqa.suse.de/tests/13005137#step/zypper_migration/5
This failed cannot reproduce now. 
Updated the code, if 'Can't determine the list of installed products' this error message can be found during zypper migration, die 'Migration failed with zypper error'

Need report failure when zypper migration failed

---

data/qam/handle_bind_source_dependencies.sh

The script could be replaced with simpler way of just adding modules, but it was made like this in the past due to reasons which are not reauired anymore, but it works
https://bugzilla.suse.com/show_bug.cgi?id=1170267#c17
- Related ticket: https://openqa.suse.de/tests/13076187#step/bind/7
- Verification run: https://dzedro.suse.cz/tests/428

bind: Add auto-agree-with-licenses due to new feature

---

lib/transactional.pm

Minor tweak was needed to correct sle-micro reboot processing in case the version is >= 6 and 
there is an encrypted disk.
- Related ticket: https://progress.opensuse.org/issues/152651
* Marble
https://openqa.suse.de/tests/13077342
* Dolomite
https://openqa.suse.de/tests/13077391

Correct OS check for correct reboot call

---

lib/windowsbasetest.pm
tests/wsl/firstrun.pm

Reverts os-autoinst/os-autoinst-distri-opensuse#18135
Seeing that the improvement did make thins worth (and the benefit was doubted pre-merge), revert seems to be the most sensible thing.

Revert "Improve maximize window poo#138248"

---

data/sles4sap/qe_sap_deployment/qesap_azure_fencing_msi.yaml
data/sles4sap/qe_sap_deployment/qesap_azure_fencing_spn.yaml
lib/qesapdeployment.pm
tests/sles4sap/qesapdeployment/configure.pm
tests/sles4sap/qesapdeployment/deploy.pm

This pr adds support for native fencing in qesap regression.
- Related ticket: https://jira.suse.com/browse/TEAM-8714
- 15sp5: http://openqaworker15.qa.suse.cz/tests/273026
- 15sp4: http://openqaworker15.qa.suse.cz/tests/273027
- 15sp3: http://openqaworker15.qa.suse.cz/tests/273030
- 12sp5: http://openqaworker15.qa.suse.cz/tests/273031
- 15sp5: https://openqaworker15.qa.suse.cz/tests/273025
- 15sp4: http://openqaworker15.qa.suse.cz/tests/273028
- 15sp3: http://openqaworker15.qa.suse.cz/tests/273029
- 12sp5: http://openqaworker15.qa.suse.cz/tests/273032

Add native fencing in qesap regression

---

lib/LTP/utils.pm
tests/kernel/klp_downgrade.pm

Kernel livepatch downgrade was tested by uninstalling the livepatch incident up until now. The `klp` command line utility recently got a feature for downgrading livepatches and should be used instead on SLE-15SP3+.
Older SLE does not support the feature or the `klp` is not available. Those versions will continue using the current incident uninstall approach.
- Related ticket: https://progress.opensuse.org/issues/109476
- Needles: N/A
- SLE-12SP5: https://openqa.suse.de/tests/13072161#step/uninstall_incident/5 (using old incident uninstall method)
- SLE-15SP3: https://openqa.suse.de/tests/13052105#step/klp_downgrade/10
- SLE-15SP4: https://openqa.suse.de/tests/13052106#step/klp_downgrade/10
- SLE-15SP5: https://openqa.suse.de/tests/13052107#step/klp_downgrade/10

Add test for klp downgrade command

---

tests/sles4sap/saptune/mr_test.pm
tests/sles4sap/saptune/mr_test_run.pm

Improve test results of mr_test for saptune 3.1 including Public Cloud and On-premise cases for pre-released 15sp6 and released 12sp5/15sp+ products.
TEAM-8662 - [saptune] mr_test in CSP for saptune 3.1
Improved test results according to https://confluence.suse.com/display/qasle/TEAM-8662+%5Bsaptune%5D+mr_test+in+CSP+for+saptune+3.1
- Related ticket: https://jira.suse.com/browse/TEAM-8662
- Needles: NA
sle-12-SP5 saptune_solutions PC:  
_https://openqa.suse.de/tests/13076788   (failed), can be tracked by [Bug 1218083](https://bugzilla.suse.com/show_bug.cgi?id=1218083))
(It shows 'failed' but not 'softfailed' as `parse_extra_log` can not parse `softfailed` ATM I think)_
https://openqa.suse.de/tests/13095379 (passed, as added fix according to bsc#1218083)
sle-12-SP5 …

Improve test results of mr_test for saptune 3.1

---

tests/smt/smt_client.pm

- Related ticket: https://progress.opensuse.org/issues/152675 https://bugzilla.suse.com/show_bug.cgi?id=1217961
- Verification run: https://openqa.suse.de/tests/13080328#step/smt_client/34

smt_client: Remove unneeded -p argument from SUSEConnect

---

tests/sles4sap/hana_install.pm

Due to load in osd workers, the `sles4sap/hana_install` test module is sporadically taking longer than 15 minutes unpacking the HANA installation files tarball. This commit combines the download of the tarball asset with its unpacking in a single pipeline with the 2700 seconds timeout which seems to be enough to download the file; since tarball is not compressed, this solution should accomplish getting the tarball unpacked into the SUT and avoid the later timeout when trying to unpack a downloaded tarball.
- Related ticket: https://jira.suse.com/browse/TEAM-8871
- Needles: N/A
- Verification run: http://openqaworker15.qa.suse.cz/tests/273041

Combine download of tarball and unpacking

---

lib/sles4sap_publiccloud.pm
t/12_sles4sap_publicccloud.t

Avoid an exception if get_hana_topology return an empty result. It could happens if SAPHanaSR-showAttr is not successful and output is not what expected.
This new behavior is obtained avoiding the usage of local variables in check_takeover.
Sleep 30 moved in a different position only to be used once for each get_hana_topology and not to be called when there's no more retry to run.
Add some unit testing for these two functions.
- Related ticket: TEAM-8878
-  http://openqaworker15.qa.suse.cz/tests/273037 :red_circle:  Here the `check_takeover` runs fine http://openqaworker15.qa.suse.cz/tests/273037#step/Crash_site_a-primary/96  but here http://openqaworker15.qa.suse.cz/tests/273037#step/Crash_site_b-primary/99 it is not ok
```
in string eq at …
```

Avoid die in check_takeover for uninitialized variables

---

lib/ssh_crypto_policy.pm

Don't add a leading "," after each config line.
- Related ticket: https://bugzilla.suse.com/show_bug.cgi?id=1218141#c16
- Verification run: [12-SP5 JeOS](https://openqa.suse.de/tests/13103407#step/sshd/456) | [15-SP5 JeOS](https://openqa.suse.de/tests/13103405#step/rpm/149) | [12-SP5 Server-DVD](https://openqa.suse.de/tests/13103406#step/sshd/456) | [15-SP5 Server-DVD](https://openqa.suse.de/tests/13103404#step/sshd/436)

Remove leading comma

---

schedule/functional/extra_tests_gnome.yaml
schedule/functional/extra_tests_gnome_development.yaml
schedule/functional/extra_tests_textmode.yaml
schedule/functional/extra_tests_textmode_phub.yaml
schedule/functional/stack_tests_python.yaml
schedule/qam/12-SP1/mau-extratests-phub.yaml
schedule/qam/12-SP2/mau-extratests-phub.yaml
schedule/qam/12-SP3/mau-extratests-phub.yaml
schedule/qam/12-SP4/mau-extratests-phub.yaml
schedule/qam/12-SP5/mau-extratests-phub.yaml
schedule/qam/15-SP1/mau-extratests-phub.yaml
schedule/qam/15-SP2/mau-extratests-phub.yaml
schedule/qam/15-SP2/qam-gnome.yaml
schedule/qam/15-SP3/mau-extratests-phub.yaml
schedule/qam/15-SP3/qam-gnome.yaml
schedule/qam/15-SP4/mau-extratests-phub.yaml
schedule/qam/15-SP4/qam-gnome.yaml
schedule/qam/15-SP5/mau-extratests-phub.yaml
schedule/qam/15-SP5/qam-gnome.yaml
schedule/qam/15/mau-extratests-phub.yaml
schedule/qam/common/mau-extratests1.yaml

- Related ticket: https://progress.opensuse.org/issues/138401
- Needles: NO
Tumbleweed: [x86_64](https://openqa.opensuse.org/tests/3782553)
LEAP: [x86_64](https://openqa.opensuse.org/tests/3782554) | [aarch64](https://openqa.opensuse.org/tests/3782512)  |[ppc64le](https://openqa.opensuse.org/tests/3782567)
15-SP5: [x86_64](https://openqa.suse.de/tests/13062414) | [ s390x](https://openqa.suse.de/tests/13062412) | [aarch64](https://openqa.suse.de/tests/13062416)
15-SP4: [x86_64](https://openqa.suse.de/tests/13062431) | [ s390x](https://openqa.suse.de/tests/13062429) | [aarch64](https://openqa.suse.de/tests/13062433)
MR to schedule in 15-SP4/15-SP5:  https://gitlab.suse.de/qa-maintenance/qam-openqa-yml/-/merge_requests/678 
PR for LEAP and Tumbleweed: …

Move all python related to tests to new test suite

---

data/journal_check/bug_refs.json

* **Following** errors in journal log can be whitelisted:
* ITS@0x8080000: Unable to locate ITS domain handle
* plugin /usr/sbin/sedispatch terminated unexpectedly
* Timed out waiting for device /dev/disk/by-label/ignition
* Timed out waiting for /dev/combustion/config
* Timed out waiting for device /UUID=xxxxxxxxxx
* [aarch64](https://openqa.suse.de/tests/13109378)
* [x86_64](https://openqa.suse.de/tests/13109551)
* [encrypted x86_64](https://openqa.suse.de/tests/13111822)

Whitelist some errors in journal log for SLE Micro 6.0

---

tests/security/swtpm/swtpm_env_setup.pm

Fixes: cfa8f1472 ("lib: Add helper for Raspberry Pi")
- https://openqa.suse.de/tests/13121082 https://openqa.suse.de/tests/13121083
- https://openqa.opensuse.org/tests/3826802 https://openqa.opensuse.org/tests/3826803
@lilyeyes @rfan1 Is this enough for testing? Or post what else I should run.
@ggardet FYI

swtpm_env_setup: Don't run enable_tpm_slb9670() twice

---

data/wicked/dhcp/dhcpd.conf
lib/mm_network.pm
lib/network_utils.pm
lib/utils.pm
tests/support_server/setup.pm

We were using an MTU of 1458 for our GRE tunnels for MM tests:
```
1500 (default eth MTU)
- 20 Bytes IPv4 header
-  4 Bytes GRE header
- 14 Bytes Ethernet header whithin GRE tunnel
-  4 Bytes Ethernet VLAN TAG header whithin GRE tunnel
=> 1458 Bytes
```
With some MM workers in PRG2 and NUE2 we need to take
the path MTU between our locations into account,
which is 1422 (78 Bytes overhead).
So we have a usable MTU of 1380 left.
Ticket: https://progress.opensuse.org/issues/152389

Lower MM MTU from 1458 to 1380

---

tests/jeos/firstrun.pm

sdboot configuration requests user interaction to confirm whether to use root password for encryption key.
- https://progress.opensuse.org/issues/152711
- Needles: https://github.com/os-autoinst/os-autoinst-needles-opensuse/pull/805
- Verification run: http://kepler.suse.cz/tests/22393#step/firstrun/8

jeos-firstboot: add encryption handler

---

tests/containers/podman_netavark.pm

* http://kepler.suse.cz/tests/22396#step/podman_netavark/1
* http://kepler.suse.cz/tests/22398#step/podman_netavark/1
disclaimer: https://bugzilla.opensuse.org/show_bug.cgi?id=1217683

MicroOS upgrade scenario still uses CNI as default

---

lib/Utils/Architectures.pm
lib/main_common.pm
lib/version_utils.pm
tests/jeos/firstrun.pm

It's JeOS like the others.
- Verification run: https://openqa.opensuse.org/tests/3829935#live

Add support for the JeOS-for-RISCV flavor

---

data/virtualization/autoyast/host_12.xml.ep
data/virtualization/autoyast/host_15.xml.ep

Main change:
Networking Configuration (interfaces Section):
Removed interface configurations in the networking setup, ensuring proper settings for network interfaces.
Partitioning Configuration (partitioning Section): Optimized the disk device selection by using /dev/disk/by-id/ with a device ID, providing flexibility for different hardware. In the partition section, removed an unnecessary partition block, making the configuration more concise.
Other changes.
IOMMU setting based on CPU type.
progress ticket: https://progress.opensuse.org/issues/152747
- Related ticket: https://progress.opensuse.org/issues/152747

Enhance AutoYast Configuration

---

tests/installation/disable_grub_timeout.pm

Add workaround for bug#1158557 as it causes failure when migrating Leap 15.5 to 15.6
- Related ticket: https://progress.opensuse.org/issues/133211
- Verification run: http://falafel.suse.cz/tests/1398

Add workaround for bug#1158557 in disable_grub_timeout

---

lib/containers/container_images.pm

The sles-ltss containers are not providing a SLE_BCI repository anymore, so don't restrict to it.
- Related ticket: https://progress.opensuse.org/issues/152074

only do explicit install on SLE_BCI repo for dists that have them

---

schedule/staging/btrfs_maintenance-staging.yaml
tests/console/btrfs_balance.pm

Proposal for a new test that creates an un-balanced BTRFS raid0 filesystem and checks functionality of the related user space tools to get a balanced volume.
- Related ticket: https://progress.opensuse.org/issues/137804
- Needles: n/a
- https://openqa.suse.de/tests/13103511
- https://openqa.suse.de/tests/13103512
- https://openqa.suse.de/tests/13103513

New test: btrfs balance functionality 

---

tests/console/sudo.pm

Fix for sudo on Azure for SLE 15-SP4 (non-BYOS), where the expected user is root.
- Related ticket: https://progress.opensuse.org/issues/152845
- Related to: https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/18339
- Verification run: [15-SP4 Server](https://openqa.suse.de/tests/13136556) | [15-SP4 Azure-Basic](https://openqa.suse.de/tests/13136557) | [15-SP4 Azure-BYOS](https://openqa.suse.de/tests/13136558) | [15-SP4 Azure-Basic aarch64](https://openqa.suse.de/tests/13136559) | [15-SP4 Azure-Standard](https://openqa.suse.de/tests/13136560) | [15-SP4 EC2-BYOS](https://openqa.suse.de/tests/13136561) | [15-SP5 Azure-BYOS](https://openqa.suse.de/tests/13136562) | [15-SP5 Azure-Basic](https://openqa.suse.de/tests/13136563) | [15-SP3 …

Fix sudo on 15-SP4

---

tests/kernel/install_ltp.pm

Reboot scheduled on JeOS RPI by enable_tpm_slb9670() after slb9670 DTS installation fails on some reason. Avoid it for other tests (JeOS on RPI runs various LTP runtests) so that they don't fail.
Even the issue is fixed, it's still better to run it only on IMA (reboot is unnecessary slowdown for other tests).
Verification run: https://openqa.opensuse.org/tests/3830657

install_ltp: Install TPM DTS only on LTP IMA tests

---

tests/smt/smt_server_install.pm

Maybe before were broken dependencies on some version, but now smt pattern does install mariadb and following try to install mariadb again does just mess with mariadb versions
- Related ticket: https://openqa.suse.de/tests/13136367#step/smt_server_install/33
- Verification run: https://openqa.suse.de/tests/13136510

Do not install mariadb after smt pattern

---

tests/console/rsync_server.pm

In the past, the package installed an /etc/rsyncd.secrets file with mode 0600.
The test then added credentials there using echo user:pass > /etc/rsyncd.secrets
(preserving the mode of the file)
The package changed to install template config to /usr/etc. As the file now does
not exist in /etc, echo creates a new file with mode 644 - which in turn is
denied by rsync's default config (strict modes on)
- Related ticket: https://progress.opensuse.org/issues/152891
- Needles: N/A
- Verification run: NONE

rsync_server: ensure /etc/rsyncd.secrets has mode 600

---

tests/console/firewalld.pm

Fixed the firewalld test in both 15-SP6 and LEAP
- Related ticket: https://progress.opensuse.org/issues/152631
- Needles: NO
[Tumbleweed](https://openqa.opensuse.org/tests/3824418#) | [15-SP5](https://openqa.suse.de/tests/13115002)| [15-SP6](https://openqa.suse.de/tests/13115421#) | [Leap](https://openqa.opensuse.org/tests/3827016#)

Fix firewalld test for 15-SP6

---

data/yam/autoyast/support_images/sles15sp4_install_gnome_all_patterns_aarch64.xml
data/yam/autoyast/support_images/sles15sp4_install_gnome_all_patterns_s390x.xml
data/yam/autoyast/support_images/sles15sp4_install_gnome_all_patterns_x86_64.xml
data/yam/autoyast/support_images/sles15sp4_install_gnome_default_patterns_aarch64.xml
data/yam/autoyast/support_images/sles15sp4_install_gnome_default_patterns_s390x.xml
data/yam/autoyast/support_images/sles15sp4_install_gnome_default_patterns_x86_64.xml
data/yam/autoyast/support_images/sles15sp4_install_minimal_default_patterns_aarch64.xml
data/yam/autoyast/support_images/sles15sp4_install_textmode_all_patterns_aarch64.xml
data/yam/autoyast/support_images/sles15sp4_install_textmode_all_patterns_s390x.xml
data/yam/autoyast/support_images/sles15sp4_install_textmode_all_patterns_x86_64.xml
data/yam/autoyast/support_images/sles15sp4_install_textmode_default_patterns_aarch64.xml
data/yam/autoyast/support_images/sles15sp4_install_textmode_default_patterns_s390x.xml
data/yam/autoyast/support_images/sles15sp4_install_textmode_default_patterns_x86_64.xml

SLES15SP4 went into ltss, so add ltss to sles15sp4 aytoyast profiles. The media installation profiles, no need to add ltss because the ltss can be registered by scc only.
- Related ticket: https://progress.opensuse.org/issues/152791
- Needles: n/a
- Verification run: [Create support images](https://openqa.suse.de/tests/overview?distri=sle&version=15-SP4&build=20231226-3&groupid=251); [Verify migration](https://openqa.suse.de/tests/overview?version=15-SP6&build=chcao-20231227&distri=sle)
- Related mr: [MR link](https://gitlab.suse.de/qa-maintenance/qam-openqa-yml/-/merge_requests/686)

Add LTSS to SLES15SP4 autoyast profiles

---

tests/qemu/qemu.pm

Terminal output now shows "socket units" instead of "basic system."
Created an appropriate needle to account for this.
- Related ticket: https://progress.opensuse.org/issues/152977
- Needles:    https://gitlab.suse.de/openqa/os-autoinst-needles-sles/-/blob/master/qemu-reached-target-socket-units-20231229.png
- Verification run: https://openqa.suse.de/tests/13168934#

Added socket units needle

---

tests/wsl/prepare_wsl.pm

Increase the timeout value for an assert_screen of WSL installation, which is taking longer than usual.
- Related ticket: https://progress.opensuse.org/issues/152927
- https://openqa.suse.de/tests/13164962#
- https://openqa.suse.de/tests/13164967#
- https://openqa.suse.de/tests/13164968#
- https://openqa.suse.de/tests/13164995#
- https://openqa.suse.de/tests/13164996#
- https://openqa.suse.de/tests/13165001#

Increase prepare_wsl timeout.

---

lib/LTP/utils.pm

Fix error when LTP_PKG is not set:
Use of uninitialized value $pkg in pattern match (m//) at lib/LTP/utils.pm line 69.
LTP::utils::want_ltp_32bit() called at lib/LTP/utils.pm line 75
LTP::utils::get_ltproot() called at tests/kernel/install_ltp.pm line 227
install_ltp::install_from_git() called at tests/kernel/install_ltp.pm line 330

LTP: Fix uninitialized value $pkg

---

lib/repo_tools.pm

Behavior of this failure is random, first run all tests passed without retry, now I restarted two jobs they had to retry both.
- Related ticket: https://bugzilla.suse.com/show_bug.cgi?id=1218084
- Verification run: https://openqa.suse.de/tests/overview?arch=&flavor=&machine=&test=qam_rmt&modules=&module_re=&group_glob=&not_group_glob=&distri=sle&build=20240102-1&groupid=414

Workaround for rmt scc cred timeout bsc#1218084

---

tests/containers/podman_netavark.pm

Some PC instances can have multiple IPs or multiple active interfaces.
In order to proceed with netavark sub tests, we just need to pick one of
them.
- [sle-15-SP6-Azure-BYOS-aarch64-Build0454-publiccloud_containers@64bit](https://openqa.suse.de/tests/13187899#step/podman_netavark/211)
- [sle-15-SP6-GCE-BYOS-x86_64-Build0425-publiccloud_containers@gce_n1_standard_2](https://openqa.suse.de/tests/13187904#step/podman_netavark/211)

Minor fixes for netavark test in PC

---

tests/microos/cockpit_service.pm

https://progress.opensuse.org/issues/152877
- Verification run: [cockpit_service](https://openqa.suse.de/tests/13185922#step/cockpit_service/2)
Please ignore the failed test module, it is a known one.

No need to reboot VM if no package update for sle-micro

---

tests/xfstests/install.pm
tests/xfstests/partition.pm

1. Add disk usage info by 'df -h'
2. round the value of loop device size to avoid long float number
- Related ticket: https://progress.opensuse.org/issues/152975
- https://progress.opensuse.org/issues/152613
- Needles: N/A
https://openqa.suse.de/tests/13168712#step/partition/60 (long float number of disk size)
http://10.67.133.133/tests/421#step/partition/59 (rounded disk size)
https://openqa.suse.de/tests/13187951 (create hdd xfstests)
https://openqa.suse.de/tests/13187978 (generic/128 passed)

xfstests: add disk usage info for debug

---

lib/YaST/workarounds.pm
lib/yast2_widget_utils.pm
tests/iscsi/iscsi_client.pm

- Description:
* Revert the [**PR_1828**](https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/1828) 
* Use a simple workaround while not making it too complicated for code.
- Related ticket: https://progress.opensuse.org/issues/152821
- Needles: 
-  iscsi_client_service-20240103
-  iscsi-initiator-discovery-startup-20240104
- 30 run for  [**mru-iscsi_client_normal_auth_backstore_lvm**](https://openqa.suse.de/tests/overview?build=hjluo%2Fos-autoinst-distri-opensuse%23redress_iscsi&version=15-SP4&distri=sle)

Fix refreshment issue for iscsi_client

---

tests/console/ncurses.pm

https://progress.opensuse.org/issues/153081
VR: 
[sles15](https://openqa.suse.de/tests/13193606#step/ncurses/7)
[sles12](http://openqa.suse.de/tests/13193619#step/ncurses/9)
[tw](https://openqa.opensuse.org/tests/3846433#step/ncurses/21)

Avoid bsc#1180307 in 'ncurses' test

---

tests/publiccloud/az_l8s_nvme.pm

The Azure machines of L type had Lsv3 filtered out, now included together with Lsv2.
- Related ticket: poo [152961](https://progress.opensuse.org/issues/152961)
- Verification run:  https://openqa.suse.de/tests/13165007

P.C. Azure L machine v3 allowed

---

lib/sles4sap_publiccloud.pm

Fix "SAPHanaSR-ScaleUp-PerfOpt" sporadical timed out on "wait_for_ssh" after/during doing "stop_hana()"; fix HANA SR - PC Azure sporadic pacemaker service does not restart.
Set HA_SBD_START_DELAY default to 60. This is the core fix. See MR: https://gitlab.suse.de/qa-css/openqa_ha_sap/-/merge_requests/597. 
Add wait_for_ssh(wait_stop => 1). It is better to add "Wait ssh disappear".
TEAM-8854 - [PC][15sp3][timebox] "SAPHanaSR-ScaleUp-PerfOpt" sporadically timed out on "wait_for_ssh" after/during doing "stop_hana()"
TEAM-8800) - [HANA SR - PC Azure][Sporadic] - pacemaker service does not restart
Experiments:
1. Tried to use `crash => "reboot &"` instead of `crash => "echo b > /proc/sysrq-trigger &"` to `crash` the os. This method works but it is not valid
2. Tried to set …

Fix "SAPHanaSR" random timed out on "wait_for_ssh"

---

tests/installation/ipxe_install.pm

Incorrect SCC server is used for virt tests on non-developing host. Replace SCC_URL with HOST_SCC_URL to fix it.
[sle12sp5 host](https://openqa.suse.de/tests/13208156)
[sle15sp6 host](https://openqa.suse.de/tests/13208164)   //fail at proxy scc registration as expected

Replace SCC_URL with HOST_SCC_URL for virt test host installation

---

tests/installation/bootloader_uefi.pm

- Related ticket: https://progress.opensuse.org/issues/153148
- Verification run: https://openqa.opensuse.org/tests/3855419#step/encrypt_lvm/5
**Please ignore the failed test module, it is a known issue**

Don't register to SCC for opensuse install

---

lib/publiccloud/basetest.pm

It appears that in case of k8s tests we can not do region required
because in this case we running all 3 providers within same job so
region need to hold 3 different value at the same time

Revert 8c93916 partially for k8s

---

lib/main_containers.pm
tests/containers/podman_integration.pm

Run upstream podman integration tests suite.
- Related ticket: https://progress.opensuse.org/issues/152575
- Verification runs (with `PODMAN_BATS_SKIP=120-load 125-import 250-systemd 255-auto-update 520-checkpoint`)
- x86_64: https://openqa.opensuse.org/tests/3858175
- aarch64: https://openqa.opensuse.org/tests/3858176
TODO:
- Add jobs to openSUSE
- Add jobs for SLE-Micro.
- Add jobs for SLES.
- Investigate failing skipped tests.

containers: Add upstream podman integration tests

---

data/generalhw_scripts/flash_sd.sh

Running jeos-ltp-syscalls@RPi4 on siodtw01 worker showed:
ssh root@localhost usbsdmux --direct /dev/usb-sd-mux/id-000000001223 host usbsdmux: usage of -s/-c/-d arguments is deprecated as the service/client split is no longer required. Please upgrade your scripts to not supply either of these arguments
This warning was added to usbsdmux in 04/2021
https://github.com/linux-automation/usbsdmux/commit/656e3d5ca46f6e7a707925707dc9504dcd18fb33 released in 0.2.0. Now there is 0.3.0.
data/generalhw_scripts/flash_sd.sh was written in 03/2020.  Other script data/generalhw_scripts/flash_sd_rootless.sh, which was added in 60e74b12a44379144924a7494ae173232b74f2a1 (2O22) did not use --direct option from the start. Test was verified to work without --direct, thus removed. …

flash_sd.sh: Remove deprecated --direct option

---

tests/security/selinux/enforcing_mode_setup.pm

If we don't do this then there are strange AVCs with no target class in the AVC log.  This can't be reproduced locally and is something specific to openQA. It makes no sense that this works, but it does
- Related ticket: https://bugzilla.suse.com/show_bug.cgi?id=1215303
- Verification run: https://openqa.suse.de/tests/12925602

Reboot system before relabeling it

---

lib/publiccloud/basetest.pm
lib/publiccloud/k8sbasetest.pm
tests/containers/push_container_image_to_pc.pm

publiccloud::aws_client/azure_client needs to demand PUBLIC_CLOUD_REGION
due to other places where we do not want to have defaults and want tests
to fail when region is not defined so this is workaround to keep variable
required for publiccloud::aws_client/azure_client but not for cases where
we using publiccloud::eks/ecr/acr which also must to init
publiccloud::aws_client/azure_client and in this case we CAN NOT define it
on job level because publiccloud::aws_client will be initialized
together with publiccloud::azure_client so same variable will need to have two different values

Proper fix of regression caused by 8c93916

---

data/autoyast_opensuse/opensuse_leap.xml.ep
schedule/functional/leap15_incidents/incident_update.yaml

https://progress.opensuse.org/issues/153166
VR: 
[leap 15.5 incidents](https://openqa.opensuse.org/tests/overview?arch=&flavor=&machine=&test=&modules=prepare_profile&module_re=&group_glob=&not_group_glob=&distri=opensuse&build=rfan0108&version=15.5#)
[leap 15.4 incidents](https://openqa.opensuse.org/tests/overview?distri=opensuse&build=rfan0109&version=15.4)
**Please ignore the failed test modules, they are known issues**
_Please merge https://github.com/os-autoinst/opensuse-jobgroups/pull/408 as well if everything is fine_

Move Leap 15.4/15.5 incidents installation tests to use autoyast

---

lib/y2lan_restart_common.pm

- Description:
- Remove  softfail for #bsc992113
- Related ticket: https://progress.opensuse.org/issues/151846
- Needles: N/A
-  [**test_result**](https://openqa.suse.de/tests/overview?version=15-SP6&build=hjluo%2Fos-autoinst-distri-opensuse%23yast_bond&distri=sle)

Remove softfail for #bsc992113

---

tests/xfstests/partition.pm
tests/xfstests/run.pm
variables.md

Add support for overlayfs testing
- Related ticket: https://progress.opensuse.org/issues/151283
- Needles: N/A
- Verification run: http://10.67.133.133/tests/435

xfstests: Add support for overlayfs testing

---

tests/jeos/firstrun.pm

- Related ticket: https://progress.opensuse.org/issues/152829
- Needles: Created on o3 already
- Verification run: https://openqa.opensuse.org/tests/3862281#live

jeos/firstrun.pm: If a TPM is present, acknowledge the TPM enrollment dialog

---

lib/main_containers.pm

The version of docker-compose is very outdated in 12sp3 which causes the test to fail
- Related ticket: https://progress.opensuse.org/issues/153385
- [12-SP3](https://openqa.suse.de/tests/13230813)
- [12-SP5](https://openqa.suse.de/tests/13230814)

Remove docker-compose for 12sp3

---

tests/transactional/host_config.pm

If the ALP repo is populated with multiple repositories, add them all.
`REPO_SLE_ALP={"ALP-Dolomite-1.0-x86_64-Build10.13-Media1","ALP-Dolomite-Unsupported-1.0-x86_64-Build10.13-Media1"}`
- ticket: [[Dolomite] test fails in host_config - fix multiple repo handler](https://progress.opensuse.org/issues/153382)
* http://kepler.suse.cz/tests/22441#step/host_config/31
* http://kepler.suse.cz/tests/22440#step/host_config/29

Handle multiple ALP dolomite repos

---

lib/sles4sap_publiccloud.pm
t/12_sles4sap_publicccloud.t
tests/sles4sap/publiccloud/qesap_terraform.pm

Change the code to expose 3 arguments to select different behaviors. It was internally implicitly done with settings before. Now setting has been moved to the test module level. It will allow the function to be used in more context, maybe driven by different settings. Not all the settings has been removed from within the function, just them that influence the composition of the playbook list. No significant behavioral changes. Only Native fencing feature has been restricted to Azure.
- Related ticket: [TEAM-8903](https://jira.suse.com/browse/TEAM-8903)
h2. Verification run: 
h2. HanaSR Azure native fencing
sle-15-SP4-HanaSr-Azure-Byos-x86_64-Build15-SP4_2024-01-11T05:03:13Z-hanasr_azure_test_sapconf_spn@64bit 
- http://openqaworker15.qa.suse.cz/tests/273752 FAILED after the deployment
- …

Reorganize create_playbook_section_list to use sub arguments

---

lib/containers/utils.pm

Newer versions of microos-tools install an alias man=man-online.
The 'command -v man' check in the interactive shell follows the alias
and reports it as known command. Subsequently, the test calls
bash -eox pipefail script.sh though, in which case script.sh does not
have access to the aliased commands. As a consequence, at this point,
'man' fails to be executed.
- Related ticket: Identified by openQA when testing SR of new microos-tools package
- Needles: N/A
- Verification run: https://openqa.opensuse.org/tests/3864126

containers: only run man if the actual command is present

---

lib/python_version_utils.pm
tests/console/python3_new_version_check.pm
tests/console/python3_setuptools.pm

and also refactor common functions used in the python3 tests.
- Related ticket: https://progress.opensuse.org/issues/152629
https://progress.opensuse.org/issues/138401
- Needles: No
Tumbleweed: [x86_64](https://openqa.opensuse.org/tests/3863171#)
SLE15-SP5: [x86_64](https://openqa.suse.de/tests/13230852) | [aarch64](https://openqa.suse.de/tests/13230850) | [s390x](https://openqa.suse.de/tests/13230851)
SLE15-SP4: [x86_64](https://openqa.suse.de/tests/13230855) | [aarch64](https://openqa.suse.de/tests/13230858) | [s390x](https://openqa.suse.de/tests/13230854)

Add 'zypper search' with strict Python3 package

---

data/virtualization/autoyast/host_15.xml.ep

After installing a new disk, both pegasus and galactica will have two disks. To ensure installation on the specified disk, World Wide Name (WWN) settings have been added.
- Related ticket:  https://progress.opensuse.org/issues/134447?issue_count=21&issue_position=15&next_issue_id=152789&prev_issue_id=153238#note-53
- Needles: n/a
- Verification run: [galactica](http://10.100.103.119/tests/611), [pegasus](http://10.100.103.119/tests/610)

Add 2 new wwn for mutil-disk server

---

lib/microos.pm
lib/opensusebasetest.pm
lib/utils.pm
tests/installation/boot_encrypt.pm

- Related ticket: https://progress.opensuse.org/issues/152829
- Needles: https://github.com/os-autoinst/os-autoinst-needles-opensuse/pull/807
* With TPM: http://10.168.4.192/tests/1443
* Without TPM: http://10.168.4.192/tests/1442
* ALP (turns out not to use microos/process_reboot but only transactional/process_reboot...): http://10.168.4.192/tests/1445

Support manual disk unlocking on MicroOS

---

lib/selinuxtest.pm

SLE Micro >= 6 is still identified as 'sle-micro'. The loaded SELinux policy however is the same as for ALP.
This change will make sure the correct file is loaded during the tests.
- Related ticket: https://progress.opensuse.org/issues/152679
- Verification run: https://openqa.suse.de/tests/13240110

Fix for POO#152679

---

products/sle/main.pm
tests/virt_autotest/guest_installation_run.pm
tests/virt_autotest/guest_upgrade_run.pm
tests/virt_autotest/update_package.pm

- Description:
SKIP reset_partition test module, current s390x LPAR have 42GIb disk pace. we have to skip reset_partition during OSD s390x test run now.  
SKIP reboot_and_wait_up_normal test module, 
- Related ticket: https://progress.opensuse.org/issues/135425
s390x
[gi-guest_developing-on-host_developing-kvm](http://10.67.129.59/tests/398) PASS
[gi-guest_sles12sp5-on-host_developing-kvm](http://10.67.129.59/tests/399) PASS
[gi-guest_sles15sp5-on-host_developing-kvm](http://10.67.129.59/tests/400) PASS
[gi-guest_developing-on-host_sles12sp5-kvm](http://10.67.129.59/tests/401) PASS
[gi-guest_developing-on-host_sles15sp5-kvm](http://10.67.129.59/tests/396) PASS
[prj4_guest_upgrade_sles12sp5_on_sles12sp5-kvm](http://10.67.129.59/tests/382) PASS …

virt_autotest: enhancement for 15sp6 s390x guest installation tests

---

tests/wsl/install/ms_win_firstboot.pm

- Related ticket: https://progress.opensuse.org/issues/153391
- Needles: https://github.com/os-autoinst/os-autoinst-needles-opensuse/blob/master/ms_win_firstboot-windows-access-to-browsing-data-20240109.png
- https://openqa.suse.de/tests/13245634
- https://openqa.suse.de/tests/13245639
Created a new needle for Windows 10 installation.
Fixed installation sequence by closing a window and opening Powershell.
Removed firstboot flag from the end of the test.

Fixed ms_win_installation test

---

lib/YaST/EFItools.pm
schedule/yast/autoyast_non_secure_boot.yaml
test_data/yast/autoyast/profiles/non_secure_boot.yaml
tests/console/verify_secure_boot.pm
tests/installation/verify_secure_boot_bios.pm

- Related ticket: https://progress.opensuse.org/issues/152395
- Needles: -
- Verification run: https://openqa.suse.de/tests/13225559

Check secure boot status with efivars

---

lib/maintenance_smelt.pm
lib/publiccloud/utils.pm
tests/publiccloud/transfer_repos.pm

Current implementation of  `is_embargo_update`  in master will always return False because OBS currently requires authentication and will redirect you to Login page so you won't get actual incident

Switch checks if incident is embargoed from OBS to smelt

---

schedule/qam/common/mau-extratests1.yaml
tests/console/dpdk.pm

schedule existing dpdk test on SLE 15-sp5
- Related ticket: https://progress.opensuse.org/issues/153053
- Verification run: https://openqa.suse.de/tests/13257032

Schedule existing dpdk test on SLE 15-sp5

---

tests/virt_autotest/esxi_open_vm_tools.pm
tests/virtualization/universal/open_vm_tools.pm
tests/virtualization/universal/patch_guests.pm
tests/virtualization/universal/upgrade_guests.pm

I have manually checked that flock is working and waiting for the guest to be released to start new test.
- Related ticket: https://progress.opensuse.org/issues/127367
- Needles: N/A
[12-SP3](https://openqa.suse.de/tests/overview?distri=sle&version=12-SP3&build=%3Atbaev%3A%3A12-SP3%3A%3Atest%3A&groupid=322)
[12-SP4](https://openqa.suse.de/tests/overview?distri=sle&version=12-SP4&build=%3Atbaev%3A%3A12-SP4%3A%3Atest%3A&groupid=322)
[12-SP5](https://openqa.suse.de/tests/overview?distri=sle&version=12-SP5&build=%3Atbaev%3A%3A12-SP5%3A%3Atest%3A&groupid=322)
[15-SP2](https://openqa.suse.de/tests/overview?distri=sle&version=15-SP2&build=%3Atbaev%3A%3A15-SP2%3A%3Atest%3A&groupid=322)
[15-SP3](https://openqa.suse.de/tests/overview?distri=sle&version=15-SP3&build=%3Atbaev%3A%3 …

check if VM guest is locked by test

---

tests/microos/image_checks.pm

https://progress.opensuse.org/issues/153451
https://jira.suse.com/browse/PED-3494
VR: http://openqa.suse.de/tests/13256872#step/image_checks/10

Fix left_sectors size on sle_micro 6.0

---

tests/microos/selfinstall.pm

https://progress.opensuse.org/issues/153457
VR: https://openqa.suse.de/tests/13239372#step/selfinstall/19
**Please ignore the failed test module, it is a known issue**

Don't need 'handle_uefi_boot_disk_workaround' in slem self-install

---

data/sles4sap/qe_sap_deployment/sles4sap_azure_generic_uri.yaml
lib/qesapdeployment.pm
lib/sles4sap_publiccloud.pm
t/09_qesapdeployment.t
t/12_sles4sap_publicccloud.t
tests/sles4sap/publiccloud/qesap_terraform.pm

Add option to force SUSEConnect usage in place of registercloudguest during registration for qe-sap-deployment.
It also needs to use role base registration playbook. This is needed to tests images uploaded in the cloud from IBS that are not known yet by the cloud reg service.
- Related ticket: [TEAM-8903](https://jira.suse.com/browse/TEAM-8903)
http://openqaworker15.qa.suse.cz/tests/273813 :green_circle: 
http://openqaworker15.qa.suse.cz/tests/273818 :green_circle:  (needs manual fix like HANA_KEYNAME) in http://openqaworker15.qa.suse.cz/tests/273818/file/deploy_qesap_terraform-sles4sap_azure_generic_uri.yaml it has `registration.yaml`. It fails but it is expected.  It calls `registercloudguest` like :
```
ERROR    OUTPUT:          fatal: [vmhana02]: FAILED! => {
ERROR    OUTPUT: …
```

Add force SUSEconnect registration option

---

tests/containers/bci_prepare.pm

In order to comply with PEP 668, we should use distro provided python packages whenever a system-wide installation is intended. Some of the sle versions do not include tox, therefore we need to use `pip`.
- ticket: https://progress.opensuse.org/issues/132338
* [sles15-image-bci-base_15.3_on_SLES_15-SP5](http://kepler.suse.cz/tests/22510)
* [rust-oldstable-image-rust_oldstable_on_SLES_15-SP1](http://kepler.suse.cz/tests/22512)
* [bci_busybox_podman@tw](http://kepler.suse.cz/tests/22513)
* [sles15-image-bci-base_15.3_on_SLES_15-SP2](http://kepler.suse.cz/tests/22509)
* [sles15-image-bci-base_15.3_on_SLES_15-SP3](http://kepler.suse.cz/tests/22511)
* [sles15-image-bci-base_15.3_on_SLES_15-SP4](http://kepler.suse.cz/tests/22508)

BCI: use distro python libs if possible

---

data/sles4sap/qe_sap_deployment/qesap_aws.yaml
data/sles4sap/qe_sap_deployment/qesap_aws_fencing.yaml
data/sles4sap/qe_sap_deployment/qesap_aws_sapconf.yaml
data/sles4sap/qe_sap_deployment/qesap_azure.yaml
data/sles4sap/qe_sap_deployment/qesap_azure_fencing_msi.yaml
data/sles4sap/qe_sap_deployment/qesap_azure_fencing_spn.yaml
data/sles4sap/qe_sap_deployment/qesap_azure_sapconf.yaml
data/sles4sap/qe_sap_deployment/qesap_azure_uri.yaml
data/sles4sap/qe_sap_deployment/qesap_gcp.yaml
data/sles4sap/qe_sap_deployment/qesap_gcp_fencing.yaml
data/sles4sap/qe_sap_deployment/qesap_gcp_sapconf.yaml
tests/sles4sap/qesapdeployment/configure.pm

Add two setting for the qesap regression:
- QESAPDEPLOY_REGISTRATION_PLAYBOOK allow to select the filename of the registration playbook, default is registration.
- QESAPDEPLOY_USE_SUSECONNECT control value for use_suseconnect Ansible argument of the registration_role playbook.
*Related ticket:* TEAM-8932
- http://openqaworker15.qa.suse.cz/tests/273990 :green_circle: 
- http://openqaworker15.qa.suse.cz/tests/274002
- http://openqaworker15.qa.suse.cz/tests/273991 :green_circle: 
qesap regression default settings trigger with not existing playbook filename `QESAPDEPLOY_REGISTRATION_PLAYBOOK=donalduck`
```
ERROR    Missing playbook: /root/qe-sap-deployment/ansible/playbooks/donalduck.yaml
4UPHd-1-
```
- http://openqaworker15.qa.suse.cz/tests/274003
`QESAPDEPLOY_REGISTRATION_PLAYBOOK` expect …

Add setting to configure registration playbook

---

lib/main_micro_alp.pm
schedule/security/selinux.yaml
tests/transactional/host_config.pm

ALP products are available in SCC and the repos should be fetched from SCC or proxySCC accordingly, not added manually from a variable.
[Staging default image](https://openqa.suse.de/tests/13258751#)
[Staging encrypted image](https://openqa.suse.de/tests/13259004)
[Dolomite](https://openqa.suse.de/tests/13259005#)
[SLE Micro 6.0](https://openqa.suse.de/tests/13259009#)

ALP: Don't add default repos manually, use SCC instead

---

data/journal_check/bug_refs.json

Added a new entry for the ALP issue in the journal_check test (bsc#1215377)
Verifcation Run:
[alp-1.0-Dolomite-Default-x86_64](https://openqa.suse.de/tests/13262292#)
[Staging: ALP](http://openqa.suse.de/tests/13262298#)

Add softfail for bsc#1215377 in ALP

---

data/sles4sap/qe_sap_deployment/mr_test_azure.yaml
data/sles4sap/qe_sap_deployment/mr_test_azure_uri.yaml
data/sles4sap/qe_sap_deployment/mr_test_ec2.yaml
data/sles4sap/qe_sap_deployment/mr_test_ec2_product.yaml
data/sles4sap/qe_sap_deployment/qesap_aws.yaml
data/sles4sap/qe_sap_deployment/qesap_aws_fencing.yaml
data/sles4sap/qe_sap_deployment/qesap_aws_sapconf.yaml
data/sles4sap/qe_sap_deployment/sles4sap_aws_generic.yaml
data/sles4sap/qe_sap_deployment/sles4sap_azure_generic.yaml
data/sles4sap/qe_sap_deployment/sles4sap_azure_generic_maintenance.yaml
data/sles4sap/qe_sap_deployment/sles4sap_azure_generic_uri.yaml

Remove the private_key from all Azure and Aws conf.yaml for the qe-sap-deployment tests.
Related to https://github.com/SUSE/qe-sap-deployment/pull/127
- sle-15-SP5-Qesap-Aws-Byos-x86_64-BuildLATEST_AWS_SLE15_5_BYOS-qesap_aws_saptune_test@64bit -> http://openqaworker15.qa.suse.cz/tests/274111  :green_circle: Test fails in Ansible `TASK [Configure cluster IP [aws]]` like the one this vr is cloned from. On the other side the Terraform warning is gone
```
DEBUG    OUTPUT: The root module does not declare a variable named "private_key" but a value
DEBUG    OUTPUT: was found in file "terraform.tfvars". If you meant to use this value, add a
DEBUG    OUTPUT: "variable" block to the configuration.
```
- sle-15-SP5-Qesap-Aws-Byos-x86_64-BuildLATEST_AWS_SLE15_5_BYOS-qesap_aws_sbd@64bit -> …

Remove private_key from qe-sap-deployment

---

tests/security/oscap_stig/oscap_xccdf_eval.pm

Stig test fails at  oscap_xccdf_eval#2. Asked Viktor on Slack and his suggestion was 
to add the failed rule to the expected results for now. 
He has a massive PR that will affect all oscap related tests.
- Verification run: https://openqa.suse.de/tests/13271066

Adding another failed rule to expected results

---

tests/containers/bci_prepare.pm

BCI tests are failing to register SDK as license pops up and needs to be accepted.
- ticket: https://progress.opensuse.org/issues/153652
- Verification run: http://kepler.suse.cz/tests/22534#step/bci_prepare/14

Accept SDK license in sle12sp5

---

lib/power_action_utils.pm

Ctrl-alt-del opens the shutdown dialog already, no need to run an obscure command.
- Verification run: https://openqa.opensuse.org/tests/3875528

lib/power_action_utils.pm: Use only ctrl-alt-del for shutdown

---

lib/containers/k8s.pm

Some of the pods are failing due to multiple reasons and we dont require them for our testing purposes. Therefore we would like to reduce to sporadic issues when starting k3s in for our container tests.
- ticket: https://progress.opensuse.org/issues/152753
* http://kepler.suse.cz/tests/22543#step/podman_pods/216
* http://kepler.suse.cz/tests/22544#step/kubectl/168
* http://kepler.suse.cz/tests/22542#step/helm_K3S/88

Limit k3s service pods

---

data/yam/autoyast/create_hdd_textmode_aarch64.xml
data/yam/autoyast/create_hdd_textmode_s390x.xml
data/yam/autoyast/support_images/sles15sp4_install_textmode_all_patterns_aarch64.xml
data/yam/autoyast/support_images/sles15sp4_install_textmode_all_patterns_s390x.xml
data/yam/autoyast/support_images/sles15sp4_install_textmode_all_patterns_x86_64.xml
data/yam/autoyast/support_images/sles15sp4_install_textmode_default_patterns_s390x.xml
data/yam/autoyast/support_images/sles15sp5_install_minimal_default_patterns_s390x.xml
data/yam/autoyast/support_images/sles15sp5_install_textmode_all_patterns_aarch64.xml
data/yam/autoyast/support_images/sles15sp5_install_textmode_all_patterns_s390x.xml
data/yam/autoyast/support_images/sles15sp5_install_textmode_all_patterns_x86_64.xml
data/yam/autoyast/support_images/sles15sp5_install_textmode_default_patterns_s390x.xml

Related ticket: https://progress.opensuse.org/issues/153043
Related MR: https://gitlab.suse.de/qa-maintenance/qam-openqa-yml/-/merge_requests/693
VRs: 
SP6: https://openqa.suse.de/tests/overview?build=sofiasyria%2Fos-autoinst-distri-opensuse%23rm_desktop&version=15-SP6&distri=sle 
SP5: https://openqa.suse.de/tests/overview?distri=sle&build=sofiasyria%2Fos-autoinst-distri-opensuse%23rm_desktop&version=15-SP5 
SP4: https://openqa.suse.de/tests/overview?version=15-SP4&build=sofiasyria%2Fos-autoinst-distri-opensuse%23rm_desktop&distri=sle

Remove desktop module from textmode ay profiles

---

tests/ha/hawk_gui.pm

Reverts os-autoinst/os-autoinst-distri-opensuse#18456 because of failures in the maintenance tests.
For example: https://openqa.suse.de/tests/13275543

Revert "Switch docker for podman in hawk_gui"

---

lib/Utils/Logging.pm

bzip2 isn't available in containers
https://progress.opensuse.org/issues/138131
VR: https://openqa.suse.de/tests/13278014#step/podman_firewall/138 (excepted failed as this is run in post_fail_hook)

Use gzip instead bz2 in export_logs_basic

---

data/virt_autotest/host_unattended_installation_files/autoyast/dev_host_12.xml.ep
data/virt_autotest/host_unattended_installation_files/autoyast/dev_host_15.xml.ep
data/virt_autotest/host_unattended_installation_files/autoyast_opensuse_kvm_one_disk.xml
data/virt_autotest/host_unattended_installation_files/autoyast_opensuse_kvm_two_disk.xml
data/virt_autotest/host_unattended_installation_files/autoyast_opensuse_xen_one_disk.xml
data/virt_autotest/host_unattended_installation_files/autoyast_opensuse_xen_two_disk.xml

- Related ticket: https://progress.opensuse.org/issues/138317
[vh082_autoyast_full_feature_tests](http://10.67.129.27/tests/208)
[vh082_autoyast_ltss_tests](http://10.67.129.27/tests/202)
[vh082_non_autoyast_host_installation](http://10.67.129.27/tests/200)
[vh081_autoyast_full_feature_tests](http://10.67.129.27/tests/215)
[vh081_non_autoyast_host_installation](http://10.67.129.27/tests/213)
[sle12sp5_on_non_UEFI_machines](http://openqa.suse.de/t13276160)

Support UEFI iPXE autoyast host installation for virt test

---

lib/y2_module_guitest.pm
tests/yast2_gui/yast2_instserver.pm

- Description:
-   Fix sporadic issues in yast2_instserver
- Related ticket: [**153379**](https://progress.opensuse.org/issues/153379)
- Related MR:  [**700**](https://gitlab.suse.de/qa-maintenance/qam-openqa-yml/-/merge_requests/700)
- Needles: N/A
- [**VR**](https://openqa.suse.de/tests/overview?build=hjluo%2Fos-autoinst-distri-opensuse%23extratests-yast2u&version=15-SP4&distri=sle) **_20/20 PASSED_**
-  Fixed
-  https://openqa.suse.de/tests/13239241#step/yast2_instserver/10
-  https://openqa.suse.de/tests/13239238#step/yast2_instserver/40
- https://openqa.suse.de/tests/13239257#step/yast2_instserver/10

Fix sporadic issues in yast2_instserver

---

tests/containers/podman_netavark.pm

The previous PR #18480 was mistakenly merged, this is a follow-up.
- Related ticket: https://bugzilla.suse.com/show_bug.cgi?id=1218937
- Verification run: https://openqa.suse.de/tests/13289134
- Related to: https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/18480

podman_netavark: conditionally rm containers.conf (contd.)

---

lib/y2_installbase.pm
tests/installation/licensing/verify_license_translations.pm

- Description: Revisit soft-failure [bsc#1203004](https://bugzilla.suse.com/show_bug.cgi?id=1203004), must be fail only for **GMC builds**
- Related ticket: [poo#151837](https://progress.opensuse.org/issues/151837)
- Verification run: [overview](https://openqa.suse.de/tests/overview?build=issues-151837)
- Related [PR#18441](https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/18441)

Revisit soft-failure bsc#1203004 for GMC

---

tests/console/system_prepare.pm

- Related ticket: https://progress.opensuse.org/issues/153589
- Needles: N/A
- Verification run: http://openqa.nue.suse.com/tests/13262644

No '-p' parameter needed for SUSEConnect to activate base product on migrated system

---

tests/containers/podman_netavark.pm

If CNI is default, it does not restore the backend configuration after config file removal.
* [sle15sp6](http://kepler.suse.cz/tests/22563#)
* [sle15sp5]()
* [sle15sp4](http://kepler.suse.cz/tests/22561#step/podman_netavark/281)
* [sle15sp3](http://kepler.suse.cz/tests/22570#step/podman_netavark/1)
* [sle-micro 6.0](http://kepler.suse.cz/tests/22569#step/podman_netavark/1)
* [sle-micro 5.4](http://kepler.suse.cz/tests/22564#step/podman_netavark/1)
* [Tumbleweed-JeOS](http://kepler.suse.cz/tests/22566#step/podman_netavark/1)
* [microos]()
* [container-host-old2microosnext@64bit]()

Netavark clean up is broken

---

lib/publiccloud/utils.pm
tests/publiccloud/patch_and_reboot.pm
tests/publiccloud/transfer_repos.pm

Optimization of patch_and_reboot moving sle-micro check, repodir in transfer_repos set uncoditional
- Related ticket: https://progress.opensuse.org/issues/137168 
- Needles:none
- Verification run: https://openqa.suse.de/tests/13290723

Optimization of patch_and_reboot and transfer_repos

---

tests/containers/podman_netavark.pm

sle-micro is switching to netavark backend as default
- http://kepler.suse.cz/tests/22583#

Migration podman network backends

---

tests/systemd_testsuite/prepare_systemd_and_testsuite.pm
tests/systemd_testsuite/runner.pm

As the systemd shipped on SLE cannot yet run the complete upstream systemd testsuite, we enable the feature to softfail only some specific sub-tests.
- Related ticket: https://progress.opensuse.org/issues/151738
- Needles: n/a
- Verification run:  https://openqa.suse.de/tests/13269669
(edit: added the ticket number to soft fail message)

Enable variable to softfail only some specific subtests

---

tests/publiccloud/hardened.pm

This test is already done in img-proof since https://github.com/SUSE-Enceladus/img-proof/pull/365
It's just burning money and increasing our carbon footprint since it always soft-fails because it lacks a workaround that adds swap.

pc: Remove test that is already done by img-proof

---

lib/opensusebasetest.pm
tests/boot/boot_to_desktop.pm

https://progress.opensuse.org/issues/153760
- Verification run: https://openqa.suse.de/tests/13270832
https://openqa.suse.de/tests/13271243#step/boot_to_desktop/17
**Please ignore the failed test module, it is a known issue**

Adapt svirt backend to be able to boot systems with root ssh disabled

---

lib/containers/common.pm

Force IPv4 for ping to workaround potential issues with IPv6 in infra.
- Related ticket: https://progress.opensuse.org/issues/154030
- Failing test: https://openqa.suse.de/tests/13307542
- Verification run: https://openqa.suse.de/tests/13308057

containers: Force IPv4 for ping

---

lib/qesapdeployment.pm

Revert part of the PC commit to update the tool image. Job using qe-sap-deployment are configured to use a fixed HDD for the pc_tool image. At the moment it is 51.
Partial revert of https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/18400
Related ticket: ???
- HANASR sle-15-SP4-Azure-SAP-BYOS-Incidents-x86_64-******-SAPHanaSR-ScaleUp-PerfOpt@az_Standard_E8s_v3 -> http://openqaworker15.qa.suse.cz/tests/274480 :green_circle: 
- MR_TEST sle-15-SP4-Azure-SAP-BYOS-Incidents-saptune-x86_64-*******-sles4sap_gnome_saptune_delete_rename@az_Standard_E8s_v3 -> http://openqaworker15.qa.suse.cz/tests/274481  :green_circle: 
-  QESAP REGRESSION sle-15-SP5-Qesap-Azure-Byos-x86_64-BuildLATEST_AZURE_SLE15_5_BYOS-qesap_azure_ansible_roles_test@64bit -> …

Revert py for qesap to 3.10

---

lib/filesystem_utils.pm
tests/xfstests/run.pm

Sometimes the blacklist and exclude group are all empty, and the $raw_list would be empty. Then the split will fails by uninitialized value.
- http://10.67.133.133/tests/437 (test without blacklist and grouplist works)
- http://10.67.133.133/tests/438 (test with grouplist works, changes not affect grouplist related tests)

xfstests: Fix uninitialized value

---

lib/y2_installbase.pm
tests/installation/release_notes_from_url.pm

- Related ticket: https://progress.opensuse.org/issues/151831
- Verification run: https://openqa.suse.de/tests/13290310

Add function to detect RC builds and update release_notes_from_url

---

lib/publiccloud/utils.pm
lib/utils.pm
tests/publiccloud/patch_and_reboot.pm
tests/publiccloud/transfer_repos.pm

Followup to PR 18454, SLEMicro pc updates fixes for img_proof issues.
The img_proof pubcloud test had some unpredictable and irregular impact from the new routine structure of named PR. In particular in some VR tests the test_sles_hardened.py remained blocked for an internl error, but also internal img_proof tests reboots losted the instance reference.  
This new structure better marks differences of new added code for `sle_micro` management, `else` using the original code, improving tests resilience.
- Related ticket: https://progress.opensuse.org/issues/137168
- Verification run: https://openqa.suse.de/tests/13314994
- More VR to follow

SLEMicro pc updates: fixes for img_proof issues

---

lib/sles4sap_publiccloud.pm

Remove local variables that are not needed.
- Related ticket:  https://jira.suse.com/browse/TEAM-8139
- sle-15-SP5-HanaSr-Azure-Byos-x86_64-Build15-SP5_2024-01-18T05:03:11Z-hanasr_azure_test_sbd@64bit -> http://openqaworker15.qa.suse.cz/tests/274239

Less variables for the is_hana_database_online

---

lib/publiccloud/utils.pm
tests/publiccloud/img_proof.pm

This PR is a hotfix for the hardened_test on img_proof:
- Fix the permissions on /etc/ssh/sshd_config
- Disable pam_apparmor (which is not even configured and has been [problematic](https://confluence.suse.com/display/SAP/Testing+of+Public+Cloud+Hardened+Images) in the past.  It prevents sudo from running inside pytest which is run by img-proof.
TODO:
- Generate the SCAP report and upload it (another PR).
Bugs opened:
- [openssh-server upgrade changes permissions for sshd_config from 0600 to 0640](https://bugzilla.suse.com/show_bug.cgi?id=1219100)
--
- Related ticket: https://progress.opensuse.org/issues/153982
- Verification run: https://openqa.suse.de/tests/13318097

Fix hardened tests on img_proof

---

tests/publiccloud/img_proof.pm

Add SCAP report from img-proof if available.
- Related ticket: https://progress.opensuse.org/issues/153982
- Verification run: https://openqa.suse.de/tests/13322519

pc: Add SCAP report from img-proof if available

---

tests/publiccloud/img_proof.pm

Finally a shiny SCAP report in:
https://openqa.suse.de/tests/13323447/file/img_proof-report.html
Related PR:
https://github.com/SUSE-Enceladus/img-proof/pull/372

pc: Add read permissions to SCAP report to download it

---

tests/publiccloud/img_proof.pm

Fix for failing test: https://openqa.suse.de/tests/13317903#step/img_proof/53

pc: Use ssh_script_run in case report path doesn't exist

---

lib/containers/common.pm

ping on SLE-12* doesn't support `-4` option.
Fix for failing tests:
https://openqa.suse.de/tests/overview?distri=sle&version=12-SP5&build=20240123-1&groupid=417
Verifications runs:
- sle-12-SP5-Server-DVD-Updates-s390x-Build20240123-1-docker_tests@s390x-kvm -> https://openqa.suse.de/t13329283

Fix for ping on SLE-12*

---

lib/main_containers.pm

In order to avoid connectivity issues, we need to enable coredns container in k3s server.
```
Defaulted container "rmt-app" out of: rmt-app, rmt-app-init (init)
error: unable to upgrade connection: container not found ("rmt-app")
```
- Verification run: http://kepler.suse.cz/tests/22600#

Enable coredns for helm-rmt container image testing

---

lib/publiccloud/provider.pm

Tell img-proof to generate report on hardened images.
Related PR: https://github.com/SUSE-Enceladus/img-proof/pull/372
- Related ticket: https://progress.opensuse.org/issues/153982
- Verification run: https://openqa.suse.de/tests/13331175#

pc: Tell img-proof to generate report on hardened images

---

lib/y2_module_guitest.pm
tests/yast2_gui/yast2_instserver.pm

- Description:
-   Revisit launch_yast2_module_x11 to use parameter to apply workaround
-  https://progress.opensuse.org/issues/153379
- Needles: N/A
- [**15sp5**](https://openqa.suse.de/tests/overview?distri=sle&build=hjluo%2Fos-autoinst-distri-opensuse%23gui_refresh_2nd&version=15-SP5)
- [**15sp4**](https://openqa.suse.de/tests/overview?distri=sle&build=hjluo%2Fos-autoinst-distri-opensuse%23gui_refresh_2nd&version=15-SP4)
- [**15sp3**](https://openqa.suse.de/tests/overview?distri=sle&build=hjluo%2Fos-autoinst-distri-opensuse%23gui_refresh_2nd&version=15-SP3)

Revisit launch_yast2_module_x11 to use parameter to apply workaround

---

data/virt_autotest/kubevirt_tests/config.toml.tmpl
data/virt_autotest/kubevirt_tests/full-tests.conf
data/virt_autotest/kubevirt_tests/node-helper.yaml
tests/virt_autotest/kubevirt_tests_agent.pm
tests/virt_autotest/kubevirt_tests_server.pm

1. bsc#1217658 - add config file to enable `device_ownership_from_security_context` CRI option
2. bsc#1217660 - skip test case "hugepages-2Mi with passt enabled" & "virtiofs VirtIO-FS with multiple PVCs should be successfully started and accessible with passt enabled"
3. Create a tmpfs mount point '/var/provision/kubevirt.io/tests' for kubevirt agent test module
- Related ticket: https://progress.opensuse.org/issues/133598
- Verification run: http://10.67.129.96/tests/2696

Test changes for kubevirt v1.1.0

---

data/autoyast_qam/15_installtest.xml.ep

Allow LTSS for SLED 15-sp4 install-test image creation
- Related ticket: https://progress.opensuse.org/issues/154081
- Verification run: https://openqa.suse.de/tests/13328880#

Enable LTSS for SLED 15-SP4

---

lib/containers/container_images.pm

Containers: zypper install using SLE_BCI from 15-SP4 shall be skipped for LTSS in Latest.
See other info in https://progress.opensuse.org/issues/154159#note-2.
- Related ticket: https://progress.opensuse.org/issues/154159
- Needles:N/A
- Verification run: see body posts

Containers: zypper install skipped for LTSS latest

---

tests/publiccloud/cloud_netconfig.pm

This PR does expand existing minimal cloud-netconfig test coverage to include GCE and EC2 alongside Azure.
- Related ticket: https://progress.opensuse.org/issues/136235
Azure: https://openqa.suse.de/tests/13356451
GCE: https://openqa.suse.de/tests/13356712
EC2: https://openqa.suse.de/tests/13356711

Expand cloud-netconfig test coverage to GCE and EC2

---

tests/installation/module_selection/select_nonconflicting_modules.pm

Quick fix for [unexpected popup dialog](https://openqa.suse.de/tests/13351512#step/addon_products_via_SCC_yast2/21) to satisfy dependency for `lifecycle-data-sle-module-python3` package.
[Verification run](https://openqa.suse.de/tests/13357532#)

Add python3 to avoid dependency popup

---

tests/installation/bootloader_zkvm.pm

[SUT hostname](https://openqa.suse.de/tests/13373142#step/bootloader_zkvm/32)
[VM instance](https://openqa.suse.de/tests/13373142#step/bootloader_zkvm/33)
[Guest ip](https://openqa.suse.de/tests/13373142#step/bootloader_zkvm/34)

Make s390x kvm setup information more visable

---

lib/virt_autotest/utils.pm
lib/virt_autotest/virtual_network_utils.pm
lib/virt_feature_test_base.pm
tests/virt_autotest/sriov_network_card_pci_passthrough.pm
tests/virt_autotest/validate_system_health.pm

- Disable log_level=1 in libvirt as there is log_filter defined. also refer to https://bugzilla.suse.com/show_bug.cgi?id=1217965#c8
- Save guest configuration file ealier for restorartion in post_fail_hook. Tests could fail at any time and guest configuration files could be required at that time. see failure: http://10.67.129.27/tests/204#step/sriov_network_card_pci_passthrough/222
- Fix uploading virt logs in post_fail_hook. logs are not uploaded in post_fail_hook currently, as they are overritten by logs in its following test modules. fg. https://openqa.suse.de/tests/13269602#downloads
[a failed test with logs uploaded](https://openqa.suse.de/tests/13284640#downloads)

Enhance and fix logging in virt automation tests

---

tests/jeos/firstrun.pm

https://progress.opensuse.org/issues/154309
- Verification run: https://openqa.suse.de/tests/13373033

Enable root ssh on slem 6.0 firstrun

---

tests/console/yast2_ftp.pm
tests/console/yast2_rmt.pm
tests/console/yast2_tftp.pm
tests/console/yast2_vnc.pm

Tumbleweed is using NetworkManager, YaST cannot configure the firewall when the system uses NetworkManager, so adapt yast2 modules tests of configuring firewall for Tumbleweed.
- Related ticket: https://progress.opensuse.org/issues/134078
- Needles: n/a
https://openqa.opensuse.org/tests/3846404#  (tumbleweed)
https://openqa.suse.de/tests/13193568# (sles)

Adapt yast2 modules tests of configuring firewall for Tumbleweed

---

tests/containers/podman_netavark.pm

Same situation as for PC, netavark dhcp proxy could not receive a lease.
Therefore when starting a container tests need to be careful what IPs
are being used.
- ticket: [Investigate failure of podman_netavark on
s390x](https://progress.opensuse.org/issues/152194)
- VR: https://openqa.suse.de/tests/13374393#step/podman_netavark/258

Use proxy server from s390x's network

---

lib/main_common.pm

Enable flatpak for SLE 15+, see ECO https://jira.suse.com/browse/PED-7568
- VR https://openqa.suse.de/tests/overview?distri=sle&build=ECO-7568&groupid=414

Enable flatpak tests for 15+

---

lib/opensusebasetest.pm

In [ bsc#1219294](https://bugzilla.suse.com/show_bug.cgi?id=1219294)  the error message was characterized as safe to ignore. This PR is adding it to the ignore list so failure is avoided: https://openqa.suse.de/tests/13365524#step/detect_yast2_failures/539
- Verification run: https://openqa.suse.de/tests/13381846

Add error message in detect_yast2_failures ignore list

---

tests/containers/podman_integration.pm

Add catatonit package to use in podman integration tests
Verification run: https://openqa.suse.de/tests/13382308 (failing because of other reason).

containers: Add catatonit package to use in podman integration tests

---

tests/console/python3_setuptools.pm

Cleanup already runs on post, remove call on test function
Force deletion during cleanup, would not consider failure if some dirs are leftover or were not present while cleaning up
- Related ticket: https://progress.opensuse.org/issues/154588
- Verification run: https://openqa.suse.de/tests/13391757

Fix python3-setuptools

---

lib/registration.pm

- Related ticket: https://progress.opensuse.org/issues/154120
- Verification runs:   https://openqa.suse.de/tests/overview?distri=sle&build=sofiasyria%2Fos-autoinst-distri-opensuse%23temp_s390&version=15-SP6

Add temporary s390x condition for suseconnect

---

tests/containers/helm.pm

- Related ticket: cURL 8.6.0 is stricter on cli parameters (https://openqa.opensuse.org/tests/3908674#step/helm_K3S/130)
- Needles: N/A
- Verification run: https://openqa.opensuse.org/tests/3908751#live

helm: Fix cURL parameters (create-dirs, not create-dir)

---

lib/LTP/utils.pm

`TMPDIR=/tmp` was set long time ago in 741f15a65 in early implementation of openQA LTP runner. I don't think it was needed even back then.
But later, when prepare_ltp_env() was added in deae63bb6, it was called more times, thus it overwrite `TMPDIR` set for some testsuited via LTP_ENV openQA variable.
NOTE: `TMPDIR` setup is needed e.g. for ltp_fs on Tumbleweed (e.g. for isofs) or for ltp_syscalls (e.g. for fallocate06 https://openqa.opensuse.org/tests/3908370#step/fallocate06/6 due https://github.com/linux-test-project/ltp/commit/3626124a42adfe536af2abff63213fa1ccc63795).
- Verification run: http://quasar.suse.cz/tests/3141#step/isofs/8
@mdoucha @czerw @acerv FYI

LTP: Don't set TMPDIR

---

tests/containers/rootless_podman.pm

Fix rootless_podman
- Related ticket: https://progress.opensuse.org/projects/jeos
- Verification run: https://openqa.suse.de/tests/13402287

Fix rootless_podman for JeOS 15-SP2

---

lib/qesapdeployment.pm
t/09_qesapdeployment.t
t/15_qesap_azure.t

Move all the az related methods in a single place within the qesapdeployment.pm library.
Add unit testing for some missing methods.
Move az related unit testing to file 15.
Fix some unit testing about code style, logging and settings usage.
- Related ticket: [TEAM-8439](https://jira.suse.com/browse/TEAM-8439)
- qesap regression  http://openqaworker15.qa.suse.cz/tests/275012
- HanaSr  http://openqaworker15.qa.suse.cz/tests/275013

Reorganize the Azure code in the qesap lib

---

tests/yast2_gui/yast2_security.pm

- Description:
* The module fails due to the yast2 window not being properly refreshed and showing the content. 
We can apply the existing workaround to avoid future failures
* [**154690**](https://progress.opensuse.org/issues/154690)
- Needles: 
* N/A
* [**_yast2_security_**](https://openqa.suse.de/tests/overview?distri=sle&build=hjluo%2Fos-autoinst-distri-opensuse%23yast2_security&version=15-SP6)

Apply the glitch workaround in yast2_security

---

lib/sles4sap_publiccloud.pm
t/12_sles4sap_publicccloud.t

Change the `registration` playbook to take an optional argument `use_suseconnect`, similar to the registration role.
- Related ticket: https://jira.suse.com/browse/TEAM-8980
https://openqa.suse.de/tests/13374416 
https://openqa.suse.de/tests/13375013 (EC2)
**NOTE**: Merge together with https://github.com/SUSE/qe-sap-deployment/pull/203

Enable use_suseconnect argument for registration.yaml

---

lib/sles4sap_publiccloud.pm

This pr removes a now false comment, after https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/18544 was merged.
- Related ticket: https://jira.suse.com/browse/TEAM-8980
- Verification run: it's just a comment

Remove deprecated comment

---

tests/hpc/slurm_db.pm

In the logs one can see:
Problem: mariadb104-10.4.30-8.5.46.aarch64 conflicts with mariadb provided by
mariadb-10.2.44-3.53.1...
Solution 1: Following actions will be done:
deinstallation of mariadb104-10.4.30-8.5.46.aarch64
deinstallation of mariadb104-errormessages-10.4.30-8.5.46.noarch
deinstallation of mariadb104-client-10.4.30-8.5.46.aarch64
Solution 2: do not install mariadb-10.2.44-3.53.1.aarch64
Which is a direct result of mariadb being already installed by slurm:
zypper -n in slurm_18_08 slurm_18_08-munge slurm_18_08-slurmdbd
...
(16/25) Installing: python3-mysqlclient-1.3.14-8.9.2.aarch64 [............done]
(17/25) Installing: mariadb104-10.4.30-8.5.46.aarch64 [............done]
(18/25) Installing: libhwloc5-2.0.0.1.11.5-4.2.aarch64 [.......done]
(19/25) Installing: …

HPC: Slurm-18 provides db as a dependency

---

lib/power_action_utils.pm
schedule/virt_autotest/default_install_svirt.yaml
schedule/virt_autotest/online_upgrade_sles_vmware.yaml
tests/installation/bootloader_svirt.pm

1. Create schedule/virt_autotest/default_install_svirt.yaml
2. Create schedule/virt_autotest/online_upgrade_sles_vmware.yaml
3. Set parameter UEFI=1 on openqa MACHINES 'svirt-vmware70'
4. Update tests/installation/bootloader_svirt.pm to skip bios boot order setup while UEFI booting
- Related ticket: https://progress.opensuse.org/issues/152917
- Related PR: https://github.com/os-autoinst/os-autoinst/pull/2424
default_install_svirt - https://openqa.suse.de/tests/13403750
online_upgrade_sles15sp5_vmware - https://openqa.suse.de/tests/13409542
textmode_svirt - https://openqa.suse.de/tests/13403752

Switch vmware tests to UEFI boot as default

---

lib/utils.pm

After discussion with Klaus for https://bugzilla.suse.com/show_bug.cgi?id=1217694, he just think to make the bug 'Won't fix' for it is just a cosmetic issue and doesn't affect functionality. So we don't need the soft failure any more.
- Related ticket: https://progress.opensuse.org/issues/151882
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/13410780#

Remove softfailure of bsc#950763

---

lib/qesapdeployment.pm
lib/trento.pm
t/08_trento.t
t/09_qesapdeployment.t
tests/sles4sap/publiccloud/qesap_ansible.pm
tests/sles4sap/qesapdeployment/deploy.pm

Remove usage of setting PUBLIC_CLOUD_PROVIDER from qesap_get_nodes_number and qesap_get_nodes_name methods. Convert them to arguments.
http://openqaworker15.qa.suse.cz/tests/275224 :green_circle: fails but it is fine, same failure of the original job ( `Configure cluster IP [gcp]` )
- **sle-15-SP5-Qesap-Azure-Byos-x86_64-BuildLATEST_AZURE_SLE15_5_BYOS-qesap_azure_ibsmirror_peering_test@64bit** http://openqaworker15.qa.suse.cz/tests/275227
- **sle-15-SP5-Qesap-Azure-Byos-x86_64-BuildLATEST_AZURE_SLE15_5_BYOS-qesap_azure_ansible_roles_test@64bit** -> http://openqaworker15.qa.suse.cz/tests/275228
- **sle-15-SP5-Qesap-Azure-Payg-x86_64-BuildLATEST_AZURE_SLE15_5_PAYG-qesap_azure_saptune_test_msi@64bit** -> http://openqaworker15.qa.suse.cz/tests/275229
- …

Remove PUBLIC_CLOUD_PROVIDER from qesap_get_nodes_*

---

lib/containers/container_images.pm

Fix skip zypper systemd install on LTSS
- Related ticket: https://progress.opensuse.org/issues/154825
- Verification run: [sles15-ltss-on-Leap-15.4](https://openqa.suse.de/tests/13412878), [sles15-ltss-on-Leap-15.5](https://openqa.suse.de/tests/13412879),  [sles15-ltss-on-centos](https://openqa.suse.de/tests/13412880), [sles15-ltss-on-liberty9](https://openqa.suse.de/tests/13412881), [sles15-ltss-on-rhel8](https://openqa.suse.de/tests/13412883), [sles15-ltss-on-ubuntu](https://openqa.suse.de/tests/13412927), [ sle-15-SP6-Online-x86_64](https://openqa.suse.de/tests/13412917), [ sle-15-SP5](https://openqa.suse.de/tests/13412924)

Skip zypper systemd install

---

tests/wsl/firstrun.pm

A new popup for OneDrive appears and breaks the needles. New logic has been added to click and close it in case it appears
- Related ticket: https://progress.opensuse.org/issues/154693
- Needles: https://github.com/os-autoinst/os-autoinst-needles-opensuse/blob/master/wsl-onedrive-popup-20240202.png
- https://openqa.suse.de/tests/13433421
- https://openqa.opensuse.org/tests/3915798
- https://openqa.opensuse.org/tests/3915799

OneDrive popup blocks tests

---

lib/LTP/WhiteList.pm

Secureboot tests now use two different implementations of downgrading livepatches, one custom by disabling update repo and running update, another through a standard KLP management tool. Both implementations need post-uninstall tests but the latter is not handled correctly by LTP whitelist because it's controlled by a new variable: `KGRAFT_DOWNGRADE`. Fix condition for removing livepatch post-uninstall suffix from LTP test names when the new uninstall method is used.
- Related ticket: https://progress.opensuse.org/issues/109476
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/13433436

LTP Whitelist: Add support for new livepatch downgrade variant

---

tests/sles4sap/hana_install.pm

MD5 sum check is now done up the "untared" archives piped directly from the `wget` command
- Verification run:  https://openqa.suse.de/tests/13435596#step/hana_install/39

MD5 sum check added on downloaded SAP HANA archives 

---

tests/containers/podman_integration.pm

Fixes podman upstream tests:
- Path for podman quadlet is different across podman versions
- Install skopeo in SLEM
- Use user-console for SLEM
- Fix PackageHub register call
---
- Related ticket: https://progress.opensuse.org/issues/153214
- Failing test: https://openqa.suse.de/tests/13435563#step/podman_integration/31
- Verification run: https://openqa.suse.de/tests/13437881 (Failing for other reasons)

slemicro: Fix PackageHub register call

---

tests/btrfs-progs/install.pm

grub2 autoboot on Micro 6.0 on aarch64. Thus use expected_grub=0 to workaround this.
- Related ticket: https://progress.opensuse.org/issues/154087
- Needles: N/A
https://openqa.suse.de/tests/13442038 (Marble)
https://openqa.suse.de/tests/13442039 (ALP)

btrfs-progs: workaround grub2 issue for installation

---

tests/console/yast2_nis.pm

Remove softfail bsc#1073281: failed to start NIS/YP clients to NIS domain binder
- Related ticket: https://progress.opensuse.org/issues/151903
- Verification run: https://openqa.suse.de/tests/13392168#

Remove softfail bsc#1073281: failed to start NIS/YP clients to NIS domain binder

---

tests/yast2_gui/yast2_keyboard.pm

The bsc#1142559 is closed as WONTFIX, so remove the soft-failure of bsc#1142559: Input command '/sbin/yast2 keyboard' on a non root user, the keyboard is started, but can not save any changes, so cancel the changes.
- Related ticket: https://progress.opensuse.org/issues/151900
- Needles: n/a
- Verification run: [15SP5](https://openqa.suse.de/tests/13442053#step/yast2_keyboard/26);  [15SP4](https://openqa.suse.de/tests/13442051#step/yast2_keyboard/26); [15SP3](https://openqa.suse.de/tests/13442124); [15SP2](https://openqa.suse.de/tests/13442108); [15SP1](https://openqa.suse.de/tests/13442132); [12-SP5](https://openqa.suse.de/tests/13442134)

Remove soft-failure of bsc#1142559 for yast2_keyboard test module

---

tests/installation/welcome.pm

self update can need more time, IMO due to slow network
```
13438390 | qam-minimal-full                   | sle    | 15-SP2  | failed | :32469:openssl-1_0_0
13438209 | qam-minimal-full                   | sle    | 15-SP2  | failed | :32466:openssl-1_1
13438182 | qam-minimal-full                   | sle    | 15-SP2  | failed | :32466:openssl-1_1
13437921 | qam-minimal-full                   | sle    | 15-SP2  | failed | :32469:openssl-1_0_0
13437920 | qam-minimal                        | sle    | 15-SP2  | failed | :32469:openssl-1_0_0
13437916 | qam-minimal                        | sle    | 15-SP2  | failed | :32466:openssl-1_1
13437915 | qam-minimal-full                   | sle    | 15-SP2  | failed | :32466:openssl-1_1
13436706 | qam-minimal-full                   | …
```

welcome: Increase timeout on ppc64le

---

tests/installation/partitioning_finish.pm

NTP syncing can take some time, again IMO slow network
```
id    |                     test                      |  distri  | version | result |        build        
----------+-----------------------------------------------+----------+---------+--------+---------------------
13442633 | cryptlvm                                      | opensuse | 15.5    | failed | 2024-02-06 09:22:19
13433914 | gnome                                         | opensuse | 15.5    | failed | 2024-02-05 12:21:21
13433913 | cryptlvm                                      | opensuse | 15.5    | failed | 2024-02-05 12:21:31
13433911 | cryptlvm                                      | opensuse | 15.5    | failed | 2024-02-05 12:21:32
13432550 | cryptlvm                                      | opensuse …
```

partitioning_finish: Increase timeout for partitioning

---

lib/oscap_tests.pm

Implemented feature to support different expected results on service packs. Now tests on SP6 will pass 
- Related ticket: https://progress.opensuse.org/issues/154696
- Verification run: https://openqa.suse.de/tests/13411774

Implemented feature to support different expected results on service packs

---

lib/oscap_tests.pm
tests/security/oscap_profile_tests/oscap_xccdf_remediate.pm

Fix for ansible GUI remediation - some ansible remediation rules switches from root-console to GUI and remediation fails.
After ansible remediation for STIG profile switching back to the root console.
- Related ticket: https://progress.opensuse.org/issues/154618
- Verification run: https://openqa.suse.de/tests/13433637

Fix for ansible GUI remediation

---

tests/containers/podman_integration.pm

1. Enable podman-remote tests on SLEM.
2. Remove mounts.conf
3. Install netavark to avoid using cni
- Related ticket: https://progress.opensuse.org/issues/153214
- Verification run: https://openqa.suse.de/tests/13444350

containers: Fixes for podman upstream tests on SLEM

---

lib/saputils.pm
lib/sles4sap.pm
lib/sles4sap_publiccloud.pm
t/09_qesapdeployment.t
t/12_sles4sap_publicccloud.t
t/14_qesap_ansible.t
t/15_qesap_azure.t
t/17_sles4sap.t
t/18_saputils.t

Rework get_hana_topology and function used by it to move the pure string parsing part of the `SAPHanaSR-showAttr --format=script` output to a separate and centralized place.
Change get_hana_topology return data format frm list of hash to hash of hash, remove the hosthame argument.
- Related ticket: TEAM-9022
- http://openqaworker15.qa.suse.cz/tests/275404 :green_circle: overall test is pass, changed code looks ok, most nested `enable_replication` composed cmd http://openqaworker15.qa.suse.cz/tests/275404#step/Stop_site_a-primary/87
- http://openqaworker15.qa.suse.cz/tests/275463
- http://openqaworker15.qa.suse.cz/tests/275405 :green_circle: code in the PR behaves properly. Overall result is FAIL, seems vmhana01 node is not healthy …

Centralize SAPHanaSR-showAttr parsing

---

tests/migration/online_migration/zypper_patch.pm
tests/migration/openldap_configuration.pm
tests/update/patch_sle.pm

Install openldap2 packages in SLES15SP3 migration regression cases
- Related ticket: https://progress.opensuse.org/issues/154912
- Verification run: https://openqa.suse.de/tests/13449058#
https://openqa.suse.de/tests/13449059

Install openldap2 packages in SLES15SP3 migration regression cases

---

data/journal_check/bug_refs.json

Ignore the output of truncating the dmi_memory_id.
- Related failure: e.g. https://openqa.suse.de/tests/13395352
- Verification run: https://duck-norris.qe.suse.de/tests/14281#step/journal_check/9 (unrelated failure)

Add ignore for truncation of dmi_memory_id

---

tests/containers/podman_integration.pm

Enable podman upstream tests in SLEM 5.4
- Related ticket: https://progress.opensuse.org/issues/153214
- Verification run: https://openqa.suse.de/tests/13447403

containers: Enable podman upstream tests in SLEM 5.4

---

data/journal_check/bug_refs.json

Ignore kernel warnings about clocksource skewing
- Related failure: https://openqa.suse.de/tests/13449279#step/journal_check/9
- Discussion: https://suse.slack.com/archives/C02DQJKULE4/p1707302944678129
- Verification run: https://duck-norris.qe.suse.de/tests/14287#step/journal_check/1 and https://duck-norris.qe.suse.de/tests/14288#step/journal_check/1

Ignore clocksource messages

---

tests/migration/openldap_configuration.pm

No need install openldap for regression 15sp3 jobs
- Related PR: https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/18607
- VR: https://openqa.opensuse.org/tests/3923570

No need install openldap for regression 15sp3 jobs

---

lib/main_common.pm

Fix poo#155146: rasdaemon is part of Server applications module since SLE 15.  We need to test it daily updates on SLE 15+ and also Tumbleweed.
- Related ticket: https://progress.opensuse.org/issues/155146
TW: https://openqa.opensuse.org/tests/3923359
SLE 15-SP1: https://openqa.suse.de/tests/13467405
SLE 15-SP2: https://openqa.suse.de/tests/13467431
SLE 15-SP3: https://openqa.suse.de/tests/13467403
SLE 15-Sp4: https://openqa.suse.de/tests/13467430
SLE 15-SP5: https://openqa.suse.de/tests/13467413
SLE 15-SP6: https://openqa.suse.de/tests/13467423

hpc: Add rasdaemon test to kernel extra testsuite

---

schedule/yast/skip_registration/skip_registration_15sp3.yaml
tests/installation/addon_products_sle.pm

The existing skip_registration schedule doesn't work for 15SP3. Adding a customized one.
- Related ticket: https://progress.opensuse.org/issues/154729
- Verification runs :  https://openqa.suse.de/tests/13450454
https://openqa.suse.de/tests/13450445
Merge before: https://gitlab.suse.de/qe-yam/openqa-job-groups/-/merge_requests/72/diffs

Add schedule and condition for 15SP3 skip_registration

---

lib/main_containers.pm
tests/containers/secret.pm

New testsuite for the secret subcommand in Podman
- Related ticket: https://progress.opensuse.org/issues/150857
- Comes from: https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/18414
- [Podman](https://openqa.suse.de/tests/13481843) :green_circle:
- [Docker (test not scheduled)](https://openqa.suse.de/tests/13469543) :green_circle:

New test for podman secret subcommand

---

tests/containers/secret.pm

The secret subcommands were added in podman 3.1.0 according to:
https://github.com/containers/podman/blob/main/RELEASE_NOTES.md#310
- Failing test: https://openqa.suse.de/tests/13508482#step/podman/67
- Verification run: https://openqa.suse.de/tests/13509671

containers: Skip podman secret test on podman < 3.1.0

---

data/console/test_openssl_nodejs.sh
schedule/qam/common/mau-extratests1.yaml

Fix and schedule openssl nodejs tests for SLE 15 SP4 and SP5
- Related ticket: https://progress.opensuse.org/issues/155083
15sp4 x86 https://openqa.suse.de/tests/13502006
15sp4 s390 https://openqa.suse.de/tests/13502015
15sp4 aarch https://openqa.suse.de/tests/13502016
15sp5 aarch https://openqa.suse.de/tests/13502017
15sp5 s390 https://openqa.suse.de/tests/13502018
15sp5 x86(full schedule) https://openqa.suse.de/tests/13502022

Fix and schedule openssl nodejs tests for SLE 15 SP4 and SP5

---

lib/containers/container_images.pm

Add --gpg-auto-import-keys to zypper ref in container
- Related ticket: https://progress.opensuse.org/issues/155149
- Failing test: https://openqa.suse.de/tests/13440585/modules/image_docker/steps/169
- Verification run: https://openqa.suse.de/t13511122

containers: Add --gpg-auto-import-keys to zypper ref in container

---

schedule/functional/extra_tests_qemu.yaml
tests/qemu/kvm.pm

* x86_64: https://openqa.opensuse.org/tests/3936149
* aarch64 on RPi4: https://openqa.opensuse.org/tests/3934887 (expected fail on KVM due to a bug in spec file of qemu which disabled KVM)

qemu kvm: Enable aarch64 test for bare metal only

---

lib/containers/engine.pm
lib/main_containers.pm
tests/containers/docker_firewall.pm
tests/containers/podman_firewall.pm
tests/containers/secret.pm
tests/containers/volumes.pm

This PR:
- Removes external containers on cleanup_system_host() because `podman prune` only removes stuff created by podman but not external tools like buildah, et al.
- Adds missing calls to cleanup_system_host() on the podman_firewall & docker_firewall modules.
- Adds missing container_factory calls to the volumes & secret modules.
- Runs the validate_btrfs module last, as it changes the storage driver, fills the disk, etc.
---
- Related ticket: https://progress.opensuse.org/issues/155419#note-1
- sle-15-SP1-JeOS-for-kvm-and-xen-Updates-x86_64-Build20240212-1-jeos-containers-podman@uefi-virtio-vga -> https://openqa.suse.de/t13513600 (failed test: https://openqa.suse.de/tests/13505861)
- opensuse-Tumbleweed-DVD-x86_64-Build20240212-ricardobranco777_revert_factory@64bi …

Container cleanup fixes

---

lib/sles4sap.pm
schedule/sles4sap/ase/test_ase.yaml
tests/sles4sap/ase_install.pm
tests/sles4sap/ase_test.pm

Add test modules to install SAP ASE and to perform some smoke tests on the installed software: check that the server is running, query it to get the installed SAP ASE version, stop and start the database server, query the cockpit service status and stop and start the cockpit.
Included with the test modules is a YAML schedule loading the new modules, and also the changes required for SAP ASE in `lib/sles4sap.pm`.
Also included in the PR is the change from the deprecated `saptune daemon` commands to the new `saptune service` commands, and minor typo fixes and formatting to the POD documentation in `lib/sles4sap.pm`.
- Related ticket: https://jira.suse.com/browse/TEAM-8934
- Needles: https://gitlab.suse.de/openqa/os-autoinst-needles-sles/-/merge_requests/1656
12-SP5: …

Add installation and smoke test for SAP ASE

---

tests/containers/secret.pm

- microos-Staging:I-Staging-DVD-x86_64-BuildI.549.1-container-host-microos@64bit-2G-HD40G -> https://openqa.opensuse.org/t3937961 (failing test: https://openqa.opensuse.org/tests/3937885#step/secret_podman/119)
- sle-micro-5.2-MicroOS-Image-Updates-s390x-Build20240213-1-slem_containers_selinux@s390x-kvm -> https://openqa.suse.de/t13519557 (failing test: https://openqa.suse.de/tests/13517592#step/secret_podman/109)

containers: Fix call to cleanup_system_host in secret module

---

lib/wickedbase.pm

Fix use of unitialized value in wickedbase::unique_macaddr(). 
See: https://openqa.suse.de/tests/13492603/logfile?filename=autoinst-log.txt
```
Use of uninitialized value in addition (+) at sle/lib/wickedbase.pm line 532.
wickedbase::unique_macaddr(t11_bridge_interface_legacy=HASH(0x55bfa4ead8a0)) called at sle/lib/wickedbase.pm line 561
wickedbase::setup_bridge(t11_bridge_interface_legacy=HASH(0x55bfa4ead8a0), "/etc/sysconfig/network/ifcfg-br0", "/etc/sysconfig/network/ifcfg-dummy0", "ifup") called at sle/tests/wicked/advanced/sut/t11_bridge_interface_legacy.pm line 26
t11_bridge_interface_legacy::run(t11_bridge_interface_legacy=HASH(0x55bfa4ead8a0), wicked::TestContext=HASH(0x55bfa4bcd5b0)) called at /usr/lib/os-autoinst/basetest.pm line 348
eval {...} called at …
```

wicked: fix use of uninitialized value

---

data/journal_check/bug_refs.json

As already investigated in the bug report, it is not a product issue, but a potential configuration issue on the DHCP server side. In any case, it is harmless, so it's ok to ignore it.
VR: http://openqa.suse.de/tests/13525356

Whitelist 1219229 - chronyd Could not add source

---

tests/security/check_kernel_config/dm_crypt.pm

Related ticket: https://progress.opensuse.org/issues/155266
- SP6 x86_64: https://openqa.suse.de/tests/13522739
- SP6 aarch64: https://openqa.suse.de/tests/13525711
- SP6 s390x: https://openqa.suse.de/tests/13525712
- SP5 x86_64: https://openqa.suse.de/tests/13525710
- SP4 x86_64: https://openqa.suse.de/tests/13525718

Do not grep for "kcryptd workqueues" in changelog

---

lib/db_utils.pm
tests/jeos/image_info.pm

Simplify the access check for the PostGREST database and introduce POSTGRES_DB variable for defining the target database for the image stats.
- Related ticket: https://progress.opensuse.org/issues/138371
- Verification run: https://openqa.opensuse.org/tests/3938739#step/image_info/8 and http://k2.qe.suse.de/d/rga27zLVz/image-size?orgId=2
- Related PR: https://github.com/os-autoinst/opensuse-jobgroups/pull/426

Simplify database access check

---

lib/qesapdeployment.pm
t/09_qesapdeployment.t
tests/sles4sap/qesapdeployment/deploy.pm

**IMPORTANT**: Revert https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/18605 before merging this
Add function to retry `qesap_execute` is a certain error string is detected in the returned logs.
- Related ticket: https://jira.suse.com/browse/TEAM-9027
**sle-15-SP5-Qesap-Azure-Byos-x86_64-BuildLATEST_AZURE_SLE15_5_BYOS-qesap_azure_sapconf_test@64bit**:
http://openqaworker15.qa.suse.cz/tests/276071
passed without error
**sle-15-SP5-Qesap-Azure-Byos-x86_64-BuildLATEST_AZURE_SLE15_5_BYOS-qesap_azure_saptune_test@64bit**:
http://openqaworker15.qa.suse.cz/tests/276072
passed without error
**FORCED ERROR (invalid QESAPDEPLOY_CLUSTER_OS_VER) BUT NOT THE ERROR WE'RE SEARCHING FOR**:
http://openqaworker15.qa.suse.cz/tests/276073#step/deploy/16
We can see the …

Add qesap_execute retry function

---

tests/microos/image_checks.pm

Reverts os-autoinst/os-autoinst-distri-opensuse#18451
Reason: https://bugzilla.suse.com/show_bug.cgi?id=1219203

Revert "Fix left_sectors size on sle_micro 6.0"

---

data/containers/autoyast_containers.xml.ep

The AY profile is missing LTSS registration for eligible LTSS hosts.
- Related ticket: [Missing LTSS extension in 12-SP5, 15-SP1, 15-SP2 and 15-SP3 host images](https://progress.opensuse.org/issues/154174)
- Verification run: http://kepler.suse.cz/tests/22643#

Extend AY profile for container hosts

---

tests/sles4sap/publiccloud/hana_sr_takeover.pm

On prem tests wait by default for `cs_wait_for_idle` to finish in 120 seconds, which can be scaled using the `TIMEOUT_SCALE` setting. Similar tests in cloud service providers wait by default for 60 seconds, and we have observed some tests failing in this step. This commit increases the timeout to 120 seconds.
- Related ticket: https://jira.suse.com/browse/TEAM-9056
- Needles: N/A
- Verification run: None as it's only increasing a timeout.

Increase wait time for cs_wait_for_idle in CSP

---

schedule/yast/skip_registration/skip_registration_15sp3.yaml

The skip_registration fails for 15SP3 because of main.pm sets ADDONS to null as the MAIN_TEST_REPO is empty as the ltss module is not include din SCC_ADDONS, as this is a skip registation test and ltss needs registation. So the only option is to  set the vars in the yaml schedule because it is parsed after the main.pm. +ADDONS doesn't work here. Setting ADDONS='all-packages' because when set to 'desktop' it fails as it matches with a non high lighted desktop needle that is used in another module but has the same tag.
VR: https://openqa.suse.de/tests/13535185#details

Edit skip_registration schedule

---

tests/x11/gnomecase/nautilus_open_ftp.pm

The Enter key doesn't work on nautilus-ftp-login screen since from GNOME45 (bsc#1205589)
In recent SLE15SP6 builds, the GNOME was updated to 45, so we need to add workaround for bsc#1205589
- Related ticket: https://progress.opensuse.org/issues/154198
- Needles: already added when debugging on o.s.d
> - Wayland: https://openqa.suse.de/tests/13467020#
> - X11: https://openqa.suse.de/tests/13466991#
No verification runs needed for Tumbleweed since the workaround has already enabled for it.
No verification runs needed for Leap since the test suite is not enabled for it.

Add bsc#1205589 workaround for SLE16SP6

---

data/virtualization/autoyast/host_15.xml.ep

Progress ticket: https://progress.opensuse.org/issues/130766
Start debug log for modular libvirt from sles15SP6
- Related ticket: https://progress.opensuse.org/issues/130766
- Related jira ticket: https://jira.suse.com/browse/PED-4804
- Related document: https://confluence.suse.com/pages/viewpage.action?pageId=1241481218#Modularlibvirt:introduction&howto-Debuglogformodularlibvirt
- Needles: N/A

Start Modular libvirt Log from sles15SP6

---

tests/xfstests/run.pm
variables.md

1. Modify some code to higher test speed
2. Add an XFSTESTS_HIGHSPEED switch to get better performance but less stability, which could accurately be configured in stable tests
3. When VIRTIO_CONSOLE is enabled, use another API than send_key because send_key is not supported in virtio console.
- Related ticket: https://progress.opensuse.org/issues/154975
- Enable XFSTESTS_HIGHSPEED(also disable Heartbeat): https://openqa.suse.de/tests/13539724
The test time getting much faster, and could compare to the one without this PR: https://openqa.suse.de/tests/13365224
Test time 31:15 minutes->06:32 minutes
- a test without enabling XFSTESTS_HIGHSPEED(to prove it not affect tests without this setting): https://openqa.suse.de/tests/13539723

xfstests: Getting faster test speed

---

data/containers/Dockerfile

Root cause of why zypper was returning 106 in 12-SP5 container tests.
```
Retrieving repository 'SLE-12-SP5-GA-Desktop-nVidia-Driver' metadata [..
New repository or package signing key received:
Repository:       SLE-12-SP5-GA-Desktop-nVidia-Driver
Key Name:         NVIDIA Corporation <linux-bugs@nvidia.com>
Key Fingerprint:  9B763D49 D8A5C892 FC178BAC F5113243 C66B6EAE
Key Created:      Thu Jun 15 16:13:18 2006
Key Expires:      (does not expire)
Subkey:           F016EEAA03224CDD 2006-06-15 [does not expire]
Rpm Name:         gpg-pubkey-c66b6eae-4491871e
Do you want to reject the key, trust temporarily, or trust always?
[r/t/a/? shows all options] (r): r
error]
Repository 'SLE-12-SP5-GA-Desktop-nVidia-Driver' is invalid.
[container-suseconnect-zypp:SLE-12-SP5-GA-Desktop-nVidia-Driver|htt …
```

Import repo keys

---

tests/sles4sap/publiccloud/qesap_ansible.pm

To mitigate TEAM-9068 we need to disable the retries for ansible untill we can make it idempotent.
- Related ticket: TEAM-9068
- Verification run: https://openqa.suse.de/tests/overview?distri=sle&build=no_ansible_retry
https://openqa.suse.de/tests/13544223 The restart is blocked
https://openqa.suse.de/tests/13544224 Unrelated failure
The rest are green

Remove ansible retry function for MU tests

---

lib/main_containers.pm

Skip compose tests on ppc64le.
- Failing test: https://openqa.opensuse.org/tests/3947578#step/podman_compose/37

containers: Skip compose tests on ppc64le

---

lib/main_containers.pm

Skip docker-compose test on Staging
Failing test: https://openqa.opensuse.org/tests/3947585#step/podman_compose/42

containers: Skip docker-compose test on Staging

---

data/journal_check/bug_refs.json

* **An** old issue ```Feb 19 02:31:21.618612 s390kvm090 sshd[2186]: error: kex_exchange_identification: Connection closed by remote host``` started occurring to SLE Micro 6.0 test. Please refer to [example](https://openqa.suse.de/tests/13542740#step/journal_check/12).
* **This** issue can be whitelisted safely.
* [sshd error is gone](https://openqa.suse.de/tests/13542811)

Whitelist sshd kex_exchange_identification error for SLE Micro 6.0

---

lib/sles4sap_publiccloud.pm
t/12_sles4sap_publicccloud.t
tests/sles4sap/publiccloud/hana_sr_schedule_primary_tests.pm
tests/sles4sap/publiccloud/hana_sr_takeover.pm
tests/sles4sap/publiccloud/hana_sr_test_secondary.pm
tests/sles4sap/publiccloud/qesap_ansible.pm

- Related ticket: https://jira.suse.com/browse/TEAM-9012
sle-15-SP5-HanaSr-Azure-Byos-x86_64-Build15-SP5_2024-02-19T05:03:10Z-hanasr_azure_test_sbd@64bit 
- http://openqaworker15.qa.suse.cz/tests/276313 :green_circle: 
- http://openqaworker15.qa.suse.cz/tests/276331 :green_circle: 
sle-15-SP5-HanaSr-Azure-Byos-x86_64-Build15-SP5_2024-02-19T05:03:10Z-hanasr_azure_test_msi@64bit 
- http://openqaworker15.qa.suse.cz/tests/276314 :green_circle: 
The deployment is using `site_a` 
```
DEBUG    OUTPUT: TASK [../roles/sap_ha_install_hana_hsr : SAP HSR - Register secondary node to HANA System Replication] ***
...
DEBUG    OUTPUT:     "cmd": "source /usr/sap/HA0/home/.sapenv.sh && /usr/sap/HA0/HDB00/exe/hdbnsutil -sr_register --name=site_b --remoteHost=vmhana01 --remoteInstance=00 …
```

Always get site_name from settings

---

tests/hpc/rasdaemon.pm

Fix poo#155536: Error injection was tested on 15-SP2 only. Condition
was extended with 15-SP6 and Tumbleweed. TODO related to arm was
removed. Error injection had different behavior on workers with AMD
and Intel cpus. Status code didn't work on AMD cpus. New status
0x9c00000000000000 should work on both platforms and represents
corrected error.
- Related ticket: https://progress.opensuse.org/issues/155536
- 15-SP2 https://openqa.suse.de/tests/13545128
- 15-SP3 https://openqa.suse.de/tests/13545133
- 15-SP4 https://openqa.suse.de/tests/13545135
- 15-SP5 https://openqa.suse.de/tests/13545143
- 15-SP6 https://openqa.suse.de/tests/13545151
- TW https://openqa.opensuse.org/tests/3947149
- 15-SP2 https://openqa.suse.de/tests/13545127
- 15-SP3 …

rasdaemon: Fix error injection check

---

lib/Utils/Logging.pm

Most of the post fail hooks are failing because the tests assume that coredumpctl is installed everywhere by default
- Verification run: http://kepler.suse.cz/tests/22658#live

Extract coredumps only when coredumpctl is available

---

tests/containers/privileged_mode.pm

Due to netavark issues and podman not available in SLE12-SP3 I'll comment this part by now in that version
- Related ticket: https://progress.opensuse.org/issues/155422
- https://openqa.suse.de/tests/13556701
- https://openqa.suse.de/tests/13556738

Skip running podman inside container in 12-SP3

---

tests/sles4sap/hana_cluster.pm

Fix hana_cluster node2 register error by adding sleep 10
TEAM-9052 - Secondary node is not register with hana cluster and primary node due to new hana version
- Related ticket: https://jira.suse.com/browse/TEAM-9052
- Needles: NA
Using SPS07rev73 to to VRs for maintenance jobs:
* Maintenance: SAP/HA Incidents / Maintenance: SLE 15 SP3 SAP Incidents
15sp3 x86 qam-SAPHanaSR_ScaleUp_PerfOpt_WMP_node01, cloned testid=13557819
It failed on hana_cluster before (https://openqa.suse.de/tests/13563447#step/hana_cluster/13, or see TEAM-9052).
https://openqa.suse.de/tests/13571786#dependencies ("sleep 180" passed)
https://openqa.suse.de/tests/13571757#dependencies ("sleep 30" passed)
https://openqa.suse.de/tests/13571895#dependencies ("sleep 30" passed)
* Maintenance: QR / …

Fix hana_cluster node2 register error

---

schedule/yast/select_modules_and_patterns/select_modules_and_patterns_aarch64.yaml

Fixes this:
https://openqa.suse.de/tests/13565314#step/validate_installed_patterns/5
by adding `select_visibile_patterns_from_bottom` test module to the YAML schedule.
[Verification run](https://openqa.suse.de/tests/13574263)

Quick fix for missing pattern installation on aarch64

---

tests/containers/podman_pods.pm
tests/containers/run_container_in_k3s.pm

Move k3s part away from podman_pods
- Related ticket: https://progress.opensuse.org/issues/152593
- Verification run: [sle-micro-6.0-Base-x86_64](https://openqa.suse.de/tests/13574345), [sle-micro-6.0-Base-aarch64](https://openqa.suse.de/tests/13574355),  [sle-micro-5.5-Default-Updates-x86_64](https://openqa.suse.de/tests/13574360) ,  [sle-15-SP5_x86_64](https://openqa.suse.de/tests/13574350), [sle-15-SP4_x86_64](https://openqa.suse.de/tests/13574361)

Move k3s part away from podman_pods

---

lib/virt_autotest/virtual_network_utils.pm

* **Network** interface attached to public facing network requires more time to get ip address assigned, for example, virtual machine employs host bridge network may fail to get ip address assigned very quickly. Please refer to [this failure](https://openqa.suse.de/tests/13084938#step/libvirt_host_bridge_virtual_network/93).
* **This** might be related to the huge number of devices in the network and subsequent conflicts detecting when a new device joins. It requires additional time to finish. 
* **Extend** timeout value to wait longer may help solve the problem.
* [verification run 01](https://openqa.suse.de/tests/13542933)
* [verification run 02](https://openqa.suse.de/tests/13542934)
* [verification run 03](https://openqa.suse.de/tests/13564605)
* [verification …

Wait longer for network interface attached to public facing network

---

lib/main_containers.pm
tests/containers/podman_netavark.pm

Last update for SLEM PC aggregates: added netavark as default also for SLEM5.5 in pcloud, and skipped cni tests.
- Related ticket: https://progress.opensuse.org/issues/137168
- Verification run: See PR body.

podman: network backend control/switch added

---

lib/wickedbase.pm
tests/wicked/before_test.pm

I guess, because of the havy use of `reload-last-good-snapshot` feature, the journal somehow isn't consistent.
E.g. we are storing a `journalctl -b -o short-precise` in the pre_test_hook and one in the post_test_hook.
So with this, the journal of pre, should be a subset of post, but it wasn't
see:
```bash
wget https://openqa.suse.de/tests/13547853/file/t16_bridge_ifreload_physical_post.tar.gz
wget https://openqa.suse.de/tests/13547853/file/t16_bridge_ifreload_physical_pre.tar.gz
ls -1 * | xargs -I F tar -zxvf F
meld t16_bridge_ifreload_physical_pre/journalctl.log t16_bridge_ifreload_physical_post/journalctl.log
```
here ` t16_bridge_ifreload_physical_post/journalctl.log` should start with the same log as `t16_bridge_ifreload_physical_pre/journalctl.log`. …

wicked: Fix incomplete journal logs

---

data/autoyast_sle15/autoyast_sle-micro_updates.xml.ep

- Description: adding `<kdump>` to fix soft-failure [bsc#1195060](https://bugzilla.suse.com/show_bug.cgi?id=1195060)
- Related ticket: [poo#](https://progress.opensuse.org/issues/153619)
- Verification run: [overview](https://openqa.suse.de/tests/overview?build=issues-153619)

Add <kdump> section in autoyast_sle-micro_updates.xml.ep

---

lib/sles4sap_publiccloud.pm
t/12_sles4sap_publicccloud.t
tests/sles4sap/publiccloud/cluster_add_repos.pm

Sometimes zypper is locked, so this pr adds a function to wait until it is released or for a specified amount of time.
- Related ticket: https://jira.suse.com/browse/TEAM-9059
https://openqa.suse.de/tests/13580534 (zypper wasn't locked)
https://openqa.suse.de/tests/13564155 (zypper wasn't locked)
https://openqa.suse.de/tests/13565334 (zypper wasn't locked)
https://openqa.suse.de/tests/13566890 (zypper wasn't locked)

Add function to wait for zypper if needed

---

tests/sles4sap/hana_cluster.pm

TEAM-9052 - Secondary node is not register with hana cluster and primary node due to new hana version
In pr https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/18716 I added `sleep bmwqemu::scale_timeout(10);` but it is not enough for ppc64le test case SAPHanaSR_ScaleUp_PerfOpt_WMP_node. So add more time.
- Related ticket: https://jira.suse.com/browse/TEAM-9052
- Needles: NA
-15sp6 ppc64le, sles4sap_scc_textmode_hana_cli, version SPS07rev73_IMDB76
http://openqa.suse.de/tests/13580613 (passed)
- 5sp6 ppc64le, SAPHanaSR_ScaleUp_PerfOpt_WMP_node, version SPS07rev73_IMDB76
http://openqa.suse.de/tests/13580713#step/check_logs/51 (failed on check log but it is a known issue: bsc#1219359)

Fix hana_cluster failure on hana node register

---

tests/sles4sap/publiccloud/hana_sr_schedule_deployment.pm
tests/sles4sap/publiccloud/qesap_ansible.pm
tests/sles4sap/publiccloud/qesap_prevalidate.pm

Split it in two test modules: one for the deployment and the other for the cluster validation.
- Related ticket: https://jira.suse.com/browse/TEAM-9076
- sle-15-SP4-HanaSr-Azure-Byos-x86_64-Build15-SP4_2024-02-23T05:03:08Z-hanasr_azure_test_sapconf_sbd@64bit    -->   http://openqaworker15.qa.suse.cz/tests/276644
- sle-15-SP4-HanaSr-Azure-Byos-x86_64-Build15-SP4_2024-02-23T05:03:08Z-hanasr_azure_test_sapconf_sbd@64bit  QESAP_DEPLOYMENT_EXPORT=1  -->   http://openqaworker15.qa.suse.cz/tests/276645 and associated import QESAP_DEPLOYMENT_IMPORT=276645 http://openqaworker15.qa.suse.cz/tests/276646

Split qesap_ansible test module

---

tests/containers/podman_netavark.pm

Containers: precheck in netavark module to skip installation if package already present.
- Related ticket: https://progress.opensuse.org/issues/137168 
- Needles: N/A
- Verification run: see PR body

Containers: netavark shall skip install of pkg present

---

tests/xfstests/run.pm

The previous PR made public cloud tests fail to boot in run steps. Change select_serial_terminal() back to select_console('root-console') when find this is a public cloud test.
- Related ticket: https://progress.opensuse.org/issues/155779
- Verification run: https://openqa.suse.de/tests/13602134

xfstests: Fix public cloud test fail after PR_18616

---

tests/kernel_performance/full_run.pm

When skipping case 'hanaonkvm' from the list file, we need to remove calling the function for creating VM.
Verification run: http://10.67.129.4/tests/68969

Fix the issue when removing hanaonkvm test

---

schedule/functional/extra_tests_qemu.yaml

https://progress.opensuse.org/issues/155719
VR:
[s390x](http://openqa.suse.de/tests/13563725) **Please ignore the failed test module, it is a known issue**
[qemu-backend](http://openqa.suse.de/tests/13563735)

Add key setps for s390x qemu tests

---

schedule/yast/installer_extended/installer_extended_aarch64.yaml

Test still failed because the install_SLES test was hardcoded into the tests YAML_SCHEDULE.
- [Verification run](https://openqa.suse.de/tests/13580349)

Quick fix for installer_extended on aarch64

---

lib/mm_network.pm
tests/network/setup_multimachine.pm

The serial console somehow looks like it messes up with the interpolation
of `mn_id`. Using serial terminal produces more stable results and problem
seems to go away.
In additional there are changes to prevent the uninitialized value warnings in autoinst-log on this jobs.
https://progress.opensuse.org/issues/155170
- Verification run: https://openqa.opensuse.org/tests/overview?distri=opensuse&build=b10n1k%2Fos-autoinst-distri-opensuse%2318713&version=Tumbleweed (x100)

Fix sporadic failures on nmcli invocation

---

lib/oscap_tests.pm

Each Scap security guide version will have own expected results and exclusions.
- Related ticket: https://progress.opensuse.org/issues/155884
https://openqa.suse.de/tests/13604989
https://openqa.suse.de/tests/13604996

Expected results and exclusions per SSG ver.

---

.gitignore
lib/db_utils.pm
lib/publiccloud/instance.pm
lib/publiccloud/provider.pm
tests/publiccloud/storage_perf.pm

In public cloud, during image creation and statistics collection, pre-check added in `influxdb_push_data`, to verify that influx db url is working well, otherwise no data pushed, but test will normally continue. 
Also timeouts added to internal curl post commands.
- Related ticket: https://progress.opensuse.org/issues/155416 
- Verification run: see body posts

Pubcloud image creation: precheck before pushing perf data to influxdb

---

lib/main_containers.pm
tests/containers/buildah.pm

The `buildah` test was being run only for podman. This way we are expanding it to Docker too, as requested in [bsc#1219563](https://bugzilla.suse.com/show_bug.cgi?id=1219563)
- Related ticket: https://progress.opensuse.org/issues/154930
- https://openqa.suse.de/tests/13605615
- https://openqa.suse.de/tests/13605614
- https://openqa.opensuse.org/tests/3964004
- https://openqa.opensuse.org/tests/3964001

Add buildah tests in Docker

---

lib/mm_network.pm

This change didn't take the code path for non-NM-based setups into account. There the default for the device parameter is determined differently and we must not assume `\S`.
See https://progress.opensuse.org/issues/156067

Fix configuring static IP after 40b811b7c

---

tests/console/dpdk.pm

https://bugzilla.suse.com/show_bug.cgi?id=1220308
- Verification run:  **Ignore the failed test module due to known issue**
[SLE](http://openqa.suse.de/tests/13615822#)
[Opensuse](https://openqa.opensuse.org/tests/overview?build=rfan0228&distri=opensuse)

Install the latest dpdk packages on sle15sp6

---

.github/workflows/openqa.yml
CONTRIBUTING.md

This change allows to clone a job when creating a PR by mentioning it in the PR description via `@openqa: Clone https://openqa.opensuse.org/…`.
This requires the split-out monitor-subcommand provided by openQA PR https://github.com/os-autoinst/openQA/pull/5482.
I tested this locally, e.g.:
```
cat .github/workflows/openqa.yml | yq -r '.jobs.clone_mentioned_job.steps[0].run' | env GH_REPO=foo GH_REF=bar OPENQA_HOST=http://127.0.0.1:9526 OPENQA_API_KEY=… OPENQA_API_SECRET=… GH_PR_BODY="Merge my changes\n\n @openqa: Clone http://127.0.0.1:9526/tests/4240  \nfootnote" DRY_RUN_JOB_IDS='{"4240" : 4246, "4239" : 4245}' bash
Cloned 'http://127.0.0.1:9526/tests/4240' into:
http://127.0.0.1:9526/tests/4246
http://127.0.0.1:9526/tests/4245
script/openqa-cli monitor … 4246 4245 …
```

Allow to clone and monitor a job when creating a PR

---

lib/main_containers.pm

- Related ticket: https://progress.opensuse.org/issues/156139
- Related PR: https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/18677
- Verification run: https://openqa.suse.de/tests/13620067

Remove buildah_docker test for 12-SP5

---

lib/mm_network.pm

Ticket: https://progress.opensuse.org/issues/155278
VR: https://openqa.opensuse.org/tests/3958923#step/setup_multimachine/45

Actually validate network connectivity on NM MM setup

---

.github/workflows/openqa.yml

* Use normal variable for openQA host in GitHub action
* See https://progress.opensuse.org/issues/130934
---
I've already added the variable in our settings and will remove the secret from our settings when this PR is merged.
Note that we could alternatively
* also remove the line completely.
* change the GitHub action code in the scripts repo to use the default value (o3) also when `OPENQA_HOST` is set to an empty value.

Avoid redacted openQA-URLs in GitHub action logs

---

tests/containers/buildah.pm

The Tumbleweed image is used across multiple test runs and should not be removed.
- Related ticket: https://progress.opensuse.org/issues/156127
- Verification run: https://duck-norris.qe.suse.de/tests/14315

Don't delete the Tumbleweed image

---

lib/mm_network.pm

This is needed to fix https://openqa.opensuse.org/tests/3966620
`ping_server` and `ping_client` testsuite on o3 already got `EXPECTED_NM_CONNECTIVITY=none` added to the testsuite definition.

Allow bypassing NM connectivity check for MM tests

---

tests/network/setup_multimachine.pm

* Ensure the server outlives the client job as it is the owner of the
barriers; otherwise the client might fail with `lock owner already
finished`
* Note that this is in-line with the examples in our documentation on
https://open.qa/docs/#_test_synchronization_and_locking_api
* See https://progress.opensuse.org/issues/156052#note-6 for details
---
openqa: Clone https://openqa.opensuse.org/tests/3964713

Fix sync issue in `setup_multimachine` leading to sporadic failures

---

data/virt_autotest/host_unattended_installation_files/autoyast_opensuse_kvm_one_disk.xml
data/virt_autotest/host_unattended_installation_files/autoyast_opensuse_kvm_two_disk.xml
data/virt_autotest/host_unattended_installation_files/autoyast_opensuse_xen_one_disk.xml
data/virt_autotest/host_unattended_installation_files/autoyast_opensuse_xen_two_disk.xml
lib/virt_autotest/utils.pm
tests/virtualization/yast_virtualization.pm

- Remove proxyd from modulue libvirt daemons as it has been removed from all system
- Remove obsolete lxc from yast virtualuzation(https://openqa.opensuse.org/tests/3954883#step/yast_virtualization/12)
Related ticket: https://progress.opensuse.org/issues/152320
[TW virtualization@64bit](https://openqa.opensuse.org/tests/3954883)
[SLE15SP6 KVM](http://openqa.suse.de/tests/13571893)

Remove virtproxyd from virt test as it has been removed from all system

---

tests/network/setup_multimachine.pm

Reverts os-autoinst/os-autoinst-distri-opensuse#18754
Most if not all multimachine tests are broken today. Might be due to this PR

Revert "Fix sync issue in `setup_multimachine` leading to sporadic failures"

---

lib/sles4sap_publiccloud.pm
t/12_sles4sap_publicccloud.t

This increases the timeout for zypper in `wait_for_zypper`.
- Related ticket: https://jira.suse.com/browse/TEAM-9059
- Verification run: https://openqa.suse.de/tests/13626173 (sporadic problem did not happen)

Increase timout for zypper ref

---

tests/containers/rootless_podman.pm

This reverts commit d9466f529117cc0c2a07ff8f05f351ffb0f4a4c4.
Revert the commit that changed the place where we run `get_podman_version()`.
On s390x, the `$podman_version` variable contains this string: `2024-02-28T12:56:16.358246+01:00 susetest systemd[2772]: Failed to start podman-5639.scope.\n2.1.1`.  
- Related ticket: https://progress.opensuse.org/issues/156187
- Failing test: https://openqa.suse.de/tests/13625916
- Verification run: https://openqa.suse.de/tests/13628131

Revert "Small rootless_podman_refactoring"

---

tests/network/setup_multimachine.pm

This brings back only the coding style changes as they were reverted as part of https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/18757.

Use more compact coding style in `setup_multimachine` module

---

tests/containers/buildah.pm

cni-plugins needs to be temporarily installed on 15-SP3.
- Related ticket: https://progress.opensuse.org/issues/154930
- Verification run: [https://duck-norris.qe.suse.de/tests/14324](https://duck-norris.qe.suse.de/tests/14324#step/buildah_docker/84)

Install missing cni-plugins package on 15-SP3

---

tests/console/sshd.pm

Since OpenSSH 8.5 [0], UpdateHostKeys is enabled by default on the ssh client configuration.
Calling the ssh client with -o HostKeyAlgorithms=<single_algorithm> would then drop the other, now "foreign" algorithms from ~/.ssh/known_hosts, making the subsequent HostKeyAlgorithms tests fail.
This commit fixes that by adding -o UpdateHostKeys=no on the test command, so that the ssh client will not try to change the known_hosts file anymore.
`UpdateHostKeys` is available since OpenSSH 6.8 [1] so every SLE-15 release should be covered, and SLE-12-SP5 as well.
[0] https://www.openssh.com/txt/release-8.5
[1] https://github.com/openssh/openssh-portable/commit/8d4f87258f31cb6def9b3b55b6a7321d84728ff2
- Related ticket: https://progress.opensuse.org/issues/156058 …

console/sshd: test_cryptographic_policies: ensure known host keys don't get dropped

---

data/yam/autoyast/support_images/hpc15sp3_install_development_node_default_patterns_aarch64.xml
data/yam/autoyast/support_images/hpc15sp3_install_management_server_default_patterns_aarch64.xml
data/yam/autoyast/support_images/hpc15sp3_install_textmode_default_patterns_x86_64.xml

Add autoyast profiles for hpc15sp3 installation to publish support images.
- Related ticket: https://progress.opensuse.org/issues/156190
- Needles: n/a
- Verification run:  https://openqa.suse.de/tests/overview?distri=sle&version=15-SP3&build=20240227-1&groupid=251
- Related mr: https://gitlab.suse.de/qe-yam/openqa-job-groups/-/merge_requests/98

Add autoyast profiles for hpc15sp3 installation

---

lib/main_containers.pm

zypper_docker is only available on SLES >12 and < 15-SP6 so limit the test runs to those platforms.
- Related failure: https://progress.opensuse.org/issues/156310
- Verification run: [15-SP6](https://openqa.suse.de/tests/13644314) (not present) | [15-SP5](https://openqa.suse.de/tests/13644316) (present)

Remove zypper-docker from newer SLES projects

---

data/containers/docker-seccomp.json
data/containers/podman-seccomp.json
lib/containers/utils.pm
lib/main_containers.pm
tests/containers/container_engine.pm
tests/containers/seccomp.pm

Introduce seccomp tests
- Related ticket: https://progress.opensuse.org/issues/155401
- opensuse-Tumbleweed-DVD-x86_64-Build20240228-containers_host_docker@64bit -> https://openqa.opensuse.org/t3973080
- opensuse-Tumbleweed-DVD-x86_64-Build20240228-containers_host_podman@64bit -> https://openqa.opensuse.org/t3973082
- sle-15-SP2-Server-DVD-Updates-x86_64-Build20240227-1-docker_tests@64bit -> https://openqa.suse.de/t13644245
- sle-15-SP2-Server-DVD-Updates-x86_64-Build20240227-1-podman_tests@64bit -> https://openqa.suse.de/t13644246
- microos-Tumbleweed-DVD-x86_64-Build20240228-container-host@64bit -> https://openqa.opensuse.org/t3973141

containers: Introduce seccomp test

---

lib/migration.pm
tests/migration/online_migration/zypper_patch.pm
tests/update/patch_sle.pm

##
- Description:
* Uninstall package libopenssl-1_1-devel if it is installed before migration
* https://progress.opensuse.org/issues/156184
- Needles: 
* N/A
* https://openqa.suse.de/t13643736
* https://openqa.suse.de/t13643737
* https://openqa.suse.de/t13643948

Uninstall package libopenssl-1_1-devel before migration

---

schedule/functional/mm_ping.yaml
tests/network/conclude_multimachine.pm

* Ensure the server outlives the client job as it is the owner of the barriers; otherwise the client might fail with `lock owner already finished`
* Note that this is in-line with the examples in our documentation on https://open.qa/docs/#_test_synchronization_and_locking_api
* See https://progress.opensuse.org/issues/156052#note-6 for details
* 2nd attempt after https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/18757
---
openqa: Clone https://openqa.opensuse.org/tests/3964713

Fix sync issue in `mm_ping` scenario leading to sporadic failures

---

tests/sles4sap/cloud_netconfig/configure.pm
tests/sles4sap/cloud_netconfig/sanity.pm
tests/sles4sap/cloud_netconfig/test.pm

Change the test to not only check the ip configuration once, but check
multiple times till change is applied.
Add `zypper ref`
Swap order on some az commands to reduce amount of time they are
executed.
- Related ticket: TEAM-8721
-  http://mango.qe.nue2.suse.org/tests/5679
- http://mango.qe.nue2.suse.org/tests/5680
- http://openqaworker15.qa.suse.cz/tests/277360

Wait in a loop until ipconfig is removed

---

lib/main_containers.pm

Follow-up of https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/18770 to include zypper_docker still in leap and SLEM and Leap-Micro.
* Verification run: https://openqa.suse.de/tests/13648931

Add Leap again for zypper-docker

---

tests/x11/nis_server.pm

- Description: increase timeout to fix sporadic failure
- Verification run: [overview](https://openqa.suse.de/tests/overview?build=leo-test-20240229)

Increase timeout for assert_screen inside nis_server.pm

---

lib/utils.pm

Failure: https://openqa.opensuse.org/tests/3976118#step/shutdown/5 , https://openqa.opensuse.org/tests/3976803#step/updates_packagekit_kde/19 and https://openqa.opensuse.org/tests/3975923#step/consoletest_finish/19

lib/utils: Leap 15.6 has SDDM 0.20, the session is not tty7 anymore

---

data/yam/autoyast/multipath.xml

- Description: Increase the minimal size for XFS to 300MB
- Related Bug: [bsc#1220728](https://bugzilla.suse.com/show_bug.cgi?id=1220728)
- Verification run: [overview](https://openqa.suse.de/tests/overview?build=issues-bug-1220728)

Increase the minimal size for XFS

---

tests/console/openvswitch.pm
tests/console/openvswitch_ssl.pm
tests/console/ovn.pm
tests/console/ovs_client.pm
tests/console/ovs_server.pm

According to https://jira.suse.com/browse/PED-5766 the '3' in the name shall be used only on 15.5
- Related ticket: https://progress.opensuse.org/issues/156271
- Needles: 
- https://openqa.suse.de/tests/13662013
- https://openqa.suse.de/tests/13662017
- https://openqa.suse.de/tests/13662028
- https://openqa.suse.de/tests/13662031
- https://openqa.suse.de/tests/13662044

Remove '3' from ovn/openvswitch on 15.6

---

tests/installation/ipxe_install.pm

- Remove DISPLAY per bsc#1218798
- don't include prj2 as it has been implemented in https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/18671
Verification run: http://10.67.129.27/tests/244
@alice-suse @waynechen55 @guoxuguang @nanzhg @RoyCai7

Remove DISPLAY from ipxe install for non-autoyast installation

---

data/sles4sap/qe_sap_deployment/mr_test_azure.yaml
data/sles4sap/qe_sap_deployment/mr_test_azure_uri.yaml
data/sles4sap/qe_sap_deployment/mr_test_ec2.yaml
data/sles4sap/qe_sap_deployment/mr_test_ec2_product.yaml
data/sles4sap/qe_sap_deployment/mr_test_gcp.yaml
data/sles4sap/qe_sap_deployment/sles4sap_aws_generic.yaml
data/sles4sap/qe_sap_deployment/sles4sap_azure_generic.yaml
data/sles4sap/qe_sap_deployment/sles4sap_azure_generic_maintenance.yaml
data/sles4sap/qe_sap_deployment/sles4sap_azure_generic_uri.yaml
lib/publiccloud/utils.pm
lib/sles4sap_publiccloud.pm
tests/sles4sap/publiccloud/qesap_terraform.pm
tests/sles4sap/qesapdeployment/configure.pm

sles4sap tests using qe-sap-deployment no more use hardcoded sshkey file path but get it from PC using get_ssh_private_key_path()
Related ticket: [poo#155554](https://progress.opensuse.org/issues/155554)
- sle-15-SP5-HanaSr-Azure-Byos-x86_64-Build15-SP5_2024-03-04T05:03:09Z-hanasr_azure_test_sbd@64bit
http://openqaworker15.qa.suse.cz/tests/277916 :green_circle: 
- sle-15-SP5-Azure-SAP-BYOS-Incidents-x86_64-Build:32633:saptune-SAPHanaSR-ScaleUp-PerfOpt-msi@az_Standard_E8s_v3 
http://openqaworker15.qa.suse.cz/tests/277917  :green_circle: Failure is later after the end of the deployment
- sle-15-SP4-HanaSr-Aws-Byos-x86_64-Build15-SP4_2024-03-04T05:03:09Z-hanasr_aws_test_saptune@64bit 
http://openqaworker15.qa.suse.cz/tests/277925
- sle-15-SP5-Azure-SAP-BYOS-Incidents-saptune-x86_64-Build:3263 …

sles4sap tests get sshkeys files from PC libs

---

tests/microos/toolbox.pm

If we run it in rootless mode, it will only work if it contains any default repository (like SLE_BCI for SLE Micro <=5.5 rootles containers). Otherwise, this call will fail because rootless user can't inherit repos from the host.

Toolbox: run zypper commands when running toolbox as rootfull

---

lib/publiccloud/instance.pm
lib/publiccloud/provider.pm
lib/publiccloud/utils.pm

Used openstack version doesn't support ed25519 keys. We need to make an exception in public cloud libs.
```
BadRequestException: 400: Client Error for url:
https://engcloud.prv.suse.net:8774/v2.1/aec806fcad544e73bf8c24d6f010afda/os-keypairs,
Keypair data is invalid: failed to generate fingerprint
```
- Related ticket: https://progress.opensuse.org/issues/156634
- Verification run: http://kepler.suse.cz/tests/22699

ed25519 is not supported in openstack

---

data/sles4sap/qe_sap_deployment/mr_test_gcp.yaml

Fix regression introduced in https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/18791
- Related ticket: [poo#155554](https://progress.opensuse.org/issues/155554)
- sle-15-SP6-GCE-SAP-BYOS-x86_64-Build0467-sles4sap_gnome_saptune_delete_rename@gce_n1_highmem_8 -> http://openqaworker15.qa.suse.cz/tests/277988

Add back private_key in mr_test terraform config

---

lib/main_common.pm

Fix poo#155146: rasdaemon is not supported on ppc64le architecture.
- Related ticket: https://progress.opensuse.org/issues/155146
- Needles: 
- Verification runs
- TW: http://openqa.opensuse.org/tests/3985281
- 15-sp6: https://openqa.suse.de/tests/13707791
- 15-sp5: https://openqa.suse.de/tests/13707792
- TW: https://openqa.opensuse.org/tests/3985282
- 15-sp6: https://openqa.suse.de/tests/13707788

Don't run rasdaemon on ppc64le

---

tests/containers/firewall.pm

Remove iptables checking in firewall module to not depend on backend
- Related ticket: https://progress.opensuse.org/issues/155395
- opensuse-Tumbleweed-DVD-x86_64-Build20240304-containers_host_docker@64bit -> https://openqa.opensuse.org/t3988065
- opensuse-Tumbleweed-DVD-x86_64-Build20240304-containers_host_podman@64bit -> https://openqa.opensuse.org/t3988066

containers: Remove iptables checking in firewall module

---

lib/qesapdeployment.pm
t/09_qesapdeployment.t

Change grep on the log to get more context.
Fix regexp in the grep
Add a record_info
- sle-15-SP4-HanaSr-Aws-Byos-x86_64-Build15-SP4_2024-03-04T05:03:09Z-hanasr_aws_test_saptune@64bit ->
http://openqaworker15.qa.suse.cz/tests/277914 here an example of the error message http://openqaworker15.qa.suse.cz/tests/277914#step/deploy_qesap_ansible/38
with `\\[` http://openqaworker15.qa.suse.cz/tests/277989
- sle-15-SP4-HanaSr-Azure-Byos-x86_64-Build15-SP4_2024-03-04T05:03:09Z-hanasr_azure_test_sapconf_msi@64bit -> http://openqaworker15.qa.suse.cz/tests/277915
- sle-15-SP5-Qesap-Azure-Payg-x86_64-BuildLATEST_AZURE_SLE15_5_PAYG-qesap_azure_saptune_test@64bit -> http://openqaworker15.qa.suse.cz/tests/277913 The new `record_info` block is only executed for Ansible and only if the error is not one of …

Create record_info with qesap Ansible error

---

lib/LTP/utils.pm
tests/kernel/kselftests.pm

This patch removes all sources build dependences and it adds packages support for multiple kselftests testing suites.
- Related ticket: https://progress.opensuse.org/issues/131180
- Verification run: https://openqa.suse.de/tests/13706574 https://openqa.suse.de/tests/13706573

Adapt kselftests module to use packages only

---

tests/containers/buildah.pm

SP6 and SP5 refreshed images dont have cni-plugins package and needs to be installed explicitly.
- ticket: https://progress.opensuse.org/issues/156556
- Verification run: http://kepler.suse.cz/tests/22709#

Install cni-plugins for buildah

---

tests/installation/installation_overview.pm

Introduced a new parameter "DISABLE_SECUREBOOT=1" for setting secureboot disabled during installation.
- Related ticket: https://progress.opensuse.org/issues/156568
- Needles: https://gitlab.suse.de/openqa/os-autoinst-needles-sles/-/merge_requests/1658
- Verification run: [default_install_svirt@svirt-vmware70](http://10.67.129.96/tests/2854), [textmode_svirt@svirt-vmware70](http://10.67.129.96/tests/2856)

Add support to disable UEFI secureboot

---

lib/x11test.pm

firefox_printing_pdf and firefox_printing_frames fail frequently。
Update firefox_print function to make it more robust.
- Related ticket: https://progress.opensuse.org/issues/138455
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/13715840#

Make firefox_print function more robust.

---

tests/x11/firefox/firefox_urlsprotocols.pm

bsc#1004573 has been marked as WONTFIX
So, we need to remove the corresponding softfailure
- Related ticket: https://progress.opensuse.org/issues/156715
- Needles: N/A
> - X11: https://openqa.suse.de/tests/13724296#
> - Wayland: https://openqa.suse.de/tests/13724283#

Remove outdated softfailure for bsc#1004573

---

tests/sles4sap/publiccloud/hana_sr_test_secondary.pm

This pr adds resource cleanup at the end of `hana_sr_test_secondary.pm`, in the same manner it happens for `hana_sr_takeover.pm`. This removes the errors seen by crm output (example of old test, without cleanup, with errors: https://openqa.suse.de/tests/13503040#step/Crash_replica/3 - compare it to the VR)
- Related ticket: https://jira.suse.com/browse/TEAM-9057
- Verification run: https://openqa.suse.de/tests/13717129#step/Crash_replica/3

Add resource cleanup to hana_sr_test_secondary

---

tests/installation/ipxe_install.pm

Need update the condition for ipxe installer to make sure yast installation test won't run on ssh while should be on vnc.
Failed job: https://openqa.suse.de/tests/13712542#step/access_beta_distribution/2
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/13724169#details

Update condition for ipxe installer

---

lib/qesapdeployment.pm

- Related ticket: https://jira.suse.com/browse/TEAM-8981
- sle-15-SP5-Qesap-Azure-Byos-x86_64-BuildLATEST_AZURE_SLE15_5_BYOS-qesap_azure_sapconf_test@64bit -> http://openqaworker15.qa.suse.cz/tests/278053 :green_circle: 
- sle-15-SP5-HanaSr-Azure-Byos-x86_64-Build15-SP5_2024-03-06T05:03:10Z-hanasr_azure_test_msi@64bit -> http://openqaworker15.qa.suse.cz/tests/278054 :green_circle: Python is ok, problem is later during the test Crash_site
- sle-15-SP5-Azure-SAP-BYOS-Incidents-x86_64-Build:32633:saptune-SAPHanaSR-ScaleUp-PerfOpt@az_Standard_E8s_v3 -> http://openqaworker15.qa.suse.cz/tests/278055
- sle-15-SP5-Azure-SAP-BYOS-Incidents-x86_64-Build:32865:ClusterTools2-SAPHanaSR-ScaleUp-PerfOpt@az_Standard_E8s_v3 -> http://openqaworker15.qa.suse.cz/tests/278056

Move the default python for qesap to 3.11

---

tests/containers/podman_netavark.pm

GCE defaults to create single, isolated instances that get `/32` subnet. This is valid unless `MULTI_IP_SUBNET` flag is set while uploading the image to the cloud environment. We happen to set this flag for images that are under GA phase. Without `MULTI_IP_SUBNET` the last test objective `macvlan setup` wont work in GCE.
- ticket: https://progress.opensuse.org/issues/156445
* [sle15sp6](http://kepler.suse.cz/tests/22717#step/podman_netavark/249)
* [sle15sp5](http://kepler.suse.cz/tests/22716#step/podman_netavark/207)

Skip macvlan test in GCE aggregates tests

---

tests/publiccloud/cloud_netconfig.pm

The softfail is obsolete, because corresponding tests were unscheduled for the time being.
- Related ticket: https://progress.opensuse.org/issues/154519
- Verification run: https://stratoscamper.qe.prg2.suse.org/tests/24

Remove obsolete softfail from cloud-netconfig

---

lib/hpc/configs.pm
tests/hpc/slurm_master.pm

The config.pm change allow the second slurm partition to be configured, so that the tests could get more complex and slurm jobs could be run against any of the existing partition. At the same time there is the default partition so there is no need to change any of the existing tests; those should run the same way
- Related ticket: https://progress.opensuse.org/issues/135248
beta cluster/x86_64
**https://openqa.suse.de/tests/13718253**
https://openqa.suse.de/tests/13718254
https://openqa.suse.de/tests/13718252
https://openqa.suse.de/tests/13718251
delta cluster/x86_64
**https://openqa.suse.de/tests/13718270**
https://openqa.suse.de/tests/13718271
https://openqa.suse.de/tests/13718268
https://openqa.suse.de/tests/13718269
delta cluster/arm …

HPC: Add second slurm partition

---

tests/security/cc/trustedprograms.pm

This bash script has been failing since ever it was created for sle 12  and besides it needs updated the ciphers for sle 15, it will never work due to lack of proper network setup in openQA, therefor we can drop it, as this might be too tricky in 
openQA.
- Related ticket's note: [poo#115919#note-20](https://progress.opensuse.org/issues/96438?issue_count=19&issue_position=18&next_issue_id=72037&prev_issue_id=115919#note-20)
- Related MR: [mr#62](https://gitlab.suse.de/security/audit-test-sle15/-/merge_requests/62)
- Verification run: [cc_audit-test-part2](https://openqa.suse.de/tests/12163312)

Drop test_basic_strongswan, lacking network setup

---

lib/version_utils.pm

Consider Slowroll as Tumbleweed
because it inherits all its packages and is at most some weeks behind.
This should help with
https://openqa.opensuse.org/tests/3994128#step/glibc_locale/32
where `glibc-lang` was missing, because `is_tumbleweed` returned false.

Consider Slowroll as Tumbleweed

---

tests/xfstests/install.pm

As now the xfstests version is quite old in testing Tumbleweed update the new ibs repo.
- in Tumbleweed: 
create_hdd_xfstests: https://openqa.opensuse.org/tests/3993393
subtests based on new hdd: [xfstests_btrfs-btrfs-201-999](https://openqa.opensuse.org/tests/3993511)  [xfstests_btrfs-btrfs-101-200](https://openqa.opensuse.org/tests/3991158)
- in SLES SP6: 
create_hdd_xfstests: https://openqa.suse.de/tests/13734397
subtests based on new hdd: [xfstests_btrfs-btrfs-101-200](https://openqa.suse.de/tests/13734402)
- in Public cloud:
grub2-publiccloud_xfs_000-100: https://openqa.suse.de/tests/13734399

xfstests: Update o3 xfstests test repo

---

tests/xfstests/partition.pm

setcap is needed by overlay/064, so add libcap-progs for dependency
- Needles: N/A
http://10.67.133.133/tests/487#step/generate_report/57 (SLE)
http://10.67.133.133/tests/493#step/overlay-064/2 (Micro)

xfstests: add libcap package for overlayfs

---

lib/opensusebasetest.pm

- Verification run: https://openqa.suse.de/tests/13743590#live

Fix password regex call for s390x

---

tests/containers/container_engine.pm

Container run --init pid 1 check was failing for false positive, due to check expression used. Here used a new expression to state the process expected to be present and pid=1.
- Related ticket: https://progress.opensuse.org/issues/156895
- Needles: N/A
- Verification run: see PR body.

Container run --init verification updated

---

tests/virt_autotest/login_console.pm

* **Recently** host upgrade keeps failing due to [bsc#1218798](https://bugzilla.suse.com/show_bug.cgi?id=1218798).
* **Skipping** setting DISPLAY before opening yast.ssh can help solve the issue.
* [xen offline upgrade starts](https://openqa.suse.de/tests/13743349)
* [kvm offline upgrade starts](https://openqa.suse.de/tests/13743163)

Skip setting DISPLAY before opening yast.ssh for host upgrade

---

tests/hpc/slurm_db.pm
tests/hpc/slurm_slave.pm

For the older, base, slurm versions there is no slurm-node package. The tests attempt to install it which leads to conflicts. Also, the slurm base version, does not provide mariadb as a dependency, so that must be installed explicitly
- Related ticket: https://progress.opensuse.org/issues/156868
sle12sp5:
https://openqa.suse.de/tests/13740825
https://openqa.suse.de/tests/13740828
https://openqa.suse.de/tests/13740824
https://openqa.suse.de/tests/13740826
https://openqa.suse.de/tests/13740829
sle15sp2/slurm (20.02)
https://openqa.suse.de/tests/13742515
https://openqa.suse.de/tests/13742519
https://openqa.suse.de/tests/13742517
https://openqa.suse.de/tests/13742518
https://openqa.suse.de/tests/13742514
https://openqa.suse.de/tests/13742516
sle15sp2/slurm-node (22_05) …

HPC: Do not attempt to install slurm-node for old slurm versions

---

data/virt_autotest/guest_params_xml_files/sles_15_sp6_64_kvm_hvm_uefi_without_power_management_x86_64_using_virtmanagerlt3.0.0.xml
lib/guest_installation_and_configuration_base.pm

* **Regression** issue found in bsc#1217359 has workaround to let guest installation pass, which requires additional network settings for SLES 15-SP6 guest on 12-SP5 KVM host. 
* **Network** settings need extra rom_bar=off to workaround the issue, for example, ```--network bridge=br123,mac=52:54:00:b3:21:25,rom_bar=off```.
* **This** can be easily achieved by setting ```guest_network_others``` to ```rom_bar=off``` in guest profile ```sles_15_sp6_64_kvm_hvm_uefi_without_power_management_x86_64_using_virtmanagerlt3.0.0.xml ```
* [15sp6 on 12sp5 kvm](https://openqa.suse.de/tests/13755928)
* [15sp6 on 12sp5 xen](https://openqa.suse.de/tests/13755636)
* [15sp6 on 15sp6 kvm](https://openqa.suse.de/tests/13755726)
* [12sp5 on 15sp6 …

Add network setting rom_bar=off for 15-SP6 guest on 12-SP5 KVM host

---

tests/console/suseconnect_scc.pm

Transactional-update returns 0 even if SUSEConnect failed. By doing a small check of the output, we can fail the test if there is a failure or timeout.
Current behavior:
registration fails but test continues: https://openqa.suse.de/tests/13756870#step/suseconnect_scc/21
- https://openqa.suse.de/tests/13757405#step/suseconnect_scc/28
- https://openqa.suse.de/tests/13756405#step/suseconnect_scc/21

Die if SUSEConnect does not register

---

tests/containers/container_engine.pm

Container run --init, pid 1 check fix updated for case with PID 1 /dev/init.
- Related ticket: https://progress.opensuse.org/issues/155404 and https://progress.opensuse.org/issues/156895
- Verification run: see PR body

Container run --init verification fixed

---

tests/containers/container_engine.pm

Re-introduce the check for `ps` not running as PID 1.
- Related ticket: https://progress.opensuse.org/issues/155404
- Verification runs: [TW podman](https://duck-norris.qe.suse.de/tests/14445) | [TW docker](https://duck-norris.qe.suse.de/tests/14439) | [15-SP2 podman](https://duck-norris.qe.suse.de/tests/14440) | [15-SP2 docker](https://duck-norris.qe.suse.de/tests/14441) | [15-SP5 podman](https://duck-norris.qe.suse.de/tests/14442) | [15-SP5 docker](https://duck-norris.qe.suse.de/tests/14443) | [12-SP5 docker](https://duck-norris.qe.suse.de/tests/14444)

Re-introduce PID 1 test

---

tests/console/sudo.pm

https://progress.opensuse.org/issues/156928
[sle](http://openqa.suse.de/tests/overview?distri=sle&build=rfan0311)
[tw](https://openqa.opensuse.org/tests/4003715#step/sudo/98)
Please ignore the failed test module, it is known issue

Fix sudo test logic for NOPASSWD

---

tests/x11/evolution/evolution_smoke.pm
tests/x11/evolution/evolution_timezone_setup.pm

For the "About" page, we need to "hold_key" instead of "send_key".
For the "Preference" page, we use shortcut "ctrl-alt-s" directly.
- Related ticket: https://progress.opensuse.org/issues/154870
15SP6: https://openqa.suse.de/tests/13762880#step/evolution_smoke/20
https://openqa.suse.de/tests/13762880#step/evolution_timezone_setup/31
15SP5: https://openqa.suse.de/tests/13762887

Fix keyboard shortcuts in evolution tests

---

tests/microos/toolbox.pm

The `toolbox.pm` test code provided a zypper update log `toolbox_zypper_up.txt` (L#114) only when failed, otherwise none, so that when test pass we had NO information of what happened, unable to verify if installation was really ok or a false-positive occurred, like nothing done, instead. 
This simple change allows to see that output. 
- Related ticket: https://progress.opensuse.org/issues/156925#note-7
- Verification run: Passed test show in a console image needle the `toolbox -- zypper up output`, that before was only redirected to a file and not visible
https://openqa.suse.de/tests/13765724#step/toolbox/65
https://openqa.suse.de/tests/13765554#step/toolbox/65

toolbox zypper-up output on console

---

lib/version_utils.pm

The virtualization incident flavors of sle micro 5.5 is named DVD/Default-Virt-Incidents. The current is_rt check will return true when checking this flavor, so accidentally load rt related tests and skip virt tests. This PR fixes this by correcting is_rt check.
- Related ticket: https://progress.opensuse.org/issues/154969
- https://openqa.suse.de/tests/13755649#
- for RT flavor historical jobs, I do not find any recent job that has existing incident repo, so can't trigger such validation job. But local simple check for existing RT flavors are good. So should be fine.

Fix is_rt for those matching Virt in flavor

---

tests/x11/steam.pm

https://progress.opensuse.org/issues/156886
https://progress.opensuse.org/issues/156223
- Verification run: [tw&leap](https://openqa.opensuse.org/tests/overview?distri=opensuse&build=rfan0312)
**Please ignore the failed test module, it is known issue**

Make sure the focus is on xterm before closing it

---

tests/network/openvpn_client.pm
tests/network/openvpn_server.pm

Revert #18828 for compatibility with old platforms.
Related ticket: https://progress.opensuse.org/issues/156898
- 12-SP3: https://openqa.suse.de/tests/13763448
- 12-SP5: https://openqa.suse.de/tests/13763179 
- 15-SP2: https://openqa.suse.de/tests/13763192
- 15-SP3: https://openqa.suse.de/tests/13763187
- 15-SP4: https://openqa.suse.de/tests/13763701
- 15-SP5: https://openqa.suse.de/tests/13763184

Fix openvpn tests for older systems

---

tests/publiccloud/img_proof.pm

Upload SCAP profile used by img-proof.
It will help in the future with bugs like https://bugzilla.suse.com/show_bug.cgi?id=1220269 to compare what changed.

pc: Upload SCAP profile used by img-proof

---

tests/containers/rootless_podman.pm

Unconditional cleanup prevents [bsc#1217683](https://bugzilla.opensuse.org/show_bug.cgi?id=1217683) from happening when updating from a podman with `btrfs` as default storage backend.
- Related ticket: https://progress.opensuse.org/issues/156295
- Verification run: https://duck-norris.qe.suse.de/tests/14455

Add fix for poo156295

---

tests/ha/check_after_reboot.pm

fix the issue from TEAM-9113 by filtering out useless return line characters and the lines beginning with square bracket, I checked all the failed openQA jobs, the failure was triggered by the useless lines beginning with square bracket, so the fix is valid so far.
- Related ticket: https://jira.suse.com/browse/TEAM-9113
- Needles: https://openqa.suse.de/tests/13712032#step/check_after_reboot/31
https://openqa.suse.de/tests/13770883#step/check_after_reboot/30, 
https://openqa.suse.de/tests/13769676#step/check_after_reboot/30

Filter out useless noise in uuid variable

---

data/journal_check/bug_refs.json

Recently the watchdog has received several updates hence we should update the list of acceptable messages
- https://bugzilla.suse.com/show_bug.cgi?id=1221307#c3
- Verification run: https://openqa.suse.de/tests/13780080#step/journal_check/8

Update clocksource whitelisted messages

---

lib/saputils.pm
lib/sles4sap_publiccloud.pm
t/18_saputils.t
tests/sles4sap/publiccloud/hana_sr_test_secondary.pm

This pull request adds a new function to check whether a cluster is healthy and ready, using SAPHanaSR and crm commands. It also adds the function at the end of `hana_sr_test_secondary.pm`.
- Related ticket: https://jira.suse.com/browse/TEAM-9057
- Verification run: https://openqa.suse.de/tests/13781005

Add function to assess cluster status

---

lib/main_micro_alp.pm
schedule/sle-micro/publiccloud/basic.yml
tests/publiccloud/slem_basic.pm

SLEM Pub.Cloud aggregates for test group [532](https://openqa.suse.de/tests/overview?distri=sle-micro&version=5.5&groupid=532), modified tests: 
- slem_basic updated, triggered by code: basic.yaml in YAML_SCEDULE setting no more used;  
- slem_containers_selinux removed.
See also MR#[1552](https://gitlab.suse.de/qac/qac-openqa-yaml/-/merge_requests/1552) 
- Related ticket: https://progress.opensuse.org/issues/137168

SLEM pubcloud aggregated: basic tests updated

---

lib/virt_autotest/utils.pm
lib/virt_feature_test_base.pm
tests/virt_autotest/guest_installation_run.pm
tests/virt_autotest/libvirt_virtual_network_init.pm
tests/virt_autotest/sriov_network_card_pci_passthrough.pm
tests/virt_autotest/validate_system_health.pm
tests/virt_autotest/xen_guest_irqbalance.pm

To fix the following problems:
- It is difficult to determine which tests is the culprit of errors or warnings in journals.
- In addition, current uploaded log by "journalctl -b" does not include the log of previous boot which reports the errors. fg. https://openqa.suse.de/tests/13564742#downloads => libvirt_virtual_network_init-journalctl-sles-15-sp6-64-fv-uefi-xen.log
- Related ticket: https://progress.opensuse.org/issues/155728
[gi-guest_sles15sp5-on-host_developing-xen](https://openqa.suse.de/tests/13763065)
[gi-host_sles12sp5-xen](http://10.67.129.27/tests/291)
[uefi-gi-guest_developing-on-host_sles12sp5-xen](https://openqa.suse.de/tests/13763082)
[gi-guest_sles12sp5-on-host_developing-xen](https://openqa.suse.de/tests/13763066)
[a failed …

Check guest health before and after each virt feature test

---

data/yam/autoyast/support_images/sles12sp5_install_all_patterns_ppc64le_multi-user.xml
schedule/migration/ppc64le_regression_test_offline_textmode.yaml

As comments in https://progress.opensuse.org/issues/155758, there is a sporadic issue https://bugzilla.suse.com/show_bug.cgi?id=1221005 on graphic test, we'd better to change it to textmode so that test won't be blocked any more.
- Related ticket: https://progress.opensuse.org/issues/156970
- Related MR: https://gitlab.suse.de/qe-yam/openqa-job-groups/-/merge_requests/109
- Needles: N/A
Installation:  https://openqa.suse.de/tests/13778180#  
https://openqa.suse.de/tests/13778181#
Migration:   http://openqa.suse.de/tests/overview?version=15-SP6&build=lemon-suse%2Fos-autoinst-distri-opensuse%23replace-gnome-to-textmode-12sp5-ppc64le&distri=sle    Now all test failed for bsc#1221005

Replace the regression migration test from gnome to textmode

---

data/virt_autotest/host_unattended_installation_files/autoyast/dev_host_12.xml.ep
data/virt_autotest/host_unattended_installation_files/autoyast/dev_host_15.xml.ep
lib/ipmi_backend_utils.pm

- Related ticket: https://progress.opensuse.org/issues/156904
//GUI installation
[sle12sp5 kvm host on unreal3](https://openqa.suse.de/tests/13763062)
[sle12sp5 kvm host on unreal2](https://openqa.suse.de/tests/13764002)
[sle12sp5 kvm host on other machines](https://openqa.suse.de/t13778179)
[sle15sp5 kvm host on other machines](https://openqa.suse.de/t13778190)
[sle12sp5 xen host on unreal3](https://openqa.suse.de/tests/13778186)
[sle15sp6 xen host on unreal2](https://openqa.suse.de/tests/13778189)
[sle15sp5 xen host on other machines](http://openqa.suse.de/tests/13778205)
//Autoyast installation
[sle15sp6 kvm host on unreal2](https://openqa.suse.de/tests/13778226) …

Correct serial device configuration in grub2 on KVM and XEN host

---

tests/console/validate_lvm_raid1.pm

- Description: [sporadic] make stable validate_lvm_raid1 reboot
- Related ticket: [poo#154753](https://progress.opensuse.org/issues/154753)
- Verification run: [overview](https://openqa.suse.de/tests/overview?build=issues-154753)

Make stable validate_lvm_raid1 reboot

---

lib/version_utils.pm
tests/console/journald_fss.pm
tests/fips/openjdk/openjdk_fips.pm

It needs to be maj.min, no other syntax allowed.
One case found by @rfan1: https://openqa.opensuse.org/tests/4011502#step/opensuse_welcome/6
Other cases found by `git grep -E 'is_leap\([^.]*\)`

Fix some is_leap calls

---

tests/containers/firewall.pm

This PR adds debug information in post_fail_hook
- Related ticket: https://progress.opensuse.org/issues/157330
- Failing test: https://openqa.opensuse.org/tests/4015303#step/docker_firewall/137
- Verification run: https://openqa.opensuse.org/tests/4015866 (failing because of https://bugzilla.opensuse.org/show_bug.cgi?id=1221458)

containers: Add debug info to post_fail_hook in docker_firewall

---

data/autoyast_sle15/autoyast_sles4sap.xml.ep

Remove pattern "sap-b1" from autoyast_sles4sap.xml.ep for prerelease sap product 15-SP6 as it is not supported from 15-SP5
TEAM-9115 - [15-SP6] autoyast_sles4sap_hana failed on "installation": "Attempt to `start` service 'firewalld' failed" & "Error while setting pattern: sap-b1"
- Related ticket: https://jira.suse.com/browse/TEAM-9115
- Needles: NA
x86_64: http://openqa.suse.de/tests/13789913# (passed)
ppc64le: https://openqa.suse.de/tests/13789911#step/installation/95 (failure can be tracked by Bug 1220851)
[Bug 1220851](https://bugzilla.suse.com/show_bug.cgi?id=1220851) - [Build 60.3] openQA test fails in "autoyast_sles4sap_hana" autoyast installation, it reports : Value '' is invalid. Use one of: ports, hostnames
NOTE: Checking steps of test code:
step1:
I checked …

Remove pattern sap-b1 from autoyast_sles4sap.xml

---

tests/update/updates_packagekit_kde.pm

- Failure: https://openqa.opensuse.org/tests/4014757#step/updates_packagekit_kde/22
- Verification runs: https://openqa.opensuse.org/tests/4015926 (TW) https://openqa.opensuse.org/tests/4016170 (15.5)

update/updates_packagekit_kde: Handle discover

---

lib/containers/common.pm
tests/containers/firewall.pm

- Related ticket: https://bugzilla.opensuse.org/show_bug.cgi?id=1221458 and https://progress.opensuse.org/issues/157330
- Needles: N/A
- Verification Runs: [Working post_fail_hook](https://openqa.opensuse.org/tests/4017525), [docker_firewall fixed](https://openqa.opensuse.org/tests/4018048)

containers: fix docker_firewall by allowing frequent docker restarts

---

products/sle-micro/main.pm

In some cases, we need to use Update jobs without any incident installed, for example for Image re-spins, etc.
VR: https://openqa.suse.de/tests/13770928#step/install_updates/1

Allow running maintenance jobs without list of incidents

---

schedule/sles4sap/qam/common/qam_install_sles4sap.yaml
tests/console/check_os_release.pm

Enable Horizontal Migration Test in QAM Incidents job groups.
TEAM-9036 - Enable Horizontal Migration Test in QAM
Added 4 test cases for each product.
create_hdd_gnome_qam_sap
sap_sles4sap_failing_horizontal_migration_rollback
sles4sap_horizontal_migration_sapconf
sles4sap_horizontal_migration_saptune
- Related ticket: https://jira.suse.com/browse/TEAM-9036
- Needles: NA
15-SP5: https://openqa.suse.de/tests/13764966#dependencies (passed, no LTSS) 
15-SP4: https://openqa.suse.de/tests/13779136#dependencies (passed, LTSS)
15-SP3: https://openqa.suse.de/tests/13779304#dependencies (passed, LTSS)
15-SP2: https://openqa.suse.de/tests/13779317#dependencies (passed, LTSS)
15-SP1: End of LTSS.
12-SP5: https://openqa.suse.de/tests/13778201#dependencies (passed, no LTSS) …

Enable Horizontal Migration Test in QAM

---

tests/qam-updinstall/update_install.pm

https://confluence.suse.com/display/~dzedro/%5Bmaintenance%5D+update_install+test
- Verification run: https://openqa.suse.de/tests/overview?build=%3A32019%3AwxWidgets-3_2&groupid=490

Change conflict handling and add some features

---

lib/hacluster.pm

Documentation of `lib/hacluster` was missing for some of the functions and for some exported variables. This commits adds it, while also fixing some minor issues such as a missing Oxford comma, the formatting of the input arguments to some of the functions and the font size on the documentation of the newer functions.
- Needles: N/A

Update lib/hacluster POD documentation.

---

lib/hpc/formatter.pm
lib/hpc/utils.pm
tests/hpc/mpi_master.pm
tests/hpc/mpi_slave.pm
tests/hpc/spack_master.pm
tests/hpc/spack_slave.pm

This function is changing the test setting which is somehow confusing as there should be test var MPI and it should simply indicate which MPI version is being used
- Related ticket: https://progress.opensuse.org/issues/137138

HPC: Remove suboptimal get_mpi sub

---

products/sle/main.pm
variables.md

Typically, we running xfstests on the disk witch xfstests is installed. To save disk space, add XFSTESTS_SKIP_INSTALL parameter to running xfstests directly. This eliminates the need to generate qcow2 file with xfstests by PUBLISH_HDD.
- Related ticket: https://progress.opensuse.org/issues/157288
- Needles: N/A
http://10.67.129.54/tests/904 (VIRTIO_CONSOLE=1 XFSTESTS_NO_HEARTBEAT=1)
http://10.67.129.54/tests/899 (VIRTIO_CONSOLE=0)
http://10.67.129.54/tests/906 (XFSTESTS_SKIP_INSTALL=0)
http://10.67.129.54/tests/908 (create_hdd_xfstests)
https://openqa.suse.de/tests/13818606 (public cloud)

xfstests: Add XFSTESTS_SKIP_INSTALL parameter

---

tests/console/validate_zfcp_multipath.pm

Adjust zfcp multipath validation now with dynamic wwid, and verify the same disk is still present which was added.
- Related ticket: https://progress.opensuse.org/issues/157234
- Needles: N/A
- Verification run: http://openqa.suse.de/tests/13818308#step/validate_zfcp_multipath/8

Get dynamic wwid for zfcp-multipath

---

tests/kernel/boot_ltp.pm
tests/kernel/install_ltp.pm
tests/kernel/run_ltp.pm

Add support for optionally printing process backtraces and blocked tasks on test failure.
Also add minor fixes for corner cases in tcpdump and crashdump handling.
- Needles: N/A
- debug disabled: https://openqa.suse.de/tests/13814385
- tasktrace only: https://openqa.suse.de/tests/13814388
- boot_ltp, all debug features: https://openqa.suse.de/tests/13814386
- install_ltp, all debug features: https://openqa.suse.de/tests/13814387

run_ltp: Print tasktrace on test failure

---

tests/x11/remote_desktop/persistent_vncsession_xvnc.pm

The parallel support server takes a long time to setup DHCP server, so the NetworkManager may time out when getting IP address.
So we will make NetworkManager to connect again after DHCP server is ready.
- Related ticket: https://progress.opensuse.org/issues/135977
- Verification run: https://openqa.suse.de/tests/13825711#step/persistent_vncsession_xvnc/8

x11/remote_desktop: make sure to get IP address

---

lib/virt_autotest/utils.pm
tests/virt_autotest/virt_utils.pm

- quinn and fozzie moved to PRG rather than DE office
- Keep the uplevel directory when cleaning up the logs. `/var/log/libvirt/` was removed when uploading logs, it made module libvirt failing to restart.
- Related ticket: https://progress.opensuse.org/issues/153682#note-23
- Related PR: https://github.com/SUSE/qa-automation/pull/820
[gi-guest_sles12sp5-on-host_developing-kvm on quinn](https://openqa.suse.de/tests/13825699)
[prj4_guest_upgrade_sles12sp5_on_sles12sp5-kvm on fozzie](https://openqa.suse.de/tests/13828009)

Regard non-detected location as de for virt machines location

---

tests/migration/online_migration/yast2_migration.pm

Add package conflict workaround for yast migration. During yast migration, if tag match with 'yast2-migration-sle-packageconflict',  send key 'alt-o'. It can continue do migration ignore the conflict package.
- Related ticket: https://progress.opensuse.org/issues/153577
- Verification run: https://openqa.suse.de/tests/13809133#
- Related MR: https://gitlab.suse.de/qe-yam/openqa-job-groups/-/merge_requests/107
- Related MR: https://gitlab.suse.de/qe-yam/openqa-job-groups/-/merge_requests/114

Add package conflict workaround for yast migration

---

lib/bootloader_pvm.pm

powerpc legolas grub loading file is extremely slow via tftpboot,  http protocol replacing tftpboot can improve the speed.
- Related ticket: https://progress.opensuse.org/issues/157630
- Needles: N/A
http://10.67.129.4/tests/70659#step/bootloader/25

Enable grub http protocol to load file from OSD by PPC64LE_GRUB_HTTP

---

lib/qesapdeployment.pm
t/09_qesapdeployment.t
tests/sles4sap/publiccloud/qesap_ansible.pm
tests/sles4sap/qesapdeployment/deploy.pm

This pr removes `qesap_cluster_logs` from individual functions, and adds it in the `post_fail` and `post_run` hooks of `sles4sap_publiccloud_basetest` and `deploy.pm`.
Also, the naming of the files is more representative of the host names.
- Related ticket: https://jira.suse.com/browse/TEAM-9076
- Verification run: https://openqa.suse.de/tests/13837393

Gather cluster logs on success

---

tests/ha/priority_fencing_delay.pm

Two commands joined by a semicolon return two separated exit codes, so it doesn't match **assert_script_run**, it matches after using AND(&&) because only returning one exit code.
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/13846021#step/priority_fencing_delay/35
PS: job#13846021 failed because of node02 job timeout, but **iptables** command worked well

Using AND(&&) to replace semicolon in bash command

---

tests/sles4sap/wizard_hana_install.pm

TEAM-9116 - [15-SP6] sles4sap_scc_textmode_hana_wizard failed on "wizard_hana_install": "You must provide a master password for your install"
TEAM-9115 - [15-SP6] autoyast_sles4sap_hana failed on "installation": "Attempt to `start` service 'firewalld' failed" & "Error while setting pattern: sap-b1"
- Related ticket: [TEAM-9115](https://jira.suse.com/browse/TEAM-9115)
- Needles: NA
- Verification run
sles4sap_scc_gnome_hana_wizard@ppc64le-sap:
-- https://openqa.suse.de/tests/13838764#step/wizard_hana_install/42 (The failed test step passed. It hangs on following steps,  I cancel it as it will be timed out after 4+ hours)
sles4sap_online_dvd_gnome_wizard@64bit-ipmi-nvdimm: 
-- https://openqa.suse.de/tests/13838742#step/wizard_hana_install/49 (The failed test step passed. It hangs on …

Fix wizard_hana_install missing master password

---

data/php/brickmath.php
schedule/qam/common/stack_tests_php.yaml
tests/console/php_composer.pm

Introduce a new test to install Composer2 and verify it locally.
- Related ticket: https://progress.opensuse.org/issues/156124
- Needles: NO
15-SP6 [x86_64](https://openqa.suse.de/tests/13827373#step/php_composer/1) | [aarch64](https://openqa.suse.de/tests/13827378) | [ppc64le](https://openqa.suse.de/tests/13827379) | [s390x](https://openqa.suse.de/tests/13827380)
15-SP5: [x86_64](https://openqa.suse.de/tests/13827381)
15-SP4: [x86_64](https://openqa.suse.de/tests/13827414)

Add a new test to install Composer and verify

---

lib/opensusebasetest.pm

refer to https://jira.suse.com/browse/TEAM-8890?focusedId=1335959&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1335959, ppc64le vm booted twice when enabling **USE_SUPPORT_SERVER**, this PR is a workaround to press the second ret key to fix the issue.
- Related ticket: https://jira.suse.com/browse/TEAM-8890
- Needles: N/A
ppc64le:
https://openqa.suse.de/tests/13845125#step/priority_fencing_delay/15
https://openqa.suse.de/tests/13845142#step/boot_to_desktop#1/5
aarch64:
https://openqa.suse.de/tests/13845133#step/priority_fencing_delay/48
x86_64:
https://openqa.suse.de/tests/13845137#step/priority_fencing_delay/11

Press second ret key when enabling USE_SUPPORT_SERVER

---

products/sle/main.pm
variables.md

In order to save disk and scalability, we intend to decouple installation steps. So that dedicated installation case is no longer necessary.
1. Rename XFSTESTS_SKIP_INSTALL to XFSTESTS_INSTALL to avoid confusion
2. All steps before testing can be run individually (install kdump etc.)
- Related ticket: https://progress.opensuse.org/issues/157756
- Needles: N/A
http://10.67.133.133/tests/529 (create_hdd_xfstests)
http://10.67.133.133/tests/530 (create_hdd_xfstests with klp)
http://10.67.133.133/tests/531 (xfstests with enable_kdump)
http://10.67.133.133/tests/533 (xfstests with klp)
http://10.67.133.133/tests/532 (xfstests with kdump and klp)
http://10.67.133.133/tests/534 (XFSTESTS_INSTALL=1)
https://openqa.suse.de/tests/13858199 (public cloud)

Xfstests: decouple installation steps

---

schedule/sles4sap/cloud-components/cloud_netconfig.yml
tests/sles4sap/cloud_netconfig/deploy.pm
tests/sles4sap/cloud_netconfig/destroy.pm
tests/sles4sap/cloud_netconfig/sanity.pm
tests/sles4sap/cloud_netconfig/test.pm

Rename test module from configure to deploy
Use die always with `()`
Use constant for cloud resources name prefix
Add optional SLE registration
- Related ticket: https://jira.suse.com/browse/TEAM-8721
- sle-15-SP5-SapCloud-Azure-Byos-x86_64-BuildLATEST_AZURE_SLE15_5_BYOS-cloud_netconfig_azure_test@64bit -> http://openqaworker15.qa.suse.cz/tests/279191
- sle-15-SP5-SapCloud-Azure-Payg-x86_64-BuildLATEST_AZURE_SLE15_5_PAYG-cloud_netconfig_azure_test@64bit -> http://openqaworker15.qa.suse.cz/tests/279190

Rename deployment test module for cloud-netconfig

---

lib/main_containers.pm
tests/containers/realtime.pm

Kernel is not compiled with `CONFIG_RT_GROUP_SCHED` option therefore cgroups cpu controller is missing `cpu.rt_.*` features therefore we cannot test docker's or podman's rt updates features. However we can still test whether containers are capable of running RT processes.
- ticket: https://progress.opensuse.org/issues/136307
* [docker](http://kepler.suse.cz/tests/23038#live)
* [podman](http://kepler.suse.cz/tests/23037#live)

Run RT workload in container

---

lib/publiccloud/provider.pm

Fix missing space between arguments in code under PUBLIC_CLOUD_SLES4SAP
- Related ticket: poo#6074
- Verification run:  sle-15-SP5-Azure-SAP-BYOS-Incidents-saptune-x86_64-Build:32998:aaa_base-sles4sap_gnome_saptune_delete_rename@az_Standard_E8s_v3 -> http://openqaworker15.qa.suse.cz/tests/279251

Fix cmd composition for terraform destroy

---

lib/sles4sap_publiccloud.pm
t/12_sles4sap_publicccloud.t
tests/sles4sap/publiccloud/hana_sr_takeover.pm
tests/sles4sap/publiccloud/qesap_ansible.pm
tests/sles4sap/publiccloud/qesap_reuse_infra.pm
tests/sles4sap/publiccloud/qesap_terraform.pm

Unify the way function arguments are managed across all function in this lib. Add more UT coverage.
Design principle for this change are:
- always use arguments as HASH
- avoid copy args to local variables if not needed
- croak for args validation as soon as possible, using always same message format, not using `(` and `)` if not needed
- document all args
- not export functions only used internally
- http://openqaworker15.qa.suse.cz/tests/279250
- http://openqaworker15.qa.suse.cz/tests/279179 :green_circle: 
-  http://openqaworker15.qa.suse.cz/tests/279248  :green_circle:
- http://openqaworker15.qa.suse.cz/tests/279180 :green_circle: 
- http://openqaworker15.qa.suse.cz/tests/279181 :red_circle: fails for issue in https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/18933
- …

Manage sub arguments in sles4sap PC lib

---

tests/publiccloud/img_proof.pm

Add swap unconditionally to hardened tests.
- Related ticket: https://progress.opensuse.org/issues/158062
- EC2: https://openqa.suse.de/tests/13880041
- Azure: https://openqa.suse.de/tests/13878442
NOTE: VR's fail due to https://bugzilla.suse.com/show_bug.cgi?id=1220269.  What matters is that the report.html is generated.

pc: Add swap unconditionally to hardened tests

---

tests/x11/remote_desktop/persistent_vncsession_xvnc.pm

Sometimes the test fails because it does not log out the persistent vnc session.  Because it chooses the host 'system-indicator' instead of 'system-indicator' in vnc session.
So add a more specific tag 'vnc-system-indicator'.
- Related ticket: https://progress.opensuse.org/issues/158077
- Needles: added
https://openqa.suse.de/tests/13885281#step/persistent_vncsession_xvnc/51

x11/remote_desktop: make test more robust by using a more specific tag

---

tests/migration/online_migration/yast2_migration.pm

Import untrusted GnuPG key for online migration test
- Related ticket: https://progress.opensuse.org/issues/157411
- Verification run: https://openqa.suse.de/tests/13874510

Import untrusted GnuPG key for online migration test

---

products/sle/main.pm
tests/xfstests/install.pm
variables.md

1. Check whether xfstests is installed before installation.
2. call the klp and kdump module after installation.
- Related ticket: https://progress.opensuse.org/issues/158074
- Needles: N/A
http://10.67.133.133/tests/547 (create_hdd)
http://10.67.133.133/tests/548 (create_hdd-klp)
http://10.67.133.133/tests/546 (create_hdd-klp, skip install)
http://10.67.133.133/tests/559 (xfstests, install klp)
http://10.67.133.133/tests/552 (xfstests)
http://10.67.133.133/tests/556 (xfstests, install xfstests, install klp)
http://10.67.133.133/tests/554 (xfstests, install xfstests, install kdump)
https://openqa.suse.de/tests/13885755 (public cloud)

xfstests: fix install issue

---

tests/migration/online_migration/pre_migration.pm

Import gpg key before migration
- Related ticket: http://progress.opensuse.org/issues/157411
- Verification run: https://openqa.suse.de/tests/13888621

Import gpg key before migration

---

data/autoyast_qam/12-common_base_installation.xml.ep
data/autoyast_qam/15-common_base_installation.xml.ep
tests/console/kdump_and_crash.pm

- Related ticket: https://progress.opensuse.org/issues/126089
- Verification run: https://openqa.suse.de/tests/overview?build=jpupava_mpath&distri=sle

Use ay profile for multipath installation

---

lib/serial_terminal.pm

After the product rename from SLE Micro to SL Micro, some tests using svirt backend started to fail because the "Enterprise" is gone from the prompt and the name.
VRs:
6.0: https://openqa.suse.de/tests/13892579#step/boot_to_desktop/10
5.5: https://openqa.suse.de/tests/13892582#step/boot_to_desktop/10
(tests are stopped after this change takes effect and passing)

Fix expected login message for SL Micro

---

tests/containers/container_engine.pm

Adds a conditional softfailure for bsc#1212825 where there is a race condition in docker/podman stop.
- Related failure: https://openqa.suse.de/tests/13886270#step/docker/133
- Verification run: [TW-podman](https://openqa.opensuse.org/tests/4045469) (unrelated failure) | [TW-docker](https://openqa.opensuse.org/tests/4045468)

Add softfailure for bsc#1212825

---

lib/sles4sap_publiccloud.pm
t/12_sles4sap_publicccloud.t
tests/sles4sap/publiccloud/hana_sr_takeover.pm

Adds a function wrapper for `cs_wait_for_idle`, which gathers info and retries in case of timeout. Replaces direct use of `cs_wait_for_idle` with the new function.
- Related ticket: https://jira.suse.com/browse/TEAM-9180
-- `cs_wait_for_idle` fails with rc 124: https://openqa.suse.de/tests/13881104#step/Crash_site_a-primary/641
-- cs_clusterstatus is executed: https://openqa.suse.de/tests/13881104#step/Crash_site_a-primary/663
-- crm mon is executed: https://openqa.suse.de/tests/13881104#step/Crash_site_a-primary/685
-- SAPHanaSR-showattr is executed: https://openqa.suse.de/tests/13881104#step/Crash_site_a-primary/707
finally, cs_wait_for_idle is re-run one more time (this time if it fails, it fails) and passes: …

Add 'wait_for_idle' wrapper function

---

tests/migration/online_migration/yast2_migration.pm

Reverts os-autoinst/os-autoinst-distri-opensuse#18966 
Not needed any more since https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/18972 merged.
VR: https://openqa.suse.de/tests/13896892#step/yast2_migration/6

Revert "Import untrusted GnuPG key for online migration test"

---

tests/sles4sap/grafana_dashboards.pm

the layout of dashboard has some changes on 15-SP6, this results in the case sles4sap_grafana_dashboards failed, this PR fixed the issue.
- Related ticket: https://jira.suse.com/browse/TEAM-8806
- Needles:
https://openqa.suse.de/tests/13890881#step/grafana_dashboards/41
https://openqa.suse.de/tests/13890881#step/grafana_dashboards/42
https://openqa.suse.de/tests/13890881#step/grafana_dashboards/43
https://openqa.suse.de/tests/13890881#step/grafana_dashboards/44
https://openqa.suse.de/tests/13896909
https://openqa.suse.de/tests/13896920
https://openqa.suse.de/tests/13896925

Fix dashboard broken issue in new version of grafana

---

data/virt_autotest/host_unattended_installation_files/autoyast/dev_host_12.xml.ep
data/virt_autotest/host_unattended_installation_files/autoyast/dev_host_15.xml.ep
lib/ipmi_backend_utils.pm
tests/virt_autotest/sriov_network_card_pci_passthrough.pm

Remove intel_iommu=on from xen dom0 kernel command
- Related ticket: https://bugzilla.suse.com/show_bug.cgi?id=1217541#c30 & https://progress.opensuse.org/issues/157711
[sriov tests on sle15sp6 xen](https://openqa.suse.de/tests/13858450)
[sriov tests on sle15sp5 kvm](https://openqa.suse.de/tests/13857439)

Remove intel_iommu=on from xen dom0 kernel command

---

tests/migration/online_migration/zypper_migration.pm

After product rename, the product is now called SL Micro without Enterprise in it.
VR: http://openqa.suse.de/tests/13892851

Remove Enterprise from the online migration using zypper

---

lib/bootloader_setup.pm

Fix poo#158203: SLE Micro 6.0 was renamed to SL Micro. We need to make difference for is_sle_micro by version.
- Related ticket: https://progress.opensuse.org/issues/158203
SL Micro: https://openqa.suse.de/tests/13897597
SLE Micro 5.5: https://openqa.suse.de/tests/13897610#

Add support for SL Micro to add_custom_grub_entries

---

data/virtualization/autoyast/host_12.xml.ep
data/virtualization/autoyast/host_15.xml.ep

Remove intel_iommu=on from xen dom0 kernel command line - MU part
- Related ticket: https://progress.opensuse.org/issues/157954
- Needles: N/A
- [sles15sp5](http://openqa.qam.suse.cz/tests/overview?build=PR%3Atest%3A18954%3Awitch&distri=sle&version=15-SP5&groupid=168)
- [sles12sp5](http://openqa.qam.suse.cz/tests/overview?build=PR%3Atest%3A18954%3Awizard&distri=sle&version=12-SP5&groupid=160)

Remove intel_iommu=on from Xen Dom0 kernel command line - MU part

---

tests/console/krb5.pm

https://progress.opensuse.org/issues/157960
- Verification run: [sle-aarch64](http://openqa.suse.de/tests/overview?build=rfan0328_krb5_timeout_fix&version=15-SP5&distri=sle)

Add some timeout for krb5 test

---

data/virt_autotest/host_unattended_installation_files/autoyast/dev_host_12.xml.ep

* **Turning** bridge_stp on may cause malfunctioning server after successful installation. System waits for wicked interface to be up for good and fails to boot up. Please refer to bsc#1222105.
* **Turning** bridge_stp off can help solve the problem.
* [15sp6 on 12sp5 kvm sapworker3:2](https://openqa.suse.de/tests/13897604)
* [15sp6 on 12sp5 xen worker35:49](https://openqa.suse.de/tests/13897160)
* [15sp6 on 12sp5 xen  imagetester:8](https://openqa.suse.de/tests/13897111)
* [12sp5 to 15sp6 host upgrade xen imagetester:2](https://openqa.suse.de/tests/13897609)
* [12sp5 to 15sp6 host ugprade kvm imagetester:8](https://openqa.suse.de/tests/13897112)

Turn bridge_stp off to unblock SLE 12-SP5 autoyast installation

---

tests/sles4sap/hana_cluster.pm

Increase test module "hana_cluster" command "hdbsql" timed out value to 900 
TEAM-9013 - [15sp6][SLES for SAP Applications] SAPHanaSR_ScaleUp_PerfOpt_WMP failed on hana_cluster: hdbsql timed out
- Related ticket: https://jira.suse.com/browse/TEAM-9013
- Needles: NA
http://openqa.suse.de/tests/13906708#step/hana_cluster/43 (hdbsql succeeded, new failures are other issues)
(0 rows affected (overall time 244.922078 sec; server time 244.921632 sec))
https://openqa.suse.de/tests/13906831#step/hana_cluster/43 (hdbsql succeeded, new failures are other issues)
(0 rows affected (overall time 516.465933 sec; server time 516.465597 sec))

Increase hana_cluster hdbsql timed out value to 900

---

schedule/functional/extra_tests_textmode.yaml

https://progress.opensuse.org/issues/157963
Run libgit2 test on x86_64 and aarch64
**There are some issues on s390x and ppc64le, see https://github.com/libgit2/libgit2/issues/6784**
[s390x](http://openqa.suse.de/tests/13896881#)
[ppc64kle](http://openqa.suse.de/tests/13896883#)
[aarch64](http://openqa.suse.de/tests/13896995#)
[x86_64](http://openqa.suse.de/tests/13896998#)

Schedule libgit2 test

---

tests/xfstests/generate_report.pm

The generate_report part has a minor issue could see in web result https://openqa.suse.de/tests/13918278#step/generate_report/13
- Related ticket: https://progress.opensuse.org/issues/158083
- SLE https://openqa.suse.de/tests/13919118
- Public cloud https://openqa.suse.de/tests/13919167

xfstests: Fix a minor issue in generate_report

---

lib/main_common.pm

Fix poo#158161: rasdaemon was disabled on ppc64le architecture on Tumbleweed because of bsc#1219917. Bug was fixed and we can enable test again.
- Related ticket: https://progress.opensuse.org/issues/158161
TW x86_64: https://openqa.opensuse.org/tests/4045380   (test is included)
TW ppc64le: https://openqa.opensuse.org/tests/4045378 (test is included, installation passed, but failed at later stage)
SLE x86_64: https://openqa.suse.de/tests/13892393 (test is included)
SLE ppc64le:  https://openqa.suse.de/tests/13892392  (test excluded)

Enable rasdaemon on all architectures on Tumbleweed

---

tests/sles4sap/hana_install.pm

bsc#1195133 is fixed, so we could remove this workaround.
https://openqa.suse.de/tests/13919147#
https://openqa.suse.de/tests/13919146#
https://openqa.suse.de/tests/13919145#
https://openqa.suse.de/tests/13919143#

Remove the workaround for bsc1195133

---

tests/installation/disable_kdump.pm

installation conformation dialog didn't pop up after pressing alt-i, this resulted in matching needle timeout, this PR fixed this issue or at least reduce the frequency of this issue
- Related ticket: https://jira.suse.com/browse/TEAM-9210
- Needles: N/A
https://openqa.suse.de/tests/13907188
https://openqa.suse.de/tests/13907189

Make sure pressing alt-i at the right time when starting installation

---

tests/console/sudo.pm
tests/publiccloud/prepare_instance.pm

Fix the workflow for the testapi user (bernhard) on publiccloud by allowing the testapi user to run sudo commands.
Also check in the sudo test runs for the expected user for the password input.
The rationale for those changes can be found as summary in https://progress.opensuse.org/issues/156649#note-20.
- Related ticket: https://progress.opensuse.org/issues/156649
- [Tumbleweed](https://openqa.opensuse.org/tests/4048726#step/sudo/9) (unrelated failure in `check_os_release`)
- [15-SP5 Azure-Basic](https://duck-norris.qe.suse.de/tests/14565#step/sudo/9)
- [15-SP5 EC2](https://duck-norris.qe.suse.de/tests/14566#step/sudo/9)
- [15-SP4 Azure-BYOS](https://duck-norris.qe.suse.de/tests/14567#step/sudo/9)
- [15-SP3 GCE-BYOS](https://duck-norris.qe.suse.de/tests/14564#step/sudo/ …

Fix sudo workflow for testapi user

---

tests/installation/add_serial_console.pm

To resolve [bsc#1219463](https://bugzilla.suse.com/show_bug.cgi?id=1219463), it requires to change the serial command parameter for workaround during installation.
```
From
> GRUB_SERIAL_COMMAND="serial"
To
> GRUB_SERIAL_COMMAND="serial --unit=0"
```
- Related ticket: https://progress.opensuse.org/issues/157714
- Verification run: [default_install_svirt@svirt-vmware70](https://openqa.suse.de/tests/13899471), [textmode_svirt@svirt-vmware70](https://openqa.suse.de/tests/13899479)

Specify the serial unit to avoid Page Fault issue in grub 2.12

---

schedule/yast/sle/flows/default_s390x_kvm_textmode.yaml

Do not use 'stop_timeout_system_reboot_now' in default schedule for s390x kvm on textmode.
- Related ticket: https://progress.opensuse.org/issues/157936
- Related MR: https://gitlab.suse.de/qe-yam/openqa-job-groups/-/merge_requests/131
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/13906725#step/system_prepare/3 (now failed for bsc#1221005)

Add default schedule for s390x kvm on textmode

---

data/virt_autotest/host_unattended_installation_files/autoyast/dev_host_12.xml.ep

SLE 12-SP5 autoyast host installation does not use second stage due to product bug bsc#1216859. XEN_DEFAULT_BOOT_IS_SET=1 does not take effect, for example, [failure 1](https://openqa.suse.de/tests/13919059#step/login_console/29), [2](https://openqa.suse.de/tests/13913446#step/login_console/29) and [3](https://openqa.suse.de/tests/13919109#step/login_console/29).
- Related ticket: https://gitlab.suse.de/qa-testsuites/openqa-job-group-yaml/-/merge_requests/178
[sle12sp5 xen on my indevidual openqa](http://10.67.129.27/tests/336)
[on OSD](http://openqa.suse.de/tests/13924074)

Set default xen boot for virt sle12 xen tests with autoyast installation

---

tests/containers/podman_integration.pm

Add pasta dependency for podman upstream tests.
- Verification run: https://openqa.opensuse.org/tests/4056084 (failing because of https://bugzilla.opensuse.org/show_bug.cgi?id=1221840)

containers: Add pasta dependency for podman upstream tests

---

tests/x11/toolkits/prepare.pm
tests/x11/toolkits/qt6.pm

Since for qt6 there's no L3 support on SLE disable its testing except for openSUSE
- Don't install qt6 devel on sles packages as they are not supported
- Exit early if is SLE as per PED-7127
VR: https://openqa.suse.de/tests/13924395#live

Disable Qt6 devel toolkit package tests on sles

---

data/virt_autotest/host_unattended_installation_files/combustion/script
data/virt_autotest/host_unattended_installation_files/ignition/config.ign
lib/bootloader_setup.pm
lib/ipmi_backend_utils.pm
lib/utils.pm
schedule/virt_autotest/slem6_baremetal_usb_install.yaml
tests/installation/bootloader_uefi.pm
tests/installation/ipxe_install.pm
tests/installation/usb_install.pm
tests/microos/selfinstall.pm

This PR mainly provides a way of baremetal machine installation via USB for sle micro 6, which does not have DVD image any more.
Related ticket: https://progress.opensuse.org/issues/151498
Needles: [MR link](https://gitlab.suse.de/openqa/os-autoinst-needles-sles/-/merge_requests/1653)
- SLE MICRO 6 VT test:
- USB INSTALL , sle micro 6: http://10.67.129.77/tests/318#, PASS
- Default-qcow, vt test: http://openqa.suse.de/tests/13831550, PASS
- kernel test
- AUTOYAST=1,  IPXE_UEFI=1, worker class 64bit-i915: http://openqa.suse.de/tests/13831512: PASS
- VT test:
- AUTOYAST=1, IPXE=1, http://openqa.suse.de/tests/13831529: PASS for host installation
- AUTOYAST=0, IPXE=1, http://openqa.suse.de/tests/13838285: PASS for host installation
- SLE MICRO 6 Container test
- …

Support bare metal installation with ISO on USB

---

tests/security/cc/audit_remote_libvirt.pm

Modular mode libvirt check has been done by @jknphy in #18110. This simply changes the check to cover 15-SP5 as well.
- Related ticket: https://progress.opensuse.org/issues/156658
- Verification run: https://openqa.suse.de/tests/13924430
The VR has failed, but due to a different issue. It is passing the point which is fixed by this PR when compared to the old run: https://openqa.suse.de/tests/13817297#step/audit_remote_libvirt/10

Libvirt in modular mode on 15-SP5

---

data/journal_check/bug_refs.json

In order to verify that combustion prepare ran, the test writes a mock message in the logs.
- VR: http://kepler.suse.cz/tests/23057#step/journal_check/1

Ignore test message from combustion

---

lib/utils.pm

The wrong condition caused the wrong x11 tty for leap kde migration test.
- Failed job: https://openqa.suse.de/tests/13922392#step/post_migration/16
- Needles: N/A
- Verification run: http://openqa.suse.de/tests/13932297#step/post_migration/14

Fix leap kde test switch x11 console issue

---

tests/jeos/firstrun.pm

- Related ticket: https://progress.opensuse.org/issues/158479
- Needles: Created on o3 already
https://openqa.opensuse.org/tests/4061491 (with TPM)
https://openqa.opensuse.org/tests/4061492 (no TPM)

jeos/firstrun.pm: Handle the new menu driven disk-encryption-tool flow

---

tests/qam-updinstall/update_install.pm

It can happen the option is entered too early and the expect get stuck

Add short sleep time into except script

---

lib/Distribution/Sle/15_current.pm
lib/Installation/CommonCriteriaConfiguration/CommonCriteriaConfigurationController.pm
lib/Installation/CommonCriteriaConfiguration/CommonCriteriaConfigurationPage.pm
lib/Installation/SystemRole/Sle/SystemRoleController.pm
lib/Installation/SystemRole/SystemRoleController.pm
schedule/security/create_hdd_cc_libyui/cc.yaml
schedule/security/create_hdd_cc_libyui/cc_qr.yaml
schedule/security/create_hdd_cc_libyui/cc_qr_aarch64.yaml
schedule/security/create_hdd_cc_libyui/cc_qr_s390x.yaml
schedule/security/create_hdd_cc_libyui/cc_qr_x86_64.yaml
schedule/security/create_hdd_cc_libyui/cc_s390x.yaml
tests/installation/common_criteria_configuration/common_criteria_encryption_pwd.pm
tests/installation/logs_from_installation_system.pm
tests/installation/system_role/select_common_criteria_role.pm
tests/security/atsec/setup_atsec_env.pm
tests/security/boot_encrypt_no_video_present.pm

Ticket: https://progress.opensuse.org/issues/156655
VRs:
- 15-SP6: https://openqa.suse.de/tests/overview?distri=sle&version=15-SP6&build=77.1&groupid=431
- 15-SP5-QR: https://openqa.suse.de/tests/overview?distri=sle&version=15-SP5&build=137.7&groupid=431
Please note that s390x is green only because I've applied a workaround to the current known ssh bug. Installation tests will be red on that platform until that bug is fixed.

Switch CC installation test from autoyast to libyui

---

tests/microos/patterns.pm

This ammends the removal of this condition in https://github.com/os-autoinst/os-autoinst-distri-opensuse/commit/c0ca4b7e6e0d3d062ad75fd0e9e7efd830021fa3
VR: http://openqa.suse.de/tests/13944528

Recover condition not to install alp_elemental_client in SLM6.0

---

tests/kernel/install_ltp.pm

https://openqa.suse.de/tests/13945402

Fix for not installing efivar in SL Micro 6.0

---

tests/qam-updinstall/update_install.pm

https://openqa.suse.de/tests/13939716#step/update_install/149
```
2 Problems:
Problem: the to be installed python-azure-agent-config-server-2.9.1.1-150100.3.29.1.noarch conflicts with 'namespace:otherproviders(waagent-config)' provided by the to be installed python-azure-agent-config-default-2.9.1.1-150100.3.29.1.noarch
Problem: the to be installed python-azure-agent-config-micro-2.9.1.1-150100.3.29.1.noarch conflicts with 'namespace:otherproviders(waagent-config)' provided by the to be installed python-azure-agent-config-hpc-2.9.1.1-150100.3.29.1.noarch
Problem: the to be installed python-azure-agent-config-server-2.9.1.1-150100.3.29.1.noarch conflicts with 'namespace:otherproviders(waagent-config)' provided by the to be installed …
```

Add conflict for python-azure-agent-config-(server|micro|hpc)

---

tests/console/verify_efi_mok.pm

Our VMware machines cannot run VMs with configured SecureBoot, the option is missing there. As of now, we can skip this check
- ticket: https://progress.opensuse.org/issues/158308
- Verification run: https://openqa.suse.de/tests/13951382

Skip MOK check in VMware runs

---

lib/main_micro_alp.pm

We are missing combustion/ignition vmdk images, hence configure vmware sl-micro 6.0 using jeos-firstboot.
As a future improvement, I think we should have one subroutine that boots images across all products.
- Related ticket: https://progress.opensuse.org/issues/158344
- Verification run: http://kepler.suse.cz/tests/23075#step/bootloader_uefi/3

Boot sl-micro in vmware

---

tests/migration/online_migration/zypper_migration.pm

After PR: https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/18936/files
Some tests break due to different var naming for before and after migration version. Removing the verify_os_version will fix the problem.
VRs:
SAP: https://openqa.suse.de/tests/13951421
Yast slem: 13946786https://openqa.suse.de/tests/13951422

Remove verify_os_version form zypper_migration module

---

lib/bootloader_setup.pm
lib/main_micro_alp.pm
tests/installation/bootloader_uefi.pm

VMWare image can be configured either by ignition/combustion or using
jeos-firstboot as a fallback. Boot test modules should be the same as
used in Minimal-VM VMWare tests.
- ticket: https://progress.opensuse.org/issues/158344
* [VMware-x86_64-Build5.12-slem_docker](http://kepler.suse.cz/tests/23090#step/firstrun/7)
* [microos-Tumbleweed-DVD-x86_64-Build20240404-microos@uefi](http://kepler.suse.cz/tests/23089#)
* [microos-Tumbleweed-MicroOS-Image-x86_64-Build20240404-microos@64bit](http://kepler.suse.cz/tests/23088#)
* [microos-Tumbleweed-MicroOS-Image-x86_64-Build20240404-microos-wizard](http://kepler.suse.cz/tests/23087#)

Boot sl-micro 6.0 in VMWare

---

schedule/hpc/multi_machine_test.yaml
tests/hpc/barrier_init.pm
tests/hpc/mpi_imb.pm
tests/hpc/mpi_master.pm
tests/hpc/mpi_slave.pm

The idea is to use scheduler to load required test modules based on specific test variables. In such case the barriers for scientific libs should be conditional
- Related ticket: https://progress.opensuse.org/issues/126842
SLE15sp6: openmpi, no IMB test:
https://openqa.suse.de/tests/13919390
https://openqa.suse.de/tests/13919391
https://openqa.suse.de/tests/13919389
https://openqa.suse.de/tests/13919392
sle15sp6: openmpi, with IMB test:
https://openqa.suse.de/tests/13919413
https://openqa.suse.de/tests/13919412
https://openqa.suse.de/tests/13919414
https://openqa.suse.de/tests/13919411
sle15sp6: mpich, no IMB test:
https://openqa.suse.de/tests/13919464
https://openqa.suse.de/tests/13919461
https://openqa.suse.de/tests/13919463
https://openqa.suse.de/tests/13919462 …

HPC: Move imb tests from mpi_master to specific pm test module

---

tests/virt_autotest/guest_installation_run.pm

Enhancement for s390x guest installation
- Related ticket: https://progress.opensuse.org/issues/157495
s390x
[gi-guest_developing-on-host_sles15sp5-kvm](https://openqa.suse.de/tests/13952406#) PASS
x86_64
[gi-guest_developing-on-host_developing-kvm](https://openqa.suse.de/tests/13952584#) PASS
[gi-guest_developing-on-host_developing-xen](https://openqa.suse.de/tests/13952585#) PASS

virt_autotest: enhancement s390x guest_installation_run

---

tests/virt_autotest/login_console.pm

PXE boot needle mismatch, fix it.
- Related ticket:  https://progress.opensuse.org/issues/158389
- Needles: NA
- Verification run: http://openqa.qam.suse.cz/tests/70845#step/login_console/1

Match pxe boot needle

---

lib/YaST/NetworkSettings/NetworkCardSetup/VLANAddressTab.pm

Extend timeout to get the expected needle
- Related ticket: https://progress.opensuse.org/issues/158158
- Verification run: Rerun eight times. All of them can pass https://openqa.suse.de/tests/13960378#next_previous

Extend timeout to get the expected needle

---

data/virtualization/autoyast/host_15.xml.ep

Progress ticket: https://progress.opensuse.org/issues/157954
1. IOMMU Enabled by Default: The iommu=on setting is activated by default, negating the need for manual kernel parameter adjustments for IOMMU support.
2. Specific Requirement for Intel Machines: For KVM virtualization on systems, only intel_iommu=on is explicitly required to enable IOMMU functionality for Intel-based systems. This adjustment reflects a focus on Intel hardware, with amd_iommu=on no longer needed in this context on AMD CPU system. The requirement to explicitly set IOMMU functionality does not apply to Xen environments.
3. SR-IOV Testing Considerations: The parameter iommu=on is removed from SLE12SP5 due to the absence of SR-IOV testing. In contrast, for SLE15, where SR-IOV tests are performed, the parameter …

Configuring Dynamic IOMMU Settings for KVM Boot Parameters

---

lib/guest_installation_and_configuration_base.pm

* **Turning** ipv6 forwarding on may interrupt network connection which can not be recovered, which was already reported as bug bsc#1222229. 
* **Turning** it off is the right thing to do at the moment, because there are still many failures with the latest build, for example, failure [1](https://openqa.suse.de/tests/13957270#step/unified_guest_installation/332) and [2](https://openqa.suse.de/tests/13957418#step/unified_guest_installation/332).
* [uefi 15sp6 on 15sp6 xen](https://openqa.suse.de/tests/13963851)
* [uefi 12sp5 on 15sp6 kvm](https://openqa.suse.de/tests/13963852)
* [uefi 12sp5 on 15sp6 xen](https://openqa.suse.de/tests/13963853)
* [uefi 15sp5 on 15sp6 kvm](https://openqa.suse.de/tests/13963874)
* [uefi 15sp5 on 15sp6 …

Turning ipv6 forwarding off to workaround bsc#1222229

---

lib/saputils.pm
t/18_saputils.t

check_hana_topology support parameter to detect if site is online. This allow to support new output of SAPHanaSR_showAttr that come from Pacemaker 2.1.7
Improve robustness by checking that all needed field of SAPHanaSR_showAttr are there.
More UT.
If you like to see how this one can works with Pacemaker 2.1.7, please have a look at unit test https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/19036/files#diff-0c9ef3d4a34a0953c21cbd57904ed0b557a64696e56e0ac7d47bc9d1e73edbd1R131 and argument `, node_state_match => '[1-9]'`
- Related ticket: https://jira.suse.com/browse/TEAM-9022
- sle-15-SP5-HanaSr-Azure-Byos-x86_64-Build15-SP5_2024-04-05T04:03:14Z-hanasr_azure_test_msi@64bit -> http://openqaworker15.qa.suse.cz/tests/280025 http://openqaworker15.qa.suse.cz/tests/280030 …

Make check_hana_topology more flexible

---

products/sle/main.pm

Enable xfstests in KOTD
- Related ticket: https://progress.opensuse.org/issues/154597
- Needles: N/A
- Verification run: http://10.67.133.133/tests/573

xfstests: Add steps to install KOTD kernel

---

tests/x11/vnc_two_passwords.pm

- Related ticket: https://progress.opensuse.org/issues/158622
- Verification run: https://openqa.suse.de/tests/13964702

vnc_two_passwords: Increase vnc_password_dialog timeout

---

tests/ha/ha_cluster_join.pm

Fix ha_cluster_join type_password failure: lower the max_interval slower the typing
TEAM-9222 - [15-SP6][HA][x86+ppc64le][sporadic] ha_delta_node* failed on "ha_cluster_join": 'systemctl start pacemaker' timed out
- Related ticket: https://jira.suse.com/browse/TEAM-9222
- Needles: NA
Tried 5 times all passed:
passed:   http://openqa.suse.de/tests/13960769#dependencies
passed:  http://openqa.suse.de/tests/13960804#dependencies
passed:  http://openqa.suse.de/tests/13960810#dependencies
passed:  http://openqa.suse.de/tests/13960815#dependencies
passed:  http://openqa.suse.de/tests/13960820#dependencies

Fix ha_cluster_join type_password failure

---

tests/publiccloud/img_proof.pm

Use .txt extension for img-proof logs to make them browser friendly and avoid downloading them.

pc: Use .txt extension for img-proof logs

---

tests/installation/bootloader_uefi.pm
tests/installation/ipxe_install.pm

We are going to deploy the SL Micro 6 baremetal test on OSD kermit machine. This machine's behavior is different from earlier automation tested machine in BJ. So this PR is to workaround/fix 2 issues on it.
- kermit does not support pressing F10 to start installation, but only ctrl+x
- kermit needs to specify `initrd=initrd` on pxe boot kernel line
- Related ticket: https://progress.opensuse.org/issues/151498#  
- sle micro uefi usb boot: 
- http://10.67.129.77/tests/333, PASS on BJ HP machine vh015
- http://openqa.suse.de/tests/13964355: OSD kermit machine, expected FAIL by bug 1222411, other verification parts are good, so fix/workaround for it works
- legacy boot sles test:
- https://openqa.suse.de/tests/13971351, PASS
- uefi boot sles test: I tried to verify it as …

Workaround/fix to let usb boot works on old Supermicro machines

---

tests/installation/bootloader_uefi.pm

follow up
for https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/19034
* http://kepler.suse.cz/tests/23092#step/bootloader_uefi/4
* http://kepler.suse.cz/tests/23093#

Select correct GRUB entry in selfinstall

---

data/virt_autotest/guest_params_xml_files/slm_6_0_64_kvm_hvm_x86_64_default_encrypted_ignition+combustion.xml
data/virt_autotest/guest_params_xml_files/slm_6_0_64_kvm_hvm_x86_64_default_encrypted_ignition.xml
data/virt_autotest/guest_params_xml_files/slm_6_0_64_kvm_hvm_x86_64_default_qcow_ignition+combustion.xml
data/virt_autotest/guest_params_xml_files/slm_6_0_64_kvm_hvm_x86_64_default_qcow_ignition.xml
data/virt_autotest/guest_params_xml_files/slm_6_0_64_kvm_hvm_x86_64_default_raw_ignition+combustion.xml
data/virt_autotest/guest_params_xml_files/slm_6_0_64_kvm_hvm_x86_64_default_raw_ignition.xml
lib/guest_installation_and_configuration_base.pm
lib/guest_installation_and_configuration_metadata.pm

* **SUSE** Linux Micro is the new product name for version 6.0 which needs to be updated in corresponding places. 
* **And** grouping common parameters that are pertinent to host in one global structure ```%host_params``` in ```guest_installation_and_configuration_metadata.pm``` ensures more clear and neat layout.
*  [**SL Micro 6.0 on SL Micro 6.0** link1](http://10.100.228.134/tests/2397) [link2](http://10.100.204.18/tests/2397) [link3](http://10.67.18.153/tests/2397) [link4](http://10.149.193.170/tests/2397)
*  [**sles15sp5 on SL Micro 6.0** link1](http://10.100.228.134/tests/2396) [link2](http://10.100.204.18/tests/2396) [link3](http://10.67.18.153/tests/2396) [link4](http://10.149.193.170/tests/2396)
* [15sp6 on 15sp6 …

Update product name for SL Micro 6.0 and group commmon parameters

---

tests/containers/podman_integration.pm

Add missing dependency for podman upstream tests
Failing tests:
- https://openqa.suse.de/tests/13972590
- https://openqa.suse.de/tests/13972588
- 15-SP4 (aarch64): https://openqa.suse.de/tests/13973408
- 15-SP5 (x86_64): https://openqa.suse.de/tests/13973409

containers: Add missing dependency for podman upstream tests

---

data/autoyast_qam/15_installtest.xml.ep

installtest images are created with repos:
HA
SLE-Product-SLES
SLE-Product-HA
SLE-Module-Basesystem
SLE-Module-Server-Applications
SAP
SLE-Product-SLES_SAP
SLE-Product-HA
SLE-Module-Basesystem
SLE-Module-Containers
SLE-Module-Desktop-Applications
SLE-Module-Development-Tools
SLE-Module-Legacy
SLE-Module-Packagehub-Subpackages
SLE-Module-Public-Cloud
SLE-Module-Python3 *
SLE-Module-SAP-Applications
SLE-Module-Server-Applications
SLE-Module-Web-Scripting
SLES
SLE-Product-SLES
SLE-Product-WE only on x86_64
SLE-Module-Basesystem
SLE-Module-Containers
SLE-Module-Desktop-Applications
SLE-Module-Development-Tools
SLE-Module-Legacy
SLE-Module-Packagehub-Subpackages
SLE-Module-Public-Cloud
SLE-Module-Python3 *
SLE-Module-Server-Applications
SLE-Module-Web-Scripting
SLED
SLE-Product-SLED …

HA image only with Basesystem, Server Applications and HA Extension

---

lib/sles4sap_publiccloud.pm
t/12_sles4sap_publicccloud.t

Remove regression introduced in previous commit that force undefined argument to get value the string 'undefined'.
Add unit testing.
- Related ticket: https://jira.suse.com/browse/TEAM-9232
- Fix regression introduced in https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/18937
- sle-15-SP4-HanaSr-Aws-Byos-x86_64-Build15-SP4_2024-04-09T04:03:11Z-hanasr_aws_test_saptune@64bit -> http://openqaworker15.qa.suse.cz/tests/280284 :green_apple:  `terraform destroy` called in case of failure http://openqaworker15.qa.suse.cz/tests/280284#step/deploy_qesap_ansible/406
- sle-15-SP4-HanaSr-Azure-Byos-x86_64-Build15-SP4_2024-04-09T04:03:11Z-hanasr_azure_test_sapconf_sbd@64bit -> http://openqaworker15.qa.suse.cz/tests/280285

Fix sles4sap_cleanup about undefined arguments

---

lib/sles4sap_publiccloud.pm
t/12_sles4sap_publicccloud.t

Remove a get_var from azure_fencing_agents_playbook_args and convert to sub argument. Caller will read from the var. It keep the code simpler. Improve debug logs from stop_db sub, for the crash testcase.
- Related ticket: https://jira.suse.com/browse/TEAM-9215
- sle-15-SP5-HanaSr-Azure-Byos-x86_64-Build15-SP5_2024-04-09T04:03:11Z-hanasr_azure_test_spn@64bit -> http://openqaworker15.qa.suse.cz/tests/280299
- sle-15-SP5-HanaSr-Azure-Byos-x86_64-Build15-SP5_2024-04-09T04:03:11Z-hanasr_azure_test_msi@64bit -> http://openqaworker15.qa.suse.cz/tests/280300

Convert get_var to explicit sub argument

---

tests/security/cc/cc_selinux_setup.pm

- Related ticket: https://progress.opensuse.org/issues/158781
- Verification run: https://openqa.suse.de/tests/13993161  (no more error about curl missing)

Install curl fo CC selinux tests
