os-autoinst/os-autoinst-distri-opensuse

schedule/kernel/bpftools.yaml
schedule/kernel/io_uring.yaml
schedule/kernel/kdump.yaml

Fix poo#158796: There was missing bootloader module, which is needed to properly boot on spvm backend.
- Related ticket: https://progress.opensuse.org/issues/158796
https://openqa.suse.de/tests/overview?build=czerw%2Fos-autoinst-distri-opensuse%2319069&distri=sle&version=15-SP6
kdump: https://openqa.suse.de/tests/13994446
Failures in above VR are not related, we just want to validate system boot.

Fix booting of bpftool, io_uring amd kdump on spvm backend

---

tests/containers/suma_containers.pm

Right now the VRs are failing, because the helm is not installed, so this PR handles it
- Related ticket: https://progress.opensuse.org/issues/155662
- Verification run: [15-SP5-docker](https://openqa.suse.de/tests/13996076), [15-SP5-podman](https://openqa.suse.de/tests/13996077)

Install helm for helm chart test

---

schedule/kernel/prepare_baremetal.yaml

Fix poo#156847: We need to schedule partitioning_firstdisk only if NUMDISKS is higher than 1. We have machines with 2 and 3 disks only.
- Related ticket: https://progress.opensuse.org/issues/156847
- Verification run: https://openqa.suse.de/tests/overview?version=15-SP6&distri=sle&build=czerw%2Fos-autoinst-distri-opensuse%2319071

kernel baremetal: Schedule partitioning_firstdisk if NUMDISKS is > 1

---

lib/susedistribution.pm

`openqa-clone-custom-git-refspec https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/19046 https://openqa.suse.de/tests/13913331`
* default@s390x-kvm: https://openqa.suse.de/tests/13965557
Related progress issue: https://progress.opensuse.org/issues/157537

Properly mask typed hypervisor passwords

---

tests/microos/disk_boot.pm

Add SLiMy BETA images to the selected images that need to wait past the bootloader.
- Related ticket: https://progress.opensuse.org/issues/157141
- Related failure: https://openqa.suse.de/tests/14004347#step/disk_boot/4
- Verification runs: [aarch64](https://openqa.suse.de/tests/14004371) | [x86_64](https://openqa.suse.de/tests/14004399)

Wait for bootloader on SLiMy BETA images

---

tests/installation/isosize.pm

This test runs before anything is set up, so avoid doing any extra stuff such as post_fail_hook.
Failure: https://openqa.opensuse.org/tests/4077118 (not sure yet why it breaks this badly)
VR: https://openqa.opensuse.org/tests/4078760#live

installation/isosize.pm: Use basetest as base class

---

tests/console/check_os_release.pm

Noticed on #19023 that for TW the module would fail, due to the build rewritten by the openqa-clone-custom-gitref-spec script, exit early in such case
[![VR](https://openqa.opensuse.org/tests/latest/badge?arch=x86_64&distri=opensuse&flavor=JeOS-for-kvm-and-xen&machine=64bit_virtio-2G&test=jeos-extra%40foursixnine%2Fos-autoinst-distri-opensuse%23dontlookatme&version=Tumbleweed)](https://openqa.opensuse.org/tests/latest?arch=x86_64&distri=opensuse&flavor=JeOS-for-kvm-and-xen&machine=64bit_virtio-2G&test=jeos-extra%40foursixnine%2Fos-autoinst-distri-opensuse%23dontlookatme&version=Tumbleweed)

Skip version check for PRs in Tumbleweed

---

data/yam/autoyast/mini_remote.xml

- Description: Add `openssh` package to autoyast profile in spvm
- Related ticket: [poo#158269](https://progress.opensuse.org/issues/158269)
- Verification run: [overview](https://openqa.suse.de/tests/overview?build=issues-158269)
+ `tests/autoyast/installation.pm` **passed**
+ the next error on `tests/autoyast/console.pm` is due to the [bsc#1221005](https://bugzilla.suse.com/show_bug.cgi?id=1221005)

Add 'openssh' package to autoyast profile in spvm

---

lib/sles4sap.pm
tests/sles4sap/hana_cluster.pm
tests/sles4sap/monitoring_services.pm

Fix monitoring_services `curl` sporadically `Failed to connect to localhost port 9668`: hanadb_exporter
-  add `retry` (line 103 ~ line 120 in file `monitoring_services.pm`)
Fix `script_run "su - $sapadm -c 'hdbnsutil -sr_state' ` sporadically timed out
- increase timeout value (in `lib/sles4sap.pm`)
Fix `check_replication_state` failed
- wait more time (in `hana_cluster.pm`)
NOTE: other changes are fixing tidy issue introduced. 
TEAM-9221 - [15-SP6][ppc64le][sporadic] "SAPHanaSR_ScaleUp_PerfOpt_WMP" failed on "monitoring_services": curl: (7) Failed to connect to localhost port 9668 after 7 ms: Couldn't connect to server
- Related ticket: https://jira.suse.com/browse/TEAM-9221
- Needles: NA …

Fix monitoring_services curl failed on connect

---

data/virtualization/autoyast/guest_15.xml.ep

It doesn't work during MU kernel-default test, recover it.
- Related ticket: https://progress.opensuse.org/issues/158829
- Needles: N/A
- Verification run: http://openqa.qam.suse.cz/tests/71193#step/patch_guests/31

Recover the function to write guest ip

---

tests/microos/rollback.pm

failure of reboot in the beginning of rollback module : https://openqa.suse.de/tests/overview?result=failed&arch=&flavor=&machine=&test=&modules=&module_re=&group_glob=&not_group_glob=&comment=&distri=sle-micro&version=6.0&build=9.1&groupid=510#
- Related ticket: https://progress.opensuse.org/issues/157096
- Verification runs: https://openqa.suse.de/tests/overview?distri=sle-micro&build=sofiasyria%2Fos-autoinst-distri-opensuse%23slem_vnc&version=6.0

Replace reboot process for slem rollback

---

tests/hpc/rasdaemon.pm

Fix poo#158161: We should do only installation test on ppc64le architecture on Tumbleweed. rasdaemon is not supported on ppc64le and is included in Tumbleweed for people who are interested in it only.
- Related ticket: https://progress.opensuse.org/issues/158161
SLE: https://openqa.suse.de/tests/overview?distri=sle&version=15-SP6&build=czerw%2Fos-autoinst-distri-opensuse%2319095
TW: https://openqa.opensuse.org/tests/overview?distri=opensuse&build=czerw%2Fos-autoinst-distri-opensuse%2319095&version=Tumbleweed
ppc64le TW: https://openqa.opensuse.org/tests/4080610#step/HPC_rasdaemon_tests/1

rasdaemon: Skip functional tests on ppc64le and Tumbleweed

---

lib/main_micro_alp.pm

perl_bootloader test module causes a failure for sdboot based tests: https://openqa.opensuse.org/tests/4080567#step/perl_bootloader/112
Related ticket: https://progress.opensuse.org/issues/158919

Avoid loading perl_bootloader test module for sdboot based tests

---

schedule/qam/12-SP5/mau-filesystem.yaml
tests/console/lvm.pm

https://progress.opensuse.org/issues/40163
[VR](https://openqa.suse.de/tests/overview?arch=&flavor=&machine=&test=&modules=btrfs_qgroups&module_re=&group_glob=&not_group_glob=&comment=&distri=sle&groupid=477#)

Add mau-filesystem on s390x

---

lib/publiccloud/ssh_interactive.pm

- Related ticket: https://progress.opensuse.org/issues/155887
* http://quasar.suse.cz/tests/3220
* http://quasar.suse.cz/tests/3219
* http://quasar.suse.cz/tests/3218
* http://quasar.suse.cz/tests/3221

Don't use deprecated syntax in script_call in PC

---

data/yam/autoyast/support_images/create_hdd_maintenance.xml.ep

Currently, th ecreate_hdd_gnome tests run with addon_others and the mu repos are not visible after installation. This can be fixed by using addon_products
- Related ticket: https://progress.opensuse.org/issues/155827
- Verification run: https://openqa.suse.de/tests/14016028#step/repos/9

Replace addon_others with addon_products in create_hdd_maintenance.xml.ep

---

schedule/sles4sap/ensa/ensa_supportserver.yaml

This adds the omitted VIRTIO_CONSOLE setting.
- Related ticket: https://jira.suse.com/browse/TEAM-8977
- Verification run: http://openqaworker15.qa.suse.cz/tests/280691#

Make ensa_supportserver run on the root-console

---

schedule/migration/migration_autoyast.yaml
schedule/yast/maintenance/autoyast_create_hdd_maintenance.yaml

##
* [**154948**](https://progress.opensuse.org/issues/154948)
- Related MR:
* [**openqa-job-group_96**](https://gitlab.suse.de/qe-yam/openqa-job-groups/-/merge_requests/96)  
- Needles: 
* N/A
* https://openqa.suse.de/tests/14037539

Provide migration from SLES 12 SP5 to SLES 15 SP4 in aggregated updates

---

tests/console/suseconnect_scc.pm

Increase timeout for registration command.
The command fails with a timeout of 27.  Use the same timeout we use above.
- Related ticket: https://progress.opensuse.org/issues/159036

Increase timeout for registration command

---

tests/xfstests/install.pm

'zypper refresh' is not a necessary step to install xfstests. So remove it for stability.
- Related ticket: https://progress.opensuse.org/issues/159018
- Needles: N/A
http://10.67.133.133/tests/580 (SLES)
https://openqa.suse.de/tests/14038560 (SLE Micro)

Remove 'zypper refresh' in xfstests installation

---

data/journal_check/bug_refs.json

https://bugzilla.suse.com/show_bug.cgi?id=1221504
Failes e.g. in https://openqa.suse.de/tests/13924015

Add bsc#1221504 (bluetooth errors in syslog) to known bugs

---

tests/sles4sap/publiccloud/cluster_add_repos.pm

The rpms that are included in these modules are not currently tested and including them breaks the scenarios because they are not currently synced to IBSM
- Related ticket: TEAM-9246
- Verification run: http://openqaworker15.qa.suse.cz/tests/280754#step/cluster_add_repos/14

Filter Desktop-Applications out of the repos to be added to ibsm

---

tests/transactional/transactional_update.pm

Add comment with link to poo#159039 about the very small chance of `t-u cleanup up` failing is an update suddenly appears.
- Related ticket: https://progress.opensuse.org/issues/159036

transactional: Add comment with link to poo#159039

---

data/sles4sap/qe_sap_deployment/qesap_azure.yaml
data/sles4sap/qe_sap_deployment/qesap_azure_fencing_msi.yaml
data/sles4sap/qe_sap_deployment/qesap_azure_fencing_spn.yaml
data/sles4sap/qe_sap_deployment/qesap_azure_roles.yaml
data/sles4sap/qe_sap_deployment/qesap_azure_sapconf.yaml
data/sles4sap/qe_sap_deployment/qesap_azure_sapconf_no_reg.yaml
data/sles4sap/qe_sap_deployment/qesap_azure_uri.yaml
lib/sles4sap_publiccloud.pm

Remove any reference to qe-sap-deployment Ansible playbook post-sap-hana-cluster.yaml as it has been merged to sap-hana-cluster.yaml in a latest qesap version.
Related to https://github.com/SUSE/qe-sap-deployment/pull/216
- Related ticket: https://jira.suse.com/browse/TEAM-9093
-> http://openqaworker15.qa.suse.cz/tests/280768
- -> http://openqaworker15.qa.suse.cz/tests/280769
- http://openqaworker15.qa.suse.cz/tests/280765
- http://openqaworker15.qa.suse.cz/tests/280766

Remove references to post-sap-hana-cluster.yaml

---

tests/publiccloud/check_registercloudguest.pm

after showing current master to the devs they notice that we executing commands not in expected order ( certs needs to be updated **before** registration will happen . This PR fixing this problem 
VR: https://openqa.suse.de/tests/14034455
https://openqa.suse.de/tests/14034456

Fix order of commands

---

data/yam/autoyast/bug-887126_autoinst.xml

Due to the fix https://build.suse.de/request/show/326197 of bsc#1221841, we should remove the at-spi* packages from corresponding profile.
- Needles: N/A
- Verification run: http://openqa.suse.de/tests/14048502#

Remove at-spi* packages from profile

---

lib/kdump_utils.pm

aarch64  baremetal  servers are slow and they need even higher timeout.
- Related ticket: https://progress.opensuse.org/issues/156781
- Verification run: https://openqa.suse.de/tests/14048641#step/kdump/52 (needle matched correctly)

kdump: Increase timeout for aarch64 and hyperv

---

lib/main_containers.pm

- Related ticket: https://progress.opensuse.org/issues/138428
- [Podman test in SLE 15-SP6 JeOS with FIPS](https://openqa.suse.de/tests/14004999)
- [Docker test in SLE 15-SP6 JeOS with FIPS](https://openqa.suse.de/tests/14004998)
- [Podman test in SL Micro 6.0 with FIPS](https://openqa.suse.de/tests/14004997)
- [Docker test in SL Micro 6.0 with FIPS](https://openqa.suse.de/tests/14004996)
- [Container host test in Leap 15.6 JeOS with FIPS](https://openqa.opensuse.org/tests/4078458)
- [Container host test in Tumbleweed JeOS with FIPS](https://openqa.opensuse.org/tests/4078459)
- [Container host test in MicroOS with FIPS](https://openqa.opensuse.org/tests/4078461)
- [Docker test in Tumbleweed with FIPS](https://openqa.opensuse.org/tests/4078463)
- [Podman test in …

New test suite which enables FIPS and runs container hosts tests

---

schedule/filesystem/btrfs-progs.yaml

Recently btrfs-progs has frequently failed in boot_to_desktop.  Switch from boot_to_desktop to microos/disk_boot.pm should workaround this issue. But update boot_hdd_image subroutine  is not a graceful way to do it. Thus we add a yaml scheduler to deal this.
- Related ticket: https://progress.opensuse.org/issues/158988
- Needles: N/A
- Verification run: http://10.67.133.133/tests/592

filesystem: Add btrfs-progs tests to yaml scheduler

---

lib/containers/common.pm
tests/containers/container_engine.pm
tests/containers/image.pm

This PR:
- Moves `test_rpm_db_backend` from lib to test module calling it
- Moves `test_search_registry` from lib to test module calling it
Related ticket: https://progress.opensuse.org/issues/155470
- opensuse-Tumbleweed-DVD-x86_64-Build20240416-containers_host_docker@64bit -> https://openqa.opensuse.org/t4089621
- opensuse-Tumbleweed-DVD-x86_64-Build20240416-containers_host_podman@64bit -> https://openqa.opensuse.org/t4089622

Minor containers lib refactoring

---

lib/sles4sap_publiccloud.pm
tests/sles4sap/publiccloud/hana_sr_takeover.pm

This pr adds a quiet optional argument for `is_hana_ready`, changes the `record_info` output to something more meaningful, and runs `crm mon` in the end of hana_sr_takeover`, to allow the reviewer to troubleshoot in case of failure.
- Related ticket: https://jira.suse.com/browse/TEAM-9239
- Verification run: https://openqa.suse.de/tests/14057479
https://openqa.suse.de/tests/14040271
new, revised output: https://openqa.suse.de/tests/14040271#step/Crash_site_b-primary/670
crm output at the end of the module: https://openqa.suse.de/tests/14040271#step/Crash_site_b-primary/684

Add cluster checks in hana_sr_takeover

---

data/autoyast_sle15/create_hdd/create_hdd_textmode_aarch64.xml
data/autoyast_sle15/create_hdd/create_hdd_textmode_s390x.xml

- Related ticket: https://progress.opensuse.org/issues/159093
- VR: https://openqa.suse.de/tests/overview?build=os-autoinst%2Fos-autoinst-distri-opensuse%2319130
Remove desktop addon and package from create_hdd_textmode autoyast profiles.

Remove desktop addon from create_hdd_textmode

---

schedule/kernel/kdump.yaml

Fix poo#159201: There was missing installation/bootloader_zkvm module on
s390x architecture. Existing boot condition was extended.
- Related ticket: https://progress.opensuse.org/issues/159201
- Verification run: https://openqa.suse.de/tests/14057491

kdump: Fix yaml schedule on s390x

---

data/yam/autoyast/bug-872532_ix64ph1069.xml

- Related ticket: [poo#159096](https://progress.opensuse.org/issues/159096)
- Verification run: [autoyast_bug-872532_ix64ph1069](https://openqa.suse.de/tests/14059883#live)

Fix addon syntax in bug-872532_ix64ph1069.xml

---

schedule/migration/migration_zdup_updatestack.yaml

Use zdup to do update stack job migration testing
- Related ticket: https://progress.opensuse.org/issues/158940
- Verification run: https://openqa.suse.de/tests/14037332
- Related MR: https://gitlab.suse.de/qe-yam/openqa-job-groups/-/merge_requests/154

Use zdup to do update stack job migration testing

---

lib/containers/container_images.pm
lib/containers/docker.pm
lib/containers/engine.pm
lib/containers/k8s.pm
lib/containers/utils.pm
tests/containers/validate_btrfs.pm

This PR removes unused functions: exec_on_container, commit, get_images_by_repo_name, remove_image, install_oc, check_runtime_version.
- Related ticket: https://progress.opensuse.org/issues/158982
- opensuse-Tumbleweed-DVD-x86_64-Build20240417-containers_host_podman@64bit -> https://openqa.opensuse.org/t4091870
- opensuse-Tumbleweed-DVD-x86_64-Build20240417-containers_host_docker@64bit -> https://openqa.opensuse.org/t4091871

Cleanup poo158982

---

tests/x11/chrome.pm

Update test and add needles due to the new  'ad privacy feature'.
- Related ticket: https://progress.opensuse.org/issues/159159
- Verification run: https://openqa.opensuse.org/tests/4092008

Update chrome test due to new UI

---

lib/opensusebasetest.pm
lib/registration.pm
tests/migration/record_disk_info.pm

Need to wait more for qemu ppc64le "wait boot", "wait screen", etc
Due to ppc64le worker perfomance issues fix these `high frequency` issues as following:
Wait more for qemu ppc64le in test module patch_sle
Use select_serial_terminal instead of select_console in test module record_disk_info
Set wait_screen_change similarity=35 instead of default 50
TEAM-8987 - [15SP6][HA Migration] migration_offline_scc_sle12sp5_ha_alpha_node02 failed on patch_sle: needle 'scc-addon-license-ha' mismatched
- Related ticket: https://jira.suse.com/browse/TEAM-8987
- Needles: NA
https://openqa.suse.de/tests/14038553 (passed on migration)
https://openqa.suse.de/tests/14038549 (passed on migration)
https://openqa.suse.de/tests/14038542 (passed on migration) …

Need to wait more for qemu ppc64le wait boot

---

schedule/migration/migration_autoyast.yaml

##
* https://progress.opensuse.org/issues/159219
- Needles: 
* N/A
* [**15sp3_and_15sp4**](https://openqa.suse.de/tests/overview?build=hjluo%2F%2Fos-autoinst-distri-opensuse%23reset_console_12sp5&distri=sle&version=12-SP5)
##

Reset console for sles15sp3 MU migration

---

lib/containers/common.pm
lib/containers/container_images.pm
lib/containers/utils.pm
tests/containers/image.pm
tests/containers/third_party_images.pm

This PR:
- Moves scc_(apply|restore)_docker_image_credentials from lib to calling test module
- Removes unused exports in containers::common
- Moves 3rd_party_image methods from lib to calling test module
- Removes unused can_build_sle_base
Related ticket: https://progress.opensuse.org/issues/155470
- opensuse-Tumbleweed-DVD-x86_64-Build20240417-containers_host_docker@64bit -> https://openqa.opensuse.org/t4094857
- opensuse-Tumbleweed-DVD-x86_64-Build20240417-containers_host_podman@64bit -> https://openqa.opensuse.org/t4094858

More refactoring and cleanup

---

tests/sles4sap/ensa/netweaver_swpm_installation.pm

ENSA2 wasn't originally tested on root-console/12sp5 where the installation takes more time than expected
- Related ticket: https://jira.suse.com/browse/TEAM-9259
[12SP5](http://openqaworker15.qa.suse.cz/tests/overview?build=%3A33441%3Aqemu&distri=sle&version=12-SP5) [12SP5](http://openqaworker15.qa.suse.cz/tests/overview?build=%3A33433%3Awireshark&distri=sle&version=12-SP5)
[15SP2 15SP4 15SP5](http://openqaworker15.qa.suse.cz/tests/overview?build=ensa2_more_time)
[15SP3](http://openqaworker15.qa.suse.cz/tests/overview?build=%3A32617%3Ashim&distri=sle&version=15-SP3)

Fix ENSA2 installation step time out on root-console/SLE12

---

data/virt_autotest/host_unattended_installation_files/combustion/script
data/virt_autotest/host_unattended_installation_files/ignition/config.ign
lib/bootloader_setup.pm
tests/installation/usb_install.pm

- This PR mainly does below. Now with these, in OSD, kermit can finish SL Micro 6 bare metal installation successfully.
- usb selection on vh082: exclude usb with key word `Virtual_NetFile`
- installed os persistent boot setting for kermit: kermit can't set the newly installed `sl-secureboot` as first boot, so do it in combustion
- add code to pass bootparam to firstboot
- recover default selinux config by removing customized config file
- workaround https://bugzilla.suse.com/show_bug.cgi?id=1222411#c9
The 2 OSD machines selected, kermit and scooter , have been fully enabled and updated in openqa worker settings to do SL Micro 6 test. See https://gitlab.suse.de/openqa/salt-pillars-openqa/-/merge_requests/775. But for general sles15sp6 test, please wait for Julie to finish uefi sles …

Workaround for bsc#1222411

---

data/containers/autoyast_containers.xml.ep

zypper-docker has become deprecated from 15-SP6 onwards. Install zypper-docker only on older SLES versions, when matching.
- Related ticket: https://progress.opensuse.org/issues/159387
- Verification run: [15-SP6 x86_64](https://openqa.suse.de/tests/14113781) | [15-SP6 aarch64](https://openqa.suse.de/tests/14113782) | [15-SP5 x86_64](https://openqa.suse.de/tests/14113783) | [15-SP5 aarch64](https://openqa.suse.de/tests/14113784) | [12-SP4 x86_64](https://openqa.suse.de/tests/14113785) | [15-SP3 s390x](https://openqa.suse.de/tests/14113786)

Install zypper-docker only up to 15-SP5

---

tests/containers/secret.pm

We have a silent error on `podman secret` as you can see [here](https://openqa.opensuse.org/tests/4096739/logfile?filename=serial_terminal.txt)
`Error: crun: executable file 'cat /run/secrets/secret1 & printenv TOP_SECRET2' not found in $PATH: No such file or directory: OCI runtime attempted to invoke a command that was not found
`
- Verification run: https://openqa.opensuse.org/tests/4098603/logfile?filename=serial_terminal.txt

containers: Fix silent error in podman secret

---

lib/publiccloud/provider.pm

openstack cleanup is failing due to `ssh_public_key` variable. This leads to hanging instances that are later on blocking resources for upcoming test runs.
- ticket: https://progress.opensuse.org/issues/158044
- Verification run: http://kepler.suse.cz/tests/23228#

Skip ssh_public_key variable usage in openstack

---

data/autoyast_qam/15_installtest.xml.ep

Server Applications Module is not available for SLED at all
- Related ticket: https://suse.slack.com/archives/C02D16TCP99/p1711011691382679
- Verification run: https://openqa.suse.de/tests/14114522

Remove server-applications module from SLED

---

lib/sles4sap_publiccloud.pm
tests/sles4sap/publiccloud/hana_sr_takeover.pm
tests/sles4sap/publiccloud/hana_sr_test_secondary.pm

Verify that the cluster is in S_IDLE and get the crm status at the end of each Takeover or Secondary HanaSR test step
- Related ticket: https://jira.suse.com/browse/TEAM-9253 https://jira.suse.com/browse/TEAM-9239
http://openqaworker15.qa.suse.cz/tests/281281#step/Stop_site_a-primary/704  --> https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/19122/files#diff-6b1b9620bf9f9d9ca1005e2e30986615be757ce405dc23e791815d048b5702ecR80  
http://openqaworker15.qa.suse.cz/tests/281281#step/Stop_site_a-primary/725  --> `crm resource cleanup`
http://openqaworker15.qa.suse.cz/tests/281281#step/Stop_site_a-primary/748  --> `crm resource status msl_SAPHana_HDB_HA000`
:red_circle:  fails at Ansible reboot timeout, before to reach the PR code
Fails during Ansible (and then fails for timeout as …

Verify cluster health at the end

---

tests/console/console_reboot.pm

https://github.com/os-autoinst/xterm_console is responsible to set the console fonts correctly. However as we are using a ssh connection in s390x, the set up is more complex.
As of now and as this issue is not present anywhere else than s390x, we can skip this check for now only in s390x tests.
Failing test: https://openqa.suse.de/tests/14106323#step/console_reboot/34

Skip console font check in s390x

---

tests/network/autofs_client.pm
tests/network/autofs_server.pm

https://bugzilla.suse.com/show_bug.cgi?id=1222947
[sle15sp6](https://openqa.suse.de/tests/14112155#dependencies)
[sle15sp5](https://openqa.suse.de/tests/14112202#dependencies)
[tw](https://openqa.opensuse.org/tests/4098096#dependencies)

Ship libnfsmap1 in place of nfsidmap on sle15sp6

---

data/virtualization/autoyast/guest_15.xml.ep
tests/virtualization/universal/patch_guests.pm

- Related ticket: https://progress.opensuse.org/issues/153916 and https://progress.opensuse.org/issues/158829
- Needles: N/A
[15-SP5-KVM](http://openqa.qam.suse.cz/tests/71808#dependencies)
[15-SP5-XEN](http://openqa.qam.suse.cz/tests/71810#dependencies)
[15-SP6-KVM](http://openqa.qam.suse.cz/tests/71806#dependencies)
[15-SP6-XEN](http://openqa.qam.suse.cz/tests/71804#dependencies)

Remove after.local usage form MU virt test

---

tests/containers/podman_quadlet.pm
tests/containers/secret.pm

This PR:
- Adds missing cleanup in podman_quadlet module.
- Removes container in podman secret module.
Related ticket: https://progress.opensuse.org/issues/159405
Failing test: https://openqa.opensuse.org/tests/4098172#step/secret_podman/154
Verification runs: 
- opensuse-Tumbleweed-JeOS-for-AArch64-aarch64-Build20240418-jeos-container_host@aarch64-HD20G -> https://openqa.opensuse.org/t4099472

Add missing cleanup to containers modules

---

lib/db_utils.pm
tests/containers/bci_version_check.pm

Collect container size stats to our container database.
- Related ticket: https://progress.opensuse.org/issues/159474
- Verification run: https://duck-norris.qe.suse.de/tests/14624#step/bci_version_check/34 (fails because I didn't provide the correct DB password)

Collect BCI container stats

---

lib/publiccloud/instance.pm

Hardened images have strict permissions on log files and we're experiencing errors when trying to upload them:
`scp: /var/log/cloud-init.log: Permission denied
`
- Related ticket: https://progress.opensuse.org/issues/158871
- Failing test: https://openqa.suse.de/tests/14017587/logfile?filename=serial_terminal.txt
- Verification run: https://openqa.suse.de/tests/14124382/logfile?filename=serial_terminal.txt (failing because of another issue).  Error must not be present in serial log.

pc: Change permissions of log files so we can copy them

---

lib/publiccloud/instance.pm

Instead of allowing others to read the log files and therefore potentially locking out the group, we should allow all users to read the log files of interest.
- Related PR: https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/19175
- Verification run: https://openqa.suse.de/tests/14128382

Allow all users to read log files of interest

---

tests/sles4sap/hana_install.pm

We update newer HANA installation version, there is change for hdblcm, so adjust the test code for it.
https://openqa.suse.de/tests/14112232   (For SPS07rev77)
https://openqa.suse.de/tests/14112233   (For SPS05rev59.12)
https://openqa.suse.de/tests/14122466# (For SPS07rev77 multipath machines on ppc64le)
https://openqa.suse.de/tests/14122035# (For SPS07rev77 multipath machines on  x86)
Related: https://jira.suse.com/browse/TEAM-9220

Adjust the hdblcm parameter

---

tests/qam-updinstall/update_install.pm

%package pubcloud
Summary:        RMT pubcloud extensions
Group:          Productivity/Networking/Web/Proxy
Requires:       rmt-server = %version
Provides:       rmt-server-configuration
Conflicts:      rmt-server-configuration
- Related ticket: https://progress.opensuse.org/issues/159528
- Verification run: https://openqa.suse.de/tests/14130618

Add rmt-server-pubcloud conflict

---

tests/console/scc_cleanup_reregister.pm

Need deregister dropped module (ltss) for maintenance migration from 15SP2 to 15SP3.
- Related ticket: https://progress.opensuse.org/issues/159219
- Related MR: https://gitlab.suse.de/qe-yam/openqa-job-groups/-/merge_requests/162
- Needles: N/A
https://openqa.suse.de/tests/14141248#  Installation
https://openqa.suse.de/tests/14141249#  Migration from 15SP2 to 15SP3

Deregister dropped module for maintenance migration

---

lib/services/ntpd.pm
schedule/security/fips_crypt_tool.yaml
tests/security/ntpd.pm

Extend ntpd library to allow service stop/disable and uninstall and schedule a new ntpd test in FIPS mode.
- Related ticket: https://progress.opensuse.org/issues/159285
- https://openqa.suse.de/tests/14131988
- https://openqa.suse.de/tests/14131998
- https://openqa.suse.de/tests/14131918
- https://openqa.suse.de/tests/14131922

Schedule ntpd tests in FIPS mode

---

tests/xfstests/install.pm

fsverity-utils is needed by xfstests verity group. But we only install it in SLES, because SLE Micro with a readonly FS and fsverity-utils just influnce a few tests.
- Related ticket: https://progress.opensuse.org/issues/159483
- Needles: N/A
http://10.67.133.133/tests/593 (install in SLES)
http://10.67.133.133/tests/594 (run generic/572 in btrfs)
http://10.67.133.133/tests/600 (run generic/572 in ext4)
http://10.67.133.133/tests/597 (install in Micro, no influence)
https://openqa.opensuse.org/tests/4109758 (install in Tumbleweed)

xfstests: install fsverity-utils in SLES

---

tests/containers/bci_version_check.pm

Use python instead of jq
- Failing test: https://openqa.suse.de/tests/14149034
- Verification run: https://openqa.suse.de/t14149768

containers: Use python instead of jq

---

tests/containers/bci_version_check.pm

This reverts commit fb15959a3f84fb310a2a9c527f02ff77793d35c6.
https://suse.slack.com/archives/C02CGKBCGT1/p1714119913196329?thread_ts=1714061846.557459&cid=C02CGKBCGT1

Revert "containers: Use python instead of jq"

---

schedule/migration/offline_regression_upgrade@pvm.yaml
schedule/migration/ppc64le_regression_test_offline_textmode.yaml

- Description: Remove x11 test modules for regression ppc64le
+ _ppc64le_regression_test_offline_textmode.yaml should not include desktop x11 test modules_
- Related ticket: [poo#158191](https://progress.opensuse.org/issues/158191)
- Verification run: [overview](https://openqa.suse.de/tests/overview?build=issues-158191)
- Related [PR#19173](https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/19173) from @lemon-suse 
+ also here X11 tests are removed for file `schedule/migration/ppc64le_regression_test_offline_textmode.yaml`
+ some merge conflict could happen

Remove x11 test modules for regression ppc64le

---

lib/main_common.pm

midori got dropped from Leap 15.6
- Related ticket: https://progress.opensuse.org/issues/158571

main_common: do not test midori on Leap 15.6

---

lib/sles4sap.pm

Set timeout => 200 to fix the script timeout.
Fix sles4sap ppc64le SAPHanaSR_ScaleUp_PerfOpt_WMP_node01 sporadically failed on hana_cluster: script timeout: su - ha1adm -c 'python exe/python_support/systemReplicationStatus.py'
TEAM-9263 - [15-SP6][sles4sap][ppc64le] SAPHanaSR_ScaleUp_PerfOpt_WMP_node01 sporadically failed on hana_cluster: script timeout: su - ha1adm -c 'python exe/python_support/systemReplicationStatus.py'
- Related ticket: https://jira.suse.com/browse/TEAM-9263
- Needles: NA
http://openqa.suse.de/tests/14161967 (passed)

Fix ppc64le sles4sap SAPHanaSR ha1adm timedout

---

tests/xfstests/install.pm
variables.md

There is no fsverity-utils in many repositories, so add a parameter 'XFSTESTS_PACKAGES' to optionally install package.
- Related ticket: https://progress.opensuse.org/issues/159711
- Needles: N/A
http://10.67.133.133/tests/603#step/install/43 (only install xfstests fio)
http://10.67.133.133/tests/604#step/install/43 (additional fsverity-utils libcap-progs)
https://openqa.suse.de/tests/14165278 (verified on QAM group)

Fix xfstests installation issue

---

tests/containers/skopeo.pm

Remove check for specific skopeo version as it's failing on 15-SP2 with older version: http://kepler.suse.cz/tests/23239#step/docker_skopeo/18

containers: Remove check for skopeo version

---

schedule/qam/15/qam-gfxdrivers.yaml
tests/kernel/usb_drive.pm
tests/kernel/usb_nic.pm

We have some USB devices physically plugged into a baremetal machine. This adds some basic smoke tests for both mass storage and Ethernet connected via USB. 
- Related ticket: https://progress.opensuse.org/issues/138122
- Needles: -
- Verification run: https://openqa.suse.de/tests/14004960#next_previous

Add some basic usb tests for ethernet and mass storage

---

lib/main_containers.pm
tests/containers/podman_integration.pm
tests/containers/skopeo_integration.pm

Add skopeo upstream tests
- Related ticket: https://progress.opensuse.org/issues/159741
- opensuse-Tumbleweed-DVD-x86_64-Build20240428-containers_host_podman_testsuite@64bit -> https://openqa.opensuse.org/t4116334
- sle-15-SP4-Server-DVD-Updates-x86_64-Build20240428-1-podman_testsuite@64bit -> https://openqa.suse.de/t14167128
- sle-15-SP5-Server-DVD-Updates-aarch64-Build20240428-1-podman_testsuite@aarch64-virtio -> https://openqa.suse.de/t14167125
- sle-15-SP6-Online-x86_64-Build82.1-podman_testsuite@64bit -> https://openqa.suse.de/t14167124

containers: Add skopeo upstream tests

---

schedule/virt_autotest/slem_open_vm_tools.yaml

Created a yaml file (schedule/virt_autotest/slem_open_vm_tools.yaml) to run open-vm-tools tests based on guest installation with the vmdk image.
- Related ticket: https://progress.opensuse.org/issues/153754

Support open-vm-tools tests on sle-micro 6.0 vmdk image

---

schedule/migration/migration_autoyast.yaml
tests/console/scc_cleanup_reregister.pm
tests/yam/migration/reboot_to_boot_screen.pm
tests/yam/migration/setup_registration.pm
tests/yam/migration/setup_upgrade.pm

- Description: Enhance migration code in maintenance. How? Making as simple as possible to read for the existing migrations:
- Using simple commands instead of library functions which have conditional logic.
- Addons are set at the level of medium, so the most clear way to deal with this setting is with another setting to exclude certain addons which should not be registered before migration.
- There is no need to unregister addons in these kind of scenario, we will not register them in the first place.
- Actions to setup upgrade and reboot for now do not take into account other architectures or situations on purpose.
- Job group changes: [mr#171](https://gitlab.suse.de/qe-yam/openqa-job-groups/-/merge_requests/171)
- Verification run: [current migrations in …

Enhance migration code in maintenance

---

lib/main_containers.pm

Hotfix for skopeo upstream test failing on aarch64.
Also, skopeo is not available in 12-SP5.
- Related ticket: https://progress.opensuse.org/issues/159774

containers: Limit skopeo tests

---

schedule/kernel/gfx-usb-drivers.yaml

Depends on https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/18460
Schedule to validate i915 + usb in product testing. It is based  on existing qam schedule and little bit stripped down.
- Related ticket: https://progress.opensuse.org/issues/138122
- Related job group configuration: https://gitlab.suse.de/kernel-qa/kernelqa-openqa-yaml/-/merge_requests/489
- Verification run:  https://openqa.suse.de/tests/14171867#
Test suite settings:
```
testsuite: null
settings:
CASEDIR: https://github.com/czerw/os-autoinst-distri-opensuse#15-sp6-ay
AUTOYAST: autoyast_qam/15_installation.xml.ep
AUTOYAST_PREPARE_PROFILE: '1'
DESKTOP: gnome
MIRROR_HTTP: http://dist.suse.de/install/SLP/SLE-%VERSION%-Full-LATEST/%ARCH%/DVD1/
NOAUTOLOGIN: '0'
SCC_ADDONS: base,sdk,serverapp …
```

kernel: Add yaml schedule for gfx and usb product testing

---

tests/containers/skopeo_integration.pm

Fix missing openssl dependency on TW.
- Related ticket: https://progress.opensuse.org/issues/159741
- Failing test: https://openqa.opensuse.org/tests/4119203
- opensuse-Tumbleweed-DVD-x86_64-Build20240429-containers_host_podman_testsuite@64bit -> https://openqa.opensuse.org/t4119809

containers: Fix missing dependency for skopeo upstream tests

---

lib/main_containers.pm
tests/containers/podman_integration.pm
tests/containers/skopeo_integration.pm

Fix for skopeo upstream tests not running on aarch64.
The default `quay.io/libpod/registry:2` image used by the upstream tests only has amd64 image but it can be bypassed using `SKOPEO_TEST_REGISTRY_FQIN` variable:
https://github.com/containers/skopeo/blob/main/systemtest/helpers.bash#L13
- Related ticket: https://progress.opensuse.org/issues/159774
- sle-15-SP4-Server-DVD-Updates-aarch64-Build20240429-1-podman_testsuite@aarch64-virtio -> https://openqa.suse.de/t14173886
- sle-15-SP5-Server-DVD-Updates-aarch64-Build20240429-1-podman_testsuite@aarch64-virtio -> https://openqa.suse.de/t14173887
- opensuse-Tumbleweed-DVD-aarch64-Build20240429-containers_host_podman_testsuite@aarch64 -> https://openqa.opensuse.org/t4119982

containers: Fix for skopeo upstream tests not running on aarch64

---

schedule/security/slmicro/selinux.yaml

https://progress.opensuse.org/issues/157138
VR: https://openqa.suse.de/tests/14039356
but with this, we need to add `EXCLUDE_MODULES=disk_boot` to s390x jobs..
VRs:
[container_selinux s390x](https://openqa.suse.de/tests/14173934#)
[container_selinux x86_64](https://openqa.suse.de/tests/14173937#)
[selinux s390x](https://openqa.suse.de/tests/14173935#)
[selinux x86_64](https://openqa.suse.de/tests/14173936#)

Fix container-selinux schedule for s390x

---

lib/containers/bats.pm
tests/containers/podman_integration.pm
tests/containers/skopeo_integration.pm

This PR:
- Refactors common code in podman & skopeo upstream tests to `containers::bats`
- Installs `bats` from upstream.
Related ticket: https://progress.opensuse.org/issues/155470
- opensuse-Tumbleweed-DVD-x86_64-Build20240429-containers_host_podman_testsuite@64bit -> https://openqa.opensuse.org/tests/4120284 (failing for other reason).
- sle-15-SP5-Server-DVD-Updates-x86_64-Build20240429-1-podman_testsuite@64bit -> https://openqa.suse.de/t14175639
- sle-15-SP4-Server-DVD-Updates-aarch64-Build20240429-1-podman_testsuite@aarch64-virtio -> https://openqa.suse.de/t14177130
TODO:
- In next PR, drop packagehub dependencies completely.

Refactor bats

---

lib/hpcbase.pm
tests/hpc/spack_master.pm

Fix poo#159831: We should use mpich libraries provided by SLE and not ones provided by spack repositories. sshd restart, which is not needed at all, was removed.
- Related ticket: https://progress.opensuse.org/issues/159831
- Verification run: https://openqa.suse.de/tests/14185459

hpc: Improve spack master setup

---

lib/ipsecbase.pm
lib/utils.pm

If support server start slow then other clients, client's network status will broken for test, so add mutex_wait for each client wait server setup complete. Also restart Network service if Neworkwork connection is still not ready.
- Verification run: https://openqa.opensuse.org/tests/4115375
Code for restart Network service if Neworkwork connection not ready will fix following error:
https://openqa.opensuse.org/tests/4115203#step/ipsec3hosts/49

Fix ipsec3host network related issue

---

data/containers/htpasswd
lib/containers/bats.pm
lib/main_containers.pm
tests/containers/podman_integration.pm
tests/containers/skopeo_integration.pm

We can drop the `apache2-utils` dependency (available only on PackageHub for SLE & SLEM) by providing a bare-bones Python implementation of the `htpasswd` command, which is called as `htpasswd -Bbn USERNAME PASSWORD` in the [podman](https://github.com/containers/podman/blob/main/test/system/helpers.registry.bash#L60) and [skopeo](https://github.com/containers/skopeo/blob/main/systemtest/helpers.bash#L321) upstream tests.
We can also drop the `go` dependency and limit the `criu` (checkpoint-restore) tests to Tumbleweed with the SKIP variables.
This allows us to enable the skopeo upstream tests for SLEM 5.5+.
- Related ticket: https://progress.opensuse.org/issues/159756
- opensuse-Tumbleweed-DVD-x86_64-Build20240501-containers_host_podman_testsuite@64bit -> …

containers: Drop packagehub dependencies for upstream tests

---

lib/containers/common.pm

cgroups v2 is default since v255 and our way to check that it's set no longer works.  Thus we're needlessly adding a deprecated entry to /etc/default/grub and restarting the SUT on Tumbleweed and MicroOS.
The correct check is described [here](https://rootlesscontaine.rs/getting-started/common/cgroup2/#checking-whether-cgroup-v2-is-already-enabled)
https://openqa.opensuse.org/tests/4145118#step/podman_integration/24
-  opensuse-Tumbleweed-DVD-x86_64-Build20240501-containers_host_podman_testsuite@64bit -> https://openqa.opensuse.org/t4157722 (failing due to other issues).

containers: Fix switch_cgroup_version()

---

lib/sles4sap_publiccloud.pm
t/12_sles4sap_publicccloud.t

Pacemaker version >=2.1.7 change 'SAPHanaSR-showAttr --format=script' output format. Adapt this wait method to support both new and old format.
Like doing https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/19049 for https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/18859
- Related ticket: TEAM-9022
- sle-15-SP6-Azure-SAP-BYOS-x86_64-Build0510-azure_sap_byos_hanasr_sapconf@az_Standard_E4s_v3 -> http://openqaworker15.qa.suse.cz/tests/282025

wait_for_cluster also care about Pacemaker version

---

lib/containers/bats.pm
lib/main_containers.pm
tests/containers/podman_integration.pm
tests/containers/runc_integration.pm

Add runc upstream tests
- Related ticket: https://progress.opensuse.org/issues/159801
- opensuse-Tumbleweed-DVD-x86_64-Build20240501-containers_host_podman_testsuite@64bit -> https://openqa.opensuse.org/tests/4158763 (failing in podman module for other reason)
- opensuse-Tumbleweed-DVD-aarch64-Build20240501-containers_host_podman_testsuite@aarch64 -> https://openqa.opensuse.org/tests/4158762 (failing in podman module for other reason)
NOTE: Must use `QEMUCPUS=2`.  Changed in https://github.com/os-autoinst/opensuse-jobgroups/pull/448

containers: Add runc upstream tests

---

lib/publiccloud/azure.pm

In PC `azure` upload_img, add a status of existing image version in cloud.
Never checked before, it allowed wrong images to pass provisioning and impact next depending tests, like in [test 14192564](https://openqa.suse.de/tests/14192564).
- Verification run: https://openqa.suse.de/tests/14196811

PC upload_img add check of image version status

---

lib/containers/bats.pm
tests/containers/podman_integration.pm

Fix for `sudo: bats: command not found` in https://openqa.opensuse.org/tests/4160107/logfile?filename=serial_terminal.txt
- Verification run: https://openqa.opensuse.org/t4160250 (failing for other reasons).

containers: Add /usr/local to sudo secure_path

---

lib/publiccloud/azure.pm
lib/publiccloud/provider.pm
t/13_publiccloud.t

SLE to SL micro renaming: fix pubcloud **Azure** image issue.
Also, in slem_basic test code triggering conditions added to fix code flow.
- Related ticket: https://progress.opensuse.org/issues/159030
- Needles: no change.
- We assume to have in these tests settings for AZURE, at least: 
`PUBLIC_CLOUD_IMAGE_URI=auto` `PUBLIC_CLOUD_USER=""` `WORKER_CLASS=pc_azure_qac`.

SL micro Latest pubcloud fix the Azure image creation issue

---

tests/xfstests/run.pm

we use background_script_run() for tar command, and then use wait() for test log upload. So that might cause a minor issue because there is a race condition between them.
Thus remove wait and use script_run() replace background_script_run()
- Related ticket: https://progress.opensuse.org/issues/159768
- Needles: N/A
http://10.67.133.133/tests/610
https://openqa.suse.de/tests/14173175 (qam group)

xfstests: fix tar command issue

---

tests/console/fs_stress.pm

see https://progress.opensuse.org/issues/154417

Skip the heavy part of fs_stress because of poor performance on RPi

---

lib/Utils/Backends.pm
lib/guest_installation_and_configuration_base.pm
lib/guest_installation_and_configuration_metadata.pm
lib/utils.pm
schedule/virt_autotest/install_guest_on_slem_kvm_host.yaml
tests/microos/selfinstall.pm
tests/virt_autotest/login_console.pm

* **Include** SL Micro 6.0 host installation part before doing guest installation. And also update corresponding settings needed in this test, including yaml ```schedule/virt_autotest/install_guest_on_slem_kvm_host.yaml```.
* **Introduce** new subroutine ```remove_efiboot_entry``` in ```lib/utils.pm``` to be called in ```selfinstall.pm``` to ensure temporarily added usb boot entry will deleted and installed system will boot from hard disk subsequently.
* **Introduce** new subroutine ```empty_usb_disks``` in ```lib/utils.pm``` to be called in ```selfinstall.pm``` to ensure system always boots from installed SL Micro on reboot.
* **Use** ```set_ssh_console_timeout_before_use``` in ```tests/virt_autotest/login_console.pm``` to prevent connection from being torn down for SL Micro as well. …

Complete SL Micro 6.0 test flow to include host installation part

---

data/journal_check/bug_refs.json

- Verification run: https://openqa.opensuse.org/tests/4120141

data/journal_check/bug_refs.json: boo#1193426 happens on 15.6 as well

---

lib/containers/container_images.pm

sle 15-sp6 does not have `zypper-docker` anymore hence all tests that are using it should be skipped.
- ticket: https://progress.opensuse.org/issues/159945
http://kepler.suse.cz/tests/23265#
http://kepler.suse.cz/tests/23266
http://kepler.suse.cz/tests/23264

Skip zypper-docker container build test in sle15sp6

---

tests/x11/chrome.pm

The button "More" is not always showing up, changed the test to reflect this.
- Related ticket: https://progress.opensuse.org/issues/159849
- Verification run: https://openqa.opensuse.org/tests/overview/?build=os-autoinst%2Fos-autoinst-distri-opensuse%2319224

Update chrome test

---

tests/containers/podman_integration.pm

This PR adds a workaround for [bsc#1217828](https://bugzilla.opensuse.org/show_bug.cgi?id=1217828).
- Related ticket: https://progress.opensuse.org/issues/159957
- sle-micro-5.5-Default-Updates-x86_64-Build20240505-1-slem_podman_testsuite@64bit -> https://openqa.suse.de/t14219381 (cloned with `PODMAN_BATS_SKIP="030-run 070-build 140-diff 252-quadlet 410-selinux 505-networking-pasta 700-play" PODMAN_BATS_SKIP_ROOT_LOCAL="012-manifest 055-rm 060-mount 065-cp 120-load 150-login 195-run-namespaces 200-pod 250-systemd 255-auto-update 500-networking 520-checkpoint" PODMAN_BATS_SKIP_ROOT_REMOTE="060-mount 120-load 200-pod 500-networking 520-checkpoint" PODMAN_BATS_SKIP_USER_LOCAL="012-manifest 055-rm 065-cp 080-pause 150-login 195-run-namespaces 250-systemd 255-auto-update …

Fixes for podman upstream tests on SLEM 5.5

---

schedule/migration/ppc64le_regression_test_offline_textmode.yaml
tests/console/system_prepare.pm

We changed the 12SP5 migration test on ppc64le from gnome to textmode (multi-user), after media migration need register desktop application for later regression test.
- Related ticket: https://progress.opensuse.org/issues/157720
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/14211997#

Register desktop appliaction after media migration from 12SP5 on ppc64le

---

data/yam/autoyast/support_images/sles12sp5_install_all_patterns_s390x.xml

We need set correct firewall setting in profile for 12SP5 on s390x to make sure firewall start and port opened.
- Related ticket: https://progress.opensuse.org/issues/158194
- Needles: N/A
-  Installation: https://openqa.suse.de/tests/14212170#
https://openqa.suse.de/tests/14212213#details
Migration:  https://openqa.suse.de/tests/14212239#

Set firewall setting in profile for 12SP5 on s390x

---

schedule/qam/common/mau-extratests-desktop.yaml
tests/texlive/latex2html.pm

- Related ticket: https://progress.opensuse.org/issues/156361
- Needles: 
SLE 15-SP5: [x86_64](https://openqa.suse.de/tests/13887602#step/latex2html/1)
SLE 15-SP4:[x86_64](https://openqa.suse.de/tests/13890711)
SLE 15-SP3: [x86_64](https://openqa.suse.de/tests/13890678)

Add a test to verify the latex2html

---

tests/jeos/firstrun.pm

Testing this properly needs an SSH connection which is complex to set up. Skip it for now.
- Verification run: https://openqa.opensuse.org/tests/4164378

jeos/firstrun.pm: Handle ssh enrollment dialog in TW Staging H

---

tests/xfstests/install.pm
tests/xfstests/partition.pm

Add kernel configuration output for convenience when debugging. All package in setting XFSTESTS_PACKAGES will also check the version and add into output.
- fio and fsverify-utils version added: http://10.67.133.133/tests/619#step/install/53
- kernel configuration added: http://10.67.133.133/tests/616#step/partition/77
- VR in old product version: https://openqa.suse.de/tests/14224126#step/install/53

xfstests: Add kernel configure in output

---

schedule/yast/encryption/cryptlvm+cancel_existing.yaml
schedule/yast/encryption/cryptlvm+cancel_existing_pvm.yaml
schedule/yast/rmt_server_install/rmt_server_install.yaml
schedule/yast/select_modules_and_patterns/select_modules_and_patterns.yaml
schedule/yast/sle/flows/default.yaml
schedule/yast/sle/flows/default_aarch64.yaml
schedule/yast/sle/flows/default_ppc64le.yaml
schedule/yast/sle/flows/default_s390x_kvm.yaml
schedule/yast/sle/flows/default_s390x_kvm_textmode.yaml
schedule/yast/sle/flows/default_s390x_zvm.yaml
schedule/yast/sle/flows/default_svirt-xen-hvm.yaml
schedule/yast/sle/flows/default_svirt-xen-pv.yaml
schedule/yast/sle/flows/default_x86_64.yaml
schedule/yast/sle/flows/default_x86_64_flavor_full.yaml

Adapt automation in Yam scope to not check the beta popup
- Related ticket: https://progress.opensuse.org/issues/159894

Adapt automation in Yam scope to not check the beta popup

---

schedule/migration/autoyast_regression_test_online_pre@pvm.yaml

No need to shutdown system for ppc64le online migration parent jobs, so remove the shutdown test modules for online migration schedule.
- Related ticket: https://progress.opensuse.org/issues/159366
- Needles: n/a
- Verification run: https://openqa.suse.de/tests/overview?version=15-SP6&build=83.1&distri=sle&groupid=251
- Related mr: https://gitlab.suse.de/qe-yam/openqa-job-groups/-/merge_requests/180

Fix ppc64le online migration schedule for misc group

---

tests/transactional/transactional_update.pm

I compared output from https://openqa.opensuse.org/tests/4157911#step/transactional_update/68 with running snapper locally on TW, character `| (0x7c)` changed to `│ (0x2502)`.
Parsing columns is built-in snapper option now, it should prevent this problem.
```
~ snapper list # openQA
8│single││ThuMay218:03:382024│root│12.09MiB│number│SnapshotUpdateof#7│
~ snapper list # locally
57  | post   |    56 | Thu 02 May 2024 01:54:24 PM CEST | root | number  |
```
- Related ticket: https://bugzilla.suse.com/show_bug.cgi?id=1223840
- Verification run: I didn't test this PR in openQA - I don't have local env anymore. Please review accordingly

Fix snapper column parsing

---

lib/main_containers.pm
tests/containers/runc_integration.pm

This PR:
- Extends runc upstream tests to SLE 15-SP4 & 15-SP5
- Minor fix for helpers used in test.
Related ticket: https://progress.opensuse.org/issues/159801
- sle-15-SP5-Server-DVD-Updates-x86_64-Build20240506-1-podman_testsuite@64bit -> https://openqa.suse.de/t14226173
- sle-15-SP4-Server-DVD-Updates-x86_64-Build20240506-1-podman_testsuite@64bit -> https://openqa.suse.de/t14226228
- sle-15-SP4-Server-DVD-Updates-aarch64-Build20240506-1-podman_testsuite@aarch64-virtio -> https://openqa.suse.de/t14227035
- sle-15-SP5-Server-DVD-Updates-aarch64-Build20240506-1-podman_testsuite@aarch64-virtio -> https://openqa.suse.de/t14227036
VR for last commit: https://openqa.suse.de/tests/14227177
Note: Jobs failed but will be fixed with respective SKIP setting in …

Extend runc upstream tests to SLE 15-SP4 & 15-SP5

---

data/virt_autotest/host_unattended_installation_files/combustion/script
lib/bootloader_setup.pm
tests/installation/bootloader_uefi.pm
tests/installation/usb_install.pm

This PR mainly:
- makes usb install for sl micro 6 works on vh081(vh082 shall be the same)
- remove the code lines that sometimes make combustion script fail and then sl micro installation goes to maintenance mode
Additional configuration in /etc/openqa/worker.ini for vh081(vh082) shall be:
```
SPECIFIED_USB_BOOT_ENTRY=Cruzer Blade // please check specifically for vh082 the usb disk being used for holding ISO
DELETE_KEY=backspace
CTRL_X_TO_BOOT=1
```
- Related ticket: https://progress.opensuse.org/issues/159378
- Needles: https://gitlab.suse.de/openqa/os-autoinst-needles-sles/-/merge_requests/1662
- vh081: http://10.67.129.77/tests/602#, PASS
- vh015: http://10.67.129.77/tests/600, PASS
- kermit: http://openqa.suse.de/tests/14165146, PASS

Make SL Micro 6 usb install work on vh081/82

---

schedule/containers/create_hdd_autoyast.yaml

bci_prepare should only be execuded based on job settings, not everywhere.
- Related failure: https://openqa.suse.de/tests/14193422#
- Verification run: https://openqa.suse.de/tests/14235099 and https://openqa.suse.de/tests/14235100
Merge together with https://gitlab.suse.de/qac/qac-openqa-yaml/-/merge_requests/1629

Quickfix: Make bci_prepare conditional

---

tests/containers/podman_integration.pm

Let's add passt when podman 5.0 is made available in SL Micro 6.0.
- Failing test: https://openqa.suse.de/tests/14235668#step/podman_integration/17
- Related ticket: https://progress.opensuse.org/issues/159753
- Verification run: https://openqa.suse.de/tests/14236250 (ignore failed BATS subtests).

containers: SL Micro 6.0 lacks criu, passt, podman-remote & python3 YAML module

---

lib/containers/urls.pm

Refactor the provided image urls. Remove old and unnecessary ones and add recent versions to the list of image URLs.
- Related ticket: https://progress.opensuse.org/issues/135257
- Verification run: [MicroOS](https://duck-norris.qe.suse.de/tests/14657#step/image_podman/38) | [Tumbleweed](https://duck-norris.qe.suse.de/tests/14664#step/image_podman/41) | [15-SP5](https://duck-norris.qe.suse.de/tests/14660#step/image_podman/632) | [15-SP4](https://duck-norris.qe.suse.de/tests/14661#step/image_podman/483) | [15-SP3](https://duck-norris.qe.suse.de/tests/14662#step/image_podman/334) | [12-SP5](https://duck-norris.qe.suse.de/tests/14663#step/image_docker/62) | [5.5](https://duck-norris.qe.suse.de/tests/14659#step/image_podman/38)

Refactoring image urls

---

lib/containers/bats.pm
tests/containers/podman_integration.pm
tests/containers/runc_integration.pm
tests/containers/skopeo_integration.pm

Enable modules for upstream tests in SLE.  Some packages like python3-*, go & glibc-* need these. 
Aggregate tests have been working til now because these modules came enabled.  Better safe than sorry.
- sle-micro-6.0-Base-x86_64-Build10.23-slem_podman@64bit -> https://openqa.suse.de/t14236922

containers: Enable modules for upstream tests in SLE

---

tests/containers/podman_integration.pm
tests/containers/runc_integration.pm
tests/containers/skopeo_integration.pm

Allow use of `(SKOPEO|PODMAN|RUNC)_BATS_SKIP_(ROOT,USER)(?:_(LOCAL|REMOTE))=all` to skip BATS tests. These tests take time and sometimes we need to skip it to make debugging easier.
Verifications run: https://openqa.suse.de/tests/14242149 (failing for other reason).

containers: Allow to skip any BATS subtests

---

tests/console/sshd.pm

- Related ticket: https://progress.opensuse.org/issues/159891
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/14234820#step/sshd/426

Ignore failure bsc#1223178 in sshd test module only for ppc64le

---

tests/ha/qnetd.pm

Fix ha_qdevice_node2 qnetd failure: new crm pkg doesn't need key anymore
TEAM-9291 - [15-SP6][HA] ha_qdevice_node2 failed on qnetd: no candidate needle with tag(s) 'password-prompt' matched
- Related ticket: https://jira.suse.com/browse/TEAM-9291 ([15-SP6][HA] ha_qdevice_node2 failed on qnetd: no candidate needle with tag(s) 'password-prompt' matched)
- Needles: NA
15-SP6: http://openqa.suse.de/tests/14225237 (passed)
Incident:
15-SP5: http://openqa.suse.de/tests/14224031 (passed)
15-SP4: http://openqa.suse.de/tests/14225247 (passed)
15-SP3: http://openqa.suse.de/tests/14225250 (passed)
15-SP2: http://openqa.suse.de/tests/14225255 (passed)
12-SP5: no qdevice cases scheduled in OSD
Aggregate:
15-SP5: http://openqa.suse.de/tests/14225292 (passed)
15-SP4: …

Fix ha_qdevice_node2 qnetd failure: crm need no PW

---

tests/x11/remote_desktop/onetime_vncsession_xvnc_remmina.pm

Remmina got updated to version 1.4.35 in build 83.1
The Remmina news doesn't appear, so we need to update test code to handle this.
Besides, using esc to quit the Remmina Preference is not applicable any more， so use `assert_and_click` to close Remmina Preference window.
- Related ticket: https://progress.opensuse.org/issues/160114
- Needles: already added when debugging on osd 
- Verification run: https://openqa.suse.de/tests/14257653#step/onetime_vncsession_xvnc_remmina/21
(Note: The VR is failed due to the bug https://bugzilla.suse.com/show_bug.cgi?id=1224048)

Fix remmina failure on SLE15SP6

---

tests/publiccloud/slem_basic.pm

Reverts os-autoinst/os-autoinst-distri-opensuse#19218. After some communication with developers and PMs it was clarified that we do need to support cockpit in SL Micro 6.0

Revert "Skip cockpit test for SLM 6.0"

---

data/publiccloud/restart_instance.sh
tests/publiccloud/run_ltp.pm

>> Still needs fixes in Kirk :( <<
Port run_ltp.ng of public cloud into Kirk
- Related ticket: https://progress.opensuse.org/issues/157177
* https://openqa.suse.de/tests/14225514
* https://openqa.suse.de/tests/14225299
* https://openqa.suse.de/tests/14224155
* https://openqa.suse.de/tests/14225297
* https://openqa.suse.de/tests/14225298

Port PublicCloud run_ltp to kirk

---

tests/virt_autotest/install_package.pm

The workaround is temporary, it will be removed when https://github.com/SUSE/qa-automation/pull/822 is finally merged.
- Related ticket: https://progress.opensuse.org/issues/159087
[prj4_kvm](https://10.145.10.207/tests/14265359)
[prj3_xen_pv](https://openqa.suse.de/tests/14265328#)
[prj1](https://10.145.10.207/tests/14265977#)
[prj2](https://10.145.10.207/tests/14265978#details)
[UEFI](https://10.145.10.207/tests/14267734)

Workaround of PR#822 to install a customized qa_lib_key and qa_lib_virtauto packages in personal IBS

---

lib/publiccloud/instance.pm

During logs upload in `create_instance`, the ssh `ls` check returns the 'list of file to upload' with an unexpected '\t' in place of space separator, causing names fusion in the tar command, then error. See i.e. job [14271031](https://openqa.suse.de/tests/14271031#step/prepare_instance/209).
After attempts to purify the spaces of the string representing the file-list, the better stable and successful solution resulted to convert filenames in array then join members in the tar command.
- Related ticket: https://progress.opensuse.org/issues/160038
- https://openqa.suse.de/tests/14277229#step/prepare_instance/207

P.C. create_instance logs list fix

---

data/virt_autotest/kubevirt_tests/core-tests.conf
data/virt_autotest/kubevirt_tests/full-tests.conf
lib/virt_autotest/kubevirt_utils.pm
schedule/virt_autotest/kubevirt-tests.yaml
schedule/virt_autotest/slem-kubevirt-tests.yaml
tests/virt_autotest/kubevirt_tests_agent.pm
tests/virt_autotest/kubevirt_tests_server.pm

1. Add slem-kubevirt-tests.yaml
2. Add live migration into core tests
3. Enable NTP service
4. Setup cnv-bridge containernetworking plugin
5. Set the value of default storage class with true
6. Optimize Whereabouts plugin downloading
- Related ticket: https://progress.opensuse.org/issues/138638
sle-micro 6.0 - http://10.67.129.96/tests/3186
sles15 sp6 - http://10.67.129.96/tests/3191

Support kubevirt tests on sle-micro 6.0

---

lib/publiccloud/instance.pm

The guard check of the array size _passed_ for `empty` array, so when no log present the tar still was triggered, but failed.
The default max index was used `$#logs` that is `= 0` for size=1 and `=-1` for empty arrays.
Therefore, a test expression `($#Array)` for empty arrays (=-1) is true, but false (=0) for size=1 arrays.
To check array size we should use `scalar(@array)`.
- Related ticket: https://progress.opensuse.org/issues/160038

Pub.Cloud upload logs: fix array size check

---

schedule/yast/maintenance/yast_mru_install_minimal_with_addons_restapi_pcm.yaml

test mru-yast-mru-install-minimal-with-addons@s390x fails due to pcm patterns taking over the top of the selection list on step: https://openqa.suse.de/tests/14287410#step/select_only_visible_patterns_from_top/10
Here, an additional schedule that uses select_patterns module, instead of select_only_visible_patterns_from_top is added.
VR: https://openqa.suse.de/tests/14291680
MR: https://gitlab.suse.de/qe-yam/openqa-job-groups/-/merge_requests/193

Add schedule with select_patterns module for yast-mru-install-minimal-with-addons

---

lib/main_containers.pm
tests/containers/aardvark_integration.pm
tests/containers/netavark_integration.pm

This PR:
- Adds aardvark-dns upstream tests from https://github.com/containers/netavark/tree/main/test
- Uses nmap's ncat instead of openbsd-netcat for netavark test: https://github.com/containers/netavark/tree/main/test
---
- Related ticket: https://progress.opensuse.org/issues/160254
- Related PR: https://github.com/os-autoinst/opensuse-jobgroups/pull/455
- opensuse-Tumbleweed-DVD-x86_64-Build20240513-containers_host_podman_testsuite@64bit -> https://openqa.opensuse.org/tests/4186976

Add aardvark-dns upstream tests

---

tests/security/ntpd.pm

ntp test was failing because package has been moved to legacy module. 
- Related ticket: https://progress.opensuse.org/issues/160080
- https://openqa.suse.de/tests/14296985
- https://openqa.suse.de/tests/14296986
- https://openqa.suse.de/tests/14296987

Add legacy module for ntp testing on SLE 15.6

---

lib/utils.pm
tests/transactional/install_updates.pm

We are booting GA images for maintenance updates. Ideally, we should install the incidents under tests on an updated system. It has been observed that installing everything at once can cause false positives and packages not being updated.
With this approach, we first update the system and after reboot, we add and install the incidents using the patch option.
VR: https://openqa.suse.de/tests/14293397#step/install_updates/257

Update the system first before installing incidents in SLE Micro

---

tests/publiccloud/img_proof.pm

Fix img-proof test on GCE.
Related MR: https://gitlab.suse.de/qac/qac-openqa-yaml/-/merge_requests/1643
Failing test: https://openqa.suse.de/tests/14298463#step/img_proof/203 (failing due to https://bugzilla.suse.com/show_bug.cgi?id=1224011)
Verification run: https://openqa.suse.de/tests/14299882

pc: Use a here-document instead of echo to write file

---

lib/main_containers.pm
tests/containers/buildah_integration.pm

Add buildah upstream tests from https://github.com/containers/buildah/tree/main/tests
- Related ticket: https://progress.opensuse.org/issues/160257
- Related PR: https://github.com/os-autoinst/opensuse-jobgroups/pull/456
- opensuse-Tumbleweed-DVD-x86_64-Build20240513-containers_host_podman_testsuite@64bit -> https://openqa.opensuse.org/tests/4188708
Notes:
- Used `BUILDAH_BATS_SKIP="commit copy run" BUILDAH_BATS_SKIP_USER="add basic bud chroot overlay rmi sbom squash"`
- Test uses images available only for amd64, not arm64.

containers: Add buildah upstream tests

---

tests/containers/podman_netavark.pm

The same situation as we with s390x or public cloud. When create a
macvlan podman network, we need to specify more verbose setup
- ticket: https://progress.opensuse.org/issues/152194
- Verification run: https://openqa.suse.de/tests/14310071#step/podman_netavark/137

vmware: create macvlan with gateway and subnet

---

lib/btrfs_test.pm
lib/main_common.pm
tests/console/snapper_create.pm
tests/console/snapper_used_space.pm

Newer version of snapper support json output. It is more convenient for parsing the data in snapper tests.
- ticket: https://progress.opensuse.org/issues/160026
* [12-SP5](http://kepler.suse.cz/tests/23327#step/snapper_create/1)
* [15-SP4](http://kepler.suse.cz/tests/23326#step/snapper_create/1)
* [TW - stagging](http://kepler.suse.cz/tests/23325#step/snapper_create/1)

Use json output for snapper

---

tests/publiccloud/img_proof.pm

Do not soft-fail for https://bugzilla.suse.com/show_bug.cgi?id=1220269 anymore.  Introduce a variable to soft-fail SCAP module on img-proof instead.
This is passing on all providers:
- EC2: https://openqa.suse.de/tests/14298685/file/img_proof-report.html
- Azure: https://openqa.suse.de/tests/14265591/file/img_proof-report.html
- GCE: https://openqa.suse.de/tests/14299882/file/img_proof-report.html

pc: Do not soft-fail for bsc#1220269

---

data/elemental/cloud-config.yaml
data/journal_check/bug_refs.json
products/elemental
tests/elemental/installation.pm

Elemental is now more integrated with SL-Micro. Add support for Elemental image based on SL-Micro 6.0.
- Needles: https://gitlab.suse.de/openqa/os-autoinst-needles-sles/-/merge_requests/1663
- Triggering: https://gitlab.suse.de/openqa/salt-states-openqa/-/merge_requests/1167 + https://gitlab.suse.de/openqa/openqa-trigger-from-ibs-plugin/-/merge_requests/172
- Verification run: on my local lab, cannot be share. See screenshot. But anyway the modified code only impact the Elemental tests which are not running well anyway.

Fix Elemental test

---

lib/main_containers.pm
tests/containers/buildah_integration.pm

- Related ticket: https://progress.opensuse.org/issues/160257
- Related MR: https://gitlab.suse.de/qac/qac-openqa-yaml/-/merge_requests/1645
- sle-15-SP5-Server-DVD-Updates-x86_64-Build20240514-1-podman_testsuite@64bit -> https://openqa.suse.de/t14311790
- sle-15-SP4-Server-DVD-Updates-x86_64-Build20240514-1-podman_testsuite@64bit -> https://openqa.suse.de/t14311792
- sle-15-SP6-Server-DVD-Updates-x86_64-Build20240514-1-podman_testsuite@64bit -> https://openqa.suse.de/tests/14311851

containers: Enable buildah upstream tests for SLE

---

lib/filesystem_utils.pm
test_data/yast/encryption/default_enc_luks2.yaml
test_data/yast/encryption/full_lvm_enc_luks2.yaml
test_data/yast/encryption/lvm_encrypt_separate_boot_luks2.yaml

LUKS2 is default on Tumbleweed meanwhile and `lsblk --help` no longer lists columns.
- Related tickets: https://progress.opensuse.org/issues/160153 https://progress.opensuse.org/issues/160260
* lvm-encrypt-separate-boot: https://openqa.opensuse.org/tests/4190740#live
* lvm-full-encrypt: https://openqa.opensuse.org/tests/4190868#live
* autoyast_reinstall_gnome: https://openqa.opensuse.org/tests/4190922#live

Fix some filesystem check failures on Tumbleweed

---

tests/console/yast2_lan_hostname/dhcp_yes_eth.pm

- Related ticket: https://progress.opensuse.org/issues/154465
- Verification run: https://openqa.opensuse.org/tests/4190718

yast2_lan_hostname/dhcp_yes_eth: Skip if NetworkManager is used

---

lib/main_containers.pm
variables.md

When doing runs with a custom git repository, we need to re-run bci_prepare.pm. This commit adds a new setting BCI_PREPARE that allows us to re-initialize the already existing git repository.
- Verification run: https://openqa.suse.de/tests/14318285#step/bci_prepare/73

Add switch to re-prepare BCI

---

lib/main_containers.pm
tests/containers/aardvark_integration.pm
tests/containers/netavark_integration.pm

- Related MR: https://gitlab.suse.de/qac/qac-openqa-yaml/-/merge_requests/1648
- Related ticket: https://progress.opensuse.org/issues/160254
- sle-15-SP6-Server-DVD-Updates-x86_64-Build20240514-1-podman_testsuite@64bit -> https://openqa.suse.de/t14318703
- sle-15-SP6-Server-DVD-Updates-aarch64-Build20240514-1-podman_testsuite@aarch64-virtio -> https://openqa.suse.de/t14318704
- sle-15-SP4-Server-DVD-Updates-x86_64-Build20240515-1-podman_testsuite@64bit -> https://openqa.suse.de/t14318705
- sle-15-SP4-Server-DVD-Updates-aarch64-Build20240515-1-podman_testsuite@aarch64-virtio -> https://openqa.suse.de/t14318706
- sle-15-SP5-Server-DVD-Updates-x86_64-Build20240515-1-podman_testsuite@64bit -> https://openqa.suse.de/t14318707
- …

containers: Enable netavark & aardvark-dns upstream tests in SLE

---

tests/console/snapper_create.pm

`--disable-used-space` flag is not present in old snapper versions. Remove this flag from global calls.
* [sle12sp5](http://kepler.suse.cz/tests/23348#step/snapper_cleanup/1)
* [sle12sp3](http://kepler.suse.cz/tests/23347#step/snapper_cleanup/1)

Remove unknown flag from old snapper

---

lib/bootloader_pvm.pm

This commit introduces the `SET_NVRAM_DEFAULTS` setting, that will cause the functions in lib/bootloader_pvm.pm to boot the LPAR into the Open Firmware command line prompt and issue a `SET_NVRAM_DEFAULTS` to reset the values in the LPAR's NVRAM to its defaults. This can help to fix some boot issues caused by aborted boot processes in the LPAR, which in turn prevent the GRUB menu from being loaded. If set, LPAR will boot into the Open Firmware prompt, issue the command and then continue to boot normally. If not set, it will boot as usual.
- Needles: https://gitlab.suse.de/openqa/os-autoinst-needles-sles/-/merge_requests/1664 …

Add a setting to force LPAR to set defaults in NVRAM before booting

---

lib/main_common.pm
t/data/test_schedule.out

- Related tickets: 
- kontact https://progress.opensuse.org/issues/159981
- khelpcenter https://progress.opensuse.org/issues/159978
- Verification run: https://openqa.opensuse.org/tests/overview?build=cedvid%2Fos-autoinst-distri-opensuse%2319297

Skip loading kontact and khelpcenter on unsupported architecture

---

tests/installation/ipxe_install.pm

`unreal3` always failed to bootup after installation. I checked the screen via iKVM console, the it hung at bootloader with GUI mode. I suspect missing `textmode=1` option in bootscript is the cause. Validation runs have been made but as this bootup failure did not happened all the time, Let's see if it will fix the failure after the PR merged. Even if it does not fix the bootup failure, it will not introduce problems to our tests.  **Expect the PR can be merged before sle15sp6 GMC candidate build on May 17**.
- Related ticket: https://progress.opensuse.org/issues/160421
[sle15sp6_kvm_host](https://10.145.10.207/tests/14318324)
[sle15sp6_xen_host](https://10.145.10.207/tests/14318397)
[sle12sp5_kvm_host](https://10.145.10.207/tests/14318452) …

Set textmode during host installation with VIDEOMODE=text

---

lib/registration.pm

- Related ticket: https://progress.opensuse.org/issues/151891
- Needles: N/A
- Verification run: http://openqa.suse.de/tests/14310970#step/scc_deregistration/11
- For installation process, it is not needed to have the workaround for python2, all test passed without the workaround http://openqa.suse.de/tests/overview?version=15-SP6&build=lemon-suse%2Fos-autoinst-distri-opensuse%23revisit-bsc%231189543&distri=sle

Remove workaround for bsc#1189543

---

tests/console/system_prepare.pm
tests/installation/addon_products_sle.pm

The installation via full media will skip registration to ensure minimal patch for migration test, we need add condition to make it clear that it is a installation process prepared for migration test.
- Related ticket: https://progress.opensuse.org/issues/160017
- Related MR: https://gitlab.suse.de/qe-yam/openqa-job-groups/-/merge_requests/197
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/14311858#

Add setting for installation via full media on power VM

---

tests/fips/openssl/openssl_fips_cipher.pm

`des3` and `des-ede3` ciphers should not be allowed in FIPS mode.
* [tw](http://kepler.suse.cz/tests/23360#step/openssl_fips_cipher/57)
* [microos](http://kepler.suse.cz/tests/23364#)

Exclude deprecate ciphers in TW and MicroOS

---

tests/wsl/firstrun.pm

Added WSL Beta license logic.
Add firstrun-wsl-licence-beta needle
Add wsl/firstrun logic to account for BETA variable
- Related ticket: https://progress.opensuse.org/issues/160448
https://openqa.suse.de/tests/14341874 --> checking for Beta license.
https://openqa.suse.de/tests/14342607 --> current run with Beta undefined
https://openqa.suse.de/tests/14342606 --> sled fails because the WE license is still in beta. According to https://bugzilla.suse.com/show_bug.cgi?id=1224351 , once GMC is pushed to update.suse.com, we will get the GM license. For now, this test will fail, as expected. 
Additionally, I have removed the BETA variable from latest WSL runs, as they are supposed to be running in GM state already: …

WSL Beta license

---

lib/main_common.pm
tests/console/btrfs_check.pm

The main idea is to check for the correct btrfs layout on the disk. Snapshots and rollbacks are already covered in other test modules.
- Related ticket: https://progress.opensuse.org/issues/66613
- http://10.146.5.131/tests/69
- https://openqa.suse.de/tests/14366334
- http://10.146.5.131/tests/70
- https://openqa.suse.de/tests/14366448
- https://openqa.suse.de/tests/14366449
- https://openqa.suse.de/tests/14366450
- https://openqa.suse.de/tests/14366514

New test for correct btrfs setup

---

tests/fips/openssl/openssl_pubkey_dsa.pm

Parameters passed to `awk` were interprated by perl instead of bash.
Fail: https://openqa.opensuse.org/tests/4203705#step/openssl_pubkey_dsa/23
VR: http://kepler.suse.cz/tests/23373#step/openssl_pubkey_dsa/23

Fix parameters interpretation in `openssl_pubkey_dsa`

---

tests/support_server/setup.pm

When doing migration, we need to cleanup the configuration which is done by previous step. We could see the code in function `setup_dns_server`, it adds `openqa.zones` to `/etc/named.conf`. So we need to remove it before configuring again.
Related: https://jira.suse.com/browse/TEAM-8653
VRs:
https://openqa.suse.de/tests/14318725#step/setup/9
https://openqa.suse.de/tests/14322174#step/setup/9

Remove the configuration left by previous setup

---

data/autoyast_sle15/autoyast_sles4sap.xml.ep

Fix [TEAM-9296](https://jira.suse.com/browse/TEAM-9296), autoyast_sles4sap_hana test case failed sometimes because of grub2 menu timeout, this PR fixed it by disabling grub timeout.
- Related ticket: https://jira.suse.com/browse/TEAM-9296
https://openqa.suse.de/tests/14267063 (ppc)
https://openqa.suse.de/tests/14267064 (ppc)
https://openqa.suse.de/tests/14267065 (ppc)
https://openqa.suse.de/tests/14288221 (x86_64)
https://openqa.suse.de/tests/14288222 (x86_64)

Disable GRUB_TIMEOUT to avoid grub_test.pm failed

---

lib/qam.pm
variables.md

Some of the repositories for the new maintenance workflow do not contain proper keys (at least the prototype ones). This adds an optional variable to include the -G (no gpg checks) flag to zypper ar.
VR:
- https://openqa.suse.de/tests/14293011 (without flag, default behavior)
- https://openqa.suse.de/tests/14293010 (with flag)

Add optional -G flag in zypper when adding MU repos

---

tests/containers/buildah_integration.pm

Call remove_mounts_conf in BATS buildah test
Failing test: https://openqa.suse.de/tests/14368044/logfile?filename=serial_terminal.txt
```
```
- sle-15-SP6-Online-x86_64-Build92.1-buildah_testsuite@64bit -> https://openqa.suse.de/t14402014 
Note: VR failing for other reason (`# Fatal glibc error: CPU does not support x86-64-v2`) but error message above not present.

containers: Call remove_mounts_conf in BATS buildah test

---

data/yam/autoyast/autoyast_scc_up.xml

##
* https://progress.opensuse.org/issues/153823
- Related MR:
* https://gitlab.suse.de/qe-yam/openqa-job-groups/-/merge_requests/166/
- Needles: 
* N/A
* [**Support_image**](https://openqa.suse.de/tests/overview?arch=&flavor=&machine=&test=supp_migr_sles_15sp4_15sp5_dev&modules=&module_re=&group_glob=&not_group_glob=&comment=&version=15-SP5&groupid=318&distri=sle#)
* Migration for 2nd step:
[**Migration_VR**](https://openqa.suse.de/tests/overview?arch=&flavor=&machine=&test=migr_sles_continuous_15sp4_15sp5_ph1_dev1&modules=&module_re=&group_glob=&not_group_glob=&comment=&build=89.1&version=15-SP6&distri=sle#)
##

Convert 1st phase of continuous migration into support image

---

tests/support_server/setup.pm

For some supportserver cases, the 'dns' is not needed, there is no `/etc/named.conf`. So we need to check before doing `sed`.
Related: https://github.com/os
-autoinst/os-autoinst-distri-opensuse/pull/19326
VR: 
https://openqa.suse.de/tests/14411116#
https://openqa.suse.de/tests/14411118#

Fix the regession issue cause by pr#19326

---

tests/sles4sap/wizard_hana_install.pm

Now the SAP Installation Wizard vesion in 15-SP5 also uses the same hot keys as the version in 15-SP6, so we need to update the test to take this into account.
- Needles: N/A
- Verification run: http://mango.qe.nue2.suse.org/tests/5838

Support new hotkeys in SAP Installation Wizard in 15-SP5

---

tests/migration/online_migration/zypper_patch.pm

This is a workaround for bsc#1224249, that is to remove package of
python3-argcomplete-1.9.2-150000.3.8.1 before migraiton, becuase the 
higher python3-argcomplete version 1.9.2-150000.3.8.1 is not synced
to SLES15SP6 update channel yet, which caused a failure when doing 
zypper migration. We will remove this workaround when the package is
synced to 15SP6 update channel after GM.
- Needles: n/a
- https://openqa.suse.de/tests/14413370#step/zypper_patch/21  (To verify zypper migration)
- https://openqa.suse.de/tests/14413371#step/zypper_patch/16  (To confirm it doesn't affect yast2 migration jobs)

Workaround to remove python3-argcomplete before migration

---

data/virtualization/autoyast/guest_12.xml.ep
data/virtualization/autoyast/guest_15.xml.ep
data/virtualization/autoyast/host_12.xml.ep
data/virtualization/autoyast/host_15.xml.ep

Hide keys in some openqa settings, and replace in the autoyast template Progress ticket: 
- Related ticket: https://progress.opensuse.org/issues/160099
- Needles: N/A
[15sp5_kvm](http://openqa.qam.suse.cz/tests/overview?build=Test_key_kvm_15-SP5&distri=sle&version=15-SP5&groupid=167)
[15sp5_xen](http://openqa.qam.suse.cz/tests/overview?build=Test_key_xen_15-SP5&distri=sle&version=15-SP5&groupid=168)
[12sp5_kvm](http://openqa.qam.suse.cz/tests/overview?build=Test_key_kvm_12-SP5&distri=sle&version=12-SP5&groupid=149)
[12sp5_xen](http://openqa.qam.suse.cz/tests/overview?build=Test_key_xen_12-SP5&distri=sle&version=12-SP5&groupid=160)
[15sp5_xen_migration](http://openqa.qam.suse.cz/tests/overview?build=Test_key_xen_15-SP5%3Alive_migrat&distri=sle&version=15-SP5&groupid=168 …

Avoid explicit ssh private keys in autoyast template

---

tests/network/nfs.pm

test is slightly slower, but is not failing
- Related ticket: https://progress.opensuse.org/issues/160706
https://openqa.suse.de/tests/14414376
https://openqa.suse.de/tests/14414377

nfs: Incease test timeout

---

tests/installation/welcome.pm

Sometimes it is not enough time to update installer on s390x, so need enlarge the timeout value.
Failed job: https://openqa.suse.de/tests/14419377#step/welcome/21
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/14421334#step/welcome/6

Enlarge welcome timeout value on s390x

---

tests/console/django.pm

The Django package provided in SP6 is python311-Django
https://bugzilla.suse.com/show_bug.cgi?id=1221960
- Related ticket: https://progress.opensuse.org/issues/159972
- Needles: NO
15SP6 - [x86_64](https://openqa.suse.de/tests/14412365) | [s390x](https://openqa.suse.de/tests/14412360) | [aarch64](https://openqa.suse.de/tests/14412358)
[x86_64](https://openqa.suse.de/tests/14412357)
15-SP5- [x86_64](https://openqa.suse.de/tests/14412389) | [s390x](https://openqa.suse.de/tests/14412385) | [aarch64](https://openqa.suse.de/tests/14412381)
15-SP4 -  [x86_64](https://openqa.suse.de/tests/14412378) | [s390x](https://openqa.suse.de/tests/14412372) | [aarch64](https://openqa.suse.de/tests/14412367)
Tumbleweed- [x86_64](https://openqa.opensuse.org/tests/4213233)
Leap - …

Fix django test in SLE 15-SP6

---

data/yam/autoyast/autoyast_scc_up.xml

It is not work for migration test via autoyast, so we need set a suitable value for the wait time for grub2 in profile.
- Needles: N/A
https://openqa.suse.de/tests/14422280#details  Migration test via autoyast
https://openqa.suse.de/tests/14422367#  Interactive migration test

Change waiting time for grub2

---

schedule/security/crypto_policies.yaml
tests/security/crypto_policies/crypto_policies_setup.pm
tests/security/crypto_policies/crypto_policies_sshd.pm

This is a new test part of a series for covering [crypto-policies](https://en.opensuse.org/SDB:Crypto-policies). 
- Related ticket: https://progress.opensuse.org/issues/159897
- Needles: no
- https://openqa.suse.de/tests/14414457
- https://openqa.suse.de/tests/14414458
- https://openqa.suse.de/tests/14414459

Add test for crypto-policies switching and sshd configuration

---

lib/publiccloud/ec2.pm
tests/publiccloud/upload_image.pm

Use pre-created "tf-vpc" VPC when uploading images to EC2.  This avoids creating new VPC's, thus avoiding the `maximum number of VPCs has been reached` error.
- Related ticket: https://progress.opensuse.org/issues/158323
- Verification run: https://openqa.suse.de/tests/14423487
Note: VR tested with deleted commit:
https://github.com/os-autoinst/os-autoinst-distri-opensuse/compare/0b38c31e1d36cc721d07bd00c2917fbebb1d9861..39a19e5171b3deb76e8afe540805cc2ef5c9644e

pc: Use common VPC for uploading in EC2

---

.github/workflows/openqa-comment.yml

The default workflow token is not enough to determine the commentator's team membership so I created a token manually.
Related ticket: https://progress.opensuse.org/issues/130940
---
I created the token with https://github.com/os-autoinst-bot and already added it to our organization secrets. It has the minimum access required for this workflow. (Creating a token like this worked on my fork. Not sure how else to test this.)

Fix permission error in workflow for cloning jobs from comments

---

tests/xfstests/install.pm

The qam-klp_xfstests_* can't add tests by XFSTESTS_GROUPLIST. The problem is QA_HEAD_REPO is old, and after update the repo, I found the repo didn't change. The root cause is add_qa_head_repo checking it's already has QA_HEAD_REPO and didn't update it even it's different. So add zypper_call("rr qa-head") before add_qa_head_repo to solve this problem
- Related ticket:  https://progress.opensuse.org/issues/160784
- https://openqa.suse.de/tests/14422713
- One more VR to check if the QA_HEAD_REPO didn't set. https://openqa.suse.de/tests/14423116

xfstests: Remove old qa-head repo before add new

---

tests/console/znc.pm

This is important as different versions pass different --datadir= parameters (or omit it, which then implies ~/.znc).
- Related ticket: https://bugzilla.suse.com/show_bug.cgi?id=1224023
- Needles: N/A
- Verification run: https://openqa.opensuse.org/tests/4217047#step/znc/10

znc: use the same parameters for --makeconf as the service uses

---

lib/x11test.pm
tests/x11/gnote/gnote_search_title.pm
tests/x11/libreoffice/libreoffice_double_click_file.pm

With GNOTE 46, right-clicking a note to delete it is no longer possible
So, we need to use a different way to delete a note, here we will use `send_key "delete";`
Besides, due to bsc#1224395 the ctrl-q do not work on libreoffice math
So, I am updating the code to use  `assert_and_click 'close-libreoffice';`
- Related ticket: https://progress.opensuse.org/issues/157672
- Needles: already added when debugging on o3 and osd
>  TW Wayland:  https://openqa.opensuse.org/tests/4215188#
(The [libreoffice_mainmenu_components](https://openqa.opensuse.org/tests/4215188/modules/libreoffice_mainmenu_components/steps/1/src) failed due to https://bugzilla.opensuse.org/show_bug.cgi?id=1225089)
>  TW X11: https://openqa.opensuse.org/tests/4219308#
>  SLE15SP6 X11: …

Fix gnote and libreoffice failure on gnome46

---

.github/workflows/openqa-comment.yml

Run the workflow only for comments that contain the relevant phrase. Note that the GitHub `contains()` function is not case sensitive which is in-line with how our GitHub workflow actually does the matching.
Related ticket: https://progress.opensuse.org/issues/130940
---
Tested on my fork where jobs where now irrelevant workflow actions end up skipped immediately (e.g. https://github.com/Martchus/os-autoinst-distri-opensuse/actions/runs/9222599851) but relevant ones are still executed (e.g. https://github.com/Martchus/os-autoinst-distri-opensuse/actions/runs/9222550135/job/25373924134).

Avoid running workflow for cloning via comments for all comments

---

tests/qa_automation/patch_and_reboot.pm

In _JeOS Maintenance Updates_ zypper update a new license agreement occurred, needing 'yes', but default 'no' caused tests to fail. `zypper update` command changed adding `-l` = `--auto-agree-with-licenses`
- Related ticket: https://progress.opensuse.org/issues/160913
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/14432777

JeOS zypper update license auto-agree added

---

tests/installation/add_serial_console.pm

Fix the needle match failure for open-vm-tools tests - https://openqa.suse.de/tests/14384793#step/esxi_open_vm_tools/61
- Related ticket: https://progress.opensuse.org/issues/159081
- Verification run: https://openqa.suse.de/tests/14423446

Fix the problem of linux login during guest poweron

---

tests/sles4sap/publiccloud/hana_sr_takeover.pm

Adds check about the state of the master node in the end of the `hana_sr_takeover` module. If the master node is the same as in the beginning of the module, the test fails.
- Related ticket: https://jira.suse.com/browse/TEAM-9214
- Verification run: https://openqa.suse.de/tests/14414267#step/Stop_site_a-primary/650 (**PASS** - issue is too sporadic to reproduce)

Add master node check

---

tests/xfstests/run.pm
variables.md

Implemented according to LTP_KNOWN_ISSUES
e.g.
XFSTESTS_KNOWN_ISSUES=https://openqa.suse.de/xfstests_known_issues.json If an error occur which is listed in json file,  then the result marded as SOFTFAIL.
- Related ticket: https://progress.opensuse.org/issues/158152
- Needles: N/A
- Verification run: http://10.67.133.133/tests/659
- https://openqa.suse.de/tests/14440494 (QAM)

xfstests: Set XFSTESTS_KNOWN_ISSUES variable

---

tests/sles4sap/wizard_hana_install.pm

Using assert_script_run instead of enter_cmd to avoid this error.
TEAM-9310 - [15-SP6][sles4sap][ppc64le] sles4sap_scc_gnome_hana_wizard sporadically failed on "wizard_hana_install": script timeout
- Related ticket: https://jira.suse.com/browse/TEAM-9310
- Needles: NA
https://openqa.suse.de/tests/14429620#next_previous (run 10+ times all runs are passed)

Fix wizard_hana_install script timeout on ppc64le

---

schedule/security/encryption/fips_install_encrypt_lvm_separate_boot@aarch64.yaml

This adds a new schedule for encrypted install test on aarch64, since the installations steps have changed on SLE 15-SP6.
- Related ticket: https://progress.opensuse.org/issues/160472
- 15 SP6: https://openqa.suse.de/tests/14441462
- 15 SP5: https://openqa.suse.de/tests/14441460
- 15 SP4: https://openqa.suse.de/tests/14441451

Separate schedule for encrypted install on aarch64

---

lib/containers/common.pm
lib/containers/containerd_crictl.pm
lib/containers/containerd_nerdctl.pm
lib/containers/engine.pm
lib/containers/utils.pm
lib/main_containers.pm
tests/containers/container_engine.pm
tests/containers/firewall.pm
tests/containers/podman_netavark.pm
tests/containers/podman_network_cni.pm
tests/containers/rootless_podman.pm

Minimize dependency on registry mirror.  Some uses of alpine can be perfectly done by smaller busybox image from OBS. Same with httpd shipped by openSUSE.
- Related ticket: https://progress.opensuse.org/issues/160823
- microos-Staging:A-Staging-MicroOS-Image-ContainerHost-x86_64-BuildA.75.24-microos@64bit -> https://openqa.opensuse.org/t4223849
- opensuse-Tumbleweed-DVD-x86_64-Build20240524-containers_image@64bit -> https://openqa.opensuse.org/t4224036

containers: Minimize dependency on registry mirror

---

test_data/yast/encryption/crypt_no_lvm_enc_luks2.yaml
test_data/yast/encryption/full_lvm_enc_luks2.yaml

Create a new test_data for 'crypt_no_lvm', and recover the encrypted device num for test_data/yast/encryption/full_lvm_enc_luks2,yaml.   Need update 'crypt_no_lvm' in https://openqa.opensuse.org/admin/test_suites after this PR merged.
- Related ticket: https://progress.opensuse.org/issues/160841
- Needles: N/A
- Verification run: https://openqa.opensuse.org/tests/4223503#  crypt_no_lvm
https://openqa.opensuse.org/tests/4223504#  cryptlvm

Fix encrypted device num issue

---

tests/virt_autotest/kubevirt_tests_server.pm

Fix a setup command failure for kubevirt test - http://10.67.129.96/tests/3322#step/kubevirt_tests_server/276
- Related ticket: https://progress.opensuse.org/issues/160910
- Verification run: http://10.67.129.96/tests/3344

Fix a command execution timeout failure

---

lib/publiccloud/ec2.pm

Fix for `The subnet ID 'none' does not exist`.
- Failing test: https://openqa.suse.de/tests/14441776/logfile?filename=serial_terminal.txt
- Related ticket: https://progress.opensuse.org/issues/158323
- Verification run: https://openqa.suse.de/tests/14451978

containers: Check output of ec2 commands that may return None

---

lib/qesapdeployment.pm
lib/sles4sap_publiccloud.pm
lib/trento.pm
t/09_qesapdeployment.t
tests/sles4sap/publiccloud/qesap_ansible.pm
tests/sles4sap/publiccloud/qesap_terraform.pm
tests/sles4sap/qesapdeployment/deploy.pm
tests/sles4sap/qesapdeployment/destroy.pm
tests/sles4sap/qesapdeployment/test_cluster.pm

Add the gluescript argument to generate JUnit Ansible report and add openQA code to consume and present it.
Enable it only for the main Ansible qesap_exec of the qesap regression test.
Simplify the qesap_exec internals making `logname` as mandatory and removing the algorithm to calculate it.
:warning: this PR needs qe-sap-deployment version greater or equal than 0.26.0
- Related ticket: TEAM-6844
sle-15-SP6-Qesap-Azure-Byos-Ibs-x86_64-BuildLATEST_AZURE_SLE15_6_BYOS_IBS-qesap_azure_uri@az_Standard_E8s_v3 
Job is failing (known issue) but features or interest are working:
- ansible is called with the new `--junit` argument
- openQA "slurps" the result and present it properly in http://openqaworker15.qa.suse.cz/tests/283546#external
- the mandatory argument `logname` is configured and result …

Add JUnit ansible output to qesap regression

---

tests/containers/slem_rancher.pm

sleep is better suited for keeping an image running than bash.
- Related ticket: https://progress.opensuse.org/issues/160967
- Related failure: https://openqa.suse.de/tests/14427929/modules/slem_rancher/steps/9
- Verification run: https://duck-norris.qe.suse.de/tests/14669

Fix starting of rancher image

---

lib/qesapdeployment.pm
t/09_qesapdeployment.t
tests/sles4sap/publiccloud/qesap_ansible.pm
tests/sles4sap/qesapdeployment/deploy.pm

Split error detection from retry. Add more unit testings. Move the read of the PC setting up from the lib to the test module.
- Related ticket: https://jira.suse.com/browse/TEAM-9092 https://jira.suse.com/browse/TEAM-9068
This PR is a preliminary step to re-think about the deployment retry mechanism, to be able to use retry also in MU testing.
- sle-15-SP5-Qesap-Azure-Payg-x86_64-BuildLATEST_AZURE_SLE15_5_PAYG-qesap_azure_saptune_test@64bit -> http://openqaworker15.qa.suse.cz/tests/284922 :green_circle: no ansible failure
-  sle-15-SP5-Qesap-Azure-Payg-x86_64-BuildLATEST_AZURE_SLE15_5_PAYG-qesap_azure_saptune_test_msi@64bit -> http://openqaworker15.qa.suse.cz/tests/284923 :green_circle: no ansible failure, failure is later and not related to PR content
- …

Split qesap Ansible retry

---

tests/containers/firewall.pm
tests/containers/podman_netavark.pm
tests/containers/secret.pm
tests/containers/volumes.pm

Use the same busybox image used in the libraries for consistency.
https://suse.slack.com/archives/C02CGKBCGT1/p1716885408648449
Verifications runs:
- sle-15-SP6-Server-DVD-Updates-x86_64-Build20240527-1-podman_tests@64bit -> https://openqa.suse.de/tests/14463386

containers: Use registry.opensuse.org/opensuse/busybox instead of BCI

---

schedule/sles4sap/qam/common/qam_install_sles4sap.yaml

Entries for 15-SP6 and 15-SP7 are missing in schedule `schedule/sles4sap/qam/common/qam_install_sles4sap.yaml` used in the installation of SLES and SLES for SAP Applications systems on QAM tests. This commit adds them.
No verification runs as change is trivial and shouldn't impact other tests.
- Needles: N/A

Add 15-SP6 & 15-SP7 on qam_install_sles4sap schedule

---

tests/migration/online_migration/zypper_migration.pm

The wicked package version on target product is lower then it is on original product, wicked package is not changes during migration, and the wicked service is disbaled by systemd-presets-branding-SMO. Need to add a workaround to enable wicked service after migration.
- Needles: n/a
- Verification run: https://openqa.suse.de/tests/14463759

Add a workaround to enable wicked service

---

lib/db_utils.pm

Sometimes pushing some datapoints to the datapoints results in 504 errors. To avoid data loss we retry 3 times with a qubic backoff sleep to avoid database load issues.
- Related failure: https://openqa.suse.de/tests/14413963#step/image_info/6
- Verification run: https://openqa.suse.de/tests/14475195

Retry database push in case of errors

---

schedule/security/scap_workbench.yaml
tests/security/scap_workbench/scap_workbench.pm

- Disable screensaver during scan
- give more RAM and CPU resources to the SUT 
- tweaks to timeouts and needles handling
- Related ticket: https://progress.opensuse.org/issues/160988
- Needles: no
- https://openqa.suse.de/tests/14480163
- https://openqa.suse.de/tests/14480164
- https://openqa.suse.de/tests/14480165
- https://openqa.suse.de/tests/14480166
- https://openqa.suse.de/tests/14480167
- https://openqa.suse.de/tests/14480168
- https://openqa.suse.de/tests/14480169
- https://openqa.suse.de/tests/14480170
- https://openqa.suse.de/tests/14480171
- https://openqa.suse.de/tests/14480172
- https://openqa.suse.de/tests/14480173
- https://openqa.suse.de/tests/14480174
- https://openqa.suse.de/tests/14480175
- https://openqa.suse.de/tests/14480176
- …

scap_workbench: some tweaks to improve on test robustness

---

lib/sles4sap/ipaddr2.pm
t/22_ipaddr2.t
tests/sles4sap/ipaddr2/deploy.pm

Add function to validate the deployment in Azure.
Fix the IP range for the deployment VNET and SUBNET
- Related ticket: https://jira.suse.com/browse/TEAM-8721
sle-15-SP5-SapCloud-Azure-Payg-x86_64-BuildLATEST_AZURE_SLE15_5_PAYG-ipaddr2_azure_test@64bit
- http://openqaworker15.qa.suse.cz/tests/285000 :red_circle: sporadic failure
- http://openqaworker15.qa.suse.cz/tests/285002 :green_circle: 
- http://openqaworker15.qa.suse.cz/tests/285001 :green_circle:

Add ipaddr2 deployment sanity test

---

lib/bootloader_pvm.pm

Fix wrong entry in lib/bootloader_pvm.pm POD
- Needles: N/A

Fix wrong entry in lib/bootloader_pvm.pm POD

---

lib/qesapdeployment.pm

- Related ticket: https://bugzilla.suse.com/show_bug.cgi?id=1224249
- sle-15-SP5-Azure-SAP-BYOS-Incidents-x86_64-Build:33974:python3-SAPHanaSR-ScaleUp-PerfOpt@az_Standard_E8s_v3 -> http://openqaworker15.qa.suse.cz/tests/285074 :green_circle: upload works http://openqaworker15.qa.suse.cz/tests/285074/logfile?filename=deploy_qesap_ansible-hana0-zypper.log.txt
- sle-15-SP5-Qesap-Aws-Byos-x86_64-BuildLATEST_AWS_SLE15_5_BYOS-qesap_aws_fencing_native_test@64bit -> http://openqaworker15.qa.suse.cz/tests/285075 :green_circle:  http://openqaworker15.qa.suse.cz/tests/285075/logfile?filename=deploy-hana1-zypp.history.txt

Upload some zypper logs during qesap tests

---

tests/migration/online_migration/zypper_migration.pm

Reverts os-autoinst/os-autoinst-distri-opensuse#19403
I revert this PR, because the SLEM 5.2 MU patch 33772 and SLEM 5.3 MU patch 33773  are both released. And the PR#19403 caused new failures on SLEM 5.3 to SLEM 5.4 and SLEM 5.4 to SLEM 5.5 migration.
- Ticket: https://progress.opensuse.org/issues/161111
- https://openqa.suse.de/tests/14482436#step/zypper_migration/33 (slem5.2 to slem5.3 migration)
- https://openqa.suse.de/tests/14485759#step/zypper_migration/31 (slem5.3 to slem5.4 migration without PR#19403)
- https://openqa.suse.de/tests/14485760#step/zypper_migration/31 (slem5.4 to slem5.5 migration without PR#19403)

Revert "Add a workaround to enable wicked service"

---

lib/main_common.pm

firewall is not pre-installed in Cloud image.
- ticket: https://progress.opensuse.org/issues/156151
- Verification run: http://kepler.suse.cz/tests/23434#

Skip firewalld checks in Minimal-VM cloud image

---

tests/containers/bci_test.pm

Rely solemnly on the BCI_TEST_METADATA setting for selecting which BCI tests to run. This is needed because all is e.g. not expected to run for BCI repo tests.
- Verification run: https://openqa.suse.de/tests/14486416
- Merge together with https://gitlab.suse.de/qac/qac-openqa-yaml/-/merge_requests/1674 and https://gitlab.suse.de/qac/container-release-bot/-/merge_requests/252

Remove custom switches for all and metadata

---

lib/opensusebasetest.pm
tests/installation/setup_zdup.pm

https://progress.opensuse.org/issues/131312
- Patch the system before upgrade
- Handle boot from harddisk for aarch64
[leap to tw](https://openqa.opensuse.org/tests/overview?groupid=119&version=Tumbleweed&build=20240529&distri=opensuse)
PR to add the tests into job group: https://github.com/os-autoinst/opensuse-jobgroups/pull/471

Enable upgrade test from leap to tw on aarch64

---

lib/publiccloud/utils.pm

P.C. SL-Micro test actually perform **registration** using by default the `transactional-update` selected for transactionals while `registercloudguest` for other cases. 
Instead, for p.c. registrations _always_ the default shall be the `registercloudguest` command, refer to https://bugzilla.suse.com/show_bug.cgi?id=1224014 
- Related ticket: https://progress.opensuse.org/issues/161177
- Needles: N/A
- Verification run, all PASS ok:
cloned SLM test on master, using forced `PUBLIC_CLOUD_SCC_ENDPOINT=registercloudguest`:
- sle-micro-5.5-EC2-BYOS-Updates-aarch64-Build20240528-1-slem_basic @ec2_c6g.large
https://openqa.suse.de/tests/14481055#step/registration/17
cloned SLM on new code using by default `registercloudguest`:
- sle-micro-5.5-EC2-BYOS-Updates-aarch64-Build20240528-1-slem_basic …

P.C. SLM update shall use registercloudguest

---

lib/publiccloud/provider.pm
tests/publiccloud/storage_perf.pm

After  the publiccloud server renamed, we need to change all references in this repo too.
P.C. measures storage new server name  default is `larry.qe.suse.de`
- See plan in https://app.slack.com/client/T02863RC2AC

P.C. measures storage new server name

---

tests/containers/apptainer.pm

This PR:
- Reverts commit that changed serial terminal for console.  We want the serial terminal to check logs.
- Fixes the image used for apptainer test.  We were forcing Leap on a TW container!
- Sets **APPTAINER_TMPDIR** to avoid space issues with tmpfs
---
- Failing test: https://openqa.opensuse.org/tests/4227507#step/apptainer/42
- Related ticket: https://bugzilla.suse.com/show_bug.cgi?id=1225644
- Verification run: https://openqa.opensuse.org/tests/4243427

Fix apptainer space issues

---

tests/containers/docker_runc.pm
tests/containers/podman_network_cni.pm
tests/containers/podman_quadlet.pm
tests/containers/podman_remote.pm
tests/containers/registry.pm
tests/containers/seccomp.pm
tests/containers/testenv_prepare.pm

Use busybox image for simple tests where we're just sleeping or playing around.  The TW image is almost 10x larger.
Verifications runs:
- sle-15-SP5-Server-DVD-Updates-x86_64-Build20240602-1-docker_tests@64bit -> https://openqa.suse.de/t14507776
- sle-15-SP5-Server-DVD-Updates-x86_64-Build20240602-1-podman_tests@64bit -> https://openqa.suse.de/t14507794

containers: Use busybox instead of tumbleweed image

---

tests/containers/buildah_integration.pm
tests/containers/podman_integration.pm

Fix space issues in BATS tests
- Failing test: https://openqa.suse.de/tests/14506430
- sle-15-SP6-Server-DVD-Updates-x86_64-Build20240602-1-podman_testsuite@64bit -> https://openqa.suse.de/t14507861
- opensuse-Tumbleweed-DVD-x86_64-Build20240531-containers_host_buildah_testsuite@64bit -> https://openqa.opensuse.org/t4243602

containers: Cleanup after each run of BATS tests in buildah

---

tests/containers/podman_netavark.pm

Use httpd from registry mirror to fix netavark test
- Related ticket: https://progress.opensuse.org/issues/161276
- Verification run: https://openqa.suse.de/tests/14508114

containers: Use httpd from registry mirror to fix netavark

---

tests/yam/migration/setup_registration.pm

##
* https://progress.opensuse.org/issues/161231
- Related MR:
* https://gitlab.suse.de/qe-yam/openqa-job-groups/-/merge_requests/218
- Failed case:
* https://openqa.suse.de/tests/14504584#step/setup_registration/10
- Needles: 
* N/A
* https://openqa.suse.de/tests/14515615 15sp3 to 15sp4
* https://openqa.suse.de/tests/14515619 sles12sp5_15sp2
##

Remove release package from SCC_ADDONS_DROP

---

lib/virt_autotest/utils.pm
tests/virt_autotest/guest_installation_run.pm
tests/virt_autotest/guest_migration_src.pm
tests/virt_autotest/guest_upgrade_run.pm
tests/virt_autotest/host_upgrade_generate_run_file.pm
tests/virt_autotest/pvusb_run.pm
tests/virt_autotest/virt_v2v_dst.pm

* **Pass** SCC registration code for guest in to avoid security issue. 
* **Introduce** new options "-e" an "-E", which represent registration codes for product and its LTSS extension, to `tests/qa_test_virtualization/tools/test_virtualization-virt_install_withopt-run` script. 
* **Introduce** new options "-e" and "-E", which represent registration codes for product and its LTSS extension, to `libs/qa_lib_virtauto/qa_lib_virtauto/lib/virt-install.sh` for specific guest installation.
* **If** multiple guest patterns to be used, their corresponding registration codes should be provided in the same order and separated by pipe symbols. 
* **If** the new settings GUEST_SCC_REGCODE and GUEST_SCC_REGCODE_LTSS are not provided, host settings SCC_REGCODE and SCC_REGCODE_LTSS_15 will be used …

Pass SCC registration code in for guest installation instead of using plain ones

---

data/elemental/cloud-config.yaml
tests/elemental/installation.pm

On fast worker the OS can be restarted *after* checking for Grub, so better to delay the reboot command.
This commit also use `wait_boot` for installation to reduce the number of code lines.
- Needles: added live
- Verification runs: [aarch64](https://openqa.suse.de/tests/14518459), [x86_64](https://openqa.suse.de/tests/14517726)

Fix Elemental openQA test

---

lib/containers/urls.pm

Avoid registry mirror in 3rd party module.
- Verification runs (each arch and runtime is covered):
- opensuse-Tumbleweed-DVD-x86_64-Build20240604-containers_host_podman@64bit -> https://openqa.opensuse.org/t4251004
- opensuse-Tumbleweed-DVD-aarch64-Build20240604-containers_host_podman@aarch64 -> https://openqa.opensuse.org/t4251006
- sle-15-SP5-Server-DVD-Updates-s390x-Build20240604-1-docker_tests@s390x-kvm -> https://openqa.suse.de/t14531929
- sle-15-SP6-Online-ppc64le-Build92.1-docker_tests@ppc64le -> https://openqa.suse.de/t14534867

containers: Avoid registry mirror in 3rd party module

---

lib/sles4sap_publiccloud_basetest.pm
tests/sles4sap/publiccloud/qesap_cleanup.pm

This pr makes the cleanup face of the cloud deployment non-fatal, to avoid altering the result of the test in case of failure.
It also gets rid of the `post_run_hook` that was intended to be used in a single-module scenario, since we don't have such a scenario or plan to implement one.
- Related ticket: https://jira.suse.com/browse/TEAM-9015
- Verification run: http://openqaworker15.qa.suse.cz/tests/285566 (PASS)
Note: when the cleanup fails, the test is green, but no message is seen in the UI - the fail message gets printed to `autoinst.log` instead.
http://openqaworker15.qa.suse.cz/tests/285587 (CLEANUP FAIL AT THE END)

Make cleanup non-fatal

---

tests/console/check_os_release.pm

The test module `console/check_os_release` is used to verify the contents of `/etc/os-release` in Tumbleweed, Leap and SLES (and SLES for SAP Applications). Since Tumbleweed is a rolling release, instead of a version number, `/etc/os-release` has a date, which the test module gets from the BUILD setting to check for correctness. However, during verification runs, usually the value of the BUILD setting is replaced with something different, which can cause a verification run from an unrelated commit to fail on `console/check_os_release`. This commit checks that BUILD is a number and if it's not, it will skip the VERSION, VERSION_ID and CPE_NAME check in Tumbleweed. Leap and SLES code remains the same.
- Needles: N/A
**Verification runs:**
- [Tumbleweed, BUILD: …

Skip version check in Tumbleweed when BUILD setting is non-numeric

---

tests/console/opensuse_repos.pm

https://progress.opensuse.org/issues/161798
[VR](https://openqa.opensuse.org/tests/overview?version=15.5&distri=opensuse&build=rfan0607_repos_gpg)

Add "--gpg-auto-import-keys" option to install openSUSE-repos-NVIDIA

---

data/elemental/cloud-config.yaml
data/elemental/install.yaml
tests/elemental/installation.pm

Add support for Stable OS images of Elemental, based on SLE Micro 5.5.
- Related ticket: https://github.com/rancher/elemental/issues/1414
- Needles: https://gitlab.suse.de/openqa/os-autoinst-needles-sles/-/merge_requests/1665
- [aarch64 regression test](https://openqa.suse.de/tests/14531605)
- [x86_64 regression test](https://openqa.suse.de/tests/14531606)
- Validation of the new one done on my local lab (osd cannot be used for this test), see following screenshot.

Add support for Elemental based on SLE Micro 5.5

---

tests/containers/docker_runc.pm
tests/containers/podman_network_cni.pm
tests/containers/podman_quadlet.pm
tests/containers/podman_remote.pm
tests/containers/registry.pm
tests/containers/seccomp.pm
tests/containers/testenv_prepare.pm

See https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/19412.
The reason for the failures on TW was that busybox doesn't have error handling so it actually exited with 0 without printing anything. The reason it failed on SLE was because SLE uses runc which fails before busybox even gets to run. Just use the TW image again.
VR: https://openqa.opensuse.org/tests/4250591#live

Reapply "containers: Use busybox instead of tumbleweed image"

---

tests/publiccloud/prepare_tools.pm

Due to migration to python311 package was renamed
Tools image creation VR - http://autobot.qe.nue2.suse.org/tests/4356
img_proof which is using created qcow -  http://autobot.qe.nue2.suse.org/tests/4358

Follow upstream changes in package name

---

lib/sles4sap_publiccloud_basetest.pm
tests/sles4sap/publiccloud/qesap_cleanup.pm

Reverts os-autoinst/os-autoinst-distri-opensuse#19455 because it makes IBSm deployment fail https://openqa.suse.de/tests/14538613#step/network_peering/72

Revert "Make cleanup non-fatal"

---

lib/sles4sap.pm
schedule/sles4sap/hana/saptune_on_pvm.yaml
tests/sles4sap/saptune/mr_test_run.pm

We run saptune 'notes' and 'solutions' on power9 lpar. So we need a add a yaml file to define the test modules.
There are some changes on saptune test, such as on power platform, the default value of `transparent_hugepage` is changed to 'madvise'. So we need to adjust our code to check that.
Related: https://jira.suse.com/browse/TEAM-9086
VRs: 
solutions on Power9: https://openqa.suse.de/tests/14527132# (Pass)
notes on Power9:       https://openqa.suse.de/tests/14527124# (Pass)
sles4sap_gnome_saptune_baremeta (x86) : https://openqa.suse.de/tests/14527098# (Pass)
delete_rename (ppc64): https://openqa.suse.de/tests/14527138#  (Pass)
delete_rename (uefi):  https://openqa.suse.de/tests/14527137# (Pass)
gnome_saptune_solutions (uefi): https://openqa.suse.de/tests/14527136# (Pass) …

Adjust the saptune test on power9

---

tests/ha/hawk_gui.pm

The `ha/hawk_gui` test module uses a python+selenium test packaged in a docker/podman container to ensure all required dependencies are installed. Early versions of the module would install a fixed docker version downloaded from download.docker.com, which will then be used to download the docker image and run the container, but starting on 15-SP6, this old version of docker clashes with the cgroups configuration of the base 15-SP6 system, preventing the container from running. This commit switches the docker commands for podman, as the latter is supported by SUSE and we can always get the latest version using `zypper in`. These changes also mean that HAWK client tests need to run from a system where podman can be installed (i.e., repositories where podman package is available are already …

Use podman instead of docker in hawk_gui test module

---

tests/elemental/installation.pm

Aarch64 worker can be slower than x86_64 one, so we need to add a small wait before connecting to the serial console.
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/14542880

Fix Elemental boot on aarch64

---

schedule/sles4sap/saptune_on_pvm.yaml

The saptune yaml files are under `sles4sap`, I put it in the wrong directory in PR#19460, so correct it.

Move saptune_on_pvm yaml schedule file to correct place

---

tests/wsl/enable_systemd.pm

YaST firstboot check for enabling the systemd feature won't be available in openSUSE versions, so the wiki has been updated to show the installing process.
Nevertheless, there's a new cleaner and smoother way of enabling systemd by installing a zypper pattern rather than writing in config files, so we should enable the feature this way: 
https://en.opensuse.org/openSUSE:WSL#Enabling_systemd
- Related ticket: https://progress.opensuse.org/issues/156814
Version: 15-SP6 / Flavor: Windows 10 BIOS: https://openqa.suse.de/tests/14541449#
Version: 15-SP6 / Flavor: Windows 10 UEFI: https://openqa.suse.de/tests/14541450#
Version: 15-SP6 / Flavor: Windows 11 UEFI: https://openqa.suse.de/tests/14541451#
Tumbleweed Win 10 BIOS: https://openqa.opensuse.org/tests/4255480# …

Wsl systemd

---

tests/yam/migration/setup_registration.pm

Reverts os-autoinst/os-autoinst-distri-opensuse#19443
The PR introcuded problems in migration from SP2 to [SP3](https://openqa.suse.de/tests/14546428#step/setup_registration/18) and [SP4](https://openqa.suse.de/tests/14546472#step/setup_registration/18).

Revert "Remove release package from SCC_ADDONS_DROP"

---

lib/utils.pm
tests/qam-updinstall/update_install.pm

```
Updates can have multiple patches, the idea is to test each patch separately. After patch rollback to state after full system patch and run another patch.
- export reboot_and_login, run after fully_patch_system if reboot is needed, after patch, not at the end of test, and after snapper rollback
- return zypper return code in fully_patch_system to know if reboot is needed
- no need to disable update repos, rollback snapshot has repos disabled
```
- Related ticket: https://progress.opensuse.org/issues/161855
- Verification run: https://dzedro.suse.cz/tests/1112#step/update_install/775
https://openqa.suse.de/tests/14551103 x86_64
https://openqa.suse.de/tests/14551104 s390x
https://openqa.suse.de/tests/14551105 ppc64le
https://openqa.suse.de/tests/14551109 aarch64 …

Use snapper rollback to get to state before patch

---

README.md

The new name is based on a brainstorming conducted within a SUSE Slack
conversation with vote. The most promising alternatives had been:
* arepa
* osdo
* oto

Define new name for the project *osado*

---

tests/yam/migration/setup_registration.pm

##
- Related ticket: https://progress.opensuse.org/issues/161231
- Needles: N/A
- https://openqa.suse.de/t14549743 sles15sp2_sp4
- https://openqa.suse.de/t14549744  sles15sp2_sp3
- https://openqa.suse.de/tests/14549752 sles15sp3_sp4

Quick fix for SUSEConnect -d

---

lib/publiccloud/instance.pm
lib/publiccloud/provider.pm

MinimalVM team does not require boot time measurements of their images. Removing this execution path we can save relatively significant runtime and mostly we get rid of expected failures as connection to Larry should not work in these tests.
- ticket: [MinimalVM ltp test trying to connect publiccloud-ng](https://progress.opensuse.org/issues/161081)
- Verification run: http://kepler.suse.cz/tests/23444#step/prepare_openstack/191

OpenStack:Remove boot time measurements

---

lib/main_micro_alp.pm

cloud-init is supported in sl-micro from now on, we need to fix the test module schedule that would align MinimalVM's
- Verification run: http://kepler.suse.cz/tests/23453#
- https://gitlab.suse.de/qac/qac-openqa-yaml/-/merge_requests/1684

Fix cloud-init schedule for sl-micro

---

lib/services/users.pm

The shortcut for changing password is not alt-p in latest TW 
So, use assert_and_click to avoid shortcut inconsistency 
Add assert_and_click "focus-name-field" to make test more robust
- Related ticket: https://progress.opensuse.org/issues/161045
- Needles: already added when debugging on o3 and osd
> TW Wayland https://openqa.opensuse.org/tests/4255499
> TW X11 https://openqa.opensuse.org/tests/4255305
> 15SP6 X11 https://openqa.suse.de/tests/14515832
> 15SP6 Wayland https://openqa.suse.de/tests/14525364

Fix change_password failure on TW

---

lib/version_utils.pm
tests/microos/disk_boot.pm

Adds the Default-Updated to the images where a grub timeout is expected to be disabled.
Also introduce the is_micro catch-all routine to simplify further checks of this and similar kinds.
- Related ticket: https://progress.opensuse.org/issues/160796
- Related failure: https://openqa.suse.de/tests/14554334#step/disk_boot/4
- Verification run: [aarch64](https://openqa.suse.de/tests/14564455) | [x86_64](https://openqa.suse.de/tests/14564452)

Add 'Default' to images with disabled grub timeout

---

tests/containers/podman_integration.pm

The `go` dependency was mistakenly dropped in https://github.com/os-autoinst/os-autoinst-distri-opensuse/commit/6153d0db18d14ce1440518bc6a7cc446bc344b01#diff-2632f5646811893cee7686c9813898d85d387aa047c6f2116fa75b8807e46953L55 
- sle-15-SP5-Server-DVD-Updates-x86_64-Build20240609-1-podman_testsuite@64bit -> https://openqa.suse.de/t14565709 (failing for other reason)
- sle-15-SP5-Server-DVD-Updates-aarch64-Build20240609-1-podman_testsuite@aarch64-virtio -> https://openqa.suse.de/t14565710 (ditto above)

containers: Add missing go dependency to podman upstream tests

---

tests/publiccloud/prepare_tools.pm

temporary workaround to hotfix bug in latest version 
VR - http://autobot.qe.nue2.suse.org/tests/4372 ( image creation ) 
VR2- http://autobot.qe.nue2.suse.org/tests/4373 ( use of image , certain test failure is expected )

Add workaround needed for latest version

---

lib/qesapdeployment.pm
t/09_qesapdeployment.t

This commit adds support for the keyword `latest` in `QESAP_INSTALL_VERSION`, along with explicit version number.
It uses the github api to fetch the latest release tag, and downloads it.
- Related ticket: https://jira.suse.com/browse/TEAM-8830
- Verification run: EXPLICIT VERSION (expected to fail, latest os-autoinst master won't work in qesap_regression with qesapdeployment version <0.26.0): https://openqaworker15.qa.suse.cz/tests/285991
USING LATEST KEYWORD: https://openqaworker15.qa.suse.cz/tests/285990#step/configure/83

Add support for latest deployment release

---

tests/qemu/qemu.pm

The module incorectly assumed that leap and sle have different naming schemes.
- Related ticket:  https://progress.opensuse.org/issues/162032
- Verification run: [SLEM 5.4 & 6.0](https://openqa.suse.de/tests/overview?distri=sle-micro&build=apappas_micro6_qemu) [Leap Micro 6 - aarch64](https://openqa.opensuse.org/tests/4261398) [Leap Micro 6 - x86](https://openqa.opensuse.org/tests/4261472)

Fix condtition for qemu pattern name

---

tests/containers/bci_prepare.pm
tests/containers/bci_test.pm

Adds virtualenv for the BCI test environment to prevent overwriting system packages.
- Related ticket: https://progress.opensuse.org/issues/158976
- Verification runs: [Generate Image](https://openqa.suse.de/tests/14569151) | [BCI test run](https://openqa.suse.de/tests/14569424)
Merge together with https://gitlab.suse.de/qac/qac-openqa-yaml/-/merge_requests/1688

Add virtualenv

---

variables.md

Adds a description for BCI_VIRTUALENV.
Follow-up of https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/19499

Add BCI_VIRTUALENV

---

data/autoyast_qam/15_installtest.xml.ep

It is required for package dependencies
0f749e4d01ff49efcadfb4786cbb6bf68720a099
- Related ticket: https://openqa.suse.de/tests/overview?build=%3A33467%3Aphp7&groupid=310 php failing only on HA because of missing sle-module-web-scripting repo

Add back repos to HA image

---

lib/publiccloud/gce.pm
lib/publiccloud/instance.pm
lib/publiccloud/provider.pm

In recent P.C. GCE preprare_instance issue (poo#161384) the post fail hook `cleanup` routine didn't provided the serial/console log instance_serial.txt because the instance-id resulted empty, no more available at that exit point, and get-serial-port-output command failed.
Here that `id` is retrieved in a different way, used where expected link was empty.
In wait-ssh a timeout parameter added to decrease the default value, for debugging purpose, but it could still be useful in future needs.
See in test Logs available the file "<modulename>-instance_serial.txt" log
- Related ticket: https://progress.opensuse.org/issues/161732
- Needles: N/A
-  https://openqa.suse.de/tests/14523157#step/prepare_instance/90
FAIL due to GCE issue, 
but the **instance_id is present** on …

P.C. GCE cleanup fix to upload log on errors

---

tests/publiccloud/img_proof.pm

After image fixed in [poo#156763](https://progress.opensuse.org/issues/156763#note-11), removing soft failure on ssh-rsa.
- Related ticket: https://progress.opensuse.org/issues/156763
- Verification run: TBD see PR body

PC img_proof fixed then removing soft failure 

---

tests/security/luks2/unlock_luks2_vol_tpm2.pm
tests/security/tpm2/tpm2_env_setup.pm

Likely the test was passing only on some worker class due to a different worker configuration or speed. 
This change introduces a more reliable and logical operations workflow, and workaround a permission denied on `/dev/tpm*` devices.
- Related ticket: https://progress.opensuse.org/issues/161300
- https://openqa.suse.de/tests/14601422
- https://openqa.suse.de/tests/14601423
- https://openqa.suse.de/tests/14601424

Enroll TPM2 key after ramdisk modification

---

lib/kdump_utils.pm

Tested for https://bugzilla.suse.com/show_bug.cgi?id=1224464

Support CRASH_MEMORY on yast2 kdump

---

data/containers/bats_skip_notok.py
lib/containers/bats.pm
tests/containers/aardvark_integration.pm
tests/containers/buildah_integration.pm
tests/containers/netavark_integration.pm
tests/containers/podman_integration.pm
tests/containers/runc_integration.pm
tests/containers/skopeo_integration.pm

We don't want to skip any BATS tests, just ignore the failures.  We have the problem that some skipped tests may pass and we're unknowingly skipping them.
This PR:
- Patches the TAP file generated by the `bats` command to comment the `not ok` lines for the "skipped" tests defined in BATS_SKIP variables.
- Warns us that we're skipping a test that is passing.
Implementation details:
- The Python program implements a state machine to parse and patch a TAP file like https://openqa.opensuse.org/tests/4268394/file/podman_integration-bats-user-local.tap
- opensuse-Tumbleweed-DVD-x86_64-Build20240612-containers_host_podman_testsuite@64bit -> https://openqa.opensuse.org/tests/4272333 (failing for other reasons, `.tap` files should have `#not ok` lines). This test is also telling …

containers: Ignore but not skip BATS tests

---

tests/publiccloud/ssh_interactive_end.pm

Hotfix for mr_test after https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/19453
Related ticket: https://progress.opensuse.org/issues/161732
- sle-15-SP2-GCE-SAP-BYOS-Incidents-saptune-x86_64-Build:34087:rpmlint-sles4sap_gnome_saptune_delete_rename@gce_n1_highmem_8 -> http://openqaworker15.qa.suse.cz/tests/286299
- sle-15-SP6-Azure-SAP-BYOS-x86_64-Build0531-sles4sap_gnome_saptune_delete_rename@az_Standard_E8s_v3 -> http://openqaworker15.qa.suse.cz/tests/286300

Do not call cleanup in ssh_interactive_end

---

tests/containers/bci_test.pm

When trying to run bci_test from a different repo/branch than origin/main, the command `git fetch && git reset --hard origin` fails, as previously a single branch defined in BCI_TESTS_BRANCH has been cloned. This is solved by removing the `origin` from the command
- http://10.146.5.131/tests/102#step/bci_test_podman/11
- http://10.146.5.131/tests/104#
- http://10.146.5.131/tests/105#
- http://10.146.5.131/tests/106
- http://10.146.5.131/tests/107#

Update BCI-Tests repo from non-main branch

---

tests/containers/buildah_integration.pm

Temporarily revert https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/19514 only for buildah.  Most of the skipped tests fail due to `no space left on device` errors.  We need to figure out a way to assign more disk space only for these tests.
Failing test: https://openqa.opensuse.org/tests/4273289
Verification run: https://openqa.opensuse.org/tests/4273805

containers: Run podman cleanup on buildah upstream tests

---

tests/containers/podman_integration.pm

Now that we don't skip tests we need to increase timeout.
Failed test: https://openqa.suse.de/tests/14626555#step/podman_integration/160

containers: Increase timeout for podman upstream tests

---

lib/main_common.pm

This test only works on btrfs, so check for that directly.
This makes it easier to also skip the module on RISC-V, which can't use btrfs in images ATM.
To not break the OpenStack-Cloud test, that medium type needs to have `FILESYSTEM=xfs` set now.
- Verification run: https://openqa.opensuse.org/tests/4270455#live

lib/main_common.pm: Run jeos/diskusage based on FILESYSTEM not FLAVOR

---

lib/LTP/utils.pm
tests/kernel/boot_ltp.pm
tests/kernel/install_ltp.pm
tests/kernel/shutdown_ltp.pm

Baremetal LTP tests cannot detect kernel oops message on serial console, unlike QEMU tests. Check kernel taint procfile for taint flags before running tests.
- Needles: N/A
- boot_ltp, tainted: https://openqa.suse.de/tests/14618689#step/boot_ltp/113
- install_ltp, tainted: https://openqa.suse.de/tests/14618691#step/install_ltp/245
- livepatches, not tainted: https://openqa.suse.de/tests/14618690#step/boot_ltp/116

Check kernel taint before and after running LTP tests

---

lib/containers/bats.pm
tests/containers/aardvark_integration.pm
tests/containers/buildah_integration.pm
tests/containers/netavark_integration.pm
tests/containers/podman_integration.pm
tests/containers/runc_integration.pm
tests/containers/skopeo_integration.pm

This PR:
- Removes unneeded backup of tests directory.
- Fixes space issues with buildah tests.
- Setups BATS_TMPDIR to avoid tmpfs /tmp
- opensuse-Tumbleweed-DVD-x86_64-Build20240613-containers_host_buildah_testsuite@64bit -> https://openqa.opensuse.org/tests/4275638
- opensuse-Tumbleweed-DVD-x86_64-Build20240613-containers_host_podman_testsuite@64bit -> https://openqa.opensuse.org/tests/4275640 (failing for other reasons)

Minor fixes to BATS tests

---

lib/x11utils.pm

Both lockscreen and display timeouts are now configured with drop-down menus which need a click more to open.
- Related ticket: https://openqa.opensuse.org/tests/4276709#step/updates_packagekit_kde/8
- Needles: Created on o3 for the VR
- Verification run: https://openqa.opensuse.org/tests/4276815

lib/x11utils.pm: Handle drop-down menus in Plasma 6.1 settings

---

lib/publiccloud/azure.pm
lib/publiccloud/ec2.pm
lib/publiccloud/gce.pm
lib/publiccloud/provider.pm

P.C. `get_terraform_output` shall return empty on jq null
P.C. serial logs skipped for SAP, after PR#19519
- Related ticket: https://progress.opensuse.org/issues/161732
- Verification run: see body PR

P.C. get instance empty and skip serial log SAP

---

tests/kernel/shutdown_ltp.pm

Some archs have third-party modules which trigger additional taint flags. Some tests also load unsigned modules. Switch post-test taint check to softfail until we decide how to handle these issues properly.
- Needles: N/A
- PPC64LE: https://openqa.suse.de/tests/14655810
- s390x: https://openqa.suse.de/tests/14655866

shutdown_ltp: Softfail on taint

---

tests/security/tpm2/tpm2_env_setup.pm

The udev rules we installed during test debug were not needed, so we can remove them
- Related ticket: https://progress.opensuse.org/issues/161300
- Needles: no
- https://openqa.suse.de/tests/14641906
- https://openqa.suse.de/tests/14641907
- https://openqa.suse.de/tests/14641908

Remove udev rules workaround for TPM devices

---

.github/workflows/checklist.yml
.github/workflows/ci-isotovideo.yml
.github/workflows/ci.yml
.github/workflows/deploy.yml
.github/workflows/openqa.yml
.github/workflows/shellcheck.yml
.github/workflows/trufflehog.yml

As GitHub moves from node 16 to node 20 checkout v3 is deprecated.

Update checkout action to v4

---

tests/publiccloud/transfer_repos.pm

Adds `EXCLUDED_TEST_REPO` variable to list incidents excluded from transfer repos
- Related ticket: https://progress.opensuse.org/issues/152883
VR:  https://openqa.suse.de/tests/14662090
https://openqa.suse.de/tests/14662096

Allow exclude incidents while transfering repos to PC

---

lib/sles4sap/ipaddr2.pm
t/22_ipaddr2.t
tests/sles4sap/ipaddr2/configure.pm

Add test step to check that bastion VM is reachable to its public IP and that ssh connection is allowed
- Related ticket: https://jira.suse.com/browse/TEAM-9467
- sle-15-SP5-SapCloud-Azure-Payg-x86_64-Buildmpagot_VR-ipaddr2_azure_test@64bit -> http://openqaworker15.qa.suse.cz/tests/286561

IpAddr2 test: ssh to bastion

---

schedule/yast/qam-yast_self_update_view_development.yaml
schedule/yast/sle/flows/default_sle15sp6_x86_view_development.yaml

Add schedule files to add module to uncheck hided development modules.
- Related ticket: https://progress.opensuse.org/issues/160700
- Related MR: https://gitlab.suse.de/qe-yam/openqa-job-groups/-/merge_requests/231
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/overview?build=lemon-suse%2Fos-autoinst-distri-opensuse%23check-out-hide-development-module&version=15-SP6&distri=sle

Uncheck hide development modules

---

lib/containers/urls.pm

Drop Debian & Ubuntu (which we were only testing on x86_64 anyway).  CentOS is deprecated.
- Related ticket: https://progress.opensuse.org/issues/162482

containers: Drop some 3rd party images, use GHCR for alpine

---

lib/main_ltp.pm

Enhancement poo#162502: We need to test maintenance staging updates
for SL Micro. There is already existing test module
transactional/install_update, which adds repositories and installs
updates. Module is included in main_ltp and will be scheduled on
transactional system and staging FLAVOR.
Job group configuration: https://gitlab.suse.de/kernel-qa/kernelqa-openqa-yaml/-/merge_requests/529
- Related ticket: https://progress.opensuse.org/issues/162509
- Needles: never
- Verification run: https://openqa.suse.de/tests/14679848

kernel: Add support for maintenance staging updates

---

data/containers/docker-compose.yml
tests/containers/compose.pm

Use our own nginx & haproxy images.  Remove dependency on registry mirror.  We should drink our own champagne.
- Related ticket: https://progress.opensuse.org/issues/162530
- Failing test: https://openqa.opensuse.org/tests/4282546
- Verification run: https://openqa.opensuse.org/tests/4283066

containers: Use our own nginx & haproxy images

---

tests/console/arping.pm

Fixes: 10f13dbef ("console: Add simple arping tests")
- http://quasar.suse.cz/tests/3500#step/arping/72
- http://quasar.suse.cz/tests/3501#step/arping/72

console/arping: Add missing record_info()

---

tests/xfstests/run.pm

We got error in generate_report.pm if both XFSTESTS_SOFTFAIL and XFSTESTS_KNOWN_ISSUES are set. Fix it by resolving conflict.
- Related ticket: https://progress.opensuse.org/issues/162566
- Needles: N/A
http://10.67.133.133/tests/662 (both XFSTESTS_SOFTFAT and XFSTESTS_KNOWN_ISSUES are set)
http://10.67.133.133/tests/663 (only XFSTESTS_KNOWN_ISSUES)

xfstests: fix generate_report issue

---

lib/main_containers.pm

The checks are redundant as we schedule these tests from YAML.  We only need to restrict the `aardvark-dns` test to Tumbleweed.  This clears the way to adding the tests for 15-SP3 that got podman 4.9.5 (and soon 15-SP2).
Verification runs: Not needed.

containers: Remove redundant platform checks for BATS tests

---

tests/installation/ipxe_install.pm
variables.md

Some workers need more than 2 minutes to reach PXE bootloader after power-on. Add a variable `PXE_BOOT_TIME` to control the bootscript switch delay for UEFI machines so that it can be configured on each worker.
This is the correct solution for #17769
- Needles: N/A
- without `PXE_BOOT_TIME`: https://openqa.suse.de/tests/12223015
- with `PXE_BOOT_TIME`: https://openqa.suse.de/tests/12223016
- without `AUTOYAST`: https://openqa.suse.de/tests/12223020

ipxe_install: Make the set_bootscript_hdd() delay configurable

---

lib/qesapdeployment.pm
t/15_qesap_azure.t
tests/sles4sap/publiccloud/qesap_terraform.pm

Add a setting HANA_TOKEN_PERMISSION to allow to change SAS token permission used to get HANA during the qe-sap-deployment. Enforce permission validation to only allow l and r.
- Related ticket: https://jira.suse.com/browse/TEAM-9453
qesap regression test does not have setting to change permission
- sle-15-SP5-Qesap-Azure-Byos-x86_64-BuildLATEST_AZURE_SLE15_5_BYOS-qesap_azure_ibsmirror_peering_test@64bit -> http://openqaworker15.qa.suse.cz/tests/286693 :green_circle:  has `r` as expected http://openqaworker15.qa.suse.cz/tests/286693#step/configure/68
Triggered with  HANA_TOKEN_PERMISSION=rl . Check that setting for HanaSR does not have effect on qesap regression test
- sle-15-SP5-Qesap-Azure-Byos-x86_64-BuildLATEST_AZURE_SLE15_5_BYOS-qesap_azure_ibsmirror_peering_test@64bit -> …

Allow HanaSR tests to specify token permission

---

schedule/ha/bv/basic_cluster_node.yaml
schedule/ha/bv/ha_supportserver.yaml
tests/support_server/clear_leases.pm

This introduces into the basic HA cluster schedules:
- `schedule/ha/bv/basic_cluster_node.yaml`
- `schedule/ha/bv/ha_supportserver.yaml`
Support to use them to publish the qcow2 images after the cluster jobs finish, by adding the CREATE_HDD=1 setting in the jobs.
Also included in the commit is the a new module for the support server to clear the lease database from the DHCP server, as this would allow the migration jobs which run from the generated qcow2 to get the same IP addresses as the ones using during qcow2 creation without needing to fix the macaddresses of the SUTs.
**Note:** only tested in x86_64 so far, but I expect it to work in aarch64 and ppc64le with `qemu` backends. There is the possibility that these schedules are not fully compatible for `svirt` backend, but I believe we …

Add support to publish qcow2 images on HA cluster schedules

---

tests/qam-updinstall/update_install.pm

```
mpich_4_0_2-gnu-hpc-macros-devel-4.0.2-150500.3.2.1.s390x conflicts with 'namespace:otherproviders(mpich-hpc-macros-devel)' provided by the to be installed mpich-ofi_4_0_2-gnu-hpc-macros-devel-4.0.2-150500.3.2.1.s390x
https://build.suse.de/projects/SUSE:SLE-15-SP6:GA/packages/mpich/files/mpich.spec?expand=1
Provides:       %{pname}-hpc-macros-devel = %{version}
Conflicts:      otherproviders(%{pname}-hpc-macros-devel)
openmpi4-config-4.1.4-150500.3.2.1.s390x conflicts with 'namespace:otherproviders(pmix-runtime-config)' provided by the to be installed pmix-mca-params-3.2.3-150300.3.10.1.noarch
https://build.suse.de/projects/SUSE:SLE-15:GA/packages/openmpi/files/openmpi.spec?expand=1
Provides:       %{pname}-runtime-config = %{version}
Conflicts: …
```

update_install: Add new mpich-hpc-macros-devel conflict

---

tests/kernel/install_ltp.pm

Enhancement poo#162659: We need to support LTP installation on Full medium without SCC registration. Needed repositories are already added by installation, but they are disabled by default. We just need to enable them.
- Related ticket: https://progress.opensuse.org/issues/162659
Full-QR:  https://openqa.suse.de/tests/14702024#step/install_ltp/45
Online-QR (as example on non full flavor): https://openqa.suse.de/tests/14701996

ltp: Enable repositories on Full installation medium

---

tests/jeos/firstrun.pm

A jeos-firstboot version supporting this feature landed in SLFO, so handle it the same way it's handled in TW.
Also move the unless block further down as the "please register" dialog actually is shown before.
- Related ticket: https://progress.opensuse.org/issues/162656
- Needles: added via Web UI
- Verification run (on 6.1): https://openqa.suse.de/tests/14694718
I tried to do a verification run on 6.0 as well, but I think the assets are not there anymore (or perhaps they got renamed? :thinking: )
I don't have enough privileges to do a run on Tumbleweed.

jeos: firstrun: handle SSH enrollment dialog on SL Micro 6.1 (poo#162656)

---

schedule/storage/nfs.yaml

For baremetal we don't want to run a support server, but we need the barriers. We can create them with a conditional schedule for the NFS server job.
- Related ticket: https://progress.opensuse.org/issues/138089
- Needles: -
nfs_support_server: https://openqa.suse.de/tests/14703624
nfs_client: https://openqa.suse.de/tests/14703623
nfs_server: https://openqa.suse.de/tests/14703622

Add barrier creation to NFS server job if IPXE=1

---

tests/sles4sap/ensa/netweaver_ensa2_cluster.pm

When need to enter in cluster maintenance mode, only execute crm command to do it in one and let the cluster propagate the info. cluster node.
- Related ticket: TEAM-9471
- sle-15-SP5-Server-DVD-SAP-Incidents-x86_64-Build:33600:aws-cli-sles4sap_ensa_supportserver@64bit-4gbram -> http://openqaworker15.qa.suse.cz/tests/286772
- sle-15-SP5-Server-DVD-SAP-Incidents-x86_64-Build:33600:aws-cli-sles4sap_ensa_ascs_node@64bit-sap -> http://openqaworker15.qa.suse.cz/tests/286771
- sle-15-SP5-Server-DVD-SAP-Incidents-x86_64-Build:33600:aws-cli-sles4sap_ensa_ers_node@64bit-sap -> http://openqaworker15.qa.suse.cz/tests/286770

ENSA2 test set maintenance from one node

---

data/autoyast_sle15/create_hdd/create_hdd_gnome_allpatterns_aarch64.xml
data/autoyast_sle15/create_hdd/create_hdd_gnome_sdk_allpatterns_aarch64.xml
data/yam/autoyast/autoyast_pcm_lgm_allpatterns_ppc64le.xml.ep
data/yam/autoyast/create_hdd_gnome_allpatterns_aarch64.xml
data/yam/autoyast/create_hdd_gnome_sdk_allpatterns_aarch64.xml
data/yam/autoyast/support_images/create_hdd_hpc_development_node_aarch64.xml.ep
data/yam/autoyast/support_images/create_hdd_hpc_development_node_x86_64.xml.ep
data/yam/autoyast/support_images/create_hdd_hpc_management_server_aarch64.xml.ep
data/yam/autoyast/support_images/create_hdd_hpc_textmode_aarch64.xml.ep
data/yam/autoyast/support_images/create_hdd_hpc_textmode_x86_64.xml.ep
data/yam/autoyast/support_images/sles15sp4_install_gnome_all_patterns_aarch64.xml
data/yam/autoyast/support_images/sles15sp4_install_gnome_all_patterns_x86_64.xml
data/yam/autoyast/support_images/sles15sp4_install_textmode_all_patterns_aarch64.xml
data/yam/autoyast/support_images/sles15sp4_install_textmode_all_patterns_x86_64.xml
data/yam/autoyast/support_images/sles15sp5_install_gnome_all_patterns_aarch64.xml
data/yam/autoyast/support_images/sles15sp5_install_gnome_all_patterns_x86_64.xml
data/yam/autoyast/support_images/sles15sp5_install_textmode_all_patterns_aarch64.xml
data/yam/autoyast/support_images/sles15sp5_install_textmode_all_patterns_x86_64.xml
lib/utils.pm

Remove wsl_base, wsl_gui and wsl_systemd patterns from autoyast profiles for support images. Based on bsc#1226314, we don't set wsl environment in migration testing, so we don't add these patterns.
- Related ticket: https://progress.opensuse.org/issues/162677
- Needles: n/a
- https://openqa.suse.de/tests/14714416# (x86_64: support image of parent)
- https://openqa.suse.de/tests/14714448# (x86_64: support image of child)
- https://openqa.suse.de/tests/14714578# (x86_64: migration job to verify support image)
- https://openqa.suse.de/tests/14714402# (aarch64: support image of parent)
- https://openqa.suse.de/tests/14714451# (aarch64: support image of child)
- https://openqa.suse.de/tests/14714452# (aarch64: migration job to verify support image)
- Related mr: …

Remove wsl patterns from autoyast profiles for support images

---

lib/guest_installation_and_configuration_base.pm
lib/hacluster.pm
lib/qam.pm
lib/sles4sap.pm
lib/utils.pm
lib/virt_autotest/utils.pm
lib/y2_base.pm
lib/y2snapper_common.pm
tests/virt_autotest/reboot_and_wait_up_upgrade.pm

```
save_y2logs is failing occasionally due to 'file changed as we read it'
- move upload_y2logs from virt_autotest::utils to utils, it's generic function
- use script_retry instead assert_script_run or script_run
- use tar.xz compression by default, today it's available on all versions
- file and compression can be defined via file argument
- use script_retry in collect_guest_installation_logs_via_ssh
```
- Related ticket: https://progress.opensuse.org/issues/162581
- Verification run: https://openqa.suse.de/tests/overview?distri=sle&build=jpupava_y2logs failures were triggered to  export logs
https://openqa.suse.de/tests/14690726#step/ha_cluster_join/22 lib/hacluster
https://openqa.suse.de/tests/14702026#step/patterns/27 lib/sles4sap …

Move, unify upload_y2logs and add retry

---

lib/security/openssl_fips_hash_common.pm
schedule/security/fips_crypt_core.yaml
tests/fips/openssl/openssl_1_1_fips_hash.pm

- Related ticket: https://progress.opensuse.org/issues/159780
- Needles: no
- https://openqa.suse.de/tests/14718572
- https://openqa.suse.de/tests/14718565
- https://openqa.suse.de/tests/14718553
- https://openqa.suse.de/tests/14718554

Refactor openssl FIPS hash tests to be generic

---

lib/main_containers.pm
tests/containers/podman_integration.pm

Some packages are not available on some versions of SLEM.
I checked the available packages with `podman run --rm ghcr.io/ricardobranco777/susepkg -p any $package`
- Related ticket: https://progress.opensuse.org/issues/162164
- SLEM-5.1 aarch64: https://openqa.suse.de/t14718805
- SLEM-5.1 x86_64: https://openqa.suse.de/t14718804
- SLEM-5.2 aarch64: https://openqa.suse.de/t14718811
- SLEM-5.2 x86_64: https://openqa.suse.de/t14718810
- SLEM-5.3 aarch64: https://openqa.suse.de/t14718809
- SLEM-5.3 x86_64: https://openqa.suse.de/t14718808
- SLEM-5.4 aarch64: https://openqa.suse.de/t14718807
- SLEM-5.4 x86_64: https://openqa.suse.de/t14718806
NOTE: All jobs will fail due to not-yet skipped subtests. These jobs are for harvesting them to add them to SKIP variables.

containers: Fixes for BATS tests on SLEM < 5.5

---

lib/security/openssl_fips_hash_common.pm

Followup from https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/19590, a small fix on the library header

Tidy library import section

---

schedule/yast/maintenance/create_hdd_maintenance_deregistered.yaml
tests/yam/migration/setup_registration.pm

##
Now we are adding a  intermidiate case to deregister the production for the follow up  maintenance updates migration test cases and publish a deregisted qcow file. 
- Related ticket:  
-  https://progress.opensuse.org/issues/161231
- Related MR:
- [**MR_236**](https://gitlab.suse.de/qe-yam/openqa-job-groups/-/merge_requests/236)
- Needles: 
- N/A
-  create_hdd_migr_maintenance_desktop_dev
- https://openqa.suse.de/tests/14715101
- migr_sles15sp3_sp4_dev
-  https://openqa.suse.de/tests/14715106
- 12sp5->15spx regression test:
- https://openqa.suse.de/t14715262
- https://openqa.suse.de/t14715263
- https://openqa.suse.de/t14715264

Add deregistration case for MU migration tests

---

lib/sles4sap/azure_cli.pm
lib/sles4sap/ipaddr2.pm
t/21_sles4sap_azure_cli.t
t/22_ipaddr2.t
tests/sles4sap/ipaddr2/configure.pm
tests/sles4sap/ipaddr2/deploy.pm
tests/sles4sap/ipaddr2/sanity.pm

Add some code to collect the diagnostic logs from any VM in the resource group. Add it to some of the post fail hook of the ipaddr2 test.
- Related ticket: https://jira.suse.com/browse/TEAM-8721
sle-15-SP5-SapCloud-Azure-Payg-x86_64-Buildmpagot_VR-ipaddr2_azure_test@64bit 
- http://openqaworker15.qa.suse.cz/tests/287030  with a simulated failure --> http://openqaworker15.qa.suse.cz/tests/287030#step/configure/28 the log
- http://openqaworker15.qa.suse.cz/tests/286951  with a simulated failure and without the setting

Add az diagnostic log collection

---

data/containers/nginx.conf
tests/containers/podman_netavark.pm

Use our own nginx instead of DockerHub's httpd to avoid rate-limit issues.
- Related ticket: https://progress.opensuse.org/issues/162638
- SLEM-5.1 x86_64: https://openqa.suse.de/tests/14728572

containers: Use our own nginx instead of dockerhub httpd

---

tests/containers/kubectl.pm

Use own busybox image instead of DockerHub images
- opensuse-Tumbleweed-DVD-x86_64-Build20240624-containers_host_kubectl@64bit -> https://openqa.opensuse.org/t4298767

containers: Use own busybox image instead of DockerHub images

---

lib/main_containers.pm
tests/containers/podman_remote.pm

This PR adds a test for the availability of the `podman-remote` package.  We [missed](https://bugzilla.suse.com/show_bug.cgi?id=1224050) it in SLEM 6.0 and [again](https://bugzilla.suse.com/show_bug.cgi?id=1226596) with SLES 15-SP3 with the podman 4.9.x update.  There is a planned podman update for SLES 15-SP2 and we need to catch this failure.
Current list of SUSE products with `podman-remote` (edited for brevity):
```
$ podman run --rm ghcr.io/ricardobranco777/susepkg -p any podman-remote
[...]
SL-Micro/6.0 podman-remote 4.9.3-1.3
SLE-Micro/5.5 podman-remote 4.9.5-150500.3.12.1
SLES/15.4 podman-remote 4.9.5-150400.4.27.1
SLES/15.5 podman-remote 4.9.5-150500.3.12.1
SLES/15.6 podman-remote 4.9.5-150500.3.12.1
[...]
```
- Related ticket: https://progress.opensuse.org/issues/162788
- …

containers: Add test for podman-remote package

---

tests/yast2_gui/yast2_instserver.pm

Apply workaround for needle 'yast2-instserver-nfs'
- Verification run: https://openqa.suse.de/tests/14736977#step/yast2_instserver/39

Apply workaround for needle 'yast2-instserver-nfs'

---

lib/virt_autotest/common.pm

MU- Change guest list to the required guest list for kvm and xen on each host product.
- Related ticket: https://progress.opensuse.org/issues/162434
SLES15-SP6 KVM - http://openqa.qam.suse.cz/tests/76235#step/waitfor_guests/68
SLES15-SP6 XEN - http://openqa.qam.suse.cz/tests/76251#step/waitfor_guests/102
SLES15-SP5 KVM - http://openqa.qam.suse.cz/tests/76288#step/waitfor_guests/90
SLES15-SP5 XEN - http://openqa.qam.suse.cz/tests/76300#step/waitfor_guests/210
SLES 15-SP4 KVM - http://openqa.qam.suse.cz/tests/76377#step/waitfor_guests/66
SLES 15-SP4 XEN - http://openqa.qam.suse.cz/tests/76364#step/waitfor_guests/70

Change guest list to the required guest list for kvm and xen 

---

data/virt_autotest/host_unattended_installation_files/autoyast/dev_host_12.xml.ep
data/virt_autotest/host_unattended_installation_files/autoyast/dev_host_15.xml.ep
lib/ipmi_backend_utils.pm
tests/virt_autotest/login_console.pm
tests/virt_autotest/update_package.pm

- Set serial console kernel options for EFI boot on XEN in grub2 files on EFI partition(`/boot/efi/efi/xen-*.cfg`)
- Disable secure boot. Disable secure boot in BIOS and autoyast template for both sle15 and sle12sp5. Though autoyast guild for sle12sp5 does not  say it supports disable secure boot, but actually it does.
- Set EFI partition for UEFI boot on both sle15 and sle12 autoyast templates
- Upload EFI xen grub configuration files
- Not update packages for registered sles on x86
Related ticket: https://progress.opensuse.org/issues/153037
- `vh082`:
[sle12sp5_xen_autoyast](http://10.67.129.27/tests/403)
[sle15sp6_kvm_full_feature_autoyast](http://10.67.129.27/tests/387)
[sle15sp5_kvm_UEFI_non-autoayst](http://10.67.129.27/tests/397) …

Set xen serial console kernel options for EFI boot

---

lib/sles4sap/azure_cli.pm
lib/sles4sap/ipaddr2.pm
t/21_sles4sap_azure_cli.t
t/22_ipaddr2.t
tests/sles4sap/ipaddr2/configure.pm

Add ipaddr2_os_connectivity_sanity method
Make query optional in az_vm_list with default to NAME 
Add verbosity each time is using StrictHostKeyChecking=accept-new
sle-15-SP5-SapCloud-Azure-Payg-x86_64-Buildmpagot_VR-ipaddr2_azure_test@64bit
- http://openqaworker15.qa.suse.cz/tests/287110
- http://openqaworker15.qa.suse.cz/tests/287117
- http://openqaworker15.qa.suse.cz/tests/287112 :green_circle:

Add connectivity sanity check in ipaddr2 test

---

tests/containers/podman_remote.pm

The `podman-remote` package is not available in Staging:
https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/19602#issuecomment-2192202709
- Failing test: https://openqa.opensuse.org/tests/4302018#step/podman_remote/59
- Verification run: Not needed.

containers: Skip podman-remote package test on Staging

---

tests/containers/podman_remote.pm

Do not check_reboot_changes if package was not installed
Failing test: https://openqa.suse.de/tests/14740400#step/podman_remote/59
Verification run: https://openqa.suse.de/tests/14744057

containers: Do not check_reboot_changes if package was not installed

---

lib/autoyast.pm

Fix poo#162917: Function get_var is mapped to get_required_var in autoyast library. It is impossible to check if variable exists autoyast templates. Mapping of get_var is fixed and new get_required_var was introduced.
It was introduced in https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/6251, unfortunately  PR doesn't contain any explanation or justification for such change.
- Related ticket: https://progress.opensuse.org/issues/162917
- Needles:  none
Maintenance AY installation: https://openqa.suse.de/tests/14744051
Job which was previously failing and is fixed: https://openqa.suse.de/tests/14738025

autoyast: Fix mapping of get_var function in template library

---

tests/containers/podman_remote.pm

On transactional systems we must do `select_console "user-console"` like we do in other modules.
- Related ticket: https://progress.opensuse.org/issues/162923
- Failing test: https://openqa.suse.de/tests/14744149/modules/podman_remote/steps/75
- Verification run: https://openqa.suse.de/tests/14744673

containers: Use select_console for transactional systems

---

schedule/security/fips_crypt_libica.yaml
tests/fips/libica.pm
tests/fips/libica_upstream_testsuite.pm

We enable the smoke test to run, this is needed to have an evidence and submit a proper bug report.
- Related ticket: https://progress.opensuse.org/issues/162437
- Needles: no
- Verification run:  https://openqa.suse.de/tests/14744724 
(the VR is supposed to fail because the test highlights a product bug)

Reorder libica tests, with smoke as first one

---

tests/xfstests/generate_report.pm
tests/xfstests/run.pm
tests/xfstests/xfstests_failed.pm

Implement LTP whitelist lookup in xfstests report generator. Properly match whitelist entries according to test environment and show failure description in the report.
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/14737587

xfstests: Implement LTP whitelist properly

---

tests/sles4sap/ipaddr2/configure.pm
tests/sles4sap/ipaddr2/deploy.pm
tests/sles4sap/ipaddr2/sanity.pm
tests/sles4sap/ipaddr2/test.pm

Add multi_module flag in ipaddr2 test to avoid PC baseclass to call destroy and log collection procedure at the end of each test module.
Related ticket: https://jira.suse.com/browse/TEAM-9428
- sle-15-SP5-SapCloud-Azure-Byos-x86_64-BuildLATEST_AZURE_SLE15_5_BYOS-ipaddr2_azure_test@64bit -> http://openqaworker15.qa.suse.cz/tests/287219

Add publiccloud_multi_module flag

---

lib/sles4sap/ipaddr2.pm
tests/sles4sap/ipaddr2/sanity.pm

Add some sanity test before to start manipulating the cluster.
Related ticket: https://jira.suse.com/browse/TEAM-9428
- sle-15-SP5-SapCloud-Azure-Byos-x86_64-BuildLATEST_AZURE_SLE15_5_BYOS-ipaddr2_azure_test@64bit -> http://openqaworker15.qa.suse.cz/tests/287229

Add os_sanity check to the Ipaddr2 test

---

tests/qam-updinstall/update_install.pm

```
%package sdt-devel
Summary:        Static probe support tools
Group:          Development/Tools/Debuggers
Requires:       %{name} = %{version}-%{release}
Conflicts:      systemtap-headers
```
- Related ticket: https://openqa.suse.de/tests/14761883#step/update_install/132
- Verification run: https://dzedro.suse.cz/tests/1175

update_install: Add systemtap-sdt-devel conflict

---

lib/services/registered_addons.pm

##
The subpacakge unregistered status is by design and comes from how we introduced subpackages repository to Package Hub.
- https://progress.opensuse.org/issues/158736
- Needles: 
- N/A
- https://openqa.suse.de/tests/14736660
##

Remove soft failure bsc#1176901

---

tests/console/yast2_lan_device_settings.pm

Change record_soft_failure to record_info.  
According https://bugzilla.suse.com/show_bug.cgi?id=1115644#c75, this is not one issue. Change the soft_failure to record_info.
- Related ticket: https://progress.opensuse.org/issues/158748
- Verification run: https://openqa.suse.de/tests/14776071

Change record_soft_failure to record_info

---

tests/sles4sap/wizard_hana_install.pm

there is different directory for hana_partitioning*.xml on 12-SP5 with 15+, this PR makes wizard_hana_install.pm work on both of 12-SP5 and 15+
- Related ticket: https://jira.suse.com/browse/TEAM-9454
- Needles: null
- Verification run: https://openqa.suse.de/tests/14770655#step/wizard_hana_install/2

Make wizard_hana_install.pm deal with hana_partitioning*.xml files on 12-SP5

---

data/autoyast_sle15/autoyast_no_scc_reg_full.xml.ep
schedule/kernel/ay_prepare_baremetal.yaml

Enhancement poo#162710: We need to test bare metal on maintenance Full-QR flavor. It must be tested without SCC registration from openQA assets. This profile has registration disabled and add repositories from MIRROR_HTTP variable. It sets graphical target based on DESKTOP variable. Installed patterns can be configured by PATTERNS.
Variable AY_INSTALLATION_DRIVE_DEVICE allows to specify installation disk. It is mainly intended for bare metal servers with multiple devices. 
PR also includes new schedule for autoyast installation on bare metal for kernel testing.
- Related ticket: https://progress.opensuse.org/issues/162710
- Verification run:  https://openqa.suse.de/tests/overview?build=testdev9&version=15-SP5&groupid=472&distri=sle

Add AY profile without SCC registration for Full medium

---

lib/main_micro_alp.pm
lib/main_security.pm

This is a proposal, feel free to reject.
What this tries to address is:
- Eliminate the logic of booting all kind of images/archs in the yaml (that logic is already part of main_micro_alp.pm)
- Eliminate the logic to check if we need to install updates or not, which would make the yaml schedule more complex. This is already addressed in main_micro_alp.pm
VRs:
- https://openqa.suse.de/tests/14727666
- https://openqa.suse.de/tests/14727665
- https://openqa.suse.de/tests/14727673
- https://openqa.suse.de/tests/14727674 (the failure here needs investigation, not produced by this PR)

Create main_security schedule

---

data/yam/autoyast/autoupgrade_with_maintenance_unreleased_updates.xml.ep
data/yam/autoyast/support_images/sles12sp5_install_with_scc_addons_x86_64.xml.ep
schedule/yast/maintenance/autoupgrade_sles12sp5_to_sles15spx_maintenance.yaml
tests/migration/prepare_maintenance_repos.pm
tests/migration/prepare_scc_addons.pm

Add a testsuite to generate the support image of SLES12SP5 via autoyast installation; 
Add upgrade autoyast profile and yaml schedule files for migration from maintenance update released to maintenance update unreleased testsuites; 
To make the job add target product's maintenance update repos, reset the SCC_ADDONS values because the modules names of SLES12SP5 and SLES15SP5 are different, and there's a blessed modules which would be added during migration fron 12SP5 to 15SPx.
- Related ticket: https://progress.opensuse.org/issues/154951
- Needles: n/a
- Verification run: [publish support image](https://openqa.suse.de/tests/14698146#); [migrate to 15SP6 + MU](https://openqa.suse.de/tests/14786768#)
- Related mr: https://gitlab.suse.de/qe-yam/openqa-job-groups/-/merge_requests/235

Upgrade SLES12SP5 MU released to SLES15SP6 MU unreleased

---

data/autoyast_sle15/autoyast_no_scc_reg_full.xml.ep

Fix poo@163145: Bare metal servers have issue with grub in graphical terminal mode during the boot. We need to set terminal to serial in autoyast profile to properly display grub menu in IPMI console.
- Related ticket: https://progress.opensuse.org/issues/163145
aarch64  unarmed: https://openqa.suse.de/tests/14798662#step/handle_reboot/2
x86_64 worf: https://openqa.suse.de/tests/14798629#step/handle_reboot/2
x86_64 tyrion: https://openqa.suse.de/tests/14798631#step/handle_reboot/2

Switch booltoader to terminal in autoyast profile for full medium

---

lib/sles4sap/azure_cli.pm
lib/sles4sap/ipaddr2.pm
t/21_sles4sap_azure_cli.t
t/22_ipaddr2.t

Add waiting function at the end of the deployment.
- sle-15-SP5-SapCloud-Azure-Byos-x86_64-BuildLATEST_AZURE_SLE15_5_BYOS-ipaddr2_azure_test@64bit -> http://openqaworker15.qa.suse.cz/tests/287686

Ipaddr2 test deployment wait VM to run

---

tests/installation/ipxe_install.pm

Enhancement poo#162170: We need the option to disable installer auto update for maintenance QR release testing.
- Related ticket: https://progress.opensuse.org/issues/162170
worf:  https://openqa.suse.de/tests/14798809
tyrion: https://openqa.suse.de/tests/14798811

ipxe: Add option to disable installer auto update

---

lib/containers/urls.pm

This PR:
- Adds official CentOS Stream 9 image to list of 3rd party images.
- Re-adds some 3rd party images removed due to issues with previous registry mirror.
- microos-Tumbleweed-DVD-x86_64-Build20240701-container-host@64bit -> https://openqa.opensuse.org/tests/4314446
- microos-Tumbleweed-DVD-aarch64-Build20240701-container-host@aarch64-4G-HD40G -> https://openqa.opensuse.org/t4314448
- sle-15-SP6-Server-DVD-Updates-s390x-Build20240702-1-podman_tests@s390x-kvm -> https://openqa.suse.de/t14800811

containers: Add centos:stream9 to list of 3rd party images

---

lib/registration.pm

##
- Related ticket: https://progress.opensuse.org/issues/154726
- Needles: N/A
- [**VR**](https://openqa.suse.de/tests/overview?distri=sle&build=hjluo%2Fos-autoinst-distri-opensuse%23revert_suseconnect-ng&version=15-SP6)

Revert suseconnect-ng fix for s390x

---

tests/xfstests/generate_report.pm
tests/xfstests/run.pm
tests/xfstests/xfstests_failed.pm

Ignore whitelist if bugzilla closed
- Related ticket: https://progress.opensuse.org/issues/162920
- Needles: N/A
http://10.67.133.133/tests/697 (no bugzilla entry in whitelist)
http://10.67.133.133/tests/701 (bugzilla not closed)
http://10.67.133.133/tests/700 (bugzilla closed)
http://10.67.133.133/tests/698 (Failed to query bugzilla ticket)
http://10.67.133.133/tests/703 (keep_fail=1)

xfstests: check bugzilla status with whitelist entries

---

lib/containers/urls.pm

Avoid `Fatal glibc error: CPU does not support x86-64-v2`
Failing test: https://openqa.suse.de/tests/14804906#step/docker_3rd_party_images/285

containers: Disable centos image test

---

lib/sles4sap/azure_cli.pm
lib/sles4sap/cloud_zypper_patch.pm
schedule/sles4sap/cloud-components/cloud_zypper_patch.yml
t/21_sles4sap_azure_cli.t
t/25_cloud_zypper_patch.t
tests/sles4sap/cloud_zypper_patch/add_repo.pm
tests/sles4sap/cloud_zypper_patch/deploy.pm
tests/sles4sap/cloud_zypper_patch/destroy.pm
tests/sles4sap/cloud_zypper_patch/network_peering.pm
tests/sles4sap/cloud_zypper_patch/zypper_patch.pm

New test sequence and relative test modules. Aim of this one is to be minimal, require few time and reduced set of cloud resources.
Test sequence:
1. create a VM on the cloud,
2. network peering to the IBSm
3. add repos
4. run zypper patch.
To give a scale of times:
- this test takes **7min 30sec** and cost **€0.01**
- qesap regression (without netpeering and add repo) **50min**
- hanasr (without netpeering and add repo) **2h 20min**
Related ticket : https://jira.suse.com/browse/TEAM-9492
http://openqaworker15.qa.suse.cz/tests/287324

New test sequence for zypper patch on cloud

---

lib/qesapdeployment.pm
t/09_qesapdeployment.t

Add sleep to fix "Missing sudo password" on GCP
Add sleep to fix ansible ssh "Missing sudo password" issue on GCP VM.
[TEAM-9480](https://jira.suse.com/browse/TEAM-9480) - [timeboxed] "Missing sudo password" sporadically prevent any ansible connection to GCP VM
NOTE-1: checked OSD and OW15 only found this issue on "qesap-regression-latest" job group:
12-SP5 GCP PAYG + BYOS: not found this sporadic issue ATM
15-SP6 GCP PAYG + BYOS: were not triggered in OW15 "qesap-regression-latest" job group.
15-SP5 GCP PAYG + BYOS: found this sporadic issue
15-SP4 GCP PAYG + BYOS: found this sporadic issue
15-SP3 GCP PAYG + BYOS: found this sporadic issue
15-SP2 GCP PAYG + BYOS were not triggered in OW15 "qesap-regression-latest" job group.
NOTE-2:
Using `sleep 30` still can find this sporadic issue so …

Add sleep to fix "Missing sudo password" on GCP

---

tests/qam-updinstall/update_install.pm

When testing any patch that rebuilds openssh, openqa fails only when testing in s390x (like in https://openqa.suse.de/tests/14804700). This happens because the test installs all packages that are part of the patch (which includes openssh-server-config-disallow-rootlogin, even if that package is never installed automatically) to test that the system can reboot successfully afterwards. The problem is that in s390x, after a reboot, openqa needs to ssh to the system to reconnect the tty, which now fails because that package disallows root to do a ssh password login.
Make sure that openssh-server-config-disallow-rootlogin is not installed since in s390 we need to ssh to the system to reconnect to the tty after a reboot.
Note that I haven't tested this patch, since I don't have a personal …

Remove openssh-server-config-disallow-rootlogin before a reboot in s390x

---

lib/wickedbase.pm

If there are coredumps, but not related to wicked, we should not fail in before_test module.
- Failed job: https://openqa.opensuse.org/tests/3705475#step/before_test/44
- Verification run: https://openqa.opensuse.org/tests/3705628

wicked: handle coredump of unknown source

---

data/autoyast_opensuse/autoyast_wicked_x86_64.xml.ep

I was missing `ping` on a fresh installed LEAP 15.5 with that autoyast profile. Also make wicked as default network backend.
- Verification run: http://openqa.wicked.suse.de/tests/219962

wicked: add iputils and backend=wicked to opensuse autoyast profile

---

data/virt_autotest/guest_params_xml_files/sles_15_sp6_64_kvm_hvm_sev_es_x86_64.xml
data/virt_autotest/guest_params_xml_files/sles_15_sp6_64_kvm_hvm_uefi_with_power_management_x86_64.xml
data/virt_autotest/guest_params_xml_files/sles_15_sp6_64_kvm_hvm_uefi_without_power_management_x86_64_using_virtmanagerlt3.0.0.xml
data/virt_autotest/guest_params_xml_files/sles_15_sp6_64_xen_hvm_uefi_with_power_management_x86_64.xml
data/virt_autotest/guest_params_xml_files/sles_15_sp6_64_xen_hvm_uefi_without_power_management_x86_64_using_virtmanagerlt3.0.0.xml
data/virt_autotest/guest_params_xml_files/slm_6_1_64_kvm_hvm_x86_64_default_encrypted_ignition+combustion.xml
data/virt_autotest/guest_params_xml_files/slm_6_1_64_kvm_hvm_x86_64_default_encrypted_ignition.xml
data/virt_autotest/guest_params_xml_files/slm_6_1_64_kvm_hvm_x86_64_default_qcow_ignition+combustion.xml
data/virt_autotest/guest_params_xml_files/slm_6_1_64_kvm_hvm_x86_64_default_qcow_ignition.xml
data/virt_autotest/guest_params_xml_files/slm_6_1_64_kvm_hvm_x86_64_default_raw_ignition+combustion.xml
data/virt_autotest/guest_params_xml_files/slm_6_1_64_kvm_hvm_x86_64_default_raw_ignition.xml

* **Add** profiles for SL Micro 6.1 guests, including default-encrypted, default-raw and default-qcow, which are installed by using ignition or ignition+combustion.
* **Also** update profiles for SLE 15-SP6 guests which already passed GM. 
* [15sp6 on SL Micro 6.1](https://openqa.suse.de/tests/14736796)
* [SL Micro 6.1 on SL Micro 6.1](https://openqa.suse.de/tests/14736870)

Add guests profiles for SL Micro 6.1 tests

---

lib/LTP/utils.pm

Link: https://progress.opensuse.org/issues/152849
Verification run: https://openqa.opensuse.org/tests/overview?build=risc-v-ltp

LTP: Add support for risc-v Tumbleweed repository

---

tests/kernel/install_ltp.pm

Argument "Full-QR" isn't numeric in numeric eq (==) at tests/kernel/install_ltp.pm line 334.
Fixes: e85ccfcae ("ltp: Enable repositories on Full installation medium")
Verification run: https://openqa.suse.de/tests/overview?build=ltp-fix-warning

LTP: Fix comparison warning

---

data/journal_check/bug_refs.json

* **Error** of missing disks should be ignored with SL Micro 6.1 as well. Otherwise this error will be reported in [journal_check](https://openqa.suse.de/tests/14784025#step/journal_check/10).
* [test run](https://openqa.suse.de/tests/14822049)

Ignore error of missing disks with SL Micro 6.1

---

tests/sles4sap/wizard_hana_install.pm

run HANA SPS05rev59(59.05) on 12-SP5 and there is an issue like this https://openqa.suse.de/tests/14810638#step/wizard_hana_install/41, so I create this PR for the workaround and mark the openQA job with the issue as `softfail`
- Related ticket: https://jira.suse.com/browse/TEAM-9454
- Needles: https://openqa.suse.de/tests/14801402#step/wizard_hana_install/41
https://openqa.suse.de/tests/14810638 (12-SP5)
https://openqa.suse.de/tests/14810637 (15-SP2)
https://openqa.suse.de/tests/14810640 (15-SP5)

Workaround for sap-installation-wizard not finding HANA 32-bit client

---

lib/wickedbase.pm

In the coredumpctl version of SLE-12-SP5 there is no -q argument.
Fixup: https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/18127
https://openqa.suse.de/t14848126 - qam-wicked_basic_sut@cfconrad/os-autoinst-distri-opensuse#fixup_pr_18127 => passed
https://openqa.suse.de/t14848125 - qam-wicked_basic_ref@cfconrad/os-autoinst-distri-opensuse#fixup_pr_18127 => passed
8054 scheduled jobs (2444 blocked by other jobs) (0 with priority < 10, 0 with priority == 10)
https://openqa.suse.de/t14848147 - wicked_basic_ref@cfconrad/os-autoinst-distri-opensuse#fixup_pr_18127 => passed
https://openqa.suse.de/t14848148 - wicked_basic_sut@cfconrad/os-autoinst-distri-opensuse#fixup_pr_18127 => passed

wicked: fix coredumpctl call for SLE-12-SP5

---

data/yam/autoyast/raid_encrypted_home_x86_64.xml.ep
schedule/yast/autoyast_raid_encrypted_home.yaml

Add testsuite of raid_encrypted_home to YaST group.
- Related ticket: https://progress.opensuse.org/issues/163313
- Needles: n/a
- Verification run: [YaST MU job](https://openqa.suse.de/tests/14837453#step/repos/5); [YaST group job](https://openqa.suse.de/tests/14846852#step/repos/7)
- Related mr: https://gitlab.suse.de/qe-yam/openqa-job-groups/-/merge_requests/255

Add testsuite of raid_encrypted_home

---

tests/installation/partitioning.pm

This change address the new CC install step asking for a device encryption passphrase.
- Related ticket: https://progress.opensuse.org/issues/160892
- Needles: https://gitlab.suse.de/openqa/os-autoinst-needles-sles/-/commit/60485bac65a535d8a615ffe54e526bd71f57f935
- https://openqa.suse.de/tests/14846869#step/partitioning/1
- https://openqa.suse.de/tests/14846870#step/partitioning/1
- https://openqa.suse.de/tests/14846871#step/partitioning/1
- https://openqa.suse.de/tests/14846872#step/partitioning/1
note: the VR fails in a later step due to [bsc#1227456](https://bugzilla.suse.com/show_bug.cgi?id=1227456), this PR will just make the install forward enough so the bug is more evident

Add device encryption passphrase for Common Criteria

---

schedule/storage/nfs.yaml

This reverts commit e889a29dac06d1379019d1d95c4cef24c5613e66.
This schedule won't work like that - let's revert it and add a dedicated schedule for baremetal NFS

Revert "Add barrier creation to NFS server job if IPXE=1"

---

tests/installation/partitioning.pm

this is a fix for a regression introduced with #19683 
- Related ticket: https://progress.opensuse.org/issues/160892
- Needles: no
- 15SP6: https://openqa.suse.de/tests/14859471#step/partitioning/1, https://openqa.suse.de/tests/14860281#step/partitioning/1
- 15SP5: https://openqa.suse.de/tests/14859473#step/partitioning/1
- 15SP4: https://openqa.suse.de/tests/14859472#step/partitioning/1
- 15SP3: https://openqa.suse.de/tests/14860282#step/partitioning/1

Handle common criteria install message for SLE < 15SP6

---

lib/main_containers.pm
tests/fips/fips_setup.pm

`patterns-microos-fips` is being used for sle-micro from 5.1 to 5.5.
Fips setup tests should look for this pattern instead of plain `fips`
As a technical debt caused by the split of responsibilities of sle-micro
testing. We have a wrong schedule of modules. firewalld is not present
in older sle-micro deployments done by the installator
- Related ticket: https://progress.opensuse.org/issues/163325
- sle-micro-5.5-DVD-Updates-x86_64-Build20240708-1-slem_installation_docker@64bit -> https://openqa.suse.de/tests/14862649#
- sle-micro-5.5-Default-Updates-x86_64-Build20240708-1-slem_fips_docker@64bit -> https://openqa.suse.de/tests/14860280

First fix slem updates

---

schedule/security/create_hdd_cc_libyui/cc_qr_s390x_15SP4.yaml

Under s390x arch, the 15SP4 install requires an extra step
- Related ticket: https://progress.opensuse.org/issues/162584
- Needles: n/a
- https://openqa.suse.de/tests/14863510 
- https://openqa.suse.de/tests/14862201 
- https://openqa.suse.de/tests/14863511     
- https://openqa.suse.de/tests/14863642

Add step to select SLES product only on 15SP4

---

lib/main_containers.pm
tests/containers/podman_netavark.pm

Do not schedule skopeo test module for older sle-micro's than 5.5
- sle-micro-5.4-Default-Updates-x86_64-Build20240708-1-slem_docker@64bit -> https://openqa.suse.de/tests/14863457
- sle-micro-5.5-Default-Updates-x86_64-Build20240708-1-slem_podman_testsuite@64bit -> https://openqa.suse.de/tests/14863503
- sle-micro-5.5-Default-Updates-x86_64-Build20240708-1-slem_docker@64bit -> https://openqa.suse.de/tests/14863508
- sle-micro-5.5-Default-Updates-x86_64-Build20240708-1-slem_podman@64bit -> https://openqa.suse.de/tests/14863515
- sle-micro-5.1-DVD-Updates-x86_64-Build20240708-1-slem_installation_podman@64bit -> https://openqa.suse.de/tests/14863976

Skip skopeo in slem older than 5.5 

---

tests/containers/podman_netavark.pm

Tests were switching back to CNI in fresh install scenarios in slem 5.5

Fix netavark cleanup for slem 5.5

---

tests/fips/fips_setup.pm

Non-transactional systems were attempting to execute `tr-up`.
- Verification run: https://openqa.suse.de/tests/14872006

Fips setup installation fix

---

lib/sles4sap_publiccloud.pm
t/12_sles4sap_publicccloud.t

SPN tests seem to take a longer time for nodes to come back up during `crash_` modules, so this replaces the fixed sleep with a function that waits until `is_system_running` returns.
- Related ticket: https://jira.suse.com/browse/TEAM-9215
https://openqa.suse.de/tests/14822488
https://openqa.suse.de/tests/14826409
https://openqa.suse.de/tests/14826533
sbd example: https://openqa.suse.de/tests/14859429

Replace sleep with system-up checks 

---

lib/qesapdeployment.pm
lib/sles4sap_publiccloud.pm
t/12_sles4sap_publicccloud.t
t/15_qesap_azure.t
tests/sles4sap/publiccloud/qesap_terraform.pm

Move PTF to a dedicated container. So it means it used it's own short live token and different folder structure.
Related ticket: https://jira.suse.com/browse/TEAM-9453
- AZURE http://openqaworker15.qa.suse.cz/tests/288522 :green_circle:   http://openqaworker15.qa.suse.cz/tests/288576
- AWS http://openqaworker15.qa.suse.cz/tests/288529 :green_circle:  fails later after the HANA installation, to SAS token mechanism works
-  AZURE http://openqaworker15.qa.suse.cz/tests/288531 :green_circle:  fails in Ansible but in `TASK [Install additional Python packages]` It is after the task about PTF installation.
-  AWS http://openqaworker15.qa.suse.cz/tests/288530 :green_circle:  PTF installation is fine http://openqaworker15.qa.suse.cz/tests/288530/logfile?filename=deploy_qesap_ansible-ansible.ptf_ins …

Move PTF test to a dedicated container

---

tests/containers/bci_test.pm

When restarting the job the HEAD is behind the main BCI-tests remote repository. Here is a restarted failed test runs -> [15-SP3-ltss image](https://openqa.suse.de/tests/14863860#step/bci_test_docker/21), [15-SP5-kernel-devel-module](https://openqa.suse.de/tests/14858108#step/bci_test_docker/21) even after a fix was provided. 
Verification run: [15-SP3-ltss](https://openqa.suse.de/tests/14864409#step/bci_test_docker/21), [15-SP5-kernel-devel-module](https://openqa.suse.de/tests/14863801#step/bci_test_docker/21)

When restarting the job the HEAD is behind the main BCI remote repository

---

tests/jeos/firstrun.pm

Use flavor instead of `ENCRYPTED_IMAGE=1`.
- ticket: https://progress.opensuse.org/issues/163448
- needle: https://gitlab.suse.de/openqa/os-autoinst-needles-sles/-/merge_requests/1666
* [sle-micro-6.0-Default-encrypted-x86_64-Build10.23-slem_k3s@uefi](http://kepler.suse.cz/tests/23645#step/firstrun/12)
* [sle-micro-6.1-Base-encrypted-x86_64-Build3.12-default@uefi-virtio-vga](http://kepler.suse.cz/tests/23648#step/firstrun/12)
* [microos](http://kepler.suse.cz/tests/23637#step/firstrun/8)
* [15sp6](http://kepler.suse.cz/tests/23647#step/firstrun/9)

Check flavor to enable encryption handling

---

tests/jeos/firstrun.pm

aarch64 MicroOS raw images can be booted in RPi. That means only `qcow2` images are using gpt table.
- Verification run: https://openqa.suse.de/tests/14885753#live

RPi uses msdos instead of gpt

---

lib/virt_autotest/utils.pm
lib/virt_autotest/virtual_network_utils.pm

- Not involve `virtproxyd` daemon as it is not installed on modular libvirt. Related ticket: https://progress.opensuse.org/issues/162881
- fix failure https://10.145.10.207/tests/14798677#step/sriov_network_card_pci_passthrough/208
[gi-guest_sles12sp5-on-host_developing-xen](http://openqa.suse.de/tests/14809044)
[uefi-gi-guest_developing-on-host_developing-xen](https://10.145.10.207/tests/14809046)
[prj4_guest_upgrade_sles15sp5_on_sles15sp5-kvm](https://10.145.10.207/tests/14809047)
[prj2_host_upgrade_sles12sp5_to_developing_kvm](https://10.145.10.207/tests/14809045)
[fix_network_test_failure_in_sriov_test](https://10.145.10.207/tests/14800754#step/sriov_network_card_pci_passthrough/208)
[another_sriov_pass_on_quinn](https://10.145.10.207/tests/14809046#step/sriov_networ …

No touching virtproxyd daemon as it is not installed on modular libvirt

---

tests/hpc/ww4.pm

Enhancement poo#163454: This improvement will check warewulf shell functionality. It will also validate repositories inside container.
- Related ticket: https://progress.opensuse.org/issues/163454
VR with expected failure: https://openqa.suse.de/tests/14850566#step/ww4/143
VR without fail: https://openqa.suse.de/tests/14892476#step/ww4/143

hpc: Add repository refresh to warewulf-container

---

lib/main_common.pm
lib/virt_autotest/virtual_network_utils.pm

1. Check Hypervisor:
Proceed only if HOST_HYPERVISOR is set to xen, kvm, or qemu.
2. Host Installation:
If ENABLE_HOST_INSTALLATION is 1:
Use AutoYaST if AUTOYAST is set, loading corresponding tests.
Otherwise, perform unattended installation with a detailed set of steps.
3. VM Installation:
If ENABLE_VM_INSTALL is 1:
Load tests for console login, preparing and waiting for guests.
If PATCH_WITH_ZYPPER is 1:
Load patch and reboot tests based on UPDATE_PACKAGE.
4. SR-IOV Network Card PCI Passthrough:
If ENABLE_SRIOV_NETWORK_CARD_PCI_PASSTHROUGH and SLE version is >15, load relevant tests.
5. Other function Tests (unless UPDATE_PACKAGE is kernel-default or ENABLE_SRIOV_NETWORK_CARD_PCI_PASSTHROUGH is 1):
Load tests for:
> * Save and Restore (ENABLE_SAVE_AND_RESTORE is 1)
> * Guest Management …

Combine host/guest installation and feature testsuites into one testsuite and move schedule logic into main.pm

---

tests/containers/rootless_podman.pm

Distro upgrade scenario has a left over configuration in `/etc/containers/storage.conf`. The default configuration is provided by `libcontainers-common` and other tests are using this config file.
- ticket: https://progress.opensuse.org/issues/163616
- Verification run: http://kepler.suse.cz/tests/23651#step/rootless_podman/1

Use default container storage configure

---

tests/qam-updinstall/update_install.pm

followup bc228ea1084b5c59e7834382d342f77771df484c
VR: https://openqa.suse.de/tests/14911266

update_install: Add nvidia aarch64 conflicts

---

tests/jeos/firstrun.pm

TBD
- opensuse-Tumbleweed-JeOS-for-AArch64-arm-Build20240711-jeos@aarch32-HD20G -> https://openqa.opensuse.org/tests/4339385#step/firstrun/72
- opensuse-Tumbleweed-JeOS-for-AArch64-aarch64-Build20240711-jeos@aarch64-HD20G -> https://openqa.opensuse.org/tests/4336110#step/firstrun/72

Differ partition table in community images

---

data/yam/autoyast/sles15sp5_gnome_unregistered_no_self_update.xml.ep

VRs: https://openqa.suse.de/tests/overview?distri=sle&version=15-SP5&build=20240711-1&groupid=431
This commit removes `xorg-x11-Xvnc` from `data/yam/autoyast/sles15sp5_gnome_unregistered_no_self_update.xml.ep`

Remove xorg-x11-Xvnc from autoyast file

---

tests/console/sysstat.pm

From sysstat.changes:
* [Quan quan Cao]: sar/sadc: Add new metrics pgprom/s and pgdem/s.
* sar: Remove %vmeff metric.
- Related ticket: https://progress.opensuse.org/issues/162194
- Verification run: https://openqa.opensuse.org/tests/4342953

console/sysstat.pm: Support for sysstat 12.7.5

---

tests/console/gpg.pm

- Related ticket: https://progress.opensuse.org/issues/163358
- Needles: Already created on o3 for the VR
- Verification run: https://openqa.opensuse.org/tests/4343099

console/gpg.pm: Handle pinentry 1.3.0

---

data/journal_check/bug_refs.json

Minimal-VM image, configure by cloud-init yields several GPT warnings/errors. This is most likely result of growpart actions.
```
Jul 15 17:51:47.318523 localhost kernel: GPT:Primary header thinks Alt.
header is not at the end of the disk.
Jul 15 17:51:47.318531 localhost kernel: GPT:2097151 != 41943039
Jul 15 17:51:47.318538 localhost kernel: GPT:Alternate GPT header not at
the end of the disk.
Jul 15 17:51:47.318546 localhost kernel: GPT:2097151 != 41943039
Jul 15 17:51:47.318552 localhost kernel: GPT: Use GNU Parted to correct
GPT errors.
```
- ticket: https://progress.opensuse.org/issues/156151
- Verification run: http://kepler.suse.cz/tests/23655#step/journal_check/8

Ignore GPT header warnings in Cloud image

---

tests/containers/podman_integration.pm

- Related ticket: https://bugzilla.suse.com/show_bug.cgi?id=1226596
Related MR: https://gitlab.suse.de/qac/qac-openqa-yaml/-/merge_requests/1737
```
$ podman run --rm ghcr.io/ricardobranco777/susepkg:latest -p any podman-remote | grep SLES/
SLES/15.3 podman-remote 4.9.5-150300.9.31.1
SLES/15.4 podman-remote 4.9.5-150400.4.27.1
SLES/15.5 podman-remote 4.9.5-150500.3.15.1
SLES/15.6 podman-remote 4.9.5-150500.3.15.1
```
Jobs for harvesting `PODMAN_BATS_SKIP_{ROOT,USER}_REMOTE` variables:
- x86_64: https://openqa.suse.de/tests/14933852
- aarch64: https://openqa.suse.de/tests/14933853

containers: podman-remote is now available on 15-SP3

---

lib/utils.pm
variables.md

When aggregate run failing and you creating product bug developers often requesting resolver case ( run zypper with special flag `debug-resolver` ) currently this can be done only manually . After merging this PR this time may be saved .
VR: http://autobot.qe.nue2.suse.org/tests/4399

Create zypper resolver and upload it

---

lib/sles4sap/ipaddr2.pm
t/22_ipaddr2.t

Shuffle order of some sanity tests. Introduce call to is_running. Rename some internal functions.
sle-15-SP5-SapCloud-Azure-Byos-x86_64-BuildLATEST_AZURE_SLE15_5_BYOS-ipaddr2_azure_test@64bit 
-  http://openqaworker15.qa.suse.cz/tests/288989 :red_circle: fails for some timeout even before reach the new code
-  http://openqaworker15.qa.suse.cz/tests/288992
-  http://openqaworker15.qa.suse.cz/tests/288987  IPADDR2_DIAGNOSTIC=1
sle-15-SP5-SapCloud-Azure-Payg-x86_64-BuildLATEST_AZURE_SLE15_5_BYOS-ipaddr2_azure_test@64bit 
-  http://openqaworker15.qa.suse.cz/tests/288990
-  http://openqaworker15.qa.suse.cz/tests/288989  IPADDR2_DIAGNOSTIC=1  :red_circle: fails for some timeout even before reach the new code

Reorganize ssh sanity tests

---

products/sle/main.pm
tests/virt_autotest/reboot_and_wait_up.pm

Enhancement reboot_and_wait_up_normal for s390x
- Related ticket: https://progress.opensuse.org/issues/151786
[gi-guest_developing-on-host_sles15sp5-kvm@virt-s390x-kvm-sle15sp5](http://10.67.129.117/tests/414) PASS
[prj4_guest_upgrade_sles15sp5_on_sles15sp5-kvm@virt-s390x-kvm-sle15sp5](http://10.67.129.117/tests/413) PASS
[gi-guest_developing-on-host_sles12sp5-kvm@virt-s390x-kvm-sle12sp5](http://10.67.129.117/tests/426) PASS

virt_autotest: enhancement reboot_and_wait_up_normal for s390x

---

lib/sles4sap/azure_cli.pm
lib/sles4sap/ipaddr2.pm

The API to wait the end of the cloud-init execution has an internal (within Azure) and external (in openQA testapi) timeout. The external one is larger to give some time to the az cli to terminate smoothly when the internal timeout elapses. Increase the delta from 10sec to 1 minute. Add timeout to other API too.
Improve diagnostic log upload code.
- http://openqaworker15.qa.suse.cz/tests/289669 :green_circle: 
sle-15-SP5-SapCloud-Azure-Payg-x86_64-BuildLATEST_AZURE_SLE15_5_PAYG-ipaddr2_azure_test@64bit
- http://openqaworker15.qa.suse.cz/tests/289670 :red_circle: 60sec of delta seems not enough
- …

Improve robustness of cloud-init wait

---

lib/sles4sap/ipaddr2.pm
t/22_ipaddr2.t

Add some preliminary connectivity test before to attempt the first ssh connection to the internal VM.
- http://openqaworker15.qa.suse.cz/tests/289671 :red_circle: fails in deployment before reaching the new code
- http://openqaworker15.qa.suse.cz/tests/289734 :green_circle: here an example http://openqaworker15.qa.suse.cz/tests/289734#step/configure/18

Check port 22 on first ssh connection

---

tests/qam-updinstall/update_install.pm

rollback has to be done after each conflict not after conflicts
- Related ticket: 1e3839969a1128be2e21b13e356ce90ed4f3ddb3

update_install: Fix the conflict rollback

---

schedule/kernel/ibtest-master.yaml
schedule/kernel/ibtest-slave.yaml

We are using these cards also for Ethernet, so let's make sure they are alwys configured for Infiniband before we run Infiniband tests.

Configure Mellanox Connect-X5 for Infiniband

---

schedule/yast/qam-yast_self_update_view_development.yaml
schedule/yast/sle/flows/default_sle15sp6_x86.yaml

##
- Related MR:
- https://gitlab.suse.de/qe-yam/openqa-job-groups/-/merge_requests/277
- Needles: N/A
- Verification Run:
- [**VR**](https://openqa.suse.de/tests/overview?distri=sle&version=15-SP6&build=hjluo%2Fos-autoinst-distri-opensuse%23remove_sle15sp6_x86_view_development)

Remove view development module from sles15sp6 maintenance update

---

data/microos/butane/script

The pure combustion test case had issues with drives in other architectures. There is need to detect an empty drive on the fly and use it as a test drive.
- VR: https://openqa.suse.de/tests/14957927#step/disk_boot/1

Run only combustion test case for non x86_64 archs

---

lib/main_containers.pm
tests/containers/netavark_integration.pm

The [netavark upstream tests use nmap's ncat](https://github.com/containers/netavark/blob/main/test/README.md?plain=1#L17) instead of OpenBSD's netcat.  As we don't ship this package in our products due to licensing issues (NSPL vs GPL), we need to install it from [nmap.org](https://nmap.org/dist/).  Unfortunately it's only available for x86_64.
This will allows us to skip less tests on netavark at the expense of no coverage on other architectures.  We expect the code paths for differents arches don't differ wildly.
- Tumbleweed: https://openqa.opensuse.org/tests/4348689 (`NCAT_VERSION=7.95-2`)
- 15-SP6: https://openqa.suse.de/tests/14959167 (`NCAT_VERSION=7.95-2`)
- 15-SP5: https://openqa.suse.de/tests/14959195 (`NCAT_VERSION=7.94-1`)
- 15-SP4: …

containers: Use nmap's ncat for netavark upstream tests

---

lib/sles4sap/sap_deployment_automation_framework/deployment.pm
t/20_sdaf_deployment_library.t
tests/sles4sap/sap_deployment_automation_framework/deploy_hanasr.pm

Current HANA SR deplyoment test module is missing a screen which will show 
status of the cluster and Hana databases. This PR adds a simple command output 
for 'crm status' and 'SAPHanaSR-showAttr'.
- Related ticket: https://jira.suse.com/browse/TEAM-9193
- Verification run: https://openqaworker15.qa.suse.cz/tests/289826#step/deploy_hanasr/239

[SDAF] Display status after deployment

---

lib/qesapdeployment.pm

sle-15-SP5-Qesap-Azure-Byos-x86_64-BuildLATEST_AZURE_SLE15_5_BYOS-qesap_azure_saptune_test@64bit
- http://openqaworker15.qa.suse.cz/tests/289758 :green_circle:  http://openqaworker15.qa.suse.cz/tests/289758/logfile?filename=deploy-hana0-cloudregister.txt
sle-15-SP6-HanaSr-Azure-Byos-x86_64-Build15-SP6_2024-07-17T02:03:22Z-hanasr_azure_test_saptune_msi@64bit 
-  http://openqaworker15.qa.suse.cz/tests/289762
PAYG where registration does not take place 
sle-12-SP5-Qesap-Azure-Payg-x86_64-BuildLATEST_AZURE_SLE12_5_PAYG-qesap_azure_saptune_test@64bit
- http://openqaworker15.qa.suse.cz/tests/289761
sle-15-SP6-Qesap-Aws-Byos-x86_64-BuildLATEST_AWS_SLE15_6_BYOS-qesap_aws_fencing_native_test@64bit
- http://openqaworker15.qa.suse.cz/tests/289759 …

Save /var/log/cloudregister during qesap tests

---

data/virt_autotest/host_unattended_installation_files/autoyast/dev_host_12.xml.ep

The incorrect network bridge configuration is causing problem:
```
The machine bare-metal2.oqa.prg2.suse.org act as router and created illegal duplicate traffics for gateway of the oqa.prg2.suse.org subnet.
We sow "DUP" responses for ping toward vlan gateway 10.145.10.254 not just in k2 VM but also in other machines like for example on DHCP servers.
We investigated the traffics and found evidences about problematic traffics in J11 TOR switches specifically on port 5 on both TORs. ports are used by the server bare-metal2.oqa.prg2.suse.org as eth0 and eth1 see: https://racktables.nue.suse.com/index.php?page=object&object_id=23403
Our suspicion is incorrect setup bond between eth0 and eth1 interfaces that want to be LACP bond, but that is not setup on our side and in he end act as loop in …
```

Prevent bonding issue by removing extra network interface from bridge_ports on sle12 autoyast

---

tests/ha/filesystem.pm

The `ha/filesystem` module does a `crm resource migrate` when testing drbd_passive, moving the resource from one node to the other. In some slower architectures, the resource has not finished starting in the target node before testing which can cause failures. This commit works around the issue by calling on `cs_wait_for_cluster` right after the move operation to ensure the cluster is ready for the test. Also part of the commit is the change of `crm resource migrate` to `crm resource move` as the migrate command is deprecated in favor of `move`.
- Related ticket: https://jira.suse.com/browse/TEAM-9514
- Failing test: https://openqa.suse.de/tests/14953019#step/filesystem#1/43
- Needles: N/A
**Verification runs:**
- 15-SP4 QU @ s390x: https://openqa.suse.de/tests/14960504 & …

Add wait_for_idle_cluster after resource move

---

lib/main_common.pm
tests/installation/bootloader_start.pm

For now our tests on s390x only expected z/VM or KVM on s390x using the
svirt backend.
This commit now adds support for the third case using the (default) qemu
backend where we actually do not need to do anything s390x specific.
```
for i in  https://openqa.suse.de/tests/14068509 https://openqa.opensuse.org/tests/4054629 https://openqa.opensuse.org/tests/4054622 https://openqa.suse.de/tests/14005042 https://openqa.suse.de/tests/14096877 https://openqa.suse.de/tests/14092754; do openqa-clone-custom-git-refspec https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/19128 $i; done
```
- sle-15-SP6-Online-s390x-Build79.1-okurz-poo158985-default-okurz-poo158985@s390x-kvm -> https://openqa.suse.de/tests/14103628 (so far expected to fail, native s390x qemu in …

Add support for s390x qemu

---

data/yam/autoyast/raid_encrypted_home_x86_64.xml.ep
tests/console/validate_raid_encrypt_home.pm

Add testsuites of autoyast_raid_encrypted_home for SLES15SP3/4/5. Adapt the current autoyast profile and validation for 15SP3.
- Related ticket: https://progress.opensuse.org/issues/163310
- Needles: n/a
- https://openqa.suse.de/tests/14958639# (15SP3)
- https://openqa.suse.de/tests/14958640# (15SP4)
- https://openqa.suse.de/tests/14958641# (15SP5)
- Related mr: https://gitlab.suse.de/qe-yam/openqa-job-groups/-/merge_requests/274

Adapt raid_encrypted_home_x86_64.xml file for SLES15SP3 installation

---

tests/console/perl_bootloader.pm
tests/transactional/trup_smoke.pm

Related ticket: https://progress.opensuse.org/issues/164021
Related bug: https://bugzilla.suse.com/show_bug.cgi?id=1228126
VR: https://openqa.suse.de/tests/14961319

Skip reinstalling bootloader if encrypted

---

.github/workflows/openqa.yml

This fixes a problem when the determination of the latest published Tumbleweed build actually did not return anything by adding the "-e" parameter to the "jq" invocation.

CI: Fix call to openQA on empty output

---

data/yam/autoyast/create_hdd_textmode_xen_hvm.xml
tests/autoyast/installation.pm

This is the first time to add autoyast installation test for svirt-xen-hvm in openQA.
- Related ticket: https://progress.opensuse.org/issues/160120
- Related MR: https://gitlab.suse.de/qe-yam/openqa-job-groups/-/merge_requests/278
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/overview?distri=sle&version=15-SP6&build=93.5&groupid=316

Add autoyast installation test for svirt-xen-hvm

---

lib/main_common.pm
tests/virtualization/universal/patch_and_reboot.pm

This PR mainly implements A3 task https://progress.opensuse.org/issues/160850, so it does mainly below:
- move below testsuites into one kvm testsuite, eg with name qam-kvm-migration-src
qam_virt_kvm_install_host_migration_src
qam_virt_kvm_install_guests_migration_src
qam_virt_kvm_guests_migration_src
- move below testsuites into one kvm testsuite, eg with name qam-kvm-migration-dst
qam_virt_kvm_install_host_migration_dst
qam_virt_kvm_install_guests_migration_dst
qam_virt_kvm_guests_migration_dst
- qam-kvm-migration-src has PARALLEL_WITH relation with qam-kvm-migration-dst
- move below testsuites into one xen testsuite, eg with name qam-xen-migration-src
qam_virt_kvm_install_host_migration_src
qam_virt_kvm_install_guests_migration_src
qam_virt_kvm_guests_migration_src
- move below …

Reconstruct MU guest migration test: merge chained tests into combined single testsuite

---

tests/sles4sap/ensa/netweaver_swpm_installation.pm

Fix sles4sap_ensa_ascs_node failed on test module netweaver_swpm_installation: sapinst timed out on 12sp5
- Related ticket: [TEAM-9539](https://jira.suse.com/browse/TEAM-9539) - [qam][12-SP5] sles4sap_ensa_* failed on netweaver_swpm_installation: command "sapinst" timed out
http://openqa.suse.de/tests/14981330 (passed, sapinst takes about 16 minutes)
http://openqa.suse.de/tests/14981334 (passed, sapinst takes about 16 minutes)
http://openqa.suse.de/tests/14981339 (passed, sapinst takes about 16 minutes)
http://openqa.suse.de/tests/14981340 (passed, sapinst takes about 16 minutes)
http://openqa.suse.de/tests/14981343 (passed, sapinst takes about 16 minutes)
http://openqa.suse.de/tests/14981359 (passed, sapinst takes about 16 minutes)

Fix netweaver_swpm_installation sapinst timed out

---

data/sles4sap/cloud-init-web.txt

sle-15-SP5-SapCloud-Azure-Payg-x86_64-BuildLATEST_AZURE_SLE15_5_PAYG-ipaddr2_azure_test@64bit 
- http://openqaworker15.qa.suse.cz/tests/290798 :red_circle: error about VM state in starting and not running
-  http://openqaworker15.qa.suse.cz/tests/290801 Deployment is fine but then `is-system-running` report `degradated`
- http://openqaworker15.qa.suse.cz/tests/290802 :green_circle: again fail on `is-system-running` but this time as `starting` 
sle-15-SP5-SapCloud-Azure-Byos-x86_64-BuildLATEST_AZURE_SLE15_5_BYOS-ipaddr2_azure_test@64bit 
- http://openqaworker15.qa.suse.cz/tests/290799 :red_circle: exotic error about not existing SubNet
-  http://openqaworker15.qa.suse.cz/tests/290800 :green_apple:

Disable package upgrade in cloud-init

---

data/microos/butane/script

`combustion` has been adapted to search for empty drive. `64bit` worker runs started to fail, as `sr0` device appeared in image tests. It is unclear from the qemu command why the VM assumes there is a cd-rom attached.
As of now, skip these devices in case they are detected by combustion script.
- ticket: [[sle-micro 6.1] Where does `/dev/sr0` come from?](https://progress.opensuse.org/issues/164159)
- Verification run: http://kepler.suse.cz/tests/23719#details

Skip srX devices in a block device check

---

schedule/security/create_hdd_autoyast/create_hdd_x86_64_uefi.yaml

Add the missing opensuse_welcome step.
- Related ticket: https://progress.opensuse.org/issues/163535
- Verification run: https://openqa.opensuse.org/tests/4356140

create_hdd_x86_64_uefi: Handle opensuse_welcome

---

lib/main_containers.pm
tests/containers/apparmor.pm

Add a basic test that checks if the apparmor service is enabled and running.
- Related ticket: https://progress.opensuse.org/issues/161996
- Verification run: https://openqa.suse.de/tests/14969348#step/apparmor/1

containers: add new apparmor test

---

tests/containers/aardvark_integration.pm
tests/containers/podman_integration.pm

Record podman version in upstream tests as we do in other modules.
We also use `podman info` but I plan to use this information from script that processes `record_info` for package version on all upstream tests.

containers: Record podman version in upstream tests

---

data/virt_autotest/host_unattended_installation_files/autoyast/dev_host_15.xml.ep
lib/ipmi_backend_utils.pm

* **According** to [libvirt recommendations](https://libvirt.org/kbase/launch_security_sev.html), AMD SEV options ```mem_encrypt=on kvm_amd.sev=1``` should be added onto kernel command line although it makes no difference from functionality perspective. 
* **Product** bug [bsc#1224107](https://bugzilla.suse.com/show_bug.cgi?id=1224107) leads to removing ```mem_encrypt=on``` from kernel command line on 15-SP6 KVM host.
* **In** order to make overall layout more neat/readable and also leave room for future more advanced options for SEV family features and other options, the content of <append> element is based on more rich and advanced test suite settings in IF condition.
* **Also** make similar changes to subroutine ```enable_sev_in_kernel``` which will be called in non-autoyast …

Add SEV kernel options in SLE 15 autoyast

---

lib/ipmi_backend_utils.pm

* **GRUB_TERMINAL_INPUT** and GRUB_TERMINAL_OUTPUT can also be present in /etc/default/grub file. They should be handled as well besides GRUB_TERMINAL in subroutine set_grub_terminal_and_timeout to have desired terminal settings.
*  [**UEFI host**  link1](http://10.100.228.134/tests/2931) [link2](http://10.100.204.18/tests/2931) [link3](http://10.67.18.153/tests/2931) [link4](http://10.149.193.170/tests/2931)
*  [**non-UEFI host**  link1](http://10.100.228.134/tests/2939) [link2](http://10.100.204.18/tests/2939) [link3](http://10.67.18.153/tests/2939) [link4](http://10.149.193.170/tests/2939)

GRUB_TERMINAL_INPUT/OUTPUT should also be handled

---

data/virt_autotest/guest_params_xml_files/slm_6_1_64_kvm_hvm_x86_64_default_encrypted_ignition+combustion.xml
data/virt_autotest/guest_params_xml_files/slm_6_1_64_kvm_hvm_x86_64_default_encrypted_ignition.xml

* **SL Micro 6.1** default encrypted image is in  raw.xz format instead of raw format which was used by SL Micro 6.0.
* [SL Micro 6.1 on SL Micro 6.1 ignition+combustion](https://openqa.suse.de/tests/14981208)
* [SL Micro 6.1 on SL Micro 6.1 ignition](https://openqa.suse.de/tests/14981416)

SL Micro 6.1 default encrypted image in raw.xz format

---

schedule/virt_autotest/slem_open_vm_tools.yaml

SLE Micro 6.0 increment test has updates for VMDK image, which has a proper test open_vm_tools. But current yaml schedule does not load the necessary install_updates module. This PR is to make that conditionally scheduled based on the flavor type.
- Related ticket: https://progress.opensuse.org/issues/159375
- for update test(load install_updates):  https://openqa.suse.de/tests/14960416# (same failure with what https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/19712 tries to solve)
- regression test(not load install_updates): https://openqa.suse.de/tests/14960510 (ignore the failure, modules are correctly loaded)

Load install_updates in slem 6.0 increment open_vm_tool test

---

lib/main_containers.pm

Temporarily limit the apparmor test to Tumbleweed only due to failures on the SLES side of things.
* Related failures e.g. [this](https://openqa.suse.de/tests/overview?groupid=417&version=15-SP3&build=20240723-1&distri=sle) and [this](https://openqa.suse.de/tests/overview?distri=sle&build=20240723-1&version=15-SP5&groupid=419)
* Follow-up of https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/19778
* Verification run: https://openqa.suse.de/tests/14999796 (schedule is OK)

Hotfix: Unschedule apparmor test

---

data/virt_autotest/host_unattended_installation_files/autoyast/dev_host_12.xml.ep
data/virt_autotest/host_unattended_installation_files/autoyast/dev_host_15.xml.ep
data/virt_autotest/virt_logs_collector.sh
lib/utils.pm

* **Enable** console kernel log on kvm system by adding ```ignor_loglevel``` on kernel command line in host autoyast profile if ```ENABLE_CONSOLE_KERNEL_LOG=1```.
* **Enable** console kernel log on xen system by adding ```guest_loglvl=all loglvl=all``` on kernel command line in host autoyast profile if  ```ENABLE_CONSOLE_KERNEL_LOG=1```.
* **Enable** persisten kernel log on SLES system by adding ```kern.* /var/log/kern.log``` in ```/etc/rsyslog.conf``` in host autoyast profile if ```ENABLE_PERSISTENT_KERNEL_LOG=1```. 
* **Also** provide subroutines ```enable_persistent_kernel_log``` and ```enable_console_kernel_log``` to enable persistent and console kernel log outside autoyast profies. They can be employed when necessary at any time for convenience.
* **Collect** persistent kernel log in …

Enable persistent and console kernel log

---

data/python/python3-scipy-test.py

SciPy 1.14 has been released, and has cleaned up a lot of deprecated functions, "simps" among them. Use the new function "simpson".
- Related ticket: https://bugzilla.suse.com/show_bug.cgi?id=1227405

Support SciPy 1.14

---

data/journal_check/bug_refs.json

Widen regex for bsc#1190662 per https://bugzilla.suse.com/show_bug.cgi?id=1190662#c29
Failing job: https://openqa.suse.de/tests/14992165#step/journal_check/11
- Related ticket: https://progress.opensuse.org/issues/163733
- Verification run: not needed imho.

bug_refs.json: Widen regex for bsc#1190662

---

data/sles4sap/cloud-init-web.txt
lib/sles4sap/azure_cli.pm
lib/sles4sap/ipaddr2.pm
t/22_ipaddr2.t
tests/sles4sap/ipaddr2/configure.pm
tests/sles4sap/ipaddr2/deploy.pm

Add setting to optionally disable cloud-init execution during the deployment. Az cloud-init is mostly in charge to configure the web server, if disabled the installation and configuration is executed later and by some ssh commands.
test with setting IPADDR2_CLOUDINIT=1
- http://openqaworker15.qa.suse.cz/tests/290913 :red_circle:  exotic ip2t-snet issue ??
- http://openqaworker15.qa.suse.cz/tests/290923 :red_circle: `[{"code":"InUseSubnetCannotBeUpdated","message":"Subnet ip2t290922-snet is in use and cannot be updated."`
- http://openqaworker15.qa.suse.cz/tests/290934 :green_circle:  it is using cloud-init (settings works), cloud-init script content is fine http://openqaworker15.qa.suse.cz/tests/290934/logfile?filename=deploy-cloud-i …

Makes cloud-init execution optional

---

tests/containers/aardvark_integration.pm
tests/containers/buildah_integration.pm
tests/containers/netavark_integration.pm
tests/containers/podman_integration.pm
tests/containers/runc_integration.pm
tests/containers/skopeo_integration.pm

record_info the package version to use in tooling to compare version tested vs. published repo in separate script.

containers: record_info package versions in upstream tests

---

schedule/security/create_hdd_autoyast/create_hdd_x86_64_uefi.yaml

This would be trivial if this wasn't one of those awful declarative schedules.
- https://openqa.opensuse.org/tests/4358256 (gnome)
- https://openqa.opensuse.org/tests/4358257 (textmode)

create_hdd_x86_64_uefi: Skip opensuse_welcome on textmode

---

data/autoyast_sle15/create_hdd/create_hdd_gnome_we_for_HAWK_x86_64.xml

This newly added autoyast profile will generate the following image SLES-15-SP6-x86_64-sap_ha-gnome+we.qcow2 for future HAWK testing in HA job groups.
This new autoyast profile is edited based on `create_hdd_gnome_we_x86_64.xml`, the difference is:
````
--- create_hdd_gnome_we_x86_64.xml
+++ create_hdd_gnome_we_for_HAWK_x86_64.xml
@@ -296,6 +296,8 @@
<package>sle-module-server-applications-release</package>
<package>sle-module-desktop-applications-release</package>
<package>sle-module-basesystem-release</package>
+      <package>sle-module-containers-release</package>
+      <package>podman</package>
<package>os-prober</package>
<package>openssh</package>
<package>kexec-tools</package>
@@ -339,6 +341,13 @@
<addons t="list">
<addon t="map">
<arch>{{ARCH}}</arch>
+ …
```

Generate qcow2 image for HAWK testing automatically by autoyast

---

lib/services/sshd.pm
tests/fips/openssl/openssl_fips_hash.pm
tests/fips/openssl/openssl_pubkey_dsa.pm

As a partial workaround, we avoid to restore snapshot when running on transactional products.
- Related ticket: https://progress.opensuse.org/issues/160197
- Needles: no
- Verification run: https://openqa.suse.de/tests/14893202 
(VR is failing because sshd tests are not ready to run on Micro yet)

Don't rollback the snapshot on Micro

---

tests/qam-updinstall/update_install.pm

Avoid known conflict
qemu-hw-usb-smartcard conflicts with 'qemu-tools'
- Related ticket: https://suse.slack.com/archives/C02D16TCP99/p1721872859703929
- Verification run: https://dzedro.suse.cz/tests/1213#step/update_install/13

update_install: Remove phub repo on all qemu updates

---

schedule/virt_autotest/slem-kubevirt-tests.yaml
schedule/virt_autotest/slem_open_vm_tools.yaml

Remove host_config test module to workaround hard disk boot failure.
- Related ticket: https://progress.opensuse.org/issues/164287
slem_open_vm_tools - https://openqa.suse.de/tests/15000500
slem-kubevirt-tests-server - https://openqa.suse.de/tests/15007285
slem-kubevirt-tests-agent - https://openqa.suse.de/tests/15007286

Remove host_config module for kubevirt tests on sle-micro

---

lib/virt_autotest/virtual_storage_utils.pm
tests/virt_autotest/libvirt_extend_storage_lvm.pm

Enable NVME Hard Drive Support
- Related ticket: https://progress.opensuse.org/issues/163502
SATA Hard Drive
[amd-zen3-gpu-sut1-1](https://openqa.suse.de/tests/15007506#) PASS
[openqaipmi5](https://openqa.suse.de/tests/15007521#) PASS
[gonzo](https://openqa.suse.de/tests/15008383#) PASS
[fozzie](https://openqa.suse.de/tests/15008384#) PASS
[quinn](https://openqa.suse.de/tests/15008380#) PASS
NVME Hard Drive
[bare-metal1](https://openqa.suse.de/tests/15007507#step/libvirt_extend_storage_lvm/179) PASS
[bare-metal2](https://openqa.suse.de/tests/15007508#step/libvirt_extend_storage_lvm/179) PASS

virt_autotest: Enable NVME Hard Drive Support

---

data/containers/ibm_hpvs/bci-busybox
data/containers/ibm_hpvs/workload.yaml
schedule/ibm.yaml
tests/containers/prepare_hpvs.pm

[IBM Hyper Protect Platform](https://www.ibm.com/downloads/cas/GPVMWPM3) is another "host system" where we need to run our containers. The specific is that there is no access on the VM itself, container is configure through `compose` and `workload contract` yamls.
VPC, network and floating IP segment is as of now configure manually, but should be moved into qe-c infra repository.
Other that this test can be considered as an IBMCloud CLI smoke test as well
- ticket: [[IBM-HPVS] Establish workflow to run custom BCI container commands and obtain the logs](https://progress.opensuse.org/issues/163190)
- Verification run: http://kepler.suse.cz/tests/23785#step/prepare_hpvs/129

[PoC] Introduce HPVS testing in IBM Cloud

---

lib/LTP/utils.pm

This fixes error: `sched_football: command not found`.
https://openqa.opensuse.org/tests/4362998#step/sched_football/6
For details see:
https://lore.kernel.org/ltp/20240729073226.GA1223191@pevik/
Verification run: http://quasar.suse.cz/tests/3529#step/sched_football/8

LTP: Temporarily fix PATH for sched_football

---

data/journal_check/bug_refs.json

Can be ignored according to https://bugzilla.suse.com/show_bug.cgi?id=1190662#c29
Related ticket: https://progress.opensuse.org/issues/163733

slem: Ignore bsc#1227930

---

data/containers/htpasswd/go.mod

The aarch64 version of `registry.opensuse.org/opensuse/bci/golang:latest` has go 1.22.4 instead of go 1.22.5:
https://openqa.suse.de/tests/15025751#step/skopeo_integration/96

htpasswd: Use go 1.22.4

---

lib/LTP/utils.pm

This reverts commit e4d325027a9ec6db7fa8df018930eb61d314902f.
LTP fix was merged [1], workaround in openQA can be removed.
[1] https://github.com/linux-test-project/ltp/commit/7788860e739101ff5d031c8984294ce985dc242e
Signed-off-by: Petr Vorel <pvorel@suse.cz>
Let's merge tomorrow once LTP packages are build
Verification run: http://quasar.suse.cz/tests/3535#step/sched_football/8

Revert "LTP: Temporarily fix PATH for sched_football"

---

lib/virt_autotest/utils.pm

* **Subroutine** ```check_failures_in_journal``` only fails test module softly if there are found failures in journal log, which looks similar to all other softfailures resulting from workaround for product bugs although they should be treated as errors. 
* **In** order to mark these errors as real failures and also make them more eye-catching, use record_info to fly red flag.
* [15sp6 on 15sp5](https://openqa.suse.de/tests/15028228)
* [15sp6 on 15sp6](https://openqa.suse.de/tests/15028230)

Fly red flag for found failures in journal log

---

lib/utils.pm

USB disk device name includes the key word in filter command, this will result in not finding out the correct usb disk name. This fix will introduce a variable to customize the filter command for the specific device.
- Related ticket: https://progress.opensuse.org/issues/164287
- Verification run: https://openqa.suse.de/tests/15020037

Fix usb disk filter for specific device

---

tests/security/ntpd.pm

ntp moved to legacy also for 15-SP4
- Related ticket: https://progress.opensuse.org/issues/164553
- Needles: no
- Verification run: https://openqa.suse.de/tests/15030643
testsuite requires also SCC_REGCODE_LIVE

Add legacy module for ntp in 15-SP4

---

tests/wsl/enable_systemd.pm

This is needed to not use legacy cgroupv1.
Not adding a softfail because this is something that needs to be addressed in WSL, not Tumbleweed.
- Related tickets: https://bugzilla.opensuse.org/show_bug.cgi?id=1228438 https://github.com/microsoft/WSL/issues/11857
- Verification run: https://openqa.opensuse.org/tests/4370169

wsl/enable_systemd.pm: Set cgroup_no_v1=all for the WSL2 host VM

---

lib/security_boot_utils.pm

on s390x QU, when disk is encrypted we need to enter password in text mode before boot sequence
- Related ticket: https://progress.opensuse.org/issues/161051
- Verification run: https://openqa.suse.de/tests/15039579

Enter passphrase on encrypted s390x disk

---

tests/qam-updinstall/update_install.pm

```
%package macros-devel
Summary:        Macro package for HPC GNU compiler environment
Group:          Development/Tools/Other
Provides:       %{pname}-hpc-macros-devel = %{version}
Conflicts:      otherproviders(%{pname}-hpc-macros-devel)
```
- Related ticket: https://progress.opensuse.org/issues/164568
https://openqa.suse.de/tests/15051069 s390x
https://openqa.suse.de/tests/15051070 ppc64le

update_install: Add gnu-compilers-hpc-macros-devel conflict

---

lib/security_boot_utils.pm

Fix for a missing parameter in check_var() API call
- Related ticket: https://progress.opensuse.org/issues/161051
- Needles: no

Add missing check_var() parameter

---

lib/utils.pm

The "ping_size_check" mentioned misleading messages about "MTU size
problems" when the ping application is not even installed or if the ping
would fail regardless of the MTU size.
This commit adds two explicit checks with separate fail messages.
Verification run: `openqa-clone-custom-git-refspec https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/19557 https://openqa.suse.de/tests/14657729`
2 jobs have been created:
- sle-15-SP3-Server-DVD-Updates-x86_64-Build20240617-1-cc_ipsec_server@64bit -> https://openqa.suse.de/tests/14680173
- sle-15-SP3-Server-DVD-Updates-x86_64-Build20240617-1-cc_ipsec_client@64bit -> https://openqa.suse.de/tests/14680174
Related progress issue: https://progress.opensuse.org/issues/162320

utils: Add explicit checks for ping command and 0-size ping in ping_size_check

---

schedule/install/agama_install.yaml
tests/installation/agama.pm

- Basic installation with GNOME now passes
https://openqa.opensuse.org/tests/4371421#step/reboot_after_installation/1
- Add await install loop with timeout
Ideally we should get rid of sleep, however, as it is written the check for any change on screen is every 30 to 60 seconds.
Worst case scenario is that if the installation is fully stuck, it will timeout after 40 minutes.
- Handling of hiding/showing tabs

Working agama test suite

---

lib/registration.pm

The newer QR images might have this option. Images that are used as of now in Updates testing should not use it.
- Verification run: http://kepler.suse.cz/tests/23827#step/suseconnect_scc/71

Skip auto agree with licenses in JeOS images

---

tests/kernel/install_kotd.pm

Use `zypper_search()` helper function to check installed kernel packages instead of opaque shell command which doesn't produce any usable debugging output.
- Needles: N/A
- aarch64: https://openqa.opensuse.org/tests/4371385#step/install_kotd/48
- x86_64: https://openqa.opensuse.org/tests/4371378#step/install_kotd/48

install_kotd: List installed kernels

---

lib/bootloader_setup.pm
schedule/install/agama_install.yaml
tests/installation/bootloader.pm

This one was forgotten from local changes. We need to go for first option and not failsafe which is current behavior.
Also let's drop grub tests for now we're going straight to firstboot.
old behavior: https://openqa.opensuse.org/tests/4372531
new fixed behavior: https://openqa.opensuse.org/tests/4372607

Agama: Use first default option for bootloader, skip grub-test  poo#164141

---

tests/kernel/install_kotd.pm
tests/kernel/update_kernel.pm

Add zypper command line parameter to force installation of kernel-default only from the KOTD repo. Even though the repo has high priority, zypper might otherwise fall back to other repos if the kernel package is somehow missing.
- Needles: N/A
- Tumbleweed aarch64 (KOTD package missing): https://openqa.opensuse.org/tests/4372675
- Tumbleweed x86_64 (KOTD package present): https://openqa.opensuse.org/tests/4372676
- SLEM 5.1: https://openqa.suse.de/tests/15054809
- SLES-12SP5: https://openqa.suse.de/tests/15054814

install_kotd: Force installation only from KOTD repo

---

tests/installation/agama.pm

Add needles and logic for user creation
* Unfortunatelly agama does not support alt-Y shortcuts and has slightly different login layout (tab has to be used twice within passwords etc), so I can't reuse existing user info functions. 
* I'm not sure if long term approach would be to add `if (get_var('AGAMA'))` to all needed user info functions in libs/*.pm or simply start to create bunch of other functions. I really take this AGAMA test suite as minimalistic to get us quickly thourgh install. I understand that full agama suite will be using a dedicated framework.
- Related ticket: https://progress.opensuse.org/issues/164141
- Verification run: https://openqa.opensuse.org/tests/4376291

Agama: handle usercreation and autologin poo#164141

---

lib/main_micro_alp.pm
tests/microos/selfinstall.pm

For all images the fallback option is jeos-firstboot. We should make sure this test object is covered by openqa.
- ticket: [[sle-micro 6.1] test fails in selfinstall - adapt the test module and test suite schedule](https://progress.opensuse.org/issues/164162)
* [combustion](http://kepler.suse.cz/tests/23841#)
* [wizard](http://kepler.suse.cz/tests/23840#)
* [ignition](http://kepler.suse.cz/tests/23842#)

Configure selfinstall images with jeos-firstboot

---

tests/installation/bootloader_svirt.pm

[hvm](http://openqa.suse.de/tests/15089039#step/bootloader_start/44)
[pv](https://openqa.suse.de/tests/15088599#step/bootloader_start/38)

Show xen host and instance information when starting job

---

tests/cpu_bugs/kvm_guest_mitigations.pm
tests/cpu_bugs/mitigations.pm
tests/cpu_bugs/spectre_v2.pm
tests/cpu_bugs/spectre_v4.pm

Adaption for KVM mitigation change from sle15sp6 to sle15sp6.
- Related ticket:https://progress.opensuse.org/issues/151349;https://progress.opensuse.org/issues/151358
- Verification run: for kvm hypervisor and guest(passthrough and custom)have verification on skylake,icelake and cascadelake machines
http://10.67.129.4/tests/72683;http://10.67.129.4/tests/72657;http://10.67.129.4/tests/72684
http://10.67.129.4/tests/72686;http://10.67.129.4/tests/72663;http://10.67.129.4/tests/72659
http://10.67.129.4/tests/72745;http://10.67.129.4/tests/72749;http://10.67.129.4/tests/72747

Adaption for KVM mitigation change from sle15sp5 to sle15sp6

---

data/virt_autotest/host_unattended_installation_files/autoyast/dev_host_12.xml.ep
data/virt_autotest/host_unattended_installation_files/autoyast/dev_host_15.xml.ep
data/virt_autotest/vgpu_guest_logging.sh
lib/ipmi_backend_utils.pm
lib/virt_autotest/utils.pm
products/sle/main.pm
tests/virt_autotest/install_package.pm
tests/virt_autotest/login_console.pm
tests/virt_autotest/vgpu.pm

- Related ticket: https://progress.opensuse.org/issues/92990
- Although MIG mode is supported in test scrips but it is not verified because it is beyond the test scope in this ticket.  These scripts were written in the past, so keep them for future support.
- Add `VGPU_TEST=short/full` to allow run short(no passthough) or full vgpu tests.
- move `set_ssh_console_timeout()` into autoyast for sle15+.
- make `SERIALDEV` optional and set default value is `ttyS1`
- allow to run test from install_package.pm directly
- remove obsolete scripts from install_package.pm
vGPU tests:
[short_test_on_OSD](https://openqa.suse.de/tests/15041226)
[vgpu_only_full_test_on_OSD](https://openqa.suse.de/tests/15087902)
[full_test_on_OSD](https://openqa.suse.de/tests/15049950) …

Support vgpu automation test

---

lib/package_utils.pm
tests/kernel/update_kernel.pm

Forcing kernel installation specifically from the KOTD repository blocks installation of `kernel-default-devel` package due to required dependencies which need to be installed from non-KOTD repos. Installing `kernel-devel` in a separate step without repo restrictions fixes the dependency issue and correctly pulls in `kernel-default-devel`.
Also add `trup_continue` keyword parameter to `install_package()` to allow multi-step installation on transactional systems.
- Needles: N/A
- SLEM 5.1: https://openqa.suse.de/tests/15090993
- SLES-12SP5: https://openqa.suse.de/tests/15090994

Split installation of KOTD kernel-default and kernel-devel into two steps

---

tests/containers/podman_remote.pm

Remove soft-failure for bsc#1226596
[bsc#1226596](https://bugzilla.suse.com/show_bug.cgi?id=1226596) seems to be fixed and it's now available on SLEM >=5.1 and SLES-15SP3+ according to:
```
susepkg -p any podman-remote | grep -e Micro -e SLES/15
SL-Micro/6.0 podman-remote 4.9.3-1.3
SLE-Micro/5.3 podman-remote 4.9.5-150400.4.30.1
SLE-Micro/5.4 podman-remote 4.9.5-150400.4.30.1
SLE-Micro/5.5 podman-remote 4.9.5-150500.3.15.1
SLES/15.3 podman-remote 4.9.5-150300.9.31.1
SLES/15.4 podman-remote 4.9.5-150400.4.27.1
SLES/15.5 podman-remote 4.9.5-150500.3.15.1
SLES/15.6 podman-remote 4.9.5-150500.3.15.1
SUSE-MicroOS/5.1 podman-remote 4.9.5-150300.9.31.1
SUSE-MicroOS/5.2 podman-remote 4.9.5-150300.9.31.1
```
- Verification run: not needed, I think.

containers: Remove soft-failure for bsc#1226596

---

tests/sles4sap/publiccloud/azure_fence_agents_test.pm

Get peering and Ansible status from the test modue argument allows post_fails_hook to properly cleanup peering in case of error.
-  WITHOUT PEERING sle-15-SP6-HanaSr-Azure-Byos-x86_64-Build15-SP6_2024-08-06T02:03:21Z-hanasr_azure_test_saptune_msi@64bit -> http://openqaworker15.qa.suse.cz/tests/293149. Status is now propagated http://openqaworker15.qa.suse.cz/tests/293149#step/Verify_azure_fence_agent_MSI/1
- WITH PEERING  sle-12-SP5-Azure-SAP-PAYG-Incidents-saptune-x86_64-Build:34935:systemd-sles4sap_gnome_saptune_delete_rename@az_Standard_E8s_v3 -> http://openqaworker15.qa.suse.cz/tests/293150

Propagate deployment status

---

lib/publiccloud/instance.pm

Apply the 20sec delta not only for script_run but also for script_output
- sle-15-SP6-HanaSr-Aws-Byos-x86_64-Build15-SP6_2024-08-06T02:03:21Z-hanasr_aws_test_fencing_sbd@64bit -> http://openqaworker15.qa.suse.cz/tests/293151
- sle-12-SP5-Azure-Incidents-x86_64-Build:34935:systemd-publiccloud_ltp_syscalls@az_Standard_B2s -> http://openqa.suse.de/tests/15102417
- sle-15-SP5-Azure-BYOS-Updates-x86_64-Build20240805-1-publiccloud_ahb@64bit -> http://openqa.suse.de/tests/15102418
- sle-15-SP5-Azure-Basic-Updates-x86_64-Build20240805-1-publiccloud_img_proof@64bit -> http://openqa.suse.de/tests/15102419

Extend timeout delta usage in run_ssh_command

---

schedule/qam/QR/15-SP6/crypt_no_lvm.yaml
schedule/qam/QR/15-SP6/encryption/cryptlvm_sle_15.yaml
schedule/qam/QR/15-SP6/lvm_raid1/lvm+raid1_sle15_aarch64.yaml

Don't need select product for aarch64
- Related ticket: https://progress.opensuse.org/issues/164967
- Verification run: https://openqa.suse.de/tests/15111266
https://openqa.suse.de/tests/15111259#
https://openqa.suse.de/tests/15111260#
https://openqa.suse.de/tests/15111509#
- Related MR: https://gitlab.suse.de/qa-maintenance/qam-openqa-yml/-/merge_requests/775

Don't need select product for aarch64

---

lib/version_utils.pm
schedule/virt_autotest/slem-kubevirt-tests.yaml

For kubevirt tests on sle-micro 6.0 increment updates, loading install_updates test module.
- Related ticket: https://progress.opensuse.org/issues/164646
- Verification run: https://openqa.suse.de/tests/15067060

Support kubevirt test for MU slem 6.0 increment updates

---

tests/console/zypper_lifecycle.pm

Added SCC_REGCODE_LIVE=*** to Online-RT flavors
- Related ticket: https://progress.opensuse.org/issues/133514
- Verification run: https://openqa.suse.de/tests/overview?build=jpupava_livep&distri=sle

zypper_lifecycle: Add livepatch product

---

lib/trento.pm

The call script_run(..., die_on_timeout => 0) is deprecated and soon to
be removed from os-autoinst.
This commit replaces the trento lib call by simply removing "die_on_timeout => 0"
as not actually needed or not necessary anymore after underlying bugs are fixed.
Related progress issue: https://progress.opensuse.org/issues/164712

Remove deprecated die_on_timeout

---

lib/version_utils.pm

VR: https://openqa.suse.de/tests/15113686 (before it didn't get to the edit screen due to [this](https://github.com/os-autoinst/os-autoinst-distri-opensuse/blob/master/tests/installation/bootloader_uefi.pm#L139) and [this](https://github.com/os-autoinst/os-autoinst-distri-opensuse/blob/master/lib/bootloader_setup.pm#L386) conditions not matching.

Add Minimal-VM flavor to is_jeos query

---

lib/main_common.pm

By default, most of the images come with btrfs. If there is an exception as RISC or Cloud Minimal VM image, the correspoding filesystem should be specified by `FILESYSTEM=xyz`.
- [failure](https://openqa.suse.de/tests/15111521#step/diskusage/1)
* [sle-15-SP7-JeOS-for-kvm-and-xen -- BTRFS](http://kepler.suse.cz/tests/23872#step/diskusage/1)
* [sle-15-SP7-JeOS-for-OpenStack-Cloud -- XFS](http://kepler.suse.cz/tests/23871#)

Schedule diskusage module only for btrfs

---

data/python/python3-pipx/package/__init__.py
data/python/python3-pipx/package/cli.py
data/python/python3-pipx/setup.py
schedule/functional/stack_tests_python.yaml
tests/console/python3_pipx.pm
tests/console/python3_setuptools.pm

- Related ticket: https://progress.opensuse.org/issues/156472
- Needles: No
SLE15-SP6:  [aarch64](https://openqa.suse.de/tests/14948447) | [s390x](https://openqa.suse.de/tests/14948448) | [x86_64](https://openqa.suse.de/tests/14948449)
SLE15-SP5: [aarch64](https://openqa.suse.de/tests/14948441) | [s390x](https://openqa.suse.de/tests/14948442) | [x86_64](https://openqa.suse.de/tests/14948443)
SLE15-SP4: [aarch64](https://openqa.suse.de/tests/14948444) | [s390x](https://openqa.suse.de/tests/14948445) | [x86_64](https://openqa.suse.de/tests/14948446)
LEAP15.6: [aarch64](https://openqa.opensuse.org/tests/4367120#step/python3_pipx/1) | [ppc64le](https://openqa.opensuse.org/tests/4367119#step/python3_pipx/1)| [x86_64](https://openqa.opensuse.org/tests/4367118#step/python3_pi …

Add a new test to verify python311-pipx

---

lib/main_common.pm
tests/console/apparmor.pm

This PR introduces a new smoke test for apparmor, scheduled after patch_and_reboot under the console tests. It's another try on the ticket, past iteration was [19778](https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/19778), which broke some tests and had to be limited to Tumbleweed in [19804](https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/19804) then finally removed in [19817](https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/19817).
- Related ticket: https://progress.opensuse.org/issues/161996
- Verification run: https://openqa.opensuse.org/tests/4382867#step/apparmor/43

console/apparmor: Add smoke test after updates

---

tests/sles4sap/forkbomb.pm

Fix forkbomb time out introduced on saptune 3.1.3
[TEAM-9573](https://jira.suse.com/browse/TEAM-9573) - Test qam-sles4sap_online_dvd_gnome_hana_nvdimm failing in multiple service packs in forkbomb sub-test
- Needles: NA
15sp6 (when saptune>=3.1.3): https://openqa.suse.de/tests/15111290#step/forkbomb/57 (passed)
15sp6 (when saptune<3.1.3): https://openqa.suse.de/tests/15111291#step/forkbomb/27 (passed)
15sp2 (when saptune>=3.1.3): https://openqa.suse.de/tests/15110924#step/forkbomb/57 (passed)
15sp2 (when saptune<3.1.3): https://openqa.suse.de/tests/15110923#step/forkbomb/18 (passed)

Fix forkbomb time out on saptune 3.1.3

---

lib/qesapdeployment.pm

This looks for a '404' return of openqa queries during the `delete_leftover_peerings` module, and outputs a more suggestive message to the user.
- Related ticket: https://jira.suse.com/browse/TEAM-9564
- Verification run: https://openqa.suse.de/tests/15066077, https://openqa.suse.de/tests/15125107

Log openqa bad queries better

---

lib/sles4sap/ipaddr2.pm
t/22_ipaddr2.t
tests/sles4sap/ipaddr2/configure.pm
tests/sles4sap/ipaddr2/deploy.pm
tests/sles4sap/ipaddr2/sanity.pm
tests/sles4sap/ipaddr2/test.pm

Add some sanity check about the cluster.
Collect log from the cloud VM about cloud-init.
- http://openqaworker15.qa.suse.cz/tests/293871 :green_circle: 
- http://openqaworker15.qa.suse.cz/tests/293872
sle-15-SP5-SapCloud-Azure-Payg-x86_64-Buildmpagot_VR-ipaddr2_azure_test@64bit 
- http://openqaworker15.qa.suse.cz/tests/293873  :green_circle: 
- http://openqaworker15.qa.suse.cz/tests/291032 :red_circle: error creating ip2t-vm-02
-  http://openqaworker15.qa.suse.cz/tests/293824 :red_circle: `crm_mon: command not found`

Add cluster sanity check to IpAddr2 test

---

lib/publiccloud/basetest.pm
lib/utils.pm

Reverts os-autoinst/os-autoinst-distri-opensuse#19859, this PR was trying upload `zypper.log` from openQA VM instead of uploading `zypper.log` from SUT VM running in the cloud hence it should be reverted and we should create another one which will do it right

Revert "Making upload of zypper.log explicit on every failure"

---

lib/containers/bats.pm
lib/main_containers.pm
tests/containers/netavark_integration.pm
tests/containers/podman_integration.pm

The [podman upstream tests use nmap's ncat](https://github.com/containers/podman/blob/main/test/system/README.md?plain=1#L84) instead of OpenBSD's netcat.  As we don't ship this package due to licensing issues (NSPL vs GPL), we need to install it from [nmap.org](https://nmap.org/dist/).  Unfortunately it's only available for x86_64.
This avoids the error messages seen in logs that force us to skip these tests:
```
```
https://openqa.opensuse.org/tests/4391501/logfile?filename=serial_terminal.txt
Verification runs: TBD

containers: Limit podman upstream tests to x86_64

---

tests/containers/podman_integration.pm

Avoid error message: 
```
```
The package is available on our products:
```
$ susepkg -p any libcriu2 | grep -e Micro -e SLES/
SLE-Micro/5.3 libcriu2 3.16.1-bp154.1.33
SLE-Micro/5.4 libcriu2 3.16.1-bp154.1.33
SLE-Micro/5.5 libcriu2 3.17.1-bp155.2.7
SLES/15.1 libcriu2 3.15-bp151.4.3.1
SLES/15.2 libcriu2 3.15-bp152.4.3.1
SLES/15.3 libcriu2 3.15-bp153.2.3.1
SLES/15.4 libcriu2 3.16.1-bp154.1.33
SLES/15.5 libcriu2 3.17.1-bp155.2.7
SLES/15.6 libcriu2 3.18-bp156.1.6
SUSE-MicroOS/5.1 libcriu2 3.15-bp153.2.3.1
SUSE-MicroOS/5.2 libcriu2 3.15-bp153.2.3.1
```

containers: Add missing libcriu2 dependency

---

tests/containers/podman_integration.pm

This helper was added to podman 5.2, needed by https://github.com/containers/podman/blob/main/test/system/331-system-check.bats
- Verification run: https://openqa.opensuse.org/tests/4394368 (podman_integration module no longer failing)

containers: Compile helpers used by podman upstream tests

---

tests/containers/podman_integration.pm

libcriu2 is not available on SLEM 6.0+
```
$ susepkg -p any libcriu2 | grep Micro
SLE-Micro/5.3 libcriu2 3.16.1-bp154.1.33
SLE-Micro/5.4 libcriu2 3.16.1-bp154.1.33
SLE-Micro/5.5 libcriu2 3.17.1-bp155.2.7
SUSE-MicroOS/5.1 libcriu2 3.15-bp153.2.3.1
SUSE-MicroOS/5.2 libcriu2 3.15-bp153.2.3.1
```

containers: libcriu2 is not available on SLEM 6.0+

---

lib/containers/bats.pm

Properly install ncat on transactional systems
- Failed test: https://openqa.suse.de/tests/15148456#step/podman_integration/62
- Verification run: https://openqa.suse.de/tests/15149041

containers: Properly install ncat on transactional systems

---

tests/containers/podman_integration.pm

Avoid error:
```
not ok 438 [255] podman-kube@.service template with rollback
#
```

containers: Fix for 250-systemd

---

data/yam/autoyast/support_images/sles15sp4_install_textmode_all_patterns_aarch64.xml

##
- Failed case:
-  https://openqa.suse.de/tests/15147774#step/installation/3
- https://openqa.suse.de/tests/15147774#step/installation/57
* Quick PR
- Needles: 
* N/A
* https://openqa.suse.de/t15148431
##

Fix supp_sles15sp4_all patterns-base-x11_raspberrypi issue on aarch64

---

tests/containers/buildah_integration.pm

Create a temp directory for root & user buildah test. This will avoid some errors because of already existing files.
- Verification run: https://openqa.opensuse.org/tests/4400557

containers: Create a temp directory for root & user buildah test

---

lib/partition_setup.pm
tests/installation/start_install.pm

If none disk selected, select the first disk.
- Related ticket: https://progress.opensuse.org/issues/164964
- Verification run: https://openqa.suse.de/tests/15133287#
https://openqa.suse.de/tests/15148449

Handle the server with multiple NVMe disks

---

data/sles4sap/angi_hana_cluster.conf
data/sles4sap/angi_susHanaHADR_AIO.template
data/sles4sap/hana_cluster.conf
lib/sles4sap.pm
tests/sles4sap/hana_cluster.pm
tests/sles4sap/hana_install.pm
tests/sles4sap/sap_suse_cluster_connector.pm
tests/sles4sap/trento/test_hana_restore_stopped.pm

SAPHanaSR will be replaced by SAPHanaSR-angi on SLES 16, but it's already available as a technical preview in 15-SP4 - SP6. We are adapting our test to cover both packages.
Introduce new setting: USE_SAP_HANA_SR_ANGI(bool)
Related ticket: https://jira.suse.com/browse/TEAM-9425
USE_SAP_HANA_SR_ANGI(true): https://openqa.suse.de/tests/15102530#dependencies
w/o USE_SAP_HANA_SR_ANGI(): https://openqa.suse.de/tests/15102979#dependencies

Added support for SAPHanaSR-angi package

---

tests/x11/hexchat_ssl.pm

Our Hexchat tests have been unstable due to Freenode not playing nice lately. This change uses the Rizon network instead.
- Related ticket: https://progress.opensuse.org/issues/165123
- Verification run: https://openqa.suse.de/tests/15161243

Change IRC server from Freenode to Rizon

---

tests/security/swtpm/tpm_selftest.pm

Improve on test robustness by enforcing a `udev` rules refresh on older distro.
- Related ticket: https://progress.opensuse.org/issues/164045
- Needles: n/a
- https://openqa.suse.de/tests/15151208
- https://openqa.suse.de/tests/15151209
- https://openqa.suse.de/tests/15151210
- https://openqa.suse.de/tests/15151211
- https://openqa.suse.de/tests/15151212
- https://openqa.suse.de/tests/15151213
- https://openqa.suse.de/tests/15151214

Refresh udev rules for 15-SP3

---

lib/utils.pm

##
- Failed case:
- https://openqa.suse.de/tests/15160304#step/patch_sle/148
* Quick PR
- Needles: 
* N/A
* https://openqa.suse.de/tests/15161257
* https://openqa.suse.de/tests/15161258
##

Skip patterns-base-x11_raspberrypi for aarch64 all pattern in patch_sle

---

tests/containers/buildah_integration.pm

Use /var/tmp for buildah upstream tests
- Verification run: https://openqa.opensuse.org/tests/4400912

containers: Use /var/tmp for buildah upstream tests

---

lib/power_action_utils.pm
tests/x11/reboot_plasma5.pm

Needed for power_action 'reboot'. Port reboot_plasma5 to use it.
Failure: https://openqa.opensuse.org/tests/4399620
- opensuse-Tumbleweed-DVD-x86_64-Build20240812-kde_dual_windows10@64bit_win -> https://openqa.opensuse.org/tests/4401321
- opensuse-Tumbleweed-NET-x86_64-Build20240812-update_tw2twnext_kde@64bit-3G -> https://openqa.opensuse.org/tests/4401301

lib/power_action_utils.pm: Handle Plasma in reboot_x11

---

data/yam/autoyast/raid_encrypted_home_sle12sp5_x86_64.xml.ep
tests/console/validate_raid_encrypt_home.pm

- Related ticket: https://progress.opensuse.org/issues/163292
- Related MR: https://gitlab.suse.de/qe-yam/openqa-job-groups/-/merge_requests/305
- Needles: N/A
- Verification run:  https://openqa.suse.de/tests/15133340# 12SP5
regression test on 15SP4: https://openqa.suse.de/tests/15133341#step/validate_raid_encrypt_home/2

Add raid_encrypted_home for sle 12sp5

---

lib/partition_setup.pm
tests/installation/start_install.pm

My bad, hana test needs /dev/sda as boot dev.
https://openqa.suse.de/tests/15167200#step/partitioning_firstdisk/5
Reverts os-autoinst/os-autoinst-distri-opensuse#19910

Revert "Handle the server with multiple NVMe disks"

---

data/virt_autotest/guest_params_xml_files/slm_6_1_64_kvm_hvm_x86_64_default_encrypted_ignition+combustion.xml
data/virt_autotest/guest_params_xml_files/slm_6_1_64_kvm_hvm_x86_64_default_encrypted_ignition.xml
data/virt_autotest/guest_params_xml_files/slm_6_1_64_kvm_hvm_x86_64_default_qcow_ignition+combustion.xml
data/virt_autotest/guest_params_xml_files/slm_6_1_64_kvm_hvm_x86_64_default_qcow_ignition.xml
data/virt_autotest/guest_params_xml_files/slm_6_1_64_kvm_hvm_x86_64_default_raw_ignition+combustion.xml
data/virt_autotest/guest_params_xml_files/slm_6_1_64_kvm_hvm_x86_64_default_raw_ignition.xml

* **osinfo-query** database has been updated on SL Micro 6.1 host.
* **Although** there is no ```slm6.1``` in the database at the moment, at least ```slm6.0``` is available. 
* **Using** ```slm6.0``` is better than ```opensusetumbleweed``` for SL Micro 6.1 guest to be installed.
* [sl micro guest on sl micro host](https://openqa.suse.de/tests/15175388)
* [sles15sp6 on sle micro host](https://openqa.suse.de/tests/15175389)

Update OS variant for SL Micro guest

---

tests/kernel/mellanox_config.pm

Previously, we explicitely searched for "infiniband" devices from Mellanox.
However, if we have those configured as Ethernet devices, we won't find any devices. We know we only have ConnectX-5 devices for InfiniBand (but on the same machines we have ConnectX-4 LX which only do Ethernet - so let's explicitely search for ConnectX-5 devices instead.

Change regex to search for devices

---

lib/kdump_utils.pm

Fix poo#165273: There was hard coded package name for kernel debuginfo on transactional systems. We should determine correct debuginfo from active kernel as we do on non-transactional systems.
- Related ticket: https://progress.opensuse.org/issues/165273
SL Micro: https://openqa.suse.de/tests/15177234
SL Micro RT: https://openqa.suse.de/tests/15177233 <-- Fix for this scenario

kdump: Determine kernel debuginfo automatically on transactional systems

---

lib/containers/bats.pm
lib/main_containers.pm
tests/containers/netavark_integration.pm
tests/containers/runc_integration.pm

Re-enable podman upstream tests on aarch64 by using the packaged nmap in https://download.opensuse.org/repositories/network:/utilities/
- SLE 15-SP3: https://openqa.suse.de/tests/15178335
- SLE 15-SP4: https://openqa.suse.de/tests/15178336
- SLE 15-SP5: https://openqa.suse.de/tests/15180020
- SLE 15-SP6: https://openqa.suse.de/tests/15178534
- SLEM 5.5: https://openqa.suse.de/tests/15179668
- Tumbleweed: https://openqa.opensuse.org/tests/4403565

containers: Re-enable podman upstream tests on aarch64

---

tests/console/install_packages.pm
tests/console/qam_zypper_patch.pm

https://progress.opensuse.org/issues/164592
1. It could be a corner case which all packages to be installed are new
2. In this case ''zypper in -l -t patch patch_id" can not apply the patch as well
- Verification run: https://openqa.opensuse.org/tests/4366648
**The VR above didn't cover the code change since the release request was approved**

Handle patch installation with all new packages

---

tests/console/libgit2.pm

Modified cleanup code in the test to uninstall the installed pygit2
This PR fixes the following issue in LEAP 15.6
```
Usage:   
pip3.11 uninstall [options] <package> ...
pip3.11 uninstall [options] -r <requirements file> ...
no such option: --break-system-packages
```
- Related ticket: https://progress.opensuse.org/issues/164931
- Needles: NO
Tumbleweed: https://openqa.opensuse.org/tests/4401059#step/libgit2/20
LEAP 15.6-  https://openqa.opensuse.org/tests/4401074#step/libgit2/19

Fix libgit2 test

---

schedule/yast/sle/flows/default_aarch64.yaml
schedule/yast/sle/flows/default_ipmi.yaml
schedule/yast/sle/flows/default_ppc64le.yaml
schedule/yast/sle/flows/default_s390x_kvm.yaml
schedule/yast/sle/flows/default_s390x_kvm_textmode.yaml
schedule/yast/sle/flows/default_s390x_svirt.yaml
schedule/yast/sle/flows/default_s390x_zvm.yaml
schedule/yast/sle/flows/default_svirt-hyperv.yaml
schedule/yast/sle/flows/default_svirt-xen-hvm.yaml
schedule/yast/sle/flows/default_svirt-xen-pv.yaml
schedule/yast/sle/flows/default_x86_64.yaml

##
- Related ticket: https://progress.opensuse.org/issues/164871
- Needles: N/A
- https://openqa.suse.de/tests/15188872
- https://openqa.suse.de/tests/15188873
- https://openqa.suse.de/tests/15188874
##

Add back test module access_beta_distribution in YaST for 15SP7

---

schedule/yast/sle/flows/default_x86_64_flavor_full.yaml

##
- Related ticket: https://progress.opensuse.org/issues/164871
- Needles: N/A
-  https://openqa.suse.de/t15199034
-  https://openqa.suse.de/t15199062
##

Add access_beta_distribution for SLE 15 SP7

---

tests/fips/openssl/openssl_pubkey_dsa.pm

DSA in FIPS mode with OpenSSL 3 is expected to fail. This will ignore all failures on 15-SP6+ and SL Micro 6.0+, which use OpenSSL 3. This will help us with review, since we won't have to manually soft-fail every new test run.
Related ticket: https://progress.opensuse.org/issues/161891
- 15-SP6:
- x86_64: https://openqa.suse.de/tests/15190739
- s390x: https://openqa.suse.de/tests/15199374
- aarch64: https://openqa.suse.de/tests/15191003
- 15-SP5:
- x86_64: https://openqa.suse.de/tests/15191028
- s390x: https://openqa.suse.de/tests/15199376
- aarch64: https://openqa.suse.de/tests/15191023

Expect a failure with DSA and OpenSSL 3 in FIPS

---

lib/hacluster.pm

Fix the regression introduced by PR#19968
https://openqa.suse.de/tests/15197050#step/drbd_passive/2 for example.
```
testapi::get_required_var("INCIDENT_ID") called at sle/lib/hacluster.pm line 1028
```
- Related ticket: No
- Needles: NO
- Verification run: NO

Fix the regression introduced by PR#19968

---

tests/jeos/firstrun.pm
variables.md

A new feature has been implemented and jeos-firstboot wizard can create a non root user directly in the UI. As of now the feature has landed in sle-micro 6.1 only.
- ticket: [test fails in firstrun - handle non-root user creation screen](https://progress.opensuse.org/issues/165180)
* [base](http://kepler.suse.cz/tests/23949#step/firstrun/31)
* [encrypted](http://kepler.suse.cz/tests/23950#step/firstrun/15)
* [encrypted & skip user](http://kepler.suse.cz/tests/23951#step/firstrun/35)
* [skip user](http://kepler.suse.cz/tests/23948#step/firstrun/13)

Create non-root user in jeos-firstboot wizard

---

schedule/ha/qam/common/qam_ha_rolling_upgrade_migration_node01.yaml
schedule/ha/qam/common/qam_ha_rolling_upgrade_migration_node01_sle12.yaml
schedule/ha/qam/common/qam_ha_rolling_upgrade_migration_node02.yaml
schedule/ha/qam/common/qam_ha_rolling_upgrade_migration_node02_sle12.yaml

`ha/ctdb` test module needs to run with a client node, and the rolling upgrade scenarios run without a client node. Test has been working so far as it was being skipped by the test code, but after commit de24f376a37ffe10d2d4d424c8ac1dbfa7c7d8a1 test is not skipped anymore leading to failures in Aggregates tests. This commit removes the test module from the schedules.
- Needles: N/A

Remove ha/ctbd test module from Rolling Upgrade schedule

---

tests/jeos/firstrun.pm

Test user creation feature in all Factory runs not only staging K.
- Verification run: https://openqa.opensuse.org/tests/4408339#live

New jeos-firstboot in Factory

---

lib/xfstests_utils.pm
tests/xfstests/run.pm

This is the first step to do following this ticket https://progress.opensuse.org/issues/162884. To move current functions into lib:
- Move function to a xfstests_util.pm file
- Adjust function parameter passing part
- Remove all get_var and check_var in lib function
- Correct some comments
The next step will create functions in lib to load sub-tests and rewrite the log analyst part.
- Related ticket: https://progress.opensuse.org/issues/163376
- Verification run: http://10.67.133.133/tests/722 (to prove the previous features are still working after moving function to lib)
- VR for current SLMicro6.1 test https://openqa.suse.de/tests/15200035
- VR for QAM SLE15SP6 KOTD test  https://openqa.suse.de/tests/15200037

xfstests: Move function to lib util

---

schedule/yast/encryption/cryptlvm+cancel_existing.yaml
schedule/yast/encryption/cryptlvm+cancel_existing_pvm.yaml

##
- Related ticket: https://progress.opensuse.org/issues/164871
- Needles: N/A
- https://openqa.suse.de/tests/15210658
- https://openqa.suse.de/tests/15210659
##

Add back test module access_beta_distribution in YaST group

---

data/yam/autoyast/sles12sp5_create_hdd_gnome_unregistered_no_self_update_aarch64.xml.ep
data/yam/autoyast/sles12sp5_create_hdd_gnome_unregistered_no_self_update_s390x.xml.ep
data/yam/autoyast/sles12sp5_create_hdd_gnome_unregistered_no_self_update_x86_64.xml.ep

Add autoyast profiles for sles12sp5 to create unregistered images.
- Related ticket: https://progress.opensuse.org/issues/163730
- Needles: n/a
- Verification run: [generate supp images](https://openqa.suse.de/tests/overview?arch=&flavor=&machine=&test=autoyast_sles12sp5_gnome_unregistered_no_self_update_tmp&modules=&module_re=&group_glob=&not_group_glob=&comment=&distri=sle&version=12-SP5&build=20240818-1&groupid=576#); [verify_consistency_self_update](https://openqa.suse.de/tests/overview?arch=&flavor=&machine=&test=verify_consistency_self_update_tmp&modules=&module_re=&group_glob=&not_group_glob=&comment=&distri=sle&version=12-SP5&build=20240818-1&groupid=576#)
- Related mr: https://gitlab.suse.de/qe-yam/openqa-job-groups/-/merge_requests/304

Add autoyast profiles for sles12sp5 to create unregistered images

---

lib/oscap_tests.pm

Small fix for case if p7zip not installed
- Related ticket: https://progress.opensuse.org/issues/165042
- Verification run: https://openqa.suse.de/tests/15201502

Install p7zip if missing

---

lib/main_common.pm

- Related ticket: https://progress.opensuse.org/issues/157174
- Verification run: https://openqa.opensuse.org/tests/4414961#live

Rewrite opensuse_welcome_applicable and return 0 for the TW aarch64 KDE Live

---

lib/xfstests_utils.pm

BTRFS_DUMP and RAW_DUMP default value is 0, which means disabled but not enable
- Related ticket: https://progress.opensuse.org/issues/165500
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/15224156
- https://openqa.suse.de/tests/15224155

xfstests: fix parameter issue

---

tests/transactional/install_updates.pm

Post install scriplet was failing after rt-kernel update. The fix has been already provided and the bug was resolved.
https://bugzilla.suse.com/show_bug.cgi?id=1213991
- Verification run: http://kepler.suse.cz/tests/23975#step/install_updates/347

Remove old rt-kernel post script workaround

---

lib/sles4sap/sap_deployment_automation_framework/basetest.pm
lib/sles4sap/sap_deployment_automation_framework/deployment.pm
lib/sles4sap/sap_deployment_automation_framework/deployment_connector.pm
lib/sles4sap/sap_deployment_automation_framework/naming_conventions.pm
t/26_deployment_connector.t
tests/sles4sap/sap_deployment_automation_framework/cleanup.pm
tests/sles4sap/sap_deployment_automation_framework/connect_to_deployer.pm

This PR adds improvements for SDAF cleanup routine: 
- snapshot based deployer VM cleanup
- cleanup behavior at different stages of test failures
- removing redundant cleanup code in post fail hook and standard cleanup test module 
- **Related ticket:** https://jira.suse.com/browse/TEAM-9459
**Successful run:** 
https://openqaworker15.qa.suse.cz/tests/294657#
**Failure before SDAF deployment starts:** 
- I stopped deployer VM was stopped to simulate unavailability
- test should not attempt to execute SDAF cleanup scripts, only delete VM and related resources
- https://openqaworker15.qa.suse.cz/tests/294654#step/configure_deployer/111
**Failure before deployer VM is created:**
- test should detect that VM was not created yet and therefore not try to delete it using az tools
- I simulated a …

Cleanup logic improvements

---

lib/LTP/utils.pm
lib/qam.pm
tests/kernel/shutdown_ltp.pm
variables.md

Add `LTP_TAINT_EXPECTED` variable which allows setting the expected list of kernel taint flags. Any flag not in the expected list will be treated as a test failure. Flags on the list will be reported in either case but without impact on the final result.
- Needles: N/A
- livepatches, not tainted: https://openqa.suse.de/tests/14971088
- livepatches, tainted: https://openqa.suse.de/tests/14971090
- livepatches, taint whitelisted: https://openqa.suse.de/tests/14971091
- boot_ltp, not tainted: https://openqa.suse.de/tests/15225281
- boot_ltp, tainted: https://openqa.suse.de/tests/15225282
- install_ltp, tainted: https://openqa.suse.de/tests/15225275

check_kernel_taint: Implement configurable taint mask

---

lib/services/sshd.pm

openssh 9.8 now creates processes with a `sshd-session:` prefix, not `sshd:` so let's support both.
Issue found in https://openqa.opensuse.org/tests/4416658#step/sshd/64
- Verification run: https://openqa.opensuse.org/tests/4417033#

Add support for openssh 9.8

---

tests/x11/firefox/firefox_passwd.pm

Increased timeout on some places due to random failures and sometimes page needed time to render otherwise test failed with partialy loaded page
- Related ticket: https://progress.opensuse.org/issues/165324
- Verification run: https://openqa.suse.de/tests/overview?distri=sle&build=dzedro%2Fos-autoinst-distri-opensuse%23firefox

firefox_passwd: Update code to handle new behavior

---

lib/kernel.pm
lib/transactional.pm
tests/kernel/update_kernel.pm

Implement installation of specific kernel version given in `KERNEL_VERSION` job variable. Transactional systems are also supported, which required some changes to the transactional utils library.
- Needles: N/A
- SLEM-5.1: https://openqa.suse.de/tests/15225298
- SLE-12SP5: https://openqa.suse.de/tests/15225299
- kubevirt tests (for `enter_trup_shell()` in VNC): https://openqa.suse.de/tests/15225336

update_kernel: Implement installation of specific kernel version

---

lib/main_common.pm
products/opensuse/main.pm

With LIVE_INSTALLATION=1 on the TW aarch64 KDE-Live, opensuse_welcome is not present in the live environment, but later in the installed system.
- Related ticket: https://openqa.opensuse.org/tests/4419472#step/first_boot/1
- Verification run: https://openqa.opensuse.org/tests/4419932#live

Include opensuse_welcome after live installation on aarch64 again

---

products/sle-micro/main.pm

Enable kernel error message checks on serial console for SLE Micro. There is currently no known kernel warning or error on SLE Micro that could be used to verify successful detection but further verification will be done in #20012.
Also remove a duplicate call to `set_distribution()` which causes multiple warnings about function redefinitions.
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/15236883

Enable kernel error checks on serial console for SLE Micro

---

tests/wsl/enable_systemd.pm
tests/wsl/install_wsl.pm
tests/wsl/wsl_cmd_check.pm

Windows spotlight update overrides any effort to apply stable windows wallpaper background logic. After investigating microsoft forums, it seems that this bug has happened a few times already throughout the years and it is happening once again. 
Instead of waiting for a fix from Microsoft that might or might not come, I have adjusted the needle to check for windows desktop even if the background image is variable.
Setup a stable wallpaper background for windows for wsl tests.
- Adjusted appropriate needle.
- Fixed assert_screen typo for needle callback
- Related ticket:  https://progress.opensuse.org/issues/164661
- Needles: https://gitlab.suse.de/openqa/os-autoinst-needles-sles/-/blob/master/windows-desktop-20240819.png
15sp5 win 10 bios: …

Setup stable wallpaper background

---

tests/qam-updinstall/update_install.pm

```
%package -n nfsidmap0-devel
Summary:        NFSv4 ID Mapping Library development libraries - legacy
Group:          Development/Libraries/C and C++
Version:        0.26
Release:        0
Requires:       libnfsidmap0 = %{version}
Conflicts:	nfsidmap-devel
```
- Related ticket: https://openqa.suse.de/tests/15238376#step/update_install/187
- Verification run: https://openqa.suse.de/tests/overview?build=%3A35068%3Anfs-utils&groupid=546&flavor=Server-DVD-Incidents-Install

update_install: Add nfsidmap-devel conflict

---

lib/sles4sap_publiccloud.pm
tests/sles4sap/publiccloud/hana_sr_takeover.pm
tests/sles4sap/publiccloud/hana_sr_test_secondary.pm

Fix Public Cloud HanaSR sporadically failed on "Stop_site_b-primary/Crash_replica": ssh timed out, returned 124
TEAM-9601 - [PC] HanaSR sporadically failed on "Stop_site_b-primary/Crash_replica": ssh timed out, returned 124
- Related ticket:https://jira.suse.com/browse/TEAM-9601
- Needles: no
I can not reproduce the "ssh cmd 124 error" with the PR. Here are the VRs I did:
- 15-SP4 Azure-SAP-BYOS SAPHanaSR-ScaleUp-PerfOpt-msi
https://openqa.suse.de/tests/15211524 (pass)
https://openqa.suse.de/tests/15211526 (pass)
https://openqa.suse.de/tests/15211527 (pass)
https://openqa.suse.de/tests/15211528 (pass)
https://openqa.suse.de/tests/15211529 (pass) …

Fix HanaSR sporadically fails on ssh cmd 124 error

---

lib/known_bugs.pm

At least syslog11 on unfixed SLERT-15SP6 produced this output in dmesg.
Verification run: https://openqa.suse.de/tests/15246031#step/boot_ltp/174
(I was not able to find a test which would fail like this any more - although I cloned https://openqa.suse.de/tests/15153541, which has failing 6.4.0-150600.10.3-rt, test run with 6.4.0-150600.10.5-rt, which is already fixed).

LTP: Add 'Call Trace:' as failure in dmesg

---

tests/microos/one_line_checks.pm

cloud-init user data sets CEST instead of UTC in image configuration.
As a part of https://progress.opensuse.org/issues/162938, fix timezone check.
* [microos](http://kepler.suse.cz/tests/23980#step/one_line_checks/1)
* [sle-micro](http://kepler.suse.cz/tests/23981#step/one_line_checks/1)

Fix one_line_checks for cloud-init tests

---

lib/known_bugs.pm
tests/kernel/run_ltp.pm

Serial hard failures during boot would terminate LTP jobs too early. Serial errors need to have "soft" type during boot and then switch to "hard" type once test environment setup is complete. The original type switching condition based on error message makes no sense. Add a new message key that explicitly designates which serial errors need the switch.
- Related ticket: https://progress.opensuse.org/issues/165740
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/15254360

Change serial error type switching logic

---

lib/sles4sap/ipaddr2.pm
t/22_ipaddr2.t
tests/sles4sap/ipaddr2/destroy.pm
tests/sles4sap/ipaddr2/test.pm

Crate a test module that move the cluster resource associated to the web
server and check that the Azure load balancer is alerted and change the
VM where the virtual IP is pointed to.
- http://openqaworker15.qa.suse.cz/tests/294146 :green_circle: 
- http://openqaworker15.qa.suse.cz/tests/294147 :red_circle: zypper in nginx exit with ZYPPER_EXIT_INF_REPOS_SKIPPED
sle-15-SP5-SapCloud-Azure-Payg-x86_64-Buildmpagot_VR-ipaddr2_azure_test@64bit 
-  http://openqaworker15.qa.suse.cz/tests/294148 :green_circle: 
-   http://openqaworker15.qa.suse.cz/tests/294149 :green_circle:

Implement ipaddr2 test module

---

tests/yam/agama/boot_agama.pm

- Related ticket: [poo#163943](https://progress.opensuse.org/issues/163943), fix for [#20043](https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/20043)
- Verification run: https://openqa.opensuse.org/tests/overview?build=jknphy%2Fos-autoinst-distri-opensuse%23agama-bootparams&version=agama-9.0&distri=opensuse

Fix name of function that get the POM for grub

---

tests/installation/bootloader_s390.pm

- Related ticket: [poo#163955](https://progress.opensuse.org/issues/163955)
- Verification run: [agama_auto_default](https://openqa.opensuse.org/tests/4435615#)

Append auto profile to boot params in s390x agama

---

data/virtualization/autoyast/guest_12.xml.ep
data/virtualization/autoyast/guest_15.xml.ep
lib/virt_autotest/common.pm
lib/virt_autotest/utils.pm
tests/virtualization/universal/dom_install.pm
tests/virtualization/universal/hotplugging_network_interfaces.pm
tests/virtualization/universal/waitfor_guests.pm
tests/virtualization/universal/xl_create.pm

Change to switch to bridge networking for guest is related to recommendation in [bsc#1222584](https://bugzilla.suse.com/show_bug.cgi?id=1222584#c19) 
- Related ticket: https://progress.opensuse.org/issues/160709
- Needles: N/A
KVM : [15-6](http://openqa.qam.suse.cz/tests/79038), [15-5](http://openqa.qam.suse.cz/tests/79039), [15-3](http://openqa.qam.suse.cz/tests/79084#), [12-5](http://openqa.qam.suse.cz/tests/79040)
XEN : [15-6](http://openqa.qam.suse.cz/tests/79057), [15-5](http://openqa.qam.suse.cz/tests/79047), [15-3](http://openqa.qam.suse.cz/tests/79086), [12-5](http://openqa.qam.suse.cz/tests/79041)
KVM Migration : [15-6](http://openqa.qam.suse.cz/tests/79059#dependencies), [15-5](http://openqa.qam.suse.cz/tests/79078), …

Switch guests to br0

---

lib/services/sshd.pm

Added expect and its dependencies to QA:Head repo, enabled repo on Micro
- Related ticket: https://progress.opensuse.org/issues/164751
- Verification run: https://progress.opensuse.org/issues/164751
please note that now sshd tests fails due to known bug: https://bugzilla.suse.com/show_bug.cgi?id=1227370

Add QA:HEAD repo for sshd testing on Micro

---

data/sssd/openldap/slapd.conf
data/sssd/openldap/sudo.schema
schedule/functional/openldap_sssd.yaml
tests/console/openldap/openldap_client.pm
tests/console/openldap/openldap_server.pm

https://progress.opensuse.org/issues/165258
**openldap2_5 package is not available on sle15sp7 now, so skip this test**
[sle15sp6](https://openqa.suse.de/tests/overview?distri=sle&version=15-SP6&build=20240825-1&groupid=564)
[sle15sp5](https://openqa.suse.de/tests/overview?distri=sle&version=15-SP5&build=20240825-1&groupid=564)

Re-enable openldap testing for 15SP5+

---

tests/yast2_cmd/yast_nfs_server.pm

The bug already fixed, and we can't reproduce it on current test coverage(15SP2 to 15SP6), so we should remove the soft failure.
- Related ticket: https://progress.opensuse.org/issues/151915
- Verification run: http://openqa.suse.de/tests/15263557#step/yast_nfs_server/16

Remove softfail for bsc#1142979

---

data/microos/butane/script
lib/main_micro_alp.pm
tests/microos/verify_setup.pm

VMWare guest machines have a floppy device and combustion script can detect them. In case it is present, combustion should skip them.
- ticket: [[vmware] add combustion & ignition support](https://progress.opensuse.org/issues/164922)
- VR: sle-micro-6.1-Default-VMware-x86_64-Build12.2-combustion@svirt-vmware70 -> https://openqa.suse.de/tests/15276847#

Skip floppy device if it is present

---

lib/sles4sap/ipaddr2.pm
t/22_ipaddr2.t
tests/sles4sap/ipaddr2/test.pm

Add connectivity test after each takeover.
Relax some nginx setup command timeouts.
Add a test step to takeover back to VM1.
Related ticket: https://jira.suse.com/browse/TEAM-9428
sle-15-SP5-SapCloud-Azure-Payg-x86_64-Buildmpagot_VR-ipaddr2_azure_test  http://openqaworker15.qa.suse.cz/tests/295534 :green_apple:

Enable more ipaddr2 test steps

---

lib/main_common.pm
schedule/kernel/sles4sap/hana_cluster_node.yaml
schedule/qam/15-SP2/qam-sles4sap_wmp_hana_node1.yaml
schedule/qam/15-SP3/qam-sles4sap_wmp_hana_node1.yaml
schedule/qam/15-SP4/qam-sles4sap_wmp_hana_node1.yaml
schedule/qam/15-SP5/qam-sles4sap_wmp_hana_node1.yaml
schedule/qam/15-SP6/qam-sles4sap_wmp_hana_node1.yaml
schedule/qam/common/qam-sles4sap_hana_node01.yml
schedule/sles4sap/ensa/ensa_nodes.yaml
schedule/sles4sap/hana/hana_cluster_node.yaml
schedule/sles4sap/hana/pvm_hana_cluster_node.yaml
schedule/sles4sap/qam/common/qam_hana_cluster_node.yaml
tests/sles4sap/sap_suse_cluster_connector.pm

Enhance test module "sap_suse_cluster_connector":
- Replace `sleep 10` with `wait_for_idle_cluster`
- Show test module failures for smm command
- Module is no longer scheduled in HANA scenarios.
- Module passes on NetWeaver scenarios.
- Add module to ASCS/ERS  scenarios and passes.
Related ticket: 
https://jira.suse.com/browse/TEAM-9612 
(TEAM-9612 - Enhance hanaSR test module "sap_suse_cluster_connector" according to the research of TEAM-9571)
Verification run:    
- VRs for code changes in `sap_suse_cluster_connector.pm`:
15sp6 qam-SAPHanaSR_ScaleUp_PerfOpt_WMP_node01
(YAML_SCHEDULE=schedule/sles4sap/qam/common/qam_hana_cluster_node.yaml)
https://openqa.suse.de/tests/15252602#step/sap_suse_cluster_connector/55 (**failed: make "smm" failed on purpose**) …

Enhance hanaSR module "sap_suse_cluster_connector"

---

data/jeos/g_cloudinit.cfg
lib/main_micro_alp.pm

If vmware is provisioned by cloud-init, the bootloader handler is accidentaly scheduled twice
- Related ticket: https://progress.opensuse.org/issues/162938
* [sle-micro-6.1-Base-VMware](https://openqa.suse.de/tests/15282674#step/first_boot/1)
* [sle-micro-6.1-Default-VMware](https://openqa.suse.de/tests/15282682#step/first_boot/1)

Skip redundant bootloader handler in vmware

---

lib/oscap_tests.pm
tests/security/oscap_profile_tests/oscap_security_guide_setup.pm

Fix python3.11 usage in oscap_tests and optimizing amount of uploaded logS.
- Related ticket: https://progress.opensuse.org/issues/165908
https://openqa.suse.de/tests/15282732#
https://openqa.suse.de/tests/15282742#
https://openqa.suse.de/tests/15282745#
https://openqa.suse.de/tests/15282758#
https://openqa.suse.de/tests/15282759#

Fix python 3.11 usage

---

tests/elemental/container_validation.pm

This is to ensure that an iso/image from another run is not used instead of the good one.
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/15282922 and https://openqa.suse.de/tests/15282931

Fix Elemental generated artifacts name

---

lib/Yam/Agama/agama_base.pm
lib/Yam/Agama/patch_agama_base.pm
tests/yam/agama/agama.pm
tests/yam/agama/auto.pm
tests/yam/agama/patch_agama_tests.pm

- Related ticket: https://progress.opensuse.org/issues/165833
- Needles: N/A
https://openqa.opensuse.org/tests/4442184#step/auto/10    x86_64, upload logs after fail in auto
https://openqa.opensuse.org/tests/4442256#step/boot_agama/9  x86_64, upload logs after fail in boot_agama
https://openqa.opensuse.org/tests/4442186#step/auto/6   s390x, upload logs after fail in fail in auto

Ensure agama automation test get logs when issue happened

---

lib/sles4sap/ipaddr2.pm
t/22_ipaddr2.t
tests/sles4sap/ipaddr2/test.pm

Add some validation on the node that is not the one running the virtual IP resource.
Swap the order of some sanity to prioritize the one about the network setup.
More UT and code comments.
sle-15-SP5-SapCloud-Azure-Payg-x86_64-Buildmpagot_VR-ipaddr2_azure_test@64bit 
-  http://openqaworker15.qa.suse.cz/tests/295606
-  http://openqaworker15.qa.suse.cz/tests/295607

Ipaddr2 add test for the node that is not master

---

data/containers/autoyast_containers.xml.ep

The firewall settings were not added in autoyast_containers.xml which caused ssh error in s390x hosts
- Related ticket: https://progress.opensuse.org/issues/165812
- [15-SP7](https://openqa.suse.de/tests/15294432) :green_circle:
- [15-SP6](https://openqa.suse.de/tests/15294846) :green_circle:
- [15-SP5](https://openqa.suse.de/tests/15294847) :green_circle:
- [15-SP4](https://openqa.suse.de/tests/15294848) :construction:

Add firewall settings for 15-SP7

---

tests/microos/verify_setup.pm

Verification of drives configured by ignition and combustion had a test bug. The condition should have been removed in earlier PRs when the config was updated.
- ticket: https://progress.opensuse.org/issues/164922
VRs:
* http://kepler.suse.cz/tests/23985#step/verify_setup/149
* http://kepler.suse.cz/tests/23984#step/verify_setup/172
* http://kepler.suse.cz/tests/23984#step/verify_setup/172

Fix drive detection

---

schedule/yast/maintenance/sap_autoyast_create_hdd_gnome_netweaver_sle12.yaml
schedule/yast/maintenance/sap_autoyast_create_hdd_textmode_netweaver_sle12.yaml

Remove PUBLISH_HDD_1 setting from sap yaml schedule file. The removed settings were already added to testsuites via [MR](https://gitlab.suse.de/qe-yam/openqa-job-groups/-/merge_requests/317/diffs#0520e5d1ec21859704fc7ebca5a545e8dd0549fb).
- Related ticket: quick PR
- Needles: n/a
-  [support image job on ppc64le](https://openqa.suse.de/tests/15289595), [migration job on ppc64le](https://openqa.suse.de/tests/15289669);
-  [support image job on x86_64](https://openqa.suse.de/tests/15303995), [migration job on x86_64](https://openqa.suse.de/tests/15304238#);

Remove PUBLISH_HDD_1 setting from sap yaml schedule file

---

lib/Yam/Agama/agama_base.pm
schedule/yam/agama.yaml
tests/yam/agama/agama.pm
tests/yam/agama/patch_agama_tests.pm

We have included script preparation, launch and Puppeteer traces upload to OpenQA with, minor modifications.
- Related ticket: https://progress.opensuse.org/issues/165830
- Needles: N/A
- Verification run: https://openqa.opensuse.org/tests/4443241#
- Related PR: https://github.com/jknphy/agama-puppeteer/pull/3

Integrate the web automation script for agama in openQA

---

lib/oscap_tests.pm

Fix pip3 -> pip3.11 call on SP6 - pip3 points to broken lib
- Related ticket: https://progress.opensuse.org/issues/165908
- Verification run: https://openqa.suse.de/tests/15297116

Fix pip3 call on SP6

---

tests/kernel_performance/install_qatestset.pm

Add workaround to prevent network interface order change: load tg3 driver before bnxt_en
- Related ticket: [TEAM-9042](https://jira.suse.com/browse/TEAM-9042)
- Needles: N/A
- Verification run:  http://10.67.129.4/tests/73223

Add workaround to prevent network interface order change

---

data/sles4sap/qe_sap_deployment/mr_test_azure.yaml
data/sles4sap/qe_sap_deployment/mr_test_azure_uri.yaml
data/sles4sap/qe_sap_deployment/sles4sap_azure_generic.yaml
data/sles4sap/qe_sap_deployment/sles4sap_azure_generic_maintenance.yaml
data/sles4sap/qe_sap_deployment/sles4sap_azure_generic_uri.yaml

Remove vm_size terraform variable from all the qe-sap-deployment config.yaml templates and replace it with the specific one for the hana nodes.
- Related ticket: https://jira.suse.com/browse/TEAM-9627
- sle-15-SP5-HanaSr-Azure-Byos-x86_64-Build15-SP5_2024-08-29T02:03:22Z-hanasr_azure_test_sapconf_msi@64bit -> http://openqaworker15.qa.suse.cz/tests/295673 :green_circle: 
http://openqaworker15.qa.suse.cz/tests/295673/file/deploy_qesap_terraform-sles4sap_azure_generic.yaml has `    hana_vm_size: Standard_E8s_v3`
it results in openqaworker15.qa.suse.cz/tests/295673/file/deploy_qesap_terraform-terraform.tfvars having `hana_vm_size = "Standard_E8s_v3"`
http://openqaworker15.qa.suse.cz/tests/295673/logfile?filename=deploy_qesap_terraform-terraform.plan.log.txt has
```
+ resource …
```

Use the proper Terraform variable for the machine

---

data/sles4sap/qe_sap_deployment/qesap_aws.yaml
data/sles4sap/qe_sap_deployment/qesap_aws_fencing.yaml
data/sles4sap/qe_sap_deployment/qesap_aws_sapconf.yaml
data/sles4sap/qe_sap_deployment/qesap_azure.yaml
data/sles4sap/qe_sap_deployment/qesap_azure_fencing_msi.yaml
data/sles4sap/qe_sap_deployment/qesap_azure_fencing_spn.yaml
data/sles4sap/qe_sap_deployment/qesap_azure_roles.yaml
data/sles4sap/qe_sap_deployment/qesap_azure_sapconf.yaml
data/sles4sap/qe_sap_deployment/qesap_azure_sapconf_no_reg.yaml
data/sles4sap/qe_sap_deployment/qesap_azure_uri.yaml
data/sles4sap/qe_sap_deployment/qesap_gcp.yaml
data/sles4sap/qe_sap_deployment/qesap_gcp_fencing.yaml
data/sles4sap/qe_sap_deployment/qesap_gcp_sapconf.yaml
data/sles4sap/qe_sap_deployment/sles4sap_aws_generic.yaml
data/sles4sap/qe_sap_deployment/sles4sap_azure_generic.yaml
data/sles4sap/qe_sap_deployment/sles4sap_azure_generic_maintenance.yaml
data/sles4sap/qe_sap_deployment/sles4sap_azure_generic_uri.yaml
tests/sles4sap/qesapdeployment/configure.pm

Add az_key_name in any relevant qe-sap-deployment template. For the moment add it near to the SAS token that later can be removed when token generation is moved to Ansible.
- Related ticket: https://jira.suse.com/browse/TEAM-9540
There are new fields in the conf.yaml but later the qe-sap-deployment simply ignore them
- sle-15-SP6-Qesap-Azure-Byos-x86_64-BuildLATEST_AZURE_SLE15_6_BYOS-qesap_azure_saptune_test@64bit -> https://openqa.suse.de/tests/15305761 :green_circle: even if no `az_key_name` is here https://openqa.suse.de/tests/15305761#step/configure/203
There are new fields in the conf.yaml and qe-sap-deployment place them in the hana_media.yaml
- sle-15-SP6-Qesap-Azure-Byos-x86_64-BuildLATEST_AZURE_SLE15_6_BYOS-qesap_azure_saptune_test@64bit -> https://openqa.suse.de/tests/15305779 …

Add az_key_name handling

---

data/microos/butane/s390x.fcc

`/dev/disk/by-id` does not exist in s390x kvm.
sle-micro-6.1-Default-qcow-s390x-Build14.2-ignition@s390x-kvm -> https://openqa.suse.de/tests/15306032

Add ignition config for s390x only

---

tests/virt_autotest/esxi_open_vm_tools.pm

The change introduces an additional check for "TD" ensuring that tests are also executed for guests。
- Related ticket: https://progress.opensuse.org/issues/166010
- Needles: NA
- Verification run: [sles 15 SP4 TD test](https://openqa.suse.de/tests/15305686)

Fix TD vmware test

---

schedule/ha/bv/basic_cluster_node.yaml

Enable ctdb test in Aggregates in osd
- Related MR for osd: https://gitlab.suse.de/qa-maintenance/qam-openqa-yml/-/merge_requests/784
- Related MR for ow15:  https://gitlab.suse.de/qa-css/openqa_ha_sap/-/merge_requests/771
- Related ticket: https://jira.suse.com/browse/TEAM-9607
15sp6: http://openqa.suse.de/tests/15291380#dependencies (all passed)
15sp5: http://openqa.suse.de/tests/15304274#dependencies (all passed) 
15sp4: http://openqa.suse.de/tests/15303718#dependencies (all passed)
15sp3: http://openqa.suse.de/tests/15291705#dependencies (all passed)
15sp2: http://openqa.suse.de/tests/15294390#dependencies (all passed)
12sp5: http://openqa.suse.de/tests/15304261#dependencies (all passed) 
VRs for `VIRTIO_CONSOLE=1`:
15sp5: …

Enable ctdb test in Aggregates in osd

---

lib/sles4sap/ipaddr2.pm
t/22_ipaddr2.t
tests/sles4sap/ipaddr2/configure.pm
tests/sles4sap/ipaddr2/deploy.pm
tests/sles4sap/ipaddr2/destroy.pm
tests/sles4sap/ipaddr2/sanity.pm
tests/sles4sap/ipaddr2/test.pm

End the Ipaddr2 test module by removing all location constraints in the cluster created along the test.
- sle-15-SP5-SapCloud-Azure-Payg-x86_64-BuildLATEST_AZURE_SLE15_5_PAYG-ipaddr2_azure_test@64bit -> http://openqaworker15.qa.suse.cz/tests/296043

Clear location constrains at the end of ipaddr2

---

lib/main_common.pm
schedule/virtualization/vmware_hyperv.yaml
tests/virtualization/universal/init_mu_virt_vars.pm

This PR mainly does below:
- use var BUILD info to set UPDATE_PACKAGE in main.pm, BUILD format eg BUILD=:33310:dtb-armv7l -- :<incident-id>:<update-package-name> (libvirt pkg needs value translation)
- PATCH_WITH_ZYPPER, set to 1 for official test, and allow customized value 0 if passing down by user 
Related ticket: A4 task openqa part, https://progress.opensuse.org/issues/160856
**Note: this PR shall be merged together with https://progress.opensuse.org/issues/160859**
```
verification run on http://10.67.129.77/
Unit test:
PASS: qemu pkg
qa2-dhcp-77:/var/lib/openqa/tests/sle # openqa-cli api  -X POST isos ARCH="x86_64" DISTRI="sle" VERSION="15-SP5" FLAVOR=Server-DVD-Virt-KVM-GuestMigration-Incidents TERADATA=  PATCH_WITH_ZYPPER=0  GUEST_ADMINISTRATION=0 …
```

[virtualization][MU]: Set PATCH_WITH_ZYPPER and UPDATE_PACKAGE in code

---

tests/console/sssd_389ds_functional.pm

This test runs systemd inside a container, which expects to be able to create subcgroups in /sys/fs/cgroup. Previously the test tried to mount /sys/fs/cgroup as read-only. Due to a series of unfortunate coincidences, this happened to work:
* Due to kernel limitations, using "-v a:b:ro" with Docker would do a recursive bind-mount but the read-only flag would only be set on the top mount. Implementing proper recursive attributes only became possible with Linux 5.12 (with mount_setattr).
* The tests seem to run on cgroupv1 or cgroup-hybrid systems, where /sys/fs/cgroup is a dummy tmpfs mount that has all of the actual subsystems mounted underneath it as child mounts.
The net result is that -v /sys/fs/cgroup:/sys/fs/cgroup:ro actually gave you a read-write set of cgroup subsystems by chance. …

sssd_389ds_functional: make cgroups rw for systemd

---

schedule/sles4sap/qam/common/qam_install_sles_4_horizontal_migration.yaml

One of the reasons for the complexity of this yaml is that it is used both in SLES4SAP jobs and SLES jobs that are to be horizontally migrated. As a first step towards simplification we need to split it.
- Related Ticket: TEAM-9610
- Verification run:  This does not change anything until the jobgroups are pointed to this schedule. VRs are going to happen in gitlab for those changes.

Split create_hdd schedules for SAP incidents

---

lib/LTP/kirk.pm
tests/kernel/kselftests.pm

This patch fixes kirk module that was bugged due to wrong --skip-tests usage and correct the way we fetch known issues file from qam.
- Verification run: https://openqa.suse.de/tests/15328453#
Signed-off-by: Andrea Cervesato <andrea.cervesato@suse.com>

Fix kselftests known issues usage

---

data/journal_check/bug_refs.json

* **Agreement** has been achieved in bsc#1218181 that ```Device lusk is not active``` can be safely whitelisted to avoid further error reporting. 
* **Please** refer to [comment](https://bugzilla.suse.com/show_bug.cgi?id=1218181#c30) for details.
* [verification run](https://openqa.suse.de/tests/15318383)

White list journal check error 'Device luks is not active'

---

lib/services/sshd.pm
lib/ssh_crypto_policy.pm

Added `nmap` and dependencies to QA:Head repo in order to run the full sshd tests on Micro
- Related ticket: https://progress.opensuse.org/issues/165986
- Needles: no
- Verification run: https://openqa.suse.de/tests/15337291 (sshd pass, test fails in later step)

Reboot if needed after installing packages on Micro

---

lib/bootloader_setup.pm
tests/installation/agama.pm
tests/installation/bootloader.pm

* introduced in https://github.com/openSUSE/agama/pull/1545
* USE REPO_0 var which contains the repo path (was AGAMA_INSTALL_URL in test suite)
- Related ticket: https://progress.opensuse.org/issues/164141
- Verification run: https://openqa.opensuse.org/tests/4454073#live
`openqa-clone-job --within-instance https://openqa.opensuse.org/tests/4438312 --skip-chained-deps YAML_SCHEDULE=schedule/install/agama_install.yaml  REPO_0=Leap-16.0-aarch64-ppc64le-s390x-x86_64-Build2.4 AGAMA=1 _GROUP=0 _LIVETEST=0  LIVETEST=0 CASEDIR=git@github.com:lkocman/os-autoinst-distri-opensuse.git#agama_install_url
`

Utilize agama.install_url

---

tests/sles4sap/monitoring_services.pm

The resource name is different in SAPHanaSR-angi and SAPHanaSR. So we need to distinguish it.
Related: https://jira.suse.com/browse/TEAM-9608
VRs:
x86: https://openqa.suse.de/tests/15338735 (Passed)
ppc64le: https://openqa.suse.de/tests/15346058 (Passed)

Fix the resource name in hanasr_angi test

---

lib/Distribution/Opensuse/AgamaDevel.pm
lib/Yam/Agama/Pom/RebootPage.pm
schedule/yam/agama.yaml
test_data/yam/agama_tumbleweed.yaml
tests/yam/agama/agama.pm
tests/yam/agama/auto.pm

Added POM model of reboot page
- Related ticket: https://progress.opensuse.org/issues/165980
- Needles: N/A
- default:
- x86_64: https://openqa.opensuse.org/tests/4456712 (05/09/2024)
- aarch64: https://openqa.opensuse.org/tests/4456713 (05/09/2024)
- auto:
- x86_64: https://openqa.opensuse.org/tests/4456710 (05/09/2024)
- aarch64: https://openqa.opensuse.org/tests/4456711 (05/09/2024)

Create page object for reboot screen in agama

---

lib/qesapdeployment.pm
t/09_qesapdeployment.t

Avoid sles4sap_publiccloud_basetest post_fail_hook to fail in case of timeout at script_run("test -e $inventory")
- Related ticket: https://jira.suse.com/browse/TEAM-9586
- Needles: N/A
- Verification run: https://openqaworker15.qa.suse.cz/tests/294923#step/Stop_site_a-primary/261

Add timeout for script_run "test -e $inventory"

---

lib/bootloader_setup.pm
lib/utils.pm
tests/installation/agama.pm

* set static password for livecd via live.password param so we can login to root console
* Improve consistency of code
* Use tty7 as a workaround for https://github.com/openSUSE/agama/issues/1582
* Spellcheck && make tidy
- Verification run: https://openqa.opensuse.org/tests/4457883

Upload agama-logs in agama.pm

---

tests/installation/agama.pm

Enable KDE on Leap 16.0 installation with agama
Related PR https://github.com/os-autoinst/opensuse-jobgroups/pull/517
kde-agama in https://openqa.opensuse.org/admin/test_suites
Verification run https://openqa.opensuse.org/tests/4457957#live

KDE enablement for agama.pm

---

schedule/install/agama_install.yaml

Just like in Leap 15.0 test suite ensure to execeute system_workarounds before system_prepare. It does seem that system-prepare already expects root-console with login. The login usually happens in previous module system_workarounds on 15.X.

Add system_workarounds to get proper root console

---

lib/qesapdeployment.pm
tests/publiccloud/patch_and_reboot.pm
tests/qa_automation/patch_and_reboot.pm
tests/sles4sap/patterns.pm
tests/sles4sap/publiccloud/qesap_ansible.pm

Sometimes we need to know the packages changes during our test when we debugging a failure, especially for QAM test. Ensure that all of our tests, whether they run on prem or in the cloud, record the list of packages and their versions before and after the zypper patch command.
Related: https://jira.suse.com/browse/TEAM-7106
VRs:
**cloud-based:**
SAPHanaSR-ScaleUp-PerfOpt:  https://openqa.suse.de/tests/15304469#downloads  (Added a file: `deploy_qesap_ansible-rpm-qa-before-patch-system.txt`)
sles4sap_gnome_saptune_delete_rename:  https://openqa.suse.de/tests/15303939#downloads (Added a file: `patch_and_reboot-rpm-qa-before-patch-system.txt`)
QAM:
create_hdd_ha_textmode_maintenance: https://openqa.suse.de/tests/15318162#downloads (Add `rpm_list.txt` in test module `patch_and_reboot`). …

Record the package list before and after zypper path

---

lib/sles4sap_publiccloud.pm

Solve a regression introduced by SSH muxing #20102
- Related ticket: https://jira.suse.com/browse/TEAM-9658
- Verification run: https://openqa.suse.de/tests/15375915#step/Crash_site_a-primary/432 (the critical part has passed)

Close SSH mux file before hanasr Crash test

---

tests/installation/agama.pm

It seems that we're confusing openQA which believes that we are already logged into console. 
The login happened during installation on agama-live. Therefore we need to call reset_consoles();
Test run https://openqa.opensuse.org/tests/4465322#live

Make sure to reset console after getting logs

---

lib/web_browser.pm
schedule/security/fips_ipmi/fips_crypt_web.yaml
tests/console/timesync.pm
tests/console/w3m_https.pm

w3m test was failing due to clock not syncronized on bare-metal SUT.
Added a simple time syncronization step to the IPMI schedule and removed useless FIPS pattern search in web modules
- Related ticket: https://progress.opensuse.org/issues/166337
- Needles: n/a
- Verification run: https://openqa.suse.de/tests/15378807
(note: VR fails on links because PackageHub is not yet available on 15-SP7, see [poo#166307](https://progress.opensuse.org/issues/166307))

Add time syncronization step to IPMI test

---

tests/console/cryptsetup.pm

Fix poo#165854
- Related ticket: https://progress.opensuse.org/issues/165854
- Verification run: https://openqa.suse.de/tests/15379176/modules/cryptsetup/steps/1/src

Satisfy password quality check requirements

---

lib/containers/bats.pm
tests/containers/buildah_integration.pm

Install pasta from upstream for buildah upstream tests
- 15-SP6: https://openqa.suse.de/tests/15380772 (some subtests failing for other reason)

containers: Install pasta from upstream for buildah upstream tests

---

tests/sles4sap/publiccloud/qesap_terraform.pm

Remove setting that is no more used in qe-sap-deployment project neither in any conf.yaml templates used in OSADO.
- Related ticket: https://jira.suse.com/browse/TEAM-8096
-  http://openqaworker15.qa.suse.cz/tests/296558 :green_circle:  deployment is fine without the setting
- http://openqaworker15.qa.suse.cz/tests/296559 :green_circle:  deployment is fine without the setting

Remove HANA_OS_MAJOR_VERSION setting

---

schedule/jeos/ssh-enroll.yaml
schedule/jeos/supportserver.yaml
tests/jeos/firstrun.pm

Since NICTYPE=tap [breaks](https://openqa.opensuse.org/tests/4454841) MicroOS Health Checker, move the first run wizard SSH enrollment test into JeOS/MinimalVM context. While at it, add some required variables to the schedule files so that the group definition can be cleaner.
https://progress.opensuse.org/issues/160664
http://rmarliere-openqa.qe.prg2.suse.org/tests/2282
http://rmarliere-openqa.qe.prg2.suse.org/tests/2283
- Schedule:
https://github.com/os-autoinst/opensuse-jobgroups/pull/509

Move SSH Enrollment test to JeOS

---

lib/LTP/utils.pm

Fix poo#166595: rpm -qi run in transaction need more time to complete.
- Related ticket: https://progress.opensuse.org/issues/166595
- Verification run: https://openqa.suse.de/tests/15390511

ltp: Add timeout to rpm -qi in log_versions

---

tests/jeos/glibc_locale.pm

- Related ticket: https://progress.opensuse.org/issues/158799
- Verification run: https://openqa.opensuse.org/tests/4467126#step/glibc_locale/82

Add timeout 10s delay for 'whoami' command in glibc_locale

---

tests/fips/openssl/openssl_pubkey_dsa.pm

Ticket: https://progress.opensuse.org/issues/165857
VRs:
- 15.6: https://openqa.suse.de/tests/15389045
- 15.4: https://openqa.suse.de/tests/15389046
- Micro 6.1: https://openqa.suse.de/tests/15389114

Rework openssl_pubkey_dsa to handle 15.6+

---

data/virt_autotest/guest_params_xml_files/sles_15_sp7_64_xen_hvm_uefi_with_power_management_x86_64.xml

A small fix. 
- Related ticket: https://progress.opensuse.org/issues/163682
[uefi-gi-guest_developing-on-host_developing-xen](http://openqa.suse.de/tests/15388338)

Correct install medium for sle15sp7 UEFI guest on XEN

---

lib/qesapdeployment.pm
tests/sles4sap/publiccloud/network_peering.pm
tests/sles4sap/qesapdeployment/test_cluster.pm

In qe-sap-deployment v0.31.0, the tag name aplied to VPC has been changed from Workspace to workspace.
Adapt the test code to this change, improve robustness.
- Related ticket: https://jira.suse.com/browse/TEAM-9676
- sle-15-SP6-Qesap-Aws-Byos-x86_64-BuildLATEST_AWS_SLE15_6_BYOS-qesap_aws_ibsmirror_peering_test@64bit -> http://openqaworker15.qa.suse.cz/tests/297070 :green_circle: http://openqaworker15.qa.suse.cz/tests/297070#step/test_cluster/683  `vpc_id` returned by the query is no more `none`

Fix tag name in vpc_id AWS query

---

tests/fips/openjdk/openjdk_fips.pm

* add legacy repo for 15.6 and greater
* remove opensuse since FIPS is not supported there
Ticket: https://progress.opensuse.org/issues/166160
VRs:
* 15.7: https://openqa.suse.de/tests/15414364
* 15.6: https://openqa.suse.de/tests/15414363
* 15.4: https://openqa.suse.de/tests/15414362

openjdk_fips: test 11 17 and 21

---

lib/utils.pm

Don't add a 'root' user with uid 1000 and don't add the testuser, if it's already present (even when not being uid 1000).
- Related failures: https://openqa.suse.de/tests/15401761#step/system_prepare/12 | https://openqa.opensuse.org/tests/4474167#step/host_config/6
- Follow-up of https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/20172 (quickfix)
- Verification runs: [https://openqa.suse.de/tests/15414352](https://openqa.suse.de/tests/15414352#step/system_prepare/29) | [https://openqa.opensuse.org/tests/4474248](https://openqa.opensuse.org/tests/4474248#step/host_config/38)

Fix testuser addition for cases where it is root

---

tests/migration/online_migration/zypper_migration.pm

We need create snapshot after migration to make sure rollback to correct version when issue happened.
- Needles: N/A
- Verification run: http://openqa.suse.de/tests/15414153#step/rollback/7

Add milestone flag for zypper_migration

---

lib/susedistribution.pm

Fixed console selection in Agama from F7 to F2
- Related ticket: https://progress.opensuse.org/issues/165830
- Needles: N/A
- Verification run: https://openqa.opensuse.org/tests/4474428#

Fix console selection in Agama

---

lib/qesapdeployment.pm
schedule/sles4sap/qesapdeploy/qesap.yml
t/09_qesapdeployment.t
tests/sles4sap/publiccloud/network_peering.pm
tests/sles4sap/qesapdeployment/test_cluster.pm
tests/sles4sap/qesapdeployment/test_crash.pm
tests/sles4sap/qesapdeployment/test_mirror.pm
tests/sles4sap/qesapdeployment/test_system.pm

Split the module about testing the deployment in 4 modules each one to focus on a different test area. Introduce a new test step to trigger a Crash in a node.
- Related ticket: https://jira.suse.com/browse/TEAM-9654
- http://openqaworker15.qa.suse.cz/tests/296642 :green_circle:  there are now 4 test module named `test_*`. Mirror test module correctly detect the setting and skip most of the stage that are not applicable.
- http://openqaworker15.qa.suse.cz/tests/296643 :green_circle:  test_mirror is running all the Azure related checks.
- http://openqaworker15.qa.suse.cz/tests/296867 :red_circle: fails in `test_mirror` but it systematically fails in existing code too http://openqaworker15.qa.suse.cz/tests/297022#next_previous
- sle-15-SP6-Qesap-Aws-Byos-x86_64-BuildLATEST_AWS_SLE15_6_BYOS-qe …

Split the qesap regression test module

---

data/virt_autotest/host_unattended_installation_files/combustion/script.aarch64.ep
data/virt_autotest/host_unattended_installation_files/combustion/script.x86_64.ep
data/virt_autotest/host_unattended_installation_files/ignition/config.ign.aarch64.ep
data/virt_autotest/host_unattended_installation_files/ignition/config.ign.x86_64.ep
lib/Utils/Backends.pm
lib/utils.pm
schedule/virt_autotest/install_guest_on_slem_kvm_host_ipxe_install.yaml
schedule/virt_autotest/install_guest_on_slem_kvm_host_usb_install.yaml
tests/installation/ipxe_install.pm
tests/jeos/prepare_firstboot_config.pm
tests/microos/selfinstall.pm

* **This** pull request aims to support automated SL Micro 6.1 iPXE installation by using PXE-capable kernel/initrd and pre-built disk image (indicated by ```rd.kiwi.install.image=MIRROR_HTTP/HDD_1```) which then will be deployed onto specified disk device (indicated by ```rd.kiwi.oem.installdevice=/dev/disk/by-id/INSTALL_DISK_WWN```) and configured by using ignition/combustion (indicated by ```FIRST_BOOT_CONFIG```).
* **Several** new subroutines in ```lib/utils.pm```:
* ```is_disk_image``` indicates pre-built disk image will used for OS installation.
* ```is_ipxe_with_disk_image```  indicates OS installation is performed with iPXE and disk image.
* **New** test module ```jeos/prepare_firstboot_config.pm```:
* **Aims** to generate ignition or combustion configuration file based on …

Automate iPXE host installation for SL Micro 6.1

---

tests/containers/bci_test.pm

- Related ticket: https://progress.opensuse.org/issues/166604
- Verification run: [centos]( https://openqa.suse.de/tests/15414842), [Liberty9]( https://openqa.suse.de/tests/15414841),  [Ubuntu](https://openqa.suse.de/tests/15414840
), [SLE-15-SP6](https://openqa.suse.de/tests/15414819)

Run kiwi container tests only on SLES

---

tests/security/create_swtpm_hdd/build_hdd.pm
tests/security/swtpm/swtpm_env_setup.pm

Missing required certtool to create a self-signed CA
- Related ticket: https://progress.opensuse.org/issues/166460
- Needles: n/a
- Verification run: https://openqa.suse.de/tests/15414810

Add missing gnutls package to nested image used to test swtpm

---

lib/grub_utils.pm
lib/opensusebasetest.pm
lib/susedistribution.pm
tests/installation/agama.pm
tests/installation/agama_reboot.pm

Following change gets us properly through grub on zdup scenario with USB boot and Agama.
This also ensures that we do not boot into Agama again after successful installation with USBBOOT.
* Handle same boot from local as for LIVE, while Agama is not LIVE, because we do have password set etc.
* Ensure that USB boot with agama goes for boot local
after installation
* Unlike with LIVE expect password on agama-installer which
otherwise behaves a lot like live
* Ensure that we boot local on zdup case with agama-installer
* On certain cases I managed to hit black screen shortly after congratulations window appeared
press a down button to eliminate it
* Use same needle as for grub_test which is simply grub2 not bootloader-grub2
- …

Agama improve grub handling in zdup and usb boot

---

data/virt_autotest/host_unattended_installation_files/autoyast/dev_host_12.xml.ep
tests/installation/ipxe_install.pm

- sle12sp5 host failed with `BRIDGE_STP='on'`, fg. https://openqa.suse.de/tests/15389928#step/install_package/11. And a few machines might fail to boot, see https://sd.suse.com/servicedesk/customer/portal/1/SD-167626. The explaination is https://sd.suse.com/servicedesk/customer/portal/1/SD-153019
- remove `WITHOUT_AUTOYAST_SECOND_STAGE=1` settings from sle12sp5 test suites on OSD webUI as there has no error pop-up any more. 
- Related ticket: https://progress.opensuse.org/issues/163682
test pass with `BRIDGE_STP='off'`, 
http://openqa.suse.de/tests/15390580
http://openqa.suse.de/tests/15389917
http://openqa.suse.de/tests/15390101

Prevent erroneous disabling of ports with STP=off for sle12

---

lib/kdump_utils.pm

- Related ticket: https://progress.opensuse.org/issues/166766
- Verification run:  https://openqa.suse.de/tests/overview?build=czerw%2Fos-autoinst-distri-opensuse%2320191&version=6.1&distri=sle-micro

kdump: Set crashkernel memory only when needed on a transactional system

---

lib/publiccloud/instance.pm
lib/sles4sap_publiccloud.pm
lib/sles4sap_publiccloud_basetest.pm
t/12_sles4sap_publicccloud.t
tests/sles4sap/publiccloud/qesap_terraform.pm

A regression was introduced into the HanaSR Crash tests in the cloud by 892dffc96dc6fe061a442c790049479751bdac3f which moved common SSH options out of the CLI and into a local `.ssh/config`. A fix for this regression was proposed in 0fe1c3226629e6e7d795237adb05809aaf9da3a5, but this turned out to be not entirely stable, so instead this commit rolls back 0fe1c3226629e6e7d795237adb05809aaf9da3a5 and selectively rolls back some of the changes from 892dffc96dc6fe061a442c790049479751bdac3f only when the test code runs in the HanaSR scenario. To this end, HanaSR tests will inject CLI SSH options including `-F none` via `publiccloud::instance::ssh_opts` class attribute right after class instances are created.
Changes include:
* A new method in `sles4sap_publiccloud_basetest` class to set the CLI …

Move Public Cloud ssh opts to CLI in HanaSR tests

---

lib/main_containers.pm
tests/containers/skopeo.pm

PR #20009 broke some tests which did not have podman pre-installed but only docker. This PR will make Skopeo tests run with either Podman or Docker depending on the use-case.
- Related test failure: https://openqa.suse.de/tests/15398447#step/skopeo/56
- Needles: N/A
- Verification run: http://dirtman.qe.prg2.suse.org/tests/41

Make Skopeo tests work with either Docker or Podman runtimes

---

tests/microos/disk_boot.pm

It has been observed that x86_64 is stalling when doing needle matchin of the grub screen, similar to what happened with aarch64 jobs for 6.0 maintenance and 6.1 jobs.
VRs:
[Microos x86_64](https://openqa.opensuse.org/tests/4482847#)
[MicroOS aarch64](https://openqa.opensuse.org/tests/4482848#)
[SLM 6.0 x86_64](https://openqa.suse.de/tests/15442938#)
[SLM 6.0 aarch64](https://openqa.suse.de/tests/15442939#)
[SLM 6.1 x86_64](https://openqa.suse.de/tests/15426133)
[SLM 6.1 aarch64](https://openqa.suse.de/tests/15442940#)
[SLM 5.5 x86_64](https://openqa.suse.de/tests/15442941#)
[SLM 5.5 aarch64](https://openqa.suse.de/tests/15442942#)

Skip grub needle check for Micro 6.0+

---

tests/sles4sap/ipaddr2/deploy.pm

A regression was introduced into the IpAddr2 tests  by 892dffc96dc6fe061a442c790049479751bdac3f which moved common SSH options out of the CLI and into a local `.ssh/config`. 
- Related ticket:  https://jira.suse.com/browse/TEAM-8721
sle-15-SP5-SapCloud-Azure-Payg-x86_64-BuildLATEST_AZURE_SLE15_5_PAYG-ipaddr2_azure_test@64bit
- http://openqaworker15.qa.suse.cz/tests/297307 :green_circle: 
- http://openqaworker15.qa.suse.cz/tests/297309

Ipaddr2 stabilize

---

tests/installation/zdup.pm

Run zdup from 15.6 -> 16.0 against REPO_0 since we have now Agama and no longer have an offline media with repo
The dup itself is expected to fail, but REPO_0 repository should be accessible.
- Verification run:  https://openqa.opensuse.org/tests/4484666

Use REPO_0 for zdup by default with Agama

---

data/journal_check/bug_refs.json

Ignore journal log: kernel: SED: plpks not available
- Verification run: https://openqa.suse.de/tests/15423924#step/journal_check/27

Ignore journal log: kernel: SED: plpks not available

---

tests/microos/disk_boot.pm

This fixes the bug created by https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/20168
where the DVD jobs use disk_boot as well after yast installation (https://openqa.suse.de/tests/15447646#step/disk_boot/4)
VR: https://openqa.suse.de/tests/15454550#step/disk_boot/1

SL Micro boot: use grub needle for ISO installations

---

lib/containers/common.pm
tests/containers/bci_prepare.pm
tests/containers/host_configuration.pm
tests/containers/install_updates.pm
tests/containers/update_host.pm

In both CentOS and Liberty Linux the yum tool has been succeeded by dnf and has become a symbolic link to it, which makes it safe to switch all occurrences in lib/containers and tests/containers.
- Link: https://progress.opensuse.org/issues/166634
- Verification runs: http://rmarliere-openqa.qe.prg2.suse.org/tests/2340 http://rmarliere-openqa.qe.prg2.suse.org/tests/2341

containers: Use 'dnf' instead of 'yum'

---

tests/installation/agama.pm

* Combination of sleep and timeout in previous run was not good. We got into situation where screen was black etc
* This is bit more simple yet more time efficient
- Verification run 1: https://openqa.opensuse.org/tests/4487031#live
- Verification run 2: https://openqa.opensuse.org/tests/4487030#live

Rework installation timeout for Agama

---

tests/installation/agama.pm

* Agama seems to randomly flash congratulations screen before installation begins. This confuses openQA
Related to https://github.com/openSUSE/agama/issues/1616
- Verification run https://openqa.opensuse.org/tests/4487115

Agama assert install progress before timeout loop

---

schedule/yam/test_cases/raid0_sle_gpt.yaml
schedule/yam/test_cases/raid_sle_gpt.yaml

Use rebooter to reboot system with RAID configration
- Related ticket: https://progress.opensuse.org/issues/166256
- Verification run: https://openqa.suse.de/tests/overview?distri=sle&version=15-SP7&build=18.1&groupid=220

Add reboot scenario after raid installation

---

lib/main_containers.pm

We test the toolbox container updates in a separate group. They should not be part of staging updates.
- Verification runs: [SLEM 6.0 Staging](https://openqa.suse.de/tests/15469238) (no toolbox) | [MicroOS](https://openqa.opensuse.org/tests/4490090) (contains toolbox)

Skip toolbox test in staging

---

lib/bootloader_setup.pm
tests/microos/selfinstall.pm

This PR aims to install SLE Micro to a specified disk, so that SLES VT tests can run on the same UEFI machine with SLE Micro test machine, without "secure boot" problem mentioned in https://progress.opensuse.org/issues/153037#note-36 by Julie.
- Related ticket: https://progress.opensuse.org/issues/166712
- SLM 6.1 host: https://openqa.suse.de/tests/15426202#step/bootloader_uefi/27
- SLM 6.0 GM host verification: https://openqa.suse.de/tests/15461667#step/login_console/5 (simulate 6.0  job by passing ISO=SL-Micro.x86_64-6.0-Default-SelfInstall-GM.iso)
- more evidence jobs for claiming that installing on the same disk solves the "secure boot" problem: https://progress.opensuse.org/issues/166712#note-11

[Virtualization][SLM] Specify disk id in usb host installation

---

tests/console/suseconnect_scc.pm

This way, in case of failures, we can see what is the actual output and check what the issue is

Don't use grep for SUSEConnect --status-text

---

tests/ha/cluster_boot_mgmt.pm

This pr overrides the `post_run_hook` for `cluster_boot_mgmt` to remove `record_avc_selinux_alerts ` which caused needle failures.
Tests were failing due to unexpected output from the above function, which is included in the parent `post_run`, which led the needle (which expected a clean terminal) to not match. This pr overrides the post run hook, and only removes this function (everything else is copied from the parent function).
Example of failure: https://openqa.suse.de/tests/15463069#step/cluster_boot_mgmt#1/19
- Related ticket: -
- Verification run: https://openqa.suse.de/tests/15463569#dependencies

Override parent post_run_hook

---

lib/qesapdeployment.pm
lib/sles4sap_publiccloud.pm
lib/sles4sap_publiccloud_basetest.pm
t/09_qesapdeployment.t
t/12_sles4sap_publicccloud.t
tests/sles4sap/publiccloud/qesap_ansible.pm

Be sure to always call terraform destroy.
Move the EXT to eventually unlock the terminal in a more generic place. Return immediately is cleanup has been already performed. Move log collection from the basetest to the library function.
- Related ticket: https://jira.suse.com/browse/TEAM-9586 and https://jira.suse.com/browse/TEAM-9684
sle-15-SP6-Qesap-Azure-Byos-x86_64-BuildLATEST_AZURE_SLE15_6_BYOS-qesap_azure_saptune_test
-  http://openqaworker15.qa.suse.cz/tests/297688 :green_circle: 
sle-15-SP6-Qesap-Aws-Byos-x86_64-BuildLATEST_AWS_SLE15_6_BYOS-qesap_aws_fencing_native_test
- http://openqaworker15.qa.suse.cz/tests/297698 :green_circle: 
sle-15-SP6-Qesap-Aws-Byos-x86_64-BuildLATEST_AWS_SLE15_6_BYOS-qesap_aws_fencing_sbd_test
-  http://openqaworker15.qa.suse.cz/tests/297695 :green_circle: …

Reorganize order of sles4sap PC cleanup

---

lib/main_micro_alp.pm
tests/qemu/qemu.pm

Add ppc64le image to osd SL Micro6.1 Virt 
- Related ticket: https://progress.opensuse.org/issues/164093
[sle-micro-6.1-Default-ppc-4096-SelfInstall-ppc64le-Build16.2-slem_installation_virt](https://openqa.suse.de/tests/15428924)
[sle-micro-6.1-Default-ppc-512-SelfInstall-ppc64le-Build16.2-slem_installation_virt](https://openqa.suse.de/tests/15437728)
[sle-micro-6.1-Default-ppc-4096-ppc64le-Build16.2-slem_virtualization](https://openqa.suse.de/tests/15437748)
[sle-micro-6.1-Default-ppc-512-ppc64le-Build16.2-slem_virtualization](https://openqa.suse.de/tests/15437729)

virt_autotest: Add ppc64le image to osd SL Micro6 Virt

---

tests/microos/disk_boot.pm

Some of the jobs that create HDDs for other jobs disable the grub timeout, and the grub screen will be waiting for input without timeout. We need a way to tell the job if it should expect that screen or not.
https://progress.opensuse.org/issues/166892
MicroOS:
[MicroOS DVD x86_64](https://openqa.opensuse.org/tests/4492280#)
[MicroOS image x86_64](https://openqa.opensuse.org/tests/4492281#)
[MicroOS image aarch64](https://openqa.opensuse.org/tests/4492282#)
SL Micro:
[5.5 create job aarch64](https://openqa.suse.de/tests/15477816#)
[5.5 toolbox test using that hdd aarch64](https://openqa.suse.de/tests/15477813#) with `KEEP_GRUB_TIMEOUT=0`
[5.5 toolbox test using that hdd x86_64](https://openqa.suse.de/tests/15477876) with `KEEP_GRUB_TIMEOUT=0`
[5.5 regular test …

Enhance disk_boot for SLMicro

---

lib/susedistribution.pm

Revert these lines regarding the graphical tty used by agama installer:
https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/20189/files#diff-cdfc5d4c733095953bb02e1338918cc890bb886a8a775280b70917e5cdb2e797R478-R483
once this has been merged https://github.com/openSUSE/agama/pull/1619

Revert back to use tty7 as graphical one for agama

---

tests/sles4sap/sap_suse_cluster_connector.pm

Use choose_node to get remote node hostname
Test cases hit a sporadic issue, for example: https://openqa.suse.de/tests/15468847#step/sap_suse_cluster_connector/78
The  serial output sporadically contains one unexpected line which makes `validate_script_output` failed:
```
[ 2944.689003] SAPInstance(rsc_sap_EN2_ASCS00)[23436]: INFO: systemd service SAPEN2_00 is active
```
So using `choose_node()` instead.
- Related ticket: No
- Needles: No
https://openqa.suse.de/tests/15477943#step/sap_suse_cluster_connector/55 (passed)

Use choose_node to get remote node hostname

---

schedule/yam/agama.yaml
tests/yam/agama/agama_grub2.pm

##
- Related ticket: https://progress.opensuse.org/issues/167024
- Needles: N/A
- [**agama_default**](https://openqa.opensuse.org/tests/overview?version=agama-9.0&build=hjluo%2Fos-autoinst-distri-opensuse%23agama_grub2&distri=opensuse)
##

Make stable agama in ppc64le by processing grub2

---

lib/qesapdeployment.pm

From `az role assignment create --help` :
````
--assignee-object-id          : Use this parameter instead of '--assignee' to bypass Graph API
invocation in case of insufficient privileges. This parameter
only works with object ids for users, groups, service
principals, and managed identities. For managed identities use
the principal id. For service principals, use the object id and
not the app id.
--assignee-principal-type     : Use with --assignee-object-id to avoid errors caused by
propagation latency in Microsoft Graph.  Allowed values:
ForeignGroup, Group, ServicePrincipal, User.
````
This should solve the problem mentioned in the ticket.  However since this error happens in cloud infra, so we can't reproduce the error on our side.  But according to the documentation, this commit …

lib/qesapdeployment: use object-id to prevent slowness in cloud

---

lib/sles4sap_publiccloud.pm

HanaSR test has a command to crash the SUT to be sent through ssh to the remote SUT. There is code after sending this command to check the prompt is available and eventually unlock it.
Fix an issue where this prompt checking break the next command sending procedure.
- Related ticket:  https://jira.suse.com/browse/TEAM-9658
- http://openqaworker15.qa.suse.cz/tests/297858
-  http://openqaworker15.qa.suse.cz/tests/297859 :green:
Crash command typed here at `17:31:28`
```
[2024-09-20T17:31:28.601214+02:00] [debug] [pid:58842] <<< consoles::serial_screen::type_string(cmd="backend_type_string", text="ssh
```
Execution immediately returns from `script_run` and `run_ssh_command`. At this point `stop_hana` calls `wait_serial` at `17:31:28`
```
[2024-09-20T17:31:28.605581+02:00] [debug] [pid:58700] …
```

Change the prompt wait  after crash approach

---

tests/sles4sap/publiccloud/qesap_terraform.pm
tests/sles4sap/qesapdeployment/configure.pm

With https://jira.suse.com/browse/TEAM-9540, having the az_sas_token value defined in qesap.py's YAML configuration files is no longer necessary, as qesap.py will calculate a SAS token dynamically if a valid key name was provided in az_key_name.
this PR doesn't deal with trento code because it hasn't updated for a long time.
- Related ticket: https://jira.suse.com/browse/TEAM-9668
- sle-15-SP6-Qesap-Aws-Byos-qesap_aws_r58xlarge_test                                                                      
- https://openqaworker15.qa.suse.cz/tests/297682 :green_circle: 
- 15-SP6-HanaSr-Aws-Byos-hanasr_aws_test_saptune_fencing_native
- https://openqaworker15.qa.suse.cz/tests/297678 :green_circle: 
- 15-SP5-HanaSr-Azure-Byos-hanasr_azure_test_sapconf_spn
- …

Remove the code related to calculate az_sas_token

---

tests/jeos/firstrun.pm

Replace the previous condition with a more targeted and correct one. This fixes the check for community JeOS on RPi.
- Related ticket: https://openqa.opensuse.org/tests/4452052#step/firstrun/54
- Verification run: https://openqa.opensuse.org/tests/4499469#live

jeos/firstrun.pm: Fix check for GPT vs MBR partition table

---

lib/main_publiccloud.pm
lib/publiccloud/basetest.pm
tests/publiccloud/cloud_netconfig.pm
tests/publiccloud/img_proof.pm
tests/publiccloud/prepare_instance.pm
tests/publiccloud/run_ltp.pm
tests/publiccloud/storage_perf.pm

Refactoring the `publiccloud::basetest::_cleanup` in a way that:
* Every test module creating `$provider` and `$instance` should save it to `$args`.
* Every custom `post_fail_hook` and `post_run_hook` should use `$self->{run_args` for accessing above objects.
* Every 'third party' (e.g. console, container, ...) test should not have `fatal` flag on Public Cloud runs.

Refactor publiccloud::basetest::_cleanup

---

schedule/sles4sap/qam/common/qam_hana_cluster_node.yaml
schedule/sles4sap/qam/common/qam_install_sles4sap.yaml
schedule/sles4sap/qam/common/qam_sles4sap_fips_mau-extratests.yaml
schedule/sles4sap/qam/common/qam_sles4sap_test.yaml
schedule/sles4sap/qam/common/qam_test_hana.yaml
schedule/sles4sap/qam/common/qam_test_netweaver.yaml
schedule/sles4sap/qam/common/sles4sap_fips_crypt_openjdk.yaml
tests/sles4sap/hana_cluster.pm

Include FIPS modules in SLES for SAP schedules.
- Related ticket: https://progress.opensuse.org/issues/166637
- Needles: N/A
- Verification run: http://mango.qe.nue2.suse.org/tests/6221, https://openqa.suse.de/tests/overview?distri=sle&build=VR4PR20235&version=15-SP5
**Note**: verification runs are only checking the changes do not introduce regression in existing tests, as such they do not run with either `FIPS_ENABLED=1` or `FIPS_INSTALLATION=1`. These tests will be scheduled after the PR is merged.

Include FIPS modules in SLES for SAP schedules

---

.github/checklist.yml

Confluence page links are not stable against page renaming. Using the shortlink provides a permalink, which will redirect always to the same page, even if moved or renamed.
- Follow-up of https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/20249

Use Permalink for Confluence page

---

tests/fips/fips_setup.pm

Followup from #20248 , fixes Tumbleweed FIPS tests 
(note that FIPS is not officially supported on Tumbleweed)
- Related ticket: https://progress.opensuse.org/issues/167063
- Needles: no
- https://openqa.opensuse.org/tests/4503506
- https://openqa.opensuse.org/tests/4503505

Check BOOT_HDD_IMAGE var only on SLE

---

data/yam/agama/auto/default_leap.json
lib/Yam/Agama/Pom/AgamaUpAndRunningPage.pm
test_data/yam/agama_leap.yaml

- Related ticket: https://progress.opensuse.org/issues/167087
- Needles: N/A
- Verification run: https://openqa.opensuse.org/tests/overview?version=agama-9.0&distri=opensuse&build=lemon-suse%2Fos-autoinst-distri-opensuse%23add-agama-test-for-leap

Add agama test for leap for auto-installation

---

tests/jeos/firstrun.pm

[Tumbleweed Minimal-VM](https://openqa.opensuse.org/tests/4504116)
[MicroOS](https://openqa.opensuse.org/tests/4504115)
[Micro 6.1](https://openqa.suse.de/tests/15518880#)
[SLE16](https://openqa.suse.de/tests/15518129#step/firstrun/13) -> failure not related, bug found

Enable SSH Enrollment for Firsboot in SLE 16

---

lib/registration.pm
tests/console/suseconnect_scc.pm

Register Micro Extention for sle-micro 6.0
NOTE: currently version<6.0 has no extention and 6.1 exist issue.
- Related ticket: https://progress.opensuse.org/issues/164382
- Needles: na
sle-micro 6.0
x86
https://openqa.suse.de/tests/15252872#step/suseconnect_scc/85
aarch64
https://openqa.suse.de/tests/15252910#step/suseconnect_scc/86
s390x
https://openqa.suse.de/tests/15252909#step/suseconnect_scc/79
sle-micro 6.1
https://openqa.suse.de/tests/15474414#step/suseconnect_scc/79 
aarch64
https://openqa.suse.de/tests/15437717#step/suseconnect_scc/80
390
https://openqa.suse.de/tests/15437716#step/suseconnect_scc/73

Register Micro Extention for sle-micro

---

tests/x11/network/NM_wpa2_enterprise.pm

Add `assert_and_click` to make NM_wpas_enterprise more robust.
- Related ticket: https://progress.opensuse.org/issues/167096
- Needles: already added when debugging on O3
- Verification run: https://openqa.opensuse.org/tests/4494603#step/NM_wpa2_enterprise/32

Fix NM_wpas_enterprise failure on TW

---

tests/console/perl_bootloader.pm

Related to [poo#165686](https://progress.opensuse.org/issues/165686) and [PR](https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/20066)
I am updating the version check to include 15-SP7 and sle-micro6.1 as the perl-Bootloader module is scheduled on these products. 
It will fail without the change since the package is still named `perl-Bootloader` on these products.
- Verification run: https://openqa.suse.de/tests/overview?build=cedvid%2Fos-autoinst-distri-opensuse%2320268

Update version check to include SP7 and micro6.1

---

tests/virtualization/universal/hotplugging_HDD.pm

The disk name changed to `vda` in sle15sp7. It was `vdb` in previous release.
- Related ticket: https://progress.opensuse.org/issues/167102
[uefi-gi-guest_developing-on-host_sles12sp5-kvm](https://openqa.suse.de/tests/15489197#step/hotplugging_HDD/74)
[gi-guest_developing-on-host_developing-kvm](https://openqa.suse.de/tests/15489200#step/hotplugging_HDD/78)

Adapt disk name change within sle15sp7 kvm guest in hotplug HDD test

---

lib/autoyast.pm

When SCC ADDON is defined in autoyast, get_var('SCC_ADDONS') returns undef, it causes warning: Use of uninitialized value in pattern match (m//), set empty default value get_var('SCC_ADDONS', '') for safe.
- Related ticket: https://progress.opensuse.org/issues/167323
- Needles: N/A
- Verification run: http://openqa.suse.de/tests/15526241

Set default value for get_var('SCC_ADDONS') in lib/autoyast.pm to avoid uninitialized value

---

data/sles4sap/angi_hana_cluster.conf
data/sles4sap/hana_cluster_cln.conf
data/sles4sap/hana_cluster_msl.conf
lib/sles4sap.pm
tests/sles4sap/hana_cluster.pm
tests/sles4sap/monitoring_services.pm
tests/sles4sap/sap_suse_cluster_connector.pm

1. From 15-SP4 to 15-SP7, use 'promoted' and 'unpromoted'.
2. For 15-SP3, 15-SP2 and 12-SP5, use 'Master' because these version
don't support 'promoted' role
3. Uniform the resource name in hana_cluster and angi_hana_cluster
configuratoin files for 15-SP4~15-SP7.
Related: https://jira.suse.com/browse/TEAM-9635
VRs:
15-SP7: https://openqa.suse.de/tests/15486508#  (softfail)
15-SP6: https://openqa.suse.de/tests/15517245#  (Softfail)
15-SP5: https://openqa.suse.de/tests/15485544#  (Softfail)
15-SP4: https://openqa.suse.de/tests/15485537#  (Passed)
15-SP3: https://openqa.suse.de/tests/15517248#  (Passed)
15-SP2: https://openqa.suse.de/tests/15486505#  (Passed)
12-SP5: https://openqa.suse.de/tests/15485651#  (Passed)
Angi VR:
15-SP6: https://openqa.suse.de/tests/15486526#  (Softfail)
15-SP7: …

Cleanup cluster configuration

---

tests/sles4sap/cloud_netconfig/deploy.pm

Remove ssh config file written by the PC factory
- Related ticket: https://jira.suse.com/browse/TEAM-8721
Same approach of https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/20194
- sle-15-SP5-SapCloud-Azure-Payg-x86_64-BuildLATEST_AZURE_SLE15_5_PAYG-cloud_netconfig_azure_test@64bit -> http://openqaworker15.qa.suse.cz/tests/298221 :green_circle:

Remove ssh config for cloud_netcofig

---

schedule/sles4sap/qam/common/qam_install_sles4sap.yaml

The module `fips/openjdk/prepare_env` needs to be included after `fips/fips_setup` in the create_hdd job if we intend to use the generated qcow2 image to be tested later with `fips/openjdk/openjdk_fips` test module.
- Related ticket: https://progress.opensuse.org/issues/166637
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/15527215#

Add fips/openjdk/prepare_env test module to create_hdd job

---

lib/containers/containerd_nerdctl.pm

Increase the currently used nerdctl version to 1.7.7.
- Verification run: https://openqa.opensuse.org/tests/4511286

Increase default nerdctl version

---

tests/yam/agama/import_agama_profile.pm
tests/yam/agama/patch_agama_tests.pm

- Related ticket: [poo#166133](https://progress.opensuse.org/issues/166133)
- Verification run: [overview](https://openqa.opensuse.org/tests/overview?build=build-issues-166133&version=agama-10.0)

Fix Agama: add dmesg before and after assert_script_run

---

lib/sles4sap/console_redirection.pm
lib/sles4sap/sap_deployment_automation_framework/deployment.pm
t/19_console_redirection.t
t/20_sdaf_deployment_library.t

Fix SDAF deployer cleanup failures
1. Add Ctrl-C if script timeout happens on "deployer VM", so following cleanup related command can be sent to serial terminal of "worker" successfully
2. Add retry for SDAF destroy
**Related ticket**: [TEAM-9647](https://jira.suse.com/browse/TEAM-9647)
[SDAF] SDAF_PRD_deploy_HanaSR failed to do deploy cleanup when failed on: configure_deployer & deploy_workload_zone
**Note**: 
1. It is very hard to reproduce the failing scenarios mentioned in JIRA ticket but I tried to modify the test code to make test case failed on expected test steps in order to verify the code changes as much as possible.
2. The retry code change in [lib/sles4sap/sap_deployment_automation_framework/deployment.pm](https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/20246/fi …

Fix SDAF deployer cleanup failures

---

tests/containers/bci_test.pm

As preparation step for moving from Libert/RES/RHEL to MLS, add mls to the host version checks.
- Related ticket: https://progress.opensuse.org/issues/167377
- Verification runs: https://openqa.suse.de/tests/15537850

Add MLS to Host_version checks

---

schedule/yam/agama_auto_ppc64le.yaml
schedule/yam/agama_ppc64le.yaml

Fix of Agama post installation grub check.
- Related ticket: https://progress.opensuse.org/issues/167024
- Needles: N/A
- Verification run: In progress

Change agama_grub2 to grub_test for x86_64 and aarch64

---

tests/sles4sap/hana_cluster.pm

Commit 285bd34454e3472e5553ef8678f67b5584bfc39a included changes in schedules and in the test module `sles4sap/hana_cluster` for FIPS Vendor Affirmation tests. The changes on the test module are not required by the certification, and instead break the test, so this commit partially reverts 285bd34454e3472e5553ef8678f67b5584bfc39a (only changes on `tests/sles4sap/hana_cluster.pm`)
- Related ticket: https://progress.opensuse.org/issues/166637
- Needles: N/A
- Verification run: N/A (this reverts changes done on #20235 )

Revert changes on tests/sles4sap/hana_cluster from 285bd34

---

lib/qesapdeployment.pm
lib/sles4sap/azure_cli.pm
t/15_qesap_azure.t
t/21_sles4sap_azure_cli.t

Move this function to a more generic az wrapper library.
- Related ticket: https://jira.suse.com/browse/TEAM-9365
sle-15-SP5-HanaSr-Azure-Byos-x86_64-Build15-SP5_2024-09-26T02:03:14Z-hanasr_azure_test_sapconf_msi@az_Standard_E4s_v3 
- http://openqaworker15.qa.suse.cz/tests/298308 :green_circle:  validation takes place somewhere after http://openqaworker15.qa.suse.cz/tests/298308#step/deploy_qesap_terraform/441
- http://openqaworker15.qa.suse.cz/tests/298310
sle-15-SP5-HanaSr-Azure-Byos-x86_64-Build15-SP5_2024-09-26T02:03:14Z-hanasr_azure_test_sapconf_spn az_Standard_E4s_v3
- http://openqaworker15.qa.suse.cz/tests/298309
- http://openqaworker15.qa.suse.cz/tests/298311

Move qesap_az_validate_uuid_pattern

---

lib/sles4sap/ipaddr2.pm
t/22_ipaddr2.t
tests/sles4sap/ipaddr2/configure.pm

It is to avoid zypper exit code 106 in BYOS images configured with cloud-init, the first time zypper is called for a sanity check
Related ticket: https://jira.suse.com/browse/TEAM-8721
sle-15-SP5-SapCloud-Azure-Byos-x86_64-BuildLATEST_AZURE_SLE15_5_BYOS-ipaddr2_azure_test
-  http://openqaworker15.qa.suse.cz/tests/298312 :green_circle: 
- http://openqaworker15.qa.suse.cz/tests/298319 :green_circle: 
sle-15-SP5-SapCloud-Azure-Byos-x86_64-BuildLATEST_AZURE_SLE15_5_BYOS-ipaddr2_azure_test
- http://openqaworker15.qa.suse.cz/tests/298296
- http://openqaworker15.qa.suse.cz/tests/298304
- http://openqaworker15.qa.suse.cz/tests/298320
sle-15-SP5-SapCloud-Azure-Payg-x86_64-BuildLATEST_AZURE_SLE15_5_PAYG-ipaddr2_a …

Run zypper ref before using zypper in sanity test

---

tests/kernel_performance/install_qatestset.pm

SLEperf requests VER_CFG values, when the test case is triggered automatically, let us generate it by default values.
- Related ticket: https://progress.opensuse.org/issues/167326
- Needles: N/A
- Verification run:https://openqa.suse.de/tests/15526364

When VER_CFG is not defined, generate them by default value

---

schedule/functional/extra_tests_textmode.yaml
schedule/qam/common/mau-extratests2.yaml
tests/console/pciutils.pm

- Related ticket: https://progress.opensuse.org/issues/165252
[opensuse](https://openqa.opensuse.org/tests/overview?distri=opensuse&build=rfan0927)
[sle](https://openqa.suse.de/tests/overview?build=rfan0927&distri=sle)
**Please ignore the failure on sle15sp7, it is https://bugzilla.suse.com/show_bug.cgi?id=1230995**

Introduce smoke tests for PCI Utils

---

lib/Distribution/Sle/AgamaDevel.pm
lib/DistributionProvider.pm
lib/Yam/Agama/Pom/Opensuse/AgamaUpAndRunningPage.pm
lib/Yam/Agama/Pom/Sle/AgamaUpAndRunningPage.pm
test_data/yam/agama_sle.yaml

We have added support for SLE agama schedule in OSD. Removed validation stage, it will need more work from developers.
- Related ticket: https://progress.opensuse.org/issues/167239
- Needles: N/A
- x86_64: https://openqa.suse.de/tests/15527936
- aarch64: https://openqa.suse.de/tests/15527941
- ppc64le: https://openqa.suse.de/tests/15527958# (Not working added grub needle)
- s390x: Not tested probably needs another round.

Boot agama in OSD in architectures using qemu

---

data/yam/autoyast/autoyast_scc_up.xml

The current autoupgrade profile didn't open the receive update flag. Open it to receive latest updates during migration via autoyast profile to fix the failure in migration VR.
- Related ticket: https://progress.opensuse.org/issues/161225
- Needles: n/a
- Failure: [migration job](https://openqa.suse.de/tests/15525185#step/installation/1) 
- Verification run: [create 12sp5 image ](https://openqa.suse.de/tests/15523512); [migration job](https://openqa.suse.de/tests/15526343) 
- Related mr: https://gitlab.suse.de/qe-yam/openqa-job-groups/-/merge_requests/334

Open receive update flag for autoupgrade profile.

---

lib/Distribution/Sle/16Latest.pm
lib/DistributionProvider.pm

- Related ticket: https://progress.opensuse.org/issues/167087
- Needles: N/A
https://openqa.opensuse.org/tests/4514146#step/agama_auto/1 agama-default-auto on x86_64
https://openqa.opensuse.org/tests/4514164#   agama-default on aarch64

Adapt distri pattern for Leap 16.0

---

tests/sles4sap/qesapdeployment/test_cluster.pm
tests/sles4sap/qesapdeployment/test_crash.pm
tests/sles4sap/qesapdeployment/test_mirror.pm
tests/sles4sap/qesapdeployment/test_system.pm

Remove cluster destroy from the test modules of qesap regression: in this way all test modules can run even if there's a failure in one of them. Deployment destroy is delegated to destroy module.
This is follow-up of https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/20156
Related ticket: https://jira.suse.com/browse/TEAM-9654
- sle-15-SP3-Qesap-Gcp-Payg-x86_64-BuildLATEST_GCE_SLE15_3_PAYG-qesap_gcp_sapconf_test
-  http://openqaworker15.qa.suse.cz/tests/297853 This one is known to have test_system to fail due to a known package bug

Remove deployment destroy from qesap regression

---

data/sles4sap/qe_sap_deployment/sles4sap_gcp_generic.yaml

Add GCP generic HansSR conf.yaml template
Related ticket:  
TEAM-9645 - Add GCP variant for HanaSR regression in ow15  
Other related PR/MR:  
MR: https://gitlab.suse.de/qa-css/openqa_ha_sap/-/merge_requests/792
MR: https://gitlab.suse.de/qa-css/qe-sap-deployment-bot/-/merge_requests/51  
VR:  
https://openqaworker15.qa.suse.cz/tests/overview?distri=sle&version=15-SP6&build=add-hanasr-GCP&groupid=42 (the crash failure is known)
Images used:
-   PUBLIC_CLOUD_IMAGE_ID=suse-byos-cloud/sles-15-sp6-sap-byos-v20240807-x86-64
-   PUBLIC_CLOUD_IMAGE_ID=suse-sap-cloud/sles-15-sp6-sap-v20240807-x86-64 (job id=298413,298414,298415,298416)
Hanasr cases:
-   hanasr_gcp_test_saptune_fencing_native_stop_kill
-   hanasr_gcp_test_saptune_fencing_native_crash
-   hanasr_gcp_test_fencing_sbd_stop_kill
- …

Add GCP generic HansSR conf.yaml template

---

schedule/functional/extra_tests_textmode.yaml
schedule/functional/extra_tests_textmode_phub.yaml

Fixed packagehub related test modules on TW and Leap
- Related PR: https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/20294
- Related MR: https://gitlab.suse.de/qe-core/qa-sle-functional-userspace/-/merge_requests/239
- Verification run:  https://openqa.opensuse.org/tests/4519896
https://openqa.opensuse.org/tests/4519898

Fixed packagehub related test modules on TW and Leap

---

schedule/functional/extra_tests_textmode.yaml
schedule/qam/common/mau-extratests2.yaml

https://progress.opensuse.org/issues/167560
**This is a workaround, upcoming fix is https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/20310**
VR: 
http://openqa.suse.de/t15558346
http://openqa.suse.de/t15558347
http://openqa.suse.de/t15558348

Load pciutils test before year_2038_detection

---

data/virt_autotest/host_unattended_installation_files/autoyast/dev_host_12.xml.ep
data/virt_autotest/host_unattended_installation_files/autoyast/dev_host_15.xml.ep
tests/installation/ipxe_install.pm
tests/installation/usb_install.pm
tests/virt_autotest/login_console.pm

This PR aims to solve the problem in https://progress.opensuse.org/issues/166712#note-23, for which if a job with secure boot enabled is installed onto a disk, that is different from the disk that our virtualization jobs will install on(for both sles and sle micro), the installed virtualization host OS will not boot successfully.
Solution is to erase disks before real installation starts:
- for sles, add in autoyast pre-script the disk erasing script
- for sle micro, at ipxe_install, call prepare_disks
- Related ticket: https://progress.opensuse.org/issues/166712
```
- kermit(uefi)
- guided_btrfs secure boot test: https://openqa.suse.de/tests/15547054 (trigger the issue)
- sles vt 12sp5 kvm host: https://openqa.suse.de/tests/15547055
- guided_btrfs secure boot test: …
```

[Virtualization]: wipe all disks before installation for sles and slm

---

tests/virt_autotest/login_console.pm

This is a known issue, set it softfailed for sles15s7 just like sles15sp6
Related ticket: https://progress.opensuse.org/issues/167509
Needles: n/a
Verification run: http://openqa.qa2.suse.asia/tests/73536

Add softfailed for sles15s7 due to bug: 1218798

---

tests/security/yast2_users/add_users.pm

Using apparmortest as base breaks the test case in case SELinux is installed as main LSM, as the test tries to restart the systemd apparmor service. As there is no need to use apparmortest as base for this specific scenario, change base to consoletest.
- Needles: N/A
- failed before: https://openqa.opensuse.org/tests/4515798 
- good after: https://openqa.opensuse.org/tests/4521502

Change base from apparmortest to consoletest for add_users.pm

---

schedule/qam/common/qam-minimal-full.yaml

- Related ticket:  https://progress.opensuse.org/issues/166988
- Verification run: https://openqa.suse.de/tests/overview?build=cedvid%2Fos-autoinst-distri-opensuse%2320238

Exclude yast2 modules from qam-minimal-full

---

data/microos/ignition/config.ign
lib/main_ltp.pm
lib/power_action_utils.pm
lib/transactional.pm
tests/installation/ipxe_install.pm
tests/microos/install_image.pm
variables.md

Enhancement poo#167021: SL Micro doesn't have installer like openSUSE
or SLE. Only raw images are supported. If we want to install SL Micro
to bare metal, we need to directly copy image to destination, this is
documented and supported way. The idea behind this extension, is to
use existing openQA boot modules for particular backends and boot SLE
installer, use installation console to mount nfs share from openQA and
deploy image to target disk. We need to modify grub configuration
before first boot, to be able to see menu in hardware consoles. root
password is configured by ignition, which has own separate parition on
the same disk. There are supported following backends and
architectures hmc/ppc64le, ipmi/x86_64/aarch64. Variables MIRROR_HTTP
and REPO_0 are needed to properly boot …

Add support to bare metal for direct image installation of SL Micro

---

tests/jeos/firstrun.pm

TOTP screen is brand new and for now we can just skip the option in order to unblock other tests. Further testing requirements should be discussed later.
- Needles: https://gitlab.suse.de/openqa/os-autoinst-needles-sles/-/merge_requests/1674
- Verification run: http://kepler.suse.cz/tests/24001#step/firstrun/13

Skip TOTP for sle micro

---

lib/main_publiccloud.pm
tests/xfstests/run.pm

Since commit 58a03ea5500f ("xfstests: subtest run could rollback"), each XFS test is now scheduled from within xfstests/run.pm, which also schedules xfstests/generate_report.pm at the end so remove those from Public Cloud main schedule. Also leave publiccloud/ssh_interactive_end to be scheduled later too, otherwise the XFS tests would take place after the SUT has been destroyed already.
- Related ticket: https://progress.opensuse.org/issues/167539
- Verification run: http://rmarliere-openqa.qe.prg2.suse.org/tests/2387 (with CASEDIR pointed towards this PR branch)

publiccloud/xfstests: Remove generate_report from schedule

---

lib/qesapdeployment.pm
lib/sles4sap/azure_cli.pm
t/15_qesap_azure.t
t/21_sles4sap_azure_cli.t

Reverts os-autoinst/os-autoinst-distri-opensuse#20288
Related ticket: https://jira.suse.com/browse/TEAM-9365
SDAF test is failing from Friday, no clue about how it could be related to this PR but try to remove it.

Revert "Move qesap_az_validate_uuid_pattern"

---

tests/fips/openssl/openssl_tlsv1_3.pm

- Related ticket: https://progress.opensuse.org/issues/167533 
- Needles: no
- Verification run: https://openqa.suse.de/tests/15568911
(test fails due to known bug: https://bugzilla.suse.com/show_bug.cgi?id=1220681 )

Remove fatal flag from openssl_tlsv1_3

---

tests/containers/buildah.pm

This workaround is not needed anymore because bsc#1220568 is fixed, and it breaks 15-SP7 test runs where cni is not available.
- Related failure: https://openqa.suse.de/tests/15568852#step/buildah_docker/107
- Verification run: [15-SP2](https://duck-norris.qe.suse.de/tests/14804#step/buildah_docker/1) | [15-SP3](https://duck-norris.qe.suse.de/tests/14805#step/buildah_docker/1) | [15-SP4](https://duck-norris.qe.suse.de/tests/14806#step/buildah_docker/1) | [15-SP5](https://duck-norris.qe.suse.de/tests/14807#step/buildah_docker/1) | [15-SP6](https://duck-norris.qe.suse.de/tests/14808#step/buildah_docker/1)

Remove workaround for bsc#1220568

---

tests/containers/podman_integration.pm

The podman upstream tests need pasta and this is only available as a package on Tumbleweed.
- Related MR: https://gitlab.suse.de/qac/qac-openqa-yaml/-/merge_requests/1843
- sle-15-SP7-Online-x86_64-Build23.2-podman_testsuite@64bit -> https://openqa.suse.de/tests/15571759

containers: Install pasta from upstream for podman upstream tests

---

tests/ha/drbd_passive.pm
tests/ha/filesystem.pm

For 15-SP7, `crm_verify -LV` will fail in 'config not valid', because
'master' is deprecated and need to use 'clone' instead. 'Master' role
need to by replaced by 'Promoted'. According to these, make this
changes.
For QAM test, 15-SP4, 15-SP5, 15-SP6 support 'Promoted' role, for lower
versions, keep to use 'master' role.
Related: https://jira.suse.com/browse/TEAM-9635
VRs:
15-SP7:  https://openqa.suse.de/tests/15548051# (Failed in other reason, and check the exit code of command 'crm_verify -LV, it's 0')
QAM: 
15-SP6: https://openqa.suse.de/tests/15548532# (Softfail)
15-SP5: https://openqa.suse.de/tests/15548031# (Softfail)
15-SP4: https://openqa.suse.de/tests/15548038# (Passed)
15-SP3: https://openqa.suse.de/tests/15548525# (Passed)
15-SP2: https://openqa.suse.de/tests/15548518# (Passed) …

Fix the invalid config in crm for 15-SP7

---

lib/qesapdeployment.pm
lib/sles4sap/azure_cli.pm
t/15_qesap_azure.t
t/21_sles4sap_azure_cli.t

Reverts os-autoinst/os-autoinst-distri-opensuse#20322
Re-add https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/20288
Related ticket: https://jira.suse.com/browse/TEAM-9365
SDAF test is failing from Friday, no clue about how it could be related to this PR but try to remove it.

Revert "Revert "Move qesap_az_validate_uuid_pattern""

---

tests/jeos/firstrun.pm

`dos` partition table is used for images intended for RPi usage. Failing check https://openqa.suse.de/tests/15582485#
- Verification run: https://openqa.suse.de/tests/15589869#step/firstrun/72

Fix partition label check for Base and Default aarch64

---

lib/sles4sap/azure_cli.pm
lib/sles4sap/ipaddr2.pm
t/22_ipaddr2.t
tests/sles4sap/ipaddr2/configure.pm
tests/sles4sap/ipaddr2/deploy.pm

Configure Standard security-type when creating VM using 12sp5 images.
Releted to [this article](https://learn.microsoft.com/en-us/azure/virtual-machines/trusted-launch-faq?tabs=cli%2Cdebianbased#can-i-disable-trusted-launch-for-a-new-vm-deployment) 
- Related ticket: https://jira.suse.com/browse/TEAM-9714  https://jira.suse.com/browse/TEAM-9725
-  http://openqaworker15.qa.suse.cz/tests/298897 :green_circle: 
-  http://openqaworker15.qa.suse.cz/tests/298981 :green_circle: 
sle-12-SP5-SapCloud-Azure-Payg-x86_64-BuildLATEST_AZURE_SLE12_5_PAYG-ipaddr2_azure_test IPADDR2_TRUSTEDLAUNCH=0
-  http://openqaworker15.qa.suse.cz/tests/298895 :green_circle:  / :red_circle:  `az vm create` is fixed but one more …

Disable TrustedLaunch and StrictHostKeyChecking accept-new for 12sp5

---

tests/fips/openjdk/openjdk_fips.pm

SLE RT does not support legacy module, so we avoid using packages from there
- Related ticket: https://progress.opensuse.org/issues/167758
- Needles: no 
- Verification run: https://openqa.suse.de/tests/15597548

Don't install legacy module packages on SLERT

---

schedule/sles4sap/qam/common/qam_install_sles4sap.yaml
tests/installation/system_role.pm

The schedule to create the image that all the on-prem SAP specific scenarios are using was complicated because it had:
1. Cases for unsupported versions
2. Workarounds for YAMLs being unable to loop
3. Unused options
4. Nested cases that were always true
This commit fixes that by:
1. Removing unsupported versions
2. Modifying system_role.pm to remove the need to unroll a version loop inside the yaml
3. Removing unused options.
4. Moving the cases up the tree.
- Related Ticket: TEAM-9610
- Verification runs 
- - SLES4SAP: [12-SP5](http://openqaworker15.qa.suse.cz/tests/overview?distri=sle&version=12-SP5&build=:35627:python-dnspython) [15-SP2](http://openqaworker15.qa.suse.cz/tests/overview?build=%3A35626%3Apython-dnspython&distri=sle&version=15-SP2) …

Simplify schedule to create Incident SLES4SAP HDD

---

lib/Distribution/Sle/AgamaDevel.pm
schedule/yam/agama.yaml

- Related ticket: [poo#167470](https://progress.opensuse.org/issues/167470)
- Verification runs: https://openqa.suse.de/tests/overview?distri=sle&version=agama-10.0&build=jknphy%2Fos-autoinst-distri-opensuse%23fix-grub-menu-agama

Create GrubMenuAgamaPage with base class

---

data/yam/agama/auto/gnome_tumbleweed.json
tests/yam/agama/agama_auto.pm

##
- Related ticket: https://progress.opensuse.org/issues/167060
- Needles: N/A
- [**agama_auto_gnome**](https://openqa.opensuse.org/tests/overview?arch=x86_64&flavor=&machine=&test=&modules=&module_re=&group_glob=&not_group_glob=&comment=&version=agama-9.0&distri=opensuse&build=hjluo#)

Create agama auto-installation selecting gnome pattern

---

os-autoinst-distri-opensuse-deps.spec

Every sub-package needs a files section even if empty.

spec: Fix build of worker sub-package
