tests/console/install_packages.pm
tests/console/qam_zypper_patch.pm

- Related ticket: https://progress.opensuse.org/issues/166538
- Needles: n/a
- Verification run: https://openqa.opensuse.org/tests/4466376

Make sure only one package per line for installing

---

tests/console/gpg.pm

Ensure that check will only be executed on SLES 15+ and not on JeOS or PC

Fix gpg test on PC and Jeos

---

tests/console/perl_bootloader.pm

- Related ticket: https://openqa.suse.de/tests/15388446#next_previous
- VR: https://openqa.suse.de/tests/overview?version=5.1&build=jpupava_boot&distri=sle-micro

perl_bootloader: Increase bootloder timeout

---

tests/containers/skopeo.pm

Adds functionality to the Skopeo test module to test it against that our packaged version of Skopeo works against our latest Image Registry API.
This is done by spinning up a container with the latest Registry image, copying an image to the local registry via Skopeo and verifying that the layers between the Remote and Local registries have the same layers.
-   Related ticket: https://progress.opensuse.org/issues/163553
-   Needles: N/A
-   Verification run: http://dirtman.qe.prg2.suse.org/tests/24#step/skopeo/1
-  Clone of https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/20003 since that one got messed up with the rebase.

Extend Skopeo test module to verify latest Registry compatibility

---

tests/security/dm_crypt.pm

VRs:
- 15.4: https://openqa.suse.de/tests/15392168
- 15.6: https://openqa.suse.de/tests/15392269

Fix dm_crypt on sle 15.6+ and sl micro 6.0+

---

tests/console/qam_zypper_patch.pm

- Related ticket: https://progress.opensuse.org/issues/166568
- Verification run: https://openqa.opensuse.org/tests/4467487#step/qam_zypper_patch/13

zypper_patch: Use force resolution

---

lib/opensusebasetest.pm

- Related ticket: https://bugzilla.opensuse.org/show_bug.cgi?id=1227389#c5
- Verification run: https://openqa.opensuse.org/tests/4470940

Upload all /var/log/pk_backend_zypp* logs

---

data/publiccloud/terraform/sap/azure.tfvars
lib/publiccloud/provider.pm

Remove any setting usage from terraform.tfvars, and PC libs dedicated to SAP. Removing this small portion of code has no impact as there's no more tests using azure.tfvars at all.
- Related ticket: https://jira.suse.com/browse/TEAM-8710
- Verification run: Change is about a no more used test

Remove STORAGE_ACCOUNT_KEY setting

---

tests/security/apparmor_profile/usr_sbin_dnsmasq.pm
tests/security/cc/audit_remote_libvirt.pm

Ticket: https://progress.opensuse.org/issues/166331

Rename HDD_L2 to HDD_2

---

lib/susedistribution.pm

- Related ticket: [poo#163919](https://progress.opensuse.org/issues/163919)
- qemu: https://openqa.opensuse.org/tests/4475882
- regression: https://openqa.suse.de/tests/15424484

Add tty2 for console installation in agama

---

data/autoyast_sle15/autoyast_wicked_aarch64.xml
data/autoyast_sle15/autoyast_wicked_ppc64le.xml

https://progress.opensuse.org/issues/166733
[create_hdd_aarch64](https://openqa.suse.de/tests/15423507)
[create_hdd_ppc64le](https://openqa.suse.de/tests/15423508)
[VR-aarch64](https://openqa.suse.de/tests/15424173)
[VR-ppc64le](https://openqa.suse.de/tests/15424185)

Add missed packages for wicked tests

---

lib/opensusebasetest.pm
schedule/security/autoyast_stig_hardening.yaml

Ticket: https://progress.opensuse.org/issues/166325
VR: https://openqa.suse.de/tests/15443214
Related MR: https://gitlab.suse.de/qe-security/osd-sle15-security/-/merge_requests/293

Fix stig_remediation test

---

.github/CODEOWNERS

And also add selected QE-SAP members into lib/publiccloud/ CODEOWNERS
- Needles: N/A

Add QE-SAP CODEOWNERS

---

data/virt_autotest/guest_params_xml_files/sles_12_sp5_64_kvm_hvm_uefi_with_power_management_x86_64.xml
data/virt_autotest/guest_params_xml_files/sles_15_sp6_64_kvm_hvm_uefi_with_power_management_x86_64.xml
data/virt_autotest/guest_params_xml_files/sles_15_sp7_64_kvm_hvm_uefi_with_power_management_x86_64.xml

https://bugzilla.suse.com/show_bug.cgi?id=1230449#c7
https://openqa.suse.de/tests/15437726
https://openqa.suse.de/tests/15437732
https://openqa.suse.de/tests/15437733

Add loader type options for UEFI guest configuration files

---

lib/sles4sap_publiccloud.pm

Call run_ssh_command with timeout different from 0. Zero has a special meaning within the PC API.
Remove %args forwarding only and exclusively for the crash command.
- Related ticket:  https://jira.suse.com/browse/TEAM-9658
sle-15-SP6-HanaSr-Aws-Byos-x86_64-Build15-SP6_2024-09-16T02:03:15Z-hanasr_aws_test_saptune_fencing_native//ec2_r4.8xlarge
- http://openqaworker15.qa.suse.cz/tests/297527 :red_circle:  here the `sync` command http://openqaworker15.qa.suse.cz/tests/297527#step/Crash_site_a-primary/418 . 
In http://openqaworker15.qa.suse.cz/tests/297527/logfile?filename=serial_terminal.txt it is like
```
> timeout 300 ssh -E /var/tmp/ssh_sut.log -F none -o LogLevel=DEBUG3 -o PasswordAuthentication=no -i '~/.ssh/id_*****' "cloudadmin@**********" -- 'sudo su -c sync'
> EOT_gCpw2
gCpw2-0- …
```

Move to finite timeout in HanaSR crash

---

schedule/yam/agama_full_disk_encryption.yaml
tests/yam/agama/import_agama_profile.pm
tests/yam/agama/patch_agama_tests.pm

- Related ticket: [poo#166133](https://progress.opensuse.org/issues/166133)
- Verification run: [agama-installer](https://openqa.opensuse.org/tests/overview?build=build-issues-166133&distri=opensuse&version=agama-9.0)
- Related PR: [agama-integration-test-webpack/pull/12](https://github.com/jknphy/agama-integration-test-webpack/pull/12)

Create Agama installation for full encryption

---

lib/Yam/Agama/agama_base.pm

- Needles: N/A
- Verification run: https://openqa.opensuse.org/tests/4489172#downloads

Upload logs for agama even test passed

---

tests/publiccloud/slem_basic.pm

- Related ticket: [poo#166322](https://progress.opensuse.org/issues/166322)
- Verification run: [Azure](https://pdostal-server.suse.cz/tests/7452), [GCE](https://pdostal-server.suse.cz/tests/7450), [EC2](https://pdostal-server.suse.cz/tests/7453)

PC: Fix the slem_basic ausearch

---

data/sles4sap/qe_sap_deployment/qesap_aws.yaml
data/sles4sap/qe_sap_deployment/qesap_aws_fencing.yaml
data/sles4sap/qe_sap_deployment/qesap_aws_sapconf.yaml
data/sles4sap/qe_sap_deployment/qesap_azure.yaml
data/sles4sap/qe_sap_deployment/qesap_azure_fencing_msi.yaml
data/sles4sap/qe_sap_deployment/qesap_azure_fencing_spn.yaml
data/sles4sap/qe_sap_deployment/qesap_azure_roles.yaml
data/sles4sap/qe_sap_deployment/qesap_azure_sapconf.yaml
data/sles4sap/qe_sap_deployment/qesap_azure_sapconf_no_reg.yaml
data/sles4sap/qe_sap_deployment/qesap_azure_uri.yaml
data/sles4sap/qe_sap_deployment/qesap_gcp.yaml
data/sles4sap/qe_sap_deployment/qesap_gcp_fencing.yaml
data/sles4sap/qe_sap_deployment/qesap_gcp_sapconf.yaml
data/sles4sap/qe_sap_deployment/sles4sap_aws_generic.yaml
data/sles4sap/qe_sap_deployment/sles4sap_azure_generic.yaml
data/sles4sap/qe_sap_deployment/sles4sap_azure_generic_maintenance.yaml
data/sles4sap/qe_sap_deployment/sles4sap_azure_generic_uri.yaml
data/sles4sap/qe_sap_deployment/trento_azure.yaml

With https://jira.suse.com/browse/TEAM-9540, having the az_sas_token value defined in qesap.py's YAML configuration files is no longer necessary, as qesap.py will calculate a SAS token dynamically if a valid key name was provided in az_key_name.
- Related ticket: https://jira.suse.com/browse/TEAM-9668
- hanasr-regresion
- 15-SP6-HanaSr-Aws-Byos-hanasr_aws_test_saptune_fencing_native
- https://openqaworker15.qa.suse.cz/tests/297635 :green_circle: : false not related to az_sas_token
- 15-SP5-HanaSr-Aws-Byos-hanasr_aws_test_fencing_sbd
- https://openqaworker15.qa.suse.cz/tests/297617 :green_circle: false not related to az_sas_token
- 15-SP6-HanaSr-Azure-Byos-hanasr_azure_test_saptune_spn
- https://openqaworker15.qa.suse.cz/tests/297636 :green_circle: false …

Remove az_sas_token variable from qesap configuration yaml config files

---

lib/qesapdeployment.pm
t/09_qesapdeployment.t
t/14_qesap_ansible.t

Remove the failok argument and manage everything with return code and by never die in the low level function. To do so, also pipe to log has to be managed differently to allow both `pipefail` and pipe to tee to be properly composed in the command and exit code to be properly returned to the caller.
- Related ticket: https://jira.suse.com/browse/TEAM-9691
sle-15-SP5-HanaSr-Azure-Byos-x86_64-Build15-SP5_2024-09-17T02:03:20Z-hanasr_azure_test_sapconf_msi az_Standard_E4s_v3 
-  http://openqaworker15.qa.suse.cz/tests/297686 :green_circle: 
sle-15-SP6-Qesap-Aws-Byos-x86_64-BuildLATEST_AWS_SLE15_6_BYOS-qesap_aws_fencing_sbd_test
- http://openqaworker15.qa.suse.cz/tests/297684 :green_circle: 
-  http://openqaworker15.qa.suse.cz/tests/297687 …

Change error handling for venv related methods

---

lib/Yam/Agama/agama_base.pm

- Needles: N/A
- Verification run: https://openqa.opensuse.org/tests/4490933#

Recategory function for agama logs

---

lib/Yam/Agama/agama_base.pm

Reverts os-autoinst/os-autoinst-distri-opensuse#20222

Revert "Recategory function for agama logs"

---

lib/Yam/Agama/agama_base.pm

Reverts os-autoinst/os-autoinst-distri-opensuse#20216

Revert "Upload logs for agama even test passed"

---

tests/security/apparmor/aa_notify.pm

Also make the test more reliable by disabling `nscd.service` autorestart, so the start/stop of the service is directly controlled by test
- Related ticket: https://progress.opensuse.org/issues/165189
- Needles: n/a
- https://openqa.suse.de/tests/15475185
- https://openqa.suse.de/tests/15475186
- https://openqa.suse.de/tests/15475187

Replace sleep() with stdout checking logic

---

lib/Distribution/Opensuse/AgamaDevel.pm
lib/Yam/Agama/Pom/RebootPage.pm
lib/Yam/Agama/Pom/RebootTextmodePage.pm
schedule/yam/agama_s390x.yaml
tests/yam/agama/agama.pm

We have added S390x test integration.
- Related ticket: https://progress.opensuse.org/issues/165830
- Related PR: In progress
- Needles: N/A
- Verification run: https://openqa.opensuse.org/tests/4483890#

Integrate the web automation script for agama in openQA

---

tests/fips/fips_setup.pm

Fixes an incorrect way of checking for test variables. 
note: this most likely will make some not properly configured test suites to fail, so we can promptly fix them. 
- Related ticket: https://progress.opensuse.org/issues/167063
- Needles: n/a
- https://openqa.suse.de/tests/15505991
- https://openqa.suse.de/tests/15505992
- https://openqa.suse.de/tests/15506004
- https://openqa.suse.de/tests/15506023

Check FIPS vars in the correct way or bailout

---

tests/console/perl_bootloader.pm

- Related ticket: https://progress.opensuse.org/issues/165686
- Verification runs:  
- Staging (TW, microos) https://openqa.opensuse.org/tests/overview?build=cedvid%2Fos-autoinst-distri-opensuse%2320066
- SLE https://openqa.suse.de/tests/overview?build=cedvid%2Fos-autoinst-distri-opensuse%2320066

Adjust test to use new package name for Tumbleweed

---

lib/sles4sap_publiccloud.pm

Timeout used as argument for run_ssh_command when sending the crash command was 0. Zero has a special meaning and handling in both run_ssh_command and below script_run API.
Change it to 10, as thanks to & within the command and -fn in ssh, this command should immediately return the prompt.
- Related ticket:  https://jira.suse.com/browse/TEAM-9658
sle-15-SP6-HanaSr-Aws-Byos-x86_64-Build15-SP6_2024-09-19T02:04:03Z-hanasr_aws_test_fencing_sbd ec2_r4.8xlarge
- http://openqaworker15.qa.suse.cz/tests/297860 :green_circle: 
`run_ssh_command` sends the command with `script_run`:
- 10sec is used in the `timeout` command wrapper
- 30sec is used as timeout argument
```
[2024-09-20T18:12:04.049813+02:00] [debug] [pid:60361] <<< testapi::script_run(cmd="timeout 10 ssh  ....  -fn -o …
```

Change crash command timeout to a positive value

---

tests/fips/fips_setup.pm

- Related ticket: https://progress.opensuse.org/issues/167260
- Needles: n/a
- https://openqa.suse.de/tests/15526396
- https://openqa.suse.de/tests/15526397
- https://openqa.suse.de/tests/15526398
- https://openqa.suse.de/tests/15526399
- https://openqa.suse.de/tests/15526400

Remove useless check for variables

---

data/journal_check/bug_refs.json

- Needles: N/A
- Verification run:  http://openqa.suse.de/tests/15526656#step/journal_check/9

Add softfail for bsc#1205931 on sle_micro 6.0

---

tests/fips/squid/squid_reverse_proxy.pm

add also a retry in the checking code to prevent flakyness
- Related ticket: https://progress.opensuse.org/issues/167149
- Needles: no 
- https://openqa.suse.de/tests/15509474
- https://openqa.suse.de/tests/15509475
- https://openqa.suse.de/tests/15509476

Use serial terminal for testing squid reverse proxy

---

schedule/qam/common/mau-extratests1.yaml
tests/console/velociraptor_client_event_collect.pm

Related ticket:
Needles: NO
SLE15SP6
x86_64   https://openqa.suse.de/tests/15487282
aarch64 https://openqa.suse.de/tests/15487280
s390x  https://openqa.suse.de/tests/15487281
SLE15SP5
x86_64   https://openqa.suse.de/tests/15487302
aarch64 https://openqa.suse.de/tests/15487530
s390x https://openqa.suse.de/tests/15487301
SLE15SP4
x86_64   https://openqa.suse.de/tests/15487460
aarch64 https://openqa.suse.de/tests/15487457
s390x https://openqa.suse.de/tests/15487458

Update test add aarch64,s390x

---

tests/qam-updinstall/update_install.pm

- Related ticket: https://progress.opensuse.org/issues/167413
- Verification run: https://openqa.suse.de/tests/overview?build=%3A35830%3Aglfw&groupid=546

update_install: Add libglfw3 conflict

---

tests/fips/libica_upstream_testsuite.pm

- Fixed the repository setup so removal at the end is effective
- updated version and example output
- Related ticket: https://progress.opensuse.org/issues/162437
- Verification run: https://openqa.suse.de/tests/15537847

Update test repo setup/teardown

---

schedule/qam/common/mau-extratests1.yaml
tests/console/velociraptor_client_event_collect.pm

Reverts os-autoinst/os-autoinst-distri-opensuse#19984

Revert "Update test add aarch64,s390x"

---

lib/security/openssl_misc_utils.pm
tests/fips/openssl/openssl_fips_cipher.pm

VR: https://openqa.opensuse.org/tests/4514606

Add also microos support

---

lib/Tomcat/ModjkTest.pm
lib/y2_installbase.pm
schedule/functional/create-hdd-allmodules-allpatterns.yaml

- Related ticket: https://progress.opensuse.org/issues/167356
allpatterns
https://openqa.suse.de/tests/overview?arch=&flavor=&machine=&test=allmodules%2Ballpatterns-gnome&modules=&module_re=&group_glob=&not_group_glob=&comment=&distri=sle&groupid=110&version=15-SP7&build=23.2
https://openqa.suse.de/tests/overview?arch=&flavor=&machine=&test=allpatterns&modules=&module_re=&group_glob=&not_group_glob=&comment=&distri=sle&groupid=110&version=15-SP7&build=23.2#
tomcat
https://openqa.suse.de/tests/15539012
https://openqa.suse.de/tests/15539010#step/tomcat/98 -> https://openqa.suse.de/tests/15539218

All patterns

---

lib/main_common.pm
schedule/functional/extra_tests_textmode.yaml
schedule/functional/extra_tests_textmode_phub.yaml
tests/console/libgit2.pm
tests/network/cifs.pm
tests/systemd_testsuite/prepare_systemd_and_testsuite.pm

Add libgit2 test module to extra_tests_textmode_phub job
- Related ticket: https://progress.opensuse.org/issues/167419
- Verification run: https://openqa.suse.de/tests/15546984#
https://openqa.suse.de/tests/15547383
https://openqa.suse.de/tests/15546996#

Added packagehub related test modules to extra_tests_textmode_phub job

---

lib/DistributionProvider.pm

Fix https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/20276

Fix distri pattern for Agama devel

---

data/yam/agama/auto/default_sle.json

Fixed Auto job
- Related ticket: https://progress.opensuse.org/issues/167239
- Needles: N/A
- x86_64: https://openqa.suse.de/tests/15547981
- aarch64: https://openqa.suse.de/tests/15548025

Boot agama in OSD in architectures using qemu

---

tests/console/year_2038_detection.pm

https://progress.opensuse.org/issues/167560
[sle](https://openqa.suse.de/tests/15558089#details)
[micro-os](https://openqa.opensuse.org/tests/4519984#details)

Reboot system to restore system date/time

---

tests/console/year_2038_detection.pm

Reverts os-autoinst/os-autoinst-distri-opensuse#20307
It can't resolve the problem perfectly

Revert "Reboot system to restore system date/time"

---

lib/YaST/workarounds.pm
tests/iscsi/iscsi_client.pm

##
- Related ticket: https://progress.opensuse.org/issues/158742
- Needles: N/A
-  https://openqa.suse.de/t15558101
-  https://openqa.suse.de/t15558102
##

Remove soft-failure bsc#1206132

---

tests/yam/agama/agama.pm

- Related ticket: [poo#167087](https://progress.opensuse.org/issues/167087)
- https://openqa.opensuse.org/tests/4522263
- https://openqa.opensuse.org/tests/4522265

Add env var for agama product selection

---

tests/console/zypper_lifecycle.pm

- Related ticket: https://progress.opensuse.org/issues/167602
- Verification run: https://dzedro.suse.cz/tests/1619

zypper_lifecycle: Workaround end of support package

---

data/journal_check/bug_refs.json

- Related ticket: https://progress.opensuse.org/issues/167338
- Verification run: https://openqa.suse.de/tests/15563460

Extend white list for bsc#1215378

---

lib/qesapdeployment.pm
t/09_qesapdeployment.t

Method qesap_terraform_clean_up_retry is only called once, and only from another method within the same library: move the code directly in the caller. Add more UT coverage for the caller.
Follow up of https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/18159
- Related ticket: TEAM-6903
-> http://openqaworker15.qa.suse.cz/tests/298767 :green_circle: 
-> http://openqaworker15.qa.suse.cz/tests/298768 :green_circle: failure is later after the deployment, so not influenced by code in this PR
-> http://openqaworker15.qa.suse.cz/tests/298769 :green_circle: 
-> http://openqaworker15.qa.suse.cz/tests/298770  :green_circle: failure is later after the deployment, so not influenced by code in this PR

Remove qesap_terraform_clean_up_retry

---

tests/qam-updinstall/update_install.pm

- Related ticket: https://suse.slack.com/archives/C02CLB8TZP1/p1727859595515859
https://openqa.suse.de/tests/overview?build=%3A35874%3Acyrus-sasl&groupid=546
https://openqa.suse.de/tests/overview?build=%3A35874%3Acyrus-sasl&groupid=557
https://openqa.suse.de/tests/overview?build=%3A35874%3Acyrus-sasl&groupid=558

update_install: Add cyrus-sasl conflicts

---

lib/Distribution/Opensuse/AgamaDevel.pm
lib/Distribution/Sle/AgamaDevel.pm
lib/Yam/Agama/Pom/AgamaUpAndRunningBasePage.pm
lib/Yam/Agama/Pom/AgamaUpAndRunningOpensusePage.pm
lib/Yam/Agama/Pom/AgamaUpAndRunningSlePage.pm
lib/Yam/Agama/Pom/EnterPassphraseBasePage.pm
lib/Yam/Agama/Pom/EnterPassphraseForRootPage.pm
lib/Yam/Agama/Pom/EnterPassphraseForSwapPage.pm
lib/Yam/Agama/Pom/GrubMenuAgamaPage.pm
lib/Yam/Agama/Pom/GrubMenuBasePage.pm
lib/Yam/Agama/Pom/GrubMenuTumbleweedPage.pm
lib/Yam/Agama/agama_base.pm
schedule/yam/agama.yaml
schedule/yam/agama_full_disk_encryption.yaml
tests/yam/agama/agama.pm
tests/yam/agama/agama_auto.pm
tests/yam/agama/boot_agama.pm
tests/yam/agama/boot_full_disk_encryption.pm

- Related ticket: [poo#167470](https://progress.opensuse.org/issues/167470)
- Verification run: [agama_full_disk_encryption](https://openqa.opensuse.org/tests/overview?build=jknphy%2Fos-autoinst-distri-opensuse%23boot-encrypt&distri=opensuse&version=agama-9.0)

Boot entering two passphrases in Agama

---

tests/console/year_2038_detection.pm

https://progress.opensuse.org/issues/167560
[sle](https://openqa.suse.de/tests/15558264)
[tw](https://openqa.opensuse.org/tests/4520055)
[micro-os](https://openqa.opensuse.org/tests/4520056)

Fix sporadic time sync issue for year_2038_detection test

---

lib/transactional.pm

- Related ticket: https://progress.opensuse.org/issues/167887
- Verification run: [VRs](http://openqa.suse.de/tests/overview?build=rfan1008&version=6.1&distri=sle-micro)

Make sure screen is changed after first grub phase

---

schedule/security/create_hdd_cc_libyui/aarch64/cc_qr.yaml
schedule/security/create_hdd_cc_libyui/aarch64/cc_qr_no_fde_15sp4.yaml

VRs: https://openqa.suse.de/tests/overview?distri=sle&version=15-SP5&build=146.3&groupid=431
Related MR: https://gitlab.suse.de/qe-security/osd-sle15-security/-/merge_requests/303

Fix QR CC installation

---

lib/transactional.pm

- Related ticket: https://progress.opensuse.org/issues/167461

health_check: Increase grub2 timeout

---

schedule/yam/agama_full_disk_encryption.yaml

- Related ticket: [poo#167470](https://progress.opensuse.org/issues/167470)
- Verification run: [overiew](https://openqa.opensuse.org/tests/overview?build=build-issues-167470)

Agama: enable installation for full encryption with focus on booting

---

schedule/kernel/kdump.yaml

- Verification run: https://openqa.suse.de/tests/15631288

kdump: Add pvm_hmc backend to kernel YAML schedule

---

lib/mm_network.pm
tests/network/setup_multimachine.pm
tests/security/cc/setup_net_test_env.pm

- Related ticket: https://progress.opensuse.org/issues/167821
- Needles: no
https://openqa.suse.de/tests/15636828
https://openqa.suse.de/tests/15636829
https://openqa.suse.de/tests/15636830
https://openqa.suse.de/tests/15636831
https://openqa.suse.de/tests/15636832
https://openqa.suse.de/tests/15636833
https://openqa.suse.de/tests/15636834
https://openqa.suse.de/tests/15636835
https://openqa.suse.de/tests/15636836
https://openqa.suse.de/tests/15636837
https://openqa.suse.de/tests/15636838
https://openqa.suse.de/tests/15636839
https://openqa.suse.de/tests/15636840
https://openqa.suse.de/tests/15636841
https://openqa.suse.de/tests/15636842
https://openqa.suse.de/tests/15636843
https://openqa.suse.de/tests/15636844
https://openqa.suse.de/tests/15636845 …

Workaround for aarch64 performance issue

---

lib/susedistribution.pm
tests/installation/bootloader_s390.pm

We have added some changes into the code to be able to boot s390x SLE Agama installer.
- Related ticket: https://progress.opensuse.org/issues/167248
- Needles: N/A
- Related PR: https://github.com/jknphy/agama-integration-test-webpack/pull/31
- s390x-zvm SLE: https://openqa.suse.de/tests/15623219
- s390x-zvm TW: https://openqa.opensuse.org/tests/4543570
- s390x-zvm Leap: https://openqa.opensuse.org/tests/4543727

Boot agama in OSD in s390x with zVM

---

lib/Distribution/Opensuse/Leap/16Latest.pm
lib/DistributionProvider.pm
lib/Yam/Agama/Pom/GrubMenuLeapPage.pm

- Related ticket: https://progress.opensuse.org/issues/167087
- Needles: N/A
- Verification run: https://openqa.opensuse.org/tests/4545056#details

Add grub menu page for Leap

---

schedule/functional/extra_tests_textmode_phub.yaml

ImageMagick comes from Desktop applications added by ansible
- Related ticket: https://openqa.suse.de/tests/15639717#step/libjpeg_turbo/15
- VR: https://openqa.suse.de/tests/15647636

functional: Change test order

---

tests/yam/agama/agama.pm

- Related ticket: https://github.com/jknphy/agama-integration-test-webpack/pull/32
- https://openqa.opensuse.org/tests/overview?version=&distri=opensuse&build=jknphy%2Fos-autoinst-distri-opensuse%23update-branch
- https://openqa.suse.de/tests/overview?build=jknphy%2Fos-autoinst-distri-opensuse%23update-branch&distri=sle&version=agama-10.0

Adapt call to web browser automation

---

lib/containers/urls.pm
lib/main_containers.pm
tests/containers/podman_bci_systemd.pm
tests/containers/podman_pods.pm
tests/containers/privileged_mode.pm
tests/containers/skopeo.pm

Reverts os-autoinst/os-autoinst-distri-opensuse#20223

Revert "Add container test runs for RISC-V"

---

tests/yam/agama/agama.pm

- https://progress.opensuse.org/issues/163919
- https://github.com/jknphy/agama-integration-test-webpack/pull/35
- https://openqa.opensuse.org/tests/overview?distri=opensuse&build=jknphy%2Fos-autoinst-distri-opensuse%23remove-env&version=agama-9.0
- https://openqa.opensuse.org/tests/overview?version=16.0&build=jknphy%2Fos-autoinst-distri-opensuse%23remove-env&distri=opensuse
-  https://openqa.suse.de/tests/overview?build=jknphy%2Fos-autoinst-distri-opensuse%23remove-env&distri=sle&version=agama-10.0

Read test option from single env variable

---

tests/kernel_performance/install_qatestset.pm

Add workaround to prevent network interface order change: load tg3 driver before bnxt_en
Related ticket: [TEAM-9042](https://jira.suse.com/browse/TEAM-9042)
Needles: N/A
Verification run: http://10.200.129.4/tests/73857
- service file is generated correctly 
```
hana02:~ # cat /usr/lib/systemd/system/load_bnxt_en.service
[Unit]
Description=Load bnxt_en driver manually
After=sshd.service
[Service]
Type=oneshot
ExecStart=modprobe bnxt_en
TimeoutSec=0
RemainAfterExit=no
TasksMax=12000
[Install]
WantedBy=multi-user.target
```
- service is launched correctly and matches expectation
```
hana02:~ # systemctl status load_bnxt_en.service
○ load_bnxt_en.service - Load bnxt_en driver manually
Loaded: loaded (/usr/lib/systemd/system/load_bnxt_en.service; enabled; preset: disabled)
Active: inactive …
```

Continue to improve the method about mitigating network interface order change

---

data/virt_autotest/guest_params_xml_files/oracle_linux_8_10_graphical_server_x86_64.xml
data/virt_autotest/guest_params_xml_files/oracle_linux_9_4_graphical_server_x86_64.xml

* **Update** Oracle Linux 8 guest to R8U10.
* **Update** Oracle Linux 9 guest to R9U4.
* **Verification Run:** 
* [verification run](https://openqa.suse.de/tests/15699434)

Upate Oracle Linux guest to R8U10 and R9U4

---

lib/Distribution/Sle/16Latest.pm
lib/DistributionProvider.pm

- Related ticket: https://progress.opensuse.org/issues/168280
- Needles: N/A
https://openqa.suse.de/tests/15710363#    Sle 16.0
https://openqa.opensuse.org/tests/4567418#live   regression test on leap 16.0

Fix Agama Sle 16.0 distribution issue

---

lib/utils.pm

In utils->ensure_ca_certificate added default folder for SUSE certificates. 
SLE-Micro actually have no corresponding folder in IBS CA:
adding a _distri_ CA pre-check, we'll use `SLE-Factory/` when CA repo not found in IBS.
Scope of this PR is the success of the `toolbox.pm` module that correctly pulls from registry the sle-m 6.1 version for ppc64le.
- Related ticket: https://progress.opensuse.org/issues/162689 
- Needles: none.
- Verification run: see PR next posts.
Note: this PR is followup of [PR 20383](https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/20383#issuecomment-2414736569) that was created for introduction of  SLE-micro 6.1 ppc64le tests and is `split N.1` of issues in it fixed. 
At the moment, due to SLE-M 6.1 images affected by …

Get default CA when missing in IBS

---

lib/Distribution/Opensuse/AgamaDevel.pm
lib/Distribution/Sle/AgamaDevel.pm
lib/Yam/Agama/Pom/AgamaUpAndRunningBasePage.pm
lib/Yam/Agama/Pom/AgamaUpAndRunningOpensusePage.pm
lib/Yam/Agama/Pom/AgamaUpAndRunningSlePage.pm

- Related ticket: [poo#163919](https://progress.opensuse.org/issues/163919)
- Verification run: https://openqa.suse.de/tests/overview?build=jknphy%2Fos-autoinst-distri-opensuse%23power9emu&distri=sle&version=16.0

Add different timeout for ppc64le emulated

---

lib/qesapdeployment.pm
t/15_qesap_azure.t

This is a following PR for #20415.
There are 3 functions for setupping native fencing permission for AZ test, but only `qesap_az_setup_native_fencing_permissions` is called by test code. So we integrate these three into one for 2 reasons:
1. After integrating, the code is not long, still easy to read.
2. Simply the test code.
Related: https://jira.suse.com/browse/TEAM-9699
VRs:
Azure-SAP-PAYG:
SAPHanaSR-ScaleUp-PerfOpt-msi@az_Standard_E4s_v3: https://openqa.suse.de/tests/15725447# (Passed)
Azure-SAP-BYOS:
SAPHanaSR-ScaleUp-PerfOpt-msi@az_Standard_E4s_v3: https://openqa.suse.de/tests/15725448# (Passed)

Integrate AZ fencing permissions functions into one

---

data/python/pynacl/test_pynacl.py
lib/python_version_utils.pm
schedule/functional/stack_tests_python.yaml
tests/console/python3_pynacl.pm

Add tests for PyNaCl
- Related ticket: https://progress.opensuse.org/issues/167111
[https://openqa.opensuse.org/tests/4582267#step/python3_pynacl/8](https://openqa.opensuse.org/tests/4582267#step/python3_pynacl/8)
[https://openqa.suse.de/tests/15739583#](https://openqa.suse.de/tests/15739583#)

Add PyNaCl and libsodium test

---

tests/security/crypto_policies/crypto_policies_tests.pm

- Related ticket: https://progress.opensuse.org/issues/161039
- Needles: no
- 15SP7 x86_64 https://openqa.suse.de/tests/15756760
- 15SP6 x86_64 https://openqa.suse.de/tests/15692744
- 15SP6 aarch64 https://openqa.suse.de/tests/15756761
- 15SP6 s390x https://openqa.suse.de/tests/15756764

Introduce test for gnutls crypto_policies

---

data/yam/autoyast/support_images/create_hdd_hpc_development_node_aarch64.xml.ep
data/yam/autoyast/support_images/create_hdd_hpc_textmode_aarch64.xml.ep
data/yam/autoyast/support_images/sles15sp4_install_gnome_all_patterns_aarch64.xml
data/yam/autoyast/support_images/sles15sp4_install_gnome_all_patterns_s390x.xml
data/yam/autoyast/support_images/sles15sp4_install_gnome_all_patterns_x86_64.xml
data/yam/autoyast/support_images/sles15sp4_install_textmode_all_patterns_aarch64.xml
data/yam/autoyast/support_images/sles15sp4_install_textmode_all_patterns_s390x.xml
data/yam/autoyast/support_images/sles15sp4_install_textmode_all_patterns_x86_64.xml
data/yam/autoyast/support_images/sles15sp5_install_gnome_all_patterns_aarch64.xml
data/yam/autoyast/support_images/sles15sp5_install_gnome_all_patterns_s390x.xml
data/yam/autoyast/support_images/sles15sp5_install_gnome_all_patterns_x86_64.xml
data/yam/autoyast/support_images/sles15sp5_install_textmode_all_patterns_aarch64.xml
data/yam/autoyast/support_images/sles15sp5_install_textmode_all_patterns_s390x.xml
data/yam/autoyast/support_images/sles15sp5_install_textmode_all_patterns_x86_64.xml

- Related ticket: https://progress.opensuse.org/issues/168808
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/15763269#step/console/4

Need remove cc pattern from AY profiles for bsc#1231607

---

tests/sles4sap/cloud_netconfig/deploy.pm

cloud-netconfig: disable TrustedLaunch feature for image not supporting it.
- Related ticket: TEAM-8721
- sle-15-SP5-SapCloud-Azure-Payg-x86_64-BuildLATEST_AZURE_SLE15_5_PAYG-cloud_netconfig_azure_test@64bit -> http://openqaworker15.qa.suse.cz/tests/300852
- sle-12-SP5-SapCloud-Azure-Payg-x86_64-BuildLATEST_AZURE_SLE12_5_PAYG-cloud_netconfig_azure_test@64bit -> http://openqaworker15.qa.suse.cz/tests/300853

Disable TrustedLaunch in 12sp5

---

tests/ha/ha_cluster_crash_test.pm

Starting on 15-SP7, the `crmsh` cluster crash test command `split-brain-iptables`, causes the crash immediately, preventing `script_run` from collecting the return value of the command, and causing a failure in the test module. The other crash commands such as `kill-sbd` or `kill-corosync` still cause the crash, but crash is delayed allowing `script_run` to collect the return value of the call.
This commit replaces `script_run` with `enter_cmd` when running `crm cluster crash_test --split-brain-iptables --force` to avoid attempting to check for the return value. It also adds a new error message with `record_info` if `split-brain-iptables` check was run and it did not cause the fence.
- Related ticket: https://bugzilla.suse.com/show_bug.cgi?id=1232107
- Needles: N/A …

Run split-brain-iptables cluster crash test with enter_cmd

---

test_data/yam/agama_sle.yaml

- Related ticket: [poo#168304](https://progress.opensuse.org/issues/168304)
- Verification run: [overview](https://openqa.suse.de/tests/overview?build=build-issues-168304)

Agama: fix validate product. SLE to SLES

---

lib/Yam/Agama/Pom/AgamaUpAndRunningSlePage.pm

- Related ticket: [poo#163919](https://progress.opensuse.org/issues/163919)

Add sync point "Configuring the product"

---

lib/registration.pm

- Related ticket: https://progress.opensuse.org/issues/168265
- Verification run: https://openqa.suse.de/tests/15770830#

registration: Add ltss_es addon to addons with SCC registration code

---

tests/yam/agama/agama.pm

- Related ticket: [poo#163919](https://progress.opensuse.org/issues/163919)
- Verification run: https://openqa.suse.de/tests/15770864

Add cert workaround also for power in agama

---

lib/Yam/Agama/Pom/AgamaUpAndRunningSlePage.pm

This reverts commit 69f724c93c2721fce72c69dbd704f89d16224bc1.

Revert "Add sync point "Configuring the product""

---

lib/utils.pm
schedule/security/create_hdd_common_criteria_for_mm.yaml

VR: https://openqa.suse.de/tests/15797686

Handle CC encrypted disk on s390x case

---

lib/mm_network.pm
tests/network/firewalld_policy_objects.pm

https://progress.opensuse.org/issues/162980
[Verification run](https://openqa.opensuse.org/tests/4600530#dependenciee)

Make sure nic is connected before adding route

---

lib/atsec_test.pm
tests/security/atsec/dbus_services_exposure.pm

VR: https://openqa.suse.de/tests/15800659
Related MR: https://gitlab.suse.de/qe-security/osd-sle15-security/-/merge_requests/311

Update dbus whitelist

---

tests/kernel/run_ltp.pm

Log "stamp" about starting command into /dev/kmsg. Printing into /dev/kmsg fix problems with missing stamps on all SLES supported archs (aarch64, ppc64le, s390x, x86_64) and on other archs (riscv64 on o3)
- message is printed, but but without time (that could probably be workarounded by *always* setting printk.time=1 - currently we set it only when /sys/module/printk/parameters/time set to 'N')
Some (but not all) of these archs which prints bootloader firmware into serial0.txt (e.g. aarch64, s390x) does not have these messages in dmesg (shutdown_ltp-dmesg.txt file in openqa).
NOTE: not verified on SLE11-SP4_LTSS (hopefully it also has /dev/kmsg).
- https://openqa.suse.de/tests/overview?build=ltp/fix-printing-dmesg-stamps-kmsg
- …

run_ltp: Fix printing command stamps in dmesg

---

lib/utils.pm
schedule/security/create_hdd_cc_libyui/s390x/cc_beta.yaml
schedule/security/create_hdd_cc_libyui/s390x/cc_maint_fde.yaml
schedule/security/create_hdd_cc_libyui/s390x/cc_qr.yaml

Ticket: https://progress.opensuse.org/issues/169072
VRs:
* https://openqa.suse.de/tests/15811372
* https://openqa.suse.de/tests/15811358

Use boot_disk also on installation

---

products/opensuse/main.pm
schedule/functional/upgrade_Leap_15.1_gnome.yaml

- Related ticket: https://progress.opensuse.org/issues/168067
- Needles: n/a
[15.0](https://openqa.opensuse.org/tests/4603484)
[15.1](https://openqa.opensuse.org/tests/4603686#step/consoletest_finish/19)

Disable screensaver for leap 15.x upgrade tw test

---

schedule/security/create_hdd_cc_libyui/aarch64/cc_qr_15sp6.yaml

Related MR: https://gitlab.suse.de/qe-security/osd-sle15-security/-/merge_requests/313
VR: https://openqa.suse.de/tests/overview?distri=sle&version=15-SP6&build=108.1&groupid=431

Add new scheduling file for 15-sp6 QR

---

lib/registration.pm

make registration.pm to support LTSS for 12-SP5 for SAP
- Related ticket: https://jira.suse.com/browse/TEAM-9783
- Verification run: https://openqa.suse.de/tests/15820557

Add LTSS update channel for  SLES for SAP 12-SP5

---

lib/x11utils.pm

Click close button to close opensuse welcome page
- Related ticket: https://progress.opensuse.org/issues/167677
- Verification run: x86 TW: https://openqa.opensuse.org/tests/4606625#step/opensuse_welcome/4
aarch64_cpu_max:  https://openqa.opensuse.org/tests/4606624#
leap 15.6: https://openqa.opensuse.org/tests/4607475#
leap 15.5: https://openqa.opensuse.org/tests/4616795#step/opensuse_welcome/4
leap 15.4: https://openqa.opensuse.org/tests/4616796#step/opensuse_welcome/4

Click close button to close opensuse welcome page

---

data/autoyast_qam/12-common_base_installation.xml.ep

- Related ticket: https://progress.opensuse.org/issues/166295
- Verification run: https://openqa.suse.de/tests/15820154

Add 'LTSS_ES' addon to 12-SP5 AutoYaST xml profile

---

tests/security/tpm2/tpm2_engine/tpm2_engine_ecdsa_operation.pm
tests/security/tpm2/tpm2_env_setup.pm

Ticket: https://progress.opensuse.org/issues/160141
VRs:
* 15-SP6: https://openqa.suse.de/tests/15848173
* 15-SP4: https://openqa.suse.de/tests/15848199
* Tumbleweed: https://openqa.opensuse.org/tests/4617426

Use tpm2-openssl on 15-SP6+

---

lib/transactional.pm

- Related ticket: https://progress.opensuse.org/issues/169189
https://openqa.suse.de/tests/15832595 
**Please ignore the failed job, it is known issue**

Wait more time at grub phase for ppc64le-emu machine

---

tests/transactional/install_updates.pm

- Related ticket: https://progress.opensuse.org/issues/169090
- Needles: n/a
- https://openqa.suse.de/tests/15848231
- https://openqa.suse.de/tests/15848232
- https://openqa.suse.de/tests/15848377
- https://openqa.suse.de/tests/15848377

Wipe audit logs after update on Micro

---

tests/ha/rear_restore.pm

Relax and Recover Scenario fails on ppc64 but not on x86_64, so it is implemented a mechanism to fix on ppc64.
- Related ticket: https://jira.suse.com/browse/TEAM-9655
> - Build 32.2
http://openqa.suse.de/tests/15867526#
http://openqa.suse.de/tests/15867529#
http://openqa.suse.de/tests/15867599#
http://openqa.suse.de/tests/15867600#
> - Build 36.1
https://openqa.suse.de/tests/15866706#
https://openqa.suse.de/tests/15866708#
https://openqa.suse.de/tests/15866709#
https://openqa.suse.de/tests/15866710#

Rear restore in ha

---

lib/main_micro_alp.pm
tests/console/perl_bootloader.pm
tests/transactional/rebootmgr.pm

- Related ticket: https://progress.opensuse.org/issues/167893
- Verification run: [vr](https://openqa.suse.de/tests/overview?distri=sle-micro&version=6.1&build=24.7&groupid=564)
MR for job group changes: https://gitlab.suse.de/qe-core/qa-sle-functional-userspace/-/merge_requests/245

Test slem on powervm

---

data/journal_check/bug_refs.json

Ignore bsc#1230472 for journal_check
- Related ticket: https://progress.opensuse.org/issues/167899
- Verification run: https://openqa.suse.de/tests/15866418#step/journal_check/21

Ignore bsc#1230472 for journal_check

---

tests/yam/agama/agama.pm

Failure: https://openqa.suse.de/tests/15879479#step/agama/1

Increase timeout for slower architectures in Agama

---

data/filesystem/autoyast_filesystem_withouthome_kernel.xml.ep

- Related ticket: https://progress.opensuse.org/issues/169378
- Verification run: https://openqa.suse.de/tests/15869549#step/repos/3

Add LTSS_ES regcode into ay profiles

---

lib/nfs_common.pm

- Related ticket: https://progress.opensuse.org/issues/169552
https://openqa.suse.de/tests/15893138
https://openqa.suse.de/tests/15893139
https://openqa.suse.de/tests/15893141

NFSv2 dropped also on 15-SP6

---

tests/jeos/firstrun.pm

Enroll the recovery key in FDE

---

tests/security/cc/audit_remote.pm
tests/security/cc/ipsec/ipsec_certificate.pm
tests/security/cc/setup_net_test_env.pm

Ticket: https://progress.opensuse.org/issues/169258
VRs: https://openqa.suse.de/tests/overview?distri=sle&version=15-SP6&build=20241107-1&groupid=431
Related MR: https://gitlab.suse.de/qe-security/osd-sle15-security/-/merge_requests/317

Fix s390x multi machine tests

---

tests/containers/buildah.pm

Reverts os-autoinst/os-autoinst-distri-opensuse#20596
* Verification run: https://openqa.suse.de/tests/15918446
* https://openqa.suse.de/tests/15917016
* https://openqa.suse.de/tests/15917018
* https://openqa.suse.de/tests/15917193
* https://openqa.suse.de/tests/15917196
* https://openqa.suse.de/tests/15917225
* https://openqa.suse.de/tests/15917272

Revert "containers: Run buildah tests also as user"

---

data/console/test_openssl_nodejs.sh
data/qam/crypto_rsa_dsa.patch
tests/console/openssl_nodejs.pm

Until it's backported with https://bugzilla.suse.com/show_bug.cgi?id=1232756
https://github.com/nodejs/node/commit/b6d162e0c46fb9090249070f1d812e5684f714f0#diff-d887db4c3a660f9157af263b0c1d1f4bc2f9c4ff419aba165c9231e58209926f

Worarkound missing test patch

---

lib/main_ltp.pm
tests/kernel/update_kernel.pm

- Related fail: https://openqa.suse.de/tests/15931892#step/bootloader#1/3
- Related MR:  https://gitlab.suse.de/kernel-qa/kernelqa-openqa-yaml/-/merge_requests/593
- Needles: NONE
- install ltp: https://openqa.suse.de/tests/15932923
- test run: https://openqa.suse.de/tests/15932924

ltp: Add PowerVM support to maintenance installation and update_kernel

---

tests/qam-updinstall/update_install.pm

- Related ticket: https://openqa.suse.de/tests/15927119#step/update_install/72 https://openqa.suse.de/tests/15938650#step/update_install/115
https://dzedro.suse.cz/tests/1730
https://dzedro.suse.cz/tests/1731

update_install: Fix two small issues

---

tests/containers/bci_test.pm

Upload all tox files for better understanding of test failures.
- Verification run: https://openqa.opensuse.org/tests/4645870

Upload tox files

---

lib/thunderbird_common.pm
tests/x11/evolution/evolution_prepare_servers.pm
tests/x11/evolution/evolution_smoke.pm

- Related ticket: https://progress.opensuse.org/issues/170035
https://dzedro.suse.cz/tests/1758 15-SP4
https://dzedro.suse.cz/tests/1759 15-SP5
https://dzedro.suse.cz/tests/1757 15-SP6

evolution: Update tests for 15-SP6

---

lib/sles4sap/sap_deployment_automation_framework/deployment.pm
tests/sles4sap/sap_deployment_automation_framework/deploy_hanasr.pm

This PR removes workarounds for SDAF bugs which were already solved upstream. 
https://github.com/Azure/sap-automation/issues/617 
https://bugzilla.suse.com/show_bug.cgi?id=1226671
https://github.com/Azure/sap-automation/issues/617
https://bugzilla.suse.com/show_bug.cgi?id=1226671
https://openqaworker15.qa.suse.cz/tests/302978#live

SDAF remove soft failures

---

tests/console/zypper_lifecycle.pm

- Related ticket: https://progress.opensuse.org/issues/170185
- Verification run: https://openqa.suse.de/tests/15997625#step/zypper_lifecycle/147

zypper_lifecycle: Add LTSS_ES exception

---

tests/security/ibmtss/ibmtss_basic_function.pm

This avoids cloning a Git repository from the Internet, thus avoiding a potential code injection.
- Related ticket: https://progress.opensuse.org/issues/169957
- Verification run: https://openqa.suse.de/tests/15997951 (failure unrelated)

Pull test data from our own Git repository

---

tests/installation/bootloader_zkvm.pm
tests/yam/agama/boot_agama.pm

- Related ticket: https://progress.opensuse.org/issues/169477
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/16014137#step/patch_agama_tests/4

Boot Agama in OSD in s390x kvm

---

data/aistack/aistack_gpu_values.yaml
data/aistack/aistack_values.yaml
data/aistack/local_path_storage.yaml
data/aistack/nvidia_gpu_values.yaml
lib/main_micro_alp.pm
tests/publiccloud/create_aistack_env.pm

- Verification run:https://openqa.suse.de/tests/16016794
Both flavor test passed
PR: create test env for AI private-ai-stack test env for 2 flavor sle-micro-6 test env and sle-micro-6 with nvidia driver and gpu enabled

aistack_basic test

---

lib/Yam/Agama/Pom/GrubMenuAgamaPage.pm
schedule/yam/agama_from_usb.yaml
tests/yam/agama/agama_boot_from_hdd.pm

Related ticket: https://progress.opensuse.org/issues/168310
- Needles: -
- O3: https://openqa.opensuse.org/tests/4588690
- OSD: Not yet successful
Still investigating the problem on OSD (SLE 16) why I get a blank screen in `first_boot`: https://openqa.suse.de/tests/15724609#step/first_boot/3

Boot from harddisk after agama installation

---

lib/ipmi_backend_utils.pm
schedule/kernel/ibtest-master-autoyast.yaml
schedule/kernel/ibtest-master-rdma-next.yaml
schedule/kernel/ibtest-master.yaml
schedule/kernel/ibtest-slave-autoyast.yaml
schedule/kernel/ibtest-slave-rdma-next.yaml
schedule/kernel/ibtest-slave.yaml
schedule/kernel/install_ltp_uefi_baremetal.yaml
schedule/kernel/sles4sap/install_sles4sap_baremetal.yaml

See https://github.com/os-autoinst/baremetal_support/pull/25#issuecomment-2478699357

Use default http port for baremetal-support.qa.suse.de

---

tests/security/ibmtss/ibmtss_basic_function.pm

- Related ticket: https://progress.opensuse.org/issues/169579
- Needles: n/a
- Verification runs
- 15SP7: https://openqa.suse.de/tests/16026243
- 15SP6: https://openqa.suse.de/tests/16026244
- Tumbleweed: https://openqa.opensuse.org/tests/4669967

Adapt version of regression testsuite to the package version

---

tests/iscsi/iscsi_client.pm

- Related ticket: https://progress.opensuse.org/issues/169840
- Needles: 
- [Verification runs](https://openqa.suse.de/tests/overview?distri=sle&version=15-SP7&build=rakoenig%2Fos-autoinst-distri-opensuse%23fix_sp7_iscsi_client)

Fix iscsi_client also for SLE 15 SP7

---

tests/qam-updinstall/update_install.pm

Enable --force-resolution --solver-focus Update on new packages
- Related ticket: https://progress.opensuse.org/issues/170197
- Verification run: https://openqa.suse.de/tests/15997651

zypper_lifecycle: Install new packages with solver_focus

---

tests/console/python3_pipx.pm
tests/console/python3_setuptools.pm

https://progress.opensuse.org/issues/169174
Fix some code logic, see https://bugzilla.suse.com/show_bug.cgi?id=1232708#c1
[sle](http://openqa.suse.de/tests/overview?distri=sle&build=rfan1128)
[opensuse](https://openqa.opensuse.org/tests/4671866#details)

Install new packages due to dependency change

---

lib/oscap_tests.pm

SCAP tests expected results optimization
- Related ticket: https://progress.opensuse.org/issues/170275
- Verification runs: (ran all platforms tests on SP7):
https://openqa.suse.de/tests/15987395
https://openqa.suse.de/tests/15987374
https://openqa.suse.de/tests/15987526
https://openqa.suse.de/tests/16015574

SCAP tests expected results optimization

---

tests/security/tpm2/keylime/keylime.pm

- Related ticket: https://progress.opensuse.org/issues/169735
- Needles: n/a
- Verification run: https://openqa.suse.de/tests/16037504

Use correct keylime configuration path on 15SP7

---

tests/microos/networkmanager.pm

- Related ticket: https://progress.opensuse.org/issues/170503  414565e01a33698d6f30a0400b0ca7f645ace753
- Verification run: https://openqa.suse.de/tests/overview?build=jpupava_nmcli&distri=sle-micro&version=6.0

Increase timeout to 120s for nmcli device disconnect

---

lib/Yam/Agama/agama_base.pm

- Related ticket: https://progress.opensuse.org/issues/168925
- Needles: N/A
https://openqa.suse.de/tests/16069479/file/agama_auto-agama-config.log
https://openqa.suse.de/tests/16069480/file/agama-agama-config.log

Include agama config attached to the job in openQA

---

data/journal_check/bug_refs.json

- Related ticket:https://progress.opensuse.org/issues/173530
- VR: n/a [will re-trigger all failed jobs once merged]

Update slem 6.2 journal log white list

---

lib/Installation/InstallationSettings/InstallationSettingsPage.pm

- Related ticket: [poo#169414](https://progress.opensuse.org/issues/169414)
- Verification run: [Overview](https://openqa.suse.de/tests/overview?build=issues-169414)

Fix sporadic fails in disable_boot_menu_timeout

---

data/yam/autoyast/create_hdd_migration_ppc64le.xml.ep

##
Set max root patition and remove s390x related stuff in the profile.
- Related ticket: https://progress.opensuse.org/issues/169789
- Needles: N/A
-  https://openqa.suse.de/tests/16079626
-  https://openqa.suse.de/tests/16079820
##

Cleanup create_hdd_migration_ppc64le.ep

---

data/journal_check/bug_refs.json

http://openqa.suse.de/tests/16082771
http://openqa.suse.de/tests/16083105

Whitelist more bugs for 6.2

---

tests/sles4sap/qesapdeployment/test_cluster.pm

Check cluster health for all CSP and not only for tests running in Azure.
- sle-15-SP6-Qesap-Aws-Byos-x86_64-BuildLATEST_AWS_SLE15_6_BYOS-qesap_aws_fencing_native_test@64bit -> http://openqaworker15.qa.suse.cz/tests/305190 :green_circle: 
- sle-15-SP6-Qesap-Gcp-Byos-x86_64-BuildLATEST_GCE_SLE15_6_BYOS-qesap_gcp_sapconf_test@64bit -> http://openqaworker15.qa.suse.cz/tests/305189 :green_circle: 
-

Qesap regression cluster health

---

tests/jeos/firstrun.pm

Since 46eeb0dd58e6 ("Introduce has_selinux_by_default to version_utils"), it is possible to check whether a product should have SELinux enabled by default. Therefore, verify in jeos/firstrun test module after all other checks.
- Related ticket: https://progress.opensuse.org/issues/168703
https://openqa.opensuse.org/tests/4667497 (Current TW has no SELinux by default, therefore no check)
https://openqa.opensuse.org/tests/4668636/logfile?filename=autoinst-log.txt#line-746 (Current TW but forcing check with VERSION=Staging:D, therefore correct failure)

jeos/firstrun: Check if SELinux is enabled by default

---

tests/publiccloud/download_repos.pm
tests/publiccloud/transfer_repos.pm

VR: 
- http://quasar.suse.cz/tests/188
- http://quasar.suse.cz/tests/189

Remove workaround for buggy wget from PC download repos

---

tests/containers/podman_quadlet.pm

This test makes use of a feature only available for podman > 5.2.0.
- Related ticket: https://progress.opensuse.org/issues/173764
http://rmarliere-openqa.qe.prg2.suse.org/tests/208 (Leap Micro 6.1 with podman 5.0.3)
https://openqa.opensuse.org/tests/4686249 (TW with podman 5.3.1)

podman_quadlet: Check for podman version

---

tests/sles4sap/publiccloud/qesap_ansible.pm

Implement a mechanism for qe-sap-deployment to soft fail tests for ansible known issues
- Related ticket: https://jira.suse.com/browse/TEAM-9862
- Verification run: https://openqaworker15.qa.suse.cz/tests/305391#
https://openqaworker15.qa.suse.cz/tests/305546#
http://openqaworker15.qa.suse.cz/tests/305547#

Ansible known issues

---

tests/security/cc/misc.pm

Ticket: https://progress.opensuse.org/issues/173860
VRs: 
* 15-SP6: https://openqa.suse.de/tests/16145218
* 15-SP5: https://openqa.suse.de/tests/16144204

Reset console before starting cc/misc

---

tests/publiccloud/slem_basic.pm

If PC SL(E)M uses bigger root disk check if size of main partitions is in excepted range
- Related ticket: https://progress.opensuse.org/issues/155941
* http://quasar.suse.cz/tests/224#step/slem_basic/188
* http://quasar.suse.cz/tests/223#step/slem_basic/293

Check root disk filesystems size for PC SLEM

---

tests/security/cc/misc.pm

Ticket: https://progress.opensuse.org/issues/173860

Do not reset console on s390x

---

tests/microos/networkmanager.pm

- Related ticket: https://progress.opensuse.org/issues/173527
- Needles: n/a
- Verification run: https://openqa.suse.de/tests/16170088
**Please ignore the failed job, it is known issue**

Add networkmanager test for slem on powerVM

---

tests/virt_autotest/kubevirt_tests_server.pm

To install dependent packages from other sources for testing use, it requires to allow installing renamed packages.
https://openqa.suse.de/tests/15782859#step/kubevirt_tests_server/78
- Related ticket: https://progress.opensuse.org/issues/168568
- Verification run: https://openqa.suse.de/tests/15811368

Avoid conflicts when installing packages from other sources

---

lib/Distribution/Opensuse/AgamaDevel.pm
lib/bootloader_pvm.pm
lib/bootloader_setup.pm
tests/yam/agama/boot_agama.pm

We have swapped ppc64le machine from svirt to hmc, this includes some changes in the way to boot and manage parameters.
- Related ticket: https://progress.opensuse.org/issues/169480
- Related testing PR: https://github.com/jknphy/agama-integration-test-webpack/pull/47
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/16178556

Boot Agama in OSD in PowerVM

---

tests/console/validate_packages_and_patterns.pm

Use update repo when sles-ltss-release update is tested
Do not expect sles-ltss-release available when LTSS is not released (ALPHA)
- Related ticket: https://progress.opensuse.org/issues/174076
https://openqa.suse.de/tests/16183490#step/validate_packages_and_patterns/5 functional
https://openqa.suse.de/tests/16183487 aggregate without LTSS
https://dzedro.suse.cz/tests/1800 aggregate with LTSS
https://openqa.suse.de/tests/16183483#step/validate_packages_and_patterns/9  incident

validate_packages_and_patterns: Get sles-ltss-release update repo

---

data/publiccloud/terraform/azure.tf
data/publiccloud/terraform/azure_cloud-netconfig.tf
data/publiccloud/terraform/azure_nfstest.tf
lib/publiccloud/azure.pm
lib/publiccloud/ec2.pm
tests/publiccloud/ssh_interactive_end.pm

sle-15-SP6-Azure-BYOS-Updates.x86_64	[publiccloud_consoletests@64bit](https://pdostal-server.suse.cz/tests/7837)	[12](https://pdostal-server.suse.cz/tests/7837)
sle-15-SP6-EC2-BYOS-Updates.aarch64	[publiccloud_img_proof@64bit](https://pdostal-server.suse.cz/tests/7836)	[24 3](https://pdostal-server.suse.cz/tests/7836)
sle-15-SP6-Azure-BYOS-Updates.aarch64	[publiccloud_img_proof@64bit](https://pdostal-server.suse.cz/tests/7832)	[24 2](https://pdostal-server.suse.cz/tests/7832)
sle-15-SP6-EC2-BYOS-Updates.x86_64	[publiccloud_consoletests@64bit](https://pdostal-server.suse.cz/tests/7835)	[12](https://pdostal-server.suse.cz/tests/7835)
sle-15-SP6-GCE-BYOS-Updates.aarch64	[publiccloud_consoletests@64bit](https://pdostal-server.suse.cz/tests/7833) …

PC: Fix the console output collecting process

---

lib/qesapdeployment.pm
t/09_qesapdeployment.t

This is a following for pr#20786. Document the argument `destroy_terraform` and add the unit test for it.
Related: https://jira.suse.com/browse/TEAM-9788

Add unit test for argument 'destroy_terraform'

---

data/journal_check/bug_refs.json

Ignore bsc#1231457 for journal_check
- Related ticket: https://progress.opensuse.org/issues/174103
- Verification run: https://openqa.suse.de/tests/16190344#step/journal_check/9

Ignore bsc#1231457 for journal_check

---

tests/console/gpg.pm

- Related ticket: https://progress.opensuse.org/issues/174112
- Needles: n/a
- Verification run: https://openqa.suse.de/tests/16204116

Make git test not fatal

---

data/yam/agama/auto/default_sle_no_scc.json
lib/autoyast.pm
lib/bootloader_setup.pm
tests/installation/bootloader_s390.pm
tests/installation/bootloader_zkvm.pm
tests/yam/agama/boot_agama.pm

- Related ticket: [poo#173935](https://progress.opensuse.org/issues/173935)
- Verification run: [sles_default_unattended_regcode](https://openqa.suse.de/tests/overview?build=issues-173935)

Pass registration code to jsonnet files

---

schedule/security/create_hdd_cc_libyui/x86_64/cc_qr.yaml
tests/security/cc/cc_audit_test_setup.pm
tests/security/installation/add_on_selection.pm
tests/security/installation/enable_repos.pm
tests/security/installation/module_selection.pm
tests/security/installation/registration.pm

Ticket: https://progress.opensuse.org/issues/174202
VRs:
* 15-SP6: https://openqa.suse.de/tests/overview?distri=sle&version=15-SP6&build=115.2&groupid=431
* 15-SP5: https://openqa.suse.de/tests/overview?distri=sle&version=15-SP5&build=146.3&groupid=431
* 15-SP4: https://openqa.suse.de/tests/overview?distri=sle&version=15-SP4&build=209.1&groupid=431
Related MR: https://gitlab.suse.de/qe-security/osd-sle15-security/-/merge_requests/340

Refactor CC QR scheduling

---

schedule/yam/agama_lvm.yaml

- Related ticket: https://progress.opensuse.org/issues/173968
- Related PR: https://github.com/jknphy/agama-integration-test-webpack/pull/54
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/16233864#live

Add agama lvm test

---

tests/security/ima/ima_kernel_cmdline_hash.pm
tests/security/ima/ima_kernel_cmdline_template.pm
tests/security/ima/ima_measurement.pm

- Related ticket: https://progress.opensuse.org/issues/173569
- https://openqa.suse.de/tests/16250301 
- https://openqa.suse.de/tests/16251015
- https://openqa.suse.de/tests/16251644 (after fixes)

Introduce retry mechanism for IMA counting of measurements

---

data/yam/agama/auto/default_sap_no_scc_plain_password.json
data/yam/agama/auto/default_sle_no_scc_plain_password.json

- Verification run: [sles_default_unattended](https://openqa.suse.de/tests/16252692)

Add file for plain password in Agama

---

schedule/virt_autotest/slem_open_vm_tools.yaml
tests/console/system_prepare.pm

- Related ticket: https://progress.opensuse.org/issues/174037
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/16185917

Longer GRUB timeout for sle-micro on VMware

---

tests/yam/agama/boot_agama.pm

- Related ticket: https://progress.opensuse.org/issues/174508
- Needles: -
- Verification run: https://openqa.suse.de/tests/16238463#

Retrieve logs when failing to sync during boot

---

tests/installation/bootloader_s390.pm

- Needles: N/A
- Verification run: https://openqa.suse.de/tests/16261972#details

Avoid auto installation conflict with dasd format on zVM

---

tests/security/selinux/selinux_setup.pm

- Related ticket: https://progress.opensuse.org/issues/168574
- Needles: no
- Verification run: (fails in later steps for other reasons) 
- https://openqa.opensuse.org/tests/4719794#step/selinux_setup/34

Ensure SELINUX is enabled if expected

---

schedule/yam/agama_lvm_s390x.yaml

- Related ticket: https://progress.opensuse.org/issues/173968
- Needles: N/A
https://openqa.suse.de/tests/16279506#step/reconnect_mgmt_console/9
https://openqa.suse.de/tests/16279523#

Add reconnect_mgmt_console for agama lvm on s390x

---

lib/bootloader_pvm.pm
lib/bootloader_setup.pm
tests/installation/agama_reboot.pm

- Verification run: https://openqa.suse.de/tests/16279534
**The failed test module is known issue, https://bugzilla.suse.com/show_bug.cgi?id=1234678**

Add Agama installation support for powerVM

---

tests/qam-updinstall/update_install.pm

Improve error description on install test
- Related ticket: https://progress.opensuse.org/issues/173887
- Verification run:  cannot verify this PR, as no failed jobs. Will verify this later.

Improve error description on install test

---

lib/opensusebasetest.pm

- Related ticket: https://progress.opensuse.org/issues/174814
- MR related: https://gitlab.suse.de/qe-yam/openqa-job-groups/-/merge_requests/403
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/16300045#

Fix remote_vnc_controller can't boot up issue

---

data/yam/agama/auto/default_sle_no_scc.jsonnet

- Related ticket: quick PR.
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/16332310#step/validate_lvm/2

Fix Agama root login issue on remote worker

---

tests/console/quota.pm

- Related ticket: [https://progress.opensuse.org/issues/164658](https://progress.opensuse.org/issues/164658)
[http://10.146.5.168/tests/470#step/quota/6](http://10.146.5.168/tests/470#step/quota/6)
[http://10.146.5.168/tests/476#step/quota/11](http://10.146.5.168/tests/476#step/quota/11)
[http://10.146.5.168/tests/478#step/quota/6](http://10.146.5.168/tests/478#step/quota/6)
https://openqa.suse.de/tests/16247616
[https://openqa.suse.de/tests/16240306#step/quota/6](https://openqa.suse.de/tests/16240306#step/quota/6)
[http://10.146.5.168/tests/490#step/quota/6](http://10.146.5.168/tests/490#step/quota/6)
[http://10.146.5.168/tests/495#step/quota/6](http://10.146.5.168/tests/495#step/quota/6)
[http://10.146.5.168/tests/498#step/quota/6](http://10.146.5.168/tests/498#step/ …

Fix quotaon

---

tests/yam/agama/patch_agama_tests.pm

- Related PR: https://github.com/jknphy/agama-integration-test-webpack/pull/57
- Verification run: [sles_default](https://openqa.suse.de/tests/16336078#step/patch_agama_tests/8)

Enhance rake logic to avoid installing all tests

---

data/yam/agama/auto/sle_default_multipath.jsonnet
lib/Yam/Agama/agama_base.pm
schedule/yam/agama_multipath_unattended.yaml

##
- Related ticket: https://progress.opensuse.org/issues/173659
- Needles:  boot_agama-agama-configuring-the-product-20241224
-  https://openqa.suse.de/tests/16296528 X86_64
- https://openqa.suse.de/tests/16353511 Aarch64
##

Add unattended multipath test

---

schedule/yam/agama_desktop.yaml

- Related ticket: [poo#168355](https://progress.opensuse.org/issues/168355)
- Verification run: [overview](https://openqa.opensuse.org/tests/overview?build=issues-168355)
- Related [PR#56](https://github.com/jknphy/agama-integration-test-webpack/pull/56)

Add agama interactive installation selecting pattern KDE

---

lib/bootloader_pvm.pm

Need ensure to format disk before installation on pvm for Agama test to avoid risk to reuse existing disk.
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/16362881#details

Format disk before installation on pvm for Agama test

---

schedule/security/selinux.yaml
tests/security/selinux/setroubleshootd.pm

- Related ticket: https://progress.opensuse.org/issues/174175
- Needles: n/a
- Verification run: https://openqa.opensuse.org/tests/4754523

New test for setroubleshootd

---

tests/containers/image.pm

Running podman as root with docker installed may be problematic as netavark uses nftables while docker still uses iptables.
Use workaround suggested in:
- https://fedoraproject.org/wiki/Changes/NetavarkNftablesDefault#Known_Issue_with_docker
- https://docs.docker.com/engine/network/packet-filtering-firewalls/#docker-on-a-router
---
- Related ticket: https://progress.opensuse.org/issues/173362
- Verification run: https://openqa.opensuse.org/tests/4754969

containers: Workaround for podman & docker

---

data/autoyast_qam/15-common_base_installation.xml.ep
data/autoyast_qam/15_installation.xml.ep
data/filesystem/autoyast_filesystem_withouthome_kernel.xml.ep
data/qam/dracut/15_custom_lvm.xml.ep
data/qam/dracut/15_custom_usr.xml.ep
lib/registration.pm
tests/console/zypper_lifecycle.pm

- Related ticket: https://progress.opensuse.org/issues/173959
- Verification run: https://openqa.suse.de/tests/overview?distri=sle&version=15-SP2&build=jpupava_15_sp2_td

Add ltss_td to addons, code and ay profiles

---

data/imagemagick/bg_script.sh
tests/x11/ImageMagick.pm

- Related ticket: https://progress.opensuse.org/issues/170413
- Verification run: https://openqa.suse.de/tests/16364904#step/ImageMagick/248

ImageMagick: Fix and cleanup code

---

data/yam/agama/auto/sap_default.json
data/yam/agama/auto/sap_default_no_scc.json
data/yam/agama/auto/sap_default_no_scc_plain_password.json
data/yam/agama/auto/sle_default.jsonnet
data/yam/agama/auto/sle_default_no_scc.jsonnet
data/yam/agama/auto/sle_default_no_scc_plain_password.json
data/yam/agama/auto/sle_multipath.jsonnet

We have changed the template to include SCC code.
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/16393741

Update templates product ID for Agama

---

data/imagemagick/bg_script.sh
tests/x11/ImageMagick.pm

Reverts os-autoinst/os-autoinst-distri-opensuse#20906

Revert "ImageMagick: Fix and cleanup code"

---

lib/virt_autotest/utils.pm
tests/virt_autotest/uefi_guest_verification.pm

* **According** to information about changes made by Jira feature PED-87 Do NOT auto-generate EFI secret-key for hibernation verification, it is necessary to regenerate key by ```echo 1 > /sys/firmware/efi/secret-key/regen before power management```.
* **New** subroutine ```execute_over_ssh``` to run command over ssh connection.
* **New** subroutine ```reboot_virtual_machine``` to try to reboot virtual machine and ensure it boots up again.
* **New** subroutine ```regen_efi_secret_key``` to be called for SLE 15 host or guest before doing ```hybrid``` and ```disk``` suspend/wakeup
* [uefi-gi-guest_developing-on-host_developing-kvm](https://openqa.suse.de/tests/16379390)
* [uefi-gi-guest_developing-on-host_sles15sp6-kvm](https://openqa.suse.de/tests/16379392)
* …

Regenrate EFI secret key before power management

---

lib/autoyast.pm
tests/yam/agama/boot_agama.pm
tests/yam/agama/import_agama_profile.pm

Added section to expand `AGAMA_PROFILE` and `AGAMA_AUTO` variables
- Needles: N/A
- https://openqa.suse.de/tests/16394077
- https://openqa.suse.de/tests/16394068

Expand profile and auto variables

---

tests/security/selinux/setroubleshootd.pm

- Related ticket: https://progress.opensuse.org/issues/175114
- Needles: no
- https://openqa.suse.de/tests/16404768
- https://openqa.suse.de/tests/16404769
- https://openqa.suse.de/tests/16404770
- https://openqa.suse.de/tests/16404771
- https://openqa.suse.de/tests/16404772
- https://openqa.suse.de/tests/16404773
- https://openqa.suse.de/tests/16404774

Avoid running setroubleshootd on SLE yet

---

schedule/functional/extra_tests_we_gnome.yaml
schedule/functional/extra_tests_we_other.yaml

https://gitlab.suse.de/qe-core/qa-sle-functional-userspace/-/merge_requests/254
- Related ticket: https://progress.opensuse.org/issues/170413
- Verification run: https://openqa.suse.de/tests/overview?distri=sle&version=15-SP7&build=jpupava_we

Move tests from we-module to extratests

---

tests/yam/agama/boot_agama.pm

failed job: https://openqa.suse.de/tests/16405456#
- Related ticket: https://progress.opensuse.org/issues/174943
- Needles: N/A

Remove expand_profile_url code section

---

tests/yam/agama/agama.pm

- Related ticket: [poo#166151](https://progress.opensuse.org/issues/166151)
+ [osd](https://openqa.suse.de/tests/overview?build=issues-166151)
+ [o3](https://openqa.opensuse.org/tests/overview?build=issues-166151)

Enable TAP for agama testing results

---

tests/yam/agama/agama.pm

Reverts os-autoinst/os-autoinst-distri-opensuse#20912

Revert "Enable TAP for agama testing results"

---

lib/publiccloud/utils.pm

A specific registercloudguest on a specific SP version has issue that result in a warning about IPv6 to result in a registration failure due to an error in its internal exception handling.
Issue has been already fixed. But getting the update on BYOS images needs image to be registered. It is not possible due to the bug itself. Temporary use SUSEConnect in this particular situation waiting for an image refresh.
- Related ticket: https://jira.suse.com/browse/TEAM-9827
- Related bug: https://bugzilla.suse.com/show_bug.cgi?id=1217583
http://openqaworker15.qa.suse.cz/tests/310197#step/registration/25 :green_circle: 
- sle-15-SP6-Azure-SAP-BYOS-Incidents-saptune-x86_64-Build:36947:dtb-armv7l-sles4sap_gnome_saptune_notes@az_Standard_E4s_v3 ->  Softfail not active …

Add workaround for bsc#1217583

---

lib/publiccloud/utils.pm
lib/registration.pm

Reverts os-autoinst/os-autoinst-distri-opensuse#20942

Revert "PC: Register LTSS via proper binary"

---

schedule/yam/agama_full_disk_encryption_s390x.yaml

##
- Needles: N/A
- https://openqa.suse.de/t16444984

Add reconnect_mgmt_console for sles_full_disk_encryption

---

schedule/security/fips/ppc64le/fips_env_mode_powervm.yaml
schedule/security/fips/ppc64le/fips_ker_mode_powervm.yaml

https://progress.opensuse.org/issues/174688

Add FIPS schedules for ppc64le

---

schedule/yam/agama_full_disk_encryption_ppc64le.yaml

- Related ticket: N/A quick PR.
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/16474411#details

Add reconnect for sles_full_disk_encryption on powerVM

---

lib/openjdktest.pm

Ticket: https://progress.opensuse.org/issues/175383
VRs: [sp4](https://openqa.suse.de/tests/16474862), [sp6](https://openqa.suse.de/tests/16474861), [sp7](https://openqa.suse.de/tests/16475362)

Use jsch from official repo

---

test_data/yam/agama_leap.yaml

- Related ticket: [poo#166151](https://progress.opensuse.org/issues/166151)
- Verification run: [Leap](https://openqa.opensuse.org/tests/overview?build=fix-validate-leap)
- Related [PR#68](https://github.com/jknphy/agama-integration-test-webpack/pull/68)

Fix validate Leap

---

data/security/crypto_policies/test_nss_client.sh
tests/security/crypto_policies/crypto_policies_tests.pm

- Related ticket: https://progress.opensuse.org/issues/175566
- Needles: no
- https://openqa.suse.de/tests/16491900
- https://openqa.suse.de/tests/16491901

New test for nss crypto policies

---

schedule/functional/extra_tests_textmode_sle16.yaml
tests/console/ovn.pm
tests/console/pam.pm

Package testing on SLE16
- Related ticket: https://progress.opensuse.org/issues/174946
- Verification run: https://openqa.suse.de/tests/16405106#
https://openqa.suse.de/tests/16405105
https://openqa.suse.de/tests/16506159

Package testing on SLE16

---

data/security/crypto_policies/test_nss_client.sh
tests/security/crypto_policies/crypto_policies_tests.pm

- Related ticket: https://progress.opensuse.org/issues/175731
- Needles: no
- https://openqa.opensuse.org/tests/4791969
- https://openqa.suse.de/tests/16506454
- https://openqa.suse.de/tests/16506455

Install openssl pkg needed for nss cryptopolicy test

---

lib/publiccloud/provider.pm

When trying to apply a terraform plan in a region that does not have a NVIDIA GPU available as required, retry in the suggested zones (GCE). As a prerequisite, it was needed to refactor the way of assembling the terraform command in the $cmd variable.
- Related ticket: https://progress.opensuse.org/issues/175590
- Verification run: https://rmarliere-openqa.qe.prg2.suse.org/tests/1165

publiccloud/provider: Retry `terraform apply` with suggested zones

---

tests/yam/agama/boot_agama.pm

Complement https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/20984/

Remove expansion of agama profile from boot

---

data/yam/agama/auto/sle_root_filesystem_ext4.jsonnet
data/yam/agama/auto/sle_root_filesystem_xfs.jsonnet
schedule/yam/agama_non_default_root_filesystem.yaml
schedule/yam/agama_non_default_root_filesystem_ppc64le.yaml
schedule/yam/agama_non_default_root_filesystem_s390x.yaml
test_data/yam/agama_ext4.yaml
test_data/yam/agama_ext4_s390x.yaml
test_data/yam/agama_ext4_spvm.yaml
test_data/yam/agama_xfs.yaml
test_data/yam/agama_xfs_s390x.yaml
test_data/yam/agama_xfs_spvm.yaml

Add unattended installation with ext4 and xfs.
- Related ticket: https://progress.opensuse.org/issues/175263
- Needles: n/a
- Verification run: [vrs](https://openqa.suse.de/tests/overview?version=agama-10.0&distri=sle&build=chcao_poo_175263)

Add unattended installation with ext4 and xfs

---

data/journal_check/bug_refs.json

- Verification run: not required

Log checker:Ignore following known issues

---

lib/publiccloud/provider.pm

Check the output of the awscli tool and if it's "None", kill the test.
- Related ticket: https://progress.opensuse.org/issues/175500
- Verification run: https://openqa.suse.de/tests/16537158#step/prepare_instance/111 (expected failure)

publiccloud/provider: Check if EC2 zone supports selected instance type

---

data/agama_auto/leap_default.jsonnet
schedule/functional/leap16/agama_create_hdd_textmode_leap.yaml

- Related ticket: https://progress.opensuse.org/issues/175350
- Verification run: x86_64: https://openqa.opensuse.org/tests/4777079
aarch64: https://openqa.opensuse.org/tests/4774712 
- Related PR: https://github.com/os-autoinst/opensuse-jobgroups/pull/579

Added create_hdd_textmode_agama_auto for leap 16.0

---

tests/console/java.pm
tests/console/libvorbis.pm
tests/toolchain/install.pm

Skip the installation of addon products on SLES16.
- Verification run: https://openqa.suse.de/tests/16544410

Don't install additional products on SLES16

---

tests/qam-updinstall/update_install.pm

- Related ticket: https://openqa.suse.de/tests/16547823
- Verification run: https://openqa.suse.de/tests/16547949

update_install: Add openvpn-dco conflict

---

data/yam/agama/auto/sle_lvm.jsonnet

- Needles: N/A
- Verification run: https://openqa.suse.de/tests/16552460#details

Fix invalid id in lvm storage section

---

schedule/sles4sap/sles4sap_gnome_saptune_product.yaml

Add something has been leaved out in https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/20274
- Related ticket: https://jira.suse.com/browse/TEAM-9985
- sle-15-SP7-Azure-SAP-BYOS-x86_64-Build0536-sles4sap_gnome_saptune_delete_rename@az_Standard_E8s_v3 -> http://openqaworker15.qa.suse.cz/tests/311575 :green_circle:

Add PUBLIC_CLOUD_SSH_CONFIG to mr_test product

---

data/imagemagick/bg_script.sh
tests/x11/ImageMagick.pm

- Related ticket: https://progress.opensuse.org/issues/170413
https://openqa.suse.de/tests/overview?distri=sle&build=jpupava_IM
https://dzedro.suse.cz/tests/1933

ImageMagick: Fix and cleanup bg_script.sh

---

schedule/yam/agama_remote_pvm.yaml
schedule/yam/agama_remote_s390x.yaml

- Needles: N/A
- Verification run: https://openqa.suse.de/tests/16561877#step/reconnect_mgmt_console/9

Add scripts to wipe disk on s390x kvm

---

tests/console/dstat.pm

- Needles: (removed soft-fail needle) https://gitlab.suse.de/openqa/os-autoinst-needles-sles/-/commit/b652f552505406f17689c88dc4f3745b60696979
- Verification run: https://openqa.suse.de/tests/16542798

dstat: Remove bsc#1085238 soft fail

---

tests/virt_autotest/guest_migration_src.pm

see https://github.com/SUSE/qa-automation/pull/857
@alice-suse @waynechen55 @guoxuguang and others, welcome review!

Remove softfail as bsc#1230971 has been fixed

---

lib/Yam/Agama/Pom/RebootTextmodePage.pm
schedule/yam/agama_remote_s390x.yaml
tests/yam/agama/agama.pm

Verification runs: https://openqa.suse.de/tests/overview?build=jknphy%2Fos-autoinst-distri-opensuse%23boot-hd-s390x-svirt&distri=sle&version=16.0

Boot Agama s390x svirt from hd

---

schedule/yam/agama_full_disk_encryption_s390x.yaml

Use legacy module to introducting passphrase twice

---

tests/console/java.pm

Do not activate and/or remove the sle-module-legacy on SLES16.
- Related failure: https://openqa.suse.de/tests/16556303#step/java/38
- Verification run: https://openqa.suse.de/tests/16581662#step/java/1 https://openqa.suse.de/tests/16581775#step/java/1

No Legacy module on SLES16

---

tests/security/mariadb/mariadb_ssl_client.pm

- Related ticket: https://progress.opensuse.org/issues/176211
- Verification run: https://openqa.suse.de/tests/16581762

Expand MariaDB test coverage

---

tests/network/cifs.pm

Custom paths like /srv/samba/ need to be explicitly allowed.
- Related ticket: https://progress.opensuse.org/issues/175839
- Verification run: https://openqa.opensuse.org/tests/4812451

network/cifs.pm: SELinux-aware directory creation

---

tests/publiccloud/check_registercloudguest.pm

`/etc/containers/registries.conf` permissions are not correct due to problems described in https://bugzilla.suse.com/show_bug.cgi?id=1233333
This PR creates a workaround that sets the correct permissions that are aligned with the permission provided by packaged `registries.conf` file.
- ticket: https://progress.opensuse.org/issues/176055
- VR: http://kepler.suse.cz/tests/24282#step/check_registercloudguest/173

Workaround registries.conf permissions after registration

---

lib/containers/k8s.pm

In order to have working tests for k3s, add soft-failure for https://github.com/k3s-io/k3s/issues/11676
- Related ticket: https://progress.opensuse.org/issues/176061
- https://openqa.opensuse.org/tests/4815986
- https://openqa.opensuse.org/tests/4815988

containers: Add soft-failure for gh#k3s-io/k3s#11676

---

data/journal_check/bug_refs.json

https://suse.slack.com/archives/C044KDGKW58/p1738062622725589
Example of failure: https://openqa.suse.de/tests/16591933#step/journal_check/13
VR: http://openqa.suse.de/tests/16605034

Whitelist sporadic ssh errors in journal

---

data/yam/agama/auto/sle_default.jsonnet

- Verification run: [sles_lvm_encrypted](https://openqa.suse.de/tests/overview?build=fix-boot-timeout)

Fix bootloader timeout

---

schedule/yam/agama_lvm_encrypted_s390x.yaml

Try to fix: https://openqa.suse.de/tests/16625118

Fix lvm encrypted schedule

---

tests/publiccloud/transfer_repos.pm

https://openqa.suse.de/tests/16626059#

Change SLM 6+ handling in transfer repos to support more repositories

---

data/yam/agama/auto/lvm_encrypted.jsonnet

Add `bootloader` section in jsonnet to stop on boot menu .
- Verification run: https://openqa.suse.de/tests/16639887

Quickfix for sporadic grub issue on PowerVM

---

data/microos/utt.repo
tests/transactional/transactional_update.pm

- Related ticket: https://suse.slack.com/archives/C02CANHLANP/p1738520014986349
- Verification run: https://openqa.suse.de/tests/16640958#step/transactional_update/73

transactional_update: Use local update-test-trivial repo

---

lib/security/openssl_misc_utils.pm

Ticket: https://progress.opensuse.org/issues/176445

Only install openssl 1.x on SLE <=15.7

---

lib/security/openssl_misc_utils.pm
tests/fips/openssl/openssl_fips_alglist.pm
tests/fips/openssl/openssl_fips_cipher.pm
tests/fips/openssl/openssl_fips_dhparam.pm
tests/fips/openssl/openssl_fips_hash.pm
tests/fips/openssl/openssl_pubkey_dsa.pm
tests/fips/openssl/openssl_pubkey_rsa.pm
tests/fips/openssl/openssl_tlsv1_3.pm

https://progress.opensuse.org/issues/175135

Fix OpenSSL FIPS testing on SLE 16

---

data/agama_auto/leap_default.jsonnet

Remove the hardcode password on the data directory
- Verification run: https://openqa.opensuse.org/tests/4834189#
https://openqa.opensuse.org/tests/4834186#

Remove the hardcode password on the data directory

---

schedule/functional/sle16/agama-create-hdd-textmode_s390x_kvm.yaml
tests/installation/agama_reboot.pm
tests/installation/bootloader_zkvm.pm

https://progress.opensuse.org/issues/174685
- Verification run: https://openqa.suse.de/tests/16679425

Enable s390x install tests on sle16

---

tests/console/firewalld.pm
tests/console/mdadm.pm
tests/fips/strongswan/strongswan_client.pm
tests/fips/strongswan/strongswan_server.pm
tests/fips/stunnel.pm
tests/security/dm_crypt.pm
tests/security/vsftpd/vsftpd_setup.pm

Ticket: https://progress.opensuse.org/issues/175135
Related MR: https://gitlab.suse.de/qe-security/osd-sle15-security/-/merge_requests/373
VRs:
* SLE16: https://openqa.suse.de/tests/overview?distri=sle&version=16.0&build=5.1&groupid=431
* 15-SP6: https://openqa.suse.de/tests/overview?distri=sle&version=15-SP6&build=20250205-1&groupid=431
* 15-SP4: https://openqa.suse.de/tests/overview?distri=sle&version=15-SP4&build=20250205-1&groupid=431

Update security tests to work with SLES 16

---

tests/console/rsync_client.pm
tests/console/rsync_server.pm

https://progress.opensuse.org/issues/175785
[sle16](https://openqa.suse.de/tests/16694432#dependencies)

Install package 'rsync' if it doesn't exist

---

lib/publiccloud/azure.pm
lib/publiccloud/ec2.pm
lib/publiccloud/gce.pm

- Fixing: #21104
- Related ticket: [poo#155116](https://progress.opensuse.org/issues/155116)
[Build20250204-1](https://pdostal-server.suse.cz/tests/overview?build=20250204-1&distri=sle&version=15-SP6) of sle-15-SP6-Azure-BYOS-Updates.x86_64	  [publiccloud_consoletests@64bit](https://pdostal-server.suse.cz/tests/8238)	[11 1](https://pdostal-server.suse.cz/tests/8238)
[Build20250204-1](https://pdostal-server.suse.cz/tests/overview?build=20250204-1&distri=sle&version=15-SP6) of sle-15-SP6-GCE-Updates.x86_64	  [publiccloud_consoletests@64bit](https://pdostal-server.suse.cz/tests/8244)	[12](https://pdostal-server.suse.cz/tests/8244)
[Build20250204-1](https://pdostal-server.suse.cz/tests/overview?build=20250204-1&distri=sle&version=15-SP6) of …

PC: Fix bootlog asset file name

---

lib/containers/bats.pm
tests/containers/buildah_integration.pm
tests/containers/podman_integration.pm
tests/containers/runc_integration.pm
tests/containers/skopeo_integration.pm

Add a common fail_hook to all BATS tests so we can collect logs.  We need it to debug SELinux in Tumbleweed.
- buildah: https://openqa.opensuse.org/tests/4838864
- podman: https://openqa.opensuse.org/tests/4838889
Notes:
- The above VR's will fail because of SELinux issue.
- We unconditionally collect these logs as we "skip" subtests with the BATS_SKIP variables and they contain useful information.

containers: Add fail_hook to BATS tests

---

lib/Utils/Logging.pm

https://progress.opensuse.org/issues/176631
- Verification run: https://openqa.suse.de/tests/16702406

Upload audit log in post_fail_hook

---

tests/containers/podman_integration.pm

We must install and configure the desired OCI runtime for the podman upstream tests.
Verification run: https://openqa.suse.de/tests/16708394 (it may fail due to https://progress.opensuse.org/issues/176190)

containers: Install desired OCI runtime in podman upstream tests

---

lib/repo_tools.pm
lib/utils.pm

https://progress.opensuse.org/issues/170422
[sle](https://openqa.suse.de/tests/16702216)
[tw](https://openqa.opensuse.org/tests/4839893)

Use http protocol to access OSD repo due to cc

---

lib/containers/bats.pm

We don't run these tests on SLE Micro or MicroOS so a lot of unused code may go away.
- Verification run: https://openqa.opensuse.org/tests/4850086

containers: Simplify bats library

---

lib/x11test.pm

https://progress.opensuse.org/issues/176895
- Verification run: https://openqa.opensuse.org/tests/4850606
- Needle: [Added new one ](https://openqa.opensuse.org/tests/4850606#step/oomath/5)

Close the oomath welcome pop-up window

---

tests/x11/vnc_two_passwords.pm

```
Main issues is that user can't open vnc session on already logged in user and
there are small differences between tigervnc versions and all SLE and openSUSE
versions
- change order of test, first run commands then graphical test
install, get tigervnc version, add test user, setup vnc, test, cleanup
less switching between consoles
- use serial terminal and expect
- install gnome-session-xsession required for session=gnome
on older tigervnc versions -session option is uknown, I removed this option
- define vncpassword three different times, bsc#1171519
- keep old a configuration for older than tigervnc 1.12 & SLE
- xauth is required for newer version, bernhard has to add entry of test :37
- prepare_vnc to maximize (super-up) vnc windows after start, the window
has often different size …
```

vnc_two_passwords: Refactor outdated test

---

tests/console/vsftpd.pm

Related: https://progress.opensuse.org/issues/170467
VR: https://openqa.opensuse.org/tests/4850767#step/vsftpd/5

Allow ftp full access when enable selinux

---

tests/console/yast2_proxy.pm

yast team will not support SELinux in their modules, so adding workarounds in the test that would need to be done manually by the user
- Related ticket: https://bugzilla.opensuse.org/show_bug.cgi?id=1237050
- Needles: N/A
- Verification run: https://openqa.opensuse.org/tests/4853049

Add workaround for yast2-proxy

---

tests/console/ovs_client.pm
tests/console/ovs_server.pm

(poo#176802)
ovs test needs to have correct labels for the keyfiles set to be able to run when SELinux is enabled
- Related ticket: https://progress.opensuse.org/issues/176802
- Needles: N/A
- https://openqa.opensuse.org/tests/4848711
- https://openqa.opensuse.org/tests/4848710
@rfan1

Set correct SELinux labels for ovs test

---

tests/console/python3_beautifulsoup4.pm
tests/console/python3_websocket_client.pm

Related: https://progress.opensuse.org/issues/176952
VR: https://openqa.suse.de/tests/16740706#step/python3_beautifulsoup4/19

Adjust usage of record_info in python3_beautifulsoup4

---

tests/fips/fips_setup.pm

Ticket: 
https://progress.opensuse.org/issues/177003
VRs:
15-SP6 Maintenance with console/apache-ssl enabled:
https://openqa.suse.de/tests/16756243
15-SP6 QU with apache-ssl enabled and clamav disabled enabled:
https://openqa.suse.de/tests/16756244
15-SP4 Maintenance:
https://openqa.suse.de/tests/16756245

Create systemd config for fips_setup on >= 15-SP6

---

data/journal_check/bug_refs.json

https://progress.opensuse.org/issues/177117
- Verification run: https://openqa.suse.de/tests/16759998

Add whitelist for bsc#1234013

---

tests/fips/fips_setup.pm

Also eliminating some warnings reported by perlcritic
Fix Ticket: 
https://progress.opensuse.org/issues/177204
VRs:
x86_64 15-SP6 Maintenance fips_env_mode_gnome
https://openqa.suse.de/tests/16771291
s390x 15-SP6 QU fips_env_mode_gnome
https://openqa.suse.de/tests/16771263
x86_64 15-SP6 Maintenance fips_env_mode_textmode_extra
with apache-ssl enabled
https://openqa.suse.de/tests/16771298

Add FIPS env vars to bashrc in all cases

---

lib/sles4sap_publiccloud.pm

- Related ticket: TEAM-10083
http://openqaworker15.qa.suse.cz/tests/313743 
http://openqaworker15.qa.suse.cz/tests/313750

Print services status

---

tests/console/perl_bootloader.pm
tests/installation/bootloader_uefi.pm
tests/jeos/firstrun.pm

- Related ticket: https://progress.opensuse.org/issues/175794
https://github.com/os-autoinst/opensuse-jobgroups/pull/596
- Verification run: https://openqa.opensuse.org/tests/4854528

Enable wizard on encrypted Leap system

---

tests/qam-updinstall/update_install.pm

- Related ticket: https://progress.opensuse.org/issues/176928
- Verification run: https://openqa.suse.de/tests/16804873

update_install: Add libica-devel conflicts on s390x

---

lib/services/nginx.pm
schedule/security/fips/sle16/fips_ker_mode_textmode_extra.yaml
tests/console/mdadm.pm
tests/console/quota.pm
tests/console/supportutils.pm
tests/security/dm_crypt.pm
tests/security/vsftpd/vsftpd.pm

Ticket: https://progress.opensuse.org/issues/175722
Related MR: https://gitlab.suse.de/qe-security/osd-sle15-security/-/merge_requests/388
VRs:
* 16.0: https://openqa.suse.de/tests/overview?distri=sle&version=16.0&build=5.1&groupid=431 (`fips_ker_mode_textmode_extra`)
* 15.4: https://openqa.suse.de/tests/16804821

Make tests compatible with SLE 16

---

schedule/security/fips/sle16/fips_ker_mode_textmode_core.yaml
schedule/security/fips/sle16/fips_ker_mode_textmode_extra.yaml
tests/console/mdadm.pm
tests/console/openvswitch_ssl.pm
tests/console/quota.pm
tests/security/dm_crypt.pm
tests/security/vsftpd/vsftpd.pm

* remove fatal condition from mdadm, quota and dm_crypt
* use has_selinux instead of has_selinux_by_default
* add missing schedule/security/fips/sle16/fips_ker_mode_textmode_core.yaml
follow-up after #21215

Multiple fixes to various tests

---

tests/security/swtpm/swtpm_env_setup.pm

Ticket: https://progress.opensuse.org/issues/176193
VRs: https://openqa.suse.de/tests/overview?distri=sle&version=15-SP5&build=20250218-1&groupid=431
Related MR: https://gitlab.suse.de/qe-security/osd-sle15-security/-/merge_requests/390

Use autoinst_url to download the asset (swtpm)

---

tests/security/swtpm/swtpm_env_setup.pm

Small improvement after #21244

Remove useless check

---

tests/security/swtpm/swtpm_verify.pm

Fix uefi check on swtpm

---

tests/security/selinux/setroubleshootd.pm

note: the tests are not yet complete due to a [dependency issue](https://bugzilla.suse.com/show_bug.cgi?id=1237388) on sealert 
- Related ticket: https://progress.opensuse.org/issues/174178
- Needles: n/a
- Verification run: https://openqa.opensuse.org/tests/4870201

Add sealert tests

---

lib/publiccloud/basetest.pm

Reverts os-autoinst/os-autoinst-distri-opensuse#21247

Revert "publiccloud: basetest: Upload SUT logs instead of host"

---

lib/publiccloud/basetest.pm

Currently, tests that inherit from publiccloud::basetest are not uploading the correct logs to openQA. Fix by calling the helper _upload_logs before the instance gets destroyed and also making sure to use the upload_log subroutine from publiccloud::instance.
The previous commit a07cb92b5dfb ("publiccloud: basetest: Upload SUT logs instead of host") which got reverted was wrong because it called _upload_logs too early and didn't allow for the necessary checks that trigger early returns to happen.
- Related ticket: https://progress.opensuse.org/issues/176898
- Related PRs: 
https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/21197
https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/21247
https://openqa.suse.de/tests/16847307 …

publiccloud: basetest: Upload SUT logs instead of host

---

lib/sles4sap/azure_cli.pm
t/21_sles4sap_azure_cli.t

- Related ticket: https://jira.suse.com/browse/TEAM-9967
sle-15-SP5-SapCloud-Azure-Byos-x86_64-BuildLATEST_AZURE_SLE15_5_BYOS-ipaddr2_azure_test
- http://openqaworker15.qa.suse.cz/tests/315086 :green_circle:
- http://openqaworker15.qa.suse.cz/tests/315087 :green_circle:
- http://openqaworker15.qa.suse.cz/tests/315088 :green_circle: 
- http://openqaworker15.qa.suse.cz/tests/315089 :green_circle:
- http://openqaworker15.qa.suse.cz/tests/315090 :green_circle:

Fix network address validation

---

.github/workflows/ci.yml
lib/LTP/utils.pm
lib/Mitigation.pm
lib/containers/bats.pm
lib/hpc/cluster.pm
lib/hpc/configs.pm
lib/oscap_tests.pm
lib/x11test.pm
tests/console/clamav.pm
tests/hpc/hpc_support.pm
tests/hpc/slurm_db.pm
tests/kernel_performance/install_qatestset.pm
tests/shutdown/cleanup_before_shutdown.pm
tests/yast2_cmd/yast_dns_server.pm

Match changes in os-autoinst:
https://github.com/os-autoinst/os-autoinst/pull/2667
Perform a full tidy run and change is_sle ? ... to is_sle() ? ... in lib/oscap_tests.pm to avoid syntax errors (false positive?).

Update Perl::Tidy to 20250214

---

data/yam/agama/auto/lvm_encrypted.jsonnet
data/yam/agama/auto/sle_default.jsonnet
data/yam/agama/auto/sle_lvm.jsonnet
data/yam/agama/auto/sle_multipath.jsonnet
data/yam/agama/auto/sle_root_filesystem_ext4.jsonnet
data/yam/agama/auto/sle_root_filesystem_xfs.jsonnet
data/yam/agama/auto/sles_sap_default.jsonnet

Add reg code in profiles for Agama unattended

---

lib/containers/bats.pm

containers: Add more logs to BATS tests

---

tests/console/rmt/rmt_feature.pm

- Related ticket: https://progress.opensuse.org/issues/175902#note-20 https://gitlab.suse.de/qa-maintenance/qam-openqa-yml/-/merge_requests/821
- Verification run: https://openqa.suse.de/tests/16871719

rmt_feature: Use ASSET_1 for data file

---

data/yam/agama/auto/lvm_encrypted_no_reg.jsonnet
data/yam/agama/auto/sle_default_no_reg.jsonnet
data/yam/agama/auto/sle_lvm_no_reg.jsonnet
data/yam/agama/auto/sle_multipath_no_reg.jsonnet
data/yam/agama/auto/sle_root_filesystem_ext4_no_reg.jsonnet
data/yam/agama/auto/sle_root_filesystem_xfs_no_reg.jsonnet
data/yam/agama/auto/sles_sap_default_no_reg.jsonnet

This is needed while we don't have yet a way to generate json dynamically, so we can keep running official job group and development one for Agama.

Add back profile with no registration

---

schedule/functional/extra_tests_gnuhealth.yaml
tests/gnuhealth/mygnuhealth.pm

openQA: Clone https://openqa.opensuse.org/tests/4306125 INCLUDE_MODULES=boot_to_desktop,mygnuhealth

Add test for mygnuhealth

---

data/yam/agama/auto/autoyast_supported.xml
lib/autoyast.pm

- Related ticket: [poo#175096](https://progress.opensuse.org/issues/175096)
- Verification run: [sles_autoyast_supported__TEST__](https://openqa.suse.de/tests/overview?distri=sle&version=16.0&build=5.1&groupid=529)

Create test suite for AutoYaST compatibility focus on supported sections

---

lib/registration.pm

##
- Related ticket: Qiuck PR
- Failed job: https://openqa.suse.de/tests/16917570#step/register_system/38
- Needles: N/A
-  https://openqa.suse.de/tests/16918752
##

Fix module numbers > 16

---

.github/CODEOWNERS

Remove myself from those files due to squad transition.

CODEOWNERS: Remove myself

---

tests/console/velociraptor_client_event_collect.pm

test run : 
x86_64 https://openqa.suse.de/tests/16804702 
s390x https://openqa.suse.de/tests/16922125
aarch64 https://openqa.suse.de/tests/16922126

 Enable tests on sle15-sp7

---

schedule/virt_autotest/sle16_guest_installation.yaml

https://openqa.suse.de/tests/overview?distri=sle&version=16.0&build=5.12&groupid=624
@alice-suse @waynechen55

Disable guest installation test as it is not ready

---

t/12_sles4sap_publicccloud.t
tests/sles4sap/hana_install.pm

Add simple UT, only  system running and degradated
It is about covering https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/21212
- Related ticket: TEAM-10083

Add unit test for wait_hana_node_up

---

tests/transactional/trup_smoke.pm

According to https://bugzilla.suse.com/show_bug.cgi?id=1228126#c5 running `fdectl tpm-authorize` after the bootloader reinstallation.
Related: https://progress.opensuse.org/issues/164024
https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/19748
VR: https://openqa.suse.de/tests/16936255#step/trup_smoke/15

Authorize TPM after reinstalling bootloader

---

data/wsl/Autounattend_Arm64.xml
data/wsl/Autounattend_BIOS.xml
data/wsl/Autounattend_UEFI.xml

- Related ticket: https://progress.opensuse.org/issues/176532
- [Win10 BIOS](https://openqa.suse.de/tests/16950003)
- [Win10 UEFI](https://openqa.suse.de/tests/16950031)
- [Win11 UEFI](https://openqa.suse.de/tests/16950030)

Added the WSL platform installation to the Autounattend

---

tests/security/selinux/selinux_smoke.pm

Review and extend coverage of `selinux_smoke`.
Related ticket: https://progress.opensuse.org/issues/178309
- aarch64: https://openqa.suse.de/tests/16961761
- s390x: (failing to boot due to infra issues)
- x86_64: https://openqa.suse.de/tests/16961694
- SLE12-SP5 x86_64: https://openqa.suse.de/tests/16961767

Update selinux_smoke test

---

tests/security/yast2_users/add_users.pm

Remove softfail for resolved bug
- Related ticket: https://progress.opensuse.org/issues/178318
- 15-SP7: https://openqa.suse.de/tests/16961157
- 15-SP6: https://openqa.suse.de/tests/16961156
- 15-SP5: https://openqa.suse.de/tests/16961157

Remove softfail for resolved bug

---

data/yam/agama/auto/lvm_encrypted_ppc64le.jsonnet
data/yam/agama/auto/sle_default_ppc64le.jsonnet
data/yam/agama/auto/sle_lvm_ppc64le.jsonnet
data/yam/agama/auto/sle_root_filesystem_ext4_ppc64le.jsonnet
data/yam/agama/auto/sle_root_filesystem_xfs_ppc64le.jsonnet

- For all unattended installations we add a PRE script to wipe the disk on ppc64le, so we can avoid troubles when the disk was previously encrypted.

Wipe disks on PowerVM testsuites

---

tests/console/consoletest_setup.pm

Ticket: https://progress.opensuse.org/issues/178297
VRs: https://openqa.suse.de/tests/overview?distri=sle&version=16.0&build=55.3&groupid=431

Install SSH on SLE16

---

tests/fips/squid/squid_reverse_proxy.pm

Make sure sed regex does not mess up apache config if its port is already set to 8080
Make sure curl is using the right squid port and the validation strings are also up to date
- Related ticket: https://progress.opensuse.org/issues/177429
Please be aware that the VRs might fail at some other steps. 
The relevant tests which are needed for this fix are the fips/squid ones.
VRs:
- 15SP6 x86: https://openqa.suse.de/tests/16963035
- 15SP4 x86: https://openqa.suse.de/tests/16963036
- 15SP7 Build69.1:
- ppc: https://openqa.suse.de/tests/16963037

Fix squid reverse proxy test

---

tests/fips/gnutls/gnutls_client.pm

Simple code cleanup.
- Related ticket: https://progress.opensuse.org/issues/178351
- Verification run: https://openqa.suse.de/tests/16964553

Refactor gnutls_client test

---

data/yam/agama/auto/sles_sap_default_ppc64le.jsonnet

Wiping the disk on PowerVM also for the SAP unattended test.

Wipe disk for SAP unattended (ppc64le)

---

data/yam/agama/auto/autoyast_supported.xml

- Related ticket: [poo#175096](https://progress.opensuse.org/issues/175096)
- Verification run: [Flavor: Online](https://openqa.suse.de/tests/overview?build=issues-175096)

Remove Unsupported Sections in ay

---

schedule/containers/create_hdd_agama.yaml

SLES 16 create_hdd_agama yaml schedule variants for the 4 architectures
- Related ticket: https://progress.opensuse.org/issues/175950

SLES16 create hdd agama for each arch-s

---

lib/registration.pm

Reverts os-autoinst/os-autoinst-distri-opensuse#21347

Revert "Removed registration on Full flavor"

---

lib/registration.pm
tests/installation/bootloader_s390.pm
tests/installation/bootloader_zkvm.pm

 Set proxySCC for offline media

---

tests/console/consoletest_setup.pm

Ticket: https://progress.opensuse.org/issues/178441

Use correct logic for SLE16

---

data/yam/agama/auto/sle_default_ppc64le.jsonnet

- Needles: N/A
- Verification run: https://openqa.suse.de/tests/16983269#step/validate_product/1

Fix format issue for sle_default_ppc64le.jsonnet

---

lib/sles4sap/sap_deployment_automation_framework/configure_tfvars.pm
lib/sles4sap/sap_deployment_automation_framework/deployment.pm
t/27_sdaf_configure_tfvars.t
tests/sles4sap/sap_deployment_automation_framework/deploy_sap_systems.pm
tests/sles4sap/sap_deployment_automation_framework/execute_playbooks.pm

Schedule SDAF test in Public Cloud / Latest HA+SAP Job Group 
- Related ticket: [TEAM-9689](https://jira.suse.com/browse/TEAM-9689) - [[SDAF] Schedule SDAF test in Public Cloud / Latest HA+SAP Job Group](https://jira.suse.com/browse/TEAM-9689)
-- https://openqa.suse.de/tests/16960232#step/deploy_sap_systems/146 (PUBLIC_CLOUD_IMAGE_LOCATION=https://\*15-SP7\* IBS img and this img was found)
-- https://openqa.suse.de/tests/16960232#step/execute_playbooks/256 (failed, this failure is a bug of https://github.com/sdaf-suse/sap-automation . I will open a SDAF bug later)
-- https://openqa.suse.de/tests/16961645#dependencies (passed, PUBLIC_CLOUD_IMAGE_ID=suse:sles-sap-15-sp5-byos:gen2:latest)

Schedule SDAF test in PCloud Latest HA+SAP

---

tests/containers/install_updates.pm

- Verification run: http://kepler.suse.cz/tests/24456#step/install_updates/16

Fix version match for tar workaround

---

tests/installation/bootloader_svirt.pm

Sometimes guests were not removed correctly by previous openQA job and they can't be removed by a subsequent openQA job, so those "ghosts" need to be removed manually via the ESXi dashboard. This fix will resolve the problem during automation runs.
- Related ticket: https://progress.opensuse.org/issues/130763
- Verification run: https://openqa.suse.de/tests/16982889

Remove invalid VM by previous openQA job

---

schedule/containers/create_hdd_agama.yaml

SLES16 container host yaml schedule updated
- Related ticket: [175950](https://progress.opensuse.org/issues/175950)

SLES16 container host yaml schedule updated for ppc64

---

tests/containers/podman_quadlet.pm

Fix Quadlet build unit.
- Related ticket: https://progress.opensuse.org/issues/178381
- Needles: N/A
- VRs:
- SLE16: https://openqa.suse.de/tests/16963958#step/podman_quadlet/143
- SLE Micro 6.2: https://openqa.suse.de/tests/17000024#step/podman_quadlet/143

Fix Podman Quadlet build unit

---

tests/security/crypto_policies/crypto_policies_tests.pm

Ticket: https://progress.opensuse.org/issues/177702
Related MR: https://gitlab.suse.de/qe-security/osd-sle15-security/-/merge_requests/404
VRs: https://openqa.suse.de/group_overview/431

Increase timeout when when running certtool

---

data/containers/agama/sle_default.jsonnet
data/containers/agama/sle_default_pvm.jsonnet
data/containers/agama/sle_default_s390x_kvm.jsonnet

SLE16: new repo folder 'data/containers/agama' for hdd creation from iso, in container tests. jsonnet files used in create_hdd tests with agama
3 files from 'agama_auto' folder.
- Related ticket: https://progress.opensuse.org/issues/175950

SLE16: data folder for agama configuration in container tests

---

schedule/yam/agama_nvme.yaml
test_data/yam/agama_nvme.yaml

- Related ticket: https://progress.opensuse.org/issues/176817
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/17011942#details

Create unattended installation for NVMe with Agama

---

tests/security/create_swtpm_hdd/build_hdd.pm

Omit not needed and missing package in case of SLE16
- Related ticket: https://progress.opensuse.org/issues/176691
- VR: 
- https://openqa.suse.de/tests/17002508
- https://openqa.suse.de/tests/17002509
- 15-SP7: https://openqa.suse.de/tests/17001469

Ajdust build_hdd.pm to run on SLE16.

---

tests/containers/container_engine.pm

Use always the latest released python version.
- Verification run: https://openqa.suse.de/tests/17013141#step/podman/366

Remove specific python version

---

tests/installation/agama.pm

Support of new Agama 12 workflow in agama.pm
- Scroll product lists and patterns until match.
- Drop skip to bottom of page to see action btns.
- Drop root password popup.
- Drop clicking on show tabs btn on each tab change.
- Tabs are now now visible on 1024x768.
- Rework root setup dialog.
- Rework define user dialog.
- Add icewm pattern option as a desktop.
- Temporarily disable autologin functionality gh#agama-project/agama#2143
Verification run: https://openqa.opensuse.org/tests/4915335#live

Support of new Agama 12 workflow in agama.pm

---

tests/yam/agama/agama.pm
tests/yam/agama/import_agama_profile.pm

bsc#1237056
- Verification runs: https://openqa.suse.de/tests/overview?distri=sle&build=jknphy%2Fos-autoinst-distri-opensuse%23btrfs-msg&version=16.0

Drop disable/enable print kernel messages in Agama.

---

data/security/agama_auto/sle16_ext4root.jsonnet
schedule/security/sle16/agama_create_hdd_textmode_ext4_mok_enroll.yaml
tests/security/mokutil_sign.pm

Ticket: https://progress.opensuse.org/issues/177832
Related MR: https://gitlab.suse.de/qe-security/osd-sle15-security/-/merge_requests/407
VR: https://openqa.suse.de/tests/17024585

Add agama_create_hdd_textmode_ext4_mok_enroll test

---

tests/console/zypper_lr_validate.pm

https://progress.opensuse.org/issues/178780
VR: https://openqa.suse.de/tests/17038912#

Add pcm  in 'zypper_lr_validate'

---

lib/containers/engine.pm

Remove assertions on cleanup_system_host
Failing test: https://openqa.suse.de/tests/17039875#step/docker_isolation/195

containers: Remove assertions on cleanup_system_host

---

schedule/security/sle16/agama_create_hdd_textmode_ext4_mok_enroll.yaml
tests/security/ima/ima_measurement.pm

Ticket: https://progress.opensuse.org/issues/177838
VRs: https://openqa.suse.de/tests/17039881 + https://openqa.suse.de/tests/17041570

Fix ima_measurement test

---

tests/console/sudo.pm

https://progress.opensuse.org/issues/178453
- Verification run: https://openqa.suse.de/tests/17047395#

Fix 'sudo' logic for sle16

---

lib/main_containers.pm
tests/containers/isolation.pm

Limit isolation test:
- Do not run on transactional systems
- Limit docker test to Tumbleweed
- Limit podman test to non-public cloud
---
- Verification run: https://openqa.opensuse.org/tests/4921949

containers: Limit isolation test

---

data/journal_check/bug_refs.json

https://bugzilla.suse.com/show_bug.cgi?id=1228079 has been resolved
Ignore hibernation messages.

Update list of know issues

---

tests/sles4sap/cloud_netconfig/deploy.pm

also converts the VHD blob to a proper disk image when needed
- Related ticket: https://jira.suse.com/browse/TEAM-10153
- Needles: no
- Verification run: https://openqa.suse.de/tests/17049579

Use public cloud image location when available

---

tests/console/start_systemd_testkit_offline.pm

- Related ticket: https://bugzilla.suse.com/show_bug.cgi?id=1231034
- Verification run: https://dzedro.suse.cz/tests/2499

start_systemd_testkit_offline: Revert softfail and remove false fail

---

schedule/functional/sle16/agama-create-hdd-textmode.yaml

Add back agama-create-hdd-textmode.yaml

---

data/yam/agama/auto/lvm_encrypted_ssh_pub_key_ppc64le.jsonnet
data/yam/agama/auto/scripts_ssh_pub_key.jsonnet
data/yam/agama/auto/sles_default_ssh_pub_key.jsonnet
data/yam/agama/auto/sles_default_ssh_pub_key_ppc64le.jsonnet
data/yam/agama/auto/sles_lvm_ssh_pub_key_ppc64le.jsonnet
data/yam/agama/auto/sles_root_filesystem_ext4_ssh_pub_key_ppc64le.jsonnet
data/yam/agama/auto/sles_root_filesystem_xfs_ssh_pub_key_ppc64le.jsonnet

- Needles: N/A
- Verification run: https://openqa.suse.de/tests/overview?version=16.0&build=lemon-suse%2Fos-autoinst-distri-opensuse%23update-fake-ssh-public-key&distri=sle

Update fake ssh public key for powerVM test

---

data/yam/agama/auto/sles_default_no_registration_ssh_pub_key_ppc64le.jsonnet

Update fake public key for sles_default_no_registration_ppc64le.jsonnet

---

tests/containers/skopeo.pm

Hotfix: Fix skopeo cleanup.
- Failing test: https://openqa.suse.de/tests/17062250#step/podman_skopeo/81
- Verification run: https://openqa.suse.de/tests/17077657#step/podman_skopeo/81

containers: Fix skopeo cleanup

---

tests/containers/rootless_podman.pm

Remove `check_bsc1200623`.
The check for [bsc#1200623](https://bugzilla.suse.com/show_bug.cgi?id=1200623) is no longer relevant here for 2 reasons:
- This bug happened in an old version of podman on 15-SP2 on s390x only.  We no longer test either podman 2.x or 15-SP2.
- The way this function was implemented (via soft-failure) actually prevented us from catching this bug again, ever since.
So it's better for the `rootless_podman` module to fail hard & fail fast if `$cid` contains extra characters.
- s390x: https://openqa.suse.de/tests/17077741
- 15-SP3: https://openqa.suse.de/tests/17077771

containers: Remove check_bsc1200623

---

data/yam/agama/auto/lvm_encrypted_ssh_pub_key.jsonnet
data/yam/agama/auto/sles_default_no_registration_ssh_pub_key.jsonnet
data/yam/agama/auto/sles_lvm_ssh_pub_key.jsonnet
data/yam/agama/auto/sles_root_filesystem_ext4_ssh_pub_key.jsonnet
data/yam/agama/auto/sles_root_filesystem_xfs_ssh_pub_key.jsonnet

Update fake ssh public key for s390x

---

tests/x11/flatpak.pm

Close GIMP welcome page
- Related ticket: https://progress.opensuse.org/issues/179059
- Verification run: https://openqa.suse.de/tests/17082272#

Close GIMP welcome page

---

tests/fips/stunnel.pm

Ticket: https://progress.opensuse.org/issues/178405

Add openssl to stunnel

---

lib/audit_test.pm
tests/security/cc/syscalls.pm

Ticket: bsc#1232518
Related MRs: 
* https://gitlab.suse.de/qe-security/osd-sle15-security/-/merge_requests/410
* https://gitlab.suse.de/security/audit-test-sle15/-/merge_requests/65
VRs:
* 15-SP7: https://openqa.suse.de/tests/overview?distri=sle&version=15-SP7&build=74.1&groupid=431
* 15-SP6: https://openqa.suse.de/tests/overview?distri=sle&version=15-SP6&build=20250318-1&groupid=431
* 15-SP4: https://openqa.suse.de/tests/overview?distri=sle&version=15-SP4&build=20250318-1&groupid=431
* 15-SP3: https://openqa.suse.de/tests/overview?distri=sle&version=15-SP3&build=20250318-1&groupid=431

Fix syscalls test on 15-SP6 and greater

---

tests/containers/podman_netavark.pm

- clean the virtual interfaces after container clean up
- busybox@s390x is still broken and cannot perform ping
- [o3](http://kepler.suse.cz/tests/24499#step/podman_netavark/339)
- sle-15-SP6-Server-DVD-Updates-s390x-Build20250318-1-podman_tests@s390x-kvm -> https://openqa.suse.de/tests/17090631#step/podman_netavark/268

Minor netavark fixes

---

tests/installation/release_notes_from_url.pm

Related [PR#21498](https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/21498) already merged

Remove commented code

---

tests/console/gpg.pm

Remove haveged package test refer bsc#1239023
- Related ticket: https://progress.opensuse.org/issues/179158
- Verification run: https://openqa.suse.de/tests/17101384#step/gpg/161

Remove haveged package test refer bsc#1239023

---

schedule/yam/agama_auto.yaml
schedule/yam/agama_extended.yaml
test_data/yam/agama_sle_extended.yaml
tests/yam/validate/validate_hostname.pm

- Related ticket: [poo#177213](https://progress.opensuse.org/issues/177213)
- Verification run: [Flavor: Online](https://openqa.suse.de/tests/overview?build=issues-177213)

Add test cases for setting hostname in Agama

---

lib/services/389ds_sssd_client.pm

Ticket: https://progress.opensuse.org/issues/175434
VR: https://openqa.opensuse.org/tests/4938955

Fix permissions on certificate for sssd in newer versions

---

tests/console/dpdk.pm

- Related ticket: https://progress.opensuse.org/issues/178165
[sle](http://openqa.suse.de/tests/17090009#details)
[tw](https://openqa.opensuse.org/tests/overview?distri=opensuse&version=Tumbleweed&build=rfan0319)
PR/MR for job group yaml files:
sle: https://gitlab.suse.de/qe-core/qa-sle-functional-userspace/-/merge_requests/260
tw: https://github.com/os-autoinst/opensuse-jobgroups/pull/618

Enable iommu on  L1 guest for dpdk test

---

tests/console/clamav.pm
tests/security/apparmor_profile/apache2_changehat.pm
tests/security/tpm2/keylime/keylime.pm
tests/security/tpm2/tpm2_measured_boot.pm

Ticket: https://progress.opensuse.org/issues/179365
Related MR: https://gitlab.suse.de/qe-security/openqa-data/-/merge_requests/419

Skip tests based on conditions

---

schedule/virt_autotest/sle16_default_svirt.yaml
tests/installation/bootloader_hyperv.pm
tests/yam/agama/agama_auto_without_log.pm

Implement automated testing for SLE 16 Hyper-V
Related job group MR: https://gitlab.suse.de/qa-testsuites/openqa-job-group-yaml/-/merge_requests/263
- Related ticket: https://progress.opensuse.org/issues/163658
- Needles: new needle: boot_agama-agama-installing-20250317
2016: https://openqa.oqa.prg2.suse.org/tests/17133907  (bug: 1217800)
2019: https://openqa.oqa.prg2.suse.org/tests/17133906
2022: https://openqa.oqa.prg2.suse.org/tests/17133908

Implement automated testing for SLE 16 Hyper-V

---

schedule/qam/common/mau-extratests-desktop.yaml
tests/x11/network/NM_wpa2_enterprise.pm
tests/x11/network/hwsim_wpa2_enterprise_setup.pm
tests/x11/network/yast2_network_use_nm.pm

Add necessary changes and schedule network tests for SLES
- Related ticket: https://progress.opensuse.org/issues/156466
- Verification run: https://openqa.suse.de/tests/17145973 (15-SP6)
15-SP5:https://openqa.suse.de/tests/17145975
15-SP4: https://openqa.suse.de/tests/17145976
15-sp3: https://openqa.suse.de/tests/17145977
15-sp2:https://openqa.suse.de/tests/17145979

Add necessary changes and schedule network tests for SLES

---

tests/console/clamav.pm
tests/security/apparmor_profile/apache2_changehat.pm
tests/security/tpm2/keylime/keylime.pm
tests/security/tpm2/tpm2_measured_boot.pm

VRs: https://openqa.suse.de/tests/17147358 and https://openqa.suse.de/tests/17147355

Fix clamav and changehat tests

---

data/yam/agama/auto/lib/storage.libsonnet
data/yam/agama/auto/template.libsonnet

On the last change we modified storage generation to accommodate to the language checker. This modification lead to a structure error that lead to unattended test error, this PR solve the previous error.
- Related ticket: https://progress.opensuse.org/issues/175111
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/17148217

Solve storage JSONNET profile definition error

---

tests/publiccloud/run_ltp.pm

Ticket : https://progress.opensuse.org/issues/178831
VRs : https://openqa.suse.de/tests/17151384

Tweak kernel to output all messages in serial terminal

---

tests/qam-updinstall/update_install.pm

- Related ticket: https://gitlab.suse.de/qa-maintenance/metadata/-/merge_requests/1316
- Verification run: https://dzedro.suse.cz/tests/2522

update_install: Don't run snapper rollback on sle11

---

tests/installation/bootloader_s390.pm
tests/installation/bootloader_zkvm.pm

After the merge I detected an error on Perl syntax based on latest changes.
- Related ticket: https://progress.opensuse.org/issues/179290
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/17162157

Fix s390x booting of Full medium

---

data/journal_check/bug_refs.json

Issue example: https://openqa.suse.de/tests/17137640#step/journal_check/10
VR: https://openqa.suse.de/tests/17162520

Whitelist bsc 1227081 - dbus-broker-launch

---

data/autoyast_qam/12_installtest.xml.ep
data/autoyast_qam/15_installtest.xml.ep
tests/qam-updinstall/update_install.pm

- Related ticket: https://openqa.suse.de/tests/16948797#step/update_install/122
https://openqa.suse.de/tests/17162498#step/repos/5 HA 15-SP6 with SAP bone
https://openqa.suse.de/tests/17162499#step/repos/5 SAP 15-SP6 without SAP bone
https://openqa.suse.de/tests/17162501#step/repos/5 SLES 15-SP6 with SAP bone
https://openqa.suse.de/tests/17162522#step/repos/3 12-SP3 with TERADATA::12-SP3::update
https://dzedro.suse.cz/tests/2528 docker

Update installtest ay profiles

---

tests/console/ansible.pm

In sle16+ ansible is supported, however due to packaging and python specifics, minor updates to the test module are required.
* [sle16](http://kepler.suse.cz/tests/24569#step/ansible/1)
* [microos](http://kepler.suse.cz/tests/24561#step/ansible/2)
* [sp7](http://kepler.suse.cz/tests/24565#step/ansible/1)
* [sp6](http://kepler.suse.cz/tests/24564#step/ansible/1)
* [sp5](http://kepler.suse.cz/tests/24563#step/ansible/1)
* [sp4](http://kepler.suse.cz/tests/24562#step/ansible/1)
* [sp3](http://kepler.suse.cz/tests/24567#step/ansible/114)
* [sp5 fips on](http://kepler.suse.cz/tests/24568#step/ansible/1)

Update ansible test module

---

schedule/yam/agama_software_patterns.yaml
schedule/yam/agama_software_patterns_s390x.yaml
tests/yam/validate/validate_installed_patterns.pm

##
- Related PR:
-  https://github.com/jknphy/agama-integration-test-webpack/pull/85
- https://progress.opensuse.org/issues/176484
- Needles: N/A
- [**Software_selection**](https://openqa.suse.de/tests/overview?arch=&flavor=Online&machine=&test=&modules=&module_re=&group_glob=&not_group_glob=&comment=&version=16.0&build=hjluo_kvm_host&distri=sle#)

Add select pattern for agama interactive installation

---

data/yam/agama/auto/lib/addons.libsonnet
data/yam/agama/auto/template.libsonnet
schedule/yam/agama_unattended_patterns.yaml
tests/yam/validate/validate_installed_patterns.pm

- Related ticket: https://progress.opensuse.org/issues/179347
- Needles: N/A
SLE 16 production group:  https://openqa.suse.de/tests/overview?distri=sle&version=16.0&build=lemon-suse%2Fos-autoinst-distri-opensuse%23add-profiles-for-sles-ha
development group:  https://openqa.suse.de/tests/overview?version=agama-10.0&build=lemon-suse%2Fos-autoinst-distri-opensuse%23add-profiles-for-sles-ha&distri=sle

Automate support extension in unattended installation (HA)

---

schedule/yam/agama_lvm_encrypted_unattended.yaml
schedule/yam/agama_lvm_encrypted_unattended_ppc64le.yaml
schedule/yam/agama_lvm_encrypted_unattended_s390x.yaml

- SUT needs to shutdown at the end
- Verification run: https://openqa.suse.de/tests/17162194

Quick fix to get PUBLISH_HDD_1 work

---

schedule/yam/agama_unattended_patterns_ppc64le.yaml
schedule/yam/agama_unattended_patterns_s390x.yaml

- Related ticket: https://progress.opensuse.org/issues/179347
- Needles: N/A
s390x: https://openqa.suse.de/tests/17173391#
ppc64le: https://openqa.suse.de/tests/17173472#

Add schedule files for ha test

---

schedule/sles4sap/sap_deployment_automation_framework/sdaf_cleanup.yml
tests/sles4sap/redirection_tests/hana_cluster_check.pm

Refactor `test/sles4sap/redirection_tests/hana_cluster_check.pm`
- Related ticket: TEAM-10164 - [SDAF] Refactor `test/sles4sap/redirection_tests/hana_cluster_check.pm`
-- ensa2 sbd fencing (passed)
http://openqaworker15.qa.suse.cz/tests/318422#step/hana_cluster_check/3 (ers)
http://openqaworker15.qa.suse.cz/tests/318422#step/hana_cluster_check/57 (hana01)
http://openqaworker15.qa.suse.cz/tests/318422#step/hana_cluster_check/111 (hana02)

Refactor SDAF redirection_tests/hana_cluster_check

---

lib/autoyast.pm
lib/bootloader_pvm.pm
lib/bootloader_setup.pm
lib/version_utils.pm
schedule/ha/bv/agama_install_sles_ha.yaml
tests/installation/agama_reboot.pm
tests/installation/bootloader_s390.pm
tests/installation/bootloader_uefi.pm
tests/installation/ipxe_install.pm
tests/yam/agama/boot_agama.pm
variables.md

https://progress.opensuse.org/issues/179554
https://agama-project.github.io/docs/user/boot_options
[All arches](https://openqa.suse.de/tests/overview?version=16.0&build=rfan0327_new&distri=sle)

Change agama install boot_options

---

tests/console/start_systemd_testkit_offline.pm

- Related ticket: https://bugzilla.suse.com/show_bug.cgi?id=1231034

start_systemd_testkit_offline: Add header info

---

data/containers/autoyast_containers.xml.ep

Implement workaround from https://bugzilla.suse.com/show_bug.cgi?id=1239691#c34
- Verification run: https://openqa.suse.de/tests/17209375#

Append disable_ddw=1 as kernel parameter

---

tests/sles4sap/sys_param_check.pm

Add system param check for sles16
- Related ticket: https://progress.opensuse.org/issues/177234
- Verification run: https://openqa.suse.de/tests/17209172#
- Related PR: https://github.com/openSUSE/sys-param-check/pull/29

Add system param check for sles16

---

schedule/functional/toolchain_sle16.yaml

https://progress.opensuse.org/issues/177243
- Verification run: https://openqa.suse.de/tests/17208739

Remove kdump test from QE-Core for sle16

---

.github/workflows/ci.yml

goes together with https://github.com/os-autoinst/os-autoinst/pull/2690

Update Perl::Tidy to 20250311

---

tests/security/ima/ima_kernel_cmdline_hash.pm

Ticket: https://progress.opensuse.org/issues/179726

Revert change on ima_kernel_cmdline_hash.pm

---

data/agama_auto/sle_default.jsonnet
data/agama_auto/sle_default_ipmi_no_reg.jsonnet
data/agama_auto/sle_default_pvm.jsonnet
data/agama_auto/sle_default_pvm_no_reg.jsonnet
data/agama_auto/sle_default_s390x_kvm.jsonnet
data/agama_auto/sle_default_s390x_kvm_no_reg.jsonnet

https://github.com/agama-project/agama/blob/master/rust/agama-lib/src/scripts/model.rs#L79
VR: n/a 
Please see more information at https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/21616

Replace 'body' with 'content' for sle16 script

---

schedule/yam/agama_ppc64le.yaml

Failed job: https://openqa.suse.de/tests/17221605#step/validate_product/6
- Related ticket: quick PR
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/17224457#details

Replace validate_product with validate_base_product

---

lib/registration.pm
tests/installation/bootloader_s390.pm
tests/installation/bootloader_zkvm.pm

Problem introduced with: https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/21590
- Verification runs: https://openqa.suse.de/tests/overview?version=16.0&build=jknphy%2Fos-autoinst-distri-opensuse%23fix-registration&distri=sle

Fix condition for proxy registration

---

tests/console/check_os_release.pm

There are multiple changes that have taken place is `/etc/os-release` file
- Verification run: http://kepler.suse.cz/tests/24593#step/check_os_release/8

Values in os-release have changed

---

tests/hpc/ww4.pm

Warewulf4 has been upgraded to version 4.6.x in the SLE HPC module for
all supported SLE versions. This update requires adapting the test to
accommodate new command-line options related to the image parameter,
default netmask and the removal of defaults.conf.
- Related ticket: https://progress.opensuse.org/issues/179542
- Verification run: https://openqa.suse.de/tests/17229582#

hpc: Adapt warewulf4 test for version 4.6.x update

---

tests/console/check_os_release.pm

should have been part of 2480b61174

Leftover fix for os-release

---

tests/containers/isolation.pm

Limit isolation test on VMWare & HyperV to IPv4.
- Failing test: https://openqa.suse.de/tests/17222010#step/docker_isolation/74
- HyperV: https://openqa.suse.de/tests/17231223
- VMWare: https://openqa.suse.de/tests/17231224

containers: Fix isolation test on VMWare & HyperV

---

tests/containers/container_engine.pm

crun is expected only on SLEM 6.1+

containers: crun is expected only on SLEM 6.1+

---

data/yam/agama/auto/sles_addons_ssh_pub_key.jsonnet
data/yam/agama/auto/sles_addons_ssh_pub_key_ppc64le.jsonnet

- Related ticket: https://progress.opensuse.org/issues/179347
- Needles: N/A
https://openqa.suse.de/tests/17238755#  ppc64le
https://openqa.suse.de/tests/17238800#   s390x

Add profiles for addons on s390x/ppc64le

---

data/yam/agama/auto/autoyast_unsupported.xml
lib/Yam/Agama/Pom/AgamaUpAndRunningPage.pm
schedule/yam/agama_autoyast_unsupported.yaml
tests/yam/agama/agama.pm

- Related ticket: [poo#177132](https://progress.opensuse.org/issues/177132)
- Verification run: [sles_autoyast_unsupported](https://openqa.suse.de/tests/overview?build=issues-177132)
- Related [PR#92](https://github.com/jknphy/agama-integration-test-webpack/pull/92)

AutoYaST compatibility focus on unsupported sections

---

tests/containers/container_engine.pm

containers: docker always uses runc

---

lib/services/users.pm

- Related ticket: https://openqa.suse.de/tests/17248681#step/change_password/22
- Verification run: https://openqa.suse.de/tests/17248721#step/change_password/22

change_password: Drop unused likely outdated needle

---

data/agama_auto/sle_default_pvm.jsonnet

- Verification run: http://openqa.suse.de/tests/17248204

Erase the root disk before installation

---

tests/console/apache.pm

https://progress.opensuse.org/issues/179768
- Verification run: [30 iterations](http://openqa.suse.de/tests/overview?distri=sle&build=rfan0403&version=16.0)

Don't start apache too often

---

data/journal_check/bug_refs.json

More info https://bugzilla.suse.com/show_bug.cgi?id=1240139
- Verification run: http://kepler.suse.cz/tests/24612

Ignore dbus-broker-launch alerts

---

data/journal_check/bug_refs.json

Remove redundant broker message

---

schedule/security/agama.yaml
schedule/security/agama_remote_pvm.yaml
schedule/security/agama_remote_s390x.yaml

Add security agama hdd creation YAMLs that will shutdown in order to be able to upload assets
- Related ticket: https://progress.opensuse.org/issues/178795
- https://openqa.suse.de/tests/17261819
- https://openqa.suse.de/tests/17261820
- https://openqa.suse.de/tests/17252767
- https://openqa.suse.de/tests/17264365
- https://openqa.suse.de/tests/17264477

Poo178795 add agama security YAMLs for Full install

---

lib/publiccloud/azure.pm
lib/publiccloud/ec2.pm
lib/publiccloud/gce.pm
lib/publiccloud/noprovider.pm
lib/publiccloud/openstack.pm
lib/publiccloud/openstack_client.pm
tests/publiccloud/aws_cli.pm
tests/publiccloud/azure_cli.pm
tests/publiccloud/img_proof.pm
tests/publiccloud/run_ltp.pm
tests/publiccloud/upload_image.pm

Ticket: https://progress.opensuse.org/issues/179951
VR :  http://openqa.suse.de/tests/17264339
http://openqa.suse.de/tests/17264343

Disable cleanup for upload_img tests

---

data/security/openjdk/Shell.java
data/security/openjdk/Tcheck.java
lib/openjdktest.pm

- Related ticket: https://progress.opensuse.org/issues/179617
- Needles: n/a
- https://openqa.suse.de/tests/17264681
- https://openqa.suse.de/tests/17264683
- https://openqa.suse.de/tests/17264684

Move java source Tcheck from gitlab to OSADO data

---

data/autoyast_qam/12-common_base_installation.xml.ep

- Related ticket: https://progress.opensuse.org/issues/108836 https://openqa.suse.de/tests/17264682#step/network_hostname/1
- Verification run: https://openqa.suse.de/tests/17265753

Fix ay for test network_configuration

---

lib/thunderbird_common.pm

- Related ticket: https://progress.opensuse.org/issues/180011
https://openqa.suse.de/tests/17268086#step/thunderbird_imap/8
https://openqa.suse.de/tests/17267335#step/thunderbird_pop/7

Thunderbird handle new donate tab

---

schedule/qam/15-SP2/qam-textmode.yaml

ebfe9a55116d859a507bb274d338913eadc1b271 https://progress.opensuse.org/issues/108836

 Revert ebfe9a5 only on schedule/qam/15-SP2/qam-textmode.yaml 

---

schedule/virt_autotest/sle16_default_svirt.yaml

Please refer progress ticket:
https://progress.opensuse.org/issues/179801
Related MR: https://gitlab.suse.de/qa-testsuites/openqa-job-group-yaml/-/merge_requests/266
- Related ticket: https://progress.opensuse.org/issues/179801
- Needles: n/a
- Verification run: https://openqa.oqa.prg2.suse.org/tests/17240506#

Apply several changes for sle16 hyperv and vmware testing

---

tests/console/redis.pm

Related: https://progress.opensuse.org/issues/179867
VRs:
https://openqa.suse.de/tests/17249072# (x86 passed)
More vr see: https://openqa.suse.de/tests/overview?build=Amrysliu%2Fos-autoinst-distri-opensuse%2321679&distri=sle&version=15-SP7

[qe-core] Change redis to valkey-compat-redis

---

schedule/storage/nfstest.yaml
tests/kernel/before_nfs_test.pm
tests/kernel/nfs_barriers.pm
tests/kernel/nfstest.pm

Add nfstest testsuite

---

lib/Yam/Agama/Pom/RebootPage.pm
schedule/virt_autotest/sle16_default_svirt.yaml

Reverts os-autoinst/os-autoinst-distri-opensuse#21711

Revert "Support vmware tests on sles16"

---

tests/publiccloud/run_ltp.pm

https://progress.opensuse.org/issues/179311
VR: https://openqa.suse.de/tests/17281521

Record commit hash of kirk repo used in test

---

schedule/functional/message.yaml

- Related ticket: https://progress.opensuse.org/issues/179452 https://gitlab.suse.de/qa-maintenance/qam-openqa-yml/-/merge_requests/832

Exclude groupwise test in yaml schedule

---

data/wsl/Autounattend_UEFI.xml

Bump the openqa-agent version.
- Related ticket: https://progress.opensuse.org/issues/178837
- Verification run: https://openqa.opensuse.org/tests/4979309#details

Update openqa-agent to 1.2.0

---

tests/publiccloud/azure_aitl.pm

Publiccloud Azure module `azure_aitl.pm` revealed an issue in `aitl.py` script output, showing a message `no result returned` and no json data, that caused `decode_json` to fail/_croak_.
See failed test: https://openqa.suse.de/tests/17267316#step/azure_aitl/95
Fix: when above message detected the elaboration is skipped to next loop, until the effective test execution start. 
Also applied some parametrization to the aitl commands, to improve maintenance, version control and code readability.
- Related ticket: https://progress.opensuse.org/issues/179623
- Needles: no.
- Verification run: https://openqa.suse.de/tests/17289701
Note: the test fail because the tested Azure image is not uploaded yet in cloud.

Azure AITL tests no-result fix

---

lib/containers/bats.pm
tests/containers/bats/README.md

Allow disabling SELinux on BATS tests.  Also document workflow on how to debug SELinux problems.
- Verification run: https://openqa.opensuse.org/tests/4982737

containers: Allow disabling SELinux on BATS tests

---

tests/console/ansible.pm

This reverts commit eb6231e60bcf0a5c908715e378231b60da0dc68f.
- Related ticket: https://progress.opensuse.org/issues/180293
https://openqa.suse.de/tests/17297639 15-SP5
https://openqa.suse.de/tests/17297640 15-SP4
https://openqa.opensuse.org/tests/overview?distri=microos&version=Tumbleweed&build=jpupava_ansible o3

Revert "Re-enable ansible-test for SLE"

---

data/yam/agama/auto/template.libsonnet

##
- Related ticket: https://progress.opensuse.org/issues/179287
- Needles: N/A
- [VR](https://openqa.suse.de/tests/overview?version=16.0&build=hjluo_packages&distri=sle)
##

Add individual package to unattended installation

---

data/sles4sap/qe_sap_deployment/qesap_gcp_peering.yaml
tests/sles4sap/qesapdeployment/configure.pm
tests/sles4sap/qesapdeployment/test_mirror.pm

Add GCP support for network peering done by qe-sap-deployment also for GCP to qesap regression test.
Verification is done also using  https://github.com/SUSE/qe-sap-deployment/pull/345
-   http://openqaworker15.qa.suse.cz/tests/320576 no peering
-   http://openqaworker15.qa.suse.cz/tests/320574 peering
- http://openqaworker15.qa.suse.cz/tests/320591 peering

Add IBSm peering test to GCP

---

data/journal_check/bug_refs.json

https://bugzilla.suse.com/show_bug.cgi\?id\=1229228
- Verification run: http://kepler.suse.cz/tests/24635#step/journal_check/8

Remove fixed and verified agetty bug

---

tests/x11/inkscape.pm

VR: http://10.149.209.202//tests/146#step/inkscape/20
Needles: https://github.com/os-autoinst/os-autoinst-needles-opensuse/pull/834

Add workaround in inkscape for boo1241066

---

schedule/qam/common/mau-extratests2.yaml

- Related ticket: https://gitlab.suse.de/qa-maintenance/qam-openqa-yml/-/merge_requests/836 https://progress.opensuse.org/issues/179452
- Verification run: https://openqa.suse.de/tests/overview?distri=sle&version=12-SP5&build=jpupava_systemtap

systemtap: Update yaml schedule on 12-SP5

---

lib/containers/bats.pm
tests/containers/bats/README.md
tests/containers/bats/podman.pm

containers/bats: Minor enhancements

---

data/yam/agama/auto/autoinst_aarch64.jsonnet
data/yam/agama/auto/autoinst_x86_64.jsonnet

- Related ticket: https://progress.opensuse.org/issues/176832
- Needles: N/A
https://openqa.suse.de/tests/17306792#details
https://openqa.suse.de/tests/17306814#details

Add profiles for oemdrv test

---

tests/publiccloud/check_services.pm

- Related ticket: https://bugzilla.suse.com/show_bug.cgi?id=1240385
- Verification run: https://pdostal-server.suse.cz/tests/8771#

Fix PC Waagent on 12-SP5

---

tests/containers/bats/README.md

containers: Simplify BATS README

---

data/security/autoyast/textmode.xml.ep

VRs: https://openqa.suse.de/tests/overview?distri=sle&version=15-SP7&build=85.1&groupid=431

Remove non existent option

---

tests/sles4sap/qesapdeployment/deploy.pm

Add a variable to be able to control the value for the --parallel argument of the terraform subcommand of the qesap.py script. If not provided, no '--parallel' is added to the command line. Value has to be an integer greater or equal to 1.
- Related ticket: https://jira.suse.com/browse/TEAM-10214
sle-15-SP6-Qesap-Azure-Payg-x86_64-BuildLATEST_AZURE_SLE15_6_PAYG-qesap_azure_saptune_test_msi
- http://openqaworker15.qa.suse.cz/tests/321212  http://openqaworker15.qa.suse.cz/tests/321219 NO PARALLEL (default to 10 within Terraform) deploy testmodule takes 37m 14s 
- http://openqaworker15.qa.suse.cz/tests/321220 QESAPDEPLOY_TERRAFORM_PARALLEL=3  deploy testmodule takes 46m 23s
- http://openqaworker15.qa.suse.cz/tests/321221 QESAPDEPLOY_TERRAFORM_PARALLEL=1  deploy testmodule takes 47m 23s 
- …

Add variable to control the Terraform parallelism

---

data/autoyast_qam/15_installtest.xml.ep
lib/registration.pm

Related: https://progress.opensuse.org/issues/180611
VR:
For 15-SP6_installation.xml.ep: https://openqa.suse.de/tests/17344438#  (Passed)
For 15-common_base_installation.xml.ep: https://openqa.suse.de/tests/17344440#  (Passed)
For 15-SP6_installtest.xml.ep: https://openqa.suse.de/tests/17344456# (Passed)
For test not use autoyast: https://openqa.suse.de/tests/17349630#step/scc_registration/178  (passed)

Add sle-module-systems-management for 15-SP6

---

tests/ha/ha_cluster_init.pm
tests/ha/setup_hosts_and_luns.pm

- Related ticket: https://jira.suse.com/browse/TEAM-10227
- Needles: n/a
- https://openqa.suse.de/tests/17345145
- https://openqa.suse.de/tests/17345146
- https://openqa.suse.de/tests/17345147  
VR expected failure due to [TEAM-10163](https://jira.suse.com/browse/TEAM-10163) (HA extension not enabled)

Install nfs-client when not installed by default (e.g. SLES16)

---

lib/registration.pm
schedule/qam/common/mau-extratests-desktop.yaml

Without SCC registration https://progress.opensuse.org/issues/131498#note-5
- Related ticket: https://gitlab.suse.de/qa-maintenance/qam-openqa-yml/-/merge_requests/838 https://progress.opensuse.org/issues/179452
https://openqa.suse.de/tests/17343972#step/cifs/1 mau-filesystem
https://openqa.suse.de/tests/17343968 mau-extratests1
https://openqa.suse.de/tests/17343971#step/pciutils/1 mau-extratests2
https://openqa.suse.de/tests/overview?build=jpupava_em&distri=sle

Skip add SCC product on TD

---

schedule/sles4sap/minimalvm/patterns.yaml

VR:
- [kvm image](https://openqa.suse.de/tests/17344707)
- [Cloud image](https://openqa.suse.de/tests/17345303)

Fix schedule for SAP minimal-VM images

---

tests/nfs/install.pm

- Related ticket: https://progress.opensuse.org/issues/178765
- Needles: NONE
TW: https://openqa.opensuse.org/tests/4995167#step/install/17
SLE16:  https://openqa.suse.de/tests/17350551#step/install/17

pynfs: Make xdrlib installation Python version-independent

---

tests/containers/bats/README.md
tests/containers/bats/logo.svg

Add links to BATS openQA jobs
VR: https://github.com/ricardobranco777/os-autoinst-distri-opensuse/blob/bats_jobs/tests/containers/bats/README.md

containers: Add links to BATS openQA jobs

---

schedule/yam/agama_extensions_and_patterns.yaml
schedule/yam/agama_extensions_and_patterns_s390x.yaml

- Related ticket: https://progress.opensuse.org/issues/180134
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/17358744#

Add yaml schedule for ha registration of interactive test

---

lib/registration.pm

Need register packagehub
- Related ticket: https://progress.opensuse.org/issues/181016
- Verification run: https://openqa.suse.de/tests/17358802

Skip add SCC product on TD for sle15sp4

---

data/network_bonding/kea-dhcp4.conf
schedule/functional/kea.yaml
tests/network/kea_client.pm
tests/network/kea_server.pm

- Related ticket: https://progress.opensuse.org/issues/176865
- Schedule: 
- SLE https://gitlab.suse.de/qe-core/qa-sle-functional-userspace/-/merge_requests/266
- TW: https://github.com/os-autoinst/opensuse-jobgroups/pull/643 
- SLE https://openqa.suse.de/tests/overview?build=cedvid%2Fos-autoinst-distri-opensuse%2321782
- TW https://openqa.opensuse.org/tests/overview?build=cedvid%2Fos-autoinst-distri-opensuse%2321782

Add kea test

---

data/sles4sap/qe_sap_deployment/mr_test_azure.yaml
data/sles4sap/qe_sap_deployment/sles4sap_azure_generic_maintenance.yaml
lib/sles4sap_publiccloud.pm
tests/sles4sap/publiccloud/network_peering.pm

This mr adds the osado code needed for terraform peering in azure.
To work it also needs 
https://gitlab.suse.de/qa-maintenance/qam-openqa-yml/-/merge_requests/841
and
https://gitlab.suse.de/qa-css/openqa_ha_sap/-/merge_requests/968
- Related ticket: https://jira.suse.com/browse/TEAM-10216
8 concurrent runs, all PASS:
https://openqa.suse.de/tests/17184362
https://openqa.suse.de/tests/17184363#
https://openqa.suse.de/tests/17184364#
https://openqa.suse.de/tests/17184365#
https://openqa.suse.de/tests/17184366#
https://openqa.suse.de/tests/17184367#
https://openqa.suse.de/tests/17184368#
https://openqa.suse.de/tests/17184369#
2 newer tests, one saptune, one hanasr:
https://openqa.suse.de/tests/17362092
https://openqa.suse.de/tests/17362108

Enable terraform peering for Azure

---

schedule/qam/common/stack_tests_php.yaml

- Related ticket: https://progress.opensuse.org/issues/180260

Add missing 15SP7 maintenance test

---

data/yam/agama/auto/lib/storage.libsonnet
data/yam/agama/auto/template.libsonnet
schedule/yam/whole_disk_and_boot_unattended.yaml
test_data/yam/whole_disk_and_boot_unattended.yaml
tests/console/validate_blockdevices.pm

##
- https://progress.opensuse.org/issues/178723
- Needles: 
- N/A 
- [**VR**](https://openqa.suse.de/tests/overview?distri=sle&build=hjluo_format_home&version=16.0)
##

Format directly home and configure boot partition

---

tests/jeos/firstrun.pm

If the group field is empty, non-root user should be added to wheel group.
- Related ticket: https://bugzilla.suse.com/show_bug.cgi?id=1241215
- Needles: https://github.com/os-autoinst/os-autoinst-needles-opensuse/pull/835
- Verification run: http://kepler.suse.cz/tests/24657#step/firstrun/64

Specify a group for an user

---

tests/sles4sap/publiccloud/network_peering.pm

Fixes small typo
- Related ticket: -
- Verification run: -

Fix small typo in network_peering

---

tests/kernel/nfs_client.pm
tests/kernel/nfs_server.pm

- Related ticket: https://progress.opensuse.org/issues/173983
- Needles: not needed
-- passing runs:
https://openqa.suse.de/tests/17362943
https://openqa.suse.de/tests/17362942
https://openqa.suse.de/tests/17362941
-- failing on purpose runs (done with small added line to alter the file content so to make md5 checksum fail):
https://openqa.suse.de/tests/17363043
https://openqa.suse.de/tests/17363044
https://openqa.suse.de/tests/17363045
-- passing again - after removing these lines from nfs_server.pm (so the code is exactly as in the last revision of this PR): 
```
assert_script_run("echo '1' >> $file");
assert_script_run("md5sum $file > new_md5sum.txt");
```
https://openqa.suse.de/tests/17363318
https://openqa.suse.de/tests/17363319 …

NFS mm tests extensions

---

lib/containers/bats.pm
tests/containers/bats/aardvark.pm
tests/containers/bats/buildah.pm
tests/containers/bats/netavark.pm
tests/containers/bats/podman.pm
tests/containers/bats/runc.pm
tests/containers/bats/skopeo.pm
variables.md

Refactor BATS tests to remove duplicate code
- aardvark: https://openqa.opensuse.org/tests/5011656
- buildah: https://openqa.opensuse.org/tests/5011584
- netavark: https://openqa.opensuse.org/tests/5011585
- podman: https://openqa.opensuse.org/tests/5011657
- runc: https://openqa.opensuse.org/tests/5011588
- skopeo: https://openqa.opensuse.org/tests/5011633

Refactor BATS tests

---

tests/containers/bats/podman.pm

containers: Remove dead code

---

lib/publiccloud/provider.pm

fixing regression caused by https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/21709
VR: https://openqa.suse.de/tests/17389582#
http://openqa.suse.de/tests/17389677
http://openqa.suse.de/tests/17389678
http://openqa.suse.de/tests/17389679

Exclude availability zone for Azure and AWS

---

lib/serial_terminal.pm

Reverts os-autoinst/os-autoinst-distri-opensuse#21832

Revert "Set PAGER=more for serial console"

---

schedule/qam/15-SP4/mau-extratests-phub.yaml
schedule/qam/15-SP5/mau-extratests-phub.yaml
schedule/qam/15-SP6/mau-extratests-phub.yaml
schedule/qam/15-SP7/mau-extratests-phub.yaml
schedule/qam/common/mau-extratests1.yaml
tests/console/ansible.pm

https://progress.opensuse.org/issues/181136
[Sle15sp3-sp7](http://openqa.suse.de/tests/overview?&build=rfan0424&distri=sle)
[Tumbleweed](https://openqa.opensuse.org/tests/5015585#)
**All VRs are without PackageHub activated before anisble tests**
**It is expected on sle15sp7 that the case failed, the package will be synced to SP7 later**

Update packages testing for ansible

---

tests/console/perf.pm

Progress ticket: https://progress.opensuse.org/issues/181328
VR https://openqa.opensuse.org/tests/5016388

Avoid using pager in perf test

---

tests/qam-updinstall/update_install.pm

- Related ticket: https://suse.slack.com/archives/C02CLB8TZP1/p1745395955069139
- Verification run: https://openqa.suse.de/tests/overview?build=%3A38344%3Anvidia-open-driver-G06-signed&groupid=546

update_install: Use solver for conflict patch too

---

data/agama_auto/sle_default.jsonnet
data/agama_auto/sle_default_pvm.jsonnet
data/agama_auto/sle_default_s390x_kvm.jsonnet
schedule/functional/sle16/agama-create-hdd-textmode.yaml
schedule/functional/sle16/agama-create-hdd-textmode_pvm.yaml

https://progress.opensuse.org/issues/180986
VRs:
x86: https://openqa.suse.de/tests/17435549  (Passed)
aarch64: https://openqa.suse.de/tests/17435477 (Passed)
ppc64: https://openqa.suse.de/tests/17435479  (Passed)
s390x: https://openqa.suse.de/tests/17452952 (Passed)

Schedule gurb_test and change grub timeout on sle16

---

schedule/yam/agama_tpm_fde_unattended.yaml
tests/yam/validate/validate_tpm_fde.pm

- Related ticket: [poo#179410](https://progress.opensuse.org/issues/179410)
- Verification run: [sles_tpm_fde__TEST__](https://openqa.suse.de/tests/overview?build=issues-179410)

New schedule for lvm TPM FDE

---

tests/publiccloud/azure_aitl.pm
tests/publiccloud/upload_image.pm

Fixing missed places in https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/21749

Fix renaming of _cleanup method to finalize

---

lib/guest_installation_and_configuration_base.pm

* **br0** setup on SLES 16.0 host needs ```autoconnect-ports``` setting in ```connection``` section in subroutine ```write_guest_network_bridge_device_nmconnection```.
* **SLES 16.0** guest installation from Agama ISO may have two ip addresses assigned to one interface (valid scenario), so getting only the first one to be used for following interaction is enough in subroutine ```get_guest_ipaddr```.
* **SLES 16.0** guest installation from Agama ISO may change its ip address after reboot, so always detecting the latest ip address for it after reboot in subroutine ```get_guest_ipaddr```.
* **Differentiate** hostnames obtained from ssh via ip address or guest name by using variables ```$_guest_transient_hostname_via_ipaddr``` and ```$_guest_transient_hostname_via_name``` in subroutine …

Add support for SLES 16.0 guest installation with br0

---

lib/containers/bats.pm

Add zypper command to list
- Verification run: https://openqa.opensuse.org/tests/5026421/logfile?filename=podman-commands.txt

containers/bats: Add zypper command to list

---

lib/sles4sap/sap_deployment_automation_framework/configure_sap_systems_tfvars.pm
lib/sles4sap/sap_deployment_automation_framework/deployment_connector.pm
t/34_sdaf_configure_sap_systems_tfvars.t
tests/sles4sap/sap_deployment_automation_framework/deploy_sap_systems.pm

Fix SDAF OSD 15SP7 deploy_HanaSR failure: test code needs to be synced with OW15
TEAM-10312 - [SDAF][OSD][15 SP7] SDAF_PRD_deploy_HanaSR failed on connect_to_deployer after the merge of PR#21770
Related MR: https://gitlab.suse.de/qac/qac-openqa-yaml/-/merge_requests/2201
- Related ticket: https://jira.suse.com/browse/TEAM-10312
**OSD**: http://openqa.suse.de/tests/17458995#step/execute_playbooks/78
(Failed but can be tracked by know issues: 
-- https://github.com/sdaf-suse/sap-automation/issues/3
-- https://github.com/sdaf-suse/sap-automation/issues/4
)
**OW15**: https://openqaworker15.qa.suse.cz/tests/322540#dependencies (passed)

Fix SDAF OSD 15SP7 deploy_HanaSR failure

---

lib/containers/bats.pm

containers/bats: Ignore error on rm

---

lib/containers/bats.pm

containers/bats: Add missing env command

---

lib/hacluster.pm
lib/sles4sap/sap_host_agent.pm
lib/sles4sap/sapcontrol.pm
schedule/sles4sap/sap_deployment_automation_framework/ensa2_scenarios.yml
t/11_hacluster.t
t/30_sapcontrol.t
t/31_sap_host_agent.t
tests/sles4sap/redirection_tests/ensa2_kill_sapinstance_ers.pm

This PR adds SDAF test scenario 'Kill SAP instance ERS process'.
- Related ticket: https://jira.suse.com/browse/TEAM-10249
- Verification run: https://openqaworker15.qa.suse.cz/tests/322559#step/ensa2_kill_sapinstance_ers/162
Additional VR which includes line https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/21888/files#diff-189465ebf4f0179a80f4d8e4394d2f6d303d2b94c1239ee0a1d5dc303d4b536eR74
https://openqaworker15.qa.suse.cz/tests/322799#dependencies

ENSA2 kill sapinstance test

---

lib/containers/bats.pm
tests/containers/bats/README.md

Drop ugly code needed for 15-SP3 where we only cover runc & skopeo.
Related MR: https://gitlab.suse.de/qac/qac-openqa-yaml/-/merge_requests/2214

containers/bats: Drop code for 15-SP3

---

lib/sles4sap/sapcontrol.pm

retry GetSystemInstanceList to give cluster more stabilization time
- Related ticket: https://jira.suse.com/browse/TEAM-10316
- Needles: n/a
12SP5:
- https://openqa.suse.de/tests/17500632
- https://openqa.suse.de/tests/17500633
- https://openqa.suse.de/tests/17500634
- https://openqa.suse.de/tests/17500635
- https://openqa.suse.de/tests/17500636
- https://openqa.suse.de/tests/17500637
- https://openqa.suse.de/tests/17500638
- https://openqa.suse.de/tests/17500639
- https://openqa.suse.de/tests/17500640
- https://openqa.suse.de/tests/17500641
- https://openqa.suse.de/tests/17500642
- https://openqa.suse.de/tests/17500643
- https://openqa.suse.de/tests/17500644
- https://openqa.suse.de/tests/17500645
- https://openqa.suse.de/tests/17500646
- …

Use retry mechanism for GetSystemInstanceList

---

data/containers/bats_skip_notok.py

Fix corner case with `bats_skip_notok.py` script that makes the BATS_SKIP mechanism fail for some individual tests that fail in mysterious ways.
The script waits for a line like `#  in test file test/system/030-run.bats, line 80)` to extract the test name `030-run`
but in [some cases](https://openqa.opensuse.org/tests/5028426/file/podman-bats-user-remote.tap) this line it's not present. This may be a bug in bats itself.  We can instead extract the test number from this line:
```
not ok 295 [130] podman kill - print IDs or raw input in 894ms
```
- Failing test: https://openqa.opensuse.org/tests/5028426
- Verification run: https://openqa.opensuse.org/tests/5029093 (`130-kill` is skipped)

containers/bats: Fix bats_skip_notok for corner case

---

schedule/sles4sap/sles4sap_agama_auto_install_pvm_test.yaml
tests/sles4sap/netweaver_filesystems.pm
tests/sles4sap/patterns.pm

Update powerpc YAML schedule and compatible issues for SLE16: 
1. ha_sles pattern name
2. nfs client service name 
- Related ticket: https://jira.suse.com/browse/TEAM-10282
- Needles: N/A
-  https://openqa.suse.de/tests/17503174 
- https://openqa.suse.de/tests/17503175
Test cases ran into failure because known issue bsc#1239107:
https://openqa.suse.de/tests/17503174#step/iscsi_client_setup/108

Enable NW cluster testing for sle16

---

data/yam/agama/auto/lib/scripts_post_partitioning.libsonnet
data/yam/agama/auto/sles_packages_ppc64le.jsonnet
data/yam/agama/auto/sles_packages_s390x.jsonnet
data/yam/agama/auto/template.libsonnet
schedule/yam/agama_extended_unattended.yaml
schedule/yam/agama_extended_unattended_ppc64le.yaml
schedule/yam/agama_extended_unattended_s390x.yaml
tests/yam/validate/validate_post_partitioning.pm

- Related ticket: https://progress.opensuse.org/issues/179011
- [VRs](https://openqa.suse.de/tests/overview?build=rakoenig%2Fos-autoinst-distri-opensuse%23poo179011&distri=sle&version=16.0)

Test Agama post-partitioning scripts

---

schedule/yam/agama_headless.yaml
schedule/yam/agama_headless_pvm.yaml
schedule/yam/agama_headless_s390x.yaml
tests/yam/agama/agama.pm
tests/yam/agama/boot_agama.pm
tests/yam/agama/validate_headless.pm

##
- Related ticket:  
- https://progress.opensuse.org/issues/180914
- Needles: N/A
-  [headless_install in dev](https://openqa.suse.de/tests/overview?version=agama-10.0&build=hjluo_headless_install&distri=sle)
- [headless_install in prod 78.2](https://openqa.suse.de/tests/overview?version=16.0&distri=sle&build=hjluo_headless_install)
##

Agama headless installation

---

lib/containers/urls.pm

Several containers are by now in ltss. Also add sp7 container

Update container registry links

---

tests/kernel/blktests.pm

- Related ticket: https://progress.opensuse.org/issues/181658
- Verification run: https://openqa.suse.de/tests/17529246

Storage: Collect nodev results for dm tests

---

tests/qam-updinstall/update_install.pm

- Related ticket: https://suse.slack.com/archives/C02D16TCP99/p1713786052984039
- Verification run: https://openqa.suse.de/tests/17526441#step/update_install/292

update_install: Softfail on expected update-test-trivial failure

---

tests/kernel/blktests.pm

- Related ticket: https://progress.opensuse.org/issues/181658
- Verification run: https://openqa.suse.de/tests/17539548

Storage: enable loop and throtl tests for SLE16

---

schedule/yam/agama_gnome.yaml
schedule/yam/agama_gnome_s390x.yaml
schedule/yam/agama_gnome_unattended.yaml

##
- https://progress.opensuse.org/issues/180245
- Needles: 
- sles16_desktop-gnome-20250425
- [**sles16 gnome installation**](https://openqa.suse.de/tests/overview?version=16.0&distri=sle&build=hjluo_install_gnome)
##

Create sles_gnome and sles_gnome_unattended installations

---

data/journal_check/bug_refs.json

VR: https://openqa.suse.de/tests/17564583#

Whitelist bsc#1242209

---

lib/containers/bats.pm
tests/containers/bats/README.md

Improve BATS README
- Verification: https://github.com/ricardobranco777/os-autoinst-distri-opensuse/blob/bats_readme/tests/containers/bats/README.md

Improve BATS README

---

tests/wicked/before_test.pm

The wicked testsuite expect the firewall to be install, but disabled by default. This is how we get it for all flavors.
- Related ticket: https://bugzilla.suse.com/show_bug.cgi?id=1241913
- Verification run: https://openqa.suse.de/tests/17565775

wicked: install but disable firewall by default

---

tests/containers/privileged_mode.pm

Remove incomplete & unstable dind/pinp test.  A proper test should be done in its own module that runs containers tests inside docker/podman instead of just installing the package.
- Failing test: https://openqa.suse.de/tests/17582869#step/podman_privileged_mode/93
- Verification run: https://openqa.suse.de/tests/17587388

containers: Remove incomplete & unstable dind/pinp test

---

schedule/kernel/agama_install_ltp_pvm.yaml

Install both the system and LTP in a single job on PowerVM.
https://openqa.suse.de/tests/17586707

ltp: Add combined system and LTP installation on PowerVM

---

lib/containers/bats.pm
tests/containers/bats/README.md

- Download `.patch` instead of `.diff`
- Improve BATS README
Verification run: https://openqa.opensuse.org/tests/5044031

Minor BATS enhancements

---

data/agama_auto/leap_gnome.jsonnet
schedule/functional/leap16/agama_create_hdd_gnome_leap.yaml

To be used in create_hdd jobs for leap

Add leap gnome jsonnet

---

tests/qemu/kvm.pm
tests/qemu/qemu.pm

https://bugzilla.suse.com/show_bug.cgi?id=1242434
https://progress.opensuse.org/issues/181898
- Verification run: https://openqa.suse.de/tests/17601627

Fix the ram size for qemu test on s390x

---

schedule/yast/sle/flows/default_aarch64.yaml
schedule/yast/sle/flows/default_aarch64_flavor_full.yaml
schedule/yast/sle/flows/default_ipmi.yaml
schedule/yast/sle/flows/default_ppc64le.yaml
schedule/yast/sle/flows/default_s390x_kvm.yaml
schedule/yast/sle/flows/default_s390x_kvm_flavor_full.yaml
schedule/yast/sle/flows/default_s390x_kvm_textmode.yaml
schedule/yast/sle/flows/default_s390x_svirt.yaml
schedule/yast/sle/flows/default_s390x_zvm.yaml
schedule/yast/sle/flows/default_s390x_zvm_textmode.yaml
schedule/yast/sle/flows/default_svirt-hyperv.yaml
schedule/yast/sle/flows/default_svirt-xen-hvm.yaml

- Related ticket: https://progress.opensuse.org/issues/181871

Remove access_beta_distribution from YaST schedules

---

schedule/yast/sle/flows/default_svirt-xen-pv.yaml
schedule/yast/sle/flows/default_x86_64.yaml
schedule/yast/sle/flows/default_x86_64_flavor_full.yaml

Related ticket:  https://progress.opensuse.org/issues/181871

Remove beta handling from default_x86_64.yaml

---

schedule/yam/test_cases/installer_extended.yaml

Related ticket: https://progress.opensuse.org/issues/181871

Remove beta tests from installer_extended schedule

---

tests/x11/doom.py

openqa: Clone https://openqa.opensuse.org/tests/5046391 EXCLUDE_MODULES=chrome,multi_users_dm,wine,gnucash

doom: Fix cleanup by closing window

---

.github/workflows/ci.yml

~Lets see if this works~ Works ™️ 
Perhaps a more elegant solution could be trying out Virtualenv or pipx but that's for another pr

Fix Ci by pinning jsonnet version to latest working one

---

lib/oscap_tests.pm

- Related ticket: https://progress.opensuse.org/issues/181982
- Verification run: https://openqa.suse.de/tests/17621731

Add systems management module on 15-SP7

---

tests/ha/priority_fencing_delay.pm

VR: https://openqa.suse.de/tests/17609994

HA: Install iptables for SLE16 in priority_fencing_delay.pm

---

schedule/install/agama_install.yaml

VR: https://openqa.opensuse.org/tests/5047569

Schedule shutdown module in gnome-agama

---

tests/security/krb5/krb5_crypt_ssh_client.pm
tests/security/krb5/krb5_crypt_ssh_server.pm

Ticket https://progress.opensuse.org/issues/182000

Use correct ssh config files on SLE16

---

lib/Yam/Agama/agama_base.pm
products/opensuse/main.pm
tests/yam/agama/agama_auto.pm

also: https://github.com/os-autoinst/opensuse-jobgroups/pull/661
- o3 https://openqa.opensuse.org/tests/5049413

Leap 16 create_hdd_* jobs enablement 

---

schedule/security/create_hdd_cc_libyui/aarch64/cc_dev.yaml
schedule/security/create_hdd_cc_libyui/aarch64/cc_maint_15sp6.yaml
schedule/security/create_hdd_cc_libyui/s390x/cc_dev.yaml
schedule/security/create_hdd_cc_libyui/s390x/cc_maint_fde.yaml
schedule/security/create_hdd_cc_libyui/x86_64/cc_dev.yaml
schedule/security/create_hdd_cc_libyui/x86_64/cc_maint.yaml
tests/security/installation/handle_beta_status.pm

Ticket: https://progress.opensuse.org/issues/182099
VRs: [15sp7-dev](https://openqa.suse.de/tests/overview?distri=sle&version=15-SP7&build=90.1&groupid=431), [15sp7-maint](https://openqa.suse.de/tests/overview?distri=sle&version=15-SP7&build=20250508-1&groupid=431), [15sp6-maint](https://openqa.suse.de/tests/overview?distri=sle&version=15-SP6&build=20250508-1&groupid=431)

Automatically handle beta status on CC installation

---

tests/security/swtpm/swtpm_verify.pm

Ticket https://progress.opensuse.org/issues/182084
VR: https://openqa.suse.de/tests/17635838

Disable swtpm_verify on 15-SP6

---

data/agama_auto/sle_default_gnome.jsonnet

https://bugzilla.suse.com/show_bug.cgi?id=1242721
https://progress.opensuse.org/issues/181478
- Verification run: [x86_64&aarch64](http://openqa.suse.de/tests/overview?build=rfan0513&distri=sle&version=16.0)

Remove workaround for bsc#1242721

---

schedule/sles4sap/minimalvm/create_hdd.yaml
schedule/sles4sap/minimalvm/patterns.yaml

- Related ticket: https://jira.suse.com/browse/TEAM-10236
- Needles: no
Minimal-VM-for-kvm-and-xen-SAP:
- https://openqa.suse.de/tests/17674158
- https://openqa.suse.de/tests/17674159
- https://openqa.suse.de/tests/17674160
- https://openqa.suse.de/tests/17674161
- https://openqa.suse.de/tests/17674162
- https://openqa.suse.de/tests/17674163
- https://openqa.suse.de/tests/17674164
Minimal-VM-Cloud-SAP:
- https://openqa.suse.de/tests/17674273
- https://openqa.suse.de/tests/17674274
- https://openqa.suse.de/tests/17674275
- https://openqa.suse.de/tests/17674276
- https://openqa.suse.de/tests/17674277
- https://openqa.suse.de/tests/17674287
as stated in the ticket AC, test failures will be addressed in a later step

Update schedule to reuse HDD also on patterns

---

lib/main_common.pm
lib/main_ltp.pm

- Related ticket: https://progress.opensuse.org/issues/182276
- Verification run: https://openqa.opensuse.org/tests/5056821
- Schedule: https://github.com/os-autoinst/opensuse-jobgroups/pull/664

kernel: Schedule kdump from load_kernel_tests

---

data/yam/agama/auto/lib/base.libsonnet
lib/bootloader_setup.pm

- Related ticket: [poo#177477](https://progress.opensuse.org/issues/177477)
- Verification run: [*_unattended__TEST__](https://openqa.suse.de/tests/overview?build=issues-177477)

Using jsonnet profiles in ppc64le/s390x

---

tests/transactional/install_updates.pm
variables.md

[up](https://openqa.suse.de/tests/17687009#step/install_updates/34)
[patch](https://openqa.suse.de/tests/17688132#step/install_updates/162)

SLMicro: Use zypper up to install updates

---

tests/kernel/run_kselftests.pm

Using TARGETS we compile/install tests only for the specified subgroup.
- Verification run: https://openqa.suse.de/tests/17698864

kernel/run_kselftests: use TARGETS for installing specific suite

---

tests/openqa/osautoinst/test_running.pm

https://progress.opensuse.org/issues/182333
- Verification run: https://openqa.opensuse.org/tests/5060606

Wait longer to make sure openQA job is running

---

tests/sles4sap/publiccloud/cluster_add_repos.pm

Avoids risk of zypper lock; this also has the benefit to cut some time from the test module execution.
- Related ticket: https://jira.suse.com/browse/TEAM-10317
- Needles: no
- https://openqa.suse.de/tests/17698447#step/cluster_add_repos/1
- https://openqa.suse.de/tests/17698465#step/cluster_add_repos/1
- https://openqa.suse.de/tests/17700356#step/cluster_add_repos/1
(subsequent test module failure is unrelated)

Create repository files on target

---

tests/sles4sap/ase_install.pm
tests/sles4sap/netweaver_install.pm

SLE 16.0 does not ship with a version of `libnsl.so.1` (deprecated in 15), but several third party products cannot be installed if the library is missing. As a workaround SLE 16.0 does ship with a `libnsl-stub1`. More details at:
https://susedoc.github.io/release-notes/slesap-16.0/html/release-notes/index.html#jsc-DOCTEAM-1849
SAP's ASE and NetWeaver require `libnsl`, so this commit modifies the installation test modules to also install `libnsl-stub1`. Workaround code for https://bugzilla.suse.com/show_bug.cgi?id=1236235 has been removed as the installation of `libnsl-stub1` makes this not necessary.
Also included in the commit is the removal of `saptune solution apply SAP-ASE` on ASE installation module, as the solution has been removed from `saptune` in 16. Recommendation is to install …

Install libnsl-stub1 for ASE and NetWeaver installation

---

data/kiwi/appliance_sle15sp7.kiwi
tests/kiwi_images_test/kiwi_build_image.pm

https://progress.opensuse.org/issues/181706
- Verification run: https://openqa.suse.de/tests/17711159

Add required addons for sle15sp7 kiwi test

---

schedule/security/create_hdd_cc_libyui/aarch64/cc_dev.yaml
schedule/security/create_hdd_cc_libyui/s390x/cc_dev.yaml
schedule/security/create_hdd_cc_libyui/x86_64/cc_dev.yaml
tests/security/installation/add_on_selection.pm
tests/security/installation/module_selection.pm
tests/security/installation/registration.pm

Ticket: https://progress.opensuse.org/issues/182129
VRs: https://openqa.suse.de/tests/overview?distri=sle&version=15-SP7&build=91.1&groupid=431

Offline installation also on Full flavor

---

lib/publiccloud/provider.pm

current regex does not cover all kind of errors which google may throw . We need to extend the list

Extend regex to cover more error types

---

tests/security/swtpm/swtpm_env_setup.pm
tests/security/tpm2/keylime/keylime.pm

Adjust TPM tests for SLE16
- Related ticket: https://progress.opensuse.org/issues/176694
- https://openqa.suse.de/tests/17712396 
- https://openqa.suse.de/tests/17712397
- https://openqa.suse.de/tests/17712399
- https://openqa.suse.de/tests/17712068
- https://openqa.suse.de/tests/17700504
- SP7:
- https://openqa.suse.de/tests/17712221
- https://openqa.suse.de/tests/17712223

TPM tests adjust for SLE16

---

tests/fips/openssh/openssh_fips.pm

Ticket: https://progress.opensuse.org/issues/179978
VR: [16.0](https://openqa.suse.de/tests/17731787), [15.7](https://openqa.suse.de/tests/17731781)

Update SSH message based on SLE version

---

schedule/qam/common/mau-extratests1.yaml

- Related ticket: https://bugzilla.suse.com/show_bug.cgi?id=1243259
https://openqa.suse.de/tests/17733430
https://openqa.suse.de/tests/17733454
https://openqa.suse.de/tests/17733459

Exclude journal_remote on 15-SP7 until it's added

---

tests/security/cc/ip_eb_tables.pm

Ticket: https://progress.opensuse.org/issues/182576
VR: https://openqa.suse.de/tests/17750022#step/ip_eb_tables/1

Softfailed ip_eb_tables

---

tests/publiccloud/img_proof.pm

1. Remove duplicate upload of cloudregister which we doing anyway in basetest
2. limit SCAP related logic only when we running SCAP test
VR: http://openqa.suse.de/tests/17752416

Improve img-proof test

---

tests/console/year_2038_detection.pm

- Related ticket: https://progress.opensuse.org/issues/177802
- Related bug: https://bugzilla.suse.com/show_bug.cgi?id=1237773
- Verification run: https://openqa.suse.de/tests/17767768

year_2038: Skip testing for s390

---

tests/console/sssd_389ds_functional.pm

https://progress.opensuse.org/issues/182780
- Verification run: [sle15sp7&sle16&MU](http://openqa.suse.de/tests/overview?distri=sle&build=rfan0522)

Simplify 'sssd_389ds_functional' test

---

schedule/storage/nfs.yaml
tests/kernel/nfs_client.pm
tests/kernel/nfs_server.pm

- Related ticket: https://progress.opensuse.org/issues/182864
https://openqa.suse.de/tests/17791403
https://openqa.suse.de/tests/17791402
https://openqa.suse.de/tests/17791400
TW:
https://openqa.opensuse.org/tests/5065841
https://openqa.opensuse.org/tests/5065842
https://openqa.opensuse.org/tests/5065843
https://openqa.opensuse.org/tests/5065976
https://openqa.opensuse.org/tests/5065975
https://openqa.opensuse.org/tests/5065974
https://openqa.suse.de/tests/17791977
https://openqa.suse.de/tests/17791975
https://openqa.suse.de/tests/17791976

nfs server sle16

---

tests/console/ping.pm

verification run:
* https://openqa.suse.de/tests/17733833#step/ping/193 (softfail on s390x)
* https://openqa.suse.de/tests/17733835#step/ping/193 (pass on other archs)

ping: Add test for ttl=0 s390x bug

---

lib/containers/bats.pm

bats: Fix aardvark-dns test

---

tests/publiccloud/prepare_tools.pm

- Related ticket: https://progress.opensuse.org/issues/182579
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/17822937#step/prepare_tools/1

Fix prepare_tools step for public cloud server image 15-SP5

---

data/security/crypto_policies/test_nss_client.sh

Ticket: https://progress.opensuse.org/issues/182786
VR: [16.0](https://openqa.suse.de/tests/17824267)

test_nss_client.sh: wait 3s before testing the connection

---

tests/installation/agama_reboot.pm

VR: https://openqa.opensuse.org/tests/5064939#live

Upload agama logs and config during installation

---

tests/network/openvpn_server.pm

Adjusting OpenVPN tests for SLE16
- Related ticket: https://progress.opensuse.org/issues/182819
- 15-SP7: 
- https://openqa.suse.de/tests/17853427
- https://openqa.suse.de/tests/17853426
- 16.0: 
- https://openqa.suse.de/tests/17836542
- https://openqa.suse.de/tests/17836543
- https://openqa.suse.de/tests/17836540
- https://openqa.suse.de/tests/17836541

Adjust OpenVPN test for SLE16

---

data/journal_check/bug_refs.json

Add bsc#1218471 to the journal check bug refs
- Related ticket: https://progress.opensuse.org/issues/183125
- Verification run: https://openqa.suse.de/tests/17853545

Add bsc#1218471 to the journal check bug refs

---

lib/opensusebasetest.pm

- Related ticket: https://bugzilla.suse.com/show_bug.cgi?id=1243491 https://progress.opensuse.org/issues/182972 https://gitlab.suse.de/qa-maintenance/qam-openqa-yml/-/merge_requests/851
https://openqa.suse.de/tests/17855867

install_patterns: Workaround GDM crash on 15-SP7 ppc64le

---

data/yam/agama/auto/lib/scripts_pre.libsonnet
data/yam/agama/auto/lvm_encrypted_ppc64le.jsonnet
data/yam/agama/auto/scripts.jsonnet
data/yam/agama/auto/scripts_ssh_pub_key.jsonnet
data/yam/agama/auto/sles_addons_ssh_pub_key_ppc64le.jsonnet
data/yam/agama/auto/sles_default_ssh_pub_key_ppc64le.jsonnet
data/yam/agama/auto/sles_gnome_ssh_pub_key_ppc64le.jsonnet
data/yam/agama/auto/sles_lvm_ssh_pub_key_ppc64le.jsonnet
data/yam/agama/auto/sles_packages_ppc64le.jsonnet
data/yam/agama/auto/sles_root_filesystem_ext4_ssh_pub_key_ppc64le.jsonnet
data/yam/agama/auto/sles_root_filesystem_xfs_ssh_pub_key_ppc64le.jsonnet
data/yam/agama/auto/sles_sap_default_ssh_pub_key.jsonnet

We need decide which method is the better solution, then apply to profiles.
- Related ticket: https://progress.opensuse.org/issues/181346
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/overview?build=poo%23181346_investigation&distri=sle&version=agama-10.0    20/20 passed on latest build in development group.
https://openqa.suse.de/tests/17682330#details   ibft passed  on latest build 125.14,

Ensure disabling questions bypass the encryption popup in Agama

---

tests/microos/install_image.pm

- Related ticket: https://progress.opensuse.org/issues/183023
ipmi : https://openqa.suse.de/tests/17871946#step/install_image/9
ppc64le: https://openqa.suse.de/tests/17871734

install_image: Add option to find target disk by WWN

---

data/yam/agama/auto/lib/security.libsonnet
data/yam/agama/auto/template.libsonnet
schedule/yam/agama_rmt_unattended.yaml
schedule/yam/agama_rmt_unattended_ppc64le.yaml
schedule/yam/agama_rmt_unattended_s390x.yaml
test_data/yam/agama_rmt.yaml

##
- Related ticket: [182996][1]
- Related MR: 
- [qe-yam#454][2]
- Needles: N/A
- [VR][3]
- Related bug: [1243788][4]
[1]: https://progress.opensuse.org/issues/182996
[2]: https://gitlab.suse.de/qe-yam/openqa-job-groups/-/merge_requests/454
[3]: https://openqa.suse.de/tests/overview?distri=sle&build=hjluo_rmt_unattended&version=agama-10.0
[4]: https://bugzilla.suse.com/show_bug.cgi?id=1243788
##

Automate SCC RMT product registration

---

lib/sles4sap_publiccloud.pm
schedule/sles4sap/qesapdeploy/qesap.yml
tests/sles4sap/qesapdeployment/test_console_redirection.pm

sle-15-SP6-Qesap-Azure-Payg-x86_64-BuildLATEST_AZURE_SLE15_6_PAYG-qesap_azure_saptune_test 
- http://openqaworker15.qa.suse.cz/tests/325748 :green_circle: 
- https://openqaworker15.qa.suse.cz/tests/325766 :green_circle: 
sle-15-SP6-Qesap-Aws-Byos-x86_64-BuildLATEST_AWS_SLE15_6_BYOS-qesap_aws_angi_test
-  http://openqaworker15.qa.suse.cz/tests/325767 :green_circle: 
sle-15-SP6-Qesap-Gcp-Payg-x86_64-BuildLATEST_GCE_SLE15_6_PAYG-qesap_gcp_ibsmirror_peering_test
- http://openqaworker15.qa.suse.cz/tests/325768 :green_circle:

Add PoC for console_redirection in qesap

---

tests/console/aaa_base.pm

- Related ticket:  https://progress.opensuse.org/issues/182777
- Verification run: https://openqa.suse.de/tests/17853054#step/aaa_base/22
sle15sp7: https://openqa.suse.de/tests/17853059
Refer bug: https://bugzilla.suse.com/show_bug.cgi?id=1243504
https://openqa.suse.de/tests/overview?build=tinawang123%2Fos-autoinst-distri-opensuse%23aaa_base&distri=sle

Update code for aaa_base

---

test_data/yam/agama_sle.yaml

We have added URI inside the test data file.
- Related ticket: https://progress.opensuse.org/issues/180956
- Related MR: https://gitlab.suse.de/qe-yam/openqa-job-groups/-/merge_requests/455
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/17882215

Added URI to agama repo validation

---

.github/workflows/ci.yml

Ticket: https://progress.opensuse.org/issues/162998

Install liblua5.3-dev in CI job as required by dependency Inline::Lua

---

data/containers/bats/skip.yaml
tests/containers/bats/README.md

Ignore `200-pod` on SLE 16.0 as it's done on Tumbleweed.

Minor BATS fixes

---

tests/x11/evolution/evolution_prepare_servers.pm

- Related ticket: https://progress.opensuse.org/issues/183230
https://openqa.suse.de/tests/17912010 15-SP7
https://openqa.suse.de/tests/17912004 15-SP6

evolution: Use Server Applications module for dovecot

---

lib/virt_autotest/esxi_utils.pm
tests/virt_autotest/esxi_open_vm_tools.pm

https://progress.opensuse.org/issues/178876
https://progress.opensuse.org/issues/183470
https://progress.opensuse.org/issues/183467
- Needles: N/A
- Verification run:  https://openqa.suse.de/tests/17917012

Change vmware hypervisor and fix timesync check and SSH

---

tests/x11/evolution/evolution_prepare_servers.pm

- Related ticket: a3b41001121ac524f49ae9587d636cd8fdf26026
- VR:
https://openqa.suse.de/tests/17933206
https://openqa.suse.de/tests/17933313

evolution: Fix typo in a3b41001121ac524f49ae9587d636cd8fdf26026

---

tests/sles4sap/publiccloud/qesap_terraform.pm

After moving peering creation to terraform, the `clean_leftover_peerings` module does not work, since it tries to clean old peerings *after* trying to generate the new one. This pr attempts to move the peering cleanup inside the `qesap_terraform` module, before running terraform.
- Related ticket: https://jira.suse.com/browse/TEAM-10386
https://openqa.suse.de/tests/17930935#step/deploy_qesap_terraform/268

Move peering cleanup before terraform deployment

---

schedule/functional/sle16/agama-create-hdd-gnome.yaml
schedule/functional/sle16/agama-create-hdd-textmode.yaml
tests/installation/network_check.pm

https://progress.opensuse.org/issues/183446
- Verification run: [sle16](http://openqa.suse.de/tests/overview?build=RFAN_06051&version=16.0&distri=sle)

Make sure NIC is up after installation

---

lib/sles4sap/sap_deployment_automation_framework/deployment_connector.pm
t/26_deployment_connector.t

This PR changes the way how `find_deployment_id`  searches for deployment ID. It collects all test IDs present in MM test chain and compares it to deployment IDs present in the cloud. If there is exactly one match between test ID and Deployment ID, function returns it as a result. 
Ticket: https://jira.suse.com/browse/TEAM-10319
Mock MM test: https://mordor.suse.cz/tests/1978# (There is no deployment, therefore the failure in last job)
HanaSR: https://openqaworker15.qa.suse.cz/tests/325874#dependencies
ENSA2: https://openqaworker15.qa.suse.cz/tests/325871#dependencies

SDAF Improve deployment ID detection

---

data/yam/agama/auto/lib/base.libsonnet
data/yam/agama/auto/template.libsonnet

Help Leo for remaining work in https://progress.opensuse.org/issues/177477#
- Related ticket: https://progress.opensuse.org/issues/177477#
- Related MR : https://gitlab.suse.de/qe-yam/openqa-job-groups/-/merge_requests/466
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/overview?version=16.0&distri=sle&build=lemon-suse%2Fos-autoinst-distri-opensuse%23transport_jsonnet_to_template

Translate existing jsonnet to template

---

tests/security/oqs_provider_openssl.pm

Ticket: https://progress.opensuse.org/issues/183461
VRs: https://openqa.suse.de/tests/overview?distri=sle&version=16.0&build=96.1&groupid=431
Related MR: https://gitlab.suse.de/qe-security/openqa-data/-/merge_requests/462

Refactor oqs-provider test

---

data/journal_check/bug_refs.json

Mark "Updating logout time failed" to be ignored

---

lib/kdump_utils.pm

A new function, `set_kdump_config`, simplifies modification of the
kdump configuration. It is possible to set a custom crashkernel
memory value or enabling fadump on SLE 16.
- Related ticket: https://progress.opensuse.org/issues/173998
x86_64: https://openqa.suse.de/tests/18031661#step/kdump/73 (failed because of unrelated bsc)
ppc64le https://openqa.suse.de/tests/18031690
ppc64le fadump:   https://openqa.suse.de/tests/18031651
Tumbleweed: https://openqa.opensuse.org/tests/5099815  (failed because of unrelated bsc)
SLE ncurses: https://openqa.suse.de/tests/18039421

kdump_utils: Extend configuration on SLE 16

---

tests/containers/bats/buildah.pm

We install `docker` to test buildah integration but forgot to enable the service, thus resulting in silent skips.
- Tumbleweed: https://openqa.opensuse.org/tests/5100332
- SLE 16.0: https://openqa.suse.de/tests/18038031
- SLES 15-SP7: https://openqa.suse.de/tests/18038030
- SLES 15-SP6: https://openqa.suse.de/tests/18038029
- SLES 15-SP5: https://openqa.suse.de/tests/18041461
- SLES 15-SP4: https://openqa.suse.de/tests/18039561

bats/buildah: Enable docker service

---

tests/x11/evolution/evolution_prepare_servers.pm

Follows: #22203
- Failure: https://openqa.opensuse.org/tests/5100282#step/evolution_prepare_servers/54
- VR: https://openqa.opensuse.org/tests/5103094#step/evolution_prepare_servers/123

Adapt evolution_prepare_servers for jeos

---

tests/sles4sap/netweaver_nfs_setup.pm

In the netweaver_nfs_setup module, we lock the support_server_ready mutex and we never unlock it. Additionally, this mutex is already used by other modules most notably lib/opensusebasetest.pm, which makes this a bigger problem as we are unable to add a reboot in any module past the point we lock the mutex, without introducing a dead lock.
To fix this, we use a different mutex that is exclusive to the netweaver_nfs_setup module.
- Related ticket: TEAM-10431
- Verification run: https://openqaworker15.qa.suse.cz/tests/overview?build=_ensa_deadlock&distri=sle&version=15-SP6

Fix use of mutex in netweaver_nfs_setup.pm

---

tests/security/tpm2/tpm2_env_setup.pm

Ticket: https://progress.opensuse.org/issues/175275
VR: https://openqa.suse.de/tests/18089986

Reinstall tpm2-0-tss on 15-SP6 aarch64

---

tests/console/wireshark_cli.pm

- Related ticket: https://progress.opensuse.org/issues/184168
- Verification run: https://openqa.suse.de/tests/18094936 (test is failing only on 12sp5)

wireshark_cli: Increase retry in script_retry

---

tests/yam/agama/boot_agama.pm

https://progress.opensuse.org/issues/184333
- Verification run: [all arches](https://openqa.suse.de/tests/overview?build=rfan1234&distri=sle&version=16.0)

Add console definition for ppc64le

---

data/virt_autotest/guest_params_xml_files/sles_16_64_kvm_hvm_sev_es_x86_64_agama_online_iso.xml
data/virt_autotest/guest_params_xml_files/sles_16_64_kvm_hvm_x86_64_agama_full_iso.xml
data/virt_autotest/guest_params_xml_files/sles_16_64_kvm_hvm_x86_64_agama_online_iso.xml
data/virt_autotest/guest_params_xml_files/sles_16_64_kvm_hvm_x86_64_qcow_ignition+combustion.xml

* **Update** SLES16 VM os variant to ```sles16```.
* [uefi guest](https://openqa.suse.de/tests/18132672)
* [sev-es guest](https://openqa.suse.de/tests/18133325)

Update SLES16 VM os variant

---

data/yam/autoyast/textmode.xml
data/yam/autoyast/textmode_ppc64le.xml
data/yam/autoyast/textmode_s390x.xml
schedule/yam/agama_migration_15sp7_textmode.yaml

- Related ticket: https://progress.opensuse.org/issues/178987
- Related MR: https://gitlab.suse.de/qe-yam/openqa-job-groups/-/merge_requests/481
- Needles: N/A
- Verification run:  https://openqa.suse.de/tests/overview?distri=sle&version=16.0&build=97.3&groupid=316

Create unattended installation for migration to 16.0

---

data/wpa_supplicant/wpa_supplicant_wo_dhcp_test.sh
tests/console/wpa_supplicant.pm

Add qa head repo for hostapd
- Related ticket: https://progress.opensuse.org/issues/184129
- Verification run: https://openqa.suse.de/tests/18164126#step/wpa_supplicant/47
TW has dhcp-client package, no need update: https://openqa.opensuse.org/tests/5117152#step/wpa_supplicant/21

Add qa head repo for hostapd

---

tests/ha/priority_fencing_delay.pm

cluster slave node didn't reboot after triggering network issue with iptables on SLE 16.0, here is the failed job:
https://openqa.suse.de/tests/17976099#step/priority_fencing_delay/16
create workaround for the issue after testing many times with cluster developer (Xin Liang).
increate timeout for assert_script_run because of the [failure](https://openqa.suse.de/tests/18039413#step/priority_fencing_delay/42)
- Related Bug: https://bugzilla.suse.com/show_bug.cgi?id=1244437
- Related MR: https://gitlab.suse.de/qa-css/openqa_ha_sap/-/merge_requests/1030
https://openqa.suse.de/tests/18093416 (x86_64: node01)
https://openqa.suse.de/tests/18093414 (x86_64: node02)
https://openqa.suse.de/tests/18116697 (ppc64le: node01)
https://openqa.suse.de/tests/18116698 …

Workaround for bsc#1244437

---

tests/sles4sap/ensa/netweaver_swpm_installation.pm

SELinux imposes wide ranging restrictions on what we can do on a system and one of them is installing from /tmp/.
This moves the installation directory to a more conformant directory and adds a step to relabel the files created by the installation.
- Related Tickets: TEAM-10414
- Verification run:  [nw_install_changes](https://openqaworker15.qa.suse.cz/tests/overview?build=%3Anw_install_changes-enforcing&distri=sle) 
SLE15 succeeds and SLE16 fails as expected because of SELinux.

Make NW installation compatible with SELinux

---

tests/update/updates_packagekit_kde.pm

Ticket: https://progress.opensuse.org/issues/184510
VR: 
- https://openqa.opensuse.org/tests/5128480#step/updates_packagekit_kde/28
- https://openqa.opensuse.org/tests/5128534#step/updates_packagekit_kde/30
- aarch64 https://openqa.opensuse.org/tests/5128580#step/updates_packagekit_kde/27
Needles created directly on o3 (discover-confirm-changes-20250624)

Handle Discover's popup to confirm updates

---

lib/utils.pm

Do not disconnect dev connection for sle16
After MR https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/22287 merge plus latest implementation of sle16 network,  the second interface will not auto set default configuration so trigger failure on ipsec test case https://openqa.suse.de/tests/18059427#step/ipsec3hosts/123.
Detail feedback from developer: https://bugzilla.suse.com/show_bug.cgi?id=1244695#c5  
- Related ticket: https://progress.opensuse.org/issues/184165
- Verification run: https://openqa.suse.de/tests/18138668#step/ipsec3hosts/4

Do not disconnect dev connection for sle16

---

tests/yam/migration/restore_upgrade_env.pm
tests/yam/migration/setup_upgrade_env.pm

- Related ticket: https://progress.opensuse.org/issues/178987
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/18215547#details

Save/restore SCC_URL during migration test

---

lib/containers/bats.pm
tests/containers/bats/README.md

- Try `git apply` without `--include` first as we need to compile helpers.
- Document https://github.com/opencontainers/runc/issues/4732
Verification run: https://openqa.suse.de/tests/18234096 (failing for other reason)

Minor BATS improvements

---

schedule/yam/agama_non_default_root_filesystem.yaml

##
- Needles: N/A
- https://openqa.suse.de/tests/18245774
##

Remove agama_arrange from agama_non_default_root_filesystem.yaml

---

tests/wicked/before_test.pm

wicked: Use OBS for CA repo

---

tests/console/libgpiod.pm

- Related ticket: https://progress.opensuse.org/issues/184591
- Verification run: https://openqa.opensuse.org/tests/5138236

libgpiod: fix test for libgpiod v2.x

---

tests/security/tpm2/tpm2_env_setup.pm

Ticket: https://progress.opensuse.org/issues/184852
VR: https://openqa.suse.de/tests/18263476

tpm2_env_setup: add workaround also for 15-SP7

---

lib/wickedbase.pm

This is useful for debugging issues like [bsc#1243291](https://bugzilla.suse.com/show_bug.cgi?id=1243291)
https://openqa.suse.de/tests/18081551 (SLE-15-SP7)
http://openqa.wicked.suse.de/tests/289809#step/t12_teaming_random/15 (tumbleweed)

Add selinux info

---

lib/klp.pm

SLE16 has kernel-default-livepatch and kernel-livepatch-* packages in
the main product repository.
- Related ticket: https://progress.opensuse.org/issues/174001
SLE16: https://openqa.suse.de/tests/18278134

klp: Add SLE 16 support

---

lib/bootloader_setup.pm
tests/installation/bootloader_s390.pm

- Related ticket: https://progress.opensuse.org/issues/181295
- Related MR: https://gitlab.suse.de/qe-yam/openqa-job-groups/-/merge_requests/506
- Needles: N/A
- s390x-kvm: https://openqa.suse.de/tests/18176939
- s390x-zvm zfcp: https://openqa.suse.de/tests/18183773
- s390x-zvm: https://openqa.suse.de/tests/18176938

Move s390x zVM setting inside bootloader code

---

tests/console/zypper_lifecycle.pm

https://progress.opensuse.org/issues/185221
- Verification run:  https://openqa.suse.de/tests/18313531#step/zypper_lifecycle/66

Adapt zypper lifecycle check logic on sle16

---

lib/sles4sap/sap_deployment_automation_framework/basetest.pm

Extend SDAF log collection for post fail hook
Related ticket:  
- [TEAM-10447](https://jira.suse.com/browse/TEAM-10447) - [SDAF] Extend log collection for post fail hook  
Verification run:   
- SDAF_PRD_deploy_HanaSR:  https://openqaworker15.qa.suse.cz/tests/331795#step/create_deployer_vm/43 (died in `deployment` on purpose: the log uploading not happened as expected)
- SDAF_PRD_HanaSR_failover:  https://openqaworker15.qa.suse.cz/tests/331813#step/redirection_check/26 (died in `redirection_check` on purpose: the logs are uploaded)
- SDAF_PRD_HanaSR_failover:  https://openqaworker15.qa.suse.cz/tests/331980#step/connect_to_deployer/84 (died in `connect_to_deployer` on purpose the logs are uploaded)
- SDAF_PRD_cleanup_HanaSR:  https://openqaworker15.qa.suse.cz/tests/331984#step/redirection_c …

Extend SDAF log collection for post fail hook

---

products/sle/main.pm

handling the svirt backend
- Related ticket: https://progress.opensuse.org/issues/184966
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/18314723

xfstests: handling the svirt backend

---

tests/installation/zdup.pm

Failure https://openqa.opensuse.org/tests/5151926#step/zdup/12
VR: https://openqa.opensuse.org/tests/5155255

Handle conflicts for gstreamer-plugins-bad

---

schedule/qam/16/create_hdd_textmode_increment.yaml

https://progress.opensuse.org/issues/185347
- Verification run: https://openqa.suse.de/tests/18362706

Schedule sle16 MU increment tests

---

tests/update/updates_packagekit_kde.pm

Ticket: https://progress.opensuse.org/issues/184510
Failure: https://openqa.opensuse.org/tests/5156108#step/updates_packagekit_kde/24
VR: https://openqa.opensuse.org/tests/5158072

Wait longer for Discovery to fetch updates

---

tests/containers/rootless_docker.pm

This reverts commit 948bcee78fe8468045347dab49e20ddcfdcc83d6.
We need to wait for the docker S:M:38234:381822 to remove this workaround.

Revert "containers: No need to disable SUSE secrets anymore"

---

lib/version_utils.pm

Failure: https://openqa.opensuse.org/tests/5158193#step/host_config/22
VR https://openqa.opensuse.org/tests/5158328

Microos-SelfInstall image uses grub2

---

tests/yam/validate/validate_systemd_timers.pm

- Related ticket: [poo#185038](https://progress.opensuse.org/issues/185038)
- Verification run: [overview](https://openqa.suse.de/tests/overview?build=issues-185038)

Test systemd timers: check elapsed time

---

schedule/security/sle16/agama_remote_pvm.yaml

Modify secruriy agama ppc64le schedule to work in full
- Related ticket: https://progress.opensuse.org/issues/185050
- Verification run: https://openqa.suse.de/tests/18372661

Adjust agama security schedule to lastest needs

---

tests/sles4sap/monitoring_services.pm

- Related ticket: https://jira.suse.com/browse/TEAM-10381
http://10.100.103.210/tests/332270 failure is fine as the missing file is about to be moved at package level.
More examples using different code versions. 
- https://openqaworker15.qa.suse.cz/tests/331856 :green_circle: package install fine and service can be started
- https://openqaworker15.qa.suse.cz/tests/331990
- `zypper in` :green_circle: https://openqaworker15.qa.suse.cz/tests/331990/logfile?filename=serial_terminal.txt#line-6713
- service enabled and status :green_circle:  https://openqaworker15.qa.suse.cz/tests/331990/logfile?filename=serial_terminal.txt#line-6755
- `journalctl` :green_circle: https://openqaworker15.qa.suse.cz/tests/331990/logfile?filename=serial_terminal.txt#line-6772

Add test for Grafana Alloy

---

data/yam/agama/auto/lib/software.libsonnet
data/yam/agama/auto/template.libsonnet
schedule/yam/agama_extended_unattended.yaml
schedule/yam/agama_extended_unattended_ppc64le.yaml
schedule/yam/agama_extended_unattended_s390x.yaml
test_data/yam/agama_sle_extended.yaml

Add custom repositories for unattended installation to the sles_extended_unattended testsuites.
- Related ticket: https://progress.opensuse.org/issues/184360
- Verification run: [verification](https://openqa.suse.de/tests/overview?arch=&flavor=Online&machine=&test=&modules=&module_re=&group_glob=&not_group_glob=&comment=&distri=sle&version=16.0&build=chcao_184360#)
- Related mr: [mr_link](https://gitlab.suse.de/qe-yam/openqa-job-groups/-/merge_requests/508)

Add custom repositories for unattended installation

---

tests/security/oqs_provider_openssl.pm

Ticket: https://progress.opensuse.org/issues/185242
VRs: [16.0](https://openqa.suse.de/tests/overview?distri=sle&version=16.0&build=116.2&groupid=431), [15-SP7](https://openqa.suse.de/tests/overview?distri=sle&version=15-SP7&build=20250709-1&groupid=431), [15-SP6](https://openqa.suse.de/tests/overview?distri=sle&version=15-SP6&build=20250709-1&groupid=431), [15-SP4](https://openqa.suse.de/tests/overview?distri=sle&version=15-SP4&build=20250709-1&groupid=431)

oqs_provider: add more ciphers

---

tests/security/vsftpd/vsftpd_setup.pm

Ticket: https://progress.opensuse.org/issues/185329
VR: https://openqa.suse.de/tests/18404498#

Enable ftpd_full_access SELinux boolean on SLE ≥16

---

lib/containers/bats.pm
lib/main_containers.pm

Move BATS schedule code to run earlier
- Related ticket: https://progress.opensuse.org/issues/185689

Move BATS schedule code to run earlier

---

lib/Yam/Agama/Pom/GrubMenuAgamaPage.pm
schedule/yam/agama_check_rescue_system.yaml
test_data/yam/agama_rescue_system.yaml
tests/yam/agama/boot_agama.pm
tests/yam/validate/validate_rescue_system.pm

- Related ticket: https://progress.opensuse.org/issues/183266
- Related MR: https://gitlab.suse.de/qe-yam/openqa-job-groups/-/merge_requests/518
- VR (in my dev group): https://openqa.suse.de/tests/18404396

Automate rescue system

---

tests/console/zypper_extend.pm

Ticket: https://progress.opensuse.org/issues/185752
Failure: https://openqa.opensuse.org/tests/5170166#step/zypper_extend/78
VR:
- 12-sp3: https://openqa.suse.de/tests/18425695
- 12-sp5: https://openqa.suse.de/tests/18425694
- 15-sp7: https://openqa.suse.de/tests/18425693
- Tumbleweed: https://openqa.opensuse.org/tests/5171316

Add correct repository for Packman for Tumbleweed

---

products/sle/main.pm
schedule/qam/16/mau-extra-tests.yaml
schedule/qam/16/mau-webserver.yaml

Add jobs for SLE16 Maintenance
- Related ticket: https://progress.opensuse.org/issues/182918
- Verification run: https://openqa.suse.de/group_overview/656
https://openqa.suse.de/group_overview/661

Add jobs for SLE16 Maintenance

---

tests/qam-updinstall/update_install.pm

- Related ticket: https://suse.slack.com/archives/C02CLB8TZP1/p1752559571561909
https://openqa.suse.de/tests/overview?build=%3A38234%3Adocker&groupid=644
https://openqa.suse.de/tests/overview?build=%3A38234%3Adocker&groupid=546

update_install: Add docker*zsh-completion conflict

---

tests/qemu/kvm.pm

- Related ticket: https://progress.opensuse.org/issues/179684
- Verification run: https://openqa.opensuse.org/tests/5175388

kvm: handle new uefi firmware - poo#179684

---

lib/containers/bats.pm

This PR enables BATS tests on aarch64 on TW that use ncat as dependency.
Related PR: https://github.com/os-autoinst/opensuse-jobgroups/pull/689
- aardvark-dns: https://openqa.opensuse.org/tests/5175622
- netavark: https://openqa.opensuse.org/tests/5175623
- podman: https://openqa.opensuse.org/tests/5175624 (failing, not included in related PR).

Enable BATS tests on aarch64

---

data/yam/agama/auto/lib/storage.libsonnet
test_data/yam/whole_disk_and_boot_unattended.yaml

- Related ticket: https://progress.opensuse.org/issues/184363
- Related MR: https://gitlab.suse.de/qe-yam/openqa-job-groups/-/merge_requests/520
- VR: https://openqa.suse.de/tests/18428928 (in my dev group)

Automate further sorting in search

---

schedule/yam/agama.yaml
schedule/yam/agama_non_default_root_filesystem.yaml
schedule/yam/agama_unattended.yaml
tests/yam/validate/validate_connectivity.pm

- Related ticket: [poo#184043](https://progress.opensuse.org/issues/184043)
+ [sles_root_filesystem_ext4_unattended__TEST__](https://openqa.suse.de/tests/overview?build=issues-184043&test=sles_root_filesystem_ext4_unattended__TEST__)
+ [sles_root_filesystem_ext4_unattended__DEFAULT__TEST__](https://openqa.suse.de/tests/overview?build=issues-184043&test=sles_root_filesystem_ext4_unattended__DEFAULT__TEST__)
+ [sles_default__TEST__](https://openqa.suse.de/tests/overview?build=issues-184043&test=sles_default__TEST__)
+ [sles_default__DEFAULT__TEST__](https://openqa.suse.de/tests/overview?build=issues-184043&test=sles_default__DEFAULT__TEST__)
+ [sles_default_unattended__TEST__](https://openqa.suse.de/tests/overview?build=issues-184043&test=sles_default_unattended__TEST__) …

Automate selection of option to prevent copying network

---

tests/containers/bats/README.md

Update list of openQA jobs after inclusion of aarch64.

bats: Update list of openQA jobs

---

tests/containers/bats/podman.pm

bats/podman: Add missing is_sle import

---

lib/haclusterbasetest.pm

Add POD to lib haclusterbasetest
- Related ticket: [TEAM-10497](https://jira.suse.com/browse/TEAM-10497) - [timeboxed]Add POD documentation to lib/haclusterbasetest
- Verification run: NA

Add POD to lib haclusterbasetest

---

data/valkey/replica.conf
data/valkey/valkey.conf
schedule/functional/sle16/extra_tests_textmode2.yaml
tests/console/valkey.pm

https://progress.opensuse.org/issues/182654
[sle16](https://openqa.suse.de/tests/18473009)
[tw](https://openqa.opensuse.org/tests/5182727)

Add TLS support for valkey test

---

tests/console/libgit2.pm

Fix the regular expression problem for libgit2
- Related ticket: https://progress.opensuse.org/issues/183842
- Verification run: https://openqa.suse.de/tests/18532901#
- Related MR: https://gitlab.suse.de/qe-core/qa-sle-functional-userspace/-/merge_requests/289

Fix the regular expression problem for libgit2

---

data/virt_autotest/sriov_network_guest_logging.sh
lib/virt_autotest/utils.pm
lib/virt_autotest/virtual_network_utils.pm
schedule/virt_autotest/sle16_guest_installation.yaml
tests/virt_autotest/sriov_network_card_pci_passthrough.pm

Related ticket: https://progress.opensuse.org/issues/178702
associate PR: https://gitlab.suse.de/qa-testsuites/openqa-job-group-yaml/-/merge_requests/283
https://openqa.suse.de/tests/18525004
https://openqa.suse.de/tests/18525170
https://openqa.suse.de/tests/18523810

Support SR-IOV ethernet device passthrough test for sle16

---

schedule/security/sle16/agama.yaml

Adjust the Agama schedule for ppc64le and Full flavor of x86_64 aarch64 
- Related ticket: https://progress.opensuse.org/issues/185587
- https://openqa.suse.de/tests/18550622
- https://openqa.suse.de/tests/18550623
- https://openqa.suse.de/tests/18549200
- https://openqa.suse.de/tests/18550631

Update agama security install schedule

---

schedule/security/create_hdd_cc_libyui/aarch64/cc_maint_15sp3.yaml
schedule/security/create_hdd_cc_libyui/aarch64/cc_maint_15sp6.yaml
schedule/security/create_hdd_cc_libyui/x86_64/cc_maint.yaml

Ticket: https://progress.opensuse.org/issues/186338
VRs: https://openqa.suse.de/tests/overview?distri=sle&version=15-SP3&build=20250724-1&groupid=431

Register extensions and modules in maintenance

---

tests/xfstests/partition.pm

The test NFS over kTLS is a new test extend for PED-12376. 
The setting in openQA to enable kTLS need to set in XFSTESTS_NFS_VERSION with TLS or TLS-<NFS version>
- Related ticket: https://progress.opensuse.org/issues/178471
- https://jira.suse.com/browse/PED-12376
NFS3   https://openqa.suse.de/tests/18547536
NFS4.0 https://openqa.suse.de/tests/18547535
NFS4.1 https://openqa.suse.de/tests/18547534
NFS4.2 https://openqa.suse.de/tests/18547271

xfstests: Add new test for NFS over kTLS

---

lib/hacluster.pm
schedule/ha/bv/basic_cluster_node.yaml
t/11_hacluster.t
tests/ha/add_sbd_device.pm
tests/ha/barrier_init.pm
tests/ha/change_sbd_metadata.pm
tests/ha/remove_sbd_device.pm

1. Add a second SBD device to cluster and check the result
2. Remove a SBD device from cluster
3. Change SBD metadata and check the result
Related: https://jira.suse.com/browse/TEAM-10493
VR:  https://openqa.suse.de/tests/18538612#

Add HA SBD sub command test cases

---

tests/kernel/run_kselftests.pm

- Related ticket: https://progress.opensuse.org/issues/182363
sle16 https://openqa.suse.de/tests/18611040
sle15sp7 https://openqa.suse.de/tests/18611038
sle15sp6 https://openqa.suse.de/tests/18611170

kelftests: Quick patch for KOTD tests

---

tests/containers/kubectl.pm

Remove soft-failure for https://bugzilla.suse.com/show_bug.cgi?id=1245087
Issue no longer seen on:
- 15-SP3: https://openqa.suse.de/tests/overview?distri=sle&version=15-SP3&build=20250730-1&groupid=417
- 15-SP4: https://openqa.suse.de/tests/overview?distri=sle&version=15-SP4&build=20250730-1&groupid=417
- 15-SP5: https://openqa.suse.de/tests/overview?distri=sle&version=15-SP5&build=20250730-1&groupid=417

containers: Remove soft-failure for resolved bsc#1245087

---

lib/containers/bats.pm

Use our own ncat packages for x86_64.  These work fine on aarch64.

bats: Use our own ncat packages for x86_64

---

lib/containers/bats.pm

Drop `bats_patches` function to simplify things.
- Verification run: https://openqa.opensuse.org/tests/5216036

bats: Drop bats_patches() function

---

lib/containers/bats.pm

Fix non-oss repo for Tumbleweed

bats: Fix non-oss repo for Tumbleweed

---

data/generalhw_scripts/power_on_off_shelly.sh

Ticket: https://progress.opensuse.org/issues/178054

Better error reporting for shelly script

---

tests/console/arping.pm

For ARP requests to work, layer 2 networking needs to be set up. Some s390x z/VM setups use layer 3 networking only and this test won't work.
- Related ticket: https://progress.opensuse.org/issues/186663
- Verification run: https://openqa.opensuse.org/tests/5222535#live

console/arping.pm: Skip if s390x SUT not configured for layer 2 networking

---

lib/Yam/Agama/Pom/GrubMenuAgamaPage.pm

- Related ticket: https://progress.opensuse.org/issues/186702
- Needles: N/A

Remove not needed including

---

lib/containers/bats.pm

Add collect_coredumps to post hooks
I needed to add this routine to provide a coredump for https://github.com/opencontainers/runc/issues/4836#issuecomment-3159341237
- Verification run: https://openqa.opensuse.org/tests/5224801 (coredump available as runc-unshare.3494.core.gz)

bats: Add collect_coredumps to post hooks

---

lib/Tomcat/ApacheProxyTest.pm
tests/x11/tomcat.pm

https://progress.opensuse.org/issues/184729
VR:https://openqa.suse.de/tests/18684862

Test tomcat on sle16

---

schedule/virt_autotest/sle16_guest_migration.xml

* **YAML** schedule file for SLE16 guest migration.
* **This** is just the yaml schedule file being used for automation work, so verification already done in https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/22501.

SLE16 guest migration yaml schedule

---

lib/sles4sap_publiccloud.pm

this is a sporadic, and not easy to reproduce, and this change will retry 5 times once "crm resource cleanup" failed.
- Related ticket: https://jira.suse.com/browse/TEAM-10483
https://openqa.suse.de/tests/18673730#step/Kill_replica/381

Retry when "crm resource cleanup" failed

---

schedule/qam/16/create_hdd_textmode_increment_s390x.yaml
schedule/qam/16/create_hdd_textmode_staging_s390x.yaml

Add s390x schedule file for sle16 MU job
- Related ticket: https://progress.opensuse.org/issues/185887
- Verification run: https://openqa.suse.de/tests/overview?distri=sle&version=15.99&build=7.7&groupid=661
https://openqa.suse.de/tests/overview?distri=sle&version=15.99&build=%3A176%3Agrep&groupid=656

Add s390x schedule file for sle16 MU job

---

tests/kernel/run_kselftests.pm

Instead of making a single big log available, let's upload them all since they're already being processed anyway.
- Related ticket: https://progress.opensuse.org/issues/187131
- Verification run: https://rmarliere-openqa.qe.prg2.suse.org/tests/1396#downloads

Kselftests: Upload partial logs

---

lib/publiccloud/ec2.pm

* Related issue: [poo#187053](https://progress.opensuse.org/issues/187053)
* Verification run: **In progress**

PC: Fix ec2 describe_instance() by providing the REGION

---

tests/console/ansible.pm

The s390x VMs run in a VLAN and in case wicked is managing the networking, hostname
seems to be set by the network infra.
The issue is not present in other tests than s390x MinimalVM.
- sle-15-SP7-JeOS-for-OpenStack-Cloud-QR-s390x-Build4.5.6-jeos-wizard@s390x-kvm -> https://openqa.suse.de/tests/18753359#step/ansible/71

Set transient hostname in ansible in case of s390x and wicked

---

schedule/virt_autotest/sle16_guest_migration.yaml

* **Rename** SLE16 guest migration schedule to yaml format

Rename SLE16 guest migration schedule to yaml format

---

tests/jeos/glibc_locale.pm

- ticket: https://progress.opensuse.org/issues/186987
Based on change https://github.com/openSUSE/aaa_base/pull/183, for
locale settings file `/etc/sysconfig/language` is no longer used in
factory.
* [sle-15-SP4-JeOS-for-kvm-and-xen-Updates](http://kepler.suse.cz/tests/25156#step/glibc_locale/52)
* [sle-15-SP7-JeOS-for-kvm-and-xen-QR-x86_64](http://kepler.suse.cz/tests/25157#step/glibc_locale/52)
* [12-sp5](http://kepler.suse.cz/tests/25160#step/glibc_locale/69)
* [opensuse-Staging:O-Staging-JeOS-for-kvm-and-xen-x86_64-BuildO.32.16-jeos](http://kepler.suse.cz/tests/25159#step/glibc_locale/87)
* [sle 16.0](http://kepler.suse.cz/tests/25158#step/glibc_locale/52)

Update glibc locale settings in TW

---

schedule/yam/agama.yaml
schedule/yam/agama_unattended.yaml
tests/yam/validate/validate_snapshots.pm

Applied requested changes mentioned in this PR https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/22813
- Related ticket: https://progress.opensuse.org/issues/185356
- Needles: N/A
- https://openqa.suse.de/tests/18783251 
- https://openqa.suse.de/tests/18783253

Ensure creation of the "after install" snapshot was removed

---

lib/containers/bats.pm
tests/containers/bats/aardvark.pm
tests/containers/bats/buildah.pm
tests/containers/bats/netavark.pm
tests/containers/bats/podman.pm
tests/containers/bats/runc.pm
tests/containers/bats/skopeo.pm

Set sane timeouts to address poo#183848
- Related ticket: https://progress.opensuse.org/issues/183848

bats: Set sane timeouts to address poo#183848

---

tests/sles4sap/monitoring_services.pm

Related: https://jira.suse.com/browse/TEAM-10555
VR: 
sle16: 
nw_node01 https://openqa.suse.de/tests/18829827# (passed)
nw_systemd_node: https://openqa.suse.de/tests/18834867# (passed)
sle15sp7: nw_node: https://openqa.suse.de/tests/18834892# (passed)

Only run grafana alloy for sle16

---

lib/sles4sap/ipaddr2.pm
tests/sles4sap/ipaddr2/cluster_create.pm
tests/sles4sap/ipaddr2/configure.pm
tests/sles4sap/ipaddr2/deploy.pm
tests/sles4sap/ipaddr2/destroy.pm
tests/sles4sap/ipaddr2/network_peering.pm
tests/sles4sap/ipaddr2/patch_system.pm
tests/sles4sap/ipaddr2/registration.pm
tests/sles4sap/ipaddr2/sanity_cluster.pm
tests/sles4sap/ipaddr2/sanity_os.pm
tests/sles4sap/ipaddr2/test_move_resource.pm

Minor changes about:
- POD documentation formatting
- Usage of constants for ping
Related ticket: https://jira.suse.com/browse/TEAM-10496
sle-15-SP7-SapCloud-Azure-Byos-x86_64-BuildLATEST_AZURE_SLE15_7-ipaddr2_azure_test 
-  http://openqaworker15.qa.suse.cz/tests/337974 :green_circle:

Minor adjustments in ipaddr2 code

---

schedule/qam/16/create-ibs-hdd-textmode.yaml
schedule/qam/common/qam-incidentinstall.yaml
tests/console/setup_ibs_repos.pm
tests/qam-updinstall/SLFO_update_install.pm

It's simpler copy of update_install without SMELT
https://progress.opensuse.org/issues/187116
https://dzedro.suse.cz/tests/2984#step/setup_ibs_repos/24 creating qcow2 for installtest
https://dzedro.suse.cz/tests/2983#step/SLFO_update_install/38

Add SLFO_update_install

---

lib/hacluster.pm
t/11_hacluster.t
tests/sles4sap/redirection_tests/check_ensa2_cluster.pm
tests/sles4sap/redirection_tests/check_hana_database.pm

SDAF tests do not contain yet checks and status screens for SBD based
cluster deployment. This PR adds checks for correct number of SBD
devices deployed
Ticket: https://jira.suse.com/browse/TEAM-10482
**VRs:**
**Hana SR:** https://openqaworker15.qa.suse.cz/tests/338153#step/check_hana_database/199
**Hana SR SBD:** https://openqaworker15.qa.suse.cz/tests/338150#step/check_hana_database/279
**ENSA2:** https://openqaworker15.qa.suse.cz/tests/337996#step/check_hana_database/198
**ENSA2 SBD:** https://openqaworker15.qa.suse.cz/tests/338161#
**Expected failure:** Number of expected devices does not match what is on the system
https://openqaworker15.qa.suse.cz/tests/338011#step/check_hana_database/220
https://openqaworker15.qa.suse.cz/tests/338003#step/check_hana_database/220
**Post VR change:** …

SDAF add checks for SBD devices

---

tests/sles4sap/publiccloud/azure_fence_agents_test.pm
tests/sles4sap/publiccloud/hana_sr_schedule_cleanup.pm
tests/sles4sap/publiccloud/hana_sr_schedule_deployment.pm
tests/sles4sap/publiccloud/hana_sr_schedule_primary_tests.pm
tests/sles4sap/publiccloud/hana_sr_schedule_replica_tests.pm
tests/sles4sap/publiccloud/hana_sr_takeover.pm
tests/sles4sap/publiccloud/hana_sr_test_secondary.pm
tests/sles4sap/publiccloud/mr_test_setup_env.pm
tests/sles4sap/publiccloud/qesap_ansible.pm
tests/sles4sap/publiccloud/qesap_cleanup.pm
tests/sles4sap/publiccloud/qesap_terraform.pm
tests/sles4sap/qesapdeployment/deploy.pm

Add POD documentation, fix typos, fix wrong lib name.
- sle-15-SP7-HanaSr-Azure-Payg-x86_64-Build15-SP7_2025-08-20T02:03:21Z-hanasr_azure_test_msi az_Standard_E4s_v3 -> http://openqaworker15.qa.suse.cz/tests/338182

Add POD documentation to HanaSR test modules

---

schedule/yam/agama_lvm.yaml
schedule/yam/agama_lvm_unattended.yaml
tests/yam/validate/validate_connectivity.pm

- Related ticket: [poo#184043](https://progress.opensuse.org/issues/184043)
- Verification run: [Online | agama-instaler](https://openqa.suse.de/tests/overview?build=issues-184043)
- Related [PR#137](https://github.com/jknphy/agama-integration-test-webpack/pull/137)

Add validate_connectivity to lvm scenario

---

tests/console/zypper_ar.pm

Follows #23079
VR: https://openqa.opensuse.org/tests/5262415

Unconditionally remove repos by alias

---

tests/containers/python_runtime.pm

Slight modification based on
* #23045
@ricardobranco777 WDYT?

Slightly simplify style in containers/python_runtime

---

tests/containers/python_runtime.pm

Extend docker-py tests to SLES 15.  For now, just make the module work but not schedule it.
- Verification run: https://openqa.suse.de/tests/18928220 (FAILED)

containers/docker-py: Extend tests to SLES 15

---

data/journal_check/bug_refs.json

- Related bug: https://bugzilla.opensuse.org/show_bug.cgi?id=1248738
- Verification run: https://openqa.opensuse.org/tests/5268712

Ignore bsc#1248738

---

tests/containers/bci_logs.pm

containers: Remove way too noisy "TYPE" record_info

---

data/yam/agama/auto/lib/software.libsonnet
data/yam/agama/auto/template.libsonnet
schedule/yam/agama_software_selection_unattended.yaml
schedule/yam/agama_software_selection_unattended_s390x.yaml

##
- https://progress.opensuse.org/issues/187686
- Needles: N/A
- Related MR: 
- https://gitlab.suse.de/qe-yam/openqa-job-groups/-/merge_requests/556
- [**sles_software_selection_unattended**](https://openqa.suse.de/tests/overview?version=16.0&distri=sle&build=hjluo%2Fos-autoinst-distri-opensuse%23removal_patterns)
##

Add addition and removal of patterns in unatttended installation

---

tests/fips/fips_setup.pm

- Related ticket: https://progress.opensuse.org/issues/187950
https://openqa.suse.de/tests/18971900
https://openqa.suse.de/tests/18971906#

fips_setup: Only do wait past bootloader with the Full media

---

data/agama_auto/sle_default_staging_s390x_kvm.jsonnet

- Related ticket: https://progress.opensuse.org/issues/187752
s390x:  https://openqa.suse.de/tests/18991932#step/zypper_lr/6
qemu:  https://openqa.suse.de/tests/18959743#step/zypper_lr/9

Add PackageHub and extra repos with unknown gpg

---

tests/sles4sap/netweaver_filesystems.pm

This ticket uses test-specific (yet reusable) dir names for NFS shares, to allow concurrent tests without conflicts in the shared directories.
- Related ticket: https://jira.suse.com/browse/TEAM-10606
https://openqa.suse.de/tests/18992615 (and dependencies)

Create unique directories for NFS share

---

tests/publiccloud/slem_basic.pm

Add smoke test for xen-tools-domU package and run a command provided by the package.
- Related ticket: https://progress.opensuse.org/issues/186915
- Verification run: https://openqa.suse.de/tests/18994405#step/slem_basic/38
NOTES:
- The above job was cloned with `PUBLIC_CLOUD_INSTANCE_TYPE=i3.large MACHINE=ec2_i3.large`
- Full list of Xen instances available at https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-types.html

Implement Xen package test for SLEM

---

lib/sles4sap/qesap/qesapdeployment.pm
t/09_qesapdeployment.t

Related: https://jira.suse.com/browse/TEAM-10562
VR: https://openqa.suse.de/tests/18992373#downloads  (file name: deploy_qesap_ansible-iscsi0-y2logs.tar.gz)
https://openqa.suse.de/tests/18992372#downloads

Collect and upload y2logs from iscsi server in cloud

---

tests/yam/agama/generate_dud.pm

- Related ticket: https://progress.opensuse.org/issues/188052
- [Verification runs]( https://openqa.suse.de/tests/overview?arch=&flavor=&machine=&test=sles_generate_dud_rk&modules=&module_re=&group_glob=&not_group_glob=&comment=&distri=sle&version=16.0&build=133.4&groupid=585#) (done on my dev group as a proof of concept for another ticket)

Fix problems with generate_dud

---

tests/containers/charts/rmt.pm

Fail faster if the rmt app is not started.
- Related failure: https://duck-norris.qe.suse.de/tests/14952
- Verification run: https://duck-norris.qe.suse.de/tests/14956 (passing because [those changes](https://gitlab.suse.de/qac/qac-openqa-yaml/-/merge_requests/2419))

Add check for rmt to be healthy

---

schedule/qam/16/agama_install_sles4sap_increment.yaml
schedule/qam/16/create_hdd_ha_textmode_increment.yaml

Related: https://jira.suse.com/browse/TEAM-10602
VR: https://openqa.suse.de/tests/overview?distri=sle&version=15.99&build=7.7&groupid=569

Enable SAP and HA SLES16 increment test

---

tests/fips/fips_setup.pm

Ticket: https://openqa.suse.de/tests/19015567
VR: https://progress.opensuse.org/issues/187632
Related MR: https://gitlab.suse.de/qe-security/openqa-data/-/merge_requests/506

Install openssl-3 on s390x FIPS

---

tests/qam-updinstall/SLFO_update_install.pm

- Related ticket: https://progress.opensuse.org/issues/187116 https://openqa.suse.de/tests/19016745
- Verification run: https://openqa.suse.de/tests/overview?distri=sle&version=15.99&build=%3A306%3Abash&groupid=656&flavor=Online-Updates-Staging-Install

SLFO_update_install: Add conflict

---

tests/elemental/container_validation.pm

The real-time OS image test sporadically fails because of timeout during the OS build. Increase some timeouts to fix this issue.
- Failing test: https://openqa.suse.de/tests/19028285
- Verification run: https://openqa.suse.de/tests/19029369

Fix Elemental2 RT test

---

lib/apachetest.pm
tests/console/apache_ssl.pm
tests/console/journald_fss.pm
tests/security/vsftpd/lftp.pm

Just speed up tests
- Verification run: https://openqa.suse.de/tests/overview?distri=sle&build=jpupava_ssl

apache_ssl: Use serial terminal

---

data/yam/agama/auto/lib/scripts_post.libsonnet
data/yam/agama/auto/template.libsonnet
lib/serial_terminal.pm
schedule/yam/agama_minimal_unattended.yaml
schedule/yam/agama_minimal_unattended_s390x.yaml
tests/yam/validate/validate_minimal_system.pm

##
- Related ticket: https://progress.opensuse.org/issues/184942
- Related MR: https://gitlab.suse.de/qe-yam/openqa-job-groups/-/merge_requests/564
- Needles: N/A
- [**sles_minimal_unattended**](https://openqa.suse.de/tests/overview?arch=&flavor=&machine=&test=sles_minimal_unattended_dev&modules=&module_re=&group_glob=&not_group_glob=&comment=&distri=sle&version=16.0&build=135.1&groupid=318#)
##

Create unattended installation with onlyRequired packages

---

schedule/security/fips/sle16/agama_remote_s390x_install_fips_ker_mode.yaml

- Related ticket: https://progress.opensuse.org/issues/186125
- Verification run: https://openqa.suse.de/tests/19137339

Add test for agama FIPS ker mode installation on s390x

---

tests/console/sudo.pm

- Related ticket: https://openqa.suse.de/tests/19138463#step/sudo/1 repeating a lot
- Verification run: https://openqa.suse.de/tests/overview?distri=sle&version=15.99&build=jpupava_sudo

sudo: Wait before typing after switching user

---

schedule/security/fips/fips_env_mode_textmode_core-15-SP4-maint.yaml

YAML for Security 15-SP4 maintenance
- Related ticket: https://progress.opensuse.org/issues/136199
- Verification run: https://openqa.suse.de/tests/19144281

Create separate YAML schedule for SLE 15-SP4

---

lib/mr_test_lib.pm

VR: https://openqa.suse.de/tests/19181537#

Import 'is_pvm_hmc' when call it

---

data/yam/autoyast/ha_s390x.xml

Detail refer to https://suse.slack.com/archives/C092PJ7EML1/p1758184479472939
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/19207206#details

Add cio_ignore=false to ha_s390x.xml

---

lib/security/vendoraffirmation.pm
out
test_known_issues.json
tests/fips/fips_setup.pm
tests/security/verify_fips_packages.pm

Ticket: https://progress.opensuse.org/issues/181331
VRs:
* 15-SP7-VA: https://openqa.suse.de/tests/overview?distri=sle&version=15-SP7&build=20250922-1&groupid=431
* 15-SP4 maint: https://openqa.suse.de/tests/19189335

Refactor Vendor Affirmation and add support for 15-SP7

---

tests/containers/docker_compose.pm
tests/containers/python_runtime.pm

Add missing jq dependency.
Failing test: https://openqa.opensuse.org/tests/5341699#step/docker_compose/203

Add missing jq dependency

---

lib/containers/bats.pm
tests/containers/bats/aardvark.pm
tests/containers/bats/buildah.pm
tests/containers/bats/netavark.pm
tests/containers/bats/podman.pm
tests/containers/bats/runc.pm
tests/containers/bats/skopeo.pm

bats: Require jq

---

tests/virt_autotest/verify_virtualization.pm
tests/yam/validate/validate_migration_logs.pm

* **Add** bootloader checking for virtualization.
* **Check** other non-fatal errors in ```validate_migration_logs.pm```.
*  [virtualization host upgrade](https://openqa.suse.de/tests/19207003)
* [migration 64bit](https://openqa.suse.de/tests/19207005)
* [migration uefi](https://openqa.suse.de/tests/19207004)

Add bootloader checking for virtualization

---

tests/xfstests/run_subtest.pm

Apply xfstests whitelist entries only in run_post_fail() method. Otherwise the test runner cannot handle test timeouts.
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/19240699

xfstests: Whitelist failures in post-fail hook

---

schedule/security/fips/sle16/fips_env_mode_powervm.yaml
schedule/security/fips/sle16/fips_sle16_powervm_hmc.yaml

- Related ticket: https://progress.opensuse.org/issues/183827
- Needles: n/a
- https://openqa.suse.de/tests/19263159
- https://openqa.suse.de/tests/19263160

Merge FIPS tests for ENV and KERN mode on SLE16 pvm_hmc

---

data/containers/bats/skip.yaml
tests/containers/bats/skopeo.pm

Add missing switch to user in skopeo test.
Populate the user ignore list due to https://github.com/containers/skopeo/issues/2718
- 15-SP4: https://openqa.suse.de/tests/19269448
- Tumbleweed: https://openqa.opensuse.org/tests/5355740

Run skopeo testsuite also as user

---

lib/sles4sap/azure_cli.pm
t/21_sles4sap_azure_cli.t

Use signatures, add query argument to get resource_group.
- Related ticket: Ticket: https://jira.suse.com/browse/TEAM-10607
- sle-15-SP7-SapCloud-Azure-Byos-x86_64-BuildLATEST_AZURE_SLE15_7-ipaddr2_azure_test@64bit -> http://openqaworker15.qa.suse.cz/tests/344796

Use signature for azure_cli function

---

tests/qam-updinstall/SLFO_update_install.pm
tests/qam-updinstall/update_install.pm

- Related ticket: https://progress.opensuse.org/issues/189183
- Verification run: https://openqa.suse.de/tests/overview?build=jpupava_ui_m&distri=sle&test=qam-incidentinstall

update_install: Fix issues and add new code

---

tests/kernel/run_kselftests.pm

- https://openqa.suse.de/tests/19270263#step/run_kselftests/2781 (**before**)
- https://openqa.suse.de/tests/19272076#step/run_kselftests/2780 (**after**)

Kselftests: Chomp @tests

---

data/autoyast_sle15/autoyast_txtmode_btrfs_luks2.xml
schedule/security/autoyast_btrfs_luks2.yaml
schedule/security/sle16/agama_luks2.yaml
tests/security/luks2/unlock_luks2_vol_tpm2.pm

Ticket: https://progress.opensuse.org/issues/183299
VRs:
- 16.0: https://openqa.suse.de/tests/overview?distri=sle&version=16.0&build=135.5&groupid=431
- 15.7: https://openqa.suse.de/tests/overview?distri=sle&version=15-SP7&build=20251001-1&groupid=431
- 15.4: https://openqa.suse.de/tests/overview?distri=sle&version=15-SP4&build=20251001-1&groupid=431
Related MR: https://gitlab.suse.de/qe-security/openqa-data/-/merge_requests/520

Add unlock_luks2_volume_with_tpm2 on SLE16

---

data/autoyast_qam/15_installtest.xml.ep

```
- Add comments to make the modules selection "better"
- Add module-multi-linux-manage-client-tools
- Remove SAP Business One & transactional-server from SLED
- Replace tabs with spaces on systems-management part
```
- Related ticket: https://suse.slack.com/archives/C02CLB8TZP1/p1759413371023779
- Verification run: https://openqa.suse.de/tests/19275753#step/repos/5

Update installtest SLE 15 ay profile

---

tests/containers/bats/buildah.pm

Add [conformance tests](https://github.com/containers/buildah/tree/main/tests/conformance) on Tumbleweed.
These upstream tests compare that `buildah` generate identical output to `docker build` (both BuildKit & buildx).
Verification runs (ran with `BATS_IGNORE_ROOT=all BATS_IGNORE_USER=all` to skip bats tests):
- with crun: https://openqa.opensuse.org/tests/5362318
- with runc: https://openqa.opensuse.org/tests/5362294

bats/buildah: Add conformance tests on Tumbleweed

---

tests/publiccloud/aws_cli.pm
tests/publiccloud/azure_cli.pm

Ticket : https://progress.opensuse.org/issues/187806
VRs : https://openqa.suse.de/tests/19300022#step/azure_cli/32
https://openqa.suse.de/tests/19300156

Skip PC module enablement for SLE 16

---

lib/publiccloud/instance.pm

Add `-o ConnectTimeout` to `$instance->ssh_opts`.
* Verification run: https://pdostal-server.suse.cz/tests/10815

PC: Add ConnectTimeout to ssh_opts

---

tests/console/libgcrypt.pm

Also speed up test by using serial terminal instead of console
- Related ticket: https://progress.opensuse.org/issues/189081
- Needles: no
- aarch64 https://openqa.suse.de/tests/19310862#step/libgcrypt/1
- x86_64 https://openqa.suse.de/tests/19310919#step/libgcrypt/1

Make sure test user has permission to access serial console
