os-autoinst/os-autoinst-distri-opensuse

- tests/xfstests/partition.pm
- variables.md
1. remove XFSTESTS_BIG_SPACE parameter
2. set each device size in MB, separate with commas
3. Each size is allocated to test_dev, scratch_dev1 and so on in turn
4. E.g XFSTESTS_PART_SIZE=5120,10240 then test_dev=5120M, scratch_dev1=10240M, and remain partitions share the rest space. Or set the size for all devices at once, values exceeding the number of devices have no effect.
- Related ticket: https://progress.opensuse.org/issues/167012
- Needles: N/A
http://10.67.133.133/tests/823 (no XFSTESTS_PART_SIZE parameter)
http://10.67.133.133/tests/822 (XFSTESTS_PART_SIZE=5120,10240,6100,6200,6300,6400,6500)
http://10.67.133.133/tests/821 (XFSTESTS_PART_SIZE=5120,10240,5100,5200,5300,5400)
http://10.67.133.133/tests/820 (XFSTESTS_PART_SIZE=10240) …
> xfstests: Add XFSTESTS_PART_SIZE parameter

- tests/publiccloud/check_registercloudguest.pm
We have a list of manual steps which are executed to verify [cloud-regionsrv-client](https://github.com/SUSE-Enceladus/cloud-regionsrv-client/tree/master). The steps can be found here: https://github.com/SUSE-Enceladus/cloud-regionsrv-client/blob/master/integration_test-process.txt
Our existing automated tests did not cover all of the steps listed so this PR aims to remedy that.
**This PR:**
- Adds missing steps to the test module.
- Removes duplicate imports (e.g. `use version_utils 'is_sle';`)
- Defines a few new functions. These are used to retain the existing logical flow of the test while adding some extra steps along the way.
- Swaps piped commands for simpler (imo) options. e.g. `ls /etc/zypp/credentials.d/ | wc -l` vs `ls -A /etc/zypp/credentials.d/`.
- Adds steps to verify …
> Cloudregistration test module improvements

- schedule/qam/common/mau-extratests1.yaml
- tests/console/velociraptor_client_event_collect.pm
Related ticket:
Needles: NO
SLE15SP6
x86_64   https://openqa.suse.de/tests/15622971
aarch64 https://openqa.suse.de/tests/15622972
s390x     https://openqa.suse.de/tests/15622973
SLE15SP5
x86_64   https://openqa.suse.de/tests/15622974
aarch64 https://openqa.suse.de/tests/15622965
s390x     https://openqa.suse.de/tests/15622975
SLE15SP4
x86_64   https://openqa.suse.de/tests/15622976
aarch64 https://openqa.suse.de/tests/15622964
s390x    https://openqa.suse.de/tests/15622977
> velociraptor test cleanup

- tests/containers/runc_integration.pm
Since https://github.com/opencontainers/runc/commit/f76489f0afe680f227a67c703f234f6c2d4357e8 all helpers changed directory.
- Related ticket: https://bugzilla.opensuse.org/show_bug.cgi?id=1230234
- Failing test: https://openqa.opensuse.org/tests/4541669
- Verification run: https://openqa.opensuse.org/tests/4543726
> containers: Add new directory for runc test helpers

- tests/containers/runc_integration.pm
Use a more robust way to find runc test helpers, as we may get `*` if either `contrib/cmd` or `tests/cmd` is empty.
- Verification run: https://openqa.suse.de/tests/15635581
> containers: Use a robust way to find runc test helpers

- data/microos/butane/script
- lib/main_micro_alp.pm
- tests/microos/verify_setup.pm
- Related ticket: https://progress.opensuse.org/issues/164341
- Verification run: https://openqa.opensuse.org/tests/4544698
Changes:
- Loads the verify_setup test for microos.
- Excludes mkfs.ext4 unit test if tumbleweed or microos as they don't have this file system.
- Changes butane script to mount /home if tumbleweed to fix user tests.
> Enable verify_setup testmodule for MicroOS

- data/sles4sap/qe_sap_deployment/qesap_aws.yaml
- data/sles4sap/qe_sap_deployment/qesap_aws_fencing.yaml
- data/sles4sap/qe_sap_deployment/qesap_aws_sapconf.yaml
- data/sles4sap/qe_sap_deployment/qesap_azure.yaml
- data/sles4sap/qe_sap_deployment/qesap_azure_fencing_msi.yaml
- data/sles4sap/qe_sap_deployment/qesap_azure_fencing_spn.yaml
- data/sles4sap/qe_sap_deployment/qesap_azure_roles.yaml
- data/sles4sap/qe_sap_deployment/qesap_azure_sapconf.yaml
- data/sles4sap/qe_sap_deployment/qesap_azure_sapconf_no_reg.yaml
- data/sles4sap/qe_sap_deployment/qesap_azure_uri.yaml
- data/sles4sap/qe_sap_deployment/qesap_gcp.yaml
- data/sles4sap/qe_sap_deployment/qesap_gcp_fencing.yaml
- data/sles4sap/qe_sap_deployment/qesap_gcp_sapconf.yaml
All the conf.yaml for all qesap regression test use value HQ0. This value is the same across all qesap regression openQA  tests and it is different from the `HDB` one that combine with `HDB` hardcoded in some cluster resource names within the qe-sap-deployment Ansible code, resulting in name having it twice.
- Related ticket: https://jira.suse.com/browse/TEAM-9426
- sle-12-SP5-Qesap-Aws-Byos-x86_64-BuildLATEST_AWS_SLE12_5_BYOS-qesap_aws_saptune_test -> http://openqaworker15.qa.suse.cz/tests/299496 :green_circle: 
- sle-15-SP6-Qesap-Aws-Byos-x86_64-BuildLATEST_AWS_SLE15_6_BYOS-qesap_aws_fencing_native_test -> http://openqaworker15.qa.suse.cz/tests/299497 :green_circle: 
- sle-15-SP6-Qesap-Aws-Byos-x86_64-BuildLATEST_AWS_SLE15_6_BYOS-qesap_aws_fencing_sbd_test -> …
> Use same sap_hana_install_sid in qesap regression

- tests/publiccloud/check_registercloudguest.pm
A bug was introduced with some of the container logic in this pr: https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/20260. SP2 to SP4 do not have `podman` in the default repos. SP5 and onwards do.
I've bumped the version on the check that runs the container logic.
- Failed tests: https://openqa.suse.de/tests/15636752#step/check_registercloudguest/163 
- Verification run: http://dirtman.qe.prg2.suse.org/tests/91#
> Fix SLE15-SP3,SP4 broken podman test

- data/virt_autotest/setup_dns_service.sh
- products/sle/main.pm
- tests/virt_autotest/setup_dns_service.pm
Related ticket: https://progress.opensuse.org/issues/167569
- Wait until guests get an IP
- Remove `lsb_release` command in test script, because
- the lsb_release package was not installed by unknown reasons
- it is useless to get the SLE version any more
- Fix typo
- Add a few debug lines
- Run reset_partition.pm for prj1 tests only
[sriov_pci_passthrough-guest_developing_fv-on-host_developing-xen](https://openqa.suse.de/tests/15562349)
[sriov_pci_passthrough-guest_sles15sp6_fv-on-host_developing-xen](https://10.145.10.207/tests/15562370)
[gi-guest_developing-on-host_developing-kvm](https://10.145.10.207/tests/15562329)
[gi-guest_win2022-on-host_developing-xen](https://10.145.10.207/tests/15562333)
> Wait until guest get IP in setup_dns

- lib/containers/urls.pm
- lib/main_containers.pm
- tests/containers/podman_bci_systemd.pm
- tests/containers/podman_pods.pm
- tests/containers/privileged_mode.pm
- tests/containers/skopeo.pm
Update container URLs to make the container test runs work on RISC-V.
- Related ticket: https://progress.opensuse.org/issues/166589
- Verification run: [TW RISC-V](https://openqa.opensuse.org/tests/4530538) | [TW x86_64](https://openqa.opensuse.org/tests/4530770) | [SLEM 6.0](https://openqa.suse.de/tests/15590591)
> Add container test runs for RISC-V

- lib/Yam/Agama/Pom/RebootPage.pm
- schedule/yam/agama_auto_gnome.yaml
- tests/yam/agama/agama_auto.pm
- tests/yam/agama/switch_to_product.pm
##
- Related ticket:  https://progress.opensuse.org/issues/167060
- Needles: `first_boot-displaymanager-20241009`
-  [**20_cases**](https://openqa.opensuse.org/tests/overview?arch=x86_64&flavor=&machine=&test=&modules=&module_re=&group_glob=&not_group_glob=&comment=&build=hjluo&version=agama-9.0&distri=opensuse#)
> Move cursor during Agama auto installation

- tests/xfstests/run_subtest.pm
Add bugzilla source into run_subtest to solve the problem that "undefined subroutine &xfstests_utils::bugzilla_buginfo".
- Related ticket: https://progress.opensuse.org/issues/167842
- Verification run: https://openqa.suse.de/tests/15647194
(prove bugzilla message works https://openqa.suse.de/tests/15647194#step/generic-363/83)
> xfstests: Fix missing source of bugzilla function

- tests/installation/start_install.pm
Sometimes it can take more time until startinstall pop-up show
- Related ticket: https://openqa.suse.de/tests/15647143#step/start_install/1
> start_install: Increase timeout

- data/network_bonding/dnsmasq.conf
- data/network_bonding/kea-dhcp4.conf
- lib/network_utils.pm
- lib/registration.pm
- schedule/functional/extra_tests_network_bonding.yaml
- schedule/microos/bonding.yaml
- tests/console/suseconnect_scc.pm
- tests/network/network_bonding.pm
- tests/network/network_bonding_setup.pm
The new code allows to test IEEE 802.3ad Dynamic link aggregation, adaptive load balancing (balanced-alb) and transmit load balancing (balanced-tlb) modes. Multimachine setup excludes possible bugs related to WAN connection. 
- Related ticket: [https://progress.opensuse.org/issues/153217](https://progress.opensuse.org/issues/153217)
* https://openqa.opensuse.org/tests/overview?arch=&flavor=&machine=&test=network-bonding-target&modules=&module_re=&group_glob=&not_group_glob=&comment=&distri=opensuse&version=Tumbleweed&groupid=38&build=20240930#
* https://openqa.opensuse.org/tests/overview?groupid=38&build=20241007&distri=microos&version=Tumbleweed
* https://openqa.suse.de/tests/overview?groupid=552&build=21.3&version=6.1&distri=sle-micro
* …
> Universal network bonding test

- data/journal_check/bug_refs.json
[1230970](https://bugzilla.suse.com/show_bug.cgi?id=1230970) pam_wtmpdb(login:session): Cannot get ID from open session
[1231391](https://bugzilla.suse.com/show_bug.cgi?id=1231391) Cannot create/open database (/var/lib/wtmpdb/wtmp.db): unable to open database file
[1231455](https://bugzilla.suse.com/show_bug.cgi?id=1231455) systemd[1]: Failed to start SETroubleshoot daemon....
https://openqa.suse.de/tests/15647694
https://openqa.suse.de/tests/15647695
> Add soft-failures for some SL Micro SELinux related bugs

- tests/sles4sap/publiccloud/azure_fence_agents_test.pm
Allow same secret overwrite mechanism already in use in qesap_terraform.
- Related ticket: https://jira.suse.com/browse/TEAM-9719
- sle-15-SP6-HanaSr-Azure-Byos-x86_64-Build15-SP6_2024-10-11T02:03:21Z-hanasr_azure_test_saptune_spn az_Standard_E4s_v3 -> http://openqaworker15.qa.suse.cz/tests/299680 
- sle-15-SP6-HanaSr-Azure-Byos-x86_64-Build15-SP6_2024-10-11T02:03:21Z-hanasr_azure_test_saptune_spn az_Standard_E4s_v3 -> http://openqaworker15.qa.suse.cz/tests/299681 :green_circle:  properly detect wrong credential http://openqaworker15.qa.suse.cz/tests/299681#step/Verify_azure_fence_agent_SPN/98 `Application with identifier 'banana' was not found in the directory ...`
- sle-15-SP6-HanaSr-Azure-Byos-x86_64-Build15-SP6_2024-10-11T02:03:21Z-hanasr_azure_test_saptune_spn az_Standard_E4s_v3 -> …
> Allow SPN secret overwrite in azure_fence_agent

- tests/containers/privileged_mode.pm
- tests/installation/bootloader_svirt.pm
USBPV functionality is about to be added by
https://github.com/os-autoinst/os-autoinst/pull/2552.
Hence we can check whether `/dev` devices are accessible in priviledge containers.
I have also added a 2 more checks for syscalls availability and more about accessibility of kernel file systems.
- ticket: https://progress.opensuse.org/issues/138410
* [sle-15-SP7-JeOS-for-kvm-and-xen-x86_64-Build1.40-jeos-containers-podman@svirt-xen-pv](http://kepler.suse.cz/tests/24054#step/podman_privileged_mode/42)
* [sle-15-SP7-JeOS-for-kvm-and-xen-x86_64-Build1.40-jeos-containers-podman@svirt-xen-hvm](http://kepler.suse.cz/tests/24055#step/podman_privileged_mode/42)
> Test access to usb device from a container

- lib/main_micro_alp.pm
Verify_setup is working correctly for Tumbleweed-MicroOS-Image with combustion as initial configuration but not with ignition.
Temporarily disable verify_setup for ignition test as initial configuration. 
- Related ticket: https://progress.opensuse.org/issues/164341
verify_setup should be present in all except **microos with ignition** -->
sle-micro with combustion: https://openqa.suse.de/tests/15657610
sle-micro with ignition: https://openqa.suse.de/tests/15657611
microos with combustion: https://openqa.opensuse.org/tests/4552809
microos with ignition: https://openqa.opensuse.org/tests/4552810
> Temporarily disable verify_setup for ignition test as initial configuration.

- tests/console/check_default_network_manager.pm
With systemd 256, `networkctl status` no longer returns 0 when systemd-networkd is disabled/inactive.  I checked this behaviour in Ubuntu 24.10 which ships Systemd 256.  
- Related ticket: https://progress.opensuse.org/issues/164652
> Remove assert for networkctl status when networkd is inactive

- lib/klp.pm
- lib/main_ltp.pm
- tests/kernel/boot_ltp.pm
- tests/kernel/install_ltp.pm
- tests/kernel/update_kernel.pm
This change introduces support for SLE Micro 6.0 and newer. There is a
difference in the live patching setup compared to previous
versions. Unlike SLE or SLE Micro 5.x, there is no additional live
patching product. Live patches are now part of the main repository.
The testing logic has also changed. There are no maintenance
incidents, as updates are tested in stagings. The staging repository
is represented by the variable `OS_TEST_REPOS`, which is the same for
other staging tests and is not specific to live patching. Kernel and
live patches tested in staging repositories contain `stage` in their
names and have a `99999` version.
- Staging H: https://openqa.suse.de/tests/overview?groupid=562&distri=sle-micro&version=6.0&build=H.34.1 (manually set to …
> Add support for kernel livepatching on SL Micro 6.0+

- tests/virt_autotest/reboot_and_wait_up.pm
* **Previously** pressing enter key is only enabled on xen host, which is also needed on kvm host now as well. Because linux login prompt may be overwritten by messages pop up on ipmi sol console.
* **Failure** example, [failure 1](https://openqa.suse.de/tests/15645634#step/reboot_and_wait_up_upgrade/20).
* [offline upgrade kvm](https://openqa.suse.de/tests/15647573)
* [offline upgrade xen](https://openqa.suse.de/tests/15647563)
* [online upgrade kvm](https://openqa.suse.de/tests/15647570)
* [online upgrade xen](https://openqa.suse.de/tests/15647568)
> Bring linux-login prompt back by pressing enter

- data/gdb/test2.c
- tests/console/gdb.pm
gcc14 has become stricter towards multi-character constants. This commit adds a (char*) cast to avoid compilation errors.
- Related ticket: https://progress.opensuse.org/issues/165896
- Verification run: [Tumbleweed](https://duck-norris.qe.suse.de/tests/14811) | [15-SP6](https://openqa.suse.de/tests/15689883) | [15-SP5](https://openqa.suse.de/tests/15689884) | [15-SP4](https://openqa.suse.de/tests/15689885) | [15-SP3](https://openqa.suse.de/tests/15689886) | [15-SP2](https://openqa.suse.de/tests/15689887) | [12-SP5](https://openqa.suse.de/tests/15689891)
> Fix string type

- tests/installation/logs_from_installation_system.pm
- tests/virt_autotest/host_upgrade_step2_run.pm
It is not necessary to execute set_pxe_efiboot.
System can boot into system normally, not pxe boot any more.
- Related ticket: https://progress.opensuse.org/issues/168019
- Needles: na
- https://openqa.oqa.prg2.suse.org/tests/15646742
- https://openqa.oqa.prg2.suse.org/tests/15656589
> Delete unnecessary pxe boot setting

- lib/security/openssl_misc_utils.pm
To address the lack of legacy module on SLE RT, and test the libopenssl1.1 we do a workaround and manually install only the binary from the legacy repository
- Related ticket: https://progress.opensuse.org/issues/167764
- Needles: no
- https://openqa.suse.de/tests/15692744
- https://openqa.suse.de/tests/15699448
> Install openssl1.1 binary when legacy module isn't available

- tests/publiccloud/transfer_repos.pm
Single quotes in Perl have the same meaning as in shell -- use string as is which leads to incorrect command and of course results
VR: https://openqa.suse.de/tests/15701295
> [PublicCloud] Fix reposize string in transfer_repos

- tests/ha/setup_hosts_and_luns.pm
Cluster tests on `svirt` and `pvm_hmc` backends rely on a directory created on a NFS share, where nodes can share information regarding node's IP addresses, iSCSI LUNs and other details. This is implemented in:
https://github.com/os-autoinst/os-autoinst-distri-opensuse/blob/master/tests/ha/setup_hosts_and_luns.pm#L43
This means that if running 2 sets of cluster tests at the same time, on the same build, same version and same architecture on either of these 2 backends, it can lead to a race condition if both clusters have the same `CLUSTER_NAME` setting. This is currently happening on the pre-release job group which has 2 HANA clusters (one testing `SAPHanaSR` resources, and the other testing `SAPHanaSR-angi` resources) running on `ppc64le-hmc-sap` workers both with setting `CLUSTER_NAME: …
> Add `_angi` to shared directory name when testing HanaSR angi

- lib/Distribution/Sle/AgamaDevel.pm
- lib/Yam/Agama/Pom/GrubMenuSlesPage.pm
- Related ticket: [poo#167470](https://progress.opensuse.org/issues/167470)
- Needles: 
+ enter-passphrase-for-root-partition-20241015.json:    "enter-passphrase-for-root-partition"  
+ enter-passphrase-for-root-partition-x86_64-20241015.json:    "enter-passphrase-for-root-partition"
+ enter-passphrase-for-swap-partition-20241015.json:    "enter-passphrase-for-swap-partition"
- Verification run: [overview](https://openqa.suse.de/tests/overview?build=build-issues-167470)
> Agama: enable installation for full encryption on SLES

- lib/publiccloud/utils.pm
- tests/publiccloud/download_repos.pm
- tests/publiccloud/transfer_repos.pm
https://progress.opensuse.org/issues/163397
Add support for Products Increments in PC tests
VR: 1) http://quasar.suse.cz/tests/179
2) http://quasar.suse.cz/tests/180
> [PublicCloud] Skip validate repo on SLEM 6+

- tests/yam/agama/agama.pm
We want to include a small workaround to install `ca-certificates-suse` package in Agama Live s390x ISO.
- Related ticket: https://progress.opensuse.org/issues/167248
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/15672986
> Agama s390x ca-certificates-s390x workaround

- tests/x11/toolkits/fltk.pm
Use desktop runner to refresh screen to make sure the expected needle can show correctly.
- Related ticket: https://progress.opensuse.org/issues/167320
- Verification run: https://openqa.suse.de/tests/15710657#next_previous (Rerun ten times cannot reproduce this sporadic issue.)
x86_64: https://openqa.suse.de/tests/15711009#
aarch64: https://openqa.suse.de/tests/15711023#
> Use desktop runner to refresh screen

- tests/yam/agama/agama.pm
Minor fix of method import in Agama test
- Related ticket: https://progress.opensuse.org/issues/167248
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/15711106
> Fix method import in Agama default test

- tests/microos/toolbox.pm
Explicitly set `fatal => 0` so that on failures the test runs continues. This is needed because on ppc64le snapshotting is disabled by default for PowerPC and this causes `fatal => 1` to be assumed by default.
- Related failure: https://openqa.suse.de/tests/15539149#step/toolbox/1
- Verification run: https://openqa.suse.de/tests/15711120
> Do not stop on failures in toolbox test runs

- lib/xfstests_utils.pm
- tests/xfstests/run.pm
- tests/xfstests/run_subtest.pm
After resetting the system, if it directly goes into the login screen, we do not need to wait to match the grub page in wait_boot. To fix poo#167347.
- Related ticket: https://progress.opensuse.org/issues/167347 and https://progress.opensuse.org/issues/162884
1. https://openqa.suse.de/tests/15700091#step/xfs-009/38
Checkpoint: to check if xfs/009 keep running and pass after xfs/008 crashed(test fail is expected), compare with previous fail https://openqa.suse.de/tests/15640564#step/xfs-009/1.
2. https://openqa.suse.de/tests/15700624#step/generic-300/2 (these test need to set QEMU_DISABLE_SNAPSHOTS=0 because it has QEMU_DISABLE_SNAPSHOTS=1 before), compare with previous fail https://openqa.suse.de/tests/15640463#step/generic-300/1
3. Verification run for nfs case: …
> xfstests: Fix match grub failed after reset

- lib/sles4sap/ipaddr2.pm
- t/22_ipaddr2.t
- tests/sles4sap/ipaddr2/configure.pm
- tests/sles4sap/ipaddr2/deploy.pm
- tests/sles4sap/ipaddr2/destroy.pm
- tests/sles4sap/ipaddr2/sanity.pm
- tests/sles4sap/ipaddr2/test_move_resource.pm
Rename function for infrastructure deploy and destroy to follow a
pattern like: <LIB>_<OBJECT>_<ACTION>
- Related ticket: TEAM-8721
- sle-15-SP5-SapCloud-Azure-Payg-x86_64-BuildLATEST_AZURE_SLE15_5_PAYG-ipaddr2_azure_test@64bit -> http://openqaworker15.qa.suse.cz/tests/300236 :green_book:
> Rename ipaddr2 lib functions about deployment

- tests/sles4sap/publiccloud/qesap_ansible.pm
- tests/sles4sap/publiccloud/qesap_terraform.pm
- tests/sles4sap/qesapdeployment/deploy.pm
Function `qesap_az_setup_native_fencing_permissions` is used to create
and assign the permission to resource, so we only need to do this for
MSI cases when using Azure fence agent.
Related: https://jira.suse.com/browse/TEAM-9699
VRs:
Azure-SAP-PAYG:
SAPHanaSR-ScaleUp-PerfOpt-spn@az_Standard_E4s_v3: https://openqa.suse.de/tests/15710747# (Passed)
SAPHanaSR-ScaleUp-PerfOpt-msi@az_Standard_E4s_v3: https://openqa.suse.de/tests/15710746# (Passed)
Azure-SAP-BYOS:
SAPHanaSR-ScaleUp-PerfOpt-msi@az_Standard_E4s_v3: https://openqa.suse.de/tests/15710741# (Passed)
SAPHanaSR-ScaleUp-PerfOpt-spn@az_Standard_E4s_v3: https://openqa.suse.de/tests/15710745# (Passed)
> Only create and assign permission for MSI

- lib/publiccloud/utils.pm
in the case 'policycoreutils-python-utils' are already  installed previous code will fail the test with:
```
Change expected: 1, happened: 0 at
sle-micro/products/sle-micro/../../lib/transactional.pm line 147.
```
which is wrong and unrelated to the test, so this change behaviour is to check if there is a change and reboot the system if there is as needed on the transactional system
poo: https://progress.opensuse.org/issues/168406
VR: http://quasar.suse.cz/tests/182
> Don't except always changes of snapshot in allow_openqa_port_selinux

- lib/virt_autotest/hyperv_utils.pm
- tests/console/system_prepare.pm
- tests/installation/bootloader_hyperv.pm
- tests/installation/reboot_after_installation.pm
- tests/installation/scc_registration.pm
- tests/shutdown/hyperv_upload_assets.pm
Check for Hyper-V 2016 with UEFI, configure VM network adapter, and log related soft failure.
1. Added hyperv_utils.pm for Hyper-V command execution.
2. Disable network card when create VM, record soft failure. (module: [bootloader_hyperv](https://openqa.oqa.prg2.suse.org/tests/15702722#step/bootloader_hyperv/29))
3. Enable network card when scc registration, record soft failure (module: 
[scc_registration](https://openqa.oqa.prg2.suse.org/tests/15702722#step/scc_registration/4))
4. Disable network card when the first boot, record soft failure (module: [reboot_after_installation](https://openqa.oqa.prg2.suse.org/tests/15702722#step/reboot_after_installation/5))
5. Enable network card when function test, record soft failure (module: …
> Check for Hyper-V 2016 with UEFI, configure VM network adapter, and log related soft failure.

- schedule/jeos/sle/jeos-main.yaml
- schedule/staging/cryptlvm_minimal_x@64bit-staging.yaml
- schedule/staging/gnome@64bit-staging.yaml
- schedule/staging/minimal+base@64bit-staging.yaml
https://progress.opensuse.org/issues/87982
- [Verification run](http://openqa.suse.de/tests/overview?distri=sle&build=rfan1021_new)
**Please ignore the failed test module, it is known issue**
> Schedule salt smoke test on SLE staging

- lib/Distribution/Opensuse/AgamaDevel.pm
- lib/Distribution/Opensuse/Leap/16Latest.pm
- lib/Distribution/Sle/16Latest.pm
- lib/Yam/Agama/Pom/GrubEntryEditionPage.pm
- lib/Yam/Agama/Pom/GrubMenuBaseBug1231658Page.pm
- Related ticket: https://progress.opensuse.org/issues/168205
- Needles: N/A
openSUSE leap: https://openqa.opensuse.org/tests/overview?build=lemon-suse%2Fos-autoinst-distri-opensuse%23debug-leap-agama-issue&version=16.0&distri=opensuse
openSUSE devel: https://openqa.opensuse.org/tests/overview?version=agama-9.0&distri=opensuse&build=lemon-suse%2Fos-autoinst-distri-opensuse%23debug-leap-agama-issue
SLES 16.0 devel: https://openqa.suse.de/tests/overview?build=lemon-suse%2Fos-autoinst-distri-opensuse%23debug-leap-agama-issue&distri=sle&version=agama-10.0
SLES 16.0 : https://openqa.suse.de/tests/overview?version=16.0&distri=sle&build=lemon-suse%2Fos-autoinst-distri-opensuse%23debug-leap-agama-issue
> Set boot parameter 'console' on grub2 entry after installation for Leap 16.0

- lib/main_publiccloud.pm
- lib/publiccloud/ssh_interactive.pm
- lib/xfstests_utils.pm
- tests/publiccloud/xfsprepare.pm
- tests/xfstests/run.pm
- tests/xfstests/run_subtest.pm
This patch set aims to increase robustness and decrease run times of XFS tests targeting Public Cloud SUTs. The main changes are that xfsprepare.pm may fail and therefore the job must stop at that point and the serial terminal is used without heartbeat so that run times are faster. Along with that, some minor fixes regarding typos and unused imports.
- Related ticket: https://progress.opensuse.org/issues/162791
http://rmarliere-openqa.qe.prg2.suse.org/tests/48
http://rmarliere-openqa.qe.prg2.suse.org/tests/55
https://openqa.suse.de/tests/15725420
https://openqa.suse.de/tests/15738773
> Improve Public Cloud XFS tests

- lib/sles4sap/ipaddr2.pm
- t/22_ipaddr2.t
- tests/sles4sap/ipaddr2/configure.pm
- tests/sles4sap/ipaddr2/sanity.pm
Code was using rootless cluster init and join mode by default. This mode is not supported in crmsh version delivered in 12sp5.
Change the code to add support for root mode:
1. Allow specifying user in function that generate ssh keys for the internal VMs. It allows calling it for root.
2. Change remote note syntax in cluster join command.
3. Add setting `IPADDR2_ROOTLESS` to control both.
https://jira.suse.com/browse/TEAM-9743
- http://openqaworker15.qa.suse.cz/tests/300340 :green_circle:  result in using root mode everywhere
- http://openqaworker15.qa.suse.cz/tests/300343 :green_circle: `crm cluster join` is now fine http://openqaworker15.qa.suse.cz/tests/300343#step/configure/191. Cluster is later not …
> Ipaddr2 cluster setup for 12sp5

- tests/containers/podman_integration.pm
We shouldn't install `pasta` if not available for obvious reasons.
This makes the [140-diff](https://github.com/containers/podman/blob/main/test/system/140-diff.bats) test to fail, so we're gonna add this to PODMAN_BATS_SKIP_USER_LOCAL & PODMAN_BATS_SKIP_USER_REMOTE.
- Verification run: https://openqa.suse.de/tests/15739973  (fails on 140-diff).
- Related MR: https://gitlab.suse.de/qac/qac-openqa-yaml/-/merge_requests/1872
> containers: Don't install pasta if not available

- data/yam/agama/auto/gnome_leap.json
- Related ticket: https://progress.opensuse.org/issues/168070
- Needles: N/A
- Verification run: https://openqa.opensuse.org/tests/4565336#
> Enable agama_auto_gnome for Leap 16.0

- tests/xfstests/run_subtest.pm
There are no known issues or Bugzilla messages for failed tests due to typos. Just correct it.
- Related ticket: https://progress.opensuse.org/issues/168274
- Needles: N/A
- Verification run: http://10.67.133.133/tests/827#step/btrfs-161/83
> xfstests: fix typo of known issue message

- data/virt_autotest/guest_params_xml_files/oracle_linux_8_10_graphical_server_x86_64.xml
- data/virt_autotest/guest_params_xml_files/oracle_linux_9_4_graphical_server_x86_64.xml
* **Oracle** Linux guest os version should match with major/minor version and version of actual medium to be used for guest installation.
* [verification run](https://openqa.suse.de/tests/15745220)
> Correct Oracle Linux guest os version

- lib/main_publiccloud.pm
- tests/publiccloud/ahb.pm
`ahb.pm` had internal logic to create an instance. `ahb.pm` was also loaded after we run `prepare_instance.pm` so the result would be two separate instances.
I have cleaned up the logic and have removed the instance creation part from `ahb.pm`.
- Related ticket: https://progress.opensuse.org/issues/168562
- Duplicate Instances (BEFORE): http://dirtman.qe.prg2.suse.org/tests/96
- Single Instance (AFTER): http://dirtman.qe.prg2.suse.org/tests/154
> bugfix: Stop AHB test module from creating a duplicate instance 

- lib/main_publiccloud.pm
Our existing AHB code had logic to create an instance by itself. As that logic is removed, we need to move the AHB test in a more suitable place that guarantees that an instance has been created.
- Related ticket: https://progress.opensuse.org/issues/168160
- Verification run: http://dirtman.qe.prg2.suse.org/tests/158#
> Execute AHB after creating an instance

- lib/main_publiccloud.pm
We want to run the **bsc_1205002.pm** test module for Latest builds. This change adds the necessary check and moves the BSC test after the instance is created with `prepare_instance.pm`.
- Related ticket: https://progress.opensuse.org/issues/168157
- Verification run: http://dirtman.qe.prg2.suse.org/tests/162#
> Enable bsc_1205002.pm for Latest builds

- tests/microos/image_checks.pm
For Leap Micro 5.4+ aarch64 builds, there is an 1M unpartitioned space that needs to be accounted for.
- Related ticket: https://progress.opensuse.org/issues/127118
- Verification run: https://openqa.opensuse.org/tests/4586017#step/image_checks/10 (it fails for other reasons, but the image_checks module now passes)
> microos/image_checks: Expect unpartitioned 2048 sectors at disk start

- tests/fips/openssh/openssh_fips.pm
Extend FIPS mode ssh client test for Tumbleweed 
- Related ticket: https://progress.opensuse.org/issues/163196
- Needles: no
- Verification run: https://openqa.opensuse.org/tests/4566538
> Ensure sshd installed before testing openssh client

- tests/jeos/firstrun.pm
- type: GMC validation test fix
Pre-installed cockpit package changes the workflow of jeos-firstboot as
it offers the user to configure OTP. This package is present only in
Default flavors of sle-micro 6.1+.
- failure: https://openqa.suse.de/tests/15756136#step/firstrun/13
- sle-micro-6.1-Base-qcow-x86_64-Build24.3-default@uefi-virtio-vga -> https://openqa.suse.de/tests/15757000
- sle-micro-6.1-Default-qcow-x86_64-Build24.3-default@uefi-virtio-vga -> https://openqa.suse.de/tests/15757001
> [fix] Cockpit is pre-installed in Default flavors only

- lib/registration.pm
Make sure that 12-SP5 hosts that we are using for container testing are deployed with LTSS module. In addition we also need to include the 'LTSS Extended Security' product (that's a different product than LTSS). LTSS on 12-sp5 will be officially released on 1.11.2024
- Related ticket: https://progress.opensuse.org/issues/166295
- Verification run: http://pherranz-openqa.qe.suse.de/tests/48
> Add LTSS in sle 12-SP5 to maintenance test runs

- tests/jeos/firstrun.pm
- type: test fix
Size of serial console is too small to fit generated QR code with
additional text information. In this case jeos-firstboot offers an user
to show the QR code in isolated view.
This PR is skip the extra button that offers to generate QR in ttyS0.
- related bug: https://bugzilla.suse.com/show_bug.cgi?id=1231177
- Verification run: [sle-micro-6.1-Default-qcow-s390x-Build24.3-default@s390x-kvm](https://openqa.suse.de/tests/15757230)
> Skip QR generator in serial console

- tests/microos/image_checks.pm
- type: test fix
Unpartition space is reported only in raw aarch64 images. Qcow2 images do not report any leftover sectors.
- failure: https://openqa.suse.de/tests/15757120#step/image_checks/10
- sle-micro-6.0-Default-qcow-Updates-Staging-aarch64-BuildO.37.5-slem_image_default@aarch64 -> https://openqa.suse.de/tests/15757280
- sle-micro-5.5-Default-Updates-aarch64-Build20241022-1-slem_image_default@aarch64 -> https://openqa.suse.de/tests/15757281
- sle-micro-6.1-Default-qcow-aarch64-Build24.3-default@aarch64 -> https://openqa.suse.de/tests/15757282
- sle-micro-6.1-Default-qcow-x86_64-Build24.3-combustion@uefi-virtio-vga -> https://openqa.suse.de/tests/15757283
- sle-micro-6.1-Default-aarch64-Build24.3-combustion@aarch64 -> https://openqa.suse.de/tests/15757284
> Only raw aarch64 have leftover sectors

- lib/sles4sap_publiccloud.pm
- t/11_hacluster.t
- t/12_sles4sap_publicccloud.t
- tests/publiccloud/sles4sap.pm
Harmonization of resource names for SAP HANA SR clusters
Must be merged togather with https://github.com/SUSE/qe-sap-deployment/pull/287
- https://openqaworker15.qa.suse.cz/tests/300016 - PASSED
- https://openqaworker15.qa.suse.cz/tests/300017 - PASSED
- https://openqaworker15.qa.suse.cz/tests/300018 - PASSED
- https://openqaworker15.qa.suse.cz/tests/299517 - PASSED
- https://openqaworker15.qa.suse.cz/tests/299518 - PASSED
- https://openqaworker15.qa.suse.cz/tests/299519 - PASSED
> Harmonization of resource names for SAP HANA SR clusters

- data/virt_autotest/guest_params_xml_files/sles_12_sp5_64_kvm_hvm_uefi_with_power_management_x86_64.xml
- data/virt_autotest/guest_params_xml_files/sles_12_sp5_64_xen_hvm_uefi_with_power_management_x86_64.xml
Related ticket: https://progress.opensuse.org/issues/166187
Related PRs:
https://github.com/SUSE/qa-automation/pull/843
https://gitlab.suse.de/qa-testsuites/openqa-job-group-yaml/-/merge_requests/212
[uefi-gi-guest_sles12sp5-on-host_developing-kvm](https://10.145.10.207/tests/15755206)
[uefi-gi-guest_developing-on-host_sles12sp5-kvm](https://10.145.10.207/tests/15754988)
[uefi-gi-guest_sles12sp5-on-host_developing-xen](https://10.145.10.207/tests/15757184)   
[prj4_guest_upgrade_sles12sp5_on_sles12sp5-xen](https://10.145.10.207/tests/15754985)
[prj4_guest_upgrade_sles12sp5_on_sles12sp5-kvm](https://10.145.10.207/tests/15756628)  
[gi-guest_developing-on-host_sles12sp5-kvm](https://10.145.10.207/tests/15754962)
[gi-guest_developing-on-host_sles12sp5-kvm](https://10.145.10 …
> Sle12sp5 guests enter LTSS

- lib/main_micro_alp.pm
- tests/console/salt.pm
https://progress.opensuse.org/issues/87982
[regression](http://openqa.suse.de/tests/15745342#)
[microos](https://openqa.opensuse.org/tests/4584834)
Skip the sle-micro test due to  https://bugzilla.suse.com/show_bug.cgi?id=1231882
> Schedule salt smoke tests on micro-os

- tests/containers/bci_prepare.pm
The go dependency was never needed and the postgresql dependency became obsolete with BCI-Tests switching from psycopg2 to pg8000. This commit removes those two dependencies.
- Related PR: https://github.com/SUSE/BCI-tests/pull/621
- [sle-Centos-Container-Host-x86_64-BuildGM-update_centos@64bit](https://openqa.suse.de/tests/15757564)
- [sle-Ubuntu-Container-Host-x86_64-BuildGM-update_ubuntu@64bit](https://openqa.suse.de/tests/15757565)
- [sle-mls9-Container-Host-x86_64-BuildGM-update_mls9@64bit](https://openqa.suse.de/tests/15757566)
- [sle-micro-5.5-Container-Image-Updates-x86_64-BuildGM-update_slem@64bit](https://openqa.suse.de/tests/15757567)
- [sle-micro-5.5-Container-Image-Updates-aarch64-BuildGM-update_slem@aarch64-virtio](https://openqa.suse.de/tests/15757568)
- …
> Remove unnecessary dependencies

- lib/hacluster.pm
- tests/ha/migrate_clvmd_to_lvmlockd.pm
During SLES+HA migration tests from 12 to 15, test code needs to deal with any `clvmd` resources configured in the cluster, as `clvmd` was available in SLES 12, but not in SLES 15. This is handled by the `ha/migrate_clvmd_to_lvmlockd` test module, which will check for `clvmd` resources in the cluster, and if they are present, will perform the necessary steps to remove the `clvmd` resource and configure in its place a `lvmlockd` resource, applying also the required changes to the LVM configuration.
Starting with the `crmsh` version available in 15-SP7, the commands to remove `clvmd` are failing as now `crmsh` reports more cases of deprecated resources and deprecated attributes syntax; it also requires a confirmation due to these warnings. The request for confirmation is making the test …
> Ignore crmsh deprecation messages when migrating from 12-SP5

- data/virtualization/autoyast/guest_12.xml.ep
- data/virtualization/autoyast/host_12.xml.ep
- lib/main_common.pm
- lib/virt_autotest/common.pm
- tests/virtualization/universal/patch_guests.pm
- tests/virtualization/universal/prepare_guests.pm
Variable EXTENDED_SECURITY is set automatically if INCIDENT_REPO conatins ltts or ltss_se repo. No need for new test suites or job groups to run tests.
- Related ticket: https://progress.opensuse.org/issues/165243
- Needles: N/A
LTSS:
XEN Migration => http://openqa.qam.suse.cz/tests/81030#dependencies
KVM Migration => http://openqa.qam.suse.cz/tests/81032#dependencies
XEN           => http://openqa.qam.suse.cz/tests/81045
KVM           => http://openqa.qam.suse.cz/tests/81021
HyperV        => https://openqa.suse.de/tests/15732313
VMware        => https://openqa.suse.de/tests/15732314
LTSS_ES:
XEN Migration => http://openqa.qam.suse.cz/tests/81028#dependencies
KVM Migration => http://openqa.qam.suse.cz/tests/81025#dependencies
XEN           => …
> Enable 12sp5 ltss and ltss_es virt tests

- lib/sles4sap/ipaddr2.pm
socat is needed for the healthprobe of the load balancer. Ensure it is always installed. 12sp5 does not have it installed by default.
- Related ticket: TEAM-8721
-  http://openqaworker15.qa.suse.cz/tests/300672 :red_circle: something is calling `az group delete` during the nginx installation.
-  http://openqaworker15.qa.suse.cz/tests/300675 :green_circle:
sle-15-SP5-SapCloud-Azure-Payg-x86_64-BuildLATEST_AZURE_SLE15_5_PAYG-ipaddr2_azure_test_cloud_init
- http://openqaworker15.qa.suse.cz/tests/300673 :green_circle: 
sle-12-SP5-SapCloud-Azure-Payg-x86_64-BuildLATEST_AZURE_SLE12_5_PAYG-ipaddr2_azure_test
- http://openqaworker15.qa.suse.cz/tests/300674 :red_circle: cloud-init fails to install socat
``` …
```
> Ensure socat is installed

- lib/main_micro_alp.pm
- type: Factory staging blocker
- failure: https://openqa.opensuse.org/tests/4591384
Skip salt smoke test in staging testing as the salt packages are missing in staging test assets.
- microos-Staging:M-Staging-MicroOS-Image-sdboot-x86_64-BuildM.83.4-microos-wizard-tpm@uefi-staging -> https://openqa.opensuse.org/tests/4591486
> Skip salt test in staging

- lib/Yam/Agama/Pom/GrubEntryEditionPage.pm
- Related ticket: [poo#168205](https://progress.opensuse.org/issues/168205)
- Verification run: https://openqa.suse.de/tests/overview?build=jknphy%2Fos-autoinst-distri-opensuse%23slowtype&distri=sle&version=16.0
> Pass max_interval to GrubEntryEditionPage

- tests/security/atsec/check_processor_vulnerability_mitigations.pm
The check is ignored on all CPUs except 64bit Intel.
Related ticket: https://progress.opensuse.org/issues/168697
- 15-SP3: https://openqa.suse.de/tests/15770794
- 15-SP4: https://openqa.suse.de/tests/15770798
- 15-SP4@uefi: https://openqa.suse.de/tests/15770800
- 15-SP5: https://openqa.suse.de/tests/15770801
- 15-SP5@uefi: https://openqa.suse.de/tests/15770802
> Whitelist CVE-2023-20569 check for cc_atsec

- lib/hacluster.pm
Running 'crm report' will generate a compress file, we need to get the correct file name to upload it.
Related: https://jira.suse.com/browse/TEAM-9765
VRs:
https://openqa.suse.de/tests/15764743#step/check_logs/13  (Upload tar.bz2 successfully)
https://openqa.suse.de/tests/15764740#step/check_logs/13  (Upload tar.gz successfully)
> Fix the upload file name for crm report

- tests/x11/vnc_two_passwords.pm
https://progress.opensuse.org/issues/168520
- Verification run: [VR](http://openqa.suse.de/tests/15781448#next_previous)
> Fix screen match issue on vnc_two_passwords

- tests/fips/fips_setup.pm
- Related ticket: https://progress.opensuse.org/issues/168700
- Needles: n/a
- https://openqa.suse.de/tests/15782850
- https://openqa.suse.de/tests/15782864
> Use correct casing for FIPS environment var

- tests/containers/bci_prepare.pm
Recent changes in the BCI-Tests allows us to also remove the python3-devel dependency.
- Related ticket: https://progress.opensuse.org/issues/168706
- [sle-Centos-Container-Host-x86_64-BuildGM-update_centos@64bit](https://openqa.suse.de/tests/15782685)
- [sle-Ubuntu-Container-Host-x86_64-BuildGM-update_ubuntu@64bit](https://openqa.suse.de/tests/15782686)
- [sle-mls9-Container-Host-x86_64-BuildGM-update_mls9@64bit](https://openqa.suse.de/tests/15782687)
- [sle-Leap15.6-Container-Host-x86_64-BuildGM-update_leap@64bit](https://openqa.suse.de/tests/15782688)
- [sle-micro-5.5-Container-Image-Updates-x86_64-BuildGM-update_slem@64bit](https://openqa.suse.de/tests/15782689)
- [sle-micro-5.5-Container-Image-Updates-s390x-BuildGM-update_slem@s390x-kvm](https://openqa.suse.de/tests/15782690)
- …
> Remove more dependencies from BCI

- tests/fips/openssh/openssh_fips.pm
Verify if is openssh is installed, in case of SLE 15 SP2 package name differs 
Related ticket: https://progress.opensuse.org/issues/168904
Verification runs: 
-  15SP2: https://openqa.suse.de/tests/15772935#step/openssh_fips/17
-  15SP4: https://openqa.suse.de/tests/15772934#step/openssh_fips/17
> Is openssh installed on 15SP2

- tests/publiccloud/nvidia.pm
The patch_and_reboot test module that usually comes before this one might already have installed a NVIDIA driver. Add the check to prevent errors in the conflict resolution step. Also, make the conflict explicit by uninstalling the non-CUDA package.
- Related ticket: https://progress.opensuse.org/issues/163736
- Verification run: http://rmarliere-openqa.qe.prg2.suse.org/tests/150
> publiccloud/nvidia: Check if driver is already installed

- tests/sles4sap/publiccloud/qesap_prevalidate.pm
PR #20469 introduced a cluster check in `tests/sles4sap/publiccloud/qesap_prevalidate` to make sure we have a healthy cluster right after the deployment. It does this by calling `lib/sles4sap_publiccloud::wait_for_cluster()`, which relies on the cloud instance where the cluster is checked to be stored in `$self->{my_instance}`.
However, this was added after a loop that cycles through all the deployed cloud instances, and in the case of SBD, this includes the iSCSI server which is not a member of the cluster. Due to the way Perl orders lists within hashes, it can happen that the iSCSI server is the last entry in this list, leaving it stored in `$self->{my_instance}` and causing `$self->wait_for_cluster()` to fail as the commands are not run in a member of the cluster.
This commits works …
> Ensure we run $self->wait_for_cluster in a cluster node

- schedule/security/audit.yaml
Only test those two modules on SLE, where we still have audit < 4.
- Related ticket: https://progress.opensuse.org/issues/167662
- Needles: N/A
- Verification run: N/A (removal of test module on TW)
> security/audit: autrace was dropped with audit 4

- data/journal_check/bug_refs.json
- bsc#1231391 also happens in SLE Micro 6.1
- VR: https://openqa.suse.de/tests/15801541
> Quickfix for journal_check

- tests/containers/privileged_mode.pm
Limit Docker-in-Docker to x86_64 and aarch64 because the image is only available there.
- Related failure: https://openqa.suse.de/tests/15807461#step/docker_privileged_mode/109
* https://openqa.suse.de/tests/15809497
* https://openqa.suse.de/tests/15809500
> Quickfix: Limit DinD to x86_64 and aarch64

- lib/containers/bats.pm
- tests/containers/buildah_integration.pm
Do not install pasta to make some tests pass.
- Related ticket: https://bugzilla.suse.com/show_bug.cgi?id=1232522
- Related MR: https://gitlab.suse.de/qac/qac-openqa-yaml/-/merge_requests/1898
- Verification runs (expected failures as we harvest them for the MR):
-  sle-15-SP7-Online-x86_64-Build32.2-buildah_testsuite@64bit -> https://openqa.suse.de/tests/15809232
- sle-15-SP6-Server-DVD-Updates-x86_64-Build20241029-1-buildah_testsuite@64bit -> https://openqa.suse.de/tests/15809233
- sle-15-SP5-Server-DVD-Updates-x86_64-Build20241029-1-buildah_testsuite@64bit -> https://openqa.suse.de/tests/15809234
- sle-15-SP4-Server-DVD-Updates-x86_64-Build20241029-1-buildah_testsuite@64bit -> https://openqa.suse.de/tests/15809235
> Revert "containers: Install pasta from upstream for buildah upstream tests"

- tests/microos/one_line_checks.pm
When setting timezone to central Europe, the test need to count with a time shift possibility hence instead of CEST `date` command returns CET.
- failure: https://openqa.suse.de/tests/15800060#step/one_line_checks/3
- Verification run: http://kepler.suse.cz/tests/24076#step/one_line_checks/1
> Timeshift in prague's timezone

- tests/microos/image_checks.pm
The image check unpartitioned space is 4062 at selfinstall flavor aarch64 platform
- Related ticket: https://progress.opensuse.org/issues/169084
- Verification run: https://openqa.suse.de/tests/15810642
> The image check unpartitioned space is 4062 at selfinstall flavor

- lib/bootloader_setup.pm
- lib/main_micro_alp.pm
Due to https://bugzilla.suse.com/show_bug.cgi?id=1229336 the `console=` parameters are gone, jeos-firstboot wizard shows in ttyS0 instead of tty.
We need to inject these parameters at boottime and bring back the grub2 handler module. -> https://src.suse.de/products/SL-Micro/pulls/59/files
- [failure](https://openqa.suse.de/tests/15590388#step/firstrun/6)
* [sle-micro-6.1-Base-aarch64-Build21.3-default@aarch64](https://openqa.suse.de/tests/15598772)
* [slem6.1](http://kepler.suse.cz/tests/24038#step/bootloader_uefi/5)
* [microos-Tumbleweed-DVD-x86_64-Build20241002-microos-sdboot@uefi-2G](http://kepler.suse.cz/tests/24033#step/bootloader_uefi/5)
* [opensuse-Tumbleweed-DVD-x86_64-Build20241002-create_hdd_textmode_uefi@uefi](http://kepler.suse.cz/tests/24034#step/bootloader_uefi/6)
* …
> Inject console parameters in GRUB2

- lib/main_micro_alp.pm
In jeos-firstboot test cases the bootloader_uefi module was loaded wrongly even systemd-boot was used.
- microos- Tumbleweed-MicroOS-Image-sdboot-x86_64-Build20241029-microos-wizard@uefi -> https://openqa.opensuse.org/tests/4606687
- microos-Tumbleweed-MicroOS-Image-sdboot-x86_64-Build20241029-microos-wizard-tpm@uefi -> https://openqa.opensuse.org/tests/4606689
> Fix schedule of booloader_uefi

- lib/bootloader_setup.pm
- tests/installation/bootloader_uefi.pm
In order to locate kernel paramaters, the test needs to skip additional
modules in case of encrypted images.
The grub2 menu takes longer to appear in case of encrypted images
- ticket: https://progress.opensuse.org/issues/169126
- [sle-micro-6.1-Base-RT-encrypted](https://openqa.suse.de/tests/15817612#step/bootloader_uefi/5)
- [sle-micro-6.1-Default-encrypted](https://openqa.suse.de/tests/15818317#step/bootloader_uefi/5)
- [sle-micro-6.0-Default-encrypted-Updates-Staging](https://openqa.suse.de/tests/15818405#step/bootloader_uefi/5)
- [sle-micro-6.1-Base-encrypted](https://openqa.suse.de/tests/15818425#step/bootloader_uefi/5)
> Skip encryption related modules in grub2

- tests/containers/podman_netavark.pm
As a workaround for bugs [bsc#1222239](https://bugzilla.suse.com/show_bug.cgi?id=1222239) [bsc#1232450](https://bugzilla.suse.com/show_bug.cgi?id=1232450), save the default IPv6 before TEST3 execution and restore it immediately after. This way, connectivity is not lost and subsequent test modules in the schedule won't fail due to that.
Also, remove the obsolete call `sysctl -w net.ipv6.conf.all.disable_ipv6=0` in podman_netavark.
- Related ticket: https://progress.opensuse.org/issues/168451
- Verification run: http://rmarliere-openqa.qe.prg2.suse.org/tests/151
> containers/podman_netavark: Save and restore IPv6 route in hooks

- tests/security/audit/auditctl.pm
- tests/security/audit/ausearch.pm
Adding an audit rule for a system call on x86_64.
When the new rule is triggered by a simple 'ps' command the log line will include the arch.
The tool 'ausearch' can filter audit events by using the arch filter.
Related ticket: https://progress.opensuse.org/issues/169060
VRs:
15-SP2: https://openqa.suse.de/tests/15820139
15-SP3: https://openqa.suse.de/tests/15820138
15-SP4: https://openqa.suse.de/tests/15820112
15-SP5: https://openqa.suse.de/tests/15820096
15-SP6: https://openqa.suse.de/tests/15820114
15-SP7: https://openqa.suse.de/tests/15820142
> Improve security audit log checks

- schedule/qam/common/mau-extratests1.yaml
They are now running on a development job group. https://openqa.suse.de/group_overview/616
> Remove velociraptor tests

- lib/xfstests_utils.pm
In xfstests_utils used a function in bugzilla library. But the `use bugzilla` is missing on the top. 
- Related ticket: https://progress.opensuse.org/issues/167842
- Verification run: https://openqa.suse.de/tests/15832520
> xfstests: Add a missing bugzilla library reference

- lib/migration.pm
Exclude `ltss_es` in function deregister_dropped_modules as `ltss` is not active.
Related ticket: [TEAM-9709](https://jira.suse.com/browse/TEAM-9709)
12-SP5 LTSS & LTSS Extended Security Setup - SLES+HA
- Verification run: https://openqa.suse.de/tests/15832771#dependencies (passed)
> Exclude ltss_es in deregister_dropped_modules

- data/yam/autoyast/autoyast_scc_up.xml
As https://suse.slack.com/archives/C02CLB2LB7Z/p1730470463015239, we need remove old settings from yam profiles and reserve 'timeout'.
- Needles: N/A
https://openqa.suse.de/tests/15846766  15SP4
https://openqa.suse.de/tests/15846769   15SP2
https://openqa.suse.de/tests/15846772   15SP3
> Clean old settings from yam profiles

- schedule/staging/ext4@uefi-staging.yaml
- Avoid that Grub is booting after a timeout by inserting `disable_grub_timeout` in the schedule. 
This solves the "blackout" in `handle_reboot`.
- Verification run: https://openqa.suse.de/tests/15846844#
> Quickfix for staging blackout

- tests/ha/rear_restore.pm
Reverts os-autoinst/os-autoinst-distri-opensuse#20479
Current tests in ppc64le are still failing:
* https://openqa.suse.de/tests/15821667#step/rear_restore/8
* https://openqa.suse.de/tests/15821670#step/rear_restore/10
And now x86_64 tests are also failing:
* https://openqa.suse.de/tests/15822639#step/rear_restore/8
* https://openqa.suse.de/tests/15822641#step/rear_restore/8
> Revert "Rear restore"

- data/yam/autoyast/support_images/sled_install_all_patterns.xml
- data/yam/autoyast/support_images/sled_install_default_patterns.xml
- Related ticket: [poo#165737](https://progress.opensuse.org/issues/165737)
+ flavor [Server-DVD-Updates](https://openqa.suse.de/tests/overview?distri=sle&groupid=529&flavor=Server-DVD-Updates)
+ flavor [Migration-from-SLE15-SPx](https://openqa.suse.de/tests/overview?distri=sle&groupid=529&flavor=Migration-from-SLE15-SPx)
+ flavor [Migration-from-SLE15-SPx-Milestone](https://openqa.suse.de/tests/overview?distri=sle&groupid=529&flavor=Migration-from-SLE15-SPx-Milestone)
- Related `openqa-job-groups` [MR#352](https://gitlab.suse.de/qe-yam/openqa-job-groups/-/merge_requests/352): to be merge after current PR
> Add migration testsuites for SLED15SP6 to SLED15SP7: AUTOYAST files

- lib/containers/k8s.pm
Install k3s-selinux on Tumbleweed before installing k3s
- Related ticket: https://progress.opensuse.org/issues/168577
- Verification run: https://openqa.opensuse.org/tests/4620609
> containers: Install k3s-selinux on Tumbleweed before installing k3s

- tests/console/console_reboot.pm
##
- https://progress.opensuse.org/issues/167581
- Needles: 
- N/A 
-  https://openqa.suse.de/tests/15865111
> Adapt console_reboot testing for pvm

- tests/console/start_systemd_testkit_offline.pm
Add softfail for systemd-testkit version
- Related ticket: https://progress.opensuse.org/issues/167515
- Verification run: https://openqa.suse.de/tests/15832181#
> Add softfail for systemd-testkit version

- lib/registration.pm
- schedule/ha/qam/common/qam_ha_rolling_upgrade_migration_node01_sle12.yaml
- schedule/ha/qam/common/qam_ha_rolling_upgrade_migration_node02_sle12.yaml
- tests/migration/online_migration/register_ltss.pm
- tests/migration/online_migration/register_without_ltss.pm
Handle HA 12-SP4 LTSS to 12-SP5 LTSS Extended Security migration
TEAM-9709 - 12-SP5 LTSS & LTSS Extended Security Setup - SLES+HA
Aggregate Flavor `Server-DVD-HA-Updates-LTSS-ES` Settings: see https://openqa.suse.de/admin/products
- Related ticket: https://jira.suse.com/browse/TEAM-9709
- Verification run (LTSS-ES): 
https://openqa.suse.de/tests/15860001#step/register_system/39 (passed :green_circle: )(`qam_ha_rolling_update_node01`, `ltss_es`)
https://openqa.suse.de/tests/15859995#step/scc_registration/35 (passed :green_circle: )(`qam_create_hdd_ha_textmode`, `ltss_es`)
https://openqa.suse.de/tests/15860007#dependencies (passed :green_circle: )(`qam_alpha_cluster_01`, `ltss_es`)
https://openqa.suse.de/tests/15860005#dependencies (passed :green_circle: )(`ha_ctdb_node01`, `ltss_es`) …
> Handle HA 12-SP4 LTSS to 12-SP5 LTSS Extended Security migration

- data/autoyast_sle12/autoyast_sles4sap_saptune.xml.ep
Make sles4sap saptune single incidents tests to support LTSS and LTSS-ES
- Related ticket: https://jira.suse.com/browse/TEAM-9783
https://openqa.suse.de/tests/15865226#dependencies
https://openqa.suse.de/tests/15866681 (only SCC_REGCODE_LTSS)
https://openqa.suse.de/tests/15866701 (no SCC_REGCODE_LTSS and SCC_REGCODE_LTSS_ES)
> Make sles4sap saptune single incidents tests to support LTSS and LTSS-ES

- lib/containers/common.pm
https://progress.opensuse.org/issues/169339
[VR](http://openqa.suse.de/tests/overview?arch=&flavor=Server-DVD-Updates-TERADATA&machine=&test=&modules=&module_re=&group_glob=&not_group_glob=&comment=&distri=sle&version=15-SP4&build=rfan1105#)
https://gitlab.suse.de/qa-maintenance/qam-openqa-yml/-/merge_requests/801 The code change is to fix the issue caused by wicked tests product changes.
> Do not enable addons for sle15sp4 TERADATA

- lib/registration.pm
- lib/virt_autotest/utils.pm
Change sles12sp5 aarch64 test to LTSS
Progress ticket: https://progress.opensuse.org/issues/169222
Solution:
Add SCC_ADDONS ltss
Add new key: SCC_REGCODE_LTSS_12
Using VERSION_TO_INSTALL(12-SP5) when installing Bare Metal sles12SP5 LTSS.
Using GUEST_LIST(sles-12-sp5-64) when installing Guest sles12SP5 LTSS.
Related PR or MR:
[qa-automation](https://github.com/SUSE/qa-automation/pull/844)
[os-autoinst-distri-opensuse](https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/20501)
[openqa-job-group-yaml](https://gitlab.suse.de/qa-testsuites/openqa-job-group-yaml/-/merge_requests/213)
VR:
[Baremetal](http://openqa.qa2.suse.asia/tests/76579#step/scc_registration/22)
[Guest](http://openqa.qa2.suse.asia/tests/76579#step/scc_registration/22) Failure reason:[cannot connect dist .suse.de …
> Support sles12sp5 LTSS aarch64 test

- lib/main_containers.pm
Simplify the scheduling conditions of podman_network_cni, which appers to have grown out of proportions.
- Related ticket: https://progress.opensuse.org/issues/166589
* [MicroOS container-host](https://openqa.opensuse.org/tests/4622477)
* [Tumbleweed containers_host_podman](https://openqa.opensuse.org/tests/4622478)
* [SLES 15-SP6](https://openqa.suse.de/tests/15866398)
* [SLES 15-SP6 aarch64](https://openqa.suse.de/tests/15866399)
* [SLES 15-SP5](https://openqa.suse.de/tests/15866400)
* [SLES 15-SP4](https://openqa.suse.de/tests/15866387)
* [SLES 15-SP3](https://openqa.suse.de/tests/15866388)
* [SLES 15-SP2](https://openqa.suse.de/tests/15866389)
* [SLEM 5.5](https://openqa.suse.de/tests/15866390)
* [SLEM 5.4](https://openqa.suse.de/tests/15866391)
* [SLEM …
> Tidy podman_network_cni scheduling

- tests/network/wireguard.pm
Whilst testing with SELinux in enforcing mode in tumbleweed for bsc#1230118, we found that the wireguard test hangs at `ausearch -m avc -r` and exits the serial terminal.
This is because in case `ausearch -m avc -r` does not find any avcs, the return value is 1 and then the whole test fails and exits due to the pipefail.
This removes the pipefail call that caused the issue and also moves one newline around for an improvement in runtime.
- Related ticket: https://progress.opensuse.org/issues/168589
- Needles: N/A
- https://openqa.opensuse.org/tests/4624374
- https://openqa.opensuse.org/tests/4624375
cc @rfan1 
thanks @Vogtinator for the help :)
> Remove pipefail from wireguard test and improve test run time (poo#168589)

- lib/serial_terminal.pm
Remove unused `$prompt` var in `serial_terminal::select_serial_terminal`.
- Needles: No need for needles, it's functionally exact.
- Verification run: No need for VR, it's functionally exact.
> quickfix: unused $prompt on select_serial_terminal

- tests/yam/agama/boot_agama.pm
When scheduling the `boot_agama.pm` module without the `EXTRABOOTPARAMS` var, the test hangs forever.
The worker log shows:
```
[2024-11-07T03:50:37.837899+08:00] [debug] [pid:14113] ||| starting boot_agama tests/yam/agama/boot_agama.pm
Use of uninitialized value in concatenation (.) or string at sle/tests/yam/agama/boot_agama.pm line 41.
boot_agama::run(boot_agama=HASH(0x55f5c1931950)) called at /usr/lib/os-autoinst/basetest.pm line 352
eval {...} called at /usr/lib/os-autoinst/basetest.pm line 346
basetest::runtest(boot_agama=HASH(0x55f5c1931950)) called at /usr/lib/os-autoinst/autotest.pm line 415
eval {...} called at /usr/lib/os-autoinst/autotest.pm line 415
autotest::runalltests() called at /usr/lib/os-autoinst/autotest.pm line 272
eval {...} called at …
```
> fix: agama boot module fails when EXTRABOOTPRAMS is not set

- tests/hpc/ww4.pm
Workaround for the ww4 tests: disabling the proxySCC to pull the latest ww4 container from recent repository
- Related ticket: https://progress.opensuse.org/issues/168028
- Verification run: https://openqa.suse.de/tests/15874176
https://openqa.suse.de/tests/15874177
https://openqa.suse.de/tests/15874178
also without the SCC file:
https://openqa.suse.de/tests/15763450#step/ww4/110
> HPC: Disable proxySCC in WW4 test

- lib/transactional.pm
Wait more time at grub phase for svirt-vmware70 machine
- Related ticket: https://progress.opensuse.org/issues/169447
- Verification run: https://openqa.suse.de/tests/15874212#
> Wait more time at grub phase for svirt-vmware70 machine

- data/virt_autotest/host_unattended_installation_files/autoyast/dev_host_12.xml.ep
- data/virt_autotest/host_unattended_installation_files/autoyast/dev_host_15.xml.ep
* **User** should be allowed to turn registration off with autoyast. 
* **This** is not only for convenience purpose but also makes test execution with Beijing openQA more resilient due to upcoming disconnection from CC area and malfunctioning local registration server.
* [sles15sp7 kvm with registration](https://openqa.suse.de/tests/15832391) 
* [sles12sp5 xen with registration](https://openqa.suse.de/tests/15832390)
* [sles15sp7 kvm without registration](https://openqa.suse.de/tests/15865115) 
* [sles12sp5 xen without registration](https://openqa.suse.de/tests/15832469)
* [sles12sp5 host GUI with registration](https://openqa.suse.de/tests/15865158)
> User is allowed to turn registration off with autoyast

- tests/xfstests/install.pm
XFSTESTS_PACKAGES doesn't work for MicroOS, thus enable it.
- Related ticket: https://progress.opensuse.org/issues/168457
- Needles: N/A
https://openqa.suse.de/tests/15874255#step/install/55 (no XFSTESTS_PACKAGES)
https://openqa.suse.de/tests/15874348#step/install/59 (XFSTESTS_PACKAGES="btrfs-progs xfsprogs")
> xfstests: install dependency packages on MicroOS

- tests/transactional/install_updates.pm
- Related ticket: https://progress.opensuse.org/issues/168676
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/overview?build=lemon-suse%2Fos-autoinst-distri-opensuse%23fix-slem-6.0-repo&distri=sle-micro&version=6.0
The failure for un-partitioned sector issue on aarch64 is not related with this PR, I filed another PR for that https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/20583
Related MR: https://gitlab.suse.de/qe-yam/openqa-job-groups/-/merge_requests/365
> Skip update maintenance repo on base system

- lib/maintenance_smelt.pm
We are working with lower case which is correct, but channel name in smelt is all upper case, this should be workaround until it's fixed, one day.
- Related ticket: https://suse.slack.com/archives/C02CLB8TZP1/p1730783709126159
- Verification run: https://openqa.suse.de/tests/15890092#step/update_install/68
> Substite LTSS-ES channel name

- tests/hpc/spack_master.pm
- Related fail: https://openqa.suse.de/tests/15879444
15-SP3: https://openqa.suse.de/tests/overview?distri=sle&build=czerw%2Fos-autoinst-distri-opensuse%2320591&version=15-SP3
15-SP7: https://openqa.suse.de/tests/overview?build=czerw%2Fos-autoinst-distri-opensuse%2320591&distri=sle&version=15-SP7
> hpc: Define library path for mpich in 15-SP3 spack test

- lib/bootloader_setup.pm
- lib/opensusebasetest.pm
- schedule/jeos/sle/jeos12sp5-main.yaml
- tests/console/verify_efi_mok.pm
- tests/installation/bootloader_uefi.pm
These are the required modifications in order to add the jeos-nosb test scenario, defined as:
DISTRI=opensuse
VERSION=Tumbleweed
FLAVOR=JeOS-for-kvm-and-xen
ARCH=x86_64 
BOOT_HDD_IMAGE=1
CHECK_MOK_IMPORT=1
DESKTOP=textmode
DISABLE_SECUREBOOT=1
UEFI=1
Please check individual commit messages for more info.
- Related ticket: https://progress.opensuse.org/issues/95434
[Tumbleweed](https://openqa.opensuse.org/tests/4624423)
[Leap 15.5](https://openqa.opensuse.org/tests/4627194)
[Leap 15.6](https://openqa.opensuse.org/tests/4627193)
[12 SP5](https://openqa.suse.de/tests/15880206)
[15 SP2](https://openqa.suse.de/tests/15878392)
[15 SP3](https://openqa.suse.de/tests/15878393)
[15 SP4](https://openqa.suse.de/tests/15879453)
[15 SP5](https://openqa.suse.de/tests/15878396)
[15 …
> Enable MinimalVM x86_64 with SecureBoot disabled test scenario

- schedule/yam/test_cases/skip_registration.yaml
We want to revert the reduce of skip_registration due to some ppc64le modules are not compatible with the rest.
- Related ticket: https://progress.opensuse.org/issues/163280
- MR: IN PROGRESS
- Needles: N/A
- x86_64: https://openqa.suse.de/tests/15749857
- aarch64: https://openqa.suse.de/tests/15749859
- ppc64le: https://openqa.suse.de/tests/15749860
> Reduce yaml files for skip_registration

- tests/xfstests/partition.pm
several xfstests in o3/xfstests_nfs3-generic has been failing with 
```
+mount.nfs: config error at /etc/nfsmount.conf:1: ignoring line not in a section 
+mount.nfs: config error at /etc/nfsmount.conf:2: ignoring line not in a section 
```
so, adding the section name in nfsmount config file
- Related ticket: https://progress.opensuse.org/issues/168559
- Verification run: https://openqa.opensuse.org/tests/4627363#step/generic-029/19
> xfstests/partition.pm: add section name when configuring nfsmount.conf file

- lib/containers/urls.pm
- tests/containers/podman_bci_systemd.pm
- tests/containers/podman_pods.pm
- tests/containers/skopeo.pm
Undo the revert of https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/20381 and bring back https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/20223 with the necessary fixes.
https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/20223 updates container URLs to make the container test runs work on RISC-V. In addition the following fixes have been applied:
* PDB
- Related ticket: https://progress.opensuse.org/issues/166589
- [Tumbleweed JeOS RISC-V](https://openqa.opensuse.org/tests/4635009)
- [microos-Tumbleweed-DVD-x86_64-Build20241109-container-host@64bit](https://openqa.opensuse.org/tests/4635317)
- [microos-Tumbleweed-DVD-x86_64-Build20241109-fips-container-host@64bit](https://openqa.opensuse.org/tests/4635318)
- …
> Re-Add "Add container test runs for RISC-V"

- tests/containers/buildah.pm
Run buildah tests also as rootless.
- Related ticket: https://progress.opensuse.org/issues/169075
- opensuse-Tumbleweed-DVD-x86_64-Build20241109-containers_host_docker@64bit -> https://openqa.opensuse.org/tests/4635815
- opensuse-Tumbleweed-DVD-x86_64-Build20241109-containers_host_podman@64bit -> https://openqa.opensuse.org/tests/4635795
> containers: Run buildah tests also as user

- tests/console/verify_efi_mok.pm
This reverts commit 9e4c2938bbe7c82ada5eb98d493c2335be9a301b.
Reverting because of multiple failures, see e.g. https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/20568#issuecomment-2469904599 and https://openqa.suse.de/tests/15918435#step/verify_efi_mok/101
> Revert "verify_efi_mok: Fix unexpected SecureBoot state check"

- tests/xfstests/partition.pm
Fixes: 66c797f525 (xfstests/partition.pm: add section name when configuring nfsmount.conf)
- Related ticket: https://progress.opensuse.org/issues/168559
> xfstests/partition.pm: move record_info nfsmount.conf to correct place

- tests/kernel/install_ltp.pm
- Related fail: https://openqa.suse.de/tests/15920107#step/install_ltp/171
- Verification run:  https://openqa.suse.de/tests/overview?build=czerw%2Fos-autoinst-distri-opensuse%2320609&distri=sle-micro&version=6.0
> ltp: Add add Base-Kernel-RT flavors to ltp installation

- schedule/jeos/sle/jeos-main.yaml
- tests/console/verify_efi_mok.pm
Enable the aarch64 architecture for jeos-nosb, a basic scenario that runs with secure boot disabled.
- Related ticket: https://progress.opensuse.org/issues/95434
[15SP6](https://openqa.suse.de/tests/15919968)
[15SP5](https://openqa.suse.de/tests/15920026)
[15SP4](https://openqa.suse.de/tests/15920028)
[15SP3](https://openqa.suse.de/tests/15920029)
[15SP6](https://openqa.suse.de/tests/15919995) - Regular jeos-main with secure boot enabled
[Tumbleweed](https://openqa.opensuse.org/tests/4637587) - Regular aarch64_secureboot with secure boot enabled
[15SP4](https://openqa.suse.de/tests/15920654) - Pristine x86_64
> jeos-nosb: Enable aarch64

- tests/installation/agama.pm
- Adding slowroll caused that product selection button is no longer visible
- Ensure we're at the bottom before trying to click product select button
Test run: https://openqa.opensuse.org/tests/4637710#live
> agama: product select is visible only at the bottom page

- lib/y2_installbase.pm
- tests/installation/logs_from_installation_system.pm
##
-  https://progress.opensuse.org/issues/164934
- Needles: 
-  select_patterns-fips-certified-conflict-20241113
- [**select_patterns**](https://openqa.suse.de/tests/overview?version=15-SP7&distri=sle&build=hjluo%2Fos-autoinst-distri-opensuse%23remove_patterns)
##
> Remove unecessary patterns for ppc64le all patterns migration

- lib/mm_network.pm
NM changes happen at runtime and automatically restarting it just wastes time and introduces more options to fail without providing any benefit.
Related issue: https://progress.opensuse.org/issues/169531
- https://openqa.opensuse.org/tests/4635229
- https://openqa.opensuse.org/tests/4635230
> Do not automatically restart NM after static configuration

- tests/containers/buildah.pm
Remove soft-failure for bsc#1232522
Do NOT merge til buildah update is shipped to 15-SP3.
- Related ticket: https://bugzilla.suse.com/show_bug.cgi?id=1232522
- 15-SP4: https://openqa.suse.de/tests/15930515
- 15-SP3: TBD
> containers: Remove soft-failure for bsc#1232522

- schedule/jeos/sle/jeos12sp5-main.yaml
The test jeos-nosb needs this in order to disable Secure Boot in the firmware before executing the test modules.
- Related ticket: https://progress.opensuse.org/issues/95434
> schedule/jeos12sp5-main: Add bootloader_uefi to uefi-virtio-vga machine

- lib/sles4sap_publiccloud.pm
- t/12_sles4sap_publicccloud.t
- tests/sles4sap/publiccloud/hana_sr_takeover.pm
- tests/sles4sap/publiccloud/hana_sr_test_secondary.pm
In 'stop_hana', for the 'crash' test scenario, there's no need to run 'wait_for_ssh' because we already have 'wait_hana_node_up'.
This is a follow up of https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/20539.
- Related ticket: https://jira.suse.com/browse/TEAM-9823
msi:
https://openqaworker15.qa.suse.cz/tests/302517 (fail at different place)
https://openqaworker15.qa.suse.cz/tests/302518
https://openqaworker15.qa.suse.cz/tests/302519
https://openqaworker15.qa.suse.cz/tests/302520
sbd:
https://openqaworker15.qa.suse.cz/tests/302587 (fail at different place)
https://openqaworker15.qa.suse.cz/tests/302588
https://openqaworker15.qa.suse.cz/tests/302589
https://openqaworker15.qa.suse.cz/tests/302590
spn: …
> sles4sap/publiccloud: avoid extra 'wait_for_ssh' in 'stop_hana'

- tests/containers/buildah_integration.pm
Increase timeout for buildah_testsuite
- Failed test: https://openqa.suse.de/tests/15931784#step/buildah_integration/266
- Verification run: https://openqa.suse.de/tests/15932761
> containers: Increase timeout for buildah testsuite

- lib/sles4sap_publiccloud.pm
https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/20469 made the test module qesap_prevalidate abort tests earlier when there are failed resources actions in the cluster monitoring output.
This has uncovered a bug in 12-SP5 which is tracked in https://bugzilla.suse.com/show_bug.cgi?id=1233026.
This pr softfails 12sp5 cases, since the error is non-fatal and the bug is going to probably be low-prio, so that it doesn't block our tests.
- Related ticket: https://jira.suse.com/browse/TEAM-9820
12sp5, softfail: https://openqa.suse.de/tests/15932702
15, PASS: https://openqa.suse.de/tests/15932703
> Softfail prevalidation for 12sp5

- data/sles4sap/qe_sap_deployment/qesap_azure_ltss.yaml
- tests/sles4sap/qesapdeployment/configure.pm
Add conf.yaml and setting to manage LTSS in qesap regression for Azure.
- Related ticket: https://jira.suse.com/browse/TEAM-9835
sle-12-SP5-Qesap-Azure-Byos-x86_64-BuildLATEST_AZURE_SLE12_5_BYOS-qesap_azure_saptune_test
http://openqaworker15.qa.suse.cz/tests/302738
With  QESAP_CONFIG_FILE=qesap_azure_ltss.yaml SCC_REGCODE_LTSS=******  QESAPDEPLOY_SCC_LTSS_MODULE='SLES-LTSS/12.5/x86_64'
http://openqaworker15.qa.suse.cz/tests/302739 :green_circle:  --> this log is particularly important http://openqaworker15.qa.suse.cz/tests/302739/logfile?filename=deploy-ansible.registration.log.txt
sle-12-SP5-Qesap-Azure-Payg-x86_64-BuildLATEST_AZURE_SLE12_5_PAYG-qesap_azure_saptune_test With …
> Add files for LTSS in qesap regression

- tests/containers/buildah.pm
https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/20619 was merged before the update for buildah hit the repos.
- Related ticket: https://progress.opensuse.org/issues/169888
> Revert "containers: Remove soft-failure for bsc#1232522"

- lib/sles4sap/azure_cli.pm
- lib/sles4sap/sap_deployment_automation_framework/inventory_tools.pm
- lib/sles4sap/sap_deployment_automation_framework/naming_conventions.pm
- schedule/sles4sap/sap_deployment_automation_framework/test_hana_sr.yml
- t/21_sles4sap_azure_cli.t
- t/24_sdaf_naming_convention.t
- t/29_sdaf_inventory_tools.t
- tests/sles4sap/sap_deployment_automation_framework/connect_to_deployer.pm
- tests/sles4sap/sap_deployment_automation_framework/prepare_ssh_config.pm
This PR adds feature for existing SDAF test to create SSH config file on worker 
VM. Deployer VM is set as proxy jump host and this will allow SSH connection 
between worker VM and SUT by executin only one SSH command. It is a first step 
to use `lib/publiccloud` library without `lib/sles4sap/console_redirection.pm`.
- Related ticket: https://jira.suse.com/browse/TEAM-9793
- Verification run: https://openqaworker15.qa.suse.cz/tests/302700#step/prepare_ssh_config/113
> Create ssh config on worker VM

- lib/mm_network.pm
Reverts os-autoinst/os-autoinst-distri-opensuse#20592
it broke a lot of other tests. Of course it did. Why did I think this was not here to cover other issues?
> Revert "Do not automatically restart NM after static configuration"

- data/virt_autotest/guest_params_xml_files/sles_15_sp6_64_kvm_hvm_sev_es_x86_64.xml
- data/virt_autotest/guest_params_xml_files/sles_15_sp7_64_kvm_hvm_sev_es_x86_64.xml
* **Use** ovmf sev firmware ovmf-x86_64-sev.bin for SEV/ES guest.
* [ovmf sev firmware works with 15sp6 guest](https://openqa.suse.de/tests/15939406)
* [ovmf sev firmware works with 15sp7 guest](https://openqa.suse.de/tests/15939407)
> Use ovmf sev firmware for SEV/ES guest

- lib/y2_installbase.pm
##
- Related ticket: https://progress.opensuse.org/issues/164934
- Needles:
- on-pattern-wsl_base-20241115
- on-pattern-wsl_gui-20241115
- on-pattern-wsl_systemd-20241115
- on-pattern-fips-20241115
- select_patterns-fips-selected-20241115
- select_patterns-wsl_base-20241115
-  select_patterns-wsl_gui-20241115
-  select_patterns-wsl_systemd-20241115   
-  select_patterns-fips-20241115
-  https://openqa.suse.de/tests/15947315
- https://openqa.suse.de/tests/15947320
##
> Send_key home each time when deselect patterns

- lib/utils.pm
Increased timeout for nmcli device disconnect $dev 
- Related ticket: https://progress.opensuse.org/issues/169726
- Verification run: https://openqa.suse.de/tests/overview/?build=cedvid%2Fos-autoinst-distri-opensuse%2320634
> Increase timeout for nmcli device disconnect

- tests/kernel/update_kernel.pm
- Related ticket: https://progress.opensuse.org/issues/169942
- Needles: 
- Verification run:  https://openqa.suse.de/tests/15942681#step/update_kernel/30 (console is reconnected, failure is not related)
> ltp: Add reconnect_mgmt_console to prepare_kernel_base

- tests/iscsi/iscsi_client.pm
- related ticket: https://progress.opensuse.org/issues/169840
- Needles: Created 2 new needles so that the changed hotkeys match
- Verification run: )
- [SP6 MU that now passes](https://openqa.suse.de/tests/15952937)
- [SP5 MU that should not get broken by the changes](https://openqa.suse.de/tests/15952938)
New PR because [the first PR](https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/20654) still had some typos.
> Quick fix for iscsi_client on SP6 (final version)

- lib/sles4sap/console_redirection.pm
- lib/sles4sap/sap_deployment_automation_framework/basetest.pm
- lib/sles4sap/sap_deployment_automation_framework/deployment.pm
- t/19_console_redirection.t
- tests/sles4sap/sap_deployment_automation_framework/deploy_hanasr.pm
Fix SDAF Post fail hook not executed in case of playbook timeout 
- Handle this issue on post_fail_hook only
- Related ticket: https://jira.suse.com/browse/TEAM-9790 (TEAM-9790 - [SDAF][BUG] Post fail hook not executed in case of playbook timeout)
- Normal runs: https://openqaworker15.qa.suse.cz/tests/302633# :green_circle: (did not break anything)
- Failed on `playbook` timed out on purpose: 
https://openqaworker15.qa.suse.cz/tests/302634#step/deploy_hanasr/214 (ansible-playbook timed out)
https://openqaworker15.qa.suse.cz/tests/302634#step/deploy_hanasr/217 (executing post fail hook and terminate `playbook` process)
https://openqaworker15.qa.suse.cz/tests/302634#step/deploy_hanasr/457 (cleanup executed successfully and all resources destroyed)
- Failed on `other …
> Fix SDAF Post fail hook not executed when timeout

- lib/sles4sap_publiccloud.pm
- t/12_sles4sap_publicccloud.t
- tests/sles4sap/publiccloud/qesap_terraform.pm
- Related ticket: https://jira.suse.com/browse/TEAM-9839
No LTSS ADDON sle-12-SP5-HanaSr-Azure-Byos-x86_64-Build12-SP5_2024-11-12T03:03:21Z-hanasr_azure_test_sbd az_Standard_E4s_v3
- http://openqaworker15.qa.suse.cz/tests/302892 :green_circle: 
No LTSS ADDON  and also including https://github.com/SUSE/qe-sap-deployment/pull/295. sle-12-SP5-HanaSr-Azure-Byos-x86_64-Build12-SP5_2024-11-12T03:03:21Z-hanasr_azure_test_sbd az_Standard_E4s_v3
- http://openqaworker15.qa.suse.cz/tests/302982 :green_circle: 
SCC_ADDONS=ltss but no regcode  (expected to fails) sle-12-SP5-HanaSr-Azure-Byos-x86_64-Build12-SP5_2024-11-12T03:03:21Z-hanasr_azure_test_sbd az_Standard_E4s_v3
- http://openqaworker15.qa.suse.cz/tests/302992 :green_circle: 
- http://openqaworker15.qa.suse.cz/tests/303000
And this is with …
> LTSS registration in HanaSR test

- tests/containers/bci_test.pm
Skip kiwi containers on non SLE hosts
- Verification run:  [kiwi-sles-15-sp6](https://openqa.suse.de/tests/15963784), [kiwi-sles-16](https://openqa.suse.de/tests/15963782)
> Skip kiwi_10.1 on MLS

- schedule/functional/extra_tests_textmode.yaml
- tests/console/valkey.pm
Change redis to valkey in Factory
- Related ticket: https://progress.opensuse.org/issues/163208
- Verification run:  TW: https://openqa.opensuse.org/tests/4645042#
leap: https://openqa.opensuse.org/tests/4648558#   Don't change, keep redis testing.
> Change redis to valkey in Factory

- tests/boot/boot_from_pxe.pm
This commit introduces the setting **FORCE_INSTALL_FROM_MIRROR_HTTP**, which when set to true forces `boot/boot_from_pxe` to install the SUT from the URL contained in **MIRROR_HTTP** (grub boot `install=` argument) even when running in workers with a closer mirror.
Idea behind this is to allow workers to specify a combination of **PXE_PRODUCT_NAME** and **MIRROR_HTTP** settings which will lead to a proper installation of a product/build under test.
- Related ticket: https://progress.opensuse.org/issues/168811
- Needles: https://gitlab.suse.de/openqa/os-autoinst-needles-sles/-/commit/c8513bdf1ef36c7eb3f58c21c0de8b8b1de0f739
- Verification run: https://openqa.suse.de/tests/15963697 :green_circle: , https://openqa.suse.de/tests/15963698 :red_circle: (installation OK, failed later in …
> Add setting to force install from MIRROR_HTTP on PXE boot

- tests/sles4sap/wizard_hana_install.pm
There is a loop in the `sles4sap/wizard_hana_install` test module, which cycles until the `sap-product-installation` needle matches. On SUTs with only one disk, this is a good solution as it allows the test to continue faster, but on SUTs with more disks, it's possible that the dialog prompting the user to select the disk where HANA is going to be installed takes a few seconds to appear, which can cause the module to wrongly match with `sap-product-installation` which is the window behind the disk selection dialog.
This commit moves the `wait_still_screen` call from the end of the loop to the start of the same loop. Idea is that module will wait until screen settles before attempting to match either the disk selection dialog or the `sap-product-installation` needle, giving it more time to …
> Move wait_still_screen to the start of the loop

- tests/x11/evolution/evolution_prepare_servers.pm
dovecot23 package is fixed in the dovecot repo
ce38026a36ffc43f8bebf03c8e81e5686c603fe6
- Related ticket: https://progress.opensuse.org/issues/170035
- Verification run: https://openqa.suse.de/tests/15987474
> evolution_prepare_servers: Remove workaound module

- tests/containers/bci_test.pm
Consider the `TIMEOUT_SCALE` setting also when computing internal BCI timeouts.
This is needed for https://gitlab.suse.de/qac/qac-openqa-yaml/-/merge_requests/1939
- Follow-up of https://gitlab.suse.de/qac/qac-openqa-yaml/-/merge_requests/1933
- Verification run: https://openqa.suse.de/tests/15997734#live
> Use TIMEOUT_SCALE

- tests/ha/iscsi_client.pm
According to https://bugzilla.suse.com/show_bug.cgi?id=1231385#c9, the shortcut has been changed. So we need to adapt our test code.
Related: https://jira.suse.com/browse/TEAM-9833
VRs:
https://openqa.suse.de/tests/15997495#  (15-SP5 Passed)
https://openqa.suse.de/tests/15997469    (15-SP6 Updates passed)
https://openqa.suse.de/tests/15997628#step/iscsi_client/50   (15-SP7 failed in bsc#1233351)
https://openqa.suse.de/tests/15997752 (15-SP6 incidents Passwd)
> Change the shortcut for yast-iscsi-client

- lib/containers/common.pm
- lib/containers/docker.pm
- tests/containers/validate_btrfs.pm
- variables.md
Introduce OCI_RUNTIME to test different OCI runtimes.
- Related ticket: https://progress.opensuse.org/issues/169639
- TW: podman w/ `OCI_RUNTIME=runc` https://openqa.opensuse.org/tests/4664555
- TW: docker w/ `OCI_RUNTIME=crun` https://openqa.opensuse.org/tests/4664653
> containers: Introduce OCI_RUNTIME

- lib/ipmi_backend_utils.pm
- Related ticket: https://progress.opensuse.org/issues/167890
bare-metal5
[gi-guest_developing-on-host_developing-kvm](https://openqa.suse.de/tests/15947566#) PASS
[prj2_host_upgrade_sles15sp6_to_developing_kvm](https://openqa.suse.de/tests/15953728#) PASS
[prj4_guest_upgrade_sles15sp6_on_sles15sp6-kvm](https://openqa.suse.de/tests/15962881#) PASS
[gi-guest_developing-on-host_developing-xen](https://openqa.suse.de/tests/15953727#) Fail by [bsc#1233225](https://bugzilla.suse.com/show_bug.cgi?id=1233225)
bare-metal6
[prj4_guest_upgrade_sles15sp6_on_sles15sp6-kvm](https://openqa.suse.de/tests/15962880#) PASS
> virt_autotest: Set up the 2 new purchased machines in OSD as ipmi worker

- tests/x11/chrome.pm
Handle unlock login keyring window to fix chrome failure.
- Related ticket: https://progress.opensuse.org/issues/169810
- Needles: already added when debugging on O3
- Verification run: https://openqa.opensuse.org/tests/4665158
> Fix chrome failure since Chrome 131

- tests/x11/chromium.pm
Fix chromium failure since Chromium 131
- Related ticket: https://progress.opensuse.org/issues/169810
- Needles: already added when debugging on O3
- Verification run: https://openqa.opensuse.org/tests/4665733#details
> Fix chromium failure since Chromium 131

- tests/console/perl_bootloader.pm
Test was tweaked for SLE Micro <= 6.1 but Leap Micro was skipped. This is to fix openQA failures for Leap Micro 6.1 too.
Test run: https://openqa.opensuse.org/tests/4666739
> Use perl-Bootloader on LeapMicro 6.1

- tests/security/ibmtss/ibmtss_basic_function.pm
The test fails when being executed on https://openqa.opensuse.org.
This change uses different sources for SLE.
- Related ticket: https://progress.opensuse.org/issues/169957
- Verification run: https://openqa.suse.de/tests/16015524#step/ibmtss_basic_function/16
> Use different sources for SLE and TW

- tests/installation/bootloader_svirt.pm
The svirt os-autoinst backend already takes care of copying the assets, therefore remove the unneeded code.
- Related ticket: https://progress.opensuse.org/issues/159579
- Verification run: https://openqa.suse.de/tests/16001344#step/bootloader_svirt/32 (failures are unrelated to PR)
> bootloader_svirt: Don't copy image from NFS datastore

- tests/containers/bci_test.pm
The used BCI_OS_VERSION gets overwritten later on in the test tuns. This fixes it by making the export there conditional to the existence of that setting.
- Related failure: https://openqa.suse.de/tests/16015072
* https://openqa.suse.de/tests/16015460#step/bci_test_podman/53 (other failure is unrelated)
> Fix BCI_OS_VERSION

- lib/main_common.pm
- lib/version_utils.pm
- t/01_version_utils.t
- tests/transactional/enable_selinux.pm
1. Only keep grub timeout for tests that have SELINUX=1 set and are sle<16, microos-tools in SLE16 and tw contain a fix for this.
2. Introduce has_selinux_by_default to version_utils, which returns true if the distro has selinux by default.
3. Do not run enable_selinux in systems that have SELinux by default, since the test will fail as it is already enabled.
4. Check SELinux failures when SELinux is enabled by default and not only when SELINUX=1 is set.
In contrast to my previous draft I now keep the `SELINUX` variable for the distros where SELinux is not enabled by default and you want to enable it before running tests.
tw ZDUP/UPGRADE should not be affected (i think) because:
1. only for sle <16
2. noop
3. `SELINUX` will not be set for these tests
4. audit log should be empty, …
> SELinux as default MAC in enforcing mode in the tumbleweed installer (bsc#1230118)

- tests/containers/buildah_integration.pm
Get list of helpers to be compiled in buildah upstream tests
- Related ticket: https://progress.opensuse.org/issues/170200
- Verification run: https://openqa.opensuse.org/tests/4667365
> containers: Get list of helpers to be compiled in buildah upstream tests

- data/journal_check/bug_refs.json
- tests/microos/image_checks.pm
Ensure that Leap Micro 6.1 follows same soft fails as SLE Micro 6.1
* bsc#1215377: sedispatch terminated unexpectedly
* bsc#1220722: no unpartitioned space left on aarch64
Test run for image checks soft-fail bsc#1220722: https://openqa.opensuse.org/tests/4667692
Test run for sedispatch soft-fail bsc#1215377: https://openqa.opensuse.org/tests/4667694
> Backport soft-fails from SL Micro 6.1 to Leap Micro

- data/yam/autoyast/support_images/autoyast_sles15sp6_media_install_textmode_default_patterns_aarch64.xml
- data/yam/autoyast/support_images/autoyast_sles15sp6_media_install_textmode_default_patterns_s390x.xml
- data/yam/autoyast/support_images/autoyast_sles15sp6_media_install_textmode_default_patterns_x86_64.xml
- data/yam/autoyast/support_images/sles15sp6_install_textmode_default_patterns_aarch64.xml
- data/yam/autoyast/support_images/sles15sp6_install_textmode_default_patterns_s390x.xml
- data/yam/autoyast/support_images/sles15sp6_install_textmode_default_patterns_x86_64.xml
- data/yam/autoyast/support_images/sles15sp6_install_textmode_hpc_aarch64.xml
- data/yam/autoyast/support_images/sles15sp6_install_textmode_hpc_x86_64.xml
We have added different templates and configurations to allow the migration of sp6 jobs in OpenQA.
- Related ticket: https://progress.opensuse.org/issues/166268
- Needles: N/A
- Related MR: https://gitlab.suse.de/qe-yam/openqa-job-groups/-/merge_requests/348
- For Migrations check this job group, build 31.1: https://openqa.suse.de/tests/overview?distri=sle&version=15-SP7&build=31.1&groupid=583
- For HDD building check build 20241107: https://openqa.suse.de/tests/overview?distri=sle&version=15-SP6&build=20241107&groupid=583
> Add migration testsuites for SLES15SP6 migration path of Texmode default pattern

- data/journal_check/bug_refs.json
* I found further missing healt-checker soft-fail, so I rather synced all of them.
* Skip these where 6.X is not involved at all
> Sync soft-fails in between Leap and SLE Micro 6.X

- data/yam/autoyast/support_images/sles15sp5_install_textmode_all_patterns_aarch64.xml
- data/yam/autoyast/support_images/sles15sp5_install_textmode_all_patterns_s390x.xml
- data/yam/autoyast/support_images/sles15sp5_install_textmode_all_patterns_x86_64.xml
Update autoyast profiles of textmode all patterns by removing fips, and add a missed pattern of yast2_server.
- Related ticket: https://progress.opensuse.org/issues/166274
- Needles: n/a
- Verification run: [support images](https://openqa.suse.de/tests/overview?distri=sle&version=15-SP6&build=20241124-1&groupid=576); [migration jobs](https://openqa.suse.de/tests/overview?arch=x86_64%2Cs390x%2Caarch64&flavor=&machine=&test=&modules=&module_re=&group_glob=&not_group_glob=&comment=&distri=sle&version=15-SP7&build=41.1&groupid=576#)
- Related mr: https://gitlab.suse.de/qe-yam/openqa-job-groups/-/merge_requests/379#note_694883
> Update autoyast profiles of textmode all patterns by removing fips

- lib/mm_network.pm
Alternative approach to solve https://progress.opensuse.org/issues/169531 - we don't really *need* full (the default if `EXPECTED_NM_CONNECTIVITY` is not set) network connectivity in our test  but also don't care if we have it so we need to expand the test to be able to check multiple values.
The timeout was mainly added to avoid confusing additional output after the test already finished like e.g. visible in https://openqa.opensuse.org/tests/4625960#step/setup_multimachine/83
Validation runs:
**rsync-server**/**rsync-client**:
* https://openqa.opensuse.org/tests/4667626 🟢
* https://openqa.opensuse.org/tests/4667627 🟢
**ping_server**/**ping_client**:
* https://openqa.opensuse.org/tests/4667630 🟢
* https://openqa.opensuse.org/tests/4667629 🟢 …
> Improve restart of NetworkManager

- lib/sles4sap_publiccloud.pm
- t/12_sles4sap_publicccloud.t
- tests/sles4sap/publiccloud/qesap_terraform.pm
Change composition of the command line for the register.yaml playbook. Allow only to add reg code for BYOS images and leave it empty when using PAYG.
- Related ticket: https://jira.suse.com/browse/TEAM-9867
http://openqaworker15.qa.suse.cz/tests/304394 :green_circle:  In particular file http://openqaworker15.qa.suse.cz/tests/304394/file/deploy_qesap_terraform-sles4sap_azure_generic_maintenance.yaml has no reg_code as expected in ...
```
- registration.yaml -e reg_code= -e email_address=''
```
> Allow having no reg code in PAYG deployments

- lib/y2snapper_common.pm
- Related ticket: https://progress.opensuse.org/issues/168583
- Needles: n/a
- Verification run: https://openqa.opensuse.org/tests/4671861#
Sanity tests with apparmor: https://openqa.opensuse.org/tests/4668376#details
VR on sle15sp7: http://openqa.suse.de/tests/16024977#details
> Allow certain snapshots to be labeled 'snapperd_data_t'

- lib/main_containers.pm
- tests/containers/podman_quadlet.pm
Improved the `containers/podman_quadlet.pm` to include tests for pod, build and network quadlets.
- Needles: N/A
- Verification run: [openqa.opensuse.org/tests/4670842#step/podman_quadlet/1
](https://openqa.opensuse.org/tests/4670842#step/podman_quadlet/1)
> Add podman pod, build and network quadlet testing

- lib/main_common.pm
- Related ticket: https://progress.opensuse.org/issues/169999
- Needles: N/A
- Verification run: [Package is none](http://openqa.qam.suse.cz/tests/81639)
[ another VR test when package is none](http://openqa.qam.suse.cz/tests/81569#step/kernel/1) please ignore failure afterwards.
> Add 'none' Condition for Convenient Testing in Package Update Logic

- tests/containers/buildah.pm
Skip buildah rootless tests on svirt
- Related ticket: https://progress.opensuse.org/issues/170452
- Verification run: https://openqa.suse.de/tests/16036660
> containers: Skip buildah rootless tests on svirt

- lib/containers/docker.pm
Ubuntu's docker lacks a /etc/docker/daemon.json.  Create this file if not present.
- Related ticket: https://progress.opensuse.org/issues/170278
- Verification run: https://openqa.opensuse.org/tests/4673127
> containers: Create daemon.json if file does not exist

- lib/migration.pm
When `SCC_ADDONS` include `ltss_es`, it matches the regex `/ltss/`, but we should not deregister it because there is no LTSS module added. It will cause the job fails. So change the code, only `SCC_ADDONS` includes 'ltss', then do deregister.
Related: https://jira.suse.com/browse/TEAM-9865
VRs:
LTSS:
offline-scc: : https://openqa.suse.de/tests/16036668#step/patch_sle/45  (Passed)
offline-dvd:  https://openqa.suse.de/tests/16036665#step/patch_sle/45  (Passed)
LTSS-ES:
offline-scc: https://openqa.suse.de/tests/16036671#step/patch_sle/42   (Passed)
offline-dvd: https://openqa.suse.de/tests/16036672#step/patch_sle/42 (Passed)
> Improve the code when deregister ltss module

- tests/security/tpm2/keylime/keylime.pm
a quick fix to address previous https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/20705
- Related ticket: https://progress.opensuse.org/issues/170512
- Needles: 
- 15SP7 https://openqa.suse.de/tests/16049978
- 15SP6 https://openqa.suse.de/tests/16049979
> Ignore failure on optional copy operation

- data/yam/autoyast/support_images/sles15sp6_install_gnome_all_patterns_aarch64.xml
- data/yam/autoyast/support_images/sles15sp6_install_gnome_all_patterns_s390x.xml
- data/yam/autoyast/support_images/sles15sp6_install_gnome_all_patterns_x86_64.xml
We have added the required modifications to include gnome migration cases into OpenQA
- Related ticket: https://progress.opensuse.org/issues/166277
- Related MR: https://gitlab.suse.de/qe-yam/openqa-job-groups/-/merge_requests/376
- Needles: N/A
- YAM support images: https://openqa.suse.de/tests/overview?distri=sle&version=15-SP6&build=20241111&groupid=583
- Migrations: https://openqa.suse.de/tests/overview?distri=sle&version=15-SP7&build=39.2&groupid=583
> Add migration testsuites for SLES15SP6 migration path of Gnome role with all patterns

- data/virt_autotest/host_unattended_installation_files/autoyast/dev_host_15.xml.ep
- lib/virt_autotest/utils.pm
- products/sle/main.pm
- tests/virt_autotest/guest_migration_src.pm
- tests/virt_autotest/update_package.pm
- tests/virt_autotest/virt_utils.pm
Related ticket: [poo#170245](https://progress.opensuse.org/issues/170245)
Related PR: https://github.com/SUSE/qa-automation/pull/851
[prj3_sle15sp7_kvm](https://10.145.10.207/tests/16011127)
[prj3_sle15sp7_xen](https://10.145.10.207/tests/16013111)
[sle15sp6_kvm](https://10.145.10.207/tests/16026152)
[gi-guest_developing-on-host_developing-kvm](https://10.145.10.207/tests/16021267)
[uefi-gi-guest_developing-on-host_sles12sp5-kvm](https://10.145.10.207/tests/16021305)
> Use NFS v3 instead v4 for virt prj3 tests to get around bsc#1230971 and mark softfail

- lib/virt_autotest/utils.pm
Issue Description:
When attempting to install a guest, the LTSS (Long Term Service Support) registration code cannot be get. Instead, it displays an incorrect or empty string '-E "|||||||||||||"'.
- Related ticket: https://progress.opensuse.org/issues/169678
- Needles: N/A
- [multi-guest test](http://openqa.qa2.suse.asia/tests/80419) with '|'
- [multi-guest test](http://openqa.qa2.suse.asia/tests/80465) with ','
- [one guest test](http://openqa.qa2.suse.asia/tests/80466)
> Fix the separator issue, support multi guest test

- tests/kernel/update_kernel.pm
Baremetal and PowerVM backends need to reconnect boot console after reboot, otherwise the test will time out waiting for GRUB menu.
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/16070701
> update_kernel: Reconnect console after installing kernel for livepatching

- lib/containers/docker.pm
We need a non-empty /etc/docker/daemon.json and for that we're using `log-level`.  We set it to `warn` but turns out some tests rely on the default `info` level, so use that instead.
- Failing test: https://openqa.suse.de/tests/16038959
- Verification run: https://openqa.suse.de/tests/16071961 (failing due to BCI issues but fails better).
> containers: Set log-level to info in /etc/docker/daemon.json

- lib/sles4sap/sap_deployment_automation_framework/deployment.pm
- t/20_sdaf_deployment_library.t
Control SDAF version to use latest -1
- support SDAF_GIT_AUTOMATION_BRANCH="latest"
- support SDAF_GIT_AUTOMATION_BRANCH="$any-version-listed-in-releases" 
- support SDAF_GIT_AUTOMATION_BRANCH="", version latest-1 will be used if this version is bigger than "v3.11.0.3"
Related ticket: [TEAM-9683](https://jira.suse.com/browse/TEAM-9683)
[SDAF][research] Mechanism to control SDAF version
Note: 
1. Versions <= "v3.11.0.3" miss feautre so test cases will report failure.
2. Atm Version_latest="v3.13.0.1"; Version_latest-1="v3.13.0.0" this version has issue, see VRs.
SDAF_GIT_AUTOMATION_BRANCH="" (then latest-1="v3.13.0.0")
https://openqaworker15.qa.suse.cz/tests/304777#step/deploy_workload_zone/231 (failed)
https://openqaworker15.qa.suse.cz/tests/304778#step/deploy_workload_z …
> Control SDAF version to use latest -1

- tools/detect_unused_modules
This fixes CI error:
tests/console/velociraptor_client_event_collect.pm module is not used in any schedule
Fixes: 3a437b6f6 ("Remove velociraptor tests")
Fixes: https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/20530
> detect_unused_modules: Whitelist velociraptor_client_event_collect

- lib/xfstests_utils.pm
Use tail to read fs_stat log may meet the issue that the path also contain dir. Use find could avoid this issue.
- Related ticket: https://progress.opensuse.org/issues/166736
Before: it has the red fail block  https://openqa.suse.de/tests/16033573#step/generic-091/32
After: it will not fails in tail log part  https://openqa.suse.de/tests/16079982#step/generic-075/38
> xfstests: Fix fs_stat log path contain dir issue

- data/autoyast_sle15/autoyast_sle-micro_updates.xml.ep
Update a slem autoyast profile to get the update repo from scc only.
From the profile, it has the registration, so the update repo could be
picked from scc, no need to add an update repo from disk.suse.de.
- To fix this failure: https://openqa.suse.de/tests/16079638
- Verification run: [x86_64](https://openqa.suse.de/tests/16080005#), [s390x](https://openqa.suse.de/tests/16080019#), [aarch64](https://openqa.suse.de/tests/16080018#)
> Update a slem autoyast profile to get update repo from scc only

- tests/containers/podman_integration.pm
criu still uses iptables as dependency.
- Related ticket: https://progress.opensuse.org/issues/173362
- Verification run: https://openqa.opensuse.org/tests/4681397
> containers: Install iptables in podman upstream tests

- lib/main_containers.pm
podman_quadlet should not be executed on Staging.
* Follow-up of https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/20713/files
> Skip podman_quadlet on Staging

- schedule/kernel/io_uring.yaml
Fix poo#173680: We need to run io_uring on s390x architecture and we need to include bootloader_zkvm into schedule.
- Related ticket: https://progress.opensuse.org/issues/173680
- Verification run: https://openqa.suse.de/tests/16083391
> Add bootloader_zkvm to io_uring schedule

- data/virt_autotest/guest_params_xml_files/sles_15_sp6_64_kvm_hvm_sev_es_x86_64.xml
- data/virt_autotest/guest_params_xml_files/sles_15_sp7_64_kvm_hvm_sev_es_x86_64.xml
* **Use** driver.iommu=on for SEV/ES guest network, please refer to [this](https://bugzilla.suse.com/show_bug.cgi?id=1231417#c25).
* **Default** SEV/ES guest installation has ```secure boot``` enabled.
* [sles15sp7 sev/es guest](https://openqa.suse.de/tests/16079812)
* [sles15sp6 sev/es guest](https://openqa.suse.de/tests/16079813)
> Use network driver.iommu=on and secureboot for SEV/ES guest

- lib/xfstests_utils.pm
Check before cat the fs_stat log.
- Related ticket: https://progress.opensuse.org/issues/173707
- Verification run: https://openqa.suse.de/tests/16094717
> xfstests: Fix problem when can't find fs_stat log

- tests/kernel/multipath_iscsi.pm
- Related fail: https://openqa.suse.de/tests/16097455#step/multipath_iscsi/42 :red_circle: 
15-SP7 KOTD (image doesn't  have multipath-tools installed):  https://openqa.suse.de/tests/16098454 :green_circle: 
12-SP5: https://openqa.suse.de/tests/16098448 :green_circle: 
15-SP6: https://openqa.suse.de/tests/16098451 :green_circle:
> multipath: Make sure multipath-tools are installed

- lib/sles4sap/console_redirection.pm
- lib/sles4sap/sap_deployment_automation_framework/inventory_tools.pm
- schedule/sles4sap/sap_deployment_automation_framework/hanasr_redirected.yml
- t/19_console_redirection.t
- t/29_sdaf_inventory_tools.t
- tests/sles4sap/redirection_tests/README.md
- tests/sles4sap/redirection_tests/hana_cluster_check.pm
- tests/sles4sap/redirection_tests/redirection_check.pm
- tests/sles4sap/sap_deployment_automation_framework/prepare_ssh_config.pm
This PR adds functionality to execute standard API call directly on SUT behind 
firewall using SSH proxy jump host. Currently adds support to SDAF based tests 
by translating ansible inventory file to data structure required by redirection 
tests. PR introduces two test modules which showcase couple of API calls and 
existing library functions working out of the box.
- Related ticket: https://jira.suse.com/browse/TEAM-9866
- Verification run: https://mordor.suse.cz/tests/878#
> SDAF - OpenQA API directly on SUT

- lib/bootloader_setup.pm
- lib/main_micro_alp.pm
- products/sle-micro/main.pm
The schedule update is required for non-selfinstall ppc64le test scenarios.
The bootloader handler is mandatory for jeos-wizard test scenario as
`console` parameters are missing and jeos-wizard won't be shown in the current `tty`.
- ticket: https://progress.opensuse.org/issues/169243
- Verification run: http://kepler.suse.cz/tests/24152#step/bootloader_uefi/4
> Update selfinstall test schedule

- lib/ipsecbase.pm
ipsecbase.pm: Update correct parameter for systemctl
- Related ticket: https://progress.opensuse.org/issues/173746
- Needles: na 
- Verification run: https://openqa.suse.de/tests/16108605#step/ipsec3hosts/18
> ipsecbase.pm: Update correct parameter for systemctl

- tests/containers/podman_quadlet.pm
Currently it fails due to lack of full environment upon test instantiation.
Fail: https://openqa.opensuse.org/tests/4686335
- Related ticket: https://progress.opensuse.org/issues/173764
- VR: https://openqa.opensuse.org/tests/4686343 (thanks @grisu48 )
> podman_quadlet: Move podman version check into pre run hook

- tests/containers/podman_quadlet.pm
Use Tumbleweed as the test image because Leap is not available on RISC-V.
- Related ticket: https://progress.opensuse.org/issues/166589
- Related failure: https://openqa.opensuse.org/tests/4685094#step/podman_quadlet/142
- Verification run: https://openqa.opensuse.org/tests/4685231#
> Use Tumbleweed as test image for quadlet

- tests/virt_autotest/kubevirt_tests_agent.pm
- tests/virt_autotest/kubevirt_tests_server.pm
Fix the following failure during connecting kubevirt nodes.
> E1206 06:37:50.095586   15055 memcache.go:265] couldn't get current server API group list: Get "https://bare-metal1.oqa.prg2.suse.org:6443/api?timeout=32s": tls: failed to verify certificate: x509: certificate is valid for kubernetes, kubernetes.default, kubernetes.default.svc, kubernetes.default.svc.cluster.local, localhost, bare-metal1, not bare-metal1.oqa.prg2.suse.org
- Related ticket: https://progress.opensuse.org/issues/173710
- Verification run: https://openqa.suse.de/tests/16127509
> Fix x509 tls certificate failure

- lib/main_micro_alp.pm
Need to use published repos
- Related ticket: https://progress.opensuse.org/issues/170158
- Verification run: https://openqa.opensuse.org/tests/4682873#
- Need update trigger command: related PR: https://github.com/os-autoinst/openqa-trigger-from-obs/pull/280
> Need to switch to 'repo to be tested for next snapshot'

- lib/concurrent_guest_installations.pm
- tests/virt_autotest/unified_guest_installation.pm
* **Use** openQA setting UNIFIED_GUEST_INSTALLATION_MEDIA to make guest installation media configurable, so media can be specified on the fly without limitation. This brings convenience especially taking non-/CC areas into consideration. 
* **Old** way of using parameter guest_installation_media in guest profile is still supported, so only when value in UNIFIED_GUEST_INSTALLATION_MEDIA is not empty, guest_installation_media will take value from it. Otherwise, the guest_installation_media still takes value from guest profile.
* **Ticket** [poo#173698](https://progress.opensuse.org/issues/173698) to request missing medium. 
* [Two sl micro guests using UNIFIED_GUEST_INSTALLATION_MEDIA](http://openqa.qa2.suse.asia/tests/80565)
* [One of two sl micro guests using …
> Make guest installation media configurable

- lib/bootloader_setup.pm
- tests/installation/bootloader_uefi.pm
Appending kernel parameters has to be done in the line with [linux](https:]/kepler.suse.cz/tests/24159#step/bootloader_uefi/7) If OFW is set, there are 2 places in the code where this can occur.
Fixing: http://kepler.suse.cz/tests/24156#step/bootloader_uefi/7
ticket: https://progress.opensuse.org/issues/169243
* [powerPC selfinstall iso](http://kepler.suse.cz/tests/24195#step/bootloader_uefi/7)
* [powerPC image](http://kepler.suse.cz/tests/24196#step/bootloader_uefi/5)
* [sle-15-SP2-JeOS-for-kvm-and-xen](https://openqa.suse.de/tests/16125405#step/bootloader_uefi/6)
* [sle-15-SP7-JeOS-for-kvm-and-xen](http://kepler.suse.cz/tests/24200#step/bootloader_uefi/6)
* [tw-jeos](http://kepler.suse.cz/tests/24189#step/bootloader_uefi/6)
* [microos-Tumbleweed-MicroOS-Image](http://kepler.suse.cz/tests …
> Restrict redundant grub2 edit moves for ppc64le

- lib/main_containers.pm
- tests/containers/podman_docker_interop.pm
Implements tests for interoperability of podman, docker and firewalld in terms of networking. Validates [bsc#1213811](https://bugzilla.suse.com/show_bug.cgi?id=1213811) and [bsc#1214080](https://bugzilla.suse.com/show_bug.cgi?id=1214080).
- Related ticket: https://progress.opensuse.org/issues/134024
- Needles: N/A
- Verification run: https://openqa.opensuse.org/tests/4687705#step/podman_docker_interop/1
> Podman, docker, firewalld softfails

- lib/publiccloud/provider.pm
- variables.md
Introduce PUBLIC_CLOUD_MAX_INSTANCES variable, which allows
only a limited amount of calls to create_instance subroutine when set. The default value is 1.
While adding documentation to this new variable, move a few Public Cloud related variables into their relevant sections and sort them all.
- Related ticket: https://progress.opensuse.org/issues/168673
- Verification run: http://rmarliere-openqa.qe.prg2.suse.org/tests/196#step/prepare_instance/188 (intentional failure with an extra create_instance call inserted)
> publiccloud/provider: Limit calls to create_instance by default

- data/yam/autoyast/create_hdd_migration_ppc64le.xml.ep
##
- Error screen:
-  https://openqa.suse.de/tests/16141905#step/online_migration_setup/1
- https://progress.opensuse.org/issues/169789
- Needles: 
- N/A 
-  https://openqa.suse.de/tests/16142016#step/online_migration_setup/2
##
> Change powerVM autoyast boot timeout to -1

- data/yam/autoyast/create_hdd_migration_ppc64le.xml.ep
- tests/migration/online_migration/yast2_migration.pm
##
We need to add SMT_URL for smt milestone case and choose "Yes" for yast2 migration with smt.
- Error screen:
-  https://openqa.suse.de/tests/16124624#step/yast2_migration/7
- https://progress.opensuse.org/issues/169789
- https://progress.opensuse.org/issues/169624
- Needles: 
- N/A 
-  https://openqa.suse.de/tests/16141815
##
> Fix SMT autoyast profile for 15sp7 spvm

- tests/microos/image_checks.pm
openQA cannot resize powerVM disk image since it is not QEMU backend, skip the check here
- Related ticket: https://progress.opensuse.org/issues/167986
- Verification run: https://openqa.suse.de/tests/16079923#step/image_checks/7
> Openqa cannot resize powerVM disk size since it is not QEMU backend

- data/virt_autotest/host_unattended_installation_files/autoyast/dev_host_12.xml.ep
- data/virt_autotest/host_unattended_installation_files/autoyast/dev_host_15.xml.ep
- lib/virt_autotest/utils.pm
- tests/virt_autotest/virt_utils.pm
* **For** test scenarios that do not do registration, using add_on_products can help enable modules and install packages without registration.
* **The** functionality is already implemented by using ```MAINT_TEST_REPO``` settings.
* **Improve** ```is_registered_sles``` in ```lib/virt_autotest/utils.pm``` to include ```REGISTER``` setting.
* **Clean** up lists of exported subroutines in ```lib/virt_autotest/utils.pm``` and ```tests/virt_autotest/virt_utils.pm```.
* [verification run with full media without registration](http://10.200.140.9/tests/112) 
* [15sp7 with online media with registration](https://openqa.suse.de/tests/15874362)
* [15sp6 with full media and modules without registration](https://openqa.suse.de/tests/15874259)
* [15sp7 with full media and …
> Use add_on_products to enable modules without registration

- tests/virt_autotest/login_console.pm
- tests/virt_autotest/reboot_and_wait_up_upgrade.pm
* **Due** to drastic change introduced by bsc#1231522, code for offline host upgrade test scenario needs to be refactored to suit this new situation.
* **The** whole process of offline host upgrade will be performed automatically on ipmi sol console to save unnecessary needle match.
* **Skip** system reboot after ```UPGRADE_AFTER_REBOOT```, because it will interrupt ongoing offline host upgrade.
* **Function** ```check_port_state``` will be used to detect whether upgrade process finishes or not continuously.
* **By** the way, if ```reboot now``` dialogue comes back in the future, its assertion can still be added in based on this pull request. This pull request cleans things up and make the overall process more clear and neat anyway.
* [offline host upgrade 12sp5 …
> Refactor code for offline host ugprade

- data/lynis/baseline-lynis-audit-system-nocolors-15-SP7-aarch64-gnome
- data/lynis/baseline-lynis-audit-system-nocolors-15-SP7-aarch64-textmode
- data/lynis/baseline-lynis-audit-system-nocolors-15-SP7-ppc64le-textmode
- data/lynis/baseline-lynis-audit-system-nocolors-15-SP7-s390x-gnome
- data/lynis/baseline-lynis-audit-system-nocolors-15-SP7-s390x-textmode
- data/lynis/baseline-lynis-audit-system-nocolors-15-SP7-x86_64-gnome
- data/lynis/baseline-lynis-audit-system-nocolors-15-SP7-x86_64-textmode
- schedule/security/lynis/lynis_create_baseline.yaml
- tests/security/lynis/lynis_create_baseline.pm
committing also a new module that can be used to create new baseline by setting a variable 'LYNIS_CREATE_BASELINE'
- Related ticket: https://progress.opensuse.org/issues/173725
- Needles: no
- x86_64    https://openqa.suse.de/tests/16149426
- x86_64    https://openqa.suse.de/tests/16149427
- aarch64   https://openqa.suse.de/tests/16149887 
- aarch64   https://openqa.suse.de/tests/16149889 
- s390x-kvm https://openqa.suse.de/tests/16149890 
- s390x-kvm https://openqa.suse.de/tests/16149888 
- ppc64le   https://openqa.suse.de/tests/16156168
> Create new lynis baseline for 15-SP7

- tests/containers/update_host.pm
The update procedure for Ubuntu only updates the package lists but not the packages themselves.
- Related ticket: https://progress.opensuse.org/issues/173539
- Verification run: https://openqa.suse.de/tests/16157791
> containers: Run apt-get upgrade on Ubuntu

- tests/containers/buildah.pm
Limit bsc#1232522 soft-failure to 15-SP3
- Related ticket: https://progress.opensuse.org/issues/169075
- Verification run: https://openqa.suse.de/tests/15997537 for another PR.
> containers: Limit bsc#1232522 soft-failure to 15-SP3

- tests/jeos/firstrun.pm
The QR flavor for RPi was omitted therefore incorrect partition table type was being asserted.
* [15-sp7](https://openqa.suse.de/tests/16158755#)
* [15-sp6 qr](https://openqa.suse.de/tests/16158754#step/firstrun/71)
> Update FLAVOR for partition table check in JeOS

- tests/wsl/prepare_wsl.pm
Despite the documentation claiming that it exists even on win 10, it's not even available on 23H2!
VRs:
x86 23H2: https://openqa.opensuse.org/tests/4695166
aarch64: 24H2: https://openqa.opensuse.org/tests/4695167
CC @Chubykalo
> wsl/prepare_wsl.pm: Run wsl.exe --update on Win 11 24H2 only

- lib/main_containers.pm
- tests/containers/bci_collect_stats.pm
- tests/containers/bci_version_check.pm
Extract a own test module bci_collect_stats to collect stats about the running containers.
This is useful as it displays errors with the container stats visibly within the job group instead of a generic test failure in "bci_version_check". Also it makes it more visible when and where the stats are collected and allows us to softfail those issues, if necessary.
* [Tumbleweed - bci_init](https://openqa.opensuse.org/tests/4695353) - **not** supposed to collect stats
* [SLES 15-SP4 bci_minimal](https://openqa.suse.de/tests/16164052) - **not** supposed to collect stats
* [SLES 15-SP6 bci_minimal](https://openqa.suse.de/tests/16164053) - is supposed to collect stats
* [SLES 15-SP6 bci_minimal ppc64](https://openqa.suse.de/tests/16164054) is supposed to collect stats and to fail, but the test …
> Refactor bci_collect_stats

- lib/Yam/Agama/agama_base.pm
- Removed the output redirection, because this is already done by giving the filename for the tee command.
- Increased timeout for the commands because sometimes the post_fail method timed out.
VR: https://openqa.suse.de/tests/16161920
> Quickfix double redirection in upload_agama_logs

- lib/sles4sap/sap_deployment_automation_framework/inventory_tools.pm
- schedule/sles4sap/sap_deployment_automation_framework/hanasr_publiccloud.yml
- tests/sles4sap/sap_deployment_automation_framework/setup_publiccloud_instances.pm
This PR adds compatibility layer for SDAF deployment based tests to use 
`lib/pubbliccloud` libraries. PR includes library function, test module 
preparing compatibility layer and a schedule.
- Related ticket: https://jira.suse.com/browse/TEAM-9794
- Verification run: https://mordor.suse.cz/tests/926#
> Add SDAF PC lib compatibility layer

- tests/console/ping.pm
Use `command -v` instead of `which` to get pathname to executable.  `command` is [POSIX](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/command.html).  Checked in openSUSE (bash & Bash `sh` mode), Debian (Dash), Alpine (sh), FreeBSD (sh & ksh), NetBSD (sh & ksh), OpenBSD (sh & ksh), DragonflyBSD (sh) & OpenIndiana (sh & ksh).
- Related ticket: https://progress.opensuse.org/issues/168961
- Verification run: https://openqa.opensuse.org/tests/4696577 (failing for other reason)
> console/ping: Use command instead of which to get full pathname

- lib/containers/common.pm
- lib/containers/container_images.pm
- lib/main_containers.pm
The container module for aarch64 12SP5 is not going to be enabled hence
the container packages will land in LTSS. We need to skip enabling
container repo.
The PR is skipping `validate_btrfs.pm` as the module is dependent on
`/var` subvolume that is not present in aarch64 sle12sp5 installations
Package `zypper-docker` is not yet present and it is unclear whether it
will be added in the near future.
```
devtmpfs        974M     0  974M   0% /dev
tmpfs           992M     0  992M   0% /dev/shm
tmpfs           992M   23M  970M   3% /run
tmpfs           992M     0  992M   0% /sys/fs/cgroup
/dev/vdb2        38G  2.9G   34G   8% /
/dev/vdb2        38G  2.9G   34G   8% /.snapshots
/dev/vdb1       305M  216K  305M   1% /boot/efi
tmpfs           199M     0  199M   0% /run/user/0
```
- ticket: …
> Enable docker testing in sle12sp5 LTSS in aarch64

- tests/qam-updinstall/update_install.pm
the name of saptune package update channel will be updated to `*_LTSS*` in `update_install.pm`, but saptune package is not in LTSS update channel, this results in the failure to find saptune rpm binary.
Now substituting the module name is useless, I drop the  related code to fix issue.
- Related ticket: https://jira.suse.com/browse/TEAM-9817
https://openqa.suse.de/tests/16110212#step/update_install/24 (saptune, NOT in LTSS)
https://openqa.suse.de/tests/16110213#step/update_install/24 (webkit2gtk3, in LTSS)
https://openqa.suse.de/tests/16110227#step/update_install/24 (ppc64le, in Public Cloud)
https://openqa.suse.de/tests/16110231#step/update_install/24 (15-SP6)
> Drop the useless code of substituting module name

- data/virt_autotest/kubevirt_tests/junit-noframes.xsl
- data/virt_autotest/kubevirt_tests/remove_dup_skipped_tests.py
- tests/virt_autotest/kubevirt_tests_server.pm
For kubevirt test in final html report (http://openqa.suse.de/tests/15823784/file/index.html), each skipped test id is counted multiple times. In summary page, test results should show PASS+FAIL test cases only, without skipped tests duplication.
- Related ticket: https://progress.opensuse.org/issues/113558
- Verification run: https://openqa.suse.de/tests/16161108 (html report: https://openqa.suse.de/tests/16161108/file/junit-noframes.html)
> Remove duplicate skipped testcases from XML result files

- lib/qesapdeployment.pm
- tests/sles4sap/publiccloud/qesap_terraform.pm
When retrying the terraform appaly command, the second error related to the resource already existing. So we could run destory befor retrying to avoid this error.
Related: https://jira.suse.com/browse/TEAM-9788
VR: https://openqa.suse.de/tests/16171500#step/qesap_terraform/368 
Using `QESAP_SIM_RC=45 QESAP_SIM_MSG='An internal execution error occurred. Please retry later'` to trigger a simulated failure.
> Run terraform destroy before retrying terraform apply

- lib/Yam/Agama/agama_base.pm
- Fixed the upload from `agama logs store` command
- Put back the output redirection to avoid screen clutter
- Verification run: https://openqa.suse.de/tests/16183350
> Quickfix for upload_agama_logs

- lib/kdump_utils.pm
Fix poo#170422: FTP service on openqa.suse.de is not available due to
recent security changes and is better to use http for debug
repository.
- Related ticket: https://progress.opensuse.org/issues/174370
The only place where debug repository was added via ftp.
- ppc64le this one needed a fix - https://openqa.suse.de/tests/16191310
- aarch64: https://openqa.suse.de/tests/16192074
- x86_64: https://openqa.suse.de/tests/16192073
ftp is not used in these scenarions, it is just generic verification.
15-SP7 KOTD:  https://openqa.suse.de/tests/16190249
15-SP6: https://openqa.suse.de/tests/16192077
12-SP5: https://openqa.suse.de/tests/16188747
> kdump: Use http instead of ftp for debug repository

- lib/main_micro_alp.pm
The last AITL PR enabled AITL for SLES and this PR also enables it for SLEM.
- Related PR: https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/20649
- Verification run: http://dirtman.qe.prg2.suse.org/tests/243#
> Enable Azure AITL tests for SLE-Micro

- data/publiccloud/aitl/custom.json
- tests/publiccloud/azure_aitl.pm
AITL tests operate on Tiers which are a bunch of tests grouped together based on different parameters. As we have no control over what goes in the Tiers, we are going to roll-out the AITL testing in a more controlled manner with a custom list.
This PR also adds the ability to exclude certain tests or groups of tests based on regex.
- Related PR: https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/20649
- Verification run: http://dirtman.qe.prg2.suse.org/tests/247#external - This VR was ran with `PUBLIC_CLOUD_AITL_EXCLUDE_TESTS` set to `nvme`. As you can see in the logs - there are no tests with `nvme` in the `caseName`.
> Add option to exclude specific AITL tests

- data/publiccloud/terraform/ec2.tf
- lib/publiccloud/ec2.pm
- tests/publiccloud/bsc_1205002.pm
- variables.md
The new generation t3a instances deliver up to 10% cost savings over comparable instance types.
- Related ticket: https://progress.opensuse.org/issues/169405
> Switch EC2 default instance type to t3a

- lib/main_common.pm
- tests/installation/bootloader_uefi.pm
This PR contains some small fixes required to run the new Tumbleweed JeOS-for-kvm-and-xen-sdboot flavor.
- Related ticket: https://progress.opensuse.org/issues/169354
- Needles: https://github.com/os-autoinst/os-autoinst-needles-opensuse/pull/823
- OBS trigger: https://github.com/os-autoinst/openqa-trigger-from-obs/pull/282
- Schedule: https://github.com/os-autoinst/opensuse-jobgroups/pull/572
- Verification run: https://rmarliere-openqa.qe.prg2.suse.org/tests/1098
> Enable JeOS-for-kvm-and-xen-sdboot flavor

- lib/main_containers.pm
- tests/console/enable_mac.pm
- variables.md
Introduce SECURITY_MAC to allow tests Apparmor & SELinux
- Related ticket: https://progress.opensuse.org/issues/168682
- Tumbleweed (podman w/ `SECURITY_MAC=selinux`): https://openqa.opensuse.org/tests/4706320
- Tumbleweed (podman w/ `SECURITY_MAC=apparmor`): https://openqa.opensuse.org/tests/4706338
- Tumbleweed (docker w/ `SECURITY_MAC=selinux`): https://openqa.opensuse.org/tests/4706453
Notes:
- There's no test for the change from a product with SELinux enabled by default to AppArmor.
- SELinux comes by default in MicroOS & SLEM 5.2+ so there's no point in testing AppArmor on transactional systems.  Also `transactional-update setup-apparmor` is not available, unlike `setup-selinux`.
TODO:
- Create job schedules for Tumbleweed & MicroOS.
> containers: Introduce SECURITY_MAC to allow testing Apparmor & SELinux

- data/yam/agama/auto/default_leap.json
- data/yam/agama/auto/default_sle.json
- data/yam/agama/auto/default_tumbleweed.json
- data/yam/agama/auto/gnome_leap.json
- data/yam/agama/auto/gnome_tumbleweed.json
- data/yam/agama/auto/leap16.json
The parameter that we used for enyrypted passwords got renamed to "hashedPassword" in this commit:
https://github.com/agama-project/agama/commit/50885f598545a89abd4b64c7b67b6125e9e6a9d5
This quick fix renames the parameter in our agama/auto profiles.
> Quickfix for agama_auto password problem

- lib/Yam/Agama/Pom/AgamaUpAndRunningPage.pm
- Fix sporadic issue: https://openqa.suse.de/tests/16209278#
- Verification runs: [20 x sles_default_unattended](https://openqa.suse.de/tests/overview?version=agama-10.0&distri=sle&build=jknphy%2Fos-autoinst-distri-opensuse%23bump-timeout2)
> Bump timeout for refreshing repos in Agama unattended

- schedule/functional/extra_tests_textmode.yaml
- tests/console/velociraptor_client_event_collect.pm
Related ticket:
Needles: NO
SLE15SP6
x86_64   https://openqa.suse.de/tests/15911376
aarch64 https://openqa.suse.de/tests/15910662
s390x  https://openqa.suse.de/tests/15910658
SLE15SP5
x86_64   https://openqa.suse.de/tests/15910664
aarch64 https://openqa.suse.de/tests/15910662
s390x  https://openqa.suse.de/tests/15910663
SLE15SP4
x86_64  https://openqa.suse.de/tests/15911495
aarch64 https://openqa.suse.de/tests/15911498
s390x https://openqa.suse.de/tests/15929198
SLE12SP5
x86_64 https://openqa.suse.de/tests/16049489  
aarch64 https://openqa.suse.de/tests/16049531
s390x https://openqa.suse.de/tests/16049943
opensuse-Tumbleweed
x86_64 https://openqa.opensuse.org/tests/4706567
aarch64 https://openqa.opensuse.org/tests/4708620
> Add client event tests

- data/autoyast_sle15/create_hdd/create_hdd_pcm_aws_aarch64.xml
- data/autoyast_sle15/create_hdd/create_hdd_pcm_aws_ppc64le.xml
- data/autoyast_sle15/create_hdd/create_hdd_pcm_aws_s390x.xml
- data/autoyast_sle15/create_hdd/create_hdd_pcm_aws_x86_64.xml
Service is not defined to be installed and I don't see reason to expect/need
of this service
Warning pop-up is blocking s390x screen to match expected needle for reboot
- Fail: https://openqa.suse.de/tests/16203444
- Verification run: https://openqa.suse.de/tests/16203541#step/installation/7
> Drop bluetooth service in aws ay profile

- tests/installation/bootloader_uefi.pm
The screen 'bootloader-sdboot' should be checked more generically, using the is_bootloader_sdboot version_utils helper.
> bootloader_uefi: Fix sdboot check

- lib/LTP/utils.pm
- tests/kernel/install_ltp.pm
- tests/kernel/run_ltp.pm
Add LTP_REBOOT_AFTER_TEST=1 variable to allow to reboot after each test (needed for certain tests, e.g. IMA).
Related ticket: https://progress.opensuse.org/issues/159045
* https://openqa.suse.de/tests/overview?build=pevik%2Fos-autoinst-distri-opensuse%23LTP_REBOOT_AFTER_TEST 
(NOTE: `ltp_ima_reboot` and `ltp_ima_selinux` fail on sle micro due missing support for installing LTP from git)
* https://openqa.opensuse.org/tests/overview?build=pevik%2Fos-autoinst-distri-opensuse%23LTP_REBOOT_AFTER_TEST
> LTP: Allow to reboot after each test (LTP_REBOOT_AFTER_TEST=1)

- tests/qam-updinstall/update_install.pm
substitue SLES_SAP for LTSS repo because SLE-Product-SLES_SAP_15-SP2 channel is empty when checking rpm binaries.
- Related ticket: https://jira.suse.com/browse/TEAM-9909
https://openqa.suse.de/tests/16209467 (docker on x86_64, PASSED)
https://openqa.suse.de/tests/16210080 (docker on ppc64le, PASSED)
https://openqa.suse.de/tests/16210132 (libsoup, PASSED)
> Substitue SLES_SAP for LTSS repo

- lib/qesapdeployment.pm
Replaces the built-in, generously privileged IAM role we used for Azure Native Fencing with a less privileged custom role we have defined.
Custom role for Azure native fencing is described here: https://learn.microsoft.com/en-us/azure/sap/workloads/high-availability-guide-suse-pacemaker?tabs=msi#1-create-a-custom-role-for-the-fence-agent
- Related ticket: https://jira.suse.com/browse/TEAM-9698
MSI:
https://openqa.suse.de/tests/16203411
https://openqa.suse.de/tests/16203481
https://openqa.suse.de/tests/16203482
https://openqa.suse.de/tests/16203483
https://openqa.suse.de/tests/16203484
https://openqa.suse.de/tests/16203485
https://openqa.suse.de/tests/16203486
https://openqa.suse.de/tests/16203528
https://openqa.suse.de/tests/16203529 …
> Change native fencing IAM role

- lib/Utils/Logging.pm
Collection of rpmnew files searches the whole root filesystem for matching files. This can take time. This commit increases the timeout for this step from the default of 30 seconds to 5 minutes to avoid openQA jobs failing while collecting logs.
- Related failure: https://openqa.suse.de/tests/16209580#step/bci_test_podman/200
- Verification run: https://openqa.suse.de/tests/16211560 (expected to fail, but log collection works properly)
> Increase timeout for finding rpmnew files

- tests/containers/bci_collect_stats.pm
Pulling can take some time, so let's increase the timeout.
- Related failure: https://openqa.suse.de/tests/16214104#step/bci_collect_stats/8
- Verification run: Can't schedule because I'm hitting a Rate limit error
> Increase timeout for podman pull

- lib/Utils/Logging.pm
This occasionally times out, so let's increase the timeout.
- Related failure: https://openqa.suse.de/tests/16213839#step/bci_test_podman/225
- Verification run: https://openqa.suse.de/tests/16214959 (failure is expected, problem collection works as expected)
> Increase timeout for broken symlinks

- lib/version_utils.pm
- tests/installation/agama_reboot.pm
- tests/installation/ipxe_install.pm
- variables.md
https://progress.opensuse.org/issues/173758
aarch64: http://10.200.129.6/tests/81288
x86_64: 
[root disk: sda](https://openqa.suse.de/tests/16210187)
[root disk: nvme0n1](https://openqa.suse.de/tests/16210189)
**Now vnc console access during the installation has some problems, see https://progress.opensuse.org/issues/170434**
So adding some workarounds to configure the serial console and root ssh login before rebooting the host from harddisk after installation
**Currently, we are still in early phase of agama, so some new changes are expected in next few weeks**
> Enable Agama auto install on Bare Metal server

- data/yam/agama/auto/default_sap.json
- data/yam/agama/auto/default_sap_no_scc.json
- test_data/yam/agama_sap.yaml
Install SLES for SAP for agama testing. Add an auto profile for sap
installation and a data file to verify sap product.
- Related ticket: https://progress.opensuse.org/issues/173806
- Needles: n/a
- Verification run: [vrs](https://openqa.suse.de/tests/overview?build=chcao_agama&distri=sle&version=agama-10.0)
> Install SLES for SAP for agama testing

- tests/microos/cockpit_service.pm
- tests/microos/patterns.pm
Increase timeout due to timeout failures.
- Related ticket: https://progress.opensuse.org/issues/174181
- Verification run: https://openqa.suse.de/tests/16235380
> Increase timeout in transactional-update install

- tests/installation/ipxe_install.pm
- Remove unnecessary needles from ipxe install for virt tests
- Related ticket: https://progress.opensuse.org/issues/169774
[quinn](https://10.145.10.207/tests/16183230)
[ph052](http://10.200.140.2/tests/580)
[fibonacci](https://10.145.10.207/tests/16183391)
[12sp5_xen_on_shichahai](https://10.145.10.207/tests/16190389)
[bare-metal2](https://10.145.10.207/tests/16190392)
[bare-metal1](https://10.145.10.207/tests/16190394)
[12sp5_kvm_on_blackbauhinia](https://10.145.10.207/tests/16190396)
[Leon's_sle12sp5_xen_ob_on_fabonacci](https://10.145.10.207/tests/16202395)
[Leon's_sle12sp5_kvm_job_on_shichahai](https://10.145.10.207/tests/16202396)
> Remove unnecessary needles from ipxe install for virt tests

- lib/x11test.pm
See ticket poo#168064
- Related ticket: https://progress.opensuse.org/issues/168064
- Needles: already added when debugging on o3 and osd
> TW https://openqa.opensuse.org/tests/4711035#
> SLE15SP7 X11 https://openqa.suse.de/tests/16234988#
> SLE15SP7 Wayland https://openqa.suse.de/tests/16234870#
> Fix ibus failure on TW

- tests/installation/ipxe_install.pm
Quick fix for PR https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/20777
The serial console settings are not correct even no function impact found so far:
`console=ttyS1,115200 linuxrc.log=/dev/ttyS1,115200 linuxrc.core=/dev/ttyS1,115200` 
Correct one should be:
`console=ttyS1,115200 linuxrc.log=/dev/ttyS1 linuxrc.core=/dev/ttyS1`
- Verification run: https://openqa.suse.de/tests/16246503
> Fix serial console settings for agama install

- lib/bootloader_setup.pm
- tests/installation/bootloader_s390.pm
- tests/installation/bootloader_zkvm.pm
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/overview?build=lemon-suse%2Fos-autoinst-distri-opensuse%23ensure-one-agama-auto-parameter&distri=sle&version=agama-10.0
> Ensure only one agama.auto in bootloader parameters

- tests/sles4sap/patterns.pm
This workaround is necessary because adding legacy module on SCC_ADDONS variable does not work on a reliable way.
VR:
https://openqaworker15.qa.suse.cz/tests/308156
https://openqaworker15.qa.suse.cz/tests/308140
> Add legacy module as requirement for package libicu60_2

- schedule/yast/sle/flows/default_s390x_kvm_flavor_full.yaml
Add offline schedule skipping registration for flavor full, QU security tests for s390x.
- Related ticket: https://progress.opensuse.org/issues/174574
- Verification run: https://openqa.suse.de/tests/16247365
> Poo#174574 add s390x full-qu schedule

- tests/containers/host_configuration.pm
Code to enable BCI tests on CentOS 10:
- Remove the `assert` to run `dhclient` as it was removed on CentOS 10 per [documentation](https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/10-beta/html/10.0_beta_release_notes/removed-features#removed-features-networking)
---
- Related ticket: https://progress.opensuse.org/issues/174433
- Verification run: https://openqa.suse.de/tests/16252637
> containers: Enable BCI tests on CentOS 10

- tests/yast2_gui/yast2_security.pm
##
On Aarch64, we need to reset consoles to refresh the x11 console. sometimes the desktop runner will not launch up the password dialog.
- Related ticket: https://progress.opensuse.org/issues/169906
- Needles: N/A
- VR:
- [**run 20 jobs with fix**](https://openqa.suse.de/tests/overview?distri=sle&build=hjlluo_withfix&version=15-SP7)
- [**run 20 jobs without fix**](https://openqa.suse.de/tests/overview?distri=sle&build=hjlluo_no_change&version=15-SP7)
##
> Ensure dialog Password_needed is reached

- schedule/filesystem/xfstests_create_hdd_micro_ppc.yaml
- schedule/filesystem/xfstests_micro_ppc.yaml
Add xfstests to yaml scheduler for microos on ppc
1. Add xfstests_create_hdd
2. Add xfstests
- Related ticket: https://progress.opensuse.org/issues/173953
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/16262132
> filesystem: Add xfstests to yaml scheduler

- lib/Yam/Agama/Pom/AgamaUpAndRunningPage.pm
- schedule/kernel/agama_create_hdd_multipath_textmode.yaml
- tests/installation/agama_multipath.pm
- Needles: https://gitlab.suse.de/openqa/os-autoinst-needles-sles/-/merge_requests/1681
multipath: http://10.100.12.105/tests/516
normal installation: http://10.100.12.105/tests/512
> agama: Add support for multipath confirmation during installation

- schedule/yast/sle/flows/default_aarch64_flavor_full.yaml
Add offline schedule skipping registration for flavor full, QU security tests for aarch64.
- Related ticket: https://progress.opensuse.org/issues/174577
- Verification run: https://openqa.suse.de/tests/16252667
> Poo#174577 add aarch64 full-qu schedule

- data/yam/agama/auto/default_sle.jsonnet
- data/yam/agama/auto/default_sle_no_scc.jsonnet
- Related ticket: [poo#174457](https://progress.opensuse.org/issues/174457)
- Verification run: [sles_default_unattended](https://openqa.suse.de/tests/overview?build=issues-174457)
- Related [PR#20834](https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/20834) about:
> _Ensure only one agama.auto in bootloader parameters_
> Use posts script to enable sshd

- data/journal_check/bug_refs.json
Journal: Spectre LFENCE message in bug-ref.json for sle-micro 5.2 added.
Found this issue in a test impacting a delivery.
After added the new log message to the bugs_ref.json, the issue disappeared in test rerun VR.
- Verification run: https://openqa.suse.de/tests/16264387
-
> journal: Spectre LFENCE message in bug-ref added

- schedule/virt_autotest/kubevirt-tests.yaml
- tests/virt_autotest/kubevirt_tests_server.pm
The variable "SERVER_IP" should be deprecated and removed.
https://openqa.suse.de/tests/16214194#step/kubevirt_tests_server/464
- Related ticket: https://progress.opensuse.org/issues/174514
- Verification run: https://openqa.suse.de/tests/16264066
> Fix getting server ip variable failure

- tests/console/yast2_i.pm
This reverts commit b45fd135cf6922ec316ba503b398e938544c82c3.
This commit have broken the openQA tests in staging (also openQA product test) which is a blocker for the development of Tumbleweed.
- Related ticket: https://progress.opensuse.org/issues/174742
- Verification run: https://openqa.opensuse.org/tests/4729699
> Revert "yast2_i: Add retry to hide dependencies menu"

- tests/autoyast/installation.pm
- Related ticket: https://progress.opensuse.org/issues/174733
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/16290943#step/installation/7
https://openqa.suse.de/tests/16299882# regression test
> Ensure match reboot popup for autoyast test on powerVM

- lib/virt_autotest/kubevirt_utils.pm
- tests/virt_autotest/kubevirt_tests_agent.pm
- tests/virt_autotest/kubevirt_tests_server.pm
Stall failure was occured intermittently while login console after sle-micro rebooting. Increasing grub timeout will solve the issue.
https://openqa.suse.de/tests/16288024#step/kubevirt_tests_server/104
- Related ticket: https://progress.opensuse.org/issues/168622
- Verification run: https://openqa.suse.de/tests/16296594, https://openqa.suse.de/tests/16296603
> Fix intermittent stall failure on slem

- tests/virt_autotest/kubevirt_tests_agent.pm
- tests/virt_autotest/kubevirt_tests_server.pm
Solve the problem of varibale getting a wrong value.
https://openqa.suse.de/tests/16299964#step/kubevirt_tests_server/1
- Related ticket: https://progress.opensuse.org/issues/168622
- Verification run: https://openqa.suse.de/tests/16300055
> Fix the function of set_grub_timeout

- lib/sles4sap_publiccloud.pm
Removing ssh key scan for run method on public cloud library
- Related ticket: https://jira.suse.com/browse/TEAM-9782
- Verification run: https://openqaworker15.qa.suse.cz/tests/308338#
- https://openqaworker15.qa.suse.cz/tests/308833#
> Remove ssh key scan for run method

- data/yam/autoyast/resize_luks2.xml
- tests/autoyast/installation.pm
##
- Related ticket: https://progress.opensuse.org/issues/174736
- Needles: N/A
- [**VR**](https://openqa.suse.de/tests/overview?version=15-SP7&build=hjluo_ay_yast_reboot&distri=sle)
##
> Ensure match reboot for autoyast test on  yast X86_64

- data/journal_check/bug_refs.json
Ignore known error for slem 5.1: kernel: Spectre V2 : Spectre mitigation: LFENCE not serializing, switching to generic retpoline
- Related ticket: [quick pr for this failure](https://openqa.suse.de/tests/16313846#step/journal_check/12)
- Needles: n/a
- Verification run: https://openqa.suse.de/tests/16314045#
> Ignore known error of Spectre-V2-LFENCE for slem 5.1

- lib/containers/engine.pm
The current code doesn't catch JSON exceptions and the content of stderr is never shown.
- Related ticket: https://progress.opensuse.org/issues/174670
- Failing job: https://openqa.opensuse.org/tests/4736980#step/rootless_podman/92
- https://openqa.opensuse.org/tests/4738160#step/rootless_podman/96 (json error)
- https://openqa.opensuse.org/tests/4738160#step/rootless_podman/94 (error output)
> containers: Catch decode_json() exception in engine->info()

- lib/containers/docker.pm
- lib/containers/engine.pm
- lib/containers/podman.pm
- tests/containers/rootless_podman.pm
The `info` method is an over-engineered solution for getting simple information from container runtimes.  Ideally we should get rid of the OOP approach to testing container engines as part of the epic for refactoring these tests.
- Related ticket: https://progress.opensuse.org/issues/152590
- Verification run: https://openqa.opensuse.org/tests/4738395#step/rootless_podman/91 (job failing due to https://github.com/containers/podman/issues/24738)
> containers: Remove info method

- tests/xfstests/install.pm
Ignore installation dependencies of xfstests on ppc64le on microos
- Related ticket: https://progress.opensuse.org/issues/174640
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/16320350
> xfstests: ignore installation dependencies

- schedule/virt_autotest/kubevirt-tests-sles.yaml
For SLES installation, autoyast will be used for kubevirt tests.
- Related ticket: https://progress.opensuse.org/issues/163682
- Verification run: https://openqa.suse.de/tests/16321193, https://openqa.suse.de/tests/16332281
> Using autoyast install for kubevirt tests

- data/yam/autoyast/autoupgrade_with_maintenance_unreleased_updates.xml.ep
- data/yam/autoyast/bug-877438_ix64ph1029.xml
- data/yam/autoyast/bug-879147_autoinst.xml
- data/yam/autoyast/multipath.xml
- data/yam/autoyast/support_images/autoyast_scc_up_maintenance.xml.ep
- data/yam/autoyast/support_images/autoyast_sles12sp5_media_def_patterns_minimal_x86_64.xml
There are some bootloader configurations in autoyast profiles are outdated, make a cleanup for these autoyast profiles.
- Related ticket: https://progress.opensuse.org/issues/169303
- Needles: n/a
- [autoyast/autoupgrade_with_maintenance_unreleased_updates.xml.ep](https://openqa.suse.de/tests/16296562#)
- [autoyast/autoupgrade_with_maintenance_unreleased_updates.xml.ep](https://openqa.suse.de/tests/16296564#)
- [autoyast/bug-877438_ix64ph1029.xml](https://openqa.suse.de/tests/16296557#)
- [autoyast/bug-879147_autoinst.xml](https://openqa.suse.de/tests/16296558#)
- [autoyast/multipath.xml](https://openqa.suse.de/tests/16296559#)
- [autoyast/support_images/autoyast_scc_up_maintenance.xml.ep](https://openqa.suse.de/tests/16296600#)
- …
> Cleanup configration of bootloader for autoyast profiles

- tests/migration/online_migration/zypper_patch.pm
The package of python3-argcomplete-1.9.2-150000.3.8.1 already is synced to SLES15SP6 update repo, so we could remove the workaround that removing the package before migration for bsc#1224249.
- Related ticket: https://progress.opensuse.org/issues/160724
- Needles: n/a
- Verification run: https://openqa.suse.de/tests/16280289#
> Remove workaround for bsc#1224249

- tests/installation/agama_reboot.pm
- tests/installation/bootloader_zkvm.pm
https://openqa.suse.de/tests/16296575
https://openqa.suse.de/tests/16296574
Changes as below:
1. Added `root.password` to boot parameters
2. Activated `agama.auto` and `agama.install_url` in `specific_bootmenu_params`
3. Skipped `remote_install_bootmenu_params` and `registration_bootloader_cmdline` for the time being
4. Force checking agama installer is started
----------------------------------------------------------------------------------------------------------------------------------------------------------------------
**The failed job is known issue https://bugzilla.suse.com/show_bug.cgi?id=1234264**
At the same time, we may need to handle `tests/installation/performing_installation/reconnect_after_reboot.pm:19:    assert_shutdown_and_restore_system('reboot', …
> Add agama installation for s390x kvm

- tests/xfstests/partition.pm
- pNFS is based on nfs4.1. Add version check for pNFS, also add related configuration setting before a test.
- /srv/pnfs_data is the real storage place for pNFS, but the test will not directly on it, and its content will keep updating when nfs mount dir has changes.
- Setup XFSTEST_NFS_VERSION=pnfs could enable pNFS in xfstests
- Check if pnfs enable or not by `cat /proc/self/mountstats | grep pnfs` (When disabled it will shows pnfs=not configured, otherwise it will shows pnfs=LAYOUT_FLEX_FILES)
- Related ticket: https://progress.opensuse.org/issues/168847
1. pNFS test https://openqa.suse.de/tests/16340416
Test run with XFSTEST_NFS_VERSION=pnfs and pNFS is enabled by checking https://openqa.suse.de/tests/16340416#step/partition/51
2. normal nfs test
nfs4.1 …
> xfstests: Support test pNFS

- data/journal_check/bug_refs.json
Softfail in sle15sp3 testing
https://openqa.suse.de/tests/16349728#step/journal_check/2
> Softfail: Spectre mitigation: LFENCE not serializing

- data/virtualization/autoyast/host_12.xml.ep
- data/virtualization/autoyast/host_15.xml.ep
- lib/main_common.pm
- lib/parallel_guest_migration_base.pm
This PR allows SLES MU VT tests to be able to run on both OSD SUTs in OSD test, as well as on PRG1 lab SUTs in openqa.qam.suse.cz.
To be detailed, this PR mainly does below
- Differentiate pxe/ipxe installation based on SUT configuration for that
- if IPXE configured(OSD case), ipxe_install is used
- if no IPXE configured (openqa.qam.suse.cz case), boot_from_pxe is used
Unless customized installation repository is given, it will generate the required repo for installation.
- Erase all disks before installation via host autoyast pre-script
- Fix guest migration issues with OSD SUT which has ipv6 and ipv4 configured
Related ticket: https://progress.opensuse.org/issues/174469
- OSD SUT 15sp6 feature test: https://openqa.suse.de/tests/16291411
- OSD SUT 15sp4 test: …
> [Virtualization][MU]: Support running SLES MU tests on OSD SUTs

- lib/version_utils.pm
SElinux has been enabled by default in new MinimalVM images.
- Verification run: https://openqa.suse.de/tests/16364292#step/firstrun/82
> MinimalVM base on sle16 comes with selinux

- tests/containers/image.pm
Remove assertion when inserting iptables rule.
- Related ticket: https://progress.opensuse.org/issues/173362
- Failing test: https://openqa.opensuse.org/tests/4756699#step/image_podman/43
> containers: Remove assert on iptables rule add

- tests/xfstests/partition.pm
- Related ticket: https://progress.opensuse.org/issues/174973
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/16363133
> xfstests: Handling microos boot on ppc64le

- tests/kernel/install_ltp.pm
Fix poo#175141: Remove Cockpit login message to prevent sporadic login failures in `boot_ltp`.
- Related ticket: https://progress.opensuse.org/issues/175141
SL Micro: https://openqa.suse.de/tests/overview?build=czerw%2Fos-autoinst-distri-opensuse%2320911&distri=sle-micro
SLE: https://openqa.suse.de/tests/overview?version=15-SP6&build=czerw%2Fos-autoinst-distri-opensuse%2320911&distri=sle
> ltp: Remove cockpit login message during installation

- lib/publiccloud/azure.pm
- lib/publiccloud/basetest.pm
- tests/publiccloud/migration.pm
- variables.md
Before we had variable PUBLIC_CLOUD_NO_CLEANUP_ON_FAILURE,
which was ignoring cleanup only when test failing.
But sometimes we need to investigate something even for test
which pass. So this PR will rename variable to
PUBLIC_CLOUD_NO_CLEANUP and drop condition that test failing
VR: http://openqa.suse.de/tests/16393923
> Introduce variable allowing to keep image after test end

- lib/main_publiccloud.pm
should_use_runargs function was missing variables of some tests
which were actually within apropriate check so tests were not executable
VRs : 
http://openqa.suse.de/tests/16405503  ( vs failed on current master https://openqa.suse.de/tests/16365063 ) 
http://openqa.suse.de/tests/16405519 ( vs failed on current master https://openqa.suse.de/tests/16365035 )
> Add missing variables to allow execution

- schedule/security/create_hdd_cc_libyui/aarch64/cc_qr.yaml
- schedule/security/create_hdd_cc_libyui/aarch64/cc_qr_15sp6.yaml
- schedule/security/create_hdd_cc_libyui/s390x/cc_qr.yaml
Modifying the security YAML to work with Full and Online flavor.
- Related ticket: https://progress.opensuse.org/issues/167755
- https://openqa.suse.de/tests/16393933
- https://openqa.suse.de/tests/16381385
- https://openqa.suse.de/tests/16393995
> QU - single yaml for Full and Online s390x and aarch64

- tests/installation/bootloader_uefi.pm
- Related ticket: https://progress.opensuse.org/issues/175216
Multiple consecutive successful verification runs 
SLEM 6.0:
https://openqa.suse.de/tests/16405093
https://openqa.suse.de/tests/16405156
https://openqa.suse.de/tests/16405585
SLEM 6.1:
https://openqa.suse.de/tests/16405026
https://openqa.suse.de/tests/16405590
https://openqa.suse.de/tests/16406840
> Improve GRUB timeout handling for VMware guests

- lib/sles4sap/ipaddr2.pm
- schedule/sles4sap/cloud-components/ipaddr2.yml
- t/22_ipaddr2.t
- tests/sles4sap/ipaddr2/cluster_create.pm
- tests/sles4sap/ipaddr2/configure.pm
- tests/sles4sap/ipaddr2/destroy.pm
- tests/sles4sap/ipaddr2/network_peering.pm
- tests/sles4sap/ipaddr2/patch_system.pm
- tests/sles4sap/ipaddr2/registration.pm
- tests/sles4sap/ipaddr2/sanity_cluster.pm
- tests/sles4sap/ipaddr2/test_move_resource.pm
When runing maintenance testing, doing network peering with IBSM and patch system with incident repo.
Related: https://jira.suse.com/browse/TEAM-9864
VR: 
15-SP5-SapCloud-Azure-Byos-cloud-init: https://openqaworker15.qa.suse.cz/tests/309577#
15-SP6-SapCloud-Azure-Payg-ipaddr2_azure_test_rootless:  http://openqaworker15.qa.suse.cz/tests/309939#
12-SP5-SapCloud-Azure-Payg-ipaddr2_azure_test:  https://openqaworker15.qa.suse.cz/tests/309942#
15-SP3: https://openqaworker15.qa.suse.cz/tests/310054#
> Adapt cloud-init tests to work with IBSm

- lib/bootloader_setup.pm
- Related ticket: https://progress.opensuse.org/issues/174943
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/overview?distri=sle&build=lemon-suse%2Fos-autoinst-distri-opensuse%23expend-variable-in-profile-on-remote-worker&version=agama-10.0
> Expand variables in Agama profile on remote worker

- data/yam/agama/auto/sle_multipath_scc_plain_password.jsonnet
##
- Related ticket: https://progress.opensuse.org/issues/173659
- Needles: N/A
- [prod_multipath](https://openqa.suse.de/tests/overview?distri=sle&version=16.0&build=hjluo_agama_regcode) 
##
> Add multipath profile for prod group

- lib/containers/utils.pm
Fix test issue introduced in https://github.com/os-autoinst/os-autoinst-distri-opensuse/commit/02624a4871ae88d5ad86dd44ec00226dfbf1dc7f
- Related ticket: https://progress.opensuse.org/issues/175245
- Failing test: https://openqa.opensuse.org/tests/4767146#step/containerd_nerdctl/70
- Verification run: https://openqa.opensuse.org/tests/4767171
> containers: nerdctl must skip update test

- data/agama_auto/sle_default.jsonnet
- data/agama_auto/sle_default_ipmi.jsonnet
- data/agama_auto/sle_default_pvm.jsonnet
- data/agama_auto/sle_default_s390x_kvm.jsonnet
- tests/installation/agama_reboot.pm
- tests/installation/ipxe_install.pm
1. Add pre scripts to initialize the disks
2. Handle variables in agama profile
VR:
[pvm](http://openqa.suse.de/tests/16424869)
[ipmi](https://openqa.suse.de/tests/16425016)
> Add pre/post scripts and remove workaround for agama auto install

- tests/publiccloud/registration.pm
Pub.cloud new logs added on `registration` cleanup, credential file also included.
- Related ticket: https://progress.opensuse.org/issues/170437 
- Verification run: see next posts.
> PC new logs added in registration cleanup

- lib/Utils/Logging.pm
The timeout parameter was not passed correctly.
- Related failure: https://openqa.suse.de/tests/16405172#step/bci_test_podman/187
- Verification run: https://openqa.suse.de/tests/16425368 (failure expected)
> Fix timeout parameter

- lib/Utils/Logging.pm
Use `.txt` extension for all logs so we can see them in the browser.
Verification run: https://openqa.suse.de/tests/16425742 (failing for other reason, but we want logs).
> Use .txt extension for all logs

- data/security/openjdk/JCEProviderInfo.java
- lib/openjdktest.pm
- Related ticket: https://progress.opensuse.org/issues/175150
- Needles: n/a
- https://openqa.suse.de/tests/16425408
- https://openqa.suse.de/tests/16425409
- https://openqa.suse.de/tests/16425410
- https://openqa.suse.de/tests/16425411
> Get java test source from data_url instead of github

- lib/sles4sap/ipaddr2.pm
- t/22_ipaddr2.t
- tests/sles4sap/ipaddr2/cluster_create.pm
- tests/sles4sap/ipaddr2/configure.pm
- tests/sles4sap/ipaddr2/destroy.pm
- tests/sles4sap/ipaddr2/network_peering.pm
- tests/sles4sap/ipaddr2/patch_system.pm
- tests/sles4sap/ipaddr2/registration.pm
- tests/sles4sap/ipaddr2/sanity_cluster.pm
- tests/sles4sap/ipaddr2/sanity_os.pm
- tests/sles4sap/ipaddr2/test_move_resource.pm
Move get_vnet from qesap to az library. Rename both create and clean function name. Add argument documentation. Add UT.
- Related ticket: https://jira.suse.com/browse/TEAM-9962
- sle-15-SP6-SapCloud-Azure-Payg-x86_64-BuildLATEST_AZURE_SLE15_6_PAYG-ipaddr2_azure_test_rootless
http://openqaworker15.qa.suse.cz/tests/310445
- sle-15-SP6-SapCloud-Azure-Payg-x86_64-BuildLATEST_AZURE_SLE15_6_PAYG-ipaddr2_azure_test_rootless with IS_MAINTENANCE=1 IBSM_RG=dsdm0we
http://openqaworker15.qa.suse.cz/tests/310388 :green_circle:
> Ipaddr2 network peering az functions.

- tests/network/cifs.pm
The old qam currywurst stand is out of business.
This updates the default host to one where currywurst is still being served.
- Related failure: https://openqa.suse.de/tests/16447221#step/cifs/13
- Verification run: https://openqa.suse.de/tests/16447802#details
> Update currywurst domain

- data/virtualization/autoyast/guest_15.xml.ep
- data/virtualization/autoyast/host_15.xml.ep
Test adaption for 15sp2 ltss extended for TERADATA, add repo as add-on
Related ticket: https://progress.opensuse.org/issues/168535
http://openqa.qam.suse.cz/tests/82756
http://openqa.qam.suse.cz/tests/82755
* Error not affect this commit or tests.
Check repo as ad-on, on hots 15-SP2:
```
lipa:~ # zypper lr | grep LTSS
17 | SLES15-SP2-LTSS-TERADATA                                                                          | SLES15-SP2-LTSS-TERADATA                                | Yes     | (r ) Yes  | Yes
23 | SUSE_Linux_Enterprise_Server_LTSS_15_SP2_x86_64:SLE-Product-SLES15-SP2-Debuginfo-LTSS-Updates     | SLE-Product-SLES15-SP2-Debuginfo-LTSS-Updates           | No      | ----      | ----
24 | SUSE_Linux_Enterprise_Server_LTSS_15_SP2_x86_64:SLE-Product-SLES15-SP2-LTSS-Up …
```
> Add LTSS repo to SLES 15-SP2 teradata

- tests/xfstests/install.pm
Add dependency repo for SLE16
- Related ticket: https://progress.opensuse.org/issues/175257
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/16445504
> xfstests: Add dependency repo for SLE16

- schedule/security/vendor_affirmation_validation_openjdk.yaml
Add vendor affirmation specific openjdk testing schedule, that does not get refactored away.
- Related ticket: https://progress.opensuse.org/issues/175147
SLES: https://openqa.suse.de/tests/16446754
SLED: https://openqa.suse.de/tests/16446824
> Re-add vendor affirmation specific openjdk schedule

- tests/containers/helm_rmt.pm
This PR:
- Fixes bug introduced in https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/20908/commits/5eecb8cf26cd965b1edd487610469ae9dbd99019#diff-e1f7c3621759a0e97dbdfb051c73f42f2feb8540c8768b67ba8072d05900c9e9
- Fixes fail hook
---
- Related ticket: https://progress.opensuse.org/issues/175479
- Verification run: https://openqa.suse.de/tests/16455624
> Fix helm_rmt tests

- tests/containers/podman_quadlet.pm
Fix has_build check for podman_quadlet
- Failing test: https://openqa.suse.de/tests/16458386#step/podman_quadlet/158
- Verification run: https://openqa.suse.de/tests/16463254
> containers: Fix has_build check for podman_quadlet

- lib/power_action_utils.pm
"Shutdown" calls lxqt-leave --shutdown and gracefully exits the desktop enviroment and powers down the machine.  "shutdown" is calling /sbin/shutdown, and isn't in the $PATH of unprivileged users
See: https://bugzilla.opensuse.org/show_bug.cgi?id=1235763
- Verification run: https://openqa.opensuse.org/tests/4779894
> Change to correct shutdown command

- data/virt_autotest/host_unattended_installation_files/agama/sle16.jsonnet
- schedule/virt_autotest/sle16_guest_installation.yaml
- tests/installation/ipxe_install.pm
- tests/virt_autotest/login_console.pm
A sle16 virt test is created in https://openqa.suse.de/group_overview/213. It can help install a sle16 kvm host by running the test. 
This is the first PR. Enhancement is on the way.
What have been done for our virt test:
- Install SLE16 on an ipmi backend baremetal host and wipefs all disks.
- Install kvm patterns on the host with a seperate partition for /var/lib/libvirt/images.
- Config sshd and ssh client on the host.
- persistent journal logging.
What have not been done: 
- ssh keys
- br0
- install system on a specified hard disk
- installed on `quinn`, `fozzie` and `bare-metal5` successfully, but failed on `bare-metal1/3`.
Related ticket: https://progress.opensuse.org/issues/169900
[a_test_on_OSD](https://openqa.suse.de/tests/16425434) …
> Support SLE16 virt test on host installation

- tests/x11/amarok.pm
send_key tag_has_match('foo') ? 'variant1' : 'variant2';
results in the condition 'sendkey tag_has_match' - and its true/false result
would trigger 'variant1' or 'variant2' as 'command'. In perl though, a 'string' on
Its own is simply a true statement:
Wrap the ternary operation properly in parentheses to ensure the result of that
operation is passed down to send_key.
- Related ticket: NONE
- Needles: N/A
- Verification run: https://openqa.opensuse.org/tests/4780021
> amarok: fix syntax for ternary operation

- tests/x11/gnome_control_center.pm
- Related ticket: https://progress.opensuse.org/issues/175365
https://openqa.suse.de/tests/16474798#step/gnome_control_center/9
https://openqa.suse.de/tests/16474781#step/gnome_control_center/9
https://openqa.suse.de/tests/16474792#step/gnome_control_center/9
> gnome_control_center: Try to start again if broken

- tests/publiccloud/run_ltp.pm
LTP tests can be excluded from the pre-define whitelist, using LTP_COMMAND_EXCLUDE or from merged definition of both.
If the whitelist is empty and an user defines LTP_COMMAND_EXCLUDE, the generated skip list is broken.
```
--run-suite cve --skip-tests
'|cve-2016-7042|cve-2016-10044|cve-2017-2618'
```
See:
https://openqa.suse.de/tests/16478633/logfile?filename=serial_terminal.txt
- Verification run: http://kepler.suse.cz/tests/24220#
> Excluding LTP test defintion fix

- schedule/functional/sle16/agama-create-hdd-textmode.yaml
- schedule/functional/sle16/agama-create-hdd-textmode_pvm.yaml
- tests/installation/bootloader.pm
- Related ticket: https://progress.opensuse.org/issues/174685
- Verification run: [build 2.2](https://openqa.suse.de/tests/overview?groupid=620&build=2.2&version=16.0&distri=sle)
**Please ignore the failed jobs, they are known issues**
BTW, s390x jobs are not ready due to https://bugzilla.suse.com/show_bug.cgi?id=1234759
> Enable agama install for qe-core

- lib/bootloader_setup.pm
- tests/yam/agama/import_agama_profile.pm
Failed job: https://openqa.suse.de/tests/16486891#step/import_agama_profile/5
- Related ticket: qucik PR
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/overview?distri=sle&version=16.0&build=lemon-suse%2Fos-autoinst-distri-opensuse%23fix-agama-profile-path-duplicated-issue
> Fix duplicated agama profile path issue

- lib/utils.pm
Reverts os-autoinst/os-autoinst-distri-opensuse#20698
s390x is only in PRG, it's not needed and we need this variable on all workers.
https://gitlab.suse.de/openqa/salt-pillars-openqa/-/merge_requests/958
> Revert "Use REPO_MIRROR_HOST as OPENQA_FTP_URL"

- tests/yam/agama/agama.pm
- Verification run: [tumbleweed_default_TAP](https://openqa.opensuse.org/tests/overview?build=fix-long-name)
> Fix long name in TAP logs

- data/containers/autoyast_containers.xml.ep
Containers: SLE15-SP5 added for LTSS in autoyast. 
15-SP4 included too,in SP range.
- Related ticket: https://progress.opensuse.org/issues/174100
- Verification run: t.b.d., see PR posts.
> Containers SLE15-SP5 added for LTSS

- lib/bootloader_setup.pm
- lib/main_security.pm
- tests/console/enable_mac.pm
Make the jeos-apparmor test work on SELinux enabled Tumbleweed.
Before: https://openqa.opensuse.org/tests/4780101
After: https://openqa.opensuse.org/tests/4784081
Related ticket: https://progress.opensuse.org/issues/168571
Verification runs (using current TW, i.e. still AppArmor):
opensuse-Tumbleweed-DVD-x86_64-Build20250115-container_host_podman_apparmor@64bit: https://openqa.opensuse.org/tests/4784820
opensuse-Tumbleweed-DVD-x86_64-Build20250115-container_host_podman_selinux@64bit: https://openqa.opensuse.org/tests/4784821
This won't fix ^ completely though. I'm not sure how to get enable_mac working with the other YAML_SCHEDULE driven apparmor tests the best way.
> Fix switching from SELinux to AppArmor

- lib/sles4sap/ipaddr2.pm
- t/22_ipaddr2.t
- tests/sles4sap/ipaddr2/configure.pm
- tests/sles4sap/ipaddr2/registration.pm
Rename some ipaddr2 API about registration. Remove API named ipaddr2_registration as it was not performing any registration. Move repo sync out from ipaddr2_scc_addons API.
- Related ticket: https://jira.suse.com/browse/TEAM-9962
sle-15-SP6-SapCloud-Azure-Payg-x86_64-BuildLATEST_AZURE_SLE15_6_PAYG-ipaddr2_azure_test_rootless
-  http://openqaworker15.qa.suse.cz/tests/310707 :green_circle: 
- http://openqaworker15.qa.suse.cz/tests/310809 :green_circle: 
- http://openqaworker15.qa.suse.cz/tests/310708 :red_circle: TEAM-9967
-  http://openqaworker15.qa.suse.cz/tests/310711 :green_circle: 
sle-15-SP5-SapCloud-Azure-Payg-x86_64-BuildLATEST_AZURE_SLE15_5_PAYG-ipaddr2_azure_test_cloud_init
- …
> Rename ipaddr2 reg APIs

- tests/sles4sap/publiccloud/qesap_terraform.pm
Turns the string comparisson used to detect BYOS to case-insensitive
- Related ticket: https://jira.suse.com/browse/TEAM-9933 (sub-task)
https://openqa.suse.de/tests/16494746 (non-capital letters)
https://openqa.suse.de/tests/16494419 (capital letters)
> Make byos check case insensitive

- data/sles4sap/qe_sap_deployment/sles4sap_aws_generic.yaml
Remove the need of SLE_IMAGE_OWNER variable from the qe-sap-deployment conf.yaml named sles4sap_aws_generic.yaml
- Related ticket: https://jira.suse.com/browse/TEAM-9910
sle-15-SP5-HanaSr-Aws-Byos-x86_64-Build15-SP5_2025-01-17T03:03:22Z-hanasr_aws_test_fencing_native ec2_r4.8xlarge
-  http://openqaworker15.qa.suse.cz/tests/310881 :green_circle: terraform is ok
sle-12-SP5-HanaSr-Aws-Payg-x86_64-Build12-SP5_2025-01-17T03:03:22Z-hanasr_aws_test_fencing_native_ltss ec2_r4.8xlarge
- http://openqaworker15.qa.suse.cz/tests/310882 :green_circle: terraform is ok
> Remove SLE_IMAGE_OWNER from sles4sap_aws_generic

- tests/installation/hostname_inst.pm
Hostname not install is expected on 15-SP1 and older
- Related ticket: https://progress.opensuse.org/issues/174373 https://bugzilla.suse.com/show_bug.cgi?id=1166778#c8
- VR: https://openqa.suse.de/tests/overview?distri=sle&build=jpupava_hostname
> hostname_inst: Remove bsc#1166778 soft fail

- lib/services/nginx.pm
semanage might not be available, install it. Additionally, do not blindly ignore the exit code to catch errors like this. The "already defined" exit is also 0, so this should be fine.
- Failure: https://openqa.opensuse.org/tests/4780102#step/nginx/1
- Verification run: http://10.168.5.231/tests/1635
> lib/services/nginx.pm: Install semanage and do not ignore its exit code

- lib/main_common.pm
- schedule/functional/extra_tests_textmode.yaml
- tests/console/snapper_zypp.pm
- Related ticket: https://progress.opensuse.org/issues/168079
- SLE https://openqa.suse.de/tests/overview?build=cedvid%2Fos-autoinst-distri-opensuse%2320618
- Leap/Tumbleweed https://openqa.opensuse.org/tests/overview?build=cedvid%2Fos-autoinst-distri-opensuse%2320618
> Add snapper-zypp-plugin test

- lib/qesapdeployment.pm
- t/16_qesap_aws.t
- tests/sles4sap/publiccloud/network_peering.pm
- tests/sles4sap/qesapdeployment/test_mirror.pm
In one of the command to create network peering the the IBSm in AWS, the value of a tag Project is needed. Value is the one used during the IBSm deployment. Create a variable to be able to provide it from the external. Variable is named IBSM_PRJ_TAG. Temporary provide a valid default value for it. As soon as all JobGroup will have the variable it needs to be changed to get_required_var without default.
This change fix problem introduced here https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/17202/files#r1922537983
This is exactly what we are already doing in Azure with variable IBSM_RG.
- sle-15-SP6-Qesap-Aws-Byos-x86_64-BuildLATEST_AWS_SLE15_6_BYOS-qesap_aws_ibsmirror_peering_test@64bit -> http://openqaworker15.qa.suse.cz/tests/311311 :green_circle: …
> Add variable for the AWS IBSm project

- scenario-definitions.yaml
- schedule/boot_to_snapshot.yaml
- tests/console/snapper_zypp.pm
Instead of booting into the initial snapshot from installation, run the snapper_zypp module to create some new snapshots which are more relevant in practice. The snapper_zypp module needs a fix to run diff between the correct snapshots.
- Related ticket: https://progress.opensuse.org/issues/175497
Tumbleweed with SELinux, poo#175497 fixed: http://10.168.5.231/tests/1653 (older snapshot, needed custom schedule for repo replacement)
Plain Tumbleweed: http://10.168.5.231/tests/1654
> Fix snapper diff in console/snapper_zypp and use it in boot_to_snapshot

- tests/virt_autotest/libvirt_isolated_virtual_network.pm
- tests/virt_autotest/libvirt_nated_virtual_network.pm
- tests/virt_autotest/libvirt_routed_virtual_network.pm
Refer to https://bugzilla.suse.com/show_bug.cgi?id=1235809#c10,  found that the named service is running on our SLES15+ vm hosts and immediately starts listening on the network interfaces created by libvirt, which prevents dnsmasq from using them.  So, this problem block our OSD virtual network  - nat, round and isolated.  So far we don't have a clear idea of the exact cause of this problem and need to continue to follow bsc#1235809. 
Good news, we have figured out a workaround. Just only stop named.service before create virtual network  - nat, round and isolated. 
I know that this is not a good solution, but in order not to let this problem affect our current osd 15SP7 Virtualization Acceptance tests, we have to use this workaround for the time being and wait until we find the root cause …
> Fix up virt nat network issue on SLES15

- lib/containers/common.pm
- lib/containers/docker.pm
- lib/containers/podman.pm
- lib/wickedbase.pm
- tests/console/libssh.pm
- tests/containers/buildah.pm
- tests/containers/buildx.pm
- tests/containers/ecs_anywhere.pm
- tests/containers/host_configuration.pm
- tests/containers/rootless_docker.pm
- tests/ha/hawk_gui.pm
- tests/rancher/docker_rancher.pm
- tests/rancher/podman_rancher.pm
- tests/rancher/rancher_rke1_master.pm
- tests/rancher/rancher_rke1_worker.pm
Remove the obligatory OS DISTRI argument from the
`install_{podman,docker,buildah}_when_needed` subroutines because with the introduction of SLES16 they are not distinct enough. Now the routines will call `get_os_release themselves` to obtain the necessary information.
* [buildah_testsuite](https://openqa.suse.de/tests/16518940)
* [containerd_tests](https://openqa.suse.de/tests/16518941)
* [docker_cgroupv2_tests](https://openqa.suse.de/tests/16518942)
* [docker_fips_tests](https://openqa.suse.de/tests/16518943)
* [docker_tests](https://openqa.suse.de/tests/16518944)
* [helm_tests](https://openqa.suse.de/tests/16518945)
* [podman_cgroupv2_tests](https://openqa.suse.de/tests/16518946)
* …
> Remove arguments from install_$ENGINE_when_needed

- lib/selinuxtest.pm
- tests/security/selinux/audit2allow.pm
- tests/security/selinux/enforcing_mode_setup.pm
- tests/security/selinux/selinux_setup.pm
- tests/security/selinux/selinux_smoke.pm
- tests/security/selinux/semanage_boolean.pm
- tests/security/selinux/semodule.pm
- tests/security/selinux/sestatus.pm
Currently the SELinux testsuite assumes that the distro does not use SELinux by default and forcibly installs the minimum policy in permissive mode and breaks otherwise. Change it so that it can cope with and properly test distros which use the targeted policy in enforcing mode by default.
- Related ticket: https://progress.opensuse.org/issues/175320
- Verification run: http://10.168.5.231/tests/1663 (TW 20250108 with SELinux by default)
Any other requests for VRs?
> Run SELinux testsuite in enforcing mode if distro has it as default

- lib/publiccloud/provider.pm
Commit a8c705084aa7 ("publiccloud/provider: Retry tf apply with suggested zones") changed the way the `terraform apply` command is called and started using script_output so the output can be parsed later. However, depending on "$?" in the following line is not viable. Use script_run instead and redirect output to a temporary file that can be read later.
Related ticket: https://progress.opensuse.org/issues/175590
- Intentional Failure: https://openqa.suse.de/tests/16537005#step/prepare_instance/136
- Passing Test: https://openqa.suse.de/tests/16537003#step/prepare_instance/125
> publiccloud/provider: Use script_run in terraform_apply

- tests/security/selinux/selinux_setup.pm
- Related ticket: https://progress.opensuse.org/issues/175647
- Needles: n/a
- https://openqa.suse.de/tests/16536143
- https://openqa.suse.de/tests/16536144
- https://openqa.opensuse.org/tests/4798116
- http://10.168.5.231/tests/1668 (thanks to @Vogtinator for the SELinux-Tumbleweed VR)
> Set selinuxtest as base class for selinux_setup

- tests/x11/firefox_audio.pm
Bug bsc#1048271 has status 'RESOLVED WONTFIX'. 
Adapted the test to pass instead of keeping track of the issue with soft-fail.
- Verification run: https://openqa.suse.de/tests/16536015#step/firefox_audio/9
> firefox_audio: Remove bsc#1048271 soft fail

- data/agama_auto/sle_default_ipmi_no_reg.jsonnet
- data/agama_auto/sle_default_no_reg.jsonnet
- data/agama_auto/sle_default_pvm_no_reg.jsonnet
- data/agama_auto/sle_default_s390x_kvm_no_reg.jsonnet
- schedule/functional/sle16/agama-create-hdd-textmode_pvm.yaml
- tests/console/system_prepare.pm
We can not support register the system to proxy scc for now,  so the workaround is:
1. do not register the system during the installation phase
2. use suseconnet command to register the system after the system boots up
VR: 
[x86_64](https://openqa.suse.de/tests/16542094)
[x86_64 uefi](https://openqa.suse.de/tests/16542131)
[aarch64](https://openqa.suse.de/tests/16542142)
[powervm](https://openqa.suse.de/tests/16542321)
> Agama proxy scc workaround for sle16 beta1 install

- lib/hacluster.pm
- lib/saputils.pm
- lib/sles4sap/console_redirection.pm
- lib/sles4sap/database_hana.pm
- lib/sles4sap/sap_host_agent.pm
- schedule/sles4sap/sap_deployment_automation_framework/hana_sr_primary_failover.yml
- t/11_hacluster.t
- t/18_saputils.t
- t/31_sap_host_agent.t
- t/32_database_hana.pm
- tests/sles4sap/redirection_tests/hana_sr_primary_failover.pm
- tests/sles4sap/redirection_tests/hanasr_schedule_tests.pm
- tests/sles4sap/redirection_tests/redirection_check.pm
This PR adds modules and libraries that enable executing variations of Hana 
primary fialover tests. Currently supported failover methods are using command 
'HDB stop' and 'HDB kill -x'. Test allows variats with automatic replica 
registration or without it. 
- Related ticket: https://jira.suse.com/browse/TEAM-9904
AUTOMATED_REGISTER=false https://openqaworker15.qa.suse.cz/tests/310697#
AUTOMATED_REGISTER=true  https://openqaworker15.qa.suse.cz/tests/310699#
> [SDAF] Database failover test

- tests/console/rsync_server.pm
This is necessary to grant the rsync daemon access.
- Related ticket: https://progress.opensuse.org/issues/175890
TW with SELinux: https://openqa.opensuse.org/tests/4799145
TW without SELinux: https://openqa.opensuse.org/tests/4799280
> console/rsync_server: SELinux-aware test directory creation

- lib/qesapdeployment.pm
- lib/trento.pm
- t/08_trento.t
- t/15_qesap_azure.t
- tests/sles4sap/publiccloud/clean_leftover_peerings.pm
Remove qesap_az_get_vnet and replace it with equivalent az_network_vnet_get.
Extend concept from https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/20946/files#diff-c25cf94dbded12cf8e346fd7f8799ab0f03f3440381ebae21ecca66ae9f79028R1994
- sle-15-SP6-Qesap-Aws-Byos-x86_64-BuildLATEST_AWS_SLE15_6_BYOS-qesap_aws_ibsmirror_peering_test@64bit -> http://openqaworker15.qa.suse.cz/tests/311326 :green_circle: 
- sle-15-SP5-EC2-SAP-BYOS-Incidents-x86_64-Build:37072:rpmlint-SAPHanaSR-ScaleUp-PerfOpt-native-stop-kill@ec2_r4.8xlarge -> http://openqaworker15.qa.suse.cz/tests/311408 :green_circle: test is failing but code using changed code is ok (`clean_left_over`, `post_fail_hooks`)
- sle-15-SP5-Azure-SAP-BYOS-Incidents-x86_64-Build:37072:rpmlint-SAPHanaSR-ScaleUp-PerfOpt@az_Standard_E4s_v3 …
> Swap qesap_az_get_vnet  with az_network_vnet_get

- lib/containers/common.pm
SLES12 doesn't have the containers module anymore.
- Related failure: https://openqa.suse.de/tests/16552187
- Related PR: https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/20997
- Verification runs: https://openqa.suse.de/tests/16552521 https://openqa.suse.de/tests/16552522
> Don't active containers module on SLES12

- tests/installation/agama.pm
Handle newly added  Agama dialog to set root password as a firs step after choosing product.
Test run: https://openqa.opensuse.org/tests/4800403#live (passes the problematic part)
> Add check for a set-root-password dialog in agama.pm

- tests/console/redis.pm
- Related ticket: https://progress.opensuse.org/issues/175377
- Verification run: https://openqa.opensuse.org/tests/4785427
-  https://openqa.opensuse.org/tests/4792262
- http://10.146.5.168/tests/553#step/redis/6
> Redis7 conflict resolution

- tests/publiccloud/check_registercloudguest.pm
Increase timeouts when pulling images
- Related ticket: https://progress.opensuse.org/issues/176052
- Verification run: https://openqa.suse.de/tests/16554109 (failing due to other bug)
> publiccloud: Increase timeouts when pulling images

- tests/containers/rootless_podman.pm
The rootless podman test requires the testapi user to be in the systemd-journal group. This commit adds the testapi user to that group, if it hadn't happen before.
- Related failure: https://openqa.suse.de/tests/16545029#step/rootless_podman/34
- Verification runs: [SLES16](https://openqa.suse.de/tests/16554196#step/rootless_podman/1) [Tumbleweed](https://openqa.opensuse.org/tests/4802947#step/rootless_podman/1)
> Add testapi user to systemd-journal if not present

- tests/console/redis.pm
- Related ticket: https://progress.opensuse.org/issues/175377
https://openqa.suse.de/tests/16560442
https://openqa.suse.de/tests/16560443
https://openqa.suse.de/tests/16560445
https://openqa.suse.de/tests/16560447
> redis: Redis7 is available since 15-SP5

- tests/console/btrfs_autocompletion.pm
https://progress.opensuse.org/issues/175881
- Verification run: https://openqa.suse.de/tests/16552380
> Install btrfsprogs-bash-completion for sle16/leap16.0

- schedule/ha/bv/agama_install_sles_ha.yaml
- tests/console/system_prepare.pm
Setup SLES 16 Tests for HA: create_hdd_ha_textmode
TEAM-9960 - Setup SLES 16 Tests for HA
- Related ticket: [TEAM-9960](https://jira.suse.com/browse/TEAM-9960)
Setup SLES 16 Tests for HA
- Related job group: https://openqa.suse.de/admin/job_templates/579?
- Verification run:  https://openqa.suse.de/tests/16542765 (passed)
New VR: after revised code according comments: https://openqa.suse.de/tests/16552154#step/system_prepare/32 (passed)
> Setup SLES 16 Tests for HA

- tests/containers/rootless_podman.pm
The user's local podman's storage configuration is corrupted after OS distro update. In order to fix the database configuration mismatch, it is required to clean up the old entries and let podman to configure the user's settings from the scratch
`Error: database graph driver "" does not match our graph driver
"overlay": database configuration mismatch`
- ticket: [[Containers] test fails in rootless_podman](https://progress.opensuse.org/issues/175866)
- Verification run: http://kepler.suse.cz/tests/24240#step/rootless_podman/44
> Cleanup old podman's storage configuration

- tests/console/btrfs_autocompletion.pm
Don't need to send hot key to exit from current running shell session
- Verification run: http://openqa.suse.de/tests/16561976
> Quick fix for PR 21026

- tests/console/openssl_nodejs.pm
because the patch is already available in the package now
- Related ticket: https://progress.opensuse.org/issues/176112
- Verification run: https://openqa.suse.de/tests/16561942#details
- https://openqa.suse.de/tests/16561943#details
> Don't patch openssl_nodejs test in 15SP4

- tests/x11/vnc_two_passwords.pm
The previous change did not adjust the path for vncserver without the systemd unit.
- Related ticket: https://progress.opensuse.org/issues/176115
SLE 12 SP5: http://10.168.5.231/tests/1709
Tumbleweed: http://10.168.5.231/tests/1710
> x11/vnc_two_passwords.pm: Invoke plain vncserver as regular user

- tests/x11/libreoffice/libreoffice_mainmenu_favorites.pm
Removed the soft-fail for fixed bug.
- Needles: https://gitlab.suse.de/openqa/os-autoinst-needles-sles/-/commit/0a934bf3acfec6a0b5318eea16ea6ea5bb856fec
- Verification run: https://openqa.suse.de/tests/16562003#step/libreoffice_mainmenu_favorites/2
> libreoffice_mainmenu_favorites: Remove bsc#1195836 softfail

- tests/security/swtpm/tpm_selftest.pm
- Related ticket: https://progress.opensuse.org/issues/175563
- Needles: no
- https://openqa.suse.de/tests/16582081
- https://openqa.suse.de/tests/16582082
- https://openqa.suse.de/tests/16582083
- https://openqa.suse.de/tests/16582084
- https://openqa.suse.de/tests/16582085
- https://openqa.suse.de/tests/16582086
- https://openqa.suse.de/tests/16582087
- https://openqa.suse.de/tests/16582088
- https://openqa.suse.de/tests/16582089
- https://openqa.suse.de/tests/16582090
- https://openqa.suse.de/tests/16582227
- https://openqa.suse.de/tests/16582228
- https://openqa.suse.de/tests/16582229
- https://openqa.suse.de/tests/16582230
- https://openqa.suse.de/tests/16582231
- https://openqa.suse.de/tests/16582232
- https://openqa.suse.de/tests/16582233
- …
> Force reload udev rules also on 15-SP7

- lib/main_common.pm
Don't run the YaST2_Lan test on SLES16 where YaST2 is not supported anymore.
* [SLES16](https://openqa.suse.de/tests/16592059) - No YaST test runs
* [SLES15-SP6](https://openqa.suse.de/tests/16592061) - Still contains YaST test runs
* [Tumbleweed](https://openqa.opensuse.org/tests/4811860) - Still contains YaST test runs
> Skip yast2_lan on SLES16

- schedule/sles4sap/installation/agama_install_sles4sap_saptune.yaml
- tests/sles4sap/saptune/mr_test.pm
There is no 'sapconf' in sle16, so remove related operation.
Ticket https://jira.suse.com/browse/TEAM-9969
VRs: https://openqa.suse.de/tests/16561970# 
https://openqa.suse.de/tests/16580407
> Remove sapconf configuration for sle 16

- tests/console/glibc_sanity.pm
Don't test 32bit libc on SLES/Leap 16 because it's not available.
- Related ticket: https://bugzilla.suse.com/show_bug.cgi?id=1236503#c1
- Verification run: https://openqa.suse.de/tests/16594145#step/glibc_sanity/10
> Don't test 32bit on SLES16

- tests/installation/configure_sdboot.pm
This dialog got removed recently.
- Related ticket: https://progress.opensuse.org/issues/175530
- Verification run: https://openqa.opensuse.org/tests/4813560
> installation/configure_sdboot.pm: No longer expect the experimental dialog

- lib/main_common.pm
is_leap requires a minor version as well. Add the minor versions to the is_leap checks where required.
- Related failure: https://openqa.suse.de/tests/16592562
- Related PR: https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/21063
- Verification run: https://openqa.suse.de/tests/16594214
> Quickfix: Fix checks for Leap 16

- data/journal_check/bug_refs.json
- Expected combustion prepare test message
- bsc#1225914 Audit daemon is low on disk space for logging
- bsc#1227908 auditd obsolete built-in options
- vmware ignore bugs
- bsc#1227900 - Speculative Return Stack Overflow
- bsc#1229139 - amd_pstate: the _CPC object is not present in SBIOS
> List of known bugs or to be ignored messages in logs

- lib/version_utils.pm
- t/01_version_utils.t
is_sle("16+") is supported, but is_leap requires 16.0 as version, which has led to multiple breakages in the past. Make the expected input consistent.
Related: https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/21066
No VR, covered by unit tests.
> lib/version_utils.pm: Support short is_leap("16+") without ".0"

- tests/ha/filesystem.pm
This commit allows the `ha/filesystem` test module to format the filesystem for the cluster_md resource test as either an ocfs2 filesystem or a gfs2 filesystem. Support for gfs2 has ben added in the later versions of SLES 15, so this module has been configured to:
- Select ocfs2 by default on SLES 15
- Select gfs2 by default on SLES 16
- Allow the default selection to be overwritten by the setting **HA_CLUSTER_MD_FS_TYPE**
Changes apply only when configuring a cloned filesystem (a filesystem which is active in all nodes of the cluster). Primary/secondary filesystem resources such as drbd will still use xfs.
- Needles: N/A
**Verification runs**
- Default 15-SP7 with ocfs2: [node 1](http://mango.qe.nue2.suse.org/tests/6277#step/filesystem/12), [node …
> Add a test for cluster_md with gfs2

- schedule/yam/agama_lvm_encrypted.yaml
- schedule/yam/agama_lvm_encrypted_s390x.yaml
We have added two new schedules to manage encrypted LVM SLES installation with Agama
This PR need some job group update with specific variables.
- Related ticket: https://progress.opensuse.org/issues/175413
- Needles: N/A
- Related PR: https://github.com/jknphy/agama-integration-test-webpack/pull/75
- x86_64: https://openqa.suse.de/tests/16552790
- aarch64: https://openqa.suse.de/tests/16552946
- ppc64le: https://openqa.suse.de/tests/16552947
- s390x: https://openqa.suse.de/tests/16552856 (Infra error)
> Add Agama interactive installation for encrypted LVM

- tests/sles4sap/qesapdeployment/test_system.pm
- Related ticket: https://jira.suse.com/browse/TEAM-9766
sle-15-SP4-Qesap-Aws-Byos-x86_64-BuildLATEST_AWS_SLE15_4_BYOS-qesap_aws_saptune_test
- http://openqaworker15.qa.suse.cz/tests/312216
sle-12-SP5-Qesap-Aws-Payg-x86_64-BuildLATEST_AWS_SLE12_5_PAYG-qesap_aws_saptune_ltss_test
- http://openqaworker15.qa.suse.cz/tests/312217 :green_circle:  job fails exactly in the same stage, but now the cause is more explicit http://openqaworker15.qa.suse.cz/tests/312217#step/test_system/50
sle-12-SP5-Qesap-Gcp-Payg-x86_64-BuildLATEST_GCE_SLE12_5_PAYG-qesap_gcp_saptune_ltss_test
- http://openqaworker15.qa.suse.cz/tests/312234 :green_circle: http://openqaworker15.qa.suse.cz/tests/312234#step/test_system/50
> Change mode to non-interactive for zypper commands

- data/yam/agama/auto/lvm_encrypted.jsonnet
- schedule/yam/agama_lvm_encrypted_unattended.yaml
- schedule/yam/agama_lvm_encrypted_unattended_ppc64le.yaml
- schedule/yam/agama_lvm_encrypted_unattended_s390x.yaml
- Related ticket: https://progress.opensuse.org/issues/175416
[Verification runs](https://openqa.suse.de/tests/overview?distri=sle&build=rakoenig%2Fos-autoinst-distri-opensuse%23poo175416&version=16.0) :
- still need adaption for `s390x` and `ppc64le` and the VRs for that.
> Add Agama unattended installation for encrypted LVM

- tests/console/procps.pm
Fix regex for top
- Related ticket: https://progress.opensuse.org/issues/174664
- Failing test: https://openqa.opensuse.org/tests/4723309#step/procps/15
- Verification run: https://openqa.opensuse.org/tests/4819879 (failing due to [poo#174667](https://progress.opensuse.org/issues/174667))
> console/procps: Fix regex for top

- tests/console/firewalld.pm
Skip backend test if iptables command not present
- Related ticket: https://progress.opensuse.org/issues/174667
- Failed test: https://openqa.opensuse.org/tests/4723309#step/firewalld/341
- Verification run: https://openqa.opensuse.org/tests/4819957 (failing due to [poo#174664](https://progress.opensuse.org/issues/174664))
> console/firewalld: Skip backend test if iptables command not present

- tests/console/journal_check.pm
- tests/x11/evolution/evolution_prepare_servers.pm
This PR:
- Removes fatality from evolution test
- Renames .log extension to .txt to make it browser-friendly
It makes the next module (mutt, the mail client) fail because the dovecot mail server is failing right now.
---
- Related ticket: https://progress.opensuse.org/issues/176379
- Failing test: https://openqa.opensuse.org/tests/4819957 (the fatality doesn't allow the rest of the tests run)
- Verification run: https://openqa.opensuse.org/tests/4820078 (failing due to https://progress.opensuse.org/issues/176379).
> x11/evolution: evolution test should not be fatal

- lib/sles4sap/database_hana.pm
- lib/sles4sap/sapcontrol.pm
- tests/sles4sap/redirection_tests/hana_sr_primary_failover.pm
- tests/sles4sap/redirection_tests/hana_sr_replica_failover.pm
- tests/sles4sap/redirection_tests/hanasr_schedule_tests.pm
PR is adding test modules and function to enable HanaSR failover test on replication site. Currently supported methods are using 'HDB stop' and 'HDB kill' commands.
- Related ticket: https://jira.suse.com/browse/TEAM-9983
- Verification run: https://openqaworker15.qa.suse.cz/tests/312236
> Replica failover tests

- lib/main_containers.pm
It's omitted on SLE < 16 already, omit it on Leap < 16 as well.
- Related ticket: https://progress.opensuse.org/issues/176298
- Verification run: http://10.168.5.231/tests/1737
> lib/main_containers.pm: Omit podman_quadlet on Leap as well

- data/wsl/UpdateInstall.ps1
- lib/windowsbasetest.pm
- schedule/wsl/install/create_windows_image.yaml
- tests/wsl/install/update_windows.pm
The existing Windows Update script is failing to run on Windows 24H2 due to deprecation within the Windows Update Agent API. This necessitates the development of a new script compatible with the updated API.
- Related ticket: https://progress.opensuse.org/issues/176097
- Needles:
- https://github.com/os-autoinst/os-autoinst-needles-opensuse/blob/master/boot_windows-windows-screensaver-20250129.png
- https://github.com/os-autoinst/os-autoinst-needles-opensuse/blob/master/windows-edge-welcome-20250127.png
- https://github.com/os-autoinst/os-autoinst-needles-opensuse/blob/master/windows-setup-browser-20250131.png
- https://openqa.suse.de/tests/16615654#
- https://openqa.suse.de/tests/16624541
- https://openqa.suse.de/tests/16624538
> New script for updating Windows.

- schedule/security/create_hdd_cc_libyui/aarch64/cc_qr_15sp6.yaml
- Related ticket: https://progress.opensuse.org/issues/175644
- https://openqa.suse.de/tests/16625406
- https://openqa.suse.de/tests/16625550
- https://openqa.suse.de/tests/16625777
(fails for another reason addressed in separate ticket)
> Enable offline (install media) repos on full-QR installation

- .github/CODEOWNERS
Related ticket: https://progress.opensuse.org/issues/175701
We can't add @fsimorda due to missing access rights. Tracked in https://progress.opensuse.org/issues/176397
> Add Codeowner Metadata for the Security Squad

- lib/publiccloud/utils.pm
is_byos is a PC utils lib checking content of FLAVOR against a regexp. Change this test to be case in-sensitive.
Related ticket: https://jira.suse.com/browse/TEAM-9933
- sle-15-SP5-HanaSr-Aws-Byos-x86_64-Build15-SP5_2025-01-31T03:03:19Z-hanasr_aws_test_fencing_native -> http://openqaworker15.qa.suse.cz/tests/312343 :green_circle: `qesap_ansible` test module is pass and registration playbook is correctly configured in http://openqaworker15.qa.suse.cz/tests/312343/file/deploy_qesap_terraform-sles4sap_aws_generic.yaml
> Change is_byos to case insensitive

- data/yam/agama/auto/lvm_encrypted.jsonnet
- needed on PowerVM because it might reuse previously encrypted partitions.
- Verification run: https://openqa.suse.de/tests/16639802
> Quickfix for wiping filesystems before installing

- tests/console/redis.pm
redis is redis7 version on 15-SP7
- Related ticket: https://openqa.suse.de/tests/16624355#step/redis/1
- Verification run: https://openqa.suse.de/tests/16640122#step/redis/4
> redis: Don't add redis7 on 15-SP7

- data/autoyast_sle12/create_hdd/create_hdd_sap_sles.xml.ep
- data/yam/autoyast/sles12sp5_create_hdd_gnome_unregistered_no_self_update_s390x.xml.ep
- data/yam/autoyast/support_images/autoyast_sles12sp5_media_def_patterns_minimal_x86_64.xml
- data/yam/autoyast/support_images/create_hdd_ha_sles.xml.ep
- data/yam/autoyast/support_images/create_hdd_sap_textmode_sles.xml.ep
- data/yam/autoyast/support_images/sles12sp5_install_all_patterns_s390x.xml
- data/yam/autoyast/support_images/sles12sp5_install_default_patterns_s390x.xml
- data/yam/autoyast/support_images/sles15sp6_install_textmode_hpc_x86_64.xml
##
- Related ticket:  https://progress.opensuse.org/issues/169681
- Needles: N/A
-  [12sp5_supp](https://openqa.suse.de/tests/overview?build=hjluo_ay_tidy&distri=sle&version=12-SP5)
##
> Simplify AutoYaST profiles for sles12sp5 support image

- lib/hacluster.pm
- lib/sles4sap.pm
SLE 16 will not come with YaST, so our tests should not even attempt to collect y2logs when running in those versions.
- Needles: N/A
> Disable calls of upload_y2logs on SLE 16

- tests/containers/bci_prepare.pm
An `LTSS container` shall run only on sle `LTSS host` with egistration activated, _otherwise_ _stop_.
- Related ticket: https://progress.opensuse.org/issues/175938 
- https://openqa.suse.de/tests/16646641 
FAIL: as expected, non-sle host and LTSS container
- https://openqa.suse.de/tests/16646636 
PASS: LTSS host and LTSS container
> BCI: LTSS containers testing on LTSS hosts only

- tests/kernel/install_ltp.pm
LTP tests fail to create a lease file as the directory tree is missing. https://openqa.suse.de/tests/16605553#step/install_ltp/159
Package `kea` is the new implementation of dhcp
* [sle 16.0](https://openqa.suse.de/tests/16649109#live)
> Skip dhcp configuration for sle 16.0

- tests/sles4sap/ase_install.pm
wget is not currently included on the default SLE16 installation.
- Related ticket: TEAM-9973
- Verification run: https://openqa.suse.de/tests/16649259#
The verification run is failing in the SAP ASE installation on a known bug (bsc#1236235)
> Install wget during ASE installation on SLE16

- tests/microos/disk_boot.pm
The issue is not happening on 6.0 and never, but on UEFI generally, same as aarch64 or ppc64le which are slower and miss the short grub2 timeout IMO same is done here for ppc64le
https://github.com/os-autoinst/os-autoinst-distri-opensuse/blob/master/lib/opensusebasetest.pm#L440
- Related ticket: https://progress.opensuse.org/issues/175884 [6.1 few months ago](https://openqa.suse.de/tests/15296462#step/disk_boot/1) [5.3](https://openqa.suse.de/tests/16646624#next_previous) [5.4](https://openqa.suse.de/tests/16644049#next_previous)
- Verification run: https://openqa.suse.de/tests/overview?distri=sle-micro&build=jpupava_uefi
> disk_boot: Don't wait grub2 also on UEFI

- tests/security/vsftpd/lftp.pm
Changes:
- Change hash comparison logic
- Replace md5 with sha256 for FIPS compliancy
Links:
- Related ticket: https://progress.opensuse.org/issues/176607
- Verification run: https://openqa.suse.de/tests/16671340
> Improve lftp test

- tests/console/snapper_zypp.pm
Fixed the capture of snapshot ID. The test was failing in [svirt-xen-hvm](https://openqa.suse.de/tests/16614248#step/snapper_zypp/12) environment because the output of `snapper ls` included unwanted BTRFS info.
- Related ticket: https://progress.opensuse.org/issues/176199
- SLE https://openqa.suse.de/tests/overview?build=cedvid%2Fos-autoinst-distri-opensuse%2321075
- openSUSE https://openqa.opensuse.org/tests/overview?build=cedvid%2Fos-autoinst-distri-opensuse%2321075
> Fix snapshot ID capture in snapper_zypp test

- tests/console/zypper_lifecycle.pm
Not important bug and will be likely not fixed
- Related ticket: https://progress.opensuse.org/issues/167602
- Verification run: https://openqa.suse.de/tests/16664765
> zypper_lifecycle: Info instead of soft fail

- tests/console/clamav.pm
- Related ticket: https://openqa.suse.de/tests/16679589#step/clamav/39
https://openqa.opensuse.org/tests/4835193#step/clamav/23 o3
https://openqa.suse.de/tests/16680257#step/clamav/35 osd
> clamav: Use repo/fixed to avoid cleanup

- lib/main_common.pm
- lib/y2_installbase.pm
- tests/installation/enable_apparmor.pm
- tests/installation/enable_selinux.pm
On distros which default to SELinux during installation, provide a way to switch to AppArmor.
- Related ticket: https://progress.opensuse.org/issues/166613
- Needles: Already added (https://github.com/os-autoinst/os-autoinst-needles-opensuse/commit/4d6833394b396c981c7a860721473dc6778b05b9)
TW with SELinux by default (Staging:D): http://10.168.5.231/tests/1732 (KDE) http://10.168.5.231/tests/1742 (textmode)
TW with AppArmor by default (current snapshot in QA): http://10.168.5.231/tests/1733
> Add installation/enable_apparmor module and run it if SELINUX=0

- tests/security/vsftpd/lftp.pm
The code would try to compare matching hashes with the file path included, always resulting in a failure. This change extracts only the hash itself from the sha256sum output. Furthermore, the logic for hash checking now marks the test as failed, when the hashes do not match, indicating a problem with the transfer, which would otherwise get overlooked.
- Related ticket: https://progress.opensuse.org/issues/176607
- Verification run: https://openqa.suse.de/tests/16680214#step/lftp/12
> Fix hash comparison

- tests/containers/bci_prepare.pm
In BCI test preparation, for LTSS versions printed the suseconnect status to improve eventual debugging.
- Related ticket: https://progress.opensuse.org/issues/175938
- Verification run: https://openqa.suse.de/tests/16680578#step/bci_prepare/45
> BCI_prepare registration status showed for debug improvement

- lib/main_common.pm
MinimalVM Cloud images come without firewalld so we need to skip the firewall enabled test there.
- Related: https://suse.slack.com/archives/C02CAFDT3MY/p1738838353392139
* [SLES16 MinimalVM-Cloud](https://openqa.suse.de/tests/16681198#) (no `firewall-enabled` test)
* [SLES16 MinimalVM-kvm-and-xen](https://openqa.suse.de/tests/16681200#details) (`firewall-enabled` test present)
> Skip firewalld on Cloud image

- tests/jeos/firstrun.pm
Ticket: https://progress.opensuse.org/issues/166175
Fixes: https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/19964
> Fix firstrun for user being created by dependency job

- tests/publiccloud/flavor_check.pm
The file-log entry in previous tests was a simple string. But since [last re-runs](https://openqa.suse.de/tests/16670825#step/flavor_check/20) that log resulted to contain  time informations too on the left so that the comparison expression _no more matching the line beginning_(`^`), but end only(`$`). Therefore regexp has been updated and same consideration applied to both flavor types.
- Related ticket: https://progress.opensuse.org/issues/176718
- Verification run: https://openqa.suse.de/tests/16686283
> Pub. cloud instance-flavor-check log regexp updated

- tests/network/autofs_server.pm
Removing soft_failure and recording info instead as the bug only happens in openQA.
https://bugzilla.suse.com/show_bug.cgi?id=1215649
VR: https://openqa.suse.de/tests/16694450
Related ticket: https://progress.opensuse.org/issues/174988
> autofs_server: Remove soft-fail bsc#1215649

- lib/klp.pm
- tests/kernel/qa_test_klp.pm
SLE Micro 6.0+ has livepatches included in the base product. Update livepatching infrastructure tests to support transactional systems and fix package versioning quirks.
- Related ticket: https://progress.opensuse.org/issues/176406
- Needles: N/A
- SLE-Micro 6.0 x86_64: https://openqa.suse.de/tests/16671249
- SLE-Micro 6.0 s390x: https://openqa.suse.de/tests/16684419
- SLE-12SP5 x86_64 KOTD: https://openqa.suse.de/tests/16694678
- SLE-15SP6 x86_64: https://openqa.suse.de/tests/16694673
- SLE-15SP6 PPC64LE: https://openqa.suse.de/tests/16694671
- SLE-15SP6 s390x: https://openqa.suse.de/tests/16694672
> Add support for transactional systems to kernel livepatching infrastructure tests

- tests/containers/buildah_integration.pm
- tests/containers/podman_integration.pm
- tests/containers/runc_integration.pm
- tests/containers/skopeo_integration.pm
This PR:
- Adds support for OCI_RUNTIME in podman upstream tests
- Minor readability fixes.
---
- runc / skopeo: https://openqa.opensuse.org/tests/4839173
- buildah: https://openqa.opensuse.org/tests/4839148
- podman: https://openqa.opensuse.org/tests/4839219
> Support OCI_RUNTIME in podman upstream tests

- data/virt_autotest/host_unattended_installation_files/agama/sle16.jsonnet
- lib/autoyast.pm
- Set up SSH key with two openqa settings `_SECRET_RSA_PUB_KEY` and `_SECRET_RSA_PRIV_KEY`.
- Fix a typo, see https://progress.opensuse.org/issues/176073
[on_ph052 in BJ](http://10.200.140.2/tests/707)
[on OSD](https://openqa.suse.de/tests/16561646)
@xlai @waynechen55 @guoxuguang @RoyCai7 @martinsmarcelo @nanzhg @tbaev and others, welcome review!
> Allow set up SSH key during Agama installation

- lib/main_common.pm
- tests/console/firewall_enabled.pm
Simplify the code flow for firewalld and make test failures better visible by running a 'die' instead of just marking the module as failed.
- Related failure: https://openqa.suse.de/tests/16663333#step/firewall_enabled/1
- [Tumbleweed](https://openqa.opensuse.org/tests/4836535)
- [MinimalVM SLES16](https://openqa.suse.de/tests/16684331) (unrealted failure)
- [SLES15-SP6](https://openqa.suse.de/tests/16684333)
- [SLES15-SP5](https://openqa.suse.de/tests/16684335)
- [SLES15-SP2](https://openqa.suse.de/tests/16684336)
- [SLES12-SP3](https://openqa.suse.de/tests/16684334)
> Refactor firewalld

- tests/console/cron.pm
- tests/console/journalctl.pm
Enabling back ntp-wait service in `journalctl.pm`  for SLE12 and removing soft-failure for [bsc#1207042](https://bugzilla.suse.com/show_bug.cgi?id=1207042). 
Ensuring that ntp-wait has finished syncing before proceeding to cron testing, otherwise cron won't start.
- Related ticket: https://progress.opensuse.org/issues/175833
- Verification run: https://openqa.suse.de/tests/16696808
> Enable back ntp-wait in journalctl test for SLE12

- lib/version_utils.pm
- t/01_version_utils.t
Drop the check for Staging:D when SELinux is the default MAC in enforcing mode on tumbleweed
- Related ticket: https://progress.opensuse.org/issues/166613
- Needles: N/A
- Verification run: https://openqa.opensuse.org/tests/overview?distri=opensuse&version=Tumbleweed&build=20250204-SELinux&groupid=1
@Vogtinator
> Drop check for Staging:D from has_selinux_by_default

- tests/publiccloud/nvidia.pm
These files might not be present in modern systems, in which a simple check for `lsmod` output is sufficient.
Link: https://bugzilla.suse.com/show_bug.cgi?id=1236824
Verification run: https://openqa.suse.de/tests/16715728
> publiccloud/nvidia: Remove check for /dev/nvidia-* files

- t/01_style.t
Add CI/CD check to avoid uses of plain password on data directory in pull requests
- Related ticket: https://progress.opensuse.org/issues/160334
> Add CI/CD check to avoid uses of plain password on data directory

- data/containers/autoyast_containers.xml.ep
BCI containers LTSS registration missing for SLE12 added in autoyast yaml.
Also already added in OSD _Medium_ proper `SCC_REGCODE_LTSS` for `SLE 12-SP5 Container-Host`.
- Related ticket: https://progress.opensuse.org/issues/175938
> Container host hdd  LTSS registration added for SLE12

- schedule/security/fips/fips_ker_mode_textmode_extra.yaml
- tests/network/samba/samba_adcli.pm
- Related ticket: https://progress.opensuse.org/issues/169954
- Needles: no
- https://openqa.suse.de/tests/16724388
- https://openqa.suse.de/tests/16724389
- https://openqa.suse.de/tests/16724390
- https://openqa.suse.de/tests/16724391
As of 2025-01-30, krb5 + crypto-policies-scripts updates are in our testing already as S:M:37150:359688 (15-SP6). 
Fail 15-SP7 is expected since update has not yet been released.
The variables needed AD_DOMAIN, AD_HOSTNAME, AD_HOST_IP, AD_WORKGROUP are specified at the jobgroup level.
> Schedule samba AD tests also in FIPS mode

- lib/sles4sap_publiccloud.pm
- t/12_sles4sap_publicccloud.t
- tests/sles4sap/publiccloud/qesap_prevalidate.pm
Enhance SAPHanaSR-showAttr version check
- Related ticket: [TEAM-10057](https://jira.suse.com/browse/TEAM-10057) - Latest SAPHanaSR-showAttr drop --version argument
(USE_SAP_HANA_SR_ANGI=true) failed as expected see TEAM-9930 for details
http://openqaworker15.qa.suse.cz/tests/313061#step/qesap_prevalidate/27 (/usr/bin/SAPHanaSR-showAttr)
http://openqaworker15.qa.suse.cz/tests/313061#step/qesap_prevalidate/42 (/usr/bin/SAPHanaSR-showAttr version: 1.2.9)
(USE_SAP_HANA_SR_ANGI='') passed
http://openqaworker15.qa.suse.cz/tests/313062#step/qesap_prevalidate/27 (/usr/sbin/SAPHanaSR-showAttr)
http://openqaworker15.qa.suse.cz/tests/313062#step/qesap_prevalidate/42 (/usr/sbin/SAPHanaSR-showAttr version: 0.162.4)
> Enhance SAPHanaSR-showAttr version check

- tests/security/selinux/semanage_boolean.pm
Fix conditions for expected booleans and restore previous boolean values properly.
Failure: https://openqa.opensuse.org/tests/4847444#step/semanage_boolean/34
- TW DVD: https://openqa.opensuse.org/tests/4848699
- TW JeOS: https://openqa.opensuse.org/tests/4848698
> security/selinux/semanage_boolean: Fix boolean handling

- tests/nfs/install.pm
The latest commit in pynfs change xdrlib to using xdrlib3 and which we don't have both in SLE and openSUSE. Workaround it to git revert this commit before building.
- Related ticket: https://progress.opensuse.org/issues/176907
- Verification run: https://openqa.suse.de/tests/16726916
> pynfs: Don't use xdrlib3

- lib/containers/bats.pm
Add more logs to bats_post_hook useful for debugging.
- Verification run: https://openqa.opensuse.org/tests/4849071 (will fail due to https://bugzilla.opensuse.org/show_bug.cgi?id=1236924 but logs should be visible).
> containers: Add more logs to bats_post_hook

- data/microos/butane/script
- tests/microos/verify_setup.pm
[disk encryption tool](https://github.com/openSUSE/disk-encryption-tool/tree/master) allows users to encrypt their images/drives in during firstboot. Until now, the feature was supported only in jeos-firstboot.
- ticket: https://progress.opensuse.org/issues/176253
- jg: https://github.com/os-autoinst/opensuse-jobgroups/pull/589
* [microos](http://kepler.suse.cz/tests/24372#step/verify_setup/112)
* [tw](http://kepler.suse.cz/tests/24371#step/verify_setup/112)
> Full disk encryption in combustion

- tests/openqa/install/openqa_bootstrap.pm
- selinux enabled : https://openqa.opensuse.org/tests/4845400
- selinux disabled: https://openqa.opensuse.org/tests/4845401
> Enabling httpd_can_network_connect flag

- data/sles4sap/qe_sap_deployment/mr_test_azure.yaml
- data/sles4sap/qe_sap_deployment/qesap_aws.yaml
- data/sles4sap/qe_sap_deployment/qesap_aws_fencing.yaml
- data/sles4sap/qe_sap_deployment/qesap_azure.yaml
- data/sles4sap/qe_sap_deployment/qesap_azure_fencing_msi.yaml
- data/sles4sap/qe_sap_deployment/qesap_azure_fencing_spn.yaml
- data/sles4sap/qe_sap_deployment/qesap_azure_roles.yaml
- data/sles4sap/qe_sap_deployment/sles4sap_aws_generic.yaml
- data/sles4sap/qe_sap_deployment/sles4sap_azure_generic_maintenance.yaml
- data/sles4sap/qe_sap_deployment/sles4sap_azure_generic_uri.yaml
- lib/qesapdeployment.pm
- lib/sles4sap/ipaddr2.pm
- t/09_qesapdeployment.t
- t/15_qesap_azure.t
- t/22_ipaddr2.t
- tests/sles4sap/publiccloud/qesap_terraform.pm
- tests/sles4sap/qesapdeployment/configure.pm
Network peering to IBSm needs, for Azure and AWS deployments, each job to use a different not overlapping network range.
Reuse the Azure algo in AWS deployments. No changes are needed in the function to calculate ranges, only changes are about conf.yaml and other minor changes like rename function removing the az part. Move UT to a generic file from the Azure specific one. Test affected are: qesap regression, HanaSR (both regression and SingleIncident), azure ipaddr2.
- Related ticket: https://jira.suse.com/browse/TEAM-9980
Is not using network peering
sle-15-SP6-Azure-SAP-BYOS-Incidents-saptune-x86_64-Build:37348:dtb-armv7l-sles4sap_gnome_saptune_delete_rename az_Standard_E4s_v3
- http://openqaworker15.qa.suse.cz/tests/313197 :green_circle: 
- …
> Extend net ranges usage to AWS

- lib/containers/bats.pm
- tests/containers/buildah_integration.pm
- tests/containers/podman_integration.pm
- tests/containers/runc_integration.pm
- tests/containers/skopeo_integration.pm
Disable tmpfs on all BATS tests as some subtests seem to ignore the `BATS_TMPDIR` & `TMPDIR` environment variables and tmpfs doesn't support SELinux labels.
- Related ticket: https://bugzilla.opensuse.org/show_bug.cgi?id=1236924
- buildah: https://openqa.opensuse.org/tests/4849871
- podman: https://openqa.opensuse.org/tests/4849872
- runc / skopeo: https://openqa.opensuse.org/tests/4849873
> containers: Disable tmpfs on all BATS tests

- data/yam/autoyast/support_images/sles15sp5_install_gnome_all_patterns_aarch64.xml
- data/yam/autoyast/support_images/sles15sp5_install_gnome_all_patterns_s390x.xml
- data/yam/autoyast/support_images/sles15sp5_install_gnome_all_patterns_x86_64.xml
- data/yam/autoyast/support_images/sles15sp5_install_gnome_default_patterns_aarch64.xml
- data/yam/autoyast/support_images/sles15sp5_install_gnome_default_patterns_s390x.xml
- data/yam/autoyast/support_images/sles15sp5_install_gnome_default_patterns_x86_64.xml
- data/yam/autoyast/support_images/sles15sp5_install_minimal_default_patterns_s390x.xml
- data/yam/autoyast/support_images/sles15sp5_install_minimal_default_patterns_x86_64.xml
- data/yam/autoyast/support_images/sles15sp5_install_textmode_all_patterns_aarch64.xml
- data/yam/autoyast/support_images/sles15sp5_install_textmode_all_patterns_s390x.xml
- data/yam/autoyast/support_images/sles15sp5_install_textmode_all_patterns_x86_64.xml
- data/yam/autoyast/support_images/sles15sp5_install_textmode_default_patterns_aarch64.xml
- data/yam/autoyast/support_images/sles15sp5_install_textmode_default_patterns_s390x.xml
- data/yam/autoyast/support_images/sles15sp6_install_gnome_default_patterns_aarch64.xml
- data/yam/autoyast/support_images/sles15sp6_install_gnome_default_patterns_s390x.xml
- data/yam/autoyast/support_images/sles15sp6_install_gnome_default_patterns_x86_64.xml
- data/yam/autoyast/support_images/sles15sp6_install_minimal_default_patterns_s390x.xml
- data/yam/autoyast/support_images/sles15sp6_install_minimal_default_patterns_x86_64.xml
- data/yam/autoyast/support_images/sles15sp6_install_textmode_all_patterns_aarch64.xml
- data/yam/autoyast/support_images/sles15sp6_install_textmode_all_patterns_s390x.xml
- data/yam/autoyast/support_images/sles15sp6_install_textmode_all_patterns_x86_64.xml
Add ltss to all sles15sp5 support image testsuites' autoyast profiles.
- Related ticket: https://progress.opensuse.org/issues/174910
- Needles: n/a
- Verification run: [sles15sp5](https://openqa.suse.de/tests/overview?version=15-SP5&build=chcao_poo_174910&distri=sle); [sles15sp6](https://openqa.suse.de/tests/overview?build=chcao_poo_174910&distri=sle&version=15-SP6)
- Related mr: https://gitlab.suse.de/qe-yam/openqa-job-groups/-/merge_requests/413
> Add ltss to all sles15sp5 support image testsuites' autoyast profiles

- lib/mm_tests.pm
- tests/security/krb5/krb5_crypt_prepare.pm
This PR is intended to have the needed code in place to run the test on SLE16.
- Related ticket: https://progress.opensuse.org/issues/176385
- Needles: n/a
- Verification run: https://openqa.suse.de/tests/16739157
(VR itself is failing for a known bug, bsc#1237064)
> Adapt krb5 tests for SLE16

- tests/security/check_kernel_config/dm_crypt.pm
Ensure device-mapper is installed before test.
- Related ticket: https://progress.opensuse.org/issues/177030
- SLE16.0: https://openqa.suse.de/tests/16739005
- SLE15.7: https://openqa.suse.de/tests/16739201
- SLE15.6: https://openqa.suse.de/tests/16739270
- SLE15.3: https://openqa.suse.de/tests/16739271
> Install device-mapper package in dm_crypt test

- tests/security/audit/aulastlog.pm
Use a password for the test user that satisfies chpasswd requirements.
Use auditd service even on Tumbleweed.
Ticket: https://progress.opensuse.org/issues/168445
VRs:
TW:     https://openqa.suse.de/tests/16739279
15-SP6: https://openqa.suse.de/tests/16739304
15-SP5: https://openqa.suse.de/tests/16739310
15-SP4: https://openqa.suse.de/tests/16739313
15-SP3: https://openqa.suse.de/tests/16739315
15-SP2: https://openqa.suse.de/tests/16739317
> Fix aulastlog test

- tests/containers/bci_prepare.pm
On 12-SP5 the LTSS subscription [is not printed in the json output](https://bugzilla.suse.com/show_bug.cgi?id=1237089). This commit switches the check to `SUSEConnect -l` where LTSS is present.
- Related ticket: https://progress.opensuse.org/issues/176700
* https://openqa.suse.de/tests/16740717#step/bci_prepare/43
* https://openqa.suse.de/tests/16740719#step/bci_prepare/40
> Check LTSS status from SUSEConnect -l

- lib/main_common.pm
- schedule/yast/opensuse/yast2_ncurses/yast2_ncurses.yaml
- Related ticket: https://progress.opensuse.org/issues/166613
- Needles: N/A
> yast: Do not test apparmor module on selinux enabled system

- data/journal_check/bug_refs.json
These two usually show up together:
sshd-session[1636]: error: mm_request_receive: read: Broken pipe
sshd-session[1636]: error: mm_reap: preauth child terminated by signal 15
They are mostly observed on machine reboots. Even though they are not nice.
they have not shown up in any real issues
- Related ticket: https://bugzilla.opensuse.org/show_bug.cgi?id=1229935
- Needles: N/A
>     journal_check: sshd frequenly reports errors to journal

- lib/virt_autotest/utils.pm
- tests/virt_autotest/virt_utils.pm
Downloading assets from OSD require authentication to achieve CC compliance, refer to https://app.slack.com/client/T02863RC2AC/C02CANHLANP
Related ticket: https://progress.opensuse.org/issues/176589
Solution:  Use ASSET_n to download guest assets.
Add `ASSET_n0` to indicate the path of vm xml file, and `ASSET_n1` for the vm disk file. fg. 
```
ASSET_10=guest_%GUEST_LIST%-fv-def-net_on-host_%DISTRI%-%VERSION%_build%BUILD%_%SYSTEM_ROLE%_%ARCH%.xml 
ASSET_11=guest_%GUEST_LIST%-fv-def-net_on-host_%DISTRI%-%VERSION%_build%BUILD%_%SYSTEM_ROLE%_%ARCH%.disk
```
Advantages:
- No authetication is required.
- It is a more typical use of downloading files from OSD repo. It is safer and faster.
- Don't start the test if there is no guest assets uploaded by its dependency tests.
Disadvantages:
- Need …
> Use ASSET_n to download guest assets for virt tests

- tests/virt_autotest/kubevirt_tests_server.pm
If the similar ip address appears in the same host, it cannot filter out the unique ethernet adapter, refer to the following example. So to fix it, just appending an end character to avoid such case.
```
inet 10.145.10.18/24 brd 10.145.10.255 scope global dynamic noprefixroute eth0
inet 10.145.10.181/24 brd 10.145.10.255 scope global dynamic noprefixroute eth1
```
- Related ticket: https://progress.opensuse.org/issues/177006
- Verification run: https://openqa.suse.de/tests/16741955
> Enhance to filter out the correct ethernet adapter

- tests/xfstests/partition.pm
No firewalld on sles 16, so skip it to workaround.
- Related ticket: https://progress.opensuse.org/issues/176904
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/16750201
> xfstests: skip firewalld setup on SLE16

- schedule/security/fips/fips_ker_mode_gnome.yaml
`schedule/security/fips/fips_ker_mode_gnome.yaml` contains `WE_REQUIRED` instead of `RUN_WE_MODULE_TESTS`, therefore we are not executing some specific tests.
- Related ticket: https://progress.opensuse.org/issues/177135
- Verification run: https://openqa.suse.de/tests/16751918
> Fix WE module variable in scheduling

- tests/nfs/install.pm
This reverts commit 55073f5bd5a3f2addfc77a01b93f8d9b3ac2b2e3.
Problem was fixed upstream:
https://git.linux-nfs.org/?p=cdmackay/pynfs.git;a=commit;h=d80769a2160ca80362aef8f53e41c6d33dc76637
Fixes: https://progress.opensuse.org/issues/176907
Verification run: (still running)
- https://openqa.suse.de/tests/overview?build=revert-pynfs-workaround
- https://openqa.opensuse.org/tests/overview?build=revert-pynfs-workaround
> Revert "pynfs: Don't use xdrlib3"

- lib/klp.pm
The default behavior of transactional-update is to discard all changes and copy the currently mounted snapshot. Add the missing continue flag when installing kernel-default-livepatch so that the command doesn't revert to the previous kernel in update_kernel.
- Related ticket: https://progress.opensuse.org/issues/176406
- Needles: N/A
- install_ltp: https://openqa.suse.de/tests/16752053
- kernel-live-patching: https://openqa.suse.de/tests/16752054
> KLP: Install livepatches without discarding latest snapshot

- lib/publiccloud/basetest.pm
- tests/publiccloud/registration.pm
The goal of this PR is to always upload the same logs in any Public Cloud test.
Related ticket: https://progress.opensuse.org/issues/176898
https://openqa.suse.de/tests/16748065 (with https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/21197/commits/c2cb1f7ecaca22f2b3e587820e2e58f745ad9408 to force a failure)
https://openqa.suse.de/tests/16754159 (QE-SAP)
https://openqa.suse.de/tests/16754192#step/registration/33 (Azure with wrong REGCODE to force a failure in registration.pm)
> Public Cloud: Refactor SUPER post_fail_hook

- lib/containers/bats.pm
- tests/containers/buildah_integration.pm
- tests/containers/podman_integration.pm
- tests/containers/runc_integration.pm
- tests/containers/skopeo_integration.pm
Fix BATS tests on SELinux.
Apply workaround suggested in [podman documentation](https://github.com/containers/podman/blob/main/troubleshooting.md#11-changing-the-location-of-the-graphroot-leads-to-permission-denied)
- Related ticket: https://bugzilla.opensuse.org/show_bug.cgi?id=1236924
- Failed tests:
- buildah: https://openqa.opensuse.org/tests/4851942#external
- podman: https://openqa.opensuse.org/tests/4851946#external
- buildah: https://openqa.opensuse.org/tests/4854743
- podman: https://openqa.opensuse.org/tests/4854744
- runc / skopeo: https://openqa.opensuse.org/tests/4854694
Notes:
- The buildah & podman failed VR's are addressed here:
https://github.com/os-autoinst/opensuse-jobgroups/pull/599
- More work is needed on individual subtests to unskip them.
> containers: Fix BATS tests on SELinux

- lib/containers/bats.pm
Do not fail if `findmnt` fails due to `/tmp` not being a different partition.
Failing test: https://openqa.suse.de/tests/16764527#step/buildah_integration/98
> containers: Do not fail on findmnt

- lib/containers/bats.pm
Run rshared mount command if /tmp is a partition.  Fixes 15-SP7 weirdness where `/tmp` is not a different partition.  Likely a bug.
Failed test: https://openqa.suse.de/tests/16767504#step/skopeo_integration/104
VR: Not needed.  Hotfix.
> containers: Run rshared mount command if /tmp is a partition

- lib/containers/bats.pm
- tests/containers/buildah_integration.pm
- tests/containers/podman_integration.pm
Minor fixes for BATS tests
- Patch `mkdir` in buildah upstream tests to always use `mkdir -p`
- Unconditionally ignore some flaky subtests in podman upstream tests
Related ticket: https://progress.opensuse.org/issues/176190
---
- buildah 15-SP6: https://openqa.suse.de/tests/16771595
- podman 15-SP6: https://openqa.suse.de/tests/16771596
- buildah 15-SP5: https://openqa.suse.de/tests/16776853
- buildah 15-SP4: https://openqa.suse.de/tests/16776855
Note: Any failure will be fixed with the relevant BATS_SKIP option.
> Minor fixes for BATS tests

- lib/selinuxtest.pm
- schedule/security/cc_audit_tests_part2.yaml
- tests/security/selinux/selinux_setup.pm
`selinux_setup` needs special handling for root console on s390x
- Related ticket: https://progress.opensuse.org/issues/176088
- https://openqa.suse.de/tests/16771623
- https://openqa.suse.de/tests/16771625
- https://openqa.suse.de/tests/16771628
- https://openqa.suse.de/tests/16771630
- https://openqa.suse.de/tests/16771631
> Handle CC testing on s390x when ssh root login is disabled

- lib/main_common.pm
- lib/main_micro_alp.pm
- lib/opensusebasetest.pm
- lib/version_utils.pm
- tests/installation/bootloader_uefi.pm
- tests/jeos/firstrun.pm
- tests/transactional/host_config.pm
[grub-bls](https://microos.opensuse.org/blog/2024-10-08-grub2-bls/) is now part of TW and MicroOS images.
- ticket: https://progress.opensuse.org/issues/176280
- VR: [tw with grub-bls without tpm](http://kepler.suse.cz/tests/24395#)
> Kick off for grub-bls testing

- lib/containers/common.pm
- variables.md
Establishes test runs for docker-stable on standard and transactional OpenSUSE-based systems
- Related ticket: [https://progress.opensuse.org/issues/176550](https://progress.opensuse.org/issues/176550)
- Needles: N/A
- Verification run: [https://openqa.suse.de/tests/16741950#step/docker/44](https://openqa.suse.de/tests/16741950#step/docker/44)
Enablement for all SLES versions: https://gitlab.suse.de/qac/qac-openqa-yaml/-/merge_requests/2067
> Add testing for docker-stable

- lib/qesapdeployment.pm
- t/09_qesapdeployment.t
- tests/sles4sap/qesapdeployment/deploy.pm
Issue is about Ansible deployment stage for jobs using
qe-sap-deployment.
Avoid that Ansible error that are not `Failure:` or `Fatal:` result in
false positive. Propagate error to test module.
sle-15-SP6-Qesap-Gcp-Payg-x86_64-BuildLATEST_GCE_SLE15_6_PAYG-qesap_gcp_sapconf_test
- http://openqaworker15.qa.suse.cz/tests/313419 :green_circle: 
sle-15-SP6-Qesap-Azure-Payg-x86_64-BuildLATEST_AZURE_SLE15_6_PAYG-qesap_azure_saptune_test_spn
- http://openqaworker15.qa.suse.cz/tests/313420 :green_circle: 
sle-15-SP6-HanaSr-Aws-Payg-x86_64-Build15-SP6_2025-02-12T03:03:18Z-hanasr_aws_test_fencing_native_crash ec2_r4.8xlarge
- http://openqaworker15.qa.suse.cz/tests/313421
sle-12-SP5-HanaSr-Gcp-Byos-x86_64-Build12-SP5_2025-02-12T03:03:18Z-hanasr_gcp_test_fencing_native_ltss_es …
> Avoid false positive for Ansible failure

- tests/console/vsftpd.pm
[Bug ticket](https://bugzilla.suse.com/show_bug.cgi?id=1176813) is closed, maybe it makes sense to stop tracking the soft-failure.
> vsftpd: Remove soft-fail bsc#1176813

- lib/containers/bats.pm
- tests/containers/buildah_integration.pm
- tests/containers/podman_integration.pm
Install desired OCI runtime in buildah upstream tests to help determine if buildah subtests failures are related to the OCI runtime.
- Tumbleweed: https://openqa.opensuse.org/tests/4860718 (`OCI_RUNTIME=runc`). Fails for unknown reason.
- SLES 15-SP6: https://openqa.suse.de/tests/16805847 (`OCI_RUNTIME=crun`).
> containers: Install desired OCI runtime in buildah upstream tests

- data/journal_check/bug_refs.json
Make the known [bug#1229228](https://bugzilla.suse.com/show_bug.cgi?id=1229228) a softfailure.
- Related failure: https://openqa.suse.de/tests/16797290#step/journal_check/1
- Related bugzilla ticket: https://bugzilla.suse.com/show_bug.cgi?id=1229228
- Verification run: https://openqa.suse.de/tests/16816443#step/journal_check/1
> Add softfailure for bsc#1229228

- tests/containers/run_container_in_k8s.pm
According to
https://kubernetes.io/docs/concepts/workloads/controllers/job/#job-termination-and-cleanup there are option to the manifest which ensures cleanup and termination of jobs. This can help us avoid hanging jobs in the cluster as the number of tests are increasing, especially with regard to BCI runs.
- ticket: https://progress.opensuse.org/issues/177420
> Set kube job termination and cleanup

- tests/containers/buildx.pm
- tests/containers/rootless_docker.pm
- Related ticket: https://progress.opensuse.org/issues/176550
- Needles: N/A
- Verification run: https://openqa.opensuse.org/tests/4863351
> Fix buildx and rootless for docker-stable on Tumbleweed

- tests/ha/vg.pm
Fix test module vg md5sum cmd timed out issue
- Related ticket:  [TEAM-10088 - [15 SP7][HA] "ha_zalpha_node" sporadically fails on test module "vg": command 'md5sum /dev/vg_cluster_md/lv_openqa' timed out](https://jira.suse.com/browse/TEAM-10088)
https://openqa.suse.de/tests/16816855/logfile?filename=autoinst-log.txt
`md5sum` took 3*60+30=210 seconds it verified the code change works.
```
[2025-02-18T11:47:44.672367Z] [debug] [pid:27894] <<< testapi::type_string(string="md5sum /dev/vg_cluster_md/lv_openqa", max_interval=250, wait_screen_change=0, wait_still_screen=0, timeout=30, similarity_level=47)
[2025-02-18T11:47:45.905865Z] [debug] [pid:27894] tests/ha/vg.pm:161 called testapi::assert_script_run
[2025-02-18T11:47:45.906089Z] [debug] [pid:27894] <<< …
```
> Fix test module vg md5sum cmd timed out issue

- lib/main_common.pm
- schedule/jeos/sle/minimalvm-toolchains.yaml
vorbis will not be part of SLES16 so there is no need to test it.
- Related ticket: https://bugzilla.suse.com/show_bug.cgi?id=1236444
* [MinimalVM 16](https://openqa.suse.de/tests/16820744) (libvorbis not scheduled)
* [SLES 15-SP7](https://openqa.suse.de/tests/16820737) (libvorbis scheduled)
* [Tumbleweed](https://openqa.opensuse.org/tests/4864738) (libvorbis scheduled)
> Exclude libvorbis on SLES16+

- lib/xfstests_utils.pm
We frequently encounter timeout issues when "rm /tmp/*". So increase the timeout value to fix this.
- Related ticket: https://progress.opensuse.org/issues/176904
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/16825726#step/btrfs-326/88
> xfstests: fix timeout issue in no heart beat mode

- tests/sles4sap/saptune/mr_test.pm
- tests/sles4sap/saptune/mr_test_run.pm
**MERGE AFTER** https://gitlab.suse.de/qa/mr_test/-/merge_requests/6 
This ticket deals with mr_test errors for sle16, namely removing sapconf and some notes that were 15-specific.
- Related ticket: [TEAM-9969](https://jira.suse.com/browse/TEAM-9969)
- Verification run: https://openqa.suse.de/tests/16804300#details
> Add sle16 config for mr_test

- data/sles4sap/qe_sap_deployment/qesap_aws.yaml
- data/sles4sap/qe_sap_deployment/qesap_aws_fencing.yaml
- data/sles4sap/qe_sap_deployment/qesap_aws_sapconf.yaml
- data/sles4sap/qe_sap_deployment/qesap_azure.yaml
- data/sles4sap/qe_sap_deployment/qesap_azure_fencing_msi.yaml
- data/sles4sap/qe_sap_deployment/qesap_azure_fencing_spn.yaml
- data/sles4sap/qe_sap_deployment/qesap_azure_roles.yaml
- data/sles4sap/qe_sap_deployment/qesap_azure_sapconf.yaml
- data/sles4sap/qe_sap_deployment/qesap_azure_sapconf_no_reg.yaml
- data/sles4sap/qe_sap_deployment/qesap_azure_uri.yaml
- data/sles4sap/qe_sap_deployment/qesap_gcp.yaml
- data/sles4sap/qe_sap_deployment/qesap_gcp_fencing.yaml
- data/sles4sap/qe_sap_deployment/qesap_gcp_sapconf.yaml
- tests/sles4sap/qesapdeployment/configure.pm
Allow to control it in qesap regression test suing an openQA variable Default value is 'default', but the variable allow to use 'optimized' when using HANA SPS8rev82.
- Related ticket: TEAM-10053
sle-15-SP6-Qesap-Gcp-Payg-x86_64-BuildLATEST_GCE_SLE15_6_PAYG-qesap_gcp_sapconf_test
- http://openqaworker15.qa.suse.cz/tests/314625 :green_circle:  not set QESAPDEPLOY_HANA_INSTALL_MODE and use HANA installer SPS7
- http://openqaworker15.qa.suse.cz/tests/314626  :green_circle:  set QESAPDEPLOY_HANA_INSTALL_MODE=optimized and use HANA installer SPS8
sle-12-SP5-Qesap-Gcp-Payg-x86_64-BuildLATEST_GCE_SLE12_5_PAYG-qesap_gcp_saptune_ltss_test
- http://openqaworker15.qa.suse.cz/tests/314633 :green_circle: failure is known issue in RA
sle-12-SP5-Qesap-Aws-Payg-x86_64-BuildLATEST_AWS_SLE12_5_PAYG-qesap_aw …
> allow to control install_execution_mode

- lib/bootloader_setup.pm
In sle12sp5, the gfx parameter is on the third line and not the forth. Move only 2 lines down from the current position of the cursor.
- ticket: https://progress.opensuse.org/issues/177453
- Verification run: [sle-12-SP5-JeOS-for-kvm-and-xen-Updates-x86_64-Build20250218-1-jeos-kdump@64bit-virtio-vga](https://openqa.suse.de/tests/16827375#step/bootloader_uefi/3)
> GFX settings: move only 2 lines down

- lib/sles4sap_publiccloud.pm
- t/12_sles4sap_publicccloud.t
- tests/sles4sap/publiccloud/qesap_terraform.pm
Allow controlling hana_var variable `sap_hana_install_install_execution_mode` from an openQA variable.
Simplify API for create_hana_vars_section and add UT.
- Related ticket: TEAM-10053
sle-15-SP6-HanaSr-Azure-Byos-x86_64-Build15-SP6_2025-02-19T03:03:23Z-hanasr_azure_test_msi az_Standard_E4s_v3
- http://openqaworker15.qa.suse.cz/tests/314759 :green_heart: no `HANA_INSTALL_MODE`. Generated `hana_vars` http://openqaworker15.qa.suse.cz/tests/314759/file/deploy_qesap_terraform-hana_vars.yaml has no `sap_hana_install_install_execution_mode`.
sle-15-SP6-HanaSr-Azure-Byos-x86_64-Build15-SP6_2025-02-19T03:03:23Z-hanasr_azure_test_msi az_Standard_E4s_v3
- http://openqaworker15.qa.suse.cz/tests/314760 `HANA_INSTALL_MODE=optimized` but still use HANA 7rev79. …
> Allow controlling install_execution_mode

- tests/wsl/enable_systemd.pm
- tests/wsl/wsl_cmd_check.pm
- Related ticket: https://progress.opensuse.org/issues/176676
- Needles: https://gitlab.suse.de/openqa/os-autoinst-needles-sles/-/blob/master/welcome-to-wsl-20250219.png
- https://openqa.suse.de/tests/16829323 :green_circle:
- https://openqa.suse.de/tests/16829308 :green_circle: (test fails for different reason)
> A new 'Welcome to WSL' screen breaks the tests

- lib/containers/bats.pm
- tests/containers/buildah_integration.pm
- tests/containers/podman_integration.pm
- tests/containers/runc_integration.pm
- tests/containers/skopeo_integration.pm
Introduce the BATS_URL variables to specify the URL to download the upstream tests.  
This allow us to test PR's against our repos like in https://github.com/SUSE/podman/pull/8
- SLE 15-SP7 podman: https://openqa.suse.de/tests/16832284 (cloned with `PODMAN_BATS_URL=https://github.com/SUSE/podman/archive/refs/heads/backport-testfix-v4.9.5.tar.gz`)
- Tumbleweed runc / skopeo: https://openqa.opensuse.org/tests/4868045
- Tumbleweed buildah: https://openqa.opensuse.org/tests/4868630
Notes:
- We're using full URL instead of split REPO / BRANCH variables because we need to support _both_ tags & branches.
- The URL must not be a `.zip` because it doesn't preserve executable permissions.
- For SLE, we'll eventually use the SUSE repos for podman, buildah, skopeo & runc as …
> containers: Introduce the *_BATS_URL variables

- lib/publiccloud/basetest.pm
Currently, tests that inherit from publiccloud::basetest are not uploading the correct logs to openQA. Fix by calling the helper _upload_logs before the instance gets destroyed and also making sure to use the upload_log subroutine from publiccloud::instance.
- Related ticket: https://progress.opensuse.org/issues/176898
https://openqa.suse.de/tests/16830278
https://openqa.suse.de/tests/16830791#downloads (with incorrect SCC_REGCODE to force a failure)
> publiccloud: basetest: Upload SUT logs instead of host

- lib/version_utils.pm
https://progress.opensuse.org/issues/177456
- Verification run: n/a, please see attachment in ticket above
> Selinux is enabled by default on Leap 16.0

- tests/console/year_2038_detection.pm
[Bug](https://bugzilla.suse.com/show_bug.cgi?id=1188626) status is WONTFIX, removing the soft-failure.
> year_2038: Remove soft failure bsc#1188626

- tests/transactional/trup_smoke.pm
The snapshot is not changed in case sdbootutil re-installs the bootloader in current `trup_smoke` test module. This behavior is aligned with sdboot flavor.
- ticket: https://progress.opensuse.org/issues/176280
- VR: http://kepler.suse.cz/tests/24436
> grub-bls: sdbootutil does not change the snapshot

- tests/sles4sap/sys_param_check.pm
Usefull and needed when there is change of param, because change is happening
on incident until update is merged, until then other tests have to use old value
Update also description
https://dzedro.suse.cz/tests/2433 with repo and branch
https://dzedro.suse.cz/tests/2434 without repo using default main branch
> Add branch option for sys-param repo

- tests/sles4sap/publiccloud/qesap_terraform.pm
Enable call of set_cli_ssh_opts in MR_TEST too.
- Related ticket: https://jira.suse.com/browse/TEAM-10109
sle-15-SP3-Azure-SAP-BYOS-Incidents-saptune-x86_64-Build:37380:dtb-aarch64-sles4sap_gnome_saptune_delete_rename az_Standard_E4s_v3
- http://openqaworker15.qa.suse.cz/tests/315092 :green_circle: 
sle-15-SP5-HanaSr-Azure-Payg-x86_64-Build15-SP5_2025-02-21T03:03:20Z-hanasr_azure_test_msi az_Standard_E4s_v3
- http://openqaworker15.qa.suse.cz/tests/315093 :green_circle: 
sle-15-SP6-Azure-SAP-BYOS-Incidents-x86_64-Build:37545:crmsh-SAPHanaSR-ScaleUp-PerfOpt az_Standard_E4s_v3
- http://openqaworker15.qa.suse.cz/tests/315094 :green_circle:
> Also set ssh_opts in mrtest

- schedule/migration/migration_autoyast.yaml
- schedule/qam/common/mau-extratests2.yaml
- schedule/virt_autotest/sle16_guest_installation.yaml
- tools/check_yaml
A previous commit added a "| grep -v" to strip verbose output, but this
broke exit code propagation. Replace the grep with stdout redirection.
> Make tools/check_yaml return failure again if YAML validation fails

- lib/main_common.pm
- lib/main_micro_alp.pm
- lib/opensusebasetest.pm
- lib/version_utils.pm
- tests/installation/bootloader_uefi.pm
- tests/jeos/firstrun.pm
- tests/transactional/host_config.pm
- tests/transactional/trup_smoke.pm
Bootloader specification is implemented by both `grub2-bls` and `systemd-boot`
> Rename grub2-bls check to be more specific

- tests/qam-updinstall/update_install.pm
The condition was made only for one version, now we have multiple and it's blocking other versions than 15-SP4, simply test TD patch on TD flavor
https://openqa.suse.de/tests/16862495
https://dzedro.suse.cz/tests/2445
> update_install: Fix TD patches

- lib/sles4sap/azure_cli.pm
- t/21_sles4sap_azure_cli.t
Fix command line composition about argument --public-ip-address, avoid adding it more than one.
sle-15-SP6-SapCloud-Azure-Payg-x86_64-BuildLATEST_AZURE_SLE15_6_PAYG-ipaddr2_azure_test_rootless
- http://openqaworker15.qa.suse.cz/tests/315386
> Fix az vm create about public-ip-address

- lib/sles4sap/sap_deployment_automation_framework/deployment.pm
- t/20_sdaf_deployment_library.t
- tests/sles4sap/sap_deployment_automation_framework/execute_playbooks.pm
This PR adjusts current code to work with deployment setups others than Hana SR 
and ENSA2. In final summary it executes only commands that are relevant to the 
deployed scenaio. For example, it won't execute cluster commands on non cluster 
deployments. Additionally it shows simple process overview for netweaver and 
single database instances.
- Related ticket: https://jira.suse.com/browse/TEAM-10063
**Single DB:** https://openqaworker15.qa.suse.cz/tests/315005#step/execute_playbooks/232 :green_circle: 
**Single DB, NW PAS:** https://openqaworker15.qa.suse.cz/tests/315006#step/execute_playbooks/349 :green_circle: 
**HanaSR:** https://openqaworker15.qa.suse.cz/tests/314957#step/execute_playbooks/268 :green_circle: 
**ENSA2**: …
> [SDAF] Fix broken outputs

- schedule/containers/create_hdd_agama.yaml
SLE16 Container host tests preparation with Agama, publish HDD from 
new schedule yaml schedule/containers/create_hdd_agama.yaml
New hdd published from agama-installer.x86_64-*.iso
- Related ticket: https://progress.opensuse.org/issues/175950
- Verification run: https://openqa.suse.de/tests/16870758
> SLE16 Container host tests preparation with Agama

- lib/sles4sap/azure_cli.pm
- lib/sles4sap/ipaddr2.pm
- t/21_sles4sap_azure_cli.t
- t/22_ipaddr2.t
This ticket creates an image out of uploaded vhd disks, in order to create VMs in the case of non-catalog images.
- Related ticket: https://jira.suse.com/browse/TEAM-10095
- Verification run: https://openqaworker15.qa.suse.cz/tests/315392
> Add support for vhd disks in cloudnetconfig test

- tests/containers/buildah_integration.pm
Apply SELinux hack also to tmp_dir (like it's done with podman) & /tmp
- Failed test: https://openqa.opensuse.org/tests/4882444
- Verification run: https://openqa.opensuse.org/tests/4883507
> containers: Apply SELinux hack to tmp_dir

- lib/publiccloud/instance.pm
- tests/publiccloud/check_registercloudguest.pm
Currently, both [failing](https://openqa.suse.de/tests/16882874) and [passing](https://openqa.suse.de/tests/16882884) registration test jobs are not destroying the cloud instances. Fix by adding `test_flags => {fatal => 1}` to the second run of publiccloud/check_registercloudguest.
Make sure that /var/log/cloudregister file is readable before uploading it.
Increase timeout for podman installation.
Improve robustness of log uploading by using script_output_retry in publiccloud/instance::upload_log.
- Related ticket: https://progress.opensuse.org/issues/177814
https://openqa.suse.de/tests/16888779#step/check_registercloudguest#1/365 (Instance destroyed)
> Public Cloud: Increase robustness

- tests/xfstests/partition.pm
Change to use opensusebasetest::firewall() to get the correct firewall service name.
- Related ticket: https://progress.opensuse.org/issues/177627#note-5
- Verification run: (only to make sure partition step works)
- 12SP5: https://openqa.suse.de/tests/16894478#step/partition/2
- 15SP7: https://openqa.suse.de/tests/16894490#step/partition/8
- 16: https://openqa.suse.de/tests/16894497
> xfstests: to get the correct firewall service name

- lib/sles4sap.pm
- t/17_sles4sap.t
- tests/sles4sap/hana_install.pm
Fix how arguments are passed to download_hana_assets_from_server. Improve package management in hana_installer.
- Related ticket: https://jira.suse.com/browse/TEAM-10126
- sle-15-SP7-Online-ppc64le-Build66.1-SAPHanaSR_ScaleUp_PerfOpt_node01@ppc64le-hmc-sap -> http://openqa.suse.de/tests/16888320 :green_circle: 
- sle-15-SP7-Online-ppc64le-Build66.1-SAPHanaSR_ScaleUp_PerfOpt_node02@ppc64le-hmc-sap -> http://openqa.suse.de/tests/16888321 :green_circle: 
- sle-15-SP7-Online-x86_64-Build66.1-create_hdd_sles4sap_gnome@64bit-4gbram -> http://openqa.suse.de/tests/16896663 :green_circle:  here the `zypper in` https://openqa.suse.de/tests/16799153#step/hana_install/16
- sle-15-SP7-Online-x86_64-Build66.1-SAPHanaSR_angi_ScaleUp_PerfOpt_supportserver@64bit-2gbram -> …
> Fix arguments download_hana_assets_from_server

- data/autoyast_hanaperf/agama-config.jsonnet
- schedule/hanaperf/agama_install.yaml
This MR is used for OS installation, by adding jsonnet and yaml schedule to enable HANA perf bare-metal installation
Pending task:
1. Automatically update disk ID according to specific variables 
2. Support more boot parameters like `intel_idle.max_cstate=1`
3. Once https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/21108 got merged, the jsonnet file need be updated for dynamic variables.
- Related ticket: https://jira.suse.com/browse/TEAM-10120
- Needles: N/A
- Verification run: http://openqa.qa2.suse.asia/tests/82812
> Initial hana performance bare-metal installation for sle16

- lib/containers/bats.pm
Rework bats_post_hook to include more logs
- 15-SP5 podman: https://openqa.suse.de/tests/16896797 (will fail, we need to collect the logs)
> containers: Rework bats_post_hook to include more logs

- lib/containers/bats.pm
Remove assert from mkdir as it may fail if another BATS module created it.
- Failed test: https://openqa.suse.de/tests/16900477#step/runc_integration/224
- Verification run: https://openqa.suse.de/tests/16904638
> containers: Remove assert from mkdir

- tests/gnuhealth/gnuhealth_client_first_time.pm
Followup to
https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/19626
```
openqa-clone-custom-git-refspec https://github.com/okurz/os-autoinst-distri-opensuse/tree/fix/gnuhealth https://openqa.opensuse.org/tests/4888103
```
- https://openqa.opensuse.org/tests/4888237
> gnuhealth: Fix mygnuhealth relying on clean desktop

- lib/bootloader_pvm.pm
- lib/bootloader_setup.pm
- lib/registration.pm
- tests/console/system_prepare.pm
- tests/installation/bootloader_zkvm.pm
- tests/installation/ipxe_install.pm
https://progress.opensuse.org/issues/177729
[x86_64-BM](https://openqa.suse.de/tests/16874375)
[powerVM](https://openqa.suse.de/tests/16874374)
```
bare-metal5:~ # suseconnect -s
[{"name":"SUSE Employee subscription for SUSE Linux Enterprise Server x86_64","identifier":"SLES","version":"16.0","arch":"x86_64","status":"Registered","regcode":"xxxxxxxxxxxxx","starts_at":"2024-12-16 12:48:17 UTC","expires_at":"2025-12-16 12:48:17 UTC","subscription_status":"ACTIVE","type":"internal"}]
bare-metal5:~ # zypper lr -u
Repository priorities are without effect. All enabled repositories share the same priority.
--+-----------------------------------------------------------------------+------------------------------+---------+-----------+---------+---------------------------------- …
```
> Add register to proxy scc support for Agama

- lib/sles4sap_publiccloud.pm
Restarts guestregister.service in case of `degraded` system status. Related bug is https://bugzilla.suse.com/show_bug.cgi?id=1238152
- Related ticket: https://jira.suse.com/browse/TEAM-10083
- Verification run: https://openqa.suse.de/tests/16922867#step/Crash_site_b-primary/472
> Add workaround for bsc#1238152

- tests/wsl/enable_systemd.pm
The WSL command line sometimes starts as root and sometimes as `<user>`. I've added a `--user root` flag to prevent this inconsistency.
- Related ticket: https://progress.opensuse.org/issues/177621
- Verification run: https://openqa.suse.de/tests/16905234
> Force to start wsl commandline as root to prevent failures

- tests/containers/helm_rmt.pm
- tests/containers/host_configuration.pm
- variables.md
Make the helm chart configuration obligatory and compact some of the test calls in the module.
Also allow usage of arbitrary helm charts provided via a `oci://` link.
Merge together with https://gitlab.suse.de/qac/container-release-bot/-/merge_requests/397
- Related ticket: https://progress.opensuse.org/issues/177940
- Related PRs: https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/16313 https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/17714
- Verification run: https://openqa.suse.de/tests/16906187#step/helm_rmt/59
> Tidy helm rmt test module

- tests/wsl/install_wsl.pm
After installing from the MS Store with wsl --install --distribution <distro_name>, the firstboot YaST screen is not being launched automatically. Added wsl --d command to proceed to firstboot.
- Related ticket: https://progress.opensuse.org/issues/177769
https://openqa.suse.de/tests/16938233
https://openqa.suse.de/tests/16938231
These test are failing due to new issue further down the line. https://bugzilla.suse.com/show_bug.cgi?id=1237756
However, the problem related to the original ticket is solved, as firstboot YaST is launched correctly after installation.
> Added wsl --distribution command for installation from MSStore

- tests/sles4sap/qesapdeployment/configure.pm
Rename USE_SAP_HANA_SR_ANGI to QESAPDEPLOY_USE_SAP_HANA_SR_ANGI. All the variables in this test module are followith this naming convention. The name is still comparable to the one used in HanaSR test modules.
- Related ticket: https://jira.suse.com/browse/TEAM-9426
sle-15-SP6-Qesap-Azure-Payg-x86_64-BuildLATEST_AZURE_SLE15_6_PAYG-qesap_azure_saptune_test
-  http://openqaworker15.qa.suse.cz/tests/315839
> Change name for the qesap variable about Angi

- tests/virt_autotest/libvirt_isolated_virtual_network.pm
- tests/virt_autotest/libvirt_nated_virtual_network.pm
- tests/virt_autotest/libvirt_routed_virtual_network.pm
Enable the listen-on option in named.conf for dnsmasq new behavior on SLES15SP6+ with UEFI and SEV-ES guest systems. refer to [bsc#1235809](https://bugzilla.suse.com/show_bug.cgi?id=1235809) for more details.
- Related ticket: https://progress.opensuse.org/issues/177354
[uefi-gi-guest_developing-on-host_developing-kvm](https://openqa.suse.de/tests/16919483#) PASS
[uefi-gi-guest_developing-on-host_developing-xen](https://openqa.suse.de/tests/16922184#) PASS
[sev-es-gi-guest_developing-on-host_developing-kvm](https://openqa.suse.de/tests/16922179#) PASS
[sev-es-gi-guest_developing-on-host_sles15sp6-kvm](https://openqa.suse.de/tests/16922180#) PASS
[sev-es-gi-guest_sles15sp6-on-host_developing-kvm](https://openqa.suse.de/tests/16922181#) PASS …
> Enable the listen-on option in named.conf on SLES15SP6+

- tests/sles4sap/ipaddr2/deploy.pm
This pr enables the ipaddr2 test to alternatively use `PUBLIC_CLOUD_IMAGE_LOCATION` instead of `CLUSTER_OS_VER` as the image source.
- Related ticket: https://jira.suse.com/browse/TEAM-9863
- Verification run: https://openqaworker15.qa.suse.cz/tests/315838
For the VR I just cloned a 15sp6 job and set the PUBLIC_CLOUD_IMAGE_LOCATION and PUBLIC_CLOUD_STORAGE_ACCOUNT in the clone command
> Allow ipaddr2 test to use alternative vars for image source

- lib/guest_installation_and_configuration_base.pm
- lib/utils.pm
* **New** subroutine ```render_autoinst_url``` in ```lib/utils.pm``` to render autoinst url from running openQA, in order to avoid direct downloading from openQA instance.
* **Replace** direct openQA address with rendered autoinst url in ```lib/guest_installation_and_configuration_base.pm```.
* [sles15sp7 on sles15sp7](https://openqa.suse.de/tests/16935921)
* [sles12sp5 on sles15sp7](https://openqa.suse.de/tests/16935922)
* [sl micro 6.2 on sl micro 6.2](https://openqa.suse.de/tests/16935919)
* [sles15sp6 on sl micro 6.2](https://openqa.suse.de/tests/16935920)
* [Build5.3 sl micro 6.2 on sl micro 6.2](https://openqa.suse.de/tests/16947412)
* [Build5.3 sles15sp6 on sl micro 6.2](https://openqa.suse.de/tests/16947887)
> Render autoinst url from openQA url

- lib/main_containers.pm
HELM_CONFIG became an optional setting, HELM_CHART is now the obligatory setting for triggering helm test runs.
- Related ticket: https://progress.opensuse.org/issues/177940
- Related MR: https://gitlab.suse.de/qac/container-release-bot/-/merge_requests/397/diffs
> Change schedule from HELM_CONFIG to HELM_CHART

- lib/publiccloud/instance.pm
IP_CHANGE detection in wait_for_ssh, and in particular when executed in AWS or GCP, are suing terraform output to detect public IP change. This technique is not working when used with deployment created by qe-sap-deployment. Skip this code when used in sles4sap tests.
Refinement for https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/21141
- Related ticket: https://progress.opensuse.org/issues/155116
sle-15-SP7-EC2-SAP-BYOS-x86_64-Build0565-ec2_sap_byos_hanasr ec2_r5.8xlarge
- http://openqa.suse.de/tests/16952679
> Disable IP_CHANGE detection for sles4sap

- lib/containers/bats.pm
On SLES16 there are no modules.
- Related failure: https://openqa.suse.de/tests/16954839
- Verification run: https://openqa.suse.de/tests/16954891 (different failure)
> Skip modules on SLES16

- tests/containers/container_engine.pm
Container engine tests are crucial for the whole test runs, as they install the container engines. If they fail it does not make any sense to continue.
Also create a milestone, as otherwise a snapshot would revert to a state before the container engines are installed.
- Related failure: https://openqa.suse.de/tests/16954887#step/docker_runc/43 (because of https://openqa.suse.de/tests/16954887#step/docker_runc/1)
- Verification run: https://openqa.suse.de/tests/16954903
> Make container engine test fatal and milestone

- tests/security/vsftpd/vsftpd.pm
Simple coverage expansion and review of the `vsftpd` test.
Related ticket: https://progress.opensuse.org/issues/178171
SLE 15 SP7:
- aarch64: https://openqa.suse.de/tests/16950772
- s390x: https://openqa.suse.de/tests/16950770
- x86_64: https://openqa.suse.de/tests/16950769
SLE 15:
- SP2: https://openqa.suse.de/tests/16950782
- SP3: https://openqa.suse.de/tests/16950778
- SP4: https://openqa.suse.de/tests/16950777
- SP5: https://openqa.suse.de/tests/16950776
- SP6: https://openqa.suse.de/tests/16938246
> Expand vsftpd test coverage

- lib/bootloader_setup.pm
- tests/installation/ipxe_install.pm
Current openQA codes uses inst.auto, but it is not supported by recent SLE16 build like 49.1 53.2 53.3
and slack discussion: https://suse.slack.com/archives/C082VE1U2F5/p1741020780699299
And workaround for https://bugzilla.suse.com/show_bug.cgi?id=1238581 to unblock bare-metal installation
- Related ticket: https://progress.opensuse.org/issues/178255
- Needles: N/A
http://openqa.qa2.suse.asia/tests/82909
> Workaround for bsc#1238581 to use agama.auto

- tests/nfs/install.pm
to workaround the upstream commit to add v4.1+ st_delegation and st_xattr tests to "all" group. Meanwhile, to file a bug to see if it's an issue https://bugzilla.suse.com/show_bug.cgi?id=1238588
- Related ticket: https://progress.opensuse.org/issues/178288
- Verification run: https://openqa.opensuse.org/tests/4901382
> xfstests: workaround pynfs all fails in NFS4.1 with DELEG

- schedule/ha/bv/agama_install_sles_ha.yaml
- schedule/sles4sap/installation/agama_install_sles4sap.yaml
- schedule/sles4sap/installation/agama_install_sles4sap_saptune.yaml
Need to include the module installation/grub_test before the first_boot for SLE16
https://openqa.suse.de/tests/16960738#step/grub_test/1 (installation/grub_test passed)
> Add installation/grub_test before the first_boot

- tests/jeos/firstrun.pm
The locale setup option is not present in our images any more since jeos-firstboot version 0.0+git20200827.e920a15. As we test only `12sp5` images, and it breaks Cloud@aarch64 image test, we need to update this condition.
- ticket: https://progress.opensuse.org/issues/117412
- opensuse-Tumbleweed-JeOS-for-OpenStack-Cloud-aarch64-Build20250304-jeos-wizard@aarch64 -> https://openqa.opensuse.org/tests/4901962
- sle-15-SP3-JeOS-for-kvm-and-xen-Updates-x86_64-Build20250304-1-jeos-main@uefi-virtio-vga -> https://openqa.suse.de/tests/16960783
- sle-12-SP5-JeOS-for-kvm-and-xen-Updates-x86_64-Build20250221-1-jeos-main@64bit-virtio-vga -> https://openqa.suse.de/tests/16960784
- opensuse-Tumbleweed-JeOS-for-AArch64-aarch64-Build20250303-jeos-container_host@aarch64-HD20G -> …
> Skip locale check except for community and 12sp5 images

- data/yam/agama/auto/sle_root_filesystem_ext4_home_filesystem_xfs.jsonnet
Create ext4 root partition and xfs home partition during installation
- Related ticket: https://progress.opensuse.org/issues/176808
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/16960810
> Add unattended installation with ext4/xfs

- lib/containers/k8s.pm
- tests/containers/helm.pm
On SLES16 there are no modules available.
- Related failure: https://openqa.suse.de/tests/16954802
- Verification run: https://openqa.suse.de/tests/16962960 (fail with unrelated error)
> Skip module installation on SLES16

- data/virtualization/autoyast/host_12.xml.ep
- lib/virt_autotest/utils.pm
- tests/console/login.pm
- tests/virtualization/universal/finish.pm
- tests/virtualization/universal/virtmanager_offon.pm
This PR is to 
- fix the unstable failures on login, finish and virtmanger_offon module when running MU SLES jobs on OSD workers, from multiple jobs, the issues do not happen any more
- revert the [earlier virtual network fix by Leon for name](https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/20938)d, which fails MU jobs like [this](https://openqa.suse.de/tests/16836568#step/libvirt_nated_virtual_network/17) // this has been fixed by https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/21288, so remove the commit
- 12sp5 host installation failure on machine quinn is fixed
Related ticket: https://progress.opensuse.org/issues/175554
- OSD workers
- xen sriov: https://openqa.suse.de/tests/16895954#
- xen feature test: …
> [Virtualization][MU] Fix login, finish,virtmanager_offon module and 12sp5 host installation unstability

- data/virt_autotest/host_unattended_installation_files/agama/sle16.jsonnet
The kvm pattern name was found changed to `kvm_server` and `kvm_tools` at build 57.3.
- Verification run: https://openqa.suse.de/tests/16970973
> Change kvm_host pattern name to kvm_server and kvm_tools

- schedule/jeos/sle/minimalvm-main.yaml
Create new schedule for SLES16, where e.g. YaST will not be present.
- Verification run: https://openqa.suse.de/tests/16971999
> Add new schedule for MinimalVM for SLES16

- schedule/jeos/sle/minimalvm-extratest.yaml
- schedule/jeos/sle/minimalvm-main.yaml
Create a new YAML schedule for SLES16 for extratests and remove not needed tests for SLES16.
- Verification run: https://openqa.suse.de/tests/16973053 (schedule works)
> Add Minimalvm extra schedule for SLES16

- tests/console/check_default_network_manager.pm
On SLES16+ NetworkManager is the default network manager.
- Related failure: https://openqa.suse.de/tests/16969170#step/check_default_network_manager/15
- Verification run: https://openqa.suse.de/tests/16973054#step/check_default_network_manager/13
> Make NetworkManager the default on SLES16

- lib/main_containers.pm
- tests/containers/podman_artifact.pm
- tests/containers/registry.pm
Add test for `podman artifact`
- Related ticket: https://progress.opensuse.org/issues/176586
- podman: https://openqa.opensuse.org/tests/4903666
- podman push/pull: https://openqa.opensuse.org/tests/4903674#step/registry/223
Notes:
- The test for `podman artifact pull` & `push` is done in the registry module.  For some reason this is scheduled in docker tests but it also runs podman.
> containers: Add test for podman artifact

- lib/main_micro_alp.pm
- tests/xfstests/install.pm
1. Add suseconnect_scc before installing xfstests when testing SLMicro products to avoid missing repo and package issues.
2. Meanwhile, lower the dependency repo(packages from SUSE:Factory:Head) priority to 101(the number 1 is the highest priority, the bigger the lower). Then it will lower than default 99 and QA:Head repo 100. If others repo don't have the package then it will start to use this repo.
- Related ticket: https://bugzilla.suse.com/show_bug.cgi?id=1238583#c4
- Verification run: https://openqa.suse.de/tests/16971527
> xfstests: Add suseconnect_scc step in micro tests

- tests/console/year_2038_detection.pm
Might make sense to remove as well soft-fail which points to resolved [poo#127343](https://progress.opensuse.org/issues/127343)
> year_2038: Remove soft-fail poo#127343

- data/virt_autotest/kubevirt_tests/node-helper-patch.yaml
This PR will fix the kubevirt "ctr" command failure on sle-micro 6.2.
Test failures:
```
kubevirt-ci   node-helper-bj55v                                        0/1     Init:CrashLoopBackOff   14 (4m48s ago)   46m
kubevirt-ci   node-helper-ng7bw                                        0/1     Init:CrashLoopBackOff   14 (4m11s ago)   46m
Defaulted container "sleeper" out of: sleeper, helper (init)
Error from server (BadRequest): container "sleeper" in pod "node-helper-bj55v" is waiting to start: PodInitializing
Warning  BackOff         2m37s (x24 over 7m35s)  kubelet            Back-off restarting failed container helper in pod node-helper-bj55v_kubevirt-ci(6f11dd69-5833-4944-99b0-5361382d99d4
+ test -z quay.io/kubevirt/alpine-ext-kernel-boot-demo:v1.2.2
+ /var/lib/rancher/rke2/bin/ctr -a …
```
> Fix pod initializing failure while deploying node-helper daemonset

- tests/sles4sap/publiccloud/hana_sr_takeover.pm
HanaSR test needs some tools provided by ClusterTools2 during the test execution, after the end of the deployment.
There's a `zypper in ClusterTools2` that is executed at the beginning of each test stage. Remove it as tool installation is performed by qe-sap-deployment.
- Related ticket: https://jira.suse.com/browse/TEAM-7830
- sle-15-SP5-HanaSr-Azure-Payg-x86_64-Build15-SP5_2025-03-06T03:03:21Z-hanasr_azure_test_msi@az_Standard_E4s_v3 -> http://openqaworker15.qa.suse.cz/tests/316122
> Stop installing ClusterTools2 multiple times

- schedule/sles4sap/installation/install_sles4sap_pvm.yaml
This schedule file is based on `schedule/sles4sap/saptune_on_pvm.yaml`, the purpose is to do installation test with Full Medium on PowerVM instead of PowerKVM.
- Related ticket: https://jira.suse.com/browse/TEAM-10114
online: https://openqa.suse.de/tests/16982683
offline: https://openqa.suse.de/tests/16982879
> schedule/sles4sap/installation: add installation test on PowerVM

- tests/containers/install_updates.pm
Package tar should be present on the system according to https://bugzilla.suse.com/show_bug.cgi?id=1238784. As of now, we need to workaround the missing binary
- Verification run: http://kepler.suse.cz/tests/24454#
> Package tar is missing

- tests/console/apache.pm
New selinux-policy changes now cause apache service start failure when using port 85. This change sets a  SELinux policy for port 85 when SELinux is enabled.
- Related ticket: https://progress.opensuse.org/issues/178240
- Verification run: https://openqa.opensuse.org/tests/4907057
> Set SELinux policy for port 85

- lib/bootloader_setup.pm
- tests/installation/zdup.pm
product-composer now supports generating repodata directorty per $basearch
Leap 16.0 is already using this feature code-o-o#leap/features#193
This PR adds appends $basearch to the REPO_0 path in case that SPLIT_REPODATA=1 is set. 
- Related ticket: https://code.opensuse.org/leap/features/issue/193
- Verification run for install_url: https://openqa.opensuse.org/tests/4907751#live
- Verification run for zdup: https://openqa.opensuse.org/tests/4907752#live
> Support install_url with split repodata per architecture 

- tests/console/apache.pm
- Related ticket: https://progress.opensuse.org/issues/178240
- Needles: N/A
- Verification run: https://openqa.opensuse.org/tests/4908950
> apache: Ensure "semanage" is installed on JeOS when SELinux managed

- tests/console/apache.pm
* Create the htdocs folder because it's not present without the apache2 package on SLES16.
* Switch to `httpd-prefork` because on Tumbleweed and SLES16 `httpd2-prefork` is not present anymore
- Related failures: https://openqa.suse.de/tests/16961276#step/apache/2
- Verification run: [SLES16](https://openqa.suse.de/tests/16978035#step/apache/1) | [SLES 15-SP6](https://openqa.suse.de/tests/16978036#step/apache/230) | [SLES 12-SP5](https://openqa.suse.de/tests/16999740)
> Fix apache test for SLES16

- lib/main_containers.pm
- tests/containers/netavark_integration.pm
Enable netavark upstream tests on SLE.
Also drop dnsmasq as unneeded in this test.
- TW: https://openqa.opensuse.org/tests/4910054
- 15-SP5: https://openqa.suse.de/tests/16994873
- 15-SP7: https://openqa.suse.de/tests/16994874
- 16.0: https://openqa.suse.de/tests/16994875
Subtest failures are skipped with `NETAVARK_BATS_SKIP` in:
Related MR: https://gitlab.suse.de/qac/qac-openqa-yaml/-/merge_requests/2109
> Enable netavark upstream tests on SLE 15-SP5+

- tests/console/perf.pm
Adds output of hardware and PMU availability to the test run.
- Related ticket: https://bugzilla.suse.com/show_bug.cgi?id=1238885#c2
- Verification run: https://openqa.suse.de/tests/17002647#step/perf/9
> Add perf hardware info

- lib/hacluster.pm
Fix 12sp5 qam-SAPHanaSR_ScaleUp_PerfOpt_node sporadically failed on check_logs: upload_logs timed out  
TEAM-10094 - [On Prem][12sp5] qam-SAPHanaSR_ScaleUp_PerfOpt_node sporadically failed on check_logs: upload_logs timed out
- Related ticket: https://jira.suse.com/browse/TEAM-10094
http://openqa.suse.de/tests/16999564#step/check_logs/12
The fix works when there are extra characters in this test step 
```
FILE=|/var/log/crm_report.tar.bz2|
[  566.472793] su[27877]: pam_unix(su-l:session): session closed for user ha1adm
SCRIPT_FINISHEDhrtK_-0-
```
> Fix 12sp5 sporadical fail: upload_logs timed out

- lib/sles4sap.pm
- t/17_sles4sap.t
- tests/sles4sap/hana_install.pm
- tests/sles4sap/netweaver_install.pm
Tickets: https://jira.suse.com/browse/TEAM-10116, https://jira.suse.com/browse/TEAM-10115
Add single node HANA and NetWeaver install for SLE16.0 with kinds of workaround:
HANA installation
`WORKAROUND_BSC1234806: '1'` for insserv-compat support during HANA installation, install package hana_insserv_compat from QA:HEAD
`WORKAROUND_BSC1239148: '1'` to change SELinux mode to permissive during HANA installation for bsc#1239148
NetWeaver installation
`WORKAROUND_BSC1236235: '1' `for mssing libnsl library during NetWeaver installation, package is stored at NFS qesap-nfs:/srv/nfs/sap/NW*/
`WORKAROUND_BSC1236372: '1' `for missing /etc/services during NetWeaver installation
`WORKAROUND_BSC1239148: '1'` to change SELinux mode to permissive during HANA installation for bsc#1239148
VR: …
> Add workaround for hana and netweaver install to support sles16

- tests/containers/container_engine.pm
On SLES we use the SLES BCI images as a base for the container build.
- Related failure: https://openqa.suse.de/tests/17009640#step/podman/274
- Verification run: https://openqa.suse.de/tests/17013076#step/podman/366
> Use BCI images as base on SLES

- tests/console/flask.pm
https://progress.opensuse.org/issues/178621
- Verification run: http://openqa.suse.de/tests/17013702#step/flask/2
**Please ignore the failed test module, it is not related to pcm module**
> Skip pcm module for sle16 in flask test

- data/yam/agama/auto/scripts_ssh_pub_key.jsonnet
The extra root password will confuse current puppeteer test.
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/17014159#step/validate_first_user/1
> Remove root password for scripts_ssh_pub_key.jsonnet

- tests/containers/podman_quadlet.pm
Depending on the version of quadlet, the -build unit has RemainAfterExit=yes. Instead of adding some version checks, just remove this test. The next line validates that the build succeeded anyway.
Also fix newline escaping.
- Related ticket: https://progress.opensuse.org/issues/178381
* TW: http://10.168.5.231/tests/1765
* SLM 6.2: http://10.168.5.231/tests/1766
https://progress.opensuse.org/issues/178381
> containers/podman_quadlet.pm: Fix on TW and avoid serial timeouts

- lib/containers/k8s.pm
- tests/containers/helm_rmt.pm
Fix k3s commands to work on slower hosts and make the `CONTAINER_IMAGE_TO_TEST` argument optional to allow for chart testing without setting a custom container.
Merge together with https://gitlab.suse.de/qac/qac-openqa-yaml/-/merge_requests/2115
- Related ticket: https://progress.opensuse.org/issues/177940
- Verification run: https://openqa.suse.de/tests/17017218#step/helm_rmt/67
> Prepare k3s test runs for helm chart test runs only

- data/autoyast_sle15/create_hdd/create_hdd_textmode_aarch64_15_sp7.xml
- data/autoyast_sle15/create_hdd/create_hdd_textmode_ppc64le_15_sp7.xml
- data/autoyast_sle15/create_hdd/create_hdd_textmode_s390x_15_sp7.xml
- data/autoyast_sle15/create_hdd/create_hdd_textmode_x86_64_15_sp7.xml
- tests/console/ansible.pm
- tests/console/validate_packages_and_patterns.pm
1. systems management module is added by default for 15-SP7 for create_hdd_textmode_autoyast case
2. Find out the ansible and ansible-core new version and install (such as ansible-9, ansible-core-2.x)
3. Change the salf repo to systems management
Related: https://progress.opensuse.org/issues/177528
Related MR: https://gitlab.suse.de/qe-core/qa-sle-functional-userspace/-/merge_requests/258
VRs:
create_hdd_textmode_autoyast:
https://openqa.suse.de/tests/17000347  (x86 passed)
https://openqa.suse.de/tests/17012820  (aarch64 passed)
https://openqa.suse.de/tests/17012818  (s390x passed)
https://openqa.suse.de/tests/17012819  (ppc64le passed)
Ansible:
https://openqa.suse.de/tests/17013685#step/ansible/43 (aarch64 passed)
https://openqa.suse.de/tests/17013688#step/ansible/43 (ppc64le passed) …
> Add systems management for 15-SP7 by default

- schedule/qam/common/mau-webserver.yaml
https://bugzilla.suse.com/show_bug.cgi?id=1236295
https://progress.opensuse.org/issues/178366
https://progress.opensuse.org/issues/175371
[sle](https://openqa.suse.de/tests/overview?build=rfan0312&distri=sle)
[tw](https://openqa.opensuse.org/tests/4915974)
**At the same time, remove old sle versions which are not tested in openQA**
> Un-schedule ‘apache-nss’ test from tumbleweed and sle16

- lib/qesapdeployment.pm
- t/09_qesapdeployment.t
Fix 12 SP5 qesap_upload_crm_report failed upload the logs as the extension ".tar.bz2" not ".tar.gz" 
[TEAM-10084](https://jira.suse.com/browse/TEAM-10084) - [12 SP5] qesap_upload_crm_report failed upload the logs as the extension‌ is ".tar.bz2" not ".tar.gz"
- Related ticket: https://jira.suse.com/browse/TEAM-10084
-- 12SP5 http://openqa.suse.de/tests/17013142 (when passed: `deploy_qesap_ansible-vmhana*-crm_report.tar.bz2` files were uploaded)
-- 15SP3 http://openqa.suse.de/tests/17014087 (when failed: `Crash_site_b-primary-vmhana*-crm_report.tar.gz` files were uploaded)
-- 15SP3 https://openqa.suse.de/tests/17024416 (when passed: `deploy_qesap_ansible-vmhana*-crm_report.tar.gz` files were uploaded)
> Fix 12SP5 crm_report logs extension "tar.gz" issue

- tests/containers/bci_version_check.pm
Helm tests run on k3s but we should still check the image under test for the correct version. This commit allows k3s in the bci_version_check module and will use podman internally to perform this check.
- Related failures: https://openqa.suse.de/tests/17023157
- Verification run: [k3s](https://openqa.suse.de/tests/17025132) | [podman](https://openqa.suse.de/tests/17025134)
> Allow k3s in bci_version_check

- data/yam/agama/auto/sles_sap_default_ppc64le.jsonnet
- schedule/sles4sap/sles4sap_agama_auto_install_pvm_test.yaml
Add Fake sshPublicKey to workaround https://bugzilla.suse.com/show_bug.cgi?id=1238590
Add single YAML file for PVM_HMC installation with conditional HANA and NetWeaver single node testing
Job group change in https://gitlab.suse.de/qa-css/openqa_ha_sap/-/merge_requests/918
- Related ticket: https://jira.suse.com/browse/TEAM-10116, https://jira.suse.com/browse/TEAM-10115
- Needles: N/A
_install on pvm_hmc + HANA install_ https://openqa.suse.de/tests/17024479
_install on pvm_hmc + NetWeaver install_ https://openqa.suse.de/tests/17024480
> Enable SLES4SAP PVM_HMC installation with HANA and NetWeaver test

- data/yam/agama/auto/lvm_multipath_encrypted.jsonnet
- schedule/yam/agama_lvm_multipath_encrypted_unattended.yaml
- test_data/yam/agama_lvm_multipath_encrypted.yaml
We have added the profile templates to perform lvm multipath encrypted tests
- Related ticket: https://progress.opensuse.org/issues/176460
- Needles: N/A
- x86_64: https://openqa.suse.de/tests/16938239#
- aarch64: https://openqa.suse.de/tests/16938237
> Create unattended installation for lvm multipath encrypted

- lib/suseconnect_register.pm
- schedule/ha/bv/agama_install_sles_ha.yaml
- tests/ha/check_hae_active.py
It is not possible yet to activate the HA Extension in current builds of SLES 16 during installation. This commit adds a new test module included in the `agama_install_sles_ha.yaml` schedule which will verify that the installed system is:
- Registered to SCC
- Using the SCC proxy
- `/etc/SUSEConnect` exists
- HA Extension is enabled
In case any of the above conditions is not met, the module will register the SUT to SCC using the proxy and activate the HA Extension, while soft failing on known bugs and tickets related to the failed conditions.
Result should be a SLES+HA 16 system with the HA Extension activated and the `ha_sles` pattern installed.
- Related ticket: https://jira.suse.com/browse/TEAM-10160
- Needles: N/A
- Verification run: http://mango.qe.nue2.suse.org/tests/6294#live
Also …
> Add test module to ensure HA is activated in SLES 16

- tests/containers/host_configuration.pm
Some test modules still rely on podman being installed, even is k3s is used.
- Related failure: https://openqa.suse.de/tests/17026737
- Verification run: https://openqa.suse.de/tests/17026781#
> Install podman for k3s test runs

- schedule/functional/extra_tests_leap_update_gnome.yaml
- schedule/functional/extra_tests_leap_update_kde.yaml
* Leap 16.0 doesn't have chromium yet
* We dropped hexchat  code-o-o#leap/features#188
> Drop hexchat and chromium from Leap upgrade tests

- lib/autoyast.pm
- Related ticket: https://progress.opensuse.org/issues/178693
- Verification run: https://openqa.suse.de/tests/overview?build=jpupava_pcm&distri=sle
> ay: Use only major version on sle12 pcm

- tests/sway/sway.pm
- Related ticket: https://progress.opensuse.org/issues/158700
- Verification run: https://openqa.opensuse.org/tests/overview?build=jpupava_sway&distri=opensuse
Could not find the test on osd
> sway: Use openSUSE brand on o3

- data/sles4sap/sap_deployment_automation_framework/WORKLOAD_ZONE.tfvars
- lib/sles4sap/sap_deployment_automation_framework/deployment.pm
- lib/sles4sap/sap_deployment_automation_framework/naming_conventions.pm
- t/20_sdaf_deployment_library.t
- t/24_sdaf_naming_convention.t
- tests/sles4sap/sap_deployment_automation_framework/deploy_sap_systems.pm
- tests/sles4sap/sap_deployment_automation_framework/execute_playbooks.pm
- tests/sles4sap/sap_deployment_automation_framework/prepare_ssh_config.pm
- tests/sles4sap/sap_deployment_automation_framework/setup_publiccloud_instances.pm
SDAF test code is missing sanity checks afte 'sap_systems' deployment wchich 
would help troubleshooting SDAF failures. This PR adds checks for important 
files that should be created by SDAF - 'SUT ssh key' and 'ansible inventory 
file'
- Related ticket: https://github.com/sdaf-suse/sap-automation/issues/3
BYOS 15SP7: https://openqa.suse.de/tests/17025069#step/execute_playbooks/120 :red_circle:  (Known issue on BYOS deployment)
PAYG 15SP5: https://openqaworker15.qa.suse.cz/tests/316589#step/execute_playbooks/80 :green_circle:
> [SDAF] Sanity check for files being created by SDAF

- lib/containers/k8s.pm
- tests/containers/bci_version_check.pm
- tests/containers/host_configuration.pm
Podman is not available on 12-SP5 so we need to skip the parts that depend on it.
- Related failure: e.g. https://openqa.suse.de/tests/17026803
- Verification run: https://openqa.suse.de/tests/17039294
> Skip podman parts on 12-SP5

- tests/sles4sap/sap_deployment_automation_framework/deploy_sap_systems.pm
Check if sap-parameters.yaml was created by SDAF
- Related ticket: https://github.com/sdaf-suse/sap-automation/issues/4
( 15SP5 SDAF_GIT_AUTOMATION_BRANCH=development) https://openqaworker15.qa.suse.cz/tests/316786#step/deploy_sap_systems/192 (`test -f /xxx/sap-parameters.yam` failed due to issue#4)
( 15SP5 SDAF_GIT_AUTOMATION_BRANCH=v3.13.0.1)   http://openqaworker15.qa.suse.cz/tests/316755#step/deploy_sap_systems/199 (`test -f /xxx/sap-parameters.yam` passed)
> Check if sap-parameters.yaml was created by SDAF

- data/yam/autoyast/salt.xml
Fix issue [Build74.1-autoyast_salt@64bit](https://openqa.suse.de/tests/17036051)
- Verification run: [autoyast_salt__FIX__](https://openqa.suse.de/tests/overview?build=fix-salt-install)
> Fix Salt installation for missing modules

- tests/sles4sap/hana_install.pm
Manage the install path, everywhere within hana_install, with the same variable.
Change the conditional bash command to remove the packages not needed for ANGI.
Related ticket: https://jira.suse.com/browse/TEAM-10126
sle-15-SP7-Online-ppc64le-Build66.1-SAPHanaSR_ScaleUp_PerfOpt_node01 ppc64le-hmc-sap
- http://openqa.suse.de/tests/16939023 :green_circle: 
- http://openqa.suse.de/tests/17013127
sle-15-SP7-Online-ppc64le-Build66.1-SAPHanaSR_ScaleUp_PerfOpt_node02 ppc64le-hmc-sap
- http://openqa.suse.de/tests/16939022 :green_circle: 
- http://openqa.suse.de/tests/17027402
sle-15-SP7-Online-x86_64-Build66.1-sles4sap_scc_gnome_hana_cli
- http://openqa.suse.de/tests/16939040   :green_circle: 
- http://openqa.suse.de/tests/17013140  :green_circle:  
sle-15-SP3-Server-DVD-SAP-Incidents-x86_64:
- …
> Manage the HANA install path

- lib/main_containers.pm
- tests/containers/isolation.pm
Add isolation module to test internal networks
- TW podman: https://openqa.opensuse.org/tests/4918119
- TW docker: https://openqa.opensuse.org/tests/4918117
- SLES 15-SP6 podman: https://openqa.suse.de/tests/17033587
- SLES 15-SP6 docker: https://openqa.suse.de/tests/17033588
- SLEM 5.5 podman: https://openqa.suse.de/tests/17039643
- SLEM 5.5 docker: https://openqa.suse.de/tests/17040376
> containers: Add isolation module to test internal networks

- tests/virt_autotest/virt_autotest_base.pm
- tests/virt_autotest/virt_utils.pm
Refer to [poo#178324](https://progress.opensuse.org/issues/178324), there was new changed to call svirt backend. Now, the **timeout** for running commands via ssh is actually enforced. Add **timeout** to `call console('svirt')->run_cmd($cmd)` as extend timeout of s390x` lpar_cmd() `
- Related ticket: https://progress.opensuse.org/issues/177342
s390x
[gi-guest_developing-on-host_developing-kvm](https://openqa.suse.de/tests/16995374#) PASS
[gi-guest_sles15sp6-on-host_developing-kvm](https://openqa.suse.de/tests/16995469#) PASS
[gi-guest_sles12sp5-on-host_developing-kvm](https://openqa.suse.de/tests/16995462#) PASS
[gi-guest_developing-on-host_sles15sp6-kvm](https://openqa.suse.de/tests/16993407#) PASS
[gi-guest_developing-on-host_sles12sp5-kvm](https://openqa.suse.de/tes …
> virt_autotest: Extend timeout of s390x lpar_cmd()

- tests/console/dstat.pm
There's already a SR to remove dstat from Factory - https://build.opensuse.org/request/show/1252085 so there's no point in keeping the test around for Tumbleweed
while we wait for [factory](https://build.opensuse.org/request/show/1252378): https://openqa.opensuse.org/tests/4917720#details
> Adapt dstat test to use drop in replacement dool

- tests/containers/host_configuration.pm
On Tumbleweed we don't set HOST_VERSION, but rely on the VERSION setting instead.
- Related failure: https://openqa.opensuse.org/tests/4919284#step/host_configuration/96
- Verification run: [Tumbleweed](https://openqa.opensuse.org/tests/4919889) | [SLES](https://openqa.suse.de/tests/17041632)
> Don't rely on HOST_VERSION to be set

- tests/console/krb5.pm
https://progress.opensuse.org/issues/178720
- Verification run:  [30 iterations](https://openqa.suse.de/tests/overview?build=rfan0313_1&version=15-SP6&distri=sle)
> Reset virtio console in case output can't show in serial terminal

- lib/main_containers.pm
- tests/containers/isolation.pm
Urgent hotfix.
Fix isolation test:
- Run isolation test earlier.
- Unconditionally create subnet for Docker
---
- Failing test: https://openqa.opensuse.org/tests/4920427#step/docker_isolation/148
- Verification run: https://openqa.opensuse.org/tests/4920584
TODO:
- Fix stupid failure in user console on transactional systems.
> containers: Run isolation test earlier

- tests/console/php_postgresql.pm
On aarch64, sometimes test will fail due to serial console stuck, using
`root-console` for part of test due to:
1. when the sessoin stuck, we couldn't restart serial-getty service and
reconnect to it, because the `pushd` `popd` records will lost which
cause failure.
2. If the whole test module uses `root-console`, the module running time
will increase to more than 6m from 2m. So use it for a part of the
module.
Related: https://progress.opensuse.org/issues/178639
VR: https://openqa.suse.de/tests/17047354
For more VRs see [this page](https://openqa.suse.de/tests/overview?build=Amrysliu%2Fos-autoinst-distri-opensuse%23postgresql&version=16.0&distri=sle)
> Increase timeout for php_postgresql case

- tests/console/sshd.pm
https://progress.opensuse.org/issues/178879
**Even I could not reproduce the issue, I suppose  it has something with performance on hyper-v:**
1. Serial terminal can't be used in hyper-v setups
2. There are lots of characters input before restarting the sshd service
So let me upload the sshd config file to check if any format issue :)
- Verification run: [vr](https://openqa.suse.de/tests/overview?version=15-SP7&build=rfan0314_2&distri=sle)
> Upload sshd_config file to check the content

- data/yam/agama/auto/sles_change_localization.jsonnet
- schedule/yam/agama_change_localization_unattended.yaml
Add unattended installation with localization changed.
- Related ticket: https://progress.opensuse.org/issues/178600
- Needles: n/a
- Verification run: [vr_on_x86_64](https://openqa.suse.de/tests/17025170#step/keymap_or_locale/3); [vr_on_aarch64](https://openqa.suse.de/tests/17025171#step/keymap_or_locale/3)
> Add unattended installation with localization changed

- tests/containers/isolation.pm
Issue noted in https://openqa.suse.de/tests/17043603#step/podman_isolation/69
the error
```
Device "30mnullm" does not exist.
SCRIPT_FINISHEDDg39P-1-
```
due to non-ptrintable extrachars.
The `-M` jq option should filter those out.
> Isolation test:jq  monochrome opt.add to skip extrachars

- tests/containers/isolation.pm
- tests/containers/rootless_docker.pm
Fix docker rootless cleanup so isolation module can work.
Also use our busybox image since https://bugzilla.suse.com/show_bug.cgi?id=1239176 is fixed.
- Failing test: https://openqa.opensuse.org/tests/4921949#step/docker_isolation/146
- Verification run: https://openqa.opensuse.org/tests/4922215
> containers: Fix docker rootless cleanup

- lib/main_containers.pm
- tests/containers/isolation.pm
Re-enable isolation test on SLES 15-SP4+
- 15-SP4: https://openqa.suse.de/tests/17049612
> containers: Re-enable isolation test on SLES 15-SP4+

- data/qam/mdadm.sh
- tests/console/mdadm.pm
```
- use expect to handle 'Continue creating array?'
- add --bitmap=internal to skip question
To optimalize recovery speed, it is recommended to enable write-indent bitmap,
do you want to enable it now? [y/N]? y
- put $@ into quotes otherwise more complex commands will be broken
```
- Related ticket: https://progress.opensuse.org/issues/174751
http://openqa.suse.de/tests/overview?distri=sle&build=jpupava_mdadm osd
https://openqa.opensuse.org/tests/overview?distri=opensuse&version=Tumbleweed&build=jpupava_mdadm o3
> mdadm: Fix failing mdadm.sh

- tests/containers/bci_test.pm
Set `TESTINFRA_LOGGING` to get more logs from BCI.
Enabled by https://github.com/SUSE/BCI-tests/pull/767
- Related ticket: https://progress.opensuse.org/issues/174634
- Verification run: https://openqa.suse.de/tests/17042772/file/bci_test_podman-commands.tgz
> bci: Enable TESTINFRA_LOGGING

- data/autoyast_hanaperf/agama-config.jsonnet
- schedule/hanaperf/agama_install.yaml
- tests/installation/ipxe_install.pm
- tests/kernel_performance/hanaperf_postinstall.pm
The PR implements x86_64 and ppc64le bare-metal installation by agama auto profile online method.
Implement a new post install script to remove old releases support and implement functions instead of deploy_hana_perf.sh.
Added EXTRA_PXE_CMDLINE and EXTRABOOTPARAMS for agama ipxe boot which is inherited from autoyast ipxe install.
- Related ticket: https://jira.suse.com/browse/TEAM-10119
- Needles: N/A
ppc64le -> https://openqa.suse.de/tests/17026798
x86_64 -> http://openqa.qa2.suse.asia/tests/82975
> Inital hanaperf bare-metal test workflow on sles16

- tests/containers/isolation.pm
containers: Skip rootless isolation test on Xen due to backend issues.
- Faling test: https://openqa.suse.de/tests/17059712#step/docker_isolation/103
- Verification run: https://openqa.suse.de/tests/17067525
> containers: Skip rootless isolation test on Xen

- tests/console/shells.pm
zsh will not be available on SLES16 ([bsc#1238873](https://bugzilla.suse.com/show_bug.cgi?id=1238873#c4)), so we need to skip testing zsh.
Also switch to use the serial terminal instead of the graphical consoles.
- Related ticket: https://progress.opensuse.org/issues/178591
- Verification run: [MinimalVM SLES 16](https://openqa.suse.de/tests/17075745#step/shells/1) | [15-SP6](https://openqa.suse.de/tests/17075747#step/shells/1) | [Tumbleweed](https://openqa.opensuse.org/tests/4929114#step/shells/1)
> Skip zsh on SLES16

- lib/qesapdeployment.pm
- t/09_qesapdeployment.t
- tests/sles4sap/publiccloud/qesap_terraform.pm
- tests/sles4sap/qesapdeployment/deploy.pm
Primary ticket: https://jira.suse.com/browse/TEAM-10133 
Secondary fix for https://jira.suse.com/browse/TEAM-10144
This pr allows terraform retry to accept an array of error messages to look for, and adds the gcp-concurrent-peering error string to the list of used strings.
The error appears because GCP networks do not allow multiple peering operations at the same time. See https://cloud.google.com/vpc/docs/using-vpc-peering#creating_a_peering_configuration
- Related ticket: https://jira.suse.com/browse/TEAM-10133
- Verification run: https://openqa.suse.de/tests/17042479, https://openqa.suse.de/tests/17067646
> Enhance terraform_retry for gcp errors

- lib/klp.pm
OpenQA FTP server now requires login which makes FTP repos unusable for zypper. Switch to HTTP repos.
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/17077502
> install_klp_product: Switch from FTP asset URL to HTTP

- data/sles4sap/sap_deployment_automation_framework/SAP_SYSTEM.tfvars
- data/sles4sap/sap_deployment_automation_framework/WORKLOAD_ZONE.tfvars
- lib/sles4sap/sap_deployment_automation_framework/configure_tfvars.pm
- lib/sles4sap/sap_deployment_automation_framework/networking.pm
- t/27_sdaf_configure_tfvars.t
- t/28_sdaf_networking.t
- tests/sles4sap/redirection_tests/hana_cluster_check.pm
- tests/sles4sap/sap_deployment_automation_framework/deploy_sap_systems.pm
This PR adds options for SDAF test deploy SBD based fencing with multiple SBD 
devices. Changes include adjusting subnet IP distribution to be more efficient 
and adds iSCSI subnet.  
- Related ticket: https://jira.suse.com/browse/TEAM-10087
HanaSR 1xSBD: https://openqaworker15.qa.suse.cz/tests/317472#step/execute_playbooks/272 :green_circle: 
HanaSR 3xSBD: https://openqaworker15.qa.suse.cz/tests/317474 :red_circle: 
Failure related to: https://github.com/sdaf-suse/sap-automation/issues/5
HanaSR MSI: https://openqaworker15.qa.suse.cz/tests/317478
> [SDAF] Enable SBD fencing option

- tests/installation/bootloader_zkvm.pm
Increase the timeout for fetching the initrd and kernel binaries because on slow days, fetching those resources might take more than 30 seconds.
- Related failure: e.g. https://openqa.suse.de/tests/17083003#step/bootloader_start/25
- Verification run: https://openqa.suse.de/tests/17083206#step/bootloader_start/46
> Increase timeout for network operations

- data/virt_autotest/host_unattended_installation_files/agama/sle16.jsonnet
- schedule/virt_autotest/sle16_guest_installation.yaml
There was a new change to latest build #61.3 and test failed with sshd is disabled, https://openqa.suse.de/tests/17063970
Two commits in the PR:
- Copy ssh public key and enable sshd after sle16 installation
- Stop prepare_non_transactional_server as it failed
Verification run: https://openqa.suse.de/tests/17082235
> Add ssh public keys to enable sshd on sle16

- schedule/ha/bv/agama_install_sles_ha.yaml
Currently SLES+HA installation tests on s390x (backend: svirt) and on ppc64le_hmc (backend: pvm_hmc) are failing in the `yam/agama/agama_auto` test module in an error message indicating that the method `expect_is_shown` does not exist in the class
`Yam::Agama::Pom::RebootTextmodePage` which is the one selected for both backends `svirt` and `pvm_hmc`.
See:
- ppc64le: https://openqa.suse.de/tests/17056517#step/agama_auto/2
- s390x: https://openqa.suse.de/tests/17056480#step/agama_auto/2
This commit modifies the schedule adding conditionally alternative modules to use during the installation on both `svirt` and `pvm_hmc`.
- Related ticket: https://jira.suse.com/browse/TEAM-10160
- Needles: N/A
Verification runs
- aarch64/qemu: https://openqa.suse.de/tests/17076093 (fails later in …
> Expand SLES+HA installation schedule to svirt & pvm_hmc

- data/sles4sap/agama/sles_sap_default.jsonnet
- data/sles4sap/agama/sles_sap_default_ppc64le.jsonnet
The jsonnet files under `data/yam/agama/auto` are expected to be under constant modification and recommendation from YAM squad is to instead use the files there as a template for dedicated copies to be used by other squads. This commit creates/copies the jsonnet files for SLES for SAP on qemu and pvm_hmc.
- Related ticket: https://jira.suse.com/browse/TEAM-10160
- Needles: N/A
- Verification run: [ppc64le](https://openqa.suse.de/tests/17084126) :green_circle:  , [x86_64](https://openqa.suse.de/tests/17084122) :green_circle:
> Copy agama jsonnets for SLES for SAP to data/sles4sap/agama

- tests/installation/release_notes_from_url.pm
Fix release notes check. See [bsc#1239553](https://bugzilla.suse.com/show_bug.cgi?id=1239553#c8) comments
- Verification run: [skip_registration](https://openqa.suse.de/tests/overview?build=leo-fix-release-notes)
> Fix release notes url check

- tests/containers/podman_netavark.pm
In order to test the capability of creating a
`macvlan` podman network, isolate this network in a VLAN and test connectivity among the 2 containers.
- tickets: https://progress.opensuse.org/issues/157906 and https://progress.opensuse.org/issues/160373
* [sle15sp6 DVD inst](http://kepler.suse.cz/tests/24498#step/podman_netavark/277)
* [microos](http://kepler.suse.cz/tests/24493#step/podman_netavark/265)
* [azure](http://kepler.suse.cz/tests/24490#step/podman_netavark/265)
* [ec2](http://kepler.suse.cz/tests/24491#step/podman_netavark/268)
* [gce](http://kepler.suse.cz/tests/24489#step/podman_netavark/268)
> netavark: macvlan testing in PC

- tests/installation/installation_overview.pm
In the case of openSUSE installations with remote backend the SSH service needs to be enabled too
VR: https://openqa.opensuse.org/tests/4932477#step/installation_overview/19
> Enable ssh service during openSUSE installations

- data/yam/agama/auto/autoyast_supported.xml
Quick PR, add ssh public key in autoyast profile to fix ssh not activated issue after installation via autoyast on remote worker. Refer to bsc#https://bugzilla.suse.com/show_bug.cgi?id=1238590
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/overview?distri=sle&version=16.0&build=lemon-suse%2Fos-autoinst-distri-opensuse%23add-ssh-pub-key-for-autoyast_supported
> Add ssh public key in autoyast profile

- lib/utils.pm
Quick PR to fix the 'no route to host' issue after installation on s390x.
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/17090182#details
> Increase timeout value for passphase on s390x

- lib/main_containers.pm
- tests/containers/isolation.pm
Validate script output on isolation test as `ping` was failing for the wrong reason on s390x.
Also use toolbox image on s390x until busybox image is updated.
- Failing tests:
- https://openqa.suse.de/tests/17087715#step/docker_isolation/150
- 15-SP6 s390x: https://openqa.suse.de/tests/17090618
- 15-SP6 x86_64: https://openqa.suse.de/tests/17090617
> containers: Validate script output on isolation test

- schedule/sles4sap/qam/common/qam_sles4sap_fips_mau-extratests.yaml
Also execute the affirmation related modules first.
- Related ticket: https://progress.opensuse.org/issues/178900
- Verification run: https://openqa.suse.de/tests/17049179
> openjdk_fips is executed elsewhere, but add nss_smoke and gpg

- tests/console/consoletest_setup.pm
- tests/fips/fips_setup.pm
- tests/security/krb5/krb5_crypt_prepare.pm
- Related ticket: https://progress.opensuse.org/issues/178456
- Verification run: https://openqa.suse.de/tests/17092923
(fails earlier without these changes)
> openssh-server, firewalld are back, openssl missing in SLE 16

- lib/qesapdeployment.pm
- t/09_qesapdeployment.t
Upload supportconfig logs as part of the qe-sap-deployment cleanup
- Related ticket: https://jira.suse.com/browse/TEAM-10138
- Verification run: https://openqaworker15.qa.suse.cz/tests/317643#downloads (see the supportconfig logs)
> Fetch supportconfig logs after sles4sap failure

- lib/sles4sap_publiccloud.pm
Atypo while uploading the sshlog on cleanup has been fixed with this pr, so that it overwrites previously uploaded file instead of having 2 files.
- Related ticket: https://jira.suse.com/browse/TEAM-10125
- Verification run: https://openqa.suse.de/tests/17096775 (search for 'ssh' in the logs - there should be a single file, compared to the cloned job, https://openqa.suse.de/tests/17084892, that has 2)
> Fix typo in ssh log

- lib/bootloader_pvm.pm
https://progress.opensuse.org/issues/179020
The netboot fails sporadically and holds at entering root password
for encrypted disk, add this workaround  to by-pass the issue
VR: https://openqa.suse.de/tests/17067536#step/boot_agama/27
> Add workaround for PVM first boot issue

- schedule/kernel/ibtest-master.yaml
- schedule/kernel/ibtest-slave.yaml
The interfaces were configured as Ethernet, but we need them to be InfiniBand.
> Fix link protocol for infiniband tests

- lib/sles4sap/sap_deployment_automation_framework/configure_tfvars.pm
- t/27_sdaf_configure_tfvars.t
Tests seem to ignore default value `msi` for fencing mechanism. This PR fixes the problem
- Related ticket: https://jira.suse.com/browse/TEAM-10087
SBD: https://openqaworker15.qa.suse.cz/tests/317722#step/deploy_workload_zone/97
Default MSI: https://openqaworker15.qa.suse.cz/tests/317720#step/deploy_workload_zone/97
> Fix SDAF fencing mechanism

- lib/web_browser.pm
- tests/console/wget_https.pm
Seems FIPS is the only user.
- Related ticket: https://progress.opensuse.org/issues/178048
15-SP2: http://openqa.suse.de/tests/17108016
15-SP3: http://openqa.suse.de/tests/17108017
15-SP4: http://openqa.suse.de/tests/17108018
15-SP5: http://openqa.suse.de/tests/17108019
15-SP6: http://openqa.suse.de/tests/17108020
> Do not use b.o.o on <= 15-SP5 bsc#1239835

- .github/workflows/ci.yml
- Makefile
- Related ticket: https://progress.opensuse.org/issues/124688
Now only changed files are checked
`export PERL5LIB=../..:os-autoinst:lib:tests/installation:tests/x11:tests/qa_automation:tests/virt_autotest:tests/cpu_bugs:tests/sles4sap/saptune:$PERL5LIB: ; for f in `git diff --name-only | grep '.pm'` ; do perl -c $f 2>&1 | grep -v " OK$" && exit 2; done ; true`
> Reduce execution of compile tests by checking changed files only

- tests/security/eal4/syscall_thrasher.pm
Test module `syscall_thrasher` is very unstable on s390x in terms of timeouts. This excludes `syscall_thrasher` from the s390x schedule.
- Related ticket: https://progress.opensuse.org/issues/176454
- Verification run: https://openqa.suse.de/tests/17115437
> Exclude syscall_thrasher from encrypted s390x

- lib/sles4sap/sap_deployment_automation_framework/deployment.pm
- t/20_sdaf_deployment_library.t
- tests/sles4sap/sap_deployment_automation_framework/deploy_sap_systems.pm
Create summary screens for different SDAF deployment scenarios TEAM-10085 - [SDAF] Create summary screens for different deployment scenarios
[TEAM-10085](https://jira.suse.com/browse/TEAM-10085) - [SDAF] Create summary screens for different deployment scenarios
- Related ticket: https://jira.suse.com/browse/TEAM-10085
-- SDAF_PRD_deploy_ENSA2 (`SDAF_DEPLOYMENT_SCENARIO=db_install,db_ha,nw_pas,nw_aas,nw_ensa`):
https://openqaworker15.qa.suse.cz/tests/317719#step/execute_playbooks/389 (passed: summary screens are started from this test step)
-- SDAF_PRD_deploy_HanaSR (`SDAF_DEPLOYMENT_SCENARIO=db_install,db_ha`):
http://openqaworker15.qa.suse.cz/tests/317727#step/execute_playbooks/290 (passed)
-- SDAF_PRD_deploy_HanaSR (`SDAF_DEPLOYMENT_SCENARIO=db_install`): …
> Create summary screens for different deployment

- schedule/functional/extra_tests_misc.yaml
See discussion in https://progress.opensuse.org/issues/178657
TL;DR is that the test depends on pox and that is unmantained (no updates in past 5 years)
> The reason is a call of ssl.wrap_socket() [1] which was deprecated[2] by python 3.7 and is removed in python 3.13.
> Using SSLContext or stick to python3.11 are fixing the problem.
> The quick fix could be this pr[3]
>
> [1] https://github.com/noxrepo/pox/blob/gar-experimental/pox/openflow/of_01.py#L1110
> [2] https://github.com/python/cpython/commit/00464bbed66e5f64bdad7f930b315a88d5afccae
> [3] https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/21412
Since Python3.11 will eventually leave TW too it makes little sense to keep executing it there
> Remove openvswitch_ssl from Tumbleweed schedule

- data/journal_check/bug_refs.json
poo: https://progress.opensuse.org/issues/179350
VR: https://openqa.opensuse.org/tests/4939332 and https://openqa.opensuse.org/tests/4945577
> Treat Connection reset by peer as a bug in journal checks

- tests/containers/buildah.pm
- tests/containers/container_engine.pm
- tests/containers/podman_quadlet.pm
- tests/containers/privileged_mode.pm
- tests/containers/realtime.pm
- tests/containers/rootless_docker.pm
- tests/containers/rootless_podman.pm
- tests/containers/seccomp.pm
Use CONTAINER_IMAGE_TO_TEST for Tumbleweed image to allow testing unreleased OCI image.
- Related ticket: https://progress.opensuse.org/issues/178645
- o3 schedule: https://github.com/os-autoinst/opensuse-jobgroups/pull/625
- Verification run with `CONTAINER_IMAGE_TO_TEST=registry.opensuse.org/opensuse/factory/totest/containers/opensuse/tumbleweed:latest`:
- TW: https://openqa.opensuse.org/tests/4945949
> containers: Use CONTAINER_IMAGE_TO_TEST for Tumbleweed image

- tests/sles4sap/hana_install.pm
Add openQA setting HDBLCM_EXTRA_ARGS to add arguments on the installation command line.
- Related ticket: https://jira.suse.com/browse/TEAM-10126
https://openqa.suse.de/tests/17110581 called with setting `HDBLCM_EXTRA_ARGS` and value of it is visible in https://openqa.suse.de/tests/17110581#step/hana_install/229
- node01 http://openqaworker15.qa.suse.cz/tests/318051
- node02 http://openqaworker15.qa.suse.cz/tests/318053
This test is also using new ASSETS and `HDBLCM_COMPONENTS=all` instead of `HDBLCM_COMPONENTS=server`. But again it proves that string from the setting is added to the command line
- node01 http://openqaworker15.qa.suse.cz/tests/318046
- node02 http://openqaworker15.qa.suse.cz/tests/318045
> Add setting about hana cli installer

- schedule/sles4sap/pvm_nw_cluster_node.yaml
- tests/ha/barrier_init.pm
- tests/sles4sap/netweaver_cluster.pm
- tests/sles4sap/netweaver_filesystems.pm
This commit introduces a new schedule for cluster nodes, to test a basic NetWeaver cluster on the pvm_hmc backend. It is based on the HANA schedule `schedule/sles4sap/pvm_hana_cluster_node.yaml` located on `schedule/sles4sap/hana/`.
- Related ticket: https://jira.suse.com/browse/TEAM-10160
- Needles: N/A
- Verification run on pvm_hmc: [node 1](https://openqa.suse.de/tests/17105012)  :green_circle: , [node 2](https://openqa.suse.de/tests/17105013)  :green_circle: 
- Verification run on qemu (regression): [support server](https://openqa.suse.de/tests/17092946)  :green_circle: , [node 1](https://openqa.suse.de/tests/17092945)  :green_circle:  & [node 2](https://openqa.suse.de/tests/17092947) :green_circle: 
New Verification Runs after latest changes:
- pvm_hmc: [node …
> Add a schedule to test basic NetWeaver cluster in pvm_hmc

- t/11_hacluster.t
Add Time mock to avoid 10sec sleep during each test execution
BEFORE:
```
[11:47:42] t/11_hacluster.t ................  ok    11581 ms ( 0.03 usr  0.00 sys +  0.51 cusr  0.07 csys =  0.61 CPU)
```
AFTER
```
[18:08:24] t/11_hacluster.t ................  ok      582 ms ( 0.01 usr  0.00 sys +  0.51 cusr  0.07 csys =  0.59 CPU)
```
> Speed up hacluster UT execution

- lib/virt_autotest/hyperv_utils.pm
- tests/installation/bootloader_hyperv.pm
For hyperv testing:
OSD CC machines(prg2) will use "mount \\openqa.suse.de\var\lib\openqa\share\factory N:" to download file
OSD non-CC machines(nue2) will use HTTP protocol to download file.
- Related ticket: https://progress.opensuse.org/issues/176514
- Needles: N/A
NUE2 VR ISO:  https://openqa.oqa.prg2.suse.org/tests/17089927
NUE2 VR HDD: https://openqa.oqa.prg2.suse.org/tests/17089928
NUE2 VR HDD(sle16): https://openqa.oqa.prg2.suse.org/tests/17089929
PRG2 VR ISO: https://openqa.oqa.prg2.suse.org/tests/17089930
PRG2 VR HDD: https://openqa.oqa.prg2.suse.org/tests/17089931
PRG2 VR HDD(sle16): https://openqa.oqa.prg2.suse.org/tests/17089932
> Switch to HTTP if mount fails during hyperv testing

- lib/main_common.pm
- tests/x11/gnome_console.pm
Gnome terminal is being replaced with gnome-console (kgx) this PR prepares the groundwork for that change
Progress ticket: https://progress.opensuse.org/issues/169162
Needles: https://github.com/os-autoinst/os-autoinst-needles-opensuse/pull/827
VR: 
- (test only) http://10.149.209.202/tests/97
- (default gnome schedule) https://openqa.opensuse.org/tests/4946137#step/gnome_console/5
> Add test for gnome-console (kgx)

- tests/containers/netavark_integration.pm
SLE 16.0 uses the `dbus-1-daemon` package instead of `dbus` for `dbus-daemon`.
`dbus-daemon: No such file or directory`
- Failed test: https://openqa.suse.de/tests/17141219/file/netavark_integration-netavark.tap
- Verification run: https://openqa.suse.de/tests/17147589
> Fix netavark upstream tests on SLE 16.0

- schedule/yam/agama_ppc64le.yaml
New schedule without hostname validation for arch ppc64le.
- Verification run: [fix_hostname_ppc64le](https://openqa.suse.de/tests/overview?build=fix_hostname_ppc64le)
> New schedule without hostname validation for arch ppc64le

- lib/main_common.pm
- tests/console/gdb.pm
- tests/console/snapper_jeos_cli.pm
We need to adapt several tests, as some packages are not going to land in sle16
* [404 salt](http://kepler.suse.cz/tests/24511)
* [404 sysvinit](http://kepler.suse.cz/tests/24512#step/gdb/1)
* [404 zsh](http://kepler.suse.cz/tests/24513#step/snapper_jeos_cli/16)
> SLE16: several packages are dropped

- data/journal_check/bug_refs.json
Previous attempt missed the fatal part of the regex
VR https://openqa.opensuse.org/tests/4948331
> Fix regex for boo#1229935

- lib/main_common.pm
- lib/services/users.pm
- lib/x11utils.pm
- tests/x11/gnome_terminal.pm
- tests/x11/ibus/ibus_installation.pm
This is a follow up to os-autoinst/os-autoinst-distri-opensuse/pull/21557
This PR does two things: 
- ensures that for new codestreams there's no dependency on gnome-terminal
- Ensures that for new codestreams gnome_terminal test installs gnome-terminal
VR:
- [Staging test](https://openqa.opensuse.org/tests/4948403)
- [default gnome scenario on TW](https://openqa.opensuse.org/tests/4948286#live)
- [Leap 15.6 update gnome](https://openqa.opensuse.org/tests/4948264#step/gnome_terminal/4)
- [Change password](https://openqa.opensuse.org/tests/4947361#step/change_password/91)
- [ibus installation](https://openqa.opensuse.org/tests/4947362#step/ibus_installation/32)
goes together with: https://github.com/os-autoinst/os-autoinst-needles-opensuse/pull/828
> Use xterm instead of gnome-terminal for some gnome tests

- schedule/ha/bv/agama_install_sles_ha.yaml
With the latest SLES 16 build, jobs in aarch64 architecture on qemu backend fail on the `installation/grub_test` test module, but reach the login prompt successfully.
Removing the module from the SLES+HA installation schedule for 16 on qemu backend produces jobs which pass on both x86_64 and aarch64 architectures, so this commit removes the module from the schedule.
- Related ticket: https://jira.suse.com/browse/TEAM-9407
- Needles: 
- Verification run: [aarch64](http://mango.qe.nue2.suse.org/tests/6307) :green_circle: , [x86_64](http://mango.qe.nue2.suse.org/tests/6304) :green_circle:
> Remove grub_test module from SLES+HA 16 installation schedule

- lib/main_common.pm
- schedule/functional/extra_tests_textmode_phub.yaml
- tests/console/ansible.pm
- tests/console/libjpeg_turbo.pm
For 15-SP7 ansible and salt are from systems-management repo, so we need to move ansible out of packageHub testing
Related: https://progress.opensuse.org/issues/177528
VR:
15-SP7: 
ansible : https://openqa.suse.de/tests/17136883  (Passed)
PackageHub: https://openqa.suse.de/tests/17147473 (Passed)
15-SP6: https://openqa.suse.de/tests/17147477# (Passed)
TW:  https://openqa.suse.de/tests/17147477# (Passed)
See more VRs in https://openqa.suse.de/tests/overview?version=15-SP7&build=Amrysliu%2Fos-autoinst-distri-opensuse%23move_ansible&distri=sle
> Move ansible test out of package hub for 15-SP7

- .github/workflows/ci.yml
- Makefile
- tools/check_jsonnet
We have two options to do this CI check for jsonnet:
1. Install jsonnet package, use the binary to do the check, but unfortunately jsonnet pkg only can be found on bookworm version while currently we used buster version, anyway, we can install jsonnet separately on bookworm, https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/21168 This method will cause more images for container and complex condition.
2. On current container, install jsonnet for python, I updated code to apply the check for python in this option 2 PR. So tester need use the format tool(jsonnet) installing go locally if see that the format doesn't match.
3. Created a [ticket](https://progress.opensuse.org/issues/179383) to follow up formatting and style. …
> Add CI check for jsonnet

- lib/saputils.pm
record_info only expect two arguments not three
Fix issue
```
testapi::record_info("check_hana_topology", " [ERROR] ", "Missing 'lss' field in topology output for site a") called at /var/lib/openqa/pool/38/os-autoinst-distri-opensuse/lib/saputils.pm line 223
```
Related ticket: https://jira.suse.com/browse/TEAM-10079
sle-15-SP6-HanaSr-Azure-Byos-x86_64-Build15-SP6_2025-03-25T03:03:21Z-hanasr_azure_test_angi az_Standard_E4s_v3
- http://openqaworker15.qa.suse.cz/tests/318166 :green_circle: test keep failing but exception now is no more about `Odd name/value argument for subroutine` 
```
[2025-03-25T17:27:50.103262+01:00] [info] [pid:76606] ::: basetest::runtest: # Test died: wait_for_sync [ERROR] Replication SYNC did not finish within defined timeout. (900 sec). at …
```
> Fix record_info in saputils

- schedule/yam/agama.yaml
- schedule/yam/agama_auto.yaml
- schedule/yam/agama_autoyast_supported_ppc64le.yaml
- schedule/yam/agama_autoyast_supported_qemu.yaml
- schedule/yam/agama_autoyast_supported_s390x.yaml
- schedule/yam/agama_from_usb.yaml
- schedule/yam/agama_remote_pvm.yaml
- schedule/yam/agama_remote_s390x.yaml
- schedule/yam/agama_s390x.yaml
- tests/yam/validate/validate_base_product.pm
Product cannot be validate with cat /etc/os-release due it doesn't differentiate well between sles and sles sap. So add a new test module to validate the product by reading /etc/products.d/baseproduct.
- Related ticket: https://progress.opensuse.org/issues/178729
- Verification run: [vrs](https://openqa.suse.de/tests/overview?distri=sle&version=16.0&build=chcao_178729)
> Add test module to validate the base product

- tests/installation/bootloader_s390.pm
- tests/installation/bootloader_zkvm.pm
We have added the required kernel parameters to load Offline ISO without download into memory.
- Related ticket: https://progress.opensuse.org/issues/179290
- Needles: N/A
- s390x-kvm: https://openqa.suse.de/tests/17139239
- s390x-zvm: https://openqa.suse.de/tests/17118733 (Created short path to configure)
> Fix s390x booting of Full medium

- tests/kernel/install_ltp.pm
exfatprogs is conflicting with exfat-utils in TW as following:
exfatprogs-1.2.8-1.1.x86_64 conflicts with 'exfat-utils'
provided by the installed exfat-utils-1.4.0-2.4.x86_64
* Related ticket: N/A
* Needles: N/A
* Verification run: https://openqa.opensuse.org/tests/4951326
Signed-off-by: Andrea Cervesato <andrea.cervesato@suse.com>
> install_ltp: don't install exfatprogs for LTP git in TW

- lib/sles4sap_publiccloud.pm
Filter output of hdbnsutil command in perl instead of grep command with shell pipe
- Related ticket: https://jira.suse.com/browse/TEAM-10147
https://openqa.suse.de/tests/17147669#step/Kill_replica/262 (with PR)
https://openqa.suse.de/tests/17141305#step/Kill_replica/262 (without PR)
> Filter output of hdbnsutil command in perl

- lib/serial_terminal.pm
Also include the finishing newline to avoid matching "Note: Cockpit disallows root login by default.".
- Related ticket: https://openqa.suse.de/tests/17135040
- Verification run: http://10.168.5.231/tests/1782
> lib/serial_terminal.pm: Make check for entered username more reliable

- tests/btrfs-progs/run.pm
The test result should be failed if no result file
- Related ticket: https://progress.opensuse.org/issues/179482
- Needles: N/A
https://openqa.suse.de/tests/17163058 (passed)
https://openqa.suse.de/tests/17163057 (failed due to no result file)
> btrfs-progs: Fix issue with test result retrieval

- lib/bootloader_setup.pm
- lib/guest_installation_and_configuration_base.pm
- tests/installation/bootloader_zkvm.pm
- tests/installation/ipxe_install.pm
- tests/yam/agama/boot_agama.pm
- variables.md
Remove the workaround for https://bugzilla.suse.com/show_bug.cgi?id=1238581
And fix a regression issue http://openqa.suse.de/tests/17168139#step/bootloader_zkvm/42
VR:[all arches](https://openqa.suse.de/tests/overview?build=rfan0327&distri=sle&version=16.0)
> Replace agama.auto with inst.auto for sle16 installation and fix a regression logic issue

- lib/registration.pm
- tests/installation/bootloader_s390.pm
- tests/installation/bootloader_zkvm.pm
Avoid to set SCC_URL in grub for Agama Full medium testing when the SCC_URL is not none. Change the checking to Agama flavor.
- Related failure: [failed_job](https://openqa.suse.de/tests/17160334#step/post_registration/1) 
- Verification run: [vrs_link](https://openqa.suse.de/tests/overview?version=16.0&build=chcao_skip_url&distri=sle)
- Related pr: [pr_21363](https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/21363/files)
> Avoid to set SCC_URL in bootloader for Agama Full medium testings

- data/jeos/g_cloudinit.cfg
- lib/main_common.pm
- schedule/jeos/sle/minimalvm-extratest.yaml
- tests/console/journalctl.pm
- tests/console/slp.pm
- tests/jeos/verify_cloudinit.pm
1. Adapt existing tests for sle16
2. Introduce s390x cloud image testing, configured by cloud-init and jeos-firstboot
- [sle-16.0-Minimal-VM-Cloud-s390x-Build11.10-minimalvm-cloud-init@s390x-kvm](https://openqa.suse.de/tests/17171276)
- [sle-16.0-Minimal-VM-Cloud-s390x-Build11.10-minimalvm-wizard@s390x-kvm](https://openqa.suse.de/tests/17171008)
- [sle16 with reboot](https://openqa.suse.de/tests/17172269#)
> Update sle16 minimal-vm tests

- lib/Yam/Agama/Pom/GrubMenuAgamaPage.pm
- schedule/yam/agama_check_installation_medium.yaml
- tests/yam/agama/agama_check_installation_medium.pm
We have added the mediacheck schedule, needles and required code.
- Related ticket: https://progress.opensuse.org/issues/176781
- Needles: `mediacheck-bootloader-prompt-20250304` and `mediacheck-boot-agama-mediacheck-20250304`
- x86_64: https://openqa.suse.de/tests/17172754
- aarch64: https://openqa.suse.de/tests/17172755
> Add scenario for mediacheck of both installation mediums

- tests/containers/run_container_in_k8s.pm
The version naming convention has changed in sle16. For more details read [Contents of /etc/os-release](https://confluence.suse.com/pages/viewpage.action?pageId=1749942754)
- Verification run: http://kepler.suse.cz/tests/24576#
> Pretty version name has changed in sle16

- tests/wsl/distro_install.pm
Accounting for all welcome_to_wsl pop-up cases.
- Related ticket: https://progress.opensuse.org/issues/176676
15sp5 win10 UEFI 
https://openqa.suse.de/tests/17173076 ✅
https://openqa.suse.de/tests/17173077 ✅ unrelated failure
https://openqa.suse.de/tests/17173078 ✅ unrelated failure
https://openqa.suse.de/tests/17173079 ✅
15sp6 win10 UEFI: 
https://openqa.suse.de/tests/17173080 ✅
15sp7 win10 UEFI: 
https://openqa.suse.de/tests/17173081 ✅
> Added welcome_to_wsl check for WSL build images.

- data/wsl/Autounattend_UEFI.xml
- lib/windowsbasetest.pm
Adds installation of openqa-agent to Windows in the Unattended Installation. This agent is pre-installed from now on but will not affect current test runs without further modifications.
- Related ticket: https://progress.opensuse.org/issues/178837
- Verification run: https://openqa.opensuse.org/tests/4952400
> Add openqa-agent to Windows

- lib/qesapdeployment.pm
- lib/sles4sap_publiccloud.pm
- t/09_qesapdeployment.t
- t/12_sles4sap_publiccloud.t
Change sles4sap tests only to collect supportconfig in case of errors, only as part of post_fail_hook.
- Related ticket: https://jira.suse.com/browse/TEAM-10138
- sle-12-SP5-HanaSr-Aws-Payg-x86_64-Build12-SP5_2025-03-26T03:03:25Z-hanasr_aws_test_fencing_native_ltss ec2_r4.8xlarge -> http://openqaworker15.qa.suse.cz/tests/318307 :green_circle:  job fails and supportconfig is uploaded https://openqaworker15.qa.suse.cz/tests/318307/file/deploy_qesap_ansible-scc_vmhana01-supportconfig_log.txz
- sle-15-SP6-HanaSr-Aws-Payg-x86_64-Build15-SP6_2025-03-26T03:03:25Z-hanasr_aws_test_fencing_native_stop_kill ec2_r4.8xlarge -> http://openqaworker15.qa.suse.cz/tests/318343 :green_circle: supportconfig not collected in case of pass
- sle-12-SP5-HanaSr-Gcp-Byos-x86_64-Build12-SP5_2025-03-26T03:03:25Z-hana …
> Only collect supportconfig in case of error

- data/virt_autotest/guest_params_xml_files/slm_6_2_64_kvm_hvm_x86_64_default_encrypted_ignition+combustion.xml
* **spice** is not supported anymore and using it leads to error reported by virt-install.
* **Failed** test run because of spice is [here](https://openqa.suse.de/tests/17168067#step/unified_guest_installation/701).
* **Use** vnc as graphics for virtual machines. 
* [slmicro 6.2 on slmicro 6.2](https://openqa.suse.de/tests/17172421)
> Use vnc instead of upstream dead spice graphics for virtual machine

- tests/console/btrfsmaintenance.pm
- Related ticket: https://progress.opensuse.org/issues/169267 246da6001988d3f6f44ef3d98fcbb518e08c4f17
- Verification run: https://openqa.suse.de/tests/17184236#step/btrfsmaintenance/43
> Extend handle interrupted status to older versions

- tests/installation/bootloader_zkvm.pm
The live.password is not added for s390x Full medium testing, add it in this PR.
- Related failure: [s390x_kvm](https://openqa.suse.de/tests/17172788#step/patch_agama_tests/3) ; [s390_zkvm](https://openqa.suse.de/tests/17172787#step/boot_agama/26)
- Verification run: [s390x_kvm_vr](https://openqa.suse.de/tests/17184357#step/patch_agama_tests/4); [s390x_zkvm_vr](https://openqa.suse.de/tests/17184356#live)
> Add live.password for Full medium testing on s390x

- schedule/functional/extra_tests_textmode.yaml
- schedule/qam/common/mau-extratests1.yaml
- tests/console/ruby.pm
Related: https://progress.opensuse.org/issues/177805
VRs:
test module `ruby` passed all in following verification run.
15-SP7:  [job on x86](https://openqa.suse.de/tests/17184381#)       [all arches](https://openqa.suse.de/tests/overview?version=15-SP7&build=Amrysliu%2Fos-autoinst-distri-opensuse%23poo_177805&distri=sle)
15-SP6: [job on s390x](https://openqa.suse.de/tests/17184617)       [all arches](https://openqa.suse.de/tests/overview?build=Amrysliu%2Fos-autoinst-distri-opensuse%23poo_177805&version=15-SP6&distri=sle)
15-SP5:  [job on aarch64](https://openqa.suse.de/tests/17184619)       [all arches](https://openqa.suse.de/tests/overview?distri=sle&build=Amrysliu%2Fos-autoinst-distri-opensuse%23poo_177805&version=15-SP5)
15-SP4: [job on x86](https://openqa.suse.de/tests/17184624) …
> Add ruby test

- tests/security/oqs_provider_openssl.pm
Add timeout 300 to make a time-outing job pass.
- Related ticket: https://progress.opensuse.org/issues/179593
- s390x (originally failing): https://openqa.suse.de/tests/17187176
- x86_64 (originally OK): https://openqa.suse.de/tests/17187185
> Add timeout to oqs_provider execute binary

- lib/main_micro_alp.pm
- tests/microos/toolbox.pm
Only sle-micro 5.5 is currently supported on power8 and requires
emulated workers. A workaround has to be introduced as we implicitly count
that ppc64le images are tested on emulated machines in case of container
testing.
- image bug: [missing toolbox package in ppc64le slem
5.5](https://bugzilla.suse.com/show_bug.cgi?id=1240332)
- toolbox container bug:
https://bugzilla.suse.com/show_bug.cgi?id=1239591
- https://openqa.suse.de/tests/17188921#
- host update job: https://openqa.suse.de/tests/17187968#
> Workaround missing disk_boot@ppc container update hosts tests

- tests/console/sssd_389ds_functional.pm
- Related ticket: https://progress.opensuse.org/issues/176154 (partially)
- Needles: N/A
- Verification run: https://openqa.opensuse.org/tests/4861561
> sssd_389ds_functional: do not attempt to interact with deprecated nscd

- data/sles4sap/agama/sles_ha_default.jsonnet
SLES+HA jobs for SLES 16 have used in the past the `data/agama_auto/sle_default.jsonnet` on qemu backends, as it is not possible to activate the HA extension during installation. This allows the installation of a SLES where the HA extension can be activated later.
However, the `data/agama_auto/sle_default.jsonnet` file does not enable ssh root login (as the pvm and s390x jsonnet files do), which means that HA tests attempting to configure clusters using ssh connections to root will fail.
This commit copies `agama_auto/sle_default.jsonnet` to `data/sles4sap/agama/sles_ha_default.jsonnet` and adds a post script to enable root login via ssh.
- Needles: N/A
- Verification run: http://mango.qe.nue2.suse.org/tests/6407
> Add agama jsonnet file for SLES+HA on qemu

- tests/console/verify_efi_mok.pm
If the secureboot efivars are not found, set the expected marker to a
false value.
- Verification run: https://openqa.suse.de/tests/17210088#step/verify_efi_mok/1
> Just testing vmware

- tests/containers/buildah_integration.pm
- variables.md
Support BUILDAH_STORAGE_DRIVER variable.
- Related ticket: https://bugzilla.suse.com/show_bug.cgi?id=1239082
- SLES 16.0: https://openqa.suse.de/tests/17215161 (`BUILDAH_STORAGE_DRIVER=vfs`)
- TW: https://openqa.opensuse.org/tests/4961739
> containers: Support BUILDAH_STORAGE_DRIVER

- data/autoyast_hanaperf/agama-config.jsonnet
https://github.com/agama-project/agama/blob/master/rust/agama-lib/src/scripts/model.rs#L79
refer to https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/21631, https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/21616
VR: n/a
> Replace 'body' with 'content' for HANAperf SLE16 agama.json

- data/sles4sap/agama/sles_ha_default.jsonnet
- data/sles4sap/agama/sles_sap_default.jsonnet
- data/sles4sap/agama/sles_sap_default_ppc64le.jsonnet
Per
https://github.com/agama-project/agama/blob/master/rust/agama-lib/src/scripts/model.rs#L79 the `body:` sections of jsonnet files for agama auto have been replaced with `content:`. This commit updates jsonnet files used by SLES for SAP and SLES+HA tests accordingly.
See also the commits/PR:
1. 736682bc47d720a38e237ed390dde0ecc7fb7d52 / #21631 
2. e37c5b98a7ba1e5a016699d3002e6aeb9fec511e / #21616 
- Related ticket: https://jira.suse.com/browse/TEAM-9407
- Needles: N/A
> Replace body section with content in SLES for SAP & HA jsonnet files

- tests/containers/container_engine.pm
Add test for default OCI runtime.  See https://bugzilla.suse.com/show_bug.cgi?id=1239088
- Related ticket: https://progress.opensuse.org/issues/179741
- TW containers_image: https://openqa.opensuse.org/tests/4962303
> containers: Add test for default OCI runtime

- tests/transactional/host_config.pm
We already have a workaround implemented in container hdds, no we need to handle the same problem in sle-micro with the kernel that contains the problematic patch
- Related ticket: https://progress.opensuse.org/issues/179702
- sle-micro-6.2-Default-ppc-4096-SelfInstall-ppc64le-Build6.20-combustion@ppc64le-emu -> https://openqa.suse.de/tests/17222155
- sle-micro-6.2-Default-ppc-4096-ppc64le-Build6.20-default@ppc64le-emu -> https://openqa.suse.de/tests/17223221
> Append disable_ddw=1 in sle-micro 6.2

- data/virt_autotest/host_unattended_installation_files/agama/sle16.jsonnet
`body` was replaced with `content` in sle16.
- Verification run: https://openqa.suse.de/tests/17223273
> Replace body with content for virt test on sle16

- tests/microos/selfinstall.pm
On SLES16 there is a line break, so the wait_serial token must be cropped to the one line being present.
- Related failure: https://openqa.suse.de/tests/17218992#step/selfinstall/3
- Verification run:  https://openqa.suse.de/tests/17227947 and https://openqa.opensuse.org/tests/4962461 (pass `selfinstall` or `firstrun`)
> Fix JeOS-Firstboot for SLES16

- lib/publiccloud/basetest.pm
- lib/publiccloud/provider.pm
- tests/publiccloud/check_registercloudguest.pm
- tests/publiccloud/check_services.pm
- tests/publiccloud/run_ltp.pm
- tests/publiccloud/slem_basic.pm
- Make sure that `$self->{my_provider}` and `$self->{my_instance}` are available in test modules where `cleanup()` subroutine needs those.
- Make sure that `$args->{my_provider}` `$args->{my_instance}` is available as it's used in `lib/publiccloud/basetest.pm` where it's available as `$self->{run_args}`.
---
- Related ticket: [poo#178099](https://progress.opensuse.org/issues/178099), [poo#179272](https://progress.opensuse.org/issues/179272)
- Part of work in this PR has been moved to: #21438
[Build:38063:corosync](https://pdostal-server.suse.cz/tests/overview?build=%3A38063%3Acorosync&distri=sle&version=15-SP5) of sle-15-SP5-Azure-SAP-BYOS-Incidents.x86_64	  [SAPHanaSR-ScaleUp-PerfOpt-msi@az_Standard_E4s_v3](https://pdostal-server.suse.cz/tests/8718) …
> Increase robustness of publiccloud::basetest _cleanup subroutine

- tests/kernel/shutdown_ltp.pm
Collect CPU steal time after failure to debug s390x timeout issues.
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/17228146
> shutdown_ltp: Collect CPU steal time from /proc/stat

- tests/containers/container_engine.pm
Add soft-failure for bsc#1239088 on SLEM 6.0+
- Failing test: https://openqa.suse.de/tests/17229421#step/podman/188
> containers: Add soft-failure for bsc#1239088 on SLEM 6.0+

- tests/containers/container_engine.pm
crun will be the default OCI runtime on SLEM 6.0+ for the time being.
> containers: Remove soft-failure on bsc#1239088

- lib/guest_installation_and_configuration_base.pm
* **Only** validate HTTP 200 OK response for http media.
* **Validating** non-http media leads to failure like [this](https://openqa.suse.de/tests/17183796#step/unified_guest_installation/371).
* [oracle linux](https://openqa.suse.de/tests/17209162)
* [15-SP7 uefi guest](https://openqa.suse.de/tests/17209163)
* [sl micro 6.2 guest](https://openqa.suse.de/tests/17209164)
> Only validate HTTP 200 OK for http media

- lib/virt_autotest/utils.pm
- tests/virt_autotest/guest_installation_run.pm
- tests/virt_autotest/host_upgrade_generate_run_file.pm
* **bsc#1231522** makes one point clear that we are looking into feature request to have some point before reboot to collect logs for further analysis and using something that already exists created exactly for this purpose which has the timeout value configurable on the linuxrc command line:
* https://github.com/yast/yast-yast2/pull/977
* https://github.com/yast/yast-installation/pull/823
* https://github.com/openSUSE/installation-images/pull/344 It's even briefly documented at https://en.opensuse.org/SDB:Linuxrc. 
* **In** order to generalize this change and also make things much easier, using "extra kernel params" can help pass any desired parameters to kernel instead of just ```reboot_timeout```.
* **Add** subroutine ```get_guest_settings``` to replicate desired settings to all guests …
> Add option for additional kernel parameters

- lib/susedistribution.pm
- lib/x11utils.pm
- t/01_x11utils.t
Currently the `ensure_installed` routine uses xterm by default, regardless of the desktop environment
with these changes the behavior now changes, except for SLE where the default would still be xterm.
This is particularily important when considering that nowdays we're using Wayland as default except for
some specific scenarios where the system is installed with X11
[poo#169162](https://progress.opensuse.org/issues/169162)
- SLES https://openqa.suse.de/tests/17162523#step/gedit/3
- gnome @ tumbleweed https://openqa.opensuse.org/tests/4951531#step/gimp/14
- kde @ tumbleweed https://openqa.opensuse.org/tests/4951595#step/hexchat/12
- xfce @ tumbleweed https://openqa.opensuse.org/tests/4951668#step/chromium/17
- gnome @ leap …
> Use desktop environment's default terminal in ensure_installed

- tests/wsl/distro_install.pm
Attempt to prevent welcome-to-wsl pop-up from breaking WSL tests in TW/Leap/SLE
- Related ticket: https://progress.opensuse.org/issues/176676
SLE: https://openqa.suse.de/tests/overview?distri=sle&version=15-SP6&build=_chubykalo-welcome-to-wsl-poo176676
Leap: https://openqa.opensuse.org/tests/overview?version=15.6&build=_chubykalo-welcome-to-wsl-poo176676&distri=opensuse
TW: https://openqa.opensuse.org/tests/overview?distri=opensuse&build=_chubykalo-welcome-to-wsl-poo176676&version=Tumbleweed
None of the errors are related to Welcome to WSL pop-up anymore.
> Remove Welcome-to-WSL pop-up

- tests/containers/container_engine.pm
> containers: Only SLEM 6.1 uses crun
