os-autoinst/os-autoinst-distri-opensuse

tests/containers/container_engine.pm

Only SLEM 6.0 & 6.1 use crun: https://bugzilla.suse.com/show_bug.cgi?id=1239088#c13

containers: Only SLEM 6.0 & 6.1 use crun

---

tests/containers/buildah.pm

Check default OCI runtime on buildah.
- Tumbleweed: https://openqa.opensuse.org/tests/4964710
- SLE 16.0: https://openqa.suse.de/tests/17240040
- SLE 15-SP7: https://openqa.suse.de/tests/17240042
- SLE 15-SP3: https://openqa.suse.de/tests/17240078
Note: SLEM lacks buildah :)

containers: Check default OCI runtime on buildah

---

data/containers/agama/sle_default_s390x_kvm.jsonnet

SLES 16 Container create hdd s390x-kvm jsonnet update:
config. `containers/agama/sle_default_s390x_kvm.jsonnet` needed in post-install to enable ssh.
Fixing the test: https://openqa.suse.de/tests/17228284
- Related ticket: https://progress.opensuse.org/issues/175950
- Needles: No.
- Verification run: https://openqa.suse.de/tests/17240564

SLES 16 Container create hdd s390x-kvm jsonnet fixed

---

tests/kernel/ulp_openposix.pm

Installing KLP product is not needed for ULP testing.
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/17174441

ulp_openposix: Don't install livepatching product on SLE-16

---

tests/x11/ibus/ibus_installation.pm

#21592 changed the default terminal in `default_gui_terminal` and logically there's some fallout where it is being used
VR: http://10.149.209.202/tests/118#step/ibus_installation/13 - failure is unrelated to the change
VR: http://10.149.209.202/tests/119#step/change_password/92 - needles related to change_password
Needles: https://github.com/os-autoinst/os-autoinst-needles-opensuse/pull/832

Use ensure_install instead of duplicated code in ibus_installation

---

lib/registration.pm

VMware GRUB does not run into a timeout and is often missed by openQA.
- Related failure: https://openqa.suse.de/tests/17231917#step/suseconnect_scc/16
- Verification run: https://openqa.suse.de/tests/17240552#step/suseconnect_scc/11

Do not expect GRUB on VMware

---

tests/fips/openssl/dirmngr_setup.pm
tests/fips/openssl/openssl_fips_dhparam.pm
tests/fips/openssl/openssl_fips_hash.pm
tests/security/vsftpd/vsftpd.pm
tests/security/vsftpd/vsftpd_setup.pm

They still fail the test, but allow subsequent tests to continue.
- Related ticket: https://progress.opensuse.org/issues/179837
core: https://openqa.suse.de/tests/17241073#
newer core run: https://openqa.suse.de/tests/17241765
extra: https://openqa.suse.de/tests/17241072#

Make various security test failures non-fatal

---

lib/sles4sap.pm

Running `saptune sollution apply` fails on SLE16 because there is already a SAP basic solution applied. This removes the basic solution before applying the one defined in `$profile`
- Related Ticket: TEAM-10220
- Verification run: https://openqa.suse.de/tests/overview?distri=sle&version=16.0&build=apappas_vr_saptune
Failures are unrelated to the PR but caused by product changes/bugs

Fix saptune failures on 16 due to changed initial conditions

---

tests/elemental/container_validation.pm
tests/elemental/installation.pm
tests/elemental/shutdown.pm

Set SELinux in permissive mode, as there is an issue with Enforcing mode and Elemental doesn't support it.
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/17241170 (also tested on my local openQA server)

Fix Elemental container image test

---

schedule/qam/12-SP3/qam-regression-installation.yaml
schedule/qam/12-SP5/qam-regression-installation.yaml
schedule/qam/15-SP2/qam-regression-installation.yaml
schedule/qam/15-SP2/qam-textmode.yaml
schedule/qam/15-SP3/qam-regression-installation.yaml
schedule/qam/15-SP4/qam-regression-installation.yaml
schedule/qam/15-SP5/qam-regression-installation.yaml
schedule/qam/15-SP6/qam-regression-installation.yaml

Use autoyast for qam jobs
- Related ticket: https://progress.opensuse.org/issues/108836
- Verification run: 15-SP5：
qam-regression-installation-SLES
https://openqa.suse.de/tests/17160394#
mru-install-desktop-with-addons
https://openqa.suse.de/tests/17168073#
qam-textmode+sle15：
https://openqa.suse.de/tests/17170995
mru-install-desktop-with-addons@s390x-kvm
http://openqa.suse.de/tests/17184020
mru-install-desktop-with-addons@aarch64-virtio
http://openqa.suse.de/tests/17184021
15-SP4：
qam-textmode+sle15：
https://openqa.suse.de/tests/17170995
15-SP3：
qam-textmode+sle15：
https://openqa.suse.de/tests/17171004
12-SP5：
https://openqa.suse.de/tests/17171006
qam-yast_self_update
http://openqa.suse.de/tests/17171032
15-SP6：
qam-regression-installation-SLED
https://openqa.suse.de/tests/17172160
* …

Use autoyast for qam jobs

---

tests/console/create_hdd_systemd_testkit.pm
tests/console/start_systemd_testkit_offline.pm

Related: https://progress.opensuse.org/issues/177237
VR:  https://openqa.suse.de/tests/17240099#

[qe-core]Add systemd_testkit_offline in functional on SLE16

---

tests/yam/agama/boot_agama.pm

- Related ticket: https://progress.opensuse.org/issues/176832
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/17248194#details

Add inst.finish in kernel boot parameters for ovmdrv test

---

tests/yam/agama/boot_agama.pm

Reverts os-autoinst/os-autoinst-distri-opensuse#21662 We can use EXTRABOOTPARAMS to add inst.finish, so do not need this PR any more.

Revert "Add inst.finish in kernel boot parameters for ovmdrv test"

---

lib/registration.pm

We're going to stop using KEEP_GRUB_TIMEOUT to avoid the issues with missed GRUB screens.
- Related failure: e.g. https://openqa.suse.de/tests/17241892#step/health_check/23
- Reverts https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/21663
Merge together with https://gitlab.suse.de/qac/qac-openqa-yaml/-/merge_requests/2162
All of them fail at `rebootmgr`, that's a different issue.
* https://openqa.suse.de/tests/17242635
* https://openqa.suse.de/tests/17242636
* https://openqa.suse.de/tests/17242637
* https://openqa.suse.de/tests/17242638

Revert Do not expect GRUB on VMware

---

data/journal_check/bug_refs.json

Known issue for SLES 16, so also known for SLEM 6.2
* Related failure: https://openqa.suse.de/tests/17241892#step/journal_check/6

Ignore RETBleed warning on SLEM 6.2

---

tests/installation/bootloader_s390.pm

See for further info:
https://bugzilla.suse.com/show_bug.cgi?id=1238891#c9
- Related ticket: https://progress.opensuse.org/issues/178396
- Related PR: tbd
- Verification run: [dasd and dasd+zfcp](https://openqa.suse.de/tests/overview?version=16.0&distri=sle&build=jknphy%2Fos-autoinst-distri-opensuse%23dasd-down)

Prevent to bring DASD down in Agama

---

tests/containers/container_engine.pm

Fix stupid issue with OCI runtime check.

containers: Use oci_runtime instead of runtime variable

---

data/hpc/sample_cplusplus.cpp
tests/hpc/mpi_master.pm

This PR introduce some test adaptions for the MPI mpich using cpp app.
We do observe sporadic failures in the tests however the MPI_finalize() seems to work well. Still openQA reports a timeout. Details with extensive testing in the related progress ticket.
- Related ticket: https://progress.opensuse.org/issues/175036
x86_64:
https://openqa.suse.de/tests/17241144
https://openqa.suse.de/tests/17241141
https://openqa.suse.de/tests/17241142
https://openqa.suse.de/tests/17241143
arm:
https://openqa.suse.de/tests/17241139
https://openqa.suse.de/tests/17241137
https://openqa.suse.de/tests/17241140
https://openqa.suse.de/tests/17241138
more runs:
https://openqa.suse.de/tests/17241156
https://openqa.suse.de/tests/17241158
https://openqa.suse.de/tests/17241155 …

HPC: MPI timeout in mpich

---

lib/x11utils.pm

- Related ticket: https://progress.opensuse.org/issues/169162
- Verification run: https://dzedro.suse.cz/tests/2532#step/change_password/71

On SLED is gnome-terminal default_gui_terminal

---

data/journal_check/bug_refs.json

SLEM 6.2 known issues: 2 rec.s updated with 6.2 version, for journal checks validation
- Related ticket: https://progress.opensuse.org/issues/179732
- Needles: no.
- Verification run: t.b.d.

SLEM 6.2 known issues updated 

---

tests/security/krb5/krb5_crypt_prepare.pm

- Related ticket: https://progress.opensuse.org/issues/180014
- Verification run: https://openqa.suse.de/tests/17265961#step/krb5_crypt_nfs_client/10 (that exact step now works), https://openqa.suse.de/tests/17265961#step/krb5_crypt_prepare/100 (it's installed here)

Make sure nfs-client is installed as part of krb5 tests

---

lib/services/users.pm

This reverts commit 1b3e8dfa2ae77e0ae080360060f8b178e9cedb56.
https://openqa.suse.de/tests/17271142 15-SP6
https://openqa.opensuse.org/tests/4970653 TW

Revert "change_password: Drop unused likely outdated needle"

---

tests/network/wireguard.pm

Add wireguard test for sle16
- Related ticket: https://progress.opensuse.org/issues/179852
- Verification run: https://openqa.suse.de/tests/17276688#
https://openqa.suse.de/tests/17276689

Add wireguard test for sle16

---

lib/bootloader_setup.pm

No idea if the condition should be more specific otherwise it will break other tests ?
- Related ticket: https://bugzilla.suse.com/show_bug.cgi?id=1239691#c34
- Failed tests: https://openqa.suse.de/tests/17265766 https://openqa.suse.de/tests/17265767
https://openqa.suse.de/tests/17266430
https://openqa.suse.de/tests/17266431

Add workaround for qemu crash on ppc64le

---

lib/main_common.pm
schedule/functional/extra_tests_textmode.yaml
schedule/functional/extra_tests_textmode_sle16.yaml
tests/console/fwupd.pm
tests/console/tuned.pm

https://progress.opensuse.org/issues/179840
[sle](http://openqa.suse.de/tests/overview?distri=sle&build=rfan0407)
[tw](https://openqa.opensuse.org/tests/4976182#)
**Please ignore the failed modules, they are known issues**

Move fwupd and tuned tests from kernel squad to core

---

tests/containers/bats/README.md
tools/detect_unused_modules

Add README for BATS tests
Migrate most of the information from https://confluence.suse.com/display/qasle/podman+upstream+tests
This README will improve over time, but at the very least it must document the variables used.

Add README for BATS tests

---

data/virt_autotest/guest_unattended_installation_files/sles_16_plus_kvm_hvm_guest_non_encrypted_storage_x86_64.jsonnet

* **Use** ```content``` instead of ```body``` when defining scripts in agama jsonnet for SLES16 guest.
* [Build71.1 online iso](http://10.200.140.9/tests/450)
* [Build71.1 full iso](http://10.200.140.9/tests/452)
* [Build71.1 online and full iso](http://10.200.140.9/tests/453)

Update agama jsonnet for SLES16 guest

---

lib/registration.pm

- Related MR: https://gitlab.suse.de/qe-yam/openqa-job-groups/-/merge_requests/418
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/overview?version=6.1&build=lemon-suse%2Fos-autoinst-distri-opensuse%23ensure-register-base-product-before-migration&distri=sle-micro

Ensure register extra module to base product before migration

---

tests/hpc/rasdaemon.pm

Fix poo#180167: Some tests were removed from extra_tests_kernel, which used to run before rasdaemon and handled the console selection. As a result, rasdaemon started failing due to the missing console setup.
- Related ticket: https://progress.opensuse.org/issues/180167
- Verification run: https://openqa.suse.de/tests/17285616

rasdaemon: Add missing console selection

---

tests/containers/bats/skopeo.pm

fakeroot is not available on SLE 16.0 impacting skopeo upstream tests.
I notified about the missing package.  This will be reverted if the decision is made to eventually add it.
- Failing test: https://openqa.suse.de/tests/17279889#step/skopeo/61
- Verification run: https://openqa.suse.de/tests/17285908

containers: fakeroot is not available on SLE 16.0

---

data/wsl/Autounattend_UEFI.xml

Add recent bugfixes by bumping the openqa-agent version in the unattended installation.
- Related ticket: https://progress.opensuse.org/issues/178837
- Verification run: https://openqa.opensuse.org/tests/4978205#live

Update openqa-agent to Version 1.1.3

---

data/sles4sap/qe_sap_deployment/qesap_azure_peering.yaml
tests/sles4sap/qesapdeployment/configure.pm
tests/sles4sap/qesapdeployment/test_mirror.pm

Prepare qesap regression code to add a proof of concept Azure variant of the test schedule doing:
- network peering to the IBSm via Terraform
- TEST repo added by Ansible
- remove test code to create the peering using az cli
- Add some validation commands
https://jira.suse.com/browse/TEAM-10216
YAML schedule running existing test module about peering. Uses new conf.yaml and with settings about peering
http://openqaworker15.qa.suse.cz/tests/320076
Without setting about peering and without scheduling test module about peering
http://openqaworker15.qa.suse.cz/tests/320078

Add POC qesap regression test with IBSm

---

lib/qam.pm
t/17_sles4sap.t
t/33_qam.t
tests/publiccloud/validate_repos.pm
tests/sles4sap/publiccloud/cluster_add_repos.pm

Now that we want to enable aggregate tests for IBSM jobs, `cluster_add_repos.pm` and `validate_repos.pm` need to be adjusted to also look for repos in the openqa variables that hold aggregate test repos.
- Related ticket: https://jira.suse.com/browse/TEAM-9981
Aggregate test: http://openqaworker15.qa.suse.cz/tests/319972 (All good - only fails because timeout needs to be changed in settings)
Single Incident test: https://openqa.suse.de/tests/17281449 (PASS)

Add aggregate repos to ibsm modules

---

tests/containers/podman_netavark.pm

Skip ping test on s390x until https://bugzilla.suse.com/show_bug.cgi?id=1239176 is solved.
We can't use DockerHub for anything now.  It's useless.
- Related ticket: https://progress.opensuse.org/issues/180203

containers/netavark: Skip ping test on s390x

---

data/virt_autotest/guest_params_xml_files/sles_16_64_kvm_hvm_x86_64_agama_full_iso.xml
data/virt_autotest/guest_params_xml_files/sles_16_64_kvm_hvm_x86_64_agama_online_iso.xml
schedule/virt_autotest/sle16_guest_installation.yaml

* **Update** guest SLES 16.0 media which take new format, including ```data/virt_autotest/guest_params_xml_files/sles_16_64_kvm_hvm_x86_64_agama_full_iso.xml``` and ```data/virt_autotest/guest_params_xml_files/sles_16_64_kvm_hvm_x86_64_agama_online_iso.xml```.
* **Update** schedule file ```schedule/virt_autotest/sle16_guest_installation.yaml``` to include guest installation part.
* **openQA** yaml config is [here](https://gitlab.suse.de/qa-testsuites/openqa-job-group-yaml/-/merge_requests/268). 
* [online iso guest installation](https://openqa.suse.de/tests/17285629)
* [full iso guest installation](https://progress.opensuse.org/issues/180164)

Update guest SLES 16.0 media

---

tests/console/php_postgresql.pm

On sle16 enforcing is on by default, so we need to modify the selinux policy
to allow apache access database. 
Related: https://progress.opensuse.org/issues/179771
VR: 
sle 16.0
https://openqa.suse.de/tests/17287611 (x86 passed on php_postgresql)
https://openqa.suse.de/tests/17287609 (aarch64 passed on php_postgresql)
**The failed module is tracked by https://bugzilla.suse.com/show_bug.cgi?id=1240949**

Modify the selinux policy for apache

---

tests/containers/helm.pm

Fix docker.io rate limit issues by replacing bitnami/apache chart with nginx-ingress which doesn't have any dependencies on dockerhub.
- Related ticket: https://progress.opensuse.org/issues/180101
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/17289697

Fix helm docker.io rate limit issues

---

lib/main_micro_alp.pm
tests/installation/configure_bls.pm
variables.md

This module selects grub2-bls during the installation. As of right now, the test run will fail afterwards due to a bug in the current MicroOS image, which causes `mkdumprd` to be called _before_ `sdbootutil add-all-kernels` during the installation when grub2-bls has been selected.
- Needles: https://github.com/os-autoinst/os-autoinst-needles-opensuse/pull/833
- Verification run: http://192.168.43.19/tests/13

Add test for selecting grub2-bls during install

---

tests/hpc/spack_master.pm

In case of some spack tests, especially for ARM, we see the tests to time out yet the mpirun is executing the tests fine. It is safer then to increase the timeout for the mpirun to 240s
- Related ticket: https://progress.opensuse.org/issues/180248

HPC: Increase the mpirun timeout

---

tests/transactional/install_updates.pm

Use zypper patch instead of zypper up
- SLEM 5.5; https://openqa.suse.de/tests/17297582

transactional/install_updates: Use zypper patch instead of zypper up

---

data/sles4sap/sap_deployment_automation_framework/SAP_SYSTEM.tfvars
data/sles4sap/sap_deployment_automation_framework/WORKLOAD_ZONE.tfvars
lib/sles4sap/sap_deployment_automation_framework/deployment.pm
lib/sles4sap/sap_deployment_automation_framework/deployment_connector.pm
t/20_sdaf_deployment_library.t
tests/sles4sap/sap_deployment_automation_framework/configure_deployer.pm
tests/sles4sap/sap_deployment_automation_framework/create_deployer_vm.pm
tests/sles4sap/sap_deployment_automation_framework/deploy_sap_systems.pm
tests/sles4sap/sap_deployment_automation_framework/deploy_workload_zone.pm
tests/sles4sap/sap_deployment_automation_framework/execute_playbooks.pm

Deployment retention does not currently work as intended and deployer 
resources are still being cleaned up even with 'SDAF_RETAIN_DEPLOYMENT' 
being set. This PR applies fixes and introduces feature which tags all 
resources that should be ignored by cleanup mechanism. Tag name can be 
customized using openQA setting `SDAF_NO_CLEANUP_TAG` with default value 
'sdaf_no_cleanup'. Tag is applied on all resources created including 
sap_systems and workload_zone.
- Related ticket: https://jira.suse.com/browse/TEAM-10222
Retain deployment: 
```SDAF_RETAIN_DEPLOYMENT='yeah' SDAF_NO_CLEANUP_TAG='pcw_ignore'```
https://openqaworker15.qa.suse.cz/tests/320288#step/SDAF%20cleanup/1
Reuse deployment:
```SDAF_DEPLOYMENT_ID=320287 SDAF_RETAIN_DEPLOYMENT='yeah'```
Deployment modules …

SDAF deployment retention fixes

---

lib/transactional.pm
lib/version_utils.pm

Fixed verification of SL Micro version, we have to switch from `VERSION=`to `VARIANT=` in `/etc/os-release`
- Needles: N/A
- 6.1->6.2: https://openqa.suse.de/tests/17298095
- 6.0->6.1: https://openqa.suse.de/tests/17298096
- 5.5->6.0: https://openqa.suse.de/tests/17298097

Fix micro target version check

---

schedule/functional/extra_tests_textmode.yaml

https://progress.opensuse.org/issues/180662
- Verification run: https://openqa.suse.de/tests/17307436

Skip fwupd tests on 390x as ACPI ESRT table it not supported

---

tests/containers/isolation.pm

Use toolbox image for ppc64le because https://bugzilla.suse.com/show_bug.cgi?id=1239176 also affects it.
- Failing test: https://openqa.suse.de/tests/17303352#step/podman_isolation/75
- Verification run: https://openqa.suse.de/tests/17308024

containers: Use toolbox image also for ppc64le

---

tests/jeos/glibc_locale.pm

During revert of locale changes done by `glibc_locale`, the encoding
`UTF-8` was omitted which results in ansible
[failure](https://openqa.suse.de/tests/17304472#step/ansible/61)
- Verification run: https://openqa.suse.de/tests/17308475#step/ansible/1

Fix locale parameters

---

schedule/functional/stack_tests_python_sle16.yaml
tests/console/python3_pipx.pm
tests/console/python3_pynacl.pm
tests/console/python3_setuptools.pm
tests/console/python3_websocket_client.pm
tests/console/python_scientific.pm
tests/console/python_virtualenv.pm

For sle16, we need to do following changes:
1. Don't remove system default installed python package: python313
2. Skip not available packages tests on sle16
Related: https://progress.opensuse.org/issues/180161
VRs:
16.0:  https://openqa.suse.de/tests/17311552  (passed)
15.7:  https://openqa.suse.de/tests/17311462   (passed)
TW: https://openqa.opensuse.org/tests/4986501# (softfail)

Don't remove system default python when doing cleanup

---

lib/main_containers.pm

Temporarily disables #21297 before a permanent fix gets implemented.
- Related ticket: https://progress.opensuse.org/issues/164015
- Needles: N/A

Temporarily disable podmansh test

---

tests/console/mtab.pm

[poo#179759](https://progress.opensuse.org/issues/179759)
We can see sporadic performance issue on ppc64le and aarch64 after switch to user console, so use serial terminal instead.
[20+ iterations on ppc](http://openqa.suse.de/tests/overview?distri=sle&build=rfan0411&version=15-SP7)
[other platform](http://openqa.suse.de/tests/overview?build=rfan0411_nonppc&distri=sle&version=15-SP7)
[tw](https://openqa.opensuse.org/tests/4987900)

User serial terminal for test 'mtab'

---

schedule/functional/extra_tests_textmode_sle16.yaml

https://progress.opensuse.org/issues/180662
quick fix for https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/21759

Un-schedule fwupd test for s390x on sle16

---

lib/sles4sap/azure_cli.pm

Increase timeout of script_run in Azure vm create from 600 to 900.
It could eventually help some tests on 15sp7 
http://openqaworker15.qa.suse.cz/tests/320836

Increase timeout for vm create

---

tests/console/sshd.pm

As https://bugzilla.suse.com/show_bug.cgi?id=1239976#c5, we can't use curl when it is minimal role.
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/17320044#details

Do not use curl for minimal role

---

lib/autoyast.pm
schedule/yam/agama_extended.yaml
schedule/yam/agama_extended_unattended.yaml
test_data/yam/agama_sle_extended.yaml
tests/yam/validate/validate_hostname.pm

We have added the required modifications to manage setting the hostname in Agama.
- Related ticket: https://progress.opensuse.org/issues/179293
- Related PR: https://github.com/jknphy/agama-integration-test-webpack/pull/100
- Needles: N/A
- sles_extended: https://openqa.suse.de/tests/17322678 (FAILED due to external reasons, tested locally)
- sles_extended_unattended: https://openqa.suse.de/tests/17322482

Automate to set the hostname during Agama installation

---

lib/autoyast.pm
tests/yam/agama/boot_agama.pm
tests/yam/agama/import_agama_profile.pm

We have added minor changes to include dynamic profile generation also in import agama profile step.
- Related ticket: https://progress.opensuse.org/issues/179173
- Needles: N/A
- sles_encrypted: https://openqa.suse.de/tests/17322677
- sles_encrypted (No generated profile) https://openqa.suse.de/tests/17324572
- sles_lvm_unattended: https://openqa.suse.de/tests/17324578
- sles_lvm: https://openqa.suse.de/tests/17324582#
- sles_lvm (No generated profile): https://openqa.suse.de/tests/17324583#

Adapt `import_agama_profile` test step to use dynamic generated JSON profiles

---

data/yam/autoyast/dummy.xml

- Related ticket: [poo#180125](https://progress.opensuse.org/issues/180125)
- Related [PR#21736](https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/21736)
> The purpose of this file is to have a static file,
with fixed content, to use as download URL in
`data/yam/agama/auto/autoyast_supported.xml`
with a fixed checksum value

Add dummy.xml file

---

lib/containers/bats.pm
lib/main_containers.pm
tests/containers/bats/README.md
tests/containers/bats/buildah.pm
tests/containers/bats/netavark.pm
tests/containers/bats/podman.pm
tests/containers/bats/runc.pm
tests/containers/bats/skopeo.pm

Simplify BATS tests:
- Run each package's tests on its job.
- The above allows us to have generic BATS_* variable names and cut the number from 25 to 10.
- Simplify BATS setup in one function.
---
- Tumbleweed:
- buildah: https://openqa.opensuse.org/tests/4993175 (failed subtest will be skipped)
- netavark: https://openqa.opensuse.org/tests/4992891 
- podman: https://openqa.opensuse.org/tests/4993046 (transient network error)
- runc: https://openqa.opensuse.org/tests/4992893
- skopeo: https://openqa.opensuse.org/tests/4992894

Simplify BATS tests

---

lib/main_common.pm

- Related ticket: https://progress.opensuse.org/issues/167018
- Needles: N/A
[15sp2](http://openqa.qam.suse.cz/tests/86101)
[15sp5](http://openqa.qam.suse.cz/tests/86102#)

Ignore sle15sp2 sriov test

---

lib/main_common.pm

- Leap 16.0 does not contain hexchat code-o-o#leap/features#188
- Chromium is still WIP
- Verification run: https://openqa.opensuse.org/tests/4993310

Drop chromium and hexchat from zdup from 15.6

---

lib/sles4sap/sap_deployment_automation_framework/deployment_connector.pm
schedule/sles4sap/sap_deployment_automation_framework/ensa2_scenarios.yml
t/26_deployment_connector.t
tests/sles4sap/redirection_tests/hanasr_schedule_tests.pm

TEAM-10245 - [SDAF] Decouple cleanup module for HanaSR scenarios
Related MR: https://gitlab.suse.de/qa-css/openqa_ha_sap/-/merge_requests/962
( :bell:  PR and MR should be merged at the same time)  
- Related ticket: https://jira.suse.com/browse/TEAM-10245
SDAF_PRD_cleanup_ensa2: https://openqaworker15.qa.suse.cz/tests/320831#dependencies (all passed)
SDAF_PRD_cleanup_HanaSR: https://openqaworker15.qa.suse.cz/tests/320834#dependencies (all passed)

Decouple cleanup module for SDAF scenarios

---

tests/publiccloud/azure_aitl.pm
variables.md

- create a variable to control AITL version which we are using 
- mute cleanup logic for AITL because we not controlling any VMs in that case 
VR: https://openqa.suse.de/tests/17353959

Disable cleanup for AITL tests

---

data/virt_autotest/host_unattended_installation_files/autoyast/dev_host_15.xml.ep

* **Do** not use ```mem_encrypt=on``` on kernel command line for qualified AMD machines, because there is product bug to be fixed. Please refer to bsc#1224107 for more information.
* **At** the moment, only ```amd-zen3-gpu-sut1-1``` machine is affected by bsc#1224107. Do not add ```mem_encrypt=on``` on its kernel command line.
* [sev/es 15sp6 on 15sp7 with amd-zen3-gpu-sut1](https://openqa.suse.de/tests/17340219)
* [sev/es 15sp7 on 15sp6 with amd-zen3-gpu-sut1](https://openqa.suse.de/tests/17293882)
* [sev/es 15sp7 on 15sp7 with amd-zen3-gpu-sut1](https://openqa.suse.de/tests/17293883)
* [sev/es guest installation with WORKER_CLASS=amd-zen3-gpu-sut1](https://openqa.suse.de/tests/17349659)
* [sev/es test with bare-metal3](https://openqa.suse.de/tests/17340221)
* …

Avoid mem_encrypt=on due to bsc#1224107

---

lib/qesapdeployment.pm
t/09_qesapdeployment.t
tests/sles4sap/publiccloud/qesap_terraform.pm

Add variable HANASR_TERRAFORM_PARALLEL to control terraform parallelism.
Ticket https://jira.suse.com/browse/TEAM-10214
- sle-15-SP6-Qesap-Azure-Payg-x86_64-BuildLATEST_AZURE_SLE15_6_PAYG-qesap_azure_angi_test@64bit -> http://openqaworker15.qa.suse.cz/tests/321529
- sle-15-SP6-HanaSr-Aws-Payg-x86_64-Build15-SP6_2025-04-15T02:03:23Z-hanasr_aws_test_fencing_native_baremetal ec2_r5b.metal -> http://openqaworker15.qa.suse.cz/tests/321530 :green_circle:  here the call to Terraform using the changed code https://openqaworker15.qa.suse.cz/tests/321530#step/deploy_qesap_terraform/474
- sle-15-SP6-HanaSr-Azure-Byos-x86_64-Build15-SP6_2025-04-15T02:03:23Z-hanasr_azure_test_msi az_Standard_E4s_v3 -> http://openqaworker15.qa.suse.cz/tests/321531 :green_circle: 
- …

Add variable to control terraform parallel

---

tests/ha/iscsi_client.pm

As the documentation is now updated, we can remove the softfail logic.
- Related ticket: https://jira.suse.com/browse/TEAM-10267
x86_64:
- https://openqa.suse.de/tests/17359569
- https://openqa.suse.de/tests/17359570
- https://openqa.suse.de/tests/17359571
- https://openqa.suse.de/tests/17359572
aarch64:
- https://openqa.suse.de/tests/17360995
- https://openqa.suse.de/tests/17360996
- https://openqa.suse.de/tests/17360997

Drop softfail for bsc#1204528 and bsc#1204978

---

data/sles4sap/qe_sap_deployment/sles4sap_gcp_generic.yaml

Add terraform variables about the IBSm network peering to the qe-sap-deployment conf.yaml file used in HanaSR tests.
https://openqaworker15.qa.suse.cz/tests/321712 :green_circle: the PR code is fine, the variables are visible in the .tfvars. Job fails as the deployment is created in a region different to the one of IBSm
https://openqaworker15.qa.suse.cz/tests/321713 :green_circle: collision
https://openqaworker15.qa.suse.cz/tests/321714

Add network peering terraform variables to GCP

---

lib/qesapdeployment.pm
t/09_qesapdeployment.t
tests/sles4sap/qesapdeployment/configure.pm
tests/sles4sap/qesapdeployment/test_cluster.pm
tests/sles4sap/qesapdeployment/test_crash.pm
tests/sles4sap/qesapdeployment/test_mirror.pm
tests/sles4sap/qesapdeployment/test_system.pm

Remove no more used library function for the cleanup. This function cannot be resued in the `run` body of the destroy.pm testmodule neither in the post_fail_hook of the deploy.pm test module.
This function was created as part of https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/20156/  but then no more used from https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/20242/
Related ticket: https://jira.suse.com/browse/TEAM-9654
- sle-15-SP6-Qesap-Azure-Payg-x86_64-BuildLATEST_AZURE_SLE15_6_PAYG-qesap_azure_angi_test@64bit -> http://openqaworker15.qa.suse.cz/tests/321648
- sle-15-SP6-HanaSr-Azure-Byos-x86_64-Build15-SP6_2025-04-15T02:03:23Z-hanasr_azure_test_msi  az_Standard_E4s_v3 -> http://openqaworker15.qa.suse.cz/tests/321626

Remove no longer used qesap_test_postfail

---

data/publiccloud/ltp_runtest
tests/publiccloud/run_ltp.pm

Add a custom LTP runtest file for Public Cloud tests
Related ticket: https://progress.opensuse.org/issues/110929
Verification run: https://openqa.suse.de/tests/17366947 (LTP_COMMAND_FILE=publiccloud)

Public Cloud: Add LTP runtest file

---

tests/sles4sap/publiccloud/qesap_terraform.pm

Add some code to allow supporting both the methods to create the network peering to the IBSm in Azure: using the az cli (legacy) and using terraform (new). The problem is to be able to support both with the same conf.yaml. This commit is to avoid failure in qesap_terraform about missing IBSM_VNET and IBSM_RG openQA variables.
Follow up of https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/21601
- Related ticket: https://jira.suse.com/browse/TEAM-10216
sle-12-SP5-Azure-SAP-BYOS-Updates-x86_64-Build20250416-1-SAPHanaSR-ScaleUp-PerfOpt@az_Standard_E4s_v3
Without this PR  http://openqaworker15.qa.suse.cz/tests/321740
With the code in this PR http://openqaworker15.qa.suse.cz/tests/321741

Allow HanaSR test to support both peering methods

---

tests/sles4sap/publiccloud/network_peering.pm

Do not check variables about IBSM that only belong to Azure when running a deploymewnt on a different CSP.
Follow up of https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/21601
BYOS https://openqaworker15.qa.suse.cz/tests/321730
PAYG https://openqaworker15.qa.suse.cz/tests/321731  https://openqaworker15.qa.suse.cz/tests/321732

Avoid failure in GCE IBSm network peering

---

lib/containers/bats.pm

There are some SELinux policies that are not audited by default.  To ease debugging, we must _rebuild the policy without the so-called "dontaudit" rule_ as suggested by https://en.opensuse.org/Portal:SELinux/Troubleshooting
- Related ticket: https://bugzilla.suse.com/show_bug.cgi?id=1238136
- Verification run: https://openqa.opensuse.org/tests/5001800/file/audit.txt

containers: Rebuild SELinux policies without the dontaudit rules

---

data/sles4sap/qe_sap_deployment/sles4sap_azure_generic.yaml
data/sles4sap/qe_sap_deployment/sles4sap_azure_generic_uri.yaml

Align them about variables for IBSm and network_ranges
- Related ticket: https://jira.suse.com/browse/TEAM-10232
https://openqaworker15.qa.suse.cz/tests/321830 :green_circle: New terraform vars are in the https://openqaworker15.qa.suse.cz/tests/321830/file/deploy_qesap_terraform-sles4sap_azure_generic.yaml , peering is created in Terraform https://openqaworker15.qa.suse.cz/tests/321830/logfile?filename=deploy_qesap_terraform-terraform.apply.log.txt#line-31
https://openqaworker15.qa.suse.cz/tests/321840 :green_circle:  this one is with old JobGroup, peering not created in Terraform but using az cli. https://openqaworker15.qa.suse.cz/tests/321840/file/deploy_qesap_terraform-sles4sap_azure_generic_maintenance.yaml  `ibsm_vnet_name: ''` has an empty value and it result in the terraform code …

Align all the Azure HanaSR conf.yaml

---

tests/sles4sap/publiccloud/qesap_terraform.pm

Define with empty variables IBSM_VPC_NAME, IBSM_SUBNET_NAME and IBSM_SUBNET_REGION.
https://openqaworker15.qa.suse.cz/tests/321941
sle-12-SP5-HanaSr-Gcp-Byos-x86_64-Build12-SP5_2025-04-18T02:03:17Z-hanasr_gcp_test_fencing_native_ltss_es gce_n1_highmem_8
- http://openqaworker15.qa.suse.cz/tests/321933 :green_circle: 
sle-15-SP6-HanaSr-Gcp-Byos-x86_64-Build15-SP6_2025-04-18T02:03:17Z-hanasr_gcp_test_peering gce_n1_highmem_8
- http://openqaworker15.qa.suse.cz/tests/321934 :green_circle:

Add a default value to IBS GCE variables

---

data/autoyast_opensuse/autoyast_firstboot.xml

The autoyast startup script relies on Xorg to start up the GUI session,
wheras the 'gnome' pattern no longer pulls in Xorg directly.
As autoyast is benig deprecated (in favor of Agama), there is no interest
in fixing the AY startup scripts.
When purely relying on GNOME (wayland), one can steps through the firts boot
wizard in ncurses mode
- Related ticket: https://bugzilla.suse.com/show_bug.cgi?id=1240855
- Needles: N/A
- Verification run: https://openqa.opensuse.org/tests/4995826

Autoyast firstboot: Use GNOME_X11 pattern

---

lib/main_containers.pm
tests/containers/podmansh.pm

Fixes issues with running on Tumbleweed, MicroOS and JeOS from [here](https://openqa.opensuse.org/tests/overview?result=failed&result=incomplete&result=timeout_exceeded&arch=&flavor=&machine=&test=&modules=&module_re=&group_glob=&not_group_glob=&comment=164015&distri=microos&distri=opensuse&version=Tumbleweed&build=20250409&groupid=1#).
- Related ticket: https://progress.opensuse.org/issues/164015
- Needles: N/A
- VRs:
TW: https://openqa.opensuse.org/tests/4999392#step/podmansh/1
MicroOS: https://openqa.opensuse.org/tests/4999393#step/podmansh/1
JeOS: https://openqa.opensuse.org/tests/4999394#step/podmansh/1
~Note: The `rootless_podman` test doesn't properly restore the user environment and leaves the user session unclean, hence breaking Tumbleweed and JeOS runs if executed before …

Reenable and fix podmansh for Tumbleweed, MicroOS and JeOS 

---

lib/serial_terminal.pm

According to https://bugzilla.suse.com/show_bug.cgi?id=1240570#c1, we should set PAGER=more instead of using PAGER=less when dumb terminal is used. Otherwise, we can hit an issue in sle16
```
$ zypper lifecycle --help; echo 5YDH1-$?-
WARNING: terminal is not fully functional
Press RETURN to continue
```
- Related ticket: https://bugzilla.suse.com/show_bug.cgi?id=1240570
* [sle16](http://kepler.suse.cz/tests/24661#step/zypper_lifecycle/1) 
* [sp7](http://kepler.suse.cz/tests/24660#step/zypper_lifecycle/1)
* [sle-15-SP7@s390x-kvm ](https://openqa.suse.de/tests/17377504)

Set PAGER=more for serial console

---

.gitignore
.perltidyrc
Makefile

There were complaints about a `.perltidyrc` change in os-autoinst.
Since os-autoinst is cloned in osado and `.perltidyrc` is just a symlink to the one in os-autoinst, changes there will have an immediate effect here.
With this osado maintainers can decide about their own perltidy rules.

Use independent .perltidyrc

---

lib/rdma.pm
tests/xfstests/partition.pm

Add support to test NFS over RDMA. The RDMA link is default emulated by rdma_rxe not real card, so the lib/rdma.pm only has its related function. Also, splitting the setting between NFS-server and NFS-client, makes it more clear.
- Related ticket: https://progress.opensuse.org/issues/177937
- Verification run: http://10.67.20.191/tests/17#step/partition/82   mount with RDMA OK
(If you can't access this link, I upload two snapshot. They are the prove that RDMA link enabled in NFS, otherwise it will shows "TCP")

xfstests: add support to test NFS over RDMA

---

lib/containers/bats.pm
lib/main_containers.pm
tests/containers/bats/README.md
tests/containers/bats/aardvark.pm
tests/containers/bats/netavark.pm
tests/containers/bats/podman.pm
tests/containers/bats/runc.pm
tests/containers/bats/skopeo.pm

Minor BATS tests enhancements:
- Simplify scheduling
- Upload kernel configuration in post hook
- Drop iptables dependency as packages are supposed to pull them in
- netavark: Remove iptables test if it's not a firewalld backend
- podman: Allow 180-blkio & remove 320-system-df
- Document skipped tests in Tumbleweed.
- aardvark: https://openqa.opensuse.org/tests/5009538
- buildah: https://openqa.opensuse.org/tests/5009539
- netavark: https://openqa.opensuse.org/tests/5009549
- podman: https://openqa.opensuse.org/tests/5009541
- runc: https://openqa.opensuse.org/tests/5010365
- skopeo: https://openqa.opensuse.org/tests/5009543

Minor BATS tests enhancements

---

tests/x11/vnc_two_passwords.pm

The 8 char password max is a protocol limitation, rather than an implementation issue.
See [1]:
"The client encrypts the challenge with DES, using a password supplied by the user as
the key. To form the key, the password is truncated to eight characters, or padded
with null bytes on the right."
[1] https://www.rfc-editor.org/rfc/rfc6143#section-7.2.2
- Related ticket: https://progress.opensuse.org/issues/181235
- Verification run:  https://openqa.opensuse.org/tests/5011250#step/vnc_two_passwords/82
Failure is https://bugzilla.opensuse.org/show_bug.cgi?id=1241518

Adjust password length according to vnc RFC

---

schedule/functional/wireguard_nm.yaml
tests/network/wireguard_nm.pm

Use networkmanager to configure wireguard server and client
- Related ticket: https://progress.opensuse.org/issues/180119
- Verification run:  https://openqa.suse.de/tests/17340072#
https://openqa.suse.de/tests/17340073
Verified on TW: https://openqa.opensuse.org/tests/4994553#
https://openqa.opensuse.org/tests/4994554#

Use networkmanager to configure wireguard server and client

---

lib/containers/utils.pm

Remove unused library calls: `get_podman_version` & `get_docker_version`.
There are no consumers of these functions now.
- Related ticket: https://progress.opensuse.org/issues/155470

Remove unused library calls

---

lib/containers/utils.pm

Remove unused library calls: `get_podman_version` & `get_docker_version`
Related ticket: https://progress.opensuse.org/issues/155470

containers: Remove unused library calls

---

lib/containers/bats.pm

Add more logs to BATS tests:
- sysctl's
- IP addresses & routes
- Dump of iptables/nftables rules
Needed to debug network tests.
- Verification run: https://openqa.opensuse.org/tests/5013839 (`BATS_TESTS=505-networking-pasta`)
VR fails for $reasons.

containers: Add more logs to BATS tests

---

lib/sles4sap/ipaddr2.pm
t/22_ipaddr2.t
tests/sles4sap/ipaddr2/cluster_create.pm
tests/sles4sap/ipaddr2/configure.pm
tests/sles4sap/ipaddr2/destroy.pm
tests/sles4sap/ipaddr2/network_peering.pm
tests/sles4sap/ipaddr2/patch_system.pm
tests/sles4sap/ipaddr2/registration.pm
tests/sles4sap/ipaddr2/sanity_cluster.pm
tests/sles4sap/ipaddr2/sanity_os.pm
tests/sles4sap/ipaddr2/test_move_resource.pm

Move the function call about the IBSm network peering delete from the library up to each test module.
- Related ticket: https://jira.suse.com/browse/TEAM-10277
sle-15-SP6-SapCloud-Azure-Payg-x86_64-BuildLATEST_AZURE_SLE15_6_PAYG-ipaddr2_azure_test_rootless
- http://openqaworker15.qa.suse.cz/tests/321937 :green_circle: 
sle-15-SP6-SapCloud-Azure-Payg-x86_64-BuildLATEST_AZURE_SLE15_6_PAYG-ipaddr2_azure_test_rootless  with wrong CLUSTER_OS_VER=paperino
- http://openqaworker15.qa.suse.cz/tests/321938 :green_circle: job fails as expected in [deploy](https://openqaworker15.qa.suse.cz/tests/321938/modules/deploy/steps/1/src) and post_fail_hook runs
- sle-15-SP5-SapCloud-Azure-Byos-x86_64-BuildLATEST_AZURE_SLE15_5_BYOS-ipaddr2_azure_test -> http://openqaworker15.qa.suse.cz/tests/321939
- …

Move one ipaddr2 dependency on qesap

---

lib/containers/bats.pm
tests/containers/bats/podman.pm

Currently we're "skipping" (ignoring the failure of) `120-load`.  This will allows us to remove `120-load` from the BATS_SKIP variables.
Also fix an issue when calling `hack/bats` with `.bats` extensions.
- Verification run: https://openqa.opensuse.org/tests/5014237#external

Fix podman scp upstream test

---

lib/containers/bats.pm
tests/containers/bats/README.md
tests/containers/bats/aardvark.pm
tests/containers/bats/buildah.pm
tests/containers/bats/netavark.pm
tests/containers/bats/podman.pm
tests/containers/bats/runc.pm
tests/containers/bats/skopeo.pm

Introduce the BATS_PATCHES variable.
This will help us to dramatically reduce the number of ignored tests via the `BATS_SKIP_*` variables.
- Verification run: https://openqa.opensuse.org/tests/5014486#external (`BATS_PATCHES="25918 25955"`)
In the [original test](https://openqa.opensuse.org/tests/5013185) we ignore `195-run-namespace`.  The above VR downloads the test patches specified by BATS_PATCHES so we can stop ignoring most tests.

containers: Introduce BATS_PATCHES

---

lib/registration.pm

##
Fix rm registercloudguest in serial console
- Related ticket: https://openqa.suse.de/tests/17384648#step/scc_deregistration/26
- Needles: N/A
- [select_serial_console]
-  https://openqa.suse.de/tests/17419339#dependencies
- [select_root_console]
- https://openqa.suse.de/tests/17432755#dependencies
##

Fix rm registercloudguest in serial console

---

lib/bootloader_setup.pm

This reverts commit 374543fa07c6b6143449f1d72621f6eb17ea0016.
SLE 16 changed content of /etc/os-release to previous state and we
need to revert to original setup.
- Related fail: https://openqa.suse.de/tests/17430835#step/install_ltp/215
SLE16: https://openqa.suse.de/tests/17434976
TW:  https://openqa.opensuse.org/tests/5015867
SLE15-SP7: https://openqa.suse.de/tests/17434989

Revert "lib/bootloader_setup: Add check for SLE16 in add_custom_grub_entries"

---

products/sle/main.pm
variables.md

1. Skip installation on s390 and ppc64 in SLE16
2. Update variables.md for XFSTESTS and XFSTESTS_INSTALL
- Related ticket: https://progress.opensuse.org/issues/181211
- Needles: N/A
https://openqa.suse.de/tests/17429939
https://openqa.suse.de/tests/17434926

xfstests: Skip installation on s390 ppc64 in SLE16

---

tests/console/check_os_release.pm

The `PRETTY_NAME` is changed to the previous format, so revert some
changes in pr #21646.
Related: https://progress.opensuse.org/issues/179765
VR: https://openqa.suse.de/tests/17433229#

Change `PRETTY_NAME` check value for sle16

---

lib/serial_terminal.pm

This reverts commit 63d1eab39da758ee60fa00256a1408b2b58cfdb6.
The problem that was reported https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/21832#issuecomment-2825542819 is in fact in the perf module https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/21869

Set PAGER=cat for serial console

---

lib/main_containers.pm

On SLEM 6.1 there is no podmansh package available.
- Related failure: https://openqa.suse.de/tests/17436204
- Related ticket: https://bugzilla.suse.com/show_bug.cgi?id=1241694 (requests `podmansh` for SLEM 6.2)
- Verification run: https://openqa.suse.de/tests/17442332 (`podmansh` not scheduled)

Skip podmansh on SLEM 6.1

---

lib/main_containers.pm

This module is failing on SLE 16.0.  I suggest moving to a separate job or make it run last so we can test other modules as this one is fatal to the whole job.
https://openqa.suse.de/tests/overview?distri=sle&version=16.0&build=78.2&groupid=630

containers: Temporarily mute podmansh

---

lib/main_containers.pm

Reverts os-autoinst/os-autoinst-distri-opensuse#21877 as this change was made hastily. We should fix the test module instead.

Revert "containers: Temporarily mute podmansh"

---

lib/main_common.pm

`apache_nss` will not be part of SLES 16.
- Related ticket: https://bugzilla.suse.com/show_bug.cgi?id=1236295#c3
- Verification run: https://openqa.suse.de/tests/17443316 (no `apache_nss` scheduled)

Skip apache_nss on SLES 16

---

tests/containers/bats/runc.pm

Use go1.24 for runc upstream tests.
The new update from runc 1.1.x to runc 1.2.x in 15-SP3 & 15-SP4 needs a newer Go version >= 1.21.  Let's use the latest as it's available on SLES 15-SP3+
```
$ susepkg -p any go1.24 | grep SLES/
SLES/15.3 go1.24 1.24.0-150000.1.9.1
SLES/15.4 go1.24 1.24.0-150000.1.9.1
SLES/15.5 go1.24 1.24.0-150000.1.9.1
SLES/15.6 go1.24 1.24.2-150000.1.17.1
SLES/15.7 go1.24 1.24.1-150000.1.12.1
SLES/16.0 go1.24 1.24.1-160000.1.3
```
- Failing test: https://openqa.suse.de/tests/17449303/logfile?filename=serial_terminal_user.txt
```
$ make memfd-bind fs-idmap pidfd-kill recvtty remap-rootfs sd-helper seccompagent; echo u7TUW-$?-
52	fatal: not a git repository (or any parent up to mount point /)
53	Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set). …
```

containers: Use go1.24 for runc upstream tests

---

tests/ha/filesystem.pm

After abea00d4715617b641cf30585ec3ebd83b30b1a9 was merged, we noticed the `ha/filesystem` module sporadically failing in 15-SP4 on some timeouts while moving the drbd_passive resource from one node to the other, and some unexpected `exit` commands in the serial terminal in 15-SP6 while checking integrity of files created on a FS on top of a drbd_passive device. This commit makes `ha/filesystem` run in the `root-console` when working on drbd_passive for all supported SPs.
- Needles: N/A

Run ha/filesystem module in root-console for drbd_passive

---

lib/containers/bats.pm

Avoid patching BATS tests if `BATS_URL` is specified.  When cloning with `BATS_URL`, patching is not desired as the branch contains the patches.
VR not needed as currently we don't have any jobs with both `BATS_URL` & `BATS_PATCHES` specified.

containers: Avoid patching BATS tests if BATS_URL is specified

---

tests/ha/ha_cluster_init.pm

The variable `$qdevice_opt` is not initialized in the test module `ha/ha_cluster_init` causing warnings such as this to be printed in autoinst-log.txt:
```
Use of uninitialized value $qdevice_opt in concatenation (.) or string at sle/tests/ha/ha_cluster_init.pm line 32.
ha_cluster_init::cluster_init("crm-cluster-init", "-s \"/dev/disk/by-path/ip-10.0.2.1:3260-iscsi-iqn.2016-02.de.o"..., "", undef) called at sle/tests/ha/ha_cluster_init.pm line 81
ha_cluster_init::run(ha_cluster_init=HASH(0x55688987ff58)) called at /usr/lib/os-autoinst/basetest.pm line 346
```
This fixes it.
- Failure: https://openqa.suse.de/tests/17456274/logfile?filename=autoinst-log.txt#line-2872
- Needles: N/A
- Verification run: N/A. `undef` is already evaluated as the empty string.

Assign default value to $qdevice_opt

---

lib/main_common.pm
tests/microos/workloads/x11-container/x11_client.pm
tests/microos/workloads/x11-container/x11_server.pm

Only covered deploy the below containers with podman: 
x11 container, pulseaudio container and firefox kiosk container
- Related ticket: https://progress.opensuse.org/issues/174418
- Needles: already added when debugging on osd
- Test suites settings can be found https://openqa.suse.de/admin/test_suites
**(Grace updated below info on Apr 25)**: 
- Verification run：
x11_client https://openqa.suse.de/tests/17452967#
x11_server https://openqa.suse.de/tests/17452966#
The `my ($pacontainerpath, $ffcontainerpath) = split(/\s+/, get_var("CONTAINER_IMAGE_TO_TEST", PA-IMAGEURL FF-IMAGEURL));` works as expected.
Tests failed since there are some issues exist (such as https://suse.slack.com/archives/C06S6BAGCPR/p1745416155523529)
The fix is on the way. 
The VR for registry.opensuse.org image URLs:
> …

Add test cases for x11 related containers' testing with podman

---

tests/kernel/ulp_openposix.pm

Add ulp live patch testing for sle16
- Related ticket: https://progress.opensuse.org/issues/179083
- Verification run: https://openqa.suse.de/tests/17442349

Add ulp live patch testing for sle16

---

lib/containers/bats.pm
tests/containers/bats/aardvark.pm
tests/containers/bats/buildah.pm
tests/containers/bats/netavark.pm
tests/containers/bats/podman.pm
tests/containers/bats/runc.pm
tests/containers/bats/skopeo.pm

Minor refactor of BATS tests:
- Move sources download to library
- Install ncat in bats_setup
- `BATS_PATCHES` can also be an URL
- Allow flexible `BATS_URL`
- Log package/OS version in TAP file
- aardvark: https://openqa.opensuse.org/tests/5024523 (`BATS_URL=main`)
- buildah: https://openqa.opensuse.org/tests/5024524 (`BATS_URL=containers#main`)
- netavark: https://openqa.suse.de/tests/17480749 (`BATS_URL=https://github.com/containers/netavark/archive/refs/heads/main.tar.gz`)
- podman: https://openqa.opensuse.org/tests/5024526 (`BATS_PATCHES=https://github.com/containers/podman/pull/25918.diff`)
- runc: https://openqa.opensuse.org/tests/5024527
- skopeo: https://openqa.opensuse.org/tests/5024528

Minor refactor of BATS tests

---

tests/migration/online_migration/yast2_migration.pm

- Verification run: [Migration-from-SLE15-SPx-Milestone](https://openqa.suse.de/tests/overview?build=leo-test-2025-04-24)
> _It looks like 15SP7 is the same with other SPx now: send_key `alt-t`_
Failed jobs: [Migration-from-SLE15-SPx-Milestone](https://openqa.suse.de/tests/overview?result=failed&groupid=266&failed_modules=yast2_migration&build=85.1)

Fix import gpg key

---

test_data/yast/opensuse/btrfs/btrfs+warnings_aarch64.yaml

It seems that the minimum size for /boot/efi changed in the meantime to > 0.5GB
Ticket: https://progress.opensuse.org/issues/176601
VR https://openqa.opensuse.org/tests/5026151

Adapt minimum size warning for boot on installer

---

lib/containers/bats.pm
tests/containers/bats/README.md
tests/containers/bats/buildah.pm
tests/containers/bats/netavark.pm
tests/containers/bats/podman.pm
tests/containers/bats/runc.pm
tests/containers/bats/skopeo.pm

Introduce `run_command` wrapper for `assert_script_run` to create a reproducer shell script for BATS tests which may be used to manually reproduce an issue.  This may be put in Bugzilla, Github issues, etc.
- aardvark-dns: https://openqa.opensuse.org/tests/5026286/logfile?filename=aardvark-commands.txt
- buildah: https://openqa.opensuse.org/tests/5026387/logfile?filename=buildah-commands.txt
- netavark: https://openqa.opensuse.org/tests/5026216/logfile?filename=netavark-commands.txt
- podman: https://openqa.opensuse.org/tests/5026217/logfile?filename=podman-commands.txt
- runc: https://openqa.opensuse.org/tests/5026218/logfile?filename=runc-commands.txt
- skopeo: https://openqa.opensuse.org/tests/5026219/logfile?filename=skopeo-commands.txt

containers/bats: Introduce run_command wrapper

---

lib/containers/bats.pm
tests/containers/bats/README.md

Since we have `BATS_PACKAGE` to schedule the tests, we don't overload `BATS_SKIP` anymore so we can drop the special value `none` and use an empty string instead.
Related MR: https://gitlab.suse.de/qac/qac-openqa-yaml/-/merge_requests/2210
Related PR: https://github.com/os-autoinst/opensuse-jobgroups/pull/656

containers/bats: No need for special value none anymore

---

lib/containers/bats.pm

Use mktemp output to manually create directory so it appears in commands.txt

containers/bats: Use mktemp output to create directory

---

lib/containers/bats.pm

Add timing information for each subtest to .tap files
Each test will now be shown as:
```
ok 1 [505] IPv4 default address assignment in 1403ms
ok 2 [505] IPv4 address assignment in 1220ms
ok 3 [505] No IPv4 in 1258ms
```
Manually tested.

containers/bats: Add timing information to .tap files

---

tests/x11/exiv2.pm

Install eog as it cannot be installed by default
- Related ticket: https://progress.opensuse.org/issues/181349
- Verification run: https://openqa.opensuse.org/tests/5027185#step/exiv2/10

Install eog as it is not installed by default

---

lib/containers/bats.pm

Skip PASS `record_info` for empty test.
https://openqa.opensuse.org/tests/5028317#step/runc/251

containers/bats: Skip PASS for empty test

---

lib/main_containers.pm

Temporarily skip the podmansh tests on MicroOS due to ongoing issues, see https://progress.opensuse.org/issues/181316.
- [MicroOS](https://openqa.opensuse.org/tests/5029055) (not scheduled)
- [Tumbleweed](https://openqa.opensuse.org/tests/5029066) (`podmansh` being scheduled)

Skip podmansh on MicroOS

---

tests/installation/addon_products_sle.pm

Related: https://progress.opensuse.org/issues/181430
VRs:
x86: https://openqa.suse.de/tests/17473950#step/addon_products_sle/62 
aarch64:  https://openqa.suse.de/tests/17473974#step/addon_products_sle/52
ppc64le: https://openqa.suse.de/tests/17473972#step/addon_products_sle/52
s390x: https://openqa.suse.de/tests/17473970#step/addon_products_sle/50 
More VRs in: https://openqa.suse.de/tests/overview?build=Amrysliu%2Fos-autoinst-distri-opensuse%2321893&distri=sle&version=15-SP6

Add systems-management for QR test

---

tests/microos/toolbox.pm

Fix toolbox test on MicroOS
- Failing test: https://openqa.opensuse.org/tests/5030846#step/toolbox/48
- Verification run: https://openqa.opensuse.org/tests/5031913 (now it fails properly with https://bugzilla.opensuse.org/show_bug.cgi?id=1239776)

Fix toolbox test on MicroOS

---

data/publiccloud/terraform/gce.tf

This parameter causing `Error creating instance: googleapi: Error 400: e2 instances do not support onHostMaintenance=TERMINATE unless they are preemptible., badRequest` . On other hand confidential VMs can be succesfully created w/o it ( see VR : https://openqa.suse.de/tests/17514300 )

Drop of not required parameter which causing issues

---

data/autoyast_sle15/mini_s390x.xml
data/yam/autoyast/create_hdd_textmode_powervm.xml
data/yam/autoyast/mini_desktop_remote.xml
schedule/yast/autoyast/autoyast_mini_spvm.yaml

Update 15sp7 autoyast profiles to open sshd service in minimal installation, based on [bsc#1241954](https://bugzilla.suse.com/show_bug.cgi?id=1241954#c12), update the mini autoyast profiles;
Add an autoyast profile for testsuite autoyast_create_hdd_gnome on power, the testsuite is using a minimal installation profile, add a new one for it which includes desktop applications module selected; 
And correct a profile of create_hdd_textmode_powervm.xml which has a duplicated addon of python3 module by changing one of them to sle-module-systems-management which is a new default selected module on SLES15SP7.
- Related failures: [autoyast_mini@ppc64le-spvm](https://openqa.suse.de/tests/17452919#step/console/1) ; [autoyast_mini@s390x-kvm](https://openqa.suse.de/tests/17452720#step/console/1); …

Update 15sp7 autoyast profiles to open sshd service in mini installation

---

data/ha/agama/sles_ha_default.jsonnet
data/ha/agama/sles_ha_default_pvm.jsonnet
data/ha/agama/sles_ha_default_s390x_kvm.jsonnet

This commit adds to the x86_64 & aarch64 qemu jsonnet file for SLES+HA the configuration required so the HA Extension is activated during installation.
Additionally new SLES+HA jsonnet files have been created for s390x on svirt and for ppc64le on pvm, also including the activation of the HA Extension during installation.
- Related ticket: https://jira.suse.com/browse/TEAM-10163
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/overview?distri=sle&build=VR4PR21919&version=16.0

Add SLES+HA agama auto jsonnet files

---

lib/transactional.pm

- Verification run: [slem_migration_6.1_to_6.2__TEST__](https://openqa.suse.de/tests/overview?build=leo-test-fix-check-version)
> there are some changes in `/etc/os-release` on SL-Micro 6.2
`VERSION="16.0 Beta4"`
See [/etc/os-release](https://openqa.suse.de/tests/17429188#step/zypper_migration/34) content.
See [confluence document](https://confluence.suse.com/display/~okir/Another+attempt+at+os-release).

Fix check_target_version

---

lib/kernel.pm
lib/klp.pm
tests/kernel/update_kernel.pm

SL-Micro livepatch installation requires special handling. Add support for selecting the correct package to test.
- Related ticket: https://progress.opensuse.org/issues/181508
- Needles: N/A
- SLE kernel-default: https://openqa.suse.de/tests/17516432
- SLE kernel-livepatch: https://openqa.suse.de/tests/17516433
- kernel-default-base: https://openqa.suse.de/tests/17516434
- kernel-azure (GM kernel): https://openqa.suse.de/tests/17516435
- kernel-azure (update): https://openqa.suse.de/tests/17516436
- SL-Micro kernel-livepatch: https://openqa.suse.de/tests/17516437
- SL-Micro 6.0 kernel-rt-6.4.0-10 livepatch: https://openqa.suse.de/tests/17516438
Note: Most verification runs will fail because the update repositories don't exist. There are no updates in the queue at the …

Add support for testing SL-Micro livepatches

---

tests/containers/bats/podman.pm

Load null_blk module for podman tests.
> Since /dev/zero is not a block device, it's unsuitable for testing cgroup controls designed for block devices.
From https://github.com/containers/podman/pull/26022#issuecomment-2842186141

containers/bats: Load null_blk module for podman tests

---

tests/kernel/blktests.pm

- Related ticket: https://progress.opensuse.org/issues/181649
- Verification run: https://openqa.suse.de/tests/17527953
In the VR we can see the value isn't causing the test to fail however we still have some other issues with the blktests

Storage: Make blktests config not mandatory

---

data/journal_check/bug_refs.json

Ignore when chrony warns about a falseticker as this is an infra problem where we cannot do much about it.
- Related failure: https://openqa.suse.de/tests/17519419#step/journal_check/9
- Verification run: https://duck-norris.qe.suse.de/tests/14843#step/journal_check/1

Ignore falseticker

---

data/publiccloud/terraform/gce.tf

e2 instances do not support onHostMaintenance=TERMINATE but c3-highcpu-192-metal requires it.
Lets use dynamic to convince both
VRs : 
- https://openqa.suse.de/tests/17530832
- https://openqa.suse.de/tests/17530835
- https://openqa.suse.de/tests/17530836

Implement conditional use of scheduling parameter

---

lib/main_containers.pm

De-schedule podman on SLEM & Leap Micro.
```
$ susepkg -p any podmansh
SLES/15.5 podmansh 4.9.5-150500.3.40.1
SLES/15.6 podmansh 4.9.5-150500.3.40.1
SLES/15.7 podmansh 4.9.5-150500.3.40.1
SLES/16.0 podmansh 5.2.5-160000.4.2
SLE-Micro/5.5 podmansh 4.9.5-150500.3.40.1
openSUSE_Leap/15.6 podmansh 4.9.5-150500.3.40.1
openSUSE_Tumbleweed podmansh 5.4.2-1.1
```
- Failing tests: https://openqa.suse.de/tests/overview?distri=sle-micro&version=6.2&build=8.9&groupid=513

containers: De-schedule podman on SLEM & Leap Micro

---

tests/containers/image.pm

Prior to pulling a released ltss container, the test needs to log in the container engine to registry.suse.com. This can be done by using the already registered credentials in `/etc/zypp/credentials.d/SCCcredentials` or by simply using the LTSS regcode that we already have present in the tests and should work also for non-suse hosts if required.
- ticket: https://progress.opensuse.org/issues/181652
- Verification run: http://kepler.suse.cz/tests/24696#step/image_docker/80

Allow ltss containers to be downloaded

---

tests/containers/bats/README.md

Display status badge for o3 jobs on BATS README.
Verification:
https://github.com/ricardobranco777/os-autoinst-distri-opensuse/blob/badge/tests/containers/bats/README.md#openqa-jobs
Doesn't work on osd due to being in internal network.

containers/bats: Show badge for openQA jobs on o3

---

tests/jeos/firstrun.pm

The user creation is optional, therefore the wheel group check should reflect to the test suite settings as well.
- VR: http://kepler.suse.cz/tests/24700#step/firstrun/60

Skip wheel check if not user is created

---

schedule/security/agama_tpm_fde_unattended.yaml

Add YAML for QE Security TPM FDE tests for hdd creation
- Related ticket: https://progress.opensuse.org/issues/176691
- https://openqa.suse.de/tests/17563625
- https://openqa.suse.de/tests/17563669

Add TPM FDE YAML schedule with shutdown

---

schedule/security/apparmor_profile.yaml

- Related ticket: https://progress.opensuse.org/issues/176154
https://openqa.opensuse.org/tests/overview?distri=opensuse&version=Tumbleweed&build=jpupava_apparmorp o3
https://openqa.suse.de/tests/overview?distri=sle&version=15-SP6&build=jpupava_apparmorp sle

usr_sbin_nscd: Don't schedule on TW

---

data/containers/ibm_hpvs/workload.yaml

`logRouter` is the method how to store logs from instances. This is currently the only logging method used in case of HPVS containers testing.
- Verification run: http://kepler.suse.cz/tests/24704#step/prepare_hpvs/135

Change logging method in ibm cloud

---

lib/containers/bats.pm

Tune curl options to workaround github rate limits.
- Failing test: https://openqa.suse.de/tests/17568241#step/podman/231
- Verification run: https://openqa.suse.de/tests/17568668

bats: Tune curl options to workaround github rate limits

---

schedule/sle-perf/setup_host.yaml
tests/kernel_performance/install_sleperf.pm

Since we use the new deploy scripts to setup our testing environment.
- Related ticket:https://progress.opensuse.org/issues/179068
- Verification run:http://10.200.129.6/tests/84504;http://10.200.129.6/tests/84628#;http://10.200.129.4/tests/80693

Add file for setup sleperf environment

---

tests/ai_ml/armnn.pm

- Verification run: https://openqa.opensuse.org/tests/5043859

armnn: skip TensorFlow Lite backend on Tumbleweed

---

data/sles4sap/qe_sap_deployment/qesap_gcp_peering.yaml

Add terraform variable about the IP ranges to use.
sle-15-SP6-Qesap-Gcp-Payg-x86_64-BuildLATEST_GCE_SLE15_6_PAYG-qesap_gcp_ibsmirror_peering_test
- http://openqaworker15.qa.suse.cz/tests/323485 :green_circle: 
- http://openqaworker15.qa.suse.cz/tests/323486 second one in parallel :green_circle:

Add ip_cidr_range to GCP pering test

---

tests/sles4sap/qesapdeployment/destroy.pm
tests/sles4sap/qesapdeployment/test_mirror.pm

Add peering cleanup in qesap regression test for tests that are running test_mirror and are configured to run for AWS.
- Related ticket: https://jira.suse.com/browse/TEAM-10325
- sle-15-SP6-Qesap-Aws-Byos-x86_64-BuildLATEST_AWS_SLE15_6_BYOS-qesap_aws_ibsmirror_peering_test -> http://openqaworker15.qa.suse.cz/tests/323468 :green_circle: https://openqaworker15.qa.suse.cz/tests/323468/logfile?filename=serial_terminal.txt&filter=aws%20ec2%20del
- sle-15-SP6-Qesap-Aws-Byos-x86_64-BuildLATEST_AWS_SLE15_6_BYOS-qesap_aws_ibsmirror_peering_test intentionally triggered without a needed variable to get a failure in test_mirror and check that cleanup works -> http://openqaworker15.qa.suse.cz/tests/323478

Add AWS peering cleanup

---

tests/rt/rt_is_realtime.pm

The realtime sysfs entry is gone, at least in sle micro 6.2 for now.
- Verification run: http://kepler.suse.cz/tests/24705#step/rt_is_realtime/1

Dont check realtime sysfs entry

---

tests/containers/realtime.pm

As mentioned in https://bugzilla.suse.com/show_bug.cgi?id=1242130, the sysfs kernel flag has been deprecated.
- Verification run: http://kepler.suse.cz/tests/24706#

Remove RT check in sysfs

---

tests/containers/bci_test.pm

Allow no test environments so that dummy test runs (e.g. for AI) are possible.
- Related: https://gitlab.suse.de/qac/container-release-bot/-/merge_requests/427
- Verification run: https://openqa.suse.de/tests/17593799

Allow empty tests run

---

schedule/virt_autotest/sle16_guest_installation.yaml

Enable UEFI and secure boot test work for sle16
Add uefi_guest_verification 
- Related ticket: https://progress.opensuse.org/issues/178699
[uefi-gi-guest_developing-on-host_developing-kvm](https://openqa.suse.de/tests/17564778#) PASS

virt_autotest Enable UEFI and secure boot test work for sle16

---

tests/containers/bci_test.pm

An empty test environment will cause the test to fail, while still allowing the explicit '-' to just skip it.
- Related: https://suse.slack.com/archives/C02CGKBCGT1/p1746561629691469?thread_ts=1746550305.107349&cid=C02CGKBCGT1
- Verification runs: [Empty environment](https://openqa.suse.de/tests/17603061#step/bci_test_podman/2) (fails intentionally) | [Skip](https://openqa.suse.de/tests/17603067)

Make an empty test environment an error

---

tests/microos/networkmanager.pm

Need to get the dynamic interface name instead of hard-coding eth0
- Related ticket: https://progress.opensuse.org/issues/181724
- Verification run: https://openqa.suse.de/tests/17604451

Need to get the dynamic interface name instead of hard-coding eth0

---

tests/installation/validation/ibft.pm

We have changed the way to check ibft in the agama logs.
- Related ticket: https://progress.opensuse.org/issues/181394
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/17517795# (Failed in a further step)

Update the zgrep search log to agama_auto-agama-logs.tar.gz for ibft validation

---

tests/ha/barrier_init.pm
tests/ha/wait_barriers.pm

Currently, HA modules rely on barriers to sync test steps among nodes, they do so by calling `barrier_wait()` API without checking whether the barriers have been created. This can lead to unexpected failures when jobs other than the parent job run first and attempt to call `barrier_wait()` on a barrier which has not been created. In those cases, tests will fail on a call to `bmwqemu::mydie()` as part of the `_try_lock()` function in `lockapi`.
To avoid such failures, this commit introduces a new mutex called `ha_barriers_ready` which is created at the end of the `ha/barrier_init` test module after all the necessary barriers have been created. The mutex is used in the `ha/wait_barriers` module before the call to `barrier_wait()` with a call to `mutex_wait()` which will block the process …

Add mutex to signal when HA barriers are ready to use

---

tests/fips/fips_setup.pm

- Related ticket: https://progress.opensuse.org/issues/181931
- Bug: https://bugzilla.opensuse.org/show_bug.cgi?id=1239509
- Verification run: https://openqa.suse.de/tests/17605494 (HDD creation) -> https://openqa.suse.de/tests/17606063 (where ssh starting would fail in consoletest_setup if openssl-3 would not be installed)

Manually installing openssl-3 should not be needed anymore

---

data/sles4sap/qe_sap_deployment/sles4sap_azure_generic.yaml
data/sles4sap/qe_sap_deployment/sles4sap_gcp_generic.yaml

Add ip_cidr_range terraform variable to the conf.yaml used by HanaSR.
- sle-15-SP6-HanaSr-Gcp-Byos-x86_64-Build15-SP6_2025-05-07T02:03:20Z-hanasr_gcp_test_peering@gce_n1_highmem_32 -> http://openqaworker15.qa.suse.cz/tests/323600

Add ip_cidr_range to GCP HanaSR

---

tests/console/firewall_enabled.pm

MinimalVM/JeOS has image specific setup in terms of firewall
1) VMWare -> package is pre-installed, FW disabled 
2) Cloud -> package is NOT pre-installed
3) Others -> FW is running
`firewall-cmd --version` shows the version only if firewalld is
running at that moment.
* [opensuse-Tumbleweed-NET-x86_64-Build20250506-minimalx](http://kepler.suse.cz/tests/24722#step/firewall_enabled/11)
* [15-SP7-JeOS-for-OpenStack-Cloud-x86_64-Build3.17-jeos-cloud-init](http://kepler.suse.cz/tests/24718#step/firewall_enabled/3)
* [sle-15-SP7-JeOS-for-OpenStack-Cloud-x86_64-Build3.17-jeos-wizard](http://kepler.suse.cz/tests/24719#step/firewall_enabled/3)
* [sle-15-SP7-JeOS-for-kvm-and-xen](http://kepler.suse.cz/tests/24720#step/firewall_enabled/1)
* …

Check firewalld state and presence in JeOS

---

tests/sles4sap/ensa/ensa_barriers.pm

Commit 5693fd7e70b8584c4447328f77c476122c790b38 which added a mutex to signal when barriers are ready to use, failed to also add the mutex to the test module `sles4sap/ensa/ensa_barriers` which is used in the ENSA2 scenario to create the barriers instead of the usual `ha/barrier_init`. This commit fixes the issue.
- Related PR: #21988
- Needles: N/A

Add ha_barriers_ready mutex creation also in ensa_barriers

---

data/autoyast_hanaperf/agama-config.jsonnet
tests/kernel_performance/install_qatestset.pm

1. Fix install_qatestset.pm disable service issue: stop service as well
2. Remove Wired*nmconnection in agama.json for bsc#1235024 workaround
- Related ticket: https://jira.suse.com/browse/TEAM-10293
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/17598238, https://openqa.suse.de/tests/17598241, http://openqa.qa2.suse.asia/tests/84710, http://openqa.qa2.suse.asia/tests/84711, http://openqa.qa2.suse.asia/tests/84769

Fix install_qatestset.pm disable service issue and nmconnection name changes 

---

tests/wicked/before_test.pm

https://progress.opensuse.org/issues/182003
[sle12](http://openqa.suse.de/tests/17622116#dependencies)
[sle15](http://openqa.suse.de/tests/17622133#dependencies)

Stop firewall before disabling it in wicked tests

---

tests/fips/openssl/openssl_fips_alglist.pm
tests/fips/openssl/openssl_pubkey_rsa.pm

See https://bugzilla.suse.com/show_bug.cgi?id=1242046
Algorithm List test is now passing: https://openqa.opensuse.org/tests/5032250#step/openssl_fips_alglist/53
Subsequent failures reported at https://bugzilla.suse.com/show_bug.cgi?id=1242046#c5
- **Add ED curves as permitted algorithm**
- **Add ML as permitted algorithm**
- [Update regex to match openssl 3.4+ rsa message](https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/21927/commits/66cc2950eddce9668a4110d2f4fd730b9a00892f)

Add new algorithms to the list in fips for openSSL 3.5

---

data/journal_check/bug_refs.json

Ignore the error message from pam_wtmpdb that causes a failed write
because of a race condition on system shutdown.
- Related ticket: https://bugzilla.suse.com/show_bug.cgi?id=1242592#c2

Add ignore for bsc#1242592

---

schedule/yam/agama.yaml
schedule/yam/agama_auto.yaml
test_data/yam/agama_sle.yaml

We added a way to validate repos set by Agama after installation.
- Related ticket: https://progress.opensuse.org/issues/180956
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/17503061

Add validation to check that installed repos are the ones expected and enabled

---

lib/bootloader_pvm.pm

As https://bugzilla.suse.com/show_bug.cgi?id=1241969#c36, we need add ip=dhcp in kernel parameter on powerVM.
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/17631747#step/boot_agama/26

Add ip=dhcp in kernel parameter on powerVM

---

data/lynis/baseline-lynis-audit-system-nocolors-15-SP6-ppc64le-textmode
tests/security/lynis/lynis_analyze_system_audit.pm
tests/security/lynis/lynis_create_baseline.pm
tests/security/lynis/lynis_harden_index.pm
tests/security/lynis/lynis_perform_system_audit.pm
tests/security/lynis/lynis_setup.pm

Auto importing GPG keys, since lynis is now located in a backports repo on PackageHub.
Generating a missing baseline file for 15-SP6 ppc64le which was causing wget failing in lynis_setup.
- Related ticket: https://progress.opensuse.org/issues/178786
- Verification run: https://openqa.suse.de/tests/17625810

Fix lynis_textmode test on 15-SP6 ppc64le

---

lib/sles4sap/sap_host_agent.pm
t/31_sap_host_agent.t
tests/sles4sap/redirection_tests/hana_sr_primary_failover.pm
tests/sles4sap/redirection_tests/hana_sr_replica_failover.pm

SDAF test modules currently collects data about DB SID and DB ID from an incorrect host agent command. Tests are passing only by coincidence. This PR fixes the issue.
- Verification run: https://openqaworker15.qa.suse.cz/tests/323622#live

Fix incorrect DB data collection

---

test_data/yast/skip_registration/default_repos.yaml

A new module of systems management is added to 15SP7, and it is seleceted in Full media installation, adapt the test data for checking the repo list for the added module.
- Related ticket: https://progress.opensuse.org/issues/181958
- Needles: n/a
- Verification run: https://openqa.suse.de/tests/17631999#step/validate_repos/21

Adapt test data for new module of systems management

---

data/lynis/baseline-lynis-audit-system-nocolors-15-SP6-s390x-gnome

Fixed lynis_setup step of the lynis tests on s390x.
- Related ticket: https://progress.opensuse.org/issues/182096
- Verification run: https://openqa.suse.de/tests/17632352

Add missing data file for s390x lynis test

---

data/publiccloud/terraform/gce.tf

List of instance types which requires TERMINATE start growing dramatically so I decided to invert logic
to keep only instance type which do not need

Invert logic to keep list of instance types which NOT need TERMINATE

---

lib/sles4sap.pm
tests/sles4sap/hana_install.pm
tests/sles4sap/hana_test.pm

On SLES for SAP 16, in order to install HANA, we need to add additional commands to configure SELinux so the HANA installation is successful without disabling SELinux. This commit adds the required commands to the `sles4sap/hana_install` test module.
- Related ticket: https://jira.suse.com/browse/TEAM-10343
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/17625440 :green_circle: , https://openqa.suse.de/tests/17625536 :green_circle: , https://openqa.suse.de/tests/17625674 :green_circle:

Add SELinux setup required by HANA

---

tests/ha/filesystem.pm

Get rid of `sleep` and provide a proper wait for cluster resources
- Related ticket: https://jira.suse.com/browse/TEAM-10344
- Needles: n/a
- https://openqa.suse.de/tests/17625510
- https://openqa.suse.de/tests/17625511
- https://openqa.suse.de/tests/17625512
- https://openqa.suse.de/tests/17625513
- https://openqa.suse.de/tests/17625503#step/filesystem/76
- https://openqa.suse.de/tests/17625504
- https://openqa.suse.de/tests/17625505
- https://openqa.suse.de/tests/17625506
- https://openqa.suse.de/tests/17625507#step/filesystem/76
- https://openqa.suse.de/tests/17625508
- https://openqa.suse.de/tests/17625509
x86_64 test now passes the filesystem step, which is the ticket acceptance criteria; subsequent failure will be triaged and addressed in a separate task.

Wait for start of filesystem resource

---

lib/publiccloud/basetest.pm

Avoid calling PC post_fail_hook for the SLES4SAP tests to fix PC mr_test test module ssh_interactive_end has ERROR when doing "terraform destroy":   
do not run  post_run_hook which includes tear down.
TEAM-10315 - [PC][mr_test] Test module ssh_interactive_end has ERROR when doing "terraform destroy"
- Related ticket: https://jira.suse.com/browse/TEAM-10315
- Verification run:   
15-SP6 Azure mr_test: https://openqa.suse.de/tests/17631778#step/ssh_interactive_end/15 :green_circle: 
15-SP7 Azure mr_test: https://openqa.suse.de/tests/17631668#step/ssh_interactive_end/15 :green_circle: 
15-SP7 EC2 mr_test: https://openqa.suse.de/tests/17631775#step/ssh_interactive_end/15 :green_circle: 
15-SP7 GCE mr_test: https://openqa.suse.de/tests/17631777#step/ssh_interactive_end/15 :green_circle: …

Avoid calling PC post_run_hook for SLES4SAP tests

---

tests/sles4sap/ensa/ensa_filesystems.pm

The serial terminal is too fast and the test moves on before the kernel syncs the updates the partition table. This intersperses the calls to parted with partprobe that will hopefully make the kernel sync them.
- Related Ticket: TEAM-10321
- Verification run: https://qesapworker-prg8.qa.suse.cz/group_overview/1 Failures are unrelated

Fix sporadic error in ensa_filesystems after moving test to serial

---

tests/publiccloud/run_ltp.pm

Make sure systemd-detect-virt fails on bare-metal
- Related ticket: https://progress.opensuse.org/issues/182153
- Verification run: https://openqa.suse.de/tests/17637532#step/run_ltp/42

pc: Make sure systemd-detect-virt fails on bare-metal

---

tests/containers/bats/podman.pm

Remove libcriu2 dependency as it should be pulled by criu on Tumbleweed.  We ignore the `520-checkpoint` test on SLES.
- Failing test: https://openqa.suse.de/tests/17635333#step/podman/61

bats/podman: Remove libcriu2 dependency

---

lib/containers/bats.pm

The newer ncat from Nmap 7.96 introduces some changes that may be breaking upstream netavark tests on TW & SLES:
https://nmap.org/changelog.html
This PR introduces `NCAT_VERSION` which defaults to the previous 7.95 version and installs it from upstream, since our repos got the newest version.
This may be reverted if the tests are patched and the patches can be applied in older versioned tags.
- Failing test: https://openqa.suse.de/tests/17641825
- Verification run: https://openqa.suse.de/tests/17647842

bats: Install specific ncat version from upstream

---

lib/sles4sap/qesap/qesap_aws.pm
lib/sles4sap/qesap/qesapdeployment.pm
t/09_qesapdeployment.t
t/16_qesap_aws.t
tests/sles4sap/publiccloud/network_peering.pm
tests/sles4sap/publiccloud/qesap_terraform.pm
tests/sles4sap/qesapdeployment/configure.pm
tests/sles4sap/qesapdeployment/destroy.pm
tests/sles4sap/qesapdeployment/test_mirror.pm

Move functions related to AWS from qesapdeploy,pm to a dedicated lib. Library is still named qesap as some of the operations are not AWS generic but related to how qe-sap-deployment terraform AWS project is designed.
Some functions have been made private and UT has been adapted accordingly to get the same coverage.
- Related ticket:  https://jira.suse.com/browse/TEAM-8439
- sle-15-SP6-Qesap-Aws-Byos-x86_64-BuildLATEST_AWS_SLE15_6_BYOS-qesap_aws_angi_test -> http://openqaworker15.qa.suse.cz/tests/323935 :green_circle: 
- sle-15-SP6-Qesap-Aws-Byos-x86_64-BuildLATEST_AWS_SLE15_6_BYOS-qesap_aws_ibsmirror_peering_test -> http://openqaworker15.qa.suse.cz/tests/323936 :green_circle: 
- sle-15-SP6-HanaSr-Aws-Payg-x86_64-Build15-SP6_2025-05-12T02:03:21Z-hanasr_aws_test_peering ec2_r4.8xlarge -> …

Move AWS related qesap functions

---

data/yam/agama/auto/scripts_ssh_pub_key.jsonnet
data/yam/agama/auto/sles_lvm_ssh_pub_key_ppc64le.jsonnet
data/yam/agama/auto/sles_root_filesystem_ext4_ppc64le.jsonnet
data/yam/agama/auto/sles_root_filesystem_ext4_ssh_pub_key_ppc64le.jsonnet
data/yam/agama/auto/sles_root_filesystem_xfs_ppc64le.jsonnet
data/yam/agama/auto/sles_root_filesystem_xfs_ssh_pub_key_ppc64le.jsonnet
data/yam/agama/auto/sles_sap_default_ppc64le.jsonnet
schedule/yam/agama.yaml
schedule/yam/agama_auto.yaml

We have added the option `stopOnBootMenu` on different profiles for ppc64le tests, this will avoid the error that GRUB goes to fast.
We included a minor change of validate_repos order in the schedule.
- Needles: N/A

Added GRUB stop and minor modifications

---

lib/main_containers.pm

The podmansh test should be on its own job and when it fails it prevents other modules from being tested.
- Failing test: https://openqa.opensuse.org/tests/5053726#step/podmansh/125
- Related ticket: https://progress.opensuse.org/issues/182213

containers: De-schedule podmansh test

---

tests/sles4sap/sapconf.pm

The `sles4sap/sapconf` test module checks the status of related services. These include `sapconf`, `systat` and `uuidd.socket`. Recently the description of `sapconf` has changed leading to the test failure. Since `sapconf` is nearing EOL, this commit drops the check for `sysstat`'s description, but keeps everything else intact.
- Related ticket: https://jira.suse.com/browse/TEAM-10357
- Needles: N/A
- Verification run: https://openqaworker15.qa.suse.cz/tests/324117 :green_circle:

Drop syststat service description check in sles4sap/sapconf

---

schedule/ha/bv/pvm_cluster.yaml

This is the schedule file for HA clusters test on ppc64le pvm on SLE16.
Since we are not using PowerKVM, there's no qcow2 image and the test schedule file is different from x86_64/aarch64/s390x.
There needs to be another MR on gitlab to use this yaml file.
- Related ticket: https://jira.suse.com/browse/TEAM-10228
node1: https://openqa.suse.de/tests/17658504
node2: https://openqa.suse.de/tests/17658505
(there are workarounds to skip problematic test steps in the VR)

add schedule file for HA clusters test on ppc64le pvm on SLE16

---

schedule/functional/extra_tests_textmode.yaml
schedule/functional/extra_tests_textmode_sle16.yaml
schedule/qam/15-SP2/qam-textmode.yaml
schedule/qam/15-SP3/qam-textmode.yaml
schedule/qam/15-SP4/qam-textmode.yaml
schedule/qam/15-SP5/qam-textmode.yaml
schedule/qam/15-SP6/qam-textmode.yaml
schedule/qam/15-SP7/qam-textmode.yaml

Add ntp_client test for sle15SPX and sle16
- Related ticket: https://progress.opensuse.org/issues/181625
- Verification run: sle16:
https://openqa.suse.de/tests/17631582
https://openqa.suse.de/tests/17631583
https://openqa.suse.de/tests/17631584
15sp7_daily:
https://openqa.suse.de/tests/17631690
https://openqa.suse.de/tests/17631692
https://openqa.suse.de/tests/17631693
https://openqa.suse.de/tests/17631694
15sp7:
https://openqa.suse.de/tests/17631587
15sp6:
https://openqa.suse.de/tests/17631588
15sp5:
https://openqa.suse.de/tests/17631591
15sp4:
https://openqa.suse.de/tests/17631592      
15sp3:
https://openqa.suse.de/tests/17631670
15sp2:
https://openqa.suse.de/tests/17631672

Add ntp_client test for sle15SPX and sle16

---

tests/installation/agama_reboot.pm

https://progress.opensuse.org/issues/182258
- [Verification run](https://openqa.suse.de/tests/17673413#step/agama_reboot/16)
Now it can show us that the installation is not done yet, and some packages are in the queue, then tester can try to increase the timeout for `AGAMA_INSTALL_TIMEOUT`

Add some debug info for agama install failure

---

tests/sles4sap/ensa/ensa_filesystems.pm

As described in commit 6be0607, the serial terminal is too fast and by the time it reaches mkfs.xfs, the partition table is not ready.
Because I could not find a way to force a sync, I added a script_retry that will cut down on the amount of failures.
- Related Ticket: TEAM-10321
- - OSD
https://openqa.suse.de/tests/overview?distri=sle&version=15-SP6&build=ensavr-1&groupid=615
https://openqa.suse.de/tests/overview?distri=sle&version=15-SP6&build=ensavr-2&groupid=615
https://openqa.suse.de/tests/overview?distri=sle&version=15-SP6&build=ensavr-3&groupid=615
https://openqa.suse.de/tests/overview?distri=sle&version=15-SP6&build=ensavr-4&groupid=615
https://openqa.suse.de/tests/overview?distri=sle&version=15-SP6&build=ensavr-5&groupid=615 …

Fix race condition in xfs fs creation in ensa2 test

---

tests/console/wget_ipv6.pm

Given the points in https://bugzilla.suse.com/show_bug.cgi?id=1240730, we should add `-6` in order to force ipv6 stack in wget.
- sle-15-SP7-JeOS-for-kvm-and-xen-s390x-Build3.22-jeos-extratest@s390x-kvm -> https://openqa.suse.de/tests/17673133
- sle-16.0-Minimal-VM-for-kvm-and-xen-s390x-Build23.1-minimalvm-extratest@s390x-kvm -> https://openqa.suse.de/tests/17673144

Force ipv6 in wget_ipv6 test

---

tests/publiccloud/run_ltp.pm

Fix metal detector on GCE.
`systemd-detect-virt` sometimes returns `"google"` on bare-metal devices.  This may be a bug in Google Cloud or it's Google Metal.
Failing test: https://openqa.suse.de/tests/17676242#step/run_ltp/43

pc: Fix metal detector on GCE

---

schedule/kernel/run_kselftests.yaml
tests/kernel/kselftests.pm
tests/kernel/run_kselftests.pm

As of now the kselftests tests are run using kirk: https://github.com/linux-test-project/kirk as well as selftests.pm module.
The LTP upstream project decided to drop kselftest support in kirk. For this reason there is a need to run kselftests using  "native" openqa runner. 
This PR is barely marking kselftests kirk runner deprecated to indicate this pm module will be removed soon.
New, simplistic kselftests runner is introduced.
The main idea for the new runner is to allow:
- running kselftests build from defined git repository, so that the most recent upstream kselftests could be used. This approach is good for instance for cgroup tests as discussed with MichalK.
- running using kselftests rpm prepared and build in IBS
Also initial patch is using native shell script to run kselftests: …

Kselftests: openqa runner

---

tests/kernel/update_kernel.pm

The livepatch refactoring missed one workaround that temporarily enables update repos. Use the correct helper method.
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/17688841 (expected to fail on missing `kernel-default-livepatch`)

update_kernel: Enable correct update repo for livepatch staging

---

tests/console/wget_ipv6.pm

Reverts os-autoinst/os-autoinst-distri-opensuse#22050
I need to check o3 again. Locally it worked maybe we need to make a worker config change

Revert "Force ipv6 in wget_ipv6 test"

---

data/containers/bats/skip.yaml

These tests have been passing for some time now:
- buildah (Tumbleweed):
- chroot: https://openqa.opensuse.org/tests/5060999#step/buildah/288
- namespaces: https://openqa.opensuse.org/tests/5060999#step/buildah/395
- podman (Tumbleweed):
- 080-pause: https://openqa.opensuse.org/tests/5061003#step/podman/294
- 130-kill: https://openqa.opensuse.org/tests/5061003#step/podman/364
- 200-pod: https://openqa.opensuse.org/tests/5061003#step/podman/434
- netavark (15-SP5):
- 200-bridge-firewalld: https://openqa.suse.de/tests/17694401#step/netavark/248
- netavark (15-SP6):
- 200-bridge-firewalld: https://openqa.suse.de/tests/17694730#step/netavark/215

bats: No need to skip some tests anymore

---

lib/sles4sap.pm
tests/sles4sap/hana_test.pm

The `test_pids_max` test from `lib/sles4sap.pm` does not work with SELinux configured to `Enforcing` mode. Commit
36fc991d6074c7a92b7a77409b28eaa4e3d3738e added code in the test module `sles4sap/hana_test` to temporarily set SELinux to `Permissive` mode before executing the test, and then reverting the change. However, `test_pids_max` is also called from other modules (for example, from `sles4sap/netweaver_test_instance`), so this commit moves the temporary SELinux changes to the `test_pids_max` method itself to avoid duplicating code in the test modules.
- Needles: N/A
- Verification run: [HANA](http://mango.qe.nue2.suse.org/tests/6725), [NW](http://mango.qe.nue2.suse.org/tests/6722)

Move SELinux set to permissive from hana_test to library

---

data/containers/bats/skip.yaml
tests/containers/bats/README.md

runc: Ignore checkpoint test as root.
https://openqa.opensuse.org/tests/5063792 failing due to https://bugzilla.suse.com/show_bug.cgi?id=1241515

bats/runc: Ignore checkpoint test as root

---

data/containers/bats/skip.yaml
lib/containers/bats.pm
lib/main_containers.pm

Drop aliasing of `aardvark` to `aardvark-dns` (the proper package name) in library code.  Perl doesn't like dashes in module names, so limit the aliasing hack to the scheduling code.
- Verification run: https://openqa.opensuse.org/tests/5063859 (`BATS_PACKAGE=aardvark-dns`)
- Related PR: https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/22098

Simplify scheduling for aardvark-dns

---

lib/publiccloud/gce.pm

Fix for https://openqa.suse.de/tests/17603722#step/prepare_instance/99
```
rror: Error creating instance: googleapi: Error 400: Invalid value for field 'resource.confidentialInstanceConfig': '{  "enableConfidentialCompute": true}'. Confidential Instance Config is only supported when using an SEV_LIVE_MIGRATABLE_V2 image., invalid
```
VRs : 
upload_img : https://openqa.suse.de/tests/17609060
confidential  VM : https://openqa.suse.de/tests/17609115

Adding extra flag to fix ability to create Confidential VMs

---

schedule/ha/bv/pvm_ha_crash_test_node.yaml
tests/ha/ha_cluster_crash_test.pm
tests/ha/setup_hosts_and_luns.pm

Enable 16.0 ppc64le Cluster Crash Test Scenario
Note:
1. `schedule/ha/bv/pvm_ha_crash_test_node.yaml` is based on `schedule/ha/bv/ha_crash_test_node.yaml` and added `gama installation` and `iscsi server` related test modules.
2. Set `fatal => 1` for test module `tests/ha/ha_cluster_crash_test.pm` as if this test module failed the `barrier_wait` will no be  executed then test module `check_logs` will hang until exceeds `MAX_JOB_TIME` .  
- Related MR: https://gitlab.suse.de/qa-css/openqa_ha_sap/-/merge_requests/1007
- Related ticket: https://jira.suse.com/browse/TEAM-10288 (TEAM-10288 - [ppc64le] Enable Cluster Crash Test Scenario)
https://openqa.suse.de/tests/17710696#step/ha_cluster_crash_test/115 (Still **failed** on reboot after `crm cluster crash_test --kill-sbd …

Enable 16.0 ppc64le Cluster Crash Test Scenario

---

tests/x11/chrome.pm

Ticket: https://progress.opensuse.org/issues/182555 and https://progress.opensuse.org/issues/182540
From: https://www.google.de/linuxrepositories/
> NOTE: From early 2023 onward, all Linux RPM packages are signed with periodically rotated subkeys of the 0xD38B4796 signing key. The 0x7FAC5991 signing key is obsoleted by this change. 
- Leap: https://openqa.opensuse.org/tests/5064503
- TW: https://openqa.opensuse.org/tests/5064502#step/chrome/10

Update Google GPG key in chrome

---

tests/x11/vnc_two_passwords.pm

Failure: https://openqa.opensuse.org/tests/5057494#step/vnc_two_passwords/56
VR: https://openqa.opensuse.org/tests/5059817
- **Send ctrl+c properly in a valid console**
- **Use parent class's post_fail_hook to collect logs**

Improve log collection fo vnc_two_passwords test

---

tests/fips/fips_setup.pm

Increase timeout for fips-mode-setup
- Failing test: https://openqa.suse.de/tests/17710544#step/fips_setup/7
- Verification run: https://openqa.suse.de/tests/17711418

fips: Increase timeout for fips-mode-setup

---

data/sles4sap/qe_sap_deployment/qesap_aws_peering.yaml
tests/sles4sap/qesapdeployment/configure.pm
tests/sles4sap/qesapdeployment/destroy.pm
tests/sles4sap/qesapdeployment/test_mirror.pm

Add conf.yaml for qesap regression test to do network peering to IBSm.
- Related ticket: https://jira.suse.com/browse/TEAM-9886
sle-15-SP6-Qesap-Aws-Byos-x86_64-BuildLATEST_AWS_SLE15_6_BYOS-qesap_aws_ibsmirror_peering_test
-  http://openqaworker15.qa.suse.cz/tests/324419 :red_circle: Failure is in `[sap-hana-download-media](https://openqaworker15.qa.suse.cz/tests/324419#step/sap-hana-download-media/1)` so not easy to find a relation to th ecode in the PR
-  http://openqaworker15.qa.suse.cz/tests/324510 :green_circle: overall deployment fails due to AWS disk issue, but peering is correctly created and destroyed by terraform https://openqaworker15.qa.suse.cz/tests/324510/logfile?filename=serial_terminal.txt#line-22985

Add qesap regression terraform peering for AWS

---

lib/sles4sap_publiccloud.pm

Fix regression introduced in https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/21993
- Related ticket: https://jira.suse.com/browse/TEAM-10370
sle-15-SP6-EC2-SAP-BYOS-Incidents-x86_64-Build SAPHanaSR-ScaleUp-PerfOpt-native-stop
-  http://openqaworker15.qa.suse.cz/tests/324509 :green_circle: https://openqaworker15.qa.suse.cz/tests/324509/logfile?filename=autoinst-log.txt&filter=qesap_aws_delete_transit_gateway_vpc_attachment#line-44738

Add missing include for qesap_aws

---

lib/containers/bats.pm

Make it possible to bypass BATS_PATCHES.  We can't set it to an empty string because we're fetching those from skip.yaml otherwise.
Make it an undocumented feature for now.  We may need it for podman 5.5 to skip the current set of patches.
Skipping VR being such an obvious change.

bats: Make it possible to bypass BATS_PATCHES

---

lib/containers/bats.pm

Drop PackageHub for SLE as we don't install libcriu2.

bats: No need for PackageHub

---

lib/Utils/Logging.pm
lib/consoletest.pm
lib/x11test.pm

VRs:
- X11 test failing https://openqa.opensuse.org/tests/5062171#step/vnc_two_passwords/166
- Tumbleweed console: https://openqa.opensuse.org/tests/5062354#step/snapper_zypp/92
- 15-sp5 console: https://openqa.suse.de/tests/17702102
- 12-sp5 No audit.log: https://openqa.suse.de/tests/17702180#step/arping/74
- 15-sp5 New AVC: https://openqa.suse.de/tests/17702182#step/openvswitch/120
- https://openqa.suse.de/tests/17702415
- https://openqa.opensuse.org/tests/5064686#step/snapper_zypp/96
Cherry-picked from https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/22070
- **Move avc_selinux_alerts to Utils::Logging**
- **Collect selinux alerts also on X11 post_fail_hook**
I'm also tempted also cherry pick this commit to upload auditd.log from …

Allow avc_selinux_alerts to be used in X11base or anywhere else

---

data/containers/bats/skip.yaml
lib/containers/bats.pm

PackageHub is still needed for fakeroot.  Also, we need to ignore `520-checkpoint` on SLES 15-SP6+ as it doesn't officialy support criu.

Minor BATS fixes

---

tests/console/aide_check.pm
tests/console/git.pm
tests/console/journald_fss.pm

Minor tweaks for console tests:
https://progress.opensuse.org/issues/178342
https://progress.opensuse.org/issues/168199
ppc64le: https://openqa.suse.de/tests/17712188
x86_64 ipmi-tyrion: https://openqa.suse.de/tests/17712711
Please ignore the ecryptfs failure on tyrion. That is unrelated to these changes.

Minor tweaks in console tests

---

data/containers/bats/skip.yaml

These tests are passing:
- 090-events:
- 16.0:
- https://openqa.suse.de/tests/17726011#step/podman/526
- 520-checkpoint:
- 15-SP5:
- https://openqa.suse.de/tests/17728953#step/podman/412
- https://openqa.suse.de/tests/17728953#step/podman/476
- 15-SP6:
- https://openqa.suse.de/tests/17730373#step/podman/412
- https://openqa.suse.de/tests/17730373#step/podman/476
Confirmed with:
```
$ susebats notok https://openqa.suse.de/tests/17726011
BATS_SKIP: 125-import
BATS_SKIP_ROOT_LOCAL: 520-checkpoint
BATS_SKIP_ROOT_REMOTE: 520-checkpoint
BATS_SKIP_USER_LOCAL: 080-pause 505-networking-pasta
BATS_SKIP_USER_REMOTE: 505-networking-pasta
$ susebats notok https://openqa.suse.de/tests/17728953
BATS_SKIP: ''
BATS_SKIP_ROOT_LOCAL: ''
BATS_SKIP_ROOT_REMOTE: ''
BATS_SKIP_USER_LOCAL: 080-pause …
```

bats: No need ignore some more tests

---

tests/microos/networking.pm

Avoid putting additional load on O3 for OSD test runs. Also avoid that OSD test runs would fail, if O3 is down.
- Related failure: https://openqa.suse.de/tests/17729695#step/networking/16
- Verification run: https://openqa.suse.de/tests/17732175

Use OSD on non-openSUSE tests

---

tests/publiccloud/nvidia.pm
variables.md

The Public Cloud NVIDIA test is too simple, add a proper call to a utility which tests the driver itself.
- Related ticket: https://progress.opensuse.org/issues/177282
- Verification run: https://rmarliere-openqa.qe.prg2.suse.org/tests/1212

publiccloud: nvidia: Do minimal driver testing with nvidia-smi

---

data/containers/bats/skip.yaml
tests/containers/bats/README.md

- Fix skip.yaml link
- Add missing comment
- Enhance it a bit
VR: 
https://github.com/ricardobranco777/os-autoinst-distri-opensuse/blob/bats_docu/tests/containers/bats/README.md

Enhance BATS documentation

---

data/sles4sap/angi_hana_cluster.conf
data/sles4sap/hana_cluster_cln.conf
data/sles4sap/hana_cluster_msl.conf
schedule/sles4sap/hana/pvm_hana_cluster_node_sle16.yaml
tests/ha/fencing.pm
tests/sles4sap/hana_cluster.pm

1. For sle16, the netcard name is changed, so we should not hard code it in configuration file.
2. For SAPHanaSR-angi test, we need to reboot the host, so need to let the selinux=permissive take effect after rebooting
Related: https://jira.suse.com/browse/TEAM-10280
VR:
sle 16
x86: https://openqa.suse.de/tests/17712093#  (Failed on check_after_reboot)
ppc64: https://openqa.suse.de/tests/17712090# (Failed on check_after_reboot)
Because there is some modification on configuration file, so run VR on 15-sp7
15sp7:
SAPHanaSR_ScaleUp_PerfOpt_WMP_node01 x86: https://openqa.suse.de/tests/17710747# (passed)
SAPHanaSR_angi_ScaleUp_PerfOpt_node01: ppc64https://openqa.suse.de/tests/17710704# (Passed)

Add SAPHanaSR-angi test for sle16

---

tests/microos/workloads/x11-container/x11_client.pm
tests/microos/workloads/x11-container/x11_server.pm

Update x11, pulseaudio and firefox kiosk container URLs
- Related ticket: https://progress.opensuse.org/issues/174418
- Needles: already added when debugging on osd
> x11 container https://openqa.suse.de/tests/17686643#step/x11_server/90
> pulseaudio container: https://openqa.suse.de/tests/17686642#step/x11_client/28 
> firefox kiosk container: https://openqa.suse.de/tests/17686642#step/x11_client/30

Update x11 related containers URLs

---

data/sles4sap/sap_deployment_automation_framework/custom_sizes.json

This PR adjusts disk sizing used for all SDAF based deployments according official SAP sizing recommendations and our requirements.
VM: Standard_E4d_v4
Memory: 32G
Data (1,2 x mem): 36G (3x16G lun)
Log (0,5 x meme): 16G
Shared (min 1x memory): 64G
OS: 64G
/usr/sap/ : 16G (usually enough)
Ticket: https://jira.suse.com/browse/TEAM-10259
Verification run: https://openqaworker15.qa.suse.cz/tests/324520

Adjust sizing for SDAF

---

tests/kernel/update_kernel.pm

Check that the correct kernel for livepatching is installed before rebooting to install the livepatch itself.
- Needles: N/A
-  https://openqa.suse.de/tests/17751854 (expected to fail on `kernel-rt_debug`)
- https://openqa.suse.de/tests/17751861 (expected to pass)

update_kernel: Check kernel package before installing livepatch

---

lib/containers/k8s.pm
lib/main_containers.pm
tests/containers/charts/privateregistry.pm
variables.md

Adds a new test for SUSE Private Registry. The test does the following:
1. Sets up the environment (K3s, Helm, Podman).
2. Installs Traefik Ingress Controller.
3. Deploys the PrivateRegistry and waits until all components are in the Ready state.
4. Tests pushing images and charts to the registry.
5. Tests pulling images and charts from the registry.
- Related ticket: https://progress.opensuse.org/issues/181238
- Needles: N/A
- https://openqa.suse.de/tests/17750021

adds test for PrivateRegistry helm chart

---

tests/console/git.pm

Do not cleanup ~/.ssh at the end of the git test.
Fix poo#168199
Related ticket: https://progress.opensuse.org/issues/168199
- 15-SP7 x86_64: https://openqa.suse.de/tests/17767748

Adjust the cleanup part of the git test

---

data/containers/bats/skip.yaml

podman in SLE 16.0 was upgraded to v5.4.2 (the same version used in Tumbleweed):
https://openqa.suse.de/tests/17760276#step/podman/149
Because of this, the patches listed in `BATS_PATCHES` fail to apply and we need to update this list to match Tumbleweed's.   
VR: https://openqa.suse.de/tests/17767770
```
$ susebats notok https://openqa.suse.de/tests/17767770
BATS_SKIP: ''
BATS_SKIP_ROOT_LOCAL: 200-pod 520-checkpoint
BATS_SKIP_ROOT_REMOTE: 520-checkpoint
BATS_SKIP_USER_LOCAL: 080-pause 505-networking-pasta
BATS_SKIP_USER_REMOTE: 505-networking-pasta
```

bats: Update BATS_PATCHES for 16.0

---

data/containers/bats/skip.yaml

Fix BATS_SKIP for SLE 16.0
```
$ susebats notok https://openqa.suse.de/tests/17770078
BATS_SKIP: ''
BATS_SKIP_ROOT_LOCAL: 520-checkpoint
BATS_SKIP_ROOT_REMOTE: 520-checkpoint
BATS_SKIP_USER_LOCAL: 080-pause 505-networking-pasta
BATS_SKIP_USER_REMOTE: 130-kill 505-networking-pasta
```

Fix BATS_SKIP for SLE 16.0

---

tests/containers/isolation.pm

Skip IPv6 in isolation test on s390x
Failing tests:
- docker: https://openqa.suse.de/tests/17760514#step/docker_isolation/103
- podman: https://openqa.suse.de/tests/17760517#step/podman_isolation/69

containers: Skip IPv6 in isolation test on s390x

---

data/journal_check/bug_refs.json

In aarch64 there is a new journal entry regarding ACPI
- sle-15-SP6-JeOS-for-kvm-and-xen-QR-aarch64-Build13.3-jeos-kdump@aarch64 -> https://openqa.suse.de/tests/17784408#step/journal_check/9

Ignore PPTT table found, but unable to locate core

---

data/containers/bats/patches/netavark/1191.patch
data/containers/bats/patches/podman/21875.patch
data/containers/bats/patches/podman/25792.patch
data/containers/bats/patches/podman/25918.patch
data/containers/bats/patches/podman/25942.patch
data/containers/bats/patches/podman/26017.patch
data/containers/bats/skip.yaml
lib/containers/bats.pm
tests/containers/bats/README.md

Incorporate upstream patches into osado.  This helps us avoid issues with secondary-rate limits in github.  We'll only use osado when the patch ID is numeric.
- Verification run: https://openqa.suse.de/tests/17790665

bats: Incorporate upstream patches into osado

---

lib/nvidia_utils.pm
tests/publiccloud/nvidia.pm
variables.md

A new test will be added for NVIDIA (baremetal). So in preparation for that, move the current subroutines into a new library.
- Related ticket: https://progress.opensuse.org/issues/182873
- Verification run: https://rmarliere-openqa.qe.prg2.suse.org/tests/1238

NVIDIA: Move reusable code from Public Cloud into a new library

---

lib/containers/helm.pm
tests/containers/charts/privateregistry.pm
tests/containers/charts/rmt.pm
variables.md

We now have 2 Helm chart tests. They share a lot of basic functionality, so before it grows into a huge mess, it makes sense to split the basic functionality into a simple library.
This library holds the functions to:
- check if the current OS is an OS we are testing helm on
- get a helm chart from a URL
- configure a helm chart based on a values file from a URL
- install a helm chart with the configuration options from the previous step
In actual tests, we only really need the check for the os and the install helm chart functions.
- RMT Helm chart: https://openqa.suse.de/tests/17790666
- PrivateRegistry: https://openqa.suse.de/tests/17790769

Split Helm functons into a utils library

---

tests/virt_autotest/kubevirt_tests_server.pm

Refer to https://openqa.suse.de/tests/17711075/file/junit-noframes.html. Generated xml result files from sle15sp7 include additional string 'KubeVirt' in testsuite and testcase name, and it's needed to be removed from xml result files before generate html reports.
- Related ticket: https://progress.opensuse.org/issues/182693
- Verification run: https://openqa.suse.de/tests/17732296/file/junit-noframes.html

Fix the testsuite and testcase name in xml results

---

lib/sles4sap.pm
tests/sles4sap/bone_install.pm
tests/sles4sap/wizard_hana_install.pm

This workaround enables B1 instalation on unsupported sles version by changing the VERSION_ID to one which is homologated by SAP. Requires previous manual testing to ensure compatibility.
In order to enable the workaround, add B1_WORKAROUND=<supported_sle> (ex. 15.6) n jobgroup.
Fixes: TEAM-10276
VR:
15-SP7:
http://10.100.103.247/tests/1158
http://10.100.103.247/tests/1152
15-SP6:
http://10.100.103.247/tests/1184
http://10.100.103.247/tests/1185

Add workaround to install B1 on unsupported sles

---

lib/eal4_test.pm
tests/security/eal4/dbus_fuzzer.pm
tests/security/eal4/dbus_services_exposure.pm

- Update copyright notices from 2022/2022-2024 to 2025
- Fix typo: 'unknow' -> 'unknown' in dbus_fuzzer.pm exit code handling
Ticket: https://progress.opensuse.org/issues/182588

Update copyright year and fix typo in EAL4 security tests

---

tests/jeos/firstrun.pm

The image registration has to be moved before FDE actions.
- needles: https://gitlab.suse.de/openqa/os-autoinst-needles-sles/-/merge_requests/1687
- Verification run: http://kepler.suse.cz/tests/24807#step/firstrun/15

FDE settings appear after registration notice 

---

tests/kernel/update_kernel.pm

- Related ticket: https://progress.opensuse.org/issues/183071
- Verification run: https://openqa.suse.de/tests/17838925 (not kernel update, but kernel is correctly switched to coco)

update_kernel: Add support for kernel-coco flavor

---

data/yam/autoyast/sles15sp3+_create_hdd_gnome_unregistered_no_self_update.xml.ep

We detected that the current mirror for SP7 is missing so we changed to another available repository.
We should invest some time to improve the AutoYast template and probably adapt to use offline media instead or mirror repository but for now we need to make it work.
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/17854870

Changed SLE DVD1 mirror URL on AutoYast template

---

data/yam/agama/auto/autoyast_supported.xml

We have added the plain script to wipe the disk, the main problem is to retrieve the output of the script.
Currently, Agama can't fetch pre-scripts output. We could include the output to a temporal file to check after the test.
- Related ticket: https://progress.opensuse.org/issues/181355
- Needles: N/A
- With this branch:
- 1: https://openqa.suse.de/tests/17634237
- 2: https://openqa.suse.de/tests/17634238
- 3: https://openqa.suse.de/tests/17634239
- 4: https://openqa.suse.de/tests/17634240
- 5: https://openqa.suse.de/tests/17634241
- 6: https://openqa.suse.de/tests/17634242
- 7: https://openqa.suse.de/tests/17634243
- 8: https://openqa.suse.de/tests/17634244
- 9: https://openqa.suse.de/tests/17634245
- 10: https://openqa.suse.de/tests/17634246
- 11: …

Wipe existed disks on  powerVM for Autoyast scenarios in Agama

---

data/autoyast_qam/15_installation.xml.ep

Installer sometimes chooses the wrong installation disk on hardware with
unconfigured RAID controllers. There is already an existing
INSTALL_DISK_WWN variable for this purpose, and we need to add it to
the SLE 15 autoyast maintenance profile.
Bare metal servers can have issues correctly displaying the GRUB menu over
IPMI console. We need to set the terminal to 'console' in order to disable
GRUB graphics.
Broken GRUB menu: https://openqa.suse.de/tests/17861253#step/installation/8
- Related ticket: https://progress.opensuse.org/issues/183023
Problematic Nvidia worker: https://openqa.suse.de/tests/17866584#step/handle_reboot/2

Increase bare metal compatibility of SLE 15 maintenance autoyast profile

---

lib/klp.pm

SL-Micro 6.1 is also missing kernel-rt-livepatch-6.4.0-10.1. Apply the same workaround as for SL-Micro 6.0.
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/17874171

install_klp_product: Extend kernel-rt livepatch workaround

---

tests/security/selinux/selinux_setup.pm

Cleanout previos logs before doing the tests.
- Related ticket: https://progress.opensuse.org/issues/181403
- https://openqa.suse.de/tests/17881202

Clean auditlog in SLE16 on s390x

---

data/containers/bats/skip.yaml

130-kill is now passing: https://openqa.opensuse.org/tests/5078602#step/podman/376
200-pod is giving us trouble.

bats/podman: Update SKIP for podman 5.5.0

---

lib/nvidia_utils.pm

When removing a package that isn't installed, zypper will return exit code 104. Accept that as success.
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/17906867

nvidia_utils: Uninstall nvidia packages safely

---

tests/sles4sap/ensa/ensa_filesystems.pm

After a discussion in research, it was suggested that `udev settle` would work unlike `partprobe` that we have been using until now. Apart from that I put the mount behind another retry.
- Related Ticket: TEAM-10390
- Verification run: https://qesapworker-prg8.qa.suse.cz/group_overview/1?limit_builds=20

Add udevadm settle to wait for partition changes

---

tests/jeos/firstrun.pm

Fix SLEM 6.2 test.
- Failing test: https://openqa.suse.de/tests/17883366#step/firstrun/19
- Related ticket: https://jira.suse.com/browse/SMO-570
- Verification run: https://openqa.suse.de/tests/17909403

slem: Avoid re-encrypt-finished on SLEM 6.2+

---

tests/installation/zdup.pm

In the rare ocassions that there's a conflict during an upgrade, we have
to know which option to choose for a given conflict and avoid failing
the test in case we have an uknown conflict
Failure: https://openqa.opensuse.org/tests/5079365#step/zdup/11
VR: 
- with conflict https://openqa.opensuse.org/tests/5082020#step/zdup/457
- without conflict https://openqa.opensuse.org/tests/5082022#step/zdup/213

Handle conflicts in zdup

---

tests/installation/bootloader_zkvm.pm

No network issue after SLE16 installation on s390x kvm.
Failed job: https://openqa.suse.de/tests/17886668#step/validate_base_product/2
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/17916377#details

Add parameters to fix s390x kvm network issue

---

tests/console/system_prepare.pm
tests/ha/ha_cluster_crash_test.pm
tests/ha/ha_cluster_init.pm

Fix 16 ppc64le ha_cluster_crash_test timed out failure.
-  Set `GRUB_TIMEOUT=30` for needles match when doing reboot (default `8s` is too short and will introduce sporadic needles mismatch failure)
- Added `save_screenshot` for `enter_cmd split-brain-iptables ...`
- Added `zypper_call "in iptables" if is_sle('>=16');`
- Added `reconnect_mgmt_console` for pvm
- Added retry for nodes check as there are sporadic issues like https://openqa.suse.de/tests/17896658#step/ha_cluster_init/41
TEAM-10374 - [16][ppc64le] after resolving TEAM-10288, ha_cluster_crash_test_x failed on ha_cluster_crash_test
- Related ticket: https://jira.suse.com/browse/TEAM-10374
https://openqa.suse.de/tests/17898083  (passed)
https://openqa.suse.de/tests/17898099#step/ha_cluster_crash_test/156 …

Fix 16 ppc64le ha_cluster_crash_test timed out

---

schedule/qam/common/mau-extratests1.yaml

Reverts os-autoinst/os-autoinst-distri-opensuse#22120
Fixed https://bugzilla.suse.com/show_bug.cgi?id=1243259

Revert "Exclude journal_remote on 15-SP7 until it's added"

---

lib/main_containers.pm
tests/containers/buildx.pm

Extend docker-buildx test to SLE 16.0
- Related ticket: https://bugzilla.suse.com/show_bug.cgi?id=1239683
- docker: https://openqa.suse.de/tests/17917272
- docker-stable: https://openqa.suse.de/tests/17917277

containers: Extend docker-buildx test to SLE 16.0

---

tests/console/system_prepare.pm

Fix sle16 system_prepare issue on aarch64 ha_cluster_crash_test_node cases introduced by PR#22201
https://openqa.suse.de/tests/17917305#step/system_prepare/24 (`system_prepare` test module passed)

Fix sle16 system_prepare er introduced by PR#22201

---

schedule/ha/bv/pvm_ha_priority_fencing.yaml

this pr is to enable priority fencing test scenario on ppc64le, but the schedule yaml file is based on schedule/ha/bv/ha_priority_fencing.yaml, and add the supports `agama installation`, `HA extension check` and `iscsi setup`
- Related MR: https://gitlab.suse.de/qa-css/openqa_ha_sap/-/merge_requests/1020
- Related ticket: https://jira.suse.com/browse/TEAM-10287
https://openqa.suse.de/tests/17916120 (node1)
https://openqa.suse.de/tests/17916121 (node2)

Enable Priority Fencing Test Scenario On ppc64le

---

lib/main_containers.pm

Enable docker-buildx test in SLEM 6.x
- Related ticket: https://bugzilla.suse.com/show_bug.cgi?id=1239683
- docker SLEM 6.0: https://openqa.suse.de/tests/17917692

containers: Enable docker-buildx test in SLEM 6.x

---

lib/main_containers.pm

This PR:
- Re-enables docker-compose tests on arches other than x86_64 & aarch64 since https://github.com/containers/podman/issues/21757 is closed.
- Extend the Tumbleweed test to SLE 16.0 & SLEM 6.x
Verification runs (docker):
- Tumbleweed ppc64le: https://openqa.opensuse.org/tests/5085517
- SLEM 6.0 s390x: https://openqa.suse.de/tests/17922271
- SLE 16.0 s390x: https://openqa.suse.de/tests/17922272
- SLE 16.0 s390x (podman): https://openqa.suse.de/tests/17922279

Enable docker-compose tests on SLE 16.0, SLEM 6.x, and arches other than x86_64 & aarch64

---

lib/containers/bats.pm
tests/containers/bats/podman.pm

Add back libcriu2 dependency to solve an issue with `520-checkpoint` test when `OCI_RUNTIME=crun`:
> could not load `libcriu.so.2`
https://openqa.opensuse.org/tests/5085670/file/podman-bats-root-local.tap
- Verification run: https://openqa.opensuse.org/tests/5085708

bats/podman: Add back libcriu2 dependency

---

tests/security/ebpf/check_cap_bpf.pm

- Related ticket: https://progress.opensuse.org/issues/183464
x86_64:
- https://openqa.suse.de/tests/17924661
- https://openqa.suse.de/tests/17924662
- https://openqa.suse.de/tests/17924663
- https://openqa.suse.de/tests/17924664
aarch64:
- https://openqa.suse.de/tests/17924665
- https://openqa.suse.de/tests/17924666
s390x:
- https://openqa.suse.de/tests/17924667
- https://openqa.suse.de/tests/17924668

Compile test executable in non-ephemeral filesystem

---

data/elemental3/config.sh
tests/elemental3/generate_image.pm
tests/elemental3/test_image.pm

Elemental3 (Unified Core) packages RKE2 as part of the OS image with `systemd-sysext`. This PR adds a basic test to validate that RKE2 is up and running.
- Needles: N/A
- [generate_image](https://openqa.suse.de/tests/17933856) :white_check_mark:
- [test_image](https://openqa.suse.de/tests/17934242) :white_check_mark:

elemental3: add system extensions and RKE2 test

---

lib/main_containers.pm
tests/containers/registry.pm

Limit the registry test to the products where the `distribution-registry` package is officially distributed and drop the dependency on PackageHub, which fails now for 15-SP3 and may introduce subtle bugs in the rest of the test modules.
```
$ susepkg -p any distribution-registry 
SLES/15.4 distribution-registry 2.8.3-150400.9.24.1
SLES/15.5 distribution-registry 2.8.3-150400.9.24.1
SLES/15.6 distribution-registry 2.8.3-150400.9.24.1
SLES/15.7 distribution-registry 2.8.3-150400.9.24.1
openSUSE_Leap/15.6 distribution-registry 2.8.3-150400.9.24.1
openSUSE_Tumbleweed distribution-registry 2.8.3-2.2
```
- Failing test: https://openqa.suse.de/tests/17931222#step/registry/14
- SLE 15-SP3 GCE: https://openqa.suse.de/tests/17935400

containers: Test registry package only on supported products

---

lib/sles4sap/azure_cli.pm
lib/sles4sap/ipaddr2.pm
t/21_sles4sap_azure_cli.t
t/22_ipaddr2.t

Double the timeout for VM boot from 300 to 600 in ipaddr2 tests. This is an attempt to mitigate test side issues happening recently on various images. The PR also add a `record_info` to print the boot time.
Related ticket: https://jira.suse.com/browse/TEAM-10404
sle-15-SP5-SapCloud-Azure-Payg-x86_64-BuildLATEST_AZURE_SLE15_5_PAYG-ipaddr2_azure_test_cloud_init
- http://openqaworker15.qa.suse.cz/tests/328246 :green_heart: 
- http://openqaworker15.qa.suse.cz/tests/328247 :red_circle: it does not reach the Running state in time http://openqaworker15.qa.suse.cz/tests/328247/logfile?filename=serial_terminal.txt#line-1354
sle-15-SP4-SapCloud-Azure-Payg-x86_64-BuildLATEST_AZURE_SLE15_4_PAYG-ipaddr2_azure_test_rootless
- http://openqaworker15.qa.suse.cz/tests/328248 :yellow_circle: VM1 takes 32sec …

Wait longer for az_vm_wait_running in ipaddr2

---

test_data/yam/agama_rmt.yaml

##
- Related ticket: https://progress.opensuse.org/issues/182996
- Related info: [**repo list**](https://openqa.suse.de/tests/17921840#step/validate_repos/12)
- Needles: N/A
- Verification run: [**VR**](https://openqa.suse.de/tests/overview?distri=sle&version=agama-10.0&build=hjluo%2Fos-autoinst-distri-opensuse%23rmt_test_data)
>[!TIP]
> VR PASSED for dev 7.12.
##

Adapt rmt validate_repos test data

---

lib/kdump_utils.pm

Adds basic use of `kdumptool commandline` to test kdump setup on SLE 16.
- Related ticket: https://progress.opensuse.org/issues/173998
SLE 16: https://openqa.suse.de/tests/17951300
SLE15: https://openqa.suse.de/tests/17951330
Micro: https://openqa.suse.de/tests/17951370
TW:  https://openqa.opensuse.org/tests/5089915 - failed at expected place due to boo#1240620
SLE 15 maintenance ncurses:  https://openqa.suse.de/tests/17951364

kdump_utils: Initial support for SLE 16

---

lib/grub_utils.pm
lib/opensusebasetest.pm
lib/version_utils.pm
t/01_version_utils.t
tests/installation/bootloader_uefi.pm
tests/installation/configure_bls.pm
tests/installation/disable_grub_timeout.pm

This is a follow up to #22187
Currently changes in the default behavior are to be confined to Staging:F.
I was tempted to replace `grub_test` with `wait_boot` but lets start small and see where we land first; systemd-bootloader is already supported in wait_grub
- non-staging grub-bls on jeos https://openqa.opensuse.org/tests/5089995
- non-staging microos+sdboot https://openqa.opensuse.org/tests/5089996
- minimalx with UEFI https://openqa.opensuse.org/tests/5089997
- textmode installation: https://openqa.opensuse.org/tests/5089998
- microos installation https://openqa.opensuse.org/tests/5089999
Needle changes: 
- https://github.com/os-autoinst/os-autoinst-needles-opensuse/pull/841
See also: 
MicroOS: https://build.opensuse.org/requests/1273704
Tumbleweed: …

Switch default bootloader for TW and Microos (in staging F)

---

data/network_bonding/kea-dhcp4.conf
tests/network/kea_server.pm

Removed the soft-fail for bsc#1243797 and changed the log path in the config file.
- Related:
- progress ticket: https://progress.opensuse.org/issues/182975
- bug ticket: https://bugzilla.suse.com/show_bug.cgi?id=1243797
- sle: https://openqa.suse.de/tests/overview?build=cedvid%2Fos-autoinst-distri-opensuse%2322244
- TW: https://openqa.opensuse.org/tests/5087966

kea: Change kea log path

---

lib/serial_terminal.pm
schedule/functional/sle16/extra_tests_textmode.yaml
schedule/functional/sle16/extra_tests_textmode2.yaml
tests/console/btrfs_balance.pm
tests/console/libgit2.pm
tests/console/wpa_supplicant.pm
tests/console/zypper_lifecycle.pm
tests/network/cifs.pm
tests/systemd_testsuite/prepare_systemd_and_testsuite.pm

Add more tests which are running on sle15sp7 but not on sle16 yet
- Related ticket: https://progress.opensuse.org/issues/181166
- Verification run: https://openqa.suse.de/tests/overview?distri=sle&version=16.0&build=89.2&groupid=220
Failed jobs have known bugs.
- Related MR: https://gitlab.suse.de/qe-core/qa-sle-functional-userspace/-/merge_requests/273
- Verified on s390x zypper_lifecycle: https://openqa.suse.de/tests/17948060#step/zypper_lifecycle/61

Add more tests which are running on sle15sp7 but not on sle16 yet

---

lib/utils.pm

Grub2-bls and systemd-boot have a ESP that is fat32 unencrypted besides systemd-boot doesn't support any kind of encryption
Follows #22239
Failure: https://openqa.opensuse.org/tests/5090451#step/grub_test/2
VR: https://openqa.opensuse.org/tests/5090896

Bootloader partitions for grub2-bls and systemd-boot can't be encrypted

---

lib/bootloader_setup.pm
lib/version_utils.pm
t/01_version_utils.t

Follows: #22277 
- **Handle upgrade scenarios**
- **Handle grub2-bls in boot_to_snapshot scenario**
VR:
- Microos container host https://openqa.opensuse.org/tests/5091168#live
for future me:
`openqa-clone-custom-git-refspec https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/22278 https://openqa.opensuse.org/tests/5090907 ISO="openSUSE-Staging:F-Tumbleweed-DVD-x86_64-Build924.1-Media.iso"`

More grub2-bls/sdboot changes

---

lib/sles4sap_publiccloud.pm
t/12_sles4sap_publiccloud.t
tests/sles4sap/publiccloud/hana_sr_schedule_deployment.pm
tests/sles4sap/publiccloud/qesap_terraform.pm

Add code in HanaSR to add maintenance repos by IBSm.yaml playbook from qe-sap-deployment.
- Related ticket: https://jira.suse.com/browse/TEAM-9887
sle-15-SP6-HanaSr-Azure-Byos-x86_64-Build15-SP6_2025-06-05T02:03:19Z-hanasr_azure_test_peering az_Standard_E4s_v3
- http://openqaworker15.qa.suse.cz/tests/328270 :green_circle:  the ibsm.yaml playbook is not executed. It is expected as the variables about the REPOS are missing.
sle-15-SP6-HanaSr-Azure-Byos-x86_64-Build15-SP6_2025-06-05T02:03:19Z-hanasr_azure_test_peering az_Standard_E4s_v3
- http://openqaworker15.qa.suse.cz/tests/328275 :green_circle: the IBSm playbook is properly added to the generated  [conf.yaml](https://openqaworker15.qa.suse.cz/tests/328275/file/deploy_qesap_terraform-sles4sap_azure_generic.yaml). The playbook is correctly …

Add code to run IBSM playbook

---

lib/containers/bats.pm

Increase timeout for BATS tests.
Failing test: https://openqa.suse.de/tests/17986615#step/podman/450

bats: Increase timeout

---

lib/containers/bats.pm

For some stupid reason there's a stupid timeout for a stupid mkdir:
https://openqa.suse.de/tests/17989702/logfile?filename=serial_terminal.txt#line-1455

bats: mkdir should not fail

---

schedule/security/cc_eal4.yaml
tests/security/eal4/accessible_network_interface.pm
tests/security/eal4/check_processor_vulnerability_mitigations.pm
tests/security/eal4/check_undocumented_security_programs.pm
tests/security/eal4/chrony_pid_file.pm
tests/security/eal4/dbus_fuzzer.pm
tests/security/eal4/dbus_services_exposure.pm
tests/security/eal4/drng_test_preparation.pm
tests/security/eal4/kvm_check.pm
tests/security/eal4/netlink_message.pm
tests/security/eal4/permission_settings.pm
tests/security/eal4/setup_eal4_env.pm
tests/security/eal4/syscall_thrasher.pm

With this change, the testsuite runs 2x faster on most platform
- Related ticket: https://progress.opensuse.org/issues/183134
- Needles: no
- https://openqa.suse.de/tests/17974011
- https://openqa.suse.de/tests/17974012
- https://openqa.suse.de/tests/17974013
- https://openqa.suse.de/tests/17974014
- https://openqa.suse.de/tests/17974660
- https://openqa.suse.de/tests/17974156
- https://openqa.suse.de/tests/17974158
- https://openqa.suse.de/tests/17974159
- https://openqa.suse.de/tests/17974160
- https://openqa.suse.de/tests/17974161
- https://openqa.suse.de/tests/17974162
- https://openqa.suse.de/tests/17974163
- https://openqa.suse.de/tests/17974164
- https://openqa.suse.de/tests/17974165
- https://openqa.suse.de/tests/17974166
- …

Use serial terminal instead of root console in eal4

---

tests/jeos/firstrun.pm
tests/microos/image_checks.pm

The gpt table has replaced dos in Default/Base flavors as we have a
dedicated RPi image.
The new .*64kb images have more sectors left unpartitioned as expected
by the tests
- failures: https://openqa.suse.de/tests/17972425#step/firstrun/83 and
https://openqa.suse.de/tests/17994364#step/image_checks/10
* [64kb](https://openqa.suse.de/tests/17999868#step/image_checks/10)
* [sle-micro-6.2-Base-qcow-aarch64-Build12.6-default@aarch64](https://openqa.suse.de/tests/18002153#step/image_checks/10)
* [sle-micro-6.1-Base-qcow-Updates-aarch64-Build63.1-slem_image_default@aarch64](https://openqa.suse.de/tests/18002138](https://openqa.suse.de/tests/18002138#step/image_checks/10))
* [sle-micro-5.5-Default-Updates-aarch64-Build20250608-1-slem_image_default@aarch64](https://openqa.suse.de/tests/18002114#st …

sle-micro 6.2 aarch64 tiny fixes

---

data/containers/bats/skip.yaml

Ignore sbom test as root as we do as user.
This [test](https://github.com/containers/buildah/blob/main/tests/sbom.bats) runs the syft and trivy Docker images on the Docker Alpine image to generate a SBOM (Software Bill Of Materials) and scan for security vulnerabilities.  This may be a test issue or bug on either of these.  It makes no sense to waste time on this one.
```
$ susebats notok https://openqa.suse.de/tests/18011237
BATS_SKIP: bud namespaces run sbom
BATS_SKIP_ROOT: 
BATS_SKIP_USER: add basic commit copy overlay rmi squash
$ susebats notok https://openqa.suse.de/tests/18011235
BATS_SKIP: bud namespaces run sbom
BATS_SKIP_ROOT: 
BATS_SKIP_USER: add basic commit copy overlay rmi squash
$ susebats notok https://openqa.suse.de/tests/18011238
BATS_SKIP: bud namespaces run sbom …
```

bats/buildah: Ignore sbom test as root

---

tests/installation/bootloader_s390.pm

We need to merge this short code to short URL from root:live line.
- Related ticket: https://progress.opensuse.org/issues/181313
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/18013317

Enable long URLs in s390x zVM

---

lib/opensusebasetest.pm

Container test for SLE16 ppc64le, the check on the _grub_ menu shall be skipped, appearing and continuing too fast and the _linux-login prompt_ directly expected.
Note that these tests rely in hdd_1 image available. But fix for create_hdd_agama_containers is still ongoing, but also unrelated, so this PR is a step forward to resolve the issue impacting the tests using that image, first.
Related ticket:https://progress.opensuse.org/issues/183641
- sle-16.0-Online-ppc64le-Build94.2-docker-stable_tests@ppc64le-emu -
https://openqa.suse.de/tests/17986608  
- sle-16.0-Online-ppc64le-Build94.2-docker_tests@ppc64le-emu -
https://openqa.suse.de/tests/17986609 
- sle-16.0-Online-ppc64le-Build94.2-podman_tests@ppc64le-emu -
https://openqa.suse.de/tests/17986610
Next VR updates in …

Container tests on sle16 ppc on boot desktop skip grub2

---

test_data/yam/agama_rmt.yaml

##
##
- Related ticket: https://progress.opensuse.org/issues/182996
- Related info: [**repo list**](https://openqa.suse.de/tests/17921840#step/validate_repos/12)
- Related MR: [**MR#473**](https://gitlab.suse.de/qe-yam/openqa-job-groups/-/merge_requests/473)
- Needles: N/A
- Verification run: [**VR**](https://openqa.suse.de/tests/overview?arch=&flavor=&machine=&test=hjluo_sles_rmt_unattended_dev&modules=&module_re=&group_glob=&not_group_glob=&comment=&distri=sle&version=agama-10.0&build=hjluo%2Fos-autoinst-distri-opensuse%23rmt_validate_URI#)
##

Validate RMT URI in validate_repos

---

lib/hacluster.pm
lib/sles4sap.pm
tests/ha/check_logs.pm
tests/ha/fencing.pm
tests/ha/qnetd.pm

This commit adds a call to `Utils::Logging::record_avc_selinux_alerts` in the `post_run_hook` of HA and SLES for SAP tests so the AVC alerts are collected and reported at the end of each module's run.
- Related Ticket: https://jira.suse.com/browse/TEAM-10408
- Needles: N/A
Check at the end of each HA or SLES for SAP test module that the command `ausearch -m avc -r` was executed.
Exceptions are `ha/check_hawk` and `ha/ha_cluster_crash_test` which are not running the `post_run_hook` from `lib/hacluster`.
- HANA: http://mango.qe.nue2.suse.org/tests/6745 :green_circle: 
- NetWeaver ASCS: http://mango.qe.nue2.suse.org/tests/6744 :green_circle: 
- ASE: http://mango.qe.nue2.suse.org/tests/6743 :green_circle: 
- Pacemaker CTS cluster test: [node](http://mango.qe.nue2.suse.org/tests/6751), …

Report SELinux AVCs after each HA & SAP test module

---

data/containers/bats/skip.yaml
tests/containers/bats/buildah.pm

Enable multi-arch testing on buildah upstream tests.  This is achieved just by installing the `qemu-linux-user` package which is available on SLES 15-SP6+ & Tumbleweed.
- Tumbleweed: https://openqa.opensuse.org/tests/5099363
- SLE 16.0: https://openqa.suse.de/tests/18031667
- SLES 15-SP7: https://openqa.suse.de/tests/18031666
- SLES 15-SP6: https://openqa.suse.de/tests/18031665 (transient network failure)
```
$ susebats notok  https://openqa.opensuse.org/tests/5099363
BATS_SKIP: sbom
BATS_SKIP_ROOT:
BATS_SKIP_USER: bud run
```

Enable multi-arch tests on buildah

---

tests/console/curl_ipv6.pm
tests/console/wget_ipv6.pm

Force ipv6 as curl can default to ipv4 in case of ipv6 is not working.
Resurrect https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/22050

Force ipv6 in wget|curl

---

data/containers/bats/patches/podman/25858.patch
data/containers/bats/skip.yaml
tests/containers/bats/podman.pm

Re-enable [161-volume-quotas](https://github.com/containers/podman/blob/main/test/system/161-volume-quotas.bats) test as it helped uncover https://bugzilla.suse.com/show_bug.cgi?id=1244500
Also incorporate https://github.com/containers/podman/pull/25858 to make it faster on SLE 16.0.
- Tumbleweed: https://openqa.opensuse.org/tests/5101219
- SLE 16.0: https://openqa.suse.de/tests/18040019 (failed due to the above bug).

bats/podman: Re-enable 161-volume-quotas test

---

tests/sles4sap/wizard_hana_install.pm

B1 2505 and 15-SP7 seems to be a bit slower than other version and in some instances took more than 600s to finish the installation, leading to random failures.
FAIL:
https://openqaworker15.qa.suse.cz/tests/328776
VR:
https://openqaworker15.qa.suse.cz/tests/329200

Raise timeout while waiting for sap-installation-wizard to finish

---

lib/containers/bats.pm
tests/containers/bats/README.md

Introduce BATS_TEST_PACKAGES variable to be able to test emergency PTF's, kernel KOTD's, etc.
- Related ticket: https://bugzilla.suse.com/show_bug.cgi?id=1244500#c5
- https://openqa.suse.de/tests/18044414
- https://openqa.suse.de/tests/18044406 (`BATS_TEST_PACKAGES=https://kerncvs.suse.de/kerneltest/suse/5e50d7e/kernel-default-6.12.0-160000.67.1.g5e50d7e.x86_64.rpm`)

bats: Introduce BATS_TEST_PACKAGES variable

---

lib/sles4sap/sap_deployment_automation_framework/deployment_connector.pm

With PR#22208 retaining deployment remained broken and test would ignore
OpenQA setting 'SDAF_DEPLOYMENT_ID'. This PR fixes the issue.
Ticket: https://jira.suse.com/browse/TEAM-10319
Retain deployment: https://openqaworker15.qa.suse.cz/tests/329072#dependencies
Reuse deployment 329072: https://openqaworker15.qa.suse.cz/tests/329188#live

Fix SDAF retaining deployment option

---

tests/installation/bootloader_s390.pm

With newer versions of x3270, commands are now more asynchronous and e.g. ENTER does not wait for previous ones to complete. Add some explicit synchronization.
- Related ticket: https://progress.opensuse.org/issues/183110
15.6 container: https://openqa.opensuse.org/tests/5099231
15.6 container again: https://openqa.opensuse.org/tests/5099242
15.5 container: https://openqa.opensuse.org/tests/5101041

tests/installation/bootloader_s390.pm: Wait for z/VM and CMS to be ready

---

tests/installation/ipxe_install.pm

Some machines need the iPXE bootscript to be set to HDD. This logic was
missing in the Agama installation workflow.
Failure: https://openqa.suse.de/tests/18050432#step/grub_test/6  system booted installer again.
- Related ticket: https://progress.opensuse.org/issues/183980
- Verification run:  https://openqa.suse.de/tests/18050595#step/first_boot/1 (will fail later in kdump, which is bsc#1244215)

ipxe_install: Set bootscript to HDD if requested for Agama installer

---

data/containers/bats/skip.yaml
tests/containers/bats/README.md
tests/containers/bats/buildah.pm

The [sbom](https://github.com/containers/buildah/blob/main/tests/sbom.bats) test is flaky as it uses 3rd party images and wastes resources.

bats/buildah: Nuke sbom test

---

tests/containers/buildah.pm

Running buildah module for PowerPC SLE16 container hosts, 
normal user tests executed **after** root tests, remain blocked until timeout.
Moving that call execution **before** root tests call, fixed the issue.
- Related ticket:- https://progress.opensuse.org/issues/183641
- Verification run: https://openqa.suse.de/tests/18052502 see more in the PR posts.

PowerPC SLE-16 container host test buildah fixed

---

data/elemental3/config.sh
tests/elemental3/generate_image.pm
tests/elemental3/test_image.pm

Some timeout need to be increased for the test to pass. Also disable GRUB timeout to ensure that the bootloader needle is correctly trapped.
- Needles: N/A
- [generate_image](https://openqa.suse.de/tests/18031314) :white_check_mark:
- [test_image](https://openqa.suse.de/tests/18031565) :x:
**NOTE:** the `test_image` test fails because of an issue with RKE2 on aarch64, this is not related to this PR. And as aarch64 binaries are recent for RKE2 and in a preview state this will check (and fix if needed) later.

Fix Elemental3 aarch64 test

---

tests/installation/bootloader_svirt.pm

**Bootloader svirt** updated for MinimalVM vmware images management,  to copy in datastore the missing images.
- Related ticket: https://progress.opensuse.org/issues/177462#note-16 
- Verification run: in next posts.
---  
Code last update:
upload image When image missing in datastore, otherwise the image found is used.

Bootloader svirt vmware checking images in datastore

---

lib/containers/bats.pm

Make reboot mandatory.  Since the introduction of `BATS_TEST_PACKAGES` & `BATS_TEST_REPOS` we may need to do it.  This cleans up a dirty part of the code.
- Verification run: not needed.

bats: Reboot is always needed

---

data/agama_auto/sle_default_ipmi.jsonnet
data/agama_auto/sle_default_ipmi_no_reg.jsonnet

This improvement to the existing IPMI profile is based on the PVM profile with additional enhancements for bare metal. There should be a bootloader timeout to ensure that the grub menu needle is matched.
We can't use an infinite timeout because some machines have console input issues and the return key is not registered. A value of 45 seconds is taken from the SLE 15 AY profile. 
We also need to set GRUB_TERMINAL to console to ensure that the grub menu is displayed properly. We do the same in SLE 15 AY profiles.
- Related ticket: https://progress.opensuse.org/issues/183146
x86_64: https://openqa.suse.de/tests/18079558 (kdump fail is bsc#1244215)
aarch64: https://openqa.suse.de/tests/18079555

agama: Improve IPMI installation profile

---

schedule/security/cc_eal4.yaml

Ticket: https://progress.opensuse.org/issues/183860
VR: https://openqa.suse.de/tests/18079608

cc_eal4: use boot_disk instead of boot_to_desktop

---

schedule/qam/common/mau-extratests1.yaml
schedule/qam/common/mau-extratests2.yaml

- Related ticket: 4895659490d1e07aa34882c1b4ac2eb58dc6c7b3
- Verification run: https://openqa.suse.de/tests/overview?distri=sle&build=jpupava_ipv6

mau-extratests2: Don't schedule ipv6 tests on 12-SP3

---

tests/console/dracut.pm

This follows up #22337 dracut is now less verbose, and the check with the `validate_script_output` is mostly checking that the command line has any output
VR: https://openqa.opensuse.org/tests/5109617#step/dracut/20
Ticket: https://progress.opensuse.org/issues/183926

Change dracut --list-modules to search for modules instead of command line

---

tests/kernel/run_kselftests.pm

- https://progress.opensuse.org/issues/182360
* cgroup: 
https://openqa.suse.de/tests/18087909: using git tree and tag v6.12
https://openqa.suse.de/tests/18087910: no git tag, so basic regression to make sure nothing breaks
* livepatch:
https://openqa.suse.de/tests/18087922 git tag set to v6.12
https://openqa.suse.de/tests/18087923 no git tag

kernel: Enhance kselftests runner while using git tag

---

tests/containers/bci_test.pm

Export the OS_PRETTY_NAME setting, as it is required by BCI-Tests.
- Related failure: https://openqa.suse.de/tests/18082593#step/_root_BCI-tests_base_/6
- Related PR: https://github.com/SUSE/BCI-tests/pull/852
- Verification run: https://duck-norris.qe.suse.de/tests/14876

Export OS_PRETTY_NAME

---

tests/microos/image_checks.pm

The partition layout is untouched so free sectors check should expect the same values as in the previous version after migration
- sle-micro-6.2-Default-aarch64-Build13.4-slem_migration_6.1_to_6.2@aarch64 -> https://openqa.suse.de/tests/18095739
- sle-micro-6.2-Default-x86_64-Build13.4-slem_migration_6.1_to_6.2@64bit -> https://openqa.suse.de/tests/18095740

Sectors do not change after migration

---

tests/qemu/qemu.pm

* **For** recent builds, uefi shell has been removed from ovmf pacakge for security and size saving purpose. Empty qemu machine can only shows "no bootable device" and enter into boot manager which does not provide anything to boot. 
* **Match** needle [qemu-enter-boot-manager](https://openqa.suse.de/tests/18011344#step/qemu/10) and then [qemu-uefi-boot-manager](https://openqa.suse.de/tests/18011344#step/qemu/11) before exiting qemu is necessary for the test run to continue.
* [sle-micro-6.2-Default-aarch64-Build12.6-slem_virtualization](https://openqa.suse.de/tests/18011344)
* [ sle-micro-6.2-Default-SelfInstall-aarch64-Build12.6-slem_installation_virt](https://openqa.suse.de/tests/18011394)
* [ sle-micro-6.2-Default-qcow-aarch64-Build12.6-slem_virtualization](htt …

Match uefi boot manager before exiting qemu

---

tests/console/libgit2.pm

Add condition to check if pygit exsited
- Related ticket: https://progress.opensuse.org/issues/183842
- Verification run: https://openqa.suse.de/tests/18042950#step/libgit2/10
pygit2 will be added at https://build.suse.de/request/show/377542

Add condition to check if pygit exsited

---

tests/jeos/firstrun.pm

Validate that SELinux is in enforcing mode.
Do the same procedure done in [selinux_setup](https://github.com/os-autoinst/os-autoinst-distri-opensuse/blob/master/tests/security/selinux/selinux_setup.pm#L72).
- Related ticket: https://progress.opensuse.org/issues/182351

jeos: Validate that SELinux is in enforcing mode

---

lib/main_common.pm
schedule/jeos/sle/jeos-base+sdk+desktop.yaml
schedule/jeos/sle/jeos-extratest-sle12.yaml
schedule/jeos/sle/jeos-extratest.yaml
schedule/jeos/sle/jeos-fs_stress.yaml
schedule/jeos/sle/jeos-ltp.yaml
schedule/jeos/sle/jeos-main.yaml
schedule/jeos/sle/jeos12sp5-main.yaml
schedule/jeos/sle/jeos15sp1-main.yaml
schedule/jeos/sle/minimalvm-extratest.yaml
schedule/jeos/sle/minimalvm-main.yaml
schedule/jeos/sle/minimalvm-toolchains.yaml
tests/jeos/host_config.pm

s390x z/KVM has a different networking setup than other openQA workers. In this particular case, we need to force eui64 address assignment.
- Verification run: https://openqa.suse.de/tests/18100322#

Generate IPv6 EUI-64 address

---

data/containers/bats/skip.yaml
lib/containers/bats.pm

Restrict BATS patches to each package test directory.
Sometimes patches may touch other files that may not exist in older versions and `git apply` would fail.  Restrict their scope to each package test directory so the patches can be cleanly applied.
Apply https://github.com/containers/podman/pull/25942 to SLES 15-SP6+ which uses podman v4.9.5.
Failed tests:
- https://openqa.suse.de/tests/18110404
- https://openqa.suse.de/tests/18110416
- SLES 15-SP6: https://openqa.suse.de/tests/18111554
- SLES 15-SP7: https://openqa.suse.de/tests/18111553
- Tumbleweed: https://openqa.opensuse.org/tests/5114221

Restrict BATS patches to each package test directory

---

lib/containers/container_images.pm

Fix container-suseconnect test
- Call `container-suseconnect` directly as customers would do instead of calling a plugin directly.
- Remove all code related to `zypper-docker` which is no longer maintained.
- Add missing `--rm` option to ephemeral container runs.
Related discussion: https://suse.slack.com/archives/C02DR0C5XUY/p1750153948868519
Supersedes https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/22388
Failing tests:
- https://openqa.suse.de/tests/18108940
- 15-SP3:
- docker: https://openqa.suse.de/tests/18112478
- podman: https://openqa.suse.de/tests/18112479
- 15-SP4:
- docker: https://openqa.suse.de/tests/18112480
- podman: https://openqa.suse.de/tests/18112481
- 15-SP5:
- docker: https://openqa.suse.de/tests/18112482
- podman: …

Fix container-suseconnect test

---

tests/jeos/firstrun.pm

Currently the test is taking longer than expected. Let's try a TO increase
- ticket: https://progress.opensuse.org/issues/183254

Increase timeout for drive re-encryption

---

lib/Installation/ModuleRegistration/ModuleRegistrationPage.pm

Problem cause: SCC_ADDONS has 'sysm' but there was no mapping for 'sysm' to the full module name. So by default the first one in the list got selected and due to recent changes in SCC the first one moved from "base" to "ha". But the HA module needs an own registration code which caused the failures e.g.
https://openqa.suse.de/tests/18109900#step/add_additional_products/1
- Verification run: https://openqa.suse.de/tests/18114997

Fix for sysm related failures in MU

---

schedule/qam/common/kernel/gfxdrivers.yaml

Restore the old qam-gfxdrivers.yaml schedule file removed by 24e25d7, with a new name in qam/common/kernel/gfxdrivers.yaml.
- Related ticket: https://progress.opensuse.org/issues/184231
Signed-off-by: Andrea Cervesato <andrea.cervesato@suse.com>

Restore qam gfxdrivers schedule

---

tests/security/apparmor/aa_prepare.pm

- Related ticket: https://progress.opensuse.org/issues/176154 https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/21925
`aa-notify -l` is failing because of https://bugzilla.opensuse.org/show_bug.cgi?id=1216660
- Verification run: https://openqa.opensuse.org/tests/5109674

aa_prepare: Replace nscd with samba

---

lib/autoyast.pm
tests/yam/agama/import_agama_profile.pm

We have added a condition to 
- Related ticket: https://progress.opensuse.org/issues/184004
- Needles: N/A
- x86_64 - 97.3/prod: https://openqa.suse.de/tests/18115174
- x86_64 - 14.8/dev: https://openqa.suse.de/tests/18115181
- aarch64 - 97.3/prod: https://openqa.suse.de/tests/18115173
- aarch64 - 14.8/dev: https://openqa.suse.de/tests/18115180
- s390x-kvm - 97.3/prod: https://openqa.suse.de/tests/18112463
- s390x-kvm - 14.8/dev: https://openqa.suse.de/tests/18115787
- ppc64le-hmc - 97.3/prod: https://openqa.suse.de/tests/18115168
- ppc64le-hmc - 14.8/dev: https://openqa.suse.de/tests/18115179

Replace 'agama profile import' with 'agama config load'

---

data/yam/agama/auto/lib/dasd.libsonnet
data/yam/agama/auto/template.libsonnet

Add unattended support for DASD, and test it in sles_lvm_unattended testing. Do not  bring the DASD device online in booting, instead, bring the device by unattended profile and active it for installation.
- Related ticket: https://progress.opensuse.org/issues/183029
- Verification run: [sles_lvm_unattended_dasd_dev]: TBD
- Related MR: https://gitlab.suse.de/qe-yam/openqa-job-groups/-/merge_requests/461

Add unattended support for DASD

---

tests/console/bind.pm

Print the variable after variable is populated,
now the variable was at the end empty
- Related ticket: https://openqa.suse.de/tests/18132230#step/bind/1
- Verification run: https://openqa.suse.de/tests/18133597 VR does not prove anything, retry is required

bind: Fix TFAIL variable

---

tests/virt_autotest/esxi_open_vm_tools.pm

Check and install nmap package before running the command.
https://openqa.suse.de/tests/17975843#step/esxi_open_vm_tools/177
- Related ticket: https://progress.opensuse.org/issues/183785
- sle16 - https://openqa.suse.de/tests/18002150
- sle-micro 6.2 - https://openqa.suse.de/tests/18139208

Fix missing nmap command failure

---

lib/kdump_utils.pm
schedule/storage/nfs.yaml
tests/kernel/kdump_over_nfs.pm
tests/kernel/nfs_barriers.pm

The patch is introducing KDUMP check over NFS where NFS multimachine tests are re-used, KDUMP is configured for writing to the mounted NFS share and then all is checked on the nfs server side - if the dump is there and if it is readable etc.
We need client and the server to wait for each other. Thus I think using get_required_var('ROLE') helps and is also simple - one module to do barrier_wait() on both client and the server side.
Then the actual test is happening on the client side only using check_function()
- Related ticket: https://progress.opensuse.org/issues/57254
* SLE16:
https://openqa.suse.de/tests/18139970
https://openqa.suse.de/tests/18139971
https://openqa.suse.de/tests/18139969
* TW x86_64:
https://openqa.opensuse.org/tests/5119273 …

Add kdump over NFS test

---

tests/console/dnsmasq.pm

- Related ticket: https://progress.opensuse.org/issues/183965
- Verification run: https://openqa.suse.de/tests/overview?distri=sle&version=15-SP4&build=jpupava_dnsmasq
https://openqa.suse.de/tests/18133676 retry
I added sleep to slow the loop down

dnsmasq: Add retry when query failed

---

schedule/sles4sap/ensa/ensa_nodes.yaml
tests/sles4sap/configure_selinux_policy.pm

SLE4SAP 16 introduces SELinux, but the default configuration causes errors during the installation of SAP software.
This creates a module that applies the instructions in the draft release notes for SLE4SAP 16, when the SELINUX_POLICY variable is set in either ´permissive´ or ´enforcing´, and disables SELinux when it is set to ´disabled´ to allow for debugging.
- Related Ticket: TEAM-10414
- Verification run: [disabled](https://openqaworker15.qa.suse.cz/tests/overview?distri=sle&version=16.0&build=:configure-selinux-disabled-restorecon), [enforcing](https://openqaworker15.qa.suse.cz/tests/overview?distri=sle&version=16.0&build=:configure-selinux-enforcing-restorecon), [permissive](https://openqaworker15.qa.suse.cz/tests/overview?distri=sle&version=16.0&build=:configure-selinux-permissive-r …

Create module to configure SELinux enforcement

---

lib/susedistribution.pm
tests/yam/agama/validate_headless.pm

We have added an installation tty console definition in case it is Agama.
In addition we have added config load and minor error check in jsonnet command.
- Related ticket: https://progress.opensuse.org/issues/184141
- Needles: N/A
- x86_64_dev: https://openqa.suse.de/tests/18150174
- x86_64_prod: https://openqa.suse.de/tests/18150363
- aarch64_dev: https://openqa.suse.de/tests/18150082
- aarch64_prod: https://openqa.suse.de/tests/18150153
- s390x-kvm_dev: https://openqa.suse.de/tests/18150078
- s390x-kvm_prod: https://openqa.suse.de/tests/18150079
- ppc64le_dev: https://openqa.suse.de/tests/18150080
- ppc64le_prod: https://openqa.suse.de/tests/18150081
- headless_dev: https://openqa.suse.de/tests/18150295
- headless_prod: https://openqa.suse.de/tests/18150294

Adapt installation console to tty2 instead of tty7

---

lib/sles4sap/sap_deployment_automation_framework/deployment.pm
t/20_sdaf_deployment_library.t

Unify sdaf uploaded logs file name.
- Related ticket: no
- Verification run: https://openqaworker15.qa.suse.cz/tests/330274#downloads (the names are `upload_logs-${hostname}_xxx.xxx` now)

Unify sdaf uploaded logs file name

---

tests/console/bind.pm

In 6e44c72 I broke the retry, on older versions it has to use run.sh instead of runall.sh to run specific test
- Related ticket: https://openqa.suse.de/tests/18145288#step/bind/97

bind: Fix single test retry

---

tests/yam/migration/restore_upgrade_env.pm
tests/yam/migration/setup_upgrade_env.pm

Failed job: https://openqa.suse.de/tests/18148231#  During 15SP7 installation, we need set AGAMA=0, then restore it after installation to avoid it affect installation of 15SP7.
- Related ticket: https://progress.opensuse.org/issues/178987 
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/18164464#
https://openqa.suse.de/tests/18164443#step/setup_upgrade_env/2 migration from 15SP5 to 15SP7
https://openqa.suse.de/tests/18164442#step/setup_upgrade_env/1 migration from 15SP6 to 15SP7

Save/restore Agama settings during installation

---

tests/kernel/update_kernel.pm

SLERT module metadata now pulls `kernel-rt_debug` package as a dependency through the RT pattern. This triggers kernel flavor checks during update installation. Lock the debug package out to ensure only `kernel-rt` updates will be installed.
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/18175156

update_kernel: Lock out kernel-rt_debug

---

lib/sles4sap/sap_deployment_automation_framework/deployment.pm

Fix upload logs failure on uploading /var/log/zypper.log
For example: https://openqaworker15.qa.suse.cz/tests/330664#step/upload_logs/52
`curl: (26) Failed to open/read local data from file/application`
- Related ticket: No
- Verification run:No

Fix upload logs failure on /var/log/zypper.log

---

lib/Installation/Partitioner/LibstorageNG/PartitioningSchemePage.pm

There's a new control in the guided partitioning scheme screen, it takes over `alt-a` for now this is confined to Staging:F
Failure: https://openqa.opensuse.org/tests/5124162#step/encrypt_lvm/6
VR: https://openqa.opensuse.org/tests/5126411 
(failure on VR already reported as https://bugzilla.opensuse.org/show_bug.cgi?id=1245247)
See also #22351

Handle new shortcut to enable disk encryption in Tumbleweed

---

schedule/ha/rear/rear_backup_16.yaml

Create a new backup schedule that can be used to test Rear feature on 16.
The new schedule is derived from the rear_backup.yaml in the same folder.
Functional and important changes, that are 16 specific, are about using Agama. This version of the schedule also move schedule specific settings to the schedule file from the JobGroup file.
- Related ticket: https://jira.suse.com/browse/TEAM-10314
https://openqa.suse.de/tests/18183542#step/rear_backup/22 fails in package installation, in rear specific test module. But image boot is fine.

Create a new dedicated Rear schedule for 16

---

tests/network/config_services.pm
tests/x11/evolution/evolution_prepare_servers.pm

-on SLED add Server Applications module for dovecot
-update description
- Related ticket: https://progress.opensuse.org/issues/184585 https://gitlab.suse.de/qa-maintenance/qam-openqa-yml/-/merge_requests/862
- Verification run: https://openqa.suse.de/tests/overview?distri=sle&build=jpupava_dovecot

Use Server Applications module for dovecot

---

data/sles4sap/qe_sap_deployment/mr_test_azure.yaml
data/sles4sap/qe_sap_deployment/mr_test_azure_uri.yaml
data/sles4sap/qe_sap_deployment/sles4sap_azure_generic.yaml
data/sles4sap/qe_sap_deployment/sles4sap_azure_generic_maintenance.yaml
data/sles4sap/qe_sap_deployment/sles4sap_azure_generic_uri.yaml
tests/sles4sap/publiccloud/qesap_terraform.pm

Add a new terraform variable named iscsi_enabled. It is controlled by a openQA variable using the same name. For the moment the value is derived by FENCING_MECHANISM. This is an intermediate commit, in a next one it will be possible to remove FENCING_MECHIANISM and all the terraform variables controlled by that.
Ticket: https://jira.suse.com/browse/TEAM-10410
sle-15-SP6-HanaSr-Azure-Byos-x86_64-Build15-SP6_2025-06-16T02:03:20Z-hanasr_azure_test_sbd az_Standard_E4s_v3 
-  http://openqaworker15.qa.suse.cz/tests/329790 :green_circle:  
1.  Job has `FENCING_MECHANISM:sbd` variable, and no ISCSI_ENABLED variable (job triggered with no modification in the JobGroup)
2. conf.yaml http://openqaworker15.qa.suse.cz/tests/329790/file/deploy_qesap_terraform-sles4sap_azure_generic.yaml has terraform …

Add ISCSI_ENABLED terraform variable

---

lib/Utils/Logging.pm
lib/consoletest.pm
lib/containers/basetest.pm
lib/installbasetest.pm
lib/opensusebasetest.pm
tests/shutdown/shutdown.pm

After each test module, we should look for recorded AVC's if the system runs with SELinux.
- [microos-image](http://kepler.suse.cz/tests/24991#)
- [tw-cloud + cloudinit](http://kepler.suse.cz/tests/24983)
- [podman - avc fail](http://kepler.suse.cz/tests/24986#step/rootless_podman/239)
- [tw](http://kepler.suse.cz/tests/24982)
- [6.2 selfinstall](http://kepler.suse.cz/tests/24989)
- [microos container host - avc fail](http://kepler.suse.cz/tests/24980#step/rootless_podman/229)
- [minimal-vm](http://kepler.suse.cz/tests/24987)
- [6.2](http://kepler.suse.cz/tests/24992#live)
- sle-micro-6.2-Default-qcow-s390x-Build13.17-default@s390x-kvm -> https://openqa.suse.de/tests/18190764
- …

Enable test failure when AVC records are found

---

tests/kernel/run_kselftests.pm

45s is a default value in the kselftests thus this is kept. However at times, this might be not enough which might be also SUT-dependent. For instance the cgroup tests for mem ctl fail if there is lower number of CPUs and setting higher number of CPUs results in the cpu tests to fail as the default 45s timeout isn't sufficient. This patch allows to set --override-timeout value to the given tests
- Related ticket: https://progress.opensuse.org/issues/184108
- Verification run: https://openqa.suse.de/tests/18183821
We have this where cpu tests pass:
When fixing kmem we set CPU to 16 and we get cpu tests failing:
https://openqa.suse.de/tests/18201023
CPU=16 and timeout set to 300 we get cpu tests passing again: **https://openqa.suse.de/tests/18204132**

kselftests: Add timeout option

---

lib/sles4sap_publiccloud.pm

Motivations:
- Playbook is applying patch to Azure fence_agent that is no more needed.
- Playbook is scheduled as part of PTF feature that is generic, even if playbook is specific.
Related ticket: https://jira.suse.com/browse/TEAM-9453
sle-15-SP6-HanaSr-Azure-Byos-x86_64-Build15-SP6_2025-06-25T02:03:24Z-hanasr_azure_test_msi az_Standard_E4s_v3
- http://openqaworker15.qa.suse.cz/tests/330909

Remove schedule of additional_fence_agent_tasks

---

lib/containers/bats.pm

Install CA repo to use with `BATS_TEST_REPOS`.  This is needed when testing updates from IBS.
- 15-SP4: https://openqa.suse.de/tests/18206571 `BATS_TEST_REPOS=https://download.suse.de/ibs/home:/danishprakash:/branches:/SUSE:/SLE-15-SP4:/Update/standard/home:danishprakash:branches:SUSE:SLE-15-SP4:Update.repo`
- 15-SP5: https://openqa.suse.de/tests/18206570 `BATS_TEST_REPOS=https://download.suse.de/ibs/home:/danishprakash:/branches:/SUSE:/SLE-15-SP5:/Update/standard/home:danishprakash:branches:SUSE:SLE-15-SP5:Update.repo`

bats: Install CA repo to use with BATS_TEST_REPOS

---

products/sle/main.pm

Add steps for ppc64le on qemu backend
- Related ticket: https://progress.opensuse.org/issues/184306
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/18201017

xfstests: processing ppc64le on qemu

---

data/yam/agama/auto/lib/addons.libsonnet

We don't require to set the SLE version in the addons section of jsonnet template.
- Needles: N/A

Removed version from addons jsonnet library

---

tests/installation/ipxe_install.pm

Specific CPU kernel options are required in bootscripts in some of our tests(with SR-IOV capability), for example, `intel_iommu=on` for Ethernet PCI passthrough test and vGPU passthrough tests. I can't find other better places than 
ipxe_install.pm to support this feature.
usage:
- Related ticket: https://progress.opensuse.org/issues/178702
- Verification run: https://openqa.suse.de/tests/18200856#step/login_console/27

Allow to pass extra CPU kernel options in specific tests

---

data/sles4sap/qe_sap_deployment/qesap_aws_peering.yaml

Fix a small unnoticed mistake introduced by 7bd4f55 It went un-noticed but can result in wrong sequence of ansible-playbook commands generated by the qe-sap-deployment glue script.
Fix small unnoticed mistake from https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/22353/files#diff-1b478325352b1fad8cd201c6802a845afe72369b435483cf65c883a13c91a30aR52
It can apparently have a negative effect like: https://openqaworker15.qa.suse.cz/tests/331014/logfile?filename=deploy-qesap_exec_ansible.log.txt#line-10410
- Related ticket: [TEAM-10427](https://jira.suse.com/browse/TEAM-10427)
sle-15-SP6-Qesap-Aws-Byos-x86_64-BuildLATEST_AWS_SLE15_6_BYOS-qesap_aws_ibsmirror_peering_test 
- http://openqaworker15.qa.suse.cz/tests/331050

Fix YAML indentation mistake in playbook list

---

tests/containers/compose.pm

When testing podman alone, install podman-docker in the compose module for testing docker-compose with podman.
- Related ticket: https://bugzilla.suse.com/show_bug.cgi?id=1244448
- SLE 16.0 podman: https://openqa.suse.de/tests/18246710
- JeOS podman & docker: https://openqa.opensuse.org/tests/5138320

containers/compose: Add workaround for docker-compose with podman

---

lib/utils.pm
tests/containers/host_configuration.pm

Use OBS repo for ca-certificates-suse.  I've been using the OBS repo on 15-SP4+ without issues.
- Related ticket: https://progress.opensuse.org/issues/180143
- opensuse-Tumbleweed-BCI-x86_64-Build20250627-bci_minimal_podman@64bit -> https://openqa.opensuse.org/tests/5138545
- sle-15-SP3-BCI-Updates-x86_64-Build9.46_base-fips-image-bci-base-fips_15.3_on_SLES_15-SP3_podman@64bit -> https://openqa.suse.de/tests/18247916

Use OBS repo for ca-certificates-suse

---

tests/console/lshw.pm

https://progress.opensuse.org/issues/184840
https://progress.opensuse.org/issues/184138
- Verification run: https://openqa.suse.de/tests/18248172

Fix 'lshw' test issue on s390x

---

lib/utils.pm

Fix ensure_ca_certificates_suse_installed on SLEM.
- Failed test: https://openqa.suse.de/tests/18247994#step/host_config/63
- Verification run: https://openqa.suse.de/tests/18248340

Fix ensure_ca_certificates_suse_installed on SLEM

---

data/x11/helm_chart/kiosk_values.yaml
lib/containers/k8s.pm
lib/main_common.pm
tests/microos/workloads/x11-container/x11_helm_client.pm
tests/microos/workloads/x11-container/x11_helm_server.pm
variables.md

Deploy below containers using helm:
X11, pulseaudio and firefox kiosk
Verify if pulseaudio is running from client side
Verify if audio can be played fine from code level
- Related ticket: https://progress.opensuse.org/issues/174418
- Needles: already added when debugging on osd
- Verification run (updated on Jun 28): 
> x11_helm_server  https://openqa.suse.de/tests/18232826
> x11_helm_client  https://openqa.suse.de/tests/18232827

Add test cases for deploying x11 related containers using helm

---

tests/containers/buildah.pm

Use cowsay instead of python3 because python3 is a meta-package that may fail.
- Related ticket: https://progress.opensuse.org/issues/184843
- Failing test: https://openqa.suse.de/tests/18241780#step/buildah_podman/112
- Verification run: https://openqa.suse.de/tests/18248921#step/buildah_podman/115
```
_____________
< hello world >
-------------
\   ^__^
\  (oo)\_______
(__)\       )\/\
||----w |
||     ||
```

containers/buildah: Use cowsay instead of python3

---

lib/main_common.pm
tests/microos/workloads/x11-container/x11_podman_client.pm
tests/microos/workloads/x11-container/x11_podman_server.pm

Rename x11_client/server to x11_podman/server to keep consistent with deploying with kubernetes with helm scenario
Update tags for x11, pulseaudio and firefox kiosk containers since the previous used 'latest' tag is not available now
- Related ticket: https://progress.opensuse.org/issues/174418
- Needles: N/A
>  x11_podman_server https://openqa.suse.de/tests/18262817#
>  x11_podman_client https://openqa.suse.de/tests/18262819#

Rename x11_client/server to x11_podman_client/server

---

tests/containers/rootless_docker.pm

https://bugzilla.suse.com/show_bug.cgi?id=1240150 is fixed so no need to apply the workaround to disable SUSE secrets.
- Verification runs (SLE 16.0):
- docker:  https://openqa.suse.de/tests/18263750
- docker-stable: https://openqa.suse.de/tests/18263751
TODO in a follow-up PR:
- Schedule the test on SLE-15:
https://github.com/os-autoinst/os-autoinst-distri-opensuse/blob/master/lib/main_containers.pm#L182

containers: No need to disable SUSE secrets anymore

---

schedule/ha/rear/rear_backup_16.yaml

Leave the ReaR backup test to run with SYSTEM_ROLE:default in test with Agama for 16.0.
- Related ticket: https://jira.suse.com/browse/TEAM-10463
https://openqa.suse.de/tests/18264831 :green_circle:  triggered with `AGAMA=1` on the command line and using dev JoGroup definition. Failure is later and due to a known issue.

Remove SYSTEM_ROLE: textmode from ReaR

---

data/containers/bats/skip.yaml
tests/containers/bats/README.md

Update BATS_SKIP for runc 1.2. 
```
$ susebats notok https://openqa.suse.de/tests/18259892
BATS_SKIP:
BATS_SKIP_ROOT: bud run
BATS_SKIP_USER:
$ susebats notok https://openqa.suse.de/tests/18259624
BATS_SKIP:
BATS_SKIP_ROOT: bud namespaces run
BATS_SKIP_USER:
$ susebats notok https://openqa.suse.de/tests/18259716
BATS_SKIP: bud
BATS_SKIP_ROOT: run
BATS_SKIP_USER:
$ susebats notok https://openqa.suse.de/tests/18259892
BATS_SKIP:
BATS_SKIP_ROOT: bud run
BATS_SKIP_USER:
```

buildah/bats: Update BATS_SKIP for runc 1.2

---

lib/network_utils.pm
tests/containers/host_configuration.pm

When using wicked, we must not override the `resolv.conf` file without also setting `NETCONFIG_DNS_STATIC_SERVERS`.
- Related ticket: https://progress.opensuse.org/issues/184375
- Related failure: https://openqa.suse.de/tests/18265291#step/host_configuration/84
- Verification run: https://openqa.suse.de/tests/18266366

Fix DNS race condition with wicked

---

schedule/ha/rear/rear_backup_16.yaml

Move HOSTNAME variable from the schedule to the JobGroup
- Related Ticket: https://jira.suse.com/browse/TEAM-10463 
- https://openqa.suse.de/tests/18280542#dependencies  :green_circle:  and   https://openqa.suse.de/tests/18280543 :green_circle: 
- https://openqa.suse.de/tests/18280545#dependencies  :green_circle:   and   https://openqa.suse.de/tests/18280546

Move HOSTNAME for rear away from the schedule.

---

data/containers/bats/skip.yaml

Fix BATS_SKIP for 15-SP4
```
susebats notok  https://openqa.suse.de/tests/18282929
BATS_SKIP: bud
BATS_SKIP_ROOT: run
BATS_SKIP_USER:
```

bats/buildah: Fix BATS_SKIP for 15-SP4

---

lib/containers/bats.pm

Record OCI runtime version to avoid looking at the package list to get this information.

bats: Record OCI runtime version

---

lib/publiccloud/provider.pm

In case of failure to create VM in defined AZ test logic tries to loop over
other AZ in same region and create VM in them. In case of success we need also to reset AZ
which defined in the provider_client. So any logic will get into correct AZ.

Update Availability Zone in case of change

---

tests/console/libgpiod.pm

Follow-up https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/22447
- Verification run: https://openqa.opensuse.org/tests/5144157#step/libgpiod/1

libgpiod: skip test if v1.x

---

tests/console/redis.pm

https://progress.opensuse.org/issues/184819
- Verification run: http://openqa.suse.de/tests/18293804#step/redis/69
The test module took `1m 26s`. then it makes sense to increase the timeout.

Increase timeout for redis test

---

.github/CODEOWNERS

- Related ticket: https://progress.opensuse.org/issues/176397
- Needles: no

Add Franta to qe-sec codeowners

---

lib/main_containers.pm

Extend the rootless docker test to SLES 15-SP4 & Leap
- Related ticket: https://bugzilla.opensuse.org/show_bug.cgi?id=1240150
- 15-SP4 docker x86_64: https://openqa.suse.de/tests/18316649
- 15-SP4 docker cgroupsv2 s390x: https://openqa.suse.de/tests/18317009
- 15-SP7 docker: https://openqa.suse.de/tests/18317267
- Verification runs (verify module is not scheduled):
- 12-SP5 docker: https://openqa.suse.de/tests/18317239
- 12-SP5 docker-stable: https://openqa.suse.de/tests/18317252
- 15-SP2 docker: https://openqa.suse.de/tests/18317262

containers: Extend the rootless docker test to SLES 15-SP4 & Leap

---

tests/microos/selfinstall.pm

Micro < 6.0 does an actual reboot to properly handle firstboot configuration. We already eject the disc once detecting that the reboot occurred, but it might be too late.
So, ensure we reboot again just in case.
Note: I'm not sure if there is a better way to that, please advice, thanks :smile: 
- Related ticket: https://progress.opensuse.org/issues/185239
- Verification run: https://openqa.suse.de/tests/18316537

microos: reboot again after ejecting cd on older Micro < 6.0

---

tests/installation/validation/ibft.pm

We have adapted IBFT on SLES16
- Related ticket: https://progress.opensuse.org/issues/181394
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/18313855#

Changed IBFT validation for SLE16

---

data/journal_check/bug_refs.json
lib/version_utils.pm
t/01_version_utils.t

Ticket https://progress.opensuse.org/issues/184861
VR: https://openqa.opensuse.org/tests/overview?distri=microos&version=Tumbleweed&build=20250703-systemd-boot&groupid=1
Follows #[22351](https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/22351)

Make systemd-boot new default bootloader in MicroOS

---

data/virt_autotest/host_unattended_installation_files/agama/sle16.jsonnet
tests/virt_autotest/login_console.pm

Set up br0 in agama where ssh reconnection is not required.
doc: https://github.com/aginies/virt-bridge-setup
ticket: https://progress.opensuse.org/issues/169900
https://openqa.suse.de/tests/18350545#step/login_console/28
https://openqa.suse.de/tests/18358861#step/login_console/28

Set up br0 with virt-bridge-setup tool

---

lib/qam.pm
schedule/qam/16/create_hdd_textmode_staging.yaml
tests/qam-minimal/install_update.pm

- Related ticket: https://progress.opensuse.org/issues/182918
- Verification run: https://openqa.suse.de/tests/overview?distri=sle&version=16.0&build=%3A155%3Ajq&groupid=656

Schedule tests for sle16 maintenance staging

---

tests/installation/agama_reboot.pm

According to `init_consoles` the correct tty for agama installer is 2, this PR avoids overwriting that default.
This change is needed after the switch to latest version of agama
Failure: https://openqa.opensuse.org/tests/5157600/#step/agama_reboot/21
VR: https://openqa.opensuse.org/tests/5157934
https://github.com/os-autoinst/os-autoinst-distri-opensuse/blob/8e15ace766f07ca5f3df9263cd49aefd237112b1/lib/susedistribution.pm#L488

Use correct tty in agama_reboot

---

lib/containers/bats.pm

Avoid SELinux hack on /tmp on suggestion by SELinux maintainers.
Fixes https://bugzilla.suse.com/show_bug.cgi?id=1245074
- SLE 16.0: https://openqa.suse.de/tests/18364885
- Tumbleweed: https://openqa.opensuse.org/tests/5158110 (failing due to transient network issues).

bats/buildah: Avoid SELinux hack on /tmp

---

lib/containers/bats.pm

Drop SELinux hack.
- SLE 16.0: https://openqa.suse.de/tests/18369598
- Tumbleweed: https://openqa.opensuse.org/tests/5158556

bats/podman: Drop SELinux hack

---

data/virt_autotest/host_unattended_installation_files/agama/sle16.jsonnet

virt-bridge-setup seems to having prblem. We need remove it to make our tests pass for RC2. I'll re-open the bug later.
Related ticket: https://progress.opensuse.org/issues/185443
https://openqa.suse.de/tests/18379819
https://openqa.suse.de/tests/18379981
@alice-suse @guoxuguang @waynechen55 @RoyCai7 @martinsmarcelo

Remove virt-bridge-setup from agama host installation

---

lib/main_containers.pm

Temporarily exclude rootless_docker test on PC until repo issues are fixed.
> the to be installed docker-rootless-extras-27.5.1_ce-150000.218.1.noarch requires 'docker = 27.5.1_ce', but this requirement cannot be provided

containers: Temporarily exclude rootless_docker test on PC

---

tests/microos/image_checks.pm

Re-introduce expected leftover settings for sle micro 6.1. `.*-64kb` flavors increased expected leftover sectors to 6144
- sle-micro-6.2-Base-64kb-aarch64-Build15.14-default@aarch64 -> https://openqa.suse.de/tests/18382651
- sle-micro-6.1-Base-SelfInstall-aarch64-Build26.83-default@aarch64 -> https://openqa.suse.de/tests/18382653
- sle-micro-6.2-Default-aarch64-Build15.14-slem_migration_6.1_to_6.2@aarch64 -> https://openqa.suse.de/tests/18383162

Increase expected leftover sectors in sle-micro

---

lib/Utils/Logging.pm
lib/consoletest.pm
lib/containers/basetest.pm
lib/hacluster.pm
lib/main_containers.pm
lib/sles4sap.pm
lib/x11test.pm
tests/console/perl_bootloader.pm
tests/ha/check_logs.pm
tests/ha/fencing.pm
tests/ha/qnetd.pm
tests/jeos/firstrun.pm

Check for AVCs and in case there any found, mark the test as failed if `AVC_FAIL_ON_DENIALS` is set.
It is expected this test will run on most of the user space tests and SELinux supported products, but for now run this code only in consoletests and container tests.
I had to re-arrange `rootless_podman` as after failure consequent tests were not recovering well from the openQA taken snapshot
- ticket: https://progress.opensuse.org/issues/182384
- [sle-16.0-Minimal-VM-for-kvm-and-xen](http://kepler.suse.cz/tests/25038)
- [microos-Tumbleweed-MicroOS-Image-ContainerHost](http://kepler.suse.cz/tests/25051#)
- [microos-Tumbleweed-MicroOS-Image](http://kepler.suse.cz/tests/25046#)
- [sle-16.0-Minimal-VM-for-kvm-and-xen](http://kepler.suse.cz/tests/25050#step/apache/2)
- …

Fail test in case of AVCs

---

tests/security/pam/pam_basic_function.pm
tests/security/pam/pam_config.pm
tests/security/pam/pam_faillock.pm
tests/security/pam/pam_login.pm
tests/security/pam/pam_mount.pm
tests/security/pam/pam_su.pm
tests/security/pam/pam_u2f.pm

This PR is for enabling the existing security_pam test suite for SLE 16.
A couple of tests are skipped. These are:
- pam_login
- pam_mount
The pam_login would rely on the pam_ssh module which was removed from SLE 16.
The pam_mount test would need the pam_mount module which is not included in the distro. The package is not even on the wishlist of SLE 16. We may get it later from Factory so that test could be re-enabled at some point.
- Related ticket
https://progress.opensuse.org/issues/183476
- Verification runs
SLE 16
x86_64 : https://openqa.suse.de/tests/18385728
aarch64: https://openqa.suse.de/tests/18385729
s390x  : FAILED -> problem with boot
ppc64  : FAILED -> agama_create_hdd_textmode_qesec is failing
SLE 15-SP7
x86_64 : https://openqa.suse.de/tests/18385562
aarch64: …

Enable security_pam tests for SLE>=16

---

schedule/ha/bv/pvm_ha_qdevice_node.yaml
schedule/ha/bv/pvm_ha_qnetd_server.yaml

This PR adds QDevice/QNetd with Diskless SBD Test Scenario on ppc64le on SLE16.
The new schedule file is based on `schedule/ha/bv/ha_qdevice_node.yaml` and `schedule/ha/bv/ha_qnetd_server.yaml`.
- Related ticket: https://jira.suse.com/browse/TEAM-10289
- Verification run: https://openqa.suse.de/tests/18362621 (The ticket specifies that the job does not need to pass -- create a ticket for future fixup is enough.)

Enable QDevice/QNetd with Diskless SBD Test Scenario on ppc64le

---

lib/containers/engine.pm
lib/main_containers.pm
tests/containers/host_configuration.pm

Tumbleweed's DVD|NET flavors remove the `quiet` kernel paramater from the image. Due to this, the console is polluted by container engines and block AVC or log retrievals.
* [opensuse-Tumbleweed-DVD-x86_64-Build20250709-containers_image](http://kepler.suse.cz/tests/25073#)
* [opensuse-Tumbleweed-DVD-x86_64-Build20250709-container_host_docker_apparmor](http://kepler.suse.cz/tests/25074#live)
* [opensuse-Tumbleweed-DVD-x86_64-Build20250709-container_host_docker_selinux + AVC_FAIL_ON_DENIALS=1](http://kepler.suse.cz/tests/25075)

Add quiet kernel option to container tests

---

lib/sles4sap/ibsm.pm
lib/sles4sap/ipaddr2.pm
lib/sles4sap/qesap/qesapdeployment.pm
t/09_qesapdeployment.t
t/35_ibsm.t
tests/sles4sap/publiccloud/qesap_terraform.pm
tests/sles4sap/qesapdeployment/configure.pm

Create a lib where to move the function to calculate the IP addresses ranges used for SUT peering to the IBSm.
- Related ticket: https://jira.suse.com/browse/TEAM-10275
- sle-15-SP6-Qesap-Azure-Payg-x86_64-BuildLATEST_AZURE_SLE15_6_PAYG-qesap_azure_ibsmirror_peering_test@64bit -> http://openqaworker15.qa.suse.cz/tests/332215 :green_circle: http://10.100.103.210//tests/332215
- sle-15-SP6-SapCloud-Azure-Payg-x86_64-BuildLATEST_AZURE_SLE15_6_PAYG-ipaddr2_azure_test_rootless@64bit -> https://openqa.suse.de/tests/18397118 :green_circle: 
- sle-15-SP6-Azure-SAP-BYOS-Incidents-x86_64-Build:39511:dtb-armv7l-SAPHanaSR-ScaleUp-PerfOpt@az_Standard_E4s_v3 -> http://openqa.suse.de/tests/18398781

Create a lib about IBSm

---

tests/security/pam/pam_faillock.pm

During the cleanup of the pam_faillock test the "userdel" command failed, because the user still had an active session. This session was the running test itself. It is safe to use the force flag here to remove the user, since this is where the test ends and there is no other test who would need that user. 
- https://progress.opensuse.org/issues/185518
SLE 16
- x86_64:  https://openqa.suse.de/tests/18398279
- aarch64: https://openqa.suse.de/tests/18398273
- s390x:   https://openqa.suse.de/tests/18398239
SLE 15-SP7
- x86_64:  https://openqa.suse.de/tests/18398240
- aarch64: https://openqa.suse.de/tests/18398243
- s390x:   https://openqa.suse.de/tests/18398241

Force user removal during cleanup in pam_faillock test

---

lib/main_micro_alp.pm
tests/support_server/login.pm

In https://openqa.opensuse.org/tests/5160456#step/login/6 the system is expecting systemd-boot when in reality
it should be grub2.
Additionally there's the change in the test schedule to avoid disabling grub timeout when actually the screen is different
Ticket: https://progress.opensuse.org/issues/184861 and https://progress.opensuse.org/issues/185395#note-3
VR: 
- With override: https://openqa.opensuse.org/tests/5163274
- Without override: https://openqa.opensuse.org/tests/5163278

Allow remote installations with different bootloaders

---

tests/fips/fips_setup.pm

Cherry picked from #22576
VR: https://openqa.opensuse.org/tests/5166634
Currently it will fail in the check, this is already reported as: https://bugzilla.opensuse.org/show_bug.cgi?id=1246013
openqa: Clone https://openqa.opensuse.org/tests/5162404
- **Use fips-mode-setup to validate FIPS setup**
- **Don't update bootloader config for microos either**

Use fips-mode-setup to validate FIPS setup on Microos

---

tests/sles4sap/ipaddr2/deploy.pm

Get the OS catalog image name from PC lib and so from PUBLIC_CLOUD_IMAGE_ID. Stop using custom CLUSTER_OS_VER.
Related: https://jira.suse.com/browse/TEAM-9961
- sle-15-SP6-SapCloud-Azure-Payg-x86_64-BuildLATEST_AZURE_SLE15_6_PAYG-ipaddr2_azure_test_rootless -> https://openqa.suse.de/tests/18405511 :green_circle: it fails as expected https://openqa.suse.de/tests/18405511#step/deploy/74
- sle-15-SP6-SapCloud-Azure-Payg-x86_64-BuildLATEST_AZURE_SLE15_6_PAYG-ipaddr2_azure_test_rootless explicitly setting  PUBLIC_CLOUD_IMAGE_ID=suse:sles-sap-15-sp6:gen2:latest  -> https://openqa.suse.de/tests/18405512 :green_circle:  `az vm create` get the catalog image set in the variable

Adopt get_image_id in ipaddr2 test

---

lib/usb.pm
tests/kernel/usb_drive.pm
tests/kernel/usb_nic.pm

Add a new library for working with USB devices which currently provides helper functions for reading a list of USB devices and checking device presence against `REQUIRED_USB_DEVICES` job setting. These functions are used by `usb_drive` and `usb_nic` kernel tests.
- Related ticket: https://progress.opensuse.org/issues/185398
- Needles: N/A
- SLE-16, expected devices present: https://openqa.suse.de/tests/18408278
- SLE-16, one device missing: https://openqa.suse.de/tests/18408277
- SLE-16, `REQUIRED_USB_DEVICES` not set: https://openqa.suse.de/tests/18408279
- SLE-15SP5, expected devices present: https://openqa.suse.de/tests/18408282
Note: None of the test modules are supposed to fail because of any missing devices alone.

Implement check for specific USB devices on SUT

---

lib/main_micro_alp.pm

- Related ticket: https://progress.opensuse.org/issues/184729
- Verification run: https://openqa.suse.de/tests/18408032
**Please ignore the failed module, it is known issue**
Changes for job group:
https://gitlab.suse.de/qe-core/qa-sle-functional-userspace/-/merge_requests/285

Move test from 'ppc-emu' workers to power10 kvm workers

---

tests/console/zypper_extend.pm

The packman repository aren't as consistant as it is for Leap and the
convenient test package funny-manpages is not available, for SLE it is
more convenient to keep using Leap repo than branching per-arch
Failure: https://openqa.suse.de/tests/18426048#step/zypper_extend/78
VR: https://openqa.suse.de/tests/18428466

Use openSUSE Leap 15.6 for SLES in zypper_extend test

---

schedule/functional/extra_tests_network_bonding.yaml

The test schedule doesn't add the required modules to ensure that the to-test snapshot is what's actually being tested.
[current](https://openqa.opensuse.org/tests/5173845#step/network_bonding_setup/106) failure shows an error fixed in the
to be tested snapshot.
VR: https://openqa.opensuse.org/tests/5174711 and https://openqa.opensuse.org/tests/5174710

Replace repos in Microos for bonding tests

---

schedule/filesystem/xfstests_micro_ppc.yaml
tests/xfstests/partition.pm

1. Run tests directly after SL Micro installation to avoid environment changes or duplication of config files
2. update partition.pm accordingly
- Related ticket: https://progress.opensuse.org/issues/185749
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/18446471

xfstests: Update xfstests scheduler for SL Micro

---

tests/console/sudo.pm

Update maintainer and documentation link
- Related ticket: https://progress.opensuse.org/issues/185731
https://openqa.suse.de/tests/overview?distri=sle&build=jpupava_sudo

sudo: Replace zypper/yast2 with visudo

---

lib/containers/bats.pm

Enable ncat repo for SLES 15 so we can run aarch64 jobs that depend on it.
- SLES 15-SP4:
- runc: https://openqa.suse.de/tests/18448085
- skopeo: https://openqa.suse.de/tests/18448086
- SLES 15-SP5:
- netavark: https://openqa.suse.de/tests/18448082
- runc: https://openqa.suse.de/tests/18448083
- skopeo: https://openqa.suse.de/tests/18448084
- SLES 15-SP6:
- netavark: https://openqa.suse.de/tests/18448088
- podman: https://openqa.suse.de/tests/18448089
- runc: https://openqa.suse.de/tests/18448209
- skopeo: https://openqa.suse.de/tests/18448091
- SLES 15-SP7:
- netavark: https://openqa.suse.de/tests/18448092
- podman: https://openqa.suse.de/tests/18448093
- runc: will be added when runc 1.2 hits official repos.
- skopeo: https://openqa.suse.de/tests/18448095

bats: Enable ncat repo for SLES 15

---

tests/kernel/blktests.pm

Some of the block tests run longer tests using fio and as such require longer time to finish
- Related ticket: https://progress.opensuse.org/issues/185881
- Verification run: https://openqa.suse.de/tests/18448473

blktests: Block section requires longer timeout

---

tests/containers/bats/podman.pm

Skip some tests on aarch64:
- 125-import due to https://bugzilla.suse.com/show_bug.cgi?id=1246607
- 180-blkio as this test is flaky on aarch64
Reference runs:
- 15-SP6: https://openqa.suse.de/tests/18448089
- 15-SP7: https://openqa.suse.de/tests/18448093
- 16.0: https://openqa.suse.de/tests/18447725 (expected failure)
- Tumbleweed: https://openqa.opensuse.org/tests/5175624 (expected failure)
Note: VR's not needed as we're removing the tests that make the tests fail on 16.0 & TW.

bats/podman: Skip some tests on aarch64

---

data/containers/bats/skip.yaml

Update BATS_SKIP for buildah with runc 1.2

bats/buildah: Update BATS_SKIP

---

lib/main_common.pm
schedule/functional/extra_tests_textmode.yaml
schedule/functional/leap16/agama_create_hdd_gnome_leap.yaml
schedule/functional/leap16/agama_create_hdd_textmode_leap.yaml
t/data/test_schedule.out
tests/console/opensuse_repos.pm

The openSUSE repos test is now updated to also remove the zypper service, so that https://progress.opensuse.org/issues/185863 doesn't happen
The test schedule has been updated to include the test by default, wherever console tests are being ran.
VR: 
- Leap 16 https://openqa.opensuse.org/tests/5177407
- Tumbleweed on aarch64 https://openqa.opensuse.org/tests/5177408
- Jeos x86 https://openqa.opensuse.org/tests/5177409

Schedule openSUSE repos test as early as possible

---

schedule/sles4sap/cloud-components/ipaddr2.yml
tests/sles4sap/ipaddr2/cluster_create.pm
tests/sles4sap/ipaddr2/configure.pm
tests/sles4sap/ipaddr2/deploy.pm
tests/sles4sap/ipaddr2/patch_system.pm
tests/sles4sap/ipaddr2/registration.pm

Reorganize how configuration steps are distributed across test modules. All registration steps are moved to test module named registration. Test module named configure only deal with ssh connection configuration. Web server installation is moved to cluster_create. The most important motivation of all these changes is in the YAML_SCHEDULE: now the difference between schedule for maintenance and non maintenance is minimal. Adopt POD documentation in IpAddr2 test modules.
Fix a bug for ipaddr2_refresh_repo.
sle-15-SP5-SapCloud-Azure-Byos-x86_64-BuildLATEST_AZURE_SLE15_5
- ipaddr2_azure_test -> https://openqaworker15.qa.suse.cz/tests/332682 :green_circle: 
- `SUSEConnect -s` https://openqaworker15.qa.suse.cz/tests/332682/logfile?filename=serial_terminal.txt#line-2510
- …

Reorganize IpAddr2 test modules and sequence

---

lib/containers/bats.pm

As observed in
https://openqa.suse.de/tests/18458486/logfile?filename=autoinst-log.txt
if BATS_SKIP is not defined there is a Perl warning about using
undefined values. This can be fixed by using join instead of a
manual string concatenation.
Related progress issue: https://progress.opensuse.org/issues/185953

lib: Prevent 'Use of uninitialized value' in bats module

---

lib/wsl.pm
schedule/wsl/wsl_main.yaml
tests/jeos/firstrun.pm
tests/wsl/distro_install.pm

WSL installation from Microsoft Store now has two installation methods. 
Legacy, which installs using yast-firstboot and Modern, which installs using jeos-firstboot. Both installation methods have to be tested. This PR is accompanied by a qac-openqa-yaml PR: https://gitlab.suse.de/qac/qac-openqa-yaml/-/merge_requests/2265
- Related ticket: https://progress.opensuse.org/issues/180704
SLES:
Win 10 Legacy: https://openqa.suse.de/tests/18462324
Win 10 Modern: https://openqa.suse.de/tests/18462703
Win 11 Legacy: https://openqa.suse.de/tests/18462702
Win 11 Modern: https://openqa.suse.de/tests/18462708
There is an issue regarding wsl installation in windows 10 for TW and Leap https://progress.opensuse.org/issues/185959 , therefore, for the time being I will propose merging …

Add modern WSL installation method from MSStore.

---

schedule/yam/agama_iscsi_activate_unattended.yaml
test_data/yam/iscsi_activation_non_root.yaml

##
- https://progress.opensuse.org/issues/183140
- Related MR:
- https://gitlab.suse.de/qe-yam/openqa-job-groups/-/merge_requests/523
- Needles: N/A
- [sles_iscsi_activation_non_root_unattended](https://openqa.suse.de/tests/overview?version=16.0&distri=sle&build=hjluo%2Fos-autoinst-distri-opensuse%23iscsi_partition_data)
##

Add test data for iscsi_activation_non_root

---

lib/sles4sap/ipaddr2.pm
tests/sles4sap/cloud_netconfig/deploy.pm

Drop usage of variable in cloud_netconfig test. Replace it with PC function get_image_id.
- Related ticket: https://jira.suse.com/browse/TEAM-10498
sle-15-SP7-SapCloud-Azure-Payg-x86_64-BuildLATEST_AZURE_SLE15_7-ipaddr2_azure_test_rootless
- http://openqaworker15.qa.suse.cz/tests/332830 :green_circle: 
sle-15-SP5-SapCloud-Azure-Byos-x86_64-BuildLATEST_AZURE_SLE15_5-cloud_netconfig_azure_test
- http://openqaworker15.qa.suse.cz/tests/332831 :red_circle: fails but after the changed code
- http://openqaworker15.qa.suse.cz/tests/332833 :red_circle: fails in registration as the previous one. Again result is better than without the code in the PR and not related to changed made here.
sle-15-SP5-SapCloud-Azure-Payg-x86_64-BuildLATEST_AZURE_SLE15_5-cloud_netconfig_azure_test
- …

Drop usage of CLUSTER_OS_VER variable.

---

tests/yam/validate/validate_connectivity.pm

- Related ticket: [poo#184043](https://progress.opensuse.org/issues/184043)
- Verification run: [overview](https://openqa.suse.de/tests/overview?build=issues-184043)
- Related [MR#524](https://gitlab.suse.de/qe-yam/openqa-job-groups/-/merge_requests/524) to merge first
Add "check" to refresh the status and "unknown" as output

Fix: add check to re-check the connectivity and unknow as output

---

lib/containers/urls.pm

Remove fedora image from 3rd party-images.
All our tests are failing for this image that takes long to download.

containers: Remove fedora image from 3rd party-images

---

lib/main_containers.pm

Skip flaky 3rd party image tests on public cloud.
When these images fail we must restart lots of tests that only increase our cloud bills.
Related ticket: https://progress.opensuse.org/issues/179566

containers: Skip flaky 3rd party image tests on public cloud

---

schedule/qam/common/mau-extratests1.yaml
tests/console/cron.pm
tests/console/mta.pm

- Related ticket: https://progress.opensuse.org/issues/185737
https://openqa.suse.de/tests/overview?distri=sle&build=jpupava_et1

cron mta: Run systemctl is active with script_retry

---

lib/containers/bats.pm

Increase timeout when installing packages
Failed test: https://openqa.suse.de/tests/18495514#step/podman/68

bats: Increase timeout when installing packages

---

data/containers/bats/patches/podman/24068.patch
data/containers/bats/skip.yaml

Backport https://github.com/containers/podman/pull/24068 to support new curl version in SLES 15.
- Failing job: https://openqa.suse.de/tests/18497547#external
- 15-SP6: https://openqa.suse.de/tests/18497979
- 15-SP7: https://openqa.suse.de/tests/18497980

bats/podman: Add PR#24068 to support new curl in SLES 15

---

lib/qam.pm
t/33_qam.t

Change `get_test_repos` function to filter out duplicates before returning, to avoid duplicate repo lists.
- Related ticket: https://jira.suse.com/browse/TEAM-10505
- Verification run: https://openqa.suse.de/tests/18475307
(failure unrelated to current pr, is due to https://jira.suse.com/browse/TEAM-10484 which will be fixed in a different pr). Check the serial terminal log and search for `-e repos`: unlike previous runs, repos appear only once.

Force get_test_repos() to return unique values

---

lib/main_common.pm

https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/22675
- Related ticket: https://progress.opensuse.org/issues/185974
- Verification run: https://openqa.suse.de/tests/18507016

zypper_in: Don't schedule broken opensuse_repos on maintenance

---

lib/main_containers.pm
tests/containers/registry.pm

This PR:
- Extends the podman artifact test to SLE 16.0 which uses podman 5.4.2
- Makes the registry module use only one engine instead of running both docker & podman
- Tumbleweed docker: https://openqa.opensuse.org/tests/5188561
- Tumbleweed podman: https://openqa.opensuse.org/tests/5188545
- SLES 16.0 docker: https://openqa.suse.de/tests/18508182
- SLES 16.0 podman: https://openqa.suse.de/tests/18508116

Extend podman artifact test to SLE 16.0

---

lib/main_containers.pm

Extend podman-remote test to SLES & Tumbleweed.  This package is available on SLES 15-SP3+
This module was limited to only SLEM 5.5+ likely by accident on https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/19697/
- Tumbleweed: https://openqa.opensuse.org/tests/5188842
- SLES 16.0: https://openqa.suse.de/tests/18508849
- SLES 15-SP3: https://openqa.suse.de/tests/18508854

containers: Extend podman-remote test on SLES & Tumbleweed

---

tests/containers/kubectl.pm

Limit scope of soft-failure for https://bugzilla.suse.com/show_bug.cgi?id=1245087 which is affecting only SLES 15-SP3 to SP5.
No soft-failures for 15-SP6+ on https://openqa.suse.de/group_overview/417

containers/kubectl: Limit scope of soft-failure for bsc#1245087

---

tests/yam/agama/agama_auto.pm

Fix code for SLE16 container host ppc64le create_hdd test, restoring the ppc64le condition, removed in PR#22611
- Related ticket: https://progress.opensuse.org/issues/185995
- create_hdd_agama_containers for ppc64le:
https://openqa.suse.de/tests/18509318
- sles_default_unattended__TEST__:
https://openqa.suse.de/tests/18473925

Fix code for SLE16 container host ppc64le create_hdd test

---

lib/main_containers.pm
tests/containers/podmansh.pm

Re-schedule podmansh test only on Tumbleweed.  This module was de-scheduled in https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/21941 due to the number of changes needed and problems in other products.  
- Verification run: https://openqa.opensuse.org/tests/5188900

containers: Schedule podmansh test only on Tumbleweed

---

lib/ipmi_backend_utils.pm
lib/main_common.pm
lib/registration.pm

Perl 5.42 introduces new warnings about possible precedence problems. It
seems we have three such cases where unusual combination of operators
were used. This commit uses common negative comparison operators instead
of negating the value of one comparison value in an equality or regex
check.

Fix possible precedence problem in conditions

---

lib/main_common.pm

Reverts os-autoinst/os-autoinst-distri-opensuse#22724 as #22726 has a fix for original repos being removed

Revert "Only schedule openSUSE repos test for TW and leap16+"

---

tests/publiccloud/run_ltp.pm

Use script_retry for git-clone to avoid test failures due to transient network issues.
- Failed test: https://openqa.suse.de/tests/18475732/#step/run_ltp/37

pc: Use script_retry for git-clone

---

test_data/yam/whole_disk_and_boot_unattended_aarch64.yaml

- It lturned out that the disk device order on aarch64 differs from the one on x86_64, so we need an extra test_data file for the aarch64 architecture.
- Related MR: https://gitlab.suse.de/qe-yam/openqa-job-groups/-/merge_requests/526
- VR: https://openqa.suse.de/tests/18524429

Fix for problems in sles_whole_disk_boot_unattended on aarch64

---

lib/sles4sap.pm

The ENSA2 test downloads the NW installation files from the NFS server defined in the job group settings. Sometimes the NFS server can get overloaded so we need at a minimum to increase the time out.
- Related Ticket: TEAM-10504
- Verification run: https://openqaworker15.qa.suse.cz/tests/333562#

Hotfix ensa2 test to use rsync and a bigger timeout to get assets

---

data/journal_check/bug_refs.json

White list issues, that are not supported in our HW or due to test configuration e.g. no secure boot testing
- Related ticket: https://progress.opensuse.org/issues/186014
- Verification run: sle-16.0-Minimal-VM-for-kvm-and-xen-ppc64le-Build29.4-minimalvm-kdump@ppc64le-p10 -> https://openqa.suse.de/tests/18525172

Whitelist power10 warnings and errors

---

lib/hacluster.pm
lib/sles4sap.pm
t/11_hacluster.t
tests/ha/check_after_reboot.pm

Create library function to test --list-options in crm_resource and crm_attribute.
Call the function as part of existing check_after_reboot test module.
The test will only taks place if the SUT has the supported crmsh installed, that is at least 5.0.0.
Add documentation and unit tests.
First commit only  changes arguments validation in hacluster, it not contain any functional changes.
It only has small cosmetic changes in hacluster lib and sles4sap. It removes importing of script_output_retry_check that is not used.
- Related ticket: https://jira.suse.com/browse/TEAM-10494
sle-16.0-Online-x86_64-Build119.1-ha_3nodes_supportserver@64bit-4gbram -> http://openqaworker15.qa.suse.cz/tests/333003
sle-16.0-Online-x86_64-Build119.1-ha_3nodes_node01@64bit-4gbram -> …

Check crm list-options

---

tests/kernel/run_kselftests.pm

- Related ticket: https://progress.opensuse.org/issues/182360
- also: https://progress.opensuse.org/issues/186083
initial: https://rmarliere-openqa.qe.prg2.suse.org/tests/1336
additional on OSD: https://openqa.suse.de/tests/18533847
This PR shall be merged only after this merged and deployed: 
https://github.com/os-autoinst/openQA/pull/6597

kselftests: Use KTAP parser

---

lib/containers/container_images.pm

Tweak curl retry options to give containers time to start
- Related ticket: https://progress.opensuse.org/issues/186185
- Failed test: https://openqa.suse.de/tests/18533509/modules/image_docker/steps/233
- Verification run: https://openqa.suse.de/tests/18534068

containers: Tweak curl retry options to give containers time to start

---

tests/containers/registry.pm

Avoid specifying small delay inherited by blind translation of script_retry arguments
Failed tests:
- docker: https://openqa.opensuse.org/tests/5192519#step/docker_registry/14
- podman: https://openqa.opensuse.org/tests/5192524#step/podman_registry/1
- docker: https://openqa.opensuse.org/tests/5193065
- podman: https://openqa.opensuse.org/tests/5193066

containers: Use --retry-all-errors with curl

---

lib/containers/container_images.pm

Avoid --retry-all-errors on SLEM < 5.3
`curl: option --retry-all-errors: is unknown`.
Failed test: https://openqa.suse.de/tests/18540601#step/podman/226

containers: Avoid --retry-all-errors on SLEM < 5.3

---

lib/sles4sap/azure_cli.pm
lib/sles4sap/qesap/qesapdeployment.pm
t/15_qesap_azure.t
t/21_sles4sap_azure_cli.t

Refine two azure_cli API: az_validate_uuid_pattern and az_storage_lease_acquire by defining some additional unit tests and improving the documentation. 
- Ticket [TEAM-10465](https://jira.suse.com/browse/TEAM-10465) - [SDAF] Fix network space assignment logic
- sle-15-SP5-Azure-SDAF-PAYG-x86_64-Build15-SP5 -> https://openqaworker15.qa.suse.cz/tests/333702
- sle-15-SP6-Qesap-Azure-Payg-x86_64-BuildLATEST_AZURE_SLE15_6_PAYG-qesap_azure_saptune_test_msi@64bit -> http://openqaworker15.qa.suse.cz/tests/333692
- sle-15-SP6-HanaSr-Azure-Byos-x86_64-Build15-SP6_2025-07-22T02:03:21Z-hanasr_azure_test_msi@az_Standard_E4s_v3 -> http://openqaworker15.qa.suse.cz/tests/333693

Refine az_validate_uuid_pattern API

---

tests/kernel/ibtests.pm

Previously, hpc-testing for InfiniBand had default values for the IP address configuration of IPoIB interfaces. This default went away, so we need to specify these. They are variables to allow overriding in case we need it, but they should only be used internally for the test suite and not be of relevance outside of this - just make it show the old behavior again.

Adapt to new behaviour of hpc-testing

---

tests/ha/iscsi_client_setup.pm

iSCSI breaks on SLE16 because there is already an initiator name assigned to the SUT that is not necessarily unique after the installation. This forces its regeneration.
- Related Ticket: TEAM-10412
- Verification run: [pacemaker](https://openqaworker15.qa.suse.cz/tests/333725)

Force regeneration of new initiator name for iscsi

---

tests/ha/fencing.pm

Current test on svirt backend will loop for a long time until timeout is reached: https://openqa.suse.de/tests/17638845#step/fencing/620
That is because the matched needle `root-console` is not accurate -- it is matching old lines instead of new lines.  So I added `clear` to avoid matching old lines and use a more accurate needle `cleared-console`.
- Related ticket: https://jira.suse.com/browse/TEAM-10360
s390x (fence by sysrq): https://openqa.suse.de/tests/18533591#step/fencing/21
x86 (fence by crm): https://openqa.suse.de/tests/18535441#step/fencing/28

Avoid useless looping in ha/fencing.pm for powervm/s390x

---

tests/console/systemd_rpm_macros.pm

In factory only few sources are synced but moreover the coverage
provided by the test is already sufficient to know that RPM is able to
expand systemd macros
Pulling assets from already published assets instead of the assets to be tested is also problematic
Failure: https://openqa.opensuse.org/tests/5195001#step/systemd_rpm_macros/27

Drop test build of multipath-tools for Tumbleweed

---

data/journal_check/bug_refs.json

- Verification run: [slem_migration_6.1_to_6.2](https://openqa.suse.de/tests/overview?build=leo-test-2025-07-25)

Fix: add "sle-micro: 6.2" in bug_ref for dracut-no-logger

---

lib/containers/container_images.pm
tests/containers/registry.pm

Drop curl `--retry-all-errors` option.
This option is not available in older curl versions and `--retry 10` has been working fine on older SLES & SLEM.
Supersedes https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/22774

containers: Drop curl --retry-all-errors option

---

lib/containers/container_images.pm
tests/containers/registry.pm

Increase number of curl retries.
The current number is not enough for FIPS tests and tests with only one vCPU
Failed tests:
- https://openqa.suse.de/tests/18568757#step/image_docker/233 (as usual a FIPS test.  It seems that Golang linked with OpenSSL as required by FIPS is VERY slow).
- https://openqa.opensuse.org/tests/5198859#step/docker_registry/17 (also needs `QEMUCPUS=2`)
- https://openqa.suse.de/tests/18569474 (still failing).
- https://openqa.opensuse.org/tests/5199492

containers: Increase number of curl retries

---

schedule/yam/agama_alert_popup.yaml
tests/yam/agama/agama.pm
tests/yam/agama/boot_agama.pm

Add test in puppeteer to verify the alert popup shown.
- Related ticket: https://progress.opensuse.org/issues/185704
- Related PR: https://github.com/jknphy/agama-integration-test-webpack/pull/124
- Needles: N/A
https://openqa.suse.de/tests/18546327#details x86_64
https://openqa.suse.de/tests/18546326#details aarch64

Test alert informing the user that Agama could not fetch the profile

---

schedule/qam/common/mau-extratests2.yaml
tests/console/valkey.pm

https://progress.opensuse.org/issues/182654
1. Add coverage for sle15sp6/sp7
2. Add some required parameters when generating the ca cert file. [or the cert file is not recognized on sle15sp6]
[sle15sp6/sp7](https://openqa.suse.de/tests/overview?build=rfan0725&distri=sle)
[sle16](http://openqa.suse.de/tests/18576941)
[tw](https://openqa.opensuse.org/tests/5203046)

Schedule valkey test on sle15sp6 and sle15sp7

---

lib/containers/container_images.pm
tests/containers/registry.pm

Increase curl --retry for FIPS tests
- Related ticket: https://progress.opensuse.org/issues/186391
- Failed test: https://openqa.suse.de/tests/18575614#step/image_docker/233
- https://openqa.suse.de/tests/18577925
- https://openqa.opensuse.org/tests/5203959 (needs https://github.com/os-autoinst/opensuse-jobgroups/pull/697)

containers: Increase curl --retry for FIPS tests

---

tests/kernel/io_uring.pm

A few minor enhancements plus a fix for the timeouts which should not softfail but fail instead. 
- Related ticket: https://progress.opensuse.org/issues/186405
sle16: passing: https://openqa.suse.de/tests/18577954
sle15sp7: https://openqa.suse.de/tests/18577976 - with catching the failed tests
TW: https://openqa.opensuse.org/tests/5203956 - with catching the failed tests
I know those  2 lops     # search for timed out tests and     # search for failed tests and known issues are awfully similar. If you prefer I can try to move it to  a function or combine it into a single loop searching for both failed tests and timeouts but I simply kept the original code just fixed the issues.

io_uring: Print the last commit

---

data/wsl/Autounattend_UEFI.xml

There's a new "experience" called 'Welcome to Edge' that is shown up the first time you open the Microsoft Edge explorer. Nevertheless, Microsoft has decided to show this screen also the first time we open our WSL distro, so we will disable it via Registry Keys
- Related ticket: https://progress.opensuse.org/issues/186290
- Verification run: (tried on my own VM)

New regkey in autounattend to disable 'Welcome to Edge' screen

---

tests/sles4sap/redirection_tests/ensa2_kill_sapinstance.pm

Test variants 'Kill sapinstance ASCS' contain currently a sporadic issue
with ASCS resource kill process does not reach expected state. Test 
only waits for failcount to appear instead of stabilizing before 
further actions. This PR corrects this behavior.
Ticket: https://jira.suse.com/browse/TEAM-10495
1st round:
15SP4: https://openqaworker15.qa.suse.cz/tests/334110#
15SP5: https://openqaworker15.qa.suse.cz/tests/334113#
15SP6: https://openqaworker15.qa.suse.cz/tests/334116#
2nd round
15SP4: https://openqaworker15.qa.suse.cz/tests/334267#
15SP5: https://openqaworker15.qa.suse.cz/tests/334270#
15SP6: https://openqaworker15.qa.suse.cz/tests/334278#

Fix sporadic issue with ASCS kill sapoinstance tests

---

tests/containers/registry.pm

Fix registry test
We can't rely on curl --retry because we can't use the more recent set of --retry-xxx options as they're not available on older products.
- Related ticket: https://progress.opensuse.org/issues/186391
- Failed test: https://openqa.suse.de/tests/18589675#step/docker_registry/17
- Verification run: https://openqa.suse.de/tests/18591171

containers: Fix registry test

---

tests/containers/firewall.pm

Fix missing validate_script_output_retry
Failing test: https://openqa.suse.de/tests/18592773#step/podman_firewall/52

containers: Use whole utils module

---

tests/containers/buildah.pm

As observed in two jobs of today refreshing repos and installing
packages can run into timeout while the operation is still ongoing. I
assume that a high workload in the overall system causes this when
multiple jobs run in parallel stressing the network infrastructure.
Related progress issue: https://progress.opensuse.org/issues/186522

buildah: Try to fix timeouts on slow repo load

---

lib/containers/common.pm

It is reasonable to assume that a container image pull can take longer
than the default 30s timeout. This was observed in at least one case
where the download was only finished by about 30% during a time when SLE
aggregate tests were running in a bunch explaining the slower download
speed.
Related progress issue: https://progress.opensuse.org/issues/186555

containers: Fix container pull on slow network transfers

---

tests/console/zypper_ar.pm

Follows #22809
- **Update leftover OSS_DEBUGINFO to OSS_DEBUG**
- **Sync Leap and Factory variables**
Needs to be merged with https://github.com/os-autoinst/openqa-trigger-from-obs/pull/311
VR (manually set REPO_OSS_DEBUG): https://openqa.opensuse.org/tests/5207495#step/kdump_and_crash/8

Update leftovers from #22809

---

tests/kernel/run_kselftests.pm

Initial idea was simple: use known_issues approach from the LTP. Specifically: lib/WhiteList.pm.
There are however very specific caveats when it comes to the kernel selftests.
Kernel selftests do not support test exclusion. Basically there are following options in the upstream:
```
-t | --test COLLECTION:TEST	Run TEST from COLLECTION
-c | --collection COLLECTION	Run all tests from COLLECTION
```
Tests are often compiled binaries. Those are called TEST looking at the example above. So COLLECTION:TEST is - for instance - cgroup:test_core where test_core is a binary containing 12 individual tests
Openqa kselftestrunner works in the way that the tap output file is parsed and KTAP.pm parser is used to produce the openQA result view for each individual test however runner can't run …

Kselftests: Improvements for -t native flag as well as known_issues

---

lib/containers/common.pm

Use serial terminal instead of root-console in container tests.
- Related ticket: https://progress.opensuse.org/issues/186561
- Verification run: https://openqa.suse.de/tests/18605717

containers: Use serial console to avoid poo#186561

---

data/virt_autotest/virt_logs_collector.sh

* **SELINUX** causes extreme long time of logs collecting by supportconfig, which further leads to timed-out logs collecting. 
* **Excluding** SELINUX from logs collecting is better for test runs.
* [successful run](https://openqa.suse.de/tests/18603819)
* [failed run/selinux skipped during logs collecting](https://openqa.suse.de/tests/18603409)

Exclude SELINUX from supportconfig logs

---

lib/main_common.pm
tests/kernel/update_kernel.pm

We need to use IPXE for bare metal maintenance testing on OSD. We never used this scenario and existing code didn't create automatic test module schedule as it should. 
IPXE support is already handled in load_boot_tests(). The previous
condition was creating a non-functional installation schedule. Since
load_reboot_tests() explicitly excludes IPXE, we need to handle the
first boot separately. 
kernel-64kb testing was using test module designed for product development. This was working fine, but we should use same approach as for other kernel flavors. kernel-64kb is fully supported by update_kernel.
There is a difference to PXE installations. We need to use autoyast, which sets higher grub timeout. Non OSD PXE jobs relies on timeout provided by PXE boot menu.  It doesn't work well with …

kernel: Improve baremetal maintenance testing over IPXE

---

tests/sles4sap/hana_install.pm

For Minimal-VM-Cloud-sap, / direcotry uses xfs, the job will fail in `assert_script_run 'test -d /.snapshots && restorecon -R / -e /.snapshots';` because there is no `/.snapshots`, the whole command will return `1`. So change the handling logic.
Related: https://jira.suse.com/browse/TEAM-10503
VRs:
https://openqa.suse.de/tests/18612487#step/hana_install/219  (Failed as expected)
https://openqa.suse.de/tests/18612488#  (Passed with init.d workaround)
For sles sap 16.0:
https://openqa.suse.de/tests/18612489# (passed with init.d workaround)

Modify the way of running restorecon when installing hana

---

tests/x11/firefox_audio.pm

https://progress.opensuse.org/issues/186585
- Verification run: https://openqa.suse.de/tests/overview?distri=sle&build=rfan0731_2&version=15-SP7
-  Needle: Added via openQA webUI
The job https://openqa.suse.de/tests/18613307#step/firefox_audio/7 can prove it works

Play audio file if it is not played automatically

---

tests/jeos/firstrun.pm

WSL Tumbleweed contains only glibc-locale-base locale package, which only contains English locale, and therefore we have no locale choices during installation.
We need to remove jeos-locale checks for Tumblweed installations to allow the tests to proceed.
- Related ticket: https://progress.opensuse.org/issues/186552
✅ Leap: Checks for system locale  https://openqa.opensuse.org/tests/5209641#step/firstrun/7
✅ TW:  Does not check for system locale https://openqa.opensuse.org/tests/5209642#step/firstrun/6
✅ SLES: Checks for system locale https://openqa.suse.de/tests/18613747#step/firstrun/5
✅ Minimal VM jeos-main: works as expected:  https://openqa.suse.de/tests/18613929

Remove jeos-locale needle check for WSL Tumbleweed

---

tests/sles4sap/sap_deployment_automation_framework/configure_deployer.pm

Current tests lack screen which would present terraform version being used. This PR adds a 'record_info' screen showing it in results.
Ticket: https://jira.suse.com/browse/TEAM-10523
https://openqaworker15.qa.suse.cz/tests/334968#step/configure_deployer/299

SDAF Show terraform version

---

tests/microos/services_enabled.pm

agetty gained the functionality to print issue files directly
- Related ticket: N/A (related to https://build.opensuse.org/requests/1296560)
- Needles: N/A
- Verification run: https://openqa.opensuse.org/tests/5209953 ![VR](https://openqa.opensuse.org/tests/5209953/badge)

microos: no longer expect issue-generator to be running

---

tests/yam/agama/agama_auto.pm

To fix issue: https://openqa.suse.de/tests/18605832#step/agama_auto/30
The issue is caused by the changes in [PR#22721](https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/22721/files), I add a condition for desktop setting.
Verification run:  
- sles_gnome_unattended: https://openqa.suse.de/tests/18624215
- create_hdd_textmode: https://openqa.suse.de/tests/18624216
- installation without DESKTOP setting:  https://openqa.suse.de/tests/18624219

Add a condition for sle16 ppc64le gnome testing

---

schedule/functional/sle16/extra_tests_textmode2.yaml
schedule/functional/stack_tests_python.yaml
schedule/qam/common/mau-extratests1.yaml
tests/console/rabbitmq.pm

python3-pika not found on SLE16 https://dzedro.suse.cz/tests/2881#step/rabbitmq/23
-use serial terminal
-use go instead of python, python3-pika not found on SLE16
-no reason to schedule test on stack_tests_python with python3-pika or without
- Related ticket: https://progress.opensuse.org/issues/182075
- Verification run: https://openqa.suse.de/tests/overview?distri=sle&build=jpupava_rabbitmq

rabbitmq: Enable on SLE16 & update

---

tests/containers/rootless_docker.pm

Use serial terminal instead of console.
- Related ticket: https://progress.opensuse.org/issues/186669
- Failed job: https://openqa.suse.de/tests/18612550#step/rootless_docker/155
- Verification run: https://openqa.suse.de/tests/18625001

containers: Use serial terminal instead of console to fix poo#186669

---

schedule/functional/extra_tests_textmode.yaml
schedule/functional/sle16/extra_tests_textmode.yaml
schedule/qam/common/mau-extratests1.yaml
tests/console/tcpdump.pm

Verify tcpdump by pinging a localhost and dumping with an icmp filter.
- Related ticket: https://progress.opensuse.org/issues/183911
- Needles: No
15-SP7: [x86_64](http://openqa.suse.de/tests/18604395#step/tcpdump/5) | [s390x](http://openqa.suse.de/tests/18604562#step/tcpdump/5) | [aarch64](http://openqa.suse.de/tests/18604561#step/tcpdump/5)
15-SP6:  [x86_64](http://openqa.suse.de/tests/18604567#step/tcpdump/5) | [s390x](http://openqa.suse.de/tests/18604566#step/tcpdump/5) | [aarch64](http://openqa.suse.de/tests/18604563#step/tcpdump/5)
15-SP5:  [x86_64](http://openqa.suse.de/tests/18604572#step/tcpdump/5) | [s390x](http://openqa.suse.de/tests/18604571#step/tcpdump/5) | [aarch64](http://openqa.suse.de/tests/18604568#step/tcpdump/5) …

add a new test to verify tcpdump

---

lib/haclusterbasetest.pm

In 30e1f5ef9174569b3b40a9c9480eea5819480eca we introduced AVC collection on SLES for SAP and HA tests on SLE 16.0. This was however temporarily removed in f9c0378c9767f9e1ed47366a530b0ee2dd980606 for HA tests.
In the meantime, we introduced a base class for HA tests in bf9b2109cb50f6a11ad8c1f831cd3ba5c11aa2ae, so we can reeanable AVC collection in HA test more cleanly.
This commit does it.
- Needles: N/A
- Verification run: http://mango.qe.nue2.suse.org/tests/7048, http://mango.qe.nue2.suse.org/tests/7047, http://mango.qe.nue2.suse.org/tests/7045, http://mango.qe.nue2.suse.org/tests/7044, http://mango.qe.nue2.suse.org/tests/7042, http://mango.qe.nue2.suse.org/tests/7050, http://mango.qe.nue2.suse.org/tests/7049
- P.S.: 2 node failure in `drbd_passive` is expected. …

Collect SELinux AVCs in HA tests

---

tests/containers/install_updates.pm

Drop soft-failure for https://bugzilla.suse.com/show_bug.cgi?id=1238784 as it was fixed.

containers: Drop soft-failure for bsc#1238784

---

tests/transactional/enable_selinux.pm

Drop soft-failure for https://bugzilla.suse.com/show_bug.cgi?id=1211917 which is fixed for SLEM 5.4:
https://openqa.suse.de/tests/overview?distri=sle-micro&version=5.4&build=20250731-1&groupid=420

containers: Drop soft-failure for bsc#1211917

---

data/sles4sap/fetch_file.yaml

Change the playbook used by qesap to download logs:
- Print the file size before to download it
- Download using ansible.posix.synchronize
- Related ticket: https://jira.suse.com/browse/TEAM-10543
sle-15-SP7-Qesap-Azure-Payg-x86_64-BuildLATEST_AZURE_SLE15_7_PAYG-qesap_azure_saptune_test_msi
- http://openqaworker15.qa.suse.cz/tests/335259 :green_circle: here how it looks like in action http://openqaworker15.qa.suse.cz/tests/335259/logfile?filename=serial_terminal.txt#line-28063
sle-15-SP6-HanaSr-Aws-Payg-x86_64-Build15-SP6_2025-08-01T02:03:22Z-hanasr_aws_test_fencing_native_baremetal ec2_r5b.metal
-  http://openqaworker15.qa.suse.cz/tests/335260

Change the fetch file playbook

---

schedule/functional/sle16/agama-create-hdd-textmode_pvm.yaml

https://progress.opensuse.org/issues/186459
- Verification run: https://openqa.suse.de/tests/18654402#
As discussed offline, I will file another PR for function `shutdown_pvm_hmc`, and this one should only focus on shutdown the setup after successfully run

Shutdown PVM setup when test completes

---

schedule/yam/agama.yaml
schedule/yam/agama_unattended.yaml
tests/yam/validate/validate_snapshot.pm

We have added a validation that check if after install snapshot is present or not.
- Related ticket: https://progress.opensuse.org/issues/185356
- Needles: N/A
- unattended: https://openqa.suse.de/tests/18604767
- interactive: https://openqa.suse.de/tests/18604770

Ensure creation of the "after install" snapshot was removed

---

lib/publiccloud/utils.pm

Use the table from registration library to get the name of the variable that is supposed to store the registration code associated to the selected addons.
- Related ticket: https://jira.suse.com/browse/TEAM-10547
- sle-15-SP5-Azure-BYOS-Hardened-Incidents-Ext-x86_64-Build:39880:cloud-regionsrv-client-publiccloud_img_proof az_Standard_B2s -> http://openqaworker15.qa.suse.cz/tests/335668
sle-12-SP5-Azure-SAP-BYOS-Incidents-saptune-x86_64-Build:39881:cloud-regionsrv-client-sles4sap_gnome_saptune_delete_rename az_Standard_E4s_v3  with `PUBLIC_CLOUD_SCC_ENDPOINT=SUSEConnect` and LTSS-ES
- http://openqaworker15.qa.suse.cz/tests/335296 :green_circle: 
- http://openqaworker15.qa.suse.cz/tests/335660 registration command is at http://openqaworker15.qa.suse.cz/tests/335660#step/registration/22 and …

Use ADDONS_REGCODE to get the variable name

---

lib/main_containers.pm

This reverts commit dbb4a1dda244c2dcd728174cc54855cf2c65a73b.
Needed CONTM repositories added to PC jobs
- Related ticket: https://progress.opensuse.org/issues/185512

Revert "containers: Temporarily exclude rootless_docker test on PC"

---

lib/publiccloud/instance.pm

Publiccloud instances in the phase checking VM that is up, remove the threshold limiting the expected-IP check to be triggered 30sec before timeout only: now it is always performed.
See also the note in https://progress.opensuse.org/issues/186717#note-5
Also, in case of IP **different**, a **red** box is reported in the job details boxes.
- Related ticket: poo#[186717](https://progress.opensuse.org/issues/186717)

P.C. wait_for_ssh: remove the threshold limiting the IP check

---

data/autoyast_hanaperf/agama-config.jsonnet

there is a incorrect kernel cmdline "security=" when NOT installing `selinux` pattern, here is the issue:
http://openqa.qa2.suse.asia/tests/85640#step/install_qatestset/10
for the details, please refer to
https://bugzilla.suse.com/show_bug.cgi?id=1247046#c20
https://bugzilla.suse.com/show_bug.cgi?id=1247046#c21
this comment explained why we need to add selinux pattern in agama jsonnet:
https://bugzilla.suse.com/show_bug.cgi?id=1247046#c5
- Related ticket: https://bugzilla.suse.com/show_bug.cgi?id=1247046
http://openqa.qa2.suse.asia/tests/86016

Add selinux pattern in agama jsonnet file because of bsc#1247046

---

data/kernel/post_process
tests/kernel/blktests.pm

Support various transports for the NVMe tests
- Related ticket: https://progress.opensuse.org/issues/186636
- VRs:
transport: rdma&fc: https://openqa.suse.de/tests/18673401 (quite some known and reported failures)
transport rdma: https://openqa.suse.de/tests/18673403 (all tests passing)
default transport: https://openqa.suse.de/tests/18673404 (one failed, bug reported)

Blktests trtypes

---

lib/containers/bats.pm
tests/containers/bats/runc.pm

This PR:
- Changes the OBS repo so we can get the latest git for ppc64le & s390x
- Fixes the runc test to work-around https://bugzilla.suse.com/show_bug.cgi?id=1247567
- Fixes the runc test to work-around https://bugzilla.suse.com/show_bug.cgi?id=1247568
Related MR: https://gitlab.suse.de/qac/qac-openqa-yaml/-/merge_requests/2380
- ppc64le:
- sle-16.0: https://openqa.suse.de/tests/18673559
- Tumbleweed: https://openqa.opensuse.org/tests/5221586
- s390x:
- sle-16.0: https://openqa.suse.de/tests/18673480
- sle-15-SP7: https://openqa.suse.de/tests/18673481
- sle-15-SP6: https://openqa.suse.de/tests/18673482
- sle-15-SP5:  https://openqa.suse.de/tests/18673484
- sle-15-SP4: https://openqa.suse.de/tests/18673485

Fix runc BATS tests on ppc64le & s390x

---

schedule/yam/agama.yaml
schedule/yam/agama_from_usb.yaml
schedule/yam/agama_ppc64le.yaml
schedule/yam/agama_remote_s390x.yaml
schedule/yam/agama_s390x.yaml
schedule/yam/agama_unattended.yaml
test_data/yam/agama_sap.yaml
test_data/yam/agama_sle.yaml
tests/console/validate_repos.pm
tests/yam/validate/validate_product.pm

Add more validations for the output of /etc/os-release for both sles and sap default installations.
- [Related ticket](https://progress.opensuse.org/issues/185404) 
- [Verification run](https://openqa.suse.de/tests/overview?version=16.0&distri=sle&build=chcao_185404_2)
- [Related mr](https://gitlab.suse.de/qe-yam/openqa-job-groups/-/merge_requests/525)

Add more validations for the output of /etc/os-release

---

tests/containers/bats/README.md
tests/containers/bats/buildah.pm
tests/containers/bats/runc.pm

We removed the PackageHub dependency in a previous PR but the `qemu-linux-user` used in the buildah tests is only available on SLES 15 on PackageHub.
- Failed tests:
-  https://openqa.suse.de/tests/18683477#step/buildah/60
- https://openqa.suse.de/tests/18683478#step/buildah/60

Limit qemu-linux-user package to SLES 16.0 & Tumbleweed.

---

lib/containers/bats.pm
tests/containers/bats/buildah.pm
tests/containers/bats/skopeo.pm

If we drop the `qemu-linux-user` dependency for the buildah upstream tests, then we would have to ignore the [bud](https://github.com/containers/buildah/blob/main/tests/bud.bats) test and this is something we can't afford given that it's the one of the most important tests.

Use PackageHub in BATS tests again

---

lib/sles4sap/ipaddr2.pm

SSH debug output in the ipaddr2 lib is now written to the logs, instead filling up the serial_terminal, so it';s now much more readable.
- Related ticket: https://jira.suse.com/browse/TEAM-10500
- https://openqaworker15.qa.suse.cz/tests/336013

Cloud ipaddr2 lib ssh debug output is now logged to file instead written to stdout

---

lib/sles4sap/ipaddr2.pm
t/22_ipaddr2.t
tests/sles4sap/ipaddr2/cluster_create.pm
tests/sles4sap/ipaddr2/configure.pm
tests/sles4sap/ipaddr2/deploy.pm
tests/sles4sap/ipaddr2/destroy.pm
tests/sles4sap/ipaddr2/network_peering.pm
tests/sles4sap/ipaddr2/patch_system.pm
tests/sles4sap/ipaddr2/registration.pm
tests/sles4sap/ipaddr2/sanity_cluster.pm
tests/sles4sap/ipaddr2/sanity_os.pm

Rename functions to all use same convention ipaddr2_<object>_verb Use constant for the user
Improve POD documentatio
Create cluster version function
- Related ticket: https://jira.suse.com/browse/TEAM-10496
sle-15-SP7-SapCloud-Azure-Payg-x86_64-BuildLATEST_AZURE_SLE15_7-ipaddr2_azure_test_rootless
- https://openqaworker15.qa.suse.cz/tests/336017 :green_circle: 
- http://openqaworker15.qa.suse.cz/tests/336041 :green_circle: 
- http://openqaworker15.qa.suse.cz/tests/336042 :green_circle: 
sle-15-SP5-SapCloud-Azure-Payg-x86_64-BuildLATEST_AZURE_SLE15_5-ipaddr2_azure_test_cloud_init
- http://openqaworker15.qa.suse.cz/tests/336027 :green_circle: 
sle-12-SP5-SapCloud-Azure-Payg-x86_64-BuildLATEST_AZURE_SLE12_ …

Generic code improvement in ipaddr2 lib

---

lib/publiccloud/instance.pm

In `wait_for_ssh` a systemctl check returning **`degraded`** after startup, implies more checks to extract the output of eventual failures. 
The `$sysout` string contains the full `systemctl` output, then also eventual failed message, that detected, we format the record_info result to be 'fail' otherwise normal, ok.
`WAIT CHECK` record_info now points out issue in RED/fail outline, for eventual post-failure analysis, if the test fails.
This feature can be explained with this _failed_ test (from [1247382](https://bugzilla.suse.com/show_bug.cgi?id=1247382)): 
if we had this feature active in  [prepare_instance/367](https://openqa.suse.de/tests/18598767#step/prepare_instance/367) (that is [L452](https://github.com/os-autoinst/os-autoinst-distri-opensuse/blob/ed30102466309b90e6720b192b357b0aeb …

P.C. system restart: WAIT CHECK highlights eventual failures

---

lib/main_containers.pm

Reverting https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/22863
Skip rootless_docker on public cloud.
Failing test: https://openqa.suse.de/tests/18679773#step/rootless_docker/79

containers: Skip rootless_docker on public cloud

---

lib/containers/bats.pm

Since the introduction of `collect_coredumps` we notice that some tests are generating core files, which needs investigation, and they take up some storage space.  Use `xz` instead of `gzip` to do faster multi-threaded compression and achieve 20% size reduction in core files.  Also use a predictable `core` prefix to easily find them in the `Logs & Assets` tab.

bats: Use xz to compress coredump and use a prefix for the name

---

lib/sles4sap/sap_deployment_automation_framework/deployment.pm

There are sporadic issues in cleanup module happening on Azure. According to MS, those are caused by Azure infrastructure as such and they recommended increasing sleep between cleanup retriess. This PR increases sleep to 2 min.
Ticket: No ticket
Original failure:
https://openqaworker15.qa.suse.cz/tests/336143/#step/cleanup/164
VR: https://openqaworker15.qa.suse.cz/tests/336215#live

SDAF extend delay between cleanup retries

---

lib/sles4sap/console_redirection/redirection_data_tools.pm
lib/sles4sap/database_hana.pm
lib/sles4sap/sap_deployment_automation_framework/deployment.pm
lib/sles4sap/sap_host_agent.pm
schedule/sles4sap/sap_deployment_automation_framework/sdaf_deployment.yml
t/20_sdaf_deployment_library.t
t/31_sap_host_agent.t
t/32_database_hana.t
t/36_redirection_data_tools.t
tests/sles4sap/redirection_tests/check_ensa2_cluster.pm
tests/sles4sap/redirection_tests/check_hana_database.pm
tests/sles4sap/redirection_tests/check_netweaver.pm
tests/sles4sap/sap_deployment_automation_framework/execute_playbooks.pm

Test modules use currently data from inventory file which is not a source with current data. This PR moves data sourcing from actual system information instead.
**Ticket:** https://jira.suse.com/browse/TEAM-10470
**Verification run:** 
**HanaSR:**  https://openqaworker15.qa.suse.cz/tests/336018#step/check_hana_database/161
**HanaSR SBD:** https://openqaworker15.qa.suse.cz/tests/336029#step/check_hana_database/168
**ENSA2:** https://openqaworker15.qa.suse.cz/tests/336209#step/check_ensa2_cluster/231
**ENSA2 SBD:** https://openqaworker15.qa.suse.cz/tests/336212#step/check_netweaver/261

SDAF remove dependency from inventory file

---

lib/LTP/utils.pm

`ss` is more modern tool than `netstat`, log network with it. Fallback to `netstat` (old systems or net-tools package not installed).
- https://openqa.suse.de/tests/overview?build=netstat-ss
- https://openqa.opensuse.org/tests/overview?build=netstat-ss

LTP: Log network with ss

---

tests/migration/online_migration/zypper_migration.pm

Same workaround I used for 53c2ec3dad it can be solved only when migration would be done with LTSS, but that is not recommended and we don't do it.
Bug is case of migration LTSS to LTSS
- Related ticket: https://bugzilla.suse.com/show_bug.cgi?id=1241014
- Verification run: https://openqa.suse.de/tests/overview?distri=sle&version=15-SP5&build=jpupava_ha

Workaround: LTSS to LTSS migration bug bsc#1241014

---

data/containers/bats/patches/aardvark-dns/619.patch
data/containers/bats/skip.yaml
tests/containers/bats/README.md

Backport https://github.com/containers/aardvark-dns/pull/619 to address https://github.com/containers/aardvark-dns/issues/618
Related ticket: https://bugzilla.opensuse.org/show_bug.cgi?id=1247812
- Tumbleweed:
- aarch64: https://openqa.opensuse.org/tests/5231401
- x86_64: https://openqa.opensuse.org/tests/5231402
- SLE 16.0:
- aarch64: https://openqa.suse.de/tests/18737148
- ppc64le: https://openqa.suse.de/tests/18737149
- s390x: https://openqa.suse.de/tests/18737150
- x86_64: https://openqa.suse.de/tests/18737151

bats/aardvark-dns: Backport PR#619 to fix dnsmasq issue

---

lib/containers/bats.pm
tests/containers/bats/buildah.pm
tests/containers/bats/podman.pm
tests/containers/bats/runc.pm
tests/containers/bats/skopeo.pm

- Use JSON on `ip -$ip_version` commands. 
- Use `return 0` on early skip.

Minor BATS enhancements

---

lib/containers/bats.pm

Beautify JSON output through jq.  The current output uses one line and is not fit for human consumption.

bats: Beautify JSON output through jq

---

data/containers/bats/patches/podman/26798.patch
data/containers/bats/skip.yaml

Backport https://github.com/containers/podman/pull/26798 to fix pasta tests
- Tumbleweed aarch64 (crun): https://openqa.opensuse.org/tests/5232829
- Tumbleweed aarch64 (runc): https://openqa.opensuse.org/tests/5232830
- Tumbleweed x86_64 (crun): https://openqa.opensuse.org/tests/5232831
- Tumbleweed x86_64 (runc): https://openqa.opensuse.org/tests/5232832
- sle-16.0 aarch64: https://openqa.suse.de/tests/18739145
- sle-16.0 ppc64le-p10: https://openqa.suse.de/tests/18739146
- sle-16.0 s390x-kvm: https://openqa.suse.de/tests/18739147
- sle-16.0 x86_64: https://openqa.suse.de/tests/18739148

bats/podman: Unignore 505-networking-pasta

---

lib/containers/bats.pm

Introduce function to collect kernel call traces in BATS tests.
Verification run: https://openqa.opensuse.org/tests/5236837

bats: Introduce function to collect kernel call traces

---

schedule/virt_autotest/kubevirt-tests-sle16.yaml
tests/virt_autotest/kubevirt_tests_agent.pm
tests/virt_autotest/kubevirt_tests_server.pm

Create a yaml file to support kubevirt tests running on sle16.
- Related ticket: https://progress.opensuse.org/issues/185920
- Verification run: https://openqa.suse.de/tests/18558237, https://openqa.suse.de/tests/18753078

Support kubevirt tests on sle16

---

tests/xfstests/partition.pm
variables.md

Add NFS with kerberos settings. The mount option could be sec=krb5:krb5i:krb5p, the setting similar to NFS over TLS, could be set with XFSTESTS_NFS_VERSION=[krb5:krb5i:krb5p]-<nfsversion> to enable, e.g:XFSTESTS_NFS_VERSION=krb5-4.2
- Related ticket: https://progress.opensuse.org/issues/177672
- Verification run: https://openqa.suse.de/tests/18753089

xfstests: Add NFS with krb5 tests

---

tests/containers/bci_prepare.pm
tests/containers/bci_test.pm

Reverts os-autoinst/os-autoinst-distri-opensuse#22704 because it causing regression
Failed job : https://openqa.suse.de/tests/18737483#step/bci_prepare/60
VR: http://openqa.suse.de/tests/18754265

Revert "Enable SaltBundle on SLES12-SP5"

---

tests/containers/bats/README.md
tests/containers/bats/aardvark.pm
tests/containers/bats/buildah.pm
tests/containers/bats/netavark.pm
tests/containers/bats/podman.pm
tests/containers/bats/runc.pm
tests/containers/bats/skopeo.pm

Use `.txt` extension to make TAP files browser-friendly.
No need to download `.tap` files anymore as they're just one click away.
- Verification run: https://openqa.opensuse.org/tests/5238544/logfile?filename=aardvark-aardvark.tap.txt

bats: Use .txt extension to make TAP files browser-friendly 

---

lib/Yam/Agama/Pom/GrubMenuAgamaPage.pm

##
- We need to wait more time for check_screen when we check needle `agama_installer_highlighted` on aarch64, cause it's cost more time for Aarch64 boot into Grub menu.
- Needles: N/A
- pro
- [10 seconds X 10 => ALL PASSED](https://openqa.suse.de/tests/overview?distri=sle&version=16.0&build=hjluo_sles_use_existing_md_raid_statistic)
- [9 seconds X 10 => 4/10 FAILED](https://openqa.suse.de/tests/overview?distri=sle&version=16.0&build=hjluo_sles_use_existing_md_raid_wait_9_seconds)
- Dev
- https://openqa.suse.de/tests/18753083
##

Bump timeout for check_screen on  Agama aarch64 bootup

---

data/virt_autotest/guest_params_xml_files/sles_16_64_kvm_hvm_x86_64_agama_online_iso.xml
lib/guest_installation_and_configuration_base.pm
lib/guest_installation_and_configuration_metadata.pm
lib/parallel_guest_migration_base.pm
lib/parallel_guest_migration_metadata.pm
lib/virt_autotest/utils.pm
lib/virt_autotest/virtual_network_utils.pm

* **New** subroutine ```reselect_openqa_console``` in ```lib/virt_autotest/utils.pm``` to do actual console reconnecting if it is lost due to operation like altering network configuration. 
* **Calling** ```reselect_openqa_console``` in module ```lib/guest_installation_and_configuration_base.pm``` after activating br0 to ensure 'root-ssh' console is always present. 
* **And** test suite level setting ```RESELECT_CONSOLE_COUNTER``` can be used to specify customized value of timeout when detecting whether concerned console is lost.
* [console reconnected after being considered lost](http://10.200.140.9/tests/1259#step/unified_guest_installation/431)
* [console is not lost during detecting period](http://10.200.140.9/tests/1268)
* [MU 15-SP7 KVM …

Stablize br0 setup on SLES16 host

---

schedule/security/sle16/agama.yaml

https://progress.opensuse.org/issues/186125
This change enables installation with FIPS in kernel mode when `FIPS_INSTALLATION` is set to 1 and `BOOTPARAMS` to `fips=1`. This adds the `fips=1` kernel parameter during installer boot and checks if FIPS is enabled in the installed system.
- Related ticket: https://progress.opensuse.org/issues/186125
- Verification run: https://openqa.suse.de/tests/18765895

Test agama with FIPS ker mode installation

---

tests/containers/bats/aardvark.pm

Use netcat-openbsd instead of ncat on SLES < 16.
The original aardvark-dns tests used netcat-openbsd (nc) and they worked.  Later they migrated to Nmap's ncat and they break on versions different than 7.92, 7.94 & 7.95.  We also depend on repos for ncat that disappear.
Issue opened upstream to migrate away from ncat: https://github.com/containers/aardvark-dns/issues/622
Failed jobs: https://openqa.suse.de/tests/18781071#step/aardvark/101
- sle-15-SP5 aarch64: https://openqa.suse.de/tests/18782411
- sle-15-SP5 x86_64: https://openqa.suse.de/tests/18782412
- sle-15-SP6 aarch64: https://openqa.suse.de/tests/18782414
- sle-15-SP6 x86_64: https://openqa.suse.de/tests/18782415
- sle-15-SP7 aarch64: https://openqa.suse.de/tests/18782416
- sle-15-SP7 x86_64: …

bats/aardvark: Use netcat-openbsd for SLES < 16

---

tests/console/system_prepare.pm
tests/installation/reboot_after_installation.pm
tests/installation/scc_registration.pm

This commit removes obsolete workaround code for Windows Server from
tests/console/system_prepare and other test modules as the related bug
https://bugzilla.suse.com/show_bug.cgi?id=1217800 is RESOLVED INVALID
anyway since 2024 and AFAIK test cover for this product was already
reduced/removed.
According to
https://learn.microsoft.com/en-us/lifecycle/products/windows-server-2016
Windows Server 2016 is EOL since 2022-01-11 (Mainstream).
I opted to remove this code to prepare a potential move of HyperV
specifics to the backend in os-autoinst when I found this backend
specific workaround code in test modules where it should not belong at
all.
Related progress issue: https://progress.opensuse.org/issues/95422

Remove obsolete workarounds for Windows Server 2016

---

tests/jeos/glibc_locale.pm

Regex matched if the key of the hash was non-existent.
VR: [simulated failure](http://kepler.suse.cz/tests/25175#step/glibc_locale/300)

Small fix, check key presence

---

data/containers/bats/skip.yaml

Ignore 200-bridge-firewalld on SLES 15 until we find a better repo for ncat.
```
$ susebats notok https://openqa.suse.de/tests/18781068
BATS_SKIP: 200-bridge-firewalld 250-bridge-nftables
$ susebats notok https://openqa.suse.de/tests/18781065
BATS_SKIP: 200-bridge-firewalld 250-bridge-nftables
$ susebats notok https://openqa.suse.de/tests/18781060
BATS_SKIP: 200-bridge-firewalld 250-bridge-nftables
$ susebats notok https://openqa.suse.de/tests/18781059
BATS_SKIP: 200-bridge-firewalld 250-bridge-nftables
```

bats/netavark: Ignore 200-bridge-firewalld on SLES 15

---

data/journal_check/bug_refs.json
lib/main_micro_alp.pm

Failures:
https://openqa.opensuse.org/tests/5242562#step/journal_check/21 (journal_check)
https://openqa.opensuse.org/tests/5242603 (host_config)
VRs:
https://openqa.opensuse.org/tests/5244550 (didn't ignore bsc#1245376 yet)
https://openqa.opensuse.org/tests/5244681 (with ignoring of bsc#1245376)

Fixes for MicroOS on ppc64le

---

tests/containers/bats/podman.pm

Support `BATS_IGNORE_USER=all` & `BATS_IGNORE_ROOT=all` to avoid having to use specify both the `_LOCAL` & `_REMOTE` variants when wanting to skip rootless or root.
Undocumented for now until we see whether it's worth it to extend it to have other values like other modules.

bats/podman: Support BATS_IGNORE_{USER,ROOT}=all

---

tests/containers/bats/podman.pm

Declare errors variable before unless block

bats/podman: Declare errors variable before unless block

---

tests/virt_autotest/esxi_open_vm_tools.pm

Add real esxi_open_vm_tools test 12-SP5 ES
openQA test in scenario sle-12-SP5-Server-DVD-Incidents-VIRT-Vmware-ES-x86_64-mau-extratests-virt-vmware@64bit does not execute real open_vm_tools steps [esxi_open_vm_tools] and quit immediately. We should run the test for ES guests too.
- Related ticket: https://progress.opensuse.org/issues/179936
- 
- Verification run: https://openqa.suse.de/tests/18833706#step/esxi_open_vm_tools/201

Add real esxi_open_vm_tools test to 12-SP5-ES

---

lib/main_containers.pm

The initial design of the Helm Chart testing had the `if / elsif / else` logic, where if the `HELM_CHART` variable didn't match any of the `if / elsif` statements, the entire test would fail with and error about the `HELM_CHART` value. 
With our new approach of testing some charts on certain versions and excluding other versions, the current logic does not work and ends up with a ton of errors. 
This PR removes tweaks the loadtest section to only trigger the tests we need.
-  http://dirtman.qe.prg2.suse.org/tests/59 - This test is a clone of https://openqa.suse.de/tests/18803092 and shows that it `privateregistry` correctly does _NOT_ get scheduled and there is no error.
- http://dirtman.qe.prg2.suse.org/tests/58 - clone of https://openqa.suse.de/tests/18803093 - no …

Fix helm chart scheduling for SPR

---

tests/containers/container_engine.pm

A SR is in the queue to migrate the default OCI runtime in SLEM 6.0 & 6.1 from crun to runc.
Add soft-failure for [bsc#1239088](https://bugzilla.suse.com/show_bug.cgi?id=1239088) to ease this migration and avoid failed jobs.

containers: Add soft-failure for bsc#1239088

---

schedule/security/fips/sle16/agama_install_fips_ker_mode.yaml

Changes previously implemented in #22968 should be moved to a better location for FIPS testing.
- Related ticket: https://progress.opensuse.org/issues/186125
- Verification run: https://openqa.suse.de/tests/18829763

Move agama FIPS install schedule to a dedicated location

---

lib/main_containers.pm

Third party image tests are not needed or redundant on:
- Staging
- Public Cloud
- Testing latest Tumbleweed image with CONTAINER_IMAGE_TO_TEST
- FIPS tests
- Testing alternative cgroups version
- VMWare due to lack of latest CPU version support.
Intentionally kept out:
- When testing alternative MAC framework (AppArmor or SELinux, which uses SECURITY_MAC variable).
Related ticket: https://progress.opensuse.org/issues/179566

Remove redundant third party image test runs from container schedule

---

data/journal_check/bug_refs.json

`kernel: Could not retrieve perf counters (-19)` ->
https://bugzilla.suse.com/show_bug.cgi?id=1238885#c4, VM setup related issue, is not a problem with MinimalVM testing scope
`hv_storvsc 79eee825-a6ca-42ba-92e6-dbc0db1b5ef6: tag#75 cmd 0x5a status: scsi 0x2 srb 0x86 host 0xc0000001` -> reported as part of https://bugzilla.suse.com/show_bug.cgi?id=1236723
`kernel: sched: DL replenish lagged too much` -> happens only in aarch64, more of a load problem of the workers
- [sle-16.0-Minimal-VM-for-MS-HyperV-x86_64-Build32.10-minimalvm-kdump@svirt-hyperv2022](https://openqa.suse.de/tests/18852518#step/journal_check/5)
- [sle-16.0-Minimal-VM-for-kvm-and-xen-aarch64-Build32.10-minimalvm-ltp-commands@aarch64](https://openqa.suse.de/tests/18852519#step/journal_check/1)
- …

Add known issues for sle16.0

---

lib/susedistribution.pm

We have removed the return key send and replaced with a long timeout in screen selection.
- Related ticket: https://progress.opensuse.org/issues/187464
- Needles: N/A
- sles_default: https://openqa.suse.de/tests/18852946
- sles_sap_default: https://openqa.suse.de/tests/18852945

Ensure console selection after boot process in power kvm

---

data/journal_check/bug_refs.json

The detected message appears during shutdown/reboot phase. It is not the same as https://bugzilla.suse.com/show_bug.cgi?id=1245376, but seems like watchdog messages during reboot can be ignored

Ignore watchdog message when reboot

---

lib/sles4sap/azure_cli.pm
lib/sles4sap/ibsm.pm
lib/sles4sap/ipaddr2.pm
lib/sles4sap/qesap/azure.pm
t/15_qesap_azure.t
t/22_ipaddr2.t
t/35_ibsm.t
tests/sles4sap/ipaddr2/cluster_create.pm
tests/sles4sap/ipaddr2/configure.pm
tests/sles4sap/ipaddr2/deploy.pm
tests/sles4sap/ipaddr2/destroy.pm
tests/sles4sap/ipaddr2/network_peering.pm
tests/sles4sap/ipaddr2/patch_system.pm
tests/sles4sap/ipaddr2/registration.pm
tests/sles4sap/ipaddr2/sanity_cluster.pm
tests/sles4sap/ipaddr2/sanity_os.pm
tests/sles4sap/ipaddr2/test_move_resource.pm

Move code about peering the the IBSm in Azure to the IBSm library as code does not have any dependency to qe-sap-deployment. Implement some qesap::azure functions using the azure_cli lib. Remove ipaddr2 test module dependency to qesap.
Ticket: https://jira.suse.com/browse/TEAM-10496
sle-15-SP7-SapCloud-Azure-Byos-x86_64-BuildLATEST_AZURE_SLE15_7-ipaddr2_azure_test
- http://openqaworker15.qa.suse.cz/tests/338169
- http://openqaworker15.qa.suse.cz/tests/338183
sle-15-SP6-Azure-SAP-PAYG-Incidents-x86_64-Build:39929:zypper-ipaddr2
- http://openqaworker15.qa.suse.cz/tests/338172
- http://openqaworker15.qa.suse.cz/tests/338184
https://openqaworker15.qa.suse.cz/tests/overview?distri=sle&version=15-SP5&build=%3A39928%3Azypper&groupid=46
https://openqaworker15.qa.suse.cz/tests/overview?build=%3A399 …

Move Azure network peering to IBSm lib

---

tests/console/validate_raid.pm

##
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/18876753
##

Revert prepare_test_data for ppc64le

---

tests/wsl/smoke_test.pm

WSL smoke test is failing because powershell is opening in o3 tests twice.
When welcome_to_wsl popup triggers after WSL installation, it should not launch Powershell again.
- Related ticket: https://progress.opensuse.org/issues/187470
o3 with welcome_to_wsl: https://openqa.opensuse.org/tests/5257227#
osd without welcome_to_wsl: https://openqa.suse.de/tests/18876765

Prevent WSL test from launching powershell twice

---

tests/transactional/trup_smoke.pm

Since transactional-update 5.1 a new snapshot is expected to be created even if there won't be any diff between snapshots for `bootloader`, `grub.cfg` and `initrd` sub commands
Ticket: https://progress.opensuse.org/issues/187584
VR: 
- https://openqa.opensuse.org/tests/5257597
- https://openqa.opensuse.org/tests/5257596

Adjust trup_smoke to new transactional-update behavior

---

tests/security/audit/auditctl.pm
tests/security/audit/aureport.pm
tests/security/audit/ausearch.pm

Improve security-audit tests
Determine whether the system runs apparmor or selinux in a better way.
Adjust pid extraction from audit events when running on Tumbleweed.
https://progress.opensuse.org/issues/187635
Tumbleweed
https://openqa.suse.de/tests/18878977
SLE-16
https://openqa.suse.de/tests/18878979
SLE-15 SP7
https://openqa.suse.de/tests/18878980
SLE-15 SP6
https://openqa.suse.de/tests/18879900

Improve security-audit tests

---

lib/main_common.pm

`load_autoyast_tests` schedules `autoyast/installation` wich leaves the
system in an already booted desktop stage, openSUSE Welcome shows up once,
making the opensuse_welcome test fail even though it behaves as expected.
Follows #23006
VR: https://openqa.opensuse.org/tests/5258052

Schedule opensuse_welcome using AY and main.pm

---

lib/opensusebasetest.pm

Initially the grub2 screen was either missed due to wrongly chosen
needle tag or because the `check_screen` delayed the code to reach grub2
needle in time.
- Failure: https://openqa.suse.de/tests/18852718#step/glibc_locale/25
- Verification run: https://openqa.suse.de/tests/18880337#step/glibc_locale/1

Fix MinimalVM powerPC reboots

---

lib/Distribution/Opensuse/AgamaDevel.pm
lib/Distribution/Opensuse/Leap/16Latest.pm
lib/Distribution/Sle/16Latest.pm
lib/Distribution/Sle/AgamaDevel.pm

We need workaround distributions that 'boot from disk' hasn't reached yet for sle production and Leap production on ppc64le.
- Needles:  grub-menu-first-entry-highlighted grub-menu-install-product
- Verification run: https://openqa.suse.de/tests/18876670#details

Adapt for 'boot from disk' on ppc64le development

---

tests/console/validate_raid.pm

##
For SLES16 we're not use the old raid configuration. so we can't use the old logic to prepare_test_data.
- Related ticket: https://progress.opensuse.org/issues/184177
- Needles: N/A
- SLES15-SP7:
- https://openqa.suse.de/tests/18876818
- SLES16:
- https://openqa.suse.de/tests/18876811

Adapt validate_raid for  SLES16 ppc64le

---

lib/hacluster.pm
t/11_hacluster.t

This pr adds an identifier (`crmshver=`) before the output of the `crmsh` version rpm command, so that the version can be caught even if extra noise makes it to the output. 
- Related ticket: https://jira.suse.com/browse/TEAM-10587
- Verification run: https://openqa.suse.de/tests/18886257 (and dependencies)

Add identifier in crmsh version command output

---

tests/publiccloud/run_ltp.pm

Use LTP helper function to initialize the LTP env defaults for whitelist checks. Fixes #23063 
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/18886503

run_ltp: Initialize public cloud LTP env correctly

---

tests/console/zypper_ar.pm

On zdup scenarios OSS and NON_OSS repos are present but disabled, as they come from openQA jobs that generated the images, since they would cause collision, its better to remove them if they're disabled
Failure: https://openqa.opensuse.org/tests/5259964#step/zypper_in/22
VR: https://openqa.opensuse.org/tests/5261062

Remove disabled repo aliases

---

lib/Distribution/Opensuse/Leap/16Latest.pm
lib/Distribution/Sle/16Latest.pm

- Related PR: https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/23047
Sle development power 10 kvm: https://openqa.suse.de/tests/18913903#step/agama/11
Leap ppc64le: https://openqa.opensuse.org/tests/5262095#live

Add missed including for is_ppc64le

---

data/containers/patches/docker-py/3261.patch
data/containers/patches/docker-py/3290.patch
data/containers/patches/docker-py/3354.patch
data/containers/patches/podman-py/572.patch
data/containers/patches/podman-py/575.patch
lib/main_containers.pm
tests/containers/python_runtime.pm

Add tests for python3-docker & python3-podman.
This brings lots of benefits:
- The python3-docker's runs hundreds of tests that we don't run in openQA because we lack other upstream tests for Docker, 
- Helping catch [bsc#1248415 - python3-podman package is not available](https://bugzilla.suse.com/show_bug.cgi?id=1248415)
- It already helped catch some test issues:
- https://github.com/docker/docker-py/pull/3354
- https://github.com/containers/podman-py/pull/572
- https://github.com/containers/podman-py/pull/575
These tests take only ~7 minutes.
TODO (in another PR):
- Eventually, these tests should be extended to catch bugs like https://bugzilla.suse.com/show_bug.cgi?id=1248373
- Extend to SLES 16.0?  This needs git 2.47+ for `git apply -3 --ours` so a special repo is needed like we do …

Add tests for docker-py & podman-py

---

tests/installation/ipxe_install.pm

https://bugzilla.suse.com/show_bug.cgi?id=1246600
https://openqa.suse.de/tests/18915252 [Please ignore the failed module, it is known issue]
- Regression [ with proxy scc]
https://openqa.suse.de/tests/18915415
-----------------------------------------------------------------------------
See the kernel command line during the installation:
`
linux root=live:http://openqa.suse.de/assets/iso/SLES-16.0-Online-x86_64-Build129.5.install.iso live.password=nots3cr3t inst.auto=http://worker36.oqa.prg2.suse.org:20603/KygwbobHyN8_yYG7/files/virt_autotest/host_unattended_installation_files/agama/sle16.jsonnet inst.finish=stop console=ttyS1,115200 linuxrc.log=/dev/ttyS1 linuxrc.core=/dev/ttyS1 linuxrc.debug=4,trace
`
Regression:
`kernel …

Don't define reg_url if SCC is used for Agama install

---

lib/Yam/Agama/Pom/AgamaUpAndRunningPage.pm
tests/yam/agama/agama.pm
tests/yam/agama/boot_agama.pm

Enhance the test to avoid introducing fictitious variable.
- Related ticket: https://progress.opensuse.org/issues/185704
- Related PR: https://github.com/jknphy/agama-integration-test-webpack/pull/136
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/18915865#details

Add test for alert informing the user that Agama could not fetch profile

---

lib/Distribution/Opensuse/Leap/16Latest.pm

Now the boot from hard disk hasn't reached Leap, we need adapt old behavior on Leap.
- Related ticket: https://progress.opensuse.org/issues/186702
- Related PR: https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/23047
- Needles: N/A
- Verification run: https://openqa.opensuse.org/tests/overview?distri=opensuse&version=16.0&build=lemon-suse%2Fos-autoinst-distri-opensuse%23adapt-install-entry-old-behaviour-leap
The failure on ppc64le is not related with the PR.

Adapt install entry old behavior on Leap

---

lib/containers/common.pm
lib/main_micro_alp.pm
tests/containers/bci_prepare.pm
tests/containers/bci_test.pm

Revert https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/23021
There are multiple issues:
- The concept of modules is not enabled on SLE 16.0: https://openqa.suse.de/tests/18918231#step/bci_prepare/26
- skopeo is not available in SLEM < 5.5: https://openqa.suse.de/tests/18918216#step/bci_prepare/20
- git (should be git-core) is also not available in SLEM < 5.5 
I tried to address them with https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/23091 without luck.

Revert "Enable BCI tests in sle-micro hosts"

---

lib/main_containers.pm

python3-podman is not available on SLES due to https://bugzilla.suse.com/show_bug.cgi?id=1248415

containers/podman-py: python3-podman is not available on SLES

---

lib/utils.pm
t/05_utils_auxiliary.t

Adds a safeguard for the timeout command to kill the underlying command if stuck.
Adding the "kill after 5 seconds" option to timeout should be relatively safe, because without this the test would fail with a timeout, and this gives the system under test another retry to do run a command. If the system is borked, it will very likely fail on those subsequent tries.
- Related ticket: https://progress.opensuse.org/issues/187566
- Verification run: https://openqa.suse.de/tests/18879000

lib: Fix script_retry dies on timeout

---

lib/hacluster.pm

Small fix for sporadic issue in crmsh version regex
- Related ticket: https://jira.suse.com/browse/TEAM-10587
- Verification run: https://openqa.suse.de/tests/18932516 (and dependencies)

Remove newline from crmshver regex

---

tests/yam/validate/validate_suseconnect_url.pm

- Related ticket: https://progress.opensuse.org/issues/184750
- Related MR: https://gitlab.suse.de/qe-yam/openqa-job-groups/-/merge_requests/553
- [Verification runs in my dev group](https://openqa.suse.de/tests/overview?arch=&flavor=&machine=&test=sles_rmt_unattended_rk&modules=&module_re=&group_glob=&not_group_glob=&comment=&distri=sle&version=16.0&build=129.5&groupid=585#)
- on s390x we're still suffering from [bsc#1247933]( https://bugzilla.suse.com/show_bug.cgi?id=1247933)

Test if registrationURL in profile is prefered over kernel parameter

---

data/containers/bats/patches/aardvark-dns/581.patch
data/containers/bats/patches/aardvark-dns/623.patch
data/containers/bats/skip.yaml
tests/containers/bats/aardvark.pm

Nmap's ncat is a problematic dependency and we can drop it completely for the aardvark-dns upstream tests by backporting these fixes:
- https://github.com/containers/aardvark-dns/pull/581
- https://github.com/containers/aardvark-dns/pull/623
- Tumbleweed:
- aarch64: https://openqa.opensuse.org/tests/5269822
- ppc64le: https://openqa.opensuse.org/tests/5269823
- x86_64: https://openqa.opensuse.org/tests/5269863
- SLES 16.0:
- aarch64: https://openqa.suse.de/tests/18936477
- ppc64le: https://openqa.suse.de/tests/18936478
- s390x: https://openqa.suse.de/tests/18937818
- x86_64: https://openqa.suse.de/tests/18938094
- SLES 15-SP6:
- aarch64: https://openqa.suse.de/tests/18938648
- x86_64: https://openqa.suse.de/tests/18939104
- SLES 15-SP7:
- aarch64: …

bats/aardvark-dns: Backport PR#623 to drop ncat dependency

---

tests/virt_autotest/prepare_non_transactional_server.pm
tests/virt_autotest/sev_snp_validation.pm

Add BIOS info ans machine info during sev-snp testing
Skip br0 creation during sev-snp and sev-es testing
- Related ticket: https://progress.opensuse.org/issues/187104
- Needles: n/a
[BIOS info display](https://openqa.oqa.prg2.suse.org/tests/18932843#step/sev_snp_validation/45)
[Machine info display](https://openqa.oqa.prg2.suse.org/tests/18932843#step/sev_snp_validation/48)
[Skip br0 creation](https://openqa.oqa.prg2.suse.org/tests/18941700#step/prepare_non_transactional_server/32)

Add BIOS info during sev-snp testing

---

lib/virt_autotest/virtual_network_utils.pm

Set up a host bridge on SLES16 with the enhancement
- Related ticket: https://progress.opensuse.org/issues/187197
kermit [uefi-gi-guest_developing-on-host_developing-kvm](https://openqa.suse.de/tests/18941941#step/prepare_non_transactional_server/55) pass
bare-metal6[uefi-gi-guest_developing-on-host_developing-kvm](https://openqa.suse.de/tests/18934181#step/prepare_non_transactional_server/51) pass

Setup a host bridge on sles16 with the enhancement

---

data/containers/patches/docker-py/3199.patch
data/containers/patches/docker-py/3203.patch
data/containers/patches/docker-py/3206.patch
data/containers/patches/docker-py/3231.patch
lib/main_containers.pm
tests/containers/python_runtime.pm

Enable docker-py tests on SLES 15-SP4+
For this we need to:
- Backport some nice & sweet test fixes.
- Use latest git to take advantage of `git apply -3 --ours` like we do in bats tests.
Also:
- Introduce `DOCKER_API_VERSION` to test different API version when requested.
- Use `/etc/sysconfig/docker` as it's better than patching `/etc/docker/daemon.json`
Opened bug: https://bugzilla.suse.com/show_bug.cgi?id=1248755
Verification runs of the individual module so you get an idea how much little time it takes:
- SLES 15-SP7: https://openqa.suse.de/tests/18942696
- SLES 15-SP4: https://openqa.suse.de/tests/18942697
- SLES 16.0: https://openqa.suse.de/tests/18942552
- Tumbleweed: https://openqa.suse.de/tests/18940292
Full verification runs:
- sle-15-SP4 aarch64: …

Enable docker-py tests on SLES 15-SP4+

---

tests/yam/validate/validate_suseconnect_url.pm

It turned out that the named regex in the validate_suseconnect_url test was matching more than it should. This is fixed now by using the "non-greedy" quantifier "?".
- Failed test: https://openqa.suse.de/tests/18941892#step/validate_suseconnect_url/2
- VR for fix:  https://openqa.suse.de/tests/18942563

Quick fix for greedy regex in validate_suseconnect_url

---

lib/Kselftests/parser.pm
lib/Kselftests/parsers/bpf/test_bpftool_sh.pm
lib/Kselftests/parsers/bpf/test_lru_map.pm
lib/Kselftests/parsers/bpf/test_maps.pm
lib/Kselftests/parsers/bpf/test_progs.pm
lib/Kselftests/parsers/bpf/test_progs_cpuv4.pm
lib/Kselftests/parsers/bpf/test_progs_no_alu32.pm
lib/Kselftests/parsers/bpf/test_sockmap.pm
lib/Kselftests/parsers/bpf/test_tag.pm
lib/Kselftests/parsers/bpf/test_tc_edt_sh.pm
lib/Kselftests/parsers/bpf/test_tc_tunnel_sh.pm
lib/Kselftests/parsers/bpf/test_tcpnotify_user.pm
lib/Kselftests/parsers/bpf/test_verifier.pm
lib/Kselftests/parsers/bpf/test_xdping_sh.pm
lib/Kselftests/parsers/net/l2tp_sh.pm
lib/Kselftests/utils.pm
tests/kernel/run_kselftests.pm

Add the post-processing parsers for BPF.
- Related ticket: https://progress.opensuse.org/issues/157186
- Verification run: https://rmarliere-openqa.qe.prg2.suse.org/tests/1528

Kselftests: Add BPF parsers

---

tests/console/validate_packages_and_patterns.pm

Update test code about validate_packages_and_patterns for sle16
- Related ticket:  https://progress.opensuse.org/issues/187824
- Verification run: https://openqa.suse.de/tests/18942167#step/validate_packages_and_patterns/8

Update test code about validate_packages_and_patterns for sle16

---

test_data/yam/agama_sap_media.yaml
test_data/yam/agama_sle_media.yaml

It is quite close to sle16 GMC now, it is reasonable to remove the 'Beta' string from the repos' name. So update the test data of repos for media installation. BTW, there isn't 'Beta' string in the installation cases in Online flavor, so no need to update datas for Online testsuites.
- Related failure: https://openqa.suse.de/tests/18952108#step/validate_repos/7
https://openqa.suse.de/tests/18959946 (sles)
https://openqa.suse.de/tests/18959956 (sap)

Update the test data of repos for medium installation testsuites

---

lib/main_containers.pm

Skip docker-py tests on public cloud

containers: Skip docker-py tests on public cloud

---

lib/publiccloud/azure_client.pm
tests/sles4sap/publiccloud/qesap_terraform.pm
tests/sles4sap/qesapdeployment/configure.pm

Add namespace as optional argument for the Azure PC client object. If missing fall back to PUBLIC_CLOUD_NAMESPACE.
- Related ticket: TEAM-10432
sle-15-SP7-SapCloud-Azure-Byos-x86_64-BuildLATEST_AZURE_SLE15_7-ipaddr2_azure_test test in Azure  not needing the double credentials. This one has been executed using sapha namespace
- http://openqaworker15.qa.suse.cz/tests/339350 :green_circle: 
sle-15-SP7-Qesap-Gcp-Byos-x86_64-Buildmpagot_VR-qesap_gcp_sapconf_test executed in GCE not using the sapha credentials namespace
- http://openqaworker15.qa.suse.cz/tests/339351 :green_circle: failure is the confirmation about the fact that it is working :-)

Add namespace as client init argument

---

tests/wsl/distro_install.pm

As stated by developers, Microsoft is deprecating the .appx format in favor of .tar.xz. These new images are already being uploaded to the Microsoft Store and are what we've been referring to as "modern" images.
The aim of this ticket is to formalize a new, tested procedure for extracting and installing future .tar.xz images when needed. This method has been verified locally and is a straightforward, three-step process.
- Related ticket: https://progress.opensuse.org/issues/187728
- [SLE .tar.xz](https://openqa.suse.de/tests/18944338#step/distro_install/23)
- [SLE .appx](https://openqa.suse.de/tests/18961861#step/distro_install/21)
- [SLE wrong extension](https://openqa.suse.de/tests/18943869#step/distro_install/14)
- [TW x86_64 …

New installation method for .tar.xz images

---

lib/containers/k8s.pm
tests/containers/scc_login_to_registry.pm

Allow install_kubectl and install_helm to be called multiple times. On subsequent calls the routines will not re-install the packages.
- Related failure: https://openqa.suse.de/tests/18963129#step/privateregistry/60
- Verification run: https://duck-norris.qe.suse.de/tests/14930

Allow reexecution install_kubectl and install_helm

---

tests/containers/scc_login_to_registry.pm

Since the purpose is only to add credentials for helm, remove all other parts which are not needed.
- Related failure: https://openqa.suse.de/tests/18963662#step/scc_login_to_registry/57
- Verification run: https://duck-norris.qe.suse.de/tests/14931#step/privateregistry/54 (unrelated issue)

Simplify scc_login_to_registry

---

data/containers/bats/patches/podman/26921.patch
data/containers/bats/skip.yaml
tests/containers/bats/podman.pm

Backport https://github.com/containers/podman/pull/26921 to drop netcat dependency
- Verification run: https://openqa.opensuse.org/tests/5274510

bats/podman: Backport PR#26921 to drop netcat dependency

---

tests/kernel/kernel_kexec.pm

On some overloaded aarch64 workers, clear_console might hang and trigger a timeout.
Related ticket: https://progress.opensuse.org/issues/184097
- Many retries failed to reproduce the error when clear_console is absent: https://openqa.suse.de/tests/18965821#next_previous
- Error was reproduced on the third time when clear_console is present: https://openqa.suse.de/tests/18964435#next_previous

kernel_kexec: Remove old workaround

---

lib/registration.pm

Set inst.register_url=scc.suse.com will make it a custom url which is not expected.
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/18885941#details

Avoid set inst.register_url for scc.suse.com on AGAMA test

---

lib/Distribution/Opensuse/Leap/16Latest.pm

- Meanwhile Leap 16 Grub menu also has "boot from harddisk" as first entry in the menu, so no need to handle Leap differently anymore.
- Verification run: https://openqa.opensuse.org/tests/5275008

Quickfix for boot_agama on Leap 16

---

lib/bootloader_setup.pm
schedule/install/agama_install.yaml
tests/installation/bootloader_uefi.pm

Switch to bootloader_start as it is a wrapper for different bootloaders which in turn, are able to handle cmdline parameters for booting the installer pointing to the right repositories
- x86: https://openqa.opensuse.org/tests/5274022
- x86 (latest build) https://openqa.opensuse.org/tests/5274301
- s390: https://openqa.opensuse.org/tests/5272383
- failure is: https://bugzilla.opensuse.org/show_bug.cgi?id=1248800
- aarch64: https://openqa.opensuse.org/tests/5274044
- ppc64: https://openqa.opensuse.org/tests/5274054
- failure is https://progress.opensuse.org/issues/180929
This is the alternative to #23123

Use bootloader_start for agama tests in Leap 16

---

tests/x11/gnomecase/gnome_default_applications.pm

* image/jpg is not a valid mimetype; it's image/jpeg - assign to Loupe
* image/png assigned to Loupe
* application/pdf assigned to Papers (replaced evince)
* application/{x-bzip2,gzip} to be opened by Nautilus internal compressor, not FileRoller
- Related ticket: https://progress.opensuse.org/issues/121276
- Needles: N/A
- Verification run: https://openqa.opensuse.org/tests/5271258
openqa: clone https://openqa.opensuse.org/tests/5269391

gnomecase: fix expected application associations for mimetypes

---

tests/sles4sap/redirection_tests/check_ensa2_cluster.pm
tests/sles4sap/redirection_tests/check_hana_database.pm
tests/sles4sap/sap_deployment_automation_framework/deploy_workload_zone.pm

There are missing imports in 'check_hana_database' and 'check_ensa2_cluster' modules. This PR fixes the bug.
Ticket: no ticket
Failing test: https://openqaworker15.qa.suse.cz/tests/339244#step/check_ensa2_cluster/83
VR:
ENSA2: https://openqaworker15.qa.suse.cz/tests/339380#
HanaSR: https://openqaworker15.qa.suse.cz/tests/339383#

Fix missing imports

---

tests/yam/migration/migration_unattended.pm

The time in grub for migration menu is too short, and openqa testing run so fast that non-x86_64 jobs can not catch the migration menu. So update the needle match for it.
- Related failures:
https://openqa.suse.de/tests/18971256#step/migration_unattended/1 (aarch64)
https://openqa.suse.de/tests/18971255#step/migration_unattended/1 (ppc64le)
- Verification run:[ verification runs](https://openqa.suse.de/tests/overview?arch=&flavor=&machine=&test=sles_migration_15sp7_textmode_test&modules=&module_re=&group_glob=&not_group_glob=&comment=&build=chcao_review_132.4&version=16.0&distri=sle#)

Update the grub of migration menu match for sle16 migration

---

tests/containers/container_engine.pm

Remove flaky search test.  This test depends that a lot of devel images don't appear at the beginning.   And it's redundant anyway given that we have `test_search_registry`
Failing test: https://openqa.suse.de/tests/18983894#step/podman/152

containers: Remove flaky search test

---

data/containers/bats/skip.yaml

These patches are no longer needed since Tumbleweed 20250829:
- aardvark-dns: PR#619 not needed since v1.16.0
- buildah: PR#6226 not needed since v1.41.3
- podman: PR#25918 & 25942 not needed since v5.6.0
Even though these patches are idempotent, we must clean them up from the list to have a minimal reproducer.  The patches are not removed from the repo because they'll be needed when podman is upgraded on SLES.

Drop some unneeded patches since latest Tumbleweed 20250829

---

tests/containers/bci_prepare.pm

Limit block to openSUSE & SLES.
Fix `bash: zypper: command not found`
Failing test: https://openqa.suse.de/tests/18992102#step/bci_prepare/167

bci_prepare: Limit block to openSUSE & SLES

---

data/yam/agama/auto/lib/base.libsonnet
data/yam/agama/auto/template.libsonnet
lib/grub_utils.pm

- Related ticket: https://progress.opensuse.org/issues/184073
- Related MR: https://gitlab.suse.de/qe-yam/openqa-job-groups/-/merge_requests/545
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/overview?distri=sle&build=lemon-suse%2Fos-autoinst-distri-opensuse%23check-agama-grub-timeout-shown&version=16.0

Automate configurable timeout for bootloader

---

data/containers/bats/skip.yaml
data/containers/patches/conmon/579.patch
lib/containers/bats.pm
tests/containers/bats/README.md
tests/containers/bats/conmon.pm

Add conmon upstream tests.
conmon is the OCI container runtime monitor used by podman to track containers.  
This job is only planned for Tumbleweed and SLES 16.0.
Related PR: https://github.com/os-autoinst/opensuse-jobgroups/pull/713
- Tumbleweed: (conmon 2.1.13)
- aarch64: https://openqa.opensuse.org/tests/5278219
- ppc64le: https://openqa.opensuse.org/tests/5278220
- x86_64: https://openqa.opensuse.org/tests/5278213
- SLES 16.0 (conmon 2.1.13)
- aarch64: https://openqa.suse.de/tests/18985083
- ppc64le: https://openqa.suse.de/tests/18985084
- s390x: https://openqa.suse.de/tests/18985085
- x86_64: https://openqa.suse.de/tests/18985080
- SLES 15-SP7 (conmon 2.1.10)
- x86_64: https://openqa.suse.de/tests/18985082

Add conmon upstream tests

---

lib/Kselftests/parsers/bpf/test_progs.pm

Related ticket: https://progress.opensuse.org/issues/187791
- Before: https://rmarliere-openqa.qe.prg2.suse.org/tests/1535/logfile?filename=run_kselftests-kselftest.tap.txt#line-82
- After: https://rmarliere-openqa.qe.prg2.suse.org/tests/1539/logfile?filename=run_kselftests-kselftest.tap.txt#line-82

Kselftests: Add $test_name to test_progs BPF parser

---

tests/console/validate_raid.pm

Ticket: https://progress.opensuse.org/issues/187839
VR: 
- Tumbleweed https://openqa.opensuse.org/tests/5278586
- SLE 15-SP7: https://openqa.suse.de/tests/18992486
- SLE 16: https://openqa.suse.de/tests/18992577#details

Avoid excluding Tumbleweed in validate_raid for ppc64le

---

lib/main_containers.pm

Schedule privateregistry on all SLES versions
This is an emergency fix for https://openqa.suse.de/tests/18995218
* https://suse.slack.com/archives/C06LTKZ2XJ7/p1756713336792249

Schedule privateregistry

---

lib/Kselftests/parser.pm
lib/Kselftests/parsers/bpf/test_xsk_sh.pm

- Related ticket: https://progress.opensuse.org/issues/187791
- Verification run: https://rmarliere-openqa.qe.prg2.suse.org/tests/1546#external

Kselftests: Add BPF test_xsk_sh parser

---

tests/console/systemd_resolved.pm

Test could fail sometimes when starting NetworkManager or resolved would not be able to resolve queries; moreover due to a possible race condition, sometimes the test would be able to pass
- failed to resolve: https://openqa.opensuse.org/tests/5257140#step/systemd_resolved/61
- NetworkManager failing to start: https://openqa.opensuse.org/tests/5257044#step/systemd_resolved/85
Ticket: https://progress.opensuse.org/issues/187653
VR: 
- https://openqa.opensuse.org/tests/overview?version=Tumbleweed&build=foursixnine%2Fos-autoinst-distri-opensuse%2323067&distri=opensuse
Failures in wpa_supplicant are unrelated
~Failures in systemd-resolved are:~ See also: https://bugzilla.opensuse.org/show_bug.cgi?id=1248501

Make systemd_resolved test more reliable

---

tests/wsl/smoke_test.pm

Powershell is still opening twice for installation from MSStore legacy scenario.
We need to only re-open powershell for installation from build in o3.
Related ticket: https://progress.opensuse.org/issues/187737 and https://progress.opensuse.org/issues/187470
Leap:
wsl_main win 11: https://openqa.opensuse.org/tests/5278591
wsl2_main win 11: https://openqa.opensuse.org/tests/5278592
modern jeos-firstrun win11: https://openqa.opensuse.org/tests/5278583
legacy yast-firstrun win 11: https://openqa.opensuse.org/tests/5278577
TW:
wsl2_main win 11: https://openqa.opensuse.org/tests/5278590
modern jeos-firstrun win11: https://openqa.opensuse.org/tests/5278584
legacy yast-firstrun win 11: https://openqa.opensuse.org/tests/5278578
SLE:
modern jeos-firstrun win11 sp6: …

Do not re-open powershell for o3 MSstore installation in WSL

---

tests/containers/charts/privateregistry.pm

Increase the time we wait for the pod to get ready and skip installation
of traefik when it's already installed.
- Related ticket: https://progress.opensuse.org/issues/188046
- Verification run: https://duck-norris.qe.suse.de/tests/14948

Fix PrivateRegistry

---

schedule/security/autoyast_btrfs_luks2_tw.yaml

Ticket: https://progress.opensuse.org/issues/187083
Current schedule has a failure rate of [about 50%](https://openqa.opensuse.org/tests/latest?arch=x86_64&distri=opensuse&flavor=DVD&machine=64bit&test=unlock_luks2_volume_with_tpm2&version=Tumbleweed#next_previous) due to a race when calling `zypper` while `PackageKit` is still running in the background
VR: https://openqa.opensuse.org/tests/overview?version=Tumbleweed&build=foursixnine%2Fos-autoinst-distri-opensuse%2323188&distri=opensuse

Ensure PackageKit gets masked properly by scheduling system_prepare

---

schedule/ha/bv/pvm_cluster.yaml

... in the schedule.
Some times using `TIMEOUT_SCALE: 2` leads to jobs reporting a failure during `shutdown/shutdown`, but it seems it just needs more time.
This increases it to `TIMEOUT_SCALE: 4`.
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/overview?build=PR23176&distri=sle&version=16.0

Increase TIMEOUT_SCALE for clusters on pvm_hmc

---

lib/main_containers.pm

This will be used to schedule odd tests.  Undocumented for now.
Also useful for debugging to go straight to a test as the INCLUDE_MODULES is a bit cumbersome.  I need it to schedule some new tests like the podman e2e tests.
Verification run: https://openqa.opensuse.org/tests/5282176 (cloned with `CONTAINER_TESTS=python_runtime`)
NOTES
- The above VR was cancelled, just to verify proper scheduling.

containers: Introduce CONTAINER_TESTS variable

---

lib/sles4sap_publiccloud.pm
t/12_sles4sap_publiccloud.t

This function adds retry capability on top of 'run_cmd'. Use this new function in 'get_hana_topology' to reduce chance of sporadic failure.
This function is modeled after `script_output_retry`:
https://github.com/os-autoinst/os-autoinst-distri-opensuse/blob/c56f08cd935d9b1f02d69bd5bc2aa7f9594e8aee/lib/utils.pm#L2074
- Related ticket: https://jira.suse.com/browse/TEAM-10485
example that this PR does not break test: https://openqa.suse.de/tests/19004924#step/Stop_site_a-primary/124
example where the retry mechanism work: https://openqa.suse.de/tests/18991224#step/qesap_prevalidate/79

SLES4SAP: Add new function 'run_cmd_retry'

---

data/containers/bats/skip.yaml
data/containers/patches/buildah/5495.patch

Backport https://github.com/containers/buildah/pull/5495 to avoid nixery registry
We're currently getting:
`# Error: initializing source docker://nixery.dev/shell:latest: reading manifest latest in nixery.dev/shell: received unexpected HTTP status: 500 Internal Server Error`
Manually tested.

bats/buildah: Backport PR#5495 to avoid nixery registry

---

tests/kernel/install_ltp.pm
tests/kernel/run_ltp.pm

The `dhcp-client` was removed from SLE-16, move it to optional dependency list. Save tcpdump files to `/var/tmp` because they may be too large for tmpfs on `/tmp`.
- Needles: N/A
- SLE-12SP5: https://openqa.suse.de/tests/19016384
- SLE-16: https://openqa.suse.de/tests/19016388

Fix LTP installation from Git and tcpdump capture on SLE-16

---

lib/Kselftests/parsers/bpf/test_progs.pm

This will enable a smaller known issues file while preserving enough test granularity and also provide better output in the openQA job.
Related ticket: https://progress.opensuse.org/issues/187791
- Before: https://openqa.opensuse.org/tests/5284180
- After: https://openqa.opensuse.org/tests/5284251

Kselftests: BPF: Remove sub-sub-test parsing from test_progs

---

lib/sles4sap/console_redirection/redirection_data_tools.pm
schedule/sles4sap/sap_deployment_automation_framework/ensa2_scenarios.yml
t/36_redirection_data_tools.t
tests/sles4sap/redirection_tests/ensa2_setup_Netweaver_WebGUI_access.pm

Setup SDAF Netweaver WebGUI access 
Related ticket: [TEAM-10579](https://jira.suse.com/browse/TEAM-10579) - [SDAF] Setup Netweaver WebGUI access 
https://openqaworker15.qa.suse.cz/tests/340062#step/ensa2_setup_Netweaver_WebGUI_access/155 (Retry detected when `curl` fails. Added retry mechanism as `curl` usually fails in the first few runs)
https://openqaworker15.qa.suse.cz/tests/340062#step/ensa2_setup_Netweaver_WebGUI_access/209 (WebUI access passed on all nw hosts)
One more failed VR for testing `Retry mechanism failed`: https://openqaworker15.qa.suse.cz/tests/340093#step/ensa2_setup_Netweaver_WebGUI_access/678 (Retry failed and post_fail_hook was invoked as expected, the post_fail_hook fail can be tracked by JIRA ticket …

Setup SDAF Netweaver WebGUI access

---

lib/x11test.pm

All three modules have their welcome needle counterpart created, however it is not visible in the test runs (popup shows up once at launch and is global).
Failure: https://openqa.opensuse.org/tests/5281998#step/oocalc/4
VR:
- https://openqa.opensuse.org/tests/overview?distri=opensuse&build=foursixnine%2Fos-autoinst-distri-opensuse%2323205&version=Staging%3AE

Handle new LibreOffice welcome popup

---

tests/containers/python_runtime.pm

- Describe upstream patches used in $runtime-py test
- Use `CONTAINER_RUNTIMES` by default when called with `CONTAINER_TESTS` like done in the VR.
Verification run: https://openqa.opensuse.org/tests/5284744

podman-py: Minor fixes

---

schedule/yam/agama_extended.yaml
schedule/yam/agama_extended_unattended.yaml
test_data/yam/agama_sle_extended_unattended.yaml
tests/yam/validate/validate_bootloader_timeout.pm

Like a safety and for completeness, we could have a test module to check the value in /etc/default/grub and add that module to both interactive and unattended with different values per each.
- Related ticket: https://progress.opensuse.org/issues/184073#change-991524
- Related MR: https://gitlab.suse.de/qe-yam/openqa-job-groups/-/merge_requests/565
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/overview?version=16.0&build=lemon-suse%2Fos-autoinst-distri-opensuse%23enhance-bootloader-timeout&distri=sle

Validate bootloader timeout value

---

data/journal_check/bug_refs.json
tests/console/snapper_create.pm
tests/console/snapper_jeos_cli.pm

- ticket: https://progress.opensuse.org/issues/186678
Tackle typing issues by using `serial_console` instead of tty and vnc.
Try to wait until the load settles after snapper actions.
Remove bugref boo#1197904 - This has been fixed in QU4 images that we should use in sle15sp4
PoC: https://openqa.suse.de/tests/18886279#step/snapper_jeos_cli/1
* https://openqa.suse.de/tests/overview?distri=sle&version=15-SP4&build=poo186678_investigation2

Reduce test unstabilities when rollback

---

lib/main_common.pm

SAP MinimalVM images are built only against sle16.0 product, therefore `sapconf` should not be applicable
- sle-16.0-Minimal-VM-Cloud-sap-x86_64-Build33.1-minimalvm-cloud-init@uefi-virtio-vga -> https://openqa.suse.de/tests/19030742

Skip sapconf in MinimalVM

---

tests/elemental3/generate_image.pm

Due to recent changes in the file naming, the download of the sysext images are not working anymore without this fix.
- Failing run: https://openqa.suse.de/tests/19029343
- Verification run: TO BE DONE

Fix Elemental3 systexts download

---

tests/elemental3/test_image.pm

Due to the changes added in PR https://github.com/SUSE/elemental/pull/168 we should start the RKE2 service during the test.
- Failing run: https://openqa.suse.de/tests/19031687
- Verification run: https://openqa.suse.de/tests/19031866

Fix Elemental3 RKE2 start

---

lib/containers/bats.pm

Ignore coredumps generated on SIGQUIT like those seen [here](https://openqa.opensuse.org/tests/5288928#step/docker_compose/161).  This is a bad practice seen on some base images like the official nginx.
Opened an issue upstream: https://github.com/nginx/docker-nginx/issues/1000

bats: Ignore coredumps generated on SIGQUIT

---

data/containers/bats/skip.yaml
lib/containers/bats.pm
tests/containers/bats/README.md
tests/containers/bats/aardvark.pm
tests/containers/bats/buildah.pm
tests/containers/bats/conmon.pm
tests/containers/bats/netavark.pm
tests/containers/bats/podman.pm
tests/containers/bats/runc.pm
tests/containers/bats/skopeo.pm

Export patch_sources to reuse by other modules like `docker_compose`, `python_runtime` and the upcoming `podman_e2e`.  Also rename the relevant `BATS_` variables.
- Verification run: https://openqa.opensuse.org/tests/5292129#step/aardvark/178

bats: Export patch_sources to reuse by other modules

---

lib/containers/bats.pm
tests/containers/bats/aardvark.pm
tests/containers/bats/buildah.pm
tests/containers/bats/conmon.pm
tests/containers/bats/netavark.pm
tests/containers/bats/podman.pm
tests/containers/bats/runc.pm
tests/containers/bats/skopeo.pm
tests/containers/docker_compose.pm

Make docker_compose reuse patch_sources from bats library.  No functional change.
Verification runs: 
- https://openqa.opensuse.org/tests/5292326#step/aardvark/178
- https://openqa.opensuse.org/tests/5292325

Make docker_compose reuse patch_sources from bats library

---

tests/containers/python_runtime.pm

Reuse bats functions in podman-py/docker-py tests.
- docker-py: https://openqa.opensuse.org/tests/5292387
- podman-py: https://openqa.opensuse.org/tests/5292392

Reuse bats functions in python_runtime

---

lib/hacluster.pm

This pr adds the fix contained in https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/23102/files in the second instance of this logic that exists on this file.
- Related ticket: https://jira.suse.com/browse/TEAM-10587

Fix crmsh version command regex

---

lib/nvidia_utils.pm

bsc#1249098 - Nvidia has changed dependency logic in newer drivers and we need to force installation of nvidia-persistenced to be compatible with older drivers.
- Related ticket: https://bugzilla.suse.com/show_bug.cgi?id=1249098#c6
- Needles:  None
- Verification run: https://openqa.suse.de/tests/19056601

nvidia: Add nvidia-persistenced installation workaround

---

data/yam/agama/auto/lib/base.libsonnet
data/yam/agama/auto/template.libsonnet
schedule/yam/agama_extended_unattended.yaml
schedule/yam/agama_extended_unattended_ppc64le.yaml
schedule/yam/agama_extended_unattended_s390x.yaml
tests/yam/validate/validate_extra_kernel_params.pm

- Related ticket: https://progress.opensuse.org/issues/184079
- Verification run: [vrs for extended_unattended testsuites](https://openqa.suse.de/tests/overview?build=chcao_184079&version=16.0&distri=sle); [vrs for other randomly picked unattended testsuites](https://openqa.suse.de/tests/overview?distri=sle&build=chcao_184079_2&version=16.0)  
- Related mr: https://gitlab.suse.de/qe-yam/openqa-job-groups/-/merge_requests/563

Add kernel parameters to bootloader section

---

data/supportserver/samba/krb5.conf
tests/network/samba/samba_adcli.pm

using the FIPS:AD-SUPPORT policy variant, kerberos init and domain join works; for the still failing winbind authentication we opened a separate bug:
https://bugzilla.suse.com/show_bug.cgi?id=1249042 and softfailed this test. 
- Related ticket: https://progress.opensuse.org/issues/176940
- Needles: no
- Verification run: https://openqa.suse.de/tests/19040340#step/samba_adcli/208

Use sub-policy for samba in FIPS mode

---

lib/power_action_utils.pm

Current logic will check LPAR status at once after shutting down the PVM setup.
The code change will help a bit to capture video logs in case shutdown fails
- Verification run: https://openqa.suse.de/tests/19056432
See https://openqa.suse.de/tests/19056432/video?filename=video.webm, it can show more logs after executing poweroff command.

Capture video logs after shutting down PVM setups

---

lib/main_common.pm
tests/x11/ibus/ibus_installation.pm

Use ibus-libpinyin instead of ibus-pinyin for SLE16+ 
Only enable ibus_installation for SLE16+ due to bsc#1248831
- Related ticket: https://progress.opensuse.org/issues/188457
- Needles: N/A
> SLE16 : https://openqa.suse.de/tests/19055771
> SLE15 SP7 : https://openqa.suse.de/tests/19055791

Use ibus-libpinyin for SLE16 and above

---

tests/security/openscap/oscap_setup.pm

Ticket: https://progress.opensuse.org/issues/184861
The oscap testsuite requires xmllint to work, with the switch to grub2-bls xmllint won't be installed in the system by default, instead of having multiple if/else install the binary by path
VR:
- TW: https://openqa.opensuse.org/tests/5297058#step/oscap_setup/2
- SLE 12-SP5: https://openqa.suse.de/tests/19073846#step/oscap_setup/2
Failures in TW are: https://progress.opensuse.org/issues/177378

Explicitly install xmllint in the oscap as the test suite depends on it

---

tests/security/secureboot/kernel_lockdown.pm

Ticket: https://progress.opensuse.org/issues/184861
The test doesn't fail per se on normal Tumbleweed, but with the grub2-bls changes it would: https://openqa.opensuse.org/tests/5294088
VR: https://openqa.opensuse.org/tests/5297311

Explicitly install mokutil in kernel_lockdown test

---

tests/console/consoletest_setup.pm

- Use a higher timeout to succeed even on *very* slow machines like RISC-V with -cpu max
- Use pipefail to detect failure
- Failure: https://openqa.opensuse.org/tests/5292893#step/consoletest_setup/30 (there is no output)
- Verification run: https://openqa.opensuse.org/tests/5297451

console/consoletest_setup.pm: More reliable ssh-keyscan invocation

---

tests/security/verify_fips_packages.pm

Update the test to install packages then compare with certified versions. Modify for more certified SLE versions.
- Related ticket: https://progress.opensuse.org/issues/136199
- 15-SP4: https://openqa.suse.de/tests/19123458
- 15-SP6: https://openqa.suse.de/tests/19123457

Determine FIPS packages versions and install

---

data/containers/bats/skip.yaml
data/containers/patches/runc/4893.patch
tests/containers/bats/runc.pm

Backport https://github.com/opencontainers/runc/pull/4893 to re-enable cgroups test on ppc64le
- SLES 16.0: https://openqa.suse.de/tests/19137322
- Tumbleweed: https://openqa.opensuse.org/tests/5313598

bats/runc: Backport PR#4893 to re-enable cgroups test on ppc64le

---

schedule/yam/agama_migration_15sp7.yaml

Move validate_migration_logs to first validation module, rename it to upload_* to make it clear meaning.
- Needles: N/A

Move validate_migration_logs to first

---

tests/yam/migration/migration_unattended.pm

As https://bugzilla.suse.com/show_bug.cgi?id=1248998#c17, disable repos of the product to migrate from due to proxySCC is not serving SLES 15 SP*.
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/19144207#step/migration_unattended/10

Disable original repos before migration

---

tests/kernel/run_kselftests.pm

This will prevent timeouts.
- https://openqa.suse.de/tests/19136516
- https://openqa.suse.de/tests/19144639
Co-developed-by: Sebastian Chlad <sebastian.chlad@suse.com> @schlad

Kselftests: Use utils::write_sut_file for writing log file

---

tests/network/samba/samba_adcli.pm

Ticket: https://progress.opensuse.org/issues/188754
VRs:
* 15-SP5: https://openqa.suse.de/tests/19145033
* 15-SP4: https://openqa.suse.de/tests/19145032
* 15-SP2: https://openqa.suse.de/tests/19145031

samba_adcli: restore original network config before exiting

---

tests/containers/host_configuration.pm
tests/containers/run_container_in_k3s.pm

The apparmor profiles in sle12sp5 are too old for k3s, in such a case we need to boot with turned off apparmor. Otherwise we deal with hanging pods
```
Warning  Failed     1s (x3 over 25s)     kubelet            (combined
from similar events): Error: failed to create containerd container: load
apparmor profile /tmp/cri-containerd.apparmor.d2752965126: parser
error("AppArmor parser error for
/tmp/cri-containerd.apparmor.d2752965126 in
/tmp/cri-containerd.apparmor.d2752965126 at line 14: syntax error,
unexpected TOK_OPENPAREN, expecting TOK_MODE"): exit status 1"")
```
The other part of the fix is to avoid testing busybox in k3s. We just need to test image of our interest.
- Verification run: http://kepler.suse.cz/tests/25284#step/run_container_in_k3s/30

Workaround k3s apparmor issue in sle12sp5

---

data/virt_autotest/guest_params_xml_files/sles_16_64_kvm_hvm_x86_64_agama_online_iso.xml
lib/virt_autotest/virtual_network_utils.pm
tests/virt_autotest/virt_utils.pm

- Related ticket: https://progress.opensuse.org/issues/188127
VIRTUAL NETWORK:
kermit[uefi-gi-guest_developing-on-host_developing-kvm](https://openqa.suse.de/tests/19040842#step/libvirt_isolated_virtual_network/90) pass
scooter[uefi-gi-guest_developing-on-host_developing-kvm](https://openqa.suse.de/tests/19040840#step/libvirt_isolated_virtual_network/90) pass
bare-metal1[uefi-gi-guest_developing-on-host_developing-kvm](https://openqa.suse.de/tests/19040839#step/libvirt_isolated_virtual_network/90) pass
bare-metal2[uefi-gi-guest_developing-on-host_developing-kvm](https://openqa.suse.de/tests/19040838#step/libvirt_isolated_virtual_network/90) pass
bare-metal6[uefi-gi-guest_developing-on-host_developing-kvm](https://openqa.suse.de/tests/19040843#step/libvirt_isolated_virt …

Deploy sles16 guest system with br0 for virtual network runs

---

data/security/secureboot/parsesign.go
schedule/security/aarch64_secureboot.yaml
schedule/security/sle16/agama-create-hdd-textmode.yaml
schedule/security/sle16/agama-create-hdd-textmode_s390x_kvm.yaml
schedule/security/sle16/agama.yaml
tests/security/secureboot/validate_keylength.pm

This test follows an unusual approach. We don't need to actually secure boot to check the signature length, as the signature is embedded in the binary image of the kernel (also in the bootloader). I prepared [a tool](https://github.com/ilmanzo/autograph-pls) that parses and extract the last valid ASN.1 structure found in a binary, so from the signature we can infer the key modulus (hence the length)  
- Related ticket: https://progress.opensuse.org/issues/176943
- Needles: 
```
s390x-kvm  https://openqa.suse.de/tests/19145172
ppc64le    https://openqa.suse.de/tests/19145173
aarch64    https://openqa.suse.de/tests/19145174
x86_64     https://openqa.suse.de/tests/19145176
```
(ppc64le fail in a later step is unrelated)

Add test to validate secure boot signing key length

---

tests/publiccloud/check_services.pm

Previous #23348 had a `screenshot` argument in the `record_info` function:
- Verification run: https://openqa.suse.de/tests/19157957#step/check_services/32 --> Fails as expected :)

Fix for the check_services function

---

tests/yam/migration/migration_unattended.pm

- Looks like we need to wait longer for GRUB to appear.
- Verification run: https://openqa.suse.de/tests/19154328

Bump timeout for migration_unattended grub needle

---

lib/publiccloud/instance.pm

In publiccloud `softreboot`, fix the condition of the message on stop-fail case:
The `wait_for_ssh` routine, when all ok, returns a defined value, as on starting as on stopping case. 
Then, in `softreboot`, when instance fails to stop in `wait_for_ssh`, the returned value is `not defined` and in that case message shall be printed and **not in ok pass** cases.
- VR, WAIT STOP OK, in:
https://openqa.suse.de/tests/19159457#step/patch_and_reboot/193, sle-micro-6.0-GCE
https://openqa.suse.de/tests/19159458#step/patch_and_reboot/84, sle-15-SP7-Azure
https://openqa.suse.de/tests/19159760, sle-15-SP4-Azure-**SAP**

softreboot: fix the condition of the message on stop-fail case

---

tests/xfstests/partition.pm

The fsgqa/fsgqa2 user added by ibs as a normal user, but didn't add in krb5 scenario.
- Related ticket: https://progress.opensuse.org/issues/188853
- https://openqa.suse.de/tests/19132345#step/partition/93
- https://openqa.suse.de/tests/19154322
- The test fail is OK, it's because of bsc#1249996, but the lack of configure was find during debugging the issue.

xfstests: Add fsgqa user in NFS krb5 scenario

---

lib/mr_test_lib.pm
schedule/ha/bv/pvm_ha_priority_fencing.yaml
schedule/ha/bv/pvm_ha_qdevice_node.yaml
schedule/ha/bv/pvm_ha_qnetd_server.yaml
schedule/ha/bv/pvm_pacemaker_cts_regression.yaml
schedule/sles4sap/hana/pvm_hana_cluster_node_sle16.yaml

After test passed successfully on ppc64le-hmc workers, we should poweroff the system properly.
This change does not include YAML schedule files which are only used in 15SPx pre-release job groups.
- Related ticket: https://jira.suse.com/browse/TEAM-10556
saptune: https://openqa.suse.de/tests/19165321#step/shutdown/1
hanasr: https://openqa.suse.de/tests/19155427#step/shutdown/1
pacemaker_cts_regression: https://openqa.suse.de/tests/19154280#step/shutdown/1
diskless_sbd_qdevice: https://openqa.suse.de/tests/19156014#step/shutdown/1
priority_fencing: https://openqa.suse.de/tests/19040030#step/shutdown/1

HA/SAP: shutdown LPAR after test on PowerVM platform

---

lib/main_common.pm
lib/virt_autotest/virtual_network_utils.pm
tests/virt_autotest/libvirt_nated_virtual_network.pm
tests/virt_autotest/libvirt_virtual_network_init.pm

Related ticket: https://progress.opensuse.org/issues/175186
- Add `ENABLE_NATED_VIR_NET` to switch on the libvirt_nated_virtual_network tests.
- Remove the soft failure warning as [bsc#1214223](https://bugzilla.suse.com/show_bug.cgi?id=1214223) has been fixed.
- Create `ifcfg-$nic` files in guests for all network tests on sle15 or lower.
- Need not copy `ifcfg-*` files from the host to guests as they are created during network tests, besides the interface name is unknown at the moment yet
//virtual-network-test
[MU sle15sp7 qam-kvm-install-and-virtual-network-test](https://openqa.suse.de/tests/19144235)
[MU sle12sp5 qam-kvm-install-and-virtual-network-test](https://openqa.suse.de/tests/19144495)
[MU sle15sp6 qam-kvm-install-and-virtual-network-test](https://openqa.suse.d …

Support to run bridge virtual network tests in virt MU

---

tests/installation/ipxe_install.pm

To allow PRG1 lab moved MU test machines capable to run development VT test in autoyast mode, `IPXE_SET_HDD_BOOTSCRIPT` needs to be supported. This PR adds this capability in code.
Related ticket: https://progress.opensuse.org/issues/184291
- jarjarbinks,worker37:51 (supports 12sp5)
- development 15sp7 xen: https://openqa.suse.de/tests/19144133#, cancel after key rebooting after installation validated(with fix of support IPXE_SET_HDD_BOOTSCRIPT in autoyast VIRT_AUTOTEST installation)
- briza(supports sriov), worker37:49
- MU kvm sriov(15sp6): https://openqa.suse.de/tests/19131848, pass
- MU xen sriov(15sp6): https://openqa.suse.de/tests/19132175, pass
- development 15sp7 kvm: https://openqa.suse.de/tests/19144194 , pass
- regression test with existing OSD machines for …

Support running development VT test on PRG1 MU machines with IPXE_SET_HDD_BOOTSCRIPT

---

data/containers/bats/skip.yaml
data/containers/bats/xfails.py

- Fine-tune BATS_IGNORE variables
- No need to print suitename in xfails.

Minor BATS fixes with Junit

---

lib/virt_autotest/common.pm

Support efi guests only when testing sev-snp
- Related ticket: https://progress.opensuse.org/issues/189042
- Needles: n/a
[MU sles15SP7 non-sev-snp tesitng](https://openqa.suse.de/tests/19166415)
[MU sles15sp7 sev-snp testing](https://openqa.suse.de/tests/19169740)

Support efi guests only when testing sev-snp

---

tests/yam/migration/migration_unattended.pm
tests/yam/validate/validate_migration_logs.pm
tests/yam/validate/validate_product.pm

Need upload logs of /var/cache/wicked_config, /var/cache/udev_rules and /etc/udev/rules.d after migration.
- Needles: N/A
https://openqa.suse.de/tests/19181392#details s390x kvm
https://openqa.suse.de/tests/19166313#live regression test on power 10 kvm

Upload logs after migration

---

tests/console/firewalld.pm

15sp3/sp4 don't have iptables-backend-nft package
15sp3/sp4 and sle-micro 6.1 iptables use legacy backend
- Verification run: https://openqa.suse.de/tests/overview?arch=&flavor=&machine=&test=&modules=firewalld&module_re=&group_glob=&not_group_glob=&comment=&distri=sle&version=15-SP4&build=20250921-1&groupid=414# 
https://openqa.suse.de/tests/overview?arch=&flavor=&machine=&test=&modules=firewalld&module_re=&group_glob=&not_group_glob=&comment=&distri=sle&version=15-SP3&build=20250921-1&groupid=414#
https://openqa.suse.de/tests/overview?distri=sle-micro&version=6.1&build=S.91.2&groupid=568

Products 15sp3/sp4 and sle-micro 6.1 iptables use legacy backend

---

tests/elemental/container_validation.pm

With some images we can see timeout during the image pulling. Increasing the timeout fixes the issue.
- Needles: N/A
- Verification run: Validated on my local lab with 6.2 OS images

Fix Elemental2 sporadic timeout

---

data/journal_check/bug_refs.json

Add known bugs coming from the VMware host.
- Example failure: https://openqa.suse.de/tests/19147098#step/journal_check/4
- Verification run: https://openqa.suse.de/tests/19181724

Add known bugs for VMware

---

tests/kernel/update_kernel.pm

The `install_ltp` test module already supports adding new boot choices to GRUB menu with different boot options. The `APPEND_GRUB_PARAMS` will modify the common command line options which apply to all boot menu choices. The boot params will also be added before the first reboot in `update_kernel` to allow applying workarounds if the kernel to be installed cannot boot with default settings.
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/19207742

update_kernel: Allow adding GRUB params from job settings

---

lib/containers/bats.pm

Increase timeout for installing packages.
Failing test: https://openqa.opensuse.org/tests/5342172#step/podman/47

bats: Increase timeout for installing packages

---

data/sles4sap/agama/sles_sap_default_baremetal.jsonnet
schedule/sles4sap/installation/sles4sap_gnome_saptune_baremetal_16.yaml
tests/installation/ipxe_install.pm
tests/sles4sap/saptune/mr_test_run.pm

Add saptune test for SLE 16.0 for SAP on bare metal, and this test only works at textmode on OSD because VNC connection is not good so far on SLE 16.0.
**Note**: Dawei provided the change about ipxe_install.pm module.
- Related ticket: https://jira.suse.com/browse/TEAM-10622
- Verification run: https://openqa.suse.de/tests/19207749 (failed because mr_test code needs to update for SLE 16.0)

Add sles4sap_textmode_saptune_baremetal test for SLE 16.0 for SAP

---

schedule/sles4sap/hana/pvm_hana.yaml
schedule/sles4sap/hana/pvm_hana_cluster_node.yaml
schedule/sles4sap/installation/install_sles4sap_pvm.yaml

This is a followup of https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/23366, adding shutdown test step for SLE15SP7 QR job groups.
- Related ticket: https://jira.suse.com/browse/TEAM-10556
install_sles4sap_pvm.yaml: https://openqa.suse.de/tests/19216450#step/shutdown/1
pvm_hana_cluster_node.yaml: https://openqa.suse.de/tests/19216015#step/shutdown/1
pvm_hana.yaml: only used in WDF, no corresponding job in osd. But it is similar to `install_sles4sap_pvm.yaml`, so this change should not cause trouble.

HA/SAP: shutdown LPAR after test on PowerVM platform for SLE15

---

tests/containers/python_docker.pm

Do not fail when creating /root/.docker
Failing test: https://openqa.opensuse.org/tests/5345844#step/python_docker/12

python_docker: ~/.docker may already exist

---

lib/sles4sap/sap_deployment_automation_framework/basetest.pm

Upload logs when execute_playbooks failed
Related ticket:
[TEAM-10644](https://jira.suse.com/browse/TEAM-10644) - Enabled SDAF HanaSR and SDAF ENSA2 Tests in Nightly Run for 15-SP7
[TEAM-10648](https://jira.suse.com/browse/TEAM-10648) - [SDAF] upload logs when execute_playbooks failed
HanaSR, when execute_playbooks failed the logs are uploaded:
http://openqaworker15.qa.suse.cz/tests/343716#downloads
http://openqaworker15.qa.suse.cz/tests/343723#downloads
ENSA2, when execute_playbooks failed the logs are uploaded:
http://openqaworker15.qa.suse.cz/tests/343717#downloads

Upload logs when execute_playbooks failed

---

data/containers/patch_junit.py

Adapt prefix to OCI_RUNTIME.
- aardvark-dns: https://openqa.opensuse.org/tests/5348071
- conmon: https://openqa.opensuse.org/tests/5348065
- runc: https://openqa.opensuse.org/tests/5348069

patch_junit: Adapt prefix to OCI_RUNTIME

---

tests/yam/migration/migration_unattended.pm

The default timeout is set to 1s for the migration grub menu which is too short to catch the menu needle. So disable timeout for migration grub menu.
- Related ticket: https://progress.opensuse.org/issues/187626#note-18
- Verification run: [verification_runs_link](https://openqa.suse.de/tests/overview?build=chcao_grub2&distri=sle&version=16.0)

Disable timeout for migration grub menu

---

schedule/yam/agama_extensions_and_patterns_unattended_without_custom_url.yaml
schedule/yam/agama_extensions_and_patterns_unattended_without_custom_url_ppc64le.yaml
schedule/yam/agama_extensions_and_patterns_unattended_without_custom_url_s390x.yaml
schedule/yam/agama_extensions_and_patterns_without_custom_url.yaml
schedule/yam/agama_extensions_and_patterns_without_custom_url_s390x.yaml

For SUSEConnect won't be created if not custom url in development group, refer to https://suse.slack.com/archives/C02AYV7UJSD/p1757326448201469 We need drop validate_suseconnect_url for development group.
- Related MR:  https://gitlab.suse.de/qe-yam/openqa-job-groups/-/merge_requests/601
- Needles:N/A
- Verification run: https://openqa.suse.de/tests/overview?version=16.0&build=lemon-suse%2Fos-autoinst-distri-opensuse%23create-schedule-without-validate_suseconnect_url&distri=sle

Create schedule file without validate_suseconnect_url

---

tests/publiccloud/ssh_interactive_end.pm

`ssh_interactive_end` is the last module on some Public Cloud jobs, doesn't test anything and should NOT mark the job as failed.
Failed job: https://openqa.suse.de/tests/19235692#step/ssh_interactive_end/92

pc/ssh_interactive_end: Ignore failure on module

---

lib/nvidia_utils.pm

- https://openqa.suse.de/tests/19247930 (Micro 6.1)
- https://openqa.suse.de/tests/19247946 (SLE15-SP6 baremetal)
- https://openqa.suse.de/tests/19189361#step/nvidia/50 (SLE15-SP5 Public Cloud *BEFORE* - pulls package from wrong repo)
- https://openqa.suse.de/tests/19247948#step/nvidia/51 (SLE15-SP5 Public Cloud *AFTER* - fails correctly as the package is not found)

nvidia: Mutually exclude other variants' repositories

---

tests/containers/bci_prepare.pm

Fix RMT with the help of https://github.com/SUSE/BCI-tests/pull/914
- Related ticket: https://progress.opensuse.org/issues/189084
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/19248741#step/bci_test_podman/1
All VRs cloned with removed `CONTAINER_RUNTIMES=k3s`.

Fix RMT testing

---

tests/sles4sap/qesapdeployment/configure.pm

Remove get_required_var for a no more used variable. In particular the variable was written on a template variable `$variables{STORAGE_ACCOUNT_NAME}` never used in any config.yaml file.
- Related ticket: https://jira.suse.com/browse/TEAM-10654
http://openqaworker15.qa.suse.cz/tests/344605
http://openqaworker15.qa.suse.cz/tests/344758
Both fails but later than the fix and due to a JobGroup configuration

Remove use of STORAGE_ACCOUNT_NAME

---

lib/publiccloud/gce.pm
lib/publiccloud/instance.pm
lib/publiccloud/provider.pm
tests/publiccloud/check_registercloudguest.pm
tests/publiccloud/img_proof.pm
tests/publiccloud/migration.pm
tests/publiccloud/prepare_instance.pm
tests/publiccloud/run_ltp.pm

Fix missing _instance_ on-error in post-fail-`finalize`.
CSP instance available in create instance after terraform_apply,
then in wait_for_ssh on-error is lost and 'finalize' cannot use it:
recover in 'finalize' the saved instance.
In gce::upload_boot_diagnostics added check of availability zone too.
- Related ticket: https://progress.opensuse.org/issues/188586
https://openqa.suse.de/tests/19234580
https://openqa.suse.de/tests/19234580/logfile?filename=autoinst-log.txt#line-2659
[fake error added in wait_for_ssh after systemcheck loop, to trigger finalize; removed after VR].
https://openqa.suse.de/tests/19234579#step/prepare_instance/1
[successful version]

Publiccloud: fix missing instance on-error  in finalize

---

tests/qam-updinstall/update_install.pm

Partially revert a622dc39735b8f608ad6fb247bf801d923494683, first part where required @patch_l2, @patch_l3 arrays are created. If patch was already installed force install packages from patch and softfail, debug experiment.
- Related ticket: https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/23483
https://dzedro.suse.cz/tests/3176
https://dzedro.suse.cz/tests/3177

update_install: Check patch log if patch has been already installed

---

lib/containers/bats.pm
tests/containers/bats/netavark.pm

Drop ncat dependency on Tumbleweed as it's no longer needed on netavark v1.16.0.
Verification run: https://openqa.opensuse.org/tests/5290240
NOTES:
- The above VR was cloned with `BATS_TEST_REPOS=https://download.opensuse.org/repositories/home:/danishprakash:/branches:/devel:/microos/openSUSE_Tumbleweed/home:danishprakash:branches:devel:microos.repo`

bats/netavark: ncat is no longer needed on netavark v1.16.0

---

lib/Utils/Logging.pm

Use Bash builtin instead of grep to avoid spawning a new process.
- Related ticket: https://progress.opensuse.org/issues/187572

record_avc_selinux_alerts: Use Bash builtin instead of grep

---

tests/fips/gnutls/gnutls_base_check.pm

Avoid killall, sometimes it's not installed. 
- Related ticket: https://progress.opensuse.org/issues/188508
- https://openqa.suse.de/tests/19277659
- https://openqa.opensuse.org/tests/5364903

Avoid killall

---

lib/containers/bats.pm

The `proceed_on_failure` parameter is used only for the `script_output` family of calls.
See https://open.qa/api/testapi/#_script_run

bats: proceed_on_failure is not used with script_run

---

tests/kernel/run_kselftests.pm

- https://rmarliere-openqa.qe.prg2.suse.org/tests/1598 **before**
- https://rmarliere-openqa.qe.prg2.suse.org/tests/1599 **after**

Kselftests: Only use `--per-test-log` if running multiple tests

---

data/autoyast_opensuse/opensuse_gnome.xml

Autoyast is 'dying' - but contains business logic to switch to graphical.target
whenever xdm is being installed
with GMOME 49, GNOME became Wayland-only, making the presence of Xorg, and also xdm,
less of a common thing. Installing the default gnome-pattern will result in
a system running gdm directly via systemd service instead of relying on the xdm
wrapper.
- Related ticket: https://bugzilla.opensuse.org/show_bug.cgi?id=1250672
- Needles: N/A

autoyast: set default target for opensuse_gnome

---

lib/containers/bats.pm
tests/containers/bats/aardvark.pm
tests/containers/bats/netavark.pm

netavark is now the only consumer so call it externally.
- Verification run: https://openqa.suse.de/tests/19299974

bats: Export install_ncat

---

lib/publiccloud/instance.pm
variables.md

We got use case where we need to ignore guestregister failures for PAYG image . Easiest way to achieve this is by introducing special variable 
VRs : https://openqa.suse.de/tests/19300344 ( failing w/o variable ) 
https://openqa.suse.de/tests/19300352 ( with variable )

Allow to ignore failures in wait_for_guestregister

---

lib/publiccloud/instance.pm
variables.md

Pub.Cloid `supportconfig`, fix breaking failures:
- Fix timeout management in supportconfig upload,avoiding stop run 
- Skip log upload when supportconfig failed
- Fix supportconfig exclusion tokens (w.a. [bsc#1250310](https://bugzilla.suse.com/show_bug.cgi?id=1250310#c2)
- Add log messages in post/hooks to clarify the cleanup type in logs
The `supportconfig` tool resulted to have a fatal stop at `Updates` token for `SLE 12-SP5` images(at least); excluded for that version, being the solution in charge to bsc#1250310.
- Related ticket:[187440](https://progress.opensuse.org/issues/187440)
sle-12-SP5-GCE-Updates publiccloud_containers
https://openqa.suse.de/tests/19277561#step/ssh_interactive_end/116
sle-12-SP5-EC2-Updates publiccloud_img_proof …

P.C. supportconfig logs: fix breaking failures

---

lib/publiccloud/basetest.pm

Pub.Cl. `supportconfig`: skip supportconfig execution and its logs collection for successful tests or modules, only let it run when test failed, in post_fail_hooks.
This in particular useful for `SLE-12-SP5` versions, able to consume very long time to run such command.
- Related ticket: https://progress.opensuse.org/issues/187440

P.C. supportconfig: skip run for successful tests
