os-autoinst/os-autoinst-distri-opensuse

- tests/console/xorg_vt.pm
> xorg_vt: Update summary for a more descriptive

- tests/x11/window_system.pm
> window_system: Update summary for a more descriptive text

- tests/console/curl_ipv6.pm
for usage with https://confluence.suse.com/pages/viewpage.action?spaceKey=~martinsmac&title=Script+collecting+testcase+coverage
> curl_ipv6: update summary with a more descriptive text

- tests/autoyast/wicked.pm
> wicked: Update summary for a more descriptive text

- tests/x11/xterm.pm
> xterm: Update summary for a more descriptive text

- lib/main_common.pm
- Related ticket: https://progress.opensuse.org/issues/51695
> ntp test won't be running on tumbleweed

- tests/console/yast2_clone_system.pm
- tests/security/apparmor/aa_autodep.pm
> Tidy up code

- lib/main_common.pm
Needs https://github.com/os-autoinst/os-autoinst/pull/1190
> Use separate "code"+"vars" UEFI firmware parts

- tests/network/vsftpd.pm
> vsftd: Update summary for a more descriptive text

- tests/support_server/wait_children.pm
> wait_children: Update summary for a more descriptive text

- tests/console/wavpack.pm
> wavpack: Update summary for a more descriptive text

- tests/console/wget_ipv6.pm
> wget_ipv6: Update summary for a more descriptive text

- tests/installation/welcome.pm
> welcome: Update summary for a more descriptive text

- tests/security/apparmor_profile/usr_lib_dovecot_imap.pm
- tests/security/apparmor_profile/usr_lib_dovecot_pop3.pm
- tests/security/apparmor_profile/usr_sbin_dovecot.pm
- tests/security/apparmor_profile/usr_sbin_nscd.pm
- tests/security/apparmor_profile/usr_sbin_smbd.pm
- tests/security/apparmor_profile/usr_sbin_traceroute.pm
> apparmor_profile: Update summary for a more descriptive text

- tests/console/vim.pm
> vim: Update summary for a more descriptive text

- tests/x11/remote_desktop/vino_screensharing_available.pm
> vino_screensharing_available: Update summary for a more descriptive text

- tests/x11/vnc_two_passwords.pm
> vnc_two_passwords: Update summary for a more descriptive text

- tests/autoyast/installation.pm
- Related ticket: https://progress.opensuse.org/issues/55220
- Verification run: http://quasar.suse.cz/tests/3562#step/installation/5
> Handle "Validation Check Failed" of Nv repo in AY installation

- lib/registration.pm
Ugly workaround for nvidia failed validation check; imports fishy GPG key.
Related to PR#8154
- Related ticket: https://progress.opensuse.org/issues/55217
- Needles: N/A (same as PR#8154)
- Verification run: http://dreamyhamster.suse.cz/tests/752
> Add ugly workaround for nvidia repo failed validation check

- lib/y2_module_consoletest.pm
- tests/console/yast2_clone_system.pm
[Verification run](https://openqa.opensuse.org/tests/1001898#).
> Upload autoyast xml schema if validation fails

- lib/y2_module_consoletest.pm
- tests/console/yast2_clone_system.pm
[Verification run](https://openqa.opensuse.org/tests/1001917#).
> Fix save_upload_y2logs call in y2_module_consoletest

- tests/console/sshd.pm
- tests/network/openvpn_client.pm
- tests/network/openvpn_server.pm
Hello,
in QAM we use openQA tests for our regression testing and because of that it's useful to be a bit more descriptive when writing the summary of the test so everyone know what the test exactly does. Because of that I'm updating summaries of tests I maintain.
> Update summaries of tests I maintain

- data/autoyast_opensuse/opensuse_gnome.xml
- Related ticket: https://bugzilla.suse.com/show_bug.cgi?id=1144439
- Needles: N/A
- Verification run: https://openqa.opensuse.org/tests/1000671#
> AutoYaST: Add product selection to openSUSE_gnome.xml

- lib/kdump_utils.pm
To avoid hardcoding and coplex conditions
- Related ticket: https://progress.opensuse.org/issues/53660
> Determine kernel dynamically

- tests/boot/uefi_bootmenu.pm
- tests/console/timezone.pm
- tests/console/update_alternatives.pm
- tests/installation/user_settings.pm
- tests/installation/user_settings_root.pm
- tests/update/updates_packagekit_gpk.pm
- tests/x11/totem/totem_launch.pm
- tests/x11/tracker/tracker_by_command.pm
- tests/x11/tracker/tracker_info.pm
- tests/x11/tracker/tracker_search_in_nautilus.pm
- tests/x11/user_defined_snapshot.pm
> Update summaries for a more descriptive text

- lib/repo_tools.pm
SLE11 zypper have limited funcionality :(
> Dont pass no_gpg_check in zypper_ar on SLE11

- lib/utils.pm
> Fix parameter handling for zypper_ar

- data/autoyast_sle12/autoyast_wicked_aarch64.xml
- data/autoyast_sle12/autoyast_wicked_x86_64.xml
- schedule/create_hdd_autoyast_wicked.yaml
enable aarch64 tests
VR - 
https://openqa.suse.de/tests/3221297 - image creation
https://openqa.suse.de/tests/3224296 - usage of image
> wicked: enable aarch64 tests

- tests/installation/system_role.pm
See [poo#55229](https://progress.opensuse.org/issues/55229).
[Verification run](http://f174.suse.de/tests/283#).
> Scroll system roles list in case role is not visible

- tests/kernel/ib_tests.pm
It seems this is the best way to reliably get a system with an enabled
SDK repository, which we need for these tests.
This is a workaround, see also [https://progress.opensuse.org/issues/54773](https://progress.opensuse.org/issues/54773)
> Add SDK repositories for ib_tests

- lib/version_utils.pm
Added a documentation block for every function
- Related ticket: https://progress.opensuse.org/issues/54671
> Add documentation for version_utils

- data/wicked/check_macvtap.c
- lib/wickedbase.pm
- tests/wicked/advanced/sut/t15_macvtap_legacy.pm
- tests/wicked/advanced/sut/t16_macvtap_xml.pm
Fix macvtap failure
VR: 
https://openqa.suse.de/tests/3240801
> wicked: Fix macvtap failure

- tests/installation/releasenotes_origin.pm
We got same issue for SP2 and update soft-failure for it.
> Update release notes bug reference for SLE15 SP2

- lib/bootbasetest.pm
Related progress issues:
* https://progress.opensuse.org/issues/48671
* https://progress.opensuse.org/issues/42683
> Disable not reliable save_memory_dumps to prevent incompletes

- lib/registration.pm
Need change ha to sle-ha, as toolchain includes ha
- Related ticket: https://progress.opensuse.org/issues/54254
> Need change ha to sle-ha, as toolchain includes ha

- lib/sles4sap.pm
The method `test_start_instance` form `lib/sles4sap` checked for the SAP instance startup with a `ps` command. With this PR, it will check using a combination of sap commands:
- `sapcontrol -nr $instance -function GetSystemInstanceList`
- `sapcontrol -nr $instance -function GetProcessList`
This PR also introduces a time to wait for the instance to start (`WAIT_INSTANCE_START`) so as to avoid false negatives on slower machines.
- Needles: N/A
- Verification run: http://mango.suse.de/tests/1289 (NetWeaver), http://mango.suse.de/tests/1290 (Hana)
> Change test_start_instance so it checks with sapcontrol

- data/autoyast_sle12/autoyast_wicked_aarch64.xml
Add SDK to solve gcc installation on aarch64
VR : 
https://openqa.suse.de/tests/3247220 ( disk creation job ) 
https://openqa.suse.de/tests/3247750 ( using created image and showing ability to install gcc )
> wicked: Add SDK to solve gcc installation on aarch64

- lib/main_common.pm
- tests/console/podman_image.pm
Adding two workarounds...
Tumbleweed JeOS: http://10.160.67.86/tests/373 (fails, product fixed with https://build.opensuse.org/request/show/723536)
Leap 15.1 JeOS: http://10.160.67.86/tests/376
> podman_image: Fix test on JeOS, add to Leap 15.1+ as well

- tests/x11/firefox_audio.pm
see https://progress.opensuse.org/issues/54401
verification run:
https://openqa.opensuse.org/tests/1006387#next_previous
> Work around typing issue for firefox audio

- lib/service_check.pm
Sort service check list while looping.
- Related ticket: https://progress.opensuse.org/issues/55469
- Needles: n/a
- Verification run: http://openqa.suse.de/tests/3247058
> Sort service check list while looping

- lib/registration.pm
Reverts os-autoinst/os-autoinst-distri-opensuse#8205
> Revert "Do not expect for addon's licenses when upgrading to 12-SP5"

- lib/wickedbase.pm
- tests/wicked/before_test.pm
move add_serial_console into pre_run hook
VR: 
https://openqa.suse.de/tests/3247991
> wicked: move add_serial_console into pre_run hook

- lib/sles4sap.pm
As introduced in PR #8206, method `test_start_instance` now features a better check for the status of SAP services after a start. This PR introduces an improvement, allowing the method to wait for the services to be properly down (status `GRAY`) before attempting to issue a `sapcontrol -nr $instance -function Start`. As documented in https://wiki.scn.sap.com/wiki/display/SI/SAP+Startup+Troubleshooting+Guide+for+Netweaver+Application+Server, `Start` commands are ignored when services are in `GREEN` or `YELLOW` status, so it is possible in slower VMs for services to still be in the process of stopping (hence, status `YELLOW`), and ignore the `Start` command which will result in a failure.
- Needles: N/A
- Verification run: http://mango.suse.de/tests/1311 (NetWeaver), …
> Wait for SAP services to be GRAY before start

- tests/x11/yast2_lan_restart_devices.pm
See [poo#54407](https://progress.opensuse.org/issues/54407).
- Verification run: https://openqa.suse.de/tests/3264333#
> Exclude tests of bond devices on s390x

- tests/console/firewall_enabled.pm
- Related ticket: https://bugzilla.opensuse.org/show_bug.cgi?id=1144543
- Needles: N/A
- Verification run: https://openqa.opensuse.org/tests/1011264
> Record soft-fail on upgrade from SFW2-based-distro to TW: FW disabled

- lib/main_common.pm
- schedule/yast/lvm_encrypt_separate_boot.yaml
Addition to https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/8238
- Related ticket: https://progress.opensuse.org/issues/54779
>  Change validation modules for lvm encrypt in yaml for lvm_encrypt_separate_boot

- schedule/yast/sle/libstorage-ng/btrfs_libstorage-ng.yaml
- schedule/yast/sle/libstorage/btrfs_libstorage.yaml
> Rename 'btrfs' libstorage tests to avoid conflict with classic btrfs

- tests/installation/add_update_test_repo.pm
> Drop SLE12SP0 workaround

- lib/wickedbase.pm
Collect tcpdump for better debuging of failures
VR: http://kimball.arch.suse.de/tests/1441
> wicked: Collect tcpdump for better debuging of failures

- tests/console/ntp.pm
- Related ticket: https://progress.opensuse.org/issues/55298
https://openqa.suse.de/tests/3278058
http://10.100.12.82/tests/113
> ntp test - survive options obtained from dhcp

- tests/console/check_default_network_manager.pm
add check that non-default manager is not running
VR: http://kimball.arch.suse.de/tests/1454
> network manager: add check that non-default manager is not running

- tests/autoyast/console.pm
- tests/console/consoletest_setup.pm
- tests/installation/disable_grub_timeout.pm
- tests/installation/logs_from_installation_system.pm
- tests/installation/start_install.pm
- tests/x11/eog.pm
- tests/x11/evolution.pm
- tests/xfstests/enable_kdump.pm
> Test summary: Update summaries for a more descriptive text

- tests/x11/firefox.pm
- tests/x11/firefox/firefox_appearance.pm
- tests/x11/firefox/firefox_changesaving.pm
- tests/x11/firefox/firefox_developertool.pm
- tests/x11/firefox/firefox_downloading.pm
- tests/x11/firefox/firefox_emaillink.pm
- tests/x11/firefox/firefox_extcontent.pm
- tests/x11/firefox/firefox_extensions.pm
- tests/x11/firefox/firefox_flashplayer.pm
- tests/x11/firefox/firefox_fullscreen.pm
- tests/x11/firefox/firefox_gnomeshell.pm
- tests/x11/firefox/firefox_headers.pm
- tests/x11/firefox/firefox_html5.pm
- tests/x11/firefox/firefox_localfiles.pm
- tests/x11/firefox/firefox_pagesaving.pm
- tests/x11/firefox/firefox_passwd.pm
- tests/x11/firefox/firefox_pdf.pm
- tests/x11/firefox/firefox_plugins.pm
- tests/x11/firefox/firefox_private.pm
- tests/x11/firefox/firefox_rss.pm
- tests/x11/firefox/firefox_smoke.pm
- tests/x11/firefox/firefox_ssl.pm
- tests/x11/firefox/firefox_urlsprotocols.pm
- tests/x11/firefox_audio.pm
> firefox: Update summaries for a more descriptive text

- lib/wickedbase.pm
Mute failures to upload tcpdump
> wicked: Mute failures to upload tcpdump

- data/hpc_slurm_sbatch.sh
- tests/hpc/slurm_master_db.pm
Initial, basic test for running sbatch script
- Verification run: http://10.160.65.14/tests/5532#step/slurm_master_db/292
> HPC: Add slurm sbatch test case

- data/hpc_slurm_pbs.sh
- tests/hpc/slurm_master_db.pm
Basic test for running PBS script under slurm using slurm-torque
- Verification run: http://10.160.65.14/tests/5550#step/slurm_master_db/312
> HPC: Add slurm-torque test case

- products/microos/main.pm
verification for schedule: https://openqa.opensuse.org/tests/1017626
actual running job: https://openqa.opensuse.org/t1017628
ticket: https://progress.opensuse.org/issues/55919
> microos: Ensure ntp screen is handled correctly

- lib/service_check.pm
- lib/services/ntpd.pm
- tests/console/ntp.pm
Add ntpd service check
- Related ticket: https://progress.opensuse.org/issues/54998
- Needles: n/a
+ Migration service check
* http://openqa.suse.de/tests/3286477
* http://openqa.suse.de/tests/3286616 (running)
+ Console ntp check:
* http://openqa.suse.de/tests/3286480
* http://openqa.suse.de/tests/3286470
> Add ntpd service check

- tests/console/microcode_update.pm
- Verification run: http://openqa.qam.suse.cz/tests/2409
> Fix AMD microcode update check

- lib/sles4sap.pm
To ensure that the copy of SAP binaries goes well we use md5 checksum.
This commit speedup the process by using a pre-generated checksum file instead of generating it each time.
Note: checksum file on our NFS server has been created for all NW and HANA directories we are using on o.s.d.
- Needles: N/A
- Verification run: http://1b210.qa.suse.de/tests/5766
> Use generated checksum file in SLES4SAP tests

- tests/installation/bootloader_s390.pm
verification run: https://openqa.suse.de/tests/3288459
> s390x: Work around broken ssh-X installation

- schedule/yast/remote_ssh_controller.yaml
Fix remote_ssh_controller.yaml to avoid change tty when connecting to ssh.
- Related ticket: https://progress.opensuse.org/issues/52313
- Needles: n/a
> Fix remote_ssh_controller.yaml

- lib/main_common.pm
- tests/console/slp.pm
Hello, this time I have openSLP test:
- Related ticket: [poo#51581](https://progress.opensuse.org/issues/51581)
- Needles: No need
* [SLES12SP1](http://pdostal-server.suse.cz/tests/4096) [SLES12SP2](http://pdostal-server.suse.cz/tests/4099)
* [SLES12SP3](http://pdostal-server.suse.cz/tests/4098) [SLES12SP4](http://pdostal-server.suse.cz/tests/4097)
* [SLES15](http://pdostal-server.suse.cz/tests/4094) [SLES15SP1](http://pdostal-server.suse.cz/tests/4095)
* [Tumbleweed](http://pdostal-server.suse.cz/tests/4092) [LEAP15.2](http://pdostal-server.suse.cz/tests/4093)
> Introduce the openSLP test

- data/autoyast_sle15/autoyast_wicked_x86_64.xml
Add AutoYaST profile for SLE 15 x86_64
VR: https://openqa.suse.de/tests/3296586
> wciked: Add AutoYaST profile for SLE 15 x86_64

- lib/systemd_testsuite_test.pm
- Related ticket: https://progress.opensuse.org/issues/56012
- Failing jobs: https://openqa.suse.de/tests/3290268#next_previous
- Related PR: #7837
> Revert 969d2b9 for systemd_testsuite

- tests/console/lvm.pm
For more info:
* [Module dm-mirror not found in JeOS images ](https://bugzilla.suse.com/show_bug.cgi?id=1148155)
- Related ticket: [[jeos][sle12sp5] test fails in lvm - missing dm-mirror module message appears when executing pvmove](https://progress.opensuse.org/issues/54908)
- Verification run: [sle-12-SP5-JeOS-for-kvm-and-xen-x86_64-Build4.63-jeos-filesystem@64bit-virtio-vga](http://eris.suse.cz/tests/16786#)
> JeOS does not support pvmove

- schedule/jeos/sle/xen/pv/jeos-main.yaml
Fix for issue introduced by https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/8321
> remove redundant modules

- tests/console/check_package_version.pm
Check package version for sles12sp5, after upgrade
- Related ticket: https://progress.opensuse.org/issues/55097
http://10.161.8.44/tests/519#step/check_package_version/47
> Add softfail to check package version file

- tests/installation/opensuse_welcome.pm
- Related ticket: https://progress.opensuse.org/issues/56024
- Verification run: https://openqa.opensuse.org/tests/1020352
> Make sure welcome screen is closed

- declarative-schedule-doc.md
> Document how to integrate yaml schedule with yaml job group settings

- lib/utils.pm
- tests/installation/opensuse_welcome.pm
- Related ticket: https://progress.opensuse.org/issues/56162
- x86_64: https://openqa.opensuse.org/t1021489
- aarch64: https://openqa.opensuse.org/t1021490
> Fix opensuse-welcome race

- .gitignore
- script/generateLibDocs.sh
> Generate docs for subdirectories

- products/opensuse/main.pm
- Related ticket: https://progress.opensuse.org/issues/56270
- Verification run: https://openqa.opensuse.org/t1023055
> Add opensuse_welcome module for live scenarios

- tests/console/apache.pm
- Related ticket: [[sle][JeOS] test fails in apache - handle zypper cache location in better way](https://progress.opensuse.org/issues/56138)
* [sle-15-SP2-JeOS-for-kvm-and-xen-x86_64-Build3.2-jeos-main_intel_image@64bit-virtio-vga](http://eris.suse.cz/tests/16819) 
* [sle-12-SP5-JeOS-for-kvm-and-xen-x86_64-Build4.63-jeos-main_intel_image@64bit-virtio-vga](http://eris.suse.cz/tests/16818)
> Enable apache installation with docs

- lib/main_common.pm
- tests/virtualization/xen/hotplugging.pm
This is a fix for [bsc#959325](https://bugzilla.suse.com/show_bug.cgi?id=959325).
- Related ticket: [poo#](https://progress.opensuse.org/issues/55307)
- Verification run: [12-SP2@Xen](http://pdostal-server.suse.cz/tests/4515) [12-SP2@KVM](http://pdostal-server.suse.cz/tests/4516)
> Fix NIC hotplugging on 12-SP2 ( bsc#959325 )

- script/generateLibDocs.sh
Related: https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/8347
> Fix relative path to css for doc in subdirs

- tests/installation/grub_test.pm
- Related ticket: https://progress.opensuse.org/issues/56285
- Verification run: https://openqa.opensuse.org/t1023229
> grub_test: Handle live menu layout to boot on hard disk

- tests/x11/evolution/evolution_prepare_servers.pm
Upload logs on failure to help to debug.
- Verification run: https://openqa.opensuse.org/t1024399
> evolution_prepare_servers: upload more logs on failure

- data/publiccloud/terraform/azure.tf
Azure was never used before for multi-machine scenarios and it
was never tested properly. This fixes the problems we have
seen when applying terraform on Azure for more than 1 VM.
> Public Cloud: Fix Multi-machine terraform configuration for Azure

- lib/serial_terminal.pm
Increase waiting time inside upload_file
> serial terminal: Increase waiting time inside upload_file

- lib/main_common.pm
- Related ticket: https://progress.opensuse.org/issues/50591
- Verification run: http://10.100.12.155/tests/13163
> Add bootloader test to mau-extratests-yast2ui

- lib/opensusebasetest.pm
- products/sle/main.pm
- tests/console/coredump_collect.pm
poo#51863
https://openqa.suse.de/tests/3331660
> Collect coredump

- tests/installation/win10_installation.pm
- Related ticket: [upgrade windows 10 image in openQA](https://progress.opensuse.org/issues/51221)
- Verification run: []()
> Fix UEFI regression

- tests/sles4sap/migrate_sles_to_sles4sap.pm
A new version of the tool is available in 12-SP5, this commmit fixes the test.
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/3343349
> Fix migration from SLES-to-SLES4SAP

- tests/console/yast2_apparmor.pm
See [poo#56171](https://progress.opensuse.org/issues/56171)
* https://openqa.suse.de/tests/3343455
* https://openqa.suse.de/tests/3343528
> Fix handling of additional packages installation pop-up

- lib/susedistribution.pm
- Related ticket: https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/8152
- Fail: http://openqa.qam.suse.cz/tests/2706#step/boot_ltp/5
http://openqa.qam.suse.cz/tests/2765
> Fix serial device on ssh-root console in select_serial_terminal

- tests/console/snapper_create.pm
Ticket: https://progress.opensuse.org/issues/55688
Verification: http://artemis.suse.de/tests/1642#step/snapper_create/4
> Fix snapper_create test

- tests/installation/bootloader_s390.pm
- Related ticket: https://progress.opensuse.org/issues/56045
- Verification run: http://openqa.slindomansilla-vm.qa.suse.de/tests/1609#
> Refactor CTC handling with less lines and being simpler

- tests/console/kmod.pm
Add fix for kmod test on aarch64 and ppc64le. Module used for testing: ip_set.
- Related ticket: https://progress.opensuse.org/issues/56699
jeos: (previous failing test): https://openqa.opensuse.org/tests/1031260
ppc64le (previous failing test): https://openqa.suse.de/tests/3350786
http://10.161.229.247/tests/154
http://10.161.229.247/tests/155
http://10.161.229.247/tests/156
http://10.161.229.247/tests/157
http://10.161.229.247/tests/158
http://10.161.229.247/tests/159
http://10.161.229.247/tests/160
> Add fix for kmod test on aarch64 and ppc64le

- tests/hpc/changelog
> HPC: changelog update

- schedule/staging/autoyast_mini_no_product@64bit-staging.yaml
Fixes https://openqa.suse.de/tests/3352831
[Verification run](https://openqa.suse.de/tests/3352865).
> Create yaml schedule for autoyast_mini_no_product test suite

- tests/installation/win10_firstboot.pm
- Related ticket: [upgrade windows 10 image in openQA](https://progress.opensuse.org/issues/51221)
- Needles: [o3](https://github.com/os-autoinst/os-autoinst-needles-opensuse/pull/591)
- Verification run: http://eris.suse.cz/tests/456
> Use VMDP to deploy efi boot win10 in kvm

- lib/main_common.pm
- products/sle/main.pm
- schedule/staging/sles4sap_offline_gnome@64bit-staging.yaml
- tests/installation/addon_products_sle.pm
Reverts os-autoinst/os-autoinst-distri-opensuse#8335
> Revert "Remove test variable WORKAROUND_MODULES"

- schedule/yast/cryptlvm/cryptlvm_sle_12_spvm.yaml
See [poo#56873](https://progress.opensuse.org/issues/56873).
> Set desktop to texmode for spvm

- lib/publiccloud/instance.pm
- Verification run: [here](http://pdostal-server.suse.cz/tests/4854#)
> Fix problem with ssh -i param at ssh_run_command()

- lib/main_common.pm
- lib/opensusebasetest.pm
- Related ticket: https://progress.opensuse.org/issues/56774
- Verification run: https://openqa.opensuse.org/t1030206
- Verification run: https://openqa.opensuse.org/t1030207
- Verification run: https://openqa.opensuse.org/tests/1033059
> Accept "opensuse-welcome" in boot_to_desktop

- lib/apachetest.pm
- Related ticket: https://progress.opensuse.org/issues/56882
- Verification run: http://10.100.12.155/tests/13248#step/apache_nss/26
> Update changed nss password

- products/sle/main.pm
- schedule/yast/cryptlvm/cryptlvm_sle_15_spvm.yaml
- schedule/yast/lvm/lvm_sle.yaml
- schedule/yast/lvm/lvm_sle_spvm.yaml
See [poo#56873](https://progress.opensuse.org/issues/56873).
* [Verification runs](https://openqa.suse.de/tests/overview?version=15-SP2&distri=sle&build=rwx788%2Fos-autoinst-distri-opensuse%238448)
> Add yaml schedule for cryptlvm on SLE 15 SP2

- lib/kdump_utils.pm
- lib/service_check.pm
- tests/console/kdump_and_crash.pm
Add kdump service check
- Related ticket: https://progress.opensuse.org/issues/55022
- Needles: N/A
Migration sles12sp4 -> sles12sp5
https://openqa.suse.de/tests/3367071
Server: toolchain_zypper@64bit-smp
https://openqa.suse.de/tests/3367134
OpenSUSE TW test result:
https://openqa.opensuse.org/tests/1034089
> Add kdump service check

- lib/Remote/Lab.pm
- lib/Utils/Backends.pm
- lib/susedistribution.pm
> backends: Add set_sshserial_serialdev() and use it

- README.md
Since we have it already online, let's make it more publicly known
> Add link for the generated documentation

- tests/installation/win10_installation.pm
- Related ticket: https://progress.opensuse.org/issues/51221
- Needles: https://github.com/os-autoinst/os-autoinst-needles-opensuse/pull/592
- Verification run: http://eris.suse.cz/tests/569#
> Click for no prod key

- tests/console/yast2_ftp.pm
- Related ticket: https://progress.opensuse.org/issues/56420
SLE 12.2: http://deathstar.suse.cz/tests/923
SLE 12.3: http://deathstar.suse.cz/tests/921
SLE 12.4: http://deathstar.suse.cz/tests/920
SLE 15.1: http://deathstar.suse.cz/tests/922
SLE 15.0: http://deathstar.suse.cz/tests/924
Opensuse 15.0:http://deathstar.suse.cz/tests/925
Opensuse 15.1: http://deathstar.suse.cz/tests/919
TW: http://deathstar.suse.cz/tests/926
> Adapt yast2_ftp to work also on SLES <= 12.2

- lib/main_common.pm
- lib/utils.pm
- lib/x11utils.pm
- tests/console/system_prepare.pm
- tests/x11/disable_screensaver.pm
Ticket: https://progress.opensuse.org/issues/40490
Needles: https://github.com/os-autoinst/os-autoinst-needles-opensuse/pull/587
Verification:
gnome: http://artemis.suse.de/tests/1660
kde: http://artemis.suse.de/tests/1659
xfce: http://artemis.suse.de/tests/1658
> Add test module to disable screensaver

- tests/console/yast2_i.pm
- Fail: https://openqa.suse.de/tests/3384889#step/yast2_i/26
- Verification run: https://openqa.suse.de/tests/3386128
> Wait longer for yast2 packager to finish

- tests/console/mysql_srv.pm
- Related ticket: https://bugzilla.suse.com/show_bug.cgi?id=1142058
- Verification run: http://10.100.12.155/tests/13304#step/mysql_srv/6
> Add workaround for bsc#1142058 until fixed

- lib/apparmortest.pm
- script/generateLibDocs.sh
see https://progress.opensuse.org/issues/57128
Fix issue with repeated h1 format in script/generateLibDocs.sh
> Add documentation for lib/apparmortest.pm

- tests/console/yast2_nis.pm
- Fail: https://openqa.suse.de/tests/3389603#step/yast2_nis/10
- Verification run: https://openqa.suse.de/tests/3393476
> Use consistent wait_still_screen instead of wait_screen_change

- lib/hpcbase.pm
- tests/hpc/slurm_db.pm
- tests/hpc/slurm_master_db.pm
- Verification run: http://10.160.65.14/tests/7954
> HPC: Add test for slurm accounting

- tests/hpc/changelog
> HPC: update changelog

- schedule/jeos/sle/hyperv/jeos-main.yaml
- schedule/jeos/sle/kvm/jeos-main.yaml
- schedule/jeos/sle/xen/hvm/jeos-main.yaml
- schedule/jeos/sle/xen/pv/jeos-main.yaml
- Related ticket: https://progress.opensuse.org/issues/57203
> Remove textinfo module

- lib/apachetest.pm
see https://progress.opensuse.org/issues/57062
> Write documentation for lib/apachetest.pm

- lib/suseconnect_register.pm
see https://progress.opensuse.org/issues/57038
> Write documentation for lib/suseconnect_register.pm

- data/autoyast_sle15/autoyast_media_up_390.xml
Add autoyast_media_up_390.xml for sle15
- Related ticket: https://progress.opensuse.org/issues/56081
- Needles: n/a
- Verification run: http://openqa.suse.de/t3367124 show installation complete
> Add autoyast_media_up_390.xml for sle15

- data/autoyast_sle12/autoyast_wicked_x86_64.xml
- tests/wicked/before_test.pm
Add ability to run certain git commit
Verification run: https://openqa.suse.de/tests/3393492
> wicked: Add ability to run certain git commit

- data/autoyast_sle15/autoyast_wicked_aarch64.xml
- data/autoyast_sle15/autoyast_wicked_x86_64.xml
- tests/wicked/before_test.pm
Stop disabling Firewalld for SLE 15
VR: https://openqa.suse.de/tests/3393714
> wicked: Minor fixes for SLE15 enablement 

- lib/repo_tools.pm
see https://progress.opensuse.org/issues/57209
> Add and extend documentation for lib/repo_tools.pm

- tests/console/sudo.pm
- Fail: https://openqa.suse.de/tests/3404446#step/sudo/43
- Verification run: https://openqa.suse.de/tests/3407107
> Wait for shell logout to finish

- schedule/qam/12-SP1/mau-filesystem@64bit.yaml
- schedule/qam/12-SP2/mau-filesystem@64bit.yaml
- schedule/qam/12-SP3/mau-filesystem@64bit.yaml
- schedule/qam/12-SP4/mau-filesystem@64bit.yaml
- schedule/qam/15-SP1/mau-filesystem@64bit.yaml
- schedule/qam/15-SP1/mau-filesystem@zkvm.yaml
- schedule/qam/15/mau-filesystem@64bit.yaml
> mau-filesystems yaml schedule for QAM

- products/sle/main.pm
- tests/console/rsync_client.pm
- tests/console/rsync_server.pm
- Related ticket: https://progress.opensuse.org/issues/52826
* client 15sp1 http://10.100.12.82/tests/125
* server 15sp1 http://10.100.12.82/tests/124
* client 12sp4 http://10.100.12.82/tests/131
* server 12sp4 http://10.100.12.82/tests/130
> Add rsync test

- lib/network_utils.pm
see https://progress.opensuse.org/issues/57458
> Correct and extend documentation for lib/network_utils.pm

- lib/service_check.pm
see https://progress.opensuse.org/issues/57365
> Write documentation for lib/service_check.pm

- tests/hpc/slurm_master_db.pm
- Verification run: http://10.160.65.14/tests/10235#step/slurm_master_db/342
> HPC: Specify nodes names for srun job

- lib/registration.pm
> Products are renamed in SLE15SP2

- products/sle/main.pm
- tests/hpc/README.migration
- tests/hpc/barrier_init.pm
- tests/hpc/before_test.pm
- tests/hpc/hpc_master.pm
- tests/hpc/hpc_master_backup.pm
- tests/hpc/hpc_migration.pm
- tests/hpc/hpc_slave.pm
- tests/hpc/hpc_support.pm
- tests/hpc/post_migration.pm
master node: http://10.160.65.14/tests/10612
compute node: http://10.160.65.14/tests/10611
> HPC: Cluster migration tests

- lib/xml_utils.pm
see https://progress.opensuse.org/issues/57518
> Correct and extend documentation for lib/xml_utils.pm

- lib/y2lan_restart_common.pm
see https://progress.opensuse.org/issues/57566
> Correct and extend documentation for lib/y2lan_restart_common.pm

- tests/hpc/hpc_migration.pm
As the module can handle barriers now, it should be indicated that
the test can be run on multimachine set-ups
> HPC: update test module description

- tests/kernel/update_kernel.pm
> Another kernel released without LP basepatch

- tests/kernel/update_kernel.pm
> Fix regular expresion in update_kernel

- lib/susedistribution.pm
Now retrying up to three times if command was not found
- Related ticket: https://progress.opensuse.org/issues/55580
> Rework x11_start_program to retry mistyping

- lib/autoyast.pm
see https://progress.opensuse.org/issues/57302
> Write documentation for lib/autoyast.pm

- lib/autofs_utils.pm
see https://progress.opensuse.org/issues/56258
> Extend documentation for lib/autofs_utils.pm

- tests/x11/firefox/firefox_localfiles.pm
> Use one needle tag for same needle

- lib/bootloader_setup.pm
add_grub_xen_cmdline_settings
replace_grub_xen_cmdline_settings
remove_grub_xen_cmdline_settings
Xen kernel's command-line will make from "GRUB_CMDLINE_XEN_DEFAULT".
> Add some API for Xen command-line

- lib/x11test.pm
- Verification run: http://10.100.12.155/tests/13461#step/firefox_downloading/24
> Apply NOLOGS variable also on x11tests

- tests/sles4sap/saptune/mr_test.pm
Quote all metacharacters that may be present in MR_TEST and fix get_solutions() returned array.
> sles4sap: quote all characters in MR_TEST variable & fix get_solutions()

- lib/bootloader_setup.pm
Reverts os-autoinst/os-autoinst-distri-opensuse#8328
> Revert "Add some API for Xen command-line"

- lib/y2_module_basetest.pm
see https://progress.opensuse.org/issues/57800
> Correct and extend documentation for lib/y2_module_basetest.pm

- lib/bootloader_spvm.pm
see https://progress.opensuse.org/issues/57740
> Write documentation for lib/bootloader_spvm.pm

- lib/thunderbird_common.pm
Ticket: https://progress.opensuse.org/issues/57581
> Document lib/thunderbird_common.pm

- lib/networkdbase.pm
Ticket: https://progress.opensuse.org/issues/57572
> Document lib/networkdbase.pm

- CONTRIBUTING.md
For the time being, only reference points where we have documentation, and point people to the right place
> Enhance a bit CONTRIBUTING.md

- data/regproxy/regproxy.py
On startup, fetch all repos available in the given prefix and proxy
those instead of deciding per tag.
kubeadm: http://10.160.67.86/tests/490
kubeadm cilium: http://10.160.67.86/tests/491
> regproxy: Proxy whole repos, not tags

- lib/data_integrity_utils.pm
see https://progress.opensuse.org/issues/57449
> Extend and correct documentation for lib/data_integrity_utils.pm

- lib/s390base.pm
see https://progress.opensuse.org/issues/57428
> Add documentation for lib/s390base.pm

- tests/x11/gnomecase/change_password.pm
- Related ticket: https://progress.opensuse.org/issues/55661
- Verification run: https://openqa.opensuse.org/tests/1053122#
> change_password: handle welcome screen

- tests/jeos/glibc_locale.pm
- Related ticket: [[JeOS][sle] test fails in glibc_locale - required module update](https://progress.opensuse.org/issues/57443)
* sle-12-SP5: 
* [en_US](http://eris.suse.cz/tests/1368)
* [de_DE](http://eris.suse.cz/tests/1365)
* sle-15-SP2:
* [en_US](http://eris.suse.cz/tests/1366)
* [de_DE](http://eris.suse.cz/tests/1370)
> Rework exit criteria for locale

- tests/x11/firefox/firefox_downloading.pm
- tests/x11/firefox/firefox_fullscreen.pm
http://10.100.12.155/tests/13479 12sp5
http://10.100.12.155/tests/13470 12sp1
http://10.100.12.155/tests/13477 15sp1
http://10.100.12.155/tests/13482 15sp2 wayland
http://10.100.12.155/tests/13484 15sp2
> Firefox fixes for occasional failures

- tests/wicked/before_test.pm
Add missing space to conditional check
VR: None was done yet
> wicked: Add missing space to conditional check

- lib/serial_terminal.pm
die in case unsuccessful login
VR: http://10.160.67.22/tests/47#step/before_test/4
> serial_terminal: die in case unsuccessful login

- lib/wickedbase.pm
Add check that console usable before collecting logs
VR: http://10.160.67.22/tests/49
> wicked: Add check that console usable before collecting logs

- lib/bootloader_setup.pm
- lib/bootloader_spvm.pm
- schedule/yast/cryptlvm/cryptlvm+activate_existing_sle_15_spvm.yaml
- tests/installation/bootloader_s390.pm
See [poo#56984](https://progress.opensuse.org/issues/56984).
* [Verification runs](https://openqa.suse.de/tests/overview?version=15-SP2&build=rwx788%2Fos-autoinst-distri-opensuse%238657&distri=sle)
> Encrypt disk on spvm to test partitions activation

- data/autoyast_sle12/autoyast_wicked_ppc64le.xml
Add AutoYaST profile for Power
VR: https://openqa.suse.de/tests/3473543
> wicked: Add AutoYaST profile for Power

- lib/yast2_widget_utils.pm
see https://progress.opensuse.org/issues/57839
> Correct documentation for lib/yast2_widget_utils.pm

- schedule/qam/12-SP1/qam-minimal-base@64bit.yaml
- Fail: https://openqa.suse.de/tests/3474560#step/system_role/2
> Remove not present system role on 12sp1

- lib/partition_setup.pm
Added function documentation for partition setup module
- Related ticket: https://progress.opensuse.org/issues/57752
> Add documentation for partition_setup

- lib/bootloader_setup.pm
Fix compat_args function wasn't exported.
> Fix "Add some API for Xen command-line" patch

- schedule/qam/15-SP1/qam-allpatterns@64bit.yaml
- schedule/qam/15-SP1/qam-minimal-base@64bit.yaml
- schedule/qam/15/qam-allpatterns@64bit.yaml
- schedule/qam/15/qam-minimal-base@64bit.yaml
https://progress.opensuse.org/issues/52859
https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/8678
https://openqa.suse.de/tests/3479188 15sp1 SLED qam-allpatterns
https://openqa.suse.de/tests/3479190 15sp1 SLES qam-allpatterns
https://openqa.suse.de/tests/3479189 15sp1 zkvm qam-minimal+base
https://openqa.suse.de/tests/3479239 15 SLED qam-allpatterns
https://openqa.suse.de/tests/3479240 15 SLES qam-allpatterns
https://openqa.suse.de/tests/3479243 15 64bit qam-minimal+base
> Use conditional_schedule for different product and machine

- lib/susedistribution.pm
Now only pressing esc if an open desktop runner
- Related ticket: https://progress.opensuse.org/issues/55580
- Verification run: tbd
> Fix the rework of x11_start_program

- data/publiccloud/restart_instance.sh
- tests/publiccloud/run_ltp.pm
> publiccloud: implement restart for GCE

- lib/y2_mm_common.pm
see https://progress.opensuse.org/issues/58202
> Write documentation for lib/y2_mm_common.pm

- lib/rescuecdstep.pm
see https://progress.opensuse.org/issues/57332
> Add documentation for lib/rescuecdstep.pm

- lib/y2snapper_common.pm
see https://progress.opensuse.org/issues/58142
> Write documentation for lib/y2snapper_common.pm

- lib/ipmi_backend_utils.pm
The original dom0_mem=4G did not work in one of the SUT,grenache-1:16, in OSD. The total memory account of this machine is only 4G. So we use the default size for all OS release with newer than sles15sp1(including sles15sp1, sles12sp5, sles15sp2 and etc), while passing dom0_mem=2G for other release on which the autoballooning is enabled by default during system installation.
- Related ticket: https://bugzilla.suse.com/show_bug.cgi?id=1153713
http://10.67.18.182/tests/1212   gi-guest_developing-on-host_developing-xen
http://10.67.18.182/tests/1215  gi-guest_developing-on-host_sles15-xen
http://10.67.18.182/tests/1217  gi-guest_developing-on-host_sles12sp4-xen
@alice-suse @xguo @waynechen55
> Change to use default size of dom0 ram since sles15sp1

- products/sle/main.pm
They are:
loadtest "virt_autotest/set_config_as_glue";
loadtest "virt_autotest/virsh_internal_snapshot";
loadtest "virt_autotest/virsh_external_snapshot";
> Enable several test modules in main

- tests/kernel/run_ltp.pm
The previous version of softfail patch for LTP timeout prevented VM rollback
on serious system error. Use post_fail_hook to override fail status while
allowing VM rollback to last good snapshot.
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/3491985
> Allow softfail on LTP timeout without preventing snapshot rollback

- tests/yast2_gui/yast2_storage_ng.pm
- https://progress.opensuse.org/issues/57977
- https://progress.opensuse.org/issues/58259
- SLE 15.1 (local): http://d250.qam.suse.de/tests/2209 :heavy_check_mark: 
- SLE 15.1 (remote): https://openqa.suse.de/tests/3509213 :heavy_check_mark: 
- SLE 15.0 (remote): https://openqa.suse.de/tests/3509220 :heavy_check_mark:
> fixes to yast2_storage_ng

- lib/main_common.pm
- lib/services/ntpd.pm
- lib/version_utils.pm
- tests/console/mta.pm
- tests/console/mutt.pm
- tests/console/suse_module_tools.pm
- tests/publiccloud/download_repos.pm
- tests/publiccloud/ssh_interactive_end.pm
Hello,
here are some small fixes of several tests from the `mau-extratests-console` tests suite.
- Related ticket: [poo#54842](https://progress.opensuse.org/issues/54842)
- Needles: [os-autoinst-needles-sles#1234](https://gitlab.suse.de/openqa/os-autoinst-needles-sles/merge_requests/1234)
- Verification run: [latest](http://pdostal-server.suse.cz/tests/5296)
> Fix mau-extratests on public cloud

- tests/ha/check_logs.pm
Remove softfail for bsc#1150704.
- Related ticket: https://bugzilla.suse.com/show_bug.cgi?id=1150704
- Needles: N/A
> Remove softfail for bsc#1150704

- lib/y2snapper_common.pm
Reverts os-autoinst/os-autoinst-distri-opensuse#8719
> Revert "Ensure right pane of last node is refreshed in yast2 snapper"

- tests/sles4sap/sapconf.pm
Testing `virtual-host` tuned profile on a VM isn't very useful and can lead to sporadic timeout issues.
- Related ticket: https://bugzilla.suse.com/show_bug.cgi?id=1146298
- Needles: N/A
- Verification run: http://1b210.qa.suse.de/tests/6020
> Fix 'sapconf' test

- lib/web_browser.pm
Now each function contains POD documentation
- Related ticket: https://progress.opensuse.org/issues/58190
> Document lib/web_browser

- tests/x11/nis_client.pm
Ticket: https://progress.opensuse.org/issues/54638
Verification: https://openqa.suse.de/tests/3519559
> Check needles for nis_client

- tests/publiccloud/boottime.pm
For better analyzes, it might be helpful to store `systemd-analyze blame`
output in InfluxDB.
- Verification run: http://cfconrad-vm.qa.suse.de/tests/6126
> Store `systemd-analyze blame` output

- lib/Installation/Partitioner/ExpertPartitionerPage.pm
- lib/Installation/Partitioner/LibstorageNG/v4/ExpertPartitionerController.pm
- schedule/yast/modify_existing_partition_opensuse.yaml
- schedule/yast/modify_existing_partition_sle.yaml
- tests/console/validate_modify_existing_partition.pm
- tests/installation/partitioning/modify_existing_partition.pm
Add test suite that modifies/resizes a partitionon a previsously formatted disk. Depends on create_hdd_gnome.
- Related ticket: https://progress.opensuse.org/issues/53804
- Needles: 
https://gitlab.suse.de/openqa/os-autoinst-needles-sles/merge_requests/1233
https://github.com/os-autoinst/os-autoinst-needles-opensuse/pull/601/files
[SLE](http://waaa-amazing.suse.cz/tests/9221) [TW](http://waaa-amazing.suse.cz/tests/9224)
> Add test suite that modifies existing partition

- tests/x11/gnomecase/application_starts_on_login.pm
- Verification run: https://openqa.opensuse.org/t1068236
> application_starts_on_login: Fix auto-save-session search on aarch64 openSUSE

- lib/networkdbase.pm
- tests/networkd/networkd_init.pm
Ticket: https://bugzilla.opensuse.org/show_bug.cgi?id=1153159
Verification: http://artemis.suse.de/tests/1716
> Networkd: Install systemd-network & use http repo

- tests/networkd/networkd_init.pm
Ticket: https://progress.opensuse.org/issues/58595
Verification:
TW: http://artemis.suse.de/tests/1718
LEAP: https://openqa.opensuse.org/tests/1068620
> networkd: Use Leap-release pkg on leap

- tests/installation/opensuse_welcome.pm
- Verification run: https://openqa.opensuse.org/t1069257
> opensuse_welcome: improve reliability

- tests/x11/gimp.pm
- Related ticket: https://progress.opensuse.org/issues/58778
- Verification run: https://openqa.opensuse.org/t1069246
> gimp: increase match_timeout

- tests/virtualization/xen/dom_install.pm
- tests/virtualization/xen/guest_management.pm
- tests/virtualization/xen/hotplugging.pm
- tests/virtualization/xen/list_guests.pm
- tests/virtualization/xen/save_and_restore.pm
- tests/virtualization/xen/virsh_start.pm
- tests/virtualization/xen/virtmanager_add_devices.pm
- tests/virtualization/xen/virtmanager_rm_devices.pm
Hello,
those are fixes we created last week during `xen` updates testing.
- Related ticket: None
- Needles: [os-autoinst-needles-sles#1236](https://gitlab.suse.de/openqa/os-autoinst-needles-sles/merge_requests/1236)
- Verification runs: `qam-regression-xen` and `qam-regression-qemu` on [openqa.qam.suse.cz](http://openqa.qam.suse.cz/)
> Fix QAM Virtualization

- lib/main_common.pm
- tests/x11/toolkits/prepare.pm
- Related ticket: https://progress.opensuse.org/issues/58628
* https://openqa.opensuse.org/t1069290
* https://openqa.opensuse.org/t1069291
> extra_tests_toolkit: qt4 removed from Tumbleweed

- lib/qam.pm
`qam::get_patches()` currently filters the list of incident patches before it gets printed to serial console. This is inconvenient for troubleshooting.
This pull request removes the `awk` filter and reads the whole zypper output from serial console. The removed `awk` filter is reimplemented in Perl on the host side.
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/3538731#step/update_kernel/68
> qam::get_patches(): print zypper output to serial console

- tests/sles4sap/sapconf.pm
Simplify tuned profiles test in `sapconf.pm`.
- Needles: N/A
- Verification run: https://openqa.suse.de/t3544759
> Simplify 'sapconf' test

- data/autoyast_qam/12-SP5_installation.xml.ep
- Related ticket: https://progress.opensuse.org/issues/58451
> Create symlink for 12sp5 autoyast

- data/qam/handle_bind_source_dependencies.sh
- schedule/qam/common/mau-bind.yaml
- Related ticket: https://progress.opensuse.org/issues/58256
https://openqa.suse.de/tests/3552701
https://openqa.suse.de/tests/3552702
> Fix bind test on s390x

- tests/wicked/basic/sut/t01_basic.pm
Add Stop several cards at once
VR: http://autobot/tests/114
> wicked: Add Stop several cards at once

- lib/opensusebasetest.pm
- lib/qam.pm
- Fail: https://openqa.suse.de/tests/3549026#step/install_update/43
http://10.100.12.155/tests/13697
https://openqa.suse.de/tests/3552625 aarch64
https://openqa.suse.de/tests/3552634 ppc64le
https://openqa.suse.de/tests/3552632 x86_64
https://openqa.opensuse.org/tests/1075734#step/firefox/137 TW
> Use xz for y2logs compression except 12-sp1

- data/wicked/dhcp/dhcpd_2nics.conf
- lib/wickedbase.pm
- tests/wicked/basic/ref/t08_setup_second_card.pm
- tests/wicked/basic/sut/t08_setup_second_card.pm
- Related ticket: https://progress.opensuse.org/issues/58865
- Verification run: http://fromm.arch.suse.de/tests/223
> Wicked: fix t08 from basic suite

- lib/y2snapper_common.pm
- tests/console/yast2_snapper_ncurses.pm
- tests/x11/yast2_snapper.pm
Revert yast2 snapper new design: #8797
- Related ticket: https://progress.opensuse.org/issues/56255
> Revert yast2 snapper new design

- lib/opensusebasetest.pm
- lib/qam.pm
- lib/y2_logs_helper.pm
- Related ticket: https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/8823
http://10.100.12.155/tests/13709#step/install_update/49
> Use get_available_compression and prefer .xz compression

- schedule/yast/minimal+base/minimal+base@yast-s390x-disk-activation.yaml
- schedule/yast/minimal+base/minimal+base@yast-s390x.yaml
- schedule/yast/minimal+base/minimal+base@yast-svirt-hyperv.yaml
- schedule/yast/minimal+base/minimal+base@yast-xen-pv.yaml
- schedule/yast/minimal+base/minimal+base@yast.yaml
- tests/console/validate_selected_patterns.pm
an new validation module is introduced to validate the installed patterns and the yaml schedules are updated accordingly.
zkvm needs to move to the yast jobs after this PR is merged. 
- Related ticket: https://progress.opensuse.org/issues/56990
- Needles: N/A
[64bit sle15](https://openqa.suse.de/tests/3542353) YAML_SCHEDULE=schedule/yast/minimal+base/minimal+base@yast.yaml
[64bit sle12](https://openqa.suse.de/t3543725) YAML_SCHEDULE=schedule/yast/minimal+base/minimal+base@yast.yaml
[aarch64 sle15](https://openqa.suse.de/t3538441) YAML_SCHEDULE=schedule/yast/minimal+base/minimal+base_sle15@yast.yaml
[aarch64 sle12](https://openqa.suse.de/t3543723) YAML_SCHEDULE=schedule/yast/minimal+base/minimal+base@yast.yaml
[ppc64le sle15](https://openqa.suse.de/t3543731) …
> Validate selected patterns

- tests/autoyast/installation.pm
- Related ticket: https://progress.opensuse.org/issues/56777
- Verification run: https://openqa.opensuse.org/tests/1035052
> Accept "opensuse-welcome" after autoyast first boot

- lib/kdump_utils.pm
Since SLE15-SP2/Leap 15.2 (standard and JeOS) there are specific kernel
packages with customized modules list.
On JeOS and some standard installation the kernel package is
'kernel-default-base', but the debuginfo package is
'kernel-default-debuginfo'.
- Related feature: https://jira.suse.com/browse/SLE-7691
- Related QA ticket: https://progress.opensuse.org/issues/56423
> Use 'kernel-default-debuginfo' on SLE15-SP2+

- schedule/yast/modify_existing_partition_sle.yaml
Fixes this failure https://openqa.suse.de/tests/3561668#step/modify_existing_partition/16
[ppc64le](https://openqa.suse.de/tests/3564642#step/logs_from_installation_system/19), [X86_64](https://openqa.suse.de/tests/3564643#step/validate_modify_existing_partition/12)
> Modify partition size as ppc requires > 10.5GiB

- lib/xen.pm
see https://progress.opensuse.org/issues/58271
> Write documentation for lib/xen.pm

- tests/jeos/firstrun.pm
- Related ticket: [[jeos][sle] create test module to verify UUID mounts](https://progress.opensuse.org/issues/57299)
* **by label**
* [sle-15-SP1-JeOS-for-kvm-and-xen](http://eris.suse.cz/tests/1759)
* [sle-12-SP5-JeOS-for-kvm-and-xen](http://eris.suse.cz/tests/1764)
* [opensuse-15.1-JeOS](http://eris.suse.cz/tests/1755#step/firstrun/50)
* [opensuse-15.0-JeOS](http://eris.suse.cz/tests/1762#step/firstrun/50)
* **by UUID**
* [sle-15-SP2-JeOS-for-kvm-and-xen](http://eris.suse.cz/tests/1760)
* [opensuse-Tumbleweed-JeOS](http://eris.suse.cz/tests/1761#step/firstrun/50)
* [opensuse-15.2-JeOS](http://eris.suse.cz/tests/1763#step/firstrun/50)
> Verify mount types

- tests/virt_autotest/virsh_external_snapshot.pm
Before virsh_external_snapshot test, add prepare step to double check guest status as shut off (inactive) status
http://10.67.19.82/tests/277
> Virtualization: Add guest check for virsh external snapshot

- lib/qam.pm
The output format of `zypper patches` has changed in SLE-12SP2. Fix `qam::get_patches()` to support both output formats.
This fixes a test bug introduced by PR #8606.
- Needles: N/A
- 11SP3: https://openqa.suse.de/tests/3580394
- 12SP1: https://openqa.suse.de/tests/3580390
- 12SP3: https://openqa.suse.de/tests/3580411
- 12SP4: https://openqa.suse.de/tests/3580391
- 15GA: https://openqa.suse.de/tests/3580392
> Fix qam::get_patches() on old SLE releases (12SP1 and older)

- tests/virtualization/virtman_view.pm
- Related ticket: https://progress.opensuse.org/issues/54056
* x86_64: https://openqa.opensuse.org/t1078600
* aarch64: https://openqa.opensuse.org/t1078601
> virtman_view: stabilize items selection in graph menu of virt manager (poo#54056)

- lib/y2snapper_common.pm
Improve stability yast2 snapper ncurses
- Related ticket: https://progress.opensuse.org/issues/56255
- Needles: [needles-sle](https://gitlab.suse.de/openqa/os-autoinst-needles-sles/merge_requests/1245) -> Merged
- Verification run: [yast2_ncurses](https://openqa.suse.de/tests/overview?distri=sle&build=jknphy%2Fos-autoinst-distri-opensuse%238888&version=12-SP5)
> Improve stability yast2 snapper ncurses

- tests/kernel/install_ltp.pm
Verification run: http://quasar.suse.cz/tests/3872
> LTP: fix missing pidstat

- tests/console/apache.pm
Ticket: https://progress.opensuse.org/issues/56747
Verification: http://artemis.suse.de/tests/1744
> Fix apache test for jobs with SYSTEM_ROLE=kvm

- lib/x11utils.pm
- tests/autoyast/installation.pm
- tests/installation/opensuse_welcome.pm
see https://progress.opensuse.org/issues/56777
verification test:
http://f40.suse.de/tests/5286#step/installation/13
> Add function to handle opensuse-welcome 'don't show on next startup'

- tests/qam-updinstall/update_install.pm
- Common fail: https://openqa.suse.de/tests/3583996#step/update_install/34
- Verification run: http://10.100.12.155/tests/13769
> Don't try to install package not present before patch

- lib/main_common.pm
- tests/sles4sap/sap_suse_cluster_connector.pm
Add test for `sap_suse_cluster_connector` command for SAP cluster.
**Note:** we may have to add changes later to this code to handle [HANA cluster](#8603).
- Needles: N/A
- Verification run: http://1b210.qa.suse.de/tests/6108
> Improve SAP/HA tests

- lib/main_common.pm
- tests/console/zypper_log.pm
Ticket: https://bugzilla.suse.com/show_bug.cgi?id=1156158
Verification:
http://artemis.suse.de/tests/1751
http://artemis.suse.de/tests/1752
> Add a test for zypper-log

- tests/console/bind.pm
- Related ticket: https://openqa.suse.de/tests/3585383#step/bind/17
- Verification run: https://openqa.suse.de/tests/3590446
> Increase timeout of registration for bind dependencies

- schedule/qam/15/mau-extratests.yaml
- schedule/qam/15/qam-minimal-base.yaml
- Fail: https://openqa.suse.de/tests/3589580
https://openqa.suse.de/tests/3590474
https://openqa.suse.de/tests/3590483
> Fix yamls for s390x on sle 15

- tests/console/avocado_prepare.pm
- Fail: http://openqa.qam.suse.cz/tests/3631#step/avocado_prepare/19
> Allow vendor changeto avoid fail of avocado install

- tests/console/zypper_log.pm
Fixes #8909
Verification:
JeOS: https://openqa.opensuse.org/t1085313
LIVE: https://openqa.opensuse.org/t1085314
> Fix zypper_log for jeos and live

- tests/console/gpg.pm
- Fail: https://openqa.suse.de/tests/3596382#step/gpg/14
> Increase timout for gpg key gen

- tests/console/gpg.pm
Reverts os-autoinst/os-autoinst-distri-opensuse#8927
> Revert "Increase timout for gpg key gen"

- tests/console/gpg.pm
- Fail: https://openqa.suse.de/tests/3597663#step/gpg/1
- Verification run: https://openqa.suse.de/tests/3598380
> Start haveged on s390x sle15+

- lib/service_check.pm
Add black/white list for service check module through INCLUDE_SERVICES /EXCLUDE_SERVICES setting
- Related ticket: https://progress.opensuse.org/issues/59385
- Needles: n/a
- Verification run: https://openqa.suse.de/tests/3586310# (case setting with EXCLUDE_SERVICES like following command) 
./openqa-clone-custom-git-refspec https://github.com/coolgw/os-autoinst-distri-opensuse/tree/black_white_list http://openqa.suse.de/tests/3577176 EXCLUDE_MODULES=patch_sle EXCLUDE_SERVICES="apache2,bind,cups" PRIORITY=0
> Add black/white list for service check module

- tests/console/avocado_prepare.pm
- tests/console/avocado_run.pm
- Fail: http://openqa.qam.suse.cz/tests/3631#step/avocado_prepare/19
- Verification run: http://openqa.qam.suse.cz/tests/3719#step/avocado_prepare/17
> Fix avocado installation and block_device_hotplug tests

- tests/console/yast2_ftp.pm
> [yast2_ftp] Add improved test summary - no code change

- tests/console/yast2_tftp.pm
> [yast2_tftp] Add improved test summary - no code change

- tests/console/yast2_nis.pm
> [yast2_NIS] Add improved test summary - No code change

- tests/console/yast2_http.pm
> [yast2_httpd] Add improved test summary - no code change

- tests/console/yast2_apparmor.pm
> [yast2_apparmor] Add improved test summary - no code change

- schedule/create_hdd_autoyast_wicked.yaml
This should be merged together with 
https://gitlab.suse.de/kernel-qa/kernelqa-openqa-yaml/merge_requests/15
> Wicked: add AUTOYAST variable to test suite yaml

- tests/console/apache.pm
Ticket: https://progress.opensuse.org/issues/56747
Verification: https://openqa.suse.de/t3616538
> Fix apache test: SYSTEM_ROLE=xen => excludedocs

- tests/btrfs-progs/run.pm
Only run one category test each time is not flexible. If cli, fuzz,
convert, etc. can run in one time, it's more efficiency and flexible in
some situation.
- Related ticket: https://progress.opensuse.org/issues/59022
http://10.67.133.10/tests/39
http://10.67.133.10/tests/42 (with blacklist)
> btrfs-progs: Get more than one category in single test

- tests/console/textinfo.pm
- Fail: https://openqa.suse.de/tests/3619345#step/textinfo/4
- Verification run: https://openqa.suse.de/tests/3621260
> Increase timout for collection of system informations

- lib/version_utils.pm
So we schedule the test correctly for SLE15 SP2
- Related ticket: https://progress.opensuse.org/issues/59975
@Soulofdestiny @SergioAtSUSE
> Adapt lib/version_utils is_server to online medium

- lib/main_common.pm
- tests/appgeo/gdal.pm
- tests/appgeo/qgis.pm
* console test: https://openqa.opensuse.org/t1095286
* desktop test: https://openqa.opensuse.org/t1090760
- Needles:
* https://github.com/os-autoinst/os-autoinst-needles-opensuse/commit/3f221c5cf0391037e6b61395124e59f1f2db043e
* https://github.com/os-autoinst/os-autoinst-needles-opensuse/commit/a57aca734e94193b8bb41295d30e8fcc82054209
> Add tests of geo applications

- tests/wsl/install/ms_win_firstboot.pm
- Related ticket: https://bugzilla.opensuse.org/show_bug.cgi?id=1157579
* [windows-10-DVD-x86_64-Build1903-windows_10@uefi_win](http://eris.suse.cz/tests/2878#)
> Turn off hibernation and fast startup

- data/console/setup-kerberos-server-3.pl
- lib/main_common.pm
- tests/console/krb5.pm
- Related ticket: https://progress.opensuse.org/issues/55718
Tumbleweed: http://deathstar.suse.cz/tests/2208
SLE12.2 http://deathstar.suse.cz/tests/2211#settings
SLE12.3 http://deathstar.suse.cz/tests/2198
SLE 12.4 http://deathstar.suse.cz/tests/2206
SLE 15.0 http://deathstar.suse.cz/tests/2207
SLE 15.1 http://deathstar.suse.cz/tests/2210
> New test: MIT kerberus 5 (krb5)

- schedule/staging/sles4sap_offline_gnome@64bit-staging.yaml
Another fix for SAP Staging:S group, as the first one was not fully complete.
- Needles: N/A
- Verification run: Not easy to do...
> Fix for SAP Staging:S group - Part 2

- lib/utils.pm
- Related ticket: https://progress.opensuse.org/issues/60365
- Verification run: http://openqa.slindomansilla-vm.qa.suse.de/tests/2011#step/zypper_ref/2
> Enable CD repos when using Full media

- tests/boot/grub2_test.pm
- Fail: https://openqa.suse.de/tests/3638995
- Verification run: https://openqa.suse.de/tests/3639649
> Wait longer for grub2 after reboot

- tests/networkd/networkd_init.pm
Ticket: https://progress.opensuse.org/issues/58595
Verification: http://artemis.suse.de/tests/2108
> Switch back to openSUSE-Release pkg for Leap

- tests/virt_autotest/guest_upgrade_run.pm
- tests/virt_autotest/host_upgrade_generate_run_file.pm
Offline media should be passed to:
1)test_virtualization-guest-upgrade-run
2)_generate_vh-update_test.sh
- Related ticket: https://openqa.suse.de/tests/3649103
https://openqa.suse.de/tests/3649104
- Needles: n/a
- Verification run: https://10.162.187.154/tests/4376
> Use offline media to do upgrade

- tests/yast2_cmd/yast_keyboard.pm
- Fail: https://openqa.suse.de/tests/3660070
- Verification run: https://openqa.suse.de/tests/3661545
> Increase wait time due to occasional failures

- tests/cpu_bugs/l1tf.pm
Since we want to test the smt control in L1TF, we add a testcase of smt in L1TF
- Verification run: http://10.67.132.101/tests/8
> Add a testcase of SMT and EPT in L1TF

- tests/cpu_bugs/meltdown.pm
Since there is no nopti check in meltdown, we add a nopti check in meltdown.
- Verification run: http://10.67.132.101/tests/4#
> Add a nopit check in meltdown

- tests/console/firewalld.pm
The newest versions of firewalld do not add chains in mangle table for
port forwarding rules[0]. This commit brings the following changes in
the test:
- not checking the mangle table which should be not affected
- checking the nat PRE_public_allow chain for the forwarding rule
- checking the nat POST_public_allow chain for the masquerade rule
[0] https://github.com/firewalld/firewalld/commit/80b241ed11d5cb93c0f7670dc7248bc5ffa9eae4
Fixes: https://progress.opensuse.org/issues/60269
Signed-off-by: Michal Rostecki <mrostecki@opensuse.org>
- Related ticket: https://progress.opensuse.org/issues/60269
> firewalld: Update the masquerading rules test

- schedule/qam/15-SP1/qam-gnome.yaml
- schedule/qam/15/qam-gnome.yaml
- Fail: https://openqa.suse.de/tests/3638181
- Verification run: https://openqa.suse.de/tests/3638182
> Fix qam-gnome yaml for s390x

- tests/wicked/before_test.pm
Enter into directory before switching the branch 
VRs : 
SUT , WICKED_SOURCES includes branch :  https://openqa.suse.de/tests/3666208
SUT , WICKED_SOURCES NOT includes branch : https://openqa.suse.de/tests/3666152
> wicked: Enter into directory before switching the branch

- schedule/qam/12-SP4/qam-gnome.yaml
- schedule/qam/12-SP4/qam-minimal-base.yaml
- schedule/qam/12-SP5/qam-gnome.yaml
- schedule/qam/12-SP5/qam-minimal-base.yaml
https://openqa.suse.de/tests/3665388
> Fix 12sp4 & 12sp5 yamls on s390x

- data/autoyast_sle15/autoyast_wicked_ppc64le.xml
> wicked: Add PowerKVM support to 15

- lib/main_common.pm
- tests/sles4sap/sap_suse_cluster_connector.pm
Add sap_suse_cluster_connector test to HANA SR test
- Verification run: [node1](http://ix64hae1001.qa.suse.de./tests/1934) & [node2](http://ix64hae1001.qa.suse.de./tests/1935)
Regression test with NW: http://ix64hae1001.qa.suse.de./tests/1943
Had to add `QEMUCPU=8` and `QEMURAM=32768` for this work.
> Add sap_suse_cluster_connector test to HANA SR test

- schedule/functional/extra_tests_in_textmode_phub.yaml
- Related ticket: https://progress.opensuse.org/issues/57290
- Verification run: http://openqa.slindomansilla-vm.qa.suse.de/tests/2034
> Add YAML schedule for package hub scenario

- tests/sles4sap/saptune/mr_test.pm
Add a wait after reboot in saptune mr_test tests to give tuned time to tune the system before logging in to avoid bsc#1143291
- Verification run: http://ix64hae1001.qa.suse.de/tests/1945
> sles4sap: Add a wait after reboot in saptune mr_test tests

- data/autoyast_qam/12_installation.xml.ep
- data/autoyast_qam/15_installation.xml.ep
- Related ticket: https://progress.opensuse.org/issues/60803
s390x
https://openqa.suse.de/tests/3681703 15
https://openqa.suse.de/tests/3681705 15sp1
https://openqa.suse.de/tests/3682210 12sp4
https://openqa.suse.de/tests/3682209 12sp5
x86_64
https://openqa.suse.de/tests/3682294 15sp1
https://openqa.suse.de/tests/3682295 12sp5
> Autoyast modification for QAM s390x installation

- tests/x11/wireshark.pm
- Fail: https://openqa.suse.de/tests/3679857
https://openqa.suse.de/tests/3683119
https://openqa.suse.de/tests/3683120
https://openqa.suse.de/tests/3683121
https://openqa.suse.de/tests/3683122
https://openqa.suse.de/tests/3683123
https://openqa.suse.de/tests/3683124
https://openqa.suse.de/tests/3683125
https://openqa.suse.de/tests/3683126
https://openqa.suse.de/tests/3683127
https://openqa.suse.de/tests/3683128
> Add and increase wait time in wireshark test

- schedule/yast/ext4/ext4@yast-s390x.yaml
- schedule/yast/ext4/ext4@yast.yaml
- test_data/yast/ext4/ext4.yaml
- tests/console/validate_ext4_fs.pm
- Related ticket: https://progress.opensuse.org/issues/58909
64bit -> https://openqa.suse.de/t3685199
s390 -> https://openqa.suse.de/t3685200
ppc64le -> https://openqa.suse.de/t3685201
aarch64 -> https://openqa.suse.de/t3685202
> Add module validate_ext4_fs

- schedule/qam/12-SP4/qam-gnome.yaml
- schedule/qam/12-SP5/qam-gnome.yaml
- schedule/qam/15-SP1/qam-gnome.yaml
- schedule/qam/15/qam-gnome.yaml
- Fail: https://openqa.suse.de/tests/3692247#step/x_vt/4
- Verification run: https://openqa.suse.de/tests/3694743
> Don't schedule x_vt test on s390x

- schedule/qam/12-SP4/qam-gnome.yaml
- schedule/qam/12-SP4/qam-minimal-base.yaml
- schedule/qam/12-SP5/qam-gnome.yaml
- schedule/qam/12-SP5/qam-minimal-base.yaml
- schedule/qam/15-SP1/qam-gnome.yaml
- schedule/qam/15/qam-gnome.yaml
- Fail:
https://openqa.suse.de/tests/3696124#step/system_role/2
https://openqa.suse.de/tests/3696227#step/glibc_sanity/9
https://openqa.suse.de/tests/3696919
https://openqa.suse.de/tests/3696920
> yaml: unschedule tests on s390x

- schedule/kernel/pressure_stall_information.yaml
- tests/kernel/pressure_stall_information.pm
Add test which checks /proc/pressure when psi=1 on kernel command line.
https://jira.suse.com/browse/SLE-9282
> Pressure Stall Information smoke test

- tests/migration/sle12_online_migration/yast2_migration.pm
workaround the package conflict during online migration with yast2
- Related ticket: https://progress.opensuse.org/issues/60368
- Needles: N/A
SLES15SP2
1) BREAK_DEPS=1 http://10.161.8.44/tests/842 and http://10.161.8.44/tests/848
2) WORKAROUND_DEPS=1 http://10.161.8.44/tests/849 Inifinity Loop
3) without conflict: http://10.161.8.44/tests/857
1) BREAK_DEPS=1 
https://openqa.suse.de/tests/3684487
https://openqa.suse.de/tests/3684643
Milestone:
https://openqa.suse.de/tests/3692283
2) No conflict: 
https://openqa.suse.de/tests/3684608
https://openqa.suse.de/tests/3684646
SLES12SP5 (verify that the new code will not effect the old sles12sp5)
http://10.161.8.44/tests/853
http://10.161.8.44/tests/855
> workaround the package conflict during online migration

- tests/security/apparmor_profile/apache2_changehat.pm
- tests/x11/libreoffice/libreoffice_mainmenu_components.pm
- Fail:
https://openqa.suse.de/tests/3691013#step/apache2_changehat/12
http://10.100.12.155/tests/14037#step/apache2_changehat/10
> Fix randomly failing tests

- schedule/qam/12-SP4/mau-extratests.yaml
- schedule/qam/12-SP5/mau-extratests.yaml
- Fail: https://openqa.suse.de/tests/3701097#step/aplay/16
https://openqa.suse.de/tests/3702970
https://openqa.suse.de/tests/3702974
> yaml: Unschedule modules not working on s390x

- tests/kernel/update_kernel.pm
This is a no-op convenience patch for `kernel-azure` testing in future SLE releases (15SP2 and later). Verification run was created with `first_azure_release()` call uncommented.
- Needles: N/A
- 12SP4: https://openqa.suse.de/tests/3698498 (without `AZURE_FIRST_RELEASE`)
- 12SP5: https://openqa.suse.de/tests/3698500 (with `AZURE_FIRST_RELEASE=1`)
> Add installation workaround for first kernel-azure

- lib/main_common.pm
- tests/yast2_gui/yast2_instserver.pm
- Related ticket: https://progress.opensuse.org/issues/55712
- Needles:
- openSUSE: https://github.com/os-autoinst/os-autoinst-needles-opensuse/pull/624
- SLES: https://gitlab.suse.de/openqa/os-autoinst-needles-sles/merge_requests/1276
- openSUSE:
- TW: http://d250.qam.suse.de/tests/2347 :heavy_check_mark: 
- Leap: http://d250.qam.suse.de/tests/2364 :heavy_check_mark: 
- SLES:
- 15sp1: http://d250.qam.suse.de/tests/2359 :heavy_check_mark: 
- 12sp5: http://d250.qam.suse.de/tests/2358 :heavy_check_mark: 
- 12sp4: http://d250.qam.suse.de/tests/2357 :heavy_check_mark: 
- 12sp3: http://d250.qam.suse.de/tests/2362 :heavy_check_mark:
> Add test for yast2-instserver

- tests/console/system_prepare.pm
Register the system after media migration, so after media migration, it still can run the regression cases
- Related ticket: https://progress.opensuse.org/issues/60872
- Verification run: http://10.161.8.44/tests/876#step/zypper_ref/2
> Register the system after media migration

- tests/installation/start_install.pm
see https://progress.opensuse.org/issues/61071
verification test:
http://f40.suse.de/tests/5795
> Remove check_bsc982138 from start_install.pm

- lib/bootloader_setup.pm
- lib/main_ltp.pm
- Related ticket: https://progress.opensuse.org/issues/58565
- Verification run: http://quasar.suse.cz/tests/4395
> Support SLERT in ltp

- tests/hpc/slurm_master.pm
Verification run: http://10.160.65.14/tests/14170
> HPC: add basic sanity check for PMIx lib

- lib/services/registered_addons.pm
Check the register addons with SUSEConnect command, replaced zypper lr check
- Related ticket: https://progress.opensuse.org/issues/60659
Before migration: http://10.161.8.44/tests/970#step/install_service/3
After migration:    http://10.161.8.44/tests/970#step/check_upgraded_service/3
> Check the register addons with SUSEConnect command

- tests/installation/await_install.pm
- tests/installation/disk_activation.pm
- tests/installation/start_install.pm
This is part of update for 11sp4 installation process, try to using current exist module to install 11sp4 system on s390. 
- Related ticket: https://progress.opensuse.org/issues/60851
- Needles: 
- Verification run: https://openqa.suse.de/tests/3735257#
> 11sp4 S390 install related update

- tests/console/orphaned_packages_check.pm
Need upload orphaned packages list file, as we need collect orphaned packages information to report bug. 
- Related ticket: https://progress.opensuse.org/issues/61116
- Verification run: http://10.161.8.44/tests/1006#step/orphaned_packages_check/11
> Need upload orphaned packages list file

- schedule/install/11sp4_s390_install.yaml
- tests/installation/bootloader_s390.pm
- tests/installation/install_11sp4_configuration.pm
11sp4 install related update
- Related ticket: https://progress.opensuse.org/issues/60851
- Needles: 
- Verification run: http://openqa.suse.de/t3740976
> 11sp4 install

- lib/service_check.pm
After migration, 15-SP2 need check services 
- Related ticket: https://progress.opensuse.org/issues/61753
http://10.161.8.44/tests/1009#step/check_upgraded_service/3
> Add 15-SP2 service check

- data/autoyast_qam/15_installtest.xml.ep
- Verification run: 15 https://openqa.suse.de/tests/3752029
> Add LTSS repo to installtest images

- tests/console/php7.pm
Ticket: https://progress.opensuse.org/issues/49115
Verification: http://artemis.suse.de/tests/2246
> Add additional php checks

- lib/opensusebasetest.pm
- lib/utils.pm
- tests/update/patch_sle.pm
we need do some workaround for 11sp4 s390 install
- Related ticket: https://progress.opensuse.org/issues/60851
- Needles: 
- Verification run: https://openqa.suse.de/tests/3755489#step/patch_sle/84
> 11sp4 s390 install workaround

- tests/boot/grub2_test.pm
https://progress.opensuse.org/issues/61835
https://bugzilla.suse.com/show_bug.cgi?id=1160318
https://openqa.suse.de/tests/3762777 15
https://openqa.suse.de/tests/3762789 15sp1
http://10.100.12.155/tests/14099
> Improve grub2 test

- tests/console/php7.pm
Related PR: #9196
Verification:
http://artemis.suse.de/tests/2255
http://artemis.suse.de/tests/2256
> Fix additional php checks

- tests/console/zypper_lifecycle_toolchain.pm
Ticket: https://progress.opensuse.org/issues/55253
Verification: http://artemis.suse.de/tests/2251#step/zypper_lifecycle_toolchain/17
> zypper lifecycle: Workaround wrong TZ: bsc#1143453

- tests/console/yast2_i.pm
- Fail: https://openqa.suse.de/tests/3764296#step/yast2_i/13
- Verification run: https://openqa.suse.de/tests/3765126
> Increase timeout to let zypper command finish

- schedule/qam/12-SP1/mau-extratests.yaml
- schedule/qam/12-SP2/mau-extratests.yaml
- schedule/qam/12-SP3/mau-extratests.yaml
- schedule/qam/12-SP4/mau-extratests.yaml
- schedule/qam/12-SP5/mau-extratests.yaml
- schedule/qam/15-SP1/mau-extratests.yaml
- schedule/qam/15/mau-extratests.yaml
- Related ticket: https://progress.opensuse.org/issues/55718
https://openqa.suse.de/tests/3769678#step/krb5/1 15sp1
https://openqa.suse.de/tests/3769677#step/krb5/1 15
https://openqa.suse.de/tests/3769659#step/krb5/1 12sp4
https://openqa.suse.de/tests/3769661#step/krb5/1 12sp3
https://openqa.suse.de/tests/3769662#step/krb5/1 12sp2
https://openqa.suse.de/tests/3769676#step/krb5/1 12sp1
> Add krb5 test into extratests yaml

- lib/serial_terminal.pm
- Fail: https://openqa.suse.de/tests/3767954#step/system_prepare/4
- Verification run: https://openqa.suse.de/tests/3769896
> Fix typo in add_serial_console

- lib/bootloader_setup.pm
Need quit loop after check screen 300 times
- Related ticket: https://progress.opensuse.org/issues/61886
https://openqa.suse.de/tests/3769470#
> Quit loop after check screen 300 times

- data/virt_autotest/vm_host_bridge_final.sh
- data/virt_autotest/vm_host_bridge_init.sh
- data/virt_autotest/vnet_host_bridge.xml
- data/virt_autotest/vnet_isolated.xml
- data/virt_autotest/vnet_nated.xml
- data/virt_autotest/vnet_routed.xml
- data/virt_autotest/vnet_routed_clone.xml
- lib/utils.pm
- lib/virt_autotest/virtual_network_utils.pm
- products/sle/main.pm
- tests/virt_autotest/libvirt_host_bridge_virtual_network.pm
- tests/virt_autotest/libvirt_isolated_virtual_network.pm
- tests/virt_autotest/libvirt_nated_virtual_network.pm
- tests/virt_autotest/libvirt_routed_virtual_network.pm
- tests/virt_autotest/libvirt_virtual_network_init.pm
Managing Virtual Networks with virsh included
the following priorities 4 types of virtual network:
- P1 HOST bridge network
- P2 NAT based network
- P3 Routed network
- P4 Isolated network
KVM:
http://10.67.19.82/tests/376
XEN
http://10.67.19.82/tests/379
> Virtualization: Managing Virtual Networks with virsh

- tests/cpu_bugs/kvm_guest_migration.pm
On SLE-15-SP2, libvirtd is pull up via various ways. One of them is libvirtd-tcp.socket. so if user need a tcp access to libvirtd, it needs to make sure libvirtd-tcp.socket is up.
> Fix libvirtd not response

- lib/main_common.pm
- tests/cpu_bugs/taa.pm
- Verification run: http://10.67.134.217/tests/6657
> Add TAA kernel parameter testcase

- tests/console/zypper_lifecycle.pm
> Don't kill testsuite in zypper_lifecycle

- lib/systemd_testsuite_test.pm
- schedule/qam/common/mau-systemd.yaml
- tests/systemd_testsuite/test_01_basic.pm
- tests/systemd_testsuite/test_02_cryptsetup.pm
- tests/systemd_testsuite/test_03_jobs.pm
- tests/systemd_testsuite/test_04_journal.pm
- tests/systemd_testsuite/test_05_rlimits.pm
- tests/systemd_testsuite/test_06_selinux.pm
- tests/systemd_testsuite/test_07_issue_1981.pm
- tests/systemd_testsuite/test_08_issue_2730.pm
- tests/systemd_testsuite/test_09_issue_2691.pm
- tests/systemd_testsuite/test_10_issue_2467.pm
- tests/systemd_testsuite/test_11_issue_3166.pm
- tests/systemd_testsuite/test_12_issue_3171.pm
- tests/systemd_testsuite/test_13_nspawn_smoke.pm
- tests/systemd_testsuite/test_14_machine_id.pm
- tests/systemd_testsuite/test_15_dropin.pm
- tests/systemd_testsuite/test_22_tmpfiles.pm
- Related ticket: https://progress.opensuse.org/issues/58487
- Verification run: https://openqa.suse.de/tests/3774167
> Yaml scheduler for mau-systemd test

- tests/cpu_bugs/spectre_v1.pm
- tests/cpu_bugs/taa.pm
@alice-suse  suggest removing double inherit.
> Removable double inheritance

- lib/main_common.pm
- lib/utils.pm
- tests/cpu_bugs/itlb.pm
- Verification run: http://mitigations.qa2.suse.asia/tests/6661
> Add iTLB testcase

- lib/publiccloud/azure.pm
- Verification run: https://openqa.suse.de/t3781844 - publiccloud_ltp_syscalls@cfconrad/os-autoinst-distri-opensuse#fix/pc_strip_colors => running
> publiccoud: Strip all color codes from az output

- tests/hpc/slurm_master.pm
HPC: expanding slurm basic tests
> Slurm basic tests

- tests/sles4sap/saptune/mr_test.pm
This PR:
- Adds a test for bsc#1152598 on baremetal.
- Fixes the case for ppc64le.
> sles4sap: Add bsc#1152598 test for saptune v2

- tests/hpc/slurm_master.pm
> HPC: hot-patch for ensuring QAM slurm testing

- lib/publiccloud/azure.pm
This is the recommended way to handle terraform outputs.
This fix issues like:
https://openqa.suse.de/tests/3776590#step/run_ltp/101
-VR: http://cfconrad-vm.qa.suse.de/tests/6691#step/run_ltp/100
> publiccloud: Use terraform state -json to get resource name

- tests/hpc/slurm_master.pm
> HPC: correct test flow execution for SLE15-SP2

- tests/installation/bootloader_s390.pm
- https://bugzilla.opensuse.org/show_bug.cgi?id=1156047
- https://bugzilla.suse.com/show_bug.cgi?id=1151394
- [Tumbleweed](http://openqa.slindomansilla-vm.qa.suse.de/tests/2088)
- [SLE15-SP2](http://openqa.slindomansilla-vm.qa.suse.de/tests/2087)
> Workaround /dev/hvc0: cannot get controlling tty

- schedule/functional/extra_tests_in_textmode_cont.yaml
- Related ticket: https://progress.opensuse.org/issues/57290
- Verification run: http://openqa.slindomansilla-vm.qa.suse.de/tests/2090
> Add YAML schedule for extra_tests_in_textmode_cont

- tests/hpc/slurm_master.pm
> HPC: Add slurm ha test case

- tests/hpc/slurm_master.pm
> HPC: Add slurm version check

- tests/console/orphaned_packages_check.pm
Fix for regression introduced #9263
- Related ticket: [test fails in orphaned_packages_check due to openSUSE-release-dvd](https://progress.opensuse.org/issues/62195)
* [Build20200115-kde@64bit](https://openqa.opensuse.org/tests/1146597)
* [Build553.1-gnome@64bit-2G](https://openqa.opensuse.org/tests/1146598)
* [Build20200115-gnome-live@USBboot_aarch64](https://openqa.opensuse.org/t1146602)
* [Build21.6-jeos@64bit_virtio-2G](https://openqa.opensuse.org/t1146603)
> Do not evaluate distro release package

- tests/console/kubeadm.pm
Add optional, to be manually started, support for openQA doing kubernetes certification testing
> kubeadm: Add upstream sonobuoy certification support

- tests/console/kubeadm.pm
Test was flaky, this should be less so
> Better detect sonobuoy start

- tests/console/kubeadm.pm
https://openqa.opensuse.org/tests/1147250#step/kubeadm/37
> Fix sonobuoy start monitoring and reporting

- data/virt_autotest/setup_dns_service.sh
1.Introduce another waiting time of 120s before attempting ping to avoid unnecessary ping failure.
2.Use -f option to ssh-copy-id from SLE 12 SP2 onwards to avoid "invalid option" error.
After installed and investigated all SLES from sles11sp4 up to sles15sp2, the -f option is only supported from SLE 12 SP2 onwards
- https://openqa.suse.de/tests/3783349#step/setup_dns_service/1
- https://openqa.suse.de/tests/3783359#step/setup_dns_service/12
- Needles: n/a
- sles11sp4 http://10.67.19.99/tests/712
- sles15sp2 http://10.67.19.99/tests/710
- And execute the following bash script manually to verify correct command is used:
#!/bin/bash
get_os_installed_release=`lsb_release -r | grep -oE "[[:digit:]]{2}"`
os_installed_release=$(echo …
> Make setup_dns_service script more resilient

- lib/main_common.pm
- tests/security/selinux/audit2allow.pm
- tests/security/selinux/print_se_context.pm
Implement test cases for SELinux, added 2 new test cases.
https://progress.opensuse.org/issues/61792
https://progress.opensuse.org/issues/61783  
- Needles: NA
sle15sp2: http://10.67.19.62/tests/1344
Tumbleweed: http://10.67.19.62/tests/1345
> Implement test for SELinux: -Z option, audit2allow

- lib/Utils/Architectures.pm
- lib/main_common.pm
- VR: https://openqa.opensuse.org/t1147046
> jeos: handle arm (armv7*) architecture

- tests/console/orphaned_packages_check.pm
* [Rescue-CD-aarch64-Build1.1-rescue@USBboot_aarch64](http://eris.suse.cz/tests/3969#step/orphaned_packages_check/1)
* [opensuse-15.1-GNOME-Live](http://eris.suse.cz/tests/3972)
* [opensuse-15.2-KDE-Live](http://eris.suse.cz/tests/3971)
* [opensuse-15.2-GNOME-Live](http://eris.suse.cz/tests/3970)
* [opensuse-15.2-GNOME-Live](http://eris.suse.cz/tests/3968)
> Livecd installations can yield orphans

- .travis.yml
- data/wicked/radvd/radvd-2.conf
- lib/mm_network.pm
- lib/network_utils.pm
- lib/wickedbase.pm
- tests/wicked/before_test.pm
- tests/wicked/ipv6/sut/t01_managed_on.pm
IPv6: Managed on, prefix length != 64, RDNSS
> IPv6: Managed on, prefix length != 64, RDNSS

- lib/utils.pm
- tests/console/hostname.pm
Reverts os-autoinst/os-autoinst-distri-opensuse#9336
> Revert "Remove hostname workaround bsc#1153402"

- tests/console/force_scheduled_tasks.pm
> Fix dummy commit in #9369

- tests/shutdown/cleanup_before_shutdown.pm
- variables.md
Change the way hostname maybe reset after installation
> Change the way hostname maybe reset after installation

- schedule/create_hdd_autoyast_wicked.yaml
wicked: Remove variable already propagated via Job Groups
> wicked: Remove variable already propagated via Job Groups

- lib/hpcbase.pm
> HPC: Lib hpcbase clean-up

- lib/hpc/cluster.pm
- lib/hpc/configs.pm
- lib/hpc/migration.pm
> HPC: Clean up of HPC specific libs

- data/autoyast_qam/15_installation.xml.ep
- Verification run: https://openqa.suse.de/tests/3818653
> Fix QAM installtest auotyast profile for s390x

- tests/sles4sap/wizard_hana_install.pm
Add `sap-installation-wizard` test for textmode.
- Related ticket: https://progress.opensuse.org/issues/62357
- Needles: Already created in o.s.d.
- Verification run: https://openqa.suse.de/t3819406
- Regression test: https://openqa.suse.de/t3820778
**NOTE:** some needles have not been created yet, because I didn't had the "issues" (so it's mainly the needles related to errors)
**NOTE2:** the failure in the regression test is for another reason (not yet identified)
> Add SAP wizard textmode test

- schedule/qam/common/mau-systemd.yaml
- Related ticket: https://progress.opensuse.org/issues/62471
> Exclude test_09_issue_2691 due to test failure

- lib/bootloader_pvm.pm
VR: https://openqa.suse.de/tests/3826527
> Ensure pvm gets booted

- tests/qam-minimal/install_update.pm
- Fail: https://openqa.suse.de/tests/3817567#step/update_minimal/58
https://openqa.suse.de/tests/3833326
https://openqa.suse.de/tests/3833327
> Fix reboot in update_minimal test on s390x

- tests/x11/gedit.pm
- tests/x11/ooffice.pm
- Fail: https://openqa.suse.de/tests/3832027#step/ooffice/6
https://openqa.suse.de/tests/3833426
https://openqa.suse.de/tests/3833427
https://openqa.suse.de/tests/3833428
> Type slower to avoid common typing failures

- lib/y2snapper_common.pm
- Related ticket: https://progress.opensuse.org/issues/62474
https://openqa.suse.de/tests/3834653 15sp1
https://openqa.suse.de/tests/3834654 12sp5
> Disable timeline snapshots in test config

- tests/console/orphaned_packages_check.pm
* [sle-12-SP4-EC2-BYOS-Updates-x86_64-Build20200121-1-mau-extratests-publiccloud@ec2_t2.large](http://pdostal-server.suse.cz/tests/6705#step/orphaned_packages_check/15)
* [sle-12-SP4-EC2-BYOS-Updates-x86_64-Build20200121-1-mau-extratests-publiccloud@ec2_t2.large](http://pdostal-server.suse.cz/tests/6706)
> Handle whitespaces in package names

- tests/ha/ctdb.pm
This PR forces samba installation, it seems samba is not already installed in SLE15.
`$join_timeout` is also replaced by `$ctdb_timeout`, it doesn't make sense to use cluster join timeout here.
- Failed test: http://1a102.qa.suse.de/tests/2916#step/ctdb/11
- Needles: N/A
- Verification run for SLE15: [Node1](http://1a102.qa.suse.de/tests/2931) -  [Node2](http://1a102.qa.suse.de/tests/2932) -  [Client](http://1a102.qa.suse.de/tests/2933)
Tests failed in remove_node module, it's not related to this PR, I will push a fix later for it.
> Make sure samba is installed for ctdb test

- lib/susedistribution.pm
- tests/console/copy_iso_to_external_drive.pm
- tests/systemd_testsuite/test_09_issue_2691.pm
- tests/virt_autotest/reboot_and_wait_up.pm
see https://progress.opensuse.org/issues/34471
verification tests:
http://f40.suse.de/tests/5585#step/test_09_issue_2691/1
http://f40.suse.de/tests/5589#step/installation_overview/2
https://openqa.suse.de/tests/3647761#step/reboot_and_wait_up_normal/4
> Replace tag text-login by tty$Nr-selected

- lib/apachetest.pm
- Related ticket: https://progress.opensuse.org/issues/62747
- Needles: N/A
- Verification run: https://openqa.opensuse.org/tests/1158278 (passed)
> test_pgsql: Add postgresql 12 as an option

- lib/hpcbase.pm
> HPC: Base lib clean-up

- schedule/vagrant.yaml
- tests/virtualization/vagrant/sshfs.pm
- Needles: not required
- Verification run: ~~https://openqa.opensuse.org/tests/1051809~~ ~~https://openqa.opensuse.org/tests/1057377~~ ~~https://openqa.opensuse.org/t1078645~~ https://openqa.opensuse.org/tests/1158478
> Add tests for the vagrant-sshfs plugin

- tests/console/sudo.pm
In newer kernels (>= 5.4), the drop_caches proc file has been turned into a
write-only file. As such, reading from it is no longer permitted.
https://github.com/torvalds/linux/commit/204cb79ad42f015312a5bbd7012d09c93d9b46fb
- Related ticket: https://progress.opensuse.org/issues/62168
- Needles: N/A
- Verification run: https://openqa.opensuse.org/tests/1158750 (passed)
> sudo: Stop trying to read from /proc/sys/vm/drop_caches

- lib/x11test.pm
- tests/x11/gdm_session_switch.pm
- Fail: https://openqa.suse.de/tests/3832235#step/gdm_session_switch/71
http://10.100.12.155/tests/14292 15sp1
https://openqa.suse.de/tests/3840988 15sp1
https://openqa.suse.de/tests/3840986 15sp2 virtio
https://openqa.suse.de/tests/3840987 15sp2
> Rework gdm_session_switch to get relevant logs

- tests/qam-updinstall/update_install.pm
- Fail: https://openqa.suse.de/tests/3819037#step/update_install/42
- Verification run: https://openqa.suse.de/tests/3850458
> Remove rmt-server-pubcloud conflict of rmt-server-config

- tests/hpc/slurm_master.pm
> HPC: Correct sanity check for pmix

- tests/ha/migrate_clvmd_to_lvmlockd.pm
While testing SLES+HA migrations to 15-SP2 from a previous version of the OS, it is necessary to migrate any **clvm** resources to **lvmlock** as **clvm** has been removed from SLES starting on 15-SP2.
To handle most cases, qcow2 images for SLES+HA 15-GM and 15-SP1 were generated without **clvm** resources, while older qcow2 images have **clvm** resources configured as **lvmlockd** is not available before 15-GM; this allows the test code to only load the `ha/migrate_clvmd_to_lvmlockd.pm` test module when performing migrations from versions of SLES+HA older than 15-GM.
However, the SLES+HA 11-SP4 qcow2 images in use for the migration tests do not have all of the same HA resources as the SLES+HA 12-* qcow2 images do, and even some of the resource names are different, so the …
> Handle clvm to lvmlockd migration when original system is 11-SP4

- lib/hpcbase.pm
> HPC: Base module doc updates

- lib/main_common.pm
- tests/cpu_bugs/xen_pv.pm
Because in the past we do not have the automation testing for XEN PV, so I implement the automation XEN function test to openQA.
- Verification run: http://10.67.132.101/tests/134
> automated XEN guest function test

- tests/yast2_gui/yast2_software_management.pm
especially on slow/busy workers.
- VR: https://openqa.opensuse.org/t1163712
> yast2_software_management: increase timeout as default value is a bit short

- data/regproxy/regproxy.py
Completes the fix in dfb0273
Verification run: https://openqa.opensuse.org/t1165005
> regproxy: fix more entries referencing hydra

- tests/virt_autotest/reboot_and_wait_up.pm
Reverts os-autoinst/os-autoinst-distri-opensuse#9487
> Revert "Add first-tty-selected in reboot_and_wait_up to cover issue from #9048"

- lib/main_common.pm
- tests/virtualization/xen/storage.pm
- Related ticket: [poo#50762](https://progress.opensuse.org/issues/50762)
- Verification run: [xen](http://pdostal-server.suse.cz/tests/6731) [kvm](http://pdostal-server.suse.cz/tests/6629)
> Add virtualization storage test

- tests/hpc/slurm_master.pm
http://10.160.65.14/tests/16525#
> HPC: Remove slurm.conf workaround

- tests/sles4sap/hana_cluster.pm
Add sleep after SAP daemon stop/start.
> sles4sap/hana_cluster: Add sleep after daemon stop/start

- lib/utils.pm
- Related ticket: https://progress.opensuse.org/issues/63349
- Verification run: http://openqa.slindomansilla-vm.qa.suse.de/tests/2193
> Check for Tumbleweed when it boots on s390x

- tests/console/php7_postgresql.pm
Verification:
```
openqa-clone-custom-git-refspec https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/9542 https://openqa.opensuse.org/tests/1170261
```
Created job #1170688: opensuse-15.2-JeOS-for-kvm-and-xen-x86_64-Build23.19-jeos@64bit_virtio-2G -> https://openqa.opensuse.org/t1170688
Related progress issue: https://progress.opensuse.org/issues/58918
> php7_postgresql: Ensure dependency "unzip" is installed

- tests/hpc/mpi_master.pm
- Verification run: http://10.160.65.14/tests/16555
> HPC: Check for openmpi^ match

- data/autoyast_qam/15_installtest.xml.ep
This PR adds the module sap-applications for being able to generate SAP qcow2 for maintenance update.
- Needles: N/A
- Verification run: [SLE15](http://1a102.qa.suse.de/tests/3195#step/repos/11) [SLE15 SP1](http://1a102.qa.suse.de/tests/3194#step/repos/11)
> Add SAP repo to SLE 15 QAM autoyast file

- tests/hpc/README.migration
- tests/hpc/hpc_master.pm
- tests/hpc/hpc_migration.pm
- tests/hpc/hpc_slave.pm
single machine: http://10.160.65.14/tests/16616
multimachine:
http://10.160.65.14/tests/16810
http://10.160.65.14/tests/16811
http://10.160.65.14/tests/16809
> HPC: Migration tests adaptions for SLE15SP2

- data/sles4sap/hana_cluster.conf
Remove invalid directivein configuration.
> sles4sap/hana_cluster: Remove invalid directive in configuration

- tests/cpu_bugs/xen_mitigations.pm
Xen hypervisor support branch-harden parameter.
http://mitigations.qa2.suse.asia/tests/9017
> Add branch-harden testcase for xen hypervisor

- lib/publiccloud/ec2.pm
- tests/publiccloud/run_ltp.pm
With new arm images, the repo url slightly changed.
- Related ticket: https://progress.opensuse.org/issues/44876
- Verification run: https://openqa.suse.de/t3904540
> publiccloud: run_ltp - use arm specific repo

- tests/installation/user_settings.pm
- Related ticket: https://progress.opensuse.org/issues/46190
- Needles:
- https://gitlab.suse.de/openqa/os-autoinst-needles-sles/merge_requests/1315
- https://github.com/os-autoinst/os-autoinst-needles-opensuse/pull/632
- [Tumbleweed](https://github.com/os-autoinst/os-autoinst-needles-opensuse/pull/632)
- [SLE15-SP2 131.1](http://openqa.slindomansilla-vm.qa.suse.de/tests/2154)
- [Leap 15.2](http://openqa.slindomansilla-vm.qa.suse.de/tests/2170)
- [SLE15-SP1](http://openqa.slindomansilla-vm.qa.suse.de/tests/2179)
- [SLE15](http://openqa.slindomansilla-vm.qa.suse.de/tests/2219)
- [SLE12-SP5](http://openqa.slindomansilla-vm.qa.suse.de/tests/2222)
- [SLE12-SP4](http://openqa.slindomansilla-vm.qa.suse.de/tests/2238)
> Workaround fullname typing issue

- tests/installation/partitioning.pm
- Related ticket: https://progress.opensuse.org/issues/63559
- Needles: https://gitlab.suse.de/openqa/os-autoinst-needles-sles/merge_requests/1329
- Verification run: http://10.67.133.10/tests/76
> btrfs-progs: Update partitioning step for create ext4 root

- tests/kernel/ib_tests.pm
Remove the dmesg checking, as this never properly worked and instead
make sure we upload all relevant logs. In order to simplify adding new
logs and avoid duplicating all this code, add a new function that
handles all relevant logs, and this function is called after successful
run and in the post_fail_hook
Also, make sure to run the post_fail_hook from the parent class.
https://openqa.suse.de/tests/3913655 won't complete for obvious reasons: the second job won't be started when running with this PR.
> Clean ib_tests

- tests/installation/bootloader_s390.pm
Verification run: http://openqa.slindomansilla-vm.qa.suse.de/tests/2241
> Change bugref from duplicate to current bug

- data/hpc/julog.sh
- tests/hpc/slurm_master.pm
- tests/hpc/slurm_slave.pm
- Verification run: this extension was checked against all currently available slurm conf:
http://10.160.65.14/tests/17758
http://10.160.65.14/tests/17784
http://10.160.65.14/tests/17763
http://10.160.65.14/tests/17768
http://10.160.65.14/tests/17774
> HPC: Add external tests

- products/sle/main.pm
- schedule/kernel/ibtest-master.yaml
- schedule/kernel/ibtest-slave.yaml
Add two schedules, ibtest-master and ibtest-slave and remove the ibtests
from sle/main.pm
> Add a declarative schedule for ibtests

- tests/yast2_gui/yast2_instserver.pm
- use alt-i to select directory alias field
- add needles for better control than blind key pressing
- add timeout with default 5 in send_key_and_wait, does speedup test
due to blinking cursor
- add timeout parameter in wait_still_screen, same reason as above
- Related ticket: https://progress.opensuse.org/issues/63850
https://openqa.suse.de/tests/3926626 15sp1
https://openqa.suse.de/tests/3926625 15
http://10.100.12.155/tests/14531 15sp1
http://10.100.12.155/tests/14529 15
http://10.100.12.155/tests/14530 12sp5
> Fix and make yast2_instserver test more robust

- data/autoyast_sle15/autoyast_mlx_con5.xml
This fixes the previous fix (e0290c8) by adding missing <use> again and
by beeing more explicit.
>  Fix the autoyast profile for mlx_con5

- data/generalhw_scripts/flash_usb_otg.sh
- data/generalhw_scripts/get_sol_over_SSH.sh
- data/generalhw_scripts/get_sol_ttyUSB0.sh
- lib/Utils/Backends.pm
Tested locally as o3 does not support it yet.
> generalhw fixes

- lib/Mitigation.pm
- lib/main_common.pm
- lib/vt_perf_libs.pm
- products/sle/main.pm
- tests/virt_autotest/login_console.pm
- tests/vt_perf/baremetal.pm
- tests/vt_perf/kvm_guest.pm
- tests/vt_perf/xen_guest.pm
This commit is as baseline of VT perf.
The target is run all performance benchmark testcase in KVM guest, XEN PV and XEN HVM guests.0
VR:
XEN_GUEST:
http://mitigations.qa2.suse.asia/tests/9070
KVM_GUEST:
http://mitigations.qa2.suse.asia/tests/9071
BAREMETAL:
http://mitigations.qa2.suse.asia/tests/9072
> Add VT perf testcases

- schedule/ha/qam/12-SP2/qam-client.yaml
- schedule/ha/qam/12-SP2/qam-cluster_2nodes_01.yaml
- schedule/ha/qam/12-SP2/qam-cluster_2nodes_02.yaml
- schedule/ha/qam/12-SP3/qam-client.yaml
- schedule/ha/qam/12-SP3/qam-cluster_2nodes_01.yaml
- schedule/ha/qam/12-SP3/qam-cluster_2nodes_02.yaml
This PR enables both HA QAM automation for SLE12 SP2/SP3 and YAML scheduling.
- Needles: N/A
- Verification run: No impact on other things as they are completely independent tests.
> Add HA QAM YAML files for 12sp2_sp3

- data/autoyast_sle15/autoyast_resize_luks2.xml
- lib/bootloader_pvm.pm
- lib/bootloader_setup.pm
- schedule/yast/autoyast_resize_luks2.yaml
- tests/autoyast/installation.pm
- tests/autoyast/pre_partitioning.pm
- tests/console/validate_file_system.pm
- tests/installation/bootloader_s390.pm
Add AutoYaST scenario to resize luks2 partition.
- Related ticket: https://progress.opensuse.org/issues/58250
- Needles: https://gitlab.suse.de/openqa/os-autoinst-needles-sles/-/merge_requests/1333
- QA SLE Functional Y MR: https://gitlab.suse.de/qsf-y/qa-sle-functional-y/merge_requests/135
- Verification run: http://rivera-workstation.suse.cz/tests/1036#step/validate_file_system/15
> Add AutoYaST scenario to resize luks2 partition

- tests/console/orphaned_packages_check.pm
- Related ticket: [[JeOS] orphan table is not parsed correctly](https://progress.opensuse.org/issues/63889)
* [no reg](http://eris.suse.cz/tests/4734#step/orphaned_packages_check/1)
* [opensuse-Tumbleweed-DVD-x86_64-Build20200227-textmode@64bit](http://eris.suse.cz/tests/4731)
* [sle-15-SP2-JeOS-for-kvm-and-xen-x86_64-Build7.77-jeos-main_intel_image@uefi-virtio-vga](http://eris.suse.cz/tests/4735)
* [opensuse-15.1-JeOS-for-kvm-and-xen-x86_64-Build8.10.26-jeos@64bit_virtio-2G](http://eris.suse.cz/tests/4736)
* [opensuse-15.2-DVD-x86_64-Build594.1-extra_tests_in_textmode@64bit](http://eris.suse.cz/tests/4737)
* [sle-15-SP1-EC2-BYOS-Updates-x86_64-Buildmloviska_os-autoinst-distri-opensuse_9649-mau-extratests-publiccloud@mloviska_os-autoinst-distri-opensuse_zypper_orphans …
> Zypper orphans change table style

- tests/x11/seahorse.pm
- Related ticket: https://progress.opensuse.org/issues/62477
https://openqa.suse.de/tests/3944963
http://10.100.12.155/tests/14577
http://10.100.12.155/tests/14576
http://10.100.12.155/tests/14573
> Add wait time to avoid occasional click failure

- tests/console/zypper_lifecycle_toolchain.pm
- Related ticket: https://progress.opensuse.org/issues/64087
- Verification run: http://10.100.12.155/tests/14589
> Fix zypper_lifecycle_toolchain, update package version

- tests/console/orphaned_packages_check.pm
- Verification run: [uploaded logs](http://eris.suse.cz/tests/4793#downloads)
> Upload zypper log from post_fail_hook

- lib/susedistribution.pm
add online install expertpartitioner key
Related ticket:N/A
Needles: N/A
Verification run: http://10.67.129.4/tests/4944#step/partitioning/1
> fix online install expertpartitioner key

- lib/bootloader_setup.pm
- Verification run: (coming soon)
> Revert "s390x: Handle multiple qcows as HDDs"

- lib/x11test.pm
- Fail: https://openqa.suse.de/tests/3952689#step/evolution_mail_pop/37
- Verification run: http://10.100.12.155/tests/14612
> Replace wait_screen_change with more reliable wait_still_screen

- lib/power_action_utils.pm
Reverts os-autoinst/os-autoinst-distri-opensuse#9598
> Revert "Do not disconnect before selecting x11 console"

- data/autoyast_qam/12_installation.xml.ep
- data/autoyast_qam/15_installation.xml.ep
- data/qam/dracut/12-SP2_custom_lvm.xml.ep
- data/qam/dracut/12-SP2_custom_usr.xml.ep
- data/qam/dracut/12_custom_lvm.xml.ep
- data/qam/dracut/12_custom_usr.xml.ep
- data/qam/dracut/15_custom_lvm.xml.ep
- data/qam/dracut/15_custom_usr.xml.ep
- Fail: https://openqa.suse.de/tests/3961663#step/patch_and_reboot/29
- Verification run: https://openqa.suse.de/tests/3961872
> Increase and unify installation bootloader timeouts

- lib/power_action_utils.pm
- t/04_power_action_utils.t
Inspired by https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/9702
> t: Add tests for power_action_utils

- tests/console/command_not_found.pm
Ticket: https://progress.opensuse.org/issues/64045
> Use test rpm from server app module

- tests/publiccloud/instance_overview.pm
https://bugzilla.suse.com/show_bug.cgi?id=1165915
https://openqa.suse.de/tests/3968317
- Verification run: https://openqa.suse.de/tests/3968741#step/instance_overview/27
> Workaround bsc#1165915 on publiccloud

- tests/installation/addon_products_sle.pm
related bsc: https://bugzilla.suse.com/show_bug.cgi?id=1157780
Verification run: https://openqa.suse.de/tests/3975674
> Remove workaround for bsc#1157780

- tests/x11/rstudio_prepare.pm
- Needles: not required
- Verification run: https://openqa.opensuse.org/tests/1199305
> Don't install git in rstudio_prepare

- tests/console/command_not_found.pm
Hello,
I'm fixing `command_not_found.pm` on Public Cloud by usinf `iftop` instead of `xosview`.
The reason is that the `xosview` is not present on Public Cloud. This is a follow-up for #9706 
- Related ticket: [poo#64045](https://progress.opensuse.org/issues/64045)
- Verification run: [SLES12SP4@GCE-BYOS](http://pdostal-server.suse.cz/tests/7594) [SLES15SP1@EC2-BYOS](http://pdostal-server.suse.cz/tests/7595) [JeOS-15-SP2@64bit-virtio-vga](https://openqa.suse.de/tests/3976580) [SLES15sp2](https://openqa.suse.de/tests/3976879) [SLES12-SP1@mau-extratests](http://pdostal-server.suse.cz/tests/7599) [SLES15-SP1@mau-extratests](http://pdostal-server.suse.cz/tests/7597) [Tumbleweed@extra_tests_in_textmode](http://pdostal-server.suse.cz/tests/7601) …
> Fix command_not_found.pm on PC by using iftop as $not_installed_pkg

- lib/susedistribution.pm
- Fail:
https://openqa.suse.de/tests/3954023#step/gnome_music/5
https://openqa.suse.de/tests/3964879#step/yast2_snapper/24
http://10.100.12.155/tests/14627
https://openqa.suse.de/tests/3968846
https://openqa.suse.de/tests/3976768 migration with become_root
> Add wait time in script_sudo for bash within become_root

- lib/qam.pm
- tests/installation/add_update_test_repo.pm
- Related ticket: https://openqa.suse.de/tests/3968952#step/add_update_test_repo/88
https://openqa.suse.de/tests/3831723
https://openqa.suse.de/tests/3971757
https://openqa.suse.de/tests/3976219 15sp1 before (761 s)
https://openqa.suse.de/tests/3976722 15sp1 after (523 s)
https://openqa.suse.de/tests/3975997 12sp5 before (404 s)
https://openqa.suse.de/tests/3976757 12sp5 after (266 s)
https://openqa.suse.de/tests/3978665 s390x with today network/SCC issues
https://openqa.suse.de/tests/3978678 x86_64 with today network/SCC issues
> Extend and speedup add_update_test_repo test

- schedule/functional/extra_tests_textmode.yaml
- schedule/functional/extra_tests_textmode_mod_desktop.yaml
Ticket: https://progress.opensuse.org/issues/64045
> Move libvorbis test to separate testsuite

- tests/installation/await_install.pm
Reverts os-autoinst/os-autoinst-distri-opensuse#9718
> Revert "Ensure timeout value in await_install less than MAX_JOB_TIME"

- tests/sles4sap/patterns.pm
This PR adapts pattern test to be able running on a plain SLE.
Because some patterns listed in the test are only availables on SLE4SAP.
- Needles: N/A
[SLE 15 SP1 NW cli installation](http://1a102.qa.suse.de/tests/3433)
[SLE 15 SP1 HANA cli installation](http://1a102.qa.suse.de/tests/3440)
[SLE 15 GA NW cli installation](http://1a102.qa.suse.de/tests/3445)
[SLE 15 GA HANA cli installation](http://1a102.qa.suse.de/tests/3440) doesn't [work](http://1a102.qa.suse.de/tests/3446/file/serial_terminal.txt) with SPS02rev0 (not supported).It will be tested later with latest SPS03rev0.
[SLE 12 SP5 NW cli installation](http://1a102.qa.suse.de/tests/3454)
[SLE 12 SP5 HANA cli installation](http://1a102.qa.suse.de/tests/3453)
[SLE 12 SP4 NW cli …
> Skip specific sles4sap patterns if sle version

- tests/installation/bootloader_s390.pm
Suggested by Berthold
- Verification run: https://openqa.opensuse.org/tests/1199488
> List kernel modules before formatting DASD

- schedule/qam/12-SP1/qam-minimal.yaml
- schedule/qam/12-SP2/qam-minimal.yaml
- schedule/qam/12-SP3/qam-minimal.yaml
- schedule/qam/12-SP4/qam-minimal.yaml
- schedule/qam/12-SP5/qam-minimal.yaml
- schedule/qam/15-SP1/qam-minimal.yaml
- schedule/qam/15/qam-minimal.yaml
Publish updated image, image will be used by grub2 minimal tests
- Fail: https://openqa.suse.de/tests/3965495 created image is not updated
https://openqa.suse.de/tests/3984796 12sp5 x86_64
https://openqa.suse.de/tests/3984797 12sp5 s390x
https://openqa.suse.de/tests/3984798 12sp5 ppc64le
https://openqa.suse.de/tests/3984799 12sp5 aarch64
https://openqa.suse.de/tests/3984800 15 x86_64
https://openqa.suse.de/tests/3984801 15 s390x
https://openqa.suse.de/tests/3984802 15 ppc64le
https://openqa.suse.de/tests/3984803 15 aarch64
> Create yaml scheduler for qam-mininal(+sle15) tests

- schedule/qam/12-SP1/qam-minimal.yaml
- schedule/qam/12-SP2/qam-minimal.yaml
- schedule/qam/12-SP3/qam-minimal.yaml
- schedule/qam/12-SP4/qam-minimal.yaml
- schedule/qam/12-SP5/qam-minimal.yaml
- schedule/qam/15-SP1/qam-minimal.yaml
- schedule/qam/15/qam-minimal.yaml
- Fail: https://openqa.suse.de/tests/3988455#step/grub_test/4
https://openqa.suse.de/tests/3988857 x86_64
https://openqa.suse.de/tests/3988854 s390x
https://openqa.suse.de/tests/3988856 ppc64le
https://openqa.suse.de/tests/3988855 aarch64
> Fix first boot in qam-minimal yaml

- tests/update/prepare_system_for_update_tests.pm
- Fail: https://openqa.suse.de/tests/3988217#step/prepare_system_for_update_tests/14
- Verification run: https://openqa.suse.de/tests/3988981
> Increase timeout for pkcon refresh

- schedule/qam/12-SP1/qam-minimal.yaml
- schedule/qam/12-SP2/qam-minimal.yaml
- schedule/qam/12-SP3/qam-minimal.yaml
- schedule/qam/12-SP4/qam-minimal.yaml
- schedule/qam/12-SP5/qam-minimal.yaml
- schedule/qam/15-SP1/qam-minimal.yaml
- schedule/qam/15/qam-minimal.yaml
- Fail: https://openqa.suse.de/tests/3988790
https://openqa.suse.de/tests/3989018 uefi
https://openqa.suse.de/tests/3989022 64bit
https://openqa.suse.de/tests/3989023 s390x
https://openqa.suse.de/tests/3989024 ppc64le
https://openqa.suse.de/tests/3989025 aarch64
> Fix boot with bootloader_start in qam-minimal yaml

- schedule/functional/extra_tests_textmode_mod_desktop.yaml
Ticket: https://progress.opensuse.org/issues/64045
> Don't run aplay test on s390x

- lib/main_common.pm
- tests/console/check_package_version.pm
Check package version which should be upgrade to expected version
Some jira features need update some packages' version, we need check package version has been updated after migration testing.
- Related ticket: https://progress.opensuse.org/issues/60305
https://openqa.nue.suse.com/tests/4001161#
> Check package version which should be upgrade to expected version

- lib/main_common.pm
- tests/kernel/install_ltp.pm
Verification run (tested on SLES for QA & QAM, Tumbleweed):
- install_ltp: http://quasar.suse.cz/tests/4879#downloads, http://quasar.suse.cz/tests/4878#downloads, http://quasar.suse.cz/tests/4877#downloads, http://quasar.suse.cz/tests/4876#downloads
- tests: http://quasar.suse.cz/tests/4884, http://quasar.suse.cz/tests/4889, http://quasar.suse.cz/tests/4887, http://quasar.suse.cz/tests/4886
> LTP: minor runtest file cleanup

- tests/installation/accept_license.pm
Reverts os-autoinst/os-autoinst-distri-opensuse#9825
> Revert "Introduce timeout with softfailure for accept license"

- schedule/qam/12-SP1/qam-minimal.yaml
- schedule/qam/12-SP2/qam-minimal.yaml
- schedule/qam/12-SP3/qam-minimal.yaml
- schedule/qam/12-SP4/qam-minimal.yaml
from 12sp[1234] qam-minimal yaml
- Fail: https://openqa.suse.de/tests/4006251#step/system_role/2
> Remove not present system role test

- tests/console/libgpiod.pm
- tests/console/sysstat.pm
Errors seen at https://openqa.opensuse.org/tests/1203871
> Fix armv7 tests on JeOS-extra

- tests/installation/user_settings.pm
Failing test: https://openqa.suse.de/tests/4009395#step/user_settings/3
> Add missing import for enter_userinfo()

- tests/sles4sap/hana_cluster.pm
Cluster configuration should done only on the first node.
This commit also remove a workaround for bsc#1153402, as this is now done in `console/hostname.pm`.
- Needles: N/A
- Verification run: http://1b210.qa.suse.de/tests/6417
> Fix HANA cluster on SLES4SAP

- tests/console/orphaned_packages_check.pm
- problem:[wrongly parsed zypper table](https://openqa.opensuse.org/tests/1206590#step/orphaned_packages_check/11)
* [sle-15-SP2-JeOS-for-kvm-and-xen-x86_64](https://openqa.suse.de/tests/4013002#step/orphaned_packages_check/1)
* [opensuse-Tumbleweed-JeOS-for-kvm-and-xen-x86_64](https://openqa.opensuse.org/tests/1208268#step/orphaned_packages_check/1)
* [opensuse-15.2-JeOS-for-kvm-and-xen-x86_64](https://openqa.opensuse.org/tests/1208351#step/orphaned_packages_check/1)
> Handle repo warning messages from zypper

- tests/x11/multi_users_dm.pm
Ticket: https://progress.opensuse.org/issues/64613
Verification:
https://openqa.opensuse.org/tests/1208347
https://openqa.opensuse.org/tests/1209234
> Fix multi_user_dm test on xfce

- lib/windowsbasetest.pm
- tests/wsl/firstrun.pm
- tests/wsl/prepare_wsl_feature.pm
follow up PR for https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/9800
> Minor fixes for opensuse images

- schedule/qam/12-SP4/qam-create_hdd_sle_sap_gnome.yml
- schedule/qam/12-SP4/qam-create_hdd_sles4sap_gnome.yml
- schedule/qam/12-SP4/qam-sle_sles4sap_scc_gnome_hana_cli.yml
- schedule/qam/12-SP4/qam-sle_sles4sap_scc_gnome_netweaver_cli.yml
- schedule/qam/12-SP4/qam-sle_sles4sap_scc_gnome_sapconf.yml
- schedule/qam/12-SP4/qam-sle_sles4sap_scc_gnome_saptune.yml
- schedule/qam/12-SP5/qam-create_hdd_sle_sap_gnome.yml
- schedule/qam/12-SP5/qam-create_hdd_sles4sap_gnome.yml
- schedule/qam/12-SP5/qam-sle_sles4sap_scc_gnome_hana_cli.yml
- schedule/qam/12-SP5/qam-sle_sles4sap_scc_gnome_netweaver_cli.yml
- schedule/qam/12-SP5/qam-sle_sles4sap_scc_gnome_sapconf.yml
- schedule/qam/12-SP5/qam-sle_sles4sap_scc_gnome_saptune.yml
- schedule/qam/15-SP1/qam-create_hdd_sle_sap_gnome.yml
- schedule/qam/15-SP1/qam-create_hdd_sles4sap_gnome.yml
- schedule/qam/15-SP1/qam-sle_sles4sap_scc_gnome_hana_cli.yml
- schedule/qam/15-SP1/qam-sle_sles4sap_scc_gnome_netweaver_cli.yml
- schedule/qam/15-SP1/qam-sle_sles4sap_scc_gnome_sapconf.yml
- schedule/qam/15-SP1/qam-sle_sles4sap_scc_gnome_saptune.yml
- schedule/qam/15/qam-create_hdd_sle_sap_gnome.yml
- schedule/qam/15/qam-create_hdd_sles4sap_gnome.yml
- schedule/qam/15/qam-sle_sles4sap_scc_gnome_hana_cli.yml
- schedule/qam/15/qam-sle_sles4sap_scc_gnome_netweaver_cli.yml
- schedule/qam/15/qam-sle_sles4sap_scc_gnome_sapconf.yml
- schedule/qam/15/qam-sle_sles4sap_scc_gnome_saptune.yml
- tests/sles4sap/patterns.pm
- tests/sles4sap/sapconf.pm
This PR adds new tests we want to execute twice a day to make sure of our repos consistency.
In a first time, these tests will be configured only for 15 and 15 SP1.
Two tests are for generating up-to-date qcow2 images, one in SLE and another one in SLES4SAP.
With those, we are testing SAP products installation (hana, netweaver, sapconf and saptune).
PR contains YAML files for scheduling and some changes in the code for using it on plain SLE.
- Needles: N/A
**SLE 15:**
[qam-create_hdd_sle_sap_gnome](http://1a102.qa.suse.de/tests/3641)
[qam-create_hdd_sles4sap_gnome](http://1a102.qa.suse.de/tests/3640)
[qam-sles4sap_scc_gnome_hana_cli with sle qcow2](http://1a102.qa.suse.de/tests/3668)
[qam-sles4sap_scc_gnome_hana_cli with sles4sap …
> Add new SAP tests on plain SLE and SLES4SAP

- lib/publiccloud/provider.pm
It looks like the connection to VAULT server is unstable. So we do some
sanity and just retry on failure.
- Related ticket: https://progress.opensuse.org/issues/64637
- Verification run: https://openqa.suse.de/t4014084
> publiccloud: Add retry loop for Vault REST API calls

- tests/console/supportutils.pm
- Related ticket: [poo#64728](https://progress.opensuse.org/issues/64728) [bsc#1166774](https://bugzilla.suse.com/show_bug.cgi?id=1166774)
- Verification run: [SLES12SP4@publiccloud](http://pdostal-server.suse.cz/tests/7810)
> Fix bsc#1166774 on supportutils test module

- tests/hpc/slurm_master.pm
- tests/hpc/slurm_slave.pm
> HPC: Add some rpms to hpc_fast_moving_tests

- tests/jeos/prepare_firstboot.pm
* Tumbleweed https://openqa.opensuse.org/t1212126
* Leap 15.2 https://openqa.opensuse.org/t1212123
> Use workaround on Leap only since Tumbleweed now includes jeos-firstboot

- tests/publiccloud/img_proof.pm
Till now, we defined the variable PUBLIC_CLOUD_IMG_PROOF_TESTS in each
testsuite, which needed to defined 6 suites.
With this change we make the decission which tests are running for which
FLAVOR inside the test-module.
Also fixing the problem, that we run ec2_byos tests on EC2-CHOST-BYOS
image, but this image doesn't have ec2metadata installed bsc#1166890.
- Verification run: https://openqa.suse.de/tests/4027411
```
openqa-clone-custom-git-refspec https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/9863 https://openqa.suse.de/tests/4016712 PUBLIC_CLOUD_IMG_PROOF_TESTS=default
```
> publiccloud: Define img_proof test list it the module

- lib/power_action_utils.pm
- Related ticket: https://progress.opensuse.org/issues/62366
- x86_64: https://openqa.suse.de/tests/4029409#step/setup/11
- s390-kvm: all workers broken :(
> Fix extra white space

- lib/bootloader_pvm.pm
In certain tests, when booting from PXE an LPAR over pvm or pvm_hmc, it is possible that the boot process aborts and the GRUB menu is shown again. This pull request adds code so this screen can be asserted, and the boot process (initrd and linux command lines) can be attempted for up to 3 times before failing.
[This](http://mango.suse.de/tests/2122) is the type of failure this PR attempts to workaround. In particular check [screen 23](http://mango.suse.de/tests/2122#step/bootloader/23) and [screen 24](http://mango.suse.de/tests/2122#step/bootloader/24).
- Needles: https://gitlab.suse.de/openqa/os-autoinst-needles-sles/-/merge_requests/1353
- Verification run: http://mango.suse.de/tests/2117
> Attempt to boot from PXE up to 3 times over pvm/pvm_hmc

- tests/kernel_performance/run_perf_case.pm
update performance case pass/fail logic. and one more check about fail.list to confirm case result.
- Needles: N/A
fail case:  http://10.67.129.4/tests/10250#
pass case: http://10.67.129.4/tests/10249
> update perf case pass fail logic

- tests/qemu/kvm.pm
- tests/qemu/qemu.pm
Ticket: https://bugzilla.suse.com/show_bug.cgi?id=1154198
https://openqa.suse.de/tests/4030056
> Fix qemu test on s390x

- schedule/migration/s390x-zVM-Upgrade.yaml
Create new schedule file for s390 zvm upgrade case
- Related ticket: https://progress.opensuse.org/issues/64433
- Needles: n/a
> Create new schedule file for s390 zvm upgrade case

- lib/publiccloud/gce.pm
The --guest-os-features value SECURE_BOOT is obsolete.
We are getting:
gcloud.compute.images.create) argument --guest-os-features: SECURE_BOOT
must be one of [MULTI_IP_SUBNET, UEFI_COMPATIBLE,
VIRTIO_SCSI_MULTIQUEUE, WINDOWS]
- Related ticket: https://progress.opensuse.org/issues/64782
> publiccloud: Fix gce img-upload - SECURE_BOOT obsolete

- schedule/functional/extra_tests_textmode_mod_desktop.yaml
Ticket: https://progress.opensuse.org/issues/64045
Verification: https://openqa.suse.de/t4035944
> Do not schedule tests requiring soundcard on XEN

- tests/x11/window_system.pm
> Fix typo and replace record_soft_failure with die

- lib/Mitigation.pm
- lib/main_common.pm
- tests/cpu_bugs/xen_hvm.pm
This is the automated func test for XEN PV and HVM. Due to their differences, we separate them into two files. And we pack the same part in the Mitigation.pm. Moreover, to meet our customers' s requirements, except for the full-run option, we add the option to test one parameter individually.
- Verification run for XEN_PV: 
ALL: http://mitigations.qa2.suse.asia/tests/9574#
SINGLE: http://mitigations.qa2.suse.asia/tests/9580#step/xen_pv/105
- Verification run for XEN_HVM: 
ALL: http://mitigations.qa2.suse.asia/tests/9402#
http://mitigations.qa2.suse.asia/tests/9585#
SINGLE: http://mitigations.qa2.suse.asia/tests/9581#
> Automated Func tests of Xen PV and HVM

- schedule/yast/skip_registration/skip_registration.yaml
Job Group settings also need to be merged: https://gitlab.suse.de/qsf-y/qa-sle-functional-y/-/merge_requests/152
- Related ticket: https://progress.opensuse.org/issues/63217
- Verification run: https://openqa.suse.de/tests/4042433
> Add schedule for skip_registration test suite

- lib/opensusebasetest.pm
> Remove redundant 'with'

- tests/hpc/hpc_migration.pm
For SLE15 SP1+ there is a new module - Python2 and so it make sense
to check if SUSEConnect reports the module cprrectly after the
migration is completed
> HPC: Add Python2 module check for sle15+

- schedule/qam/12-SP4/qam-minimal.yaml
- Fail: https://openqa.suse.de/tests/4053123
- Verification run: http://10.100.12.155/tests/14860
> Add system_role on x86_64 12sp4 qam-minimal yaml

- tests/console/yast2_lan_device_settings.pm
postfix start log
``
localhost config_postfix[15316]: /usr/sbin/postconf: fatal: parameter inet_interfaces: no local interface found for 192.168.1.119
``
- Related ticket: [[JeOS] test fails in evolution_prepare_servers](https://progress.opensuse.org/issues/64914)
- Needles:
* [o3](https://openqa.opensuse.org/tests/1219184#step/yast2_lan_device_settings/47)
* [osd tbd]()
* [opensuse-15.1-JeOS-for-kvm-and-xen-x86_64](https://openqa.opensuse.org/tests/1219184#step/yast2_lan_device_settings/65)
* [opensuse-Tumbleweed-JeOS-for-kvm-and-xen-x86_64](https://openqa.opensuse.org/tests/1219204#step/yast2_lan_device_settings/41)
> Check /etc/hosts after changing back to DHCP

- tests/yast2_cmd/yast_keyboard.pm
- Fail: https://openqa.suse.de/tests/4068228
> Increase timeout otherwise still_time can exceed it

- lib/main_common.pm
- tests/security/tpm2/tpm2_engine/tpm2_engine_ecdsa_operation.pm
- tests/security/tpm2/tpm2_engine/tpm2_engine_info.pm
- tests/security/tpm2/tpm2_engine/tpm2_engine_random_data.pm
- tests/security/tpm2/tpm2_engine/tpm2_engine_rsa_operation.pm
- tests/security/tpm2/tpm2_engine/tpm2_engine_self_sign.pm
- tests/security/tpm2/tpm2_env_setup.pm
- tests/security/tpm2/tpm2_tools/tpm2_tools_auth.pm
- tests/security/tpm2/tpm2_tools/tpm2_tools_encrypt.pm
- tests/security/tpm2/tpm2_tools/tpm2_tools_self_contain_tool.pm
- tests/security/tpm2/tpm2_tools/tpm2_tools_sign_verify.pm
Create this PR to implement test for tpm2 related tasks, including tpm2_server(env setup),tpm2_engine and tpm2_tools.
https://progress.opensuse.org/issues/64905
https://progress.opensuse.org/issues/64902
https://progress.opensuse.org/issues/64899
- Needles: N/A
http://10.67.17.9/tests/110
The failed case is caused by bug https://bugzilla.suse.com/show_bug.cgi?id=1166936
> Implement test for tpm2_server,tpm2_engine and tpm2_tools

- tests/x11/gnomecase/change_password.pm
- Related ticket: https://progress.opensuse.org/issues/62687
* x86_64: https://openqa.opensuse.org/t1220990
* aarch64: https://openqa.opensuse.org/t1221202
> Fix change_password test for aarch64

- lib/apachetest.pm
- Related ticket: https://progress.opensuse.org/issues/65175
- Verification run: http://10.100.12.155/tests/14886
> Fix wrong configdir used after upgrade and drop all used db's

- tests/console/aide_check.pm
1. Rework and Fix the aide initialize database error
2. Add more check on differences between database and file system
- Related ticket: https://progress.opensuse.org/issues/64364
- Needles: NA
- Verification run: http://10.163.10.37/tests/567 [aide_check]
> Rework the aide test case and fix the initialized database error

- tests/installation/installation_overview.pm
Reverts os-autoinst/os-autoinst-distri-opensuse#9882
> Revert "Fail when detecting wrong desktop"

- schedule/qam/12-SP2/qam-minimal.yaml
- schedule/qam/12-SP3/qam-minimal.yaml
- Fail: https://openqa.suse.de/tests/4060960
https://openqa.suse.de/tests/4084244 12sp2
https://openqa.suse.de/tests/4084229 12sp3
> Add system_role on x86_64 12sp[23] qam-minimal yaml

- tests/console/suseconnect_scc.pm
- Related ticket: adhoc QU3 testing
* [sle-15-SP1-JeOS-for-kvm-and-xen-x86_64](https://openqa.suse.de/tests/4084635)
* [sle-15-SP2-JeOS-for-kvm-and-xen-x86_64](https://openqa.suse.de/tests/4084636)
> Consider QU updates when dealing with SCC

- tests/jeos/kiwi_templates.pm
- Verification run: [sle-15-SP1-JeOS-for-kvm-and-xen-x86_64](https://openqa.suse.de/t4086301)
> Jeos kiwi rpm

- tests/console/lvm.pm
In recent updates of lvm2 lvmetad does not seem to take into account the
devices/filter (Bug #1163526). A check has been added to ensure correct
functionality.
Two loop devices are attached to the same disk image, a device filter is created to counter this, and the Warnings from `pvs` are checked to see if if lvmetad reads the filter. If it does not, the test fails
- Related ticket: https://progress.opensuse.org/issues/63431
sle-15-SP1: http://angmar.suse.de/tests/1507
tumbleweed: http://angmar.suse.de/tests/1494 
Note: Test has PASSED on tumbleweed and FAILED on sle-15-SP1, where the lvmetad functionality is not the expected.
> Check if lvmetad uses devices filter

- data/valgrind/valgrind-test.sh
This PR fixes the valgrind test for s390x and aarch64
On s390x and aarch64 sgcheck is not available, so we perform the `sgcheck` test only on `x86_64`.
This commit adds a check for `x86_64` and skips the test if not on that platform.
- Needles: N/A
[SLE15-SP1 s390x](https://openqa.suse.de/t4091245) | [SLE15 s390x](https://openqa.suse.de/t4091246)
[SLE15-SP1 x86_64](https://openqa.suse.de/t4084249) | [SLE15 x86_64](https://openqa.suse.de/t4084250) | [SLE12-SP5 x86_64](https://openqa.suse.de/t4084251) | [SLE12-SP4 x86_64](https://openqa.suse.de/t4084252)
> Fix sgcheck for s390x and aarch64

- tests/publiccloud/boottime.pm
As this module start growing, we need to split the logical parts.
- Verification run: https://openqa.suse.de/tests/4098684
> publiccloud: Refactor boottime test module

- data/autoyast_opensuse/autoyast_multi_btrfs.xml
As per https://bugzilla.suse.com/show_bug.cgi?id=1167053#c3
[Verification run](https://openqa.opensuse.org/tests/1228043#).
> Fix autoyast_multi_btrfs for openSUSE

- tests/publiccloud/boottime.pm
With this additional check, we can specifically catch wicked timeout
issues.
- Related ticket: https://progress.opensuse.org/issues/56462
- Verification run: https://openqa.suse.de/t4100283
> publiccloud: Adding blame timing threshold for wicked.service

- tests/x11/vnc_two_passwords.pm
- Related ticket: https://progress.opensuse.org/issues/64568
- Verification run: http://openqa.slindomansilla-vm.qa.suse.de/tests/2400
> Fix race condition when stopping xev

- data/publiccloud/terraform/sap/azure.tfvars
- data/publiccloud/terraform/sap/ec2.tfvars
- data/publiccloud/terraform/sap/gce.tfvars
- lib/publiccloud/basetest.pm
- lib/publiccloud/provider.pm
Add support for ha-sap-terraform-deplov v4.1.0 for SLES4SAP PC images.
- Needles: N/A
- Verification run: [GCE](http://1b210.qa.suse.de/tests/6505), [EC2](http://1b210.qa.suse.de/tests/6496), [Azure](http://1b210.qa.suse.de/tests/6507)
> Improvements for Public Cloud tests on SLES4SAP

- tests/console/system_prepare.pm
- tests/migration/sle12_online_migration/post_migration.pm
Check SUSEConnect --status-text and add info to log
- Related ticket: https://progress.opensuse.org/issues/65211
https://openqa.nue.suse.com/tests/4096510#
https://openqa.nue.suse.com/tests/4096511#
> Check SUSEConnect --status-text and save output info to logfile

- data/publiccloud/terraform/sap/azure.tfvars
- data/publiccloud/terraform/sap/ec2.tfvars
- data/publiccloud/terraform/sap/gce.tfvars
Boolean type shouldn't be protected, otherwise they are seen as string variables.
- Needles: N/A
- Verification run: manually tested.
> Fix tfvars files on Public Cloud for SLES4SAP

- tests/appgeo/gdal.pm
* x86_64: https://openqa.opensuse.org/t1228820
* aarch64: https://openqa.opensuse.org/t1228819
> Check a tif image with gdalinfo

- tests/installation/installation_overview.pm
Reverts os-autoinst/os-autoinst-distri-opensuse#9982
> Revert "Fail when detecting wrong desktop - 2nd try"

- tests/sles4sap/patterns.pm
- Fail: https://openqa.suse.de/tests/4122534#step/patterns/85
> Increase zypper_call timeout for sles4sap patterns

- data/publiccloud/terraform/sap/gce.tfvars
DRBD OS image was hardcoded, this commit fix it.
- Needles: N/A
- Verification run: manually tested
> Fix SLES4SAP GCE Public Cloud tests

- tests/installation/releasenotes_origin.pm
As per [bsc#1145615](https://bugzilla.suse.com/show_bug.cgi?id=1145615).
[Verification run](https://openqa.suse.de/tests/4129584#).
> Remove soft-failure for bsc#1145615

- data/autoyast_sle15/autoyast_btrfs.xml
Fixes https://openqa.suse.de/tests/4102690 related with bug https://bugzilla.suse.com/show_bug.cgi?id=1160969
Unfortunately after many trys I was not able to determine which xml tag(s) I removed that make the difference. I tried among other options with obvious candidate, 'software' section, but no luck.
- Verification run: https://openqa.suse.de/tests/4106467
> Fix autoyast_btrfs profile

- tests/hpc/slurm_master.pm
- Verification run: http://fromm.arch.suse.de/tests/691
See: http://fromm.arch.suse.de/tests/691#external (HPC_single_tests | pdsh-slurm)
> HPC: Add new test for pdsh-slurm over ssh

- schedule/functional/extra_tests_textmode_phub.yaml
Ticket: https://progress.opensuse.org/issues/65480
Verification:
https://openqa.suse.de/tests/4139544
http://openqa.suse.de/t4139585
> Schedule arch specific bootloader for phub test

- tests/hpc/rasdaemon.pm
> HPC: Initial clean-up of rasdaemon test

- tests/virtualization/xen/patch_guests.pm
Hello,
to validate that guests with both old and new kernel are running I introduce this pull request.
- Related ticket: [poo#62540](https://progress.opensuse.org/issues/62540)
- Documentation: [qam virtualization for kernel testing](https://confluence.suse.com/display/maintenanceqa/qam+virtualisation+for+kernel+testing)
- Verification run: [SLE 15 SP1 KVM](http://pdostal-server.suse.cz/tests/8201) [SLE 12 SP4 XEN](http://pdostal-server.suse.cz/tests/8220)
> QAM Kernel Virtualization: Reboot all guests after patching

- tests/kernel_performance/full_run.pm
enhance performance full run list
- Related ticket: https://trello.com/c/fwuKG5cY/699-p1fix-openqa-full-run-list-issue
- Verification run: http://10.67.129.4/tests/12239
> enhance performance full run list

- tests/kernel/ib_tests.pm
When running the InfiniBand testsuite, it may be required to skip
certain tests or modify the configuration option. This is now possible
by adding variables to the master testsuite. The variables are
documented inside the source code, and the entire documentation was
updated to be fully up-to-date.
With these changes, all command line options offered by the testsuite is
now available to be modified on openQA testsuite level.
> Expose testsuite options to openQA

- tests/console/slp.pm
- Related ticket: [[qac][JeOS] remove obsolete softfails from slp.pm](https://progress.opensuse.org/issues/65981)
* [sle-15-SP2-JeOS-for-kvm-and-xen](https://openqa.suse.de/tests/4155276)
* [leap15.2](https://openqa.opensuse.org/t1242952)
* [opensuse-Tumbleweed-JeOS-for-kvm-and-xen](https://openqa.opensuse.org/tests/1242955#)
> Remove obsolete softfails for openslp and openslp-server

- tests/kernel/blktests.pm
> Storage: Collect generic logs for blktests runs

- tests/iscsi/iscsi_client.pm
https://bugzilla.suse.com/show_bug.cgi?id=1166707
https://bugzilla.suse.com/show_bug.cgi?id=1162514
- Needles: already updated
http://10.100.12.155/tests/15157/modules/iscsi_client/steps/51/edit
> Rename tag needle to expected start on demand

- lib/main_common.pm
- lib/selinuxtest.pm
- tests/security/selinux/fixfiles.pm
- tests/security/selinux/semanage_fcontext.pm
Add test for SELinux: semanage_fcontext + fixfiles
All passed.
https://progress.opensuse.org/issues/65669
https://progress.opensuse.org/issues/65672
- Needles: NA
- Verification run: https://openqa.nue.suse.com/tests/4143807#
> Add test for SELinux: semanage_fcontext + fixfiles

- schedule/functional/extra_tests_textmode_sdk.yaml
> Fix name for YAML extra_tests_textmode_sdk

- tests/console/enable_usb_repo.pm
After enabling USBinstall test for Full medium and adding SCC_REGISTER: none, the enable_usb_repo module fails as it could not handle scenario with more than one usb repo. This commit adds extra condition so that module recognizes Full medium tests and enables proper repository.
- Related ticket: https://progress.opensuse.org/issues/65322
Full: http://falafel.suse.cz/tests/675
Online: https://openqa.suse.de/tests/4161530
> Add condition for Full medium in enable_usb_repo

- schedule/functional/extra_tests_gnome.yaml
VR: http://phobos.suse.de/tests/3856948
Ticket: https://progress.opensuse.org/issues/45395
> Add Keyboard layout gdm test

- tests/console/textinfo.pm
- Related ticket: https://progress.opensuse.org/issues/65804
- Verification run: https://openqa.opensuse.org/t1244249
> Simplify textinfo handling and download it on demand for poo#65804

- tests/console/snapper_jeos_cli.pm
This commit simplifies determination of created snapshot ID.
Also it extracts common logic into helper function
> JeOS: refactor snapper test

- products/sle/main.pm
- schedule/functional/extra_tests_textmode.yaml
- tests/console/vsftpd.pm
Ticket: https://progress.opensuse.org/issues/13174
Verification: http://kazhua.suse.de/tests/24
> Fix vsftpd test and run it on a single machine

- lib/kdump_utils.pm
- Fail: https://openqa.suse.de/tests/4171787#step/kdump_and_crash/35
https://openqa.suse.de/tests/4173814
https://openqa.suse.de/tests/4173815
> Install mokutil needed on UEFI jeos

- lib/main_common.pm
- Related ticket: https://openqa.suse.de/tests/4172898
- Verification run: https://openqa.suse.de/tests/4176242
> Typo does not schedule add_update_test_repo test

- tests/console/vsftpd.pm
Verification: http://kazhua.suse.de/tests/26
> Fix vsftpd module

- lib/virt_autotest/kernel.pm
- tests/virtualization/xen/list_guests.pm
- tests/virtualization/xen/patch_and_reboot.pm
- tests/virtualization/xen/patch_guests.pm
Hello,
we're starting to run kernel maintenance updates on top of our virtualization infstrastructure.
In this PR I'm introducing a very simple function which @srlemke already uses for manual testing.
* Verification run: [SLE 15 SP1 KVM](http://pdostal-server.suse.cz/tests/8417)
> Check the kernel for QAM Virtualization purposes

- schedule/ai_ml.yaml
- schedule/systemd/suse_patches-systemd_testsuite.yaml
See [poo#66253](https://progress.opensuse.org/issues/66253).
[Verification run](https://openqa.suse.de/tests/4181778#).
> Wrap curly braces in remaning yaml schedule

- tests/update/patch_sle.pm
Add sdk repo for 11sp4 install
- Related ticket: https://progress.opensuse.org/issues/65618
- Needles: na
- Verification run:  https://openqa.suse.de/tests/4123143#
> Add sdk repo for 11sp4 install

- tests/qam-minimal/s390tools.pm
- Related ticket: https://progress.opensuse.org/issues/66227
> Update cputype check due new z13 s390x

- tests/console/vsftpd.pm
Ticket: https://progress.opensuse.org/issues/13174
> Upload vsftp logs on fail

- data/kernel/post_process
Correct parsing of the description provided by the blktests for each
executed test, so that it could be correctyl displayed on the openQA
webUI
> Storage: Update the test description in the WebUI

- tests/kernel/blktests.pm
This should help investigating any regressions
- Verification run: https://openqa.suse.de/tests/4194648
> Storage: Add record_info printing kernel info

- tests/publiccloud/download_repos.pm
- Related ticket: [poo#66412](https://progress.opensuse.org/issues/66412)
- Verification run: [SLE 15 SP1 on GCE](http://pdostal-server.suse.cz/tests/8449), [SLE 15 SP1 on EC2](http://pdostal-server.suse.cz/tests/8448)
> Validate the repo url before running wget

- tests/console/firewall_enabled.pm
see https://progress.opensuse.org/issues/65016
verification run:
https://openqa.suse.de/tests/4197115#next_previous
> Increase timeout for command 'firewall-cmd --state' on ppc64le

- lib/publiccloud/azure.pm
- lib/publiccloud/basetest.pm
Add ability to skip cleanup of created env
> publiccloud: Add ability to skip cleanup of created env

- tests/openqa/install/openqa_bootstrap_container.pm
Ticket: https://progress.opensuse.org/issues/66283
> openqa_bootstrap_container: upload container journal on fail

- schedule/functional/extra_tests_gnome.yaml
see https://progress.opensuse.org/issues/66289
verification run:
https://openqa.suse.de/tests/4202221
> Unschedule user_defined_snapshot on s390x

- lib/publiccloud/provider.pm
Add variable which controls how long VM created in CSP will not be cleaned up
> publiccloud: Add variable which controls how long VM created in CSP will not be cleaned up

- tests/console/system_prepare.pm
PR #10025 introduced the execution of `SUSEConnect --status-text` to add its output to the test log.
While this has not negatively impacted tests in most scenarios, we detected several instances when it fails in the SLES+HA Migration from 15-GM in s390x as shown [here](https://openqa.suse.de/tests/4181858#step/system_prepare/11).
Error message says the process is locked by `/usr/bin/zypper`, but in the test logs (psaxf.log), the offending process is already gone.
Additionally, the test is able to finish successfully without changes in the build or the test code as evidenced in: https://openqa.suse.de/tests/4181858#next_previous, so this seems to be impacted by the performance of the SUT.
This PR introduces a small wait time before attempting to run the `SUSEConnect --status-text` command …
> Run SUSEConnect --status-text several times (up to timeout) when System Management is locked by another process

- tests/kernel_performance/install_qatestset.pm
add product version for performance teseting
- Related ticket: https://trello.com/c/9wWh1H9S/711-p1ciopenqa-create-milestone-information-file
- Needles:N/A
- Verification run: http://10.67.129.4/tests/12716
> add performance testing product version cfg file

- tests/openqa/webui/test_results.pm
Ticket: https://progress.opensuse.org/issues/66111
Verification: https://openqa.opensuse.org/tests/1257157
> openqa_bootstrap: Select job details tab

- data/publiccloud/terraform/sap/ec2.tfvars
Add DRDB test on AWS to test SLES4SAP Public Cloud image.
- Needles: N/A
> Add DRBD test on AWS

- tests/hpc/slurm_db.pm
The mariadb service does not correspond to the mariadb daemon for sle
12-sp2 and 12-sp3. Instead, the service should be mysql.
- Related ticket: https://progress.opensuse.org/issues/66562
sle15 : http://angmar.suse.de/tests/2023
sle12-sp4: http://angmar.suse.de/tests/2018
sle12-sp3: http://angmar.suse.de/tests/2008
sle12-sp2: http://angmar.suse.de/tests/2028
sle15-sp2: http://angmar.suse.de/tests/2048
> HPC: Use mysql service for older mariadb versions

- tests/ha/ha_cluster_init.pm
When initializing a cluster with `ha-cluster-init` with Qdevice/Qnetd configuration, bootstrap script will prompt for the password of the Qnetd server. Current test code uses `wait_serial(qr/Password:\s*$/i)` to determine when the bootstrap script is prompting for the password before typing it, but this is not reliable when test is not running directly in the serial console.
Redirecting output of HA bootstrap script to `$serialdev`, is similarly unreliable as password prompt is printed by a `ssh` child process on the calling terminal.
This PR introduces an alternative to checking for the password prompt depending on the calling terminal (using `assert_screen`) similar to how `utils::exec_and_insert_password` handles password prompt.
- Needles: N/A
- Failing test: …
> Improve password prompt detection in ha-cluster-init

- tests/console/snapper_jeos_cli.pm
replace file existance check with file content checksum check
> snapper: replace file existance check with file content checksum check

- schedule/kernel/uefi_baremetal_basic.yaml
this should not be part of this schedule
> remove scheduling of ibtests-barriers

- tests/kernel/blktests.pm
- Related ticket: https://progress.opensuse.org/issues/65780
- Verification run: https://openqa.suse.de/tests/4224824
> Storage: As ZBD is now enable upload results

- lib/y2snapper_common.pm
- tests/x11/yast2_snapper.pm
- Fail:
https://openqa.suse.de/tests/4210709#step/yast2_snapper/52
https://openqa.suse.de/tests/4212720#step/yast2_snapper/38
- Verification run: http://10.100.12.155/tests/15521
> yast2_snapper: Wait after pressing show changes button

- lib/networkdbase.pm
- tests/networkd/networkd_init.pm
Ticket: https://bugzilla.suse.com/show_bug.cgi?id=1171481
Verification: http://kazhua.suse.de/tests/35#step/networkd_init/38
> Use .nspawn files insted of modified systemd-nspawn@.service file

- schedule/hpc/multi_machine_test.yaml
- schedule/hpc/single_machine_test.yaml
- Related ticket: https://progress.opensuse.org/issues/65753
- Verification run: https://openqa.suse.de/tests/4232156
> HPC: Add migration tests to yaml scheduler

- schedule/functional/extra_tests_textmode_containers.yaml
- tests/console/podman.pm
Ticket: https://progress.opensuse.org/issues/66025
Verification:
http://kazhua.suse.de/tests/40
http://kazhua.suse.de/tests/41
> Schedule podman test in extra_tests_textmode_containers

- tests/jeos/prepare_firstboot.pm
- Verification run: https://openqa.opensuse.org/t1266137
> Handle jeos-firstboot which moved from /usr/lib to /usr/sbin in Tumbleweed

- lib/data_integrity_utils.pm
> Fix typo in error message in verify_checksum subroutine

- tests/transactional/tdup.pm
> Make sure changes occur during transactional-update dup

- tests/qa_automation/patch_and_reboot.pm
- Related ticket: poo#18860 #10281
http://10.100.12.155/tests/15669
http://10.100.12.155/tests/15670
http://10.100.12.155/tests/15671
> Workaround virtio_console login issue on 12-SP1

- tests/wicked/before_test.pm
Disable SSL verification in git 
VR: http://dante.arch.suse.de/tests/535
> Disable SSL verification in git

- lib/networkdbase.pm
Ticket: https://progress.opensuse.org/issues/66916
Verification: https://openqa.opensuse.org/t1271270
> Ensure that nspawn conf dir exists

- data/containers/docker-compose.yml
- lib/containers/common.pm
- lib/main_common.pm
- lib/registration.pm
- tests/console/docker.pm
- tests/console/docker_compose.pm
- tests/console/docker_image.pm
- tests/console/docker_runc.pm
- tests/console/zypper_docker.pm
* New folder `lib/containers/` is created to separate future different test modules.
* The library `lib/containers/common.pm` was created and related code moved in.
* Function `clean_docker_host` was created to ensure every test ends with clean host.
* Sample `docker-compose.yml` was created and executed in `docker_compose.pm` module.
- Related ticket: [poo#66952](https://progress.opensuse.org/issues/66952) [poo#66955](https://progress.opensuse.org/issues/66955)
- Verification run: [SLE 12 SP4](http://pdostal-server.suse.cz/tests/8556), [SLE 15 SP1](http://pdostal-server.suse.cz/tests/8555), [Tumbleweed](http://pdostal-server.suse.cz/tests/8554)
> Refactor docker* and extend docker-compose.yml

- lib/susedistribution.pm
Fixup previously merged commit
VR https://openqa.opensuse.org/tests/1271685 (pending)
> Fix tag name for PolicyKit-authenticate

- schedule/functional/extra_tests_textmode_containers.yaml
- tests/console/podman_image.pm
Ticket: https://progress.opensuse.org/issues/66025
Verification: http://kazhua.suse.de/tests/45
> Add podman_image to containers testsuite

- lib/apparmortest.pm
- lib/main_common.pm
- tests/security/yast2_apparmor/settings_disable_enable_apparmor.pm
- tests/security/yast2_apparmor/settings_toggle_profile_mode.pm
Implement test for yast2 apparmor - settings
All passed
https://progress.opensuse.org/issues/66901
https://progress.opensuse.org/issues/67021
- Needles: merged
- Verification run: https://openqa.nue.suse.com/tests/4256030
https://openqa.nue.suse.com/tests/4258926# (latest)
> Implement test for yast2 apparmor - settings

- lib/opensusebasetest.pm
- Fail: https://openqa.suse.de/tests/4257852#step/gedit/5
> gedit: Use very slow typing in enter_test_text

- data/autoyast_sle15/autoyast_sles4sap.xml.ep
- lib/sles4sap.pm
- schedule/sles4sap/autoyast_sles4sap_hana.yaml
- tests/sles4sap/hana_cluster.pm
- tests/sles4sap/hana_install.pm
- tests/sles4sap/hana_test.pm
- tests/sles4sap/migrate_sles_to_sles4sap.pm
- tests/sles4sap/netweaver_install.pm
- tests/sles4sap/netweaver_test_instance.pm
- tests/sles4sap/wizard_hana_install.pm
Add a HANA installation test using AutoYaST.
- Needles: N/A
- Verification run: [autoyast_sles4sap_hana](http://1b210.qa.suse.de/tests/6759)
- Regression tests: [sles4sap_scc_textmode_hana_cli](http://1b210.qa.suse.de/tests/6755), [sles4sap_scc_textmode_hana_wizard](http://1b210.qa.suse.de/tests/6757), [sles4sap_scc_gnome_hana_wizard](http://1b210.qa.suse.de/tests/6758), [sles4sap_scc_textmode_netweaver](http://1b210.qa.suse.de/tests/6756), [sles4sap_hana_node01](http://1b210.qa.suse.de/tests/6774), [sles4sap_hana_node02](http://1b210.qa.suse.de/tests/6775)
> Add HANA AutoYaST test

- tests/x11/window_system.pm
- Fail: https://openqa.suse.de/tests/4260761
https://openqa.suse.de/tests/4260841 15-SP1
https://openqa.suse.de/tests/4260842 15-SP2 virtio
https://openqa.suse.de/tests/4260843 15-SP2
> Do not exit serial console after it was activated

- tests/locale/keymap_or_locale.pm
- Related ticket:  #10288 https://openqa.suse.de/tests/4264383
- Verification run: https://openqa.suse.de/tests/4264983
> keymap_or_locale: Switch to root console

- tests/locale/keymap_or_locale.pm
Reverts os-autoinst/os-autoinst-distri-opensuse#10340
> Revert "keymap_or_locale: Switch to root console"

- tests/locale/keymap_or_locale.pm
- Related ticket: #10340 
https://openqa.suse.de/tests/4265797 s390x
https://openqa.suse.de/tests/4265798 x86_64
> Switch to user console, test before can use virtio console

- tests/autoyast/installation.pm
On zkvm, system shuts down instead of reboot on SLE15-SP2. The commit adds the steps to reconnect to the machine, that is shut off after installation. Please, see bsc#1167210. 
- Related ticket: https://progress.opensuse.org/issues/67048
- Needles: N/A
- Verification run: https://openqa.nue.suse.com/tests/4264315#
> Workaround to reconnect for autoyast installation on zkvm

- tests/console/ntp_client.pm
- Related ticket: https://progress.opensuse.org/issues/67099
https://openqa.suse.de/tests/4266044 15-SP1
> Synchronize chrony before calling sources information

- tests/console/consoletest_setup.pm
- tests/ha/pacemaker_cts_cluster_exerciser.pm
#10288 
https://openqa.suse.de/tests/4266245#step/hawk_gui/29
https://openqa.suse.de/tests/4266278#step/pacemaker_cts_cluster_exerciser/6
https://openqa.suse.de/tests/4268853
> Fix issue with ssh key on HA

- schedule/containers/extra_tests_textmode_containers.yaml
Ticket: https://progress.opensuse.org/issues/66031
> Schedule docker_compose in extra_tests_containers

- schedule/kernel/install_ltp_uefi_baremetal.yaml
to match profile for intel
- https://openqa.suse.de/tests/4269921
> Add shutdown_ltp to install_ltp_uefi_baremetal

- lib/main_common.pm
- products/opensuse/main.pm
- schedule/qam/12-SP1/mau-extratests.yaml
- schedule/qam/12-SP1/mau-filesystem.yaml
- schedule/qam/12-SP1/qam-allpatterns.yaml
- schedule/qam/12-SP1/qam-gnome.yaml
- schedule/qam/12-SP1/qam-minimal-base.yaml
- schedule/qam/12-SP1/qam-minimal.yaml
- schedule/qam/12-SP1/qam-regression-installation.yaml
- schedule/qam/12-SP1/qam-textmode-autoyast.yaml
- schedule/yast/lvm/lvm_sle.yaml
- tests/qa_automation/patch_and_reboot.pm
https://progress.opensuse.org/issues/67120
https://progress.opensuse.org/issues/67174
https://openqa.suse.de/tests/4269899 15-SP2 ppc64le
https://openqa.suse.de/tests/4272659 12-SP1 x86_64
https://openqa.opensuse.org/tests/1276969 TW ppc64
https://openqa.opensuse.org/tests/1276970 TW ppc64
https://openqa.opensuse.org/tests/1276481 TW ppc64le
https://openqa.opensuse.org/tests/1276480 TW aarch64
https://openqa.opensuse.org/tests/1276559 15.2 textmode
> Fix login failure on ppc64le virtio console

- lib/main_common.pm
- products/opensuse/main.pm
```
openqa-clone-custom-git-refspec https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/10306 https://openqa.opensuse.org/tests/1271885 SCHEDULE=tests/installation/bootloader_uefi,tests/installation/finish_desktop
```
opensuse-Tumbleweed-GNOME-Live-aarch64-Build20200517-gnome-live@USBboot_aarch64 -> https://openqa.opensuse.org/t1272274
> main_common: Simplify some conditions; Add more unregister needles

- schedule/containers/extra_tests_textmode_containers.yaml
Ticket: https://progress.opensuse.org/issues/66031
> Schedule docker_base_images via YAML on opensuse

- data/autoyast_sle15/autoyast_containers_aarch64.xml
- schedule/containers/create_hdd_autoyast.yaml
dd autoyast profiles for aarch64
VR: https://openqa.suse.de/tests/4286204
https://openqa.suse.de/tests/4283746
> containers: add autoyast profiles for aarch64

- schedule/yast/allmodules+allpatterns+registration/allmodules+allpatterns+registration@pvm.yaml
- schedule/yast/allmodules+allpatterns/allmodules+allpatterns_pvm.yaml
- tools/detect_unused_modules
See [poo#66730](https://progress.opensuse.org/issues/66730).
[MR to ENABLE in the JobGroup](https://gitlab.suse.de/qsf-y/qa-sle-functional-y/-/merge_requests/201).
[Verification run](https://openqa.suse.de/tests/4288144).
> Add schedule for allmodules+allpatterns+registration on powerVM

- data/autoyast_sle15/autoyast_containers_ppc64le.xml
- Related ticket: https://progress.opensuse.org/issues/66583
- Verification run: https://openqa.suse.de/tests/4289021
> Containers: add autoyast profile for ppc

- data/generalhw_scripts/power_on_off_tuya.sh
- data/generalhw_scripts/tuya_sync.js
since IFTTT support is not available anymore for this specific hardware (since 2020-05-26).
Tested with my RPi3 worker https://openqa.opensuse.org/tests/1280157
> Add script to support Tuya/Konyks smartstrip/smartplug

- data/generalhw_scripts/flash_sd.sh
- data/generalhw_scripts/flash_usb_otg.sh
> Add script to flash SD cards using sd-mux-ctrl or usbsdmux tools + fixup for cleanup of flasher

- tests/ha/ha_cluster_init.pm
Sometimes, double fencing [occurred](https://openqa.suse.de/tests/4288922) in x86_64 scenario.
It is recommended setting `SBD_DELAY_START` to yes for such a situation.
Explanation from the man pages:
Whether to delay after starting sbd on boot for "msgwait" seconds.
This may be necessary if your cluster nodes reboot so fast that the
other nodes are still waiting in the fence acknowledgment phase.
This is an occasional issue with virtual machines.
- Needles: N/A
- Verification run: [Node1](http://1a102.qa.suse.de/tests/4375), [Node2](http://1a102.qa.suse.de/tests/4376) In progress
[Screen with the replacement](http://1a102.qa.suse.de/tests/4375#step/ha_cluster_init/15)
> Enable sbd delay start in ha tests

- tests/security/ima/ima_measurement.pm
Fix ima measurement logic & upload file before failure
Failed case can be tracked by bug:
https://bugzilla.suse.com/show_bug.cgi?id=1172223
- Related ticket: https://progress.opensuse.org/issues/67243
- Needles: NA
- Verification run: http://openqa.suse.de/tests/4291033#
> Fix ima measurement logic & upload file before failure

- tests/console/journalctl.pm
Reboot is not working seamlessly on public cloud. This commit removes the `--boot=1` tests on public cloud and fixes the an issue with aarch64 and JeOS images
- Related tickets: https://progress.opensuse.org/issues/67240 https://progress.opensuse.org/issues/67327
- Needles: https://github.com/os-autoinst/os-autoinst-needles-opensuse/pull/668
- Verification run: [SLE15-SP1 publiccloud](http://phoenix-openqa.qam.suse.de/tests/1450#step/journalctl/1) (failing on other tests, no sideffects from journalctl) | [SLE15-SP1](http://phoenix-openqa.qam.suse.de/t1442) | [SLE15](http://phoenix-openqa.qam.suse.de/t1443) | [SLE12-SP5](http://phoenix-openqa.qam.suse.de/t1444) | [SLE12-SP4](http://phoenix-openqa.qam.suse.de/t1445) | [SLE12-SP3](http://phoenix-openqa.qam.suse.de/t1446) | …
> Fix journalctl for publiccloud and aarch64-jeos

- data/generalhw_scripts/flash_sd.sh
> Add flags to dd command to flash sd card to improve speed and be sync

- tests/console/journalctl.pm
This is a refactoring commit. Test files have been moved to `/var/tmp` and will be deleted after the test runs.
- Related PR: https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/10390#issuecomment-635800030
- Needles: -
- Verification runs: [SLE15-SP1](https://openqa.suse.de/t4293917) | [SLE15](https://openqa.suse.de/t4293918) | [SLE12-SP5](https://openqa.suse.de/t4293919) | [SLE12-SP4](https://openqa.suse.de/t4293920) | [SLE12-SP3](https://openqa.suse.de/t4293921) | [SLE12-SP2](https://openqa.suse.de/t4293922) | [Tumbleweed](https://openqa.opensuse.org/t1282955) | [Leap 15.2](https://openqa.opensuse.org/t1282956)
> Improve consistency of journalctl test

- lib/x11test.pm
- Related ticket: https://progress.opensuse.org/issues/65169
http://10.100.12.155/tests/16057
> Fix different encryption method

- lib/main_common.pm
- tests/jeos/glibc_locale.pm
- Verification run: [tw](http://kepler.suse.cz/tests/296#)
- Motivation: [Missing package in test case](https://bugzilla.opensuse.org/show_bug.cgi?id=1172291#c1)
> Install glibc translation file for TW

- schedule/containers/extra_tests_textmode_containers.yaml
See #10428
Verification: https://openqa.opensuse.org/t1284654
> Schedule docker_compose only on opensuse

- data/autoyast_sle15/autoyast_containers_s390x.xml
- schedule/containers/create_hdd_autoyast.yaml
- Related ticket: https://progress.opensuse.org/issues/66583
- Verification run: https://openqa.suse.de/tests/4294111
> Containers: add autoyast profile for s390

- tests/console/docker_image.pm
- variables.md
Hello,
this is my attempt to solve the problem described in the ticket below without reregistration of the host system.
- Related ticket: [bsc#1170489#c22](https://bugzilla.suse.com/show_bug.cgi?id=1170489#c22)
- Verification run: [SLE 15 SP1 x86_64](http://pdostal-server.suse.cz/tests/8723)
> Use special credentials for docker_image test

- products/sle/main.pm
- tests/smt/smt_client1.pm
- tests/smt/smt_server.pm
- tests/smt/smt_server_install.pm
- Related ticket: https://progress.opensuse.org/issues/51158
- Needles: https://gitlab.suse.de/openqa/os-autoinst-needles-sles/-/merge_requests/1385
- Verification run: http://octarine.suse.cz/tests/overview?distri=sle&version=12-SP5&build=50&groupid=3
```
defaults:
x86_64:
machine: 64bit
priority: 50
products:
sle-12-SP5-Server-DVD-Updates-x86_64:
distri: sle
flavor: Server-DVD-Updates
version: 12-SP5
scenarios:
x86_64:
sle-12-SP5-Server-DVD-Updates-x86_64:
- qam-smt-client1
- qam-smt-server
- mru-install-desktop-big-disk
- qam-smt-server-install
- qam-install-no-registration
```
qam-smt-client1
```
BOOT_HDD_IMAGE=1
DESKTOP=gnome
HDD_1=SLES-%VERSION%-%ARCH%-qam-install-no-registration-Build%BUILD%.qcow2
HOSTNAME=client1
NICTYPE=tap
PARALLEL_WITH=qam-smt-server
QAM_SMT=1 …
```
> Add multimachine smt test

- tests/console/git.pm
- tests/security/selinux/audit2allow.pm
- tests/security/selinux/chcat.pm
- tests/security/selinux/chcon.pm
- tests/security/selinux/enforcing_mode_setup.pm
- tests/security/selinux/fixfiles.pm
- tests/security/selinux/print_se_context.pm
- tests/security/selinux/restorecon.pm
- tests/security/selinux/selinux_setup.pm
- tests/security/selinux/selinux_smoke.pm
- tests/security/selinux/semanage_boolean.pm
- tests/security/selinux/semanage_fcontext.pm
- tests/security/selinux/semodule.pm
- tests/security/selinux/sestatus.pm
- tests/security/selinux/setsebool.pm
Change the console connection from serial to vnc for some tests
The reason why post this commit is that, we hit some tests failed on s390x platform when re-connecting the active serial console.
https://openqa.nue.suse.com/tests/4285536#step/git/2
https://openqa.nue.suse.com/tests/4285602#step/sestatus/59
- Related ticket:67624
- Needles: N/A
- Verification run: https://openqa.nue.suse.com/tests/4305744
https://openqa.nue.suse.com/tests/4305656
> Change console connection from serial to vnc

- schedule/yast/encryption/cryptlvm+cancel_existing_pvm.yaml
The commit adds the appropriate yaml shedule for the test suite on PowerVM
- **Merge Request with Job Group Settings:** https://gitlab.suse.de/qsf-y/qa-sle-functional-y/-/merge_requests/204
- Related ticket: https://progress.opensuse.org/issues/67405
- Verification run: https://openqa.suse.de/tests/4312210
> Add schedule for cryptlvm+cancel_existing_pvm

- lib/services/registered_addons.pm
- tests/console/system_prepare.pm
Reverts os-autoinst/os-autoinst-distri-opensuse#10347
> Revert "Check if SUSEConnect command includes all expected addons info"

- lib/bootloader_pvm.pm
check pvm lpar state for shutdown and activation
see https://progress.opensuse.org/issues/65663
verification:
https://openqa.suse.de/tests/4312244
> Add check for pvm lpar's shutdown and activation state

- tests/virtualization/xen/hotplugging.pm
1.lsblk checking after attaching raw disk is skipped for VIRT_AUTOTEST KVM test suites due to uncertainty. In fact, the test already checks by using virsh domblklist beforehands
2.bsc#1167828 has workaround "sh root\@$guest modprobe acpiphp"
3.bsc#1169065 will not be fixed and corresponding test will be skipped.
- Related ticket: Mainly virtualization KVM test suites that are affected by "lsblk checking"
- Needles: n/a
- [sles11sp4 guest on sles15sp2 host KVM](http://10.67.133.40/tests/214)
- [sles15sp2 guest on sles11sp4 host KVM](http://10.67.133.40/tests/208)
> Remove some softfailed records to push up pass rate

- schedule/install/offline_spvm_install.yaml
- schedule/migration/offline_spvm_Upgrade.yaml
Add yaml schedule files to schedule spvm cases modules
> Add yaml schedule files to schedule spvm cases modules

- lib/services/cups.pm
- tests/sysauth/sssd.pm
- Needles: N/A
- Verification run: N/A (obvious enough)
> Remove unused disable_and_stop_service

- tests/console/container_base_images.pm
Verification run: http://10.160.67.86/tests/695
> Fix and clean up container_base_images

- tests/wicked/before_test.pm
fix IPv6 tests for Leap/TW
VR: http://autobot.qa.suse.de/tests/750
> wicked: fix IPv6 tests for Leap/TW

- tests/console/check_package_version.pm
Added jira feature version check
- Related ticket: https://progress.opensuse.org/issues/67711
- Verification run: https://openqa.nue.suse.com/tests/4343507#
> Added jira feature version check

- data/autoyast_sle12/autoyast_wicked_x86_64.xml.ep
- http://dante.arch.suse.de/tests/1902 (SLE_12_SP3)
- http://dante.arch.suse.de/tests/1903 (SLE_12_SP2)
> wicked: Add autoyast template for SLE_12

- tests/wicked/before_test.pm
This PR will fix wicked testsuite for SLE 12 (SP1)
- Verification run: http://dante.arch.suse.de/tests/2187 (SLE 12)
> wicked: Fix wicked for sle 12

- tests/autoyast/installation.pm
Fix AutoYaST invalid default target by taking into account processed warnings, so we will match needle again for next warning but if it is already processed we will skip.
- Related ticket: https://progress.opensuse.org/issues/67729
- Verification run: [30 runs autoyast_invalid_default_target](https://openqa.suse.de/tests/overview?build=209.2_jrivera_poo67729&distri=sle&version=15-SP2)
> Fix autoyast handling of warnings with test_data

- schedule/qam/common/qam-scc.yaml
- tests/console/suseconnect.pm
Merge https://openqa.suse.de/tests/4357383 and https://openqa.suse.de/tests/4357387
http://10.100.12.155/tests/16105 12-SP3
http://10.100.12.155/tests/16109 12-SP4
http://10.100.12.155/tests/16108 12-SP5
http://10.100.12.155/tests/16106 15
http://10.100.12.155/tests/16107 15-SP1
> yaml: Merge scc tests into one

- schedule/functional/allmodules+allpatterns-gnome.yaml
see https://progress.opensuse.org/issues/66541
verfications:
https://openqa.suse.de/tests/4358155
https://openqa.suse.de/tests/4358156
https://openqa.suse.de/tests/4358157
https://openqa.suse.de/tests/4358158
> Add allmodules+allpatterns-gnome test suite to SLE15-SP2

- tests/console/suseconnect_scc.pm
see https://progress.opensuse.org/issues/27853
verifications:
https://openqa.suse.de/tests/4361788#step/suseconnect_scc/12
https://openqa.suse.de/tests/4361789#step/suseconnect_scc/12
https://openqa.suse.de/tests/4361790#step/suseconnect_scc/12
> Extend SUSEConnect test with minimal UI check

- lib/networkdbase.pm
- tests/networkd/networkd_dhcp.pm
Ticket: https://bugzilla.opensuse.org/show_bug.cgi?id=1141597
Verification: http://kazhua.qa.suse.de/tests/49#
> Don't emit timezone for networkd dhcp server

- tests/networkd/networkd_dhcp.pm
Ticket: https://bugzilla.opensuse.org/show_bug.cgi?id=1141597
Verification: http://kazhua.qa.suse.de/tests/50
> Add missing softfail description

- lib/apparmortest.pm
- Verification run: https://openqa.suse.de/tests/4369403
> apache2_changehat: Decrease timeout for tabing to selected field

- data/qam/dracut/15-SP2_custom_lvm.xml.ep
- data/qam/dracut/15-SP2_custom_usr.xml.ep
- Fail: https://openqa.suse.de/tests/4370923#step/prepare_profile/3
- Verification run: not really needed
> Create link for 15-SP2 profiles

- tests/wsl/firstrun.pm
[timeout in registration step](https://openqa.suse.de/tests/4372037#step/firstrun/16)
> Wait longer while interacting with SCC servers

- tests/wsl/firstrun.pm
> Give more time to refresh repos in firstboot

- schedule/yast/autoyast_bcache.yaml
- schedule/yast/autoyast_btrfs.yaml
- schedule/yast/autoyast_nfs_share.yaml
- schedule/yast/autoyast_y2_firstboot.yaml
- schedule/yast/encryption/crypt_no_lvm.yaml
- schedule/yast/encryption/crypt_no_lvm_pvm.yaml
- schedule/yast/minimal+base/minimal+base@yast-s390x-disk-activation.yaml
- schedule/yast/minimal+base/minimal+base@yast-s390x.yaml
- schedule/yast/minimal+base/minimal+base@yast-svirt-hyperv.yaml
- schedule/yast/minimal+base/minimal+base@yast-xen-pv.yaml
- schedule/yast/minimal+base/minimal+base@yast.yaml
Move some settings from openQA test suites to yaml schedule file.
- Related ticket: https://progress.opensuse.org/issues/66964
- MR in YaST job group: https://gitlab.suse.de/qsf-y/qa-sle-functional-y/-/merge_requests/208/
> Fix settings for test suites in YaST group

- tests/hpc/slurm_db.pm
> HPC: Upload logs for bsc#1173150

- lib/hpc/configs.pm
> HPC: Increase log level for slurmdbd

- lib/transactional.pm
- lib/utils.pm
- tests/transactional/health_check.pm
- tests/transactional/transactional_update.pm
Reverts os-autoinst/os-autoinst-distri-opensuse#10550
> Revert "Handle GRUB twice for zkvm"

- schedule/yast/minimal+base/minimal+base@yast-s390x-disk-activation.yaml
- schedule/yast/minimal+base/minimal+base@yast-s390x.yaml
- schedule/yast/minimal+base/minimal+base@yast-svirt-hyperv.yaml
- schedule/yast/minimal+base/minimal+base@yast-xen-pv.yaml
- schedule/yast/minimal+base/minimal+base@yast.yaml
Corrects wrong settings in this test suite for yast job group.
- Related ticket: https://progress.opensuse.org/issues/66964
> Fix settings minimal+base_yast

- schedule/ha/qam/15-SP2/qam-client.yaml
- schedule/ha/qam/15-SP2/qam-cluster_2nodes_01.yaml
- schedule/ha/qam/15-SP2/qam-cluster_2nodes_02.yaml
This PR basically adds files for HA QAM in 15-SP2
- Needles: N/A
> Add HA QAM files for 15-SP2

- tests/ha/yast_cluster_init.pm
Current version of `tests/ha/yast_cluster_init` needs to address some changes made to the yast2 cluster module, namely there is the possibility of a notice at startup which prompts to install dependencies, and the **Cluster - Service** screen feature different shortcuts/hotkeys to enable startup of the cluster.
Additionally, the **Cluster - Corosync Qdevice** screen is not present in SLES+HA versions older than 15-GM, so code was added to backport the module to older OS versions.
- Needles: https://gitlab.suse.de/openqa/os-autoinst-needles-sles/-/merge_requests/1391
- Verification run: [node 1](http://mango.suse.de/tests/2825), [node 2](http://mango.suse.de/tests/2826), [support server](http://mango.suse.de/tests/2824)
- Verification runs (regression):
1. 12-SP2: …
> Add Support for yast2-cluster in SLES+HA 12 & 15-SP2

- lib/hpcbase.pm
> HPC: Upload specific slurmdbd logs

- tests/hpc/slurm_db.pm
- tests/hpc/slurm_master.pm
> HPC: Register cluster before starting slurm ctl

- lib/containers/utils.pm
Podman test fails when scheduled for SLES15-SP1 s390x
- Related ticket: https://progress.opensuse.org/issues/68447
- Needles: N/A
SLES 15sp2 [x86_64](https://openqa.suse.de/tests/4399144)
SLES 15sp1[ x86_64](http://10.161.229.247/tests/486) [s390x](https://openqa.suse.de/tests/4393431)
Tumbleweed : [x86_64](https://openqa.opensuse.org/tests/1319424)
> Fix fail in podman test in s390x

- tests/virtualization/xen/smoketest.pm
This commit removes some soft_failures in virtualization smoke tests that are known
- Related ticket: https://progress.opensuse.org/issues/68401
- Needles: -
- Verification run: http://phoenix-openqa.qam.suse.de/tests/1685
> Remove soft_failures from known issues in virtualization tests

- lib/containers/utils.pm
Docker test fails on public cloud
- Related ticket: https://progress.opensuse.org/issues/68431
- Needles: N/A
SLES 15sp1 [GCE](http://10.161.229.247/tests/503) [Azure](http://10.161.229.247/tests/504) [EC2](http://10.161.229.247/tests/501) [x86_64](https://openqa.suse.de/tests/4402565)
> Fix docker fail on public cloud

- schedule/yast/encryption/cryptlvm+activate_existing+force_recompute_pvm.yaml
See [poo#68257](https://progress.opensuse.org/issues/68257).
[Job group changes](https://gitlab.suse.de/qsf-y/qa-sle-functional-y/-/merge_requests/221).
[Verification run](https://openqa.suse.de/tests/4402528).
> Add schedule for cryptlvm force_recompute on powerVM

- tests/ai_ml/armnn.pm
- Verification run: https://openqa.opensuse.org/t1307292
> Enable more TfLite tests

- schedule/systemd/suse_patches-systemd_testsuite.yaml
- tests/systemd_testsuite/test_36_numapolicy.pm
- tests/systemd_testsuite/test_37_runtimedirectorypreserve.pm
- tests/systemd_testsuite/test_39_execreload.pm
- tests/systemd_testsuite/test_40_exec_command_ex.pm
- tests/systemd_testsuite/test_41_oneshot_restart.pm
- tests/systemd_testsuite/test_42_execstoppost.pm
- tests/systemd_testsuite/test_44_log_namespace.pm
- tests/systemd_testsuite/test_47_issue_14566.pm
Currently only tested for Tumbleweed x86_64
+ Verification run: http://emerson.suse.de/tests/2253
+ Testsuite package submitted: https://build.opensuse.org/request/show/816500
> add more systemd tests

- tests/virt_autotest/virsh_external_snapshot.pm
- tests/virt_autotest/virsh_internal_snapshot.pm
- tests/virtualization/xen/patch_guests.pm
- tests/virtualization/xen/smoketest.pm
- tests/virtualization/xen/stresstest.pm
- Verification run: [SLE 15 SP1 KVM](http://pdostal-server.suse.cz/tests/9183)
> Fix virt snapshot tests and wait for guest after rebooting after patching

- schedule/yast/encryption/cryptlvm+activate_existing+import_users_pvm.yaml
- tests/console/validate_user_login_textmode.pm
- Related ticket: https://progress.opensuse.org/issues/68386
- Verification run: https://openqa.suse.de/tests/4405889
> Add user login validation in PowerVM

- schedule/install/offline_spvm_install.yaml
Add one new module for migration installation step
> Add one new module for migration installation step

- tests/update/zypper_clear_repos.pm
As requested by lnussel this is a preparation for https repos
- Related ticket: https://progress.opensuse.org/issues/66259
- Verification run: https://openqa.opensuse.org/tests/1313827
> Also remove https repositories

- .travis.yml
- lib/autoyast.pm
- lib/main_common.pm
- lib/susedistribution.pm
- lib/version_utils.pm
- lib/y2_module_guitest.pm
- tests/console/ipsec_tools_h2h.pm
- tests/kernel/virtio_console_long_output.pm
- tests/support_server/flaky_mp_iscsi.pm
- tests/virt_autotest/virt_utils.pm
Sync with recent change in os-autoinst introduced by
2b303bc
> Update tidy to fix compatibility with os-autoinst

- tests/update/zypper_clear_repos.pm
Reverts os-autoinst/os-autoinst-distri-opensuse#10578
See https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/10578#issuecomment-654233573
> Revert "Also remove https repositories"

- tests/sles4sap/hana_install.pm
For the HANA cli installation in qemu, we expect the job to have correctly configured settings so a second disk with enough space for HANA is configured in the VM. When backend is not qemu, the test will rely on whatever disks are already configured in the system, be it bare metal or a ppc64le LPAR; in these cases, the tests selects `/dev/sdb` by default, even if this device does not have enough space for HANA or if it does not exist.
This commit introduces changes to make the `sles4sap/hana_install` test module select a device for HANA when the backend is not qemu. This is done by probing for available block devices, and verifying if these have enough space for HANA as calculated from the system RAM. If no disks are found with enough space for HANA, test will fail.
Since SLES4SAP is …
> Improve HANA cli installation when BACKEND is not qemu

- schedule/containers/extra_tests_textmode_containers.yaml
- schedule/containers/sle_image_on_sle_host.yaml
- schedule/functional/extra_tests_gnome.yaml
- schedule/functional/extra_tests_gnome_sdk.yaml
- schedule/functional/extra_tests_textmode.yaml
- schedule/functional/extra_tests_textmode_mod_desktop.yaml
- schedule/functional/extra_tests_textmode_phub.yaml
- schedule/functional/extra_tests_textmode_sdk.yaml
- schedule/yast/transactional_server/transactional_server_helper_apps.yaml
- schedule/yast/transactional_server/transactional_server_snapper.yaml
- schedule/yast/yast2_gui/yast2_gui_sle.yaml
- schedule/yast/yast2_ncurses/yast2_ncurses_gnome.yaml
- tests/boot/uefi_bootmenu.pm
- tests/installation/bootloader_start.pm
Ticket: https://progress.opensuse.org/issues/66114
https://openqa.suse.de/t4384296
https://openqa.suse.de/t4384297
https://openqa.suse.de/t4384298
https://openqa.suse.de/t4384300
https://openqa.suse.de/t4384301
https://openqa.suse.de/t4384335
> bootloader_start: Show which module's code is used

- lib/susedistribution.pm
- products/sle/main.pm
- tests/virt_autotest/login_console.pm
1. Mitigations: add MITIGATION_INSTALL to main.pm
2. update expertpartitioner key with alt-x if got Online Flavor
3. Add boot with XEN for xen_mitigation test
- Verification run: http://10.67.134.217/tests/10338
> Add installation case for mitigation test

- tests/console/journalctl.pm
Add some more logs in case journalctl tests fail.
- Related ticket: https://progress.opensuse.org/issues/68654
- Verification run
1. [SLE 15-SP2 x86_64](https://openqa.suse.de/t4424515) | [SLE15-SP2 s390x](https://openqa.suse.de/tests/4424510)
2. [SLE 15-SP1 x86_64](https://openqa.suse.de/t4424505) | [SLE15-SP1 s390x](https://openqa.suse.de/tests/4424511)
3. [SLE 15 x86_64](https://openqa.suse.de/t4424506) | [SLE15 s390x](https://openqa.suse.de/tests/4424512)
4. [SLE12-SP5 x86_64](https://openqa.suse.de/t4424507)
5. [SLE12-SP4 x86_64](https://openqa.suse.de/t4424508)
6. [SLE12-SP3 x86_64](https://openqa.suse.de/t4424509)
7. [SLE12-SP2 x86_64](https://openqa.suse.de/t4424516)
8. [Tumbleweed](https://openqa.opensuse.org/t1326448)
9. [Leap](https://openqa.opensuse.org/t1326449)
> Improve output on journalctl fails

- tests/console/dracut_enhanced.pm
Source repositories are now added manually (not needed for <sle15sp1)
Fix for poo#68425
http://10.161.229.209/tests/48
> Add source repositories for test

- tests/kernel/boot_ltp.pm
Passing runfile contents through `script_output()` sometimes results in pieces of the file missing. Upload the active runfiles as assets instead. As a bonus, the runfile will be downloadable from the job assets tab in the web UI.
- Needles: N/A
- SLE-12SP5@x86_64: https://openqa.suse.de/tests/4414150
- SLE-12SP5@s390x: https://openqa.suse.de/tests/4414153
> Upload active runfiles in boot_ltp

- lib/Mitigation.pm
- tests/cpu_bugs/xen_mitigations.pm
Generate junit log to recode test cases detail info for xen hypervisor mitigation test
- Needles: N/A
- Verification run: http://10.67.134.217/tests/10249
> New functions to generate junit log for xen mitigation test

- schedule/qam/15-SP1/qam-create_hdd_sle_sap_gnome.yml
The patch_and_reboot module is loaded two times, this PR removes one.
- Needles: N/A
> Fix a scheduling issue in QAM file for SAP 15SP1

- tests/console/journalctl.pm
Adds softfailure for [bsc#1173856](https://bugzilla.suse.com/show_bug.cgi?id=1173856) instead of test failing.
- Related ticket: https://progress.opensuse.org/issues/68654
- Needles: -
- - SLE15 SP2 [s390x](https://openqa.suse.de/t4431926) | [x86_64](https://openqa.suse.de/t4431919)
- - SLE15 SP1 [s390x](https://openqa.suse.de/t4431927) | [x86_64](https://openqa.suse.de/t4431920)
- - SLE15 [s390x](https://openqa.suse.de/t4431928) | [x86_64](https://openqa.suse.de/t4431921)
- - SLE12 SP5 [s390x](https://openqa.suse.de/t4431929) | [x86_64](https://openqa.suse.de/t4431922)
- - SLE12 SP4 [s390x](https://openqa.suse.de/t4431930) | [x86_64](https://openqa.suse.de/t4431923)
- - SLE12 SP3 [x86_64](https://openqa.suse.de/t4431924)
- - SLE12 SP2 …
> Add softfail for bsc#1173856 on HyperV runs

- lib/susedistribution.pm
Ticket: https://progress.opensuse.org/issues/64439
> Ignore pkcon pkg already installed error

- tests/cpu_bugs/ipmi_to_qemu.pm
Zypper repo path follows SLES version, fix current hard code by fetching
values from get_sles_release() with error detection.
Add perl-Test-Assert package during package installation.
Positive verification: http://10.67.19.72/tests/330
Negative verification: http://10.67.19.72/tests/331
> Fix ipmi_to_qemu adding repo and package issue

- data/autoyast_qam/12_installtest.xml.ep
- Verification run: https://openqa.suse.de/tests/4446738
> Use regcode variable instead of hardcoded version to determine LTSS

- .gitignore
- script/yaml_generator/README.md
The PR updates the documentation for YAML Generator with the detailed steps to setup and styles change.
> Update doc for yaml generator

- tests/containers/container_diff.pm
- tests/containers/containers_3rd_party.pm
- tests/containers/docker.pm
- tests/containers/docker_compose.pm
- tests/containers/docker_image.pm
- tests/containers/docker_runc.pm
- tests/containers/podman.pm
- tests/containers/podman_image.pm
- tests/containers/zypper_docker.pm
Typo fix on the container metadata.
> Adjust package metadata

- schedule/migration/rmt_export.yaml
Add one schedule yaml file for rmt export
> Add one schedule yaml file for rmt export

- lib/Mitigation.pm
Previous implementation calls cpuid packages, which provided by HPC Module, but this module is unable to be sellected during online installation. Re-implement read_cpuid with perl and shell to get out of cpuid package and HPC Module.
Verification URL: 
http://10.67.19.72/tests/overview?distri=sle&version=15-SP2&build=209.2&groupid=3
http://10.67.19.72/tests/overview?distri=sle&version=15-SP2&build=209.2&groupid=2
> Re-implement Mitigation library read_cpuid()

- schedule/migration/rmt_import.yaml
Add rmt import yaml schedule file
> Add rmt import yaml schedule file

- data/generalhw_scripts/power_on_off_tuya.sh
- Related ticket: https://progress.opensuse.org/issues/69052
Tested successfully manually.
> Implement a retry mechanism in power_on_off_tuya.sh - poo#69052

- tests/cpu_bugs/xen_mitigations.pm
Enhance xen vul test to adapt to multiple Micro-architecture test
1.Divide big hash to multiple small one.
2.Add pv_l1tf related test cases
3.Use correct test cases according to machine micro-arch
4.Reduce some output to avoid worker consume more memory. 
- Needles: N/A
- Verification run: http://10.67.134.217/tests/10369
> Solve existing issues for xen hypervisor mitigation test

- lib/kdump_utils.pm
It's possible to get that information by querying the package and processing
that a bit.
Fixes poo#69073
Leap 15.1: http://10.160.67.86/tests/706
Leap 15.2: http://10.160.67.86/tests/707
Tumbleweed aarch64: https://openqa.opensuse.org/tests/1335213
Might need verification runs on some other archs and SLE as well.
> Make install_kernel_debuginfo more generic

- tests/console/pam.pm
Ticket: https://progress.opensuse.org/issues/49112
Verification: https://openqa.suse.de/t4462199
> Fix pam test for non-tw systems

- tests/wicked/before_test.pm
Adding support for wicked tests running on SLE 12 SP1 needed by wicked CI 
VR: http://autobot.qa.suse.de/tests/930
> wicked: specify repo by URL for SLE lower than 12 SP2

- tests/yast2_gui/yast2_instserver.pm
- Fail: https://openqa.suse.de/tests/4468746
- Verification run: https://openqa.suse.de/tests/4470319
> yast2_instserver: Remove not needed key press on 15-SP2

- tests/fips/mozilla_nss/firefox_nss.pm
- https://openqa.suse.de/tests/4466114#step/firefox_nss/14
https://openqa.suse.de/tests/4466517
https://openqa.suse.de/tests/4466525
> firefox: Be more specific in search for master password field

- data/shar_testdata.sh
- lib/main_common.pm
- schedule/functional/extra_tests_textmode.yaml
- tests/console/shar.pm
Ticket: https://progress.opensuse.org/issues/49112
Verification: http://kazhua.qa.suse.de/tests/60
> Add shar test

- tests/x11/firefox/firefox_extensions.pm
- Related ticket: https://progress.opensuse.org/issues/68929
- Verification run: https://openqa.suse.de/tests/4475139
> Use click instead of alt-a which does select all text on page

- data/mitigation/xen/get_guest_ip.sh
Add expect script to openqa data folder
This script is used to get guest ip address
- Needles: N/A
- Verification run: http://10.67.134.217/tests/11157
> Add expect script get_guest_ip to openqa data

- tests/console/shar.pm
Ticket: https://progress.opensuse.org/issues/69262
Verification: https://openqa.opensuse.org/t1339852
> Fix shar test for jeos

- lib/Mitigation.pm
Fix xen re-login issue after reboot operatiion due to no code cover that.
- Needles: N/A
- Verification run: http://10.67.134.217/tests/11249
> Solve xen login via ipmi after reboot

- data/autoyast_sle15/autoyast_rt.xml
- schedule/rt/sle15/rt-product-autoyast.yaml
- schedule/rt/sle15/rt-utilities.yaml
- tests/rt/kmp_modules.pm
- tests/rt/rt_is_realtime.pm
- tests/rt/rt_preempt_test.pm
- tests/rt/rt_tests.pm
* [sle-15-SP2-Server-DVD-RT-x86_64-Build0001-rt-validation_extra_tests@64bit ](http://kepler.suse.cz/tests/1013)
* [sle-15-SP2-Server-DVD-RT-x86_64-Build0001-rt-product_autoyast@64bit ](http://kepler.suse.cz/tests/1011)
* [sle-15-SP2-Server-DVD-RT-x86_64-Build0001-rt-utilities@64bit](http://kepler.suse.cz/tests/1015)
> Refresh RT test suites for slert15sp2

- data/autoyast_sle15/autoyast_rt.xml
- tests/rt/kmp_modules.pm
> RT minor updates

- lib/main_common.pm
http://10.100.12.155/tests/16302
http://10.100.12.155/tests/16301
> Add disable_screensaver into piglit test to avoid black screen

- tests/wicked/before_test.pm
fix list to scalar assignment
VR: http://dante.arch.suse.de/tests/4139
> wicked: fix list to scalar assignment

- tests/cpu_bugs/xen_mitigations.pm
Add parameter TEST_SUITES to webui which supports user specific parts of test cases to run
- Needles: N/A
- Verification run: http://10.67.134.217/tests/11312#
> Add param TEST_SUITES to support parts cases test

- data/autoyast_kvm/sles11sp4x32_PRG.xml
- data/autoyast_kvm/sles11sp4x64_PRG.xml
- data/autoyast_kvm/sles12sp3_PRG.xml
- data/autoyast_kvm/sles12sp4_PRG.xml
- data/autoyast_kvm/sles12sp5_PRG.xml
- data/autoyast_kvm/sles15_PRG.xml
- data/autoyast_kvm/sles15sp1_PRG.xml
- data/autoyast_kvm/sles15sp2_PRG.xml
- data/autoyast_xen/sles11sp4HVMx32_PRG.xml
- data/autoyast_xen/sles11sp4HVMx64_PRG.xml
- data/autoyast_xen/sles11sp4PVx32_PRG.xml
- data/autoyast_xen/sles11sp4PVx64_PRG.xml
- data/autoyast_xen/sles12sp3HVM_PRG.xml
- data/autoyast_xen/sles12sp3PV_PRG.xml
- data/autoyast_xen/sles12sp4HVM_PRG.xml
- data/autoyast_xen/sles12sp4PV_PRG.xml
- data/autoyast_xen/sles12sp5HVM_PRG.xml
- data/autoyast_xen/sles12sp5PV_PRG.xml
- data/autoyast_xen/sles15HVM_PRG.xml
- data/autoyast_xen/sles15PV_PRG.xml
- data/autoyast_xen/sles15sp1PV_PRG.xml
- data/autoyast_xen/sles15sp2HVM_PRG.xml
- data/autoyast_xen/sles15sp2PV_PRG.xml
- lib/xen.pm
We already test SLE15-SP2 XEN and KVM hypervisor but we still miss guests.
Here are autoyast profiles and I am also creating corresponding needles.
- Related ticket: [poo#69676](https://progress.opensuse.org/issues/69676)
- Needles: [os-autoinst-needles-sles#1414](https://gitlab.suse.de/openqa/os-autoinst-needles-sles/-/merge_requests/1414)
- Verification run: [KVM](http://pdostal-server.suse.cz/tests/9642#step/virtmanager_final/27) [XEN](http://pdostal-server.suse.cz/tests/9684#step/virtmanager_final/82)
> Add SLE15-SP2 virt. guests

- lib/susedistribution.pm
First step to replace 'pkcon install' by 'zypper_call in'
see: https://progress.opensuse.org/issues/39908
verifications:
http://10.162.23.47/tests/7920
> Adapt all current scenarios which use pkcon by zypper_call

- schedule/rt/sle12/rt.yaml
- schedule/rt/sle15/rt-validation_extra_tests.yaml
* [slert12sp5](http://kepler.suse.cz/tests/1078)|
* [slert15p2](http://kepler.suse.cz/tests/1077)
> Execute update test cases earlier in SLERT

- tests/cpu_bugs/xen_domu_mitigation_test.pm
- tests/cpu_bugs/xen_mitigations.pm
Fixing packages expect, xlmstartlet missing issues
- Needles: N/A
- Verification run:  http://10.67.134.217/tests/11199, http://10.67.134.217/tests/11312
> Fixing package missing issue
